### ISSUE TITLE
aws_lambda_event_source_mapping diffs don't match on almost any update

### ISSUE THREAD

**Issue by t-pascal** [hashicorp/terraform#4905]
Using the aws_lambda_event_source_mapping code example below seems to create an error "diffs didn't match during apply. This is a bug with Terraform and should be reported." on almost any change when the source mapping has already been created.

For example, in the tf fragment below, changing "batch_size" or "enabled" or "starting_position" on an object will almost always cause the error on (re)apply. Rerunning after the error does not produce an error and the event source mapping seems to be updated correctly. This would be cosmetic, except I have had lambda functions stop working after the above error occurs. The problem is intermittent so I can't determine which field might be causing the issue.

Steps:
1. Terraform apply to create function and handler
2. Change a field in the event_source_mapping
3. Terraform apply changes to generate error (source mapping does appear to be updated)
4. Terraform apply again runs cleanly

```
resource "aws_lambda_function" "myfunction" {
    s3_bucket = "arn:aws:s3:::mybucket"
    s3_key = "myfile.zip"
    s3_object_version = "someversion"
    function_name = "myfunction"
    role = "arn:aws:iam::12345678:role/myrole"
    handler = "index.handler"
    memory_size = 128
    runtime = "nodejs"
    timeout = 10
}

resource "aws_lambda_event_source_mapping" "mylambda" {
    batch_size = 3000
    event_source_arn = "arn:aws:kinesis:us-east-1:12345678:stream/mystrean"
    enabled = true
    function_name = "${aws_lambda_function.myfunction.arn}"
    starting_position = "TRIM_HORIZON"
}
```

**Comment by brendangibat** [comment]
I've been seeing the same error, the only thing I'm changing is the `s3_key` in the aws_lambda_function.

**Comment by brendangibat** [comment]
One thing I've noticed for this problem is that if the dependencies for aws_lambda_event_source_mapping are destroyed / recreated, which terraform tends to do for updates to the code for lambdas, it will hit the problems described - diffs don't match, the plan has a complete description and the apply is empty.

@t-pascal What I've done to get around the problem that it looks like terraform isn't recreating the event source mapping when it should (because terraform decided to destroy one of the dependent resources), is to explicitly destroy the mapping before executing an update. Overall that isn't too big of a problem for us, since it would just give us a few seconds of time between mappings being recreated, and kinesis is queueing (which is our source).

**Comment by t-pascal** [comment]
Yeah, good catch. I have been using a workaround where I manually delete the lambda function and/or the mappings before running apply. It makes the process much more reliable.

**Comment by stack72** [comment]
Hi @t-pascal

Can you tell me if this is still an issue for you? Terraform has a nightly test that changes this:

```
resource "aws_kinesis_stream" "kinesis_stream_test" {
    name = "kinesis_stream_test"
    shard_count = 1
}

resource "aws_lambda_function" "lambda_function_test_create" {
    filename = "test-fixtures/lambdatest.zip"
    function_name = "example_lambda_name_create"
    role = "${aws_iam_role.iam_for_lambda.arn}"
    handler = "exports.example"
}

resource "aws_lambda_event_source_mapping" "lambda_event_source_mapping_test" {
		batch_size = 100
		event_source_arn = "${aws_kinesis_stream.kinesis_stream_test.arn}"
		enabled = true
		depends_on = ["aws_iam_policy_attachment.policy_attachment_for_role"]
		function_name = "${aws_lambda_function.lambda_function_test_create.arn}"
		starting_position = "TRIM_HORIZON"
}
```

to this:

```
resource "aws_kinesis_stream" "kinesis_stream_test" {
    name = "kinesis_stream_test"
    shard_count = 1
}

resource "aws_lambda_function" "lambda_function_test_update" {
    filename = "test-fixtures/lambdatest.zip"
    function_name = "example_lambda_name_update"
    role = "${aws_iam_role.iam_for_lambda.arn}"
    handler = "exports.example"
}

resource "aws_lambda_event_source_mapping" "lambda_event_source_mapping_test" {
		batch_size = 200
		event_source_arn = "${aws_kinesis_stream.kinesis_stream_test.arn}"
		enabled = false
		depends_on = ["aws_iam_policy_attachment.policy_attachment_for_role"]
		function_name = "${aws_lambda_function.lambda_function_test_update.arn}"
		starting_position = "TRIM_HORIZON"
}
```

Notice the change to `function_name`, `batch_size` and `enabled`. This test has been passing for a while now

Paul

**Comment by stack72** [comment]
Hi @t-pascal 

I am going to go ahead and close this out - if you still think this is an issue then please do let me know and I can reinvestigate it

Thanks again

Paul
