### ISSUE TITLE
Feature Request: Create AWS Event Rules

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/terraform#4908]
Would be neat to add this:

https://aws.amazon.com/blogs/aws/new-cloudwatch-events-track-and-respond-to-changes-to-your-aws-resources/

To avoid having it do it per each region manually.. would be best to have this from terraform.

**Comment by radeksimko** [comment]
Hi @JoeOrtiz 
I started working on both event rules & targets today.
I will hopefully submit the PR for both during the next week.

Also I'm closing this as a duplicate of https://github.com/hashicorp/terraform/issues/4827
