### ISSUE TITLE
allow provisioner connections in local_exec provisioner

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform#4911]
...is there any technical reason why this isn't allowed? I'm using ansible for provisioning and it would be nice to use `connection` to stall kicking off the `local_exec` until SSH is up on the target instance (similar to how `remote_exec` works in conjunction with `connection`).

Alternatively, could a `ssh` 'provisioner connection' be made that is used purely to poll for ssh access before executing any provisioner?

**Comment by vmindru** [comment]
+1 for now i am using remote-exec ls ....  for that purpose

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. While provisioners, as a whole, aren’t a top priority for the team, when some time is available to focus on them we’re going to use that attention to tackle some long-standing defects.

We are also thinking about how to evolve provisioning for many of our community’s use cases but have yet to take a firm decision on the direction that work will take.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
