### ISSUE TITLE
ignore_changes Prevents New Box From Launching

### ISSUE THREAD

**Issue by jamescarr** [hashicorp/terraform#4912]
I have the following `aws_instance` definition:

```
resource "aws_instance" "graylog_server" {
    ami = "${var.graylog_server_next_image}"
    instance_type = "m3.medium"
    key_name = "failsafe"
    iam_instance_profile = "${aws_iam_instance_profile.graylog_profile.name}"
    vpc_security_group_ids = ["${aws_security_group.logging.id}"]
    subnet_id = "${aws_subnet.private-us-east-1b.id}"
    tags {
      "role" = "graylog_server"
    }
    lifecycle {
        ignore_changes = ["tags"]
    }


```

If I try to apply this I get

```
* aws_instance.graylog_server: diffs didn't match during apply. This is a bug with Terraform and should be reported.

```

Removing the `ignore_changes` attribute allows me to launch, after which point I can add it back. It works unless the instance is being replaced it seems.

**Comment by jamescarr** [comment]
Yeah after doing several replacements this evening I've come to realize that `ignore_changes` is useless with this defect since I need to remove it every time an instance is replaced and then add it back afterward so tags aren't messed with on future runs.

**Comment by phinze** [comment]
Hi @jamescarr - I believe this particular `ignore_changes` issue should be solved. I'm working on addressing additional problems w/ the field over in #5627
