### ISSUE TITLE
Feature Request: create-spot-datafeed-subscription

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/terraform#4922]
Curious if anyone is willing to tackle to add:

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSpotDatafeedSubscription.html

It would just make it convenient.

**Comment by stack72** [comment]
Hi @JoeOrtiz 

Apologies this has taken so long to implement! A PR has been opened to add this functionality to Terraform

Paul
