### ISSUE TITLE
Cannot use docker provider since v0.6.7

### ISSUE THREAD

**Issue by lvjp** [hashicorp/terraform#4923]
Docker provider cannot connect to my docker since v0.6.7
It was working fine until v0.6.6

I up some log in a [gist](https://gist.github.com/lvjp/27852eb5a2a75b9f695e).

I also remark that i can find `connect(7, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0` in v0.6.7 but not in v0.6.10.

If you need more log file, just ask me.

**Comment by superseb** [comment]
The Docker package used by the provider (https://github.com/fsouza/go-dockerclient) has the following example:

```
    endpoint := "unix:///var/run/docker.sock"
```

Can you try if this works for you?

**Comment by lvjp** [comment]
Thanks @superseb,  

This solve my problem. I check it from v0.6.6 to v0.6.10 of terraform.

Maybe it will be a good idea to change host [default value](https://github.com/hashicorp/terraform/blob/master/builtin/providers/docker/provider.go#L16) since the [official Docker daemon documentation](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-socket-option) said that default socket point to the same file.

**Comment by superseb** [comment]
Yep, that would be useful. Are you going to submit a PR for this?
