### ISSUE TITLE
Cannot use disk type local-ssd with google_compute_instance_template

### ISSUE THREAD

**Issue by etiennetremel** [hashicorp/terraform#4924]
Is there a way we can use a disk with type local-ssd in the google_compute_instance_template?

It is possible from the google_compute_instance, but not its template.

Or maybe the documentation is not up-to-date? Looking at the schema, I can see there is something about disk type: 
https://github.com/hashicorp/terraform/blob/990f957c29ccc01caafb95da6c4aed7df8536823/builtin/providers/google/resource_compute_instance_template.go#L87

The Google API doc also provide informations about local-ssd: https://cloud.google.com/compute/docs/reference/latest/instanceTemplates

Any clue how I can use this?

**Comment by lwander** [comment]
Looks like the documentation is just missing that field. I'll push a PR.

**Comment by lwander** [comment]
See #5126

**Comment by stack72** [comment]
This has been closed with #5126
