### ISSUE TITLE
Default value of AWS Redshift Cluster skip_final_snapshot

### ISSUE THREAD

**Issue by dtan4** [hashicorp/terraform#4925]
[Document of AWS Redshift Cluster resource](https://www.terraform.io/docs/providers/aws/r/redshift_cluster.html) indicates that the default value of `skip_final_snapshot` is `false`.
However, the code [`resource_aws_redshift_cluster.go`](https://github.com/hashicorp/terraform/blob/7c9d309d6f2a010aa28aab6b7a7c4af30d51b173/builtin/providers/aws/resource_aws_redshift_cluster.go#L170) indicates that the default value is `true`...

Which one is correct?

**Comment by stack72** [comment]
Hi @dtan4 - the default should be true. I will update this now

Apologies for this

**Comment by dtan4** [comment]
Thanks for quick update :exclamation:
