### ISSUE TITLE
RDS Enhanced Monitoring support

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#4940]
AWS recently made available enhanced monitoring for RDS instances, similar to what you can have with EC2 instances.

Would be awesome to have support for it in TF.

**Comment by stack72** [comment]
@failshell got a link to anything about it?

**Comment by failshell** [comment]
annoncement: https://aws.amazon.com/blogs/aws/new-enhanced-monitoring-for-amazon-rds-mysql-5-6-mariadb-and-aurora/

I haven't looked in the detail for the API, but I believe you add monitoring => true to the hash you pass to the RDS API when you modify an instance.

**Comment by stack72** [comment]
@failshell just opened a PR for this - will test this and see if we can get it merged

**Comment by failshell** [comment]
wow that was quick :)

**Comment by stack72** [comment]
@failshell it's not quite ready yet - i need to run the tests and make sure I document what IAM Role is require

**Comment by stack72** [comment]
Hi @failshell - this has been merged and will be available in Terraform 0.6.12 in the next day or 2

**Comment by failshell** [comment]
awesome. thanks!
