### ISSUE TITLE
Duplicate module entries added to statefile cause confusing failures

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#4942]
If for any reason the statefile JSON ends up with duplicate entries for a given module path, very confusing behavior can result - with the duplicates being preserved for some time, then resulting in unresolvable state conflicts when working w/ remote state.

Terraform should recognize duplicate module entries in a state file being loaded and immediate raise a validation error.

**Comment by mitchellh** [comment]
Got a PR up or this.
