### ISSUE TITLE
AWS elastic cache specifying snapshot_retention_limit doesnt allow to create t2.micro instance

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#4947]
I have a Elastic cache template that have snapshot_retention_limit  in it.
But as appears it cant be specified for t2.micro instances.
```
* aws_elasticache_cluster.redis: Error creating Elasticache: InvalidParameterCombination: Instance type does not support snapshotting. Snapshot retention limit parameter should not be specified.
	status code: 400, request id: a0e8c652-c934-11e5-92e5-9f4a1b5228e7
```
I tried to set 0, still no luck. So basically its means that i can provision micro instance with the same template as other size instances since terraform always passing snapshot_retention_limit

**Comment by optimisticanshul** [comment]
```
	if v, ok := d.GetOk("snapshot_retention_limit"); ok {
		if  !strings.Contains(aws.String(nodeType), "t2.")
		  req.SnapshotRetentionLimit = aws.Int64(int64(v.(int)))
	}

**Comment by stack72** [comment]
Hi @aldarund 

Unfortunately this is not supported by [AWS](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Snapshots.html#Snapshots.Constraints). This isn't something that Terraform can support 

I will add a mention of this to the documentation to avoid confusion

Paul

**Comment by aldarund** [comment]
@stack72 yes  i understand that aws not supporting it. The point is that i cant use same terraform template for different instance types, even if i change the value. Maybe allow something like -1  value to allow terraform not pass this param to aws , so same tempalte can be used both for micro and other instances?

**Comment by SweedInsight** [comment]
Any solution provided until now?

trying to implement a logic for t2 but i have to assign a retention limit value 

  # only use snapshots when automatic_failover is enabled
  snapshot_window          = "${element(split(".", var.elasticache_instance_type), 1 ) != "t2" ? var.snapshot_window : ""}"
  snapshot_retention_limit = "${element(split(".", var.elasticache_instance_type), 1 ) != "t2" ? var.snapshot_retention_limit : 0}"
