### ISSUE TITLE
Amazon Simple Systems Manager (SSM) 

### ISSUE THREAD

**Issue by aminek01** [hashicorp/terraform#4952]
Hello,
Is there a way to create SSM document and join instance to directory service domain:

http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-join-aws-domain.html

**Comment by skippy** [comment]
updated doc location: https://docs.aws.amazon.com/ssm/latest/APIReference/Welcome.html

**Comment by liamjbennett** [comment]
I stumbled into this issue for the same use-case mentioned above. I should have a PR to support this shortly.

**Comment by aminek01** [comment]
Thank you so much.

**Comment by liamjbennett** [comment]
There is one more resource `ssm_activation` still to be added before this issue can be closed.

**Comment by liamjbennett** [comment]
http://docs.aws.amazon.com/ssm/latest/APIReference/API_CreateActivation.html

**Comment by stack72** [comment]
All 3 resources now added - thanks @liamjbennett :)
