### ISSUE TITLE
Poor error reporting when ASG creation fails due to service limits

### ISSUE THREAD

**Issue by serenitus** [hashicorp/terraform#4964]
If the creation of an AWS ASG would cause a quantity of EC2 instances to be created that takes you outside your current EC2 service limit then the ASG creation simply times out with no useful information:

```
Error applying plan:

1 error(s) occurred:

* aws_autoscaling_group.magento: timeout while waiting for state to become '[success]'
```

Hopefully the AWS APIs return sufficient error information for Terraform to provide better feedback.

**Comment by radeksimko** [comment]
Hi @serenitus 
I believe we improved the error message in https://github.com/hashicorp/terraform/pull/14480 which was just merged and will be part of the next release (0.9.6).
