### ISSUE TITLE
Feature: Support AWS API Gateway

### ISSUE THREAD

**Issue by brycefisher** [hashicorp/terraform#4968]
AWS Lambda doesn't have any native routing. Instead it relies completely on [AWS API Gateway](https://aws.amazon.com/api-gateway/) for internet facing requests.

The use case is that if I want to deploy an API powered by Lambda, it would be great to use terraform to deploy both the API gateway and the lambda function.

**Comment by apparentlymart** [comment]
Agreed that this would be pretty awesome! It looks like API Gateway support already in progress in #4295.

**Comment by brycefisher** [comment]
Wohoo!! Great news, thanks so much.
