### ISSUE TITLE
Support VM Scale Sets in AzureRM

### ISSUE THREAD

**Issue by 2k0ri** [hashicorp/terraform#4974]
Azure RM provides [VM Scale Sets(VMSS)](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-vmss-walkthrough-cli/).
It is still beta, but this feature enables auto-scaling like AWS.

**Comment by stack72** [comment]
Hi, @2k0ri, we are currently in a process of bringing the AzureRM provider up to parity with AzureSM - you can track it's progress in this ticket #4836 

When w have parity, then we will start to look at the later features. Of course, please feel free to open a PR if you need this faster and we will happily look at it for you :)

Paul

**Comment by majormoses** [comment]
@stack72 looking at the ticket we have feature parity, do you know where this is on the roadmap?

**Comment by stack72** [comment]
Hi @majormoses 

It currently isn't in my plan to take care of. I have some things to finish with Virtual Machines

As far as the roadmap is concerned, that's worth asking @phinze, @catsby and @jen20 about

Paul

**Comment by majormoses** [comment]
@phinze @catsby @jen20 any idea when this is going on the roadmap? If this is not on the somewhat short term roadmap would the best bet be to resort to using the template resource?  https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html

**Comment by stack72** [comment]
@majormoses not sure if this is too late for you or not but #6711

**Comment by majormoses** [comment]
@stack72 yup I have been following it...it is one of the few missing providers that I am calling a blocker on starting my azure migration journey...

**Comment by stack72** [comment]
Merged to master in #6711 

I will be keeping a close eye on the issues / use-cases people post here
