### ISSUE TITLE
Output silently ignored if it references a non-existing attribute

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#4975]
Configuring an `output` to reference a non-existing attribute of a resource, silently fails when running `terraform apply`. The `apply` completes successfully with no message, but no `output` is created in the state file.

This was what I had accidentally put in my `.tf` file:
```
output "dns" {
  value = "${aws_elb.elb.public_dns}"
}
```

The proper attributes is `dns_name`. I think for usability, a message should be printed here about this property not existing (if possible).

**Comment by t-pascal** [comment]
We also confirmed this. The following should report an error rather than silently produce no output:

`` output "default_key_name" {
  value = "${aws_key_pair.ops.name}"
}``

May be related somewhat to other silent output failures in #5334 and #2598 in our research

**Comment by mitchellh** [comment]
Centralizing on #5334
