### ISSUE TITLE
aws_iam_role_policy don't support multiple resources

### ISSUE THREAD

**Issue by fitati** [hashicorp/terraform#4977]
Hi, 

I'm trying to create an iam_role_policy for multiple S3 buckets, but resource variable must be a string, aws supports this configuration, how can we deal with it.

regards

**Comment by stack72** [comment]
Hi @fitati,

Can you provide a sample of the terraform config that you are using and what you think it would support?

Thanks

Paul

**Comment by fitati** [comment]
Hi @stack72 

when I try to configure an aws_iam_role_policy with to access to S3 bucket, for multiple buckets resources, I use this configuration:

resource "aws_iam_role_policy" "resource_policy" {
    name = "${var.name}"
    role = "${var.iam_role}"
    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "${split(",", var.action)}"
      ],
      "Effect": "${var.effect}",
      "Resource": ["${split(",", var.resource)}"]
    }
  ]
}
EOF
}

I put an array for Resources to be able to add multiple buckets to the Iam_role_policy, terraform returns: variable resource must be a string value (this is a terraform exception not AWS Error).

but on aws console we can configure multiple buckets for the same iam_role_policy.

Thanks.

Aymen

**Comment by stack72** [comment]
Hi @fitati, the code in Terraform for `aws_iam_role_policy` doesn't do *any* validation on the policy document itself:

```
func resourceAwsIamRolePolicyPut(d *schema.ResourceData, meta interface{}) error {
	iamconn := meta.(*AWSClient).iamconn

	request := &iam.PutRolePolicyInput{
		RoleName:       aws.String(d.Get("role").(string)),
		PolicyName:     aws.String(d.Get("name").(string)),
		PolicyDocument: aws.String(d.Get("policy").(string)),
	}

	if _, err := iamconn.PutRolePolicy(request); err != nil {
		return fmt.Errorf("Error putting IAM role policy %s: %s", *request.PolicyName, err)
	}

	d.SetId(fmt.Sprintf("%s:%s", *request.RoleName, *request.PolicyName))
	return nil
}
```

All the code does, is that the user input for policy and sends that to AWS. Therefore, I don't think this is an error with Terraform

**Comment by muikrad** [comment]
@fitati I don't think you can make it work the way you are doing it. When you use split(), you are creating a list for Terraform to use internally, but there is no way (that I found) to correctly output a json-compatible array from a terraform string array.

**Comment by catsby** [comment]
Hey all – I'm going to close this for now. I agree with @stack72 here, I don't believe this is a Terraform bug. Thanks!
