### ISSUE TITLE
Network ACL rules recreated very time

### ISSUE THREAD

**Issue by cgreenefindly** [hashicorp/terraform#4981]
I have created 4 aws_network_acl_rule. Every time I do a plan / apply, the acl rules are recreated. Is that suppose to happen?

**Comment by stack72** [comment]
@cgreenefindly please can you show the terraform config (minus secrets) and the resultant plan 

Thanks

Paul

**Comment by catsby** [comment]
Hey all, I'm going to go ahead and close this since we haven't heard back. Please let us know if you do have a config file (minus any secret info) that demonstrates this, and I'll be happy to re-open and take a look
