### ISSUE TITLE
Seemingly random parse failures

### ISSUE THREAD

**Issue by lukesteensen** [hashicorp/terraform#4982]
This can be reproduced on v0.6.11 with https://gist.github.com/lukesteensen/00d59e66f3ac20b4b6e8

It's pretty trivial to run the example multiple times and see failures while refreshing state, creating the plan, and applying the plan.

We've run into cases in our actual infrastructure where instances were destroyed and not recreated due to this error happening mid-apply.

**Comment by phinze** [comment]
Thanks for the report @lukesteensen. Sounds like a race condition in the parser. Sorry for the trouble it caused you during `apply` - we'll get this looked at ASAP!

**Comment by lukesteensen** [comment]
Thanks @phinze! Much appreciated

**Comment by phinze** [comment]
Just a quick update here - I've got local reproduction thanks to your example. Still working on root cause diagnosis. Will follow up as soon as I know more.
