### ISSUE TITLE
Failing to get `token` to work with the AWS provider

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#4984]
Until recently, I was using v0.6.8. With that release, setting the `AWS_SESSION_TOKEN` environment variable, Terraform would pick that up and use it in an `aws` provider.

With v0.6.11, we can provide the `AWS_SECURITY_TOKEN`, but Terraform does not see it. When I put in the `token` parameter for the provider, it works fine. When I test with `aws` cli tools, I can confirm the MFA credentials in the shell environment are correct and functional. I have not looked at the code, but it appears as if TF is ignoring the `AWS_SECURITY_TOKEN` env var, and otherwise requiring the `token` be set explicitly with a TF variable. Interestingly, and slightly counter-intuitive from what I would expect, I only needed to add `token` to the `aws` provider in the top level of the project, none of my modules were updated with a `token` variable or to pass in `token` to their local provider (in the module).

**Comment by ketzacoatl** [comment]
I am not skilled much in go, but I am looking at this and wondering, is the token schema - https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/provider.go#L46 - simply missing something to work with the env like https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/provider.go#L56?

Seems like https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L148 is the thing to use  to look up that env var.. but then there is https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L349.

**Comment by ketzacoatl** [comment]
@phinze, @radeksimko, @jen20, etc, digging into the commit history and comparing code to docs, I am having a difficult time confirming the nuances of what is expected behavior, and where the breakage is. In particular, https://github.com/hashicorp/terraform/commit/ace215481aa46c2a419a42c05b7529f787c53c19 seems to introduce a major change (or at least something capable of breaking token handling), but which also appears to be orthogonal to handling tokens.

Guidance here would be greatly appreciated!

**Comment by phinze** [comment]
Hi @ketzacoatl - sorry for the trouble here! I'm wondering if this is a doc typo - I see mention of `AWS_SESSION_TOKEN` in the code - does that work like you were expecting `AWS_SECURITY_TOKEN` to?

**Comment by ketzacoatl** [comment]
I believe I have had issues with both. I can retest both to be sure.

**Comment by ketzacoatl** [comment]
I landed back on this issue while searching for details to compare what Terraform does against what AWS documents in http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html.

Question: why does Terraform use `$AWS_SECURITY_TOKEN` when AWS defaults to `$AWS_SESSION_TOKEN`? Could Terraform be convinced to accept the AWS default if it is provided? It's not a big deal, but feels better than ensuring all credential management tools/scripts add in the `$AWS_SECURITY_TOKEN` for use with Terraform.

That aside, I would elect to close this issue given that we're nearly on to v0.7.x

**Comment by ketzacoatl** [comment]
@phinze, I posted some additional questions on https://groups.google.com/forum/#!topic/terraform-tool/GwLxpA5Xo4A, as I'm unable to get providers/MFA and modules to work correctly together, and I'm not sure what the correct setup is supposed to be.

**Comment by ketzacoatl** [comment]
bump, with the deepest appreciation for your time to review ^

**Comment by ketzacoatl** [comment]
I'm unable to get token to work correctly when sourced from an envvar, but I believe it's related to using `token` with modules. Please see my mailing list post linked to above.

**Comment by ketzacoatl** [comment]
I think this can be closed.  0.7.x has worked well in practice, in various configurations I've tested in real-world use.
