### ISSUE TITLE
Bug using version_real attribute on atlas_artifact

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#4989]
When you use the [`version_real`](https://www.terraform.io/docs/providers/atlas/r/artifact.html#version_real) attribute in the [`atlas_artifact`](https://www.terraform.io/docs/providers/atlas/r/artifact.html) resource, you get an error in the `terraform plan`.

In my case, I could successfully grab the version number by splitting the `id` attribute and grabbing the number for the `function_name` argument of my `aws_lambda_function` resource.

```
resource "aws_lambda_function" "test_lambda" {
  function_name = "hello_world_${element(split(" ", atlas_artifact.hello_lambda.id), length(split(" ", atlas_artifact.hello_lambda.id))-1)}"
  filename      = "${template_file.artifact_local_path_zip.rendered}"
  handler       = "${atlas_artifact.hello_lambda.metadata_full.fn_handler}"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  description   = "Lambda function is using Atlas slug: ${atlas_artifact.hello_lambda.slug}"

  lifecycle { create_before_destroy = true }
}
```

But when I update to just use the `version_real` attribute to get the artifact number, the plan fails.

```
resource "aws_lambda_function" "test_lambda" {
  function_name = "hello_world_${atlas_artifact.hello_lambda.version_real}"
  filename      = "${template_file.artifact_local_path_zip.rendered}"
  handler       = "${atlas_artifact.hello_lambda.metadata_full.fn_handler}"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  description   = "Lambda function is using Atlas slug: ${atlas_artifact.hello_lambda.slug}"

  lifecycle { create_before_destroy = true }
}
```

```
Terraform v0.6.11

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
Error running plan: 1 error(s) occurred:

* Resource 'atlas_artifact.hello_lambda' does not have attribute 'version_real' for variable 'atlas_artifact.hello_lambda.version_real'
```

Wondering if this could be due to the fact that [atlas-go](https://github.com/hashicorp/atlas-go) returns the [Version as an `int`](https://github.com/hashicorp/atlas-go/blob/master/v1/artifact.go#L28), but Terraform [expects a string](https://github.com/hashicorp/terraform/blob/master/builtin/providers/atlas/resource_artifact.go#L148). Not entirely sure if `d.Set("version_real", v.Version)` would fail due to version being an `int` though, just a guess.

It's worth noting that both the [`id`](https://github.com/hashicorp/terraform/blob/master/builtin/providers/atlas/resource_artifact.go#L146) and [`slug`](https://github.com/hashicorp/terraform/blob/master/builtin/providers/atlas/resource_artifact.go#L150) contain the Version and render correctly on both plan and apply.

**Comment by dennis-bsi** [comment]
I have outputs referencing the atlas_artifact.version_real and get nothing in return. I've resorting to using `"${element(split("/", atlas_artifact.main.slug), length(split("/", atlas_artifact.main.slug))-1)}"` to get the artifact version deployed.

**Comment by teamterraform** [comment]
The `atlas_artifact` mechanism is no longer present in Terraform, so we're going to close this out now.
