### ISSUE TITLE
Can't declare providers in more than one module level

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#500]
I declared  aws provider in a module and in a module that is using that module and i get
Cycle: module.globals -> provider.aws.

Modules are not supposed to be affected by other modules (according to the documentation), and it seems legit to me that different modules will want to create AWS resources and depend on their own provider (and surely in consul)

**Comment by phinze** [comment]
I think this issue has been handled in the latest version of Terraform. Feel free to reopen if it's still an issue though!
