### ISSUE TITLE
[AWS] Associate aws_eip post creation

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#5002]
There are a few cases I have come across where it is necessary to create and elastic IP but associate it later, one was raised in https://github.com/hashicorp/terraform/issues/1273 but my use case is slightly more specific.

I am trying to create an openvpn server which has a public ip, the only way I've found to do that is to provide the IP in the user data as the public_hostname. This is needed because I won't be allocating FQDN etc, just going to use the IP, but when you log into the webpage and download the client config, it pulls the public_hostname into the config, and if you don't give a public ip then it defaults the private ip, which is awkward for a VPN connection from outside the VPN.

```hcl
	user_data = <<USERDATA
		public_hostname=${aws_eip.openvpn_eip.public_ip}
USERDATA
```

So the solution I have come up with is to create the `aws_eip` but not provide an `instance_id`:

```hcl
resource "aws_eip" "openvpn_eip" {
    vpc = true
}
```

And then obviously I can make the `aws_instance` depend_on the `aws_eip` explicitly, however the problem I have is there is no way to associate the `aws_eip` post creation and it effectively becomes orphaned. As @JesperTerkelsen suggests on issue #1274 a sensible approach would be to use the same pattern as `AWS_VOLUME_ATTACHMENT`.

In the mean time I have a workaround by using the AWS CLI tools as below in a remote-exec inline provisioner, not pretty but it does work:

### Install AWS CLI tools to allow EIP To be associated

```sh
"sudo apt-get -y install zip unzip",
"curl \"https://s3.amazonaws.com/aws-cli/awscli-bundle.zip\" -o \"awscli-bundle.zip\"",
"sudo unzip awscli-bundle.zip",
"sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws",

# Associate the EIP
"AWS_ACCESS_KEY_ID=${var.access_key} AWS_SECRET_ACCESS_KEY=${var.secret_key} aws ec2 associate-address --instance-id ${self.id} --public-ip ${aws_eip.openvpn_eip.public_ip} --region ${var.aws_region}"
```

The suggestion therefore is to implement an `AWS_EIP_ASSOCIATION` which essentially does what my code above does.

**Comment by byrnedo** [comment]
I would appreciate this.

**Comment by stack72** [comment]
Hi @davehodgson / @byrnedo 

Just a FYI, we recently released https://www.terraform.io/docs/providers/aws/r/eip_association.html to manage EIPs and their associations

Paul
