### ISSUE TITLE
aws_route53_record recreates wildcard record every time

### ISSUE THREAD

**Issue by philk** [hashicorp/terraform#501]
I'm trying to create a wildcard record like this:

```
resource "aws_route53_record" "wildcard_domain_com" {
  zone_id = "${aws_route53_zone.domain_com.zone_id}"
  name = "*.domain.com"
  type = "A"
  ttl = "300"
  records = ["IP"]
}
```

Totally works fine and shows up in my .tfstate file. When I refresh (or attempt to apply with a refresh) the refresh deletes the entry from my .tfstate file causing the record to get recreated on apply (not a duplicate, just overwritten). Tried it with CNAME type and same result.

I would guess it has something to do with the API returning a strange response. `aws route53 list-resource-record-sets` returns `\\052.domain.com` instead of `*.domain.com` as expected:

```
{
            "ResourceRecords": [
                {
                    "Value": "domain.com"
                }
            ],
            "Type": "CNAME",
            "Name": "\\052.domain.com.",
            "TTL": 300
        }
```

**Comment by catsby** [comment]
Thanks for reporting this @delitescere – sorry for the silence. I have a fix in PR #1222 , though it's kind of ugly (manually searching for `\\052` feels gross)

**Comment by catsby** [comment]
cc @philk  too, since he's the original reporter

**Comment by catsby** [comment]
Hey @philk and @delitescere – #1222 was just merged into `master`, so I'm closing this. Thanks again!
