### ISSUE TITLE
ErrorAction type setting - feature suggestion

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#5010]
I've been using Terraform for a few months now and love it, but there is one element to it that annoys me and I haven't found a way round. I've done quite a bit of searching but not come across it so if it exists please let me know ;)

Several times while building a script to deploy an environment with 6-7 servers and 30-40 resources, the script can take around 30 mins to run due to various provisioners etc that I tend to run, which is great as long as it runs - go have a coffee and come back and its built everything.

BUT

While developing that 30 min run script it often takes several attempts to get right. If the resources towards the end cause some error which kills terraform for example today I have a server that can't join a domain because it can't see it and the command is issued from a remote-exec provisioner, Terraform Apply waits for the command to complete, eventually it doesn't and the script exits inelegantly with an non zero status:
- Script exited with non-zero exit status: 1

At that point the script just falls over and kills the run, but I have other resources being created in parallel with their own provisioners which are now in an unstable state so I need to destroy, fix the problem and rerun which takes about 30 mins per attempt.

My issue here is that the other resources may have been about to throw an error or I may have wanted them to complete so I could check they would have completed ok. That is to say I would rather Terraform just highlight the error and keep going, presenting a message at the end that there was an error.

So I'm asking for a parameter similar to the powershell -ErrorAction SilentlyContinue or Continue.

This would have save me several hours personally as I would be able to fix all/most of the errors at once instead of fixing one, re-running, waiting, fixing another etc.

I hope the above makes sense

**Comment by teamterraform** [comment]
Hi @davehodgson! Sorry for the long silence here.

Somewhere along the line a feature like what you were suggesting was added: `provisioner` blocks now support [customizable failure behavior](https://www.terraform.io/docs/provisioners/index.html#failure-behavior), which includes the ability to ignore an error and proceed with actions on downstream resources.

We believe that should meet the use-case you described here, and so we're going to close this out as part of some general issue gardening. Thanks for sharing this use-case, and sorry we neglected to update this issue when we added the `on_failure` argument.
