### ISSUE TITLE
ssl certificate on google_compute_ssl_certificate won't be deleted with terraform destroy

### ISSUE THREAD

**Issue by Blasterdick** [hashicorp/terraform#5015]
After running terraform destroy -force applying plan once again fails with:

* google_compute_ssl_certificate.my-domain-com: Error creating ssl certificate: googleapi: Error 409: The resource 'projects/my-project/global/sslCertificates/my-domain-com' already exists, alreadyExists

**Comment by Blasterdick** [comment]
anyone?

**Comment by lwander** [comment]
What do `tf plan` and `tf show` output?

**Comment by Blasterdick** [comment]
After manually deleting ssl certificate via 

` gcloud compute --project my-project ssl-certificates delete my-certificate`

I re-run terraform apply, and issue seems to desappear, so, I can't reproduse it now as well (it look like something went wrong with terraform destroy first time).

If I face it again, I'll reopen this issue. Thank you.
