### ISSUE TITLE
Unable to access individual variables from a list of module output

### ISSUE THREAD

**Issue by dmercer1** [hashicorp/terraform#5018]
I'm am using a collection of Terraform Community modules to create a VPC with some public and private subnets, then a security group and an ELB. I'd like to use the output of the VPC creation when I create the ELB, specifically the subnet ID's. Right now I set up the output of the VPC module like so:

`output "public_subnets" {
  value = "${join(",", aws_subnet.public.*.id)}"
}`

That should be a list of four values, each value being a subnet ID that was just created. When I try to access a value in that list in my next module declaration like so:

`subnets = "${module.vpc.public_subnets.0.id},${module.vpc.public_subnets.1.id}"`

I get an error:

> Error configuring: 2 error(s) occurred:

>* module.main-elb: missing dependency: module.vpc.output.public_subnets.0.id
>* module.main-elb: missing dependency: module.vpc.output.public_subnets.1.id

I admit I have not seen anything in the documention stating that this is actually possible, I was just inferring from the variable documentation that this would work. Is what I'm trying possible, or should I just set up my module an individual output for each subnet ID? If this is not possible, it would be very helpful to enable as a feature. Thanks.

**Comment by phinze** [comment]
Hi @dmercer1 - we're working on first class array support over in #57, but currently module outputs cannot have a list type, so `module.public_subnets` is simply a string type that needs to be `split()` back out into a list.

Not sure if the `subnets` target you mention is looking for a list or not, but if it is, here's how you'd snag the first two elements and drop them into a list
```tf
  subnets = [
    "${element(split(",", module.vpc.public_subnets), 0)}",
    "${element(split(",", module.vpc.public_subnets), 1)}",
  ]
```

If you just wanted them to be a string, you could drop both of those interpolations into a single string.

Let me know if that makes sense!

**Comment by dmercer1** [comment]
That slightly more elegant than the solution I came up with, using individual variables:

output "public_subnet_0" {
  value = "${aws_subnet.private.0.id}"
}

output "public_subnet_1" {
  value = "${aws_subnet.private.1.id}"
}

output "public_subnet_2" {
  value = "${aws_subnet.private.2.id}"
}

output "public_subnet_3" {
  value = "${aws_subnet.private.3.id}"
}

**Comment by tehmaspc** [comment]
@phinze - thanks; that's helpful.

BTW - based on how TF works element 0 should always be the same value each time - AFTER the initial creation of resources correct? Since tfstate is there I can assume that in the case of my list of subnets that 0, 1, 2, ... will be the same order each time?

Thanks!

**Comment by mitchellh** [comment]
This should all be good to go now with native lists.
