### ISSUE TITLE
acctests: Allow using profiles for acceptance tests

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5019]
This was raised in https://github.com/hashicorp/terraform/pull/4939#issuecomment-180476010 but I was generally thinking about this myself for a while.

I absolutely don't want acceptance tests to be picking up the `default` profile ( :exclamation: ), but I think it would be practical if we use `terraform-acceptance-tests` or something similar for this.

This might affect the current acceptance test setup we have in Travis, but probably shouldn't as we use ChainProvider and if the profile isn't present, ENV vars should be just picked up.

This may also fix https://github.com/hashicorp/terraform/issues/4409

**Comment by stack72** [comment]
@radeksimko I believe this is now solved thanks to @bigkraig and #6383

**Comment by bigkraig** [comment]
i've been running the acceptance tests using AWS_PROFILE

**Comment by stack72** [comment]
Me too :)
