### ISSUE TITLE
provider/aws: colon character rejected when used with `tags`, works with `tag` block

### ISSUE THREAD

**Issue by brandongalbraith** [hashicorp/terraform#5021]
When using the `tag` block with the `aws_autoscaling_group` resource, I'm able to specify tags in the following format:
```
tag {
  key = "blah:description"
  value = "Instances for whatever."
  propagate_at_launch = true
}
```
It appears that the `tag` block cannot be used with the `aws_instance` resource though.

```
tags {
  "blah:description" = "value"
}
```

When I attempt to use the `tags` block with `aws_instance`, and specify a key with a colon character (`:`) in it, I receive and error about an invalid character. I have attempted to specify the key with the semicolon both quoted and unquoted.

This is occurring on Terraform v0.6.11

**Comment by joeig** [comment]
Have you found a solution for this?

**Comment by joeig** [comment]
One workaround might be to create a file called "override.tf.json" which defines the tag with colon. But this isn't the solution I expect :-)

**Comment by holybit** [comment]
Pretty much same issue here. AWS is pretty clear about their [tag restrictions](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions).

However, as an experiment if you manually use the AWS console and enter the the tag value `	
0115;10;US/Mountain;all` it accepts it w/o error. [AWS EBS Snapshot Scheduler](https://aws.amazon.com/answers/infrastructure-management/ebs-snapshot-scheduler/) is an example of an "official" AWS workload that [uses tags](http://docs.aws.amazon.com/solutions/latest/ebs-snapshot-scheduler/deployment.html#step2) that violate their own supposed tagging restrictions.

Here is a terraform config snippet for `aws_instance` for some the tag example above:
```json
  tags {
    Name                     = "tf-jenkins-master"
    environment              = "prod"
    lifecycle                = "${var.lifecycle}"
    repo_name                = "${var.repo_name}"
    "scheduler:ebs-snapshot" = "0115;10;US/Mountain;all"
  }
```

```bash
$ terraform apply
...
* aws_elb.jenkins_master: ValidationError: 1 validation error detected: Value '084515us/mountain;all' at 'tags.4.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
	status code: 400, request id: 964c0a76-e3f4-11e6-9aa8-7985e3025bee
```

**Comment by jaferrando** [comment]
Why is this still open? AWS valid tag names must be acceptable. Just as AWS reserves the "aws:" prefix for their owned tags, many of us want to use a similar scheme to differenciate types or tags, and implement policies that restrict privilege to modify certain tags.

**Comment by mildwonkey** [comment]
@jaferrando this ticket is not open, it was closed in 2016. I will lock it so it no longer generates notifications.

Anyone experiencing new issues with the aws provider should open tickets [in the aws provider repository](https://github.com/terraform-providers/terraform-provider-aws).

Please continue to open issues here for any other terraform issues you encounter, and thanks!
