### ISSUE TITLE
Add instance and cluster parameter groups to aws_rds_cluster

### ISSUE THREAD

**Issue by sscott-starz** [hashicorp/terraform#5023]
`cluster_parameter_group_name` and `instance_parameter_group_name` are missing on `aws_rds_cluster`. This is the same as `parameter_group_name` on `aws_db_instance`.

These are needed so that parameter groups can be created and used with Aurora.

Thanks!

**Comment by stack72** [comment]
@sscott-starz I can only find reference to `cluster_parameter_group_name` in the [AWS SDK](http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html) 

Have you got any links to `instance_parameter_group_name`? I have opened a PR to address this issue

Paul

**Comment by sscott-starz** [comment]
I looked everything over again and it looks like we actually need a new resource and modification for two other resources.

New
aws_rds_cluster_parameter_group: probably can inherit from aws_db_parameter_group
http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster-parameter-group.html


Modify
Add cluster_parameter_group_name to aws_rds_cluster.
http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html
Add parameter_group_name to aws_rds_cluster_instance.
http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html

**Comment by sscott-starz** [comment]
Can we at least get these added? The default parameter groups can't be modified.

Modify
Add cluster_parameter_group_name to aws_rds_cluster.
http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html
Add parameter_group_name to aws_rds_cluster_instance.
http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html

**Comment by catsby** [comment]
Added in #6865
