### ISSUE TITLE
Cloudflare default TTL will always show as to change after creation

### ISSUE THREAD

**Issue by kyl191** [hashicorp/terraform#5040]
I'm hitting the same thing as https://github.com/hashicorp/terraform/issues/147#issuecomment-143296884, but that was a comment added to a closed issue.

The Cloudflare API will return a TTL of 1 for domains that have TTL set to automatic. If the TTL is unstated in the resource, Terraform will default it to 1.

However, the mapping between the default value & what CloudFlare returns doesn't exist - creating a resource like
```
resource "cloudflare_record" "do-ns1" {
    domain = "test.xyz"
    name = "do"
    value = "ns1.digitalocean.com"
    type = "NS"
}
```
will result in changes after the initial creation:
```
~ cloudflare_record.do-ns1
    ttl: "1" => ""
```

The workaround is to add `ttl:1` to the resource - but it's somewhat annoying where ttl is supposed to be optional.

(Testing against 0.6.11)

**Comment by stack72** [comment]
@kyl191 I just opened the PR that fixes this (#5042)
