### ISSUE TITLE
Support Cloudflare API proxying parameter

### ISSUE THREAD

**Issue by kyl191** [hashicorp/terraform#5049]
This is somewhat undocumented, but Cloudflare's API supports setting proxying status through the API with the `proxied` parameter when updating a DNS record: https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

Looking at the code, it seems to be a combination of adding a new record type in https://github.com/pearkes/cloudflare/blob/master/record.go#L89 and appending the new parameter in https://github.com/pearkes/cloudflare/blob/master/record.go#L214

**Comment by xla** [comment]
There is now hashicorp/terraform#5508 which implements the missing option.

**Comment by stack72** [comment]
This has been merged in #5508 :)
