### ISSUE TITLE
config: Report duplicate `output` definitions as invalid

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5052]
The following is currently considered as valid config:

```hcl
variable "var1" {
	default = "Yoda"
}
variable "var2" {
	default = "Pug"
}

output "yada" {
	value = "${var.var1}"
}
output "yada" {
	value = "${var.var2}"
}
```

```
$ terraform apply
```
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  yada = Yoda
```

I believe we should be returning error in these cases as outputs are saved as key/value map - i.e. there will always be only 1 unique value returned for a single key.

**Comment by radeksimko** [comment]
`variable`s have the same issue:

```hcl
variable "var1" {
	default = "Yoda"
}
variable "var1" {
	default = "Pug"
}
```
is reported as valid.

**Comment by phinze** [comment]
Yep agreed terraform should protect against these config mistakes. :+1:

**Comment by sorenmat** [comment]
I've looked into this, and have a fix for the output issue.
But it seems like having multiple variables with the same name is a feature, and it should just override the values. See
https://github.com/hashicorp/terraform/blob/master/config/config_test.go#L371 and the test-fixture https://github.com/hashicorp/terraform/blob/master/config/test-fixtures/validate-var-default/main.tf

Should we still make a check for duplicate variables ?

**Comment by radeksimko** [comment]
@sorenmat I don't see how duplicate variable definitions can be useful as we'll always pick one at the end... so I'd suggest we check for this too.

**Comment by billf** [comment]
some amount of duplicates need to be supported for https://www.terraform.io/docs/configuration/override.html to work.

**Comment by radeksimko** [comment]
@billf good point, we should definitely have tests covering these cases as these _are valid_.
However 2 duplicate variables _in the same file_ should be reported as invalid.

**Comment by brainsik** [comment]
Duplicates in different files should also be invalid. That's the case I'm really worried about as the configurations grow. Is there ever a time where you'd want to re-use a var/output name outside of an override file?
