### ISSUE TITLE
Add support for Customer supplied Encryption in Google

### ISSUE THREAD

**Issue by klenje** [hashicorp/terraform#5053]
Google has added since a few months the ability to use [Customer supplied encryption](https://cloud.google.com/compute/docs/disks/customer-supplied-encryption) in GCE. It would be good if Terraform offered an encryption parameter in google_compute_instance and google_compute_disk resources

**Comment by billf** [comment]
disclaimer: i use the google provider a lot but i neither work for google nor am i a terraform committer.

It's still a beta feature. To access it, Terraform would have to use the beta gcloud go SDK. gcloud resources refer to each by `self_link` (basically, a URL pointing to the resource). contrast that with AWS resources which reference each other by name. the `self_link` generated by any users of a beta SDK would have a different URL than non-beta resources. For example, use of the beta SDK for compute instances to get this feature would cause `google_compute_instance`'s `self_link` attribute to change and that would cause resources that use that attribute to be marked dirty even with zero changes to the terraform files. Then, when the feature moves from beta to general availability any resources that depend on it would again become tainted by the URL change by going back to the release SDK. the schema would have to account for this via versioning and various transition functions.

what i'm saying is even if it's a trivial change to map a single resource attribute to a single field in a map passed to the SDK, use of the beta SDK itself has widespread ramifications.

**Comment by lwander** [comment]
Hey, @klenje, I agree with @billf and will tag this issue as upstream to revisit when this API reaches v1.

**Comment by sbadia** [comment]
Hi here, CSEK(customer supplied encryption key) is now generally available since the 2016/08/01
* https://cloudplatform.googleblog.com/2016/08/how-Google-protects-your-data-Customer-Supplied-Encryption-Keys-for-Compute-Engine-goes-GA.html

**Comment by qvallance-ctc** [comment]
Looks like this issue addressed in #11167

**Comment by danawillow** [comment]
Yes, this is done.
