### ISSUE TITLE
Terraform forces instance re-creation when count change

### ISSUE THREAD

**Issue by Deserved** [hashicorp/terraform#5054]
Version: **0.6.9**
Code sample: 
```
variable "spark-slave-m4large-count" {
  description = "Number of Spark Slave m4.large type instances"
  default = 3
}

resource "template_file" "spark-slave-m4large-userdata" {
  template = "${file("${path.module}/templates/spark-slave.tpl")}"
  count = "${var.spark-slave-m4large-count}"

  vars {
    public_dns = "${format("spark-slave%02d.%s.myhost.mydomain", count.index + 1, "m4large")}"
    worker_port = "${format("%d", var.spark-slave-m4large-port + count.index)}"
  }
}

resource "aws_spot_instance_request" "spark-slave-m4large" {
...
user_data = "${element(template_file.spark-slave-m4large-userdata.*.rendered, count.index)}"
...
}
```

If I change count number to 4, it will force all instances to be destroyed and re-deployed again, and all due to template count change, for some reason when I change template count, it change hash of it as-well, sample from the plan:

```
 user_data:                                 "057f72dfc9742792778009d716bbe0fe22e11237" => "b74f3d83ff0df806f087c42c8600dbd31e59744a" (forces new resource)

```

It looks like, it re-renders all templates, is that expected behaviour? How can I avoid it?

**Comment by phinze** [comment]
Hi @Deserved - this is an expression of #3449, which we have active work in progress to address by adding first class list indexing to Terraform's interpolation language. You can track that issue to learn when a fix is available. :+1:
