### ISSUE TITLE
file provisioner - feature request...two way transfer

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#5055]
I have a use case whereby I am standing up an ubuntu box in AWS, I copy a couple of script files up using the file provisioner, run the commands with remote-exec and would like to copy the files back down afterwards.

In my specific case it is to copy some certs from the server which have been generated by a newly created CA. 

Would just be handy to be able to us the scp from the file provisioner in reverse rather than having to do it on local exec from a windows laptop.

**Comment by phinze** [comment]
Hi @davehodgson - thanks for the report of your use case. This feature was also requested in #3379, so I'm going to close this to keep the threads consolidated. Definitely something we'd like to add!
