### ISSUE TITLE
Assign Elastic IP to Spot Instance throws error (enhancement)

### ISSUE THREAD

**Issue by Deserved** [hashicorp/terraform#5062]
When I create spot instance and try to assign EIP to it, I get error that EIP can not be assigned to pending instance. So I have to run terraform twice, first to set spot instance, second time is to assign EIP to spot instance to active instance. Is it possible to set flag **wait_for_fulfillment** to true only when status of instance is Active, or to have some other flag?

Thank you.

**Comment by evilezh** [comment]
+1
wait_for_fulfillment also needs to check, that instance is actually running, so you can do some action on it.
And as suggested, maybe some extra flag.

**Comment by jbrodley** [comment]
+1
