### ISSUE TITLE
aws_route53_record does not support .arpa records, aka reverse DNS.

### ISSUE THREAD

**Issue by vanDonselaar** [hashicorp/terraform#5068]
It is not possible to create reverse DNS records using `aws_route53_record`.

Minimal working example:
```
resource "aws_route53_zone" "my_private_zone" {
   name = "terraform.example.org"
}

resource "aws_route53_record" "reverse_record" {
  zone_id = "${aws_route53_zone.my_private_zone.id}"
  name = "1.0.168.192.in-addr.arpa"
  type = "PTR"
  ttl = "300"
  records = ["node1.terraform.example.org"]
}
```
Problem: this results in a DNS record that includes the zone name: `1.0.168.192.in-addr.arpa.terraform.example.org.`. Trying to work around this problem by terminating the record entry with a dot doesn't work either: 
```
1 error(s) occurred:

* aws_route53_record.reverse_record: InvalidChangeBatch: FATAL problem: DomainLabelEmpty encountered at 1.0.168.192.in-addr.arpa..terraform.example.org
```

This is all caused by the method `expandRecordName` in `/builtin/providers/aws/resource_aws_route53_record.go`.

I think this can be fixed by the following adjustment:

```patch
--- builtin/providers/aws/resource_aws_route53_record.go	(revision 73102aba427cc071075ad2672f7f1d0f9cb035c3)
+++ builtin/providers/aws/resource_aws_route53_record.go	(revision )
@@ -501,7 +501,7 @@
 func expandRecordName(name, zone string) string {
 	rn := strings.ToLower(strings.TrimSuffix(name, "."))
 	zone = strings.TrimSuffix(zone, ".")
-	if !strings.HasSuffix(rn, zone) {
+	if !strings.HasSuffix(rn, zone) && !strings.HasSuffix(rn, ".arpa") {
 		rn = strings.Join([]string{name, zone}, ".")
 	}
 	return rn
```
I'm not sure if this is safe to do. This method was introduced in https://github.com/hashicorp/terraform/pull/1279/ which fixes quite a lot of issues regarding updating of DNS records (i.e. https://github.com/hashicorp/terraform/issues/1126, https://github.com/hashicorp/terraform/issues/1264 and https://github.com/hashicorp/terraform/issues/1122). So this might need some more testing.

**Comment by billf** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/route-53-reverse-dns/

the proper zone to put such a record in would be `0.168.192.in-addr.arpa` and then you would add a PTR record for "1.0.168.192.in-addr.arpa"

**Comment by vanDonselaar** [comment]
I see, my mistake. Thanks for pointing out.
