### ISSUE TITLE
Cycle error on plan when changing aws_key_pair.

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#5073]
I have aws_launch_configuration, aws_autoscaling_group with create_before_destroy.
And i wanted to change aws_key_pair that is used in aws_launch_configuration. And im getting following error:
```
Refreshing Terraform state prior to plan...
Error running plan: 1 error(s) occurred:

* Cycle: aws_key_pair.deployer (destroy), aws_key_pair.deployer, aws_launch_configuration.ecs, aws_autoscaling_group.ecs, aws_launch_configuration.ecs (destroy)
```

Is there a workaroudn for it?

**Comment by catsby** [comment]
Hey @aldarund – there is a known limitation with `create_before_destroy`, in that all dependent resources also need to have `create_before_destroy`. So here, try adding `create_before_destroy` to your `key_pair`. 

See "NOTE on create_before_destroy and dependencies" here for a bit of more information https://www.terraform.io/docs/configuration/resources.html 

Let me know if you are still running into this after adding that block!

**Comment by aldarund** [comment]
I didnt tried, but i will. I just though that key pair have a specific name, so it wont be able to create a new key with the same name before destroying old. Or is it handled somehow?
