### ISSUE TITLE
config: keys() & values() interpolation functions

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5074]
As @dannietjoh mentioned in https://github.com/hashicorp/terraform/pull/2198#issuecomment-181292702 these two functions are undocumented.

Interestingly both of these functions, along with `lookup()` that is documented are mapped in `./config/raw_config.go` as opposed to all other functions which are mapped directly in `./config/interpolate_funcs.go`.

I don't know (yet) whether there was/is a reason for it to be there and whether it had/has a different place in the lifecycle which should be documented too or whether it's just something from the past and this mapping can now be moved to `./config/interpolate_funcs.go` and treated the same way.

**Comment by phinze** [comment]
They need to be there because they need access to variable values from elsewhere in the config. All of the `interpolate_funcs` implementations receive primitives directly as arguments, but these functions need to go look up values based on received keys.

Definitely need docs for these though!

**Comment by iroller** [comment]
+1 on docs. Really glad to find those two functions

**Comment by eedwardsdisco** [comment]
I started using these functions, but as a warning, they puke if you don't supply a valid map, which would have been useful as I was trying to make a map an optional variable, which could scale from 0 entries to N entries, and then use the `length` of the `keys()` to generate other resources as `count`.

**Comment by phinze** [comment]
Docs are done on master, as well as enhancements to make them more resilient to different types. 👍
