### ISSUE TITLE
unable to create ecs_service with load_balancer

### ISSUE THREAD

**Issue by tadasv** [hashicorp/terraform#5079]
I have no luck creating aws_ecs_service with load balancer. If I remove load balancer block from ecs_service I have no problems creating the service, otherwise the step timeouts.

Terraform v0.6.11

Error message:

`aws_ecs_service.simple_service: timeout while waiting for state to become '[success]'`

```hcl
resource "aws_iam_role" "ecs_elb" {
    name = "ecs-elb"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_policy_attachment" "ecs_elb" {
    name = "ecs_elb"
    roles = ["${aws_iam_role.ecs_elb.id}"]
    policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole"
}

resource "aws_elb" "simple_service_elb" {
    name = "simple-service-elb"
    subnets = ["${split(",", module.vpc.public_subnets)}"]
    security_groups = ["${aws_security_group.allow_cluster.id}"]

    listener {
        instance_port = 8000
        instance_protocol = "http"
        lb_port = 80
        lb_protocol = "http"
    }

    health_check {
        healthy_threshold = 2
        unhealthy_threshold = 2
        target = "HTTP:8000/"
        interval = 15
        timeout = 5
    }
}

resource "aws_ecs_service" "simple_service" {
    name = "simple-service"
    cluster = "${aws_ecs_cluster.staging.id}"
    task_definition = "${aws_ecs_task_definition.simple_service.arn}"
    desired_count = 1
    iam_role = "${aws_iam_role.ecs_elb.arn}"
    depends_on = ["aws_iam_policy_attachment.ecs_elb"]

    load_balancer {
        elb_name = "${aws_elb.simple_service_elb.id}"
        container_name = "simple-service"
        container_port = 8000
    }
}
```

**Comment by MaikuMori** [comment]
Enable debug logging using `env TF_LOG=DEBUG terraform apply`and you will notice that it's stuck in an infinite loop somewhere. This happens when it tries to destroy/update something which has some unknown to terraform aws constraint.

I had similar problem. Also `TF_LOG=DEBUG` is very helpful in these cases where normal error messages are too vague.

**Comment by radeksimko** [comment]
The actual error _should_ be visible (normally). There is [a bug](https://github.com/hashicorp/terraform/issues/4926) hiding away the real cause which may cause the confusion unfortunately.

@tadasv Until we get that bug fixed, would you mind providing the debug log (minus any secrets)?

There can be many reasons the creation of your ECS service fails - ports mismatch (container or host), container name mismatch between svc and task definition, insufficient IAM role, ...

I'm afraid we're not able to help without further details.

---------

Also I'm pretty sure that a standard ECS & ELB configuration works, we actually have an acceptance test for this: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_ecs_service_test.go#L421-L513

**Comment by tadasv** [comment]
@radeksimko I ran it with debug logging on. I had incorrectly setup IAM role. It works fine.

I wish there was better reporting by default instead of having to go through debug logs.

**Comment by radeksimko** [comment]
Thanks for sharing the details @tadasv , as mentioned there will be better reporting once we fix https://github.com/hashicorp/terraform/issues/4926

Thanks for understanding, I will now close this issue as I believe there isn't anything to fix.
