### ISSUE TITLE
Datadog provider

### ISSUE THREAD

**Issue by ojongerius** [hashicorp/terraform#5080]
Is there anything I can do to get some attention for #3611?

**Comment by ketzacoatl** [comment]
Creating a duplicate ticket creates more work for team that already has a lot on their plate, there must be a better way to get the attention you are looking for..

**Comment by jen20** [comment]
Hi @ojongerius. I just looked over #3611 and have a few suggestions, but on the whole it looks good. I'll close this and comment there later today to keep everything in one place.

**Comment by ojongerius** [comment]
Thanks @jen20 !
