### ISSUE TITLE
Provider vcd has no option for setting disk size

### ISSUE THREAD

**Issue by mikemcclay** [hashicorp/terraform#5083]
Feature request to add the ability to define the disk size for the vm being provisioned.

At the moment all Vm's are provisioned with the vcloud platform default of 16GB. It would make this provider much more useful if it could allow for the disk size to be set.

**Comment by robcoward** [comment]
Hi @mikemcclay - this is a feature I'm looking into implementing. Did you close this issue for a reason ?

**Comment by mikemcclay** [comment]
I closed it because I wanted to go back to the (awesome) GDS vcloud tools and fully identify what functionality they have over the vcd provider for Terraform. If your looking to add functions to the vcd provider then thats great and thanks in advance for your efforts on expanding the featureset.

**Comment by robcoward** [comment]
I'm compiling a shopping list of features to be added and will start raising a few issues here so others have visibility of what I'm planning.
