### ISSUE TITLE
terraform 0.6.11 breaks openstack provider

### ISSUE THREAD

**Issue by Holmser** [hashicorp/terraform#5086]
When applying I initially received an EOF error, now when I apply or destroy terraform crashes.
[crash.txt](https://github.com/hashicorp/terraform/files/125240/crash.txt)

**Comment by jtopjian** [comment]
@Holmser I apologize that you're running into this. I believe this has been fixed #4966, so things should go back to normal in 0.6.12.

If you don't think the crash is related to the bug in #4966, can you describe how you're producing the error and we'll get it sorted out?
