### ISSUE TITLE
Add count to template_cloudinit_config.part

### ISSUE THREAD

**Issue by wr0ngway** [hashicorp/terraform#5091]
I'd like to be able to have a module which takes a csv of config names, and generates a merged cloudinit config for adding to the user-data for an aws_instance.  This would let me have a library of templates I can mix/match to my instances without having to go as heavyweight as ansible/etc.  Seems like the only thing I;m missing is the ability to use `count` within `template_cloudinit_config.part` 

```
// cloud-init module

variable "template_names_csv" {
  description = "The template names to generate a combined cloud config for"
}

resource "template_cloudinit_config" "combined" {
  gzip = false
  base64_encode = false

  part {
    count = "${length(split(",", var.template_names_csv))}"
    content_type = "text/cloud-config"
    content = "${file(format("%s/%s.yml","${path.module}/templates",element(split(",", var.template_names_csv), count.index)))}"
    merge_type = "list(append)+dict(recurse_array)+str()"
  }
}

output "rendered" {
  value = "${template_cloudinit_config.combined.rendered}"
}
```

```
// my terraform main.tf

module "test-config" {
  source = "cloud-init"
  template_names_csv = "util,docker"
}

resource "aws_instance" "test" {
  ...
  user_data = "${module.test-config.rendered}"
}

```

**Comment by mitchellh** [comment]
Great idea, but unfortunately not possible until we have nestable resources in helper/schema. We have that planned for the future but its a bit far out. Until then, you'll have to get by with manually expanding :( sorry.

**Comment by tritao** [comment]
Is this possible yet?

**Comment by poveyd** [comment]
We're interested in this feature too.

**Comment by aablumberg** [comment]
Also looking for this.
