### ISSUE TITLE
Crashing bug in AWS build

### ISSUE THREAD

**Issue by RevCBH** [hashicorp/terraform#5097]
Sorry, don't have a clean repro yet. I'm on 0.6.10, will try updating to 0.6.11 to see if that fixes it.
[crash.log.gz](https://github.com/hashicorp/terraform/files/125764/crash.log.gz)

**Comment by RevCBH** [comment]
Still crashing in 0.6.11. I'll try to get something narrow to hand off.

**Comment by RevCBH** [comment]
Based on a section of the log, this appears to be a dupe of https://github.com/hashicorp/terraform/issues/5092

```
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x1a1723]
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: goroutine 241 [running]:
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.routeIDHash(0x8224e9c20, 0x0, 0x0, 0x0)
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160205-6028-1j45z54/terraform-0.6.11/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:303 +0xa3
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteCreate(0x8224e9c20, 0x96c760, 0x822632000, 0x0, 0x0)
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160205-6028-1j45z54/terraform-0.6.11/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:161 +0x9bd
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0x82258f380, 0x8221499e0, 0x821f71450, 0x96c760, 0x822632000, 0x10101, 0x0, 0x0)
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160205-6028-1j45z54/terraform-0.6.11/src/github.com/hashicorp/terraform/helper/schema/resource.go:145 +0x28e
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0x8224d8ab0, 0x82270f4c0, 0x8221499e0, 0x821f71450, 0x201, 0x0, 0x0)
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160205-6028-1j45z54/terraform-0.6.11/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0x82211d4e0, 0x822296d40, 0x821f71610, 0x0, 0x0)
2016/02/10 20:42:28 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160205-6028-1j45z54/terraform-0.6.11/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x76
```

**Comment by catsby** [comment]
Hey @RevCBH do you have any steps that can help me reproduce and isolate this? It looks like a few things happened here, the first you mention is a security group issue and the second is related to routes.

**Comment by RevCBH** [comment]
Here's a sanitized bundle of what produced the run:
[terraform-bug.tar.gz](https://github.com/hashicorp/terraform/files/127184/terraform-bug.tar.gz)

I ran `terraform get`, then `terraform apply -target=module.bootstrap`, then `terraform apply`.

It crashes on the final `terraform apply`. The security group and the subnet it complains about if you run `terraform apply` again get created in AWS, but aren't reflected in the .tfstate file.

**Comment by RevCBH** [comment]
@catsby - Was that helpful in creating a repro? Is there anything else I can provide? If you guys haven't had a chance to look at it yet I might be able to dive into it today.

If I put together a PR is it best to do it against master or a release tag?

**Comment by catsby** [comment]
Hey @RevCBH – sorry, I have not dug in yet. We do have a [contributing guide][1] if you haven't seen it, it's helpful to be aware of. Otherwise yes please send any PRs based off of / to the `master` branch.




[1]: https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md

**Comment by catsby** [comment]
I posted #5155 , it should address this

**Comment by RevCBH** [comment]
Awesome, thanks! Sorry I didn't get to it. I'll test it out locally now.

**Comment by RevCBH** [comment]
Confirmed that this fixes the crash I was seeing.

**Comment by catsby** [comment]
Awesome, thanks for following up!
