### ISSUE TITLE
InvalidBDM from nova-api with block device mapping.

### ISSUE THREAD

**Issue by pryorda** [hashicorp/terraform#5098]
When provisioning an instance with a block device in openstack you will recieve a InvalidBDM error if you do not specify volume_size.

Example:    
block_device = {
      uuid = "39807484-2edb-4aae-9fe4-1a878482f16e"
      source_type = "image"
      destination_type = "volume"
}

If you add volume_size it works
Example
block_device = {
      uuid = "39807484-2edb-4aae-9fe4-1a878482f16e"
      source_type = "image"
      volume_size = "50"
      destination_type = "volume"
}

In the code it would be good to query the volume_size from flavor if not se.

**Comment by jtopjian** [comment]
I see that `volume_size` is marked as optional... I think it should actually be required, but your idea is a cool workaround to keep it optional. :)

**Comment by jtopjian** [comment]
I'm revisiting this and I think the correct change is to make `volume_size` required. This does two things:

1. Mimics the functionality of the Nova CLI client (therefore avoids "surprises")
2. Makes using multiple block devices more consistent. #5131 will add the ability to use multiple block_devices and would provide an inconsistent user experience all but one required a size.

I'll get this fixed up.

Thank you for reporting it :)

**Comment by jtopjian** [comment]
Ah! Actually there's a bit more to this! I'm finishing up #5131 which will have more details. 

Thanks again for reporting this -- it highlighted some quirky behavior within OpenStack :smile:
