### ISSUE TITLE
Support for OpenStack (including Rackspace Cloud)

### ISSUE THREAD

**Issue by jumoel** [hashicorp/terraform#51]
Are there any plans for a Rackspace provider in terraform?

**Comment by justinclayton** [comment]
+1. Is progress on various components of this provider being tracked somewhere?

**Comment by jtopjian** [comment]
If anyone is interested, I did a little weekend project of taking the current state of @haklop's work, broke it out into a dedicated repository, and updated some of it to work with the latest version of gophercloud:

https://github.com/jtopjian/terraform-provider-openstack

**Comment by keithchambers** [comment]
Definitely interested.  Thank you for sharing!

**Comment by drnic** [comment]
Boom shakalaka!

**Comment by nibalizer** [comment]
woot!

**Comment by justinclayton** [comment]
Applause to all involved!





On Tue, Mar 31, 2015 at 3:40 PM -0700, "Spencer Krum" <notifications@github.com> wrote:












woot!

**Comment by zzamboni** [comment]
Great stuff, thanks!

**Comment by tfhartmann** [comment]
Nice work!!! 

:shipit:

**Comment by ehaselwanter** [comment]
Awesome!

**Comment by plalloni** [comment]
Great!
