### ISSUE TITLE
Openstack - Interesting things happen when soft delete is enabled

### ISSUE THREAD

**Issue by imduffy15** [hashicorp/terraform#5104]
Openstack has featured labelled "soft-delete", it enables cloud admins to restore a VM for a certain amount of time before the VM is fully removed.

It functions very different to standard delete, for a start, the VM is in a state of "soft-deleted" and all volumes, VIP, security groups associated with this VM are still seen to be in use.

This causes a great mess for terraform, even if you modify the code to see a soft-deleted we'd have to do some polling for who knows how long to delete the instance and associated items.

How would people feel about using ForceDelete as a default for openstack instance destroys? This would mean soft delete is bypassed for terraform and terraform can function as normal in an environment where soft delete is enabled.

I've recently added support in gophercloud for this https://github.com/rackspace/gophercloud/commit/370c4300029d713ff36f3377c3e98e5ad73b1c4d so it wouldn't be too hard to fit it in to our current model.

Thoughts?

Thanks,
Ian.

**Comment by jtopjian** [comment]
Thanks for bringing this up :)

I'll admit that I'm not familiar at all with soft deleting instances. Maybe this was my ignorance, I thought but any conversation that mentioned soft deletes were debating deleting rows from databases or keeping the row but marking it as deleted. Can you fill me in? 

Doing `nova help | grep soft`, I see that `nova restore` restores a soft deleted instance. How does one make an instance soft deleted to begin with?

To confuse me even more, this is the first result from Googling "nova soft delete" is [this](https://specs.openstack.org/openstack/nova-specs/specs/mitaka/approved/no-more-soft-delete.html) which has been approved and implemented...

**Comment by imduffy15** [comment]
> Can you fill me in?

The term, schedule for deletion might be better.... Basically, when enabled, if you delete an instance that instance will be qued for deletion until a defined period of time passes. This allows an operator to restore an instance in the event it was deleted in error.

> How does one make an instance soft deleted to begin with?
Its a standard delete when the option `reclaim_instance_interval=some-interval` is configured within `/etc/nova/nova.conf`

The restore command you found is how the instance is restored, this is the only way to do a restore sadly (no ui option)

> To confuse me even more, this is the first result from Googling "nova soft delete" is this which has been approved and implemented...

This is from Liberty onwards, all older releases still have soft delete functionality.

**Comment by jtopjian** [comment]
Thank you very much! 

I think this is worthwhile to have here as an enhancement request :smile:
