### ISSUE TITLE
Support configuring a Lambda function inside a VPC

### ISSUE THREAD

**Issue by nick-nz** [hashicorp/terraform#5105]
AWS has just announced support for accessing resources inside VPCs from Lambda functions. It would be great to be able to configure this with Terraform.

Docs here: http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

**Comment by muikrad** [comment]
+1!

I am not familiar with Terraform's release cycle, is this something we ought to see soon, or we will most likely have to wait a few months?
