### ISSUE TITLE
Create a Google Cloud Engine instance with access to a service account

### ISSUE THREAD

**Issue by pdunnavant** [hashicorp/terraform#511]
It would be awesome if we could set the initial service account access when bringing up the initial server instance.

It looks like there's been a little thought around this, given this commented code:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance.go#L273-L282

I may try to dig into this myself; I just don't have any experience with Go yet. :-)

**Comment by sparkprime** [comment]
@phinze you can close this now

**Comment by phinze** [comment]
:+1: landed in master!
