### ISSUE TITLE
Tags attribute for aws_autoscaling_group 

### ISSUE THREAD

**Issue by yikdoj** [hashicorp/terraform#512]
Hi  , 

I have used terraform a while , very happy to see tags is added to ec2_instance in new version , can we also add tags attribute/function to resource aws_autoscaling_group ? cause it is very usable creating instances with tags provided by  autoscaling group . 

Kevin

**Comment by catsby** [comment]
Tags for Auto Scaling Groups were added in https://github.com/hashicorp/terraform/pull/1319, so I'm closing this now. Thanks!
