### ISSUE TITLE
aws_autoscaling_group that pulls in data from terraform_remote_state always shows up as modified in plan

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#5121]
I have a reasonably complicated Terraform setup and can't share all of it, so I'll try to cherry pick what I *believe* is relevant. Hopefully, I won't miss anything critical.

I have Terraform module, let's call it `module-m`, that defines an `aws_autoscaling_group` and sets the `vpc_zone_identifier` to a variable called `vpc_subnet_ids` that is passed into that module:

```
resource "aws_autoscaling_group" "autoscaling_group" {
  name = "some name"
  min_size = "${var.cluster_min_size}"
  max_size = "${var.cluster_max_size}"
  launch_configuration = "${aws_launch_configuration.launch_configuration.name}"
  vpc_zone_identifier = ["${split(",", var.vpc_subnet_ids)}"]
}
```

`module-m` is pulled in by a top-level `main.tf` file:

```
module "module_m" {
  source = "modules/module-m"

  cluster_min_size = 5
  cluster_max_size = 10

  vpc_subnet_ids = "${terraform_remote_state.vpc.output.subnet_ids}"
}
```

Notice how it sets `vpc_subnet_ids` to a value pulled from `terraform_remote_state`:

```
resource "terraform_remote_state" "vpc" {
  backend = "s3"
  config {
    bucket = "${var.vpc_remote_state_bucket_name}"
    key = "${var.vpc_remote_state_key_file_name}"
    region = "${var.region}"
  }
}
``` 

With this setup, every time I run `terraform plan`, I'm told there are changes to be applied to this `aws_autoscaling_group` even though nothing has actually changed:

```
~ module.module_m.aws_autoscaling_group.autoscaling_group
    vpc_zone_identifier.1210648614: "" => " subnet-66784611"
    vpc_zone_identifier.1685994473: "subnet-66784611" => ""
    vpc_zone_identifier.223948712:  "" => " subnet-a086d2f9"
    vpc_zone_identifier.3024374379: "subnet-78ebf11d" => "subnet-78ebf11d"
    vpc_zone_identifier.554572903:  "subnet-a086d2f9" => ""
```

Any ideas?

**Comment by billf** [comment]
there is whitespace before the letter `s` in `subnet` in the new entries. the one that isn't changing probably is the first element in the list.

```
    vpc_zone_identifier.1210648614: "" => " subnet-66784611"
    vpc_zone_identifier.1685994473: "subnet-66784611" => ""
    vpc_zone_identifier.223948712:  "" => " subnet-a086d2f9"
    vpc_zone_identifier.3024374379: "subnet-78ebf11d" => "subnet-78ebf11d"
    vpc_zone_identifier.554572903:  "subnet-a086d2f9" => ""

```

the most likely reason for that is whitespace after the delimiter leaking in
e.g. `"subnet-abcdef, subnet-fedcba, subnet-123456"` vs `"subnet-abcdef,subnet-fedcba,subnet-123456"` 

i can think of a few ways to address this: correcting at write-time the `output` the remote state is exporting or correcting the `terraform_remote_state.vpc.output.subnet_ids` at read-time.

- when storing the values, the `trimspace(...)` interpolation function can be used.
- if that's not an option, when pulling them out and reading them: use `split(", ", ...)` to include the whitespace as part of the delimiter.
- if sometimes `,foo` happens and sometimes `, foo` happens and the module has to be defensive against it: use `split(" ")` in combination with `compact()` to remove the empty elements generated.

agree that the AWS SDK (& the terraform AWS glue) could be a little more defensive about this and trim input. if the interpolation result isn't something like `"subnet-abcdef, subnet-fedcba"`, then this could be a bug.

hope that helps.

**Comment by brikis98** [comment]
Ah, great catch! It was indeed caused by extra spaces in `terraform_remote_state.vpc.output.subnet_ids`. I've removed those and now things work fine. Thank you!
