### ISSUE TITLE
Use strip on production shipped binaries

### ISSUE THREAD

**Issue by dlsniper** [hashicorp/terraform#5133]
Hi,

I wonder if it would be ok to use the ` strip ` command on the production shipped binaries to remove away some of the information in order to make the size of the binaries better.
As an example, I've done it for terraform 0.6.11 and from ~150mb archived it dropped to ~100mb while the unpacked version dropped from ~600mb to ~400mb.
What do you think about this? I couldn't notice any issues with panics and other than making the process not debuggable in a nice way via gdb or delve I don't see any downsides.

Thank you.

**Comment by jen20** [comment]
Hi @dlsniper - there is a plan to move to using the `hashicorp/go-plugin` library for 0.7 (there is a pull request open for this from @mitchellh now). Part of this will mean the built in providers are bundled as a single executable in the same manner as Packer. This will go a long way to addressing the size of the binaries. That said, stripping the binaries may also be a valuable addition - I'll mark this as a core enhancement for now and come back to it nearer a release.

**Comment by stack72** [comment]
Hi @dlsniper 

We have combined the binaries into a single binary for 0.7 :) The binary is also a low smaller :) https://github.com/hashicorp/terraform/pull/6013

Paul
