### ISSUE TITLE
v0.6.11 - not picking up final_snapshot_identifier

### ISSUE THREAD

**Issue by dcloud9** [hashicorp/terraform#5134]
On "updating" a stack that has no final_snapshot_identifier, $terraform apply|plan|destroy -force can;t pick up final_snapshot_identifier and rendered error below.

Error applying plan:

1 error(s) occurred:

* aws_db_instance.default: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by stack72** [comment]
Hi @dcloud9, thanks for the bug report here. Please can you post a sample of the terraform config you are using (minus secrets) so that I can try and re-create this?

Thanks

Paul

**Comment by dcloud9** [comment]
@stack72, most params are parameterised, nothing fancy. It's the way TF behaves when final_snapshot_identifier did not exist in RDS creation, then update TF template with that on and run terraform plan.
Noticed that param is not being picked up at all unlike other params such as copy_tags_to_snapshot.
```
# RDS DB Instance
resource "aws_db_instance" "default" {
  allocated_storage           = "${var.db_allocated_storage}"
  auto_minor_version_upgrade  = "false"
  backup_retention_period     = "1"
  copy_tags_to_snapshot       = "true"
  db_subnet_group_name        = "${aws_db_subnet_group.default.id}"
  engine                      = "mysql"
  engine_version              = "5.XX"
  final_snapshot_identifier   = "${var.tag_project}-${var.tag_environment}-db${var.db_instance_count}-final"  
  identifier                  = "${var.tag_project}-${var.tag_environment}-db${var.db_instance_count}-id"
  instance_class              = "${var.db_instance_class}"
  multi_az                    = "${var.db_multi_az}"
  name                        = "${var.tag_service}"
  parameter_group_name        = "${aws_db_parameter_group.default.id}"
  password                    = "${var.db_password}"
  publicly_accessible         = "false"
  skip_final_snapshot         = "${var.db_skip_final_snapshot}"
  storage_encrypted           = "${var.db_encryption}"
  storage_type                = "gp2"
  username                    = "${var.db_username}"
  vpc_security_group_ids      = ["${aws_security_group.default.id}"]

  depends_on = ["aws_db_parameter_group.default"]  
}
```

**Comment by timothykimball** [comment]
Having this problem as well w/ v0.6.12

Only occurs when attempting to deleting infrastructure deployed with an older copy of terraform.

**Comment by stack72** [comment]
Hi @dcloud9 

Can you let me know if this is still a problem? I cannot recreate this error

Thanks

Paul

**Comment by dcloud9** [comment]
I don't have issues in my v0.6.15. We can close it. Thanks.

**Comment by stack72** [comment]
Wonderful news :) thanks!

**Comment by windus** [comment]
I'm still having issues with this and I just upgraded to 0.6.16.  "aws_db_instance.default: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required"  I've tried using skip_final_snap too and no dice.

**Comment by stack72** [comment]
Hi @windus 

Please can you post the sample of code for the db_instance resource (minus secrets) and we can have a look

Thanks


Paul

**Comment by windus** [comment]
I'd be happy to.  Interesting note:  I upgraded to 06.16, tried
again...same problem.  Then I blew everything away in my VPC including the
RDS (leaving the snap to build from in place) and also blew away my tfstate
files.  Then I ran apply from this new clean state and it went ok.  I did
the destroy and it finally destroyed.  So you can't keep tfstate files from
previous versions around and expect the parser to read them correctly when
you've upgraded?  Odd....

**Comment by stack72** [comment]
That's a potential bug. Question, when you made the change for the skipping of the snapshot, did you apply before destroy? If you didn't apply, then that book would not have been updated on the state and would have defaulted to the old way of doing it

P.

**Comment by windus** [comment]
I would keep skip snap in there and apply.  It would fail.  Then I
commented it out and put the final snap name in...still failed saying I
need to specify a snap shot.  It just wasn't reading either tag right.  So
I upgraded and did the same experiment again with same results.

Then I realized I had whined about this before online and found my update
from a few months ago saying I had "fixed" it when clearing out all the VPC
by hand and the tfstate file, so I followed that same advice and that's
when I got past it.

Does that makes sense?

**Comment by osterman** [comment]
I am encountering this bug as well on Terraform 0.6.16.
```
(assume-aws-role ops)$ bin/terraform-0.6.16/terraform -v
Terraform v0.6.16
```

The exact message is:

```
* aws_db_instance.database: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required
```

It's triggered by this change:
```
storage_encrypted:                 "true" => "false" (forces new resource)
```

Here's the underlying resource:
```
resource "aws_db_instance" "database" {                                                                                                                                
  identifier = "${var.namespace}"
  final_snapshot_identifier = "${var.namespace}"
  count = "${var.database_count}"

  # The DB name to create
  name="supernova"

  # Configurable per STAGE (dev/prod/...)
  multi_az = false
  storage_encrypted = false
  publicly_accessible = true
  skip_final_snapshot = true
  allow_major_version_upgrade = true
  apply_immediately = true

  # DB Config
  username = "${var.database_username}"
  password = "${var.database_password}"

  # Instance Config
  instance_class = "${lookup(var.instance_types, "database")}"
  copy_tags_to_snapshot = true

  tags = {
    Name = "${var.namespace}-database"
    Namespace = "${var.namespace}"
  }

  # Storage
  allocated_storage = 100
  iops = 1000

  # Engine
  engine = "postgres"
  engine_version = "${var.database_version}"

  # Network
  port = 5432
  db_subnet_group_name = "${aws_db_subnet_group.database.name}"
  vpc_security_group_ids = [
    "${aws_security_group.database.id}",
    "${aws_security_group.cluster.id}"
  ]

  # AWS config
  backup_window = "05:00-08:30"
  maintenance_window = "sat:09:30-sat:22:00"
}
```

**Comment by osterman** [comment]
Downgrading to `0.6.15` allows me to "work around" the problem. This means there's definitely a bug in 0.6.16.

Interestingly, the output is slightly different. 

```
storage_encrypted:                 "true" => "0" (forces new resource)
```

Note in `0.16.16` it says that `storage_encrypted` was changed to`false`, but in `0.6.15` it says it was changed to `0`.
