### ISSUE TITLE
provider/aws: ECR region support

### ISSUE THREAD

**Issue by dlsniper** [hashicorp/terraform#5137]
Hi,

Currently AWS ECR only supports running from ` us-east-1 ` which is unfortunate as I have to use it from ` eu-central-1 `.
While this is possible from the Interface, it's not currently possible from Terraform.
Would a patch that adds a special override for the region for this be accepted? The idea would be that adding a property like ` region = eu-east-1 ` would also allow for further usage of this as ECR slowly expands in the global AWS offering.

What do you think?

**Comment by stack72** [comment]
As suggested in #5139, a suitable workaround (until AWS releases this globally) will be as follows:

```
provider "aws" {
}

provider "aws" {
    alias = "east"
    region = "us-east-1"
}

resource "aws_ecr_repository" "foo" {
  provider = "aws.east"
  name = "bar"
}
```
