### ISSUE TITLE
AWS default region

### ISSUE THREAD

**Issue by tilgovi** [hashicorp/terraform#5143]
With following minimal example:

```
provider "aws" {}
resource "aws_eip" "test" {}
```

Credentials are properly picked up from my ~/.aws/credentials from the default credential set. However, I have a default region configured there yet I am asked for the region when I run `terraform apply`.

**Comment by catsby** [comment]
Hey @tilgovi – where are you configuring the default region, in `~/.aws/config`? I don't believe the credentials file supports the `region` key, but we should probably pick up from `config`, which I don't think we are...

**Comment by tilgovi** [comment]
You guessed it. I couldn't tell from AWS docs whether the credentials file could also contain a region setting or not so I tried it both places.

**Comment by catsby** [comment]
Hrm, yeah right now we only read a default region from the environment, such as `AWS_REGION`. 
We could likely add a new `DefaultFunc` here, that first checks the environment and then second checks the `~/.aws/config` file here:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/provider.go#L59

Unfortunately I'm unlikely to get to this anytime soon, so anyone listening who's interested, feel free to take a stab at it :smile:

**Comment by tilgovi** [comment]
The AWS documentation example ([here](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles)) makes it seem as though the config file is the place for this.

That means we probably need a ConfigFile setting, too, with the proper default like the credentials file.

I may take a stab at this :).

**Comment by catsby** [comment]
Sounds great @tilgovi , let us know if you have any questions on the direction or otherwise. I'm going to close this issue for now, thanks!

**Comment by HontoNoRoger** [comment]
As far as I can tell from https://www.terraform.io/docs/providers/aws/ and my own experience with Terraform, `~/.aws/config` is still not honored.
Any updates on that?
It would be really cool for bigger terraform projects to not rely on a `provider "aws"` block but instead use user specific configuration for the default region.

**Comment by pgporada** [comment]
@HontoNoRoger I'm working on a PR for this atm.
