### ISSUE TITLE
Mixing variable definition and specification is order specific

### ISSUE THREAD

**Issue by darrensony** [hashicorp/terraform#5144]
From: https://www.terraform.io/docs/configuration/load.html

<blockquote>
The order of variables, resources, etc. defined within the configuration doesn't matter. Terraform configurations are declarative, so references to other resources and variables do not depend on the order they're defined.
</blockquote>

However, it appears that a empty (forward) declaration that occurs after a value declaration unsets the value.

To wit, this works:

````
variable "test" {}
variable "test" { default = "5" }
````

But swap the order, and it queries for a value for "test":

````
variable "test" { default = "5" }
variable "test" {}
````

Expected Behaviour: A late forward declaration should be silently ignored if there is already a value set for that variable in the symbol table.

**Comment by mitchellh** [comment]
The real validation here is that a variable should only be allowed to be defined once. Fixed in referenced PR.
