### ISSUE TITLE
terraform managed chef environment file Error - cookbook_constraints: should be a map

### ISSUE THREAD

**Issue by anshulshrivastava** [hashicorp/terraform#5148]
I tried several ways of writing chef_environment resource by using chef provider. But getting constant error - `chef_environment.example: cookbook_constraints: should be a map`.

my code is looks like - 
```
variable "cookbooks" {
  type = "map"
  default = {
    "role_cb" = "= 0.0.1"
  }
}

resource "chef_environment" "example" {
    name = "example"
    description = "Managed by Terraform"
    override_attributes_json = <<EOF
{
   "override_attributes":{
     "include_something": true,
     "environment_tag": "example",
     "tz": "UTC"
   }
}
EOF

    cookbook_constraints = "${lookup(var.cookbooks, "role_cb")}"

}
```

I have one more question related to reading a file and pass its content on default_attributes_json attribute - 
`    default_attributes_json = "${file("default_attributes.json")}" `

This doesn't work too.

**Comment by jen20** [comment]
Hi @anshulshrivastava! Thanks for opening an issue.

`cookbook_constraints` does need to be a map; it maps cookbook names to the version constraint that should apply. I'm not particularly familiar with the chef resources so it's not entirely clear what your expectation is here, but from reviewing the provider code and docs I'd expect that to look something like:

```tf
resource "chef_environment" "example" {
    name = "example"
    // ... other arguments
    cookbook_constraints {
         "some cookbook name" = "${lookup(var.cookbooks, "role_cb")}"
    }
}
```

With regards to the file interpolation: is there an error message? The interpolation syntax looks correct to me.

**Comment by anshulshrivastava** [comment]
@jen20 Thanks for your reply, 
``` cookbook_constraints {
         "some cookbook name" = "${lookup(var.cookbooks, "role_cb")}"
    }```

worked for me. And I am not getting any errors on file interpolation. 
Again, Thank you, this chef provider feature resolves so much complexity in our infrastructure management.
