### ISSUE TITLE
CloudWatch Logs metric filters

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#5153]
For deriving metrics from logs http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CountingLogEventsExample.html

I won't have time in the immediate future but when I do I'll contribute this if no one gets to it first!

**Comment by dgarlitt** [comment]
+1

**Comment by radeksimko** [comment]
FYI: WIP in https://github.com/hashicorp/terraform/pull/5444

@dgarlitt I see you started working on it too in https://github.com/dgarlitt/terraform/commit/e48dc4ee4dc031238374df37824c4939980a625a

I will have a look to see if I haven't missed anything and I'd be more than happy for you to review & test my PR.

**Comment by dgarlitt** [comment]
@radeksimko I noticed that you had a pull request after I pushed that commit on my fork, so I stopped my work. I'd be happy to take a look at your PR when it's complete, I've already looked it over once and you have been very thorough.

**Comment by radeksimko** [comment]
https://github.com/hashicorp/terraform/pull/5444 was merged a week ago.

CloudWatch Metric Filters are part of the latest release.
https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_metric_filter.html
