### ISSUE TITLE
unsupported key type "OPENSSH PRIVATE KEY"

### ISSUE THREAD

**Issue by brainsik** [hashicorp/terraform#5156]
Remote execution fails if you have a "new-format private key". This means you're not able to protect your private key with a KDF, which is a Good Thing to do.

Output received:

```
Error applying plan:

1 error(s) occurred:

* Failed to parse key file "[XXX PRIVATE KEY DATA XXX]": ssh: unsupported key type "OPENSSH PRIVATE KEY"
```

The OpenSSH man page section about KDF support:

```
     -a rounds
             When saving a new-format private key (i.e. an ed25519 key or any
             SSH protocol 2 key when the -o flag is set), this option speci-
             fies the number of KDF (key derivation function) rounds used.
             Higher numbers result in slower passphrase verification and
             increased resistance to brute-force password cracking (should the
             keys be stolen).
```

**Comment by phinze** [comment]
Hi @brainsik - this is a good idea, but I'm not sure if [`crypto/ssh`](https://godoc.org/golang.org/x/crypto/ssh) supports it.

If we can figure out how to make this happen in Go - happy to add it as a feature!

**Comment by vincecima** [comment]
Any update on Go's underlying library updating?

**Comment by passcod** [comment]
It looks like crypto/ssh has support for these keys: https://github.com/golang/crypto/blob/master/ssh/testdata/keys.go#L43-L50

**Comment by stack72** [comment]
Closed via #9661

**Comment by passcod** [comment]
This should be reopened given the change was reverted.

**Comment by mkb** [comment]
Note you can work around this by setting `agent = true` in the `connection` block.
