### ISSUE TITLE
Add function to truncate string

### ISSUE THREAD

**Issue by joshuajabbour** [hashicorp/terraform#5157]
It would be helpful to be able to truncate strings, because some providers limit the length of identifiers and such. A new built-in function like `truncate(string, length)` would help users solve this problem.

**Comment by billf** [comment]
Agree this would be useful.

if anyone finds themselves on this issue stuck until it is added, you can use the `replace()` function to work around it, e.g. `${replace(var.foo, "/(.{0,10})(.*)/", "$1")}`

**Comment by joshuajabbour** [comment]
Ah smart; hadn't noticed replace allowed regex...

**Comment by spanktar** [comment]
this seems like an oversight in the interpolations toolbox.  Yes we can hack around it, but it should really be there.

**Comment by nathanielks** [comment]
More concisely than replace + regex is the `substr` function:

```
${substr(var.some_string, 0, 10)}"
```

**Comment by steveh** [comment]
Looks like that was added March this year: https://github.com/hashicorp/terraform/pull/12870

So, can probably close this now.

**Comment by joshuajabbour** [comment]
Excellent. The new `substr` function solves this.

**Comment by yermulnik** [comment]
Apologies for posting to closed issue, but I've faced that `substr()` don't accept input if it's shorter than `offset+length`: `substr: 'offset + length' cannot be larger than the length of the string in`. So I had to google around and found solution in this [post](https://groups.google.com/d/msg/terraform-tool/hhC5P4eIcVU/rdWiVfRvLgAJ): `${format("%.14s", var.project_name)}`

**Comment by threemachines** [comment]
We ran into the ElastiCache case as part of a module, where the expected name length was unpredictable, but we found a different solution: we substr the entire string if it's not too long. I suppose it's a matter of opinion if that's better or hackier than a hypothetical ternary 😅

`replication_group_id = "${substr("${var.cluster_name}", 0, min(length("${var.cluster_name}"), 20))}"`

Just in case it helps anybody else.
