### ISSUE TITLE
Timeout on destroying rds with skip_final_snapshot = false

### ISSUE THREAD

**Issue by kszarlej** [hashicorp/terraform#5161]
With relatively big RDS instances the timeout of 40 minutes is not enough for destroying when skip_final_snapshot is set to false. 

I have RDS 800gb in size with skip_final_snapshot = false - when I try to delete this instance using terraform I am hitting the 40 minute timeout when terraform waits for state change. It is probably caused by long running snapshot creation process - after terraform quits with 

> aws_db_instance.myrds: Destroying...
> Error applying plan:
> 
> 1 error(s) occurred:
> - aws_db_instance.myrds: timeout while waiting for state to become ''

I logged into console, and saw that snapshot progress is 10% and is still being created.

Is it possible to change terraform behavior so it will: (just my proposals)

a) on deleting if timeout occurs mark in tfstate that the snapshot is not created yet, inform user that terraform will try to delete it on next run and exit. On next terraform apply check if snapshot is already created, and if snapshot is present delete rds instance without making snapshot this time. 
b) don't count time spent in waiting for snapshot just wait for it indefinitely, or use different timeout for snapshot creation
c) increase 40m timeout dramatically?
d) some other solution that I can't think of now

cheers  guys

**Comment by catsby** [comment]
Hello – We've since added a `Timeout` feature here, supported by `aws_db_instance`, that let's you customize the timeout for each create, update, or delete action of an individual `aws_db_instance`:

- https://www.terraform.io/docs/providers/aws/r/db_instance.html#timeouts
