### ISSUE TITLE
Adding multiple resources at once causes Google API to timeout and leaves terraform state inconsistent with Google

### ISSUE THREAD

**Issue by hjfbynara** [hashicorp/terraform#5163]
I've seen this with various types of resources but can pretty much reproduce it consistently with the cloudsql resource.  If I recreate 4-5 databases on the same cloudsql instance at once - invariably terraform apply will return the following error for one of the databases:

Error applying plan:
1 error(s) occurred:
- google_sql_database.db02: Error, failed to insert database db02 into instance mysql01: googleapi: Error 503: Service temporarily unavailable., serverException

If you login to the Google console you see the database did get created but terraform does not know about it due to the time out. 

To recover I need to manually delete the databases using the Google console for those databases that terraform does not know about.  Rerun plan to get new plan and then rerun apply with the new plan.

While I understand this is not specifically an issue with Terraform, since it was the Google API call that timed out, but maybe there should be better error recovery or a retry or a more delay added to API calls.  

Not sure if Google has a way of querying the status of an API call, especially for longer running API requests  (Pretty sure Amazon AWS has this capability).  If it does then the terraform Google provider should use that method - submit API call (don't wait around) and then go into a status check loop (with a count or timeout).  Return good when status says complete or fail if failed or timed out.

If that is not how Google APIs work,  then a reasonable workaround is to put longer delays for certain resource operations.

NOTE: this will be more problematic as you add additional features to the cloudsql capabilities as some changes require cloudsql instance restarts before proceeding - which will likely exasperate these types of things.

**Comment by lwander** [comment]
What happens when you call `$ terraform plan` after the creation fails? What should happen is terraform will read the server state, see that every sql instance is accounted for, and you should be fine.

We do query the status of long running API calls with [this](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/compute_operation.go), so what you're seeing is a failure of the API.

**Comment by hjfbynara** [comment]
Sorry for the long delay - had to finish something before I could attempt a
test of what you asked.

1. Ran plan to create a new SQL instance and 4 databases at same time.
Received following error:

google_sql_database_instance.mysql: Creation complete
google_sql_database.thurloe: Creating...
  instance:  "" => "testinstance"
  name:      "" => "thurloe"
  self_link: "" => "<computed>"
google_sql_database.cromwell: Creating...
  instance:  "" => "testinstance"
  name:      "" => "cromwell"
  self_link: "" => "<computed>"
google_sql_database.agora: Creating...
  instance:  "" => "testinstance"
  name:      "" => "agora"
  self_link: "" => "<computed>"
google_sql_database.rawls: Creating...
  instance:  "" => "testinstance"
  name:      "" => "rawls"
  self_link: "" => "<computed>"
google_sql_database.thurloe: Creation complete
google_sql_database.agora: Creation complete
Error applying plan:

2 error(s) occurred:

* google_sql_database.rawls: Error, failed to insert database rawls into
instance testinstance: googleapi: Error 503: Service temporarily
unavailable., serverException
* google_sql_database.cromwell: Error, failed to insert database cromwell
into instance testinstance: googleapi: Error 503: Service temporarily
unavailable., serverException

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

2.

**Comment by hjfbynara** [comment]
Sorry hit some odd key that caused message to be sent - grr...

Sorry for the long delay - had to finish something before I could attempt a
test of what you asked.

1. Ran plan to create a new SQL instance and 4 databases at same time.
Received following error:

google_sql_database_instance.mysql: Creation complete
google_sql_database.thurloe: Creating...
  instance:  "" => "testinstance"
  name:      "" => "thurloe"
  self_link: "" => "<computed>"
google_sql_database.cromwell: Creating...
  instance:  "" => "testinstance"
  name:      "" => "cromwell"
  self_link: "" => "<computed>"
google_sql_database.agora: Creating...
  instance:  "" => "testinstance"
  name:      "" => "agora"
  self_link: "" => "<computed>"
google_sql_database.rawls: Creating...
  instance:  "" => "testinstance"
  name:      "" => "rawls"
  self_link: "" => "<computed>"
google_sql_database.thurloe: Creation complete
google_sql_database.agora: Creation complete
Error applying plan:

2 error(s) occurred:

* google_sql_database.rawls: Error, failed to insert database rawls into
instance testinstance: googleapi: Error 503: Service temporarily
unavailable., serverException
* google_sql_database.cromwell: Error, failed to insert database cromwell
into instance testinstance: googleapi: Error 503: Service temporarily
unavailable., serverException

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

2. Going into Google console I see all dbs were created

information_schema utf8 utf8_general_ci System
agora utf8 utf8_general_ci User
cromwell utf8 utf8_general_ci User
mysql utf8 utf8_general_ci System
performance_schema utf8 utf8_general_ci System
rawls utf8 utf8_general_ci User
thurloe utf8 utf8_general_ci User


3. If I re-run plan again - terraform says it needs to create two databases

+ google_sql_database.cromwell
    instance:  "" => "testinstance"
    name:      "" => "cromwell"
    self_link: "" => "<computed>"

+ google_sql_database.rawls
    instance:  "" => "testinstance"
    name:      "" => "rawls"
    self_link: "" => "<computed>"


Plan: 2 to add, 0 to change, 0 to destroy.

4. If I attempt to apply plan it complains that databases exist

google_sql_database.rawls: Creating...
  instance:  "" => "testinstance"
  name:      "" => "rawls"
  self_link: "" => "<computed>"
google_sql_database.cromwell: Creating...
  instance:  "" => "testinstance"
  name:      "" => "cromwell"
  self_link: "" => "<computed>"
Error applying plan:

2 error(s) occurred:

* google_sql_database.cromwell: Error, failed to insert database cromwell
into instance testinstance: googleapi: Error 503: Service temporarily
unavailable., serverException
* google_sql_database.rawls: Error, failure waiting for insertion of rawls
into testinstance: speckle::MySQL exception: mysql_query Can't create
database 'rawls'; database exists


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

So the only way to get around this is to delete the two databases in Google
console and re-run plan/apply.

  -Henry

**Comment by lwander** [comment]
Looks like this is partially fixed by #5231, but that's only a temporary workaround.
