### ISSUE TITLE
terraform destroy -input=false not working

### ISSUE THREAD

**Issue by cfortier2** [hashicorp/terraform#517]
I was writing a rake task to automate my terraforming but the `-input=false` seems to be ignored:

![image](https://cloud.githubusercontent.com/assets/2601345/4817300/6605165c-5ee7-11e4-9378-57e44c6041a0.png)

**Comment by mitchellh** [comment]
@gregeinfrank is correct. This is only for asking for input. I'll add a force flag.

**Comment by jalateras** [comment]
It no one is looking into this I can have a look at it.

**Comment by phinze** [comment]
Actually `terraform destroy` gained a `-force` flag some time ago.

Closing this - @jalateras feel free to follow up if there's still some other behavior you'd like to see here.

**Comment by jalateras** [comment]
@phinze cool. Just looking at helping out with some open issues.
