### ISSUE TITLE
openstack_networking_port_v2 creating a port on a network from another tenant

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#5171]
In my OS setup, we have multiple tenants that all share the same network.

I am able to create a network port in my tenant just fine: 

`> neutron port-create --name foo SharedNetwork`

But when I try to create it via terraform: 

```
resource "openstack_networking_port_v2" "foo" {
  name = "foo"
  network_id = "29e67a54-76dd-4626-b7cb-64e7c2bdaefa"
  admin_state_up = "true"
}
```

Neutron responds with "NetworkNotFound".  Presumably because this network_id is defined in another tenant.  So then I put in that tenant_id, but then I get a 400:

`{"NeutronError": "Specifying 'tenant_id' other than authenticated tenant in request requires admin privileges"}`

What is terraform doing differently than neutron?

**Comment by jtopjian** [comment]
Very interesting and a good question. I'll look into this as soon as I can.

**Comment by matthughes** [comment]
Here's a bit more detail:

```
> neutron port-create --name foo SharedNetwork
# first it looks up the network id for SharedNetwork
# Then it just posts the following
POST /v2.0/ports.json -d '{"port": {"network_id": "29f67a54-76dd-4626-b7cb-64e7c2bdaefa", "name": "foo", "admin_state_up": true}}'
```

Compared with terraform 0.6.11
```
2016/02/17 15:02:13 [DEBUG] terraform-provider-openstack: 2016/02/17 15:02:13 [DEBUG] Create Options: ports.CreateOpts{NetworkID:"29f67a54-76dd-4626-b7cb-64e7c2bdaefa", Name:"foo", AdminStateUp:(*bool)(0xc8204386e0), MACAddress:"", FixedIPs:interface {}(nil), DeviceID:"", DeviceOwner:"", TenantID:""}
```

Since TF log doesn't actually show me the real POST, I can't tell what is being sent over the wire.  I do see that it is posting to:

/v2.0/ports, not /v2.0/ports.json.  No idea if that matters.

**Comment by jtopjian** [comment]
Hi there,

I'm starting to take a look at this and was wondering how SharedNetwork was created? Did you modify the Neutron policy to allow non-admin tenants to create shared networks? Or is SharedNetwork a network created by the admin with the `shared` flag set?

Thanks,
Joe

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
