### ISSUE TITLE
plan crashes when count is set using self in aws_instance 

### ISSUE THREAD

**Issue by brainsik** [hashicorp/terraform#5174]
* OS X 10.11.3
* Terraform version: 0.6.11  3590cfadb09ba67bdefe204fb454fdb2a6878dff
* [crash.log](https://gist.github.com/brainsik/3b7c2a93c40cfb988b2c)

----

To reproduce, create a single `.tf` file with the following:
```hcl
resource "aws_instance" "web" {
    count = "${self.whatever}"
}
```

Run `terraform plan`.

**Comment by phinze** [comment]
Thanks for the report, @brainsik - we'll get this fixed up.
