### ISSUE TITLE
Support for CloudWatch Events

### ISSUE THREAD

**Issue by muikrad** [hashicorp/terraform#5175]
AWS recently released CloudWatch Events.

http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/Welcome.html

Now that VPC is supported in AWS Lambda functions, I assume a lot of people are starting to ditch their schedule servers (such as chronos) in favor of lambda functions tied to cron-based AWS events. They will want to be able to create a scheduled event and create an association between it and their lambda functions.

**Comment by stack72** [comment]
Hi @muikrad,

This will be in terraform 0.6.12 as it was merged in this PR #4986 

Paul
