### ISSUE TITLE
provider/aws: Dynamically attached EBS volumes cause Terraform to destroy/create instances

### ISSUE THREAD

**Issue by SpencerBrown** [hashicorp/terraform#5181]
Using Terraform 0.6.11 to provision a Kubernetes cluster. 

We deploy pods that have AWS EBS volumes. Kubernetes dynamically attaches the EBS volume to the node on which it deploys the pod, as it should in its role as a cluster container manager.

If we run any `terraform plan` against the cluster while one of these pods is running, Terraform sees the dynamically attached EBS volume, notices it was not attached in its state file, and decides it needs to __destroy and recreate the AWS instance__. 

Clearly this is unacceptable. Terraform needs to not assume that it must statically attach all EBS volumes to AWS instances.

Perhaps, during refresh, it could not mark as a difference that (external to it) an EBS volume that it knows about has been attached to an instance?

**Comment by phinze** [comment]
Hi @SpencerBrown - thanks for the report.

It seems like Terraform's drift detection is getting in the way of your use case. Let's see if we can figure out a way through this.

I'm guessing you have `ebs_block_device {}` stanzas in your `aws_instance` declaration? As soon as one of those shows up in the config, Terraform's drift detection will attempt to resolve the set of block devices attached in AWS with the set of block devices specified in the config.

There are two ways to work around this:

 * Use `ignore_changes = ["ebs_block_device"]` to prevent Terraform from triggering a diff on the changes you expect to make.
 * Refactor the config to use `resource_aws_ebs_volume` and `resource_aws_volume_attachment`, which are purely additive resources and so won't trigger the drift detection.

Let me know if I'm correct about that `ebs_block_device {}` guess and whether all this makes sense to you! :+1:

**Comment by SpencerBrown** [comment]
Yes your guess was correct, @phinze. 

I went with option #2 and it fixed my issue, so I'm closing this issue.

However I need to open another one now that I discovered in testing this one.

**Comment by phinze** [comment]
Sounds good - glad we figured out a way to unblock you. :+1:
