### ISSUE TITLE
plan with target does not output correct plan file

### ISSUE THREAD

**Issue by wsh** [hashicorp/terraform#5183]
Hi folks--perhaps I've just done it wrong (tm) but something really odd (and terrifying) happened tonight when I tried to execute a simple plan to add an SNS topic. Terraform thought my tfstate was out of sync with a few nodes in a different region. Thinking it was okay to postpone fixing that, I ran

    terraform plan -target=aws_sns_topic.enrollments -out sns.plan

and got back

```
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: sns.plan

+ aws_sns_topic.enrollments
    arn:    "" => "<computed>"
    name:   "" => "syllego-enrollments"
    policy: "" => "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

Then when I tried to run that plan

    terraform apply sns.plan

```
aws_instance.syllego-cassandra-node-west.2: Destroying...
aws_instance.syllego-cassandra-node-west.3: Destroying...
aws_instance.syllego-cassandra-node-west.0: Destroying...
aws_instance.syllego-cassandra-node-west.1: Destroying...
aws_sns_topic.enrollments: Creating...
  arn:    "" => "<computed>"
  name:   "" => "syllego-enrollments"
  policy: "" => "<computed>"
aws_sns_topic.enrollments: Creation complete
^CInterrupt received. Gracefully shutting down...
^CTwo interrupts received. Exiting immediately. Note that data
loss may have occurred.
```

(The interrupts were me frantically going "oh shit!" and trying to stop things from going down.) Needless to say, this is **not** what I expected. This is exactly how I've executed plans previously, and it meshes with [the docs](https://www.terraform.io/docs/commands/apply.html) so far as I can tell. Again, if I'm doing it wrong, please tell me--but if not, holy shit. (I just lost an hour, for sure.) I'm running v0.6.11.

**Addendum**: I decided to take a look at the plan file. Not sure why I didn't look at it sooner. Sure enough, it includes a bunch of EC2-related stuff.

**Comment by mitchellh** [comment]
Howdy! This is awful, I'm so sorry.

There are quite a lot of protections in place for this to not happen so my occam's razor is telling me that as you said on Twitter, the plan being saved vs the plan being shown is likely somehow different or something thereabouts.

Let's get to the bottom of this. 

Can you reproduce this in any way (not on your real infrastructure). If so, can you give us the configs to setup the cluster, then the config we'd plan/apply to repro this? We can help minimize it from there but that will be key to getting this to work.

Thanks!

**Comment by wsh** [comment]
I'll certainly do my best. :smile: Just need to get my real infra. back up and running asap.

**Comment by wsh** [comment]
Okay, I can repro the plan command with that target producing a .plan file that contains a lot of *other* stuff in it. If you'd like, I can try to set up another AWS account and apply it, but I'm still working on restoring my cluster so that could take a little while. Otherwise, how would you like me to send you the tfstate etc.? Sorry if I'm missing something obvious--I'm a GitHub novice (I know, my employer, the irony).

**Comment by phinze** [comment]
Hi @wsh, digging into this now - let me do some tests on this side just based on your scenario description, and I'll follow up if there are any other details that would be helpful for repro. I'll update you as soon as I know more.

**Comment by wsh** [comment]
Sure thing--I don't want to delay you, but just so you know I examined the
generated plan file and saw a bunch of references to resources that
definitely weren't in my target (or displayed in the output of the plan
command). Perhaps that's intentional but it seems really suspect. Please
let me know how I can help if I can in any way.

On Thursday, February 18, 2016, Paul Hinze <notifications@github.com> wrote:

> Hi @wsh <https://github.com/wsh>, digging into this now - let me do some
> tests on this side just based on your scenario description, and I'll follow
> up if there are any other details that would be helpful for repro. I'll
> update you as soon as I know more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/terraform/issues/5183#issuecomment-185782473>
> .
>


-- 
__________________
Will Hayworth
(914) 584-5372
willhayworth.com

**Comment by phinze** [comment]
Ah sure - I can see why that would seem fishy, but it's expected. The plan file encodes a full State (Terraform's view of the world) so that when Terraform executes it can verify that the infrastructure hasn't drifted before it does anything. This is a separate data structure from the Diff, which encodes the actions the Plan is actually supposed to perform. The `-target` parameter scopes down the Diff, but not the State.

Quick question as I'm fiddling with test cases over here:

>  Terraform thought my tfstate was out of sync with a few nodes in a different region. 

Did your full unscoped `terraform plan` include removals for `aws_instance.syllego-cassandra-node-west` instances?

**Comment by phinze** [comment]
Also: did any of the resources being destroyed fall inside a module - or was everything in the root module?

**Comment by phinze** [comment]
My original theory was that there's some sort of orphan resource problem with plan files, but I ran through these steps and verified everything was working properly in a flat module topology:

https://gist.github.com/phinze/5ada49eb304f76e31d74

(Hence my follow up questions about modules.)

It's looking like more information about your state & config would be useful - generally it's easiest to toss these things up as a [GitHub Gist](https://gist.github.com) or equivalent.

For the State, you can take a scan through the `tfstate` contents for anything sensitive / in your environment and redact as necessary.

For the Config, if it's relatively small you can paste it into a multi-file Gist - if it's more complex, pushing a repo works well. Again you can obfuscate or redact anything sensitive.

We'll get this figured out!

**Comment by wsh** [comment]
The full unscoped plan did include removals (each resource had a +/- next to it in the output), duly noted re. the plan file, everything is in the root module, and I'll get my stuff pushed for you to look at ASAP.

**Comment by phinze** [comment]
(No rush from my side, just letting you know I'm ready and willing to help figure this out as soon as you post config/state details.)

**Comment by wsh** [comment]
Okay, all pushed. :smile: [This private repo](https://github.com/wsh/terraform-bug-5183), to which you and @mitchellh both have access, contains every Terraform file in my repo and my full `tfstate`. Running ```terraform apply sns.plan``` on the file in that repo will produce this output:

```
aws_sns_topic.enrollments: Creating...
  arn:    "" => "<computed>"
  name:   "" => "syllego-enrollments"
  policy: "" => "<computed>"
aws_instance.syllego-cassandra-node-west.2: Destroying...
aws_instance.syllego-cassandra-node-west.0: Destroying...
aws_instance.syllego-cassandra-node-west.1: Destroying...
aws_instance.syllego-cassandra-node-west.3: Destroying...
```

But `terraform plan -target=aws_sns_topic.enrollments -out sns.plan` produced:

```
Path: sns.plan

+ aws_sns_topic.enrollments
    arn:    "" => "<computed>"
    name:   "" => "syllego-enrollments"
    policy: "" => "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```
(I've been working with a read-only API key for obvious reasons. :smile: )

**Comment by wsh** [comment]
Something I just noticed, by the way: if I do `terraform refresh` **before** I run the plan, it doesn't try to destroy the instances.

**Comment by mitchellh** [comment]
That is a strong hint. 

My current thought (not proven at all) or hint to @phinze: What if "apply" with a plan is doing a refresh first, which is creating a plan internally to delete those nodes, and somehow those aren't diff checking properly to be rejected when compared to the given plan?

**Comment by phinze** [comment]
Great, thanks for this. I see the problem right away. Your state is carrying "tainted" resources. If you check the output of `terraform show` you'll see these resources listed: 

![zsh](https://cloud.githubusercontent.com/assets/37534/13161609/788933da-d664-11e5-9fd8-0223d3f2ad17.png)

These are resources that had provisioners fail for whatever reason. Terraform marks these resources as invalid and schedules them for clean up in a subsequent `terraform apply`.

It seems that the target scoping is not properly pulling these tainted resources out of consideration in a plan file scenario, so the "clean up" is happening unexpectedly.

Using this information I should be able to stitch together a solid repro case. I'll follow up once I have it.

**Comment by wsh** [comment]
Bingo, that makes sense--the provisioners for those nodes fail because of a bug in AWS OpsWorks. :smile: (It's regional.)

**Comment by wsh** [comment]
Hey, any update on this? It would suck if someone else hit it.

**Comment by phinze** [comment]
Hi @wsh - thanks for the ping! I got pulled away last week. The severity of the bug is reduced slightly by the fact that the instances that end up being destroyed were tainted (already scheduled for destruction). Only slightly though, since the plan/apply contract is the most important contract in Terraform.

( Related here is getting tainted destroys to show up in the plan - that would have made the nature of this bug clear much more quickly. #4156 )

### Repro steps

```tf
# main.tf step 1
resource "template_file" "foo" { }
```
```bash
❯ terraform apply
❯ terraform taint template_file.foo
```
```tf
# main.tf step 2
resource "template_file" "foo" { }
resource "template_file" "bar" { }
```
```bash
# Unscoped plan
❯ terraform plan
+ template_file.bar
    rendered: "" => "<computed>"

-/+ template_file.foo
    rendered: "" => "<computed>"
```
```bash
# Scoped plan
❯ terraform plan -target template_file.bar -out bar.tfplan
Path: bar.out

+ template_file.bar
    rendered: "" => "<computed>"
```

### Expected behavior
```
❯ terraform apply bar.tfplan
template_file.bar: Creating...
  rendered: "" => "<computed>"
template_file.bar: Creation complete
```

### Observed behavior
```
❯ terraform apply bar.tfplan
template_file.foo: Destroying...
template_file.bar: Creating...
  rendered: "" => "<computed>"
template_file.bar: Creation complete
```

**Comment by wsh** [comment]
What you said about mitigation is true, but until #4820 is implemented or something else is provided it's not clear to me how I'd succcessfully untaint my resources in the event of provisioner failure. I guess the solution would be just to rerun the command without the provisioner so that it's successful, but it's kind of annoying.

**Comment by phinze** [comment]
Alrighty, with #5516 running through my repro case yields the expected behavior. Ping @jen20 for review when you get the chance.
