### ISSUE TITLE
Error while applying an update

### ISSUE THREAD

**Issue by heckdevice** [hashicorp/terraform#5188]
Error when scaling-up / adding new resource to an existing terraform inventory.

Basically was increasing the count of few resources and it gives the following error.

* openstack_compute_instance_v2.control.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* openstack_compute_instance_v2.worker.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.

**Comment by phinze** [comment]
Hi @heckdevice, we can definitely help look into this, can you share a bit more detail about the config / state when you encountered this error.

If we can come up with steps to reproduce the error, we can figure out what the bug is and get it fixed! :+1:

**Comment by heckdevice** [comment]
Basically was trying to update a deployment of two nodes to three nodes and each node have a floating ip association. This is on a in-house OpenStack setup.

On applying the update the above error comes.

**Comment by jtopjian** [comment]
@heckdevice Are you able to post the Terraform configuration you're using to trigger this?

Off the top of my head, if you're using `count` and something like `element`, this may be a result of #3449.

**Comment by heckdevice** [comment]
@jtopjian i am relying on the count for increasing the count but have no volume mapping as its managed by nova and not cinder in my openstack. I however and associating floating ips to each instance.

[dc1-base.txt](https://github.com/hashicorp/terraform/files/174521/dc1-base.txt)

on update i am simply changing the datanode_count and that's where i see the issue.

**Comment by jtopjian** [comment]
OK, sounds very similar to #3662 (which is another symptom of #3449). Can you confirm if #3662 looks more similar to what you're seeing? If not, I'll try to reproduce this issue on my end.

**Comment by heckdevice** [comment]
@jtopjian Looking into #3449 it seems more like #3885

**Comment by jtopjian** [comment]
OK, good to know. I think it's safe to say the problem you're seeing is a bug in core. Someone in #3449 mentioned a workaround -- maybe that can get things sorted for the time being?

Let me know your thoughts. If you're getting confident that the problem you're seeing can be compared to one of the other issues that point to #3449, I'll close this issue in favor of #3449.

**Comment by heckdevice** [comment]
@jtopjian Let's close for now in fav of #3449. Will check back on the workaround if it actually works. Thanks.

**Comment by jtopjian** [comment]
@heckdevice okie dokie
