### ISSUE TITLE
Change of associate_public_ip_address is not picked up by terraform

### ISSUE THREAD

**Issue by piotrgo** [hashicorp/terraform#5189]
I have created an ec2 instance with
``` associate_public_ip_address = true ```

After changing that setting to 
``` associate_public_ip_address = false ``` 
terraform doesn't pick up any changes (ie. plan show's nothing to change)

If that's any interest they are being created in non default VPC.
Cheers,
Piotr

**Comment by stack72** [comment]
Hi @piotrgo, apologies for the wait here. I have just had a look at this. This cannot really be done. Once an instance has been created with `associate_public_ip_address = true`, it cannot be changed to `associate_public_ip_address = false` unless the instance would be recreated. The only real thing to do here would be to force a new resource if that value changed

Does this seem reasonable to you?

**Comment by piotrgo** [comment]
Hello,
no worries. That's what I would actually expect from terraform - to force a new resource in such situation.

Cheers
Piotr

**Comment by stack72** [comment]
Hi @piotrgo,

so I started looking at this and terraform already works in this way. When i run an instance and then change that value, I see the following:

```

-/+ aws_instance.foo
    ami:                         "ami-c5eabbf5" => "ami-c5eabbf5"
    associate_public_ip_address: "true" => "0" (forces new resource)
    availability_zone:           "us-west-2b" => "<computed>"
    ebs_block_device.#:          "0" => "<computed>"
    ephemeral_block_device.#:    "0" => "<computed>"
    instance_state:              "running" => "<computed>"
    instance_type:               "t2.micro" => "t2.micro"
    key_name:                    "" => "<computed>"
    placement_group:             "" => "<computed>"
    private_dns:                 "ip-10-1-1-42.us-west-2.compute.internal" => "<computed>"
    private_ip:                  "10.1.1.42" => "10.1.1.42"
    public_dns:                  "" => "<computed>"
    public_ip:                   "52.37.14.20" => "<computed>"
    root_block_device.#:         "1" => "<computed>"
    security_groups.#:           "0" => "<computed>"
    source_dest_check:           "true" => "1"
    subnet_id:                   "subnet-fce1e98b" => "subnet-fce1e98b"
    tenancy:                     "default" => "<computed>"
    vpc_security_group_ids.#:    "1" => "<computed>"
```

Can you tell me what version of TF you are using?

**Comment by piotrgo** [comment]
Hello @stack72 ,

I am using 0.6.11.

**Comment by stack72** [comment]
@piotrgo, can you post me the output of what you see when you change the value? (remove any secrets please)

**Comment by piotrgo** [comment]
Morning @stack72 , I've just created new dummy machine and it all works as expected and I can't reproduce the issue anymore. Maybe it was something between chair and keyboard. 
Thanks for your time.

**Comment by stack72** [comment]
@piotrgo great news - glad it works as expected. Let me know if there are any other issues
