### ISSUE TITLE
Terraform refresh failing to respect current state

### ISSUE THREAD

**Issue by ljsommer** [hashicorp/terraform#5199]
I have found myself in many situations where terraform apply will fail because x resource has y resource attached (why doesn't it just remove them in order of dependency and move on????????).
To remedy one such situation, I deleted the resource in question which was an AWS auto-scale group.

Now, no 'plan' or 'refresh' can succeed. Doing a terraform refresh will refresh state on a lot of resources and then hit the one I deleted:

```
`Error refreshing state: 2 error(s) occurred:

* aws_autoscaling_policy.ecs-cluster-up: Error retrieving scaling policies: ValidationError: Group ECS ASG vpc-* not found
    status code: 400, request id: 4b0f696e-d67f-11e5-b9f2-7bae58d5748a
* aws_autoscaling_policy.ecs-cluster-down: Error retrieving scaling policies: ValidationError: Group ECS ASG vpc-* not found
    status code: 400, request id: 4b1583c8-d67f-11e5-bdc7-3dfd695c0d7a`
```

**So my question is**\- TF is aware that the resource is not found, _is that not the actual real-world state_? Why would it not find that it is missing, note it as missing and needing repopulated as indicated by the tf files and do so?

Working with state in TF is one of the most frustrating things I've run into in some time.

**Comment by phinze** [comment]
Hi @ljsommer - sorry for the trouble here, and thank you for the report.

> Why would it not find that it is missing, note it as missing and needing repopulated as indicated by the tf files and do so?

This is indeed what it should be doing! This is a bug in the ECS cluster resource that we'll get fixed up. We do our best to catch "NotFound" style errors, but in certain cases like this one the upstream API returns a different class of error - like a `ValidationError` here - that we need to treat as not found as well.

To work around this, you can manually remove the `resources` entries for `aws_autoscaling_policy.ecs-cluster-up` and `aws_autoscaling_policy.ecs-cluster-down` in your `terraform.tfstate` JSON, which should unblock you.

**Comment by ljsommer** [comment]
Wonderful response thank you very much and apologies for the hyperbole in my post I had just accidentally deleted an entire environment  ;)

**Comment by gregorskii** [comment]
Hi I am seeing this same issue with Dynamo DDB tables.

```
❯ terraform refresh
module.ddb.aws_dynamodb_table.<TABLE>-dynamodb-table: Refreshing state... (ID: <TABLE>)
module.ddb.aws_dynamodb_table.<TABLE>-dynamodb-table: Refreshing state... (ID: <TABLE>)
Error refreshing state: 2 error(s) occurred:

* aws_dynamodb_table.<TABLE>-dynamodb-table: ResourceNotFoundException: Requested resource not found: Table: <TABLE> not found
	status code: 400, request id: 7A8D6S7A1HIQI0S1LM974M214VVV4KQNSO5AEMVJF66Q9ASUAAJG
* aws_dynamodb_table.<TABLE>-dynamodb-table: ResourceNotFoundException: Requested resource not found: Table: <TABLE> not found
	status code: 400, request id: K9J24K2HD8LQRR48P461PN3303VV4KQNSO5AEMVJF66Q9ASUAAJG
```

Thanks

**Comment by ckelner** [comment]
Seeing a similar issue with ASGs on 0.6.15:

```
Refreshing Terraform state prior to plan...
Error refreshing state: 2 error(s) occurred:

* aws_autoscaling_policy.astro_scale_up: Error retrieving scaling policies: ValidationError: Group astro-asg not found
    status code: 400, request id: 862c8809-1d16-11e6-b7a3-8991b77f141c
* aws_autoscaling_policy.astro_scale_down: Error retrieving scaling policies: ValidationError: Group astro-asg not found
    status code: 400, request id: 862d7209-1d16-11e6-b993-5190eb81096b
```

Thanks

**Comment by HenryTheHamster** [comment]
Yep, we're hitting the AutoScaling policy problem too...
```
* aws_autoscaling_policy.hobbit_scale_up: Error retrieving scaling policies: ValidationError: Group hobbits not found
	status code: 400, request id: d7da431e-47ef-11e6-aae3-8f0db5ac2042
* aws_autoscaling_policy.hobbit_scale_down: Error retrieving scaling policies: ValidationError: Group hobbits not found
	status code: 400, request id: d7dcb430-47ef-11e6-b81f-db72422c4b0a
```

**Comment by AMMullan** [comment]
Same as @HenryTheHamster - ASG policy causing problem on 0.6.16 :/

**Comment by tomdavidson** [comment]
confirm the same as HenryTheHamster and there is not 'aws_autoscaling_policy.ecs-cluster' in the state file.
