### ISSUE TITLE
IAM Policies: Unable to detect manual changes

### ISSUE THREAD

**Issue by jonapich** [hashicorp/terraform#5201]
IAM policies created with Terraform will not be able to detect when the said policy has changed in AWS.
1. Create/Apply an IAM policy with Terraform
2. Modify it manually using AWS's dashboard
3. Launch Terraform again, notice it doesn't detect the modification at all

Sounds like a lack of unit tests on that module?

**Comment by stack72** [comment]
@muikrad - not sure what you mean by lack of unit tests?

Can you give us a sample of what the terraform config looked like at the start and then post what changes were made?

**Comment by muikrad** [comment]
I mean, there should be a test that ensures that modifications to terraform-managed infrastructure outside of terraform is correctly detected and reverted. For instance, if you change the tag on an EC2 instance using the AWS dashboard and run terraform again, terraform will revert the tag to the old value. This is not happening with the IAM policy at all (changes are not detected).

**Comment by muikrad** [comment]
Here's a sample config for you to test:

```
resource "aws_iam_policy" "policy" {
  name = "test-terraform-bug"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:Describe*",
      "Resource": "*"
    }
  ]
}
EOF
}
```

Apply that, then go in AWS and change ec2:Describe* to ec2:*. Then run terraform again, it won't detect the change.

**Comment by jkinred** [comment]
I've also encountered this with `aws_iam_role` and have opened a WIP PR at #5299.

I haven't actually tested this with `aws_iam_policy` but I've included it in the WIP PR to express my intention to fix both resources.

@stack72 - Would really dig a review of my PR and some advice on writing tests. I'm a novice Go programmer and will work it out eventually but some advice would fast track the PR.

**Comment by stack72** [comment]
@jkinred - I have just had a look and made some comments on the PR - it's certainly on the right lines :)

**Comment by maxrothman** [comment]
What's the status of this and #5299? Would love to see this fixed.

**Comment by zerolaser** [comment]
I've also encountered this with aws_iam_group. I have added an exisiting aws policy to the group, wheni run terraform plan. it shows no changes.

**Comment by afaleti** [comment]
Was this ever resolved?
