### ISSUE TITLE
aws_network_interface diffs didn't match during apply when using ignore_changes lifecycle on private_ips

### ISSUE THREAD

**Issue by lussier** [hashicorp/terraform#5202]
Whenever I attach a lifecycle policy like this one

`lifecycle { "ignore_changes" = ["private_ips"] }`

to an aws_network_interface, the apply throws a _diffs didn't match during apply_ error for all the interfaces. I'm using Terraform v0.6.11.

As a workaround I create them without that lifecycle policy, and then reintroduce it after a first apply.

**Comment by phinze** [comment]
Hi @lussier - we believe this has been fixed on master with #4965 having landed. Do you have the ability to give master a shot and see if the problem still exists there?

**Comment by lussier** [comment]
Hi @phinze. I just retested the creation scenario with the master version without any problem. I confirm that the issue is fixed in master. Thanks a lot!
