### ISSUE TITLE
file function not finding files in modules

### ISSUE THREAD

**Issue by joseph-wortmann** [hashicorp/terraform#5213]
I have a module, where I'm loading user-data for a launch config like this:

user_data = "${file("mgt-user-data.sh")}"

The file "mgt-user-data.sh" is in the same directory as the .tf that calls it, and both are gotten during terraform get.

However, where planned the following error comes back:

  * file: open mgt-user-data.sh: no such file or directory in:

${file("mgt-user-data.sh")}

This works perfectly in non-module .tf that I have, but fails every time in a called module.

The file function should, IMHO, base relative path resolution on the path of the caller, but it does not appear to be doing that (otherwise it would find the file listed above).

**Comment by joseph-wortmann** [comment]
It also will not work with relative paths in the main .tf, UNLESS terraform is run within the .tf directory. if run from outside the directory, it will fail.

The only way the file function appears to behave reliably is if absolute paths are used.

**Comment by stack72** [comment]
Hi @joseph-wortmann,

Can you try this?

`user_data = "${file("${path.module}/mgt-user-data.sh")}"`

and see if that works for you?

Paul

**Comment by joseph-wortmann** [comment]
Thanks Paul,

That worked. Thank you.

However, that seems very non-intuitive. I think that relative paths should
do something like this automatically for users, or at the very least this
syntax should be added as an example to the documentation. My 2 cents.

Regards,

Joseph Wortmann
(205) 612-3826

**Comment by stack72** [comment]
@joseph-wortmann - glad this worked. I will leave this issue open and speak to some of the other contributors and get their thoughts

**Comment by phinze** [comment]
I just reviewed the docs around this and it's definitely confusing as is! Adding explicit mention of the way `path` is interpreted to the `file()` docs and will link back here.

**Comment by phinze** [comment]
Updated docs landed on the site! Let me know if there's anything further we can do to clarify the behavior, @joseph-wortmann. :+1:

**Comment by joseph-wortmann** [comment]
Thank you!

Regards,

Joseph Wortmann
(205) 612-3826

**Comment by Jazun713** [comment]
I had this same issue using the file provisioner.  Using $path.module does help resolve this.

**Comment by spacemudd** [comment]
Had the same issue involving:

```
provisioner "file" {
    source = "./install_docker.sh"
    destination = "/tmp/install_docker.sh"
    connection {
      type = "ssh",
      user = "root",
      private_key = "${file(var.ssh_private_key)}"
    }
  }
```

Worked as suggested by using `$path.module`:

```
provisioner "file" {
    source = "${path.module}/install_docker.sh"
```

**Comment by ltupin** [comment]
Can we consider it as "normal" or should we work on this "old" issue ? 
Maybe just missing documentation (or maybe I dont find it) ?

Involving filemd5 its same:
`etag   = "${filemd5("scripts/bootstrap_actions.sh")}"`

Resolved also by using `$path.module:`:
`etag   = "${filemd5("${path.module}/scripts/bootstrap_actions.sh")}"`

Thanks to @stack72 !
