### ISSUE TITLE
Terraform crashes when self.Name is used in module

### ISSUE THREAD

**Issue by simonrondelez** [hashicorp/terraform#5215]
Terraform crashes when self.Name is used as a parameter in a module.
See [stacktrace](https://files.zenhub.io/56c73f9716c1bcfd62940ca0).

**Comment by phinze** [comment]
Hi @simonrondelez thanks for the report - this is actually the same crash as #5174, so I'm going to merge this thread down with that one so they can be addressed together. :+1:
