### ISSUE TITLE
provider/aws: Add support for retention period for Kinesis streams

### ISSUE THREAD

**Issue by Bowbaq** [hashicorp/terraform#5219]
Kinesis streams retain data for 24 hours by default. This retention period can be increased up to 168 hours (7 days).

Relevant API calls:
- [IncreaseStreamRetentionPeriod](http://docs.aws.amazon.com/kinesis/latest/APIReference/API_IncreaseStreamRetentionPeriod.html)
- [DecreaseStreamRetentionPeriod](http://docs.aws.amazon.com/kinesis/latest/APIReference/API_DecreaseStreamRetentionPeriod.html)

**Comment by stack72** [comment]
Hi @Bowbaq - I am working on this right now for you

Paul

**Comment by Bowbaq** [comment]
Awesome, thanks!

**Comment by stack72** [comment]
Closed in #5223 :)
