### ISSUE TITLE
Prompt for confirmation after variable input

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#5224]
This flow should have the "yes" confirmation _after_ the variable inputs.

```
$ terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: us-east-1
```

**Comment by mitchellh** [comment]
I'm not particularly convinced the query order here matters and I sort of feel I'd want to know up front that I'm about to do a destructive operation. Why do you feel that it should ask that after going through the work of inputting auth information?

**Comment by mitchellh** [comment]
No response but I think we're good. :)
