### ISSUE TITLE
Manage infrastructure from behind a proxy

### ISSUE THREAD

**Issue by kief** [hashicorp/terraform#523]
I'm working in an office that only allows outbound http/s connections via a proxy. This currently prevents use with AWS provider, and I assume others as well. It would be useful to have a way to configure terraform (command line and/or config files) with the proxy details.

Thanks

**Comment by wkielas** [comment]
As a temporary workaround I use iptables + redsocks to proxy outgoing terraform traffic, but real proxy support would be much better.

**Comment by ipolyzos** [comment]
+1

**Comment by justnom** [comment]
This is already supported natively by the Golang `net/http` package which `aws-sdk-go` uses.

To set an HTTP proxy just set the either the `HTTP_PROXY` or `HTTPS_PROXY` environment variables.

On Windows:
`set HTTP_PROXY=<your proxy address here>`

On Mac/Linux:
`export HTTP_PROXY=http://<your proxy address here>`

Hope this helps :)

**Comment by phinze** [comment]
Yep @justnom is right - should be achievable via those environment variables.

**Comment by cricketlong** [comment]
+1

**Comment by spacemonkey** [comment]
+1

**Comment by Kurry** [comment]
@phinze 
This doesn't seem to be working in the newest version.

 I get this error:

```
localhost:terraform-example kurrytran$ terraform plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* RequestError: send request failed
caused by: Post https://iam.amazonaws.com/: EOF
localhost:terraform-example kurrytran$ which terraform
/usr/local/bin/terraform
localhost:terraform-example kurrytran$ terraform version
Terraform v0.6.14
```

With these proxies set:

```
http_proxy=
RSYNC_PROXY=
rsync_proxy=
HTTPS_PROXY=
https_proxy=
HTTP_PROXY=
```

**Comment by sbkumar007** [comment]
+1

**Comment by mikesimons** [comment]
I'm trying to inspect traffic coming from terraform-openstack-provider to debug some auth issues (using https://www.charlesproxy.com/) and it's totally ignoring the env vars. These requests are not showing up in Charles.

`env http_proxy=http://127.0.0.1:8888 HTTP_PROXY=http://127.0.0.1:8888 HTTPS_PROXY=http://127.0.0.1:8888 https_proxy=http://127.0.0.1:8888 terraform plan`

Grabbing the pid of a plugin process (8586 here) and inspecting the environment before it shuts down...

```
s> xargs -n 1 -0 < /proc/8586/environ | grep -i proxy
HTTPS_PROXY=http://127.0.0.1:8888
HTTP_PROXY=http://127.0.0.1:8888
http_proxy=http://127.0.0.1:8888
https_proxy=http://127.0.0.1:8888
```

So the plugin is getting the vars but they're not being used.

I think the problem (at least in the case of the openstack provider) is that you're [overriding the transport](https://github.com/hashicorp/terraform/blob/b204d35e1969ac95d3868c605f0bf3b11d5134ad/builtin/providers/openstack/config.go#L86) passed to gophercloud but not [setting Proxy from the env like the DefaultTransport does](https://github.com/golang/go/blob/605e751b53a8bec7d1f51b2ccc0093e063358dc6/src/net/http/transport.go#L39).

Each provider needs checking to ensure that it's either using the default transport or setting the proxy on its custom transport ([AWS for instance](https://github.com/hashicorp/terraform/blob/b204d35e1969ac95d3868c605f0bf3b11d5134ad/builtin/providers/aws/config.go#L157) uses go-cleanhttp which correctly sets proxies from env).

**Comment by pmithrandir** [comment]
Hello,

I'm using terraform behind a proxy, and I don't think it's working for openstack.
I get a time out each time I'm trying to reach my openstack platform, even if when using heat command it works.

Pierre

**Comment by pierrecarre** [comment]
+1

**Comment by danielcoman** [comment]
Hello,

I'm currently testing terraform and I'm also not able to get it working behind a corporate proxy with the openstack provider. 

Daniel 

+1

**Comment by TG-KK** [comment]
Not working with AWS provider too, even though variables are set

**Comment by kolly83** [comment]
Hello

Same here. Not working with AWS provider too, even though variables are set.

Although I was able to get it work once with the export proxy.

Any idea?

Thank you.
