### ISSUE TITLE
-/+ Google compute network forces new resource with no changes

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#5233]
With the addition of subnets (awesome btw) it has created an undesired backwards incompatibility with existing networks.    This should be either ignored or updated in existing networks.    The following was received from a terraform plan

```
-/+ google_compute_network.internal
    auto_create_subnetworks: "" => "0" (forces new resource)
    gateway_ipv4:            "10.60.0.1" => "<computed>"
    ipv4_range:              "10.60.0.0/16" => "10.60.0.0/16"
    name:                    "internal-network" => "internal-network"
```

Although this new auto_create_subnetworks is a new field, and it is in fact missing from legacy networks, it should not force a new resource or it will destroy existing networks.

**Comment by kendawg2** [comment]
following up with a bit more detail.    This is an existing legacy network.   The terraform code that created it is as follows:

resource "google_compute_network" "internal" {
    name = "internal-network"
    ipv4_range = "10.60.0.0/16"
    
}

What appears to happening is that the optional "auto_create_subnetworks" is being added, even though this should be detected as a legacy network.   It is setting it to the default value of "false" but in this case, it should definitely not be adding it.    This will effectively break all existing GCE infrastructure if indeed this forces a new resource (It will attempt to destroy the existing network which every server relies on) .  I believe the code reflects that element being added unconditionally but only forces it if it's a custom subnet network.  

I hope this helps.

**Comment by kendawg2** [comment]
I should mention it is version 0.6.12 and the commit that added GH-5130 is causing this issue.   A great new feature by the way.

**Comment by sl1pm4t** [comment]
Thanks for the info @kendawg2  - I didn't notice this issue until you tagged me, but I'll have a look.

**Comment by sl1pm4t** [comment]
I submitted a fix
