### ISSUE TITLE
aws_redshift_cluster resource should calculate value of cluster_type

### ISSUE THREAD

**Issue by bsiegel** [hashicorp/terraform#5235]
If the number_of_nodes is 1, the cluster_type should be `single-node`, otherwise it should be `multi-node`. Any combination that doesn’t follow that pattern is invalid according to the AWS API. The redshift_cluster resource should calculate the correct value of cluster_type rather than allowing the user to specify its value.

**Comment by stack72** [comment]
@bsiegel thanks for the request - just opened #5238 to deal with this issue

Paul

**Comment by stack72** [comment]
Hi @bsiegel - this has been merged now so I am going to go ahead and close this issue
