### ISSUE TITLE
Validation warning saying something will be an error in terraform 0.4

### ISSUE THREAD

**Issue by Jonty** [hashicorp/terraform#5243]
https://github.com/hashicorp/terraform/blob/11aa0cda5ae8883b8c9411b91f28ed6388dd82cd/terraform/eval_validate.go#L125

If I'm not mistaken, terraform is on 0.6.* - should this be updated, or changed into an error?

**Comment by phinze** [comment]
Ha yes definitely. Thanks for letting us know about that - we'll get it updated.
