### ISSUE TITLE
google_compute_http_health_check with HTTPS backend service

### ISSUE THREAD

**Issue by Blasterdick** [hashicorp/terraform#5246]
Using google_compute_http_health_check with HTTPS backend service gives me an error:

```
* google_compute_backend_service.frontend-https-balancer: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.he
althChecks[0]': 'https://www.googleapis.com/compute/v1/projects/my-test/global/httpHealthChecks/http-health-check'.  HttpHealthCheck might not be 
used with HTTPS backend service, invalid
```

while official documentation [points](https://cloud.google.com/compute/docs/load-balancing/health-checks), that:

There are two types of health checks available:

```
HTTP health checks, which are required for HTTP and network load balancing.
HTTPS health checks, which are recommended when setting up backend services that use HTTPS, though you could use HTTP health checks instead.

```

What should I do, if in my case I can't use https link for a health check. Thanks in advance.

**Comment by Blasterdick** [comment]
Missunderstood documentation, issue closed.

**Comment by faithseed** [comment]
care to elaborate? can we use HTTP healthcheck with a HTTPS balancer? Thanks!
