### ISSUE TITLE
Support for security groups in AWS lambda resources

### ISSUE THREAD

**Issue by liquorvicar** [hashicorp/terraform#5247]
Is it possible to assign a security group to an AWS lambda resource? I couldn't see anything in the docs and when I tried it it threw an error.

If not, is it something you would consider adding?

**Comment by stack72** [comment]
@liquorvicar, I think you are meaning this in the context of VPCs and lambda? If so, this exists in master right now

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_lambda_function.go#L99

If this is something else then please let me know

**Comment by liquorvicar** [comment]
That looks exactly like what we need. Thanks :+1:

**Comment by stack72** [comment]
@liquorvicar excellent this will be released as 0.6.12 either tonight or tomorrow
