### ISSUE TITLE
redshift cluster resource incorrectly sets publicly_accessible

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#5252]
aws_redshift_cluster resource has attribute publicly_accessible.

Yet when you set this to "false" on a new redshift cluster, the redshift cluster in AWS is marked as publicly_accessible.

And when you change this in AWS, terraform does not recognise the difference.

**Comment by gtmtech** [comment]
terraform 0.6.11

**Comment by stack72** [comment]
@gtmtech - i am just testing this now - by default (without setting anything on the cluster) - `publicly_accessible` gets set to true by AWS

I am running a test to make sure that `publicly_accessible = false` works as expected - will update this issue

**Comment by stack72** [comment]
@gtmtech - so I have jsut verified that you cannot set `publicly_accessible = false` - unless you are using a VPC. Can you psot a copy of your Terraform config (minus secrets)? Or are you able to confirm that you are not using a VPC?

**Comment by gtmtech** [comment]
```
resource "aws_redshift_cluster" "dummy" {
    cluster_identifier = "${var.environment_name}-redshift-cluster"
    database_name = "dummydb"
    master_username = "dummyuser"
    master_password = "dummypass"
    node_type = "dc1.large"
    cluster_type = "single-node"
    vpc_security_group_ids = ["${aws_security_group.dummy.id}"]
    cluster_subnet_group_name = "dummy-subnet-group"
    encrypted = "true"
    publicly_accessible = "false"
}
```

**Comment by stack72** [comment]
@gtmtech - have found the error here. Will fix it now and it should make the terraform 0.6.12 release in a day or 2

**Comment by stack72** [comment]
@gtmtech - PR open at #5262

**Comment by gtmtech** [comment]
Awesome turnaround time, thanks @stack72 !
