### ISSUE TITLE
aws_ecr_repository RequestError

### ISSUE THREAD

**Issue by sudochop** [hashicorp/terraform#5253]
I'm getting a consistent issue when trying to create an ECR. The full error is as follows:

```
Error applying plan:

1 error(s) occurred:

* aws_ecr_repository.repo_api: RequestError: send request failed
caused by: Post https://ecr.us-west-2.amazonaws.com/: dial tcp 54.240.251.144:443: i/o timeout

.. etc ..
```

The ECR gets created, as far as I can tell - even managing to move on to other steps:

```
aws_ecr_repository.repo_api: Creating...
  arn:         "" => "<computed>"
  name:        "" => "app/api"
  registry_id: "" => "<computed>"
aws_security_group.default: Modifying...
  ingress.#:                                     "3" => "4"
  ingress.1289815486.cidr_blocks.#:              "0" => "0"
.. etc ..
```

The `apply` seems to timeout as the very last step. It hangs after it finishes everything else.

`Terraform v0.6.11`

**Comment by stack72** [comment]
@sudochop - unfortuntely AWS have only released ECR in us-east-1. It is not available in us-west-2

**Comment by sudochop** [comment]
Ah, that would make sense. What's odd here is I never (nor have the ability) to explicitly set it. That seems to be what it defaulted to. My other resources _are_ all based in us-west-2, so I'm assuming it's trying to base it's region on what's set in my aws resource? It seems like the behaviour works as expected _if_ they offered ECR's in multiple regions - but for the moment, until that's the case, this seems to be a bit of a bug / unexpected.

**Comment by stack72** [comment]
@sudochop what do you consider the bug to be and what is your thoughts on the intended behaviour?

**Comment by sudochop** [comment]
Well, it seems like if the ECR is only available in us-east-1, it shouldn't be trying to default to us-west-2, especially when I haven't / don't have the ability to set it explicitly. Basically, because my aws resource is configured for us-west-2, I don't have the ability to use the ESR resource. Until amazon releases ESR's in more regions, the behaviour should just be to default to us-east-1 until we have an option to specify an alternative in the resource.

**Comment by stack72** [comment]
@sudochop the reason that ECR is defaulting to us-west-2 is because that is the region that you are telling you provider to use. We can't (and shouldn't) ever tell a user where to put their infrastructure - that is all down to their decision. You can use multi provider config to get around the issue. A sample is as follows:

```
provider "aws" {
}

provider "aws" {
    alias = "east"
    region = "us-east-1"
}

resource "aws_ecr_repository" "foo" {
  provider = "aws.east"
  name = "bar"
}
```

This will allow you to build your ecr repo is us-east-1 and then all the other config in your normal AWS region region. This should allow you to proceed. Please let me know if this helps

Paul

**Comment by sudochop** [comment]
This solves my issue - thank you!

**Comment by stack72** [comment]
Glad this takes care of your issue @sudochop - we had a few requests about this so i know the issue well. I am hoping that AWS will release ECR to other regions soon and then we will be able to skip this going forward :)
