### ISSUE TITLE
Allow local-exec to be fired 1x when using count > 1 with aws_instance

### ISSUE THREAD

**Issue by johnt337** [hashicorp/terraform#5257]
When using a aws_instance block with a count set to greater than 0 and using a provisioner of local-exec, the command executes for each instance in count.

Is there a way to control the execution?

**Comment by johnt337** [comment]
Coming from an ansible approach to infrastructure management, having a concept similar to with_items would increase the flexibility of working with terraform for me.

**Comment by phinze** [comment]
Hi @johnt337 - you can do this will a `null_resource`:

```tf
resource "aws_instance" "foo" {
  count = 10
  # ...
}
resource "null_resource" "after-foo" {
  depends_on = ["aws_instance.foo"]
  provisioner "local-exec" {
    inline = "echo 'Instance Ids: ${join(",", aws_instance.foo.*.id)}'"
  }
}
```

Hope this helps! Let me know if you have any further questions on this.

**Comment by johnt337** [comment]
Sorry for the delay, was bogged down yesterday dealing with a prod issue.
This worked as great. I had to swap "inline" for "command" but outside of that it ran as expected.

Does this same approach work for injecting output from adhoc commands before aws_instance or aws_autoscaling_group fire?

I'm trying to avoid maintaining a terraform wrapper script for scenarios like this:

`terraform apply --var=etcd_token=$(curl -s https://discovery.etcd.io/new?size=3)`
