### ISSUE TITLE
Adhoc execute commands for var injection and setup before terraform apply.

### ISSUE THREAD

**Issue by johnt337** [hashicorp/terraform#5258]
At current while trying to generate a fleet cluster id with terraform, I have to wrap the terraform apply process with a script to inject that data as variables.

Using a script similar to:

```
#!/bin/bash

REGION=us-east-1
ENV=dev

case "$1" in
  apply)
    SIZE=`grep -E "deployment.cluster_size_min" ./${ENV}.tfvars | awk -F= '{print$2}' | sed -e 's/"//g'`
    echo "cluster size: ${SIZE}"
    etcd_token=`curl -s https://discovery.etcd.io/new?size=${SIZE} 2>/dev/null`
    echo "cluster token: ${etcd_token}"

    terraform apply --var "etcd_token=${etcd_token}" ${@: 2}
...
```

Is there a better way to do this within terraform?

**Comment by johnt337** [comment]
I validated I could execute this before the aws_instance or aws_autoscale_group.

resource "null_resource" "pre-flight" {
  provisioner "local-exec" {
    command = "echo 'pre-flight......'"
  }
}

However can that be assigned as an input to a variable?

i.e. 
``` hcl
variable "etcd_token" {
    "default": "${null_resource.pre-flight.rendered}"
}
```

Last time I tried that I couldn't seem to define a variable with interpolation involved.

**Comment by jen20** [comment]
Hi @johnt337! Thanks for opening this! Right now there isn't a better way than wrapping a script around the execution of Terraform. This is something that may be covered by #4169 however. For now I'll close this issue and continue to track it there.

**Comment by johnt337** [comment]
Hi @jen20 thanks for the feedback, i'll be sure to track #4169.

**Comment by chbrown** [comment]
Btw, it looks like, insofar as #4169 ever intended to implement this functionality, it got split off into #8144 (which is currently open). @apparentlymart is doing some excellent work on this front, thanks!

**Comment by ramalhais-sky** [comment]
This can be worked around with an External Data Source:
https://www.terraform.io/docs/providers/external/data_source.html

but it's alot of boilerplate
