### ISSUE TITLE
Crash during OpenStack apply

### ISSUE THREAD

**Issue by wadetandy** [hashicorp/terraform#5259]
Error: `panic: interface conversion: interface is nil, not bool`

[crash.log](https://gist.github.com/wadetandy/0183bd3de420b8d6a3d8)

**Comment by jtopjian** [comment]
Hi Wade,

I'm sorry that you hit this bug. It has been [fixed](https://github.com/hashicorp/terraform/pull/4966) and will be part of the 0.6.12 release, which I think is happening soon.

Again, sorry about the crash...

Joe

**Comment by wadetandy** [comment]
Thanks.  Sorry for the duplicate ticket but couldn't find it in my searching for some reason.

**Comment by jtopjian** [comment]
No problem at all!
