### ISSUE TITLE
Terraform crashes if you place iam_instance_profile in a list...

### ISSUE THREAD

**Issue by BetaGrumm** [hashicorp/terraform#5260]
I realize this is improper syntax, but the following option on an aws_instance resource:
```
iam_instance_profile = ["${aws_iam_instance_profile.prfile-name.name}"]
```
(note the brackets [ ]) will throw a terraform crash. Removing the brackets works as expecrted. 

I thought I would report this as in every other case of bad syntax involving lists brackets, terraform has been ever so kind as to inform me of my erroring ways. This time not so much.

**Comment by phinze** [comment]
Hi @BetaGrumm - what version of Terraform do you see this crash on?

On 0.6.11 this config:

```tf
resource "aws_instance" "foo" {
  ami                  = "ami-abc123"
  instance_type        = "t2.nano"
  iam_instance_profile = ["foo"]
}
```

Yields this error:

```
❯ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_instance.foo: iam_instance_profile must be a single value, not a list
```

**Comment by BetaGrumm** [comment]
Hi @phinze.
I'm running Terraform v0.6.3

**Comment by phinze** [comment]
Ah yes, that bug has been since fixed. If you update you shouldn't see the crash anymore.

Going to close this issue since the bug is fixed in a later version. Let me know if you have any follow up questions. :+1:

**Comment by BetaGrumm** [comment]
My god I love these tools. :+1: 

Thanks.

**Comment by phinze** [comment]
:smile:
