### ISSUE TITLE
panic: missing root module

### ISSUE THREAD

**Issue by sakuvee** [hashicorp/terraform#5268]
I have a simple case where I create a VPC on AWS account. When I issue "terraform apply", terraform 0.6.11 crashes with message "panic: missing root module" immediately after "Apply complete". So all resources are set up as specified but something mysterious happens right before end of process.

Full crash log available here: https://gist.github.com/sakuvee/dd710aa67c90674ff784

**Comment by phinze** [comment]
Hi @sakuvee - that's very strange! Can you share your config so we can reproduce the panic and debug?

**Comment by sakuvee** [comment]
Hi @phinze, the reason seemed to be "resource" declaration missing from my main.tf. I modified it to contain some simple test_role creation like below, and the crashing problem vanished. In my setup everything is set up from modules, so there's no need for resource declaration in the main.tf itself, but is it still a mandatory configuration?


provider "aws" {
    region = "${var.region}"
    allowed_account_ids = ["${var.allowed_account_id}"]
}

resource "aws_iam_role" "test_role" {
    name = "test_role"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

module "vpc" {
    source = "git::ssh://git@github.com/<my_acct>/aws-terraform-modules.git//vpc?ref=feature/nat_gateway"

    name = "vpc-test-${var.env}"
    cidr = "${var.vpc_cidr}"
    private_subnets = "${var.private_subnets}"
    public_subnets = "${var.public_subnets}"
    region = "${var.region}"
    az_suffixes = "${var.az_suffixes}"
}

**Comment by phinze** [comment]
@sakuvee Weird! No resource should be required in the top level. Can you regenerate the crash with a [debug log](https://www.terraform.io/docs/internals/debugging.html) enabled and upload that to a Gist (minus any secrets)? That will help a lot trying to figure out what the repro steps are for this bug.

**Comment by ortz** [comment]
I'm having the same issue after "terraform apply".
from crash log:
`2016/04/07 11:12:21 [DEBUG] waiting for all plugin processes to complete...
2016/04/07 11:12:21 [DEBUG] /Users/ortzabary/bin/terraform_0.6.14_darwin_amd64/terraform-provider-aws: plugin process exited
panic: missing root module

goroutine 1 [running]:
panic(0x82b680, 0xc8206d3ea0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/terraform/terraform.(*State).RootModule(0xc820ae3410, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:205 +0xa7
github.com/hashicorp/terraform/command.outputsAsString(0xc820ae3410, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/apply.go:379 +0x81
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc8200b2c00, 0xc82000a210, 0x0, 0x0, 0xc820109690)
        /opt/gopath/src/github.com/hashicorp/terraform/command/apply.go:253 +0x24bd
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200b8600, 0xc820107aa0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x5ee
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:142 +0xb05
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:78 +0xa10
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:21 +0x18`

**Comment by catsby** [comment]
Folding this into https://github.com/hashicorp/terraform/issues/5855
