### ISSUE TITLE
can't destroy an env with a count input variable

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#527]
I have a module with an aws_instance with a count as :
    count = "${var.server_count}"

server_count is provided from the root module. Creating the infrastructure works great, but when i try to destroy it i get:
Error creating plan: strconv.ParseInt: parsing "${var.server_count}": invalid syntax

It's as if it doesn't do the interpolation, and I can't destroy the infrastructure.

**Comment by mitchellh** [comment]
This works now. I'm not sure when it was fixed but it now does work. We've also added a test case for it just to be certain.
