### ISSUE TITLE
customer_gateway_configuration xml

### ISSUE THREAD

**Issue by richardbowden** [hashicorp/terraform#5274]
Does anyone know of a tool that can take this XML and convert into Cisco CLI format, googling did not come up with anything, how do others consume this output?

Thanks
Rich

**Comment by stack72** [comment]
@richardbowden I am not quote sure what you are asking here? Was this meant for the Terraform issues list?

**Comment by jen20** [comment]
Hi @richardbowden - looks like this was sent to the wrong mailing list? If not could you please add some additional context and reopen? Thanks!
