### ISSUE TITLE
wildcard aws_route53_record keeps showing up as needing to be created by plan

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#528]
I created a few route53 records and all of them worked except the wildcard.  I can create it fine and terraform tells me 1 resource was added, and it appears in the tfstate file.  Then when I run a `terraform plan` afterwards the plan wants to create that same wildcard record again (just create, not teardown then create).

I noticed that in the terraform.tfstate file the "id" attribute has the format `FOO_*.example.com_CNAME` for zone id FOO and the CNAME wildcard record "*.example.com".   Could the asterisk in the id be messing up the matching on future runs?

**Comment by catsby** [comment]
Hey @dcosson – do you have an example `*.tfplan` file I could use to try and reproduce this?

**Comment by dcosson** [comment]
Sure, I had taken out the code since it wasn't working so don't have it now but I'll try to reproduce it when I get a chance in the next few days

**Comment by catsby** [comment]
Great, thanks! There's a *small* chance a change made recently could address this, but regardless I'd like to take a closer look.

**Comment by catsby** [comment]
Hey @dcosson if you do put an example together, **make sure you do not** include any secrets in the `tfplan` you share :smile:

**Comment by catsby** [comment]
@dcosson sorry for the spam – I meant to ask for the `.tf` file, the human readable one, not the generated plan  :) Still, omit secrets et. al

**Comment by xueshanf** [comment]
+1. Same issue with Terraform v0.3.7. 

        resource "aws_db_instance" "mypostgresdb" {
            identifier = "mypostgresdb"
            ...
        }
        resource "aws_route53_record" "star_postgresdb" {
            zone_id = "${var.aws_route53_zone_id_postgresdb}"
            name = ".postgresdb.exmaple.com"
            type = "CNAME"
            ttl = "60"
            records = [ "${aws_db_instance.mypostgresdb.address}" ]
        }

The route53 record is created alright, but re-run tf refresh or tf plan will generate a new terraform.tfstate without the route53 record, hence, the plan is to create a new one. The original terraform.tfstat after creation contains record like this (edited to mask ids):

                "aws_route53_record.star_postgresdb": {
                    "type": "aws_route53_record",
                    "primary": {
                        "id": "*****J2JAYYTML_*.postgresdb.exmaple.com_CNAME",
                        "attributes": {
                            "id": "*****J2JAYYTML_*.postgresdb.example.com_CNAME",
                            "name": "*.postgresdb.example.com",
                            "records.#": "1",
                            "records.3085735408": "mypostgresdb.csgs2i6xlsen.us-west-2.rds.amazonaws.com",
                            "ttl": "60",
                            "type": "CNAME",
                            "zone_id": "XXXXXXXXXXX"
                        }
                    }
                }

**Comment by catsby** [comment]
This should be fixed in #1222 which I just merged. Let me know if you continue to see this issue.
