### ISSUE TITLE
OpenStack Provider: Error waiting for instance to become ready (EOF)

### ISSUE THREAD

**Issue by josdotso** [hashicorp/terraform#5281]
Having an issue with 0.6.11:

Full log is here:
https://gist.github.com/josdotso/2ace926c9405d1b19bf1

Excerpt:
```
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalIf
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalSequence
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalWriteStateTainted
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalIf
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalClearPrimaryState
2016/02/23 19:35:14 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/02/23 19:35:14 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* openstack_compute_instance_v2.s1__instance_n1: Error waiting for instance (0afb79dd-5d95-409a-a402-cf932451e6f8) to become ready: Get https://openstack-cloud:8774/v2/393000acb7644ba78a15a4eadfbeabef/servers/0afb79dd-5d95-409a-a402-cf932451e6f8: EOF
2016/02/23 19:35:14 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* openstack_compute_instance_v2.s1__instance_n1: Error waiting for instance (0afb79dd-5d95-409a-a402-cf932451e6f8) to become ready: Get https://openstack-cloud:8774/v2/393000acb7644ba78a15a4eadfbeabef/servers/0afb79dd-5d95-409a-a402-cf932451e6f8: EOF
2016/02/23 19:35:14 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* openstack_compute_instance_v2.s1__instance_n1: Error waiting for instance (0afb79dd-5d95-409a-a402-cf932451e6f8) to become ready: Get https://openstack-cloud:8774/v2/393000acb7644ba78a15a4eadfbeabef/servers/0afb79dd-5d95-409a-a402-cf932451e6f8: EOF
2016/02/23 19:35:14 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* openstack_compute_instance_v2.s1__instance_n1: Error waiting for instance (0afb79dd-5d95-409a-a402-cf932451e6f8) to become ready: Get https://openstack-cloud:8774/v2/393000acb7644ba78a15a4eadfbeabef/servers/0afb79dd-5d95-409a-a402-cf932451e6f8: EOF
2016/02/23 19:35:14 [TRACE] Exiting eval tree: openstack_compute_instance_v2.s1__instance_n1
2016/02/23 19:35:14 [DEBUG] vertex provider.openstack (close), got dep: openstack_compute_instance_v2.s1__instance_n1
2016/02/23 19:35:14 [DEBUG] vertex provisioner.file (close), got dep: openstack_compute_instance_v2.s1__instance_n1
2016/02/23 19:35:14 [DEBUG] vertex root, got dep: provisioner.file (close)
2016/02/23 19:35:14 [DEBUG] vertex root, got dep: provider.openstack (close)
2016/02/23 19:35:14 [DEBUG] vertex root, got dep: provisioner.chef
2016/02/23 19:35:14 [DEBUG] waiting for all plugin processes to complete...
2016/02/23 19:35:14 [DEBUG] /home/vagrant/bin/terraform-provisioner-file: plugin process exited
2016/02/23 19:35:14 [DEBUG] /home/vagrant/bin/terraform-provisioner-local-exec: plugin process exited
2016/02/23 19:35:14 [DEBUG] /home/vagrant/bin/terraform-provisioner-remote-exec: plugin process exited
2016/02/23 19:35:14 [DEBUG] /home/vagrant/bin/terraform-provisioner-chef: plugin process exited
2016/02/23 19:35:14 [DEBUG] /home/vagrant/bin/terraform-provider-openstack: plugin process exited
```

Here's the graph:
<img width="600" alt="screen shot 2016-02-23 at 3 56 45 pm" src="https://cloud.githubusercontent.com/assets/13571670/13266490/52e9dcf2-da46-11e5-877a-3e834e98e714.png">

Here's the .tf file:
https://gist.github.com/josdotso/fa06f5a3dd90ff1ee84f

The issue seems intermittent, happening approximately 90% of the time.  The version of OpenStack in question is OpenStack Icehouse.  I tested against multiple OpenStack deployments/sites.

Created this as a separate issue per comments in 
#3034 

Also may be related to #5244, but the seems like a different issue to me.

**Comment by jtopjian** [comment]
Thanks for all the info!

**Comment by jtopjian** [comment]
@josdotso I haven't had a chance to run this in a test environment, but I looked over your Terraform configuration and crash log. I have a hunch that the EOF is being caused by the provisioner not being able to connect to the instance. Not necessarily a network policy issue, but possibly no IP address existing at all. It might be that `openstack_networking_floatingip_v2.s1__fip_n1` is being marked as created before the floating IP is actually provisioned within Neutron.

You _should_ be able to use `openstack_compute_floatingip_v2` in place of `openstack_networking_floatingip_v2`. The former uses the Nova API and the latter uses the Neutron API. The big difference (I think I recall) is that the Nova API will block until a Floating IP has been allocated while the Neutron API is a bit asynchronous. 

Do you mind giving that a quick try and see what happens?

If it fixes the problem, then I'll take a closer look into `openstack_networking_floatingip_v2` and make sure it doesn't return until the `address` attribute holds a real value.

**Comment by josdotso** [comment]
@jtopjian 

Thanks for the quick follow up!  I did a couple runs with compute_floatingip replacing networking_floatingip, but had the same result.  I then removed the floating IP declarations completely and tried again, but again had the same result.

**Comment by josdotso** [comment]
I just tried another permutation where I switched to compute_floatingip throughout the file, and moved the floating_ip instance link line from the instance's network block and into the main block.  This worked the first time, but the second time I was back to EOF.  Didn't run it enough times to establish any change in the ~90% failure rate.

```
resource "openstack_compute_instance_v2" "s1__instance_n1" {
    name = "admin-n1"
   flo ating_ip = "${openstack_compute_floatingip_v2.s1__fip_n1.address}"
    volume {
        volume_id = "${openstack_blockstorage_volume_v1.s1__volume_n1.id}"
    }
    image_name = "${var.image}"
    flavor_name = "${var.flavor}"
    key_pair = "${openstack_compute_keypair_v2.s1__keypair_n1.name}"
    security_groups = [ "${openstack_compute_secgroup_v2.s1__secgrp_n1.name}" ]
    network {
        uuid = "${openstack_networking_network_v2.s1__network_n1.id}"
        access_network = true
    }
    provisioner "file" {
        connection {
            user = "${var.instance_user}"
            key_file = "${file("${var.ssh_key}")}"
        }
        source = "${var.ssh_key}"
        destination = "~/.ssh/id_rsa"
    }
    provisioner "file" {
        connection {
            user = "${var.instance_user}"
            key_file = "${file("${var.ssh_key}")}"
        }
        source = "${var.ssh_key_pub}"
        destination = "~/.ssh/id_rsa.pub"
    }
    provisioner "file" {
        connection {
            user = "${var.instance_user}"
            key_file = "${file("${var.ssh_key}")}"
        }
        source = "${var.openrc}"
        destination = "~/openrc.sh"
    }
}
```

**Comment by jtopjian** [comment]
@josdotso Cool - thanks for removing the floating IP -- that reduces the number of variables :)

Would you be able to run this config with `TF_LOG=DEBUG` and post the results?

**Comment by josdotso** [comment]
@jtopjian I changed the config some, and it was working well a few times, but I still get the error.

Notes:
- Boot from volume, rather than just attaching a volume
- Remove the firewall bits
- Have floating IP stuff back in the mix.

I'm going to try it without the access_network directive and see where that goes.  

As an aside, after the rare case when provisioning is successful, VMs (even VMs I create manually in this network/security-group space) can ping public IPs (e.g. 8.8.8.8), but they cannot resolve public addresses (e.g. `nslookup google.com` fails.. as does `nslookup google.com 8.8.8.8`.  What a day! :)

I'm fairly certain the DNS this is entirely separate from the crashing.  I tried specifying DNS servers in the subnet and stating 'dhcp = true', but no dice. 


Here's the log: http://pastebin.com/raw/kU5kGZaC
Here's the updated config: https://gist.github.com/josdotso/fa06f5a3dd90ff1ee84f/9324c9a125ff300d93e1bdd26b9bc8061420a0e1

**Comment by josdotso** [comment]
v0.6.12 seems to be doing better at this.  Will let you know if I see more failures.  Just had three good runs in a row with v0.6.12.   No failures yet on this version.  DNS issue is still outstanding until I confirm otherwise, but again that's probably not at all related.

**Comment by jtopjian** [comment]
That would be awesome news! Definitely keep me up to date. :smile:

**Comment by josdotso** [comment]
Seems fine now.  Thanks!
