### ISSUE TITLE
Expanded resources do not have `count` attribute

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#5283]
Terraform v0.6.11

Steps the reproduce:

```hcl
resource "aws_instance" "web" {
  count = 3
  # ...

  provisioner "remote-exec" {
    inline = "echo ${self.count}"
  }
}
```

Note, this is different than `count.index`, I want to get the value supplied to the resource for `count`, which should be "3" in this example. This works for the first resource (0), but not 1 and 2. Terraform complains that `aws_instance.web.1` does not define a count attribute, but `aws_instance.web.0` does.

This could be that the pre-expanded resource has `count`, but the post-dynamicexpand resources do not.

**Comment by mitchellh** [comment]
I just ran through this and `self.count` now no longer works at all. I'm not sure this was ever actually intended anyways but I'm going to look into it.
