### ISSUE TITLE
Deleting aws_route_internet_access in AWS breaks planning

### ISSUE THREAD

**Issue by danosipov** [hashicorp/terraform#5288]
I had to delete the VPC in AWS, which deleted all related subnets & routes. Rerunning terraform yields an error

```
$> terraform plan
...
aws_route.internet_access: Refreshing state... (ID: r-rtb-####)
Error refreshing state: 1 error(s) occurred:

* aws_route.internet_access: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-####' does not exist
	status code: 400, request id:
```

**Comment by stack72** [comment]
Hi @danosipov, 

Please can you share the config (minus) secrets that would allow us to try and reproduce this so we can try and track down the error

Thanks

Paul

**Comment by danosipov** [comment]
@stack72 I'm going to try to minimize the config, though that may be tricky. I was using the sample from https://github.com/hashicorp/terraform/blob/master/examples/aws-two-tier/main.tf but added route table associations

```
resource "aws_route_table_association" "first" {
    subnet_id = "${aws_subnet.default.id}"
    route_table_id = "${aws_vpc.druid.main_route_table_id}"
}
resource "aws_route_table_association" "second" {
    subnet_id = "${aws_subnet.db.id}"
    route_table_id = "${aws_vpc.druid.main_route_table_id}"
}
```

These caused the problem upon manual deletion of the VPC from AWS. I've had to remove the corresponding entries from `terraform.tfstate` to get it to run again.

**Comment by stack72** [comment]
Ok, if I am reading this correct, then the order of your operations are are follows:

1. Create the setup using Terraform
2. Delete the VPC from the AWS console
3. Try and re-apply the configuration using Terraform?

**Comment by danosipov** [comment]
@stack72 Yes, thats how I encountered the issue.

**Comment by guiocavalcanti** [comment]
@stack72 I have the same error using 0.7.1. [Here](https://gist.github.com/guiocavalcanti/ba5878a46696c81d009ed0c91a56dc9f) you can see part of my logs. At first I thought it was a tack problem and opened an issue (https://github.com/kz8s/tack/issues/45) there.
