### ISSUE TITLE
aws_security_group diffs didn't match during apply error.

### ISSUE THREAD

**Issue by alext** [hashicorp/terraform#5301]
We're encountering a "diffs didn't match during apply" error with terraform. I've managed to reduce it to the following test case:

```
variable "list_of_cidrs" {
  default = "198.51.100.0/24,203.0.113.0/24"
}

resource "aws_eip" "test-ip" {
  count = 2
  vpc = true
}

resource "aws_security_group" "web" {
  name = "example-security-group"
  description = "Example security group"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"
    cidr_blocks = [
      "${split(",", var.list_of_cidrs)}",
      "${formatlist("%s/32", aws_eip.test-ip.*.public_ip)}",
    ]
  }
}
```

A clean run of this will always produce the error. A second run (where the eips are already created) works successfully.

I've run this with debug logging, and posted the output here: https://gist.github.com/alext/7b2e983176176765cfae

**Comment by radeksimko** [comment]
Reproduced, thanks for the report.

I have a strong feeling this is caused by the combination of two interpolation functions, here's an equivalent config that is not affected by that bug:

```hcl
variable "list_of_cidrs" {
  default = "198.51.100.0/24,203.0.113.0/24"
}

resource "aws_eip" "test-ip" {
  count = 2
  vpc = true
}

resource "aws_security_group" "web" {
  name = "example-security-group"
  description = "Example security group"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"
    cidr_blocks = [
      "${split(",", var.list_of_cidrs)}"
    ]
  }

  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"
    cidr_blocks = [
      "${formatlist("%s/32", aws_eip.test-ip.*.public_ip)}"
    ]
  }
}
```

Each CIDR is going to be used for 1 SG rule on the API level anyway, so the resulting effect is exactly the same.

Ain't saying the bug shouldn't be fixed though! :wink:

**Comment by alext** [comment]
Hi, thanks for getting back to me.  Interestingly, we'd looked at the workaround you mentioned, but for terraform 0.6.11 and earlier, it would cause it to update the security group on every run.

I just tried it again with 0.6.12, and it's behaving correctly.  Thanks for the pointer.

**Comment by mitchellh** [comment]
Fixed in newer versions (as posted here) :)
