### ISSUE TITLE
aws_route53_zone with comment argument is not working (when it changed)

### ISSUE THREAD

**Issue by smaeda-ks** [hashicorp/terraform#5317]
Hi,

I tried to use "comment" argument in aws_route53_zone{}.
But comment value did not changed.

Official Document: https://www.terraform.io/docs/providers/aws/r/route53_zone.html

At First,
I have applied without comment argument like this.
```tf
resource "aws_route53_zone" "test-domain" {
    name = "test-domain"
    vpc_id = #omitted
}
```
Then, I can see default comment value "Managed by Terraform" set by Terraform in AWS console.
Next I tried to add comment argument that code.
```tf
resource "aws_route53_zone" "test-domain" {
    name = "test-domain"
    comment = "test-domain"
    vpc_id = #omitted
}
```

But comment value did not changed.
Is this a bug? or in the specification?

Thanks.

FYI
```sh
$ terraform version
Terraform v0.6.11

$ curl http://169.254.169.254/latest/meta-data/placement/availability-zone
ap-northeast-1
```

PS
I tried with v0.6.12 but same result.

**Comment by stack72** [comment]
Hi @smaeda-ks, I am just about to open a PR that fixes this issue :)

**Comment by smaeda-ks** [comment]
Hi @stack72,

Cool!!
Super thanks.

**Comment by stack72** [comment]
Closed by @5318 :)
