### ISSUE TITLE
Syntax error interpolating count attribute when value passed between modules

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5322]
From a [report on the Terraform mailing list](https://groups.google.com/d/msgid/terraform-tool/e0790b65-d599-4f20-b81c-fe13db55e0c6%40googlegroups.com).

## Repro config

```tf
# main.tf
module "source" {
  source = "./source"
}
module "child" {
  source  = "./child"
  list = "${module.source.list}"
}

# source/main.tf
output "list" { value = "foo,bar,baz" }

# child/main.tf
variable "list" { }
resource "template_file" "temp" {
  count     = "${length(split(",", var.list))}"
  template  = "foo"
}
```

## Steps

Run `terraform plan`.

## Expected behavior

A plan to create 3 templates.

## Observed behavior

```
Error configuring: 1 error(s) occurred:

* strconv.ParseInt: parsing "${length(split(\",\", var.list))}": invalid syntax
```

Related issues:

 * #1497 
 * #3884 
 * #4738 

This might actually be a dupe of one of those, but I wanted to get this repro out there. :+1:

**Comment by dbrandt** [comment]
This is biting me right now. I'm trying to start up one EC2 instance in every availability zone with output from [tf_aws_availability_zones](https://github.com/terraform-community-modules/tf_aws_availability_zones) but running into this parse error instead, forcing me to use hard coded values.

**Comment by jmfuchs** [comment]
Any update on this?

Thanks!

**Comment by clstokes** [comment]
Related to #4703 too maybe?
