### ISSUE TITLE
`ResourceNotFoundException: No tags found for provided resource` on "aws_elasticsearch_domain" provider

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#5325]
We've been seeing this error on terraform plans since upgrading to `terraform 0.6.12` this morning:

```
Error refreshing state: 1 error(s) occurred:

* aws_elasticsearch_domain.es: ResourceNotFoundException: No tags found for provided resource: arn:aws:es:us-east-1:689543204258:domain/stage-logstash
	status code: 409, request id: 16a3ed6b-dbdf-11e5-89cf-55c1901d1758
```

looking at the changelog for the 0.6.12 release it lists `provider/aws: Add support for Tags to ElasticSearch [GH-4973]` so I'm assuming it has something to do with this.

I figured that adding a tag argument would fix the issue but was still seeing the same error when trying to terraform plan.

```
variable "cluster_name" {
    default = "logstash"
}
    tags {
        Name = "${var.cluster_name}"
    }
```

I went into our AWS console and added the tag manually and tried another terraform plan.  It succeeded with the tag manually added before the terraform plan was run.

```
~ module.logstash_elasticsearch.aws_elasticsearch_domain.es
    tags.#:    "0" => "1"
    tags.Name: "" => "logstash"
```

I'm not sure what to make of this one.  Would think that the missing tag would just be added without having to manually add to that cluster through the AWS console beforehand.

**Comment by alfonso-cabrera** [comment]
I'm also getting this same error with 0.6.12. Works fine in 0.6.11. Also looks like the documentation is missing this info. Looking at 

`https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elasticsearch_domain.go`

it shows this:

`"tags":` tagsSchema(),` in the resourceAwsElasticSearchDomain function but there is nothing in the documentation regarding what's expected.

**Comment by stack72** [comment]
@PurrBiscuit @alfonso-cabrera, I have found the cause of this issue. I will have a fix in place later
today

Paul

**Comment by stack72** [comment]
@PurrBiscuit @alfonso-cabrera - I believe I have just fixed this in #5361.

**Comment by PurrBiscuit** [comment]
hey, thanks @stack72

**Comment by stack72** [comment]
I am not sure if you can build from source and test it or you will wait for it to be released in 0.6.13, but either way, please let me know

Paul

**Comment by PurrBiscuit** [comment]
we can wait until the 0.6.13 release.  right now it's not an issue for us anymore since adding those tags manually.  thank you.

**Comment by stack72** [comment]
:+1:

**Comment by elisehuard** [comment]
Same error observed with v0.6.12, same workaround worked.  Looking forward to 0.6.13 :)

**Comment by paultyng** [comment]
Sorry, my fault on this one :( need to work on my Go skills.  I had the same bug until I manually tagged also.

**Comment by stack72** [comment]
Not at all @paultyng - I should have picked this up in the tests :)
