### ISSUE TITLE
fetch_chef_certificates option is broken

### ISSUE THREAD

**Issue by ioben** [hashicorp/terraform#5328]
The `fetch_chef_certificates` chef provisioner option is broken.  
It should run the command `sudo knife ssl fetch` (the tests do this), in actuality it tries to run `sudo chef-client ssl fetch`, which will never work if the SSL cert wasn't already verified.

In [/builtin/provisioners/chef/resource_provisioner.go](https://github.com/hashicorp/terraform/blob/ebfcaed3c18f6e7046d6985f9b2322f21fd24324/builtin/provisioners/chef/resource_provisioner.go#L146) line 146 the variable `linuxChefCmd` should be `linuxKnifeCmd`, the same modification needs to be made on line 152 for the windows chef command variants.

You can see [in the relevant test](https://github.com/hashicorp/terraform/blob/7c327523327f6ecf1e1cc5a7225793fb47f2a2dc/builtin/provisioners/chef/resource_provisioner_test.go#L152) the correct command is used.  It may be a good idea to add another test to verify the `apply` function is calling other functions correctly to catch any other issues like this.

**Comment by ioben** [comment]
Relevant PR: #5331

**Comment by svanharmelen** [comment]
Fixed by PR #5331

**Comment by rossedman** [comment]
:+1: This has been driving me nuts until I came to the same conclusion. Hoping to see this released soon please.
