### ISSUE TITLE
how to create aws_rds_cluster instance (aurora) with multi_az flag?

### ISSUE THREAD

**Issue by vpothnis** [hashicorp/terraform#5333]
Hello, 

The documentation for creating an aws_rds_cluster_intance (aurora instance) https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html does not seem to specify a way to create the instance with multi_az attribute. 

Any idea how to set up an aurora instance with multi_az set to true with terraform? 

Thanks!

**Comment by stack72** [comment]
Hi @vpothnis,

What configuration are you trying to get setup with?

Paul

**Comment by vpothnis** [comment]
Hi @stack72,

This is what I have:

`resource "aws_rds_cluster" "aurora_test_cluster" {
    cluster_identifier = "aurora-test-cluster"
    database_name = "auroratest_core"
    master_username = "USERNAME_HERE"
    master_password = "PASSWORD_HERE"
    backup_retention_period = 5
    preferred_backup_window = "11:15-12:15"
    vpc_security_group_ids = [ "${aws_security_group.aurora_db.id}" ]
    db_subnet_group_name = "nonprod-db-subnet-group"
    final_snapshot_identifier = "auroratest-final-ss"
}

resource "aws_rds_cluster_instance" "aurora_test" {
    count = 2
    identifier = "auroratest-${count.index}"
    cluster_identifier = "${aws_rds_cluster.aurora_test_cluster.id}"
    instance_class = "db.r3.xlarge"
    db_subnet_group_name = "nonprod-db-subnet-group"
}`

The subnet `nonprod-db-subnet-group` has subnets from all 3 AZs assigned to it.

Thanks
Vinay

**Comment by bsiegel** [comment]
From the information provided in https://github.com/aws/aws-sdk-go/issues/475, it looks like the only thing that happens when you select the value for "Multi-AZ" is whether the AWS Console creates a single DB instance node, or whether it also creates a replica node in another AZ. So you should be able to control this by simply changing the number of `aws_rds_cluster_instance` resources you create.

**Comment by phinze** [comment]
Yep @bsiegel is correct! Here's a config that yields a writer and a reader striped across two AZs:

```tf
variable "azs" {
  default = "us-west-2a,us-west-2b"
}

resource "aws_vpc" "main" {
  cidr_block = "10.123.0.0/16"
}

# Creating one subnet in each AZ
resource "aws_subnet" "private" {
  vpc_id = "${aws_vpc.main.id}"
  count             = "${length(split(",", var.azs))}"
  availability_zone = "${element(split(",", var.azs), count.index)}"
  cidr_block        = "10.123.${count.index}.0/24"
}

resource "aws_db_subnet_group" "aurora" {
  name = "phinze-test-db-subnetgroup"
  description = "it is silly that this is required in the API"
  subnet_ids = ["${aws_subnet.private.*.id}"]
}

resource "aws_rds_cluster" "default" {
  cluster_identifier   = "multiaz-cluster"
  database_name        = "mydb"
  master_username      = "myuser"
  master_password      = "longerthan8chars"
  db_subnet_group_name = "${aws_db_subnet_group.aurora.name}"
}

resource "aws_rds_cluster_instance" "aurora_instance" {
  count                = 2
  cluster_identifier   = "${aws_rds_cluster.default.id}"
  instance_class       = "db.r3.large"
  db_subnet_group_name = "${aws_db_subnet_group.aurora.name}"
}
```

**Comment by vpothnis** [comment]
thank you for your inputs!
