### ISSUE TITLE
Bad output value silently ignored

### ISSUE THREAD

**Issue by brainsik** [hashicorp/terraform#5334]
Naïvely one might expect to be able to use a list as an output (instead of the required string). Doing this produces no error:

``` hcl
output "subnets" {
    value = "${aws_subnet.example.*}"
}
```

Nor this:

``` hcl
output "subnets" {
    value = "${join(",", aws_subnet.example.*)}"
}
```

Nor this:

``` hcl
output "subnets" {
    value = "${aws_vpc.example.this-no-exist}"
}
```

Basically, you end up stumbling around confused why your output isn't showing up. It would be great to get some sort of error message instead of silently dropping the output.

Appears related to #4369.

**Comment by eedwardsdisco** [comment]
I also got bit by this one.

Out of curiosity, why does your second example fail?

I've successfully used the following, the variable is a list:

```
output "name_servers" {
	value = "${join(",", aws_route53_zone.domain.name_servers)}"
}
```

**Comment by brainsik** [comment]
The second one fails because it's not specifying a field to return. Should be something like `aws_subnet.example.*.id` to return a list of IDs (that are then converted into a comma separated string).

**Comment by eedwardsdisco** [comment]
Ah, that's clear now, thanks!

**Comment by jen20** [comment]
Thanks for reporting this - I agree this should give an error rather than silently dropping the output.

**Comment by wr0ngway** [comment]
This also happens for bad interpolation function calls, e.g. passing the wrong type or number of args to a interpolation function, e.g. compact("x", "y")

**Comment by mitchellh** [comment]
This is actually tracked as "core+bug" issue #4975. I'm centralizing there!

**Comment by rhettg** [comment]
@mitchellh you centralized #4975 to this issue, forming a frustrating cycle.

Is there a more canonical issue that could be linked?

**Comment by mitchellh** [comment]
Oh Hah. I made a mistake, #9080 is the open one.
