### ISSUE TITLE
Setting multiple load balancers in ECS service is invalid

### ISSUE THREAD

**Issue by egoldschmidt** [hashicorp/terraform#5336]
Multiple load balancers in an ECS service specification is [not allowed](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html) by AWS. Unfortunately, doing so results in an opaque `InternalFailure` error which is very difficult to debug. I suggest we amend the `aws_ecs_service` docs to make this more clear.

**Comment by radeksimko** [comment]
Fixed via https://github.com/hashicorp/terraform/pull/5605 and https://github.com/hashicorp/terraform/commit/693b5de932fcad2e84724af2e95cbc11bde69055

Thanks for the report.
