### ISSUE TITLE
Cannot interpolate splat in output var

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#534]
In a module, i have :
output "all_ids"{
    value = "${join(",", aws_instance.server.*.id)}"
}

(for the aws_instance named "server" in that file)
and i'm getting:
Error creating plan: Resource 'aws_instance.server' not found for variable 'aws_instance.server.*.id'

**Comment by dpkp** [comment]
Is this still an issue?  This works for me w/ terraform 0.3.6:

```
output "private_ips" {
   value = "${join(",", aws_instance.foobar.*.private_ip)}"
}

resource "aws_instance" "foobar" {
   count = 3
   ...
}
```

**Comment by mitchellh** [comment]
This works now, correct!
