### ISSUE TITLE
lifecycle should support ${vars}

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#5346]
One of our `aws_ebs_volume` resources is configured like this:

```
    lifecycle {
        prevent_destroy   = "${var.foo.prevent_destroy}"
    }
```

with variable appropriately set:

```
variable "foo" {
    default = {
        prevent_destroy     = "true"
    }
}
```

However, a plan-destroy leads to:

```
Error loading config: Error loading resources/aws_ebs_volume.foo.tf: Error parsing lifecycle for aws_ebs_volume[foo]: 1 error(s) decoding:

* cannot parse 'prevent_destroy' as bool: strconv.ParseBool: parsing "${var.foo.prevent_destroy}": invalid syntax
```

So lifecycles should support variables too.

**Comment by gtmtech** [comment]
Terraform 0.6.11

**Comment by deniszh** [comment]
:+1:
Same here, even on latest master version.

**Comment by jen20** [comment]
Right now lifecycle blocks don't get interpolated so this isn't supported. I'll tag this as a core enhancement and look at whether it is possible or not.

**Comment by norcalli** [comment]
+1 I would like this for both prevent_destroy and ignore_changes to control focus of updates, as there are currently bugs in terraform with i.e. the listener block in aws_elb and also occasionally the db_instance where it triggers an erroneous update that would be useful. It also would be useful in lieu of a `-ignore` which mirrors the `-target` flag in `terraform plan`.

**Comment by dsolsona** [comment]
+1 here.

I wish I could do `ignore_changes = ["${split(",", var.ignore_changes)}"]`

**Comment by vervas** [comment]
any updates here?

**Comment by kevinlondon** [comment]
This looks like the same issue as https://github.com/hashicorp/terraform/issues/3116 to me.

**Comment by mitchellh** [comment]
Dup of #3116 Thanks @kevinlondon
