### ISSUE TITLE
vsphere_virtual_machine timeout waiting for creation creates no tfstate

### ISSUE THREAD

**Issue by matt-deboer** [hashicorp/terraform#5347]
Often when running `terraform apply` to create one or more (usually multiple) vsphere_virtual_machine instances, terraform stalls waiting for the vmware tools to come online and report an ip address (quite possibly an esxi problem). This never modifies the .tfstate file, thus subsequent runs of `apply` will attempt to create the resource again, only to error out finding that it already exists--the net result being manual stop and/or removal of each of the offending vms before running `apply` again.

It would be better if entries for these vms were added to the .tfstate file in a "tainted" state, finally removing the tainted state once the vm reports back as online. This would allow subsequent runs of `apply` to delete and recreate the vm as needed, instead of requiring manual deletion, and it would also allow runs of `apply` to be aborted for stalling out without requiring a bunch of manual intervention.

**Comment by jen20** [comment]
I think the issue here is whether we get back an ID before the resource creation is complete. If so we may be able to use partial state to record this.

**Comment by chrislovecnm** [comment]
@jen20 you think this also may be the ip address issue that we are having?  @tkak's PR https://github.com/hashicorp/terraform/pull/4283  We are really not waiting for the ip address correctly

**Comment by chrislovecnm** [comment]
@matt-deboer https://github.com/hashicorp/terraform/pull/6377 may have fixed this ... you mind testing?

**Comment by chrislovecnm** [comment]
@jen20 @stack72 this should be addressed.  Can we close?

**Comment by stack72** [comment]
Fixed by #6377
