### ISSUE TITLE
aws_vpc_dhcp_options.consul: diffs didn't match during apply.

### ISSUE THREAD

**Issue by MansM** [hashicorp/terraform#5362]
$ terraform -version
Terraform v0.6.12 (OSX)

Message:
Error applying plan:

1 error(s) occurred:
- aws_vpc_dhcp_options.consul: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

```
Terraform Version: 0.6.12
Resource ID: aws_vpc_dhcp_options.consul
Mismatch reason: diff RequiresNew; old: false, new: true
Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.0":*terraform.ResourceAttrDiff{Old:"", New:"10.0.1.181", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "domain_name_servers.1":*terraform.ResourceAttrDiff{Old:"", New:"10.0.1.222", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}}, Destroy:false, DestroyTainted:false}
```

code:

```
resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_vpc_dhcp_options" "consul" {
  domain_name_servers = ["${aws_instance.nomadserver1.private_ip}", "${aws_instance.nomadserver2.private_ip}"]

}

resource "aws_vpc_dhcp_options_association" "dns_resolver" {
    vpc_id = "${aws_vpc.default.id}"
    dhcp_options_id = "${aws_vpc_dhcp_options.consul.id}"
}
```

**Comment by jrnt30** [comment]
Just as an aside, the `domain_name_servers` I believe should be comma delimited list per http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html, not multiple values unless TF is doing the concatenation under the covers (which it doesn't appear to).  

I have been burned by this a few times when using CloudFormation and really hate that they (AWS) don't make this more clear  :)

**Comment by MansM** [comment]
0.6.13 has the same issue

**Comment by klokkie** [comment]
Same on 0.6.14 ...

**Comment by jsravn** [comment]
Seeing this on 0.7.0 as well.

**Comment by jsravn** [comment]
Seems to happen if `domain_name` is left out. Adding that explicitly, e.g. `domain_name = eu-west-1.compute.internal` fixes it.

**Comment by nicksuckling** [comment]
This seems to still be an issue in 0.7.5 even when using domain_name = .
https://gist.github.com/nicksuckling/a0b6cab8049d6d6cf30ee108ebbab3b7

**Comment by mitchellh** [comment]
Tracing this in #10192. Same error, but on a newer version.
