### ISSUE TITLE
Feature request: "Initial delay" attribure to google_compute_instance_group_manager

### ISSUE THREAD

**Issue by Blasterdick** [hashicorp/terraform#5371]
"Initial delay" - the time to allow an instance to boot and applications to fully start before the first health check.

The "initial delay" can be found when you create the instance group via Google Developers Console, Web UI, or when use the Beta version of the [gcloud SDK](https://cloud.google.com/sdk/gcloud/reference/beta/compute/instance-groups/managed/set-autohealing) via command line.

It would be great to get this stuff working ;)

**Comment by lwander** [comment]
ping @evandbrown

**Comment by billf** [comment]
c.f. https://github.com/hashicorp/terraform/issues/5053#issuecomment-182096731 for a description of why supporting access to beta features is difficult for terraform at present.

**Comment by Blasterdick** [comment]
@billf I understand you, mate. Thanks for a quick reply. Now I'll spam Google with plea to add this in upstream ASAP.
