### ISSUE TITLE
Store remote state in vault

### ISSUE THREAD

**Issue by sheerun** [hashicorp/terraform#5374]
Hey,

My terraform state contains pretty sensitive information so I wonder if it's possible to save remove state in vault, or in some other encrypted way. Except for Atlas push, of course.

So question: are there plans for vault remote state backend (http api or so), and is it possible to enable client-side encryption for any remote state backend in some way?

**Comment by phinze** [comment]
Hi @sheerun - good question!

We definitely have plans to support remote state encryption via Vault. Not quite sure on the timeline for that functionality, though.

In the meantime, the [s3 backend](https://www.terraform.io/docs/state/remote/s3.html) does support S3's encryption-at-rest feature.

**Comment by sheerun** [comment]
To be clear: most beneficial would be client-side encryption for any backend. Is it possible to implement?

**Comment by mtougeron** [comment]
@sheerun there's been a lot of discussion about this in issue #516
