### ISSUE TITLE
Abort apply early when provisioner fails

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/terraform#5381]
Hi,

if I replace an resource that has create_before_destroy set and set `--parallelism` to 0, TF first creates a new instance.

I expect that if the resources provisioner fails, TF would abort but this isn't the case.
Instead it continues, trying to create new resources which fail but still deletes all old resources.

Maybe I miss something but this behavior is not what I would expect. Maybe there is a way around it but I can't find anything in the documentation to making TF abort early if it runs into errors.

**Comment by mitchellh** [comment]
I haven't reproduced it yet but I'm going to word this another way: the bug happening here (if it is reproducible) is that a CBD resource if it fails provisioning should not continue with destroying the original deposed resource. 

I feel like this is a case we handle but of course you reported this so potentially not! Easy for us to test though and I'll get on it.

**Comment by mitchellh** [comment]
I couldn't reproduce this, with the following config:

```
variable "trigger" { default = "0" }

resource "null_resource" "foo" {
    triggers {
        var = "${var.trigger}"
    }

    provisioner "local-exec" {
        command = "exit ${var.trigger}"
    }

    lifecycle {
        create_before_destroy = true
    }
}
```

Steps:

```
$ terraform apply
$ TF_VAR_trigger=1 terraform apply
```

Result:

The old value still remains the primary, the new value becomes tainted. This is as expected.

**Comment by discordianfish** [comment]
Ok, it's been a while since I ran into this. Will reopen if I can reproduce it with my stack.
