### ISSUE TITLE
Terraform is panicking when using azurerm provider 

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/terraform#5384]
Terraform is panicking while I try and follow the basic provider setup from https://www.terraform.io/docs/providers/azurerm/.

The output of the crash log is here https://gist.github.com/mbfrahry/5ed5be3a4d871ab5a8e8

**Comment by stack72** [comment]
Hi @mbfrahry, what is the config that you are using (minus secrets)?

**Comment by mbfrahry** [comment]
provider "azurerm" {
  subscription_id = "..."
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}

**Comment by stack72** [comment]
@mbfrahry, how did you generate your config? Does the access details you have allow registering providers?

**Comment by mbfrahry** [comment]
The subscription id and the tenant id were given from azure. The client id and client secret were very tricky and I don't know if I did it right but I followed https://auth0.com/docs/connections/enterprise/azure-active-directory. 

Is that the best way to get a client id and client secret??

**Comment by spuder** [comment]
duplicated by #5399

**Comment by stack72** [comment]
Hi @mbfrahry 

Thanks to @AwaNoodle (#5965) - there is no some documentation for how to create the correct credentials - https://www.terraform.io/docs/providers/azurerm/index.html

Please try and make sure that the correct credentials are specified and let me know if there are still issues for you

Thanks

Paul

**Comment by stack72** [comment]
Hi @mbfrahry 

I haven't heard back to see if this helped solve the issue. From the other reported issues that are similar, this solves them. I am going to close this out for now. Please let me know if there is still a problem

Thanks

Paul

**Comment by mbfrahry** [comment]
Oh shoot! I was subscribed to a similar issue and thought this one died. I got the documentation for azurerm and it works great! Thanks for looking back on this

**Comment by stack72** [comment]
thanks for letting me know @mbfrahry :)
