### ISSUE TITLE
AWS SNS delivery status support

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#5386]
Would be great to have SNS delivery status support so it doesn't have to be manually added per topic in the UI, pretty sure there's an API for it

**Comment by stack72** [comment]
Hi @tj, any idea where the docs or an example would be for this?

Thanks

P.

**Comment by tj** [comment]
It's pretty hidden, in the "Other topic actions" dropdown: https://mobile.awsblog.com/post/TxHTXGC8711JNF/Using-the-Delivery-Status-feature-of-Amazon-SNS

**Comment by stack72** [comment]
excellent link - thanks for that!

**Comment by dgarlitt** [comment]
+1

**Comment by boyand** [comment]
+1

**Comment by james-huston** [comment]
+1

**Comment by stack72** [comment]
Hi @tj 

Apologies for not getting back to this sooner - I am looking at this now

Paul

**Comment by stack72** [comment]
ok, from looking at this, I am *really* confused. I am not quite sure what this relates to in the API. I am trying to work out where this would fit into Terraform

@tj any thoughts here?

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!

**Comment by acoover** [comment]
+1
