### ISSUE TITLE
TERRAFORM CRASH - when configuring for Azure ARM

### ISSUE THREAD

**Issue by nagardd** [hashicorp/terraform#5399]
Hi All,

I was trying to configure terraform with Azure ARM using the template (in CentOS 7):

```
# Configure the Azure Resource Manager Provider
provider "azurerm" {
  subscription_id = "..."
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}

# Create a resource group
resource "azurerm_resource_group" "production" {
    name     = "production"
    location = "West US"
}

# Create a virtual network in the web_servers resource group
resource "azurerm_virtual_network" "network" {
  name                = "productionNetwork"
  address_space       = ["10.0.0.0/16"]
  location            = "West US"
  resource_group_name = "${azurerm_resource_group.production.name}"

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
  }

  subnet {
    name           = "subnet3"
    address_prefix = "10.0.3.0/24"
  }
}
```

Then I followed the steps to get client id and secret from the page:
https://auth0.com/docs/connections/enterprise/azure-active-directory

 tenant_id I got from output of command Login-AzureRmAccount.

When running command: terraform plan I got the error:

```
$ terraform plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/03/01 18:18:57 [DEBUG] terraform-provider-azurerm: [signal 0xb code=0x1 addr=0x10 pc=0x6068d7]
2016/03/01 18:18:57 [DEBUG] terraform-provider-azurerm: 
2016/03/01 18:18:57 [DEBUG] terraform-provider-azurerm: goroutine 33 [running]:
***/more output here***

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Could  you please let me know what I've done wrong?

Thanks.

**Comment by spuder** [comment]
+1 Easy enough to reproduce.

## Reproduce

Create a provider exactly how the documentation shows. (Including having three dots for the client_id)
```
provider "azurerm" {
  subscription_id = "xxxxxxx"
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}
```

## Workaround

Remove the 3 dots, or comment out the client_id, client_secret and tenant_id completly. 
```
provider "azurerm" {
  subscription_id = "xxxxxx"
  # client_id       = "..."
  # client_secret   = "..."
  # tenant_id       = "..."
}
```

**Comment by jen20** [comment]
Hi, thanks for opening an issue. You need all four configuration items to make successful calls to the Azure API, however this shouldn't panic. Assuming this has not already been addressed in the latest release we will do so in the next one.

**Comment by nagardd** [comment]
Hello, thanks for working on this. I forgot to mention that I am using version v0.6.11.

**Comment by mbfrahry** [comment]
I am having this same issue in version v0.6.12

**Comment by elmalto** [comment]
Is there a workaround?

**Comment by AwaNoodle** [comment]
I've been having the same issue with 0.6.12 and 0.6.14. I've tested on Windows and Mac with the same results. I have a simple Azure network with a single subnet, one security group, storage. No VMs as yet.

[crash.log](https://gist.github.com/AwaNoodle/86373a42a6cdc72ded5e)

If you need the scripts, let me know.

**Comment by stack72** [comment]
Hi @nagardd,

Thanks to @AwaNoodle - there is no some documentation for how to create the correct credentials - https://www.terraform.io/docs/providers/azurerm/index.html

Please try and make sure that the correct credentials are specified and let me know if there are still issues for you

Thanks

Paul

**Comment by nagardd** [comment]
Hi Paul,

Sorry for late replay. I was busy with other stuff. 
I tested this with correct credentials (with credentials that I have access to AzureRM via Python) and there is no crash!!

The crash is with the credentials (correct credentials) that I have no access to AzureRM with SDK. 
So the license type (pay-as-you-go) has limits that deny python and other automations.

Thanks for help.

**Comment by stack72** [comment]
@nagardd 

This is good news. thanks for letting me know

Closing this now

P.

**Comment by spuder** [comment]
For anyone else struggling getting the azure credentials, there is a tool that can help out: 

https://github.com/pendrica/azure-credentials
