### ISSUE TITLE
Terraform "official" styleguide?

### ISSUE THREAD

**Issue by geovanisouza92** [hashicorp/terraform#5403]
Hi, thanks for this amazing project!

I'm starting to sketch our infrastructure and while splitting the various components, I was thinking about the recommended way to name files, variables, outputs, etc. I found [bsnape/terraform-style-guide](https://github.com/bsnape/terraform-style-guide), but it seems superficial and incomplete, so, I would like to hear from Terraform creators (and all community, of course) what do you think is the "Terraform Styleguide".

Thank you.

**Comment by mpeter** [comment]
https://github.com/hashicorp/best-practices

This repo mostly works, and is geared towards also demonstrating integration with Atlas. I've found it useful as a good example of organizing a module based, multi-environment, multi-region, potentially multi-provider project.
* We use a makefile in each directory that sets up the remote s3 backend, which uses the directory name to setup a corresponding s3 path.
* We use the same Makefile to create symlinks to a "module" subdirectory. That keeps you from having to create ugly "../../../modules/foo" references everywhere.
We organize things in multiple sub-directories, and use a Makefile that

- /.envrc
- /terraform
  - src
    - Makefile
    - main.tf (stuff that's global to an account, like IAM roles)
    - dev
      Makefile
      main.tf (stuff that's global to an environment)
      - us-east-1
        - Makefile
        - main.tf (This contains our main configurations, which make calls to modules/roles/foo mostly)
      - us-west-2
    - test
    - prep
    - prod
  - modules
    - roles
      - bastion (makes calls to additional modules)
    - compute
    - data
    - network
    - util

Makefile
```
PRJ_ROOT := $(shell git rev-parse --show-cdup)
MOD_PATH := $(PRJ_ROOT)terraform/modules
BRANCH := $(shell cd $(PRJ_ROOT) && git rev-parse --abbrev-ref HEAD)

init:
  test ! -L modules && ln -s $(MOD_PATH) modules || true
remote: init
  terraform remote config \
  -backend=s3 \
  -backend-config="region=us-east-1" \
  -backend-config="bucket=foo" \
  -backend-config="key=$(BRANCH)/$(REL_PATH)/terraform.tfstate" \
  -backup=-
```
/.envrc (http://direnv.net/)
```
source_up
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_DEFAULT_REGION=us-east-1
export TF_VAR_aws_region=us-east-1
export TF_VAR_root_path=$(git rev-parse --show-cdup) && echo $PWD
```

**Comment by jen20** [comment]
Hi @geovanisouza92! Thanks for opening this issue. As @mpeter says the closest thing to a substantive style guide is the best practices repo, to which we should add a link in the documentation. In addition to that, since Terraform was released the HCL language has spawned an "HclFmt" command which is analogous to Go's "GoFmt" command and should help with code style.
