### ISSUE TITLE
MySQL provider crashes when instance is a Docker container

### ISSUE THREAD

**Issue by geovanisouza92** [hashicorp/terraform#5404]
If we want to configure/create a MySQL database on an instance that is a Docker container, it seems that MySQL provider tries to communicate with the server, that doesn't exists yet, and crashes.

To workaround, we have to create the Docker container first, `plan`, `apply`, configure the MySQL provider and resources, `plan` and `apply`.

Trying to do the same thing with PostgreSQL provider doesn't crashes and works like a charm.

**Comment by apparentlymart** [comment]
I guess the MySQL provider must be connecting to the server a little too enthusiastically, doing it during provider instantiation rather than when asked to create a resource.

**Comment by apparentlymart** [comment]
I'll take a look at this when I get a chance, and see how the postgres provider differs.

**Comment by geovanisouza92** [comment]
@apparentlymart I thought exactly this! Thank you.

**Comment by partamonov** [comment]
Can be related to #5687
