### ISSUE TITLE
arn attribute for aws_elb ?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/terraform#5406]
I couldn't see it, but what would be one way to expose the ARN attribute for an aws_elb resource ?

**Comment by stack72** [comment]
@JoeOrtiz, just opened this PR #5411 that addresses it

**Comment by stack72** [comment]
Hi @JoeOrtiz 

Circling back on this to try and close off some older issues - what do you need to use the ELB ARN for?

P.

**Comment by stack72** [comment]
I am going to close this off - AFAICT I can't see anywhere where the use of ARN for ELB is used. If it were the case, AWS would expose the functionality. If you have a specific usecase then let me know and we can reopen

Thanks

Paul

**Comment by tomelliff** [comment]
@stack72 we have the same use case as @gustav-b where we would prefer to use an outputted ARN from the ELB directly instead of concatenate the id/name with other stuff.

Taking a look at things it looks like the elbv2 API exposes this but it was never exposed in the old elb API.
