### ISSUE TITLE
Reference resource name from resource itself

### ISSUE THREAD

**Issue by yadutaf** [hashicorp/terraform#5412]
I'm playing around with terraform, nothing critical. The interpolation is very powerful and the discussion around iterators and inheritance is extremely interesting. After reading them, I am still wondering how I can reference current resource name from itself ? For instance, I have an OpenStack resource looking like:

```
resource "openstack_compute_instance_v2" "web" {
  count = 3  
  name = "web-${count.index}")}"
}
```

In this example, "web" is duplicated. Is there a way to re-use the resource name in the hostname ? Like:

```
resource "openstack_compute_instance_v2" "web" {
  count = 3  
  name = "${self.resource.name}-${count.index}")}"
}
```

**Comment by jen20** [comment]
Hi @yadutaf! Thanks for opening this issue. Self referential variables outside of provisioners has been a long-running issue tracked here: https://github.com/hashicorp/terraform/issues/3267 - I'll close this in favour of the discussion going on there. Thanks!

**Comment by jen20** [comment]
I mean https://github.com/hashicorp/terraform/issues/925 rather than https://github.com/hashicorp/terraform/issues/3267, sorry!
