### ISSUE TITLE
issue with adding load balancer to aws_ecs_service

### ISSUE THREAD

**Issue by arozwalak** [hashicorp/terraform#5414]
I've created `aws_iam_role_policy` as part of my `ecspolicy` module and I'm outputing this policy as 

```
output "ecs_role_policy" {
  value = "${aws_iam_role_policy.ecs_role_policy.policy}"
}
```

then I'm sending this as variable `ecs_role_policy` to my other module which creates `aws_ecs_service` with `load_balancer`. I have problem with adding `depends_on = ["${var.ecs_role_policy}"]. When I call `terraform plan` I'm getting `missing dependency: ${var.ecs_role_policy}. Any idea how I can pass correctly role policy as dependency to my ecs_service to attach `load balancer`?

**Comment by jen20** [comment]
Hi @arozwalak! Could you provide some more context around your configuration here? I suspect you actually want to provide the ARN rather than the policy?

**Comment by stack72** [comment]
Closing this as there has been no response. @arozwalak feel free to re-comment if you still need help here

Paul
