### ISSUE TITLE
Start from scratch after manual infrastructure destruction

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#5419]
I created a Heroku plan with an addon:

```
resource "heroku_app" "app" {
  name = "${var.app_name}"
}

resource "heroku_addon" "cloudinary" {
  app = "${heroku_app.app.name}"
  plan = "cloudinary:${var.cloudinary_plan}"
}
```

This works and does create the app and the Cloudinary addon according to the provided name. After a couple of successful tests, I went ahead and manually deleted the apps on Heroku since I didn't actually need them.

I made some changes my `.tf` files locally to try some more things out, but `terraform plan` was not happy with the remote resource no longer existing. No big deal, I assume that Heroku and the terraform state are inconsistent now.

Problem is, I couldn't really find a way to reset the state other than just manually removing the `.tfstate` file which seems a bit weird to me.

`terraform destroy` won't work because the app is not there.

I also tried using `terraform taint`, but due to #1768 I had to taint both the app and addon individually whereas I want to indicate that the entire infrastructure is destroyed at once. However, even after `terraform taint` neither `destroy` nor `plan` would work. I _had_ to remove the `.tfvars`.

If there is not already a correct way to do this an option for `terraform destroy` or even a separate command like `terraform reset` would be handy if you have already manually destroyed some or all of your infrastructure.

**Comment by thatderek** [comment]
Had you tried `refresh`? https://www.terraform.io/docs/commands/refresh.html

**Comment by ajcrites** [comment]
@thatderek I get the same error using `refresh` as I do with `destroy` -- it complains that the remote app could not be found even if I taint it.

**Comment by jen20** [comment]
Hi @ajcrites! Thanks for opening this issue. `Refresh` is called as part of a plan, and then again as part of an apply, so this is a bug in the Heroku provider - one of the main things Terraform is supposed to do is resolve these differences. I'll mark this as a bug and we'll address it. In the meantime you may be able to remove the relevant section from your state file manually, and proceed from there as a workaround.

**Comment by catsby** [comment]
Hello there – for future readers, Terraform does now have more commands for working with the state file. 

In this instance, you could `rm` it from state:

    $ terraform rm heroku_app.app 
    $ terraform rm heroku_addon.cloudinary

I'm going to close this issue for now, but I've also opened 2 new issues to address the error(s) you saw once you deleted the App and addon out of band from Terraform:

- #14286
- #14287
