### ISSUE TITLE
Unable to get variables from tfstate

### ISSUE THREAD

**Issue by sheerun** [hashicorp/terraform#5424]
Hey,

I'd like to know what variables were used when running `terraform apply` but all I can get from `tfstate` is set of resources and outputs.. So I can only see values of variables as part of them. I'd like to see initial set of variables instead. Why isn't it possible? Could you incorporate initial variables into `tfstate`?

**Comment by mitchellh** [comment]
This isn't possible currently mostly due to not having a good answer to #516 and variables generally contain access variables. There isn't a likely scenario where this is fixed in the short term so I'm going to close this instead of having it become stale. Sorry!
