### ISSUE TITLE
TestAccComputeVpnTunnel_basic fails

### ISSUE THREAD

**Issue by evandbrown** [hashicorp/terraform#5431]
Separating this issue out from several reported in #5385. The TestAccComputeVpnTunnel_basic began failing after the GCE API began validating the peerIp field and rejecting any RFC5735 values. It appears this was introduced ~3 weeks ago based on the [last successful test run](https://travis-ci.org/hashicorp/terraform/builds/108197215).

**Comment by jen20** [comment]
Hi @evandbrown! Looks like this is resolved now your PR at #5433 has been merged. Please feel free to reopen if this is not the case. Thanks!
