### ISSUE TITLE
Global Tags for AWS provider

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform#5435]
I apologize if this has already been written up in an issue, I searched but didn't find anything.

We use cost allocation tags in our AWS account when doing our reports for accounting purposes.  When building out a Terraform environment, the vast majority of resources should all be tagged very similarly (owner, environment, app) and then we set / override tags in each specific resource on a case by case basis (specific service something is running, ie. consul, etc).  It would be nice not to have to redundantly specify these tags on every resource that supports them (and also keep up to date on when tag support is added to a resource and have to go back and add those). It would also be nice for tags to flow down through modules using the same provider.

I can see a couple possible solutions:

* Global tags set on the aws provider
* Some ability to merge a map of tags in to resources instead of manually writing out each tag k/v pair, but the issue with this is child module support.

**Comment by gusmat** [comment]
+1

**Comment by joshuaspence** [comment]
+1

**Comment by paultyng** [comment]
This is probably a same / duplicate of #2283.

Some other related issues: #3531, #5356, #4380

**Comment by serialseb** [comment]
Yes indeed, same as #2283

**Comment by apparentlymart** [comment]
I'm going to close this in favor of #2283, to consolidate the discussion. Thanks, @paultyng!

**Comment by huyanhvn** [comment]
+1

**Comment by farvour** [comment]
+1

**Comment by spacefuntus** [comment]
+1
