### ISSUE TITLE
AWS Aurora - Changing Instance size forces destruct - Doesn't recognise instance size change

### ISSUE THREAD

**Issue by boxrick** [hashicorp/terraform#5436]
AWS allows you to change the instance size "On the fly" without any downtime, this is also supported on a normal RDS instance on Terraform.

1) If you are using Cluster DB ( Aurora ), changing the instance size causes a destruction of the resource. This is obviously wrong and un-needed 

2) A similar issue with this, is if the instance size is changed manually Terraform does not detect and try to rectify the issue.

**Comment by chrisfu** [comment]
+1. Terraform seems to want to destroy even when making even the most trivial of changes to a cluster... even when it comes to adding/removing CIDR from an associated security group.

**Comment by bsiegel** [comment]
Seems like this will be addressed by #5710

**Comment by stack72** [comment]
Fixed via #6865
