### ISSUE TITLE
AWS: internal ENI causes crash

### ISSUE THREAD

**Issue by alsonkemp** [hashicorp/terraform#5438]
AWS internal services can have ENIs assigned to them and this causes a null pointer dereference in Terraform.  I did a *terraform refresh* and got a fairly non-descriptive error:

    [... snip ...]
    aws_security_group.sg-e440d580-MProdRDS-MProdDBSecurityGroup-IF10EBC2VT0F: Refreshing state... (ID: sg-e440d580)
    aws_network_interface.eni-f7e90baa: Refreshing state... (ID: eni-f7e90baa)
    aws_elb.api-elb-internal-prod: Refreshing state... (ID: api-elb-internal-prod)
    Error refreshing state: 932 error(s) occurred:

    * aws_route53_record.kdb-internal-m-private-prod-com-CNAME: unexpected EOF
    * aws_network_interface.eni-2498a35c: unexpected EOF
    * aws_iam_role_policy.MJenkinsS3DeployBucket: connection is shut down
    * aws_network_interface.eni-248e4a6e: connection is shut down
    [... snip ...]

Looks as though an exception was swallowed, so I put together a small Python script to iterate *terraform refresh* over each resource:

    aws_network_interface.eni-9b915ee2: unexpected EOF
    panic: runtime error: invalid memory address or nil pointer dereference
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x581e9c]
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: goroutine 67 [running]:
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: panic(0x10ef260, 0xc82000a130)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsNetworkInterfaceRead(0xc82042a3c0, 0xe10b60, 0xc820388000, 0x0, 0x0)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_network_interface.go:143 +0xb7c
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc820313400, 0xc82012a450, 0xe10b60, 0xc820388000, 0xc820228478, 0x0, 0x0)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x43a
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc820329b60, 0xc820105380, 0xc82012a450, 0x1, 0x0, 0x0)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc8201a9fc0, 0xc820130130, 0xc820130450, 0x0, 0x0)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: reflect.Value.call(0x103d360, 0x12dc798, 0x13, 0x137ecb8, 0x4, 0xc8200f7ed8, 0x3, 0x3, 0x0, 0x0, ...)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: reflect.Value.Call(0x103d360, 0x12dc798, 0x13, 0xc8200f7ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc820362680, 0xc820362640, 0xc8202c5780, 0xc820237900, 0xc8202d0da0, 0xe11ca0, 0xc820130130, 0x16, 0xe11d00, 0xc820130450, ...)
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
    2016/03/02 15:30:10 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
    2016/03/02 15:30:10 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_network_interface.eni-9b915ee2: unexpected EOF
    2016/03/02 15:30:10 [ERROR] root: eval: *terraform.EvalSequence, err: aws_network_interface.eni-9b915ee2: unexpected EOF
    2016/03/02 15:30:10 [ERROR] root: eval: *terraform.EvalOpFilter, err: aws_network_interface.eni-9b915ee2: unexpected EOF
    2016/03/02 15:30:10 [ERROR] root: eval: *terraform.EvalSequence, err: aws_network_interface.eni-9b915ee2: unexpected EOF
    2016/03/02 15:30:10 [TRACE] [walkRefresh] Exiting eval tree: aws_network_interface.eni-9b915ee2
    2016/03/02 15:30:10 [DEBUG] /home/alson/apps/terraform-provider-aws: plugin process exited
    2016/03/02 15:30:10 [DEBUG] vertex provider.aws (close), got dep: aws_network_interface.eni-9b915ee2
    2016/03/02 15:30:10 [DEBUG] waiting for all plugin processes to complete...
    
    EXCEPTION: Command 'terraform refresh --target=aws_network_interface.eni-9b915ee2' returned non-zero exit status 1`

All of the failures correspond to ENIs which are allocated by Elasticache, ELB, etc instances.  I'll remove the ENIs from my tfstate file (which was generated by *terraforming* (<- handy that...)) but wanted to raise this as an issue.

Another detail: these ENIs do not have attachments:

    resource "aws_network_interface" "eni-a36302e8" {
        subnet_id         = "subnet-5d0c612a"
        private_ips       = ["10.204.1.235"]
        security_groups   = ["sg-dc8dfeb8"]
        source_dest_check = true
    }

**Comment by jen20** [comment]
Hi @alsonkemp! Thanks for opening this issue. Could you confirm that you are using Terraform 0.6.12 in this test? Thanks.

**Comment by alsonkemp** [comment]
@jen20 Confirmed.  Just updated yesterday in case it fixed this issue...

**Comment by catsby** [comment]
This panic is happing on the same line as #5618

**Comment by catsby** [comment]
Hey @alsonkemp – you don't have a sample or snippet of config that shows how that ENI is being used by chance, do you? If you can share, please remove any secrets .

Thanks!

**Comment by alsonkemp** [comment]
@catsby I was able to put together the following:

nif.tf
```
resource "aws_network_interface" "eni-53ba0e19" {
        subnet_id         = "subnet-ffd0bd88"
        private_ips       = ["10.205.1.116"]
        security_groups   = ["sg-6adcae0e"]
        source_dest_check = true
}
```

terraform.tfstate

```
{
    "version": 1,
    "serial": 774,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "aws_network_interface.eni-53ba0e19": {
                    "type": "aws_network_interface",
                    "primary": {
                        "id": "eni-53ba0e19",
                        "attributes": {
                            "id": "eni-53ba0e19",
                            "private_ips.#": "1",
                            "private_ips.1343215115": "10.205.22.135",
                            "security_groups.#": "1",
                            "security_groups.183107813": "sg-6adcae0e",
                            "source_dest_check": "true",
                            "subnet_id": "subnet-ffd0bd88",
                            "tags.#": "0"
                        }
                    }
                }
            }
        }
    ]
}
```

Error:

```
alson@tortuga : 02:23 PM : $ terraform refresh
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: us-west-2

aws_network_interface.eni-53ba0e19: Refreshing state... (ID: eni-53ba0e19)
Error refreshing state: 1 error(s) occurred:

* aws_network_interface.eni-53ba0e19: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x586e4c]
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: goroutine 42 [running]:
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: panic(0x10fdde0, 0xc82000a140)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsNetworkInterfaceRead(0xc820152000, 0xe1dfc0, 0xc820344900, 0x0, 0x0)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_network_interface.go:143 +0xb7c
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc82037e3c0, 0xc820148330, 0xe1dfc0, 0xc820344900, 0xc82032cc80, 0x0, 0x0)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:210 +0x43a
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc8203a0990, 0xc8204ae640, 0xc820148330, 0x1, 0x0, 0x0)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc8202a5720, 0xc82045e090, 0xc82045e3e0, 0x0, 0x0)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: reflect.Value.call(0x104b8e0, 0x12ec158, 0x13, 0x138e960, 0x4, 0xc8202f3ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:435 +0x120d
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: reflect.Value.Call(0x104b8e0, 0x12ec158, 0x13, 0xc8202f3ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/reflect/value.go:303 +0xb1
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc82037f640, 0xc82037f600, 0xc82037a970, 0xc820335400, 0xc8202a5e80, 0xe1f100, 0xc82045e090, 0x16, 0xe1f160, 0xc82045e3e0, ...)
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:383 +0x1c2
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/03/15 14:23:25 [DEBUG] terraform-provider-aws: 	/opt/go/src/net/rpc/server.go:477 +0x49d
2016/03/15 14:23:25 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_network_interface.eni-53ba0e19: unexpected EOF
2016/03/15 14:23:25 [DEBUG] /home/alson/apps/terraform-provider-aws: plugin process exited
2016/03/15 14:23:25 [ERROR] root: eval: *terraform.EvalSequence, err: aws_network_interface.eni-53ba0e19: unexpected EOF
2016/03/15 14:23:25 [ERROR] root: eval: *terraform.EvalOpFilter, err: aws_network_interface.eni-53ba0e19: unexpected EOF
2016/03/15 14:23:25 [ERROR] root: eval: *terraform.EvalSequence, err: aws_network_interface.eni-53ba0e19: unexpected EOF
2016/03/15 14:23:25 [TRACE] [walkRefresh] Exiting eval tree: aws_network_interface.eni-53ba0e19
2016/03/15 14:23:25 [DEBUG] vertex provider.aws (close), got dep: aws_network_interface.eni-53ba0e19
2016/03/15 14:23:25 [DEBUG] waiting for all plugin processes to complete...



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by catsby** [comment]
Thank you so much for the reproducer! We'll look into this soon

**Comment by catsby** [comment]
Hey @alsonkemp I'm having trouble reproducing this on `master`. I started with this config:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "foo" {
  cidr_block = "172.16.0.0/16"
}

resource "aws_subnet" "foo" {
  vpc_id            = "${aws_vpc.foo.id}"
  cidr_block        = "172.16.10.0/24"
  availability_zone = "us-west-2a"
}

resource "aws_security_group" "foo" {
  vpc_id      = "${aws_vpc.foo.id}"
  description = "foo"
  name        = "foo"
}

resource "aws_network_interface" "bar" {
  subnet_id         = "${aws_subnet.foo.id}"
  private_ips       = ["172.16.10.100"]
  security_groups   = ["${aws_security_group.foo.id}"]
  source_dest_check = true

  tags {
    Name = "bar_interface"
  }
}
```

The line referenced in your crash doesn't line up with master anymore, in v0.6.12 it's [this line][1], which as a `nil` guard before it...

Not to shift blame but I'm curious if the `terraforming` tool is mudding the water here... can you confirm for me that all the attributes referenced by that ENI exist? The SG exists with that ID, the Subnet, etc? 





[1]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_network_interface.go#L156

**Comment by catsby** [comment]
Hey all – haven't heard back for some time, so I'd like to consider this closed. 

If anyone is still hitting this issue please let us know. I _think_ it's related to the Terraforming tool, but without more data and a reproduction case I can't quite confirm. 

As I mention above, the specific line in question has a `nil` guard so I think we're safe at this time. If anyone else hits this please let us know and I can take another look.

Thanks!
