### ISSUE TITLE
Error in updating subnet, results in deletion of existing instance

### ISSUE THREAD

**Issue by yahyapo** [hashicorp/terraform#544]
Refer to this gist : https://gist.github.com/snehaso/53f7d1705b226e668d7e

This creates a stack with a public subnet and an instance within it.
On updating the CIDR range of the subnet to an invalid number, the "terraform plan" tells me that it is deleting and re-creating the instance.
On running "terraform apply" it gives me an obvious error that the subnet has an invalid CIDR but the instance is deleted and remains that way.

**Comment by mitchellh** [comment]
I can't reproduce this anymore, so I'm assuming its fixed at some point. If I'm wrong please post another repro case. Thanks!
