### ISSUE TITLE
Switching from AWS NAT instances to NAT Gateway and re-use the same Elastic IPs

### ISSUE THREAD

**Issue by senthuran-td** [hashicorp/terraform#5443]
Currently, our NAT IPs are white listed at the customer end and I want to change the NAT services from instances to AWS gateway services.
Could I able to do the changes in one execution plan (in one direct apply command)? 

When I run this following *.tf, I get cycle error

```hcl
resource "aws_nat_gateway" "nat" {
  count         = "${length(split(",", var.public_subnets))}"
  subnet_id     = "${element(split(",", module.public_subnet.subnet_ids), count.index)}"
  allocation_id = "${element(aws_eip.nat.*.id, count.index)}"
}

resource "aws_eip" "nat" {
  vpc      = true
  count    = "${length(split(",", var.public_subnets))}"
  network_interface = "${element(aws_nat_gateway.nat.*.network_interface_id, count.index)}"
  lifecycle {
    prevent_destroy = true
  }
}
```

error:

```
Errors:

  * 2 error(s) occurred:

* Cycle: aws_eip.nat (destroy), aws_nat_gateway.nat (destroy)
* Cycle: aws_nat_gateway.nat, aws_eip.nat
```

**Comment by stack72** [comment]
Hi @senthuran-td 

Apologies for not getting back to you in so long for this. For this particular usecase, we introduced a new resource - https://www.terraform.io/docs/providers/aws/r/eip_association.html

You can associate an existing EIP to a NAT Gateway and therefore when you destroy, you are only destroying the association NOT the EIP

Hope this helps

Paul
