### ISSUE TITLE
vSphere provider tutorial fails

### ISSUE THREAD

**Issue by Supernomad** [hashicorp/terraform#5448]
Currently in the vSphere provider tutorial the `name` attribute is set to a name with an underscore in it.

However this causes VMWare customization to fail when the node is brought up. 

The error returned from VMWare is: 
```
vsphere_virtual_machine.web: A specified parameter was not correct.
spec.identity.hostName
```

Searching around I finally figured out what it meant via this doc, specifically in the `Resolution` section:
https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2009820

Terraform Version:
```
terraform -v
Terraform v0.6.12
```

vSphere Version:
```
VMWare vSphere v5.5 U2
```

Really just bringing it up so if someone searches for the issue they can find the resolution more easily, as it really doesn't have anything to do with Terraform itself.

**Comment by phinze** [comment]
Thanks @Supernomad! Fixed up on master and will go out w/ next site deploy. :+1:

**Comment by Supernomad** [comment]
Awesome glad it was useful @phinze
