### ISSUE TITLE
[Openstack] Terraform Crashed during instance metadata parsing

### ISSUE THREAD

**Issue by kamaltherocky** [hashicorp/terraform#5451]
Attached the crash log
[crash.log.txt](https://github.com/hashicorp/terraform/files/157666/crash.log.txt)

**Comment by jtopjian** [comment]
@kamaltherocky Can you upgrade to 0.6.11? This bug should have been fixed in that release. Let me know if it still happens, though.

**Comment by jtopjian** [comment]
I re-read the crash log and can confirm this bug was fixed in a previous version. I'm going to close this issue, but please feel free to re-open if you're still running into it.
