### ISSUE TITLE
terraform should support interpolation in module source parameter

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform#5452]
I want to pull module source code from different locations depending upon environment.  Given that it's in  a BitBucket repo, the root path to the repo will differ based on location.  For example, I currently have this:

`source = "git::ssh://git@stash.dev.mycompany.com/terraform/modules/module.git"`

I want to be able to do this:

`source = "${var.git_server}/terraform/modules/module.git"`

Where:
`variable "git_server" { 
  default = {
   "dev" = "git::ssh://git@stash.dev.mycompany.com"
   "qa"  = "git::ssh://git@stash.qa.mycompany.com"
   "stage" = "git::ssh://git@stash.stage.mycompany.com"
   "prod" = "git::ssh://git@stash.prod.mycompany.com"
 }
}`

Or, since I currently use a python wrapper around terraform to auto-select my -var-file option based on an environment name, I could simply have in my environment file settings for each one:
`
variable "git_server" { default = "git::ssh://git@stash.dev.mycompany.com" }
variable "git_server" { default = "git::ssh://git@stash.dev.mycompany.com" }
variable "git_server" { default = "git::ssh://git@stash.dev.mycompany.com" }
`
Further, if I'm importing a shared state from consul or S3, I might want to infer my git server from that state via an output variable.

Not being able to do this:
- Causes unnecessary repetition of code (violates the DRY principle)
- Reduces flexibility
- Reduces code re-use
- Prevents sharing of common infrastructure.

**Comment by igorlg** [comment]
+1

**Comment by phinze** [comment]
Hi there, thanks for the report - consolidating this down with https://github.com/hashicorp/terraform/issues/1439 which has a lot more discussion.
