### ISSUE TITLE
RDS Enhanced Monitoring MonitoringRoleARN value is required

### ISSUE THREAD

**Issue by deanmraz** [hashicorp/terraform#5455]
I am getting an weird issue with trying to enable RDS enhanced monitoring..

* aws_db_instance.mysql: Error modifying DB Instance <name>: InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.

I do have the variable set and I've copied the implementation used in the test case here: https://github.com/stack72/terraform/commit/e87d3bb711c1e1da134e0911d194a999ee62a77e

I wonder if it has something to do with expecting capital ARN in MonitoringRoleARN, but when I try various variables it fails as invalid. 

My implementation: 
```
  monitoring_role_arn = "${aws_iam_role.enhanced_policy_role.arn}"
  monitoring_interval = "${var.enhanced_monitoring_interval}"
```

Also, confirmed that the role and policy gets created with the right access. I manually turned on the enhanced monitoring and it worked using the role created by terraform. 

@stack72 do you have any ideas?

**Comment by deanmraz** [comment]
still playing around with this... Removing the role and the policy and trying again I get this error first: 

* aws_db_instance.mysql: Error modifying DB Instance <name>: InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: ENHANCED_MONITORING

then trying again I get the 
`MonitoringRoleARN value is required` 

I also have the depends_on defined on the aws_db_instance resource 
`depends_on = ["aws_iam_policy_attachment.policy-attach"]`

**Comment by deanmraz** [comment]
Ensuring role created before policy attachment fixed this issue for me
```
resource "aws_iam_policy_attachment" "policy-attach" {
  depends_on = ["aws_iam_role.enhanced_policy_role"]
```

**Comment by deanmraz** [comment]
That wasn't it.. looks like theres an issue with attaching the policy to multiple roles across regions. The last one ran gets the attached profile while the rest are blank. Instead of using attach policy resource I created a custom policy with the enhanced policy. 

```
resource "aws_iam_role_policy" "policy" {
  depends_on = ["aws_iam_role.enhanced_policy_role"]
  name = "enhanced-monitoring-attachment-${var.mysql_base_name}-${var.mysql_name}"
  role = "${aws_iam_role.enhanced_policy_role.name}"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EnableCreationAndManagementOfRDSCloudwatchLogGroups",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:PutRetentionPolicy"
            ],
            "Resource": [
                "arn:aws:logs:*:*:log-group:RDS*"
            ]
        },
        {
            "Sid": "EnableCreationAndManagementOfRDSCloudwatchLogStreams",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "logs:GetLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:*:*:log-group:RDS*:log-stream:*"
            ]
        }
    ]
}
EOF
}
```

**Comment by stack72** [comment]
@deanmraz this was a really good find. Is this now resolved?

**Comment by deanmraz** [comment]
@stack72 yup confirmed its working!

**Comment by stack72** [comment]
Nice thanks for this @deanmraz

**Comment by sandyfox** [comment]
I don't see it working. I have a preconfigured role that I would like to attach which is out of terrafrom and I am passing it as a variable to aws_db_instance resource. Its still failing with same error

InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0

**Comment by bflad** [comment]
For continued tracking of this issue, its probably best to continue the discussion in the open AWS provider issue here: https://github.com/terraform-providers/terraform-provider-aws/issues/315

I believe I tried reproducing it awhile ago and wasn't successful, but maybe the more recent folks here can provide samples of their configurations before and after so we can get this fixed up once and for all (or at least document why this behavior occurs).
