### ISSUE TITLE
Missing case in resource_docker_image_funcs.go

### ISSUE THREAD

**Issue by rhyas** [hashicorp/terraform#5456]
There seem to be several functions that are missing the use case where an Image can be defined as "user/repo:tag"

**Comment by phinze** [comment]
Hi @rhyas - can you provide a bit more detail here? Is this missing functionality or missing documentation? You can find tips on what is helpful to include in our [contributing guidelines](https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md#issues). Thanks!

**Comment by rhyas** [comment]
I think it's missing functionality, but I need to debug a little bit more. Basically, here's the error in a nutshell:

Here's my resource definition:

resource "docker_image" "config" {
    name = "myuser/server:cfg"
}

Here's what happens when I apply using that resource:

`
Error applying plan:

1 error(s) occurred:

* docker_image.config: Unable to read Docker image into resource: Unable to pull image myuser/server:cfg: Error pulling image myuser/server:cfg: Error: image myuser/server not found

Which seems it's dropping the tag somewhere along the line. My initial poke through the code probably relied on the comments too much, because there's no commented account of the specific "user/repo:tag" case on any of the functions. But digging deeper, that seems to work in most cases regardless of the comments. 

I should note that the apply works fine if there's already a local copy of the image/tag, so it only has an issue when it has to pull a fresh image from docker hub. 

So something is still not quite right there. I leave it up to you if you want to use this bug around for now for discussion, or if you want me to file a new one that's less specific to the code in question, and more specific to the actual reproduce-able error.

**Comment by rhyas** [comment]
I'm going to close this, because after digging around, this is not an issue with tag/repo processing, it turns out it's one dealing with authentication, or rather, lack thereof.
