### ISSUE TITLE
Documentation for aws_autoscaling_group (vpc_zone_identifier) is contradictory

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#5457]
https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html

First occurrence:
```
vpc_zone_identifier (Optional) A list of subnet IDs to launch resources in. 
```

Second occurrence further down the page:
```
vpc_zone_identifier - The VPC zone identifier
```

**Comment by phinze** [comment]
Hi @FransUrbo - thanks for the report. The source for our docs is [in this repo](https://github.com/hashicorp/terraform/tree/master/website). Would you be able to make a PR with a fix for this inconsistency?

**Comment by catsby** [comment]
Fixed in #5580

**Comment by FransUrbo** [comment]
Ehm... I was more indicating the <code>a list of subnet IDs</code> visavi <code>VPC zone IDs</code>. Is it a list of subnets or VPCs??

**Comment by dguisinger** [comment]
I agree, the documentation doesn't communicate what you actually need to know to use it.  A VPC Zone ID is not a Subnet ID or list of...
