### ISSUE TITLE
Clarification on the aws_autoscaling_group documentation

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#5458]
https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#launch_configuration

Reading up on the AWS ASG, I see that it's possible to create an ASG from a EC2 Instance (http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/create-asg-from-instance.html#create-asg-from-instance-console).

The <code>launch_configuration</code> in the Terraform resource <code>aws_autoscaling_group</code>, does that allow for an instance?

**Comment by phinze** [comment]
Hi @FransUrbo - we don't currently support the ASG-from-instance feature of the API, which is why we require a `launch_configuration` parameter at this point. We'd welcome a PR to add that functionality though! :+1:

**Comment by FransUrbo** [comment]
[I've been away so I haven't been working on this in over a week, but now I'm back at trying to create ASGs for the environment].

How do I provision a <code>launch_configuration</code> (and <code>aws_elb</code>) then? I "converted" my <code>aws_instance</code> to a <code>aws_launch_configuration</code> (with all my <code>connection</code>, <code>provisioner "file"</code> and <code>provisioner "remote-exec"</code>s etc, but all I get is:

```
module.ENVIRONMENT.aws_elb.INSTANCE: Creating...
[....]
Error applying plan:

1 error(s) occurred:

* aws_elb.INSTANCE: timeout while waiting for state to become '[success]'
```

And this when I try to create <code>module.ENVIRONMENT.aws_autoscaling_group.INSTANCE</code> (which depend on <code>module.ENVIRONMENT.aws_launch_configuration.INSTANCE</code>, which depend on <code>module.ENVIRONMENT.aws_elb.INSTANCE</code>).

There's nothing in the documentation about provisioning a ELB or LC...

**Comment by FransUrbo** [comment]
Never mind. It might be another issue (or my misunderstanding of the documentation). The problem was the following section in the <code>aws_elb</code> resource:

```
  listener {
    instance_port = 443
    instance_protocol = "https"
    lb_port = 443
    lb_protocol = "https"
    ssl_certificate_id = "arn:aws:iam::123456789012:server-certificate/certName"
  }
```

Looking at it now, the <code>123456789012</code> is probably something I'll need to change from my own setup :).
