### ISSUE TITLE
Issue with resource "aws_volume_attachment"

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#5459]
Suddenly after successfully provisioning and attaching several volumes to instances as they launch I am now getting a self reference complaint.

```
terraform : [31mError configuring: 1 error(s) occurred:
At line:1 char:1
+ terraform plan
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([31mError conf...or(s) occurred::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
* Self reference: aws_instance.HOSTNAME[0m[0m
```

**Comment by davyt10** [comment]
This is block of code causing the issue.

resource "aws_volume_attachment" "HOST_Data" {
  device_name = "xvdf"
  volume_id = "${aws_ebs_volume.HOST_Data.id}"
  instance_id = "${aws_instance.HOST.id}"
}

**Comment by phinze** [comment]
HI @davyt10 - sorry for the trouble here. Do you think you could provide the full config you're using to help us try to reproduce the bug?

**Comment by davyt10** [comment]
elf.tf contains Vol creation code;

resource "aws_ebs_volume" "QA01T01QINSV01_Logs" {
    availability_zone ="${var.availability_zone.AZa}"
    size = 10
    type = "gp2"
    encrypted = "true"

    tags {
Hostname = "QA01T01QINSV01"
Label = "Logs"
MountPoint = "L"
Application= "${var.application}"
MakeSnapshot= "true"
Device = "xvdg"
Environment = "${var.environment}"

    }
}

instance.tf contains ec2  instance resource creation and vol attachment

    resource "aws_instance" "QA01T01QINSV" {
    count =1
    ami = "${var.ami.Server2k8R2}"
    availability_zone ="${var.availability_zone.AZa}"
    key_name = "${var.aws_key_name}"
    instance_type = "c4.xlarge"
    vpc_security_group_ids = ["${aws_security_group.SG_EUW1_QA01_INFSVC.id}"] 
    iam_instance_profile = "S3-SSI-ISO-RO-ACCESS"
    subnet_id = "${var.Subnet.private_subnet_64}"
    /* user_data = "${file("Server-Install-AWS.ps1")}" */
   
    tags {

        Name = "QA01T01QINSV0${count.index+1}"
        Environment = "${var.environment}"
        Application="${var.application}"
        AppicationAttributes = "{\"Template\":\"T01\", \"Version\":\"xxx\", \"SubApp\":\"\", \"ServerFriendlyName\":\"xxx\", \"OwnerAppEnvironment\":\"xxx\"}"
        ApplicationRole= "InfrastructureServices"
        Owner = "{\"Email\":\"xxx\", \"Dept\":\"DublinDev\"}"


    } 

resource "aws_volume_attachment" "QA01T01QINSV01_Logs" {
  device_name = "xvdg"
  volume_id = "${aws_ebs_volume.QA01T01QINSV01_Logs.id}"
  instance_id = "${aws_instance.QA01T01QINSV.id}"
}

**Comment by phinze** [comment]
Okay, I'm having trouble reproducing the `Self reference: ` error message using the configs you specified.

Here's a stripped down version of the config you provided that seems to work properly:

```tf
resource "aws_ebs_volume" "QA01T01QINSV01_Logs" {
  size              = 10
  type              = "gp2"
  encrypted         = "true"
  availability_zone = "${aws_instance.QA01T01QINSV.availability_zone}"

  tags {
    Hostname = "QA01T01QINSV01"
  }
}

resource "aws_instance" "QA01T01QINSV" {
  ami           = "ami-d12cceb1"
  instance_type = "t2.nano"

  tags {
    Name = "QA01T01QINSV0${count.index+1}"
  }
}

resource "aws_volume_attachment" "QA01T01QINSV01_Logs" {
  device_name = "xvdg"
  volume_id   = "${aws_ebs_volume.QA01T01QINSV01_Logs.id}"
  instance_id = "${aws_instance.QA01T01QINSV.id}"
}
```

Can you spot any differences between this config and your config that generates the error?

**Comment by phinze** [comment]
Hi again @davyt10 - happy to continue to work with you on this, but I'm going to close the issue for now. Let me know if you'd like to dig in further and I can reopen! :+1:

**Comment by davyt10** [comment]
Hi Paul,

Thanks, the issue was my side.
