### ISSUE TITLE
Non descript error when key_name does not exist or mispelled

### ISSUE THREAD

**Issue by dustingraves** [hashicorp/terraform#5463]
Terraform apply would error with:

Error applying plan:

1 error(s) occurred:
```

aws_launch_configuration.etcd: Creating...
  ...
  key_name:                    "" => "key-name.pem"
  ...

* aws_launch_configuration.etcd: Error creating launch configuration: timeout while waiting for state to become '[success]'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
This would happen if `key_name` had an incorrect value, ie:

incorrect: `key-name.pem` 
actual: `key-name`

This was tested against v0.6.11 and v0.6.12

**Comment by phinze** [comment]
Thanks for the report @dustingraves - this should definitely display a better error message. I've got a fix for some related error message shadowing in #5460, but we should double check this case specifically once that lands since I'm surprised this didn't return immediately - seems like it should.

**Comment by jen20** [comment]
Hi @dustingraves! This is part of a wider group of issues which is being tracked by a meta-issue over at #5537. Thanks for reporting this!

In this case I'll leave this issue open so that we can circle back to it and ensure that we are making appropriate checks during the plan phase.

**Comment by stack72** [comment]
Hi @dustingraves 

Can you tell me if this issue is still happening for you? We believe we have solved the `timeout` error message. This means an actual error message should be found now

thoughts?

Paul

**Comment by stack72** [comment]
Closed as no response - please feel free to comment if this is still happening
