### ISSUE TITLE
google_compute_network error

### ISSUE THREAD

**Issue by xuwang** [hashicorp/terraform#5465]
```shell
$ terraform version
Terraform v0.6.12
```
Doc: [providers>google>compute_network](https://www.terraform.io/docs/providers/google/r/compute_network.html)

network.tf:
```
...
resource "google_compute_network" "ha_demo" {
    name = "ha-demo"
    auto_create_subnetworks = true
}
...
```
```shell
$ terraform apply
google_compute_network.ha_demo: Creating...
  auto_create_subnetworks: "" => "1"
  gateway_ipv4:            "" => "<computed>"
  name:                    "" => "ha-demo"
  self_link:               "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* google_compute_network.ha_demo: Error creating network: googleapi: Error 400: Invalid value for project: ha-demo-20160303, invalid
```
Simple enough, let me know if this works.
Thanks, 
Xu Wang

**Comment by phinze** [comment]
Hi @xuwang - thanks for the report.

The error `Invalid value for project: ha-demo-20160303, invalid` seems to point to some sort of an authentication problem. Are you able to create other resources in your google account using the same credentials?

**Comment by xuwang** [comment]
My mistake, used a wrong project id.  close this issue.

THANK YOU!
