### ISSUE TITLE
ability to specify prevent_destroy via variable

### ISSUE THREAD

**Issue by timothykimball** [hashicorp/terraform#5481]
We use modules extensively to help us compose complex infrastructure out of lots of smaller parts.

When testing, prevent_destroy should not get in the way.

In production, prevent_destroy should only be applied to the critical entities. And we should be able to turn it off/on w/o having to modify shared modules between different instances of infrastructure.

The way we do this is by specifying a variable in the top level main.tf for the particular instance indicating wether we should care or not about critical infrastructure not getting accidentally deleted.

From what I can see, specifying prevent_destroy as a variable is not supported by terraform. When we do it, we receive the following error:

```
* cannot parse 'prevent_destroy' as bool: strconv.ParseBool: parsing "${var.prevent_destroy_vault_data}": invalid syntax
```

Maybe it is and I am doing something dumb?

Thanks for a great product btw. You guys rock...

T

**Comment by radeksimko** [comment]
I believe a similar, more generic issue (related to the whole `lifecycle` block) is tracked under https://github.com/hashicorp/terraform/issues/5346

Do you think we can close this issue in favour of https://github.com/hashicorp/terraform/issues/5346 and keep the discussion in one place?

**Comment by stack72** [comment]
Closing in favour of #5346
