### ISSUE TITLE
Unable to create instance with VPC using vpc_security_group_ids

### ISSUE THREAD

**Issue by cjohannsen81** [hashicorp/terraform#5486]
Hi,

I created a new VPC in AWS (non-default) and used it:

```hcl
resource "aws_instance" "prov-node" {
    ami = "ami-ad8894c1"
    key_name = "${var.aws_keypair}"
    vpc_security_group_ids = ["vpc-b0720bd9"]
    availability_zone = "eu-central-1a"
    instance_type = "m3.large"
    tags {
      Name = "Chef Provisioning Node"

      }
      provisioner "remote-exec" {
        inline = [
          "sudo apt-get -y update",
          "sudo apt-get -y install nginx",
          "sudo service nginx start"
        ]
      }
}

```
It always fails with:

```
* aws_instance.prov-node: Error launching instance, possible mismatch of Security Group IDs and Names. See AWS Instance docs here: https://terraform.io/docs/providers/aws/r/instance.html.

	AWS Error: Value () for parameter groupId is invalid. The value cannot be empty

```

I´m using Terraform v0.6.12 and the VPC is created in AWS:

chef
vpc-b0720bd9
available
172.16.0.0/20
dopt-e8e40a81
rtb-91155cf8
acl-e1e4a888
Default
No

Am I missing something?

**Comment by radeksimko** [comment]
Hi @cjohannsen81 
I think this is the causing the problem:

```
vpc_security_group_ids = ["vpc-b0720bd9"]
```

the field expects **group IDs**, not VPC IDs.

Feel free to reopen if you're still having issues.

**Comment by radeksimko** [comment]
Also you'll need to specify the [`subnet_id`](https://www.terraform.io/docs/providers/aws/r/instance.html#subnet_id) and use subnet which is part of that VPC, otherwise default VPC is used instead.

**Comment by cjohannsen81** [comment]
Urgh, my fault! Thanks!

**Comment by manjunath6681** [comment]
this is not working for me. 

resource "aws_instance" "JumpBox" {
  ami           = "${data.aws_ami.jenkins.id}"
  instance_type = "t2.micro"
  subnet_id = "${aws_subnet.public_subnet.id}"
  vpc_security_group_ids = ["${aws_security_group.public_ssh_sg.id}"]

}

when i run Terraform Plan, The vps_security_group_ids shows not show the sg id i am setting instead displays <computed>


+ aws_instance.JumpBox
    ami:                          "ami-700f8913"
    associate_public_ip_address:  "<computed>"
    availability_zone:            "<computed>"
    ebs_block_device.#:           "<computed>"
    ephemeral_block_device.#:     "<computed>"
    instance_state:               "<computed>"
    instance_type:                "t2.micro"
    ipv6_address_count:           "<computed>"
    ipv6_addresses.#:             "<computed>"
    key_name:                     "<computed>"
    network_interface.#:          "<computed>"
    network_interface_id:         "<computed>"
    placement_group:              "<computed>"
    primary_network_interface_id: "<computed>"
    private_dns:                  "<computed>"
    private_ip:                   "<computed>"
    public_dns:                   "<computed>"
    public_ip:                    "<computed>"
    root_block_device.#:          "<computed>"
    security_groups.#:            "<computed>"
    source_dest_check:            "true"
    subnet_id:                    "${aws_subnet.public_subnet.id}"
    tenancy:                      "<computed>"
    volume_tags.%:                "<computed>"
    vpc_security_group_ids.#:     "<computed>"

**Comment by muffat** [comment]
dsfsdf

**Comment by sujoy-chatterjee** [comment]
Hi, I have come across the exact same issue. My error message after running terraform apply in the above context is:

aws_instance.mongo: Error launching source instance: InvalidGroup.NotFound: The security group 'my_security_group' does not exist in VPC 'vpc-7ef73604'
        status code: 400, request id: df1b098a-2474-478f-a44e-9e0792582fa3

I though see on AWS console that my security group is associated with my VPC under the "security group" link.

Will appreciate any help.
Thanks.

Suj
