### ISSUE TITLE
Allow setting aws_network_interface description

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#5496]
It would be nice if the `aws_network_interface` allowed you to set the `description` for the eni.

Thanks

**Comment by phinze** [comment]
Oh hey look we don't support that field. Would definitely be an easy add, and we should do it! :+1:

**Comment by stack72** [comment]
PR about to be opened for this! Just running through the tests now

**Comment by stack72** [comment]
This has been added in #5523

**Comment by mtougeron** [comment]
Awesome, thanks!
