### ISSUE TITLE
terraform_remote_state do not find value

### ISSUE THREAD

**Issue by michalbagrowski** [hashicorp/terraform#5498]
I'm trying to use resource "terraform_remote_state" as in docs [REMOTE_STATE](https://www.terraform.io/docs/providers/terraform/r/remote_state.html) 

i have created [example](https://github.com/michalbagrowski/consul_terraform_remote_test)

In "consul_2" i'm trying to reference "consul/output.tf" "testname" with no succes and error 

`Resource 'terraform_remote_state.consul' does not have attribute 'output.testname' for variable 'terraform_remote_state.consul.output.testname'
`

am i doing something wrong?

**Comment by michalbagrowski** [comment]
Terraform v0.6.12

**Comment by clstokes** [comment]
Hi @michalbagrowski, I think you do have an error in your `terraform_remote_state` configuration. For `path` you're specifying `path=aa`. The value should just be `aa`.

```
resource "terraform_remote_state" "consul" {
    backend = "consul"
    config {
        address = "docker:8500"
        path = "aa"                    # <-- This line should look like this.
    }
}
```

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
