### ISSUE TITLE
Using split with ELB subnets results in permanent diff

### ISSUE THREAD

**Issue by yissachar** [hashicorp/terraform#5507]
When using split to populate an ELB subnet array, the ELB is created but results in an error. Further Terraform plans result in a diff detection on the subnets, but cannot be resolved due to the error.

Example code:

```
resource "aws_elb" "temptest" {
  name = "temptest"
  subnets = ["${split(",", "${aws_subnet.a.id}, ${aws_subnet.b.id}")}"]

  listener {
    instance_port = 80
    instance_protocol = "tcp"
    lb_port = 80
    lb_protocol = "tcp"
  }
}
```
Running `terraform apply` results in:

> * aws_elb.temptest: Failure adding ELB subnets: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.

Running `terraform plan` now gives us:

> ~ aws_elb.temptest
    subnets.1991296403: "subnet-6fd03f45" => "subnet-6fd03f45"
    subnets.2170053819: "" => " subnet-c7459db1"
    subnets.2903463796: "subnet-c7459db1" => ""

Further `terraform apply` results in the same error as before. If I manually go into the AWS console and delete the second subnet then `terraform apply` executes successfully. However, subsequent `terraform plan` brings up the diff again, and I'm back to where I started.

If the subnet line in the Terraform file is changed to:

`subnets = ["${aws_subnet.a.id}", "${aws_subnet.b.id}"]`

Then everything works as expected. This would be a fine fix for the toy code I've posted, but I'm using this in the context of modules where I have to use split to workaround the fact that we can't directly pass arrays in.

**Comment by phinze** [comment]
Hi @yissachar - thanks for the report.

My first guess is that your split delimiter is `","` but the two items look like they are delimited by `", "` - so you get extra whitespace on the second subnet ID. If you remove the extra whitespace or change the delimiter to include it, do you get consistent behavior?

**Comment by yissachar** [comment]
Heh, that works. I feel a bit silly now. It did used to work fine even without a space in the delimiter though, so I'm not sure what changed that exposed my mistake. Either way, this fix works for me, thanks!
