### ISSUE TITLE
AWS VPN Resources 

### ISSUE THREAD

**Issue by murtaza52** [hashicorp/terraform#551]
Hi.

We are using terraform to create a VPC and the related resources in AWS. We were not able to find the corresponding AWS resources in terraform -

Customer Gateway
Virtual Private Gateway
VPN Connection
Option for "Route Propogation" in Route Tables
 
Are there any plans to add the above to terraform in the near future?

Thanks,
Murtaza

**Comment by ojongerius** [comment]
+1

**Comment by catsby** [comment]
I believe all these features are now available. Please re-open or comment if we've missed something.

Thanks!
