### ISSUE TITLE
ECR Repository link attribute

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#5518]
I am creating an ECR and then creating a task definition using an image in that ECR. I currently have to construct the repo url but it would be simpler to make this an attribute of the ECR.

    resource "aws_ecr_repository" "ingest" {
      name = "ingest-repo"
      provisioner "local-exec" {
        command = "deploy-container.sh"
      }
    }
    resource "aws_ecs_task_definition" "ingest" {
        family = "ingest-task"
        container_definitions = <<EOF
    [{
      "name": "ingest",
      "image": "https://${aws_ecr_repository.ingest.registry_id}.dkr.ecr.${var.aws_region}.amazonaws.com/ingest:latest"
    }]
    EOF
    }

The `image` above could be replaced with `${aws_ecr_repository.ingest.link}/ingest:latest`

**Comment by stack72** [comment]
@ajcrites, I am trying to locate the docs that point to how that URL is formed - have you been able to find that?

**Comment by stack72** [comment]
I guess this is what we need:

http://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html

It specifically says the following:

```
The registry format is aws_account_id.dkr.ecr.us-east-1.amazonaws.com. 
```

What do you suggest the property name to be exposed as?

**Comment by ajcrites** [comment]
`id` is used as a property name for other URLs/ARNs such as those generated by SQS/SNS. Either this or `registry_url` would make sense to me.

I would expect it to look something like:

    https://<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_NAME>

I think the region can only be us-east-1 for now, but should still be something that's already known ahead of time.

**Comment by stack72** [comment]
@ajcrites PR open ad #5524 for this :)

**Comment by stack72** [comment]
@ajcrites this has been added in #5524
