### ISSUE TITLE
Error waiting for Redshift Cluster state to be "available": timeout while waiting for state to become '[available]'

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5521]
I am attempting to create a Redshift cluster with Terraform, but it seems to always time out. It seems that the cause is that it takes a long time to create a Redshift cluster (around 15 minutes). I can see the cluster in the AWS console, but it is in the "creating" state/

**Comment by jen20** [comment]
Hi @joshuaspence! This is part of a wider group of issues which is being tracked by a meta-issue over at #5537. Consequently I'll close this issue in favour of continuing the discussion over there in order to keep it in one place. Thanks for reporting this!
