### ISSUE TITLE
provider/aws: Change publicly_accessible in Redshift to not be ForceNew

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#5540]
Redshift currently has `publicly_accessible` as `ForceNew`, but it seems modifying it in the API is possible without recreation:

- http://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyCluster.html

We should add that to `resourceAwsRedshiftClusterUpdate` and remove the `ForceNew`

**Comment by stack72** [comment]
@catsby I will add this shortly

**Comment by stack72** [comment]
This is currently missing from the SDK - opened an issue with AWS for this https://github.com/aws/aws-sdk-go/issues/585

**Comment by stack72** [comment]
@catsby now that this has been added to the AWS SDK, a PR is being created (just running tests) so will be with you shortly
