### ISSUE TITLE
`formatlist` function doesn't work with empty lists

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5542]
I am trying to create an SPF record with the following Terraform code:

```
resource "aws_route53_record" "spf1" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  name    = "_spf1"
  type    = "TXT"
  ttl     = 120
  records = ["v=spf1 ${join(" ", formatlist("ip4:%s", compact(split(",", var.spf_records.spf1))))} -all"]
}
```

This doesn't work, however, if `${var.spf_records.spf1}` is the empty string.

**Comment by jen20** [comment]
Hi @joshuaspence - my branch which supports native lists in Terraform and is due to be merged shortly fixes this issue. Thanks for reporting!

**Comment by antonsoroko** [comment]
In fact it's a very annoying problem with formatlist. It would be great if this bug would be fixed.

**Comment by mitchellh** [comment]
This is fixed with native lists.
