### ISSUE TITLE
Add Argument for 'Provider' in OPENSTACK_LB_POOL_V1

### ISSUE THREAD

**Issue by civik** [hashicorp/terraform#5545]
Any possibility that the 'provider' argument could be added?  As documented it is a v2 API feature, however it exists in V1 and is a parameter that can be passed in.  Very useful when you have multiple backend device_driver specified in your lbass_agent.ini .

**Comment by jtopjian** [comment]
@civik Sorry for the late reply on this. 

Yup, this shouldn't be a problem to add. For what LB resource(s) would `provider` be applicable to?

**Comment by civik** [comment]
@jtopjian It would be part of the pool resource. Something like so:

```
resource "openstack_lb_pool_v1" "pool_1" {
  name = "pool_1"
  protocol = "TCP"
  subnet_id = "${openstack_networking_subnet_v2.subnet_1.id}"
  lb_method = "ROUND_ROBIN"
**  provider = "F5"**
  monitor_ids = ["${openstack_lb_monitor_v1.monitor_1.id}"]
}
```

**Comment by jtopjian** [comment]
@civik Thanks for the info 😄 

It looks like this first needs to be added to [Gophercloud](https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/extensions/lbaas/pools/requests.go). I'll look at getting it added there first.

**Comment by jtopjian** [comment]
@civik Support was just added to Gophercloud. I'll get this into Terraform as soon as I have a chance.

**Comment by jtopjian** [comment]
@civik Please see #6919 and let me know if you have any comments!
