### ISSUE TITLE
Is it possible to provision with Saltstack in a masterless configuration?

### ISSUE THREAD

**Issue by pierrebonbon** [hashicorp/terraform#5547]
I managed to created a _Digital Ocean droplet_ with _Terraform_, and now I would like to provision it with _Salt_, ideally  in a _masterless configuration_ using the same `.sls` files used to provision the development machine. With _Vagrant_ this is rather trivial, with _Terraform_ however it seems to be much less straightforward. Terraform's documentation regarding provisioners is mute on this subject. I couldn't find any reference on how to invoke Salt to provision an instance.

In Vagrant, it's simply a question of declaring the provisioner in the `Vagrantfile`, like this:

    config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true

And afterwards, it just a question of creating a state tree pointing to our state files, where we declare the packages we would like our machine to be provisioned with, the files that we would like to sync, etc. Is it even possible to do anything similar in _Terraform_?

**Comment by jen20** [comment]
Hi @pierrebonbon! Currently there is no explicit support for Salt, or in fact for any configuration management tool other than Chef. However, you can probably make use of the `file` and `remote-exec` provisioner here to execute Salt as necessary - I'm not familiar enough with it to suggest the exact contents of the script though! A quick google suggests something like [http://ahus1.github.io/saltconsul-examples/tutorial.html](this) (untested and unverified) might be suitable. Thanks for opening the issue - please feel free to reopen if you have further questions on this!

**Comment by pierrebonbon** [comment]
Hi @jen20, thank you for the reply and the link. Any chance that _Terraform_ will offer explicit support for _Salt_ in the near future?

**Comment by pierrebonbon** [comment]
solution [here][n1]

[n1]: http://serverfault.com/questions/762673/terraform-how-to-provision-droplet-with-salt-minion-masterless

**Comment by sevagh** [comment]
Hello. As a heavy user of both Terraform and Salt I'd like to take a stab at writing and contributing a `salt-masterless` provisioner upstream.

Could I get some tips on how to proceed?

I have been looking at https://github.com/hashicorp/packer/tree/master/provisioner/salt-masterless for inspiration.

**Comment by sevagh** [comment]
https://github.com/hashicorp/terraform/pull/14720
