### ISSUE TITLE
Query on file-provisioners for sudo permission.

### ISSUE THREAD

**Issue by baskaran-md** [hashicorp/terraform#5549]
If my ssh_user have only sudo permission, and if the /etc is owned by "root", then the following `file - provisioners` errors out as 
`Build 'amazon-ebs' errored: scp: /etc/configs.d: Permission denied`
```
"provisioners": [  
   {
      "type": "file",
      "source": "conf/configs.d",
      "destination": "/etc"
  } 
]
```
Is there any direct solution apart from copying to /tmp location and doing a sudo with `"type": "shell"` ?
```
    {
      "type": "shell",
      "execute_command": "echo {{user `ssh_username`}} | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "inline": [
        "cp -r /tmp/configs.d /etc/"
      ]
    },
```

**Comment by phinze** [comment]
Hi @baskaran-md - good question!

The `file` provisioner is essentially the same as an `scp` - so your workaround of uploading to a temporary location the user has access to and then doing a shell command to `sudo cp` or `mv` it into place is correct!

**Comment by baskaran-md** [comment]
Got it. Thank you.
