### ISSUE TITLE
google_container_cluster hits 400 when using a network with self_link

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#5552]
```
google_container_cluster: {
  ...
  network: "${google_compute_network.test.self_link"
}
```

Trying to apply results in:

```
* google_container_cluster.us-central1-c-standard-test-private: googleapi: Error 400: network "https://www.googleapis.com/compute/v1/projects/.../global/networks/test-m" does not exist., badRequest
```

The `prod` network exists for sure. When I refresh tf state, it shows up. It also shows up in the list of networks from `google compute networks list`.

**Comment by devth** [comment]
It works if I do this instead:

```
google_container_cluster: {
  ...
  network: "test-m"
}
```

`test` is the network name in terraform inventory, `test-m` is the actual resource name in GCP.

**Comment by sl1pm4t** [comment]
The Google API expects the name of the network, not the resource URL.
Does it work if you change your resource definition to:
```
google_container_cluster: {
  ...
  network: "${google_compute_network.test.name"
}
```

**Comment by paddyforan** [comment]
This should now work with either the `self_link` or the `name`, thanks to @sl1pm4t's work, so I'm going to close this issue out. If you encounter more problems, feel free to open another issue or comment in this issue again, and we'll reopen it. Thanks!
