### ISSUE TITLE
Google test suite 500 errors

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5554]
Capturing these for historical analytics before I re-kick the travis jobs that failed:

<img width="974" alt="job__10012_3_-_hashicorp_terraform_-_travis_ci" src="https://cloud.githubusercontent.com/assets/37534/13673227/c2ee818e-e69d-11e5-92c1-5083ea054b2d.png">

<img width="997" alt="job__10012_4_-_hashicorp_terraform_-_travis_ci" src="https://cloud.githubusercontent.com/assets/37534/13673306/1049c344-e69e-11e5-93b1-3f86c5186567.png">

**Comment by phinze** [comment]
@lwander @evandbrown @sparkprime these do seem to bite us more often in Google Cloud than the other providers. Not sure if there's any action item to take away from this on the Terraform side, so I'm going to close it right away, but wanted it recorded as an FYI.

I'll try to continue to record nightly acctest 500-class failures so that we have a historical account in case it would be helpful for feedback to upstream API teams. :+1:

**Comment by sparkprime** [comment]
Do you know / can estimate what % of requests end in 500?

**Comment by erjohnso** [comment]
@phinze - has it been consistently happening, and over what period of time. I'm looking on our side too, but would like to know how far back to go.

**Comment by sparkprime** [comment]
@phinze It looked like the error rate was very low (0.1%) for Terraform useragent.  That doesn't limit to the regression tests but it does give a pretty good idea.  I wonder if the number of calls being made are so high that the law of averages is kicking in.  Do the other providers have retry loops?

**Comment by phinze** [comment]
@sparkprime Definitely possible on both counts!

I can tell you that we almost never see 500-class errors coming through on the AWS side, where we are running >3x more tests with >2x higher parallelism - I took a quick peek at aws-sdk-go and it's not immediately clear to me whether it retries through 500s.

**Comment by evandbrown** [comment]
The AWS SDK does do retries. It's configurable, and I'm not sure what the per-service defaults are, but I'd expect it for common list and get requests. @erjohnso pointed me to API logs; I'll start tracking 5xx errors, see if we can pinpoint, and look at adding retry support to our SDKs.
