### ISSUE TITLE
Resource aws_ami_copy should have option to propagate tags

### ISSUE THREAD

**Issue by bradchoate** [hashicorp/terraform#5561]
Original AMI may contain tags that should be copied over to the new instance. I would expect a "copy" operation to do this by default with an option to exclude them, but an option that defaults to not copying to prevent a breaking change would be reasonable.

**Comment by eedwardsdisco** [comment]
I had the same thoughts but it doesn't really make much sense, since getting the tags from the source AMI require additional permissions beyond just having the AMI shared with your account or user.

**Comment by bradchoate** [comment]
Well, if that's the case, then definitely make it an option, but default it to not propagating the tags as it does now. If the auth'd user doesn't have permissions for reading the tags, then warn on that if the resources is configured to copy them.
