### ISSUE TITLE
Support for `addonsConfig` on google_container_cluster resource

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#5567]
https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#Cluster

https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#AddonsConfig

**Comment by phinze** [comment]
Chatted w/ @lwander about this - sounds like they're working on a timeline for GA for this feature.

It's difficult for Terraform to add support for alpha GCP features generally - there's a good description of why over here: https://github.com/hashicorp/terraform/issues/5053#issuecomment-182096731

tl;dr - Stay tuned!

**Comment by devth** [comment]
Fixed by https://github.com/hashicorp/terraform/pull/5871
