### ISSUE TITLE
Security Group References in a Peered VPC

### ISSUE THREAD

**Issue by rodlogic** [hashicorp/terraform#5568]
On March 1st, AWS announced [Security Group references in a peered VPC](https://aws.amazon.com/about-aws/whats-new/2016/03/announcing-support-for-security-group-references-in-a-peered-vpc/).

Since support for this in the AWS Go SDK was added in [1.1.8](https://aws.amazon.com/releasenotes/6213336098717231), it would be a good idea to upgrade to 1.1.8, at least (latest is 1.1.9). The current version in use by Terraform seems to be 1.1.2.

**Comment by phinze** [comment]
Hi @rodlogic, the vendored library is updated now - what else do we need in Terraform to support this behavior?

**Comment by rodlogic** [comment]
As far as I know, the new SDK should fix the issue. If it is not too much trouble building master I can try it to verify.

**Comment by rodlogic** [comment]
I gave a quick shot at building terraform on my OSX laptop without luck. If you have a simple way to generate a binary for OSX, I am happy to take it and test this on my project.

**Comment by rodlogic** [comment]
I tested again with v0.6.3, which now uses AWS GoSDK v1.1.9, but unfortunately I am seeing the same issue:
```
* aws_security_group_rule.OPS-ENV-ICMP-EGRESS: Error authorizing security group rule type egress: InvalidGroup.NotFound: You have specified two resources that belong to different networks.
	status code: 400, request id:
```

The issue went away once I upgraded to the latest ```aws-cli/1.10.14 Python/2.7.10 Darwin/15.3.0 botocore/1.4.5```. So I am wondering if the problem is actually in the AWS Go SDK.

**Comment by phinze** [comment]
@rodlogic Terraform 0.6.14 [is using aws-sdk-go v1.1.12](https://github.com/hashicorp/terraform/blob/v0.6.14/Godeps/Godeps.json#L225) released 6 days ago. I believe that should have the proper behavior now. Are you able to re-test this with 0.6.14?

**Comment by rodlogic** [comment]
I can confirm that this is now fixed.

**Comment by dusansusic** [comment]
4 years later:
```
Error: error creating EKS Node Group (eks-nodes): InvalidParameterException: Security group(s) [sg-xxxxxxxxx] are not in the same VPC as the subnets. Please specify a security group that is associated with the VPC: vpc-xxxxxxxxxxxxx.
```

I have 2 peered VPC's. Over AWS console, I am able to add security_group_id to other SG, but with terraform I get an error above.
