### ISSUE TITLE
template_file vars resource dependency logic

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform#5572]
I'm not sure if I'm misunderstanding the logic or not, but I'm having an issue with using a template_file resource referencing an aws_instance resource.

**Terraform version: 0.6.12**

Example:
```
resource "aws_instance" "server1" {
.......
}

resource "template_file" "file" {
     template = "${file(${path.module}/template_file.tpl")}"
     vars {
         ip_address  = "${aws_instance.server1.private_ip}"
}

resource "aws_instance" "server2" {
.......
}
```

The way I understand it, the template_file will wait for the aws_instance to be created.  The error I'm getting is `failed to render : X:X unknown variable accessed: ip_address`

I also tried adding 

```
depends_on = ["aws_instance.server1"]
```

but that doesn't do anything.

**Comment by phinze** [comment]
Hi @nocode99 - yep that should work just fine!

Here's a full config that works for me:

```tf
provider "aws" {
  region = "us-west-2"
}
resource "aws_instance" "server1" {
  instance_type = "t2.nano"
  ami           = "ami-d12cceb1"
}
resource "template_file" "file" {
  template = "Here is the IP: ${ip_address}"
  vars {
    ip_address = "${aws_instance.server1.private_ip}"
  }
}
output "template" {
  value = "${template_file.file.rendered}"
}
```

![nvim](https://cloud.githubusercontent.com/assets/37534/13684872/60db8ed4-e6d3-11e5-8286-c48f094a807f.png)

Hope this helps!

**Comment by nocode99** [comment]
I think I found my issue.  I was looking at the error wrong initially and I didn't include this part in my original post because I didn't think it was relevant at the time.  In this example, I have a second template_file referencing the same local template_file.tpl but without the proper variable.  I'm guessing since terraform is generating a temp file with the vars being passed in, it throws the error I saw.  

If it matters, my template_file is a shell script and I had a `if` statement looking for said var like such:

```bash
if [ -v ${ip_address} ] ; then
   echo "${ip_address}  web_server" > sudo tee --append /etc/hosts
fi
```

terraform.tf
```tf
resource "template_file" "file1 {
    template = ${file(${path.module}/template_file.tpl")}"
}

resource "aws_instance" "server1" {
.......
}

resource "template_file" "file2" {
     template = "${file(${path.module}/template_file.tpl")}"
     vars {
         ip_address  = "${aws_instance.server1.private_ip}"
}

resource "aws_instance" "server2" {
.......
}
```

Thanks for the quick response!

**Comment by phinze** [comment]
Ah yes - inside the template all variables are considered required. If you want a second template to render the `${ip_address}` as blank, just pass it in as blank:

```tf
resource "template_file" "file1 {
  template = ${file(${path.module}/template_file.tpl")}"
  vars {
    ip_address = ""
  }
}
```

Does that work for your use case?

**Comment by nocode99** [comment]
Yep - I ended up using that and it worked.  Thanks!
