### ISSUE TITLE
aws_autoscaling_policy doesn't always get created

### ISSUE THREAD

**Issue by bantonj** [hashicorp/terraform#5574]
When applying with a configuration that includes a aws_autoscaling_policy about 1/4 of the time, the policy will not be created. Everything else in the configuration is properly created. Unfortunately I don't have any logs of the output from terraform yet.

**Comment by phinze** [comment]
Hi @bantonj - sorry for the trouble! We do run an acceptance test suite that exercises `aws_autoscaling_policy` nightly, and those tests do consistently pass for us, so configs will definitely be helpful here to figure out what might be causing the flaky behavior.

**Comment by bantonj** [comment]
Thanks @phinze.

I realize now that I am tainting the launch configuration and autoscaling group before running apply. When I take those out it seems to make the policy work more reliably. Is using taint this way not recommended?

taint aws_autoscaling_group.nginx_b_test-for-prod-164
taint aws_launch_configuration.nginx_launch_conf_b_test-for-prod-164

I've attached the configuration file (changed extension to make Github happy). I have a log of the debug output from Terraform as well. It doesn't seem to have any sensitive information in it, but wanted to check first to see if it was definitely safe to attach, it's a biy too verbose for me to check by eye.

[main_test-for-prod-164.txt](https://github.com/hashicorp/terraform/files/168335/main_test-for-prod-164.txt)

**Comment by bantonj** [comment]
Did a little more investigation, and if I add

**Comment by dabdine-r7** [comment]
We're experiencing this issue too, and it also seems to be related to tainting. In our case, we taint the auto scaling group to force a recreate/reroll all the nodes. When we do that and run apply, it claims success. When we run a plan post apply, we see all the aws_autoscaling_policy resources waiting to be created.
