### ISSUE TITLE
Terraform doesn't fail immediately if aws_session_token has expired

### ISSUE THREAD

**Issue by stonith** [hashicorp/terraform#5579]
If AWS credentials are incorrect, terraform will fail immediately. However, if the `aws_session_token` has expired, terraform takes a long time to fail. In my case, a terraform plan only fails after 1.5min+ if I use an expired `aws_session_token`.

**Comment by zanona** [comment]
Oh yes, that takes a loooooong time. I can actually grab a coffee in the meantime (not kidding).

**Comment by stack72** [comment]
Hi @stonith 

Is this still the case?

Paul

**Comment by stonith** [comment]
@stack72 Yes, it still is as of 0.7.7. I just tried it and it took 1min 40sec to timeout.

```
Error refreshing state: 1 error(s) occurred:

* ExpiredToken: The security token included in the request is expired
	status code: 403, request id: ******
Rebuilding instance config JSON...Done!
terraform plan  2.89s user 0.46s system 3% cpu 1:39.54 total
```

We've worked around this with some shell script wrappers for now though.

**Comment by danpantry** [comment]
Just wanted to update and say that this is still the case as of 0.9.4.
