### ISSUE TITLE
cloudstack_instance should not require name parameter

### ISSUE THREAD

**Issue by larstobi** [hashicorp/terraform#5585]
From the [Terraform docs](https://www.terraform.io/docs/providers/cloudstack/r/instance.html) we can read:

> name - (Required) The name of the instance. Changing this forces a new resource to be created.

From the [CloudStack docs](http://cloudstack.apache.org/api/apidocs-4.8/domain_admin/deployVirtualMachine.html) we can read:

| Parameter Name | Description | Required |
|------------------------|-----------------|--------------|
| name | host name for the virtual machine | false |

I expect to be able create an instance with terraform without supplying a name and get the generated unique instance name from CloudStack (i.e. VM-3de42035-6ab5-4c84-b422-26ea8e454353).

What happens when I omit the name parameter is I get an error from Terraform:

    Errors:
      * cloudstack_instance.test: "name": required field is not set

**Comment by jen20** [comment]
Hi @larstobi! Thanks for reporting this. I've opened a pull request at #5587 which should resolve this, and have CC'd in the maintainer of the CloudStack provider for review.

**Comment by svanharmelen** [comment]
Fixed and merged :+1: 

Thanks @larstobi and @jen20!
