### ISSUE TITLE
Why process .tf files when destroying?

### ISSUE THREAD

**Issue by rodlogic** [hashicorp/terraform#5590]
I thought that ```terraform destroy``` would only need to use the current state file to destroy all resources, but it seems that it also parses all the .tf files.

More often than not, I have an infrastructure up and running and decide to implement a few changes to my .tf files. At some point I decide to destroy all existing resources and starting from scratch. The problem is that I can't destroy all the existing resources until I make sure my .tf have no errors.

Yes, git/svn are your friends here, but I am not seeing a technical reason for this behavior.

**Comment by phinze** [comment]
Hi @rodlogic - there is some discussion around this question in #5425, with some explanation for why this is the case. Going to close this to keep the conversation consolidated in #5425. :+1:
