### ISSUE TITLE
HCL syntax error goes unnoticed

### ISSUE THREAD

**Issue by darrensony** [hashicorp/terraform#5600]
Attempting to use a map in a resource silently does nothing.

````
variable "my_tags" {
    type = "map"
    default = {
        Name = "My Value"
    }
}

resource "aws_internet_gateway" "my_gateway"
{
  vpc_id = "vpc-9999999" # redacted
  tags my_tags           # XXX: This should WORK or should FAIL
}
````

- Does not raise any error or warning during "plan"
- Does not raise any error or warning during "apply"
- Does not actually apply the tag Name="My Value" to the created resource

Expected Behaviour:
- Should either apply the tag, or raise an error that this is invalid syntax

**Comment by jen20** [comment]
Hi @darrensony! Right now this should trigger a syntax error, as it is not valid HCL - I'm going to mark this as a bug (probably introduced during the parser switch from YACC to a Go-style scanner/parser a few versions back). The actual feature for applying tags from a map is being tracked at #5435. Thanks for reporting this!

**Comment by mitchellh** [comment]
This is fixed now, on master it gives me a syntax error.
