### ISSUE TITLE
Parameter encrypted is invalid: EBS block device in launch configuration

### ISSUE THREAD

**Issue by inkblot** [hashicorp/terraform#5608]
I have an `aws_launch_configuration` with an `ebs_block_device` that looks like this:

```
ebs_block_device {
  device_name = "/dev/xvdf"
  snapshot_id = "${terraform_remote_state.images.output.master_snapshot_us-east-1}"
}
```

`terraform` is able to create this launch configuration (and the snapshot_id is a valid snapshot) but the autoscaling group is unable to launch instances and the activity history for the autoscaling group shows failed launches with this error message:

```
Launching a new EC2 instance. Status Reason: Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping. Launching EC2 instance failed.
```

I believe that this is essentially the same bug as #1862, but with respect to the `aws_launch_configuration` resource rather than `aws_instance`.

**Comment by radeksimko** [comment]
Hi @inkblot 
do you mind if we close this as a duplicate of https://github.com/hashicorp/terraform/issues/5360 ? I believe it's exactly the same issue.

**Comment by inkblot** [comment]
That looks right.

**Comment by telebh** [comment]
I have the same issue to create ASG from launch instance from template. I did not set any encryption while creating the launch template. any workaround this issue?
