### ISSUE TITLE
Unable to create DO droplet with multiple keys, only first one uploaded

### ISSUE THREAD

**Issue by ippoippo** [hashicorp/terraform#561]
I want to be able to access any droplets I create from multiple client machines. Each of these machines have their own public/private key pair. 

I've uploaded the public key for each machine to DigitalOcean using their own web console.
Using the console, I can successfully create a CoreOS (Stable) droplet and access it from both machines.

However, if I use Terraform to provision the Droplet, it looks like only one key is being added to the new droplet.

My repo is located at https://github.com/ippoippo/docker-devops-infra

The specific code that is failing is this...

```
# Create a server
resource "digitalocean_droplet" "dockerdevops1" {
    image = "${var.do_image}"
    name = "dockerdevops1"
    region = "${var.do_region}"
    private_networking = true
    size = "${var.do_size}"
    # TODO - Why is only ssh_key1 uploaded?
    ssh_keys = ["${var.do_ssh_key1}", "${var.do_ssh_key2}"]
}
```

The machine using key1 is OK. Key2 is not present on the droplet.

**Comment by fenfe1** [comment]
I've just hit this problem as well, I assume this means no-one is creating VMs with multiple root SSH keys?

**Comment by ippoippo** [comment]
I'm a little disappointed that this issue hasn't even been acknowledged.

I could try to fix it myself and create a PR. Need to learn Go first, before attempting to fix it myself.

**Comment by ryanuber** [comment]
@ippoippo sorry for the delays, we definitely want to get this fixed. @svanharmelen I noticed you refactored this at some point. Not sure if that has anything to do with the actual issue, but any thoughts? I'll take a closer look at this soon if someone else doesn't jump on it.

Thanks for the report!

**Comment by svanharmelen** [comment]
@ryanuber @ippoippo also sorry for the delay from my part. I'm pretty tied up with some other (still related) projects so don't have much time at the moment...

I just looked at the code changes I made when refactoring the DigitalOcean provider, but I fail to see how those changes could be causing this. In both the old and new situation the keys end up in a `[]string` in `opts.SSHKeys`. So if it doesn't work now, I'm wondering if this has actually worked before... My gut feeling tells me it didn't.

While having a quick look at the client package I notice this line: https://github.com/pearkes/digitalocean/blob/master/droplet.go#L130 which has a parameter called `ssh_keys[]`. I wonder if that is a typo as the API docs from DigitalOcean talk about a `ssh_keys` parameter. So maybe that causes this issue?

Unfortunately for now I don't have more time to do some functional testing to fix this one, but I think doing a quick test with `ssh_keys[]` renamed to `ssh_keys` might just be the solution... Maybe at the same time add a `fmt.Printf("KEYS: %+v", opts.SSHKeys)` the line above L130 to see if both keys are actually in there...

**Comment by ippoippo** [comment]
@ryanuber @svanharmelen 
Appreciate the feedback guys.

If I too somehow find some spare time from my day job and normal weekend out of work errands (hey, I'm in Japan.... spare time... don't have that ;)  )....
then I may have a look at this.
Never programmed in Go before, but if it's a simple little fix and simple test.... maybe 
Can't promise anything though

**Comment by pearkes** [comment]
This should be fixed by switching to sending JSON for creation requests in https://github.com/pearkes/digitalocean/issues/4.

Unfortunately it wasn't as simple as modifying the parameter, DO only wanted to accept arrays via JSON. But, should be fixed if you `updatedeps`.
