### ISSUE TITLE
notification_target_arn and role_arn shouldn't be required in aws_autoscaling_lifecycle_hook

### ISSUE THREAD

**Issue by pcarrier** [hashicorp/terraform#5614]
AWS does not require those.

For example an AWS instance can report its instance ID as healthy in user-data pretty easily.

Maintaining an SQS queue and an IAM role usable by autoscaling (so with policies) is unnecessary complicated in those cases.

See http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_PutLifecycleHook.html

**Comment by stack72** [comment]
Your PR has been merged that fixes this :)
