### ISSUE TITLE
Ignoring files when copying with file provisioner

### ISSUE THREAD

**Issue by pierrebonbon** [hashicorp/terraform#5615]
I'm copying a directory (and subdirectories) to a remote machine with the `file` provisioner, but would like to skip some of the files in it. I wonder if there is currently a way (explicit) to ignore files when copying with the `file` provisioner, or do I need to delete them afterwards with a `remote-exec` block?

Possibly related with #1948

**Comment by mitchellh** [comment]
Rather than add this to the file provisioner, we recomend you work around this at the moment using `local-exec` to filter the files into a new directory then upload. This isn't ideal but is a solid workaround.

**Comment by pierrebonbon** [comment]
Thanks for the hint, will try that solution.

**Comment by gaui** [comment]
Introduce `.tfignore` just like `.gitignore` ? 😁

**Comment by bukowa** [comment]
@gaui idea sounds amazing
