### ISSUE TITLE
DynamoDB table cannot be provisioned in the same block

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#5624]
I have a provision script that seeds some data to a DyanomoDB table I create like so:

```
resource "aws_dynamodb_table" "t1" {
  # table creation seems to work fine
  provisioner "local-exec" {
    "seed-db"
  }
}
```

My seed-db script will work properly if I create the table and run it on its own, but with Terraform here I will get a ResourceNotFoundException indicating that the table has not been created yet.

I can also move the "seed-db" to another block that happens after the dynamodb block and the seeding will work properly.

**Comment by teamterraform** [comment]
Hi @ajcrites! Sorry for the long silence here.

To be honest, we're not really sure what was going on here, but it's been so long now I'm sure you don't have a reproduction case handy anymore to gather more information. The most likely explanation is that the DynamoDB API reported a successful create but it took a little more time for that create to be fully committed in the remote system, and the provisioner ran too soon after that and got the incorrect error from the API.

The fact that the script worked when you ran it manually or when a downstream resource would trigger it seems to confirm that theory: that likely added enough of a time delay after the creation to clear up the problem.

This sort of temporary inconsistency is, unfortunately, quite common in distributed systems. Over the years the AWS provider team has added in additional checks to various parts of the provider to try to wait until the remote API is consistently reporting the existence of the new object, which makes this sort of behavior less likely.

We're going to close this out now on the assumption that eventual consistency was the problem. If you or anyone else sees a similar problem like this in recent versions of Terraform and the AWS provider, please open an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) about it.
