### ISSUE TITLE
Terraform Crash - unexpected EOF

### ISSUE THREAD

**Issue by ledor473** [hashicorp/terraform#5625]
Hi,

I'm pretty new with Terraform and now I get a crash whenever I run the `terraform plan`

Here's the crash.log
[crash.txt](https://github.com/hashicorp/terraform/files/172439/crash_truncated.txt)

Let me know if anything else could help you!

Best regards

**Comment by stack72** [comment]
Hi @ledor473, 

I was able to find the following in the crash log:

```
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x6200c6]
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: goroutine 74 [running]:
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: panic(0x10ef260, 0xc82000a1a0)
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 	/opt/go/src/runtime/panic.go:464 +0x3e6
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.flattenLambdaVpcConfigResponse(0xc820308e80, 0x0, 0x0, 0x0)
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/structure.go:693 +0x336
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsLambdaFunctionRead(0xc820510a20, 0xe10b60, 0xc82025c200, 0x0, 0x0)
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_lambda_function.go:260 +0x596
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc82033a400, 0xc82050f260, 0xe10b60, 0xc82025c200, 0xc8202502a8, 0x0, 0x0)
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x43a
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc82035eba0, 0xc820381780, 0xc82050f260, 0xc8204f0801, 0x0, 0x0)
2016/03/14 12:42:21 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da

```

Please can you provide the terraform version you are using and a sample of the config you are using that created the crash? Please exclude any secrets in it ;)

Thanks

Paul

**Comment by ledor473** [comment]
Oh I forgot to include the version... I'm using: v0.6.12

Here's the .tf file I'm using (with some string replacement)
[TF file](https://github.com/hashicorp/terraform/files/172525/projectname.txt)

**Comment by stack72** [comment]
Thanks @ledor473 :)

**Comment by stack72** [comment]
Hi @ledor473,

I have just tested this and this is indeed an issue because of VPC support in Lambda. The good news here, is that it is already fixed in #5182 and will be released really soon!

Paul

**Comment by catsby** [comment]
Going to close this for now then, thanks for the digging @stack72 

@ledor473 – let us know if the changes in #5182 don't fix things for your

Thanks!

**Comment by ledor473** [comment]
@stack72 Great!

I'll search how frequent do you release (there's probably a page in the documentation or somewhere). If it's too long I'll compile from source to unblock me.

Thanks for the very quick reply

**Comment by stack72** [comment]
IF you want to try and compile from source as a test, that would be very useful! I believe we will release soon though

**Comment by ledor473** [comment]
@stack72 I've managed to compile it and it worked flawlessly !

**Comment by stack72** [comment]
@ledor473 thanks so much for letting me know. Sorry i wasn't in touch earlier, I have been travelling!
