### ISSUE TITLE
add or remove 'resource "aws_instance"' destroys existing ec2 instance

### ISSUE THREAD

**Issue by jianhuawuchn** [hashicorp/terraform#5632]
1. create a terraform configuration file with one "aws_instance" resource defined
2. go to command line and type "terraform apply", and wait for instance to be lunched  in AWS cloud
3. add another "aws_instance" resource in the same terraform configuration file
4. terraform plan & terraform apply again

ATTENTION: my existing ec2 instance in AWS cloud gets **TERMINATED **, and relaunched. This is really not good, something has to be fixed immediately.

**Comment by jrasell** [comment]
Hi @jianhuawuchn; could you paste your Terraform configuration, remembering to omit any sensitive information.

**Comment by dansteen** [comment]
Interestingly enough, I am experiencing something similar.   Given the following config:

```resource "aws_instance" "jenkins" {
  ami = "ami-9eaa1cf6"
  instance_type = "c4.2xlarge"
  availability_zone = "${var.availability_zone}"
  key_name = "${var.key}"
  vpc_security_group_ids = [ "${var.default_sg}", "${aws_security_group.jenkins.id}" ]
  subnet_id = "${var.subnet}"
  associate_public_ip_address = "${lookup(var.associate_public_ip, var.internal)}"
  user_data = "${file("autoscale-userdata.sh")}"
  iam_instance_profile = "${var.iam}"

  tags {
    role = "${var.name}"
    env  = "${var.env}"
    dns_zone = "${var.env_zone}"
  }

  # let the name be set dynamically
  lifecycle {
    ignore_changes = ["tags.#", "tags.Name" ]
  }

  root_block_device {
    volume_size =  20
    volume_type =  "gp2"
    delete_on_termination = "false"
  }
  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp2"
    volume_size = "80"
    delete_on_termination = "false"
  }
  ebs_block_device {
    device_name = "/dev/xvdc"
    volume_type = "gp2"
    volume_size = "80"
    delete_on_termination = "false"
  }
  ebs_block_device {
    device_name = "/dev/xvdd"
    volume_type = "gp2"
    volume_size = "200"
    delete_on_termination = "false"
  }
```
I get the following plan:
```-/+ module.jenkins_prod.aws_instance.jenkins
    ami:                                               "ami-9eaa1cf6" => "ami-9eaa1cf6"
    associate_public_ip_address:                       "true" => "1"
    availability_zone:                                 "us-east-1e" => "us-east-1e"
    ebs_block_device.#:                                "3" => "3"
    ebs_block_device.2634515331.delete_on_termination: "0" => "0"
    ebs_block_device.2634515331.device_name:           "/dev/sdd" => ""
    ebs_block_device.3905984573.delete_on_termination: "false" => "0" (forces new resource)
    ebs_block_device.3905984573.device_name:           "/dev/xvdb" => "/dev/xvdb" (forces new resource)
    ebs_block_device.3905984573.encrypted:             "false" => "<computed>"
    ebs_block_device.3905984573.iops:                  "240" => "<computed>"
    ebs_block_device.3905984573.snapshot_id:           "" => "<computed>"
    ebs_block_device.3905984573.volume_size:           "80" => "80" (forces new resource)
    ebs_block_device.3905984573.volume_type:           "gp2" => "gp2" (forces new resource)
    ebs_block_device.3910332938.delete_on_termination: "false" => "0" (forces new resource)
    ebs_block_device.3910332938.device_name:           "/dev/xvdc" => "/dev/xvdc" (forces new resource)
    ebs_block_device.3910332938.encrypted:             "false" => "<computed>"
    ebs_block_device.3910332938.iops:                  "240" => "<computed>"
    ebs_block_device.3910332938.snapshot_id:           "" => "<computed>"
    ebs_block_device.3910332938.volume_size:           "80" => "80" (forces new resource)
    ebs_block_device.3910332938.volume_type:           "gp2" => "gp2" (forces new resource)
    ebs_block_device.3965576335.delete_on_termination: "" => "0" (forces new resource)
    ebs_block_device.3965576335.device_name:           "" => "/dev/xvdd" (forces new resource)
    ebs_block_device.3965576335.encrypted:             "" => "<computed>" (forces new resource)
    ebs_block_device.3965576335.iops:                  "" => "<computed>" (forces new resource)
    ebs_block_device.3965576335.snapshot_id:           "" => "<computed>" (forces new resource)
    ebs_block_device.3965576335.volume_size:           "" => "200" (forces new resource)
    ebs_block_device.3965576335.volume_type:           "" => "gp2" (forces new resource)
    ephemeral_block_device.#:                          "0" => "<computed>"
    iam_instance_profile:                              "AutoScaleBox-prod" => "AutoScaleBox-prod"
    instance_state:                                    "running" => "<computed>"
    instance_type:                                     "c4.2xlarge" => "c4.2xlarge"
    key_name:                                          "aws-production" => "aws-production"
    placement_group:                                   "" => "<computed>"
    private_dns:                                       "ip-xx-xx-xx-xx.ec2.internal" => "<computed>"
    private_ip:                                        "xx-xx-xx-xx" => "<computed>"
    public_dns:                                        "ec2-xx-xx-xx-xx.compute-1.amazonaws.com" => "<computed>"
    public_ip:                                         "xx-xx-xx-xx" => "<computed>"
    root_block_device.#:                               "1" => "1"
    root_block_device.0.delete_on_termination:         "false" => "0"
    root_block_device.0.iops:                          "60" => "<computed>"
    root_block_device.0.volume_size:                   "20" => "20"
    root_block_device.0.volume_type:                   "gp2" => "gp2"
    security_groups.#:                                 "0" => "<computed>"
    source_dest_check:                                 "true" => "1"
    subnet_id:                                         "subnet-xxxxxxx" => "subnet-xxxxxx"
    tags.dns_zone:                                     "xxxxx" => "xxxxx"
    tags.env:                                          "prod" => "prod"
    tags.role:                                         "jenkins" => "jenkins"
    tenancy:                                           "default" => "<computed>"
    user_data:                                         "458bdd9c20822a4b76f78a000d38c7c5e761b634" => "458bdd9c20822a4b76f78a000d38c7c5e761
b634"
    vpc_security_group_ids.#:                          "2" => "2"
    vpc_security_group_ids.1588657903:                 "sg-xxxx" => "sg-xxxx"
    vpc_security_group_ids.3883424384:                 "sg-xxxx" => "sg-xxxx"
```

I even tried adding an a:
``` lifecycle {
    ignore_changes = ["ebs_block_device"]
  }
```

And it still showed that it wanted to replace the instance:

```
-/+ module.jenkins_prod.aws_instance.jenkins
    ami:                                       "ami-9eaa1cf6" => "ami-9eaa1cf6"
    associate_public_ip_address:               "true" => "1"
    availability_zone:                         "us-east-1e" => "us-east-1e"
    ephemeral_block_device.#:                  "0" => "<computed>"
    iam_instance_profile:                      "AutoScaleBox-prod" => "AutoScaleBox-prod"
    instance_state:                            "running" => "<computed>"
    instance_type:                             "c4.2xlarge" => "c4.2xlarge"
    key_name:                                  "aws-production" => "aws-production"
    placement_group:                           "" => "<computed>"
    private_dns:                               "ip-xx-xx-xx-xx.ec2.internal" => "<computed>"
    private_ip:                                "xx-xx-xx-xx" => "<computed>"
    public_dns:                                "ec2-xx-xx-xx-xx.compute-1.amazonaws.com" => "<computed>"
    public_ip:                                 "xx-xx-xx-xx" => "<computed>"
    root_block_device.#:                       "1" => "1"
    root_block_device.0.delete_on_termination: "false" => "0"
    root_block_device.0.iops:                  "60" => "<computed>"
    root_block_device.0.volume_size:           "20" => "20"
    root_block_device.0.volume_type:           "gp2" => "gp2"
    security_groups.#:                         "0" => "<computed>"
    source_dest_check:                         "true" => "1"
    subnet_id:                                 "subnet-xxxxx" => "subnet-xxxx"
    tags.dns_zone:                             "xxxxx" => "xxxxx"
    tags.env:                                  "prod" => "prod"
    tags.role:                                 "jenkins" => "jenkins"
    tenancy:                                   "default" => "<computed>"
    user_data:                                 "458bdd9c20822a4b76f78a000d38c7c5e761b634" => "458bdd9c20822a4b76f78a000d38c7c5e761b634"
    vpc_security_group_ids.#:                  "2" => "2"
    vpc_security_group_ids.1588657903:         "sg-xxxxx" => "sg-xxxxx"
    vpc_security_group_ids.3883424384:         "sg-xxxxx" => "sg-xxxxx"
```

But it does not show any reason for why - there is no "forces new resource".

Thanks for looking into this!  It's definitely causing some trouble.

**Comment by catsby** [comment]
Hey @jianhuawuchn – do you have a configuration that reproduces this? If you do and can share that, that would be very helpful in reproducing, just be sure to remove any secret information. 

I attempted to reproduce with the steps given and was not able to. I created the first instance, and then the second, with no interruption of the first. 

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "tf_test" {
  ami           = "ami-260c1f47"
  instance_type = "t2.nano"

  source_dest_check = false

  tags {
    Name = "tf-test"
  }
}

# added later
resource "aws_instance" "tf_test_other" {
  ami           = "ami-260c1f47"
  instance_type = "t2.nano"

  source_dest_check = false

  tags {
    Name = "tf-test-other"
  }
}
```

```
$ terraform apply .
aws_instance.tf_test: Refreshing state... (ID: i-0f5b5636a084c4af9)
aws_instance.tf_test_other: Creating...
  ami:                      "" => "ami-260c1f47"
  availability_zone:        "" => "<computed>"
  ebs_block_device.#:       "" => "<computed>"
  ephemeral_block_device.#: "" => "<computed>"
  instance_state:           "" => "<computed>"
  instance_type:            "" => "t2.nano"
  key_name:                 "" => "<computed>"
  placement_group:          "" => "<computed>"
  private_dns:              "" => "<computed>"
  private_ip:               "" => "<computed>"
  public_dns:               "" => "<computed>"
  public_ip:                "" => "<computed>"
  root_block_device.#:      "" => "<computed>"
  security_groups.#:        "" => "<computed>"
  source_dest_check:        "" => "0"
  subnet_id:                "" => "<computed>"
  tags.#:                   "" => "1"
  tags.Name:                "" => "tf-test-other"
  tenancy:                  "" => "<computed>"
  vpc_security_group_ids.#: "" => "<computed>"
aws_instance.tf_test_other: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by jianhuawuchn** [comment]
I will share my configuration  file. Not in office today.

One thing worth to mention here is my terraform state file is stored in AWS s3, and values or parameters in my configuration file are pulled out from state file dynamiclly.

Cant understand why this bug is closed, I believe a lot more people willing to know the way to solve this bug or issue.

**Comment by jianhuawuchn** [comment]
##################terraform configuration for setting up VPC#########################
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.aws_region}"
}

// create VPC
resource "aws_vpc" "vml_vpc" {
  cidr_block = "10.65.65.0/24"
  instance_tenancy = "default"

  tags {
    Name = "VML_VPC"
  }
}

// create Internet Gateway
resource "aws_internet_gateway" "igw_vml_vpc" {
    vpc_id = "${aws_vpc.vml_vpc.id}"

    tags {
      Name = "IGW_For_VML_VPC"
    }
}
// define vpc endpoint connection to s3
resource "aws_vpc_endpoint" "vml_vpc_to_s3" {
    vpc_id = "${aws_vpc.vml_vpc.id}"
    service_name = "com.amazonaws.ap-southeast-2.s3"
    route_table_ids = [ "${aws_route_table.vml_public_routing_table_zone_a.id}", "${aws_route_table.vml_public_routing_table_zone_b.id}"]
}

//define eip for aws nat Gateway
resource "aws_eip" "nat_public_subnet_zone_a" {
    depends_on = [ "aws_internet_gateway.igw_vml_vpc"]
}

resource "aws_eip" "nat_public_subnet_zone_b" {
    depends_on = [ "aws_internet_gateway.igw_vml_vpc"]
}

//define subnets in AWS VPC
resource "aws_subnet" "vml_vpc_public_subnet_zone_a" {
  vpc_id = "${aws_vpc.vml_vpc.id}"
  cidr_block = "10.65.65.0/28"
  availability_zone = "ap-southeast-2a"

  tags {
    Name = "VML_VPC_PUBLIC_SUBNET_ZONE_A"
  }
}

resource "aws_subnet" "vml_vpc_private_subnet_zone_a" {
  vpc_id = "${aws_vpc.vml_vpc.id}"
  cidr_block = "10.65.65.64/28"
  availability_zone = "ap-southeast-2a"

  tags {
    Name = "VML_VPC_PRIVATE_SUBNET_ZONE_A"
  }
}

resource "aws_subnet" "vml_vpc_public_subnet_zone_b" {
  vpc_id = "${aws_vpc.vml_vpc.id}"
  cidr_block = "10.65.65.128/28"
  availability_zone = "ap-southeast-2b"

  tags {
    Name = "VML_VPC_PUBLIC_SUBNET_ZONE_B"
  }
}

resource "aws_subnet" "vml_vpc_private_subnet_zone_b" {
  vpc_id = "${aws_vpc.vml_vpc.id}"
  cidr_block = "10.65.65.192/28"
  availability_zone = "ap-southeast-2b"

  tags {
    Name = "VML_VPC_PRIVATE_SUBNET_ZONE_B"
  }
}

//define aws nat Gateway
resource "aws_nat_gateway" "nat_public_subnet_zone_a" {
  allocation_id = "${aws_eip.nat_public_subnet_zone_a.id}"
  subnet_id = "${aws_subnet.vml_vpc_public_subnet_zone_a.id}"
}

resource "aws_nat_gateway" "nat_public_subnet_zone_b" {
  allocation_id = "${aws_eip.nat_public_subnet_zone_b.id}"
  subnet_id = "${aws_subnet.vml_vpc_public_subnet_zone_b.id}"
}

//define routing for subnets in zone a
resource "aws_route_table" "vml_public_routing_table_zone_a" {
      vpc_id = "${aws_vpc.vml_vpc.id}"

      tags {
        Name = "VML_VPC_PUBLIC_ROUTING_TABLE_ZONE_A"
      }
}

resource "aws_route" "vml_public_route_zone_a" {
    route_table_id = "${aws_route_table.vml_public_routing_table_zone_a.id}"
    destination_cidr_block = "0.0.0.0/0"
    depends_on = [ "aws_route_table.vml_public_routing_table_zone_a"]
    gateway_id = "${aws_internet_gateway.igw_vml_vpc.id}"
}

resource "aws_route_table_association" "vml_public_routing_table_association_zone_a" {
    subnet_id = "${aws_subnet.vml_vpc_public_subnet_zone_a.id}"
    route_table_id = "${aws_route_table.vml_public_routing_table_zone_a.id}"
}

resource "aws_route_table" "vml_private_routing_table_zone_a" {
      vpc_id = "${aws_vpc.vml_vpc.id}"

      tags {
        Name = "VML_VPC_PRIVATE_ROUTING_TABLE_ZONE_A"
      }
}

resource "aws_route_table_association" "vml_private_routing_table_association_zone_a" {
    subnet_id = "${aws_subnet.vml_vpc_private_subnet_zone_a.id}"
    route_table_id = "${aws_route_table.vml_private_routing_table_zone_a.id}"
}

//define routing for subnets in zone b
resource "aws_route_table" "vml_public_routing_table_zone_b" {
      vpc_id = "${aws_vpc.vml_vpc.id}"

      tags {
        Name = "VML_VPC_PUBLIC_ROUTING_TABLE_ZONE_B"
      }
}

resource "aws_route" "vml_public_route_zone_b" {
    route_table_id = "${aws_route_table.vml_public_routing_table_zone_b.id}"
    destination_cidr_block = "0.0.0.0/0"
    depends_on = [ "aws_route_table.vml_public_routing_table_zone_b"]
    gateway_id = "${aws_internet_gateway.igw_vml_vpc.id}"
}

resource "aws_route_table_association" "vml_public_routing_table_association_zone_b" {
    subnet_id = "${aws_subnet.vml_vpc_public_subnet_zone_b.id}"
    route_table_id = "${aws_route_table.vml_public_routing_table_zone_b.id}"
}

resource "aws_route_table" "vml_private_routing_table_zone_b" {
      vpc_id = "${aws_vpc.vml_vpc.id}"

      tags {
        Name = "VML_VPC_PRIVATE_ROUTING_TABLE_ZONE_B"
      }
}

resource "aws_route_table_association" "vml_private_routing_table_association_zone_b" {
    subnet_id = "${aws_subnet.vml_vpc_private_subnet_zone_b.id}"
    route_table_id = "${aws_route_table.vml_private_routing_table_zone_b.id}"
}
//define security groups
resource "aws_security_group" "sg_for_public_routing_table_zone_a" {
    name = "sg_for_public_routing_table_zone_a"
    description = "Security Group For Public Routing Table Zone A"
    vpc_id = "${aws_vpc.vml_vpc.id}"
}

resource "aws_security_group" "sg_for_public_routing_table_zone_b" {
    name = "sg_for_public_routing_table_zone_b"
    description = "Security Group For Public Routing Table Zone B"
    vpc_id = "${aws_vpc.vml_vpc.id}"
}

// define security group rules for zone a
resource "aws_security_group_rule" "sgr_ingress_for_public_routing_table_zone_a" {
    type = "ingress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    security_group_id = "${aws_security_group.sg_for_public_routing_table_zone_a.id}"
}

resource "aws_security_group_rule" "sgr_egress_for_public_routing_table_zone_a" {
    type = "egress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    security_group_id = "${aws_security_group.sg_for_public_routing_table_zone_a.id}"
}

// define security group rules for zone b
resource "aws_security_group_rule" "sgr_ingress_for_public_routing_table_zone_b" {
    type = "ingress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    security_group_id = "${aws_security_group.sg_for_public_routing_table_zone_b.id}"
}

resource "aws_security_group_rule" "sgr_egress_for_public_routing_table_zone_b" {
    type = "egress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    security_group_id = "${aws_security_group.sg_for_public_routing_table_zone_b.id}"
}

//Outputs
output "sg_for_public_routing_table_zone_a" {
  value = "${aws_security_group.sg_for_public_routing_table_zone_a.id}"
}

output "sg_for_public_routing_table_zone_b" {
  value = "${aws_security_group.sg_for_public_routing_table_zone_b.id}"
}

output "vml_vpc" {
  value = "${aws_vpc.vml_vpc.id}"
}

output "vml_vpc_public_subnet_zone_a" {
  value = "${aws_subnet.vml_vpc_public_subnet_zone_a.id}"
}

output "vml_vpc_public_subnet_zone_b" {
  value = "${aws_subnet.vml_vpc_public_subnet_zone_b.id}"
}

output "vml_vpc_private_subnet_zone_a" {
  value = "${aws_subnet.vml_vpc_private_subnet_zone_a.id}"
}

output "vml_vpc_private_subnet_zone_b" {
  value = "${aws_subnet.vml_vpc_private_subnet_zone_b.id}"
}
#############terraform configuration for settting up EC2 ###########################
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.aws_region}"
}

resource "terraform_remote_state" "vml_vpc" {
    backend = "s3"
    config {
      bucket = "vmlau-terraform-state"
      key = "a-aws-vpc-vmlau/terraform.tfstate"
      region = "${var.aws_region}"
    }
}

resource "aws_instance" "vml_au_ec2_aem" {
  ami = "${lookup(var.aws_ami, var.aws_region)}"
  instance_type = "${var.aws_aem_instance_type}"
  key_name = "${var.aws_key_pair}"
  tags {
    Name = "VMLAUTestEC2"
  }

  subnet_id = "${terraform_remote_state.vml_vpc.output.vml_vpc_public_subnet_zone_a}"
  availability_zone = "${lookup(var.aws_availability_zone, var.ap-southeast-2a)}"
  associate_public_ip_address = true
  vpc_security_group_ids = [ "${terraform_remote_state.vml_vpc.output.sg_for_public_routing_table_zone_a}"]

  root_block_device {
    volume_type = "standard"
    volume_size = "50"
  }
}

**Comment by jianhuawuchn** [comment]
strange, it seems working fine now. weird

**Comment by simplyaldo** [comment]
I am experiencing something similar. everything was ok until yesterday. 
Since today `terraform plan` and

**Comment by aesansun** [comment]
broken for me also .

**Comment by apparentlymart** [comment]
@aesansun if you're able to share a little more information, it'd be great if you could open a new issue in [the `aws` provider repository](https://github.com/terraform-providers/terraform-provider-aws). We'd like to get to the bottom of this, but it was closed due to not being reproducible, so if you're able to provide some more context in a new issue that would be very helpful in figuring out what's going on here.

The AWS provider is no longer maintained in this repository, so the older issues about it here will not be getting as much attention as they would've before.

**Comment by aesansun** [comment]
Here is the question. I have a simple module where I feel in the values to create an ec2 instance.

If I run terraform apply it builds the vm, then I run another apply and it destroys the first and builds a new one.

 

I just wanted to add another vm and have it in the state file.

 

module

 

[1:18] 

resource "aws_instance" "vm" {

  count           = "${var.number_of_servers}"

  ami             = "${var.ami-id}"

  instance_type   = "${var.instance_type}"

  key_name        = "${var.ec2-key-name}"

  subnet_id       = "${var.subnet_id}"

  vpc_security_groups_ids  = ["${var.security_group}"]

 

}

 

applicaiton caller

 

module "vm" {

  source            = "/modules/vm_create"

  number_of_servers = "${var.number_of_servers}"

  ami-id            = "${var.ami-id}"

  instance_type     = "${var.instance_type}"

  ec2-key-name      = "${var.ec2-key-name}"

  hostname          = "${var.hostname}"

  ip-address        = "${var.ip-address}"

  port              = "${var.port}"

  security_group    = "${var.security_group}"

  subnet_id         = "${var.subnet_id}"

}
