### ISSUE TITLE
Support for configuring Akamai

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5639]
We are using Akamai as a CDN provider and it would be awesome if we could use Terraform to configure our Akamai sites.

**Comment by joshuaspence** [comment]
I started doing some work on this, but I've run into a few issues so far...

**1. Some resources are read-only**
Some Akamai resources, such as a [contract](https://jsapi.apiary.io/apis/akamaiopen2lunapapiproduction/reference/contracts.html), are read-only. I think that this is because they are created on Akamai's end rather than by the account owner. In the Akamai account that I have access to there exists only a single contract so I was thinking that we could have an `akamai_contract` data source, but I suppose it is possible that other accounts will have multiple contracts. It seems that when creating other resources through the API, they must be linked to a contract.

**2. There is no API sandbox**
There is no API sandbox and I don't think that users can register there own accounts with Akamai. A similar question was asked on [Akamai's community forums](https://community.akamai.com/thread/3340) and the response was:

> Unfortunately, the only way to interact with the services that the APIs expose is to have an account setup with Akamai.

**3. Configuration is readonly**
It seems that (at least in my use case) the primary resources for an Akamai provider would be `akamai_property` and maybe `akamai_property_version`. I think that the data model for Akamai properties is different to what Terraform exacts, though. In Akamai, a property can have multiple versions of its configuration associated with it. The versions are labelled sequentially beginning at 1. Changing _anything_ in the property configuration means that a new version needs to be created. I'm not sure if any other existing Terraform providers behave in this way.

**4. Configuration requires explicit activation**
Once a property has been configured, it is then required to be "activated". Activation can be performed to either the staging environment, the production environment, or both. I'm not sure how best to handle this in Terraform. My initial thought was to leave activation out of scope and require users to manually verify and activate any configuration that Terraform creates. I suppose that another option would be to add some `activate_immediately` property to the resource.

**Comment by CpuID** [comment]
@joshuaspence one thing to note, HashiCorp are normally willing to maintain an active account (with minimal or no traffic throughput) with various CDNs for acceptance testing purposes. I know I went through this with @jen20 for Edgecast/VDMS earlier this year. This may help when you want to perform potentially destructive code testing on resources, and you want to do it on a non-production account.

**Comment by apparentlymart** [comment]
Hi @joshuaspence,

Not sure if this is still useful since I guess you've started already, but FYI the Fastly provider has a similar versioning mechanism to deal with. You can see the notes I made while researching/designing that in #3716.

**Comment by joshuaspence** [comment]
Thanks for the pointer to #3716, definitely useful

**Comment by jschulenklopper** [comment]
Things might have changed (recently). This page, https://developer.akamai.com/api/luna/papi/overview.html, mentions (with emphasis by me):

> The Property Manager API (a.k.a. PAPI) offers a programmatic OPEN interface to manage how Akamai edge servers process requests, responses, and objects served over the Akamai platform. [...] Like the Luna Control Center’s Property Manager [the administration UI - JSc], **this API lets you modify your property configurations and activate them on Akamai staging or production networks.** The API allows you to access the same features rapidly and flexibly using your own tools. **PAPI allows you to generate properties dynamically**, associate them with dynamically generated hostnames, and to create new CP codes to report on your content’s traffic.

Using PAPI requires that Akamai enables that for your account, so account creation and account-level configuration is outside of the scope of this API... but after that many (all?) of the things possible via manual configuration in Luna should be possible via the API.

I reached out to Akamai Community asking for a Terraform provider - apparently that question hasn't been asked there previously.

**Comment by jamiesonio** [comment]
I was looking for Akamai Terraform provider today and came across this that was published recently.
https://github.com/Comcast/terraform-provider-akamai

**Comment by paultyng** [comment]
Closing, as there is a community provider.
