### ISSUE TITLE
aws_db_instance iops param should be only being used when storage_type is io1

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#5648]
In Cloud Formation, the iops param is being ignored unless the storage type is io1.  However, in Terraform, even iops is an optional field, it can't co-exist with storage type is gp2.  Since Terraform does not support condition, it is very difficult to use when applying the same configuration in 2 different environments by using variable files (cannot unassign iops param)

**Comment by iceycake** [comment]
Looks like setting the iops value to -1 can unset the iops param.  However, it is still not as useful as in Cloud Formation so I can preset a iops value and gp2 will simply ignore it until the storage type changes to io1.

**Comment by iceycake** [comment]
Attempt to fix it

https://github.com/hashicorp/terraform/pull/5679

**Comment by catsby** [comment]
We'll resolve this in #5679, thanks!
