### ISSUE TITLE
Cloudformation stack in unrecoverable state should be tainted

### ISSUE THREAD

**Issue by torfredrik** [hashicorp/terraform#5652]
If you create a stack that ends up in the state ROLLBACK_COMPLETE the only way to recover is to delete the stack and recreate it with a valid cloudformation template.

Using terraform I would expect the stack to be tainted when it reaches this state, and any updates I make to the template and apply to the stack should result in a recreation of the stack.

The problem is [shown in this gist.](https://gist.github.com/torfredrik/ad0b18aed804590fc14c)

**Comment by stack72** [comment]
@radeksimko is this usecase covered in your latest CloudFormation fixes ?

**Comment by radeksimko** [comment]
@stack72 it is not. It's probably not a bad idea to taint on `ROLLBACK_COMPLETE`, but I think we've never done it automatically for any other resource and (AFAIK) there isn't any simple way to notify the user when we do this, so I'm not so keen on making this automatic until we have a way to notify the user, e.g.:

```
Error applying plan:

1 error(s) occurred:

* aws_cloudformation_stack.test: ValidationError: Stack:arn:aws:cloudformation:us-west-2:123456789012:stack/test/22955a90-81c9-11e6-b4a4-51a686fe3792 is in ROLLBACK_COMPLETE state and can not be updated.

aws_cloudformation_stack.test was automatically tainted and will be recreated during next apply.
```
