### ISSUE TITLE
Launch configuration user_data can't handle binary

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#5654]
I have a script, called from a <code>aws_launch_configuration</code> in a <code>provisioner "local-exec"</code> that creates a setup script with a embedded BZ2 tarball.

This resulting script is then used in a <code>user_data</code>:

```
  provisioner "local-exec" {
    command = "./bin/package_files_for_LC.sh [options]"
  }

  user_data = "${file("..../userdata-script.sh")}"
```

If I include the tarball in binary form

**./bin/package_files_for_LC.sh**:

```
#!/bin/sh
[misc other stuff]
cat <<EOF > "..../userdata-script.sh"
#!/bin/sh
[misc other stuff]
`cat "../file.tar.bz2"`
```

TF will refuse to create the launch configuration.

However, if i uuencode it, it will work:

**./bin/package_files_for_LC.sh**:

```
#!/bin/sh
[misc other stuff]
cat <<EOF > "..../userdata-script.sh"
#!/bin/sh
[misc other stuff]
`cat "../file.tar.bz2" | uuencode -`
```

However, the resulting file gets quite big. So far the tarball is quite small (just a bunch of other setup shell scripts that I'll need in the provisioning of the instance), so I don't know if there's a size limit on the <code>user_data</code> part.

**Comment by FransUrbo** [comment]
This might be a size issue, so possibly related to #5525.

**Comment by mitchellh** [comment]
If you use cloudinit user data parts, then you can upload binary data.
