### ISSUE TITLE
Missing parameter interpolation from module when updating cloudformation

### ISSUE THREAD

**Issue by torfredrik** [hashicorp/terraform#5656]
When a cloudformation stack that is receiving parameters from a module is updated the parameters from the module are not interpolated and supplied resulting in errors.

Here is a [gist showing](https://gist.github.com/torfredrik/c6ab785d80213d2a3181) the problem.

**Comment by radeksimko** [comment]
Hi,
this should be already fixed in the latest release from today (`0.6.13`).
See https://github.com/hashicorp/terraform/pull/5603

Can you confirm you're running the latest version?

**Comment by torfredrik** [comment]
Updated to version 0.6.13 and the issue is no longer visible.
