### ISSUE TITLE
Add support for DescribeAvailabilityZones call

### ISSUE THREAD

**Issue by rcostanzo** [hashicorp/terraform#566]
Availability zones should be dynamically looked up and then referenced as variables vs. having to hard code them. This is available in the goamz library already and we just need the plumbing to expose the DescribeAvailabilityZonesResp object.

**Comment by mitchellh** [comment]
LGTM. Tagged.

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!
