### ISSUE TITLE
CAPABILITY_IAM missing when updating cfn stack in module

### ISSUE THREAD

**Issue by torfredrik** [hashicorp/terraform#5661]
When an cloudformation stack is updated inside of a module the CAPABILITY_IAM capability is not passed as part of the update.

[This gist](https://gist.github.com/torfredrik/1e8e6f81e5cad2fba88d) shows the problem.

This seems related to https://github.com/hashicorp/terraform/issues/5656 somehow, I think the update for modules must not be including all the arguments that are included during creation of the stack.

**Comment by radeksimko** [comment]
Hi,
this should be already fixed in the latest release from today (`0.6.13`).
See https://github.com/hashicorp/terraform/pull/5603

Can you confirm you're running the latest version, please?

**Comment by torfredrik** [comment]
Updated to 0.6.13, this fixed the issue. Closing this issue.
