### ISSUE TITLE
Elasticsearch EBS documentation doesn't seem correct

### ISSUE THREAD

**Issue by yissachar** [hashicorp/terraform#5665]
According to the [docs](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html), `ebs_options.volume_size` is optional. Yet if I ignore it and attempt to `apply` I receive the following error:

> aws_elasticsearch_domain.es: ValidationException: Volume size must be provided when EBS is enabled.

Terraform file:
```
resource "aws_elasticsearch_domain" "es" {
    domain_name = "es"

    cluster_config {
        instance_type = "t2.small.elasticsearch"
        instance_count = "1"
    }

    ebs_options {
        ebs_enabled = true
    }
}
```

**Comment by phinze** [comment]
Ah thanks for the heads up, @yissachar - will get this fixed! :+1:

**Comment by catsby** [comment]
Documented in #5693 , thanks! Unfortunately we can only document it, because the field isn't required unless `ebs_enabled` is true.
