### ISSUE TITLE
Instance destruction not appearing in plan

### ISSUE THREAD

**Issue by Gary-Armstrong** [hashicorp/terraform#5669]
OK, so I don't have the luxury to repro this right now but I do have text evidence.  I know!  Also, apologies for the length.

So here's the general timeline.
I have been mostly successfully manipulating my env by altering count vars on the command line.  Mostly, because EIP (re)attachment falls on the ground when I change counts from 1 to 1+n when n > 0... but that's a separate issue.

Today I grabbed TF 0.6.13 and it seems like a great improvement for someone like me.  Very excited.
Anyway, I needed to make a test instance.

```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan -var 'wxtest_count=1'
Refreshing Terraform state prior to plan...
...
+ aws_instance.wxtest
    ami:                                               "" => "ami-61bbf104"
...
```

That's awesome and I do a few more plans before the apply.

```
Plan: 2 to add, 0 to change, 0 to destroy.
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform apply -var 'wxtest_count=1'
...
aws_instance.wxtest: Creating...
  ami:                               "" => "ami-61bbf104"
...
```
I get some errors when I picked a bad IP address but that is easily resolved.  Instance is created and provisioner starts but fails due to ssh failing.  I assume this is unrelated.
```
Error applying plan:

1 error(s) occurred:

* dial tcp 10.233.212.4:22: i/o timeout
```

Fine, I've see this many times.  Since the default count is zero, and plain plan will destroy this thing.
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan
Refreshing Terraform state prior to plan...

aws_instance.wxtest: Refreshing state... (ID: i-8283f401)
...
No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```
That is very bad.  Doing `terraform plan -var 'wxtest_count=1'` will then recreate the test instance:
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan -var 'wxtest_count=1'
Refreshing Terraform state prior to plan...

aws_iam_role.wxmix_role: Refreshing state... (ID: wxmix-qa-us-east-1-role)
aws_eip.nat: Refreshing state... (ID: eipalloc-30ed0b57)
aws_iam_policy.wxmix_policy: Refreshing state... (ID: arn:aws:iam::133124267079:policy/wxmix-qa-us-east-1-policy)
aws_vpc.main: Refreshing state... (ID: vpc-55d8ad31)
aws_instance.wxtest: Refreshing state... (ID: i-8283f401)
...
-/+ aws_instance.wxtest
    ami:                               "" => "ami-61bbf104"
...
+ null_resource.provision_wxtest


Plan: 2 to add, 0 to change, 0 to destroy.
```

I decide to change the instance type.  You can see that the instance shows up in the refresh.
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan -var "wxtest_instance_type=t2.small"
Refreshing Terraform state prior to plan...

aws_eip.nat: Refreshing state... (ID: eipalloc-30ed0b57)
aws_vpc.main: Refreshing state... (ID: vpc-55d8ad31)
aws_iam_policy.wxmix_policy: Refreshing state... (ID: arn:aws:iam::133124267079:policy/wxmix-qa-us-east-1-policy)
aws_instance.wxtest: Refreshing state... (ID: i-8283f401)
...
No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

OK, that is just flat out wrong.  Extant instance is a t2.micro.

Maybe I can just get rid of it and start over.  I've "fixed" a lot of things that way.
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan -destroy -target=aws_instance.wxtest
Refreshing Terraform state prior to plan...

aws_instance.wxtest: Refreshing state... (ID: i-8283f401)

No changes. Infrastructure is up-to-date. This means that Terraform
```

Oh, dear.  Is it in the tfstate?
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ grep wxtest terraform.tfstate
                "aws_instance.wxtest": {
```
It is.  Well, I actually have another task I'm working on involving network changes so I just go work on that and ignore this test instance.  That's when the BAD THING happens.
```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform plan
Refreshing Terraform state prior to plan...

aws_nat_gateway.nat_gw: Refreshing state... (ID: nat-06ad86bdb5ecd3802)
aws_iam_policy.wxmix_policy: Refreshing state... (ID: arn:aws:iam::133124267079:policy/wxmix-qa-us-east-1-policy)
aws_vpc.main: Refreshing state... (ID: vpc-55d8ad31)
aws_instance.wxtest: Refreshing state... (ID: i-8283f401) # <=== MY BUDDY
...
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

- aws_eip.nat

-/+ aws_instance.viewer
    ami:                                            "ami-9eb789f4" => "ami-9eb789f4"
    associate_public_ip_address:                    "false" => "0"
...

- aws_nat_gateway.nat_gw

~ aws_route_table.wxmix_qa
    route.1577844729.cidr_block:                "" => "0.0.0.0/0"
    route.1577844729.gateway_id:                "" => "igw-66a95002"
...
Plan: 1 to add, 1 to change, 3 to destroy.
```
So, add 1 (new viewer instance), change 1 (route table), destroy 3 (EIP, nat gw, and old viewer).  Looked legit on a quick review.  I mean, the 3rd destroy was the old viewer instance, right?

```
Garys-IBM-MacBook-Pro:config-qa-aws-us-east-1 gmstrong$ terraform apply
aws_nat_gateway.nat_gw: Refreshing state... (ID: nat-06ad86bdb5ecd3802)
aws_vpc.main: Refreshing state... (ID: vpc-55d8ad31)
aws_instance.wxtest: Refreshing state... (ID: i-8283f401)  # <==== HEY BUDDY!
...
aws_nat_gateway.nat_gw: Destroying...
aws_instance.viewer: Destroying...
aws_instance.wxtest: Destroying...    # <==== ???
aws_instance.wxtest: Destruction complete    # <==== ???
...
Apply complete! Resources: 1 added, 1 changed, 4 destroyed.  # <==== !!!
```
Four destroyed.  That's unexpected.
Confirmed "wxtest" does not appear in the .tfstate and confirmed it is Terminated in AWS via console.

I actually have to leave now but I'll be happy to provide TF code samples tomorrow when I come online again.

**Comment by phinze** [comment]
Hi @Gary-Armstrong - thanks for the report. What you're seeing is an expression of https://github.com/hashicorp/terraform/issues/4156 - when provisioners are failing on your instance, it's being marked as `tainted`, which schedules it for cleanup in a later run. `terraform show` will list the instance as tainted in the state to confirm this.

Once we get #4156 implemented (a task that is fairly high on our priority list!) this behavior should get a _lot_ clearer as it's happening.

After looking over #4156, does this all sound right to you?

**Comment by Gary-Armstrong** [comment]
That does sound like what is happening here.  When I get a spare minute tomorrow, I'll see about rewinding through git commits and see if I accidentally committed a tfstate with wxtest tainted, just to confirm.

**Comment by phinze** [comment]
Tainted resources will show up in the plan in the next Terraform release now that #6600 is done! 👍
