### ISSUE TITLE
Create subnets only after possibly conflicting subnets have been destroyed

### ISSUE THREAD

**Issue by delitescere** [hashicorp/terraform#567]
v0.3.1

I renamed some subnet resources in the terraform file.

The `apply` didn't complete destroying the old subnets before creating the new ones. I received ` Error creating subnet: The CIDR '10.0.1.0/24' conflicts with another subnet (InvalidSubnet.Conflict)` errors, even though the subnet that it conflicted with was being asynchronously being destroyed.

Options:
1a) Analyse the current state and plan, work out that a subnet needn't be destroyed at all (it is just renamed in the source and plan files), and/or
1b) Calculate IP range dependencies for existing and new overlapping subnets (e.g. a previous /24 subnet is being removed and two /25 subnets replacing the same range), make the destroy/create steps sequential for those that need it

or 

2) New subnets not created until all subnets that are going to be destroyed have destruction complete

**Comment by phinze** [comment]
Hello! I believe we have since handled this via better API polling in the subnet resource. Feel free to follow up if you're still experiencing this in the latest version of Terraform. :+1:
