### ISSUE TITLE
ASG metrics_collection does not support update, but is not ForceNew

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5671]
Was just reviewing the `metrics_collection` stuff again for [this CHANGELOG update](https://github.com/hashicorp/terraform/commit/725ffe01d642b1629e63bc7a21e5d33d269c49f9) and realized it has no update code path. So users changing this on an existing ASG will see an update in the plan, but no change will actually be made.

I might be reading the code wrong, but wanted to note this here so we can follow up.

**Comment by phinze** [comment]
cc @stack72

**Comment by stack72** [comment]
Just a FYI, according the AWS SDK and the [docs](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#metrics_granularity), the only value accepted here is 1Minute. Therefore people can change this value but it won't technically do anything anyway in AWS :) 

```
type EnableMetricsCollectionInput struct {
	_ struct{} `type:"structure"`

	// The name or ARN of the Auto Scaling group.
	AutoScalingGroupName *string `min:"1" type:"string" required:"true"`

	// The granularity to associate with the metrics to collect. The only valid
	// value is 1Minute.
	Granularity *string `min:"1" type:"string" required:"true"`
```

PR incoming to update docs

**Comment by phinze** [comment]
Reflecting some chat we had about this - documenting the default seems like the thing to do for now, and we can circle back on the update case if/when this field actually accepts other values.
