### ISSUE TITLE
aws_lambda_function requires s3_object_version on update but not on initial creation

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#5673]
So, for the following config:

```
resource "aws_lambda_function" "assessment-trait-scores-scaler" {
    s3_bucket = "${var.jenkins_archive}"
    s3_key = "kinesis_scaler/assessment-trait-scores-scaler-${consul_keys.assessment-trait-scores-scaler.var.version}.jar"
    function_name = "assessment-trait-scores-scaler-${var.env}"
    role = "${aws_iam_role.assessment-trait-scores-scaler.arn}"
    handler = "com.traitify.lambda.ScaleKinesis::handle"
    memory_size = 512
    runtime = "java8"
    timeout = 300
    vpc_config {
      subnet_ids = [ "${split(",", var.subnets)}" ]
      security_group_ids = [ "${var.default_sg}" ]
    }
}
```

I have no problem doing an initial update of the lambda function, but on a subsequent update where the function changes I get the following error:

```
* aws_lambda_function.assessment-trait-scores-scaler: Error modifying Lambda Function Code assessment-trait-scores-scaler-stag: InvalidPar
ameter: 1 validation errors:
- field too short, minimum length 1: S3ObjectVersion
```

To resolve this I have to add in a line:

```
    s3_object_version = "null"
```

Then things work as expected.  As a note, there is no version on the object in S3, so this should not be required.

I'm on Terravorm v0.6.13

Thanks!
-Dan

**Comment by radeksimko** [comment]
I guess we could make `s3_object_version = "null"` by default in update calls if it's not defined.

FYI: There is no way to update the Lambda function if the bucket is not versioned, so it will always be using the same code until you either enable versioning on that bucket and start using `s3_object_version` or start using `filename` & `source_code_hash` or `taint` the whole resource.

I don't have objections against different (rare) use-cases, but can you help me understand why do you not want to update you Lambda function (ever)? I'm having a (strange) feeling that people may expect this to just work (i.e. be constantly update) without S3 versioning.

**Comment by dansteen** [comment]
thanks for the reply @radeksimko 

In the config above, you will see that we define the s3_key as:
```
s3_key = "kinesis_scaler/assessment-trait-scores-scaler-${consul_keys.assessment-trait-scores-scaler.var.version}.jar"
```

This uses a dynamic variable as the name of the jar file to push up to lambda.   This value changes based on the contents of consul, so we get our updates that way, rather than versioning the same file in s3.

Does that make sense?

**Comment by radeksimko** [comment]
I see, so you're versioning via S3 object key, that makes total sense - totally valid use case.

Thanks for the explanation!

**Comment by norcalli** [comment]
I was doing the same thing and ran into the problem. Setting `s3_object_version` to "null" worked, but I would like it to do this by default since it's not documented. I was also versioning by appending the `etag`.

**Comment by FastNinja** [comment]
+1 same issue.

**Comment by justinsoliz** [comment]
Just an FYI, Im still seeing the exact behavior described above
version: Terraform v0.7.2

Something else to note, if you do flip versioning on the bucket, setting the `s3_object_version` to null will not work.
