### ISSUE TITLE
MySQL provider. Issue with cycle dependencies and graph (0.6.12, 0.6.14)

### ISSUE THREAD

**Issue by partamonov** [hashicorp/terraform#5687]
```
resource "aws_db_instance" "db" {
  identifier = "${lower("${var.name}")}"
  allocated_storage = "5"
  engine = "mysql"
  engine_version = "5.6.27"
  instance_class = "db.t2.micro"
  username = "admin"
  password = ""
  multi_az = false
  apply_immediately = true
  db_subnet_group_name = "${aws_db_subnet_group.rds.id}"
  vpc_security_group_ids = ["fgdgfgdgdf"]
  publicly_accessible = false
  backup_retention_period = 0
}

/*provider "mysql" {
    endpoint = "${aws_db_instance.db.endpoint}"
    username = "${aws_db_instance.db.username}"
    password = "gdfgfdgdfgdf"
}

resource "mysql_database" "discovery" {
    depends_on = ["aws_db_instance.db"]
    name = "discovery"
    provisioner "local-exec" {
      command = "D:/tools/mysql/bin/mysql.exe --host=${aws_db_instance.db.address} --user=${aws_db_instance.db.username} --password=dfgdfgdfg --protocol=TCP --database=${self.name} < CREATE.sql"
    }
}
```

This part of code causing issues. (see attched create.log)

And if I'm creating RDS instance first and as second run I'm creating DBs everything is fine, but destroy failing with

```
aws_db_instance.db: Refreshing state... (ID: cisdocker)
mysql_database.preview: Refreshing state... (ID: preview)
mysql_database.discovery: Refreshing state... (ID: discovery)
mysql_database.deployer: Refreshing state... (ID: deployer)
Error creating plan: 1 error(s) occurred:

* Cycle: mysql_database.discovery (orphan), mysql_database.deployer (orphan), mysql_database.preview (orphan), aws_db_instance.db (destroy), aws_db_subnet_group.rds (destroy), aws_db_subnet_group.rds, aws_db_instance.db, provider.mysql
```

And once again commenting mysql databases part and apply did the trick for first run and second run can be with destroy flag

[create.txt](https://github.com/hashicorp/terraform/files/177415/create.txt)

**Comment by partamonov** [comment]
Also crashed today with 0.6.14
```
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: github.com/hashicorp/terraform/builtin/providers/mysql.providerConfigure(0xc0821d04e0, 0x0, 0x0, 0x0, 0x0)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/mysql/provider.go:50 +0x37c
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc0821aed20, 0xc0821a89c0, 0x0, 0x0)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:143 +0x1c2
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Configure(0xc0821d60e0, 0xc0821a89c0, 0xc0821b8190, 0x0, 0x0)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:313 +0x5f
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: reflect.Value.call(0xa237e0, 0xb01ca8, 0x13, 0xb552b8, 0x4, 0xc0821c7ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/go/src/reflect/value.go:435 +0x1214
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: reflect.Value.Call(0xa237e0, 0xb01ca8, 0x13, 0xc0821c7ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/go/src/reflect/value.go:303 +0xb8
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: net/rpc.(*service).call(0xc0821b49c0, 0xc0821b4980, 0xc082155ae8, 0xc08206b200, 0xc0821d6100, 0xafada0, 0xc0821a89c0, 0x16, 0x9323c0, 0xc0821b8190, ...)
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/go/src/net/rpc/server.go:383 +0x1c9
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: created by net/rpc.(*Server).ServeCodec
2016/03/29 09:07:46 [DEBUG] terraform-provider-mysql.exe: 	/opt/go/src/net/rpc/server.go:477 +0x4a4
```

**Comment by partamonov** [comment]
Looks like I realized the root cause of this issue.
mysql provider tries to establish connection even during plan phase to db endpoint.
```
resource "aws_db_instance" "db" {
  identifier = "${lower("${var.name}")}"
  allocated_storage = "5"
  engine = "mysql"
  engine_version = "5.6.27"
  instance_class = "db.t2.micro"
  username = "admin"
  password = ""
  multi_az = false
  apply_immediately = true
  db_subnet_group_name = "${aws_db_subnet_group.rds.id}"
  vpc_security_group_ids = [""]
  publicly_accessible = false
  backup_retention_period = 0
}
output "Database Address" {
  value = "${aws_db_instance.db.address}"
}

provider "mysql" {
    endpoint = "test.com:3306" **<-- here was ${aws_db_instance.db.endpoint}**
    username = "${aws_db_instance.db.username}"
    password = ""
}

resource "mysql_database" "new" {
    name = "discovery"
    provisioner "local-exec" {
      command = "Blah"
    }
}
```

After change of variable to hardcoded value I see the following error
```
> terraform plan
Refreshing Terraform state prior to plan...

Error refreshing state: 1 error(s) occurred:

* dial tcp 69.172.200.235:3306: connectex: No connection could be made because the target machine actively refused it.
``` 

May be the same way of configuration as for postgre will fix that or we should not evaluate
```
        proto := "tcp"
	if endpoint[0] == '/' {
		proto = "unix"
	}
```

**Comment by partamonov** [comment]
@apparentlymart just to mention you here. I can try to fix that

**Comment by apparentlymart** [comment]
Hi @partamonov. Thanks for reporting this and sorry for these problems.

I am a little confused here because I am familar with this problem of the provider trying to connect too early, but I thought I remembered already fixing it by following the example set in the Postgres provider -- connecting separately for each operation, rather than trying to open the connection early in the provider configuration.

It looks like I didn't, because the current code still has the connection during provider `Configure`.

If you'd like to work on fixing this that'd be awesome. I can review when you're done. Otherwise, I will come back to this at some point but won't be able to work on it immediately.

**Comment by partamonov** [comment]
@apparentlymart I've started today. Will create PR by the end of the week

**Comment by partamonov** [comment]
No luck so far. I tried to variants. I was able to resolve issue with `terraform plan` - it now works fine.

But I still having issue with creating MySQL instance and databases in it. It looks for me that during first run mysql provider is not able to capture endpoint from AWS RDS Instance in my case.

In one variant I have:
`mysql_database.app: Error creating MySQL database: driver: bad connection`
In second:
`mysql_database.app: dial tcp: missing address`

Second run works fine.
Deletion still has dependency issue #4645
`* Cycle: aws_security_group.docker (destroy), aws_security_group.docker, mysql_database.app (destroy), aws_db_instance.db (destroy), aws_db_subnet_group.rds (destroy), aws_db_subnet_group.rds, aws_db_instance.db, provider.mysql`

**Comment by Hoverbear** [comment]
Hi!
We bumped into this issue as well. I went ahead and tested https://github.com/partamonov/terraform/blob/mysql-5687/builtin/providers/mysql/provider.go against this test Terraform file:

```terraform
variable "token" {}

provider "digitalocean" {
    token = "${var.token}"
}

resource "digitalocean_droplet" "db" {
    name = "db-${count.index}"
    size = "512mb"
    region = "fra1"
    image = "centos-7-x64"
    count = 1
    ssh_keys = [ "<REDACTED>" ]
    
    connection {
        type = "ssh"
        user = "root"
        private_key = "<REDACTED>"
    }
    provisioner "remote-exec" {
        inline = [
            "yum install mariadb-server -y",
            "systemctl start mariadb"
        ]
    }
}

provider "mysql" {
    endpoint = "${digitalocean_droplet.db.ipv4_address}:3306"
    username = "root"
    password = "test"
}

resource "mysql_database" "test" {
    name = "test"
}
```

This is able to plan just fine. Applying hits a bump because the provisioner can't actually connect to the server (it's prevented by the configuration).

I'd like to help get that patch set into shape to merge. What are the remaining steps, @apparentlymart ?

**Comment by mengesb** [comment]
I'm hitting the problem that @Hoverbear is hitting; I can't create an instance that has a DB already installed, and then use the mysql provider to do things later with mysql resources. I have to have the DB up and connectable with an account BEFORE i have this provider and resources.

Using TF 0.7.0

**Comment by jgreen-zynga** [comment]
We're seeing this still as well on TF 0.7.13. @Hoverbear, is your fix still viable? @apparentlymart is there something we can do to help?

**Comment by partamonov** [comment]
@jgreen-zynga I think one on latest commits from Mitchell should fix that, see #4645

**Comment by jgreen-zynga** [comment]
Thanks! Will check it out and monitor when it hits release.

**Comment by zackpete** [comment]
I'm having the same problem on v0.8.5 (and it looks like the commits from #4645 are in the 0.8.5 release, so they may not have fixed this)

[Config that reproduces it](https://gist.github.com/zackpete/a5044894f72058881778155d65f3d002)

I used an interpolated value from the docker_container.mysql_server.hostname in the mysql provider, trying to get it to recognize the dependency (since you can't use 'depends_on' in a provider) otherwise the mysql provider tries to connect to a nonexistent docker container, if it hasn't been provisioned yet.

[Resulting log](https://gist.github.com/zackpete/fa369e905372650290f2ff158263de3b)

**Comment by dharani30** [comment]
I need to fetch the rds username and password from the vault in terraform. how I can do it

**Comment by dharani30** [comment]
this is my command to fetch the dbusername from vault.

cat rdsusername.sh
username=`curl -s --insecure -k -H "X-Vault-Token: xxxx" -X GET http://x.x.xx:8200/v1/secret/rdsuser |  awk 'BEGIN { FS = "data" } { print $2 }' |  cut -d ":" -f3 | cut -d "\"" -f2`
echo $username

I need to take the output of this file as my mysql dbusername.

resource "aws_db_instance" "testrds" {
    identifier                      = "testrds_mysqlrds"
      name                            = "${testrds_name}"
    username                        = ""
    password                        = ""
  
Please someone help.
