### ISSUE TITLE
provider/aws: KMS key may fail to enable key rotation

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5688]
Pasting from Travis [nightly job](https://travis-ci.org/hashicorp/terraform/jobs/116552314):

```
--- FAIL: TestAccAWSKmsKey_isEnabled (406.01s)
    testing.go:148: Step 2 error: Error applying: 1 error(s) occurred:

        * aws_kms_key.bar: Failed to set key rotation for "7e5a8e30-49a3-4257-b12a-277cf3d6bfaa" to true: "DisabledException: arn:aws:kms:us-west-2:187416307283:key/7e5a8e30-49a3-4257-b12a-277cf3d6bfaa is disabled.\n\tstatus code: 400, request id: 4f313968-ebfc-11e5-abec-6fffd87a64bf"
```

I'm pretty sure this test was passing before, so I assume it's intermittent and related to the eventually consistent nature of KMS.

**Comment by stack72** [comment]
FYI, the issue here is that you cannot Rotate a disabled key

So the test is incorrect

**Comment by stack72** [comment]
@radeksimko not even via the UI can I rotate a key that is disabled :)

**Comment by radeksimko** [comment]
> not even via the UI can I rotate a key that is disabled :)

I'm not arguing about that, I'm saying we are **not** trying to rotate a key that is disabled. Check the code. 😉
