### ISSUE TITLE
provider/GCE : instance group manager cannot have 0 instace at creation

### ISSUE THREAD

**Issue by menren** [hashicorp/terraform#5690]
In some case I would like to creation a instance group manager with 0 instance in the beginning.
Even with `target_size = 0`, the instance group is created with 1 instance.

Is it an expected behaviour or a bogus ?

As a workaround I can rescale the target size to 0, but how do I create an instance group with 0 instance ?

**Comment by stack72** [comment]
Hi @menren 

This is due to a known issue in terraform when using 0 values. The fix required for this is being tracked in #5694 

When this is finished, we should be able to get this working

Thanks

Paul

**Comment by menren** [comment]
Hi @radeksimko @stack72 

thank you for tracking this issue and hope that the fix is finished soon :)

**Comment by menren** [comment]
Hello @stack72 do you have any news about this ticket ?

Thanks
