### ISSUE TITLE
Add "generated" tag to tfstate file

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5698]
We currently commit our `tfstate` file into our `git` repository. It would be beneficial to us if the `tfstate` file contained `{ "@generated": true }` because this would indicate to our linters and code review tool (Phabricator) that this file is generated and does not need to be linted/reviewed.

**Comment by stack72** [comment]
Hi @joshuaspence 

I brought this up with the team - we think that this is very tool specific. If we added something like this to the state file then it would open up a lot more requests for other specific tooling additions. I think your best bet would be to build some level of scripting around this to ensure that the file doesn't need linted or reviewed

Sorry if this isn't what you were expecting to happen for this :(

Paul
