### ISSUE TITLE
Store arrays in variables

### ISSUE THREAD

**Issue by gwagner** [hashicorp/terraform#57]
I have lists of security groups and or lists of ec2 instances that i would like to to keep in arrays ( separated by files which are auto loaded by *.tf ) so i know when i change things in one place, it gets changed in another.  

Right now vars can only hold strings or key value maps, but not arrays (if i am reading the docs and error messages correctly)

**Comment by ojongerius** [comment]
:+1:

**Comment by justinclayton** [comment]
:+1:

**Comment by glongman** [comment]
:+1:

**Comment by kubek2k** [comment]
:+1: + same for maps

**Comment by sbward** [comment]
:+1:

**Comment by joescii** [comment]
:+1:, y'all

**Comment by joegoggins** [comment]
+1. Looks like this is done already and slated for [release in 0.4.0](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md)

btw: the way you guys maintain your changelog.md is down right inspiring and incredibly useful. 
You don't see that often enough in the open source world--props!

**Comment by mitchellh** [comment]
@joegoggins Not completely fixed but there is certainly a workaround in 0.4.0.

**Comment by mitchellh** [comment]
And thanks for the compliments on the changelog! :)

**Comment by clstokes** [comment]
What's the status of this? My use case is the same as the OP's. I don't see mention of this in the 0.4.0 release notes...

**Comment by clstokes** [comment]
Split/join is the workaround for now I take it?

**Comment by mitchellh** [comment]
Yes, for now.

**Comment by lyrixx** [comment]
:+1: and then we will need to be able to do something like:

```
        cidr_blocks = ${var.ip1} +  ${var.ip2} + ["0.0.0.0/0"]
```

**Comment by jamesob** [comment]
Is someone currently at work on this? I'm willing to jump in and start a patch if not.

**Comment by jamesob** [comment]
I'm not able to get the `split`/`join` hack working for `aws_instance.security_groups`. I've got a module configured this way:

```
# foo.tf

resource "aws_instance" "server" {
  ...
  security_groups = "${split(",", var.sec_groups)}"
}


# variables.tf

variable "sec_groups" {                                                                                                                                                                                                              
   default = "sg-xx,sg-x,sg-xxx"
   description = "The security groups to instantiate the EC2 instance under."                                                                                                                                                                                                                                                                        
}
```
and using it thusly
```
# foo_user.tf

module "foo" {
  sec_groups = "sg-x,sg-xx,sg-xxx,sg-xxxx"
} 
```
and getting this error:
```
 ⇨  terraform plan -var "access_key=$KEY" -var "secret_key=$SECRET" -module-depth=1

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_instance.server: security_groups: should be a list
```
Any insight?

**Comment by johnrengelman** [comment]
I think you need to wrap your usage of split with [ ].
So
security_groups = ["${split(",", var.sec_groups)}"]

**Comment by jamesob** [comment]
Thanks, @johnrengelman. Two things:

1. Wow, that's nuts.
2. Is this in the docs anywhere?

**Comment by johnrengelman** [comment]
Um. Not sure. Did that work for you? 
Sorry I'm only on my phone right now.

**Comment by jamesob** [comment]
Yeah, it did. Been pouring over the docs for the better part of the day and didn't see that anywhere...

**Comment by radeksimko** [comment]
> Wow, that's nuts.

Agree with you here, I made the same mistake the other day, but I'm afraid this is all coming from the fact that there's no direct support for arrays yet. It's all internally stored in a string so far.

> Is this in the docs anywhere?

Interpolations are generally documented [here](https://www.terraform.io/docs/configuration/interpolation.html), I can't think of any specific place that would be mentioning this behaviour though, feel free to chime in with PR to docs.

**Comment by johnrengelman** [comment]
Yeah I think that's just one of those things about indicating that it's an array. I ran into that earlier this week.

**Comment by radeksimko** [comment]
>  feel free to chime in with PR to docs.

unless @mitchellh or the core team plans to work on the array support for the next release, but AFAIK it's not currently the top priority on the list. // please correct me if I'm wrong

**Comment by solarce** [comment]
@jamesob it's documented in the sense that certain Attributes of specific resources require a `list` input, and using `.split()` is a "workaround" to generate a string inside the `list` that matches HCL's list formatting.

You need to reference specific resource attribute documentation to determine if the correct input needs to be a list or not, e.g. http://www.terraform.io/docs/providers/aws/r/db_parameter_group.html#parameter or http://www.terraform.io/docs/providers/aws/r/route_table.html#propogating_vgws are `lists`

**Comment by jamesob** [comment]
@solarce nowhere is it documented that you use an unintuitive notation to signal that a string is "actually" a list by way of some interpolation function, i.e. `["${split(",",var.foo)}"]`. This is a bug.

I'll be submitting a doc PR in the next few minutes in the `module` section, detailing 

1. the limitation of modules, and 
2. the workaround necessary for parameterizing lists in modules.

**Comment by solarce** [comment]
@jamesob it's not limited to modules, even when you're declaring actual resources directly in your configuration file, some inputs to attributes need to be a list and use `[ "item1"]` synatx , even if it's just a list of one item.

The entire point of using split and join is working around the fact that right now a string is the only thing that can only be assigned to a variable.

**Comment by jamesob** [comment]
PR up at https://github.com/hashicorp/terraform/pull/1878.

**Comment by johnrengelman** [comment]
@jamesob I think what is happening here is that when you initially declare the `split` it's inside a string interpolation. So from the perspective of the code that's parsing the parameters, there is a String there. So you need to wrap the string in `[]` to make it a list. The interpolation must be happening later which breaks the single string into multiple.

**Comment by c4milo** [comment]
has there been any progress on this? I just had an issue with the join/split workaround: https://github.com/hashicorp/terraform/issues/1997

**Comment by jamesob** [comment]
@c4milo I'm taking a look at this today. Golang newbie here though, so no promises :).

**Comment by arothian** [comment]
+1 This would be a big help!

**Comment by larstobi** [comment]
:+1:

**Comment by larstobi** [comment]
:+1:

**Comment by baguasquirrel** [comment]
:+1:

**Comment by blewa** [comment]
+1

**Comment by james-s-nduka** [comment]
:+1: Would help massively

**Comment by franklinwise** [comment]
It's been a year... is this going to happen?

**Comment by jamesob** [comment]
I'm waiting here for advice/a second pair of eyes: https://github.com/hashicorp/terraform/pull/2697

**Comment by pearcec** [comment]
:+1:

**Comment by lekkerdriveway** [comment]
Would love this solved!

**Comment by gtmtech** [comment]
Would be very useful in making code clearer :+1:

**Comment by ajvb** [comment]
:+1:

**Comment by Sam-Martin** [comment]
:+1:

**Comment by igoratencompass** [comment]
+1

**Comment by roderickrandolph** [comment]
:+1:

**Comment by stvnwrgs** [comment]
:+1:

**Comment by milsonian** [comment]
:thumbsup:

**Comment by Deserved** [comment]
+1 This one and nested array/maps are most missing features

**Comment by cleung2010** [comment]
:+1:

**Comment by fulloflilies** [comment]
+1

**Comment by zrml** [comment]
:+1:

**Comment by nrcxcia** [comment]
+1

**Comment by orimarti** [comment]
+1

**Comment by comerford** [comment]
:+1:

**Comment by jakshi** [comment]
:+1:

**Comment by jen20** [comment]
This is actively being worked on at the moment - in due course changes will appear in `hashicorp/hil` and then in this repository,

**Comment by thanandorn** [comment]
:+1:

**Comment by stefancocora** [comment]
:+1:

**Comment by baguasquirrel** [comment]
:fireworks:

-- sent on the fly

**Comment by jbiel** [comment]
:+1:

**Comment by rizvfe00** [comment]
:+1:

**Comment by bgeffe-rms** [comment]
:+1:

**Comment by aamorin** [comment]
:+1:

**Comment by franklinwise** [comment]
+1

**Comment by bendodd** [comment]
+1

**Comment by BastienM** [comment]
:+1:

**Comment by whiteadam** [comment]
+1

**Comment by lyrixx** [comment]
Hey guys ; it's official ; we can now stop adding :+1: to this thread
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by tamsky** [comment]
In an attempt to challenge folks' idea that +1 comments are useless (to anyone), I'd like to share my reason for using it:

I'm subscribed to many issues across many repos.

Within a repo, I'd like to be able to search issues by `notifications:subscribed`.  But that feature doesn't exist.  Boo.

If the new reactions feature could help me search for issues I care about, I'd use that, but since it doesn't, I'll be continuing to post +1 comments so I can use `commenter:$USERNAME` as a proxy for "find issues that I'm subscribed to".

**Comment by whiteadam** [comment]
Yeah, that's why I +1 also :)

DIE EMOJI!

**Comment by vmorris** [comment]
This has been open for a year, everybody wants it, any status?

**Comment by mitchellh** [comment]
Most the work to support this is merged already for 0.7. I expect a close is imminent.

**Comment by fwisehc** [comment]
Eta?

**Comment by tehmaspc** [comment]
Soon. Watch CHANGELOG.md -  0.7 changes are already being updated.

**Comment by stack72** [comment]
Hi all

I am going to close this - all of the initial work for lists has been merged. There are a few outstanding issues being tracked but there are open issues for these

Paul

**Comment by balser** [comment]
Where is the best place to track this enhancement moving forward?

**Comment by stack72** [comment]
@baler 0.7 will allow lists in variables

**Comment by davyt10** [comment]
could you provde an example of how to pass list in variable? I am still getting an error when passing a list of instances to an ELB module.
error
variable instances in module solrs_elb should be type string, got list

module
module "solrs_elb" {
 source = "../../modules/Generic/mod_elb_slrs"
 environment = "${var.environment}"
 application = "${var.application}"
 slrs_elb_sg = "${module.ci_solrs_elb_sg.SLRS_ELB_SG_ID}"
 subnet_AZa =  "${var.slrs_elb_subnet_private1}"
 subnet_AZb =  "${var.slrs_elb_subnet_private2}"
 instances = ["${aws_instance.CI03T02QSLRS.0.id}","${aws_instance.CI03T02QSLRS.1.id}"]
}


elb resource

resource "aws_elb" "ELB-SLRS" {
  name            = "ELB-${var.environment}-SLRS"
  internal        = true
  subnets         = ["${var.subnet_AZa}", "${var.subnet_AZb}"]
  security_groups = ["${var.slrs_elb_sg}"]

  listener {
    instance_port     = 8080
    instance_protocol = "http"
    lb_port           = 8080
    lb_protocol       = "http"
  }

  health_check {
    healthy_threshold   = 10
    unhealthy_threshold = 2
    timeout             = 5
    target              = "TCP:8080"
    interval            = 30
  }

 instances = ["${var.instances}"]

  cross_zone_load_balancing = true
  idle_timeout = 60
  connection_draining = true
  connection_draining_timeout = 400 

  tags {
    Name        = "ELB-${var.environment}-SLRS"
    Application = "${var.application}"
    Environment = "${var.environment}"
    Balancing   = "SOLRSlave"
  }
}

**Comment by johnrengelman** [comment]
@davyt10 inside your module you declare something like `variable instances {}`. Trying changing that to be:
```
variable instances {
  type = "list"
}
```

**Comment by davyt10** [comment]
worked..thankyou!
