### ISSUE TITLE
Required target_id param in aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#5702]
The target_id looks like an arbitrary id to guarantee the unique of the event rule target.  Should it be a computed schema instead of a required schema?

**Comment by radeksimko** [comment]
Hi @iceycake 

> The target_id looks like an arbitrary id to guarantee the unique of the event rule target.

`TargetId`/`target_id` is quite important part of the resource, see https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_cloudwatch_event_target.go#L177-L196

I don't think there is any way we can compute/generate this - correct me if I'm wrong.

**Comment by iceycake** [comment]
May be it is just me or the documentation.  What's does the target_id do?  I can't find it in AWS documentation.  In the go code, I see id = rule + "-" + target_id

**Comment by radeksimko** [comment]
@iceycake Sorry, I initially mixed this up with `arn`, so I'm taking back the words about the importance.

It is documented here:
http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_Target.html

> **Id**
> The unique target assignment ID.
> Type: String
> Length constraints: Minimum length of 1. Maximum length of 64.
> Pattern: `[\.\-_A-Za-z0-9]+`
> Required: Yes

It says _Required_, but as you said it doesn't probably do anything except guaranteeing uniqueness.

I think we could make it optional and automatically generated.

**Comment by stack72** [comment]
Merged in #5787
