### ISSUE TITLE
consul remote ssl_verify_client TLS?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/terraform#5703]
Curious, is there a way to present your client certificate plus key to do proper TLS verification with consul, if you have it strictly to verify the client via TLS?

**Comment by phinze** [comment]
Hi @JoeOrtiz - are you talking about pinning the certificate of the remote consul endpoint, or about authenticating using an SSL client certificate?

**Comment by JoeOrtiz** [comment]
Authenticating using the SSL client certificate.

**Comment by maxenglander** [comment]
Somehow I missed this when creating issue #7013. I created a PR which enables client TLS certification with the Consul provider: https://github.com/hashicorp/terraform/pull/7015.

**Comment by mitchellh** [comment]
Done!
