### ISSUE TITLE
Azure: Too many requests

### ISSUE THREAD

**Issue by ToruMakabe** [hashicorp/terraform#5704]
Do you have any plan to implement retry or exponential back off logic? Sometimes I got an error with HTTP status code 429 due to exceeding the API rate limitation of Azure.

Error applying plan:

1 error(s) occurred:

* azurerm_virtual_network.vnet1: autorest:DoErrorUnlessStatusCode 429 PUT https://management.azure.com/subscriptions/my_subscription_id/resourceGroups/mygroup/providers/Microsoft.Network/virtualnetworks/vnet1?api-version=2015-06-15 failed with 429

**Comment by stack72** [comment]
Hi @ToruMakabe 

We have released a patch in 0.6.15 that reduces the number of network calls to the AzureRM API. We found some flawed logic in how we register providers that was fixed

this should help alleviate your issue - we haven't ran into the API limits so I am going to close this out. IF you are still hitting the issue, please do let me know

thanks for raising the issue

Paul

**Comment by ToruMakabe** [comment]
Awesome. Thanks!

**Comment by pgroene** [comment]
I'm using version 0.6.16, and see this error all the time. I'm only starting 25 resources (3 subnets, 6 nics and 6 vms). I'l test with less  -parallelism=n.
