### ISSUE TITLE
remote state - destroy - does not have attribute

### ISSUE THREAD

**Issue by richardbowden** [hashicorp/terraform#5708]
I am getting errors when performing a destroy action. Plan and Apply works fine.

This is using atlas as the remote state store.

Structure:

├── main.tf
├── modules
│   ├── bastion
│   │   ├── bastion.tf
│   │   └── variables.tf
│   └── vpc
│       ├── outputs.tf
│       ├── subnets.tf
│       ├── variables.tf
│       └── vpc.tf
└── vars.tfvars

I have a similar structure for launching instances etc, this uses remote state to get vpc, subnet id's etc, so in main.tf I have the following statements to expose the required info to allow remote state to access the data from the other terraform structures

main.tf
output "private_core_services_b_subnet_id" {
  value = "${module.vpc.private_core_services_b_subnet_id}"
}

output "private_core_services_c_subnet_id" {
  value = "${module.vpc.private_core_services_c_subnet_id}"
}

the issue is when running the destroy command I get the following output, but the resources are actually destroyed.

I have seen other issues like this one that have been closed, but none up until now seem to of used remote state?

Error applying plan:

5 error(s) occurred:

* Resource 'atlas_artifact.tu_base_ansible' does not have attribute 'metadata_full.region-eu-west-1' for variable 'atlas_artifact.tu_base_ansible.metadata_full.region-eu-west-1'
* Resource 'terraform_remote_state.core_services' does not have attribute 'output.private_core_services_c_subnet_id' for variable 'terraform_remote_state.core_services.output.private_core_services_c_subnet_id'
* Resource 'terraform_remote_state.core_services' does not have attribute 'output.vpc_id' for variable 'terraform_remote_state.core_services.output.vpc_id'
* Resource 'terraform_remote_state.core_services' does not have attribute 'output.private_core_services_a_subnet_id' for variable 'terraform_remote_state.core_services.output.private_core_services_a_subnet_id'
* Resource 'terraform_remote_state.core_services' does not have attribute 'output.private_core_services_b_subnet_id' for variable 'terraform_remote_state.core_services.output.private_core_services_b_subnet_id'

**Comment by phinze** [comment]
Hi @richardbowden - thanks for the report. Can you double check this on Terraform v0.6.14 released yesterday and let us know if the error persists there?

**Comment by richardbowden** [comment]
@phinze hey, the error persists on v0.6.14 I am trying to investigate in source, not having much luck at pin pointing the issue
