### ISSUE TITLE
Aurora updates

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#5710]
Right now, most if not all of AWS RDS Cluster Instance attributes are `ForceNew`. Because they are essentially regular RDS Instances, we should be able to update them via `ModifyDBInstance`:

- http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html

I believe this to be true, but haven't confirmed. We should investigate, since recreating a db instance because we changed the name sounds silly

**Comment by stack72** [comment]
@catsby I believe we can close this now

The `aws_rds_cluster` resource now has an Updatefunc and it also has started having modification operations on it

Thoughts?

**Comment by catsby** [comment]
@stack72 not quite; this ticket is referring to RDS Cluster Instance, which still is all `ForceNew`

**Comment by catsby** [comment]
We've added some updates in #6865
