### ISSUE TITLE
Changing aws_elasticache_cluster Redis engine_version attempts update, but does nothing

### ISSUE THREAD

**Issue by soulcutter** [hashicorp/terraform#5714]
For example in the plan:

```
~ aws_elasticache_cluster.myredis
    engine_version: "2.8.19" => "2.8.24"
```

On apply, it says the modification has been made, but subsequent plans still shows the old value.

```
aws_elasticache_cluster.myredis: Modifying...
  engine_version: "2.8.19" => "2.8.24"
aws_elasticache_cluster.myredis: Modifications complete
```

Checking AWS console, confirms that the value has not changed.

**Comment by stack72** [comment]
Hi @soulcutter,

by any chance does your config have the `apply_immediately` set as false?

For a modification like this to complete, we need to make sure that `apply_immediately` is true

Please let me know your thoughts

Paul

**Comment by soulcutter** [comment]
Hm, it's the default, so false. I see that in the documentation now. I wonder if the output could mention that? 

Bradley Schaefer

**Comment by stack72** [comment]
Hi @soulcutter, 

apologies for not getting back to you sooner on this. We tried to clarify this behaviour in https://github.com/hashicorp/terraform/pull/4386

If you feel that it needs more clarification then we'd happily accept a PR :)

Paul

**Comment by soulcutter** [comment]
Thanks for your consideration! That documentation is helpful

Bradley Schaefer
