### ISSUE TITLE
Make aws_elb listeners separate resources

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform#5719]
We already have the option to use separate resources for rules for `aws_security_group`s and `aws_network_acl`s. It seems like it would make sense to have `aws_elb` listeners work the same way. Doing so would make it easier to put `aws_elb`s in modules and then add their listeners elsewhere.

**Comment by stack72** [comment]
Closing as a duplicate of #7246

That issue has links to some current issues we are tracking
