### ISSUE TITLE
Openstack provisionning timeout

### ISSUE THREAD

**Issue by jseaidou** [hashicorp/terraform#5722]
I have a configuration file that I am pushing to atlas, it looks like this: 

```
variable "auth_url" {}
variable "password" {}
variable "user_name" {}
variable "tenant_name" {}

provider "openstack" {
        user_name = "${var.user_name}"
        tenant_name = "${var.tenant_name}"
        password = "${var.password}"
        auth_url = "${var.auth_url}"
}
resource "openstack_compute_instance_v2" "test-server" {
        name = "Terraform-Test"
        image_id = "a2d41409-6341-4d03-b2c6-95aebbcedbd3"
        flavor_name = "large-fast"
        network {
                name = "Network-br600"
            }
}
```

I push to atlas like so: 
```TF_VAR_auth_url=${OS_AUTH_URL} TF_VAR_user_name=${OS_USERNAME} TF_VAR_password=${OS_PASSWORD} TF_VAR_tenant_name=${OS_TENANT_NAME} terraform push -name "jseaidou/example"```
that succeeds. However when I queue the plan I get the following output:

```
Terraform v0.6.13

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
Error refreshing state: 1 error(s) occurred:

* Post https://box.platform9.net/keystone_admin/v2.0/tokens: dial tcp 54.153.71.14:443: i/o timeout

Setup failed: failed refreshing state (exit 1)

```
Running terraform plan locally succeeds however.

**Comment by jtopjian** [comment]
On first glance, this might be a firewall issue. On my personal workstation, I'm unable to connect to `54.153.71.14` on any of ports 443, 35357, or 5000 (the latter two being native ports to Keystone).

**Comment by jseaidou** [comment]
got it. After looking more into platform9 it does seem to be behind a firewall. Closing ticket, and sorry for the bother.

**Comment by jtopjian** [comment]
No bother at all :smile:
