### ISSUE TITLE
aws_security_group same changes reported in consecutive plans

### ISSUE THREAD

**Issue by tphummel** [hashicorp/terraform#5731]
i'm on mac osx: `15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`. El Capitan 10.11.3.

This problem has been happening at least since terraform 0.6.11. And continued unchanged in 0.6.12 and 0.6.13. 

[This message board thread](https://groups.google.com/forum/#!searchin/terraform-tool/security$20group/terraform-tool/fx4R9Ts4MWE/h9AHJKlABgAJ) looks similar to what I'm seeing but there isn't much detail to confirm. 

I have four security groups that report changes every time i run `terraform plan`. `terraform apply` reports to run successfully. But if I immediately run `terraform plan` again following the apply, I get the same exact changeset from the previous `terraform plan` which was supposedly applied. 

These are `aws_security_group` resources. I'm not using the newer `aws_security_group_rule` resource. My first hypothesis was it was some combination of ingress blocks of different types (CIDR, security_group, self) together in a single resource that was causing this. However, this hasn't continued to be the case. 

I tried unsuccessfully to reproduce the problem [here](https://gist.github.com/tphummel/c0e2943e18b2300de654) with different combinations of `ingress` blocks in several resources. 

Here is the simplest of all plan outputs to illustrate the problem:
```
~ aws_security_group.vault-server
    ingress.2272603688.cidr_blocks.#:     "0" => "0"
    ingress.2272603688.from_port:         "" => "8200"
    ingress.2272603688.protocol:          "" => "TCP"
    ingress.2272603688.security_groups.#: "0" => "0"
    ingress.2272603688.self:              "" => "1"
    ingress.2272603688.to_port:           "" => "8200"
    ingress.860878657.cidr_blocks.#:      "0" => "0"
    ingress.860878657.from_port:          "8200" => "0"
    ingress.860878657.protocol:           "tcp" => ""
    ingress.860878657.security_groups.#:  "0" => "0"
    ingress.860878657.self:               "1" => "0"
    ingress.860878657.to_port:            "8200" => "0"
```

here is the state entry for that resource:
```
"type": "aws_security_group",
  "primary": {
      "id": "sg-VVVVV",
      "attributes": {
          "description": "Managed by Terraform",
          "egress.#": "0",
          "id": "sg-VVVVV",
          "ingress.#": "1",
          "ingress.860878657.cidr_blocks.#": "0",
          "ingress.860878657.from_port": "8200",
          "ingress.860878657.protocol": "tcp",
          "ingress.860878657.security_groups.#": "0",
          "ingress.860878657.self": "true",
          "ingress.860878657.to_port": "8200",
          "name": "vault-server",
          "owner_id": "YYYYY",
          "tags.#": "0",
          "vpc_id": "vpc-XXXX"
      }
  }
},
```

it appears it just wants to change the id on the ingress statement. `apply` doesn't appear to actually do that though. I've tried messing with state file itself, changing the id and incrementing the serial number with no success. doing that has gotten me out of similar things like this in the past. 

I wish I was having more luck reproducing the problem from scratch. Hopefully I've communicated enough detail to get to the bottom of it. Thanks

**Comment by jen20** [comment]
Hi @tphummel! There was some major work done before 0.6.12 around security groups, but it looks like that needs revisiting. Could you post the configuration which results in the diff above? Thanks!

**Comment by tphummel** [comment]
@jen20 thanks for getting back to me :-). i mentioned i'm seeing this with four different security groups. here is the simplest of the four:

*config*

```
variable "default_vpc" { default = "vpc-XXXXX" }

resource "aws_security_group" "vault-server" {
  name = "vault-server"
  vpc_id = "${var.default_vpc}"
  ingress {
    self = true
    from_port = 8200
    to_port = 8200
    protocol = "TCP"
  }
}
```

*state*
```
"type": "aws_security_group",
  "primary": {
      "id": "sg-VVVVV",
      "attributes": {
          "description": "Managed by Terraform",
          "egress.#": "0",
          "id": "sg-VVVVV",
          "ingress.#": "1",
          "ingress.860878657.cidr_blocks.#": "0",
          "ingress.860878657.from_port": "8200",
          "ingress.860878657.protocol": "tcp",
          "ingress.860878657.security_groups.#": "0",
          "ingress.860878657.self": "true",
          "ingress.860878657.to_port": "8200",
          "name": "vault-server",
          "owner_id": "YYYYY",
          "tags.#": "0",
          "vpc_id": "vpc-XXXX"
      }
  }
},
```

*plan*
```
~ aws_security_group.vault-server
    ingress.2272603688.cidr_blocks.#:     "0" => "0"
    ingress.2272603688.from_port:         "" => "8200"
    ingress.2272603688.protocol:          "" => "TCP"
    ingress.2272603688.security_groups.#: "0" => "0"
    ingress.2272603688.self:              "" => "1"
    ingress.2272603688.to_port:           "" => "8200"
    ingress.860878657.cidr_blocks.#:      "0" => "0"
    ingress.860878657.from_port:          "8200" => "0"
    ingress.860878657.protocol:           "tcp" => ""
    ingress.860878657.security_groups.#:  "0" => "0"
    ingress.860878657.self:               "1" => "0"
    ingress.860878657.to_port:            "8200" => "0"
```

let me know if I can provide any other info. I'm not quite sure what the next steps might be. Like i said I'm having trouble reproducing the problem from scratch.

**Comment by catsby** [comment]
hey @tphummel – I believe this is due to case sensitivity of the protocol:

```
ingress.2272603688.protocol:          "" => "TCP"
[...]
ingress.860878657.protocol:           "tcp" => ""
```

A patch was introduced to address this by lowercasing the protocol when creating the key 

- https://github.com/hashicorp/terraform/pull/5495

This patch went out in the latest version of Terraform (v0.6.13) which I see you mention. I ran the following plan you supplied through v0.6.13 and can't reproduce it

```
resource "aws_vpc" "tf_test" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "tf_sg_test"
  }
}

resource "aws_security_group" "vault-server" {
  name   = "vault-server"
  vpc_id = "${aws_vpc.tf_test.id}"

  ingress {
    self      = true
    from_port = 8200
    to_port   = 8200
    protocol  = "TCP"
  }
}
```

This gist has my full output:

- https://gist.github.com/catsby/b9517c8caf29e5cdd609

The protocol difference is the only thing I see here that stands out. Can you reproduce this for me on v0.6.13 and capture the version/output?

**Comment by tphummel** [comment]
@catsby protocol case was the cause. correcting from uppercase to lowercase in my config fixed the issue for 3 of 4 security groups on the next `plan`. the fourth group needed to be applied to take the change. but now I have a clean `plan`. 

like you, I can't reproduce this problem from scratch on v0.6.13. my guess is that because of the patch you linked to above, it might have been reproducible prior to v0.6.13. and that going forward new SGs won't be susceptible to this. 

does this sound right to you?

thank you so much for the support! this had been bugging us for a little while :-)

**Comment by jen20** [comment]
I think that is the case @tphummel! I'll close this for now - if you see any repeat of it please feel free to re-open! Glad it's resolved.
