### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by mrwilby** [hashicorp/terraform#5733]
We have a 'reasonably complex' project structure - a lot of modules, null_resources and other goodies to help modularize our environment.

Since upgrading to 0.6.11 and 0.6.12 (could've been earlier too - but we really started noticing the problem lately) we now see the terraform process completely die with exit code 2 - there's basically no output at all (unless you turn on debug logging) - the process just bombs without showing anything.

I managed to get a trace log of the issue today and captured the call stacks which I'll add here:

https://gist.github.com/mrwilby/e78ed1274a46c54ae3f9

I have the full trace log but I am not willing to post that in public as it contains a lot of project information.

**Comment by jen20** [comment]
Thanks for reporting this @mrwilby! This is definitely a core bug - potentially introduced when `hil` was factored out into it's own repository and separated out from Terraform's core, though I forget the exact timelines. The stack trace should be sufficient to debug this though.

**Comment by roderickrandolph** [comment]
experienced the same problem - 0.6.14 seems to fix it. thank you!

**Comment by phinze** [comment]
That's great news @roderickrandolph! #5772 did land in 0.6.14 and attempts to address this - @mrwilby can you give 0.6.14 a shot as well and let me know if it sorts out your issue?

**Comment by mrwilby** [comment]
Sorry for the delay. This does indeed look good now with 0.6.14. Thanks!

**Comment by phinze** [comment]
Hooray! Closing :+1:
