### ISSUE TITLE
Terraform crashes when adding more than one file provisioner

### ISSUE THREAD

**Issue by pabloa502** [hashicorp/terraform#5734]
Terraform crashes when adding more than one file provisioner

I am using Terraform v0.6.13 on windows x64

**Comment by phinze** [comment]
Hi @pabloa502 - can you attach a crash log / error message to this report? Then we can take a look and get this fixed up! :+1:

**Comment by catsby** [comment]
Hey Friends – I'm going to close this for now, please let us know if you're still hitting this issue in the latest version of Terraform (v0.6.16 at time of writing)
