### ISSUE TITLE
option_settings crashes elastic beanstalk template

### ISSUE THREAD

**Issue by mbaxa** [hashicorp/terraform#5741]
With Terraform v0.6.13 a terraform plan crashes with the following config

```
resource "aws_elastic_beanstalk_application" "test" {
  name = "test_name"
  description = "test_desc"

}

resource "aws_elastic_beanstalk_configuration_template" "dev" {
  name = "dev"
  description = ""
  application = "${aws_elastic_beanstalk_application.test.name}"

  option_settings {
     namespace = "aws:ec2:vpc"
     option_name = "VPCId"
     value = "vpc-a1c540c4"
  }
```
[crash.log](https://github.com/hashicorp/terraform/files/181650/crash.txt)

If I remove the option_settings part, it completes correctly:
```
+ aws_elastic_beanstalk_application.test
    description: "" => "test_desc"
    name:        "" => "test_name"

+ aws_elastic_beanstalk_configuration_template.dev
    application: "" => "test_name"
    name:        "" => "dev"
```

**Comment by catsby** [comment]
Hey @mbaxa – thanks for the detailed info! I patched this in https://github.com/hashicorp/terraform/pull/5756, however you need know some things:

- I renamed the `option_settings` config to just `setting`. This matches Beanstalk Environments, and currently Beanstalk Configuration Template will crash on the use of `option_settings` anyway...
- In my testing, I found that you need to also include an option setting for `Subnets`, in the event you don't already have that in your config. 

Let me know if you have any other questions! Thanks for reporting this :smile:

**Comment by mbaxa** [comment]
Wow, thanks for fixing so quickly! :+1:  Yeah, I had a full suite of settings that I was trying to move into a template; I just cut it down to one to make the bug report cleaner. :smile:
