### ISSUE TITLE
aws_instance parameter network_interfaces is missing!

### ISSUE THREAD

**Issue by P13612** [hashicorp/terraform#5765]
Hi,

in AWS CloudFormation you have in AWS::EC2::Instance a parameter NetworkInterfaces:

{
   "Type" : "AWS::EC2::Instance",
   "Properties" : {
      .
      .
      "NetworkInterfaces" : [ EC2 Network Interface, ... ],
      .
      .
      .
   }
}
This Parameter is missing entirely in  terraform/builtin/providers/aws/resource_aws_instance.go
This significantly limits how ENIs can be used.

aws_network_interface shows a code example:

resource "aws_network_interface" "myapp" {
    subnet_id = "${aws_subnet.public_a.id}"
    private_ips = ["10.0.0.50"]
    security_groups = ["${aws_security_group.web.id}"]
    attachment {
        instance = "${aws_instance.test.id}"
        device_index = 1
    }
}

But ENI's may preferably be used the other way around. First an ENI is created with a private IP and then the instance is hooked to this ENI. This is always true when you try to setup an infrastructure with dedicated fixed private_ips. You first setup the ENIs and then the helpers like RDS databases and caches and they may no longer steel the IP's dedicated for the application instances. 

This scenario can not be build with terraform right now. Can somebody add this, so one can write:

resource "aws_instance" "app" {
  .
  .
  .
  network_interfaces = [${aws_network_interface.myapp}]
  .
  .
  .

Thanks

Peter

**Comment by grubernaut** [comment]
Fixed via #12933
