### ISSUE TITLE
Whatever downloads modules doesn't use the root certificates stored in the OS X keychain

### ISSUE THREAD

**Issue by thegranddesign** [hashicorp/terraform#5771]
I'm not sure which library is being used to download modules, but typically on Mac, if I "Always Trust" a self-signed certificate's `pem` file, I never get a warning about that connection being insecure.

Unfortunately despite it working fine in Chrome, git, etc, when Terraform attempts to download a module from my site, I get a self-signed certificate warning.

`x509: certificate signed by unknown authority`

**Comment by thegranddesign** [comment]
Sorry, not a warning.  An error.  The `get` completely fails.

**Comment by jen20** [comment]
Hi @thegranddesign! This is likely an artefact of how Go interacts with the OS X certificate store. Root CAs are obtained via the function listed below on OS X, so unless the certificate is in the keychain specified it won't be found. Ultimately there isn't much we can do here, as far as I can see - @phinze or @mitchellh - do you have any suggestions?

```
func execSecurityRoots() (*CertPool, error) {
	cmd := exec.Command("/usr/bin/security", "find-certificate", "-a", "-p", "/System/Library/Keychains/SystemRootCertificates.keychain")
	data, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	roots := NewCertPool()
	roots.AppendCertsFromPEM(data)
	return roots, nil
}
```

**Comment by mitchellh** [comment]
@jen20 You're right, we're just using the Go standard library with no trickery.

**Comment by thegranddesign** [comment]
Would it be possible to also check to see if the certificate exists in the Login keychain?

**Comment by mitchellh** [comment]
I'm open to a PR similar to @jen20's above to make this work on OS X. Until then, we're just using the default cert lookup in Go.
