### ISSUE TITLE
remote-exec inline doesn't proceed to next command

### ISSUE THREAD

**Issue by varuns-zetaris** [hashicorp/terraform#5775]
provisioner "remote-exec" {
    inline = [
           "aws s3 cp ${var.jar_path} ./",
           "hadoop jar <job>",
           "aws s3 cp job_* ${var.log_path}"
    ]
    }

I have a terraform deployment which fires up a cluster in ec2 run a job using remote-exec . However the hadoop job get executed but after the 2nd command , terraform doesn't go further. It doesn't proceed to the 3rd command . And terraform create doesn't complete. Am i missing anything. If the time taken by job is less it works . But if its long running jobs like 1-2 hrs it fails.

**Comment by rklyne** [comment]
I'm seeing this too when provisioning postgres. New on v0.6.13 for me. I'm rolling back to v0.6.12 temporarily.

**Comment by jen20** [comment]
Hi @varuns-zetaris and @rklyne! We release 0.6.14 yesterday afternoon (US time) which should address this - the PR was #5751. I'll close this issue for now, but if you see a recurrence of it with 0.6.14 please feel free to reopen. Thanks for reporting!

**Comment by rklyne** [comment]
@jen20 You're on fire!
Thank you very much
