### ISSUE TITLE
openstack: Instance resize doesn't work if flavor_name is changed

### ISSUE THREAD

**Issue by toddnni** [hashicorp/terraform#5780]
Instance resizing doesn't work if **flavor_name** is changed. However, resize does work if **flavor_id** is changed.

The error message received from API is
```
{"badRequest": {"message": "Resize requires a flavor change.", "code": 400}}
```

To my understanding it doesn't work, because in **resource_openstack_compute_instance_v2.go** the update function uses **getFlavorID()** to get the a new flavor ID when either **flavor_id** or **flavor_name** is changed, and the function doesn't query OpenStack for a new flavor ID as the old value is already defined.

Maybe we should 
- reverse the order of **flavorId != ""** and **flavorName != ""** checks in **getFlavorID()** so that name change will be reflected
- or add a parameter to **getFlavorID** to signal that a parameter changed and it should check for a new ID using the new name

**Comment by jtopjian** [comment]
Good catch :smile:

**Comment by jtopjian** [comment]
@toddnni I've created #6020 which should fix this. would you be able to compile from source with this patch and give it a test?
