### ISSUE TITLE
v0.6.13 - remote-exec executes first inline record only

### ISSUE THREAD

**Issue by dcloud9** [hashicorp/terraform#5782]
Hi,
I've just updated to v0.6.13 from .12 and noticed only the first command of inline is executed then exits.
I've downgraded back to v0.6.12 and remote-exec executed all inline commands.
````
  provisioner "remote-exec" {
    inline = [
      "sudo mkfs.ext4 /dev/xvdg",
      "echo /dev/xvdg /data/glusterfs ext4 defaults 0 0 | sudo tee -a /etc/fstab",
      "sudo mount /data/glusterfs",
      "sudo chown 92:92 /data/glusterfs",          
      "sudo sed -i 's/^HOSTNAME=.*/HOSTNAME=ss1-${var.buildnum}.${var.tag_environment}.${var.tag_project}.beta.eurostar.com/' /etc/sysconfig/network",
      "sudo rm -rf /etc/localtime",
      "sudo ln -s /usr/share/zoneinfo/Europe/London /etc/localtime",
      "echo Provision completed. Check error code.",
      "echo Rebooting... && sudo reboot"
    ]    
    connection {
      type = "ssh"
      user = "ec2-user"
      bastion_host = "${var.gw1_fqdn}"
    }    
  }

**Comment by stack72** [comment]
Hi @dcloud9 - I believe this was fixed in the release of 0.6.14 (https://github.com/hashicorp/terraform/pull/5751)

If you upgrade to 0.6.14, that should sort out the issue

Please let me know if it doesn't

Paul

**Comment by dcloud9** [comment]
Sure @stack72 . I'll test in v0.6.14 and let you know.

**Comment by dcloud9** [comment]
@stack72 I can confirm v0.6.14 fixed the remote-exec bug. Thanks.

**Comment by stack72** [comment]
Thanks for confirming @dcloud9 :)
