### ISSUE TITLE
Provider link is broken

### ISSUE THREAD

**Issue by DaveBlooman** [hashicorp/terraform#5783]
Not sure where the consul provider link is supposed to go on this page, https://github.com/hashicorp/terraform/tree/master/examples/consul, but it leads here, https://github.com/hashicorp/terraform/blob/master/docs/providers/consul/index.html, which 404's.

**Comment by stack72** [comment]
@DaveBlooman this has been fixed and pushed to master

Thanks for pointing out the broken link
