### ISSUE TITLE
aws: Support step scaling autoscaling policies

### ISSUE THREAD

**Issue by cbroglie** [hashicorp/terraform#5791]
The `aws_autoscaling_policy` resource only supports simple scaling, but the AWS Go SDK supports  step scaling (https://github.com/aws/aws-sdk-go/blob/9da4345e8a55ca7e7e018d367e628aa002ad1de8/service/autoscaling/api.go#L4818).

**Comment by stack72** [comment]
There is a PR already open for this

https://github.com/hashicorp/terraform/pull/4277

**Comment by ctiwald** [comment]
Any guidance someone can give me on getting #4277 merged I'd deeply appreciate. It's been open for months and as far as I know is good to go.

**Comment by stack72** [comment]
Hi @ctiwald 

I will review this today / tomorrow and see if we can get it merged :)

P.

**Comment by stack72** [comment]
@cbroglie I am closing this so that we can track progress in the original PR :)

**Comment by cbroglie** [comment]
Works for me, thanks
