### ISSUE TITLE
Missing RDS Event Subscription

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#5797]
Looks like we are missing RDS Event Subscription.  Looks like potential feature enhancement?

**Comment by stack72** [comment]
http://docs.aws.amazon.com/cli/latest/reference/rds/create-event-subscription.html

**Comment by radeksimko** [comment]
Totally agreed, if nobody else steps in and I don't have any more important resources to work on, I will pick this one up.

**Comment by iceycake** [comment]
I was planning to work on this but I am pretty busy these few weeks and I still have an open PR needs some more works.  Feel free to take on it. 😃

**Comment by stack72** [comment]
Merged in #6367
