### ISSUE TITLE
Export ASG and ELB information for beanstalk environments

### ISSUE THREAD

**Issue by Dchamard** [hashicorp/terraform#5798]
For my use case to create cloudwatch alarms on the ELB and ASG that beanstalk created, i actually need the resources information. Right now terraform, do not export these informations after beanstalk environment creation. This is a limitation  that blocks us to create cloudwatch alarms on beanstalk environments with terraform.

**Comment by dharrisio** [comment]
At a quick glance this looks like it should be pretty easy to do for the ELB, as this info is returned in the describe environment api. (http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_EnvironmentResourcesDescription.html)

The ASG may be a bit more difficult to correlate with a specific environment.

**Comment by Dchamard** [comment]
Looks like this call might do it?
http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_EnvironmentResourceDescription.html

**Comment by dharrisio** [comment]
@Dchamard you're right, I only saw the EnvironmentResourcesDescription when I originally looked at this.

**Comment by dharrisio** [comment]
@Dchamard I submitted #5915 for this, let me know if it does what you needed as well.

**Comment by Dchamard** [comment]
Thats exactly, what I needed! Thank you so much

**Comment by stack72** [comment]
Ho @Dchamard 

This has been taken care of and merged as #5915 - thanks to @dharrisio for all the work on that PR and thanks for the issue to help us improve

Paul
