### ISSUE TITLE
Allow assignment of security_group_rule to multiple security_group objects 

### ISSUE THREAD

**Issue by cdorros** [hashicorp/terraform#5800]
The work done here to create the new security_group_rule type is hugely appreciated - solved many cycle issues I was having:
https://github.com/hashicorp/terraform/pull/1620

It would be extremely useful to be able to assign security_group_rules to multiple security_groups, to allow for re-use. Additionally, inverting the assignment by allowing an array of security_group_rules to be defined in the security_group object, instead of the current behavior (assigning security_group ID to security_group_rule).

Title is related to https://github.com/hashicorp/terraform/issues/3525, but the content of that ticket is not what I'm after.

**Comment by phinze** [comment]
Hi @cdorros - definitely understand the desire to allow for security_group_rule reuse. Consolidating the conversation around this down in https://github.com/hashicorp/terraform/issues/2081. :+1:
