### ISSUE TITLE
introspecting resource names

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform#5805]
Is there any way to do this?

```
resource "aws_iam_role" "some-role" {
  name = "${self.name}"
  path = "/"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {"AWS": "*"},
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```

**Comment by mitchellh** [comment]
There are other issues requesting this sort of functionality. We hope to support it one day but don't at the moment.

**Comment by tkellen** [comment]
Is there another issue I might track progress on this for? Alternatively some place I could get guidance on attempting to implement this?

**Comment by mitchellh** [comment]
There issssss I'm sorry for not finding it, but check through the "core" + "enhancement" tagged issues. It is more general and asking for more "self." access. 

For implementing it: there aren't many resources other than simply reading the source. :( I don't know exactly what I'd call it but I've been thinking of making a var that can track resource metadata. Maybe its even `${self.meta.X}` and the metadata should probably be available... not sure though.

**Comment by tkellen** [comment]
No worries @mitchellh, I found it!
