### ISSUE TITLE
New plugin for OTC(Open Telekom Cloud)

### ISSUE THREAD

**Issue by cricketlong** [hashicorp/terraform#5810]
Deutsche Telekom has published its own cloudplatform, is it time to make a new plugin for it? Though it's based on openstack, Deutsche Telekom would specialize its funtionalities.

**Comment by catsby** [comment]
Hey @cricketlong – we're always willing to consider new providers, however we can't guarantee we'll bundle them with Terraform itself. If you or others are interested in this provider, please checkout the [Contributing Guide][1], which covers contributing (including Providers). 

Even if a provider is not bundled and distributed with Terraform itself, 3rd party plugins are still possible as mentioned here:

- https://www.terraform.io/docs/plugins/basics.html
- https://www.terraform.io/docs/plugins/provider.html

Let us know if you have questions!

[1]: https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md
