### ISSUE TITLE
Redeploy terraform.io website

### ISSUE THREAD

**Issue by alexpbrown** [hashicorp/terraform#5812]
Given that [my PR](https://github.com/hashicorp/middleman-hashicorp/pull/23) was merged, I _think_ the terraform.io website just needs a rebuild/redeploy for the changes to take effect.

Most noticeable thing fixed will be that links on pages like [this](https://www.terraform.io/docs/configuration/interpolation.html) will have working anchor links again for all of the list-items.

**Comment by pearkes** [comment]
Will also need a `bundle update middleman-hashicorp`.

**Comment by alexpbrown** [comment]
Great! Does the website get redeployed on the same schedule as terraform releases? Or is there some separate trigger?

**Comment by alexpbrown** [comment]
Sorry to nag on this issue (maybe I should open a different one?), but it still doesn't look right. To be more specific, when I do `make` on the website dir for master on my machine, the "file()" anchor link on [this](https://www.terraform.io/docs/configuration/interpolation.html) page works correctly. On the real website, it currently does not. Let me know if there's more information I can provide.

**Comment by bruun** [comment]
Has your change been deployed? I'm experiencing that there are duplicate `name` properties in the generated HTML, causing URLs to link back to the top level argument. 

Example:
https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#custom_error_response

**Comment by alexpbrown** [comment]
Looks like it. the previously broken anchor links on the interpolation page[0] for example, seem to work. I'm not sure what you're describing is related, but you probably want to open a separate issue that links to this one if you want someone to take a look.

[0] https://www.terraform.io/docs/configuration/interpolation.html#file_path_

**Comment by bruun** [comment]
Seems what I am experiencing is the same as described in https://github.com/hashicorp/middleman-hashicorp/issues/6, which is still open. Thanks for the quick response :-)
