### ISSUE TITLE
aws_main_route_table_association removal does not update main_route_table_id in tfstate

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/terraform#5819]
Initially, I used an aws_main_route_table_association to use a new route table as my main route table but later removed this resource. This successfully changed the route table back to the original one on removal but the tfstate file still references the changed route table id from the old resource.

```
                "aws_vpc.production_us_west_1": {
                    "type": "aws_vpc",
                    "primary": {
                        "id": "vpc-34c5b851",
                        "attributes": {
                            "cidr_block": "10.200.0.0/16",
                            "default_network_acl_id": "------",
                            "default_security_group_id": "------",
                            "dhcp_options_id": "------",
                            "enable_classiclink": "false",
                            "id": "------",
                            "main_route_table_id": "OLD ID HERE"
                        }
                    }
                }
```

**Comment by phinze** [comment]
Hi @sheldonkwok - I'd expect the VPC to catch the new main route table on the subsequent refresh. Does the ID update in the state after your next `terraform refresh` or `terraform plan` (which performs a refresh)?

**Comment by sheldonkwok** [comment]
Running `terraform plan` did not resolve this issue. I got the error of attempting to use the old main_route_table_id when running `terraform plan`

**Comment by mitchellh** [comment]
This should be fixed now. If it is not, please simply reopen a new issue and we'll retriage.
