### ISSUE TITLE
Terraform consule module fails during provisioning with 'remote-exec' (/usr/bin/env: bash : No such file or directory) 

### ISSUE THREAD

**Issue by chrisdcampbell** [hashicorp/terraform#5821]
Terraform v0.6.14
Consul Module is latest from today

Running terraform apply with a .tf file that contains the consul module. The process ends prematurely with node-0 and consul-0 VMs up and running.

**.tf**
<pre><code>provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}

resource "aws_instance" "node" {
  ami = "${lookup(var.amis, var.region)}"
  instance_type = "t1.micro"
  key_name = "${lookup(var.key_names, var.region)}"

  tags {
    Name = "node-${count.index}"
  }
}

module "consul" {
  source = "github.com/hashicorp/consul/terraform/aws"
  key_name = "${lookup(var.key_names, var.region)}"
  key_path = "${lookup(var.key_paths, var.region)}"
  region = "${var.region}"
  servers = "3"
}
</code></pre>

**Plan:**
<pre><code>-/+ module.consul.aws_instance.server.0
    ami:                        "" => "ami-9abea4fb"
    availability_zone:          "" => "<computed>"
    ebs_block_device.#:         "" => "<computed>"
    ephemeral_block_device.#:   "" => "<computed>"
    instance_state:             "" => "<computed>"
    instance_type:              "" => "t2.micro"
    key_name:                   "" => "service_key2"
    placement_group:            "" => "<computed>"
    private_dns:                "" => "<computed>"
    private_ip:                 "" => "<computed>"
    public_dns:                 "" => "<computed>"
    public_ip:                  "" => "<computed>"
    root_block_device.#:        "" => "<computed>"
    security_groups.#:          "" => "1"
    security_groups.3694337380: "" => "consul_ubuntu"
    source_dest_check:          "" => "1"
    subnet_id:                  "" => "<computed>"
    tags.#:                     "" => "1"
    tags.Name:                  "" => "consul-0"
    tenancy:                    "" => "<computed>"
    vpc_security_group_ids.#:   "" => "<computed>"
</code></pre>

**Output:**
<pre><code>module.consul.aws_instance.server.0: Provisioning with 'file'...
module.consul.aws_instance.server.0: Provisioning with 'remote-exec'...
module.consul.aws_instance.server.0 (remote-exec): Connecting to remote host via SSH...
module.consul.aws_instance.server.0 (remote-exec):   Host: 54.186.175.143
module.consul.aws_instance.server.0 (remote-exec):   User: ubuntu
module.consul.aws_instance.server.0 (remote-exec):   Password: false
module.consul.aws_instance.server.0 (remote-exec):   Private key: true
module.consul.aws_instance.server.0 (remote-exec):   SSH Agent: false
module.consul.aws_instance.server.0 (remote-exec): Connected!
module.consul.aws_instance.server.0: Provisioning with 'remote-exec'...
module.consul.aws_instance.server.0 (remote-exec): Connecting to remote host via SSH...
module.consul.aws_instance.server.0 (remote-exec):   Host: 54.186.175.143
module.consul.aws_instance.server.0 (remote-exec):   User: ubuntu
module.consul.aws_instance.server.0 (remote-exec):   Password: false
module.consul.aws_instance.server.0 (remote-exec):   Private key: true
module.consul.aws_instance.server.0 (remote-exec):   SSH Agent: false
module.consul.aws_instance.server.0 (remote-exec): Connected!
module.consul.aws_instance.server.0 (remote-exec): /usr/bin/env: bash
module.consul.aws_instance.server.0 (remote-exec): : No such file or directory
Error applying plan:

1 error(s) occurred:

* Script exited with non-zero exit status: 127

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
</code></pre>

When I SSH into the server I find the following assets

**/tmp**
<pre><code>$ls
consul-server-addr   terraform_1298498081.sh  upstart.conf
consul-server-count  terraform_2019727887.sh
</code></pre>

Interestingly enough the last commit to the consul module changed the shebangs to <code>#!/usr/bin/env bash</code> from <code>#!/bin/bash</code> which seems to be how this fails.

Thanks for reading!

**Comment by chrisdcampbell** [comment]
Manually reverting this commit https://github.com/hashicorp/consul/commit/071631dc164d06dd7448a16f1365dd95cb633302 fixes my problem.

**Comment by phinze** [comment]
Hi @chrisdcampbell - sorry for the trouble here. Can you report this over on the consul repo, they should be able to investigate and come up with a fix for everybody! :+1:

**Comment by podnov** [comment]
In case someone else runs across this and wants a quick fix, I was able to use this command to to be able to move forward:

```
(cd .terraform/modules/c5794fcfe1fcbe95b4506e43175319b4/terraform/aws/scripts/ \
    && git checkout b4dfd0fa4d7242bc0d23b9d84a19353918ad918d install.sh ip_tables.sh service.sh \
    && dos2unix *)
```

Caveats:
- The dos2unix part may be omitted depending on your os/git config
- I don't know enough about terraform yet to know that the c5794fcfe1fcbe95b4506e43175319b4 portion is constant

**Comment by jaygorrell** [comment]
I ran into this also. Just change to unix/osx (LF) line endings for the scripts/*.sh files and you'll be good to go, even with the latest version... no need to pull b4dfd0. Most good editors can do this for you.

**Comment by bradcosine** [comment]
Running dos2unix on the 3 .sh scripts in */terraform/shared/scripts worked for me. I did not revert to an older commit. Thanks @jaygorrell

**Comment by trevorseo** [comment]
![image](https://user-images.githubusercontent.com/8579758/27871497-c98a64b2-61e0-11e7-9a31-43e4d746d00d.png)
Oh, it works just by changing CRLF to LF in my editor. Thanks a lot!
