### ISSUE TITLE
Password inconsistency between config and state

### ISSUE THREAD

**Issue by dene14** [hashicorp/terraform#5825]
Not sure whether it feature or bug... assuming latter:

Met this in "aws_db_instance" resource:
password = "pa$$w0rt"
resulting in
password: "pa$w0rt"

for both state file and online configuration.

**Comment by phinze** [comment]
Thanks for the report, @dene14 - this looks to be like our interpolation "double dollar sign" escaping code being a little overzealous. @jen20 do you think you can look into this when you have the chance?

**Comment by mitchellh** [comment]
This works fine in master. You have to do `$$$$` since `$$` is our interpolation escape mechanism.
