### ISSUE TITLE
element function on list of rendered templates fails with incorrect data

### ISSUE THREAD

**Issue by gottwald** [hashicorp/terraform#5828]
I am experimenting with terraform and found something that looks like a bug when using templates in combination with count and the element function.

I've got a var definition like this:

```
variable "mesos-master-hosts" {
  default = {
    "0" = "mesos-master1"
    "1" = "mesos-master2"
    "2" = "mesos-master3"
  }
}
```

And I render cloud instance start scripts as templates like this:

```
resource "template_file" "mesos_master_init" {
  count = "${length(keys(var.mesos-master-hosts))}"
  template = "${file("mesos-master-init.sh.tpl")}"
  vars {
    count_index = "${count.index}"
    zk_id = "${count.index + 1}"
    mesos_hostname = "${lookup(var.mesos-master-hosts, count.index)}"
    mesos_master_hosts = "${values(var.mesos-master-hosts)}"
    mesos_zk = "${format("zk://%s/mesos", join(",", formatlist("%s:2181", values(var.mesos-master-hosts))))}"
    marathon_zk = "${format("zk://%s/marathon", join(",", formatlist("%s:2181", values(var.mesos-master-hosts))))}"
    chronos_zk_hosts = "${join(",", formatlist("%s:2181", values(var.mesos-master-hosts)))}"
  }
}
```

And with that, I create GCE instances like so:

```
resource "google_compute_instance" "mesos-master" {
  count = "${length(values(var.mesos-master-hosts))}"
  name = "${lookup(var.mesos-master-hosts, count.index)}"

  # skipping a lot of other unimportant attributes like
  # machine_type, zone, tags, disk, network, etc

  metadata_startup_script = "${element(template_file.mesos_master_init.*.rendered, count.index)}"
}
```

Somehow the metadata_startup_script attribute is set to the value `mesos-master1` here instead of the rendered template.
If I supply a rendered template by directly accessing the index of the list like `metadata_startup_script = "${template_file.mesos_master_init.0.rendered}"`, then I get a rendered script like I intended to.

Is this a bug or am I doing something wrong?

Tested with Terraform v0.6.14
There is another Issue #5736 regarding count and templates that might be related.

**Comment by gottwald** [comment]
Found the error:
```
mesos_master_hosts = "${values(var.mesos-master-hosts)}"
```
I accidently assigned a list to a template var instead of a string.
Everything works if I change it to something like this:
```
mesos_master_hosts = "${join(",", values(var.mesos-master-hosts))}"
```

Seems like handing a list to the template var completely throws off the template rendering.
I would have expected an error message instead of this behaviour.
Will leave this issue open for you to judge whether this needs to be changed or not.

**Comment by phinze** [comment]
Hi @gottwald - thanks for the report, and sorry for the confusing behavior here.

I believe the impending first-class list support will make this a proper error message in the near future.

Is that correct @jen20? If so, I think we can close this since we know it will be fixed up soon!

**Comment by panda87** [comment]
@gottwald Can you pls create a gist or something like that and present what 'mesos-master-init.sh.tpl' file contains?

Thanks

**Comment by gottwald** [comment]
Don't have the original any more but something like this would do:
```
#!/bin/bash

echo "Other content.... foo bar"

echo "count_index: ${count.index}"
echo "zk_id: ${zk_id}"
echo "mesos_hostname: ${mesos_hostname}"
echo "mesos_master_hosts: ${mesos_master_hosts}"
echo "mesos_zk: ${mesos_zk}"
echo "marathon_zk: ${marathon_zk}"
echo "chronos_zk_hosts: ${chronos_zk_hosts}"
```

Was just referencing the vars, nothing fancy.

**Comment by panda87** [comment]
Thanks @gottwald

**Comment by mitchellh** [comment]
This is a proper error message and handled with 0.7 now.
