### ISSUE TITLE
azurerm 0.6.14 400 Bad Request creating nic 

### ISSUE THREAD

**Issue by lmeyemezu** [hashicorp/terraform#5829]
Hi,
I get  following error whenever i try to create a nic 
autorest:DoErrorUnlessStatusCode 400 PUT https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/xxxx/providers/Microsoft.Network/networkInterfaces/af-jenkins-dev-nic1?api-version=2015-06-15 failed with 400 Bad Request
my configuration is below 
```
resource "azurerm_network_interface" "af-jenkins-dev-nic1" {
    name = "af-jenkins-dev-nic1"
    location = "${var.location.name}"
    resource_group_name = "${azurerm_resource_group.xxxxx.name}"
    network_security_group_id = "${azurerm_network_security_group.xxxx.id}"
    ip_configuration {
        name = "af-jenkins-dev-nic1-configuration"
        subnet_id = "${azurerm_subnet.xxx.id}"
        private_ip_address_allocation = "dynamic"
        public_ip_address_id = "${azurerm_public_ip.jenkins_dev_public_ip.ip_address}"                
    }
    tags {
    envt = "${var.envt.name}"
    project = "${var.project.name}"
  }
```
Any idea ?

**Comment by BigCheeze45** [comment]
Looks like the subscription ID you provided is invalid:
`The subscription 'xxxxxxx' could not be found.`

[Take a look at this](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/#authenticate-with-password---azure-cli) walkthrough on authenticating a service like Terraform to interact with your Azure subscription.

**Comment by lmeyemezu** [comment]
Hi ,
xxxx is just masking subscription id because of corporate rules.

Cet e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Cordialement,
Meye-Mezu Lylian
Tel.:06 98 93 13 14

2016-03-24 18:24 GMT+01:00 Prince Kannah <notifications@github.com>:

**Comment by majormoses** [comment]
@lmeyemezu any chance you could surface the underlying error by running all terraform through something like charles proxy? The next version of TF should hopefully include a fix to the go sdk to not swallow these errors but until then it requires a bit more effort to surface them.

Install: https://www.charlesproxy.com/documentation/installation/ (or something like it)

Add ssl proxy host rules: Proxy -> SSL Proxy Settings:

- management.azure.com
- login.microsoftonline.com
- account.windowsazure.com
- *.azure.com

Install charles ssl cert from here: http://www.charlesproxy.com/getssl

Your instructions will differ from here based on platform. I have done this on linux. You need to copy the file you dowload into: /usr/local/share/ca-certificates/$FILENAME.crt (note that it changed from .pem to .crt and run `sudo update-ca-certificates`. 

you will then need to tell terraform how to communicate with the proxy which respects the https_proxy and http_proxy ENV vars. In linux it would be something like this `export https_proxy=localhost:8888` and `export http_proxy=localhost:8888`.

**Comment by stack72** [comment]
Hi @lmeyemezu 

I am tracking this as part of a larger rollup set of AzureRM issues #6526. I am going to close this so that I can work on the issue there

Paul
