### ISSUE TITLE
AWS RDS provisioning times out

### ISSUE THREAD

**Issue by personias** [hashicorp/terraform#5831]
Appears similar to now closed Bug [#438-AWS RDS provisioning times out](https://github.com/hashicorp/terraform/issues/438) - needing larger or configurable timeout
May be fixed with the resolution of [#5161-Timeout on destroying rds with skip_final_snapshot = false](https://github.com/hashicorp/terraform/issues/5161)

When running the AWS Provider, RDS Oracle provisioning, with multi-AZ, the provisioning takes longer than the 40 min hard-coded in Terraform timeout and errors out:

```
aws_db_instance.test: Error: timeout while waiting for state to become 'available'
Error applying plan:
1 error(s) occurred:
timeout while waiting for state to become 'available'
```

After this, the instance does complete creating.  But, Terraform is unaware.  If I attempt to run apply again, it will destroy the instance; recreate & timeout again.

Attempted workaround: I've tried provisioning it with 'rds_is_multi_az=false' (which completes within the 40 minutes & succeeds) and then, running a 2nd apply with 'rds_is_multi_az=true'.  Unfortunately, this doesn't work, as Terraform sees this as an entirely new DB Instance & throws the error that the instance already exists:

Output from running terraform apply -var 'rds_is_multi_az=true' after successfully running terraform apply -var 'rds_is_multi_az=false"

```
Error applying plan:
1 error(s) occurred:
aws_db_instance.main_rds_instance: Error creating DB Instance: DBInstanceAlreadyExists: DB Instance already exists
       status code: 400, request id: 4casdf31-f134-11e5-8asb-0d4dasda6dca
```

**Comment by personias** [comment]
$ terraform version
Terraform v0.6.14

**Comment by heimweh** [comment]
Seeing this issue as well (ver 0.7.1), 
would be great if we could at least configure the timeout instead of having it hardcoded to 40 min. 

Mine came online shortly after 50 min, but that can of course vary from time to time. 
Since we don't persist any information regarding the newly created DB instance it will be re-created on each `apply`.

**Comment by mattsoftware** [comment]
Same issue for me. Booting aurora from snapshot takes 45 minutes, however the 40 minute hardcoded timeout beats it. When running the plan again the aurora instance is destroyed and then tried to be created again, etc. 

It would be fantastic to not have this number hardcoded, but some sane default which could be provided in the config if I know the resource is going to take longer to create. 

I.e. if my instance takes longer than 10 minutes to boot then I want the plan to fail so I can investigate. If booting my aurora instance from a snapshot takes longer than 60 minutes then fail and I can investigate. 

I dont think a hardcoded 'one size fits all' timeout is very useful at all.

**Comment by jamestyrrell** [comment]
This issue is affecting me too, a configurable timeout with the default of no timeout would be perfect.

**Comment by xypaul** [comment]
+1

**Comment by knope** [comment]
+1

**Comment by rfink** [comment]
+1

**Comment by arsdehnel** [comment]
Seems like this can be closed now given the timeouts options?

https://www.terraform.io/docs/providers/aws/r/db_instance.html

**Comment by radeksimko** [comment]
@arsdehnel You're right. Thanks for the note. Closing.

**Comment by jamestyrrell** [comment]
@SerCeMan @paulszabo

**Comment by ricardson** [comment]
+1
