### ISSUE TITLE
Multiple environments with different security group 

### ISSUE THREAD

**Issue by shanhchen** [hashicorp/terraform#5833]
We have a dev environment we want to set the white list on and the prod environment where all traffic should be allowed, then result security group id is feed into ELB. What is the best practice to solve this issue?

**Comment by catsby** [comment]
Hello –

Your best bet is probably review the best practices repository we've started here:

- https://github.com/hashicorp/best-practices/tree/master/terraform/providers/aws

That may provide some guidance here. In general, you can like leverage modules to help you here:

- https://www.terraform.io/docs/configuration/modules.html

Lastly, you may have more success in getting guidance by contacting our mailing list or asking in our IRC channel. You can find more information on how to connect on our Community page:

- https://www.terraform.io/community.html

Thanks!
