### ISSUE TITLE
Error when creating tags with Triton provider

### ISSUE THREAD

**Issue by chorrell** [hashicorp/terraform#5836]
I'm hitting an issue setting a tag for an instance using the Triton provider.

It works fine for simple tags like this:

```
  tags = {
          hello = "world"
          foo = "bar"
      }
```

But it fails with a tag like this:

```
  tags = {
          triton.cns.services = "test"
      }
```

The above tag sets a DNS name for the instance via the [CNS service](https://github.com/joyent/triton-cns).

Here's the error I get:

```
Error applying plan:

1 error(s) occurred:

* triton_machine.test: failed to replace tags for machine with id 43f8bff9-ba48-4dae-89d3-d31e6c6c9d7f
caused by: Missing parameters https://us-east-1.api.joyent.com/christopher/machines/43f8bff9-ba48-4dae-89d3-d31e6c6c9d7f/tags
caused by: request "https://us-east-1.api.joyent.com/christopher/machines/43f8bff9-ba48-4dae-89d3-d31e6c6c9d7f/tags" returned unexpected status 409 with body "{\"code\":\"ValidationFailed\",\"message\":\"error replacing tags: Invalid tag parameters\",\"errors\":[{\"field\":\"tags\",\"code\":\"Invalid\",\"message\":\"\\\"\\\" is not DNS safe\"}]}"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

What I think is happening is the CNS service tag name "test" is that some sort of escaping issue is happening, hence the "Invalid tag parameters" error and `\"message\":\"\\\"\\\" is not DNS safe\"`. I think this might be because the tag name has periods ( `.`)

**Comment by jen20** [comment]
Hi @chorrell! Just as a quick way of narrowing this down - do you get the same error if you specifiy the key as `"triton.cns.services"`?

**Comment by phinze** [comment]
Hi folks, this is an expression of a current limitation of Terraform's config that we're probably going to need to address soon - dots in keys do not work!

You can track the canonical issue for this problem over here: #2143

Going to close this issue to consolidate into that thread, feel free to follow up if you believe there's an independent problem to track here. :+1:

**Comment by chorrell** [comment]
OK, makes sense. Is there any kind of workaround for this to get tags with `.` to work?

**Comment by sodre** [comment]
@phinze I would like to follow up on this bug/feature request. 

If what @chorrell really wants is to support Triton's CNS. Triton CNS has a predefined [set of tags](https://github.com/joyent/triton-cns/blob/master/docs/metadata.md) that we can easily do an invertible transformation.

I have this working in my fork, I'll follow up with a pull-request shortly.

**Comment by jen20** [comment]
Tags with dots now work ok (in 0.7.0-rc1)!
