### ISSUE TITLE
Join AWS instance into directory service directory

### ISSUE THREAD

**Issue by saswatp** [hashicorp/terraform#5842]
When I create an aws_instance for a windows server, I don't see a way to automatically join that to a AWS directory service directory. In the EC2 console , I can do that. 

Is there a way this could be done (with proper iam instance profile) ??

**Comment by msnelling** [comment]
I am also looking for a way to do this. I don't see an argument to specify the directory id.

**Comment by edutori** [comment]
Any update on this regards?

**Comment by bentterp** [comment]
I would also like to see this feature. Without it, managing 2016 Nano on AWS is a pain....

**Comment by stack72** [comment]
Hi, 

I believe this can be done via the SSM association - https://www.terraform.io/docs/providers/aws/r/ssm_association.html

Thanks 

Paul
