### ISSUE TITLE
remote saml_metadata_document

### ISSUE THREAD

**Issue by tomdavidson** [hashicorp/terraform#5848]
I would like to reference a remote document over https in creating a aws_iam_saml_provider rather than a local file, something similar to modules' `source = "github.com/....` such as:

```
resource "aws_iam_saml_provider" "default" {
    name = "myprovider"
    saml_metadata_document = "${file("https://domain.local/idp/shibboleth")}"
}
```

The remote file seems especially relevant in this case - am I overlooking existing functionality?

**Comment by radeksimko** [comment]
This looks like an interesting idea. I think that adding a way to get data from remote location over HTTP(S) and/or other protocols may require a slightly more sophisticated approach though. It would almost deserve its own resource, or better - [data source](https://github.com/hashicorp/terraform/pull/4961).

Something like this (hypothetical data source):

```hcl
data "remote_file_over_http" "saml_doc" {
  url = "https://domain.local/idp/shibboleth"
  follow_redirects = true
  expected_content_type = "text/xml"
  basic_auth = "user:pass"
}
```

Also I think it would make even more sense to have `shibboleth` and other IdPs supported as Terraform providers and be able to codify the configuration on that end too. It obviously depends on IdP's APIs. 

Automation FTW. :smiley:

**Comment by tomdavidson** [comment]
I agree, that making some cas providers would be slick, but i think the remote file resource would still have significant value. I suggest "remote_file" that supports local, http, and git just as module source does?

In my case, I want to fake it for now. This seems a bit hackish, do you have a better suggestion?

```
variable "saml_metadata_file" {
    default = "idp-metadata.xml"
}

resource "null_resource" "getfile" {
    provisioner "local-exec" {
        command = "curl -s -o  ${var.saml_metadata_file} https://domain.local/idp/shibboleth"
    }
}

resource "aws_iam_saml_provider" "cas" {
    name = "cas"
    saml_metadata_document = "${file("${var.saml_metadata_file}")}"
}
```

**Comment by radeksimko** [comment]
That might work, but you may want to define explicit dependency between `null_resource` and `aws_iam_saml_provider` otherwise Terraform may try to create `null_resource` and `aws_iam_saml_provider` at the same time and the file may be missing:

```hcl
resource "aws_iam_saml_provider" "cas" {
    depends_on = ["null_resource.getfile"]
    name = "cas"
    saml_metadata_document = "${file("${var.saml_metadata_file}")}"
}
```

The value you'll get from such setup is arguable though. Terraform doesn't know whether the remote file has changed and it will never re-execute the provisioner (unless you explicitly `taint` the `null_resource`).

**Comment by tomdavidson** [comment]
It "works" but not unsure about best practice and convention. I added the explicit depends. It does download the file, but there is no clean up for it. 

Do I need to declare the saml_metadata_file variable generally , could I add this var to null_resource.getfile? Example code?

**Comment by eric-nord** [comment]
Could this be resolved by updating  [HTTP DATA PROVIDER](https://www.terraform.io/docs/providers/http/data_source.html) to allow ```application/samlmetadata+xml``` on [line 95](https://github.com/hashicorp/terraform/blob/master/builtin/providers/http/data_source.go)

We could then use something like this to access the metadata file:

```data "http" "saml_metadata_document" {
  url = "https://website.com/federationmetadata/2007-06/saml_metadata.xml"

    request_headers {
    "Accept" = "application/samlmetadata+xml"
  }
}


resource "aws_iam_saml_provider" "default" {
  name                   = "${var.idp_name}"
  saml_metadata_document = "${data.http.saml_metadata_document.xml}"
}
```
