### ISSUE TITLE
Prevent creation of duplicate aws_lambda_permission

### ISSUE THREAD

**Issue by dmitryint** [hashicorp/terraform#5849]
I try to create two Lambda functions, run it by the scheduler.

However, I ran into a problem.

Here is my code:

``` hcl
resource "aws_lambda_function" "EBSToSnapshotBackup" {
    filename = "ebs_to_snapshot_backup.py.zip"
    function_name = "ebs_to_snapshot_backup"
    description = "Set instance tags: backup=true, Retention=days"
    runtime = "python2.7"
    role = "${aws_iam_role.ebs-backup-worker.arn}"
    handler = "ebs_to_snapshot_backup.lambda_handler"
}

resource "aws_lambda_function" "EBSSnapshotRotation" {
    filename = "ebs-snapshot-janitor.py.zip"
    function_name = "ebs-snapshot-janitor"
    runtime = "python2.7"
    role = "${aws_iam_role.ebs-backup-worker.arn}"
    handler = "ebs-snapshot-janitor.lambda_handler"
}

resource "aws_lambda_permission" "allow_cloudwatch_to_call_EBSToSnapshotBackup" {
    statement_id = "AllowExecutionFromCloudWatch"
    action = "lambda:InvokeFunction"
    function_name = "${aws_lambda_function.EBSToSnapshotBackup.function_name}"
    principal = "events.amazonaws.com"
    source_arn = "${aws_cloudwatch_event_rule.every_day.arn}"
}

resource "aws_lambda_permission" "allow_cloudwatch_to_call_EBSSnapshotRotation" {
    statement_id = "AllowExecutionFromCloudWatch"
    action = "lambda:InvokeFunction"
    function_name = "${aws_lambda_function.EBSSnapshotRotation.function_name}"
    principal = "events.amazonaws.com"
    source_arn = "${aws_cloudwatch_event_rule.every_day.arn}"
}

resource "aws_cloudwatch_event_rule" "every_day" {
    name = "every_day"
    description = "Fires every day"
    schedule_expression = "rate(1 day)"
}

resource "aws_cloudwatch_event_target" "EBSToSnapshotBackup_every_day" {
    rule = "${aws_cloudwatch_event_rule.every_day.name}"
    target_id = "ebs_to_snapshot_backup"
    arn = "${aws_lambda_function.EBSToSnapshotBackup.arn}"
}

resource "aws_cloudwatch_event_target" "EBSSnapshotRotation_every_day" {
    rule = "${aws_cloudwatch_event_rule.every_day.name}"
    target_id = "ebs-snapshot-janitor"
    arn = "${aws_lambda_function.EBSSnapshotRotation.arn}"
}
```

Terraform is able to successfully create the necessary infrastructure.

But the connection between Cloudwatch scheduled event and Lambda functions not being created correctly.

And therefore lambda functions are not triggered by the event scheduler.

![2016-03-24 8 33 00](https://cloud.githubusercontent.com/assets/9825180/14009263/90f424c0-f1a3-11e5-89f4-4041678569e2.png)

To successfully run the scheduler, in the tab 'Event sources' in the Lambda function must be an event `every_day` but it is not added.

![2016-03-24 8 33 22](https://cloud.githubusercontent.com/assets/9825180/14009266/9b63df4a-f1a3-11e5-8a8b-7a8dc2e3f49e.png)

**Comment by tj** [comment]
Hit this as well, confusingly appears like it works from the CloudWatch events Events page, but they don't do anything

**Comment by radeksimko** [comment]
Usually the reason you wouldn't see any Event Sources in the GUI is because you don't have Lambda permission in place to allow the CloudWatch Event to trigger the Lambda function, but it seems that's not your case.

Your example doesn't include definition for `aws_iam_role.ebs-backup-worker`. I used a basic one:

```hcl
resource "aws_iam_role" "ebs-backup-worker" {
  name = "test_lambdafuntion_iam_role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```

then replaced two `aws_lambda_function` fields (`filename`, `engine`) and `apply` worked for me:

```
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
```
and I can see 1 record in the `Event sources` tab for both Lambda functions.

I'm using Terraform `v0.6.16`.

i.e. I'm unable to reproduce this issue. Can you provide more details, please? e.g. definition for the IAM role?

**Comment by dmitryint** [comment]
This advice helped solve my problem.
https://github.com/hashicorp/terraform/issues/4393#issuecomment-204415472

**Comment by radeksimko** [comment]
Ah, I see, duplicate statement ID... 

We could possibly do something clever, like prevent creation of permission with statement id that already exists.
