### ISSUE TITLE
Azure PaaS (Service Bus, ...)

### ISSUE THREAD

**Issue by FlorianLudwig** [hashicorp/terraform#5858]
The Azure platform offers a wide range of Platform-as-a-Services. The service bus is just one of them.  It would be great having one place (terraform) to create, change and version them like the rest of the Azure infrastructure.

**Comment by MattTunny** [comment]
Would love to have this feature in terraform!

**Comment by pmcatominey** [comment]
@FlorianLudwig Service Bus resources are available now!

**Comment by FlorianLudwig** [comment]
Awesome! Will try it next week.

**Comment by pmcatominey** [comment]
Closing as ServiceBus is supported now.
