### ISSUE TITLE
Launch Configurations no longer properly wait for IAM Instance Profile propagation in v0.6.14

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5862]
We fixed #2349 a while ago, but a recent AWS SDK update broke our error detection.

https://github.com/hashicorp/terraform/blob/7501f3272106ce77a1117229ce65d10c2aefe094/builtin/providers/aws/resource_aws_launch_configuration.go#L435

I have a failing test locally - will follow up when I have a fix!

**Comment by phinze** [comment]
For folks running into this in current version - you can work around it by adding a `local-exec` provisioner with a `sleep` to your instance profile resource so it waits for propagation before continuing. :+1:

**Comment by gugahoi** [comment]
This seems to still be a problem in Terraform v0.7.1. Any ideas of a fix other than adding `sleep`?

**Comment by superlogical** [comment]
I'm seeing this issue with Terraform v0.7.1 too

**Comment by k2t0f12d** [comment]
Might be a red herring because AWS has had an IAM outage today.

**Comment by pghalliday** [comment]
I just ran into this issue I think. I destroyed the deployment and ran apply again and it succeeded the second time around

**Comment by stannie42** [comment]
I've this issue in terraform v0.7.9

* aws_launch_configuration.web-lc: Error creating launch configuration: ValidationError: Invalid IamInstanceProfile: test_profile
	status code: 400, request id: c6c7e5e7-ac27-11e6-b3b1-27fac36f2226
