### ISSUE TITLE
Default AWS profile used by nested modules for aws_route53_record resource

### ISSUE THREAD

**Issue by dustyburwell** [hashicorp/terraform#5868]
I've encountered an issue with the AWS provider while trying to create a route53 record inside of a nested module. Even though I've set the profile for the AWS provider, it appears to be trying to use the `[default]` profile when refreshing state for this resource. I've set up a somewhat contrived, but minimal [test case](https://github.com/dustyburwell/terraform_test_case).

My `[default]` profile is for a different account than the one I'm attempting to terraform. When running `terraform plan`, while refreshing state, I receive an error similar to the following:

```
* aws_route53_record.dns: AccessDenied: User: arn:aws:iam::<account_id>:user/dustyburwell@gmail.com is not authorized to access this resource
	status code: 403, request id: <uuid>
```

The `<account_id>` referenced above is the account tied to my `[default]` profile, not the `[testaccount]` profile as set in the aws provider block. If I move the provider block into the module the next level up (i.e. https://github.com/dustyburwell/terraform_test_case/blob/master/test_impl/main.tf), things work as expected.

Please let me know if you need any further information. Cheers.

**Comment by dustyburwell** [comment]
Also, please, let me know if I'm doing something completely silly, here. I'm trying to compose more generic modules into super modules that have some nice defaults set. Perhaps there's a better way to go about this.

**Comment by radeksimko** [comment]
@dustyburwell Can you check whether you have any environment variables set?

```
$ printenv | grep AWS
```

such variables with invalid credentials may be causing this issue as environment variables [have priority](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L393) over the config file.

**Comment by dustyburwell** [comment]
I don't have any AWS environment variables set:

```
➜  printenv | grep AWS
➜  
```

**Comment by radeksimko** [comment]
> Even though I've set the profile for the AWS provider

from [what I can see](https://github.com/dustyburwell/terraform_test_case/blob/master/base_module/main.tf) you did not declare the `provider` block again inside the module?

There is currently no easy way to predictably inherit providers between modules I think, so you'll need to redeclare the provider inside the module _for now_. It admittedly does make the module less reusable as module code in most cases shouldn't be responsible for setting up the provider connection.

Do you think we can treat this issue as a duplicate of https://github.com/hashicorp/terraform/issues/2832 ?

**Comment by dustyburwell** [comment]
Yes! #2832 definitely seems to track toward the same problem. And I've noticed that setting the provider profile inside the module does work around the issue. Thanks!
