### ISSUE TITLE
Azure: Documentation on Authentication

### ISSUE THREAD

**Issue by FlorianLudwig** [hashicorp/terraform#5880]
The documentation is sparse on how to correctly authenticate the azure provides.

See also [this comment](https://github.com/hashicorp/terraform/issues/5875#issuecomment-202097500) on #5875 - it is also suggested that the issue might result in incorrectly setup authentication.  Which is hard to do with the current sparse information in the documentation.

I am trying this guide: https://msdn.microsoft.com/en-us/library/azure/ee460782.aspx#bk_ad but setting up Azure AD just to access the API seems not to be the "right way" to do it, or is it?

**Comment by majormoses** [comment]
This landed: https://github.com/hashicorp/terraform/pull/5965/files

I will test it and see if there is enough doc to get going.

**Comment by voiddragon** [comment]
I think adding the CLI methods might be helpful as well.

https://github.com/Azure/acs-engine/blob/master/docs/serviceprincipal.md

**Comment by majormoses** [comment]
@voiddragon does this work for you?

**Comment by voiddragon** [comment]
Yup, had to reset the secret before I could get it to work though.

**Comment by majormoses** [comment]
@voiddragon the doc you linked uses `az` rather than `azure` do you happen to know if that is basically a custom alias? sorry I have not had time to validate.

**Comment by voiddragon** [comment]
@majormoses az is the alias for the new python based cli

**Comment by majormoses** [comment]
@voiddragon thanks I will update the doc
