### ISSUE TITLE
How to use google bucket as remote storage via S3 backend (or other?)

### ISSUE THREAD

**Issue by daodennis** [hashicorp/terraform#5889]
Hi,

I am trying to use a Google Bucket as remote state storage and I am under the impression that it has API compatibility with the AWS S3 API, though I can't seem to make it work out of the box.
I think I am close?

`$ terraform remote config -backend=s3 -backend-config="bucket=" -backend-config="key=terraform.tfstate" -backend-config="endpoint=www.googleapis.com/download/storage/v1/b/" -backend-config="region=us-east=1"
Remote configuration updated
Error while performing the initial pull. The error message is shown
below. Note that remote state was properly configured, so you don't
need to reconfigure. You can now use `push` and `pull` directly.

Error reloading remote state: :
	status code: 404, request id:`

I tried to create the file 

Some other misc notes:

I configured `"backend="` because otherwise I get an SSL Error:
`Error reloading remote state: RequestError: send request failed
caused by: Get https://shpsec-hackday-terraform-global.www.googleapis.com/download/storage/v1/b/terraform.tfstate: x509: certificate is valid for *.googleapis.com, *.clients6.google.com, *.cloudendpointsapis.com, cloudendpointsapis.com, googleapis.com, not terraform-global.www.googleapis.com`

Here is some Google Docs on the Compatibility mode: https://cloud.google.com/storage/docs/request-endpoints

There is also "Interoperability Mode" that I enabled in the GCP console and I created a key. I used that key to create an AWS provider, because the key was named access_key and secret, but I get the exact same 404 output.

I am not sure how to man in the middle the terraform TLS traffic to see exactly what the request parameters are and TF_LOG=trace just show the loading of all the plugins. (I can file a separate FR for this to log some of the HTTP parameters?)

**Comment by stack72** [comment]
Hi @daodennis 

there is a PR in place to use Google as a storage medium for state

https://github.com/hashicorp/terraform/pull/3719

We will try and get this merged soon

Paul
