### ISSUE TITLE
aws_api_gateway_integration_response selection_pattern not sent

### ISSUE THREAD

**Issue by rog555** [hashicorp/terraform#5891]
Hello @radeksimko @phinze @nicolai86,

In resource_aws_api_gateway_integration_response.go, "selection_pattern" is in the schema but not sent in resourceAwsApiGatewayIntegrationResponseCreate [PutIntegrationResponse](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_api_gateway_integration_response.go#L69)

This effectively means can only have one integration_response per method

cheers

roger

**Comment by radeksimko** [comment]
Thanks @rog555 for the report.

Bugfix in #5893
