### ISSUE TITLE
core/schema: Introduce schema.ForceNewWhen

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5895]
There seems to be a need for a new schema field - `ForceNewWhen`.

This came up in https://github.com/hashicorp/terraform/issues/5373 where we found that Route53 Hosted Zone's VPC association updates don't have to trigger replacement of the whole zone at all times.

I assume the end-schema-user interface might look roughly like this:

``` go
"vpc_id": &schema.Schema{
    Type:         schema.TypeList,
    Optional:     true,
    ForceNewWhen: func(oldValue, newValue interface{}) {
        if len(oldValue.([]interface{})) == 0 || len(newValue.([]interface{})) {
            return true
        }
        return false
    },
},
```

**Comment by apparentlymart** [comment]
The proposal in #8769 would address this as part of its broader scope, though perhaps a more targeted solution is warranted too so that all that complexity can be avoided for relatively-straightforward cases...

**Comment by stevehorsfield** [comment]
We've been hit by a similar issue with Lambda versions and CloudFront. I would personally favour a focus on an broad architectural fix.

**Comment by radeksimko** [comment]
@stevehorsfield Hi, the broad architectural fix is described as proposal in https://github.com/hashicorp/terraform/issues/8769 with implementation being worked on in https://github.com/hashicorp/terraform/pull/14887

Feel free to subscribe to either of those using the `Subscribe` button on the right side.

**Comment by teamterraform** [comment]
Hi all!

The proposal @apparentlymart referred to above was later implemented and is available for providers to use. The mechanism is for the resource type object to include a field called `CustomizeDiff` which is a Go function that can take various actions against the planned changeset, including marking a particular argument change as requiring the object to be replaced.
