### ISSUE TITLE
vsphere_virtual_machine: not supported (vCenter only)

### ISSUE THREAD

**Issue by fuhbar** [hashicorp/terraform#5896]
What does this error message mean? 

```
2016/03/29 14:28:35 [DEBUG] terraform-provider-vsphere: 2016/03/29 14:28:35 [DEBUG] folder: "Tests"
2016/03/29 14:28:36 [DEBUG] vertex provider.vsphere (close), waiting for: vsphere_virtual_machine.terraform-test
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalWriteState
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalIf
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalIf
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalWriteState
2016/03/29 14:28:36 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/03/29 14:28:36 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.terraform-test: not supported (vCenter only)
2016/03/29 14:28:36 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.terraform-test: not supported (vCenter only)
2016/03/29 14:28:36 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* vsphere_virtual_machine.terraform-test: not supported (vCenter only)
2016/03/29 14:28:36 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.terraform-test: not supported (vCenter only)
2016/03/29 14:28:36 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.terraform-test
2016/03/29 14:28:36 [DEBUG] vertex provider.vsphere (close), got dep: vsphere_virtual_machine.terraform-test
Error applying plan:
2016/03/29 14:28:36 [DEBUG] waiting for all plugin processes to complete...

1 error(s) occurred:

* vsphere_virtual_machine.terraform-test: not supported (vCenter only)
```

Running terraform 0.6.14 against VSphere 5.5 and 6.0 - both same result as above. 

Traced this error message to `vmware/govmomi` dependency at:
* [object/common.go:31](https://github.com/hashicorp/terraform/blob/master/vendor/github.com/vmware/govmomi/object/common.go#L31)
* [object/custom_fields_manager.go:42](https://github.com/hashicorp/terraform/blob/master/vendor/github.com/vmware/govmomi/object/custom_fields_manager.go#L42)
* [object/extension_manager.go:35](https://github.com/hashicorp/terraform/blob/master/vendor/github.com/vmware/govmomi/object/extension_manager.go#L35)
* [object/distributed_virtual_switch.go:39](https://github.com/hashicorp/terraform/blob/master/vendor/github.com/vmware/govmomi/object/distributed_virtual_switch.go#L39)

But from a non developer perspective its hard to get any semantic value out of these findings. What might possibly caused this error?

**Comment by superseb** [comment]
@fuhbar Can you supply exact vSphere versions and the .tf file you are using?

**Comment by fuhbar** [comment]
@superseb Using the following VCenter Versions
* Version: 5.5.0 / Build: 3252642
* Version: 6.0.0 / Build: 3339084

The terraform file i am using is as follows: 

```terraform
# Configure the VMware vSphere Provider
provider "vsphere" {
  user                  = "${var.vsphere.user}"
  password              = "${var.vsphere.password}"
  vsphere_server        = "${var.vsphere.server}"
  allow_unverified_ssl  = true
}

# Create a folder
resource "vsphere_folder" "terraform" {
  path = "${var.vsphere.folder}"
  datacenter = "${var.vsphere.dc}"
}

# Create a virtual machine within the folder
resource "vsphere_virtual_machine" "terraform-test" {
  name   = "terraform-test"
  folder = "${vsphere_folder.terraform.path}"
  datacenter = "${var.vsphere.dc}"
  cluster = "${var.vsphere.cluster}"
  vcpu   = 2
  memory = 4096

  gateway = "${var.host_defaults.gateway}"
  domain  = "${var.host_defaults.mgmt_domain}"
  dns_servers = [ "8.8.8.8", "8.8.4.4" ]

  network_interface {
    label = "${var.host_defaults.network}"
    ipv4_address = "172.16.1.2"
    ipv4_prefix_length = 24
  }

  disk {
    datastore = "${var.host_defaults.datastore}"
    size = 40
  }
}
# vim: set ts=2 sw=2 et ft=terraform:
```

The variables files looks similiar to this one: 
```terraform
variable "vsphere" {
  description = "The environment we are working in"
  default {
    user = "user@domain"
    password = "XXXXXX"
    server = "vcenter01.domain.local"
    folder = "Tests"
    dc = "FFM"
    cluster = "clust01"
  }
}

variable "host_defaults" {
  description = "Host common defaults"
  default {
    network = "upstream-prod"
    mgmt_domain = "mgt.domain.local"
    datastore = "FC01"
    gateway = "172.16.1.1"
  }
}
# vim: set ts=2 sw=2 et ft=terraform:
```

**Comment by xantheran** [comment]
Can you remove the VM folder creation part of it?

Create the target folder before hand and add the path to your vsphere_virtual_machine.terraform-test resource and then run terraform apply.

**Comment by fuhbar** [comment]
@xantheran Unfortunately I got the same result when a leave out the folder part and create it manually. Even the debug output is identical - except for the line naming the folder which now is (expectable) blank ("").

Following your idea I've removed all the optional stuff and kept the required ones. Same result.  

No idea how to continue. Anyone?

**Comment by xantheran** [comment]
What licensing do you have for vCenter and ESXi?

**Comment by fuhbar** [comment]
* VMware vSphere 5 Enterprise Plus (unlimited cores per CPU)
* VMware vSphere 6 Enterprise Plus (CPUs)

**Comment by chrislovecnm** [comment]
@fuhbar @xantheran should we reach out to the govomi folks?  

@fuhbar can u use [govc](https://github.com/vmware/govmomi/tree/master/govc) to recreate this?  Recreating this problem with `govc` will also us to isolate it further.

**Comment by xantheran** [comment]
Does the user@domain account have read access to the root level in cluster clust01 on dc FFM?

**Comment by chrislovecnm** [comment]
@fuhbar can you verify @xantheran's question.  `govc` is a good tool to do this with.  It is a go cli that is awesome.  Located [here](https://github.com/vmware/govmomi/tree/master/govc).

**Comment by fuhbar** [comment]
@xantheran @chrislovecnm Thanks for your support. Nailed it down to insufficient Permissions.

* [govc](https://github.com/vmware/govmomi/tree/master/govc) delivered the same results as terraform does: `govc: not supported (vCenter only)`
* Tried local Administrator account instead of LDAP connected one, this time with success

Will investigate which permissions were missing tomorrow. Will report here and close issue.

**Comment by chrislovecnm** [comment]
@fuhbar - problem is definitely something wth perms or licensing.  Let us know what you find out, would be good to document!

**Comment by chrislovecnm** [comment]
@fuhbar we actually have some documentation that is waiting on a merge that may help:

https://github.com/mixacha/terraform/blob/master/builtin/providers/vsphere/README.md

Let @mixacha and I know if that helps, or should be revised.

**Comment by fuhbar** [comment]
@chrislovecnm thanks man, you are great. Haven't found time to get back to this. 

With the reference to the documentation you've supplied this issues is pretty much completely solved. Closing it.

Thanks again! :)
