### ISSUE TITLE
`destroy` should wait (longer) for an RDS instance to be destroyed

### ISSUE THREAD

**Issue by timmytofu** [hashicorp/terraform#5899]
With the minimal config at the bottom, I can create a DB in a subnet. When I `terraform destroy`, though, I inevitably get an error 

```
* aws_db_subnet_group.pg-subnet-group: InvalidDBSubnetGroupStateFault: Cannot delete the subnet group 'pg-subnet-group' because at least one database instance: postgres is still using it.
        status code: 400, request id: 47b1b254-f5bd-11e5-8be4-d967ab0696f7
```

If I run `terraform destroy` again it works, starting by destroying `pg-subnet-group`. So, I think terraform needs to wait a little longer/check that the DB instance is completely destroyed before trying to destroy resources upon which it depends.

System info:

```
tim 2016Mar29 10:54:33> terraform -version
Terraform v0.6.13

tim 2016Mar29 10:57:50> uname -a
Linux seitan 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Config used:

```
variable "aws_access_key" {}
variable "aws_secret_key" {}

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "us-west-2"
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "vpc"
  }
}

resource "aws_security_group" "db-sg" {
  name = "db-sg"

  vpc_id = "${aws_vpc.vpc.id}"

  tags {
    Name = "db-sg"
  }
}

resource "aws_subnet" "db-priv-west2a" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.1.0/24"

  availability_zone = "us-west-2a"
}

resource "aws_subnet" "db-priv-west2c" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.2.0/24"

  availability_zone = "us-west-2c"
}

resource "aws_db_subnet_group" "pg-subnet-group" {
  name = "pg-subnet-group"
  description = "blah"

  subnet_ids = [ "${aws_subnet.db-priv-west2a.id}", "${aws_subnet.db-priv-west2c.id}" ]
}

resource "aws_db_instance" "postgres" {
  allocated_storage = 5
  engine            = "postgres"
  engine_version    = "9.4.5"
  identifier        = "postgres"
  instance_class    = "db.t2.micro"
  storage_type      = "standard"

  vpc_security_group_ids = [ "${aws_security_group.db-sg.id}" ]
  publicly_accessible = false
  db_subnet_group_name = "pg-subnet-group"

  name     = "foo"
  username = "foofoofoo"
  password = "barbarbar"
  port     = "5432"

  backup_retention_period = "1"
  skip_final_snapshot = "true"
}
```

**Comment by catsby** [comment]
Hey @timmytofu – I think you're hitting this issue because your `aws_db_instance` does not directly depend on your `aws_db_subnet_group`; Terraform does not know the two are related, so it's trying to delete the subnet before waiting for the DB to be destroyed. 

You can see that your DB Instance depends on your Security Group `db-sg` because of this reference in `aws_db_instance`:

    vpc_security_group_ids = [ "${aws_security_group.db-sg.id}" ]

This tells Terraform that it needs to create the security group first, then the database. However, when you add the `db_subnet_group_name ` value to your Database, you reference the text name instead of using Terraforms interpolation. Ex:

    db_subnet_group_name = "pg-subnet-group"

To make this work, you should change the above to this:

    db_subnet_group_name = "${aws_db_subnet_group.pg-subnet-group.name}"

That will create a connection between the two resources, and Terraform will properly order both creation and deletion.

Hope this helps! Let me know if you're still hitting this problem after making the recommended change

**Comment by yelvert** [comment]
This is still broken, even with `db_subnet_group_name` set on the `aws_db_instance`. The `db_subnet_group` was provisioned with terraform and there is only one db instance associated to it.

    resource "aws_db_subnet_group" "app" {
      name = "app_${var.env_name}"
      subnet_ids = ["${aws_subnet.us-east-1b-private.id}", "${aws_subnet.us-east-1d-private.id}"]
    }

    resource "aws_db_instance" "app" {
      allocated_storage = 5
      engine = "postgres"
      engine_version = "9.5.4"
      instance_class = "db.t2.micro"
      name = "MyApp_${var.env_name}"
      username = "myapp"
      password = "<%= app_db_pass %>"
      db_subnet_group_name = "app_${var.env_name}"
      vpc_security_group_ids = [
        "${aws_security_group.app_db.id}"
      ]
    }

I get the following error

    aws_db_instance.app: Still destroying... (4m0s elapsed)
    aws_db_instance.app: Still destroying... (4m10s elapsed)
    aws_db_instance.app: Still destroying... (4m20s elapsed)
    aws_db_instance.app: Still destroying... (4m30s elapsed)
    aws_db_instance.app: Destruction complete
    aws_security_group.app_db: Destroying...
    aws_security_group.app_db: Destruction complete
    Error applying plan:

    1 error(s) occurred:

    * aws_db_subnet_group.app: InvalidDBSubnetGroupStateFault: Cannot delete the subnet group 'app_development' because at least one database instance: tf-00cb15ea2753bfb558a052a005 is still using it.
      status code: 400, request id: bca0fdb2-e800-11e6-b052-1d3ae12bff72

    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.

It simply just doesn't wait long enough after the `db_instance` destruction is complete before trying to destroy the `db_subnet_group`.

**Comment by shederman** [comment]
Hi, I'm getting this exact same issue, means tear down does not work predictably. When will this be fixed?

**Comment by asim42** [comment]
@shederman I reached here with same problem please read @catsby's reponse. It solved my problem as well.

**Comment by carlio** [comment]
This is still the same for me even when using interpolated `db_subnet_group_name` - I have to apply twice and manually wait for the RDS instance to appear. Same with destroy.
