### ISSUE TITLE
Referencing task_definition with interpolation in aws_ecs_service causes change when applying

### ISSUE THREAD

**Issue by roylines** [hashicorp/terraform#5903]
I am referencing a task definition using interpolation as follows:

```
resource "aws_ecs_task_definition" "microservice" {
  count = "${var.microservices_count}"
  ...
}

resource "aws_ecs_service" "microservice" {
  count = "${var.microservices_count}"
  task_definition = "${element(aws_ecs_task_definition.microservice.*.arn, count.index)}"
  ...
}
```

This works fine as I increase the microservices_count from, for example, 2 to 3 and apply. If I now reduce the count from 3 to 2 terraform thinks there is a change to the task_definition for the resources at index 1 and 2, and terraform plan shows the following:

```
~ aws_ecs_service.microservice.0
    task_definition: "arn:aws:ecs:us-east-1:126133281286:task-definition/auth:14" => "${element(aws_ecs_task_definition.microservice.*.arn, count.index)}"

~ aws_ecs_service.microservice.1
    task_definition: "arn:aws:ecs:us-east-1:126133281286:task-definition/promos:13" => "${element(aws_ecs_task_definition.microservice.*.arn, count.index)}"
```

It appears to be comparing the string before interpolation and thinking the task_definition has changed when it hasn't. This causes the state to get messed up, and subsequent calls to apply will fail.

Any suggestions welcome, and happy to contribute if you point me in the right direction.

**Comment by adamgotterer** [comment]
I'm having a similar problem. Accept my interpolated string doesn't even need to change for the service to be marked as modified.

**Comment by mitchellh** [comment]
This is fixed in master, was a dup of a bug just fixed last week!
