### ISSUE TITLE
google-two-tier example is incomplete

### ISSUE THREAD

**Issue by mcalthrop** [hashicorp/terraform#5912]
Hi

I tried using the `google-two-tier` example in the `examples` directory, but it doesn't work:
* there are no instructions for creating the `~/.ssh/gcloud_id_rsa.pub` public key
* even when the `~/.ssh/gcloud_id_rsa.pub` file is created using `ssh-keygen`, the terraform deployment still does not work
* no errors are reported when it fails &ndash; you only know it has failed because the Google Compute console shows an error for each VM that was created

Additionally, the `sshKeys` syntax has been superseded by `ssh-keys`, and to make use of this new syntax, a newer version of the ubuntu distribution is required.

I've managed to get it working (see [mcalthrop/terraform-sandbox](/mcalthrop/terraform-sandbox/tree/master/example-google-two-tier)), which I plan to use as a basis for a PR to address the issues raised in this ticket. I also plan to update the `README` to include instructions for generation of the public key.

**Comment by stack72** [comment]
Hi @mcalthrop 

Closing this as you had a PR merged for #5917 - thanks for letting us know and then fixing it :)

P.

**Comment by mcalthrop** [comment]
Thanks @stack72! Forgot to close. It was a great way to learn more about Terraform.
