### ISSUE TITLE
provider/aws: Question about Elastic Beanstalk tests

### ISSUE THREAD

**Issue by dharrisio** [hashicorp/terraform#5922]
The current Beanstalk acceptance tests may fail on some AWS accounts. For example, with a recently added test I am now seeing it fail with this message:

```
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSBeanstalkConfigurationTemplate_VPC -timeout 120m
=== RUN   TestAccAWSBeanstalkConfigurationTemplate_VPC
--- FAIL: TestAccAWSBeanstalkConfigurationTemplate_VPC (9.47s)
	testing.go:154: Step 0 error: Error applying: 1 error(s) occurred:
		
		* aws_elastic_beanstalk_configuration_template.tf_template: Error creating Elastic Beanstalk configuration template: InvalidParameterValue: No Solution Stack named '64bit Amazon Linux 2015.03 v2.0.3 running Go 1.4' found.
			status code: 400, request id: 046adf7f-f5fa-11e5-81f8-273f518c38c5
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	9.479s
```

The reason this happens is that AWS rotates what solution stacks are available in a given account fairly quickly. If you don't use a stack version in that account and a new version is released, you don't have access to the now 'old' solution stack. In order to prevent having to update the test config documents with updated solution stacks, it would be nice to look these up based on the account the tests are being run in. After some experimentation/reading the code, it appears that the test provider is not available outside of the test step check functions. To work around that I did this https://gist.github.com/dharrisio/0a0a48756dc197ed9ca8#file-resource_aws_elastic_beanstalk_environment_test-go-L109

That gist is a bit old and out of date now, but I was wondering if there was a better way to create the session and describe the available solution stacks?

**Comment by dharrisio** [comment]
One possible workaround here to use a `solution_stack` that was created before versions were added to the stack name. Updating to use the stack `64bit Amazon Linux running Python` appears to fix the problem. 

The only downside with this method is that the tests are being run with a stack that no one would actually use in Elastic Beanstalk.

**Comment by stack72** [comment]
Hi @dharrisio 

I am going to go ahead and close this - we have proved that the terraform plan runs with the Python stack. I know this is not *exactly* what people would use, but it proves that the terraform config is valid and creates the correct outputs etc :)

Thanks for raising the awareness of the fact that the stack names get updated / revved

Thanks

Paul
