### ISSUE TITLE
nutanix acropolis support

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform#5923]
Could we get support for nutanix hypervisors? Specifically the Acropolis api

It comes in both a community edition and an enterprise edition. 

http://www.nutanix.com/products/acropolis/

The rest api is well documented, and has an interactive explorer. 

http://prismdevkit.com/nutanix-rest-api-explorer/

**Comment by jen20** [comment]
Hi @spuder! Thanks for opening an issue here. This isn't on our roadmap right now, but as per the [contribution guidelines](https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md) we would be happy to review pull requests for it assuming that we have a way to run acceptance tests. If it becomes a priority in future, I'll reopen and update this issue!

**Comment by JonKohler** [comment]
FYI @spuder 
Jon from Nutanix here - Wanted to let y'all know that we're indeed working on this 

If you haven't seen it already, I just posted up an early demo to my youtube channel here: 
https://www.youtube.com/watch?v=V8_Lu1mxV6g

We'll work on generating a proper PR for this once we get a bit further in the dev cycle to get this upstream

**Comment by umitseremet** [comment]
Hi @JonKohler, is there any way to use your development branch about this project in our test pipeline cases? Is your code in public repo?

**Comment by JonKohler** [comment]
@umitseremet - We're working with HashiCorp now to go through the code review now, circling back with them this week. Meaning the upstream work is progressing, albeit I'm the slow poke (need to get them access to a few clusters to validate provider code). Working through that shorty.

Hit me up at jon at nutanix dot com from your business mail, happy to chat more, and we can figure out if the current state of the provider will suit your needs. Looking forward to chatting!

**Comment by JonKohler** [comment]
Hey folks, quick update. We're still working on this. I've started up a slack channel on the nutanix slack instance for both internal folks and external/community folks to collaborate with us on all things terraform. If anyone wants to join up, feel free to ping me jon@nutanix.com from your business address and I'll get you added. Alpha binary is there, and we can also add folks to our private repo if anyone want to collaborate on a code level

**Comment by JonKohler** [comment]
Hey folks. Hoping for some help from the community to make sure what we're building will be useful to our existing and prospective customers. Below are a few questions to get that conversation going.

There's also a quick call to action to get requests formally tracked via our support organization, as we do for all new feature requests. This helps keep us honest by getting it into the system of record and also helps us formally track volume. It also let us know who exactly to follow up with when we're done.

Terraform Integration Questions:

1. Are you standardized on a specific version of Terraform, or do you use the latest available when releases come out?
2. If standardized on a specific version, is there a reason that you can not use the latest available?
3. Can you describe your typical daily/weekly workflow with terraform?
4. Can you share a sanitized copy of your existing TF files?
5. If not, can you describe in detail the existing providers you are using, along with specifically what resources and/or data sources types you are using?
6. If you are an existing NX/Software Only (Cisco, HPe, etc) customer, can you please file a support ticket with priority "RFE" on portal.nutanix.com, and reference terraform support for Nutanix FEAT-5346?
7. If you are an existing Dell XC / Lenovo HX customer, please open a similar type of request via your support channels.
8. If you are a prospective customer, feel free to share that information with terraform@nutanix.com and/or jon@nutanix.com

**Comment by JonKohler** [comment]
FYI folks - following up on this

I'm so pleased to announce tech preview release of terraform-provider-nutanix. 

You can see it linked off as a community provider (for now) on terraform's site, here: https://www.terraform.io/docs/providers/type/community-index.html or get to the repo, here: https://github.com/nutanix/terraform-provider-nutanix
