### ISSUE TITLE
Improve error message when output is missing closing brace

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#5929]
Given a TF config like this:

``` tf
# ^^ .... potentially lots of config above
output "noclosebrace" { value = "ohno"
```

Terraform produces a omewhat obtuse error message:

```
Error loading config: Error parsing /tmp/noclose/main.tf: object expected closing RBRACE got: EOF
```

Found this because - it turns out - TF versions .12 and earlier were silently ignoring missing closing brace  problems.

**Comment by mitchellh** [comment]
This is fixed!

**Comment by pricoppd** [comment]
how did you fix it?

**Comment by jensbodal** [comment]
Not sure if asking how they fixed it in the code (linking to a PR) or how you fix it if you see the error.  If it's the latter, you should see an error now like: 

```
... At 16:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

The `expected` is a union of the expected values, the `got` is what it found.

```
locals {
  tags = "${map("Foo", "Bar")}"
  }
}

$ terraform plan
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /directory/terraform/locals.tf: At 16:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

In this case it's telling me it found an `RBRACE` where it should have found one of `IDENT | STRING | ASSIGN | LBRACE`.
