### ISSUE TITLE
Feature: Print actions in progress during apply

### ISSUE THREAD

**Issue by glasser** [hashicorp/terraform#5932]
During a long apply with many resources being affected, it can be hard to tell what's actually going on.  To figure out what resources are currently being created, modified, or destroyed you have to scan the entire output and ignore whatever has had its "complete" message already.

I think UiHook should (optionally? by default? with configurable timeout?) print messages reminding you what's in progress every so often.  eg, if it's been 10 seconds since the last message of any sort printed, it should print a reminder of what resources are currently in progress.  (A simpler version would be to just print the message every 10 seconds no matter what, but I think it's a little nicer if it only shows up when terraform is otherwise idle.)

UiHook already tracks these resources in its `resources` map.  All that's required is to create a goroutine that prints in the background from... somewhere, I'm not sure where. (I'm not even quite sure where the UiHook comes from: there's one constructed in `command.Meta.contextOpts` and one in `command.Config.ContextOpts`... but maybe the latter is dead code?)

**Comment by radeksimko** [comment]
I remember @mitchellh was mentioning at the last London HUG meetup that he plans to work on this.

------

I suggested it should not be as simple as `Still creating resource x.y.z` but instead the resource should be able to report the real state back to the UIHook where applicable - e.g. RDS instance can be in 3 states during the 20-30mins of creation process (pending, creating, backing-up, ...).

I assume this would require a more changes in the core though, it would be hard to introduce without breaking provider plugin interface and I'm not sure if the value is worth it.

**Comment by mitchellh** [comment]
@radeksimko I think we start with the simple approach, since we can do that for free without any core changes right now. Otherwise its probably a pretty deep core change.

**Comment by glasser** [comment]
See https://github.com/hashicorp/terraform/pull/6032

**Comment by stack72** [comment]
Hi @glasser 

This has been closed in #6163 :)

Paul
