### ISSUE TITLE
Terraform vsphere provider custom_configuration_parameters

### ISSUE THREAD

**Issue by dkalleg** [hashicorp/terraform#5933]
Hi,

Looking for a little guidance on the custom_configuration_parameters attribute in vsphere resource_vsphere_virtual_machine.go.  I haven't found any documentation on what parameters this supports.  I've tried digging through the govmomi repo for whats expected and I've only discovered that it takes any generic key/value.  I've tried giving various entries, with no luck.  

I've tried giving direct vmx options, hoping it would act as a pass through.  I've tried giving govmomi interface naming schemes, such as "BootOptions.EnterBIOSSetup" = "True".  I notice that if my key has a dot in it, the value does not get picked up; the Terraform stdout shows an empty string where "True" should be.  If I don't have a dot in my key, the Terraform stdout properly shows my value.

Example:
    custom_configuration_parameters {
        "guestOS" = "otherlinux-64"
        "BootOptions.EnterBIOSSetup" = "TRUE"
        "sata0:0.present" = "TRUE"
        "sata0:0.deviceType" = "cdrom-image"
        "sata0:0.fileName" = "/vmfs/volumes/56f1c547-fcf062b8-a79c-40a8f04fd22b/ISO/ubuntu-14.04.3-server-amd64.iso"
    }

yeilds:

```
$ ~/Downloads/terraform_0.6.14_darwin_amd64/terraform apply
vsphere_folder.dans_tf_folder: Creating...
  existing_path: "" => "<computed>"
  path:          "" => "dans_tf_folder"
vsphere_virtual_machine.dans_terraform_vm2: Creating...
  custom_configuration_parameters.#:                          "" => "5"
  custom_configuration_parameters.BootOptions.EnterBIOSSetup: "" => ""
  custom_configuration_parameters.guestOS:                    "" => "otherlinux-64"
  custom_configuration_parameters.sata0:0.deviceType:         "" => ""
  custom_configuration_parameters.sata0:0.fileName:           "" => ""
  custom_configuration_parameters.sata0:0.present:            "" => ""
  disk.#:                                                     "" => "1"
  disk.0.size:                                                "" => "16"

```

Thanks,
Dan

Terraform Google Groups link:
https://groups.google.com/forum/#!topic/terraform-tool/JoTvqaVgeco

**Comment by chrislovecnm** [comment]
@dkalleg this is going to be limited to what the vsphere go api supports.  What is your specific question?  If we can turn this into more documentation it would be GREAT!!

**Comment by dkalleg** [comment]
More specific question: Is it possible to use the custom_configuration_parameters field that exists in Terraform today to add a cdrom drive to a vm definition.  If so, how?

**Comment by chrislovecnm** [comment]
@dkalleg actually not sure. I am guessing no. But that is only a guess. Here is more about the custom configurations http://blogs.vmware.com/vsphere/2012/03/acessing-virtual-machine-advanced-settings.html

Look at how to add the CD-ROM using https://github.com/vmware/govmomi/tree/master/govc that is the command line version of the API that this provider is based on.

Why isn't the cd-rom in the image? What exactly are you trying to do?

**Comment by chrislovecnm** [comment]
@dkalleg can you and @kristinn work this out??  Happy to give my two cents worth.  READY, SET, GO!!!!

**Comment by chrislovecnm** [comment]
@dkalleg are we ready to close this?

**Comment by dkalleg** [comment]
Sure
