### ISSUE TITLE
Changing aws_elb internal state when ELB has an associated aws_proxy_protocol results in broken state

### ISSUE THREAD

**Issue by nosmo** [hashicorp/terraform#5934]
When changing the state of an `aws_elb` object with an associated `aws_proxy_protocol` object, the `apply` will successfully change the internal state of the `aws_elb` object without issue. Subsequent applies will attempt to update the configuration of the associated `aws_proxy_protocol`s from a null configuration to the desired state, which seems to indicate that the reconfigured elb no longer has a proxy protocol configured. This change will fail as it seems there is no existing associated proxy protocol after the `internal` change: 

```
* aws_proxy_protocol_policy.my_extlb: Error setting policy for backend: PolicyNotFound: There is no policy with name TFEnableProxyProtocol for load balancer my-elb
        status code: 400, request id: 981a012d-f6c1-11e5-aae6-4bff236498
```

Editing the terraform.tfstate file to remove the corresponding `aws_proxy_protocol` entries results in the creation of the proxy protocol rules and a successful apply, with the final tfstate file's `aws_proxy_protocol` entries being identical to the ones present when the apply was failing to locate the TFEnableProxyProtocol entries.

**Comment by stack72** [comment]
Hi @nosmo 

Apologies for the issue here. Thanks for reporting it. In order to help debug it, could you provide the terraform config that is causing you pain? Please exclude any secrets from it. This will allow us to run your scenario and see where the issue may lay

Thanks

Paul

**Comment by nosmo** [comment]
The core of the config is the following: 
```
resource "aws_elb" "myelb" {
  name = "myelb-a"
  internal = false
 
  listener {
    instance_port = 80
    instance_protocol = "tcp"
    lb_port = 80
    lb_protocol = "tcp"
  }
 
  listener {
    instance_port = 443
    instance_protocol = "tcp"
    lb_port = 443
    lb_protocol = "tcp"
  }
 
  cross_zone_load_balancing = false
}
resource "aws_proxy_protocol_policy" "myproto" {
  load_balancer = "${aws_elb.myelb.name}"
  instance_ports = ["80", "443"]
}
```

Setting `internal = true` will produce the behaviour described in the initial ticket. 
Thanks!

**Comment by plombardi89** [comment]
Just ran into this as well. Had to go grab the TF state file out of S3. Remove the offending JSON and then re upload. Annoying

**Comment by cpoole** [comment]
ran into this today as well. 

here is a portion of the tfstate file that is causing the problem:

```
"aws_proxy_protocol_policy.internal_apps_elb_proxy_protocol": {
                    "type": "aws_proxy_protocol_policy",
                    "depends_on": [
                        "aws_elb.internal_apps_elb"
                    ],
                    "primary": {
                        "id": "internal-apps-prod-elb:TFEnableProxyProtocol",
                        "attributes": {
                            "id": "internal-apps-prod-elb:TFEnableProxyProtocol",
                            "instance_ports.#": "0",
                            "load_balancer": "internal-apps-prod-elb"
                        }
                    }
                },
```

terraform spits out the error:
```
Error applying plan:

1 error(s) occurred:

* aws_proxy_protocol_policy.internal_apps_elb_proxy_protocol: Error setting policy for backend: PolicyNotFound: There is no policy with name TFEnableProxyProtocol for load balancer internal-apps-prod-elb
	status code: 400, request id: 8ca93248-4406-11e6-a67a-83b11763edec

```

**Comment by zot24** [comment]
I'm experiencing the same issue here

```
Error applying plan:

1 error(s) occurred:

* aws_proxy_protocol_policy.global: 1 error(s) occurred:

* aws_proxy_protocol_policy.global: Error setting policy for backend: PolicyNotFound: There is no policy with name TFEnableProxyProtocol for load balancer api-elb-https-public
	status code: 400, request id: b913281e-46fd-11e7-b74e-953bc0f013cb
```
