### ISSUE TITLE
Copy file provisioner for windows vm in azure going to connection timeout.

### ISSUE THREAD

**Issue by sanjaykumarswarnkar** [hashicorp/terraform#5943]
I am trying to start a "Windows Server 2012 R2 Datacenter, November 2015" VM in azure, the vm is getting started but if I try to copy a file it is throwing this error. After looking over various posts regarding this I came to know its a firewall issue in the vm, is there a way to add an exception without manual intervention because then whole point of automating infrastructure will be gone.

Error applying plan:
1 error(s) occurred:
- unknown error Post http://13.91.102.162:5985/wsman: dial tcp 13.91.102.162:5985: getsockopt: connection timed out

**Comment by stack72** [comment]
Hi @sanjaykumarswarnkar 

Please can you share the config that you are using to build this VM? This will help us try and track down the issue you are encountering. Please remove any secrets from the configuration :)

Thanks

Paul

**Comment by sanjaykumarswarnkar** [comment]
[config.txt](https://github.com/hashicorp/terraform/files/197492/config.txt)

**Comment by sanjaykumarswarnkar** [comment]
HI @stack72 
please find the attached config file

**Comment by sanjaykumarswarnkar** [comment]
[config.txt](https://github.com/hashicorp/terraform/files/197514/config.txt)

**Comment by sanjaykumarswarnkar** [comment]
[config.txt](https://github.com/hashicorp/terraform/files/197518/config.txt)
