### ISSUE TITLE
vsphere crash

### ISSUE THREAD

**Issue by deasmi** [hashicorp/terraform#5945]
crash.log here [GIST](https://gist.github.com/deasmi/c8ce2d6e23a8a3385bfce6153f8d3d8b)
Running latest 0.6.14

Recently rebooted vcenter server and had a few SSO issues, which are now fixed for vsphere client at least, but this looks to be past logon stage to my uneducated eyes.

**Comment by deasmi** [comment]
If it's any help I have confirmed the the credentials used are able to logon via vsphere console and operate on all objects.

**Comment by deasmi** [comment]
So after a reboot of underlying ESXi host as well this no longer occurs. Not sure what to do here, should I close this or not ?

There is clearly a 'bug' but may only happen if vSphere throws something odd back which I suspect is what was happening.

**Comment by chrislovecnm** [comment]
@deasmi PLEASE keep this open.  This is a bug that needs to be fixed!

**Comment by chrislovecnm** [comment]
@stack72 can I get a low hanging fruit and P2 tag??

**Comment by stack72** [comment]
@chrislovecnm huh? We don't have priority tags

**Comment by chrislovecnm** [comment]
@stack72 lol ... Insert rimshot... most projects do

**Comment by chrislovecnm** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/7031 when it is merged
