### ISSUE TITLE
vpc_peering_status of deleted doesn't get re-created.

### ISSUE THREAD

**Issue by ashb** [hashicorp/terraform#5946]
I deleted a VPC peering connection and now terraform thinks its still okay. The state file looks like this (edited to remove tags and ids):

```json
                "aws_vpc_peering_connection.build_system": {
                    "type": "aws_vpc_peering_connection",
                    "depends_on": [
                        "aws_vpc.default"
                    ],
                    "primary": {
                        "id": "pcx-c1ae7da8",
                        "attributes": {
                            "accept_status": "deleted",
                            "auto_accept": "true",
                            "id": "pcx-c1ae7da8",
                            "peer_owner_id": "**",
                            "peer_vpc_id": "vpc-**",
                            "tags.#": "0",
                            "vpc_id": "vpc-***"
                        }
                    }
                },
```

It seems there's no way to get terraform to recreate this whilst the stat is "deleted" in AWS still.

**Comment by catsby** [comment]
Thanks @ashb — I've patched this in #5959 which was just merged, it should go out in the next release!

**Comment by ashb** [comment]
Thanks for speedily protecting me against my own stupidity :D

**Comment by catsby** [comment]
> Thanks for speedily protecting me against my own stupidity :D

Not you at all! Terraform should behave the way you were expecting, but it wasn't. Thanks for bringing it to our attention!
