### ISSUE TITLE
aws_iam_policy_attachment singleton

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#5947]
The docs say the following about iam policies being attached to roles:

```
NOTE: The aws_iam_policy_attachment resource is only meant to be used once for 
each managed policy. All of the users/roles/groups that a single policy is being attached
 to should be declared by a single aws_iam_policy_attachment resource.
```

This kind of messes with the workflow when you have a heavily modularized setup.   As an example, if I have a set of "standard" iam policies that need to be applied to every box in the environment (for example, things required for box buildup and tear-down etc), every time I instantiate a module, I will need to remember to add that specific module instance into the "roles" list for the aws_iam_policy_attachment line.   If I could just include the aws_iam_policy_attachment config _inside_ the module, then for each module instance the additional roles would automatically pick up the policies.   

I am currently using in-line policies to work around this, but it would definitely be nice to be able to have this laid out a bit more "modularly".

Thanks!

**Comment by ctso** [comment]
The fact that Terraform actually allows you to use multiple `aws_iam_policy_attachment` resources is a bit concerning as well.  This can end up being very destructive.  In the event that you have two policy attachment resources managing the same `policy_arn`, they basically end up fighting with each other and causing permadiffs.

Is there any reason to actually allow this behavior?
