### ISSUE TITLE
Dependencies while destroying and re-applying are not calculated correctly when using AWS

### ISSUE THREAD

**Issue by yahyapo** [hashicorp/terraform#595]
I built a stack with a VPC and subnets on AWS. On renaming a module which created a subnet, terraform plan showed that it would delete the existing subnet and create another one with the same CIDR range.

Expectation : The already existing subnet is deleted first and then the new one is created.

Actual Result : Terraform messes up the dependencies and tries to create a new subnet before deleting the existing one which gives "Error creating subnet: The CIDR '10.2.10.128/25' conflicts with another subnet (InvalidSubnet.Conflict)"  error.

**Comment by mitchellh** [comment]
This is fixed.

**Comment by yahyapo** [comment]
Thanks much!!
