### ISSUE TITLE
Syntax error on passing module output variables to another module

### ISSUE THREAD

**Issue by geriBatai** [hashicorp/terraform#5951]
If one module's output is passed as a variable to another module, modifying this output causes syntax error:

```
$ terraform plan
Error configuring: 1 error(s) occurred:

* strconv.ParseInt: parsing "${length(split(\",\", var.fail))}": invalid syntax
```

However, if variables are set to the same value directly for the module, there's no error reported. 

Sample repository: [geriBatai/terraform_module_fail](https://github.com/geriBatai/terraform_module_fail)

```
$ terraform version
Terraform v0.6.12
```

**Comment by jmfuchs** [comment]
+1
v0.6.14

**Comment by RevCBH** [comment]
+1
v0.6.14
v0.6.15-dev (c280d621892be81b99724e3cf86eb6a6e1a84731)

**Comment by RevCBH** [comment]
It only appears to fail for me on the count property. For example, when I make a change like this it works:
```
resource "aws_route" "peer" {
    count = "1"
    //count = "${length(split(",", var.target_cidr_blocks))}"
    route_table_id = "${var.route_table_id}"
    destination_cidr_block = "${element(split(",", var.target_cidr_blocks), count.index)}"
    vpc_peering_connection_id = "${aws_vpc_peering_connection.peer.id}"
}
```

It also turns out that the `var.target_cidr_blocks` variable isn't an output from another module here, so I might be seeing a different issue.

**Comment by RevCBH** [comment]
The error I'm seeing originates here: https://github.com/hashicorp/terraform/blob/master/config/config.go#L198

Instead of an integer string, it's still the whole interpolation expression, in this case `${length(split(",", var.target_cidr_blocks))}`

**Comment by RevCBH** [comment]
Here's a trace of all the goroutines running when the error occurs. I can't seem to get anything from debug.PrintStack() inside of this particular thread of execution.

[trace.txt](https://github.com/hashicorp/terraform/files/228331/trace.txt)

**Comment by mitchellh** [comment]
Dup of #3888 going to centralize resources there.
