### ISSUE TITLE
AWS Opsworks Stack - Unable to create Linux Chef 12 stacks

### ISSUE THREAD

**Issue by smckim** [hashicorp/terraform#5958]
Similar issue to #5905 
Opsworks stacks are initially created with a lot of default values, and then updated afterwards with values specified in the configuration file. Stacks are initially created with the default  configuration_manager_version of Chef 11.4, which **cannot** be upgraded in Opsworks to Chef 12, causing terraform apply to fail.

**Comment by optimisticanshul** [comment]
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_opsworks_stack.go#L65

@smckim i think here we are passing 11.4 that is causing this bug

**Comment by apparentlymart** [comment]
This is also related to #5569

**Comment by tommyorndorff** [comment]
Is there any way to work around this?  I need to port over chef 12 opsworks stacks from cloudformation to terraform using amazon linux 2013.03.

**Comment by smckim** [comment]
My work around was to create the stack in the console first and then manually edit the tfstate file with the values from the stack I created (which matched the values I had in my aws_opsworks_stack resource configuration). Further updates on the stack work fine, it's just the initial creation of the stack with terraform that currently doesn't work.

**Comment by vinyar** [comment]
As a work around:
Since instances already come with chef 11.x you can add omnibus updated cookbook to your runlist and upgrade chef-client as part of the chef run
https://github.com/hw-cookbooks/omnibus_updater

**Comment by stack72** [comment]
Closed with #6244
