### ISSUE TITLE
Feature: refresh new resources during same apply where applicable

### ISSUE THREAD

**Issue by RyanBowlby-Reflektion** [hashicorp/terraform#5960]
An `aws_route53_record` resource may wish to use the .public_dns attribute of an aws_instance. However, that attribute is changed or populated AFTER an aws_eip resource is associated with the instance and TF is none the wiser of this change.

feature as pseudo ¯_(ツ)_/¯

``` python
if aws_eip resource exists AND is associated with aws_instance resource then
  refresh the aws_instance attrs/object (have valid public_dns on instance)
fi
```

Having something like the above occur prior to terraform continuing the `apply` would allow the `aws_route53_record` to continue without error. Here's the existing error from lack of the public_dns attr:
- aws_route53_record.elasticsearch.1: InvalidChangeBatch: Invalid Resource Record: FATAL problem: DomainNameEmpty encountered at 
  status code: 400, request id: 67278509-f76c-11e5-bee1-519728f467d4
- aws_route53_record.elasticsearch.0: InvalidChangeBatch: Invalid Resource Record: FATAL problem: DomainNameEmpty encountered at 
  status code: 400, request id: 67275e49-f76c-11e5-82aa-5f00669ffac0

I've been running terraform apply twice to work around this error for nearly a year. This is somewhat less ideal now that I'm attempting to use Atlas.

**Comment by srjturner** [comment]
+1. Any reference to the public_dns of an instance that has an associated eip is broken. Is there any workaround to get the (post-association) public_dns?
