### ISSUE TITLE
Enable online resizing of Persistent Disks in GCE

### ISSUE THREAD

**Issue by iiro** [hashicorp/terraform#5968]
Google has just announced that the resize (grow) operation of Persistent Disks is now GA and not in beta anymore:

https://cloudplatform.googleblog.com/2016/03/introducing-Google-Cloud-Persistent-Disks-with-non-disruptive-online-resizing.html

Would be neat to have this supported in Terraform as well.

**Comment by thuck** [comment]
Any news on this? Could I help in some way? Or there anyone already working on this?
