### ISSUE TITLE
provider/aws: Add support for OpsWorks Apps

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#5970]
Hello, per issue #28, I'm creating a new issue request.

OpsWorks preliminary support was already in the v0.6.x release, but it's missing critical api coverage to make it useful. IMHO ultimate coverage would include: stack, layers, instances and apps creation. This way, Terraform manages the infrastructure, and separately a CI environment can simply use the AWS create-deployment hook when builds pass.

Dependencies: 

- [x] OpsWorks Stacks and Layers - @apparentlymart gracously added these back in https://github.com/hashicorp/terraform/pull/2162
- [ ] OpsWorks Instances - Open PR lingering here: https://github.com/hashicorp/terraform/issues/3459 ( @phinze any update to having that merged?)
- [ ] OpsWorks Apps - Found open PR here https://github.com/hashicorp/terraform/pull/4419

:+1:

**Comment by janschumann** [comment]
Are you already working on OpsWorks Apps? Unfortunately I have missed this issue and started to work on it also. https://github.com/finanzcheck/terraform/tree/opsworks_apps

Want to work on this together?

**Comment by u2mejc** [comment]
How in the world did you find that? I must not have broaden my search to include "applications" and with no discussion, I'm sure it wouldn't be high in the results anyways.

@janschumann I'd be happy to work together on this but I guess we should work with the existing PR if it's feature complete. I'll try rebasing it, but I'd like to rename it to aws_opsworks_app, mirroring your branch. I'm not fixated on the resource name, but it eases use (and SEO) when the naming matches the AWS's use and I'm not keen to terraform renaming some functions.

> Are you already working on OpsWorks Apps? Unfortunately I have missed this issue and started to work on it also. https://github.com/finanzcheck/terraform/tree/opsworks_apps

> Want to work on this together?

> Hm. Found an open PR on that task: #4419

**Comment by janschumann** [comment]
Check. Let me know if you get the rebase work. I gave it a quick try with conflicts in base aws provider sources...

**Comment by u2mejc** [comment]
@janschumann I pulled down the PR, was able to rebase it (only one line collision was in builtin/providers/aws/provider.go, the list of resources has changed significantly in the last few months). I've posted a patch for @odise in his PR so he can get the cred for his hard work and get the PR to compile against master today. :smile:

**Comment by janschumann** [comment]
I´ll keep working on my own branch. At least for my education :-)

**Comment by odise** [comment]
Guys feel free to work on this PR. I won't continue it as I'm currently working on other topics.

**Comment by janschumann** [comment]
@odise Ok. Thanks for adding me to your fork!

**Comment by janschumann** [comment]
@odise @u2mejc #4419 is now squashed and rebased. please let me know if i can do anything to get it merged. i would also like to discuss improvements/enhancements for this resource.

**Comment by u2mejc** [comment]
Thx @odise :+1:

**Comment by u2mejc** [comment]
Awesome work @janschumann Let's talk about enhancements here too.

Hopefully we can get #3459's support meged about the same time too.

**Comment by apparentlymart** [comment]
#4419 and #3459 are merged now, so I think this issue is resolved... let me know if I missed something else in the comments!

**Comment by u2mejc** [comment]
Thank you Martin!!!
