### ISSUE TITLE
Add CoreOS Fleet provider

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#5974]
Terraform now supports Docker provider (which I think _should_ work also as scheduler w/ Docker Swarm) and ECS, Kubernetes is WIP and Fleet is another scheduler by CoreOS:

https://coreos.com/fleet/docs/latest/api-v1.html
https://github.com/coreos/fleet/tree/master/api

I'm creating this issue to track the interest.

**Comment by robholland** [comment]
Fleet is now in maintenance mode and won't be developed further so it may not be worth supporting.

**Comment by radeksimko** [comment]
@robholland can you provide any more details/links supporting this?

**Comment by robholland** [comment]
Sure: https://github.com/coreos/fleet/blob/master/README.md#current-status

**Comment by philips** [comment]
Fleet is deprecated, this should be closed.
