### ISSUE TITLE
Subnet couldn't be deleted due working Auto Scaling Group

### ISSUE THREAD

**Issue by alexander-balashov** [hashicorp/terraform#5977]
**Reproduction steps**

1. Deploy infrastructure
1. Change config for networking resource that has bound to Auto Scaling Group (ASG) resource. For example: Change CIDR block at Subnet
1. Try to update infrastructure

**Executed result**

Infrastructure should be successfully updated

**Actual result**

Deployment failed

**Research results**
Terraform marks Subnet for deleting and ASG for modification. But Subnet resource can't be deleted since ASG still uses Subnet resource.

Terraform v0.6.11

Log: 

```
.......
aws_subnet.zone2: Destroying...
aws_subnet.zone1: Destroying...
Error applying plan:

2 error(s) occurred:

* aws_subnet.zone2: Error deleting subnet: timeout while waiting for state to become '[destroyed]'
* aws_subnet.zone1: Error deleting subnet: timeout while waiting for state to become '[destroyed]'
.......
```

**Comment by catsby** [comment]
Hey @alexander-balashov – I believe adding the `create_before_destroy` lifecycle block to your Subnet should do the trick:

```hcl
resource "aws_subnet" "tf_test_subnet" {
  [....]
  lifecycle {
    create_before_destroy = true
  }
}
```

This will instruct Terraform to create a new Subnet before destroying the old one, allowing Terraform to then update the ASG and other dependencies with the new Subnet information, removing the dependency, and allowing destruction of the old one.


Let me know if you have any other questions!
