### ISSUE TITLE
azurerm dns zone should include apex ns record set values in attributes

### ISSUE THREAD

**Issue by cmsd2** [hashicorp/terraform#5980]
In order to create a subdomain and delegate to it with an ns record it's necessary to get the subdomain's apex ns record set and to put those 4 returned dns servers in an ns record in the parent zone.

There's no way to get those apex ns records for a zone using terraform at the moment.

The azure rm rest api only returns the bare minimum info about a given zone and is probably why this hasn't been implemented so far.
This would require an additional rest api call e.g. in resourceArmDnsZoneRead, to explicitly ask for details of the implicitly created apex ns record, and to add the results to the zone's attributes.

The aws provider has this info and shows how it might look to users.

**Comment by stack72** [comment]
Hi @cmsd2 

This was added in https://github.com/hashicorp/terraform/pull/7434

Paul
