### ISSUE TITLE
[aws] terraform destroy - InvalidGroup.InUse

### ISSUE THREAD

**Issue by radekg** [hashicorp/terraform#5982]
Using the latest terraform for OSX for some testing on aws - v.0.6.14. Doing `terraform destroy` leaves me with `InvalidGroup.InUse: There are active instances using security group XYZ`. Sounds logical but what I do not understand is why does it not try removing instances first?

I have this infra configured similar to:

```
aws_security_group "some_group" {
  name "some_group"
  ...
}

aws_instance "..." {
  security_groups = ["${aws_security_group.some_group.name}"]
  ...
}
```

`apply` works perfect, `destroy` not so much. Am I missing something? Surely the order of destroying should be the reverse of creating.

The current state means that I can simply forget `destroy`. Any hints?

**Comment by jmfuchs** [comment]
Similar issue with v0.6.14.  Running into an error when doing a destroy on a VPC with NACL's.  The NACL shows as being destroyed but then never gets destroyed and results in the VPC destruction failing due to dependencies.  After if I run 'terraform plan -destroy' it shows the VPC as the only resource existing even though the NACL still exists which is causing the destroy to fail.

Any advice?

Thanks!

**Comment by catsby** [comment]
Hey @radekg – I don't believe you're missing anything, Terraform should destroy the instances first. 

Unfortunately I can't reproduce this without more information. I tried the following configuration:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "default" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true

  tags {
    Name = "default"
  }
}

resource "aws_subnet" "tf_test_subnet" {
  vpc_id                  = "${aws_vpc.default.id}"
  cidr_block              = "10.0.0.0/24"
  map_public_ip_on_launch = true

  tags {
    Name = "tf_test_subnet"
  }
}

resource "aws_security_group" "tf_test_sg_ssh" {
  name        = "tf_test_sg_ssh"
  description = "tf_test_sg_ssh"
  vpc_id      = "${aws_vpc.default.id}"

  ingress {
    from_port   = 0
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    self        = true
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "tf_test_sg_ssh"
  }
}

resource "aws_instance" "tf_test" {
  ami = "ami-260c1f47"
  count = 3
  subnet_id = "${aws_subnet.tf_test_subnet.id}"
  instance_type   = "t2.micro"
  #security_groups = ["${aws_security_group.tf_test_sg_ssh.id}"]
  vpc_security_group_ids = ["${aws_security_group.tf_test_sg_ssh.id}"]

  tags {
    Name = "terraform test"
  }
}
```

This configuration spins up 3 instances in a security group. All of `plan`, `apply`, and `destroy` complete for me with no problem. 

Note too the use of `vpc_security_group_ids` over `security_groups`. If you're on EC2 Classic, you can use `security_groups`; `vpc_security_group_ids ` should be used if you're using a VPC.

Do you by chance have a full configuration (minus any secrets) that reproduces this?

**Comment by radekg** [comment]
Along the lines of:

```
variable "infra_name" {
  default = "test_infra"
}
variable "bootstrap_port" {
  default = "10000"
}
variable "ami_id" {
  default = "ami-7abd0209"
}

resource "aws_security_group" "ssh_access" {
  name = "${var.infra_name}_ssh_access"
  description = "Allow all ssh access"
  ingress {
      from_port = 22
      to_port = 22
      protocol = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "bootstrap_http" {
  name = "${var.infra_name}_bootstrap_http"
  description = "Bootstrap machine HTTP access"
  ingress {
      from_port = "${var.bootstrap_port}"
      to_port = "${var.bootstrap_port}"
      protocol = "tcp"
      security_groups = ["${aws_security_group.master.name}", "${aws_security_group.agent.name}"]
  }
}

resource "aws_security_group" "master_tag" {
  name = "${var.infra_name}_master_role"
  description = "Master machines - ref only"
}

resource "aws_security_group" "master" {
  name = "${var.infra_name}_master"
  description = "Master machines"
  ingress {
    from_port = 2181
    to_port = 2181
    protocol = "tcp"
    security_groups = ["${aws_security_group.agent.name}"]
  }
  ingress {
    from_port = 2888
    to_port = 2888
    protocol = "tcp"
    security_groups = ["${aws_security_group.agent.name}"]
  }
  ...
}

resource "aws_security_group" "agent" {
  name = "${var.infra_name}_agent"
  description = "Agent machines"
  ingress {
    from_port = 5051
    to_port = 5051
    protocol = "tcp"
    security_groups = ["${aws_security_group.master_tag.name}"]
  }
}

resource "aws_instance" "bootstrap" {
  ami = "${var.ami_id}"
  instance_type = "m3.medium"
  tags {
    Name = "${var.infra_name}_bootstrap"
  }
  security_groups = ["${aws_security_group.ssh_access.name}", "${aws_security_group.bootstrap_http.name}"]
}

resource "aws_instance" "master_node" {
  count = 1
  ami = "${var.ami_id}"
  instance_type = "m3.medium"
  tags {
    Name = "${var.infra_name}_master_node-${count.index}"
  }
  security_groups = [ "${aws_security_group.ssh_access.name}",
                      "${aws_security_group.master_tag.name}",
                      "${aws_security_group.master.name}" ]
  provisioner "remote-exec" {
    inline = [
      "echo ${aws_instance.bootstrap.private_ip} >> /etc/expected-bootstrap-ip",
      "echo ${self.count} >> /etc/expected-master-count"
    ]
  }
}

resource "aws_instance" "agent_node" {
  count = 3
  ami = "${var.ami_id}"
  instance_type = "m3.medium"
  tags {
    Name = "${var.infra_name}_master_node-${count.index}"
  }
  security_groups = [ "${aws_security_group.ssh_access.name}",
                      "${aws_security_group.agent.name}" ]
  provisioner "remote-exec" {
    inline = [
      "echo ${aws_instance.bootstrap.private_ip} >> /etc/expected-bootstrap-ip",
    ]
  }
}
```

I wonder, is it possible that the existence of the machines was not recognised until the provisioner is successfully executed?

**Comment by radekg** [comment]
As I explicitly do not set any connection properties for provisioners. Just wanted to see if my machines come up and if the provisioner actually, at least, attempts talking to my machines. However, the provisioner was not able to get access to the boxes. It still looks like a "bug" of some sort to me. At least fail creating machines if provisioner connection settings are required.

I have an idea for how the dependency resolution for aws security groups could be improved. Is a github issue sufficient?

**Comment by radekg** [comment]
Hi @catsby. I've managed to confirm that this is due to the provisioner not running on the machine. Once the provisioner successfully finishes, `destroy` works perfectly fine. However, I believe the process should be slightly more lenient and the existence of the machines should be somehow recognised before the provisioner attempts the run. The reason is that subsequent `apply` calls destroy machines which were not provisioned to attempt provisioning.

So, to clarify:

 - `terraform apply`: creates all security groups, creates machines, provisioner tries but fails because of no key / error in the provisioning code
 - `terraform apply`: running again; all machines which failed provisioning are terminated and relaunched; provisioner fails again
 - `terraform destroy`: fails with the original error

The process could be refined a bit more:

If `terraform apply` was not able to even start provisioning, the existence of the machines should be checked on next run, with the recorded fact that provisioning was not attempted. In such case, only provisioning should be attempted as the machine is for sure in a clean state. Terminating machines and relaunching can be very expensive stunt and in some cases, like SoftLayer, a very, very long painful process.

With regards, to relaunching if **the provisioner fails**. I am not quite sure if the decision to simply relaunch machines os based on trusting the user creating idempotent provisioning programs? Generally, a very simple mistake in one of the provisioning programs may result is a very expensive terraform recovery process.

The pressure should be put on operators providing idempotent provisioning programs and trying to recover by simply relaunching machines.

Thoughts? Questions?

**Comment by radekg** [comment]
Furthermore, if the provisioner never attempts connecting (CTRL+C before it tries the first time), the subsequent `apply` will not even figure out that there are machines already up. In such case there is a huge risk that people have instances running without actually knowing about it.
