### ISSUE TITLE
Automatic Bug Reports

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#5983]
I had an issue with diffs, and terraform suggested filing an issue with some useful data.  Unfortunately this was for an EC2 instance with some very specific instance data that would create user accounts, etc.  I'm sure most of my user_data is safe enough to share, but it is a bit of a headache to scrub files, especially when the issue is a diff issue that has a lot of densely packed data.

What would be cool (asking for :cake: now...) is if the tool would 1. help you file an issue and 2. any potentially secure data was posted to some internal hashicorp place, and it was automatically cross referenced.

This is a bit of crash-reporting that can still maintain the usefulness of publicly viewable issues.

Meanwhile, maybe a word of caution regarding sensitive information should be added to the error output.

**Comment by pkolyvas** [comment]
Due to the age of this ticket, and the lack of having anything on our near or distant plans, I'm going to close this enhancement issue out. We're not likely to tackle it anytime soon unfortunately.
