### ISSUE TITLE
terraform equivalent to 'vagrant provision'?

### ISSUE THREAD

**Issue by pierrebonbon** [hashicorp/terraform#5989]
Is there currently an equivalent to `vagrant provision` in terraform? I'm using Salt to provision my machine when building infrastructure with terraform (with the `remote-exec` directive to install and run Salt) and oftentimes need to update files. I've resorted to destroying and building infrastructure each time I need to update some file, but I wish I could just update it.

**Comment by apparentlymart** [comment]
Thanks for the suggestion, @pierrebonbon! In #3193 this was discussed and agreed that this workflow makes sense, but nobody has had the time or interest to work on it yet. I'm going to close this issue for now to consolidate discussion in #3193; feel free to chime in over there if you want to share some details about your use-case that may help us to design that feature.

I just added [a comment](https://github.com/hashicorp/terraform/issues/3193#issuecomment-204771314) over there which shows a workaround that can be used for some situations in the mean time.

**Comment by pierrebonbon** [comment]
@apparentlymart thanks for the feedback and the workaround! I will try it out and will sure leave my comments there about my use-case.
