### ISSUE TITLE
Cannot create a google_compute_instance with no ephemeral IP address.

### ISSUE THREAD

**Issue by jharriman** [hashicorp/terraform#599]
Google Compute Engine allows instances to be created without assigning an ephemeral IP address (https://cloud.google.com/compute/docs/instances-and-network), but Terraform doesn't seem to support creating an instance without an external IP.  

Currently Terraform hard codes 1 access config when creating an instance, which forces us to assign an external IP address. (Thanks to Spark on IRC for hunting down the problem in the Terraform source)

Sometimes, we do not want instances to be addressable from the global internet. Terraform should allow us to remove the ephemeral IP address from newly created GCE instances.

**Comment by sparkprime** [comment]
@Phinze can close this now

**Comment by phinze** [comment]
:+1:
