### ISSUE TITLE
cannot set MAC address in network interface in vsphere provider

### ISSUE THREAD

**Issue by godfryd** [hashicorp/terraform#5992]
Currently it is only possible to set MAC address when one is deploying VM to vsphere.
We are using static DHCP where we allocate IP address to MAC address.
So we would need to be able to configure MAC address only on network interface.
The system will get IP from DHCP when it is booted.
Could you add support for that?

**Comment by chrislovecnm** [comment]
More info please

**Comment by godfryd** [comment]
What info is needed? Terraform is not able to set MAC address of deployed vm.

**Comment by chrislovecnm** [comment]
@godfryd every time I have used the plugin vSphere sets the mac address, not terraform.  So I don't understand why you are expecting or needing terraform to do this.  What is your exact use case?  Why do you expect terraform to set the MAC, when vSphere sets the mac, and then the DHCP server gives the vm a ip.  Are you guys using static MAC addresses??  This is an extreme edge case that is not supported.

Here are the docs for vSphere:

http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.networking.doc%2FGUID-1C9C9FA5-2D2D-48DA-9AD5-110171E8FD36.html

Here are the use cases:

- Generated MAC addresses
  - Assigned by vCenter Server
  - Assigned by the ESXi host
- Manually set MAC addresses
- Generated for legacy virtual machines, but no longer used with ESXi

--------

With all of that said I don't think that is your problem.... What are happening with the logs on vSphere and the vm.  As I mentioned please provide more information.

**Comment by chrislovecnm** [comment]
@stack72 this is not a enhancement request btw ... only a question.  I doubt that will will support static mac assignment.  But you never know ... do you.

**Comment by chrislovecnm** [comment]
@godfryd major edit on the last post, as I did not read 'STATIC MACS' in your issue.  My mistake.  At this point terraform provider does not have the capability to set a mac address.  If that is indeed your use case, please feel free to submit a PR.  You may want to verify that the underlying API supports that first.

Again sorry that I did not read your issue as well as I could.

**Comment by godfryd** [comment]
Yes, in our environment we are able to use only manually assigned MAC addresses. So we need terraform to control MAC addresses and preserve them when given virtual machine is being recreated. Otherwise we will be getting randomly generated MAC to the same VM.
