### ISSUE TITLE
Output multiple datum per instance in one `output` definition.

### ISSUE THREAD

**Issue by byrnedo** [hashicorp/terraform#5993]
Is there a way to output multiple pieces of information in an `output` variable for each node in a bunch of servers?  Can I use count?

My use case is that I want to output a generated command line for the user to use after `terraform apply` has finished. In my case it's a `docker-machine create` command with each server's ips and ssh details filled in. 

Basically something like this:

```
output "info" {
    value = "some-command --ip=${element(aws_instance.docker.*.public_ip, count)}  --private-ip=${element(aws_instance.docker.*.private_ip, count)}"
}

```

**Comment by mitchellh** [comment]
Please ask usage questions on the mailing list or via the chat rooms.

You can probably use `null_resource` for this.
