### ISSUE TITLE
[aws] remote-exec provisioner attempts connecting to private ip while launching to ec2 classic

### ISSUE THREAD

**Issue by radekg** [hashicorp/terraform#5997]
It happened second time in the last two days that terraform tried using private ip of an instance while executing remote-exec for a machine in ec2 classic. Not sure how to give more details except of the error I have:

```
Error applying plan:

1 error(s) occurred:

* dial tcp 10.103.130.240:22: i/o timeout

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by radekg** [comment]
```
variable "provisioner" {
  type = "map"
  default = {
    username = "centos"
    key_name = "centos-test"
    keys_dir = "/keys"
    directory = "/home/centos/provisioner"
  }
}

...

  connection {
    user = "${var.provisioner.username}"
    key_file = "${var.provisioner.keys_dir}/${var.provisioner.key_name}.pem"
  }
  provisioner "remote-exec" {
    inline = [
      "mkdir -p ${var.provisioner.directory}",
      ...
    ]
  }
```

To clarify: first `apply` tries to ssh to the private ip. It fails after timeout and a subsequent `apply` terminates the machine, after relaunch it goes into a correct public IP.

**Comment by don-code** [comment]
I've also hit this issue several times over the past few weeks. There appears to be some latency between an instance being launched and its public IP being assigned; if Terraform queries instance data when a public IP isn't yet available, it will take the instance's private IP address to also be its public IP.

I originally noticed this in the AWS console and attempted to capture `DescribeInstances` output immediately after launch (e.g. without the public IP), but so far haven't been able to consistently reproduce the latency.
