### ISSUE TITLE
cloud-config provider

### ISSUE THREAD

**Issue by mcuadros** [hashicorp/terraform#6002]
Currently I am using Terraform in a GCE with docker-swarm and coreos, I have many different cloud-config files, with copy pasted parts, because some they share bare things.

Instead of dealing with, error prone, raw files with variables being interpolate by a template resource, I am suggesting create a cloud-config provider to allow to create testable configurations.

Small example:
```tf
provider "cloud_config" {
	users = [
		"${cloud_config_user.foo.rendered}"
	]

    units = [
    	"${cloud_config_unit.consul.rendenred}"
    ]
}

resource "cloud_config_user" "foo" {
	name = "foo"
	groups = ["foo", "wheel"]
}

resource "cloud_config_unit" "consul" {
    description = "Consul Server"
    requires = ["docker.service"]
    after = ["docker.service"]

    service {
 	    exec_start_pre = [
    		"/usr/bin/docker kill consul",
    		"/usr/bin/docker rm consul",
    		"/usr/bin/docker pull gliderlabs/consul",
    	]

    	exec_stop = "/usr/bin/docker stop consul"
    	exec_start = "docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap"
    }
```

If this is interesting I am open to contribute to terraform with this provider.

**Comment by jen20** [comment]
Hi @mcuadros! It seems that much of what you want may already be in the [`cloudinit_config` resource](https://www.terraform.io/docs/providers/template/r/cloudinit_config.html)? I'll close this for now - but please feel free to reopen if the existing resource does not meet your needs. We'd be happy to review pull requests which improves the resource though!

**Comment by mcuadros** [comment]
@jen20 using `cloudinit_config` works with RAW text file, you can't validate the content, the only way is deploy and suddenly find that you forgot a space a slash or something. 

What I am suggesting is create a proper resource not a template system, following the specs of cloud-init

**Comment by mcuadros** [comment]
@jen20 ping
