### ISSUE TITLE
Add SWF to AWS Provider

### ISSUE THREAD

**Issue by aventurella** [hashicorp/terraform#6003]
Unless, I am just missing it, I do not see any reference to AWS SWF in the AWS provider.

**Comment by catsby** [comment]
Hey @aventurella – you are correct, Terraform does not (yet!) support AWS Simple Workflow Service. While we're constantly working to improve our provider coverage, some of them are vast and very detailed, so we're definitely not 100% on our coverage. 

We do actively try to keep up though, it's just a balance of maintaining our existing coverage and keeping up with changes, and adding to our coverage with additional resources. We do happily accept user contribution as well, so if yourself or someone else would feel like divining into a resource for SWF, we have a contributing guide here:

- https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md

We're also available for guidance in this process, either here on GitHub issues, or in IRC or our mailing list. Details on those can be found on our Community page:

- https://www.terraform.io/community.html

Thanks for writing in! I hope you can still find Terraform useful without SWF support

**Comment by aventurella** [comment]
No worries! I'm sure you have a list a 1000 miles long to get it, I just noticed it since I was setting up  some SWF things this morning, I can totally work around it. 

Thanks for building an awesome product!

**Comment by joekhoobyar** [comment]
+1

**Comment by gkhakare** [comment]
+1
