### ISSUE TITLE
Special handling for AWS elb security group

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#601]
The elb security group has the id amazon-elb/sg-843f59ed (amazon-elb-sg).
If i try to create a security group that references this id, it actually creates it fine. 
but each time i'll apply after that i'll get The security group 'sg-843f59ed does not exist'
what happens is that after a refresh, terraform will receive the id as sg-843f59ed  (and that will be in the state file), and that's when i'll get the error.

**Comment by catsby** [comment]
Hello – sorry for the silence. I assume this ELB security group exists independently of Terraform? 

> but each time i'll apply after that i'll get The security group 'sg-843f59ed does not exist'

What kind of changes or commands are you running to see this?

Could you possibly give me a bare-minimum configuration file that demonstrates this? Be sure to omit and sensitive secrets/keys. 

Thanks!

**Comment by catsby** [comment]
We haven't heard from you in a bit, so we're going to go ahead and close this. If you have any more information to help us debug or reproduce this, we can re-open it.

In the meantime, we have recently added a feature to the ELB resource regarding security groups, perhaps it's helpful:

- https://github.com/hashicorp/terraform/pull/1708

**Comment by scalp42** [comment]
I believe this is related to: https://github.com/hashicorp/terraform/issues/2420 @catsby 

AWS provides a generic "amazon-elb/amazon-elb-sg" when creating an ELB, not sure how to reference this with Terraform.
