### ISSUE TITLE
github_team: Support Team Privacy setting

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#6015]
Need to add support for `privacy` setting on Github Teams: https://developer.github.com/v3/orgs/teams/#create-team

/cc @JacobASeverson

**Comment by JacobASeverson** [comment]
+1 I can do this sometime this week if someone doesn't beat me to it.

**Comment by JacobASeverson** [comment]
Fixed by https://github.com/hashicorp/terraform/pull/6116

**Comment by JacobASeverson** [comment]
This can be closed out ^

**Comment by stack72** [comment]
Thanks for the reminder @JacobASeverson :)
