### ISSUE TITLE
Github Provider: Support API Rate Limiting

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#6016]
The Github API has a rate limit than can be easily overcome when managing an organization.
This ticket is simply a spot to start a conversation about how to properly handle the rate limit.

Details: https://developer.github.com/v3/#rate-limiting

**Comment by JacobASeverson** [comment]
If I'm reading this right we are authenticating with OAuth so the limit is 5,000/hour? Or is that not the case?

**Comment by apparentlymart** [comment]
In other providers the approach has been for Terraform to politely retry things for a while and then fail if they can't be dealt with in a reasonable amount of time (a few minutes, I think.)

This window-based rate limiting strategy doesn't really play well with our usual approach: if the limit is hit at 15 minutes after the hour, it's not reasonable for Terraform to pause for 45 minutes before completing the request. Instead, it'd be better for it to fail with an error message telling the user when to retry.

If the limit is indeed 5,000/hour then it's probably reasonable as a starting point to just handle this error response gracefully by giving a user-friendly error message. We could potentially have a special case for waiting if the reset time is less than 2min in the future, but that seems like it'd be rare enough to not be worth the extra complexity.

[Elsewhere in the docs](https://developer.github.com/v3/#conditional-requests) it's suggested that clients can use conditional GET requests and they won't count against the rate limit if `304 Not Modified` is returned; we could potentially store the resource etag as a computed resource attribute and use `If-None-Match` in our refresh requests, thus reducing Terraform's impact on hitting the rate limit. Unfortunately it looks like [the Github client library Terraform is using delegates conditional request handling to the `http.Transport` layer](https://godoc.org/github.com/google/go-github/github#hdr-Conditional_Requests), which means it'd probably take some significant hoop-jumping to use the Terraform state as the "cache" for it to read.

**Comment by JacobASeverson** [comment]
Thanks for the elaboration @apparentlymart. Recognizing a rate limit error and providing a more friendly message does indeed sound like a good starting point. I'll start looking at that as well as options for conditional GETs.
