### ISSUE TITLE
azurerm support availability set

### ISSUE THREAD

**Issue by majormoses** [hashicorp/terraform#6022]
Forgive my lack of knowledge and details on azure (just starting this journey) in order to create redundancy in a similar fashion as aws availability zones you need to create an availability set for each service you want to make HA.

**Comment by stack72** [comment]
Hi @majormoses 

We already support this

https://www.terraform.io/docs/providers/azurerm/r/availability_set.html

Please let me know if this is what you are looking for

Thanks

Paul

**Comment by majormoses** [comment]
@stack72 I think I somehow just missed it...sorry you can close...

**Comment by stack72** [comment]
Ah no worries at all :)
