### ISSUE TITLE
Accessing remote state as local file

### ISSUE THREAD

**Issue by stumyp** [hashicorp/terraform#6030]
I have multiple TF projects stored in a single Git repository.
They are independent environments, but sometimes it is required to share some values like IPs, instance names, etc.
I could have started publishing remote states to S3 or HTTP, but since they are all next to each other is it possible to use `remote_state` with provider `local_file` or something similar to avoid extra steps ?
Looks like simple implementation to me, comparing to all really remote state backends.

(Apologies if I missed it in the documentation, Google didn't find anything for me)

**Comment by stumyp** [comment]
ha, I found this in the source code:
```
var BuiltinClients = map[string]Factory{
        "atlas":       atlasFactory,
        "consul":      consulFactory,
        "etcd":        etcdFactory,
        "http":        httpFactory,
        "s3":          s3Factory,
        "swift":       swiftFactory,
        "artifactory": artifactoryFactory,

        // This is used for development purposes only.
        "_local": fileFactory,
}
```

What would be the downside of using `_local` backend for production ?

**Comment by stumyp** [comment]
related to https://github.com/hashicorp/terraform/issues/3618

**Comment by mitchellh** [comment]
Going to close this for #3618
