### ISSUE TITLE
aws_elastic_beanstalk_configuration_template.options not set since 9ae8e85

### ISSUE THREAD

**Issue by atward** [hashicorp/terraform#6035]
@catsby, https://github.com/hashicorp/terraform/commit/9ae8e85640f4a3f5faeb94ff7f96236b46758ba2 broke updates to aws_elastic_beanstalk_configuration_template.options

Code still refers to option_settings: https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/builtin/providers/aws/resource_aws_elastic_beanstalk_configuration_template.go#L135 More references throughout.

Test cases should be extended to test that options are set correctly.

**Comment by catsby** [comment]
Fixed in #6043 , sorry for this!
