### ISSUE TITLE
Problem with remote-exec from macOS

### ISSUE THREAD

**Issue by ecweaver** [hashicorp/terraform#604]
On MacBook, Mavericks, running Terraform 0.3.1, I successfully made an instance but then TF had trouble connecting.  I made a connection block in the resource, specifying user="ubuntu" and my key file. 
I traced it with dtruss to make sure it read the file, and saw it exchange version info, and then some gibberish, and then it said "handshake failed" and looped retrying.

Using the same template and key file from a linux AWS instance worked fine.
Lots more details upon request.

**Comment by mitchellh** [comment]
We no longer set the default host to localhost so this shouldn't happen anymore.
