### ISSUE TITLE
provider/aws: feature request: Add a aws_sns_topic_permission resource 

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#6042]
# What

Lambda functions have a resource [`lambda_permission`](https://www.terraform.io/docs/providers/aws/r/lambda_permission.html) to allow grant permissions to resources to invoke them.

We need the same for SNS, which behaves and exposes similar API the methods than lambda: [`AddPermission`](http://docs.aws.amazon.com/sns/latest/api/API_AddPermission.html) and [`RemovePermission`](http://docs.aws.amazon.com/sns/latest/api/API_RemovePermission.html).
## Example

```
resource "aws_sns_topic_permission" "with_cloudwatch" {
    statement_id = "AllowPublishFromCloudWatch"
    action = "Publish"
    topic_name = "${aws_sns_topic.example.name}"
    principal = "events.amazonaws.com"
    source_arn = "${aws_cloudwatch_event_rule.console.arn}"
}
```
## References
- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_lambda_permission.go
- https://github.com/hashicorp/terraform/pull/6025#issuecomment-206396614
- http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/EventsResourceBasedPermissions.html

**Comment by radeksimko** [comment]
Hi @keymon 
we have support for [`aws_sns_topic_policy`](https://www.terraform.io/docs/providers/aws/r/sns_topic_policy.html) since `0.7.3` (September 5, 2016) which does pretty much what you described.

Do you agree we can close this issue now?

**Comment by keymon** [comment]
Yes, ofc.
