### ISSUE TITLE
aws_db_parameter_group name argument error

### ISSUE THREAD

**Issue by phoolish** [hashicorp/terraform#6044]
I've been importing preexisting infrastructure into terraform, but I have run into an issue with the default aws db parameter group names:

```
  * aws_db_parameter_group.default-mysql5-5: only lowercase alphanumeric characters and hyphens allowed in "name"
  * aws_db_parameter_group.default-mysql5-1: only lowercase alphanumeric characters and hyphens allowed in "name"
  * aws_db_parameter_group.default-mysql5-6: only lowercase alphanumeric characters and hyphens allowed in "name"
  * aws_db_parameter_group.default-postgres9-4: only lowercase alphanumeric characters and hyphens allowed in "name"
```

Resources:
```
resource "aws_db_parameter_group" "default-mysql5-1" {
    name        = "default.mysql5.1"
    family      = "mysql5.1"
    description = "Default parameter group for mysql5.1"

}

resource "aws_db_parameter_group" "default-mysql5-5" {
    name        = "default.mysql5.5"
    family      = "mysql5.5"
    description = "Default parameter group for mysql5.5"

}

resource "aws_db_parameter_group" "default-mysql5-6" {
    name        = "default.mysql5.6"
    family      = "mysql5.6"
    description = "Defaul MySQL Parameter Group"

}

resource "aws_db_parameter_group" "default-postgres9-4" {
    name        = "default.postgres9.4"
    family      = "postgres9.4"
    description = "Default parameter group for postgres9.4"

}
```

**Comment by stack72** [comment]
Hi @phoolish 

Thanks for raising the issue here. I have followed these [docs](http://docs.aws.amazon.com/cli/latest/reference/rds/create-db-parameter-group.html) when creating the resource:

```
--db-parameter-group-name (string)

The name of the DB parameter group.
Constraints:
Must be 1 to 255 alphanumeric characters
First character must be a letter
Cannot end with a hyphen or contain two consecutive hyphens
```

Does the consul allow this behaviour?

Thanks

Paul

**Comment by phoolish** [comment]
@stack72 

Interesting.  It does not allow the dot notation in console either.

```The parameter DBParameterGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue;```

I wonder if this is a carry over from an older implementation.  Anyway, this should be a non-issue moving forward.

**Comment by stack72** [comment]
thanks @phoolish for letting me know

P.

**Comment by noky** [comment]
I get a similar error when running copy-db-parameter-group default.mysql5.6 .
How is it supposed to copy this parameter group if it has a dot on the name?

**Comment by stack72** [comment]
Hi @noky 

I am not sure I'm afraid - we followed the docs when creating this resource. The console also doesn't allow dots in the name

Paul

**Comment by boussou** [comment]
how to do then?
If I want to change a parameter, I need to copy the default group before changing right?
since the default created  identifier id  **default.mysql5.7** with a dot, it fails right?
so do we have to path the aws cli to do that?

**Comment by boussou** [comment]
Workaround: dot are not allowed. there is 2.
You have to create yours using the GUI tool.
then the GUI allows to compare 2 parameter groups.
