### ISSUE TITLE
providers/aws: add aws_s3_bucket resource region argument

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#6051]
The current version of aws_s3_bucket doesn't support the region argument. It accepts input and will show it in planning / apply, but it doesn't apply it and throws no errors. 

Having this as a feature would be useful for defining resources outside your default region (which is often us-east-1, due to some global resources not being available in every region).

`Terraform v0.6.15-dev (aef5bcf98227b0ac964657a29ef2a1ebeed19a51)`
- Compiled with OpsWorks Application support PR: https://github.com/hashicorp/terraform/pull/4419

**Comment by marcoamorales** [comment]
In v0.6.16 you can specify the region for an aws_s3_bucket, but it seems the attribute was left out from the documentation.

**Comment by u2mejc** [comment]
@marcoamorales It's looks visible in the code, but if you test it, you'll see it doesn't work:

```
resource "aws_s3_bucket" "b" {
    bucket = "terraform-test-delete-me"
    region = "us-west-2"
    tags {
        Name = "terraform-test-delete-me"
    }
}
```

The above says it applies successfully, but instead uses the global region used by terraform. (from ENV or the provider aws block.)

The reason is that Terraform uses helpers to initiate the golang SDK for every possible resource when it starts up, I wasn't able to think of a clean (non-hacky) way of re-initiating the helper each time a new S3 resource is requested. 

Of note, I found that it's kind of mute since you can specify the region on a per module basis.

**Comment by iroller** [comment]
Also interested in region support for s3 buckets.

**Comment by lazycodeninja** [comment]
We have a use case where a single module needs to create an S3 buckets in multiple regions.  In fact, they're being created in the same `aws_s3_bucket` resource; driven by a list variable containing bucket names.

Between this issue and #3072 / #1819, there's no way to do this in a generic way driven by vars.

**Comment by phinze** [comment]
Yep looks like [we read the region from the client](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_s3_bucket.go#L324-L343), but don't fetch the value from the config to override it. Should be a pretty easy fix!

**Comment by Ninir** [comment]
Hi guys,

Just worked on this in #10482 . Hope it will fit!

**Comment by josjaf** [comment]
I am still experiencing this error. I shouldn't have to define another provider to access another region. It's not respecting region flag inside the bucket.
