### ISSUE TITLE
User data cycle error in modules

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#6055]
I have a modules based stack that is producing the following error when I try to update the user data and re-apply the plan:

```
Error running plan: 1 error(s) occurred:

* Cycle: module.mcp.template_file.redacted, module.mcp.aws_launch_configuration.redacted, module.mcp.aws_autoscaling_group.redacted, module.mcp.aws_launch_configuration.redacted (destroy), module.mcp.template_file.redacted (destroy)
```

I have the following lifecycle rule in the launch configuration and autoscaling group (which also has no dependencies):
```
lifecycle {
    create_before_destroy = true
}
```

Do lifecycle rules not work with modules?

**Comment by jschneiderhan** [comment]
FYI - I was having the same problem as you describe here. I added the same lifecycle rule that I had on my launch configuration to my template file and the cycle went away.

**Comment by toddrosner** [comment]
@jschneiderhan You just solved my problem. I had not thought of adding a lifecycle hook there, but it does make sense. Without modules, this step is not required, but either way, problem solved.

Cheers!
