### ISSUE TITLE
PowerDNS provider changed for version 4.0.0(Alpha2) ttl key moved outside of the record

### ISSUE THREAD

**Issue by linuxus** [hashicorp/terraform#6056]
For anyone trying to use PowerDNS provider against their release candidate (Alpha2 and beyond) please note that they've moved their ttl key out of the record json block to outer block. If you use the current powerdns provider with terraform >=0.6.14 you will get an error with Key 'ttl' is not an integer or not present because this key is required and must be set when sent payload against pdns api

**Comment by smuth4** [comment]
I'd really like to have terraform working with 4, and am willing to take a stab at the work, but my strategy would be doing a couple requests upon client initialization to detect the version of the API (since 4.x isn't stable yet). I'm not sure if that's a kosher strategy, or it would be preferred to wait until 4 is stable and then terraform would only support that.

**Comment by linuxus** [comment]
Hi Stephen,
I'd agree with you that detecting version of the API would help avoid using
unsupported version but I'm not sure if there is a better approach. An
alternative would be to update the provider (pdns) in Terraform to support
the new API at least for 4.0. Alpha2 since PowerDNS updated the api to with
better structure.

As far as my deployment concerns I'm downgrading pdns code base to version
3.4.x so that at least the provider works as expected as I'm not sure when
pdns GA will be released.

Thanks,
Abdi

**Comment by jen20** [comment]
Hi @linuxus and @smuth4! I'm open to either suggestion here. If there is an easy way to detect the version in use we can use that, otherwise we could put some config in the provider to determine which API to use. I'm assuming there are not major changes, but if there are a new provider may be more appropriate.

**Comment by smuth4** [comment]
I took a closer look at what would be needed, and as far I can tell from the documentation the two relevant things that change are the endpoint prefix (`/` to `/api/v1`), and some minor restructuring of the JSON data (the `ttl` issue plus one or two other things). As for determining the version, that would basically be pinging [`/api`](https://doc.powerdns.com/md/httpapi/api_spec/#url-api) to see if it returns valid JSON, and falling back to the 3.4 API if it doesn't.
Other than that, it looks like 95% of [client.go](https://github.com/hashicorp/terraform/blob/master/builtin/providers/powerdns/client.go) would still be applicable, so I wouldn't think it deserves a whole new provider.

**Comment by linuxus** [comment]
Hi Stephen,
I agree with you that most the client code are valid and shouldn't require
a lot of refractor. Let me know when you have a PR and I can test it out
against my environment.

Thank so much for looking into this.

Abdi

**Comment by smuth4** [comment]
I have a branch here which works with both 3 and 4: https://github.com/smuth4/terraform/tree/pdns-4
The only thing that needs to change between the two is that for a `powerdns_record`, the `name` argument for 4 must have a trailing period, while for 3 it must not. That branch is the minimum viable change to make it work, I'm still looking at if it's worth moving to a more complex but elegant solution, and any opinions on the current changes are welcome: https://github.com/hashicorp/terraform/compare/master...smuth4:pdns-4

**Comment by hco** [comment]
How can we move forward on this issue?
Is there any way I can help?

@smuth4 Could you maybe provide me with a binary for Mac OS of your branch? I'd volunteer to test it, but I couldn't compile it. That might be due to my lack of understanding of go, though :)

**Comment by gtmtech** [comment]
@hco others - 

PowerDNS 3.x API was actually an "experimental API", and really only for testing. Now that they've established the requisite json schema for /v1 of their api (in PowerDNS 4.0.0) - I suggest we just go with what works for PowerDNS 4, and not bother supporting an experimental API. Thoughts?

**Comment by gtmtech** [comment]
It sounds like @smuth4 may be ready with an updated PR later today. If so, can we get this reviewed and merged? Happy to help out and test, there's no point in having a broken provider for 4 months!

**Comment by smuth4** [comment]
Apologies, it took longer than I expect to get a proper build environment up, but I've put out the PR for review.
