### ISSUE TITLE
Refresh destroys and recreates unchanged NACLS

### ISSUE THREAD

**Issue by jmfuchs** [hashicorp/terraform#6057]
version: v0.6.14
provider: aws

The documentation says to set the protocol = "-1" to set the rule for all protocols but when a refresh is run the protocol shows as "all" which differs from the template and forces the destruction and recreation of the nacls even though there were no changes.

```
resource "aws_network_acl_rule" "test" {
    network_acl_id = "${aws_network_acl.public.id}"
    rule_number = 250
    egress = true
    protocol = "-1"
    rule_action = "allow"
    cidr_block = "0.0.0.0/0"
}
```

Refresh

`protocol:       "all" => "-1" (forces new resource)`

**Comment by colout** [comment]
+1 to correct the documentation.  You probably already figured it out, but you can do this to fix your plan (hopefully this helps others in the future):

`resource "aws_network_acl_rule" "test" {
    network_acl_id = "${aws_network_acl.public.id}"
    rule_number = 250
    egress = true
    protocol = "all"
    rule_action = "allow"
    cidr_block = "0.0.0.0/0"
}`
