### ISSUE TITLE
Add local_state resource to Terraform provider

### ISSUE THREAD

**Issue by jasonf20** [hashicorp/terraform#6062]
Currently (as far as I can tell) you can't use the "remote_state_resource" to read output values from a local `*.tfstate` file.

My suggestion is adding another resource `local_state` which will take the following configuration values:
file = path to the tfstate file you want to use
variable_name = the output variable name you would like to get

It will output the following:
file = The file used
value = The value loaded from the output of the given tfstate

**Comment by miry** [comment]
I got the same problem, may be it could be resovled with current features. I have 2 state files. And It would great to have access to the foreign from cluster state file for some IP example.

**Comment by shanielh** [comment]
Fixed on `0.7.3` : https://github.com/hashicorp/terraform/pull/8647 :smile:  

Please close.
