### ISSUE TITLE
aws_route53_zone doesn't properly refresh state

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform#6072]
## Steps to reproduce

- Create an `aws_route53_hosted_zone` resource and define the `comment` argument
- `terraform apply`
- Via the AWS web console or the API, alter the comment of the zone
- `terraform plan`

## Expected result

The state file is updated with the altered comment and the plan indicates that it will update the comment

## Actual result

The state file is not updated with the altered comment and the plan indicates that there are no changes

**Comment by apparentlymart** [comment]
The resource implementation is certainly *trying* to make this work, as evidenced by [the branch to update the Comment when set](https://github.com/hashicorp/terraform/blob/d750d4d1cccb08f194cdbc9484825f548be286d2/builtin/providers/aws/resource_aws_route53_zone.go#L174-176), so it seems that something more subtle is going on here than just a missing feature.

One possible bug I see there is that it only updates the comment when it's non-nil. Each AWS API handles "empty" a little differently, and if Route53 is one of those APIs that returns `nil` for an empty value then it looks like this code would fail to update the comment if it were set to *the empty string* in the AWS console, but that shouldn't prevent it from refreshing when it's non-empty.

Seems like this one is going to require some digging to figure out.

**Comment by stack72** [comment]
Hi @maxrothman 

Apologies that we haven't gotten back to you sooner on this. I am not sure this is an issue anymore - I certainly cannot recreate it i'm afraid. I created the following config - using Terraform 0.7.4 (latest!)

```
provider "aws" {
    region = "us-west-2"
}

resource "aws_route53_zone" "main" {
       	name = "hashicorp.com."
       	comment = "Custom comment"

       	tags {
       		foo = "bar"
       		Name = "tf-route53-tag-test"
       	}
}
```

A simple Terraform apply works as follows:

```
% terraform apply                                                                                                                                           ✭
aws_route53_zone.main: Creating...
  comment:        "" => "Custom comment"
  force_destroy:  "" => "false"
  name:           "" => "hashicorp.com."
  name_servers.#: "" => "<computed>"
  tags.%:         "" => "2"
  tags.Name:      "" => "tf-route53-tag-test"
  tags.foo:       "" => "bar"
  vpc_region:     "" => "<computed>"
  zone_id:        "" => "<computed>"
aws_route53_zone.main: Still creating... (10s elapsed)
aws_route53_zone.main: Still creating... (20s elapsed)
aws_route53_zone.main: Still creating... (30s elapsed)
aws_route53_zone.main: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

I went to the AWS console and modified the comment:

<img width="449" alt="screen shot 2016-09-23 at 17 58 29" src="https://cloud.githubusercontent.com/assets/227823/18794427/5e6762ca-81b7-11e6-947b-f57966fed80e.png">

The next terraform plan looked as follows:

```
% terraform plan                                                                                                                                            ✭
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

aws_route53_zone.main: Refreshing state... (ID: Z372CX3QMDHJWE)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ aws_route53_zone.main
    comment: "Custom comment Updated" => "Custom comment"


Plan: 0 to add, 1 to change, 0 to destroy.
```

The apply worked as follows:

```
% terraform apply                                                                                                                                           ✭
aws_route53_zone.main: Refreshing state... (ID: Z372CX3QMDHJWE)
aws_route53_zone.main: Modifying...
  comment: "Custom comment Updated" => "Custom comment"
aws_route53_zone.main: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

This then looks as follows in the console:

<img width="441" alt="screen shot 2016-09-23 at 17 59 41" src="https://cloud.githubusercontent.com/assets/227823/18794454/8511c5a0-81b7-11e6-93db-39a69580be0d.png">

Hope this helps

Paul
