### ISSUE TITLE
aws rds read replica not changing security group and parameter group

### ISSUE THREAD

**Issue by mboret** [hashicorp/terraform#6091]
Hi,

I'm trying to create a RDS(MariaDB) Read Replica between two AWS region(master in eu-west-1 and Read Replica in ap-southeast-1). 
I set a custom security group and parameter group for this database. 
When I perform a terraform plan, my custom security group and parameter group are well listed. 
But after the apply process(terraform indicates that all has succeeded), when I check my new RDS database in AWS, I've the default security group and the default parameter group. 

And if I make a new terraform plan, it indicates that the database will be destroy to change these two parameters... and always same result. 

I can update these parameters by the AWS console but terraform seems to be unable to do it.

**Comment by stack72** [comment]
Hi @mboret 

Apologies this has taken so long to get back to you. I have just tested the behaviour of this and it seems to work as expected here. Please can you let me know what you configuration looks like (minux secrets). The config I am testing on looks as follows:

```
resource "aws_db_instance" "bar" {
  identifier           = "mydb-rds-test"
  engine               = "mysql"
  engine_version       = "5.6.23"
  instance_class       = "db.t2.micro"
  name                 = "mydb"
  username             = "foo"
  password             = "barbarbar"
  parameter_group_name = "default.mysql5.6"

  apply_immediately = true

  storage_type      = "io1"
  allocated_storage = 200
  iops              = %d
}
```

**NOTICE: `apply_immediately = true`**

If this parameter is not set then the changes will not take place until the next maintenance window. The reason we do not want this to default to true is that some changes (e.g. change of node type or allocated_storage) can cause the instance to be rebooted

Please let me know if this helps

Paul

**Comment by stack72** [comment]
Ping @mboret :)

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
