### ISSUE TITLE
Additional resources to manage default ACL, security group, and route tables.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#6093]
AWS VPCs come with a default set of network resources - an ACL, a security group, and a main route table. There's no way to then manage these resources directly, because Terraform has no awareness of them (as of v0.6.14).

New resource types should be added to Terraform that allow these resources to be explicitly managed.

**Comment by catsby** [comment]
I'm [WIP] here

**Comment by kamaltherocky** [comment]
+1

This will be very helpful feature when you want to override the default configuration (SG, Route Table and NACL)

**Comment by catsby** [comment]
#6165 added the default network acl resource
#8323 adds the default route table resource

**Comment by catsby** [comment]
Default security group added in #8861

**Comment by catsby** [comment]
@clstokes good to close this?

**Comment by clstokes** [comment]
@catsby closed! Thanks! 🍰
