### ISSUE TITLE
Support name prefix everywhere

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#6099]
I generally try to use `name_prefix` instead of `name` where possible, but not all resources support `name_prefix`. For example, `aws_security_group` does but `aws_iam_role` does not. It would be great to have support for `name_prefix` everywhere that `name` is supported.

**Comment by stack72** [comment]
@joshuaspence I am going to go ahead and close this out. The bulk of this has been added :) 

Thanks for all the work you put in on this
