### ISSUE TITLE
aws_instance: root_block_device: Cannot attach root ebs volume correctly on EC2 Windows Instance

### ISSUE THREAD

**Issue by zhefanlin** [hashicorp/terraform#6108]
Version 0.6.14 and 0.6.13
When using "root_device_block" in aws_instance resource block to create a windows intance, AMI had 40GB by default, I set the root_block device size to 50GB,

"terraform plan" did noticed the root size change, but after "terraform apply", the block device /dev/sda1 on AWS console still 40GB, besides the /dev/sda1, there was another device called xvdco which is 50GB.

![image](https://cloud.githubusercontent.com/assets/4819185/14406390/1cb1819c-fe74-11e5-887e-13e1261aa4cb.png)

I log in that instance, found xvdco in windows disk manager as Disk D:, the disk C:\ was still defualt 40GB

![image](https://cloud.githubusercontent.com/assets/4819185/14406463/4e7f44be-fe76-11e5-9c16-f8612d1abd6b.png)
Note: the two temporary disks are SSD coming with c3.xlarge

![image](https://cloud.githubusercontent.com/assets/4819185/14406476/999fa074-fe76-11e5-9faf-80bcc4769c06.png)

Cannot reproduce every time, sometimes it works fine...

If I use "ebs_block_device" plus device_name="/dev/sda1" instead of "root_block device", it works fine each time, root disk got attached and mount correctly, but it will recreate instance resource if I want to re-apply without destroy it.

**Below is my code:**
resource "aws_instance" "inst" {
  provider = "aws.windows_instance_${var.num_drive}_drives"
  ami = "${var.ami_id}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key}"
  source_dest_check = false
  associate_public_ip_address = "${var.assoc_public_addr}"
  subnet_id = "${var.subnet_id}"
  security_groups = ["${var.security_group_id}"]

  # C:\ drive
    root_block_device {
    # device_name = "/dev/sda1"
    volume_size = "${element(split(",",var.volume_size), 0)}"
    volume_type = "${var.volume_type}"
    delete_on_termination = true
  }

  user_data = "${template_file.winconfig.rendered}"

  tags {
    Application = "${var.stack_name}"
    Name = "${var.name}"
  }
}

"terraform plan" Output:
![image](https://cloud.githubusercontent.com/assets/4819185/14406413/b78300e2-fe74-11e5-9d8f-9c1b18221913.png)

"terraform apply" Output:
![image](https://cloud.githubusercontent.com/assets/4819185/14406423/00cdc426-fe75-11e5-9b3a-2e9a01f1f932.png)

**Comment by zhefanlin** [comment]
not sure if this error related to the aws ami.
The "ami-c796bcad" I was using could reproduce this error everytime

**Comment by Demerol** [comment]
Was this ever fixed?

If i add a Root_block_device to my amazon instance they come up with 2 ebs volumes attached, the 'default' volume created by the ami and a secondary created by terraform that is attached with a randomly appdended name after /dev/sda1

**Comment by luis-echegaray** [comment]
Still present as of 12/14 on Windows Server 2016 w/ Containers

C:\ shows up as a 30gb, and my     

root_block_device {
        volume_size = 200
    }

shows up as a separate volume

![screen shot 2016-12-14 at 10 50 36 am](https://cloud.githubusercontent.com/assets/12701030/21189017/459852c6-c1eb-11e6-92a6-44868b47c65c.png)
