### ISSUE TITLE
Error applying plan ELB

### ISSUE THREAD

**Issue by Meabed** [hashicorp/terraform#6121]
It happen first time and When i apply terraform again it works fine. 
`
* aws_elb.be-elb: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.14
    Resource ID: aws_elb.be-elb
    Mismatch reason: attribute mismatch: instances.2268514773
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.#":*terraform.ResourceAttrDiff{Old:"6", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.4246230854":*terraform.ResourceAttrDiff{Old:"i-054df816ce520d0f4", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.892388259":*terraform.ResourceAttrDiff{Old:"i-07df053038550524a", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1635304643":*terraform.ResourceAttrDiff{Old:"i-01f840f7489a572d0", New:"i-01f840f7489a572d0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2268514773":*terraform.ResourceAttrDiff{Old:"", New:"${aws_instance.be_a.*.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2406087513":*terraform.ResourceAttrDiff{Old:"i-04072bd6df29e9a5d", New:"i-04072bd6df29e9a5d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.3735614233":*terraform.ResourceAttrDiff{Old:"i-051e43fa28b1c63a0", New:"i-051e43fa28b1c63a0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.400216052":*terraform.ResourceAttrDiff{Old:"i-05673af3e0fbc488c", New:"i-05673af3e0fbc488c", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.749124040":*terraform.ResourceAttrDiff{Old:"", New:"i-02e12b6e0e871d3f7", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.870662888":*terraform.ResourceAttrDiff{Old:"", New:"i-070a7b33bb93aefa1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.892388259":*terraform.ResourceAttrDiff{Old:"i-07df053038550524a", New:"i-07df053038550524a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"6", New:"12", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1567295868":*terraform.ResourceAttrDiff{Old:"", New:"i-0b7eb7945605c5240", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.192635060":*terraform.ResourceAttrDiff{Old:"", New:"i-09c7c63fa88284eb9", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2824574363":*terraform.ResourceAttrDiff{Old:"", New:"i-071add123b3ad29cc", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.4246230854":*terraform.ResourceAttrDiff{Old:"i-054df816ce520d0f4", New:"i-054df816ce520d0f4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1635304643":*terraform.ResourceAttrDiff{Old:"i-01f840f7489a572d0", New:"i-01f840f7489a572d0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2406087513":*terraform.ResourceAttrDiff{Old:"i-04072bd6df29e9a5d", New:"i-04072bd6df29e9a5d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.3735614233":*terraform.ResourceAttrDiff{Old:"i-051e43fa28b1c63a0", New:"i-051e43fa28b1c63a0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1739463281":*terraform.ResourceAttrDiff{Old:"", New:"i-0b76e5f63483b4d25", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.400216052":*terraform.ResourceAttrDiff{Old:"i-05673af3e0fbc488c", New:"i-05673af3e0fbc488c", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

* aws_elb.fe-elb: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.14
    Resource ID: aws_elb.fe-elb
    Mismatch reason: attribute mismatch: instances.2396875183
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.2513463109":*terraform.ResourceAttrDiff{Old:"i-07bfc202667361c6f", New:"i-07bfc202667361c6f", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.858741329":*terraform.ResourceAttrDiff{Old:"i-06c48f00228076914", New:"i-06c48f00228076914", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"2", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2396875183":*terraform.ResourceAttrDiff{Old:"", New:"${aws_instance.fe_a.*.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.1559187197":*terraform.ResourceAttrDiff{Old:"", New:"i-03ffc679004a2f5c8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2513463109":*terraform.ResourceAttrDiff{Old:"i-07bfc202667361c6f", New:"i-07bfc202667361c6f", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.3464594517":*terraform.ResourceAttrDiff{Old:"", New:"i-07db48f5377ef79c6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.858741329":*terraform.ResourceAttrDiff{Old:"i-06c48f00228076914", New:"i-06c48f00228076914", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.#":*terraform.ResourceAttrDiff{Old:"2", New:"4", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
`

**Comment by catsby** [comment]
Hey @Meabed do you have a configuration that demonstrates this consistently?

**Comment by catsby** [comment]
Hello – I'm going to close this for now, please let us know if you're still hitting this issue in the latest version of Terraform (v0.6.16 at time of writing)
