### ISSUE TITLE
vSphere Linked Clone

### ISSUE THREAD

**Issue by rossedman** [hashicorp/terraform#6122]
I thought the vsphere provider that was merged into Terraform proper was from @mkuzmin . That being said was the `linked_clone` reference removed? This is shown [here](https://github.com/mkuzmin/terraform-vsphere/blob/master/resource_virtual_machine.go#L56).

**Comment by stack72** [comment]
Hi @rossedman 

Linked clone support has been opened as a PR here https://github.com/hashicorp/terraform/pull/4634

I am going to close this issue so that we can track all requests / references in this PR

Thanks for getting in touch

Paul

**Comment by rossedman** [comment]
@stack72 Thanks a lot for the response.
