### ISSUE TITLE
Usage of single qoutes vs double qoutes and interpolations

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#613]
I was trying to do:

```
inline = [
    "sudo sh /tmp/boostrap_env_file_on_aws.sh ${count.index} ${join(' ', google_compute_instance.weave.*.network.0.external_address)}"
]
```

...as it seemed natural to put single quotes... right? Well, but that resulted in the whole `${join...` string being passed to the script. I was thinking the issue is with the variable that I'm trying to join, as I wasn't sure what was the exact thing to get external IP for a GCE instance.

However, turned out that nested double-qouted string is totally fine with the parser, which feels odd and could be at least documented explicitly.

Here is the working one:
```
inline = [
    "sudo sh /tmp/boostrap_env_file_on_aws.sh ${count.index} ${join(" ", google_compute_instance.weave.*.network.0.external_address)}"
]
```

**Comment by mitchellh** [comment]
This is fixed now, you'll get a syntax error. The language is better formalized now from #785
