### ISSUE TITLE
aws_network_acl_rule ignores specified ports when protocol = -1

### ISSUE THREAD

**Issue by flamingspaz** [hashicorp/terraform#6130]
### Terraform Version

0.6.14
### Affected Resource(s)
- aws_network_acl_rule
### Terraform Configuration Files

``` hcl
resource "aws_network_acl_rule" "apps-production-allowserffromstaging" {
    network_acl_id = "${aws_vpc.apps-production-vpc.default_network_acl_id}"
    rule_number    = 30
    egress         = false
    protocol       = "-1"
    rule_action    = "allow"
    cidr_block     = "${aws_vpc.apps-staging-vpc.cidr_block}"
    from_port      = 8300
    to_port        = 8302
}
```
### Debug Output

Let me know if you need the full debug output for this but I'm not sure its needed
https://gist.github.com/flamingspaz/d020c524852563405be7c89abf9c1bc9
### Expected Behavior

1) Terraform should return an error stating from_port and to_port must be 0 when protocol = "-1"

2) Documentation should be updated to indicate that the from_port and to_port values are ignored when protocol = "-1". I'm sending a PR to add a note if this is what you'd prefer.
### Actual Behavior

![Output](https://yalam.co.uk/i/SaWQ.png)
### Steps to Reproduce
1. `terraform apply`

**Comment by catsby** [comment]
I merged #6130, which adds documentation for this, but we should probably leave it open and actually error or warn in this situation
