### ISSUE TITLE
Terraform EC2 security group ingress rule flapping

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#6135]
Hi,

When I create security group ingress rule that opens access from SG in another aws account, `terraform apply` always recreates this rule even if no changes in terraform config files were made:

```
-/+ aws_security_group_rule.apigw_access
    from_port:                "443" => "443"
    protocol:                 "tcp" => "tcp"
    security_group_id:        "sg-ba999ac2" => "sg-ba999ac2"
    self:                     "false" => "0"
    source_security_group_id: "sg-8c777ceb" => "373682980000/sg-8c777ceb" (forces new resource)
    to_port:                  "443" => "443"
    type:                     "ingress" => "ingress"
```

SG ingress rule config:

```
resource "aws_security_group_rule" "apigw_access" {
  type = "ingress"
  from_port = 443
  to_port = 443
  protocol = "tcp"
  security_group_id = "${aws_security_group.ecs_security_group.id}"
  source_security_group_id = "373682980000/sg-8c777ceb"
}
```

Please advise. Thank you.

P.S. terraform 0.6.14

**Comment by enisher** [comment]
+1

**Comment by joshuaspence** [comment]
+1

**Comment by anosulchik** [comment]
Guys, is there any news on it? Looks like fresh version 0.6.15 contains the same bug.

**Comment by dimitrystd** [comment]
+1

**Comment by tony612** [comment]
I have the similar problem

**Comment by jose-cardoso-tjg** [comment]
Yet another bump. 3 months on and using v0.7.3 this issue remains unresolved.

Extremely annoying as we're using VPC peering and cross-referenced security groups quite heavily.

**Comment by kapilt** [comment]
Afaics this issue is primarily about the lack of support for cross-account or cross-vpc security groups, internally the code knows nothing of them (UserIdGroupPairs turns into a flat list of sg-ids), and the flapping is a side effect in this of trying to put in invalid strings, ie simply putting in account/sg-id reference doesn't mean the code supports it. the issue title should probably be updated to reflect this is primarily about supporting cross vpc/cross account security group references.

**Comment by kapilt** [comment]
so apparently the ec2 api can interpret the ambiguity (missing params) if just given a sg-id without the peering conn or remote vpc reference, so just passing the sg-id should work at least within an account, cross-account unclear.

**Comment by matthieudolci** [comment]
@kapilt cross-account does not work. Just tried it.

**Comment by CarlInglisBJSS** [comment]
Still getting the same issue in 0.8.8.

**Comment by anosulchik** [comment]
Just to confirm that in latest terraform, SG rules created with aws_security_group_rule are inconsistent -- it's required to run terraform twice to get it working. It doesn't matter if source group oi cross-account SG or not.

**Comment by grubernaut** [comment]
Hi all, and @anosulchik, thanks for the issue!

Just to verify, as it's a known issue, the source security group `aws_security_group.ecs_security_group`:
```
  security_group_id = "${aws_security_group.ecs_security_group.id}"
```

Doesn't have any inline `ingress` or `egress` rules inline does it? 

As in:
```
resource "aws_security_group" "ecs_security_group" {
  ingress {
    ....
  }
  egress {
    ....
  }
}
```

**Comment by clickboxer** [comment]
I have this issue as well with current Terraform version (0.9.2 at this time).
By reading the remote state I can tell that the expected value (AWS_ACCOUNT_NUMBER/SECURITY_GROUP_ID)  is stored in the state file.
The same value can be read through the AWS console.

A `terraform refresh` doesn't solve the problem.

Any update or help on this issue would be appreciated.

**Comment by clickboxer** [comment]
After some testing, I would say that flapping is due to the presence of a useless piece of information: the AWS account ID.
One just needs to specify the Security Group ID and AWS will complete this info with the Account ID as a prefix in the console.

**Comment by bodgit** [comment]
I've just stumbled across this as we were experiencing flapping, we had a single `aws_security_group` resource with inline ingress and egress rules like so:

```
resource "aws_security_group" "test" {
  name   = "test"
  vpc_id = "vpc-deadbeef"

  egress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    security_groups = [
      "sg-feedbeef",
    ]
  }
  ...
}
```

If I change the security_group reference to be `123456789012/sg-feedbeef` then the flapping disappears.

So in my mind, there's two possible fixes here:

1. Update the documentation to mention that if referencing a peer security group to include the peer account ID using the above notation.
2. Update the security group code that when reading the security groups from the API that it removes any account ID prefix that might be present, looks like something around https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_security_group.go#L562 would be needed.

I'd err towards the latter as Amazon doesn't mention that you need to do 1) and it also seems to JFW if you just specify the plain security group ID. For now I've worked around this by doing 1) in my code as I have the account ID as a variable anyway as I'm establishing the peering using TF.

Happy to whip up a PR for either.
