### ISSUE TITLE
Support multiple canned ACLs for AWS S3 buckets

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform#6139]
The `aws_s3_bucket` resource's `acl` field currently accepts a string. AWS supports multiple grants to multiple users ([ref](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html)). Perhaps the `acl` field could take a map or even broken out into a separate resource.

**Comment by tchemineau** [comment]
👍 

For example, when we want to create a S3 bucket to store application logs AND ELB logs. Application logs need a private ACL, ELB logs need log-delivery-write ACL.

See this online documentation:
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by maxrothman** [comment]
Any progress on this?

**Comment by jcornell123** [comment]
Any progress on this issue?
