### ISSUE TITLE
Terraform timed out while applying updates to Triton Machine Metadata

### ISSUE THREAD

**Issue by sodre** [hashicorp/terraform#6148]
### Terraform Version
Terraform v0.6.15-dev (70c65fb00a69680257a21c44aa023df999cd9b1b+CHANGES)

### Affected Resource(s)
triton_machine

### Terraform Configuration Files
The Initial configuration is:
```hcl
resource "triton_machine" "test" {
  name = "test"
  package = "t4-standard-128M"
  image = "eb9fc1ea-e19a-11e5-bb27-8b954d8c125c"
}
```

Then add a metadata field to the config file:
```hcl
resource "triton_machine" "test" {
  name = "%s"
  package = "t4-standard-128M"
  image = "eb9fc1ea-e19a-11e5-bb27-8b954d8c125c"
  user_data = "hello"
}
```

### Debug Output
--- 

### Expected Behavior
Create/Update/Delete operations on Triton instances should return immediately after they are confirmed with the provider.

### Actual Behavior
After calling `terraform apply` the second time the program times out.

### Steps to Reproduce
Please list the steps requires to reproduce the issue, for example:
1. Start with the basic instance config
2. `terraform apply`
3. Edit the config file and add the user_data field.
4. `terraform apply`
4.a) It will time out. <--- This is the bug
5. `terraform show | grep user_data`
5.b) user_data = "hello" as expected, that is the provider accepted the command.

### Important Factoids
Running on debug install of Triton.

**Comment by stack72** [comment]
Hi @sodre 

I am going to close this out as you have opened a PR that fixes this work. Thanks so much for all the work on tracking this down and fixing it :)

Paul
