### ISSUE TITLE
AzureRM Data Disk

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/terraform#6150]
Hi there,

please add support for Data Disk with AzureRM.

Terraform is amazing!

**Comment by stack72** [comment]
Hi @clintonm9

As far as I can see, from the ARM docs, there is no way to create a DataDisk from the API. Is this incorrect? If so, please point me at the docs and I will happily get it implemented

Paul

**Comment by clintonm9** [comment]
@stack72 

Is this what you need?
https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx

Thanks

**Comment by stack72** [comment]
Hi @clintonm9 

This is the creation and updating of VMs. We have that resource already - it even has the ability to attach already created data disks.

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#storage_data_disk

P.

**Comment by stack72** [comment]
Hi @clintonm9 

This is being fixed and a PR is just about to open for it. Tracking this as part of the wider AzureRM issue right now

Paul
