### ISSUE TITLE
ignition provider 

### ISSUE THREAD

**Issue by mcuadros** [hashicorp/terraform#6151]
I want suggest [ignition](https://coreos.com/ignition/docs/latest/) support exactly in the same way I suggested the cloud-init support: https://github.com/hashicorp/terraform/issues/6002

Creating a detailed provider with a resource for each kind of entity on ignition, like the units, files, users, etc. To avoid having plain text files, being deployed without any verification. 

BTW If this is interesting I am open to contribute to terraform with this provider.

**Comment by stack72** [comment]
Hi @mcuadros

thanks for the suggestion. Please feel free to open a PR with the enhancement - we will happily have a look at the functionality :)

Paul

**Comment by mcuadros** [comment]
Sure, I will open a PR ASAP.

**Comment by stack72** [comment]
<3 @mcuadros :)
