### ISSUE TITLE
aws_iam_group_policy / AWS 404

### ISSUE THREAD

**Issue by derBroBro** [hashicorp/terraform#6153]
Hello,

first: thank you very much for this great tool!
As I was not sure if the follwing is a bug I ask in the IRC and they confirmed me to open an issue.

Best Malte

### Terraform Version
Terraform v0.6.14 (Windows)

### Affected Resource(s)
aws_iam_group_policy

### Terraform Configuration Files
```
resource "aws_iam_group" "GROUP_test123" {
    name = "GROUP_test123"
    path = "/users/"
}
resource "aws_iam_group_policy" "POLICY_test123" {
    name = "POLICY_test123"
    group = "${aws_iam_group.GROUP_test123.id}"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "codecommit:CreateBranch"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
EOF
}
### Output
aws_iam_group_policy.POLICY_test123: Destroying...
Error applying plan:

1 error(s) occurred:

* aws_iam_group_policy.POLICY_test123: Error deleting IAM group policy GROUP_test123:POLICY_test123: NoSuchEntity: The group with name GROUP_test123 cannot be found.
        status code: 404, request id: bdb1a08d-0168-11e6-8864-1fb0fdf56a61

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior
TF is understanding the resouce is already gone a dont try to remove them again and again

### Actual Behavior
TF tries every time to remove the roussource again

### Steps to Reproduce
terraform apply

**Comment by leventyalcin** [comment]
These issue can be related with #6136

**Comment by stack72** [comment]
Hi @derBroBro 

My apologies for not getting to this sooner - this has actually already been fixed :) 

https://github.com/hashicorp/terraform/commit/31258e06c65d85eeee2cd86131bb4cecaeba48cc

Hope this helps - sorry again for the time this has taken :(

Paul
