### ISSUE TITLE
provider/aws: aws_elastic_beanstalk_environment resource needs migration.

### ISSUE THREAD

**Issue by dharrisio** [hashicorp/terraform#6164]
A recent commit of mine caused issues with previous versions of Terraform.

The issues were introduced with #5966

In previous versions tier could have been left blank and did not have a default value. A change was made so that the default value was "WebServer", while setting up the `cname` output to only work for "WebServer" tier environments.
Unfortunately, this attribute also forces a new resource. Which results in a diff that looks like this:

```
tier:                         "" => "WebServer" (forces new resource)
```

The migration should update tier values of "" to "WebServer" in the state to prevent this.

I was able to produce these issues using `v0.6.15-dev (8f06676c58db0a3038a2a83ae8a2b36421370d54)` initially, and the errors were displayed when using the most recent version: `v0.6.15-dev (bf619d0c9dc2dd8e80ab7055a3a11aa3f8ed3e04)`

Plan used to create issues
```
provider "aws" {
  region = "us-east-1"
}

resource "aws_elastic_beanstalk_application" "tftest" {
  name = "tf-test-migrations"
  description = "tf-test-desc"
}

resource "aws_elastic_beanstalk_environment" "tfenvtest" {
  name = "tf-test-migrations-env"
  application = "${aws_elastic_beanstalk_application.tftest.name}"
  solution_stack_name = "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4"
}
```

Output
```
-/+ aws_elastic_beanstalk_environment.tfenvtest
    all_settings.#:          "89" => "<computed>"
    application:             "tf-test-migrations" => "tf-test-migrations"
    autoscaling_groups.#:    "1" => "<computed>"
    cname:                   "tf-test-migrations-env.wevmurue9y.us-east-1.elasticbeanstalk.com" => "<computed>"
    cname_prefix:            "" => "<computed>"
    instances.#:             "1" => "<computed>"
    launch_configurations.#: "1" => "<computed>"
    load_balancers.#:        "1" => "<computed>"
    name:                    "tf-test-migrations-env" => "tf-test-migrations-env"
    queues.#:                "0" => "<computed>"
    setting.#:               "0" => "<computed>"
    solution_stack_name:     "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4" => "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4"
    tier:                    "" => "WebServer" (forces new resource)
    triggers.#:              "0" => "<computed>"
    wait_for_ready_timeout:  "" => "10m"
```

Sorry about missing this in the initial pr, will have the migrations done soon!

**Comment by stack72** [comment]
@dharrisio 

Thanks for the PR that fixes this - I am going to go ahead and close this out right now as we can track any convo in that PR

P.
