### ISSUE TITLE
Terraform openstack doesn't use latest image

### ISSUE THREAD

**Issue by jseaidou** [hashicorp/terraform#6166]
When giving `image_name` to `openstack_compute_instance_v2`, if we have multiple images for the same name in glance, it will not sometimes use the latest. We generally autogenerate new images with same names and keep only the last few versions as backups. Terraform should allow to specify to use latest or to default to that.

**Comment by jtopjian** [comment]
That's actually really bizarre. If you specify a non-unique image name, you should be getting the following error:

```* openstack_compute_instance_v2.test: Found 2 images matching Ubuntu 14.04```

In which case, you'll need to specify a UUID rather than a name.

Are you using the latest version of Terraform?

**Comment by jseaidou** [comment]
@jtopjian sorry my mistake. It seems like I have confused different image-ids. You are right I do see that. 
However is it possible to allow Terraform use latest out of multiple images instead of erroring? 
To give some information:
we have a pipeline built that will update images with new code etc .. and we push them to openstack. We keep the last few versions for rollback reasons but we want to be able to automatically deploy the latest image and replace the old instances with the new ones. Hardcoding image-ids defeats the purpose of this.

**Comment by jtopjian** [comment]
@jseaidou Thanks for the background. I understand the use case and I agree that hard-coded image-ids are no good here. However, I feel that placing this kind of logic in the `image_name` retrieval wouldn't be a good design. Let's say after it was implemented, someone wanted the earliest image instead.

Gophercloud (the underlying OpenStack Golang library that Terraform uses) doesn't support the Glance API yet, though most of the work has been [done](https://github.com/rackspace/gophercloud/pull/458). Once this is merged, I can see this kind of flexible image searching implemented. For example:

```
image {
  name = "Ubuntu 14.04"
  tag = "latest"
}
```

And hopefully that query would result in a single image-id, or else an error would be thrown.

In the meantime, what if the logic of determining the latest image was moved outside of Terraform: somehow or another, the latest image-id found its way to `latest-image-id.txt`, and you specified the following in your instance:

```image_id = "${trimspace(file("latest-image-id.txt"))}"```

Or maybe the image-id is stored in a Consul key (the example use of `consul_keys` in the [docs](https://www.terraform.io/docs/providers/consul/r/keys.html) is doing this exact thing - reading an ami ID)

Thoughts?

**Comment by jseaidou** [comment]
I think we can definitely implement a similar workaround, but I do believe this is logic that should be tied to terraform as well. I will look into consul_keys, we're currently using etcd and might not make sense to also set up consul. Is there any chance that there will be a etcd provider as well, and a similar `etcd_keys`? 
Thanks for the help!

**Comment by jtopjian** [comment]
hm, I'm not entirely sure about etcd stuff. A quick search in the issues and prs didn't turn much up, but I really only focus on the OpenStack side.

I agree - once there's better access to the Glance/Image API, adding support for image querying will be possible to do.

**Comment by jtopjian** [comment]
@jseaidou I'm going to go ahead and close this issue with the understanding that more intelligent image querying will be investigated/implemented once the Glance/Image API lands in Gophercloud. Please feel free to re-open if you'd like to discuss further :)
