### ISSUE TITLE
panic: 'Unary - is only allowed' crash

### ISSUE THREAD

**Issue by shinka81** [hashicorp/terraform#6170]
Hello,
 I was working on creating a new module for creating AWS Aurora instances and ran in to this crash output when I went to `terraform plan`. I am able to successfully plan when I remove the `replace(aws_rds_cluster.db.endpoint, /:.*/, '')` function (see below) so it has me thinking this is the culprit, be it user error or just a bug. 

Thanks for any help!

### Terraform Version
```
terraform -v
Terraform v0.6.14
```

### Affected Resource(s)
(there are also dependencies for these resources involved within this folder but these seem to be linked to the crash)
- aws_route53_record
- aws_rds_cluster

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "db" {
   zone_id = "${var.some_zone_id}"
   name = "${var.environment_abbreviation}-${var.db_name}-db.internal.aws"
   type = "CNAME"
   ttl = "300"
   records = ["${replace(aws_rds_cluster.db.endpoint, /:.*/, '')}"]
}
...
resource "aws_rds_cluster" "db" {
  cluster_identifier = "${replace(var.vpc_name, "_", "-")}-${replace(var.db_name, "_", "-")}-db"
  master_username = "${var.super_user}"
  master_password = "${var.super_user_password}"
  backup_retention_period = "${var.db_backup_retention_period}"
  preferred_backup_window = "${var.db_preferred_backup_window}"
  preferred_maintenance_window = "${var.db_preferred_maintenance_window}"
  port = 3306
  vpc_security_group_ids = ["${aws_security_group.db.id}"]
  db_subnet_group_name = "${aws_db_subnet_group.db.id}"
}
```

### Panic/Debug Output
https://gist.github.com/shinka81/0bbcc519152c59608bbab18c30b847db

### Expected Behavior
A route53 CNAME record generated based on the `aws_rds_cluster` resources `endpoint` attribute. The replace is attempting to remove the `:3306`.

### Actual Behavior
Terraform crashed, see above for output.

### Steps to Reproduce
steps required to reproduce the issue:
1. `terraform plan`

Note: this is a new module I am working on so I haven't actually got it to apply yet, just crashed on this plan so this could also be user error :)

**Comment by shinka81** [comment]
This actually turned out to be the same problem as #5672 . I needed quotes around the second argument to replace(). Feel free to close this if necessary

**Comment by apparentlymart** [comment]
Thanks for the report and the followup, @shinka81. Indeed quotes are required around the second argument... and it is of course a bug that Terraform crashes in this case, but agreed that it looks like #5672 is already covering this bug so I'm going to close this as you suggested.

Thanks again!
