### ISSUE TITLE
aws_s3_bucket_object uses kms_key_id attribute inconsistently

### ISSUE THREAD

**Issue by beeerd** [hashicorp/terraform#6172]
### Terraform Version
0.6.14

### Affected Resource(s)
- aws_s3_bucket_object
- aws_kms_key

### Terraform Configuration Files
```
resource "aws_kms_key" "main" {}

resource "aws_s3_bucket" "ca_cert" {
  bucket = "ca.cert"
  acl = "private"
}

resource "aws_s3_bucket" "ca_key" {
  bucket = "ca.key"
  acl = "private"
}

resource "aws_s3_bucket_object" "ca_cert" {
  key = "ca.crt"
  bucket = "ca.cert"
  source = "/tmp/certs/ca/ca.crt"
  kms_key_id = "${aws_kms_key.main.id}"
  depends_on = ["aws_s3_bucket.ca_cert"]
}

resource "aws_s3_bucket_object" "ca_key" {
  key = "ca.key"
  bucket = "ca.key"
  source = "/tmp/certs/ca/ca.key"
  kms_key_id = "${aws_kms_key.main.id}"
  depends_on = ["aws_s3_bucket.ca_key"]
}
```

### Debug Output
First apply: https://gist.github.com/beeerd/45da50c41eee72ea1a9d4d6aa894026b
Second apply: https://gist.github.com/beeerd/dc2f9ff9f79c61ba491e4fe21318e231

### Expected Behavior
Second apply should be no-op, since no changes are made between runs of `terraform apply`

### Actual Behavior
On the first run of `terraform apply` the `aws_kms_key.arn` resource is incorrectly interpolated as the attribute for each s3 bucket object's `kms_key_id` resource reference. This can be observed by looking at the terraform.tfstate file after the first run. Stdout does not reveal this behavior.

On the second run the `aws_kms_key.main.id` resource is applied instead of `aws_kms_key.main.arn`. This triggers an additional error about etag being used in conjunction with `kms_key_id`.

### Steps to Reproduce
Using the HCL above, run:
1. `terraform apply`
2. `terraform apply`

### Workaround
Explicitly using `aws_kms_key.*.arn` in place of `aws_kms_key.*.id` on the `kms_key_id` attribute of a `aws_s3_bucket_object` resource will avoid this behavior. This is confusing considering the attribute name implies that the kms key id should be used rather than the arn.

### References
Possibly related:
- GH-5689

**Comment by catsby** [comment]
Hey @beeerd sorry for the confusion here. I've opened https://github.com/hashicorp/terraform/pull/6309 to clarify this in the documentation. The terms get muddy with ID for Terraform being what you're demonstrating here, `aws_resource.foo.id`, but on AWS's side they're referring to the ARN... mostly. It doesn't help us that AWS will accept the ID here or the ARN (the ID just being the last part of the ARN), but it always returns the ARN... 

Hopefully I've cleared that up. Sorry for the trouble!

**Comment by ncs-msmith** [comment]
Thank you!

**Comment by beeerd** [comment]
Thank you! I reviewed the documentation update, LGTM.

**Comment by catsby** [comment]
@beeerd awesome, thanks for following up, and thanks for bringing this to our attention 😄
