### ISSUE TITLE
aws ENI re-attachment fails after ec2 instance recreation

### ISSUE THREAD

**Issue by Mil0dV** [hashicorp/terraform#6179]
### Terraform Version

Terraform v0.6.15-dev (70c65fb00a69680257a21c44aa023df999cd9b1b)
### Affected Resource(s)
- aws_network_interface
### Terraform Configuration Files

``` hcl
resource "aws_instance" "staging" {
  ami                                  = "${var.app_ami}"
  instance_type                        = "t2.micro"
  instance_initiated_shutdown_behavior = "terminate"
  subnet_id                   = "subnet-1209e77b"
  security_groups             = ["${split(",", var.security_groups)}"]
  key_name                    = "eu-central"
  source_dest_check           = false
  associate_public_ip_address = true
}

resource "aws_network_interface" "staging" {
  subnet_id   = "subnet-1209e77b"
  attachment {
    instance     = "${aws_instance.staging.id}"
    device_index = 1
  }
}
```
### Expected Behavior

After tainting the instance I expected terraform apply to recreate the instance and attach the ENI. 
### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* aws_network_interface.staging: Error detaching ENI: InvalidAttachmentID.NotFound: The interface attachment 'eni-attach-4e6c9c89' does not exist.
    status code: 400, request id: e033f78f-2244-4dd3-9467-d57eee74e8cd
```
### Steps to Reproduce
1. `terraform apply`
2. `terraform taint aws_instance.staging`
3. `terraform apply`
### References

@catsby mentioned:
"yeah, I see it:"
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_network_interface.go#L194 
"being called from here" https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_network_interface.go#L222

**Comment by ledor473** [comment]
I'm having the same issue. 
Seems like detaching manually (via the Console or the CLI) before running Terraform fix this.

**Comment by pecastro** [comment]
+1

**Comment by pecastro** [comment]
+1

**Comment by toddrosner** [comment]
I frequently get that exact error when destroying module based stacks
