### ISSUE TITLE
Support socket reuse or expose 2 factor for Bastions w/ 2FA Enabled

### ISSUE THREAD

**Issue by zmallen** [hashicorp/terraform#6180]
I am currently deploying to a cloud provider through a company-ran Bastion. I think the Bastion support is great, but we have additional security mechanisms in place that use 2FA through our phones to authenticate to these bastions.

Generally, when we authenticate once, ssh reuses a socket state kept by the previous authenticated session so that we dont have to send another code/push to a phone. It would be great if Terraform supported this feature so we can deploy via a bastion. Another possibility would be to show the 2FA prompt from Duo for example so we can make a push to the phone, authenticate and allow the pass through.

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. While provisioners, as a whole, aren't a top priority for the team, when some time is available to focus on them we're going to use that attention to tackle some long-standing defects. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, the use cases, and needs of our practitioners.
