### ISSUE TITLE
Environment variables in .tf files

### ISSUE THREAD

**Issue by hstove** [hashicorp/terraform#62]
Hey! This is a very cool project.

I browsed all over the documentation and couldn't find a way to interpolate environment variables in a configuration file. Is this possible?

**Comment by pasviegas** [comment]
+1 to doing it like packer.

**Comment by willejs** [comment]
:+1: for packer like ${env.NAME}

**Comment by mzizzi** [comment]
:+1: for ${env.NAME} syntax

**Comment by ryancharette** [comment]
+1 for packer like ${env.NAME}

**Comment by joegoggins** [comment]
+1 for `${env.NAME}`  ! :shipit: :smile:

**Comment by mhamrah** [comment]
+1. Also, HCL is very similar to [HOCON](https://github.com/typesafehub/config#using-hocon-the-json-superset) as used by the [TypeSafe config library](https://github.com/typesafehub/config). It's not a standard, but there are probably some patterns you might find beneficial, like the hierarchy of variable substitutions across file, command line, and environment.

**Comment by mitchellh** [comment]
@mhamrah Thanks for pointing that out, I'm going to take a look!

**Comment by mbrevoort** [comment]
+1

**Comment by sparkprime** [comment]
So I have done a [writeup](http://google.github.io/jsonnet/doc/casestudy_fractal.1.html) of a casestudy of using [Jsonnet](http://google.github.io/jsonnet/doc/) on top of Terraform (+ Packer and a few other things).  In there I solve this credentials problem by importing a file from disk that is not checked into version control, this is discussed on page 2.

Jsonnet is a bit like HOCON by the way, but is more powerful and has a principled design.

**Comment by woodhull** [comment]
+1

**Comment by kilhage** [comment]
+1

**Comment by spesnova** [comment]
+1

**Comment by woodhull** [comment]
We ended up solving this by wrapping terraform in a ruby script that stuffs
env variables into var command line arguments and provisons things that
terraform does not support yet.

On Monday, March 16, 2015, Seigo Uchida <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/terraform/issues/62#issuecomment-82030930>.
>


-- 
--
This is my personal email address. If you are emailing me about
ControlShift, please send a note to nathan@controlshiftlabs.com

**Comment by dentarg** [comment]
No-one here having the problem that secrets end up in terraform.tfstate? (#516) Example: the Heroku provider stores every ENV var from Heroku (`heroku config`) in terraform.tfstate. Could be a lot of secrets...

**Comment by mitchellh** [comment]
@dentarg There is another issue where people have definitely brought this up. We're still discussing it there.

**Comment by 7heo** [comment]
Since the syntax in terraform is `type.name.attr`, wouldn't it be more logical to use `${shell.env.$NAME}`?

**Comment by delitescere** [comment]
> Since the syntax in terraform is type.name.attr, wouldn't it be more logical to use ${shell.env.NAME} (for $NAME)?
> @7heo 

No.

**Comment by mitchellh** [comment]
@7heo We have precedent for 2-element things: `${path.module}`, etc. I think that is much cleaner.

**Comment by piotr-napadlek** [comment]
Hi, sorry to be an archeologist, but is the idea of using ${env.NAME} syntax dead already? I would find it much easier than either mapping to TF_VAR_ variables or passing them through -var because that requires wrappers scripts to translate stuff that is always on my/CI environment - I could just call terraform init and terraform apply instead.

**Comment by rpatrick00** [comment]
Here is a little hack I put together to get around the lack of access to environment variables.

https://github.com/rpatrick00/terraform-provider-environment

**Comment by J7mbo** [comment]
I have a `.env` file. Terraform should just read environmental variables. I shouldn't have to change my whole env var structure just to work with terraform.
