### ISSUE TITLE
Crash on invalid configuration syntax

### ISSUE THREAD

**Issue by jonasschneider** [hashicorp/terraform#6210]
This is crashing:

    resource "aws_route_table" "private" {
      route "private-to-vpn-client" {
        destination_cidr_block = "${var.vpn_client_cidr}"
        instance_id = "${aws_instance.vpn.id}"
      }
    }

(I wanted to give the route a name, and I realise it's invalid. It shouldn't crash, though.)

Terraform v0.6.14

Crash log: https://gist.github.com/96787bb2f9503bd7cc6fa43ca050d3e3

**Comment by catsby** [comment]
Hey @jonasschneider – is there any more to this story? I tried to reproduce your example and I don't get any crashing (both using Terraform v0.6.14 and a build from `master` branch):

```hcl
resource "aws_route_table" "private" {
  route "private-to-vpn-client" {
    destination_cidr_block = "10.0.0.0/16"
    instance_id            = "id-12345"
  }
}
```

output:

```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_route_table.private: "route.0.cidr_block": required field is not set
  * aws_route_table.private: route.0: invalid or unknown key: private-to-vpn-client
  * aws_route_table.private: "vpc_id": required field is not set
```

Your crash is giving this error:

    panic: runtime error: index out of range

Sounds like some configuration syntax is using splats, or arrays of sorts. Is there anyway to share all (or more) of the configuration, minus any secrets of course, so we can look into this more? I agree that even if there were config mistakes, a crash is not right, so we'd like to dig in more

Thanks!

**Comment by jonasschneider** [comment]
Sorry, I messed with the snippet before I posted it to cut out some
parts (which I thought were harmless). I'll try to reproduce and post
a better config.

**Comment by mitchellh** [comment]
Hey @jonasschneider. Haven't heard from you in awhile and we need that repro! 

There has been a lot of changes around splats, list handling, etc. since 0.7.0 and so its likely this is either fixed or masked away somehow. If you can still repro this please help us out by just opening a new issue and we'll take a look at it. Thanks!

**Comment by jonasschneider** [comment]
Sorry for not following up. I believe this particular error turned out to be related to internal "state surgery" by us, where we manually edited the Terraform state file to avoid having to rebuild critical resources due to name/module structure changes.
