### ISSUE TITLE
triton provider key_material does not accept a file as the docs say

### ISSUE THREAD

**Issue by jhorwit2** [hashicorp/terraform#6211]
Version: current stable

As you can see in this [PR](https://github.com/hashicorp/terraform/pull/6090/files) `key_file` was changed in favor of `key_material`; however, it was does not work with a file. The private key value is passed to create a new auth object [here](https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/vendor/github.com/joyent/gosign/auth/auth.go#L54), but since it's a file name it breaks.

**Comment by phinze** [comment]
Hi @jhorwit2 - the `file()` interpolation function is the intended way to lift file contents into config. Will get the docs fixed up on this!

Should be:

```
provider "triton" {
  account      = "AccountName"
  key_material = "~/.ssh/id_rsa"
  key_id       = "25:d4:a9:fe:ef:e6:c0:bf:b4:4b:4b:d4:a8:8f:01:0f"
  # ...
}
```

**Comment by jhorwit2** [comment]
@phinze just submitted a PR #6255 for the documentation a few lines down that still references the key path.
