### ISSUE TITLE
InvalidCloudWatchLogsRoleArnException when updating aws_cloudtrail

### ISSUE THREAD

**Issue by wnkz** [hashicorp/terraform#6217]
### Terraform Version

`Terraform v0.6.14`
### Affected Resource(s)
- aws_cloudtrail
### Terraform Configuration Files

``` hcl
resource "aws_cloudtrail" "default" {
  name = "${var.trail_name}"
  s3_bucket_name = "${var.s3_bucket_id}"
  cloud_watch_logs_role_arn = "${aws_iam_role.cloudtrail_cloudwatchlogs_role.arn}"
  cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.cloudtrail_default.arn}"
  is_multi_region_trail = true
  include_global_service_events = true
}
```
### Debug Output

`plan`:

```
~ module.sandbox_cloudtrail.aws_cloudtrail.default
    cloud_watch_logs_group_arn: "arn:aws:logs:eu-west-1:REDACTED:log-group:CloudTrail/DefaultLogGroup:*" => "arn:aws:logs:eu-west-1:REDACTED:log-group:/foo/CloudTrail/DefaultLogGroup:*"
```

`apply`:  

```
* aws_cloudtrail.default: InvalidCloudWatchLogsRoleArnException: You must specify a role ARN as well as a log group.
    status code: 400, request id: b874bd0b-0566-11e6-8fb3-25e0a3e4d28a
```
### Expected Behavior

The trail should have been updated.
### Actual Behavior

`InvalidCloudWatchLogsRoleArnException` is returned, my guess is that the AWS API is requiring both `cloud_watch_logs_role_arn` and `cloud_watch_logs_group_arn` when updating and Terraform only supplies the one that changed. (http://docs.aws.amazon.com/cli/latest/reference/cloudtrail/update-trail.html)
### Steps to Reproduce
1. Create an `aws_cloudtrail` resource with both `cloud_watch_logs_role_arn` and `cloud_watch_logs_group_arn` configured
2. `terraform apply`
3. Edit the `cloud_watch_logs_group_arn` property to a different existing logs group
4. `terraform apply`
### Important Factoids

NA
### References

NA

**Comment by mdxp** [comment]
I'm seeing a very similar behavior. In my case it fails on the first run and if I run it again it will complete successfully. Very weird.

**Comment by radeksimko** [comment]
This is most likely an effect of eventually consistent IAM Role. We already have retry logic in many other places, apparently not in `aws_cloudtrail` yet. :/

**Comment by mdxp** [comment]
I can confirm that this is caused by the IAM Role not being consistent. A walkaround until `aws_cloudtrail` supports this is to add timeout on the resource.
