### ISSUE TITLE
feature request: aws_instance, block_device, volume_id

### ISSUE THREAD

**Issue by soniah** [hashicorp/terraform#622]
(On terraform dev 5d89ca).

When using the resource "aws_instance" and specifying a block_device, one of the keys is snapshot_id.

It would be useful to also be able to specify an existing volume_id.

**Comment by phinze** [comment]
You can do this today via [`aws_volume_attachment`](https://terraform.io/docs/providers/aws/r/volume_attachment.html)! :tada:

**Comment by soniah** [comment]
:+1:

**Comment by arthurschreiber** [comment]
Using `aws_volume_attachment` introduces issues with ordering when trying to delete an `aws_volume_attachment` and the `aws_instance` at the same time.

If we had the option to specify a `volume_id`, the issues described in #4643 and #2957 would not happen.
