### ISSUE TITLE
I believe aws_ebs_volume parameter "size" is not Optional

### ISSUE THREAD

**Issue by Gary-Armstrong** [hashicorp/terraform#6223]
Hi there,

### Terraform Version
Terraform v0.6.14

### Affected Resource(s)
aws_ebs_volume

### Terraform Configuration Files
```hcl
resource "aws_ebs_volume" "data_vol" {
  availability_zone = "${var.region}${var.my_zone}"
  type = "gp2"
}
```

### Expected Behavior
Documentation specifies 'size' is optional.
https://www.terraform.io/docs/providers/aws/r/ebs_volume.html

### Actual Behavior
```
* aws_ebs_volume.stage_data: Error creating EC2 volume: MissingParameter: The request must contain the parameter size/snapshot
	status code: 400, request id:
```

### Steps to Reproduce
1. Create resource as above.
2. `terraform plan`
3. Nod head.
4. `terraform apply`
5. Observe error.

### References
I searched a bit for EBS size issues, didn't see anything.  I do assume that 100% of people will actually want to specify a EBS size in their code.  I do, too, but I wanted to see what TF did when I left out the parameter.

I assume a doc update is in order.

**Comment by stack72** [comment]
Hi @Gary-Armstrong 

This is a good find - basically, 1 of size or snapshot_id is required

We can make an ammendment to the docs to support this

Thanks

Paul

**Comment by joshuaspence** [comment]
Shouldn't this requirement be enforced in code as well as documented?

**Comment by stack72** [comment]
@joshuaspence there is currently no way to have schema level validation to have 1 or another value required. The schema states that each of the params are 'optional'
