### ISSUE TITLE
Policy on new provider acceptance tests - keys for Travis CI

### ISSUE THREAD

**Issue by CpuID** [hashicorp/terraform#6228]
I just wanted to verify the policy on providing keys to the HashiCorp team for Travis CI runs on new providers?

**Comment by CpuID** [comment]
*bump* I intend to look at writing a provider, but need to confirm the policy here so I can discuss with the vendor (a CDN provider) how this part will work.

@catsby @phinze are you able to clarify as HashiCorp staff?

**Comment by jen20** [comment]
Hi @CpuID! Generally we set up a test account for SaaS providers. Some providers give us credit to use for this purpose, others don't. In general we would prefer to use our own accounts vs a contributors though. If you want to discuss this in more detail please feel free to ping us by email to discuss specifics!
