### ISSUE TITLE
Starting commands with screen or nohup are not kept running.

### ISSUE THREAD

**Issue by snorberhuis** [hashicorp/terraform#6229]
I provision several machines using Terraform. I also want to use Terraform to start the service it has to provide using ssh and a command, so that I not need something else to do this. The behaviour I expect is that Terraform is able to do this using `screen` or `nohup`:

```
provisioner "remote-exec" {
inline = "nohup sudo command &"
}
```

or

```
provisioner "remote-exec" {
 inline = "screen -d -m sudo command"
}
```

But these commands are not kept running for no apparent reason. I checked the machines and the commands are not kept running. When I ssh manually and execute the same command the commands are kept running.

You can reproduce this simply by having a terraform config with these provisioning commands and a command to your liking. 

Why can this not be done and is this a bug?

**Comment by jangrewe** [comment]
This fix worked for me: http://stackoverflow.com/questions/36207752/how-can-i-start-a-remote-service-using-terraform-provisioning

**Comment by mitchellh** [comment]
That looks like a decent workaround.

**Comment by simpsonjon** [comment]
I'm still seeing this issue. Sleeping for a few seconds is not working for me. I can see the command started but it was killed the moment the provisioner finished that line of remote-exec.

**Comment by jangrewe** [comment]
@simpsonjon just sleep probably won't be sufficient, as all processes will be killed on disconnect.

**Comment by simpsonjon** [comment]
@jangrewe Do you have a suggestion on how to handle running a command through screen/nohup and having terraform allow it to keep running?

**Comment by jangrewe** [comment]
@simpsonjon the link i posted above did work fine for me, but maybe you're doing something that won't work this way. you should probably show what you're trying to do.

**Comment by simpsonjon** [comment]
I'm in the process of learning terraform so I have a small app deploy a scaling group and performs a load test.
`
inline = [
            "sudo apt-get update",
            "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -",
            "sudo apt-get install -y nodejs",
            "cd /opt/app",
            "npm install",
            "sudo npm install -g forever",
            "nohup forever main.js --url=http://${aws_elb.web.dns_name} &",
            "sleep 1",
        ]

connection {
            type = "ssh"
            user = "ubuntu"
}
`

**Comment by snorberhuis** [comment]
@simpsonjon  I have been working on a lot of processes detaching and the same problems keep coming up. 

Some problems arise if you try to write to a `stdout` or `stderr`. These streams might be destroyed after detaching resulting in error's in your code. Some examples of this occurring might be simple prints.

**Comment by kgruszka** [comment]
Shouldn't it be reopened? I have the same problem with
```
inline = [
  "sudo nohup npm start &",
  "sleep 1"
]
```

this works fine:
```
inline = [
  "sudo forever start index.js"
]
```

**Comment by ghmulti** [comment]
@simpsonjon sleep did not work for me either, adding local-exec after remote-exec and run nohup over ssh manually worked for me though:
```
provisioner "remote-exec" {
  inline = [
    ...
  ]
  connection {
    type = "ssh"
    user = "ec2-user"
    private_key = "${file(var.aws_key_path)}"
  }
}

provisioner "local-exec" {
  command = "ssh -o 'StrictHostKeyChecking no' -i ${var.aws_key_path} ec2-user@${self.public_ip} 'nohup some-command </dev/null >/dev/null 2>&1 &'"
}
```

**Comment by omarabid** [comment]
@mitchellh The sleep "work-around" is not decent. This should be considered as a bug since it is not the expected behavior.

**Comment by vfreefly** [comment]
The problem is still present. Looks like as a solution - create and enable systemD service which will handle command

**Comment by JohnAntonusMaximus** [comment]
Is anybody on track to open a PR to fix this? Terraform is pretty pointless as an automated provisioning system if you can't run processes as daemons as you need to ssh manually to restart them. Also why is this issue closed? Definitely not a closed bug.

**Comment by VanTamNguyen** [comment]
I'm still seeing this issue in August of 2018. Terraform please fix this!

**Comment by delirius325** [comment]
This is still an issue and @omarabid is right, the workaround shouldn't be considered as the right method.

**Comment by juanjoserivera** [comment]
@mitchellh This is definitely an unexpected behavior, while "sleep 1" workaround work for me, shouldn't be standard solution.

**Comment by trihoangvo** [comment]
`Sleep 1` does not work for `npm start`. Anyone have a solution that works with `npm`?
If I use `forever`, I have to specify a js script. And I have to parse the `package.json` (which is known by `npm`) for the script.

**Comment by mgarstecki** [comment]
I managed to get this to work using a `disown` after the `nohup ...` command (as per https://superuser.com/a/705448):
```
nohup ... &; disown
```

I specifically use bash as interpreter in my commands.
