### ISSUE TITLE
Issue with new map check code 

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#6230]
Having issues with a specific commit right now - d7d39702c04b3ae5e2df0b50c6a7aa9b479d19b3.

Given a configuration snippet like this:
```hcl
variable invertbool {
  type = "map"
  default = {
    "1" = false
    "0" = true
  }
}
```

Which is then called off of something like:

```hcl
${lookup(var.invertbool, var.bool)}
```

I'm getting (paraphrased):

```
variable invertbool should be type map, got type string
```

Reverting the commit fixes the issue.

It should be noted that I am not strictly working off strings here, as these are older modules that are taking "boolean" values, that ultimately get interpolated in modules into `1` and `0`. However, in messing around with the module, I haven't been able to get past this error, even when I change everything (the inner module key variable, and the outer module parameter) to be a specific string.

Also, a bit more context as to what this is specifically doing - basically, the main application here is to create a matching ephemeral rule for `aws_network_acl_rule` resources. It's designed to flip the supplied `egress` parameter.

**Comment by glasser** [comment]
@jen20  I'm seeing this too, for a map defined in a stack like

```
variable service_region_ami {
  type = "map"
  default = {
    us-east-1 = "ami-e4c9db8e"
  }
}
```

and not actually passed in to the module definition at all.  (ie, the only mentions of this var are that declaration and one use, both inside the module.)

**Comment by jen20** [comment]
Thanks for the notes guys - seems we have some holes in the test coverage. I'll investigate this and fix prior to a point release.

**Comment by jen20** [comment]
Could you post a more detailed piece of config showing this @vancleuver? It's a bit unclear which modules things are in from the description above.

**Comment by jen20** [comment]
I think I've managed to reproduce this using the mechanism described by @glasser. Hopefully it's just one issue - I think I see what is happening.

**Comment by jen20** [comment]
OK I have a fix, but it only applies to the `dev-0.7` branch where we can nil check. I need to figure out a way to backport this to `master` branch, or revert the commit on master and leave this as something which only hits in 0.7. I am currently minded towards the latter option, but would appreciate an opinion from @phinze or @mitchellh here.

**Comment by jen20** [comment]
Only kidding, I've ported it to `master` as well. Expect a fix to land shortly with some test cases. It would be greatly appreciated if @vancluever and @glasser could verify it fixes the issues you are seeing! I assume since you had the commit in the first place you are building from source on a regular basis :-)

**Comment by glasser** [comment]
I'll try to take a peek but I'm traveling this week (and I rolled back the version we use for our projects to before this commit).

**Comment by vancluever** [comment]
@jen20, confirmed fixed over here, will monitor further and report back if there is any other issues with the module, and post the code. The module itself is is internal, and while it doesn't have anything in particularly sensitive in it, I'd just have to get it vetted for release.

Cheers!
