### ISSUE TITLE
google_compute_instance_group_manager does not get destroyed when google_compute_instance_template does, resulting in error

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#6234]
When changing metadata in google_compute_instance_template - which is set via a template_file - the depending google_compute_instance_group_manager does not get rebuilt

```
1 error(s) occurred:

* google_compute_instance_template.instance_template: Error deleting instance template: googleapi:
 Error 400: The instance_template resource 'instance-template' is already being used by '
instance-group-manager', resourceInUseByAnotherResource
```

Tainting the google_compute_instance_group_manager  still results in an error because it's simultaneously destroyed with the google_compute_instance_template, not before.
### Terraform Version

0.6.13
### Affected Resource(s)
- google_compute_instance_group_manager
- google_compute_instance_template 
- template_file
### Terraform Configuration Files

`````` hcl
resource "template_file" "template_file" {
  template = "${file("container-manifest.yml")}"
  vars {
    ...
  }
}

resource "google_compute_instance_template" "instance_template" {
    name = "instance-template"
    machine_type = "n1-standard-1"
    region = "europe-west1"

    // boot disk
    disk {
        source_image = "https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20160217"
        disk_type = "pd-standard"
        disk_size_gb = "32"
        auto_delete = true
        boot = true
    }

    network_interface {
        network = "${google_compute_network.network.name}"
        access_config {
            // Ephemeral IP
        }
    }

    metadata {
        google-container-manifest = "${template_file.template_file.rendered}"
    }
}

resource "google_compute_instance_group_manager" "instance_group_manager" {
    name = "instance-group-manager"
    instance_template = "${google_compute_instance_template.instance_template.self_link}"
    base_instance_name = "instance-group-manager"
    zone = "europe-west1-c"
    target_size = "1"

    depends_on = ["google_compute_instance_template.instance_template"]
}```

### Debug Output
https://gist.github.com/JorritSalverda/0ed5eebe2ed2e52404af7d5707a3c101

### Expected Behavior
- destroy google_compute_instance_group_manager 
- destroy google_compute_instance_template
- create google_compute_instance_template
- create google_compute_instance_group_manager 

### Actual Behavior
- destroy google_compute_instance_template
- error because it's in use by google_compute_instance_group_manager 

### Steps to Reproduce
1. change template file
2. `terraform apply`
``````

**Comment by jwaldrip** [comment]
Occurring for us as well. Makes it very hard to manage user-data....

**Comment by evandbrown** [comment]
@JorritSalverda, anticipated behavior here would be to re-create the InstanceGroupManager, correct? If so, I'll have the patch in to fix this shortly.

Thanks!

**Comment by JorritSalverda** [comment]
@evandbrown yes, I would expect the InstanceGroupManager is recreated, because in the dependency graph it should depend on the InstanceTemplate. Thx.

**Comment by evandbrown** [comment]
OK, had some time to reflect on this. Deleting and re-creating the Instance Group Manager has implications (@billf pointed out how this cascades to backend services if you use those).

In #6604 I'm proposing the use of `lifecycle.create_before_destroy` on the Instance Template. Terraform will create an updated instance template resource, update the Instance Group Manager, then destroy the previous instance template. The Instance Group Manager's [default `update_strategy`](https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#update_strategy) would result in the creation of new instances from the updated template.

To support `create_before_destroy`, I've made the Instance Template `name` optional. If omitted, an auto-generated name will be used. You may also specify a `name_prefix` which will get a uuid suffix. However, the `create_before_destroy` functionality will not work if you specify the `name`. This is basically identical to the AWS launch configuration implementation.

Finally, in your example, both the Instance Template _and_ template file resources will need the `create_before_destroy` lifecycle policy.

Thoughts?

**Comment by JorritSalverda** [comment]
Hm, this is a though one. I've actually set up a set of scripts that does deployments with GCE's http load balancer, backend services and one instance group replacing another. Getting the same functionality in terraform is probably not what we should be after on the short term.

I think though you can remove an instance group from a backend service - a service can have multiple backends - but doesn't require them to be present at all times. Hence deleting an instance group should remove the backend from the backend service, not the full service itself.

**Comment by thecodeassassin** [comment]
Will a fix for this be included in 0.7 ? I am currently circumventing this by always creating new resources by appending a uuid to the name but this is less than ideal :(

**Comment by zbikmarc** [comment]
I have exact same issue in Terraform v0.8.2

Terraform wants to remove instance template before actually removing instance groups using them. As a result it fails with following error.

```
Error applying plan:

2 error(s) occurred:

* google_compute_instance_template.cassandra_instance_template: Error deleting instance template: googleapi: Error 400: The instance_template resource 'cassandra-template-00a2373dabbe061c1b906e9669' is already being used by 'cassandra-group', resourceInUseByAnotherResource
* google_compute_instance_template.rest_instance_template: Error deleting instance template: googleapi: Error 400: The instance_template resource 'rest-template-00a2373dabbe061c1b906e966a' is already being used by 'rest-group', resourceInUseByAnotherResource
```
I tried to change update_strategy from NONE to RESTART and otherwise but no result.

**Comment by zbjornson** [comment]
I've hit the same (or similar) problem. In our case, a template_file is not involved.

The discussion above talks about destroying the instance group as part of the solution. However, you can change the instance template assigned to a GCE instance group. Thus, I think the correct behavior is actually:

1. Create new instance template.
2. Change instance group to use new template.
3. Delete old instance template.

This is also how GCE does [rolling updates](https://cloud.google.com/compute/docs/instance-groups/updating-managed-instance-groups) -- it changes the template without destroying/recreating the MIG.

Our workaround has been:

1. Change instance template in .tf file
2. `terraform state rm <the instance template's identifier>`
3. `terraform apply`
4. manually delete old template.

which prevents TF from trying to delete the in-use template.

**Comment by zbikmarc** [comment]
My latest observations:
I'm unable to delete instance template because it is used by instance group (obviously) in all Google Cloud regions **except europe-west1** where it works flawlessly.

My template:

```
variable "region" {
    type    = "string"
    default = "europe-west1"
}

variable "zone" {
    type    = "string"
    default = "europe-west1-c"
}

variable "image" {
    type    = "string"
    default = "ubuntu-os-cloud/ubuntu-1604-lts"
}

provider "google" {
  credentials = "${file("/path/to/credentials.json")}"
  project     = "MyProject"
  region      = "${var.region}"
}

resource "google_compute_instance_group_manager" "instance-group" {
  name        = "instances-group"
  description = "instance group"

  base_instance_name = "rest"
  instance_template = "${google_compute_instance_template.instance-template.self_link}"

  update_strategy = "NONE"
  zone            = "${var.zone}"

  target_size  = 2
}

resource "google_compute_instance_template" "instance-template" {
  name_prefix  = "instance-template-"
  machine_type = "f1-micro"
  region       = "${var.region}"

  tags = ["internal", "http-server"]

  disk = {
    source_image = "${var.image}"
  }

  network_interface = {
    network = "default"
  }

 // I thought those two lines are causing problems but no
 // metadata_startup_script = "${file("metadata_startup_scripts.sh")}"
 // metadata_startup_script = "echo test > /tmp/test

}

```

**Comment by ctindel** [comment]
@evandbrown It's hard to tell if this bug should be closed by PR 6604 or not.  The PR says it addresses this issue, but this issue is still open and it seems like the problem still exists in the most recent 0.8.6.

Please advise?

**Comment by universalvishwa** [comment]
Problem is still there even in terraform 0.11.10

**Comment by JackDavidson** [comment]
This is also still a problem for me.

**Comment by partdavid** [comment]
This is also a problem still for me, it makes it impossible to straightforwardly make changes to instance templates (like startup-scripts and base instance config). The desired behavior is as described by @zbjornson . We have to follow the state surgery workaround he describes above.
