### ISSUE TITLE
etag for AWS lambda resource

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#6236]
Hi there,

I'm creating lambda function with terraform with the following configuration:

```
resource "aws_lambda_function" "ecs_autoscale_lambda" {
  depends_on = [ "null_resource.ecs_autoscale_lambda_template_zip" ]
  filename = "environments/${var.environment_name}/lambdas/ecs_autoscale.zip"
  function_name = "tf-${var.service_name}-${var.environment_name}_ecs_autoscale"
  role = "${aws_iam_role.iam_role.arn}"
  runtime = "nodejs"
  timeout = "8"
  handler = "example.handler"
}
```

When terraform runs for the first time when lambda doesn't exist than all works fine -- terraform creates new lambda function from ecs_autoscale.zip file. But in case ecs_autoscale.zip is updated and terraform is applied -- nothing happens, terraform doesn't detect changes and does nothing with lambda in AWS.

In there any way to enable etag for lambda (like it's done for s3 object) to make it possible for terraform to track changes in lambda code and update it when it's necessary.

Thank you.

P.S. I'm using terraform 0.6.14.

**Comment by apparentlymart** [comment]
Hi. @anosulchik!

I believe the equivalent of `etag` for Lambda functions is `source_code_hash`, which can be set this way:

```hcl
    source_code_hash = "${base64sha256(file("environments/${var.environment_name}/lambdas/ecs_autoscale.zip"))}"
```

**Comment by radeksimko** [comment]
Even though it's mentioned in the docs it probably isn't as visible as it can be, I guess?
https://www.terraform.io/docs/providers/aws/r/lambda_function.html#source_code_hash

Users may not realise that there are some (not entirely straightforward) steps required to make updates work with `filename`.

**Comment by adriamorgado** [comment]
Hi there,

I am creating an `aws_lambda_function` resource and I am just wondering whether the `source_code_hash` argument expects the zip file containing the lambda function source code to be present during the execution plan step.

In my case, the lambda resource depends on a null resource that will, in the first place, execute a script to pull the zip files from a Git repository, as it follows:

```
resource "null_resource" "lambda_function" {
    provisioner "local-exec" {`
        command = "./get_lambda_functions.sh"
    }
}

resource "aws_lambda_function" "lambda-function" {
    depends_on = [ "null_resource.lambda_function" ]
    filename = "lambda.zip"
    [...]
    source_code_hash = "${base64sha256(file("lambda.zip"))}"
```

However, I am getting the following error when running `terraform plan`:

```
Errors:

  * file: open SetAlarm.zip: no such file or directory in:

${base64sha256(file("lambda.zip"))}
```

Thanks!

**Comment by catsby** [comment]
Hello – as Radek and Martin have mentioned please use the `source_code_hash` for this behavior. Thanks!
