### ISSUE TITLE
Feature request - Support for Instance creation across Availability Zones while using count

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#6239]
Support for Instance creation across Availability Zones while using count. So for example specify what AZ's are in play and set count to 2. During instance creation terraform will evenly create distribute instance across AZ's

**Comment by jrnt30** [comment]
If you enumerate the list of AZs in a comma delimited list as a variable, you can use the count and the split/lookup feature to grab the "associated" AZ from there.  In addition, the lookup function will roll over to the start if the count exceeds the length of the array which allows you to "round robin" between all of your AZs

**Comment by davyt10** [comment]
Would you be able to provide an example? Thanks in advance.

**Comment by jrnt30** [comment]
```

resource "aws_instance" "mongo" {
  count                  = "${var.instance_count}"
  ami                    = "${var.ami}"
  instance_type          = "${var.instance_type}"
  key_name               = "${var.key_name}"
  iam_instance_profile   = "${var.iam_instance_profile}"
  user_data              = "${template_file.userdata.rendered}"
  subnet_id              = "${element(split(",",var.data_subnet_ids),count.index)}"
  vpc_security_group_ids = ["${aws_security_group.mongo.id}"]
}
```

**Comment by jen20** [comment]
Hi @davyt10! @jrnt30's example is correct - you can use `element`, `count.index` and a list of availability zones to distribute among here. Another way to achieve this is to use an autoscaling group. If you have any further questions here please feel free to reopen the issue!
