### ISSUE TITLE
SIGTERM results in zombie processes

### ISSUE THREAD

**Issue by freefood89** [hashicorp/terraform#6248]
Terminating `terraform plan` while it's trying to grab resources from AWS  results in unreaped zombies

### Terraform Version
v0.6.9

### Affected Resource(s)
N/A

### Terraform Configuration Files
N/A

### Debug Output
[debug gist](https://gist.github.com/freefood89/2e19cf26b21ebb177002726e9f720168)
[ps aux gist](https://gist.github.com/freefood89/cee9e3a08526826a47b65dde68c7382a)

### Panic Output
N/A

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. ctrl+c while it's struggling to call AWS APIs:

    2016/04/19 14:48:54 [DEBUG] vertex aws_launch_configuration.asg_lc, waiting for: provider.aws 
    2016/04/19 14:48:54 [DEBUG] vertex aws_elb.asg_elb, waiting for: provider.aws
    2016/04/19 14:48:54 [DEBUG] vertex root, waiting for: provider.aws (close)

3. repeat many times

### Important Factoids
In my network AWS APIs are called through a proxy, which I forgot to specify in the environment variables. These zombies resulted from canceling these erroneous `terraform plan` calls.

**Comment by doertedev** [comment]
I have a general question regarding anything ec2 related, but maybe a general terraform question:

Can it be that terraform recognizes the "abort" but then can somehow "get lost" in cleaning up after itself? 

```
$ terraform apply

terraform_remote_state.s3state: Refreshing state... (ID: 2016-06-29 08:56:39.102469213 +0000 UTC)
^C^C^C^C^Caws_iam_group_membership.xxx: Refreshing state... (ID: xxx-group-membership)
aws_security_group.sg-xxx: Refreshing state... (ID: sg-xxx)
aws_vpc.vpc-xxx: Refreshing state... (ID: vpc-xxx)
aws_iam_group.xxx: Refreshing state... (ID: xxx)
aws_iam_group.xxx: Refreshing state... (ID: xxx)
aws_iam_user.xxx: Refreshing state... (ID: xxx)
aws_iam_user_policy.xxx: Refreshing state... (ID: xxx)
aws_iam_user_ssh_key.xxx: Refreshing state... (ID: xxx)
aws_iam_group_membership.xxx: Refreshing state... (ID: xxx-group-membership)
aws_key_pair.xxx: Refreshing state... (ID: xxx)
aws_security_group.sg-xxx: Refreshing state... (ID: sg-xxx)
aws_subnet.xxx: Refreshing state... (ID: subnet-xxxx)
Interrupt received. Gracefully shutting down...
Two interrupts received. Exiting immediately. Note that data
loss may have occurred.
```

Basically this seems that it realizes I aborted right from the start but doesn't seem to care. 

This is confusing when applying the wrong plan by mistake: everything gets created according to the plan, but then it says "note that data loss may have occurred". So I ask myself - did he actually create it now? 

This either is a bug, a misleading notice or I'm misunderstanding.

Thanks in advance.

**Comment by mitchellh** [comment]
This should be fixed up now with the latest version of our plugin system.
