### ISSUE TITLE
updating count var changes existing resources (openstack)

### ISSUE THREAD

**Issue by dod83** [hashicorp/terraform#6250]
Hello,

While updating the var count (using the openstack provider) from 1 to 2 the following happens:

test> terraform plan -parallelism=1 Refreshing Terraform state prior to plan...

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ module.fe_node.commone_node
    3 resource(s)

Plan: 2 to add, 1 to change, 0 to destroy.

The "1 to change" causes some heavy confusion as it actually takes the existing block volume and switches it up with the new one. So at the end the new instance gets the existing volume and the old instance gets the new volume.

When I switch the count var to 1 again it says no changes to be made so I guess the state file is valid and knows the correct state of the block volumes and compute instances.

What can go wrong? is there a more safe way to add nodes (increase the count var) to an already existing environment?

Thanks,
D.

**Comment by jtopjian** [comment]
@dod83 This is most likely related to bug #3449. You can be absolutely sure if you're using other interpolation functions with `count` such as `element`. Can you confirm if this is the case?

**Comment by dod83** [comment]
Hi @jtopjian ,

Yes we are using elements in compute instance:

 volume {
    volume_id = "${element(openstack_blockstorage_volume_v1.data-volume.*.id, count.index + 1)}"
        device = "/dev/vdb"
 }

Is this a know bug or was it fixed in the latest versions?

Thanks,
D.

**Comment by jtopjian** [comment]
@dod83 Thanks for confirming 😄 

It's definitely a known bug and being actively worked on. I'm going to close this issue in favor of #3449, but please let me know if you have any other questions!

**Comment by dod83** [comment]
Thanks! I will be watching #3449 and testing again with the fixed version.
