### ISSUE TITLE
Dynect "convenient" client cannot create NS records

### ISSUE THREAD

**Issue by syskill** [hashicorp/terraform#6252]
This omission is decidedly inconvenient for me.
### Terraform Version

Terraform v0.6.12; doesn't look like this has been fixed in master.
### Affected Resource(s)
- dyn_record
### Terraform Configuration Files

``` hcl
resource "dyn_record" "dev_ns_0" {
    zone = "example.com"
    name = "dev"
    type = "NS"
    value = "${aws_route53_zone.dev.name_servers.0}"
}
```
### Expected Behavior

As indicated by `terraform plan` output:

```
+ dyn_record.dev_ns_0
    fqdn:  "" => "<computed>"
    name:  "" => "dev"
    ttl:   "" => "0"
    type:  "" => "NS"
    value: "" => "ns-1337.awsdns-42.com"
    zone:  "" => "example.com"
```
### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* dyn_record.dev_ns_0: Failed to create Dyn record: Failed to create Dyn RData: Invalid Dyn record type: NS
```

**Comment by eploko** [comment]
Stumbled upon this in v0.6.16 as well.

**Comment by brandoconnor** [comment]
Looks like any record outside of A, AAAA, CNAME, TXT, and SPF are rejected outright: https://github.com/hashicorp/terraform/blob/master/vendor/github.com/nesv/go-dynect/dynect/convenient_client.go#L150

I'll look to submit a PR covering NS records.
