### ISSUE TITLE
Need way to specify tags to be left as-is

### ISSUE THREAD

**Issue by ecweaver** [hashicorp/terraform#626]
Our application sets its own AWS instance  tags.  TF strips them off when Apply is run again.  

We need some way to specify "This tag => don't care".  

For example we set Name ourselves and it's not in the template. 
How about:
   Name => [ ]
meaning tag Name: stet

**Comment by phinze** [comment]
This can be accomplished today via the [`ignore_changes` metaparameter](https://terraform.io/docs/configuration/resources.html#ignore_changes).

```tf
resource "aws_instance" "foo" {
  // ...
  tags {
    "intial" = "value"
  }
  ignore_changes = ["tags"]
}
```
