### ISSUE TITLE
Failure changing number_of_nodes count on aws_redshift_cluster resource

### ISSUE THREAD

**Issue by bsiegel** [hashicorp/terraform#6274]
It appears that the `number_of_nodes` value for a `aws_redshift_cluster` can't be changed once created.

### Terraform Version
0.6.14

### Affected Resource(s)
- aws_redshift_cluster

### Terraform Configuration Files
```hcl
resource "aws_redshift_cluster" "default" {
  cluster_identifier           = "test"
  database_name                = "test"
  master_username              = "test"
  master_password              = "testtest123"
  node_type                    = "dc1.large"
  number_of_nodes              = "2"
  cluster_subnet_group_name    = "${aws_redshift_subnet_group.private.id}"
  vpc_security_group_ids       = ["${aws_vpc.default.default_security_group_id}"]
  publicly_accessible          = "false"
  preferred_maintenance_window = "sun:00:00-sun:02:00"
  encrypted                    = "true"
}
```

### Expected Behavior
Redshift cluster size updated from 2 to 3

### Actual Behavior
```
Error applying plan:

1 error(s) occurred:

* aws_redshift_cluster.default: [WARN] Error modifying Redshift Cluster (test): InvalidParameterCombination: No modifications were requested
        status code: 400, request id: 973b43d7-076a-11e6-8145-a7ce291aa817
```

### Steps to Reproduce
1. Update `number_of_nodes`from `2` to `3`
1. Do a `terraform apply`

**Comment by bsiegel** [comment]
This is probably the cause, from the [docs](https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html):

> When using the API, you have to specify the node type, node size, and the number of nodes even if you only change one of the two.

**Comment by stack72** [comment]
Hi @bsiegel 

Thanks for the bug report on this one, I am currently looking into it

Paul

**Comment by stack72** [comment]
Hi @bsiegel 

Was able to reproduce the failure easily with a new test - will implement the new functionality now and then PR it. Quick question though - what happens if the user changes both the number of nodes && and node_type (i.e. from dc1.large to dc1.xlarge)

Will it resize the entire cluster?

```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSRedshiftCluster_updateNodeCount' 2>~/tf.log
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /vendor/)
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestAccAWSRedshiftCluster_updateNodeCount -timeout 120m
=== RUN   TestAccAWSRedshiftCluster_updateNodeCount
--- FAIL: TestAccAWSRedshiftCluster_updateNodeCount (602.85s)
	testing.go:172: Step 1 error: Error applying: 1 error(s) occurred:

		* aws_redshift_cluster.default: [WARN] Error modifying Redshift Cluster (tf-redshift-cluster-3599417419286307578): InvalidParameterCombination: No modifications were requested
			status code: 400, request id: aef5f463-0827-11e6-bf7b-3b003af9e5ca
FAIL
exit status 1
FAIL	github.com/hashicorp/terraform/builtin/providers/aws	602.870s
```

**Comment by stack72** [comment]
@bsiegel  I have just opened a PR that fixes this

Paul
