### ISSUE TITLE
aws_subnet.cidr_block stored in state does not match input

### ISSUE THREAD

**Issue by oillio** [hashicorp/terraform#6285]
The cider_block field in the state has leading '0' truncated from ip octets.  However, when comparing against the defined resource, it compares against the raw value.  If there are leading '0' in the resource definition, it leads to an infinite update loop.

For example:
```
resource "aws_subnet" "public-a" {
  vpc_id = "${var.vpc}"
  cidr_block = "172.30.00.0/24"
  availability_zone = "us-east-1a"
}
```

leads to the following:
```
-/+ aws_subnet.public-a
    availability_zone:       "us-east-1a" => "us-east-1a"
    cidr_block:              "172.30.0.0/24" => "172.30.00.0/24" (forces new resource)
    map_public_ip_on_launch: "false" => "0"
    vpc_id:                  "vpc-XXXXXX" => "vpc-XXXXXX"
```

**Comment by catsby** [comment]
Hey @oillio – the AWS API is normalizing that IP address; Terraform is not modifying it. We're sending `172.30.00.0/24` and getting back `172.30.0.0/24`, and storing that value, thus the change is picked up when re-reading your configuration. 

I don't believe that 172.30.00.0/24 itself is a valid cidr block. We do cidr block validation on VPC resources, for instance, and perhaps we should do that here as well, but that would still leave you stuck 😦

**Comment by oillio** [comment]
Obviously you can do whatever you want, and this is a minor issue.  I have a workaround.

Having said that, I would argue that this is a sign of a systemic issue with trying to detect state changes by effectivly diffing an AWS API request with an AWS API result.
I have run into related issues a number of times.  The new elasticbeanstalk support is full of them.  As well as #2879, #4097, #4273, #6289, and #6158.
