### ISSUE TITLE
ConfigDocument JSON always triggers change with whitespace

### ISSUE THREAD

**Issue by artburkart** [hashicorp/terraform#6289]
Hi there,
### Terraform Version

``` console
$ terraform version
Terraform v0.6.14
```
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_elastic_beanstalk_environment
### Terraform Configuration Files

Doesn't trigger change

``` hcl
  setting = {
    namespace = "aws:elasticbeanstalk:healthreporting:system"
    name = "ConfigDocument"
    value = <<EOF
{"Version":1,"CloudWatchMetrics":{"Instance":{"ApplicationRequestsTotal":60},"Environment":{"ApplicationRequests5xx":60,"ApplicationRequests4xx":60,"ApplicationRequests2xx":60}}}EOF
  }
```

Triggers change

``` hcl
  setting = {
    namespace = "aws:elasticbeanstalk:healthreporting:system"
    name = "ConfigDocument"
    value = <<EOF
    {
    "CloudWatchMetrics": {
      "Environment": {
        "ApplicationRequests2xx": 60,
        "ApplicationRequests5xx": 60,
        "ApplicationRequests4xx": 60
      },
      "Instance": {
        "ApplicationRequestsTotal": 60
      }
    },
    "Version": 1
    }
    EOF
  }
```
### Expected Behavior

`terraform plan` shouldn't expect a change with this config setting
### Actual Behavior

Every time I run `terraform plan`, a change is expected, except when I copy and paste the output of the `terraform plan` and use it in the JSON keys in the exact same order without any whitespace.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. `terraform plan`
### Important Factoids

Nothing special
### References

Similar to [6257](https://github.com/hashicorp/terraform/issues/6257), but not the same.

**Comment by daveadams** [comment]
See also #3634. I think the solution for many of these JSON issues will be for Terraform to parse the JSON from either end and compare the resulting data structure instead of just comparing the JSON strings. AWS clearly isn't always storing these documents internally as strings, but is regenerating the JSON on the fly for a describe.

**Comment by mrooney** [comment]
Seeing this also with Terraform 0.7.2. Thanks for the embedded EOF workaround, it solves the problem for now, though it would be awesome to have newlines or load from a separate JSON file without the newlines being an issue :)

**Comment by ethangunderson** [comment]
Still seeing this in v0.8.6, but the EOF workaround is not working for me.
