### ISSUE TITLE
"aws_directory_service_directory" plan causes a panic if the resource is deleted manually

### ISSUE THREAD

**Issue by asvoboda** [hashicorp/terraform#6292]
Hi there,

### Terraform Version
Terraform version: 0.6.14

### Affected Resource(s)
- aws_directory_service_directory

### Terraform Configuration Files
```hcl
resource "aws_directory_service_directory" "microsoft-ad" {
  name = "${var.ad-fqdn}"
  password = "whatever"
  size = "Small"
  type = "MicrosoftAD"

  vpc_settings {
    vpc_id = "${var.vpc-id}"
    subnet_ids = [ "${element(split(",", var.public-mgmt-subnet-ids), 0)}", "${element(split(",", var.public-mgmt-subnet-ids), 1)}" ]
  }
}
```

### Debug Output
https://gist.github.com/asvoboda/0f1fb8bbc7267aa12d5c59b37f249e6d

### Expected Behavior
Terraform continues merrily on its way, just as it does for any resource that was manually deleted.

### Actual Behavior
Terraform panics and crashes.

### Steps to Reproduce
1. `terraform apply` and creates a ds resource
2. Delete that resource manually and wait until it is fully removed. 
3. `terraform plan`, and terraform panics

**Comment by stack72** [comment]
Hi @asvoboda 
thanks for the bug report. I have just submitted a PR that will fix this. It will be released as part of 0.6.15

Paul
