### ISSUE TITLE
ignoring user_data changes silently recreates aws_instances because of user_data changes

### ISSUE THREAD

**Issue by nkonopinski** [hashicorp/terraform#6296]
### Terraform Version
Terraform v0.6.14
Terraform v0.6.15-dev (4345c0819496896896612c159bd1982bcb7349ff)

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
resource "aws_instance" "web" {
  lifecycle {
    ignore_changes = ["user_data"]
  }

### Expected Behavior
tf should respect ignore_changes for user_data and not re-create instances when the user_data value changes.

### Actual Behavior
tf plan reports a new hash for user_data on all aws_instances, which forces new resources. This is irritating because there have been no changes made to the user_data template. The final output of the plan says it will add and destroy the number of aws_instances which are currently running.

As a work around to this bug, I added ignore_changes user_data to aws_instances in main.tf. Now tf plan does not report any differences for user_data on aws_instances. In fact it doesn't even list the aws_instances in the plan output. It does, however, list the same number of resources it will add and destroy on the last line of the plan.  As a safe guard to doing anything horrible, I added prevent_destroy = true to the aws_instances. Now when I run plan I receive error messages reading "the plan would destroy this resource" for all aws_instances.

### Important Factoids
The state files were originally created with an older version of tf but I don't remember the exact version, probably somewhere around 0.6.8

**Comment by stack72** [comment]
Hi @nkonopinski 

thanks so much for the bug report here. Unfortunately, we are currently tracking this issue right now as it has bitten a few people. I am going to link this to the major issue we opened to track it's progress and then close this as a duplicate. The details here will certainly help 

Thanks again

Paul
