### ISSUE TITLE
vSphere provider doesn't work correctly if secondary/alias addresses are added

### ISSUE THREAD

**Issue by deasmi** [hashicorp/terraform#6326]
I am using aliases/secondary IP addresses for some services which get added by puppet rather than configured but the vSphere template.

As such when I re-run terraform plan it detect the IP address and then think it needs to make a change.

I think this is a bug as these are not the primary addresses as can be seen here.

```
[deasmi@desktop:~/projects/terraform-zelotus] $ terraform plan zelotus.com/
Refreshing Terraform state prior to plan...

<.. CUT...>
vsphere_virtual_machine.orch1: Refreshing state... (ID: terraform/orch1)
<.. CUT ..>

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ vsphere_virtual_machine.orch1
    network_interface.0.ipv4_address:       "192.168.xx.50" => "192.168.xx.27"
    network_interface.0.ipv4_prefix_length: "32" => "24"


Plan: 0 to add, 1 to change, 0 to destroy.
[deasmi@desktop:~/projects/terraform-zelotus] $

```

On the server itself 

```
[root@orch1:~] # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:9e:c5:85 brd ff:ff:ff:ff:ff:ff
    inet 192.168.xx.27/24 brd 192.168.xx.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet 192.168.xx.50/24 brd 192.168.xx.255 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 XXXX:XXXX:XXXX::27/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe9e:c585/64 scope link
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:9e:0a:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.yy.27/24 brd 192.168.yy.255 scope global ens224
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe9e:a60/64 scope link
       valid_lft forever preferred_lft forever
[root@orch1:~] #
```

So it's picking up the 192.168.xx.50 secondary as the primary address and wanting to change it.

**Comment by jen20** [comment]
Hi @deasmi! Thanks for opening an issue here, I'd agree this probably is a bug. The thing to investigate here is what the vSphere API returns as the "primary" vs "other" IP addresses, and whether or not there is a way of distinguishing them.

**Comment by chrislovecnm** [comment]
@jen20 this may be our network ip wait issue ..

**Comment by chrislovecnm** [comment]
@deasmi can you use govc to verify that the API is seeing the IP address change?  It is a command line tool that is based off of the same API.  Located [here](https://github.com/vmware/govmomi/tree/master/govc).  We are having some challenges with networking, but mostly on read during creation of the vm.

**Comment by deasmi** [comment]
So that's interesting. 

govc returns the single original IP address, whereas looking in the vSphere console ( via vmware tools ) all of the IP addresses are shown.

However looking at the govc source, with my very limited understanding of the language, it seems it would only ever return one IP address anyway?

https://github.com/vmware/govmomi/blob/master/govc/vm/ip.go

**Comment by chrislovecnm** [comment]
@deasmi I recommend that we work with the owners of govmomi figuring this out. Do you mind filing an issue with them and keeping this one open?

Thanks Chris

**Comment by chrislovecnm** [comment]
@deasmi any ideas to my previous comment?

**Comment by deasmi** [comment]
@chrislovecnm still investigating. Reading the gonmomi it seems to be calling out to command line stuff. Trying to get under the hood to see what that returns as if that's incorrect then doubt this is fixable.

**Comment by chrislovecnm** [comment]
So we are bumping the govmomi version. And let me know when and if you have an issue in with them. We have some assisrtance by VMware on this.

**Comment by deasmi** [comment]
Not sure govc is using the API in the same was as it is showing the original IP address and not the additional one. .27 is the correct original address. 


```[deasmi@build:/build/dean/goworkspace] $ govc vm.ip -vm.ipath=/London/vm/terraform/orch1 -dc=London
192.168.XX.27
[deasmi@build:/build/dean/goworkspace] $```

Terraform is still complaining about the .50 alias.


```~ vsphere_virtual_machine.orch1
    network_interface.0.ipv4_address:       "192.168.45.50" => "192.168.45.27"
    network_interface.0.ipv4_prefix_length: "32" => "24"```

Latest terraform dev and govc as of today.

**Comment by deasmi** [comment]
Ok, actually with a bit more poking, govc is returning  all the IP addresses correctly. So I think this is a terraform bug.

````
[deasmi@build:~] $ govc vm.ip -vm.ipath=/London/vm/terraform/orch1 -dc=London -v4=false -a=true
192.168.45.27,192.168.45.50,fe80::250:56ff:fe9e:c585,2001:470:959a::27,192.168.46.27,fe80::250:56ff:fe9e:a60
[deasmi@build:~] $
```

The -v4=false and -a=true flags

**Comment by chrislovecnm** [comment]
@thetuxkeeper this is probably vsphere changing the damn ids ....  Ideas?

cc: @markpeek

**Comment by thetuxkeeper** [comment]
@chrislovecnm I think it's a problem how it's implemented. Right now the last IP found is saved/returned by the read function. 

I don't see much information in the API (vCenter API webinterface and `guest.net` subtree), only `ipAddress`, `prefixLength` and `state`. So it's hard to determine the "primary" IP. We would have to assume that the order won't change and use the first. For IPv6 the `fe80::/64` link-local address is the first entry. So you have to use the second entry for IPv6.
I think the best way would be to implement the support of multiple IPs per interface. At least storing all IPs in the tfstate file as first step (later setting/updating multiple per interface).

Additionally there seems to be a bug in the vmware API (vSphere/vCenter 5.5 Update 3 here) since the IPv4 prefix length is always 32 for secondary IPs (doesn't matter if `ip addr add` or `ifconfig` is used). I used the vCenter webinterface, so it's not problem of govmomi or terraform.
