### ISSUE TITLE
create_before_destroy causes apply summary to be incorrect

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#6327]
If I change a Terraform resource that causes the resource to be recreated (e.g. `(forces new resource)`), the value of `create_before_destroy` will alter the apply summary causing it to match the plan summary or causing it to not match. Specifically, `create_before_destroy = true` will mask the destroyed resource from being counted for the apply summary.
##### With create_before_destroy = false

Plan and apply **match**:

`Plan: 1 to add, 0 to change, 1 to destroy.`
`Apply complete! Resources: 1 added, 0 changed, 1 destroyed.`
##### With create_before_destroy = true

Plan and apply **do not** match:

`Plan: 1 to add, 0 to change, 1 to destroy.`
`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

Gist with config and sample logs - https://gist.github.com/clstokes/4f634769f0647b6c1e2f04bcc78c8b91.

**Comment by mitchellh** [comment]
Reproduced, thanks for the easy steps.

**Comment by mitchellh** [comment]
Have a fix in referenced PR.
