### ISSUE TITLE
Internal error when metadata refers to variable

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#634]
The following tf file yields the error below:

    provider google {
        account_file = "service_account_key.json"
        client_secrets_file = "service_account_key.json"
        project = "XXXXXXXXXXXXXX"
        region = "us-central1"
    }
    resource "google_compute_address" "test" {
        name = "test"
    }
    resource "google_compute_instance" "default" {
        name = "test"
        machine_type = "n1-standard-1"
        zone = "us-central1-a"
        disk {
            image = "debian-7-wheezy-v20140814"
        }
        network {
            source = "default"
        }
        metadata {
            foo = "${google_compute_address.test.address}"
        }
    }

2014/12/09 15:30:00 [INFO] Terraform version: 0.3.2 dev bf3d16a260b2fe261075b824e8a89f9ffe286770
2014/12/09 15:30:00 Detected home directory from env var: /home/dcunnin
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: aws = /home/dcunnin/go-workspace/bin/terraform-provider-aws
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: cloudflare = /home/dcunnin/go-workspace/bin/terraform-provider-cloudflare
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: consul = /home/dcunnin/go-workspace/bin/terraform-provider-consul
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: digitalocean = /home/dcunnin/go-workspace/bin/terraform-provider-digitalocean
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: dnsimple = /home/dcunnin/go-workspace/bin/terraform-provider-dnsimple
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: google = /home/dcunnin/go-workspace/bin/terraform-provider-google
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: heroku = /home/dcunnin/go-workspace/bin/terraform-provider-heroku
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: mailgun = /home/dcunnin/go-workspace/bin/terraform-provider-mailgun
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: null = /home/dcunnin/go-workspace/bin/terraform-provider-null
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: file = /home/dcunnin/go-workspace/bin/terraform-provisioner-file
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: local-exec = /home/dcunnin/go-workspace/bin/terraform-provisioner-local-exec
2014/12/09 15:30:00 [DEBUG] Discoverd plugin: remote-exec = /home/dcunnin/go-workspace/bin/terraform-provisioner-remote-exec
2014/12/09 15:30:00 Detected home directory from env var: /home/dcunnin
2014/12/09 15:30:00 [DEBUG] Attempting to open CLI config file: /home/dcunnin/.terraformrc
2014/12/09 15:30:00 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2014/12/09 15:30:00 [DEBUG] Creating graph for path: [root]
2014/12/09 15:30:00 [DEBUG] Starting plugin: /home/dcunnin/go-workspace/bin/terraform-provider-google []string{"/home/dcunnin/go-workspace/bin/terraform-provider-google"}
2014/12/09 15:30:00 Detected home directory from env var: /home/dcunnin
2014/12/09 15:30:00 [DEBUG] Waiting for RPC address for: /home/dcunnin/go-workspace/bin/terraform-provider-google
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 Plugin address: unix /tmp/tf-plugin087511946
2014/12/09 15:30:00 [DEBUG] Graph [root] created and valid. 4 nouns.
2014/12/09 15:30:00 [DEBUG] Creating graph for path: [root]
2014/12/09 15:30:00 [DEBUG] Graph [root] created and valid. 4 nouns.
2014/12/09 15:30:00 [INFO] Validating provider: google
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: expanding to count = 1
2014/12/09 15:30:00 [INFO] Validating resource: google_compute_address.test
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: expanding to count = 1
2014/12/09 15:30:00 [INFO] Validating resource: google_compute_instance.default
2014/12/09 15:30:00 [INFO] Writing backup state to: terraform.tfstate.backup
2014/12/09 15:30:00 [DEBUG] Creating graph for path: [root]
2014/12/09 15:30:00 [DEBUG] Graph [root] created and valid. 4 nouns.
2014/12/09 15:30:00 [INFO] Configuring provider: google
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO] Requesting Google token...
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Email: 1005268309260-dnidkmrpu9kvkvopi3l52sjluq75gimp@developer.gserviceaccount.com
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Scopes: https://www.googleapis.com/auth/compute
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Private Key Length: 916
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Token URL:
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO] Instantiating GCE client...
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: expanding to count = 1
2014/12/09 15:30:00 [INFO] Module root walking: google_compute_address.test (Graph node: google_compute_address.test)
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: Not refreshing, ID is empty
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: expanding to count = 1
2014/12/09 15:30:00 [INFO] Module root walking: google_compute_instance.default (Graph node: google_compute_instance.default)
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: Not refreshing, ID is empty
2014/12/09 15:30:00 [DEBUG] Creating graph for path: [root]
2014/12/09 15:30:00 [DEBUG] Graph [root] created and valid. 4 nouns.
2014/12/09 15:30:00 [INFO] Configuring provider: google
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO] Requesting Google token...
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Email: 1005268309260-dnidkmrpu9kvkvopi3l52sjluq75gimp@developer.gserviceaccount.com
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Scopes: https://www.googleapis.com/auth/compute
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Private Key Length: 916
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Token URL:
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO] Instantiating GCE client...
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: expanding to count = 1
2014/12/09 15:30:00 [INFO] Module root walking: google_compute_address.test (Graph node: google_compute_address.test)
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: Executing diff
2014/12/09 15:30:00 [DEBUG] google_compute_address.test: Diff: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "selfLink":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x2}}, Destroy:false, DestroyTainted:false}
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: expanding to count = 1
2014/12/09 15:30:00 [INFO] Module root walking: google_compute_instance.default (Graph node: google_compute_instance.default)
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: Executing diff
2014/12/09 15:30:00 [DEBUG] google_compute_instance.default: Diff: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"metadata_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "tags_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "zone":*terraform.ResourceAttrDiff{Old:"", New:"us-central1-a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "disk.0.image":*terraform.ResourceAttrDiff{Old:"", New:"debian-7-wheezy-v20140814", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "disk.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.0.internal_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "can_ip_forward":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.0.name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x2}, "metadata.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.source":*terraform.ResourceAttrDiff{Old:"", New:"default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "machine_type":*terraform.ResourceAttrDiff{Old:"", New:"n1-standard-1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.0.external_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
2014/12/09 15:30:00 [INFO] Apply walk starting
2014/12/09 15:30:00 [DEBUG] Creating graph for path: [root]
2014/12/09 15:30:00 [DEBUG] Graph [root] created and valid. 4 nouns.
2014/12/09 15:30:00 [INFO] Configuring provider: google
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO] Requesting Google token...
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Email: 1005268309260-dnidkmrpu9kvkvopi3l52sjluq75gimp@developer.gserviceaccount.com
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Scopes: https://www.googleapis.com/auth/compute
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Private Key Length: 916
2014/12/09 15:30:00 terraform-provider-google: 2014/12/09 15:30:00 [INFO]   -- Token URL:
2014/12/09 15:30:01 terraform-provider-google: 2014/12/09 15:30:01 [INFO] Instantiating GCE client...
2014/12/09 15:30:01 [DEBUG] google_compute_address.test: expanding to count = 1
2014/12/09 15:30:01 [INFO] Module root walking: google_compute_address.test (Graph node: google_compute_address.test)
2014/12/09 15:30:01 [DEBUG] google_compute_address.test: Executing Apply
2014/12/09 15:30:01 terraform-provider-google: 2014/12/09 15:30:01 [DEBUG] Address insert request: &compute.Address{Address:"", CreationTimestamp:"", Description:"", Id:0x0, Kind:"", Name:"test", Region:"", SelfLink:"", Status:"", Users:[]string(nil)}
google_compute_address.test: Creating...
  address:  "" => "<computed>"
  name:     "" => "test"
  selfLink: "" => "<computed>"
2014/12/09 15:30:02 terraform-provider-google: 2014/12/09 15:30:02 [DEBUG] Waiting for state to become: DONE
2014/12/09 15:30:02 terraform-provider-google: 2014/12/09 15:30:02 [TRACE] Waiting 1s before next try
2014/12/09 15:30:03 terraform-provider-google: 2014/12/09 15:30:03 [TRACE] Waiting 1s before next try
2014/12/09 15:30:04 terraform-provider-google: 2014/12/09 15:30:04 [TRACE] Waiting 1s before next try
2014/12/09 15:30:05 terraform-provider-google: 2014/12/09 15:30:05 [TRACE] Waiting 1s before next try
google_compute_address.test: Creation complete
2014/12/09 15:30:07 [DEBUG] google_compute_instance.default: expanding to count = 1
2014/12/09 15:30:07 [INFO] Module root walking: google_compute_instance.default (Graph node: google_compute_instance.default)
2014/12/09 15:30:07 [ERROR] Diffs don't match.

Diff 1: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"tags_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "zone":*terraform.ResourceAttrDiff{Old:"", New:"us-central1-a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "disk.0.image":*terraform.ResourceAttrDiff{Old:"", New:"debian-7-wheezy-v20140814", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metadata_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "disk.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "can_ip_forward":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.0.name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.internal_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.source":*terraform.ResourceAttrDiff{Old:"", New:"default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "machine_type":*terraform.ResourceAttrDiff{Old:"", New:"n1-standard-1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "network.0.external_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metadata.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Diff 2: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"network.0.internal_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "zone":*terraform.ResourceAttrDiff{Old:"", New:"us-central1-a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "disk.0.image":*terraform.ResourceAttrDiff{Old:"", New:"debian-7-wheezy-v20140814", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "can_ip_forward":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"test", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "machine_type":*terraform.ResourceAttrDiff{Old:"", New:"n1-standard-1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "tags_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.external_address":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metadata.0.foo":*terraform.ResourceAttrDiff{Old:"", New:"107.178.209.128", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "metadata.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "network.0.source":*terraform.ResourceAttrDiff{Old:"", New:"default", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "disk.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "metadata_fingerprint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
2014/12/09 15:30:07 [ERROR] Error walking 'google_compute_instance.default': google_compute_instance.default: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.
2014/12/09 15:30:07 [INFO] Apply walk complete
Error applying plan:

2014/12/09 15:30:07 waiting for all plugin processes to complete...
google_compute_instance.default: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
2014/12/09 15:30:07 [DEBUG] /home/dcunnin/go-workspace/bin/terraform-provider-google: plugin process exited

**Comment by sparkprime** [comment]
I don't seem to suffer this bug anymore.

**Comment by svanharmelen** [comment]
@mitchellh not having much time to do some functional testing right now, so from the top of your head do you think the behaviour as described above could be changed/solved by the fieldreader/writer changes in helper/schema? If so, I think we can close this one...

**Comment by mitchellh** [comment]
Perhaps so but I jus want to verify.

**Comment by svanharmelen** [comment]
Of course... Was just wondering if you could tell by heart if this behaviour should be changed or that it shouldn't be related...

**Comment by mitchellh** [comment]
Yeah off the top of my head I'm not 100%. I'm wondering if maybe this was fixed by all those smaller fixes we did @svanharmelen. But not sure.

**Comment by mitchellh** [comment]
This is fixed.
