### ISSUE TITLE
vSphere Provider - VM Update Capability

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6341]
## Updating Virtual Machines Via vSphere provider

This is an issue for tracking update capability of the vSphere provide.  At the time of writing this issue the provider does not include the capability to update via TF.

The following items need to be validated that the govomi API allows updating.
## General VM Settings
- ~~`vcpu` - The number of virtual CPUs to allocate to the virtual machine~~ completed
- ~~`memory` - The amount of RAM (in MB) to allocate to the virtual machine~~ completed
- `memory_reservation` - The amount of RAM (in MB) to reserve physical memory resource
- `datacenter` / `cluster` move via `vmotion`
- `domain` - A FQDN for the virtual machine; defaults to "vsphere.local"
- `time_zone` - update
- `dns_suffixes` - List of name resolution suffixes for the virtual network adapter
- `dns_servers` - List of DNS servers for the virtual network adapte
- `boot_delay` - Time in seconds to wait for machine network to be ready.
- `windows_opt_config` - Extra options for clones of Windows machines.
- ~~`custom_configuration_parameters` -  Update map of values that is set as virtual machine custom configurations.~~ not going to even think about address this ...
### `network_interface` updates
- add new interface
- remove interface
- change ipv4_address on specific nic

`windows_opt_config updates`
- `admin_password` - The password for the `administrator` account. Omit for passwordless admin (using `""` does not work).
- `domain` - (Optional) Domain that the new machine will be placed into. If `domain`, `domain_user`, and `domain_user_password` are not all set, all three will be ignored.
- `domain_user` - (Optional) User that is a member of the specified domain.
- `domain_user_password` - (Optional) Password for domain user, in plain text.
### `disk` updates
- ~~add new disk~~
- ~~remove disk~~
- resize disk
### `cdrom` updates
- add or remove cdrom

**Comment by mixacha** [comment]
@chrislovecnm cpu and memory update PR #6356

**Comment by chrislovecnm** [comment]
@mixacha - Thanks! We need docs and unit tests in the PR

**Comment by mixacha** [comment]
Kudos goes to @thetuxkeeper <https://github.com/thetuxkeeper>, I just
referenced the pull request in this issue so we keep track of it :-)

**Comment by chrislovecnm** [comment]
CPU and mem marked as completed

**Comment by chrislovecnm** [comment]
Disk updates are in. @thetuxkeeper you planning on working on nics?

**Comment by thetuxkeeper** [comment]
@chrislovecnm: I'll try to find enough time for it next week. Since I get a little pressure from above, I have to prioritize "getting it work"/"produce results" and deploying the base infrastructure with TF (what already works for us together with ansible). Now work piles up (integration of consul, nomad, ...)

**Comment by chrislovecnm** [comment]
@thetuxkeeper no worries.  You help is always appreciated.  If you don't have time, can you file an issue and outline design on how you are planning on addressing?

**Comment by chrislovecnm** [comment]
@thetuxkeeper the good news doing that is that I bet you will find more bugs 😄

**Comment by thetuxkeeper** [comment]
@chrislovecnm : haha ;) ok, will do file an issue if I don't have time for it. One problem is the one we have "everywhere", the ID/index stuff. It's hard to start if there's no solution yet.

**Comment by smenon78** [comment]
I am trying to do a VM undate to add an additional disk
disk {
    template = "template"
    datastore = "datastore-1"
  }
  disk {
    size = "60"
    name = "hard disk 2"
    datastore = "datastore-1"
  }

I tried with and without specifying datastore, I still keep getting this error
: [ERROR] Update Remove Disk - Error finding datastore: default datastore resolves to multiple instances, please specify

Terraform v0.9.5


Any idea?
