### ISSUE TITLE
`terraform fmt` always updates source file

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#6343]
I am trying to write a `terraform fmt` binding for [arcanist](https://github.com/phacility/arcanist). It seems that running `terraform fmt some_file.tf` will always update the source file. This seems inconsistent with the documentation, which seems to imply that the source file will only be modified with the `-write` flag. Specifically, I am trying to have `terraform fmt some_file.tf` output the modified file to STDOUT rather than overwriting the input file.

**Comment by mdxp** [comment]
I assumed that using -diff like this: `terraform fmt -diff` will only display the diff just like the man page is describing: "Display diffs instead of rewriting files" but in order to get this functionality you have to add the `-write=false` flag that is not very intuitive.

**Comment by jrnt30** [comment]
That's a good point.  It appears they are all mutually exclusive.  The explanation of diff is misleading

**Comment by dcarley** [comment]
The description was copied straight from [gofmt](https://golang.org/src/cmd/gofmt/gofmt.go#L31). I agree, it's confusing - documentation pull requests incoming.

**Comment by radeksimko** [comment]
Can this be closed now, when #6398 was merged or is there anything left to implement/fix?

**Comment by teamterraform** [comment]
Hi all! Sorry for the long silence here.

It looks like the confusing and incorrect documentation that led to this issue have been corrected (and, by now, rewritten again a few times!), so we're going to close this out.
