### ISSUE TITLE
aws_autoscale_notification causes issues while re-launching ASG with aws_autoscaling_group changes

### ISSUE THREAD

**Issue by pauldatta** [hashicorp/terraform#6348]
I have been using terraform to launch a new AMI within my existing ASGs by destroying them and recreating - changing the aws_autoscaling_group within my cf file does this for me.

I recently added an aws_autoscale_notification to the mix that looks like the below which is what has broken things I feel. 
`aws_autoscaling_notification.app_asg_notification - diffs didn't match` (see gist down below).

```
resource "aws_autoscaling_notification" "asg_notification" {
  group_names = [
    "${aws_autoscaling_group.apps_a.name}",
    "${aws_autoscaling_group.apps_b.name}"
  ]
  notifications  = [
    "autoscaling:EC2_INSTANCE_LAUNCH", 
    "autoscaling:EC2_INSTANCE_TERMINATE",
    "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
  ]
  topic_arn = "SOME ARN"
}
```

Do you think adding a create_before_destroy = true will help?
Will do a few more launches and see how it works.
### Terraform Version

0.6.15
### Affected Resource(s)
- aws_autoscaling_notification
### Terraform Configuration Files

Default
### Debug Output

https://gist.github.com/pauldatta/37825bcde28dc1c72ca7ac45b9e718b8
### Expected Behavior
- Create New LC + ASG 
- Old LC + ASG deleted
- Instances are spun up
- Old instances are terminated
### Actual Behavior
- Create New LC + ASG 
- Old LC + ASG were _not_ deleted
- Instances are spun up
- Old instances were _not_ terminated 
### Steps to Reproduce
1. Modified aws_autoscaling_group name to initiate a change
2. `terraform apply`

**Comment by mitchellh** [comment]
This should be fixed in the latest version of Terraform.

Its hard to be 100% sure but we fixed many issues related to not showing <computed> properly (which triggered this). Please give it a try and if it is still happening open a new issue. thanks!
