### ISSUE TITLE
Ebs volumes are not attached and available at boot time for userdata script to mount them.

### ISSUE THREAD

**Issue by Dchamard** [hashicorp/terraform#6349]
### Terraform Version
0.6.15
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_volume_attachments
- aws_ebs_volume

### Expected Behavior
- Terraform create the volumes
- Terraform create the instance
- Terraform attach the volumes to the ec2 instance
- Terraform starts the instance
 
### Actual Behavior
Terraform attach the volumes after that the instance is started.
This means that the volumes are not available when the userdata script runs.
I had to implement a retry loop in userdata to wait until the volume is avaiblable.
I feel like terraform should wait until the volume is attach before starting the instance.

### Steps to Reproduce
resource "aws_instance" "zookeeper" {
  count                   = "${var.zookeeper_instance_count}"
  ami                     = "${lookup(var.ec2_base_amis, var.region)}"
  instance_type           = "${var.zookeeper_instance_type}"
  key_name                = "${var.key_name}"
  vpc_security_group_ids  =  ["${concat(split(",", var.base_security_group_ids),aws_security_group.zookeeper.id)}"]
  user_data               = "${element(template_file.zookeeper.*.rendered, count.index)}\n${file("${path.module}/userdata/zookeeper_userdata")}"
  subnet_id               = "${element(split(",", var.public_subnets), count.index)}"
  monitoring              = "true"
  tags {
    Name                    = "${format("${var.stack_name}-zookeeper%02d", count.index + 1)}"
      stack_type            = "${element(split("-",var.stack_name), 0)}"
      virtual_env           = "${element(split("-",var.stack_name), 1)}"
      sub_env               = "${element(split("-",var.stack_name), 2)}"
      incremental           = "${element(split("-",var.stack_name), 3)}"
      service               = "${var.stack_name}-zookeeper"
      zkid                  = "${count.index}"
      role                  = "zookeeper"
  }
}

resource "aws_volume_attachment" "zookeeper_magnetic1" {
  count        = "${var.zookeeper_instance_count}"
  device_name  =  "${var.zookeeper_device_name_magnetic_1}"
  volume_id    = "${element(aws_ebs_volume.zookeeper_magnetic1.*.id, count.index)}"
  instance_id  = "${element(aws_instance.zookeeper.*.id, count.index)}"
}

resource "aws_ebs_volume" "zookeeper_magnetic1" {
  count             = "${var.zookeeper_instance_count}"
  availability_zone = "${var.region}${element(split(",", var.availability_zones), count.index)}"
  type              =  "standard"
  size              = "${var.zookeeper_magnetic_volume_size}"
}

**Comment by eedwardsdisco** [comment]
Are you sure that Terraform is starting the instance?

I'm pretty sure that the instance automatically starts the moment it's created, as per AWS behavior, not Terraform.
