### ISSUE TITLE
Support KmsKeyId in aws_db_instance resource for rds encryption

### ISSUE THREAD

**Issue by krushi90** [hashicorp/terraform#6353]
As part of https://github.com/hashicorp/terraform/pull/1041, support for storage encryption was added but with default key. Can we add support for specifying KmsKeyId in aws_db_instance resource? 

In my current use case, I need to use a different key(not default key) for RDS encryption. Since encryption can only be set at the time of creating RDS instance, I don't know if there is any other way to specify a different key other than creating a cloud formation resource for RDS. Are there any alternate solutions for this as of now?

**Comment by krushi90** [comment]
@hc-asana I see closed flag on this. Does this mean this will be implemented or will not be implemented? Thanks.

**Comment by stack72** [comment]
Hi @krushi90 

I just added this https://github.com/hashicorp/terraform/commit/cf37c3adaa67a6ed0eda517671a2ad38f9838b6c

This will make Terraform 0.7 so this can now be closed :)

Paul
