### ISSUE TITLE
0.6.15 Windows vSphere Updates?

### ISSUE THREAD

**Issue by rossedman** [hashicorp/terraform#6354]
Did the vSphere additions for Windows support not included in the newest release? There seems to be some updates that are vSphere updates that are newer, but I didn't see those commits from @aheeren included. Interested to know what happened to those. They were committed on April 13th.

Thanks

**Comment by aheeren** [comment]
@rossedman Looks to me like the changes are there: https://github.com/hashicorp/terraform/blob/v0.6.15/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L47 I haven't built/tested the release, but I can't see any reason for the functionality of windows to have changed. I'll leave it up to you to close or not close this issue.

**Comment by jen20** [comment]
Hi @rossedman! Some commits from @aheeren landed in 0.6.15 as children of `eded8bb` and were shipped as part of that release. If you're still seeing issues with Windows machines, would you consider opening a new issue (following the new template) describing what you are seeing and we'll try to take a look! Thanks!

**Comment by rossedman** [comment]
@jen20 @aheeren Thanks. I'm not seeing issues so far. Built from master. Didn't realizes changes were in 0.6.15. Thanks a lot. That's exciting news.
