### ISSUE TITLE
Missing "wait_for_ready_timeout" in tfstate file causes error upgrading from 0.6.14 -> 0.6.15

### ISSUE THREAD

**Issue by awesometown** [hashicorp/terraform#6357]
We're using Terraform to provision Elastic Beanstalk applications in AWS. Today I tried upgrading Terraform from version 0.6.14 to 0.6.15 to take advantage of the new "cname_prefix" field. However, when I tried to run "terraform apply" against an existing stack, I received this error:

> - aws_elastic_beanstalk_environment.bs_environment: time: invalid duration

However, if I destroy the entire stack, delete my .tfstate file and run "terraform apply", everything works, suggesting a problem with 0.6.15 reading the older .tfstate file.

Looking at the tfstate files from old and new stacks, I see the newer ones contain a value for "wait_for_ready_timeout" in the section related to the Beanstalk stack, while the older ones do not (it appears this field was also added in 0.6.15). If I hack the older state file and manually add

> `"wait_for_ready_timeout": "10m"`

then I can run "terraform apply" successfully against the old stack.

It seems like the problem is likely that Terraform 0.6.15 is trying to parse a time out of a value that is not present in older tfstate files and should probably be filling in a default value or something in these cases.

I'm hoping that's sufficient info to go on; if not, I can work on creating a sample config and provide debug logs.

**Comment by dharrisio** [comment]
It sounds like I might have missed a migration on that one, sorry! The `wait_for_ready_timeout` was also added in 0.6.15. If you could provide more details that would be great. I tried to create it with the basic tf document below, but didn't run into the issue you described.

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_elastic_beanstalk_application" "tftest" {
  name = "tf-test-migrations"
  description = "tf-test-desc"
}

resource "aws_elastic_beanstalk_environment" "tfenvtest" {
  name = "tf-test-migrations-env"
  application = "${aws_elastic_beanstalk_application.tftest.name}"
  solution_stack_name = "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4"
}
```

- terraform apply (v0.6.14)
- terraform plan (v0.6.15)
- terraform apply (v06.15)

### Plan output from v0.6.15
```
~ aws_elastic_beanstalk_environment.tfenvtest
    wait_for_ready_timeout: "" => "10m"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Apply output from v0.6.15
```
aws_elastic_beanstalk_application.tftest: Refreshing state... (ID: tf-test-migrations)
aws_elastic_beanstalk_environment.tfenvtest: Refreshing state... (ID: e-z3nxpqrze4)
aws_elastic_beanstalk_environment.tfenvtest: Modifying...
  wait_for_ready_timeout: "" => "10m"
aws_elastic_beanstalk_environment.tfenvtest: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

In the mean time I'll dig into this some more to see if I can recreate the issue.

**Comment by stack72** [comment]
@dharrisio is this going to be fixed by the PR just merged?

**Comment by dharrisio** [comment]
@stack72 I'm not sure if it is related. I've tried a few other things, but haven't been able to recreate the issue yet.

**Comment by stack72** [comment]
got it - let me know :)

**Comment by awesometown** [comment]
Hmm, ok. I'll take a stab at finding a simple(ish) configuration that reproduces the problem tonight or tomorrow morning. I don't think there's anything too exciting about our beanstalk configuration, except that we've got a bunch of "setting" values.

**Comment by awesometown** [comment]
I think I've got it. I confirmed that I cannot repro the problem with your sample above, but can with one additional step. As I mentioned, we specifically jumped on 0.6.15 so that we could take advantage of specifying "cname_prefix" in the beanstalk configuration. Doing so forces a recreate of the beanstalk environment (which is expected), but that seems to be the scenario where the problem appears.

If I use your sample from above, but when switching from 0.6.14 to 0.6.15 I *also* add

```
cname_prefix = "foo"
```
to the beanstalk environment, doing "terraform plan" gives

```
 -/+ aws_elastic_beanstalk_environment.tfenvtest
    all_settings.#:          "93" => "<computed>"
    application:             "tf-test-migrations" => "tf-test-migrations"
    autoscaling_groups.#:    "1" => "<computed>"
    cname:                   "tf-test-migrations-env.rn9ahqbdgk.us-east-1.elasticbeanstalk.com" => "<computed>"
    cname_prefix:            "" => "foo" (forces new resource)
    instances.#:             "1" => "<computed>"
    launch_configurations.#: "1" => "<computed>"
    load_balancers.#:        "1" => "<computed>"
    name:                    "tf-test-migrations-env" => "tf-test-migrations-env"
    queues.#:                "0" => "<computed>"
    setting.#:               "0" => "<computed>"
    solution_stack_name:     "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4" => "64bit Amazon Linux 2016.03 v2.1.0 running Go 1.4"
    tier:                    "WebServer" => "WebServer"
    triggers.#:              "0" => "<computed>"
    wait_for_ready_timeout:  "" => "10m"
```

but then doing "terraform apply" gives:

```
aws_elastic_beanstalk_application.tftest: Refreshing state... (ID: tf-test-migrations)
aws_elastic_beanstalk_environment.tfenvtest: Refreshing state... (ID: e-vsnwmbmpdd)
aws_elastic_beanstalk_environment.tfenvtest: Destroying...
Error applying plan:

1 error(s) occurred:

* aws_elastic_beanstalk_environment.tfenvtest: time: invalid duration 
```

**Comment by dharrisio** [comment]
@awesometown Thanks for the details, I was able to recreate the issue included the `cname_prefix`. Digging into this now.

**Comment by dharrisio** [comment]
This error is being returned from the `resourceAwsElasticBeanstalkEnvironmentDelete` fucntion. More specifically trying to read the `wait_for_ready_timeout` value. 
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elastic_beanstalk_environment.go#L507

I was able to get around this using this, but it seems like a migration might be a better way to handle this one. https://gist.github.com/dharrisio/7463479e67551a50308d331e92e36cd2#file-resource_aws_elastic_beanstalk_environment-go-L507

@stack72 Do you think a migration would be better here?

I also find it a bit odd that we don't see the error when updating a resource, because it gets the value for `wait_for_ready_timeout` the same way as the delete. In an update does the state get updated with the default value before `resourceAwsElasticBeanstalkEnvironmentUpdate` is called?

**Comment by beanaroo** [comment]
Can confirm this behaviour on Terraform v0.9.4

**Comment by dharrisio** [comment]
@beanaroo Did you see this upgrading from v0.6.14 -> v0.9.4? The issue above should have only occurred when an environment is getting destroyed, so I'm wondering if you are seeing a different error.
