### ISSUE TITLE
[azurerm] No support for setting blob contents

### ISSUE THREAD

**Issue by colemickens** [hashicorp/terraform#6360]
### Affected Resource(s)
- azurerm_storage_blob

### Expected Behavior
Azure blob contents should be settable from Terraform. (GCE Storage Blob has a "content" field).

### Actual Behavior
There is no such feature.

**Comment by colemickens** [comment]
I have some WIP here: https://github.com/colemickens/terraform/tree/azure-blob-upload

**Comment by colemickens** [comment]
Also, blob types should probably be "block" or "page", rather than right now it expects "blob" or "page". There's no blob type "blob".

**Comment by apparentlymart** [comment]
Hi @colemickens! Thanks for this.

If you'd like, feel free to open a pull request for your Terraform fork, which will make it easier to see what you've changed and eventually merge it. Work-in-progress PRs are very welcome... just put [WIP] at the start of the summary so we can see clearly that it's not yet ready to merge.

**Comment by stack72** [comment]
Hi @colemickens 

Thanks for the heads up about the block / blob issue. I have just opened #7328 to fix that

I would love it f you could submit a PR for the upload functionality - you know the feature much better than I do so I would be playing catch up here :)

Paul

**Comment by stack72** [comment]
Closed via #7994
