### ISSUE TITLE
provider/aws: aws_vpc_peering_connection should use connected AWS account ID by default

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#6396]
Currently `aws_vpc_peering_connection` has `peer_owner_id` as a required field. Since this is not a reliable parameter to get from Terraform, it makes deployment into a template that does not have knowledge of account IDs a bit problematic.

Looking in the SDK, [`CreateVpcPeeringConnectionInput`](http://docs.aws.amazon.com/sdk-for-go/api/service/ec2.html#type-CreateVpcPeeringConnectionInput) seems to allow defaulting on `PeerOwnerId`:

```
PeerOwnerId *string
The AWS account ID of the owner of the peer VPC.

Default: Your AWS account ID
```

As I'm looking at writing a module to allow easy plugging of peers into our VPCs, I'm going to take a stab at changing this behaviour.

There will be a couple of other places things need to be changed as well due to the fact that it seems to facilitate testing there is indeed a default right now, going to `AWS_ACCOUNT_ID`. `resource_aws_route_table_test.go` will need a slight refactoring as well.

**Comment by stack72** [comment]
Hi @vancluever 

I can see from the current resource:

```
Schema: map[string]*schema.Schema{
			"peer_owner_id": &schema.Schema{
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				DefaultFunc: schema.EnvDefaultFunc("AWS_ACCOUNT_ID", nil),
			},
```

Therefore, is this issue (and associated PR) still required?

Paul

**Comment by vancluever** [comment]
Hey @stack72! Reviewing right now and will get back to you shortly!

**Comment by vancluever** [comment]
Hey @stack72 - yeah I think this is still needed: from my diff:

```
 		Schema: map[string]*schema.Schema{
  			"peer_owner_id": &schema.Schema{
 -				Type:        schema.TypeString,
 -				Required:    true,
 -				ForceNew:    true,
 -				DefaultFunc: schema.EnvDefaultFunc("AWS_ACCOUNT_ID", nil),
 +				Type:     schema.TypeString,
 +				Optional: true,
 +				ForceNew: true,
 +				Computed: true,
```

So what's needed is to actually make it optional, versus required, so that it can default to the AWS account ID making the connection (this allows TF to apply intra-account peering without having to know the account ID beforehand).

**Comment by vancluever** [comment]
@stack72 - rebase complete on the referenced PR!
