### ISSUE TITLE
Feature request: additional-zones on google_container_cluster resource

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#6397]
https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

> --additional-zones ZONE,[ZONE,…]
> The set of additional zones in which the specified node footprint should be replicated. All zones must be in the same region as the cluster's primary zone. If additional-zones is not specified, all nodes will be in the cluster's primary zone.
> Multiple locations can be specified, separated by commas. For example:
> 
>  $ {command} example-cluster --zone us-central1-a \ 
>      --additional-zones us-central1-b,us-central1-c

**Comment by Stono** [comment]
+1million, literally.

**Comment by devth** [comment]
@evandbrown @lwander @viglesiasce ping – possible to get this in?
