### ISSUE TITLE
provider/aws Redshift restore from cluster snapshot

### ISSUE THREAD

**Issue by pschipitsch** [hashicorp/terraform#6406]
Would like to use terraform to restore from Redshift cluster snapshot.

https://github.com/aws/aws-sdk-go/blob/master/service/redshift/api.go#L2149,L2188

**Comment by danielrmeyer** [comment]
+1

**Comment by satvidh** [comment]
+1

**Comment by ManuelCalavera** [comment]
+1

**Comment by makered** [comment]
+1

**Comment by pmoosh** [comment]
+1

**Comment by fenak** [comment]
+1

**Comment by myoung34** [comment]
What version of TF is this in? I dont see this in the docs at https://www.terraform.io/docs/providers/aws/r/redshift_cluster.html
