### ISSUE TITLE
Docker *.tf unexpected EOF crash

### ISSUE THREAD

**Issue by JulianSza** [hashicorp/terraform#6409]
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
# Configure the Docker provider
provider "docker" {
    host = "tcp://127.0.0.1:4243/"
}

# Create a container
resource "docker_container" "terra" {
    image = "${docker_image.terrabox.latest}"
    name = "terra"
    command =[""]
    must_run = true
    restart ="always"
}

resource "docker_image" "terrabox" {
    name = "busybox:latest"
}
```

### Panic Output
gist.github.com/JulianSza/57484554cd5a5d83324ec59e14094058

### Expected Behavior
Error message saying `command =[""]` is invalid

### Actual Behavior
Crash (unexpected EOF)

### Steps to Reproduce
`terraform apply`

**Comment by jen20** [comment]
Hi @JulianSza! I can reproduce this on `terraform apply` - thanks for the clear repro. We'll get this fixed ASAP.

**Comment by jen20** [comment]
Hi @JulianSza - this should be fixed in https://github.com/hashicorp/terraform/pull/6424 - we'll try to ensure that gets merged before the next release of Terraform!
