### ISSUE TITLE
cookies in aws_cloudfront_distribution not optional

### ISSUE THREAD

**Issue by ruippeixotog** [hashicorp/terraform#6425]
I have the following minimal `aws_cloudfront_distribution` resource config:

```
provider "aws" {
  access_key = "<INSERT_VALID_ACCESS_KEY>"
  secret_key = "<INSERT_VALID_SECRET_KEY>"
  region = "us-east-1"
}

resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    domain_name = "mybucket.s3.amazonaws.com"
    origin_id = "S3-mybucket"

    s3_origin_config {
      origin_access_identity = ""
    }
  }

  enabled = true

  default_cache_behavior {
    allowed_methods = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods = ["GET", "HEAD"]
    target_origin_id = "S3-mybucket"

    forwarded_values {
      query_string = false
    }

    viewer_protocol_policy = "allow-all"
    min_ttl = 0
    default_ttl = 3600
    max_ttl = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```

Running `terraform plan` (Terraform v0.6.15) with this config causes a panic (full stack trace [here](https://gist.github.com/ruippeixotog/dcb01808a0ad8f4d87857c77cae61152)). I found out that by adding a value for `default_cache_behavior.forwarded_values.cookies` everything worked as expected.

`cookies` is therefore not in accordance in [the Terraform documentation](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#cookies), which says the argument is optional. Even if `cookies` should be required, a human-readable error message should be printed in any case.

**Comment by stack72** [comment]
Just a note here that the error occurs in the creation of the Hash for the forwardedValues

```
func forwardedValuesHash(v interface{}) int {
	var buf bytes.Buffer
	m := v.(map[string]interface{})
	buf.WriteString(fmt.Sprintf("%t-", m["query_string"].(bool)))
	if d, ok := m["cookies"]; ok {
		buf.WriteString(fmt.Sprintf("%d-", cookiePreferenceHash(d.(*schema.Set).List()[0].(map[string]interface{}))))
	}
	if d, ok := m["headers"]; ok {
		for _, e := range sortInterfaceSlice(d.([]interface{})) {
			buf.WriteString(fmt.Sprintf("%s-", e.(string)))
		}
	}
	return hashcode.String(buf.String())
}
```

P.

**Comment by jrnt30** [comment]
@apparentlymart Had some additional info/log @ https://github.com/hashicorp/terraform/issues/6441#issuecomment-216324989

**Comment by catsby** [comment]
Hey @ruippeixotog – I think you're very correct there, despite the sparse documentation on AWS that explicitly says yes or no here... from my testing I was getting error messages if this was omitted. 

I've opened #6505 to address this by documenting that it's required. Unfortunately I think there's a core bug that is preventing us from warning if it's omitted, but we'll have to address that in another PR. For now though, it will be documented and at the least no longer crash!

Sorry for the trouble here. Let me know what you think

**Comment by ruippeixotog** [comment]
Correcting the documentation is more than enough for me. Thank you for the fast fix!

**Comment by catsby** [comment]
#6505 was merged, fixing the crash and updating the documentation, so I'm going to close this. Thanks!
