### ISSUE TITLE
Crash on v0.6.15 when missing quotes in file function

### ISSUE THREAD

**Issue by dstibrany** [hashicorp/terraform#6432]
The crash happened when running `terraform plan` with the following resource:

```
resource "aws_key_pair" "mesosphere" {
  key_name   = "mesosphere"
  public_key = "${file(/Users/dstibrany/.ssh/mesosphere.pub)}"
}
```

Adding quotes to the the file path fixed it.

[crash.log.zip](https://github.com/hashicorp/terraform/files/243880/crash.log.zip)

**Comment by apparentlymart** [comment]
Hi @dstibrany! Sorry for this crash, and thanks for the report!

I think this is the same bug as in #5672, so I'm going to close this to consolidate the discussion over there.
