### ISSUE TITLE
EIP reallocation failure

### ISSUE THREAD

**Issue by cstruct** [hashicorp/terraform#6436]
Hi,

Since the v0.6.15 release terraform cannot reassociate elastic IPs.

### Terraform Version
Fails on `Terraform v0.6.15`
Succeeds on `Terraform v0.6.14`

### Affected Resource(s)
- aws_eip

### Terraform Configuration Files
Changing config from:
```hcl
resource "aws_eip" "default" {
  vpc = true
  instance = "${aws_instance.instance_a.id}"
}
```
to:
```hcl
resource "aws_eip" "default" {
  vpc = true
  instance = "${aws_instance.instance_b.id}"
}
```

### Debug Output
[TRACE log](https://gist.github.com/cstruct/16b25a70711a7554b95fb0b52e23600b)

### Expected Behavior
The EIP should be reassociated with the new instance

### Actual Behavior
Terraform fails with:
```
aws_eip.default: Failure associating EIP: InvalidParameterValue: 10.x.x.x is not mapped to the interface eni-xxxxxxxx
```

### Steps to Reproduce
1. set existing `aws_eip.instance` to a new value
1. `terraform apply`

**Comment by WishCow** [comment]
Also affected by this

**Comment by dbrandt** [comment]
Ran in to this as well.

@cstruct Thanks for taking the time to write up a thorough bug report. I wasn't certain if I was doing something stupid with AWS or if this was an issue...

**Comment by catsby** [comment]
Hey @cstruct thanks for opening this!

#6521 should fix this. Note that if you're using `private_ip` in your EIP resource, you'll need to use the new `associate_with_private_ip` attribute that's added in that pull request

**Comment by cstruct** [comment]
Thank you @catsby
