### ISSUE TITLE
Schema update existing member of list vs update new member of list

### ISSUE THREAD

**Issue by dkalleg** [hashicorp/terraform#6444]
Hi there,
### Terraform Version

Terraform v0.6.16-dev (e0f1283ee4692cbdebbde5042d4c8bc66685b9aa+CHANGES)
### Affected Resource(s)
- vsphere resource_vsphere_virtual_machine.go
- Probably every other provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
### Problem definition

I don't see a way to distinguish updating a resources attribute if:
1) That attribute is a list
2) You are adding to that list, not modifying an existing member of that list
### Debug Output

Important lines are the "forces new resource" lines

```
dan@Mac:~/Documents/tfTest$ terraform plan
2016/05/02 14:52:26 [WARN] Invalid log level: "all". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
Refreshing Terraform state prior to plan...

vsphere_folder.dansTfFolder: Refreshing state... (ID: Datacenter/DansTfTest)
vsphere_virtual_machine.dansTerraformVm: Refreshing state... (ID: DansTfTest/tfTestVmDisk)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

-/+ vsphere_virtual_machine.dansTerraformVm
    datacenter:                             "Datacenter" => "Datacenter"
    disk.#:                                 "1" => "3"
    disk.0.bootable:                        "true" => "1"
    disk.0.type:                            "eager_zeroed" => "eager_zeroed"
    disk.0.vmdk:                            "images-update/ubuntu.vmdk" => "images-update/ubuntu.vmdk"
    disk.1.bootable:                        "" => "0" (forces new resource)
    disk.1.size:                            "" => "2" (forces new resource)
    disk.1.type:                            "" => "eager_zeroed" (forces new resource)
    disk.2.bootable:                        "" => "0" (forces new resource)
    disk.2.size:                            "" => "3" (forces new resource)
    disk.2.type:                            "" => "eager_zeroed" (forces new resource)
    domain:                                 "vsphere.local" => "vsphere.local"
    folder:                                 "DansTfTest" => "DansTfTest"
    linked_clone:                           "false" => "0"
    memory:                                 "1024" => "1024"
    memory_reservation:                     "0" => "0"
    name:                                   "tfTestVmDisk" => "tfTestVmDisk"
    network_interface.#:                    "1" => "1"
    network_interface.0.ip_address:         "" => "<computed>"
    network_interface.0.ipv4_address:       "192.168.41.154" => "<computed>"
    network_interface.0.ipv4_prefix_length: "24" => "<computed>"
    network_interface.0.ipv6_address:       "fe80::250:56ff:fe99:1f08" => "<computed>"
    network_interface.0.ipv6_prefix_length: "64" => "<computed>"
    network_interface.0.subnet_mask:        "" => "<computed>"
```
### Expected Behavior

New member of Schema list should not trigger a ForceNew check
### Actual Behavior

Forced new
### Steps to Reproduce

Using vSphere as an example:
1) Create tf template for a vm with one disk & terraform apply
2) Add a disk in the .tf template & terraform apply
### Important Factoids

This specific example occurs because two of the attributes of a vSphere disk have default values.  If you see the output above, you'll see what happens when I create a vm with one disk _then_ add two disks to the .tf template and run terraform apply once more. You see "disk.1" and "disk2" are new and has flagged bootable/size/type as forcing new.  

**Here's the real distinction**:  When targeting an **existing disk that terraform has already created once**, I would like the ForceNew to apply.  When targeting a **completely new disk in the list of disks**, I don't want the ForceNew to apply.
I understand this is not the same use case for everyone, but I want to find a way to work around this issue of adding a member to an attribute list without having situationally warranted ForceNews to destroy my entire vm.
### References

This request may provide a solution for this issue:
https://github.com/hashicorp/terraform/issues/5895
Where we could say ForceNewWhen: { logic to apply to only previously existing list members }

I see a way I can work around this by removing the default values for the various disk definition attributes.  If type, for example, didn't have a default of eager_zeroed, then it wouldn't be flagged, like so:
`disk.1.type:                            "" => "eager_zeroed" (forces new resource)`
But I'd like to see a way to accomplish this without having to sacrifice my default value.

**Comment by apparentlymart** [comment]
Hi @dkalleg,

For the moment I've tagged this as specific to the vSphere provider, because in other cases the behavior you're describing would be correct... adding a new item to a list requires a new resource just as much as editing an existing one.

If vSphere allows adding new disks to a VM but doesn't allow exiting existing ones then it may be that this should just be expressed in a different way to Terraform. For example, we could potentially have a separate resource for "additional disks" on an instance that get added after it's been created, and have the list within the instance be the "initial disks". The AWS provider has a similar idea where you can attach an EBS volume after a machine is already booted, but you do it with `aws_volume_attachment` rather than by directly editing the `aws_instance` resource.

However, if it turns out that we can't solve this without a core change then we can always re-tag it as core. :grinning:

Thanks for the feature request, and the detailed use-case description!

**Comment by dkalleg** [comment]
Thanks @apparentlymart! I certainly understand that many use cases would expect and want the behavior we see from Terraform today, I meant to propose this more as a feature add rather than an adjustment to todays behavior.

I'm working on the workaround I mentioned above of adjusting the overall schema definition of a disk.  I'll report back if it doesn't work out or not, and how graceful the change turns out to be.

**Comment by chrislovecnm** [comment]
@dkalleg email me when u have a chance!

**Comment by chrislovecnm** [comment]
@dkalleg I assume this is still open?

**Comment by dkalleg** [comment]
@chrislovecnm I'd say its still a plausible enhancement.  We've worked around it in vSphere by using Sets instead of Lists.
