### ISSUE TITLE
OpenStack Security Group IPv6 Capitalization 

### ISSUE THREAD

**Issue by lewg** [hashicorp/terraform#6451]
When using the OpenStack provider, if you specify an IPv6 cidr with capital letters, terraform will continually try to re-create the group (and fail) because the state returned and stored for the cidr is in lowercase. The provider should do a case-insensitive compare. 

### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- openstack_compute_secgroup_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_secgroup_v2" "test_uppercase" {
  name = "test_access_uppercase"
  description = "Securty Group Test - IPv6 Uppercase"
  rule {
    from_port = 61000
    to_port = 61000
    ip_protocol = "tcp"
    cidr = "2001:558:FC00::/39"
  }
}
```

### Debug Output
https://gist.github.com/lewg/da85fb63f7c8eb605a647f124a63125e

### Expected Behavior

The security group exists, there should be no modification. 

### Actual Behavior

It believes it needs to be changed, which then fails because that cidr already exists. 

### Steps to Reproduce
1. `terraform apply`
3. `terraform apply`

**Comment by jtopjian** [comment]
Bonus points for IPv6 😃 

Thanks for reporting this!
