### ISSUE TITLE
aws_api_gateway_integration_response with selection_pattern attribute cannot be created

### ISSUE THREAD

**Issue by JefStat** [hashicorp/terraform#6461]
### Terraform Version

Terraform v0.6.15

### Affected Resource(s)

- aws_api_gateway_integration_response

### Terraform Configuration Files

https://gist.github.com/JefStat/7db907e52566ce59c575881a7c7c3467

### Debug Output
 https://gist.github.com/JefStat/9eca9815630d2c0fff90a313da94b180

### Expected Behavior
Created API Gateway Integration Response for selection pattern

### Actual Behavior
Did not create API Gateway Integration Response for selection pattern

### Steps to Reproduce
1. `terraform apply` with only the 200 integration response
2. `terraform apply` again to apply changes that were not create due to depends on not affecting certain resources
3. `terraform apply` changes with a selection response pattern

**Comment by radeksimko** [comment]
Hi @JefStat 
I believe this is fixed in the master branch via https://github.com/hashicorp/terraform/pull/5893 which will be part of the next release (`0.6.16`).

Feel free to reopen if the issue persists.
