### ISSUE TITLE
provider/vsphere: crash with empty "cdrom" argument

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6462]
The following line is throwing a panic if the value of cdrom is set to an empty string. 

https://github.com/hashicorp/terraform/blob/501c05d0f76bcdb9f53a733fad675e531d0939bd/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L686

Need to test for `nil`, and should test the parameter value.

**Comment by stack72** [comment]
Hey @chrislovecnm 

Is this still an issue? The link seems to suggest that we check using d.GetOk on CDRom

P.

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
