### ISSUE TITLE
godep error

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6464]
I am on the master branch and I am trying to update `govmomi`.  I keep getting an error while running:

```console
$ godep restore
godep: error restoring dep (github.com/aws/aws-sdk-go/service/cloudfront): Wanted to restore rev 6876e9922ff299adf36e43e04c94820077968b3b, already restored rev e7cf1e5986499eea7d4a87868f1eb578c8f2045a for another package in the repo
godep: Error restoring some deps. Aborting check.
```

Ideas?

The update fails as well:

```console
$ godep update -v github.com/vmware/govmomi
godep: no packages can be updated
```

**Comment by catsby** [comment]
I've bumped this locally and have a patch here https://github.com/hashicorp/terraform/pull/6465, waiting for acceptance tests to pass

**Comment by chrislovecnm** [comment]
@catsby YOU ROCK!!!

cc: @thetuxkeeper @dkalleg

**Comment by catsby** [comment]
I merged #6465 , I hope that unblocks you here. Let me know!

**Comment by chrislovecnm** [comment]
@catsby I am still getting the `no packages can be updated`

**Comment by catsby** [comment]
The patch I put in was to fix the `cloudfront` godep error. For updating the other library, see [Adding a dependency](https://github.com/hashicorp/terraform#adding-a-dependency) and [Updating a dependency](https://github.com/hashicorp/terraform#updating-a-dependency) in the README. If those don't work, let me know.

**Comment by chrislovecnm** [comment]
@catsby yah that did not work. Followed those instructions and what is on godeps readme :(

**Comment by catsby** [comment]
I opened https://github.com/hashicorp/terraform/pull/6472 to address this, bumping the dependency to the latest tag, v0.6.1

I too got the `no packages can be updated` message, but I was running `godep update github.com/vmware/govmomi` – when I tried `godep update github.com/vmware/govmomi/...` it did update, with all the sub packages. Were you using the trailing `/...`? The instructions make it look like "and so on..." , but I believe it's meant literally as-is 

Anyway, checkout #6472 and make sure that's the right dependency version

**Comment by chrislovecnm** [comment]
👍 thanks
