### ISSUE TITLE
aws_elasticache_parameter_group crash when change exists outside of tfstate

### ISSUE THREAD

**Issue by paulruiz** [hashicorp/terraform#6466]
Panic crash in _aws.flattenElastiCacheParameters_ when running terraform apply, plan or destroy with existing _aws_elasticache_parameter_group_ where change to a parameter is made outside of terraform.  Verified reproducible with terraform -v "0.6.15" and "0.6.14"

To reproduce
* terraform apply the aws_elasticache_parameter_group.tf included in the gist below
* change the timeout parameter value in AWS console or by awscli
```
aws elasticache modify-cache-parameter-group --cache-parameter-group-nam bug-repro --parameter-name-values ParameterName=timeout,ParameterValue=0
```
* terraform plan
* crash :(

aws_elasticache_parameter_group.tf, crash.log and terraform.tfstate are included in the gist
https://gist.github.com/paulruiz/06878773487ed51b1923dc600ff691f2

**Comment by paulruiz** [comment]
Sorry.  Actually the crash only happens if you make the change in AWS console.  Updating the parameter via awscli produces the expected diff from plan.

**Comment by paulruiz** [comment]
Further testing in AWS console revealed that no parameter change is necessary.  A crash can be triggered by just selecting the parameter group, clicking "Edit Parameters", then clicking "Save Changes", without making any changes to parameters.  Then run terraform plan.

**Comment by catsby** [comment]
Hey @paulruiz thanks for opening this – I've sent a patch in https://github.com/hashicorp/terraform/issues/6687 to only save attributes with valid values that come with them. Turns out there's one added that has no value...

**Comment by catsby** [comment]
https://github.com/hashicorp/terraform/pull/6687 has been merged, closing this, thanks!
