### ISSUE TITLE
Untagged default ACL in VPC - AWS

### ISSUE THREAD

**Issue by boxrick** [hashicorp/terraform#6470]
### Terraform Version
0.6.15

### Affected Resource(s)

Please list the resources as a list, for example:
- aws_vpc

### Terraform Configuration Files
resource "aws_vpc" "vpc_primary" {
  cidr_block           = "${var.vpc_cidr}"
  enable_dns_hostnames = true
  instance_tenancy    = "default"

  tags {
    Name               = "${var.product}-${var.environment}-vpc"
    Owner              = "${var.resource_owner}"
  }
}

### Important Factoids
When I create a VPC using Terraform, it creates a default ( untagged ) ACL. This should inherit or use the tags assigned to the VPC. Instead this ACL remains un-named and untagged with no way to control this resource from Terraform. As a minimum it should be tagged to match the details of the VPC or an option within this resource to tag the default ACL even if we create more.

**Comment by catsby** [comment]
Hello @boxrick – 

Terraform v0.6.15 included a resource to manage the Default Network ACL, with tags support:

- https://www.terraform.io/docs/providers/aws/r/default_network_acl.html

Please let me know if that resource doesn't suit your needs! It's new as of the latest release, but it should allow you to manage the default acl. There are some caveats explained in the documentation though.
