### ISSUE TITLE
Terraform crashes when `disk` is wrongly declared in a `google_compute_instance`

### ISSUE THREAD

**Issue by dvianello** [hashicorp/terraform#6495]
### Terraform Version

Terraform v0.6.15
### Affected Resource(s)
- google_compute_instance
- google_compute_disk
### Terraform Configuration Files

``` hcl
resource "google_compute_instance" "openlava_nfs" {
    name = "${var.name}-nfs"
    machine_type = "${var.nfs_machine_type}"
    zone = "${var.zone}"
    disk {
      image = "${var.image}"
      type = "${var.storage_type}"
    }
    disk {
      disk = "${google_compute_disk.openlava_homes.name}"
      type = "${var.storage_type}"
      device_name = "xvdb"
    }
    disk {
      disk = "${google_compute_disk.openlava_pipelines.name}"
      type = "${var.storage_type}"
      device_name = "xvdc"
    }
    metadata {
      block-project-ssh-keys = "TRUE"
      ssh-keys = "${var.ssh_auth_string}"
    }
    network_interface {
    subnetwork = "${google_compute_subnetwork.private_subnet.name}"
    }
}

resource "google_compute_disk" "openlava_homes" {
    name = "openlava-homes"
    zone = "${var.zone}"
    type = "${var.storage_type}"
    size = "${var.homes_size}"
}

resource "google_compute_disk" "openlava_pipelines" {
    name = "openlava-pipelines"
    zone = "${var.zone}"
    type = "${var.storage_type}"
    size = "${var.pipelines_size}"
}
```
### Panic Output

https://gist.github.com/dvianello/b9b5124398b9ae8064d12b9ec45077aa
### Expected Behavior

Terraform exits with an error stating that `type` cannot be used when declaring a `disk` into a `google_compute_instance` referring to an already created  `google_compute_disk`. I understand that there is no logic in doing that (now!) but Terraform should exit with an error, not crashing. Docs should be updated, too.
### Actual Behavior

Terraform crashes
### Steps to Reproduce
1. `terraform apply`

**Comment by paddyforan** [comment]
Hi @dvianello! Thanks for reporting the issue, and sorry for any inconvenience caused.

Thanks to your information, I've got a minimal reproduction of a config that will cause the crash:

```tf
resource "google_compute_instance" "foo" {
  name         = "foo"
  machine_type = "f1-micro"
  zone         = "us-west1-a"

  disk {
    image = "ubuntu-os-cloud/ubuntu-1604-lts"
    type  = "pd-standard"
  }

  disk {
    disk        = "${google_compute_disk.bar.name}"
    type        = "pd-standard"
    device_name = "xvdb"
  }

  network_interface {
    network = "default"
  }
}

resource "google_compute_disk" "bar" {
  name = "bar"
  zone = "us-west1-a"
  type = "pd-standard"
  size = "1"
}
```

As you mentioned, this config file isn't valid, and even after we fix this crash, won't work. But you're totally right that this should be an error message and not a crash. I'm working on a patch for that right now.
