### ISSUE TITLE
Terraform Crashes with panic: Unary - is only allowed

### ISSUE THREAD

**Issue by zulkarnainsncr** [hashicorp/terraform#6498]
### Terraform Version
```
2016/05/05 10:09:33 [INFO] Terraform version: 0.6.15 0c5c54e
```

### Panic Output

```
2016/05/05 10:09:33 [INFO] Terraform version: 0.6.15 0c5c54e
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] Discovered plugin: atlas = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-atlas
2016/05/05 10:09:33 [DEBUG] Discovered plugin: aws = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-aws
2016/05/05 10:09:33 [DEBUG] Discovered plugin: azure = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-azure
2016/05/05 10:09:33 [DEBUG] Discovered plugin: azurerm = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-azurerm
2016/05/05 10:09:33 [DEBUG] Discovered plugin: chef = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-chef
2016/05/05 10:09:33 [DEBUG] Discovered plugin: clc = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-clc
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cloudflare = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cloudflare
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cloudstack = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cloudstack
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cobbler = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cobbler
2016/05/05 10:09:33 [DEBUG] Discovered plugin: consul = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-consul
2016/05/05 10:09:33 [DEBUG] Discovered plugin: datadog = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-datadog
2016/05/05 10:09:33 [DEBUG] Discovered plugin: digitalocean = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-digitalocean
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dme = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dme
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dnsimple = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dnsimple
2016/05/05 10:09:33 [DEBUG] Discovered plugin: docker = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-docker
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dyn = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dyn
2016/05/05 10:09:33 [DEBUG] Discovered plugin: fastly = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-fastly
2016/05/05 10:09:33 [DEBUG] Discovered plugin: github = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-github
2016/05/05 10:09:33 [DEBUG] Discovered plugin: google = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-google
2016/05/05 10:09:33 [DEBUG] Discovered plugin: heroku = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-heroku
2016/05/05 10:09:33 [DEBUG] Discovered plugin: influxdb = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-influxdb
2016/05/05 10:09:33 [DEBUG] Discovered plugin: mailgun = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-mailgun
2016/05/05 10:09:33 [DEBUG] Discovered plugin: mysql = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-mysql
2016/05/05 10:09:33 [DEBUG] Discovered plugin: null = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-null
2016/05/05 10:09:33 [DEBUG] Discovered plugin: openstack = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-openstack
2016/05/05 10:09:33 [DEBUG] Discovered plugin: packet = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-packet
2016/05/05 10:09:33 [DEBUG] Discovered plugin: postgresql = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-postgresql
2016/05/05 10:09:33 [DEBUG] Discovered plugin: powerdns = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-powerdns
2016/05/05 10:09:33 [DEBUG] Discovered plugin: rundeck = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-rundeck
2016/05/05 10:09:33 [DEBUG] Discovered plugin: statuscake = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-statuscake
2016/05/05 10:09:33 [DEBUG] Discovered plugin: template = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-template
2016/05/05 10:09:33 [DEBUG] Discovered plugin: terraform = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-terraform
2016/05/05 10:09:33 [DEBUG] Discovered plugin: tls = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-tls
2016/05/05 10:09:33 [DEBUG] Discovered plugin: triton = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-triton
2016/05/05 10:09:33 [DEBUG] Discovered plugin: ultradns = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-ultradns
2016/05/05 10:09:33 [DEBUG] Discovered plugin: vcd = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-vcd
2016/05/05 10:09:33 [DEBUG] Discovered plugin: vsphere = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-vsphere
2016/05/05 10:09:33 [DEBUG] Discovered plugin: chef = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-chef
2016/05/05 10:09:33 [DEBUG] Discovered plugin: file = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-file
2016/05/05 10:09:33 [DEBUG] Discovered plugin: local-exec = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-local-exec
2016/05/05 10:09:33 [DEBUG] Discovered plugin: remote-exec = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-remote-exec
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] Attempting to open CLI config file: /Users/zkag0001/.terraformrc
2016/05/05 10:09:33 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] waiting for all plugin processes to complete...
panic: Unary - is only allowed

goroutine 1 [running]:
panic(0x83c060, 0x821529050)
/opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.(parserParserImpl).Parse(0x82152aa00, 0x882138d870, 0x821525920, 0x0)
lang.y:133 +0x2168
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.parserParse(0x882138d870, 0x821525920, 0x117eef8)
yaccpar:153 +0x9b
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.Parse(0x8215264c0, 0x39, 0x0, 0x0, 0x0, 0x0)
/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil/parse.go:27 +0x103
github.com/hashicorp/terraform/config.(interpolationWalker).Primitive(0x821499b80, 0x83c060, 0x821528800, 0x98, 0x0, 0x0)
/opt/gopath/src/github.com/hashicorp/terraform/config/interpolate_walk.go:116 +0x155
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkPrimitive(0x82c620, 0x821528ef0, 0x94, 0xb37d20, 0x821499b80, 0x0, 0x0)
```

**Comment by zulkarnainsncr** [comment]
2016/05/05 10:09:33 [INFO] Terraform version: 0.6.15  0c5c54e7b6a59d77e89ce24057509503639d8d3d
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] Discovered plugin: atlas = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-atlas
2016/05/05 10:09:33 [DEBUG] Discovered plugin: aws = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-aws
2016/05/05 10:09:33 [DEBUG] Discovered plugin: azure = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-azure
2016/05/05 10:09:33 [DEBUG] Discovered plugin: azurerm = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-azurerm
2016/05/05 10:09:33 [DEBUG] Discovered plugin: chef = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-chef
2016/05/05 10:09:33 [DEBUG] Discovered plugin: clc = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-clc
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cloudflare = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cloudflare
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cloudstack = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cloudstack
2016/05/05 10:09:33 [DEBUG] Discovered plugin: cobbler = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-cobbler
2016/05/05 10:09:33 [DEBUG] Discovered plugin: consul = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-consul
2016/05/05 10:09:33 [DEBUG] Discovered plugin: datadog = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-datadog
2016/05/05 10:09:33 [DEBUG] Discovered plugin: digitalocean = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-digitalocean
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dme = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dme
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dnsimple = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dnsimple
2016/05/05 10:09:33 [DEBUG] Discovered plugin: docker = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-docker
2016/05/05 10:09:33 [DEBUG] Discovered plugin: dyn = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-dyn
2016/05/05 10:09:33 [DEBUG] Discovered plugin: fastly = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-fastly
2016/05/05 10:09:33 [DEBUG] Discovered plugin: github = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-github
2016/05/05 10:09:33 [DEBUG] Discovered plugin: google = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-google
2016/05/05 10:09:33 [DEBUG] Discovered plugin: heroku = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-heroku
2016/05/05 10:09:33 [DEBUG] Discovered plugin: influxdb = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-influxdb
2016/05/05 10:09:33 [DEBUG] Discovered plugin: mailgun = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-mailgun
2016/05/05 10:09:33 [DEBUG] Discovered plugin: mysql = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-mysql
2016/05/05 10:09:33 [DEBUG] Discovered plugin: null = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-null
2016/05/05 10:09:33 [DEBUG] Discovered plugin: openstack = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-openstack
2016/05/05 10:09:33 [DEBUG] Discovered plugin: packet = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-packet
2016/05/05 10:09:33 [DEBUG] Discovered plugin: postgresql = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-postgresql
2016/05/05 10:09:33 [DEBUG] Discovered plugin: powerdns = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-powerdns
2016/05/05 10:09:33 [DEBUG] Discovered plugin: rundeck = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-rundeck
2016/05/05 10:09:33 [DEBUG] Discovered plugin: statuscake = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-statuscake
2016/05/05 10:09:33 [DEBUG] Discovered plugin: template = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-template
2016/05/05 10:09:33 [DEBUG] Discovered plugin: terraform = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-terraform
2016/05/05 10:09:33 [DEBUG] Discovered plugin: tls = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-tls
2016/05/05 10:09:33 [DEBUG] Discovered plugin: triton = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-triton
2016/05/05 10:09:33 [DEBUG] Discovered plugin: ultradns = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-ultradns
2016/05/05 10:09:33 [DEBUG] Discovered plugin: vcd = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-vcd
2016/05/05 10:09:33 [DEBUG] Discovered plugin: vsphere = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provider-vsphere
2016/05/05 10:09:33 [DEBUG] Discovered plugin: chef = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-chef
2016/05/05 10:09:33 [DEBUG] Discovered plugin: file = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-file
2016/05/05 10:09:33 [DEBUG] Discovered plugin: local-exec = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-local-exec
2016/05/05 10:09:33 [DEBUG] Discovered plugin: remote-exec = /usr/local/terraform_0.6.15_darwin_amd64/terraform-provisioner-remote-exec
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] Attempting to open CLI config file: /Users/zkag0001/.terraformrc
2016/05/05 10:09:33 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/05/05 10:09:33 [DEBUG] Detected home directory from env var: /Users/zkag0001
2016/05/05 10:09:33 [DEBUG] waiting for all plugin processes to complete...
panic: Unary - is only allowed

goroutine 1 [running]:
panic(0x83c060, 0x821529050)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.(*parserParserImpl).Parse(0x82152aa00, 0x882138d870, 0x821525920, 0x0)
        lang.y:133 +0x2168
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.parserParse(0x882138d870, 0x821525920, 0x117eef8)
        yaccpar:153 +0x9b
github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil.Parse(0x8215264c0, 0x39, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil/parse.go:27 +0x103
github.com/hashicorp/terraform/config.(*interpolationWalker).Primitive(0x821499b80, 0x83c060, 0x821528800, 0x98, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/interpolate_walk.go:116 +0x155
github.com/hashicorp/terraform/vendor/github.com/mitchellh/reflectwalk.walkPrimitive(0x82c620, 0x821528ef0, 0x94, 0xb37d20, 0x821499b80, 0x0, 0x0)

**Comment by phinze** [comment]
Hi @zulkarnainsncr - sorry to hear about the crash! Looks like you had a little trouble with the new issue template - I'll reformat the above issue for you. 👍

**Comment by phinze** [comment]
Doing a search of the issues - looks like the same panic is reported over in #5672.

If you have the config that triggered this panic - can you drop it over on that thread? Thanks!
