### ISSUE TITLE
aws elb does not add new instance when count increases

### ISSUE THREAD

**Issue by spyrospph** [hashicorp/terraform#650]
I create ec2 instances:

resource "aws_instance" "webserver" {

<some config>

 count               = "${var.webserver_count}"
}

In my elb declaration I do:

resource "aws_elb" "liveweb_elb" {

<some config>

instances = ["${aws_instance.webserver.*.id}"]
}

When I start with 2 instances and then I try to increase to 3, the NEW instance does not get auto registered in the elb.

**Comment by mitchellh** [comment]
This is also fixed. Note that we have test cases covering this now too so I imagine this was fixed awhile back.
