### ISSUE TITLE
Adding retry to chef provisioner

### ISSUE THREAD

**Issue by mrlamroger** [hashicorp/terraform#6506]
Hi,

Are there plans to add retry logic to the chef provisioner? Something similar to the max_retries in the aws  provider.

**Comment by svanharmelen** [comment]
@mrlamroger could you specify your question a little? What step you you think should benefit from adding some retry logic?

**Comment by svanharmelen** [comment]
@mrlamroger I'm tempted to close this issue as I don't understand what this could solve. So please let me know your thoughts so I can understand your point... Thx!

**Comment by svanharmelen** [comment]
Closing issue for now, if you have any updates please just reopen the issue at will :wink:

**Comment by davidk01** [comment]
The issue is that some flaky Chef recipes and run lists can benefit from running a few times. I've seen this happen several times where on a small instance `fork` fails with out of memory error the first time but then is successful on a retry.

**Comment by Chili-Man** [comment]
We use hosted Chef, and sometimes the Chef Servers are flaky and fail to respond causing the chef-client run to fail; Usually retrying it several times will eventually make it succeed all the way through. We've had to build a wrapper script around terraform to add this logic, which is not ideal. It would be a lot cleaner to have the retry logic on the chef provisioner @svanharmelen

**Comment by jsirex** [comment]
Vote on this too.
There are many situation when chef may fail at first time.
