### ISSUE TITLE
aws_route53_record changing name from 'foo.terraform.io'  to 'foo.terraform.io.' with create_before_destroy end up with no record

### ISSUE THREAD

**Issue by donaldguy** [hashicorp/terraform#6511]
One thing the title elides is that I am using a state injected by dtan4/terraforming (and mitchellh's `state mv` pr ... actually ...  but I don't think that's a determining factor) which a) was responsible for the disparity in trailing period (even though my state was consistent, albeit moved from one place to another) and b) weight needed to be reset cause I had a pre- dtan4/terraforming#197 install

I haven't gotten a chance to work on an isolated reproduction but I feel pretty confident based on my knowledge of how states are managed that its probably an issue produced other ways
 
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "public_dns" {
  zone_id = "<redacted>"
  name = "${concat(var.subdomain_name, ".terraform.io.")}"
  type = "A"
  ttl = "3600"
  records = ["${aws_eip.subdomain_server.public_ip}"]

  lifecycle {
    create_before_destroy = true
  }
}
```

### (Non-debug) output
```
$ terraform plan
[snip]
-/+ module.foo.bar.aws_route53_record.public_dns
    fqdn:               "subdomain.terraform.io" => "<computed>"
    name:               "subdomain.terraform.io" => "subdomain.terraform.io." (forces new resource)
    records.#:          "1" => "1"
    records.3095317055: "<ip>" => "<same ip>"
    ttl:                "3600" => "3600"
    type:               "A" => "A"
    weight:             "" => "-1"
    zone_id:            "<redacted>" => "<redacted>"
[snip]

$ terraform apply
module.foo.bar.aws_route53_record.public_dns: Refreshing state... (ID: <redacted>_subdomains.terraform.io_A)
module.foo.bar.aws_route53_record.public_dns: Creating...
  fqdn:               "" => "<computed>"
  name:               "" => "subdomain.terraform.io."
  records.#:          "" => "1"
  records.3095317055: "" => "<ip>"
  ttl:                "" => "3600"
  type:               "" => "A"
  weight:             "" => "-1"
  zone_id:            "" => "<redacted>"
module.foo.bar.aws_route53_record.public_dns: Still creating... (10s elapsed)
module.foo.bar.aws_route53_record.public_dns: Still creating... (20s elapsed)
module.foo.bar.aws_route53_record.public_dns: Still creating... (30s elapsed)
module.foo.bar.aws_route53_record.public_dns: Creation complete
module.foo.bar.aws_route53_record.public_dns: Destroying...

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Expected Behavior
Terraform should have either never detected a needed change between that with and without the root domain OR it should, more generally, do some sort of check that the resource created in a create_before_delete isn't actually identical to the resource its about to delete

in either case when the terraform run is successfully complete there shouldn't be no DNS record  (or it should report an error upon attempting to delete that which it just created)

### Actual Behavior
A roughly no-op operation was done to create an identical record, then "both" were deleted (probably only one is deleted, but AWS treats it as equivalent)

at the end of the run there is no record being published by the name servers. A subsequent `terraform apply` recreates it

### Steps to Reproduce (what I did. there are probably other ways to trigger)
1. Manually (or actually with an old deprecated terraform state) create a route53 record pointing to your hostname at your domain
2.  Write a new terraform hcl designating the record and  `terraform apply` (or in my case run dtan4/`terraforming r53r --tfstate > dns.tfstate` and `terraform7 state mv -state=dns.tfstate -state-out=terraform.tfstate aws_route53_record.subdomain-terraform-io-A module.foo.module.bar.aws_route53_record.public_dns` )
4. Write a new terraform hcl designating the record, or possibly edit your existing state)adding (or maybe removing?) a trailing dot from the tld.
5. `terraform apply`

**Comment by catsby** [comment]
Hey @donaldguy thanks for reporting this! This is a tricky one, since the Route53 API doesn't have a strict create / update endpoint, it just accepts PUT and a change request (things that don't exist are implicitly created). `create_before_destroy` presents a challenge there...

I've opened #6592 to address your particular case here, where the name should not change here at all, and thus no delete after being created.

**Comment by catsby** [comment]
Hey there – #6592 has been merged and will go out in the next release, thanks!
