### ISSUE TITLE
notFound error while destroying a GCP Instance with attached disks

### ISSUE THREAD

**Issue by dvianello** [hashicorp/terraform#6515]
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- google_compute_instance
- google_compute_disk

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "openlava_nfs" {
  name         = "${var.name}-nfs"
  machine_type = "${var.nfs_machine_type}"
  zone         = "${var.zone}"
  tags         = ["nfs", "no-ip"]

  disk {
    image = "${var.image}"
    type  = "${var.storage_type}"
  }

  disk {
    disk        = "${google_compute_disk.openlava_homes.name}"
    device_name = "xvdb"
  }

  disk {
    disk        = "${google_compute_disk.openlava_pipelines.name}"
    device_name = "xvdc"
  }

  network_interface {
    subnetwork = "${google_compute_subnetwork.private_subnet.name}"
  }
}

resource "google_compute_disk" "openlava_homes" {
  name = "openlava-homes"
  zone = "${var.zone}"
  type = "${var.storage_type}"
  size = "${var.homes_size}"
}

resource "google_compute_disk" "openlava_pipelines" {
  name = "openlava-pipelines"
  zone = "${var.zone}"
  type = "${var.storage_type}"
  size = "${var.pipelines_size}"
}
```

### Debug Output
https://gist.github.com/dvianello/b01fcdf37b6a95e15ef5dd9da3136219

### Expected Behavior
Terraform destroys the provisioned infrastructure without errors.

### Actual Behavior
Terraform exits with the following error: 
> Error applying plan:
> 
> 2 error(s) occurred:
> 
> * google_compute_disk.openlava_pipelines: Error deleting disk: googleapi: Error 404: The resource 'projects/extreme-lore-114513/zones/europe-west1-d/disks/openlava-pipelines' was not found, notFound
* google_compute_disk.openlava_homes: Error deleting disk: googleapi: Error 404: The resource 'projects/extreme-lore-114513/zones/europe-west1-d/disks/openlava-homes' was not found, notFound
> 

Infrastructure is however destroyed correctly. Running a second `terraform destroy` exits successfully, as nothing has to be destroyed.

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by sl1pm4t** [comment]
Seems to be a duplicate of #5942

**Comment by dvianello** [comment]
I guess you're right - sorry about that!
