### ISSUE TITLE
provider/postgresql: default ssl_mode is "prefer" introduces breaking change with AWS RDS

### ISSUE THREAD

**Issue by gdowmont** [hashicorp/terraform#6519]
Following the upgrade to 0.6.15, and the commit https://github.com/hashicorp/terraform/commit/220d73f32c8cfef1de1a40e5f29ef3f39aa51c2d we have found that we were unable to run plan/apply using Postgresql provider with the following error:

`postgresql_role.****: Error reading info about role: pq: unsupported sslmode "prefer"; only "require" (default), "verify-full", and "disable" supported`

We are using AWS RDS PostgreSQL 9.4.5 . Setting sslmode to require in the provider settings allows us to run plan/apply however the message on https://github.com/hashicorp/terraform/commit/220d73f32c8cfef1de1a40e5f29ef3f39aa51c2d explicitly mentions that "prefer" was set to avoid any breaking changes.

**Comment by apparentlymart** [comment]
Hi @gdowmont. Sorry for the trouble here.

The choice of "prefer" was made based on the Postgres manual saying that it was the default. Has RDS just got a more restrictive configuration than regular Postgres, or is the documentation I was reading out of date or otherwise inaccurate? (I will readily confess to not knowing much about Postgres, so I was relying on its documentation and some very light local testing here.)

**Comment by gdowmont** [comment]
Hey Martin. I doubt there is a way to check in the provider if the postgres
is RDS. Would it make sense to put a note in the docs to indicate that
"prefer" cannot be used with RDS. By the way 'pq' docs mention that
"require" is the default for the driver which oddly contradicts the default
from postgres. See https://godoc.org/github.com/lib/pq

**Comment by apparentlymart** [comment]
I'm not sure here whether it would be better to document that this needs to be set or to just change the default to be "require"... I'd appreciate thoughts from people who know more about Postgres than me about whether "require" is an expected default or whether that would be surprising or cause problems for people...

When I tested this locally whatever version of postgres I got out of the Ubuntu archive was able to accept "prefer" but I didn't test whether that was actually the default... I just trusted the docs.

**Comment by stack72** [comment]
@apparentlymart hat do we think the resolution of this issue is?

**Comment by mitchellh** [comment]
Its unfortunate this was a breaking change for you @gdowmont and I'm sorry we couldn't do something about it sooner. Its now been over 6 months since we introduced the change and you're the only person to have been hit by this so I think we're okay... I'm sorry this affected you though.
