### ISSUE TITLE
AWS Block device changes don't need to destroy the aws_instance

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#654]
We should be able to change block devices without tearing down the instances... I can see from an immutable infrastructure perspective why you might not want to allow that though.

**Comment by phinze** [comment]
You can do this today by managing [`aws_ebs_volume`](https://terraform.io/docs/providers/aws/r/ebs_volume.html) resources separately and attaching them via [`aws_volume_attachment`](https://terraform.io/docs/providers/aws/r/volume_attachment.html). :+1:
