### ISSUE TITLE
security_groups confusing behavior on non-default VPC

### ISSUE THREAD

**Issue by arsdehnel** [hashicorp/terraform#6546]
### Terraform Version
v0.6.15

### Affected Resource(s)
- aws_instance

I was using security_groups within an aws_instance resource that was not within my default VPC:

```hcl
resource "aws_instance" "bastion" {
  ami = "ami-ef5e24df"
  depends_on = ["aws_security_group.bastion"]
  instance_type = "t2.micro"
  subnet_id = "${aws_subnet.test_subnet.id}"
  security_groups = ["${aws_security_group.bastion.id}"]
}
```

This created the instance without a problem and created the reference to the security group without a problem (in the AWS console and the `terraform apply` output).  But it was not saved in the terraform state so every time I ran `apply` I got a -/+ for that instance to recreate it with the same reference to the same existing security group.  Changing that line to the `vpc_security_group_ids` solved my problem without having to change the value that I'm providing.

Seems to me that security_groups should be considered for deprecation as the `vpc_security_group_ids` attribute seems to handle the situation better and works for both default and non-default VPCs the same.

**Comment by arsdehnel** [comment]
Also just noticed that this behavior is slightly different than the behavior for `aws_security_group` resources which is also confusing.  Realizing that now this is getting to be more involved of a request, too.

**Comment by apparentlymart** [comment]
Hi @arsdehnel. Sorry for the trouble here!

This issue was reported a few times, so I'm going to close this one to consolidate the discussion in #6416.
