### ISSUE TITLE
Terraform v0.6.16 Release Process

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#6561]
Hello again @apparentlymart, @jtopjian, @sparkprime, @stack72, @radeksimko, @svanharmelen , @lwander and @ack!

It's Terraform release time again, this time for v0.6.16

Please hold off on merges until this issue is closed - thanks!

**Comment by phinze** [comment]
Reopening until dev-0.7 merge is done.

**Comment by jen20** [comment]
This is done! Thanks everyone.
