### ISSUE TITLE
vSphere Provider Roadmap Outline

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6565]
# vSphere components started

Will update what is completed:
1. Virtual machines - mostly done
   - Update functionatlity is underway
2. Disks - Need to double check what is doen
   - vmx attachable disks 
   - cdrom iso images
3. Misc
   - folder - update is missing
   - cdrom
4. Finders
   - some basic finders are implemented to support object creation
# Overview of vSphere components not started
1. Base servers crud  **P3**
   - single vsphere server (not going to be addressed)
   - cluster
     - add, update, create, no delete
2. Datacenter  **P2**
   - cluster and non-clustered
   - CRD are in govc ... do we have update?
3. Datastores - **P1** -  some work done
   - non-ha datastores
   - ha cluster based datastores (SDRS)
   - basic file commands cp,mv,rm
   - CRD are in govc ... do we have update?
   - basic file commands
4. Networks - **P1**
   - portgroups
     - CRD - no update
   - distributed virtual switch
   - firewalls
   - vnics
   - finders for "Networks" but no CUD available R only - TODO verify
5. Resource pools - prority??
   - Full CRUD
6. ESX Hosts - **P4**
   - portgroups
   - vswitch
   - storage partition
   - maintenance mode
   - host options
   - vnic
7. Misc - **P4**
   - Events
   - Extensions
   - Host Info
   - Licenses
   - Logs

**Comment by chrislovecnm** [comment]
@stack72 @jen20 @phinze ~ can I get a vsphere label

**Comment by rossedman** [comment]
👍 Looks good.

**Comment by thetuxkeeper** [comment]
:+1: Same here, looks good.
Some "missing" things:
- folders have no update implemented, but supported by `Rename_Task` in vSphere API (haven't checked govmomi)
- datastore files: upload (but no creation without source), rename/update, read and deletion are implemented. So file uploads should already work (vmdk, cdrom iso, ...)

**Comment by chrislovecnm** [comment]
> datastore files: upload (but no creation without source), rename/update, read and deletion are implemented. So file uploads should already work (vmdk, cdrom iso, ...)

I this is number 7 item one?

**Comment by thetuxkeeper** [comment]
@chrislovecnm: I think it fits best to "Datastores"->"basic file commands". Since the files are always in a datastore.
When I think about "Folders" it's the organizational structure for VMs in "VMs and Templates" view in the vSphere client. I think that's also the terminology in the API.

**Comment by chrislovecnm** [comment]
@thetuxkeeper where do you want me to put the text?

**Comment by thetuxkeeper** [comment]
I would put it to "Datastores"->"basic file commands".
And you can remove "Image Uploads" since it's covered by the datastore operations if there's nothing I'm missing.

**Comment by mrjcleaver** [comment]
@chrislovecnm - has this doc / initiative been moved elsewhere?

**Comment by chrislovecnm** [comment]
@mrjcleaver the velocity of this provider has fallen ;(

**Comment by mrjcleaver** [comment]
My belief is that this happened as a consequence of it being sucked into the main repo. Now it is subject to central approval, to whom it is comparatively unimportant (vs. say AWS) therefore neglected.

**Comment by chrislovecnm** [comment]
Hashicorp is also not able to do testing, but yes the PR process has been challenging.

**Comment by mrjcleaver** [comment]
Okay, well, the harder it is the less momentum the initiative will have.

**Comment by stack72** [comment]
FYI, I am in the process of getting an ESXi cluster setup for us to be able to run tests against - this will help at least get the tests working and allow us to be able to test PRs for functionality working as expected

**Comment by donbecker** [comment]
@chrislovecnm Is the roadmap in this issue updated? 

I haven't found another reference anywhere detailing what in vSphere is supported, and what is not.

**Comment by chrislovecnm** [comment]
The issue is not completely up to date, the docs are fairly up to date

**Comment by donbecker** [comment]
@chrislovecnm thanks for the quick reply. 

With VMware now supporting [OpenStack](http://www.vmware.com/products/openstack.htmll) on top of ESXi, will development on the vSphere provider likely wind down / transition to the OpenStack provider?

**Comment by renaudhager** [comment]
Hi all,

Do you have a plan to support hot increase for CPU and memory ? 

Thanks.
