### ISSUE TITLE
openstack firewall policy and rules: avoid big array

### ISSUE THREAD

**Issue by damstux** [hashicorp/terraform#6567]
Hello,

I would like to manage my openstack firewall policy and rules, I have read this:

https://www.terraform.io/docs/providers/openstack/r/fw_policy_v1.html

Is it possible to iterate over openstack_fw_rule_v1.rule_* to avoid a long array like this:
  rules = ["${openstack_fw_rule_v1.rule_1.id}",
           "${openstack_fw_rule_v1.rule_2.id}"]

Thanks !

**Comment by jen20** [comment]
Hi @damstux! Right now there is no way to do wildcard matching of resource names - only those generated by a count are eligible for the "splat" syntax. I don't think there is an easy workaround here - if you're using 0.7rc you can define the list as a variable to move it out of band of the configuration however. If you have further questions please feel free to reopen this issue!
