### ISSUE TITLE
provider/vsphere: Existing VMDK deleted with VM 

### ISSUE THREAD

**Issue by dagnello** [hashicorp/terraform#6572]
Running terraform:
Terraform v0.6.16

When a VM is created with an existing VMDK with terraform apply, the VMDK should not be deleted when the VM resource is deleted with terraform destroy.  Current functionality deletes the VMDK with the VM.  This makes the initial state and final state of vSphere different.

**Comment by chrislovecnm** [comment]
A quick skim of the code is not show any evidence of that we are deliberately removing the disk.  So maybe I am missing the delete call, or the api is tanking the file.  Couple of questions:

1. version of vsphere?
2. what are the streps that you are following to get this behavior?
3. have you run the master branch or ran the unit tests?

Thanks

Chris

**Comment by thetuxkeeper** [comment]
I think it's the way vmware does it. govmomi just calls https://vdc-repo.vmware.com/vmwb-repository/dcr-public/2d445149-7707-4c7d-98a7-9f00394b7df2/7322d611-ef3b-454a-ab63-ad3302d8b218/doc/vim.ManagedEntity.html#destroy
Perhaps you have to remove the disk first (without deleting it) and then deleting the VM. I think that's the way you have to do it with the vSphere client.

**Comment by chrislovecnm** [comment]
@thetuxkeeper I assume that is not how we are doing it ... LOL

**Comment by dagnello** [comment]
this has been resolved
