### ISSUE TITLE
azurerm - INFO - WALinuxAgent ERROR:unicode argument without an encoding occured creating /var/lib/waagent/CustomData

### ISSUE THREAD

**Issue by tasquith** [hashicorp/terraform#6591]
Please see the following which I've encountered using terraform v0.6.16 (not that I think its a TF problem). Raising here for visibility if others get the same error.

Using base64 encoded user data (as required by the API), an error related to encoding occurs when provisioning the machine. 

Full details below:

Azure/WALinuxAgent#187

**Comment by stack72** [comment]
@tasquith closing this as this seems to have been closed upstream as well!
