### ISSUE TITLE
Add support for iam_roles to Redshift

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#6594]
Redshift somewhat recently added the ability to assign a list of IamRoles to a cluster, e.g. in the [go sdk](http://docs.aws.amazon.com/sdk-for-go/api/service/redshift.html#type-Cluster). This lets you specify the iam credentials of an s3 bucket or dynamodb table to COPY from in a role when you create the redshift cluster, so you don't need to pass them in to the COPY sql command.

Would be great for this to make it into terraform.

**Comment by stack72** [comment]
Hi @dcosson 

Just a FYI, I have a PR open for this right now - it is a WIP as it requires 1 other PR to merge first :)

P.

**Comment by dcosson** [comment]
@stack72 sweet!

**Comment by stack72** [comment]
Closed in #6647
