### ISSUE TITLE
Cannot remove `template_name` from beanstalk environment

### ISSUE THREAD

**Issue by tecnobrat** [hashicorp/terraform#6603]
Looks like if you add a `template_name` to a beanstalk environment, and then try to remove it later, you get the following error:

```
* aws_elastic_beanstalk_environment.360_content_pass_admin: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, UpdateEnvironmentInput.TemplateName.
```

Terraform v0.6.16

**Comment by tecnobrat** [comment]
Looks like it actually removed, in despite of this error.

**Comment by dzhus** [comment]
I had to do `terraform apply` twice in order to move away from template.

**Comment by catsby** [comment]
#7811 should address this!
