### ISSUE TITLE
aws_opsworks_stack hangs on creating IAM role

### ISSUE THREAD

**Issue by iroller** [hashicorp/terraform#6605]
Hi,

I'm using the following template to create `aws_opsworks_stack` and it just hangs for 20+ minutes on `terraform apply` with `Service Role Arn: Credential has not the necessary trust relationship`.

I've tried it on a completely new AWS account and the result is the same.

### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- aws_opsworks_stack
- aws_iam_role_policy
- aws_iam_role

### Terraform Configuration Files
IAM role and policy configs were taken from terraform docs:
https://gist.github.com/iroller/435b4d326d738e4faa5d4f9685cd73f5

### Debug Output
https://gist.github.com/iroller/76f3d5923399347237ffa1ee249b1d74

### Expected Behavior
OpsWorks stack should be created

### Actual Behavior
Hangs on creating IAM role
### Steps to Reproduce
1. `terraform apply`

Also interrupting it with `Ctrl+C` doesn't seem to be working in this case.

**Comment by iroller** [comment]
The following change in policy helped:
```
            "Principal": {"AWS": "*"},
```

**Comment by lethalpaga** [comment]
For the record, do **not** use `"AWS":"*"` as a principal, this means you allow all the AWS users (including in different accounts) to assume that role.

Use `"Service": "opsworks.amazonaws.com"` instead.
