### ISSUE TITLE
RDS support for OpsWorks

### ISSUE THREAD

**Issue by iroller** [hashicorp/terraform#6608]
Hi there,

Is there a chance the support for [RDS in OpsWorks](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_RdsDbInstance.html) is in work somewhere? I'm new to terraform and can be just not seeing it. Could you let me know if it's something not yet supported by terraform and if it's planned to be supported?

Thanks!

**Comment by iroller** [comment]
To give some details I was trying to use the following:
```
resource "aws_opsworks_application" "my-app" {
  depends_on = ["aws_db_instance.my-rds"]

  # DB
  data_source_arn = "${aws_db_instance.my-rds.arn}"
  data_source_type = "RdsDbInstance"
  data_source_database_name = "myapp_production"
...
```

And it's always giving me the same error:
```
* aws_opsworks_application.my-app: ResourceNotFoundException: unable to find rds instance with ARN arn:aws:rds:us-east-1:...:db:my-rds
```

Even though there's aws rds instance setup separately using `aws_db_instance` terraform resource.

**Comment by catsby** [comment]
Hello – We do now support a MySQL layer:

- https://www.terraform.io/docs/providers/aws/r/opsworks_mysql_layer.html

Please let us know if that's not what you're looking for here. Thanks!
