### ISSUE TITLE
Using network name not working for openstack_compute_instance_v2 

### ISSUE THREAD

**Issue by sebastien-prudhomme** [hashicorp/terraform#6609]
### Terraform Version

Terraform v0.6.16

### Affected Resource(s)

openstack_compute_instance_v2 

### Terraform Configuration Files
```hcl
resource "openstack_compute_instance_v2" "jmeter-2" {
  name = "jmeter-2"
  availability_zone = "Apple"
  image_name = "ubuntu-16.04-20160509"
  flavor_name = "m1.small"
  user_data = "${file("jmeter-2.cloudinit")}"

  network {
    name = "internal-subnet2"
  }
}
```

### Output

* openstack_compute_instance_v2.jmeter-2: Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST https://openstack-pprd.national.agri:8774/v2/bc0bf96ab70e464ca3dce73e3e086775/servers], but got 400 instead
{"badRequest": {"message": "Bad network format: missing 'uuid'", "code": 400}}

### Comments

When looking in Terraform source code, i see no use of "IDFromName" function for network part (as for flavor or image names)

**Comment by jtopjian** [comment]
@sebastien-prudhomme can you provide some details about your OpenStack environment? Is it Neutron or nova-network based?

If you run the following command on the command-line, does it succeed?

```shell
$ nova net-list
```

**Comment by sebastien-prudhomme** [comment]
Our environment is based on Neutron:

```
$ neutreon net-list
+--------------------------------------+--------------+------------------------------------------------------+
| id                                   | name         | subnets                                              |
+--------------------------------------+--------------+------------------------------------------------------+
| 20e663e4-a933-471a-ac3a-1a83b62b7608 | vlan115      | 2959a9fa-6150-4695-8132-6bf030d76a81 10.207.223.0/25 |
| 695884a6-908f-491d-8210-8ed1bf72c921 | ext-net      | c5d191a6-ad17-4143-bbdb-49a91933232d 10.207.225.0/24 |
| 919b327a-2bcb-44cc-98c3-96cd374e475b | privebosh    | 94b2f854-61ca-4fb8-b534-5de5dd301035 192.168.1.0/24  |
| bc4710be-4cc7-4e5e-ac8e-e4067b698ee1 | internal-net | 4634f048-7413-4b1e-ae84-3e98c4bef0f0 10.0.1.0/24     |
| fcd63e36-b152-43d7-acf5-0cb84a60764c | vlan116      | 43b81cd0-ea22-483a-b1ee-1117e7ebb483 10.207.224.0/24 |
+--------------------------------------+--------------+------------------------------------------------------+
```

**Comment by jtopjian** [comment]
Yes, but can you try running the nova command? Nova has internal support for the Neutron API, which Terraform uses in the "instance" resource. Running that command and verifying the success helps with troubleshooting Terraform.

**Comment by sebastien-prudhomme** [comment]
The nova net-list (or tenant-network-list) command returns a 404:

```
ERROR (NotFound): Not found (HTTP 404) (Request-ID: req-3550a143-b10c-48cd-bdd5-782445d35cb1)
```

**Comment by jtopjian** [comment]
Perfect - thanks!

To resolve this issue, specify both the `name` and `uuid` in the network block. Things should start working after that  😄

**Comment by sebastien-prudhomme** [comment]
I know that it works with `uuid` (i don't even have to add `name`). But what i would like is not to use uuid at all.

I'm perplex because as i've said in the comment part of this issue, i see nothing inthe source code that try to resolv the network uuid by using the network name.

But i'm neither a Go nor an OpenStack developper, so...

**Comment by jtopjian** [comment]
I agree, but it looks like your cloud is disabling the Nova `os-tenant-networks` API. See #5293 for more information.

Even though `os-tenant-networks` is a Nova API, it has direct integration with Neutron and is what allows the _instances_ to see both the names and uuids of the networks they are launched on. Without it, it's almost impossible (or as of yet unsolved) for an instance to be able to query itself and resolve names to uuids. That's why you have to specify both.

**Comment by sebastien-prudhomme** [comment]
Thanks for the other issue reference.

HP OpenStack there too.

I close this issue as it is a duplicate of the other.
