### ISSUE TITLE
aws route table and route entries 

### ISSUE THREAD

**Issue by evilezh** [hashicorp/terraform#6611]
Simple scenario:
in module-1 create route table and in module-2 add route table entries (for route-table defined in module 1).
run1-> create all
run2-> remove new entries from route table
run3-> add new entries to route table
run4->run2
run5->run3
run6->run2
.......
As route-table-id is passed as variable to module-2, i guess it is not easy to detect relationships and that needs special processing in mind.

Maybe for objects, which might include other objects (e.g. route-table and route-table-entry), it is possible to  evaluate them at the end.
E.g. build route-table object in memory .... add new entries as required .. and at the end of evaluating, we would get real look of object.
new route table ->
id, [] routes
....
new route for table id=x
add new route where id=x
And when run finishes .. then compare object we got with what we have.

**Comment by paulcollinsiii** [comment]
I just ran into this exact issue as well. 
Module 1 handles creating a VPC for me
Module 2 is adding a peering connection and adding the routing for that peering

**Comment by tomelliff** [comment]
It's hard to tell exactly here without seeing any Terraform code but I think this might be a case of using both an `aws_route_table` resource with routes defined and `aws_route` resources.

The [`aws_route_table` resource docs](https://www.terraform.io/docs/providers/aws/r/route_table.html) and [`aws_route` resource docs](https://www.terraform.io/docs/providers/aws/r/route.html) explain how these conflict and if you want to add routes separately you should not define any routes in the `aws_route_table` resource and instead define them all via the `aws_route` resource instead.
