### ISSUE TITLE
aws_api_gateway_deployment doesn't support stage configuration

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#6612]
Terraform v0.6.16

Beyond stage variables, `aws_api_gateway_deployment` doesn't provide a way to configure other settings available in the console, such as "Cache Settings", "CloudWatch Settings", and "Default Method Throttling".  In order to enable logging, I have to manually make changes in the console.

**Comment by aadamovich** [comment]
+1

**Comment by jantman** [comment]
I opened #7754 for this before I found this issue. It has the specifics of the implementation needed; the gist is that the API Gateway API doesn't expose those settings ("methodSettings") on create; you have to run a subsequent update operation on the created deployment to set them. AWS Support has confirmed this.

**Comment by gsfjohnson** [comment]
@jantman:  It appears you have coded the necessary adjustments.  What about submitting this as a PR?

**Comment by jantman** [comment]
@gsfjohnson sorry for any confusion... I haven't coded the necessary adjustments.

The commits and issues above that mention this are on my webhook2lambda2sqs project, which is a Python wrapper around Terraform (well, purpose-specific with generated configs). The "fixes" that I did were, after the Terraform run (executed by Python) finishes, I go back in with the Python ``boto`` aws client library and issue the API calls to modify the methodSettings on the stage that TF created.

No Go involved, sorry...

**Comment by rochdev** [comment]
+1

**Comment by sebolabs** [comment]
+1

**Comment by gliptak** [comment]
Would some of these be configured using ```aws_api_gateway_stage```?
https://github.com/hashicorp/terraform/issues/6972

**Comment by philltomlinson** [comment]
+1

**Comment by gpetras** [comment]
+1

**Comment by JJK801** [comment]
+1

**Comment by cjmurphy42** [comment]
+1

**Comment by kevinburke** [comment]
hi folks - I also want this feature but I'm not sure the additional +1's are helping anything, and are probably annoying the project's maintainers.

**Comment by radeksimko** [comment]
Hi folks,
we do appreciate the +1's if these don't generate notifications. 😅 

Therefore it's more helpful for everyone to use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) as we can then sort issues by the number of 👍  and eventually decide based on that:
https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Aprovider%2Faws

The 👍  _reactions_ do count and we're more than happy for people to use those and prefer over "+1" comments for the mentioned reasons.

Thanks.

**Comment by himanso** [comment]
Hi,

Is stages creation in api gateway implemented in terraform? If yes, in which version it is available?

Thanks
Himanshu

**Comment by radeksimko** [comment]
Just to give you a quick update with some good news:
`aws_api_gateway_stage` was just merged in #13540 and #13542 with `aws_api_gateway_method_settings` adding the ability to control the mentioned things (CW metrics, logging, throttling etc.) is to be merged soon.

**Comment by radeksimko** [comment]
Both mentioned resources will be shipped in `0.9.3` which is coming out _very soon_.

**Comment by gokuatkai** [comment]
pardon me It's been a long time but, I think this issue was no solved.
The PRs describe and solve **method settings**, and if I may this issue was about **stage settings** that can be then inherited in the methods.
Should I open a new issue?
