### ISSUE TITLE
Default values for list variables

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#6623]
I've just built Terraform from the master branch in order to play with list variables. I've noticed that default values for list variables don't seem to work as expected. I have a module containing a variable declaration as follows:

```
variable "security_groups" {
  type        = "list"
  default     = []
}
```

When running `terraform get` to pull in my module, I get the following error:

```
Error loading Terraform: Error downloading modules: module REDACTED: Error loading .terraform/modules/1e96f088e0095afffbc6ae5c0f18655f/variables.tf: 'security_groups' has a default value which is not of type 'list'
```

Am I missing something, or is this a bug?

**Comment by mitchellh** [comment]
This is fixed, and has been for awhile we just forgot to close this issue!
