### ISSUE TITLE
Terraform fails to identify missing sns subscriptions

### ISSUE THREAD

**Issue by MartinMeinhold** [hashicorp/terraform#6625]
See #4888 for the original case which only addressed the `aws_sns_topic` resources but not the `aws_sns_topic_subscription` one. I can see the related PR  #4891 updated `aws_sns_topic` but didn't touch the subscriptions.

### Terraform Version

```
Terraform v0.6.16
```

### Affected Resources
- aws_sns_topic_subscription

### Terraform Configuration Files
```hcl
resource "aws_sns_topic" "testme" {
    name     = "testme"
    provider = "aws.us_east_1"
}

resource "aws_sns_topic_subscription" "testme" {
    topic_arn = "${aws_sns_topic.testme.arn}"
    protocol  = "lambda"
    endpoint  = "${aws_lambda_function.somefunction.arn}"
    provider  = "aws.us_east_1"
}
```

### Expected Behavior
Terraform would translate the `NotFound` response code to a missing resource and try to create it.

### Actual Behavior
Terraform bails out in planning mode with an unexpected error.

### Steps to Reproduce
1. Create a configuration with a `aws_sns_topic` and a `aws_sns_topic_subscription` and create an execution plan
2. Apply the execution plan; terraform will create the sns topic and the subscription
3. Delete subscription manually (e.g. via the Amazon Console or via the CLI)
4. Create a new execution plan; terraform should discover the previously created subscription has been deleted ...

... but instead it bails out with

```
* aws_sns_topic_subscription.testme: NotFound: Subscription does not exist
	status code: 404, request id: a22e7ed7-3630-5a8a-b767-317ac1440e24
```

### References
- #4888

**Comment by stack72** [comment]
Hi @MartinMeinhold 

apologies for not picking this up in the first `fix` - I have just opened another PR which fixes the issue in the topic subscription this time

Paul

**Comment by MartinMeinhold** [comment]
No worries, all good. Thanks for the quick response.
