### ISSUE TITLE
Feature: Ability to enable Amazon S3 bucket acceleration

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#6626]
AWS [announced](https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/) new feature called **Amazon S3 Transfer Acceleration** which you can use to accelerate transfer speed for cross-country transfer of large objects.

You can enable this feature by using [PUT Bucket accelerate](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTaccelerate.html) endpoint via AWS API. 

We're performing this action manually after our initial `terraform apply`, but it would be really handy if Terraform supports enabling bucket for acceleration.

You can read more about this feature on Amazon S3 Documentation: [Amazon S3 Transfer Acceleration](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html)

**Comment by stack72** [comment]
Hi @premist 

PR has just been opened to add this feature :)

Paul

**Comment by premist** [comment]
Hi @stack72, that was fast! Awesome :)

**Comment by catsby** [comment]
This was added in #6628
