### ISSUE TITLE
File Provisioner on Cygwin cannot find file

### ISSUE THREAD

**Issue by rvodden** [hashicorp/terraform#6627]
I'm running Terraform v0.6.15 on cygwin built with setup version 2.847 (both 64bit on windows 8.1). I only know that this affects a file provisioner on a google_compute_instance, but I imagine it affects other resources too.

### Terraform Config
bastion.tf:
```hcl
resource "google_compute_address" "bastion-address" {
    count = "1"
    name = "${var.prefix}-bastion-address-${count.index}"

}

resource "google_compute_instance" "bastion" {
  count        = "1"
  name         = "${var.prefix}-bastion-${count.index}"
  zone         = "europe-west1-b"
  machine_type = "n1-standard-1"
  tags             = ["bastion"]

  disk {
    image = "${var.image_type}"
  }

  network_interface {
    network = "default"
    access_config {
      nat_ip = "${element(google_compute_address.bastion-address.*.address, count.index)}"
    }
  }

        # copy the generated public key onto the server
        provisioner "file" {
                source = "${var.PROJECT_ROOT}/audry.key.pub"
                destination = "/tmp/audry.key.pub"

                connection {
                    type  = "ssh"
                        user = "packer"
                        password = "packer"
                }
        }
}
```
environment.tf:
```
variable "prefix"       { default = "richard" }
variable "AUDRY_PREFIX" { default = "richard" }
variable "AUDRY_USER"   { default = "LONRV1" }
variable "AUDRY_HOME"   { default = "C:\\Users\\USER\\Code\\Audry\\terraform\\terraform" }
```
vars.tf:
```
variable "image_type"   { default = "centos-72-hardened-21" }
```
google.tf:
```
provider "google" {
  credentials = "${file("account.json")}"
  project     = "audry-test-666"
  region      = "europe-west1"
}
```
### Debug Output
https://gist.github.com/rvodden/ab3baa3ab370a84f4c099698156dec63

### Expected Behavior
I'd expect the provisioner to succeed
### Actual Behavior
It failed saying that it cannot find the file. Specifically:
```
Error applying plan:

1 error(s) occurred:

* GetFileAttributesEx /cygdrive/c/Users/USER/Code/Audry/audry.key.pub: The system cannot find the path specified.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```
### Important Factoids
I've checked CRLF vs LF line-endings (I've forced everything to be CRLF; then forced everything LF - the results are the same).
The `AUDRY_HOME` environment variable is set to `/cygdrive/c/Users/USER/Code` in the cygwin environment. When it is set to `c:/Users/USER/Code`

**Comment by jen20** [comment]
Hi @rvodden! Unfortunately we rely on the Go runtime mechanism (runtime.GOOS) for detecting which OS we are running on, and that appears to be detecting Cygwin environments as Windows. My suspicion is that this is statically compiled into the binary rather than runtime detection. At this stage I don't think we want to add code to Terraform to special case Cygwin - it seems like something which should be addressed in the Go runtime. You can, however, run from a normal Windows environment as a workaround.
