### ISSUE TITLE
lookup function in connection block not working

### ISSUE THREAD

**Issue by pradeepbhadani** [hashicorp/terraform#6633]
Hi,

I want to use private_IP or Public_IP of AWS instance based on my workstation location.
So i was writing block like below : 

```
  connection {
    variable "connection_type" {
      type = "map"
      default = {
        private = "${self.private_ip}"
        public = "${self.public_ip}"
      }
    }

    host = "${lookup(connection_type, "private")}"
    type = "ssh"
    user = "${var.node_user}"
    agent = false
    key_file = "${var.key_name}"
  }
```

But "host" always get public IP.

Any idea on how to make it dynamic and supply IP to host variable based on some flags?

Above block always pick pblic IP even if i specify "private"  for lookup funciton.

**Comment by mitchellh** [comment]
This works for me. Variable declarations must be declared at the top level. A bug to validate this is at #6582
