### ISSUE TITLE
vsphere_virtual_machine and vsphere_folder race condition on destroy

### ISSUE THREAD

**Issue by sprokopiak** [hashicorp/terraform#6637]
I'm encountering a race condition when using both vsphere_folder and vsphere_virtual_machine. Around ~75% of the time I try to destroy my VM in a created folder, Terraform tries to destroy the folder before the VM, which causes an error to be thrown since the folder is not empty.

From what I've seen, the destroy virtual machine resource always runs before the destroy folder resource can error, resulting in a vSphere environment where my VM was deleted, but the folder remains. This is easily cleaned up by running `terraform destroy -force` again to destroy the folder.
### Terraform Version

v0.6.16
### Affected Resource(s)

Please list the resources as a list, for example:
- vsphere_virtual_machine
- vsphere_folder
### Terraform Configuration Files

``` hcl
# Create a folder
resource "vsphere_folder" "web" {
    path = "SCP Testing/terraform"
    datacenter = "DEVESX"
}

# Create a virtual machine within the folder
resource "vsphere_virtual_machine" "web" {
    name = "terraform-web"
    folder = "${vsphere_folder.web.path}"
    datacenter = "DEVESX"
    vcpu = 4
    memory = 8192
    cluster = "General"

    network_interface {
        label = "dvPortGroup_8HourLease"
    }

    disk {
        template = "templates/CP - packer-virtualbox-iso-1462307446"
        datastore = "/DEVESX/datastore/VM Datastores/Nobackup"
    }
}
```
### Debug Output

[Output](https://gist.github.com/sprokopiak/889d7d9f12a16b4da090ff51b43d4621)
### Panic Output

N/A
### Expected Behavior

The virtual machine should have been destroyed, and then the folder should have been deleted.
### Actual Behavior

The folder tried to get deleted before deleting the virtual machine. The folder failed to be deleted because the virtual machine was still inside the folder. The virtual machine ended up being deleted on vSphere, but the folder remained.
### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy -force`
### Important Factoids

vSphere 5.5
### References

N/A

**Comment by chrislovecnm** [comment]
@matt-deboer you added this functionality.  Any ideas?

**Comment by matt-deboer** [comment]
Hi, sorry for the long delay; have been focused on some other stuff for a while and haven't gotten back to TF until just recently.

I can confirm this behavior; initial guess is that destroy is an async operation whose completion isn't being properly awaited.

Taking a look...

**Comment by matt-deboer** [comment]
Actually, on further inspection, it looks like this might be a reappearance of #120...

I can see that the virtual machine delete is a task that is being awaited; anyway, it's irrelevant based on the order of terraform's actions in the log.

@sprokopiak Your log says that TF actually tried to delete the folder before it tried to delete the vm, and unless I'm mistaken, the order of those operations is determined by TF core--based on the dependency graph, not by the individual provider.

When you run `terraform graph`, do you see a dependency pointing from the vm to the folder?

**Comment by sprokopiak** [comment]
@matt-deboer Sorry, but today was my last day at my current company, where I had access to ESX. I am unable to verify the output from `terraform graph`.
