### ISSUE TITLE
terraform apply crash using triton plugin (v0.6.16)

### ISSUE THREAD

**Issue by kkaig** [hashicorp/terraform#6640]
Hi there,
I know nothing about terraform, as this is the first time I've used it and it crashed, so I can't provide much more info except what I did.

Reproducing:
Version: Terraform v0.6.16
git clone https://github.com/ContainerSolutions/dcos-in-triton.git
terraform apply # you'll need a working private triton setup for this
[commandline.stderr.txt](https://github.com/hashicorp/terraform/files/261776/commandline.stderr.txt)
[commandline.stdout.txt](https://github.com/hashicorp/terraform/files/261777/commandline.stdout.txt)

[crash.txt](https://github.com/hashicorp/terraform/files/261760/crash.txt)

**Comment by catsby** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/7208, thanks!
