### ISSUE TITLE
Feature: Add support to create AWS WAF Web ACLs and Rules

### ISSUE THREAD

**Issue by brian98point6** [hashicorp/terraform#6646]
Hi,

My team would like to use Terraform to create and manage [AWS WAF](http://aws.amazon.com/documentation/waf/). Currently, the only mention of WAF in Terraform config is in the web_acl_id config for CloudFront.

In the near future, we are specifically looking to create web ACLs and rules in WAF. 

AWS CLI reference: http://docs.aws.amazon.com/cli/latest/reference/waf/index.html?highlight=waf

Thanks!
Brian

**Comment by kaaloo** [comment]
This would be awesome!  I'm currently using a cloudformation resource but it's slow as a dog...

**Comment by ziggythehamster** [comment]
Here's the list of resources that would need to be created:

* aws_waf_byte_match_set
* aws_waf_ip_set
* aws_waf_rule
* aws_waf_size_constraint_set
* aws_waf_sql_injection_match_set (could also be aws_waf_sqli_match_set)
* aws_waf_web_acl (which plugs into the CloudFront distribution)
* aws_waf_xss_match_set

**Comment by nicwise** [comment]
(ok, so I'm new to this)

I'd love to see this too - mostly as I'm doing a load of work/research around WAF and our primary tool is Terraform :)

Outside of learning Go and hacking on Terraform, is there any way I can get in and help move it along?

**Comment by grebois** [comment]
+1

**Comment by cultavix** [comment]
+1

**Comment by stack72** [comment]
Hi 

the first 3 WAF resources have just been merged to Terraform thanks to @optimisticanshul :)

Paul

**Comment by stack72** [comment]
Closing this as the last of the resources has just been merged :)

all 7 are now part of the 0.7.8 release
