### ISSUE TITLE
In aws_opsworks_application -> auto_bundle_on_deploy keeps appearing as changed in terraform plan

### ISSUE THREAD

**Issue by iroller** [hashicorp/terraform#6654]
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_opsworks_application

### Terraform Configuration Files
```hcl
resource "aws_opsworks_application" "app" {
  type        = "rails"

  auto_bundle_on_deploy = true
```

Even though plan was already applied auto_bundle_on_deploy is being displayed as changed on each plan:
```
~ aws_opsworks_application.app
    auto_bundle_on_deploy: "true" => "1"
```

**Comment by apparentlymart** [comment]
Hi @iroller! Thanks for this report.

Could you give this a try on version 0.6.16? That release contains the change from #6499 which I think will fix this issue.

**Comment by stack72** [comment]
Hi @iroller 

Can you tell me if this is still an issue for you?

Paul

**Comment by iroller** [comment]
Hi,

Not an issue anymore in 0.6.16. Thanks!
