### ISSUE TITLE
concat() function does not support lists for inputs as documented

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform#6657]
Hi there,

### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- core

### Terraform Configuration Files
```hcl
resource "tls_private_key" "api-key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "api-server-key-csr" {
  key_algorithm = "RSA"
  private_key_pem = "${tls_private_key.api-key.private_key_pem}"
  subject {
    common_name = "api"
  }
  ip_addresses = ["${concat(["1.2.3.4"],["5.6.7.8]")}"]
}
```

### Expected Behavior
According to [interpolation syntax docs](https://www.terraform.io/docs/configuration/interpolation.html#concat_list1_list2_) the concat() function should take **two lists** as arguments and join them and **return the resulting list**.

### Actual Behavior
However, I noticed that in practice this is not the case, and instead the concat() function **only works on string** typed inputs, effectively concatenating them, as it's name implies.
I'm not sure if the documentation is misinforming and joining lists was never the intended feature or if the feature should actually work but it doesn't.

### Steps to Reproduce
Using the above configuration snipped, do a plan:
1. `terraform plan`

And you should see an error like:

`Error loading config: Error loading /Users/alex/workspace/terraform-test/tls.tf: Error reading config for tls_cert_request[api-server-key-csr]: parse error: syntax error
`

Now, switch the arguments to concat() to plain strings, like:
```
ip_addresses = ["${concat("1.2.3.4","5.6.7.8")}"]
```

And the `terraform plan` should go through and produce:

```
+ tls_cert_request.api-server-key-csr
    cert_request_pem:      "" => "<computed>"
    ip_addresses.#:        "" => "1"
    ip_addresses.0:        "" => "1.2.3.45.6.7.8"
    key_algorithm:         "" => "RSA"
    private_key_pem:       "" => "37935e2f61ac06c349d43e6ed5512a640cd6c9f8"
    subject.#:             "" => "1"
    subject.0.common_name: "" => "api"

+ tls_private_key.api-key
    algorithm:          "" => "RSA"
    ecdsa_curve:        "" => "P224"
    private_key_pem:    "" => "<computed>"
    public_key_openssh: "" => "<computed>"
    public_key_pem:     "" => "<computed>"
    rsa_bits:           "" => "2048"
```

Notice how the `ip_addresses.0:` value is the result of joining the two input strings.

**Comment by eedwardsdisco** [comment]
Looks like more of a syntax issue, I don't think you can declare lists with the example you provided:

```
ip_addresses = ["${concat(["1.2.3.4"],["5.6.7.8]")}"]
```

Once you're inside the outer `[]`'s, I don't believe terraform supports declaring an 'inner list'.

**Comment by kwilczynski** [comment]
I have a similar issue, attempt to do something this:

Given that "a" and "b" are lists.

```
module "test" {
  source = "./test"
  variable = "${concat(split(",", var.a), split(",", var.b))}"
}
```

Results in some empty fields being added, thus when passing "${var.variable}" to something that expects a list of IDs or CIDRs, it would fail. Adding `compact` does not seem to fix this (which is also odd).

**Comment by jen20** [comment]
Hi @alexsomesan! As @eedwardsdisco points out the issue is that there is no syntax for list literals in HIL. We may change this in 0.7 to add support, but for now you need to use concat, or a resource field which results in a list as input to `concat`. Please feel free to reopen this if you have further questions.

**Comment by Fodoj** [comment]
Was it implemented? @jen20

**Comment by hardboiled** [comment]
@jen20 @alexsomesan Can't you just do this?
`["${concat(list("1.2.3.4"), list("5.6.7.8"))}"]`

**Comment by spommerening** [comment]
Maybe it's a bit late but I had a similar problem (which was my own mistake..) and so I came here and saw this... tested it like:

```
output "prod_instance_ids" {
  value = "${concat(aws_instance.prod01.*.id,aws_instance.prod02.*.id)}"
}
```

Worked.

**Comment by John1Q84** [comment]
concat with inner lists does not work, I just use join with empty delimter

this is what I want to do
`concat(list(var.string0), list(var.string1))`
it does not work, 

I replace it like this
`join("",` list(var.string1, var,string2)`

**Comment by sssd-dev** [comment]
I was looking for the solution to concat two lists and found the solution using in below format - 

locals {
  a_identifiers = [
    "arn:aws:iam::hhhhjjjjj:role/account_dev",
    "arn:aws:iam::hhhhjjjjj:role/account_stage",
  ]
}
locals {
  b_identifiers = [
    "arn:aws:iam::hhhhjjjjj:role/account_qa",
    "arn:aws:iam::hhhhjjjjj:role/account_prod",
  ]
}
locals {
  combo_identifiers = "${concat(a_identifiers,b_identifiers)}"
}
## this is how I can use it after this - 
data "aws_iam_policy_document" "access_policy" {
  statement {
    effect = "Allow"

    principals {
      type = "AWS"

      identifiers = ["${local.combined_identifiers}"]
    }

    actions = [
      "ec2:*",
    ]

    resources = [
      "*",
    ]
  }
}

Hope someone will find it useful

**Comment by kivagant-ba** [comment]
`list()` can't be used with `concat()`. `[]` also can't be used with `concat()`. Strings can't be used with `concat()`. Nothing can be used with `concat()`. 

```
resource "aws_route" "abc" {
  # Add 1 for the "public" route table
  count = "${length(module.edf.zones) + 1}"

  route_table_id = "${element(
    concat(
      module.edf.private_route_table_ids,
      list(module.edf.public_route_table_id)
    ),
    count.index
  )}"

  destination_cidr_block    = "${var.vpc_cidr}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peer.id}"
}
```


```
* aws_route.abc[0]: element: element() may only be used with flat lists, this list contains elements of type list in:

${element(
    list(
      module.edf.private_route_table_ids,
      list(module.edf.public_route_table_id)
    ),
    count.index
  )}
```
