### ISSUE TITLE
terraform 0.6.16 - Vmware Vsphere Provider - domain saved as "vsphere.local" in some network configurations

### ISSUE THREAD

**Issue by totojack** [hashicorp/terraform#6658]
### Terraform Version

terraform 0.6.16
### Affected Resource(s)
- vsphere_virtual_machine
### Terraform Configuration Files

```
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_cluster" {}
variable "vsphere_datacenter" {}
variable "vsphere_domain" {}
variable "vsphere_dns" {}
variable "vsphere_timezone" {}
provider "vsphere" {
user = "${var.vsphere_user}"
password = "${var.vsphere_password}"
vsphere_server = "${var.vsphere_server}"
allow_unverified_ssl = true
}
resource "vsphere_virtual_machine" "web" {
name = "terraform-web"
folder = "${vsphere_folder.testfolder.path}"
vcpu = 2
memory = 2048
datacenter = "${var.vsphere_datacenter}"
cluster = "${var.vsphere_cluster}"
domain = "my.custom.domain.com"
dns_servers = ["${var.vsphere_dns}"]
#resource_pool = ""
time_zone = "${var.vsphere_timezone}"

network_interface {
label = "virtualwire_Template"
ipv4_address = "172.16.1.19"
ipv4_prefix_length = "28"
ipv4_gateway = "172.16.1.17"
}

disk {
template = "TEMPLATE/Centos7_tmpl_20160422_01"
datastore = "VPLEX-SAS"
}
disk {
size = "20"
datastore = "VPLEX-SAS"
}
disk {
size = "10"
datastore = "VPLEX-SAS"
}
}
```
### Debug Output

https://gist.github.com/totojack/4db892bf6d9b03b3b982401fedd8c2f6
### Expected Behavior

domain value saved in files:
- /etc/resolv.conf , with line "search my.custom.domain.com"
- /etc/sysconfig/network-scripts/ifcfg-eth0 , with line "domain my.custom.domain.com"
### Actual Behavior

domain value saved as default value 'vsphere.local' in files:
- /etc/resolv.conf, with line "search vsphere.local"
- /etc/sysconfig/network-scripts/ifcfg-eth0 , with line "domain vsphere.local"
### Steps to Reproduce

add gateway to configuration
terraform apply
### Important Factoids

I'm testing with a Centos 7 VM on vsphere 6.

**Comment by chrislovecnm** [comment]
Dumb question, but do you have open vm tools installed?  And if so which version?

Thanks

@stack72 @jen20 @phinze can we get a vsphere tag on this?

**Comment by totojack** [comment]
Hi Chris.

This is the version of vm tools installed and running: 

[root@terraform-web ~]# yum info open-vm-tools.x86_64
Installed Packages
Name        : open-vm-tools
Arch        : x86_64
Version     : 9.10.2
Release     : 4.el7
Size        : 1.4 M
Repo        : installed
From repo   : base
Summary     : Open Virtual Machine Tools for virtual machines hosted on VMware
URL         : http://open-vm-tools.sourceforge.net/
License     : GPLv2
Description : The open-vm-tools project is an open source implementation of VMware Tools. It
            : is a suite of open source virtualization utilities and drivers to improve the
            : functionality, user experience and administration of VMware virtual machines.
            : This package contains only the core user-space programs and libraries of
            : open-vm-tools.

[root@terraform-web ~]# vmware-toolbox-cmd -v
9.10.2.48224 (build-2822639)

[root@terraform-web ~]# ps ax | grep tools
   980 ?        Ss     6:12 /usr/bin/vmtoolsd


Thanks
Luca
