### ISSUE TITLE
Error hooking instances to AWS ELB upon `terraform apply`

### ISSUE THREAD

**Issue by n8gard** [hashicorp/terraform#6668]
I've been getting this error when running `terraform apply` that recycles EC2 instances connected to an ELB. The instances spinup fine but the error (below) seems to happen upon trying to configure the ELB to attach the new instances. If I ignore this error and run another `apply` it works fine. This is happening fairly consistently.

Error output:
-----------------
Error applying plan:

1 error(s) occurred:

* aws_elb.web: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.15
    Resource ID: aws_elb.web
    Mismatch reason: attribute mismatch: instances.205313744
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.205313744":*terraform.ResourceAttrDiff{Old:"", New:"${aws_instance.web-charlie.*.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2212443783":*terraform.ResourceAttrDiff{Old:"", New:"i-eebd8f73", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.588011441":*terraform.ResourceAttrDiff{Old:"", New:"${aws_instance.web-bravo.*.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1381180199":*terraform.ResourceAttrDiff{Old:"i-65b592e2", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.173722440":*terraform.ResourceAttrDiff{Old:"i-a6c9183c", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.562814360":*terraform.ResourceAttrDiff{Old:"i-be201123", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"instances.1381180199":*terraform.ResourceAttrDiff{Old:"i-65b592e2", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.173722440":*terraform.ResourceAttrDiff{Old:"i-a6c9183c", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.562814360":*terraform.ResourceAttrDiff{Old:"i-be201123", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.1819176040":*terraform.ResourceAttrDiff{Old:"", New:"i-5f4291c5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.2212443783":*terraform.ResourceAttrDiff{Old:"", New:"i-eebd8f73", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "instances.4229235863":*terraform.ResourceAttrDiff{Old:"", New:"i-804c6f07", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by catsby** [comment]
Hey @n8gard – do you have an example config that I can reproduce this with? If you do please be sure to omit any secrets, thanks!

**Comment by n8gard** [comment]
Sadly, I dont think so. I wouldnt know what to copy-n-paste out of our nascent, production project. It's pretty big and I couldn't share it in its entirety anyways... :( What else can I do to be helpful?

**Comment by n8gard** [comment]
Closing as this issue is the same as: https://github.com/hashicorp/terraform/issues/7210. I'll pile on to that one.
