### ISSUE TITLE
Add support for Elasticsearch destination to firehose delivery streams

### ISSUE THREAD

**Issue by epetrovich** [hashicorp/terraform#6680]
Amazon enabled that feature on Apr 19 2016

https://aws.amazon.com/about-aws/whats-new/2016/04/amazon-kinesis-firehose-adds-amazon-elasticsearch-data-ingestion-and-enhanced-monitoring-features/

**Comment by catsby** [comment]
Thanks for the request! 
For anyone taking up the charge, here's the documentation:

- Developer guide: http://docs.aws.amazon.com/firehose/latest/dev/what-is-this-service.html
- API Guilde: http://docs.aws.amazon.com/firehose/latest/APIReference/Welcome.html

**Comment by stack72** [comment]
This work is now going to be possible thanks to the work by @catsby in this PR https://github.com/hashicorp/terraform/pull/7375

**Comment by catsby** [comment]
Well, mostly @dminnear 😉

**Comment by iceycake** [comment]
The code in #7839 should be ready for PR.

**Comment by stack72** [comment]
Closed via #7839
