### ISSUE TITLE
"no error reported by variable"

### ISSUE THREAD

**Issue by jtopper** [hashicorp/terraform#6685]
### Terraform Version

`Terraform v0.7.0-dev (fce7aa483d9b1a810629eec74bb859fe608c4f97)`

### Affected Resource(s)

Looks to be terraform core, but could be `template_file` resources.

### Terraform Configuration Files
```hcl
# test.tf
module "test_module" {
    source = "test_mod"
    policy = "${template_file.repo_bucket_iam_policy.rendered}"
}

resource "template_file" "repo_bucket_iam_policy" {
    template = ""
}
```

```hcl
# test_mod/mod.tf
variable "policy" {
    description = "Bucket policy"
}
```

### Debug Output
https://gist.github.com/jtopper/be687bc38e36ae5709fd2237b1026ff4

### Panic Output
None

### Expected Behavior
This plan should have compiled correctly.

### Actual Behavior
```
Error configuring: 1 error(s) occurred:

* no error reported by variable "repo_bucket_iam_policy" is nil
```

### Steps to Reproduce
1. `terraform plan`

### References
Looks to be related by @jen20's changes in #6596

**Comment by jen20** [comment]
Thanks for reporting this @jtopper - I'll investigate tomorrow.

**Comment by jtopper** [comment]
This looks to be resolved at the current HEAD of master.  Closing.

**Comment by dmikalova** [comment]
I'm getting this issue in 0.7.0. I did a destroy, it failed due to a race condition, and now I can't delete the rest of my infra because it gives this error.

**Comment by dmikalova** [comment]
Still getting this in terraform 0.7.1.

**Comment by jdblack** [comment]
Still present as of 0.7.2

**Comment by mattsoftware** [comment]
I am getting this error in 0.7.4
