### ISSUE TITLE
creating azurerm storage account fails (from timeout) first time

### ISSUE THREAD

**Issue by MattFenner** [hashicorp/terraform#6702]
when doing a terraform apply with a azurerm_storage_account

it will spend like 10 minutes trying to create it and then fail. but when you runn apply again it will work almost immediately.

this should be a fairly quick operation.

**Comment by jen20** [comment]
Hi @MattFenner - is this something that is repeatable in your Azure account? If so would you be prepared to undertake some additional debugging research for us? I have not seen this in any of our test accounts, though the time taken does vary from seconds to multiple minutes.

**Comment by MattFenner** [comment]
it is consistently about 15min for me. assuming it is pretty easy to do i can get some debug info for you

**Comment by ManushB** [comment]
Hey, @MattFenner , try changing the name of the storage account every time. There is an issue with azure. It holds the storage account name even after it is destroyed for couple of hours.

**Comment by stack72** [comment]
Hi @MattFenner 

The information that @ManushB gave is indeed correct. StorageAccount names are unique across the entire of AzureRM so you will not be able to destroy and recreate in quick succession

Paul

**Comment by Preskton** [comment]
+1 to above.  I've found that after destroying a storage account, you usually need to wait about 15 minutes for that name to be reusable.

**Comment by stack72** [comment]
Hi folks

We believe we have made this experience better in #8215 where we are much better about interacting with long running processes

I am going to close this for now - if this happens again then please let us know

Paul

**Comment by vinayvenkat** [comment]
I too see this on a regular basis. I don't see any notifications other than that terraform keeps tracking the progress.

**Comment by bernadinm** [comment]
This issue still exist. I have reproduced this on terraform 0.10.2.
