### ISSUE TITLE
error messages for azurerm not very helpful

### ISSUE THREAD

**Issue by MattFenner** [hashicorp/terraform#6706]
Hi,

I understand the azurerm plugin is quite new. But i have found it very hard to work with due to the error messages basically being unhelpful.

Generally they will just contain the HTTP error code e.g. 403 and the url which can tell you the resource it is trying to apply. otherwise you are left to figure out the rest by yourself.

For this reason i have switched back to using the old azure service manager plugin until this experience is better.

thanks.

**Comment by stack72** [comment]
Hi @MattFenner 

Thanks for reporting this. This is something we are actively trying to fix already - we need to make a breaking change when upgrading the SDK version. It is already being tracked https://github.com/hashicorp/terraform/issues/6526 as the Update of SDK issue

Keep an eye on that issue and we should have it in place for Terraform 0.7

Thanks

Paul
