### ISSUE TITLE
invalid memory address or nil pointer reference

### ISSUE THREAD

**Issue by leemhenson** [hashicorp/terraform#6707]
### Terraform Version
0.6.16  6e586c89394f5474b6c5f3217a4a75ce80c3fd6c

### Affected Resource(s)
aws_elastic_beanstalk_environment seems to be the one where it crashed

### Panic Output
https://gist.github.com/leemhenson/068a12fce26b514c40d029f4b6f28daa

**Comment by stack72** [comment]
HI @leemhenson 

Apologies for this happening. In order to try and help us identify the issue, please can you post the config that is causing the error (minus secrets)

Thanks

Paul

**Comment by leemhenson** [comment]
Hi. This isn't a production aws account so nothing in here is particularly secret, but I've used the hashicorp public key to encrypt it anyway:

http://s3hub-a093d33b9dd701d3b44148d81ad43449e0e46d79c7f6adb937c44339b.s3.amazonaws.com/terraform.tgz.gpg

Let me know if I've done it wrong and you can't read it.

**Comment by leemhenson** [comment]
Ah, I'm 80% sure this is due to the following error coming out in the eb logs:

> Creating load balancer failed Reason: Server Certificate not found for the key: arn:aws:iam::[account id]:server-certificate/[cert name]

It seems to crash terraform rather than being a 'graceful' error.

**Comment by leemhenson** [comment]
Yep, fixing the ref to the server certificate has fixed the terraform crash.

**Comment by stack72** [comment]
@leemhenson 

thanks for the info here. I guess we need to get the right code in place for this. I will see if one of the team can decode the package

P.

**Comment by catsby** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/7222 , thanks @dharrisio ! 

Thank you @leemhenson for reporting!
