### ISSUE TITLE
aws subnet VPC forced to change when using "map_public_ip_on_launch" field

### ISSUE THREAD

**Issue by spyrospph** [hashicorp/terraform#671]
Hi,

With the latest edition of the field "map_public_ip_on_launch" in the subnet of the aws VPC we get the below change when terraform planning

~ aws_subnet.some.0
map_public_ip_on_launch: "false" => ""

However when we try to terraform update we get the following error:

Error applying plan:

1 error(s) occurred:

    Resource type 'aws_subnet' doesn't support update

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

The issues is that the state "map_public_ip_on_launch" is false anyway in my VPC so update should not be required.

I am using latest terraform compiled on linux

-S.

**Comment by brycekahle** [comment]
Perhaps this [line](https://github.com/hashicorp/terraform/blob/a3faad4f0db54c60bea5282142b51d0d2e30a706/builtin/providers/aws/resource_aws_subnet.go#L128) is the offender? Shouldn't that be `d.Get("map_public_ip_on_launch")`

**Comment by catsby** [comment]
Hello all – @spyrospph I sent a patch in #1234 that actually reads the `map_public_ip_on_launch` value (thanks @brycekahle :smile:). 

I'm not sure I totally follow the scenario you describe though, so I can't say for sure if that addresses this issue. Can you follow up with me here and let me know?

**Comment by catsby** [comment]
I'm going to close this for now, please re-open if you feel #1234 does not address this.
