### ISSUE TITLE
`data` blocks don't work within the acceptance test harness

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#6713]
The acceptance test harness always expects the diff to be empty after apply, but data sources will *always* generate a diff because they are always eager to refresh themselves when given the opportunity.

This means that right now `data` blocks can't be used in acceptance tests. I missed this initially because in porting `terraform_remote_state` I neglected to update its test to use `data` block instead of a `resource` block.

We need some sort of exception to allow this to work as expected.

**Comment by jen20** [comment]
@apparentlymart we can probably use:

```
	// ExpectNonEmptyPlan can be set to true for specific types of tests that are
	// looking to verify that a diff occurs
	ExpectNonEmptyPlan bool
```

For this? It might be better to create a wrapper that sets this when testing data resources though.

**Comment by apparentlymart** [comment]
@jen20, yeah, I ended up doing this for now in the template PR... but I was thinking that the test harness should just understand that data sources are supposed to generate a diff and not include that, rather than having each individual test have to specify it.

Might not be super-important for now though.
