### ISSUE TITLE
Terraform v0.6.16 dynamically linked

### ISSUE THREAD

**Issue by enieuw** [hashicorp/terraform#6714]
Hi,

I'm having some issues running Terraform v0.6.16 on Alpine Linux. Version 0.6.15 and 0.6.14 run great but for some reason the binary distribution for v0.6.16 seems dynamically linked which is giving me some issues with glibc. On Alpine 3.3.3 I'm getting the following results after installing the binary:
```
/home/user # file /usr/local/bin/terraform
/usr/local/bin/terraform: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
/home/user # /usr/local/bin/terraform
sh: /usr/local/bin/terraform: not found
```

Manually compiling terraform 0.6.16 from the tag in the repo gives me the following result:
```
/home/user # file /usr/local/bin/terraform
terraform: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
/home/user # /usr/local/bin/terraform version
Terraform v0.6.16
```

Was this an intended change? If so I'll need to switch building my containers to building from source

**Comment by mindw** [comment]
This affects the "official" terraform docker images.
possibly caused by mitchellh/gox#49 .

**Comment by jen20** [comment]
We're aware of this issue - it was an unexpected change in default from `gox` during 0.6.16 release window. Terraform 0.6.17 will be statically linked once again as with previous versions. It is scheduled to hit tomorrow or the following day.

**Comment by mindw** [comment]
Just for the record, this issue caused at least a couple of hours of work for me and others. It is a major regression (not a question) and should be communicated as such.

**Comment by ColinHebert** [comment]
@jen20, any idea when 0.6.17 will be released? Or are we going straight to 0.7? In which case what's the ETA?

**Comment by siddharthist** [comment]
This looks like it is still an issue in v0.7.0-rc1! 
From my Dockerfile (alpine):
```
ENV TERRAFORM_VERSION 0.7.0-rc1
RUN curl -sSLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip -d /usr/local/bin /tmp/terraform.zip && \
    rm -f /tmp/terraform.zip
```
Looks like it's still dynamically linked.
```
bash-4.3# ldd /usr/local/bin/terraform 
	/lib64/ld-linux-x86-64.so.2 (0x55c857ed7000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55c857ed7000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55c857ed7000)
```
```
bash-4.3# file /usr/local/bin/terraform 
/usr/local/bin/terraform: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

**Comment by mindw** [comment]
I've investigated this further and can confirm the above change in gox is the cause for this regression.
For statically linked amd64 linux terraform binaries add the following line to scripts/build.sh:
```
export CGO_ENABLED=0
```
And build. pull request shortly.

**Comment by phinze** [comment]
Thanks for the continued investigation on this, everyone! This was a casualty of our evolving release process as we worked on the imminent 0.7 release. We agreed internally to add `CGO_ENABLED=0` to the build script but the actual change never got made! 😬 

Will pull in #7107 which should take care of this in the next RC build. 👍

**Comment by jen20** [comment]
Ah, I think it was made on the maint-0.6 branch and never forward ported. Whoops! Good catch in #7107!
