### ISSUE TITLE
aws_autoscaling_group health_check_type not working

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#6716]
### Terraform Version
0.6.16

### Affected Resource(s)
- aws_autoscaling_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "example" {
    availability_zones =  [ "${split(",", var.vpc_private_subnet_azs)}" ]
    desired_capacity = "1"
    force_delete = false
    health_check_grace_period = 300
    health_check_type = "EC2"
    launch_configuration = "${aws_launch_configuration.example.name}"
    load_balancers = [ "example" ]
    max_size = "1"
    min_size = "1"
    name = "${aws_launch_configuration.example.name}"
    vpc_zone_identifier = [ "${split(",", var.vpc_private_subnets)}" ]
    wait_for_elb_capacity = "1"

    lifecycle { create_before_destroy = true }
}
```

### Debug Output
```
1 error(s) occurred:

* aws_autoscaling_group.example: "example-m5hakrx4f5gdpb4uruoh7goata": Waiting up to 10m0s: Need at least 1 healthy instances in ELB, have 0
```

### Expected Behavior
The health_check_type is set to "EC2" so I would expect it to not be waiting for a healthy instance in the ELB.  The instance is reporting as healthy in our AWS console.  This used to work for us.

### Actual Behavior
The instance is created in the asg and starts reporting as healthy based on EC2 checks.  The ELB health checks are failing, which is expected for us right now based on the ami we are using.  Once we get the instance to pass the ELB health checks we'll be using an ELB health check but for now I just want it to pass based on the EC2 check.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by lukaf** [comment]
Hi @PurrBiscuit ,

ELB check if preformed by terraform because of `wait_for_elb_capacity = "1"` in your configuration.

**Comment by PurrBiscuit** [comment]
ah, you're right.  thanks for pointing that out.
