### ISSUE TITLE
azurerm refresh fails when a storage account is missing

### ISSUE THREAD

**Issue by cchildress** [hashicorp/terraform#6725]
### Description
If a storage account is removed from the Azure web portal terraform fails to handle the missing resource gracefully. This affects refresh, plan, and apply. It looks like terraform is trying to query information about storage containers inside the account before querying the account itself, so it doesn't realize that they will be gone as well.
Not being able to refresh the state files is a bit annoying though. Here are the workarounds I've found so far:
* Go to the Azure portal and recreate enough resources manually to help Terraform find what it expects.
* Just delete all your resource groups and re-deploy everything.
* Edit the state file and remove the resources you think are gone from there.

### Terraform Version
0.6.15

### Affected Resource(s)
* azurerm_storage_container
* azurerm_storage_account

### Terraform Configuration Files
<pre>resource "azurerm_storage_account" "an_storage_std" {
  name = "anstoragestandard"
  resource_group_name = "${azurerm_resource_group.an_prod.name}"
  location = "westeurope"
  account_type = "Standard_LRS"
}
resource "azurerm_storage_container" "an_os_images" {
  name = "an-os-images"
  resource_group_name = "${azurerm_resource_group.an_prod.name}"
  storage_account_name = "${azurerm_storage_account.an_storage_std.name}"
  container_access_type = "private"
}</pre>

### Debug Output
<pre>Error refreshing state: 1 error(s) occurred:
* azurerm_storage_container.an_os_images: Error retrieving keys for storage account "anstoragestandard": autorest:DoErrorUnlessStatusCode 404 POST https://management.azure.com/subscriptions/3581893b-e014-4aab-820e-d84c7d38a77c/resourceGroups/AN_Prod/providers/Microsoft.Storage/storageAccounts/anstoragestandard/listKeys?api-version=2015-06-15 failed with 404 Not Found</pre>

### Expected Behavior
If a storage account has been removed, why try to get state info for the files that were in the account?
I think it would be safe to mark them removed as well and update the state file.

### Actual Behavior
Terraform fails here and does not update the state file.

### Steps to Reproduce
1) Provision a storage account and a storage container inside the account.
2) Delete the storage account from the Azure portal
3) Run 'terraform refresh'

### References
This may be appropriate to track along with [issue #6526](https://github.com/hashicorp/terraform/issues/6526).

**Comment by stack72** [comment]
Hi @cchildress

Thanks for reporting this issue - sorry it is happening. The error message that you are seeing is talking about a resource that isn't in the configuration sample you have provided. Can you check that you have the correct configuration in place (or should I assume that the config you have provided is a small sample of what you are using)?

Thanks

Paul

**Comment by cchildress** [comment]
Hey @stack72 
Sorry about that, I copy and pasted the wrong storage config; I've updated the initial post with the right config.

What I suspect is happening is the refresh goes and tries to query state on azurerm_storage_container.an_os_images, but gets a 404 error because it relies on anstoragestandard from azurerm_storage_account.an_storage_std which was deleted in the Azure portal manually.
If it evaluated the storage account before the container it could realize that the resource is gone.
