### ISSUE TITLE
Azure RM: timeout on apply AZURERM_TEMPLATE_DEPLOYMENT-based resources, although deployment succeeds

### ISSUE THREAD

**Issue by Preskton** [hashicorp/terraform#6737]
Howdy, it would be really neat if there was a configurable timeout threshold on `azurerm_template_deployment` to allow for certain template deployments to take longer.  Right now, when deploying HD Insights clusters (which normally take 20 min+), I'm getting:

```
* azurerm_template_deployment.hdinsights-cluster: Error waiting for Template Deployment (my-hdinsights-cluster) to become available: timeout while waiting for state to become '[succeeded]'
```

... but it still succeeds!

**Terraform Version** = 0.6.15

### Expected Behavior
I would like a timeout parameter either at the azurerm provider level or at the resource level that allows me to arbitrarily elevate (or lower) the default timeout threshold.  It would be cool if you could turn off the timeout as well, but I'd take that as a nice to have.

### Actual Behavior
There appears to be a hard timeout configured that works for most resources.  It doesn't, though, account for resources that might take a really long time to deploy, like an HD Insight cluster.

**Comment by stack72** [comment]
Hi @Preskton

This timeout has been increased in Terraform 0.6.16 to 40 minutes:

```
log.Printf("[DEBUG] Waiting for Template Deployment (%s) to become available", name)
	stateConf := &resource.StateChangeConf{
		Pending: []string{"creating", "updating", "accepted", "running"},
		Target:  []string{"succeeded"},
		Refresh: templateDeploymentStateRefreshFunc(client, resGroup, name),
		Timeout: 40 * time.Minute,
	}
```

This was done in: https://github.com/hashicorp/terraform/commit/ae38ef2e0198ff2e06ba87d0e3214fede2bded22

Paul

**Comment by stack72** [comment]
Also, @Preskton, if you upgrade to 0.6.16, you will see that Terraform is a lot faster when working with AzureRM. We found some issues in how we register providers that are now smoothed out and remove unnecessary API calls :)

**Comment by Preskton** [comment]
@stack72 I can tell it's faster - great stuff!  In the case of HD Insights cluster deployments it's not Terraform or the API interactions.  It's that deploying an HD Insights cluster actually takes 20+ minutes depending on the number of nodes, complexity, etc., etc.  This is where a configurable timeout would be helpful.  I like having the built-in default, but it would be very helpful to override it for weird operations.

**Comment by Preskton** [comment]
And just saw the note about 40 minutes.  Will do a few runs and let you know how it goes.  20 minutes is usually par for the course for HD Insights, so 40 should cover it.

**Comment by svaidyans** [comment]
Hi Preskton,

I am trying to provision HD Insight clusters using Terraform.  The documentation on TF website is very minimal.  If it is not a trouble, could you please share the Terraform script you have for the HDI provisioning.  Thanks a bunch!

Warm Regards,
Vaidya.

**Comment by stack72** [comment]
Hi @svaidyans 

This terraform resource will only use the resource templates that you will have already created for ARM 

You can check out the Azure documentation for examples

https://github.com/Azure/azure-quickstart-templates

P.

**Comment by Preskton** [comment]
@svaidyans What we ended up doing was:

1. Manually creating the type of HDI cluster we wanted via the Azure portal.
2. Exporting the Azure RM template for the whole cluster. (this is what @stack72 means when it was "already created for ARM")
3. Used here-doc (multiline) string to bring the template into an `azurerm_template_deployment` and dropped terraform variables into the template as necessary (for things like subnets, naming, etc.)

If you plan on deploying more than one HDI cluster, please note that the first six characters for each cluster in a resource group must be unique!

Also note that we are averaging about 20 minutes to deploy a single cluster.

pd

**Comment by svaidyans** [comment]
Hi Preskton,

Thank you very much.  

I have created the HDI cluster manually and also wrote the PowerShell script to automatically provision / destroy it on demand.  (Yes, for me also the provisioning takes a maximum of 27 minutes with average being 24 minutes).  We are standardizing on automation and currently evaluating Terraform.  So I was checking up on provisioning the HDI through Terraform and got stuck up on the resource to use.  I am not sure on the 3rd instruction above "Used here-doc (multiline)...".  If it is not a trouble, can you please expand on it.  Alternately is it possible to invoke a PowerShell script from within a Terraform module - if so, how? 

Once again thanks a bunch for your inputs,
Warm Regards,
Vaidya.

**Comment by Preskton** [comment]
@svaidyans the "here doc" syntax is referenced here (no pun intended): https://www.terraform.io/docs/configuration/syntax.html.

It looks something like this (starts with `<<TEMPLATEBODY` and ends at a line with nothing but `TEMPLATEBODY` (no spaces/indentations).  The code that goes here is the Azure RM template you exported from your HDI cluster via the portal.  Also notice that you can still drop variables in.

```
resource "azurerm_template_deployment" "hdi-storm" {
    name = "myhdistorm"
    resource_group_name = "${var.resource_group}"
    template_body = <<TEMPLATEBODY
    {
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
    "contentVersion": "0.9.0.0",
    "resources": [
        {
            "type": "Microsoft.HDInsight/clusters",
            "name": "myhdicluster",
...
}
TEMPLATEBODY
```

**Comment by svaidyans** [comment]
Hi Preston, 
Thanks very much.  I will try this out.
Warm Regards,
Vaidya.
On 15-Jun-2016 7:25 am, Preston Doster <notifications@github.com> wrote:@svaidyans the "here doc" syntax is referenced here (no pun intended): https://www.terraform.io/docs/configuration/syntax.html.

It looks something like this (starts with <<TEMPLATEBODY and ends at a line with nothing but TEMPLATEBODY (no spaces/indentations).  The code that goes here is the Azure RM template you exported from your HDI cluster via the portal.  Also notice that you can still drop variables in.

resource "azurerm_template_deployment" "hdi-storm" {
    name = "myhdistorm"
    resource_group_name = "${var.resource_group}"
    template_body = <<TEMPLATEBODY
    {
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
    "contentVersion": "0.9.0.0",
    "resources": [
        {
            "type": "Microsoft.HDInsight/clusters",
            "name": "myhdicluster",
...
}
TEMPLATEBODY
