### ISSUE TITLE
Azure RM: azurerm_storage_account should export storage keys

### ISSUE THREAD

**Issue by Preskton** [hashicorp/terraform#6739]
The azurerm_storage_account should export storage keys for use in later Terraform operations.  This would be particularly helpful when creating a storage account, then using it in an Azure RM template deployment where the storage key is an input param (ex: HD Insights cluster).

**Comment by stack72** [comment]
Hi @preskton

Thanks for the suggestion here. Do you think the names `primary_access_key` and `secondary_access_key` make sense here?

Paul

**Comment by Preskton** [comment]
@stack72 Those names work for me.  I know in a more recent version of the Azure RM PowerShell, they switched the result of `Get-AzureRmStorageAccountKey` to return an array of keys instead of properties called `Key1` and `Key2`.  Seems like they're preparing to support more than two keys?

In any case, `primary_access_key` and `secondary_access_key` would be a great start.
