### ISSUE TITLE
provider/openstack Adding fixed_ip_v4 doesnt work

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#6740]
1. Create an instance without specifying fixed ip v4
2. Add fixed_ip_v4
3. Run apply

Result:

Each run terraform will show that ip address is added, but actually not. So each run it will show `  network.0.fixed_ip_v4: "192.168.0.41" => "192.168.0.21"` without every actually modifying it.

**Comment by Fodoj** [comment]
From source code:

```
// Only changes to the floating IP are supported
```

Thats fine, but then we should not get this message that terraform tries to modify it

**Comment by jtopjian** [comment]
The most likely solution for this is going to be to set `ForceNew` on this argument.

**Comment by jtopjian** [comment]
@Fodoj Check out #6844 and let me know if you have any thoughts!
