### ISSUE TITLE
SNS delivery policy always re-applies

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#6754]
Seems like it's just another JSON formatting issue, but adding a delivery_policy will always plan as changed immediately after an apply. In this case:

``` hcl
resource "aws_sns_topic" "report_results" {
  name = "report_results"
  delivery_policy = <<EOF
{
  "http": {
    "defaultHealthyRetryPolicy": {
      "minDelayTarget": 20,
      "maxDelayTarget": 20,
      "numRetries": 10,
      "numMaxDelayRetries": 0,
      "numNoDelayRetries": 0,
      "numMinDelayRetries": 0,
      "backoffFunction": "linear"
    },
    "disableSubscriptionOverrides": false
  }
}
EOF
}
```

**Comment by stack72** [comment]
After a simple recreation, the different is as follows:

```
~ aws_sns_topic.report_results
    delivery_policy: 
    "{\"http\":{\"defaultHealthyRetryPolicy\":{\"minDelayTarget\":20,\"maxDelayTarget\":20,\"numRetries\":10,\"numMaxDelayRetries\":0,\"numNoDelayRetries\":0,\"numMinDelayRetries\":0,\"backoffFunction\":\"linear\"},\"disableSubscriptionOverrides\":false}}" => 
    "{\n  \"http\": {\n    \"defaultHealthyRetryPolicy\": {\n      \"minDelayTarget\": 20,\n      \"maxDelayTarget\": 20,\n      \"numRetries\": 10,\n      \"numMaxDelayRetries\": 0,\n      \"numNoDelayRetries\": 0,\n      \"numMinDelayRetries\": 0,\n      \"backoffFunction\": \"linear\"\n    },\n    \"disableSubscriptionOverrides\": false\n  }\n}\n"
```

**Comment by trevorr** [comment]
I hit this too. It seems like Terraform should strip all (unquoted) whitespace before comparing. As an ugly workaround, one can replace the regex `[ \n]` with nothing and convert the here-document to a string by replacing `"` with `\"`. The latter part is necessary because the here-document always adds a trailing newline.

**Comment by tannirurahul** [comment]
If you want to add throttling policy ie max receives per second we can follow the code pasted below 

delivery_policy = <<EOF
{
  "http": {
    "defaultHealthyRetryPolicy": {
      "minDelayTarget": 20,
      "maxDelayTarget": 60,
      "numRetries": 70,
      "numMaxDelayRetries": 50,
      "numNoDelayRetries": 2,
      "numMinDelayRetries": 5,
      "backoffFunction": "linear"
    },
    "disableSubscriptionOverrides" : false ,
    "defaultThrottlePolicy" : {
      "maxReceivesPerSecond" : 50
    }
  }
}
EOF
