### ISSUE TITLE
aws_s3_bucket resource lifecycle_rule argument requires prefix

### ISSUE THREAD

**Issue by brandongalbraith** [hashicorp/terraform#6755]
### Terraform Version
0.6.15

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### Expected Behavior
Terraform docs for aws_s3_bucket resource indicate lifecycle_rule requires prefix, when AWS does not (lifecycle rule can be applied to entire bucket).

### Actual Behavior
Unable to apply lifecycle_rule to bucket without [prefix](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#prefix) parameter:

```
prefix - (Required) Object key prefix identifying one or more objects to which the rule applies.
```

**Comment by pmoust** [comment]
setting `prefix = ""` targets the whole bucket.

**Comment by brandongalbraith** [comment]
Thanks @pmoust! Want me to fork and submit a PR for https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/r/s3_bucket.html.markdown to update the docs?

**Comment by brandongalbraith** [comment]
Thanks @pmoust!
