### ISSUE TITLE
vSphere provider - Network in 'disconnected' state after booting from a template

### ISSUE THREAD

**Issue by dkalleg** [hashicorp/terraform#6757]
Hi there,
### Terraform Version

Terraform v0.7.0-dev (fae3529da245e66e8df9eadefa0513881f49308d+CHANGES).  
Clean tip of master as of time of posting this.
### Affected Resource(s)
- vSphere provider, vm resource creation
### Terraform Configuration Files

```
resource "vsphere_virtual_machine" "TerraformVm" {

    # Required vars
    name                                = "tfTestVmDisk"
    vcpu                                  = 1
    memory                             = 1024
    datacenter                          = "Datacenter"

    network_interface {
        label = "melody"
    }

    disk {
        template = "ubuntuTemplate"
    }
```
### Debug Output

Provider stuck while waiting for an IP, but is stuck forever since the network does not connect at boot.  If I manually connect the network, the vm will grab an IP and continue on happily and successfully.
### Expected Behavior

Booting from a template, which has a network associated, should connect at boot.
### Actual Behavior

VM boots and is associated with the network, but the network shows in 'disconnected' state and terraform hangs until network is manually connected.
### Steps to Reproduce
1. Create template that has an associated network
2. Create .tf script and define a vm from that template
3. `terraform apply`
4. Watch tf waitForIp forever
### Important Factoids
- Template's network option for "Connect on boot" is enabled.  
- Template's boot option for "Update vmware tools before boot" is enabled.
- Booting a vm from the same template manually will successfully connect to the network at boot (if I select the "Power on after creation" option) through the web ui  

I'm suspecting either some problem with my template, or a problem with the buildNetowrkDevice() function.  I've tinkered with swapping the adapterType between "vmxnet3" and "e1000" with no resolution.  I don't see any additional options we can provide to types.VirtualDeviceConfigSpec / type.VirtualEthernetCard.
Hoping to hear if anyone else even see's this issue.

**Comment by chrislovecnm** [comment]
@dkalleg questions:

1. OS
2. vSphere version
3. double check govmomi tag for me

BTW DUDE NICE BUG REPORT!!!!  Can we just get everyone to write those.

**Comment by chrislovecnm** [comment]
Can you recreate with govc btw??

**Comment by dkalleg** [comment]
1. Ubuntu 14.04
2. VMware ESXi, 6.0.0, 3073146
3. From Godeps.json:
```
			"ImportPath": "github.com/vmware/govmomi",
			"Comment": "v0.6.2",
			"Rev": "9051bd6b44125d9472e0c148b5965692ab283d4a"
```

Haven't tried govc, will see

**Comment by chrislovecnm** [comment]
@dkalleg trying govc may allow us to diagnose if this is api or TF .. I am guessing TF, but it would be a good step.

**Comment by dkalleg** [comment]
Creating a vm from a tempalte with govc does properly connect to the network.

**Comment by dkalleg** [comment]
FYI, i tried adding the Connectable definition in the VirtualDevice definition in buildNetowkrDevice(), but it didn't resolve the issue:
```
--- a/builtin/providers/vsphere/resource_vsphere_virtual_machine.go
+++ b/builtin/providers/vsphere/resource_vsphere_virtual_machine.go
@@ -965,6 +965,11 @@ func buildNetworkDevice(f *find.Finder, label, adapterType string) (*types.Virtu
                                                VirtualDevice: types.VirtualDevice{
                                                        Key:     -1,
                                                        Backing: backing,
+                                                       Connectable: &types.VirtualDeviceConnectInfo{
+                                                               StartConnected:    true,
+                                                               AllowGuestControl: true,
+                                                               Connected:         true,
+                                                       },
                                                },
                                                AddressType: string(types.VirtualEthernetCardMacTypeGenerated),
                                        },
@@ -979,6 +984,11 @@ func buildNetworkDevice(f *find.Finder, label, adapterType string) (*types.Virtu
                                        VirtualDevice: types.VirtualDevice{
                                                Key:     -1,
                                                Backing: backing,
+                                               Connectable: &types.VirtualDeviceConnectInfo{
+                                                       StartConnected:    true,
+                                                       AllowGuestControl: true,
+                                                       Connected:         true,
+                                               },
                                        },
                                        AddressType: string(types.VirtualEthernetCardMacTypeGenerated),
                                },
```

**Comment by VAdamec** [comment]
Same issue with Terraform v0.6.16, all is correctly set but interface is not connected, same template works with pysphere/govc without any issue.

**Comment by VAdamec** [comment]
Same with Terraform v0.7.0-dev (283e3ae6b5a9ba17092ca416ba412018f139e7e8)

**Comment by chrislovecnm** [comment]
@VAdamec yes we will be looking into it.  

@dkalleg any ideas on this one?

**Comment by dkalleg** [comment]
@chrislovecnm  Not at the moment, I've exhausted my current ideas.  
I tried comparing our govmomi calls to the equivalent pyvmomi calls to create a vm from a template.  The only obvious difference I saw was the VirtualDeviceConnectInfo struct with the "StartConnected" attribute, but that did not solve the issue for us.

**Comment by VAdamec** [comment]
Seems that removing openvm tools (version 9) and use tools from ESX helps (version 10) helps. I'll try to get more info and test more versions.

**Comment by chrislovecnm** [comment]
@VAdamec openvmtool v10 is out as well.  Which os are you on?

**Comment by chrislovecnm** [comment]
@VAdamec appreciate you helping with this!!!

**Comment by VAdamec** [comment]
Centos6 64b, is there any repository with latest openvm tools ? I find only version 9 for this version of centos.

**Comment by chrislovecnm** [comment]
Does ttp://packages.vmware.com/packages/rhel7/x86_64/ have it?  This is a good reference. http://www.boche.net/blog/index.php/2015/08/09/rhel-7-open-vm-tools-and-guest-customization/  to use the older version you may need this plugin: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2075048

**Comment by chrislovecnm** [comment]
@dkalleg which version of openvm tools are you using amigo?  

The TF code is doing something odd, and if it deals with openvm tool I am wondering if the openvm tools logs may have something in them.

**Comment by dkalleg** [comment]
9.4.0 since it comes with Ubuntu 14.04.  I'm a bit surprised if an os level package is controlling whether we see a network in connected or disconnected state in vSphere.  I was under the impression that this connected/disconnected state was a "hardware" layer switch in vSphere.  I'll try to do some testing on my end to see if updating open-vm-tools resolves the issue for me too some time next week.

**Comment by chrislovecnm** [comment]
@dkalleg can you co-worker install deployPkg https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2075048 or upgrade to 9.10+

I am fairly certain this is because we remove and then add the nics.

**Comment by chrislovecnm** [comment]
@dkalleg I am quite certain that this a vsphere tools issue.  Can anyone verify on your end?

**Comment by dkalleg** [comment]
@chrislovecnm Haven't had a chance to test it yet.  I'll update here once I do.  Hopefully by next week.

**Comment by dweomer** [comment]
This was exactly the problem I was having. Installing open-vm-tools-deploypkg from VMWare addressed the problem.

**Comment by chrislovecnm** [comment]
Will make sure it is in the docs... I think it is already. 9.10+ has it built in.

**Comment by dweomer** [comment]
@chrislovecnm is there any effort to modify the vSphere driver to not return until the possible reboot incurred from the NIC reconfigure has happened? this is breaking assumptions of my modules as well as preventing provisioner blocks from executing (because they are invariably invoked while the reboot is happening)

**Comment by chrislovecnm** [comment]
@dweomer yes it is a known issue https://github.com/hashicorp/terraform/issues/6727

**Comment by chrislovecnm** [comment]
@dkalleg I think this just needs to be documented

**Comment by abrarshivani** [comment]
@dkalleg I had the same issue. It works if skip_customization is 'true'.

**Comment by aocole** [comment]
Using `skip_customization = true` resolved this for me as well.

**Comment by lynic** [comment]
Any solution to this issue? I have the same problem, while when I try to install `open-vm-tools-deploypkg` it saids it's obsoleted by open-vm-tools.

**Comment by trodemaster** [comment]
I'm also seeing this issue and have a bit more input to add. Have been seeing this issue for a couple months as I added more VMs to my deployment it has gotten worse. 

Terraform version Terraform v0.8.5-dev (69552697bf27366ac63a603aaec369fbf3e05194)
Running on macOS 10.12.3
Deploying Ubuntu 16 VMs with latest open-vm-tools
vSphere 6.5 but had same issue on 6.0

The VMs deploy without issue If I do 1-4 of them at a time. Once the parallel deployment goes past 8 the time increases and I see VMs come up but do not have the nic connected. When seeing issues I have received this error "vsphere_virtual_machine.packertest-VM21: The guest operating system did not respond to a hot-remove request for device ethernet0 in a timely manner.". 

I'm very sure that the issues are not with my templates or VMware tools at this point. These exact same images have thousands of successful deploys and customizations in production. The same TF deploys work if only a few run at a time. 

What I'm focused on is part of the customization and nic removal/recreation is timing out under load. Having replicated the issue while debug_client is enable dumps a ton of soap envelopes and responses but I'm not able to find useful data in them.

**Comment by trodemaster** [comment]
I just testing with Terraform v0.10.0-dev (0c69e466496e86b23e0024889d01efa074b75035) and confirmed that the issue I'm seeing is not fixed with this build. I'll open a new bug when I have time to attempt another debugging session.

**Comment by hauntshadow** [comment]
Has this issue been resolved? I've ran into a similar issue trying to clone a VM. The network is set up properly, but it isn't connected.

**Comment by chanslor** [comment]
I am also seeing this issue. has it been resolved?

**Comment by trodemaster** [comment]
If your still seeing this issue I suggest looking at the vsphere console and see if the VMs are migrating between hosts during the deployment. I was able to avoid the disconnection by making my DRS settings less aggressive.

**Comment by nickkadams** [comment]
I encountered this issue this week using:

Ubuntu 16.04.4 built with Packer 1.2.3
Terraform v0.11.7 with provider.vsphere v1.5.0

I installed open-vm-tools which resulted in grabbing the latest 10.2.0-3. My fix was to version pin:

```sudo apt-get install -y open-vm-tools=2:10.0.7-3227872-2ubuntu1```

Hope this helps someone else.

**Comment by pmithil7** [comment]
@nickkadams downgrading open-vm-tools is not the fix for me. I still see the issue on my Ubuntu 16.04 systems.

**Comment by G3ph4z** [comment]
I has same issue, with Ubuntu 18.04

**Comment by nickkadams** [comment]
@G3ph4z I believe your issue is: https://kb.vmware.com/s/article/56409 I added a shell script to my packer run to resolve it and my 18.04.2 Terraform images do not have that issue anymore.

**Comment by G3ph4z** [comment]
@nickkadams Thank you but it didn't help.
