### ISSUE TITLE
AWS ECS auto scaling support in terraform aws provider

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#6763]
Hi there,

AWS just enabled automatic scaling for EC2 container service -- https://aws.amazon.com/about-aws/whats-new/2016/05/amazon-ec2-container-service-supports-automatic-service-scaling/

It would be super great to have this in terraform. Thanks!

**Comment by enisher** [comment]
👍

**Comment by asharti** [comment]
+1

**Comment by koenijn** [comment]
Just wanted to try it out, but no terraform support yet.

**Comment by mpas** [comment]
+1

**Comment by nasskach** [comment]
+1

**Comment by brikis98** [comment]
+1

**Comment by eedwardsdisco** [comment]
+1

**Comment by bpuglisi** [comment]
+1

**Comment by jcarnegie** [comment]
+1

**Comment by nasskach** [comment]
I have developed something using the AWS Go SDK that works, now I will try to include it in Terraform.

**Comment by chris-mac** [comment]
@nasskach do you have a link to any WIP? Happy to contribute any way I can.

**Comment by fcofdez** [comment]
Is someone working on this? I could send a PR with the auto-scaling feature in a few days.

**Comment by nasskach** [comment]
Sorry, I had a lot of work last week and I didn't manage to finish my PR quickly. I see that @andskli has already sent a PR for this feature (#7663).

**Comment by stack72** [comment]
Closed via #7663
