### ISSUE TITLE
AWS SES support

### ISSUE THREAD

**Issue by iroller** [hashicorp/terraform#6771]
Hi,

Are there any plans to add SES support to Terraform? It looks to be there in aws-sdk-go: https://github.com/hashicorp/aws-sdk-go/blob/master/gen/ses/ses.go

**Comment by yissachar** [comment]
FYI I started a PR a while ago for this: https://github.com/hashicorp/terraform/pull/5387

I ran out of time to finish it up, but if someone is looking to implement this, that should be a good place to start. The only thing I am missing is that receipt rule actions aren't ordered, but that should be fixable by implementing a `position` field as I commented in the PR.

**Comment by spanktar** [comment]
I don't have any Go experience or I would totally help.  Any chance we can motivate this PR to get finished so I don't have to do any MORE CloudFormation BS to cover TF blind spots?  The less CF the better!

**Comment by yissachar** [comment]
@spanktar I've now completed the PR. It's up to the Terraform team now to get this merged in.

**Comment by bobbydeveaux** [comment]
Amazing @yissachar - have a project where we need this ASAP. @spanktar any ETA on this?

Many thanks! :)

**Comment by bobbydeveaux** [comment]
@stack72 *bump*

**Comment by stack72** [comment]
Closed via #5387

**Comment by ccpost** [comment]
It seems like #5387 is just for the email receiving bits of SES.  Has anyone taken a look at supporting the sending endpoints as well?
