### ISSUE TITLE
hcl: Crash when value is 'null'

### ISSUE THREAD

**Issue by adamdecaf** [hashicorp/terraform#6774]
### Terraform Version
```
adam@Planet-X -- tf-crash:  terraform -v
Terraform v0.6.16
```

### Affected Resource(s)
* none (hcl parsing)

### Terraform Configuration Files
```hcl
{
  "module": {
    "app": {
      "foo": null
    }
  }
}
```

### Debug Output
* https://gist.github.com/adamdecaf/3cc22941bdd24cee49993829473d0831

### Panic Output
* https://gist.github.com/adamdecaf/3cc22941bdd24cee49993829473d0831

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` or `terraform apply`

### Important Factoids
This looks to be more a parsing issue with [hcl](https://github.com/hashicorp/hcl) rather than tf itself.

**Comment by jen20** [comment]
Hi @adamdecaf! Wow this is nasty. It _is_ actually a syntax error, since null is not an allowed variable, and you haven't enclosed it as a string, but panicing is not an acceptable response here. I'll get this fixed for 0.7.
