### ISSUE TITLE
aws_elasticache_cluster has no "id" attribute

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform#6779]
* Terraform Version: 0.6.15
* Affected Resource: aws_elasticache_cluster

Given that [most](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html) [other](https://www.terraform.io/docs/providers/aws/r/db_instance.html) [resources](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) have an ID attribute, even those that have a user-provided ID, `aws_elasticache_cluster` should also have an ID attribute. It's impossible to reference the resource otherwise.

**Comment by apparentlymart** [comment]
@maxrothman... it looks like for this resource the id is in `cluster_id`. Can you use that to reference it?

It's weird that it has an inconsistent name, though. We might consider deprecating the `cluster_id` attribute in favor of the more standard `id`.

**Comment by maxrothman** [comment]
@apparentlymart The resource takes `cluster_id` as an argument, but it's not a referenceable attribute of the resource. The only attributes of that resource are `cache_nodes` and `configuration_endpoint`.

**Comment by apparentlymart** [comment]
All arguments are also attributes that you can reference, in spite of what the documentation suggests, so you should be able to interpolate `cluster_id` just as you can interpolate `configuration_endpoint`.

**Comment by maxrothman** [comment]
That works. Thanks!
