### ISSUE TITLE
aws_elasticsearch_domain has no domain_name attribute

### ISSUE THREAD

**Issue by maxrothman** [hashicorp/terraform#6780]
Terraform version: 0.6.15
Resource: aws_elasticsearch_domain

Though the `aws_elasticsearch_domain` does have a `domain_id` attribute, it lacks a `domain_name` attribute (which would essentially return the value of the given `domain_name` argument). Since this is what AWS requires as input for other resources (e.g. CloudWatch alerts), the existing `domain_id` attribute is not sufficient.

**Comment by stack72** [comment]
Hi @maxrothman 

All of the parameters from the resource are actually usably in interpolations / outputs. This may not be very clear and we should address this

You should therefore be able to do something like

```
resource "aws_elasticsearch_domain" "example" {
  domain_name = "tf-test-1"
}

output "elasticsearch_domain_name" {
  value = "${aws_elasticsearch_domain.example.domain_name}"
}
``` 

Please let us know if this is not the case

thanks

Paul

**Comment by maxrothman** [comment]
That works. Thanks!
