### ISSUE TITLE
How to Handle AWS Spot Instance args (tags, etc.)

### ISSUE THREAD

**Issue by johnnyshields** [hashicorp/terraform#6791]
This is a dupe of issue #3263 and PR #4380. I am raising a new issue because I'd like to revisit the problem and agree on an approach with the Terraform team.
#### The Problem
- We need to set tags on AWS spot instances.
- The Terraform schema contains a `spot_instance_request` resource. A `aws_spot_instance_request` is **not** an "instance" itself, rather it is a **request** to Amazon to generate an instance.
- The Terraform schema allows setting `tags` on `aws_spot_instance_request`, however, the tags are not forwarded by AWS to the actual instance when the request in fulfilled (see: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html)
#### Possible Solutions
1. Interpret `tags` on `aws_spot_instance_request` to mean the tags to set on the instance created when the spot request is fulfilled. This is what PR #4380 does.
2. Add an `instance_args` node to the `aws_spot_instance_request` resource which allows various args like `tags` to be set by Terraform on the instance after fulfillment.
3. Enhance the `aws_instance` to have new fields `is_spot_instance`, `spot_price`, `spot_type` etc. If these are set, then Terraform uses a spot instance request workflow to initialize the instance. This approach will require the most effort but is ultimately the most friendly / least surprising to the developer in my opinion--many AWS-related libraries use this abstraction pattern.
4. Introduce a new resource `aws_spot_instance` which behaves as described in #3, to avoid changing the `aws_instance` object.

**Comment by johnnyshields** [comment]
According to the docs:

> Spot Instance Requests support all the same arguments as `aws_instance`

and most of these args except tags seemed to be passed thru to the created instance, so I guess option #1 (PR #4380) is probably the best to stay consistent with the current design.

**Comment by johnnyshields** [comment]
One more comment, to meet the immediate need I'd be in favor of merging PR #4380 even if a different option is chosen in the future (they aren't mutually exclusive.)

**Comment by cbarbour** [comment]
This is the documented behavior of AWS spot instances, rather than a bug in the AWS provider.

As a workaround, consider using an auto-scaling group. The autoscaling group can request spot instances, and the launch_configuration will pass tags onto the instance. You don't need to autoscale the autoscaling group; you can specify the pool size manually.

The downside to that approach, is that the autoscaling resources do not provide attributes for the resulting instances.
