### ISSUE TITLE
Update of a lambda function stored in unversioned S3 bucket does not work

### ISSUE THREAD

**Issue by alexef** [hashicorp/terraform#6794]
Saw that this should have already be fixed by #4770 and #5370, but I'm facing the following issue:

Changing the configuration from:

    resource "aws_lambda_function" "test" {
      s3_bucket = "example"
      s3_key = "test.zip"
      function_name = "testFunction"
    }

to

    resource "aws_lambda_function" "test" {
      s3_bucket = "example"
      s3_key = "test2.zip"
      function_name = "testFunction"
    }

raises the error:

    * aws_lambda_function.testFunction: Error modifying Lambda Function Code testFunction: InvalidParameter: 1 validation error(s) found.
    - minimum field size of 1, UpdateFunctionCodeInput.S3ObjectVersion.

Looking at the the `UpdateFunctionCodeInput` what I suppose it happens is that terraform checks the tfstate and expects that the `s3_object_version` field has at least one character, so for updates it becomes mandatory.

**Comment by apparentlymart** [comment]
Thanks for reporting this @alexef!

I can confirm this bug as I too encountered it a few days ago and hadn't got around to opening an issue for it yet.

I think the fix here is actually quite simple: during Create, [we set the version field only if it's non-empty in the config](https://github.com/hashicorp/terraform/blob/f6a21e789954a4d9e770ba9b5378b117f3d0721a/builtin/providers/aws/resource_aws_lambda_function.go#L155:L157), so it gets sent as `null` to AWS. But during `Update`, [we set it unconditionally](https://github.com/hashicorp/terraform/blob/f6a21e789954a4d9e770ba9b5378b117f3d0721a/builtin/providers/aws/resource_aws_lambda_function.go#L311), causing *the empty string* to be sent when it's empty, which the AWS API implementation then complains about.

I think updating the update implementation to look like the create one will fix this. I'll probably get to this eventually if no-one else does, but if someone else happens upon this while looking for a "first Terraform change" this is probably a good, straightforward one to start with and make sure there's an acceptance test for updating so we can catch any other issues where the Create/Update codepaths are different.

**Comment by alexef** [comment]
Thank you @apparentlymart for making it seem so easy! Here comes my first PR.

I'm really not sure about the acceptance test you mentioned above - just copied and adapted an existing one.

**Comment by ProTip** [comment]
This was tripping me up today as well on the latest release.

**Comment by joncolby** [comment]
would love to see this change merged.  I'm hitting this problem constantly.  We are managing a few lambdas with terraform (0.7.1).
