### ISSUE TITLE
azurerm: Can't enable ipv4_forwarding on a NIC

### ISSUE THREAD

**Issue by colemickens** [hashicorp/terraform#6803]
Affected resource: `azurerm_network_interface`

**Comment by stack72** [comment]
Hi @colemickens 

Thanks for opening the issue here. Can you point out (in the docs or the SDK) how we can add this? I can get it added easily then

FTR, if this is part of the new SDK, then I am having a lot of issues upgrading to it atm as this had serious breaking changes to how we were using it. So it may be slower if it's part of that SDK

P.

**Comment by colemickens** [comment]
Hi @stack72,

It should just be a matter of adding an option to https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_network_interface_card.go to also affect `iface.EnableIPForwarding`.

https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/network#InterfacePropertiesFormat

This should exist even in older versions of the Go SDK.

**Comment by colemickens** [comment]
Also, please feel free to reach out if there are specific upgrade pain points and I can advise on how to handle the changes. I think most of the breaking changes have been needed to support other Azure clouds besides public cloud and to properly support long-running operations, and shouldn't be terribly difficult to adopt. Let me know.

**Comment by jen20** [comment]
@colemickens The biggest problem is that polling no longer appears to be handled internally. Underneath I couldn't care less whether you are polling, I just want the ID out of the request when it is finished. We must block in all cases anyway. See jen20/riviera for a more optimal way of dealing with polling.

**Comment by stack72** [comment]
@colemickens thanks for the link - i guess it was implemented the first time around as it wasn't in the docs - https://msdn.microsoft.com/en-us/library/mt163668.aspx

Adding it now :)

**Comment by colemickens** [comment]
Oh.... thanks for pointing that out. I'll try to see about getting that fixed.

And thanks for adding the feature as well!

**Comment by stack72** [comment]
Closed by #6807
