### ISSUE TITLE
Feature Request : Open Resource where to define Custom Provisioners

### ISSUE THREAD

**Issue by rainmanh** [hashicorp/terraform#6804]
Hi
Terraform v0.6.16
I noticed terraform v0.6.16 for AWS does not have support got SES and I didn't want to create wrapping scripts but I wanted to have a fully integrated solution within terraform

SO I have used python (boto3) and Resource: aws_iam_account_password_policy as follows:
```
resource "aws_iam_account_password_policy" "main" {
  minimum_password_length = "${var.minimum_password_length}"
  require_lowercase_characters = "${var.require_lowercase_characters}"
  require_numbers = "${var.require_numbers}"
  require_uppercase_characters = "${var.require_uppercase_characters}"
  require_symbols = "${var.require_symbols}"
  allow_users_to_change_password = "${var.allow_users_to_change_password}"
  password_reuse_prevention = "${var.password_reuse_prevention}"
  max_password_age = "${var.max_password_age}"
  provisioner "local-exec" {
    command = "python python/email_validation.py ${var.region} ${var.admin_email} ${var.profile}"
  }
}
```
So in that way , I have expanded a Resource I needed with a part, written in python, which I also needed.

But rather than re-utilising resources, wouldn't be a good idea to have some sort of Open Resource which we can customise integration our scripting to complete the whole terraform set of tasks? 

Does it make sense?

Thanks

**Comment by jen20** [comment]
Hi @rainmanh! You can use the `null_resource` for this - it allows for provisioners in exactly the manner you need. You can then use `depends_on` on this and other resources to hook it into the correct spot in the graph. I'll close this issue for now - if you have further questions on this please feel free to reopen it!
