### ISSUE TITLE
Website update documentation is out of date

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6808]
Hey guys

For some reason https://www.terraform.io/docs/providers/vsphere/index.html is seeming to be older documentation, or is broken. For instance https://github.com/hashicorp/terraform/blob/v0.6.16/website/source/docs/providers/vsphere/r/file.html.markdown is not showing up. When I have a chance I will see if I can run the website locally, but I have zero knowledge of how it renders.

Thanks

**Comment by catsby** [comment]
We deploy the site with every release. Documentation changes that still reflect the current version of Terraform need to be cherry-picked into the `stable-website` branch and can be deployed separately. 

Looking at #6401 , it doesn't seem that the `vsphere_file` resource was added to the vpshere layout:

- https://github.com/hashicorp/terraform/blob/master/website/source/layouts/vsphere.erb

The file did get rendered and deployed, there just isn't a link to it. There do appear to be some formatting/rendering issues with that page though:

- https://www.terraform.io/docs/providers/vsphere/r/file.html

**Comment by chrislovecnm** [comment]
if we submit a PR can we get it fixed?

**Comment by chrislovecnm** [comment]
Meaning can we get the site updated ;)

**Comment by catsby** [comment]
Yes, a PR to add the link to the vpshere index page and to fix the formatting for the page can get merged and deployed out of band of the release cycle

**Comment by chrislovecnm** [comment]
@catsby someone beat me to it ..
