### ISSUE TITLE
azurerm: support load balancers

### ISSUE THREAD

**Issue by colemickens** [hashicorp/terraform#6812]
**providers/azurerm**: support load balancers

Proposed: support Load Balancers on Azure by introducing a new resource `azurerm_load_balancer`. It looks like the `azurerm_network_interface` already supports being placed in the backend pool of a load balancer, and there's already support for `azurerm_public_ip` to provide as frontend ip configurations to the load balancer.

**Comment by jen20** [comment]
Hi @colemickens! This is being worked on in #6467, #6429 and (originally) #4343. Unfortunately "add support for" is a rather large job as the API is rather complex. Given that there are open pull requests for review, I'm going to close this issue in favour of discussion continuing on the relevant pull requests.
