### ISSUE TITLE
Website: 404 returns a 301 to a 200

### ISSUE THREAD

**Issue by ajlanghorn** [hashicorp/terraform#6815]
When hitting a page that returns a "page not found" error in the browser, a la [/404.html](https://terraform.io/404.html), I imagined that the HTTP response code would be a 404. Instead, it's a 301 to /404.html (by way of Location header), which returns a 200. At no point does the S3 bucket return a 404 for... a 404. Could a custom error document be implemented here to fix that, as I think that will return a proper 404?

```
$ curl -I https://www.terraform.io/oasd9uhdsdhidasj.html
HTTP/1.1 301 Not Found
...
location: /404.html
```

```
$ curl -I https://www.terraform.io/404.html
HTTP/1.1 200 OK
```

**Comment by ajlanghorn** [comment]
In hindsight, this might be the standard behaviour when using S3 to host a static site. I've forgotten whether it is off the top of my head. Assuming it is, this is probably a `wontfix` until either AWS fix it, or the site moves elsewhere

**Comment by Ninir** [comment]
I think this can be closed since it has the expecting behaviour:

```bash
$ curl -I https://www.terraform.io/test_404.html
HTTP/1.1 404 OK
```

**Comment by stack72** [comment]
@ajlanghorn yeah, we are hosting in AWS using S3 - so this is not something we have control of i'm afraid :(
