### ISSUE TITLE
Data resources in non-root modules render incorrectly in plan output

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#6823]
![terraform-nested-module-data](https://cloud.githubusercontent.com/assets/20180/15454990/ffc86678-1ffb-11e6-8391-aacd35376573.png)

The plan renderer has a special case for resources whose names begin with `data.`, but when data resources appear inside nested modules they don't actually have this prefix and so the diff is presented as if it were an update of a managed resource.

**Comment by jen20** [comment]
Good catch @apparentlymart! The logic here is going to need to take into account the prefix of the module I think. I'll work on this now.
