### ISSUE TITLE
provider/aws: failure re-applying aws_db_subnet_group

### ISSUE THREAD

**Issue by jumping** [hashicorp/terraform#6828]
### Terraform Version
`
Terraform v0.6.16
`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_subnet_group

### Terraform Configuration Files
```hcl
resource "aws_db_subnet_group" "rds_one" {
  name = "rds_one_db"
  description = "db subnets for rds_one"
  subnet_ids = ["${aws_subnet.testing-public-1.id}", "${aws_subnet.testing-public-2.id}"]

  tags {
    Name = "testing"
  }

}
```

### Panic Output
aws_db_subnet_group.rds_one: InvalidParameterValue: The specified resource name does not match an RDS resource in this region.
	status code: 400, request id: 2637c708-20c3-11e6-934a-3f7afee82e87

### Expected Behavior
If the group rds_one_db exists, then could not run the `terraform apply` more than one time.

**Comment by jumping** [comment]
https://gist.github.com/jumping/5fd23e5e8cfd1123adcaaf219178dba7

**Comment by catsby** [comment]
Hello –

Unfortunately I don't have an AWS account for Beijing region; can you tell me, are you able to reproduce this bug in any other region? 
Is there any HTTP request debugging information that's helpful if you run these commands with `TF_LOG=1` environment variable set?

`$ TF_LOG=1 terraform apply -target=aws_db_subnet_group.rds_one`

**Comment by stack72** [comment]
@jumping ping on this

**Comment by stack72** [comment]
Going to close this - haven't heard back from you on this since we pinged - please do let us know if there is still an issue

Paul

**Comment by andylockran** [comment]
I appear to be getting the same issue in eu-west-1
