### ISSUE TITLE
0.7 make dev and make bin failed

### ISSUE THREAD

**Issue by arcadiatea** [hashicorp/terraform#6840]
The build procedure has bug after download the new master (verion 0.7)

error message
`Stderr: # github.com/hashicorp/ticketmaster/terraform
./config.go:249: cannot use "github.com/hashicorp/terraform/plugin".Handshake (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin".HandshakeConfig) as type "github.com/hashicorp/ticketmaster/terraform/vendor/github.com/hashicorp/go-plugin".HandshakeConfig in assignment
./config.go:251: cannot use "github.com/hashicorp/terraform/plugin".PluginMap (type map[string]"github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin".Plugin) as type map[string]"github.com/hashicorp/ticketmaster/terraform/vendor/github.com/hashicorp/go-plugin".Plugin in assignment
./config.go:286: cannot use "github.com/hashicorp/terraform/plugin".Handshake (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin".HandshakeConfig) as type "github.com/hashicorp/ticketmaster/terraform/vendor/github.com/hashicorp/go-plugin".HandshakeConfig in assignment
./config.go:289: cannot use "github.com/hashicorp/terraform/plugin".PluginMap (type map[string]"github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-plugin".Plugin) as type map[string]"github.com/hashicorp/ticketmaster/terraform/vendor/github.com/hashicorp/go-plugin".Plugin in assignment
`

**Comment by ChloeTigre** [comment]
Hey,

This will happen when you symlink the real development path into $GOPATH/src/github.com/hashicorp/terraform and you will have `go get -u` the deps yourself.

Solution: checkout for real terraform in the right path.

(this is how I ended up here)

**Comment by arcadiatea** [comment]
Got it. I was using symlink and have the problem. It works fine without symlink

**Comment by jmehnle** [comment]
But why is this necessary? It turns out symlinking Tf into `$GOPATH/src/github.com/hashicorp/terraform` makes a lot of sense in my situation.
