### ISSUE TITLE
aws RDS (Aurora), instance parameter and changes

### ISSUE THREAD

**Issue by arcadiatea** [hashicorp/terraform#6841]
Terraform 0.7, Aurora RDS instance
Issue 1. The current terraform did not support parameter group at instance level. 
Issue 2. The current terraform did not have code to detected any changes at Aurora RDS Instance level to call a ModifyInstance action. The critical parameter lack of the ModifyInstance action is instance class change. Any change of db instance type will end with a destroy and rebuild. 

I have fixed code ready to submit later today.

**Comment by catsby** [comment]
Hello –

> The current terraform also did not detect the changes of db instance type. The db instance type changes result in a resource destroy and rebuild.

I'm not sure I understand here. You mention it did not detect the change of db instance type (I assume `instance_class` config parameter), but you also mention the change resulted in a destroy/rebuild.. which suggests it was detected. Maybe I'm misunderstanding. Do you have a configuration that demonstrates this behavior?

**Comment by arcadiatea** [comment]
@catsby 
I updated the issue definition.
The current terraform model be able to detect the change of instance class, but instead of do a ModifyInstance action, it go for the destroy and recreate route.  The current terraform has no feature on cluster instance update (resourceAwsRDSClusterInstanceUpdate). I will submit a pull request for just fix the instance class change and parameter group today. 
I am looking other feature which needed to be changed at Aurora Instance level and open different issues and pull requests

**Comment by arcadiatea** [comment]
@catsby 
Current plan when instance class change.

`-/+ aws_rds_cluster_instance.www_instance
    cluster_identifier:   "prd00000111-linda2-acctmgr-aurora-www" => "prd00000111-linda2-acctmgr-aurora-www"
    db_subnet_group_name: "prd00000111.linda2.acctmgr-aurora" => "prd00000111.linda2.acctmgr-aurora"
    endpoint:             "prd00000111-linda2-acctmgr-aurora-www-0.cv5zmqt8xpne.us-east-1.rds.amazonaws.com" => "<computed>"
    identifier:           "prd00000111-linda2-acctmgr-aurora-www-0" => "prd00000111-linda2-acctmgr-aurora-www-0"
    instance_class:       "db.r3.xlarge" => "db.r3.2xlarge" (forces new resource)
    port:                 "3306" => "<computed>"
    publicly_accessible:  "false" => "false"
    tags.#:               "3" => "3"
    tags.Environment:     "linda2" => "linda2"
    tags.InventoryCode:   "acctmgr-aurora" => "acctmgr-aurora"
    tags.ProductCode:     "PRD00000111" => "PRD00000111"
    writer:               "true" => "<computed>"


Plan: 1 to add, 0 to change, 1 to destroy.`

After fix, it should be
`
~ aws_rds_cluster_instance.www_instance
    instance_class: "db.r3.xlarge" => "db.r3.2xlarge"
`

**Comment by catsby** [comment]
Does this assume users have specified the `apply_immediately` flag? Otherwise as I understand it, the change will not occur until the next maintenance window.

**Comment by arcadiatea** [comment]
Yes, apply_immediately flag is also included as a choice.

**Comment by catsby** [comment]
We merged #6865 so I'm going to close this, thanks!
