### ISSUE TITLE
Check for invalid characters within azurerm_storage_container

### ISSUE THREAD

**Issue by dpnl87** [hashicorp/terraform#6846]
When running Terraform 0.6.16 with the azurerm provider I noticed that `plan` accepts invalid characters for a `azurerm_storage_container` which will fail when applying the changes to Azure.

```
resource "azurerm_storage_container" "chef_linux_container" {
    name = "linux_disk"
    resource_group_name = "${azurerm_resource_group.chef_test_rg.name}"
    storage_account_name = "${azurerm_storage_account.chef_test_storage.name}"
    container_access_type = "private"
}
```

> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * azurerm_storage_container.chef_linux_container: Error creating container "linux_disk" in storage account "cts20160524": storage: service returned error: StatusCode=400, ErrorCode=InvalidResourceName, ErrorMessage=The specifed resource name contains invalid characters.
> RequestId:7f2285a8-0001-009d-1ab6-b52384000000
> Time:2016-05-24T12:18:24.3800597Z, RequestId=7f2285a8-0001-009d-1ab6-b52384000000, QueryParameterName=, QueryParameterValue=

When you remove `_` it works.
```
resource "azurerm_storage_container" "chef_linux_container" {
    name = "linuxdisk"
    resource_group_name = "${azurerm_resource_group.chef_test_rg.name}"
    storage_account_name = "${azurerm_storage_account.chef_test_storage.name}"
    container_access_type = "private"
}
```

**Comment by stack72** [comment]
Hi @dpnl87 

Apologies you are having this issue. I just opened a PR this afternoon to fix this

Thanks

Paul

**Comment by dpnl87** [comment]
Thnx for addressing this so quickly! 👍

**Comment by reddare** [comment]
Hello from 2019!
