### ISSUE TITLE
AzureRM - Feature Req - Azure File Service

### ISSUE THREAD

**Issue by tasquith** [hashicorp/terraform#6849]
Hi,

I've had a quick look around and can't seem to find a duplicate request so apologies if I've missed something.

Are there any plans to support Azure File Services? We are considering it as part of a backup/recovery strategy for our linux machines.

https://azure.microsoft.com/en-gb/documentation/articles/storage-how-to-use-files-linux/

I've included the API ref below:

https://msdn.microsoft.com/library/azure/dn167006.aspx

Regards,
Tom

**Comment by stack72** [comment]
Hi @tasquith 

Thanks for the request here. I have started the work, BUT the issue I am facing is that the `FileClient` has no notion of a Get request. So when I create a FileShare etc, I can't actually query to see if it was successfully created

P.

**Comment by tasquith** [comment]
Hi @stack72,

Sorry, I hadn't noticed that you'd replied!

That's a pain, is that an issue with the azure-sdk-for go?

Cheers,
Tom

**Comment by stack72** [comment]
@tasquith 

this isn't an issue on their side - we just need to implement it in a different way. I'll try and punt this for 0.7.1

Paul

**Comment by stack72** [comment]
Ok, I had to open an issue on this

https://github.com/Azure/azure-sdk-for-go/issues/364

**Comment by stack72** [comment]
Closed via #8674
