### ISSUE TITLE
Variable key names that start with numbers cause error

### ISSUE THREAD

**Issue by echohack** [hashicorp/terraform#6857]
When using variable key names that start with numbers it will die. This example will cause an error:

```
variable "cpu" {
  default = {
    medium = "1"
    large = "2"
    xlarge = "4"
    2xlarge = "6"
  }
}
variable "memory" {
  default = {
    medium = "2048"
    large = "4096"
    xlarge = "8192"
    2xlarge = "16384"
  }
}
```
Error:
```
Error downloading modules: module basic-server: Error parsing .terraform/modules/89749676d10d29b9f4028aceba325e4e/main.tf: At 12:11: nested object expected: LBRACE got: ASSIGN
```

Change the variables so the numbers aren't first and the error goes away:

```
variable "cpu" {
  default = {
    medium = "1"
    large = "2"
    xlarge = "4"
    x2large = "6"
  }
}
variable "memory" {
  default = {
    medium = "2048"
    large = "4096"
    xlarge = "8192"
    x2large = "16384"
  }
}
```

`terraform -v`
`Terraform v0.6.16`

**Comment by apparentlymart** [comment]
Hi @echohack!

Does it work if you put the key names in quotes? I think that will help the parser understand that these are single names rather than a number followed by a name.

**Comment by jen20** [comment]
Hi @echohack! I'd never seen this before but can reproduce it. I think we can fix up the parser to not do this - I consider this to be a bug in HCL.

cc @phinze.

**Comment by jen20** [comment]
Hi @echohack! I've taken another look at this, and it is not straightforward to make this parse in the manner you'd like. However, if you enclose the number in string quotes as @apparentlymart suggests, all is well:

```hcl
variable "cpu" {
  default = {
    medium    = "1"
    large     = "2"
    xlarge    = "4"
    "2xlarge" = "6"
  }
}

variable "memory" {
  default = {
    medium    = "2048"
    large     = "4096"
    xlarge    = "8192"
    "2xlarge" = "16384"
  }
}
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

I'm going to open a pull request to document this behaviour in the [configuration syntax](https://www.terraform.io/docs/configuration/syntax.html) documentation - please feel free to reopen this issue if you have further questions.
