### ISSUE TITLE
aws_autoscaling_group & aws_launch_configuration can't be configured w/ 'lifecycle'

### ISSUE THREAD

**Issue by bdruth** [hashicorp/terraform#6859]
Looking at the docs, it seems that 

aws_autoscaling_group
aws_launch_configuration

should both support a lifecycle property - but I get an error using JSON configs that this an invalid or unsupported property.

I'm using the same "lifecycle" config snippet as I use for an aws_iam_server_certificate, which seems to work just fine.

**Comment by catsby** [comment]
Hey @bdruth – can you share your JSON config(s) that demonstrate this? We'll take a look

**Comment by bdruth** [comment]
I can't get the error to happen anymore :(

**Comment by catsby** [comment]
OK, well if you do come across this again please let us know!
