### ISSUE TITLE
Need way to interpolate count index as other than zero-based (for host names)

### ISSUE THREAD

**Issue by ecweaver** [hashicorp/terraform#686]
Around our shop, server names with numbers are done one-based.  
Since the only way, in a counted resource, to interpolate a ${count.index} is zero-based, this causes annoying zero-based server names.  

IWBNI there were either another "part" for count, say index1, or a way to specify an offset such as indexplus 1 or a way to nest those references and an "add" interpolation.  Something, anything, please.

**Comment by tkak** [comment]
It would be very helpful if terraform supported basic math feature or index1 feature.

**Comment by mitchellh** [comment]
@tkak It is coming )

**Comment by mitchellh** [comment]
Done. We added math support in for int types so you can do things like `${count.index+1}` now.

**Comment by jimmycuadra** [comment]
I think there might be a related issue for this, but what about left padding a number to a certain number of digits so you can use the count to create server names like server-01, server-02, etc.?

**Comment by pmoust** [comment]
ΞξφφφφφΞξφφφφφφ
Στις 16 Δεκ 2014 9:54 μ.μ., ο χρήστης "Eric Weaver" <
notifications@github.com> έγραψε:

**Comment by mitchellh** [comment]
@jimmycuadra There is a `sprintf`-style issue on page 1 somewhere. :)
