### ISSUE TITLE
cannot use empty strings with jsonencode

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#6863]
### Terraform Version

0.6.16
### Affected Resource(s)
- `jsonencode` function

Likely an issue with the core jsonencode function, it's inserting an extraneous escaped pair of double quotes for an empty string, causing it to break anything that would otherwise accept an empty string but cannot accept `""` or `\"\"`.
### Terraform Configuration Files

```
variable "my_test_var" {
  type = "string"
  default = ""
}
```

```
output "test" {
  value = "jsonencode(var.my_test_var)"
}
```

running apply:

```
Outputs:
  test           = ""
```

inspecting tfstate:

```
            "outputs": {
                "test": "\"\""
            },
```
### Expected Behavior
- Output value is empty
- tfstate shows empty string `"test": ""`
### Actual Behavior
- Output value shows (post-escaping) double quotes
- tfstate shows string value of `"test": "\"\""`
### Steps to Reproduce
1. `terraform apply`

**Comment by mitchellh** [comment]
This appears to be the correct behavior: encoding `""` should be `""`. Storing that within the state itself requires escaping it. Am I missing something?

**Comment by eedwardsdisco** [comment]
@mitchellh Yes you're missing something :P

If I define an empty variable, it gets json encoded into an additional pair of quotes, thus not actually empty any more.

Thus encoding `""` is `""""`, which gets escaped as `"\"\""` inside the json state.

**Comment by eedwardsdisco** [comment]
I guess to clarify the use case, I want to be able to store a variable empty, but if that variable has text, then I want it to be json encoded.

If you're going to always json encode an empty string into a pair of quotes, then I need a 'jsondecode' function to go along with the encode function.

e.g. if I go to read back the value of that variable later, as long as I know it was always written using jsonencode, then I would be able to jsondecode and end up with an empty string again.

**Comment by mitchellh** [comment]
I'm running it locally and getting this value in my state:

```
$ terraform output foo
""
```

This is the correct JSON encoding of an empty string, verified by another language (Ruby):

```
irb(main):003:0> require "json"
=> true
irb(main):004:0> JSON.dump("")
=> "\"\""
irb(main):005:0> puts JSON.dump("")
""
=> nil
```

It isn't turning into `"\"\""` as you're saying, although it is STORED that way since we store in JSON format so it must escape the strings. But when you read it is the empty string.

JSON encoding "" should not equal `` (void?) since we don't support that.

`jsondecode` makes sense but would be fairly limited right now since we don't support nested lists/maps within Terraform variables.

**Comment by eedwardsdisco** [comment]
@mitchellh 

Thank you for the response. It's been a while since I filed this issue and I don't remember the exact scenario of the project that I was working on that bit me. I believe it related to using the value in an interpolation, and in that use case it was actually ending up with a value of `""` rather than an empty string, which broke the behavior trick I was trying to utilize at the time.

As to your point, it sounds like an empty string encoded in json correctly will be `""`, and thus I would need a `jsondecode` to return that to an empty value (e.g. my expectation was originally that `"name$(var.my_json_encoded_empty_value)test"` interpolates to `nametest`, not `name""test`)

Sorry for any confusion.
