### ISSUE TITLE
Unable to destroy VPC [The vpc has dependencies and cannot be deleted]

### ISSUE THREAD

**Issue by mpas** [hashicorp/terraform#6866]
Hi there,

Hi there, i am running into an issue where we are unable to perform a 'terraform destroy'. 
The result is that everything gets deleted except the vpc.

* aws_vpc.vpc: DependencyViolation: The vpc 'vpc-123456789' has dependencies and cannot be deleted.

### Terraform Version
0.6.16

### Affected Resource(s)
- aws_vpc.vpc

### Debug Output
* aws_vpc.vpc: DependencyViolation: The vpc 'vpc-123456789' has dependencies and cannot be deleted.

**Comment by stack72** [comment]
Hi @mpas 

thanks for reporting the issue here. Apologies you are finding this to be the case. In order to try and help debug the issue you are having, please can you post your TF config (minus secrets!) and the commands you are using to try and delete

Thanks

Paul

**Comment by mpas** [comment]
@stack72 Somehow the problem disappeared. Tried several times and it seems to be ok now. So closing the issue. Thanks
