### ISSUE TITLE
aws_security_grop_rule acceptance tests (PartialMatch) fail in master

### ISSUE THREAD

**Issue by stevehorsfield** [hashicorp/terraform#6871]
### Terraform Version
```
version
Terraform v0.7.0-dev (5fcc0892661aee905b926b01ad6aa60243ee6b0d)
```

### Affected Resource(s)
- aws_security_group_rule

### Terraform Configuration Files
See https://github.com/hashicorp/terraform/blob/1a2846072c2d4fe52da6483a42c81ca9120b734b/builtin/providers/aws/resource_aws_security_group_rule_test.go#L744-L843

### Debug Output
See https://gist.github.com/stevehorsfield/d440a04a1dc7436ec8057dde947d0737

### Panic Output
No panic.

### Expected Behavior
Tests should succeed. Resources should be deleted.

### Actual Behavior
Tests failed. See https://gist.github.com/stevehorsfield/d440a04a1dc7436ec8057dde947d0737 for output.

Test VPC and resources are left behind in AWS.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSecurityGroupRule_PartialMatching_basic'`
make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSSecurityGroupRule_PartialMatching_Source'
```

### Important Factoids
Running in EC2 VPC - no Classic support. Using Vault for IAM credentials.
Other integration tests in the AWS Security Group and AWS Security Group Rule files pass, except those requiring EC2 Classic.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-3413

**Comment by catsby** [comment]
Thanks @stevehorsfield – I believe this is a duplicate of https://github.com/hashicorp/terraform/issues/6728 which should be patched by https://github.com/hashicorp/terraform/pull/6730 , which I will be reviewing today. Thanks!

**Comment by stevehorsfield** [comment]
Sure @catsby - I didn't find that issue when I searched for a related issue, so thanks for confirming.

**Comment by catsby** [comment]
@stevehorsfield no worries, it's not labeled the same and only references the test later in a comment, so I'm not surprised. Thanks again!
