### ISSUE TITLE
Can't specify IP CIDR as a variable when creating a security group rule

### ISSUE THREAD

**Issue by achalupa74** [hashicorp/terraform#6875]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
PS C:\TF\test> terraform -v
Terraform v0.6.16

### Affected Resource(s)
- aws_security_group_rule

### Terraform Configuration Files
2 TF files included in ZIP file:
    - test.tf is the calling module.  Simple calls brooklyn_jump_server_security_group.tf to create a security group with two rules.
    - brooklyn_jump_server_security_group.tf creates 1 security group with 2 ingres rules.  The ingres rule that has the IP CIDR sourced via a variable does NOT get created.

resource "aws_security_group_rule" "all_in_release" {
  provider = "aws.brooklyn_jump_server_security_group"
  type = "ingress"
  from_port = 0
  to_port = 0
  protocol = "-1"
  cidr_blocks = ["${release_eng_cidr_block}"]
  #cidr_blocks = ["10.240.0.0/16"]
  security_group_id = "${aws_security_group.jump.id}"
}

### Debug Output
In the attached ZIP file you'll see the terraform apply console output that implies that it created 3 resources (the SG, and 2 rules).

### Expected Behavior
The terraform apply should create 1 security group with 2 INGRES rules in it.

### Actual Behavior
No errors were displayed.
The terraform apply created the security group but the security group only has 1 rule in it.
The rule that set the cidr_blocks variable by passing it another variable did NOT get created.
See capture.jpg included in the ZIP file.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` using the code provided in the attached ZIP.

### Important Factoids
If we hard code the cidr_blocks rather than using a variable it works fine.

[security_group_rule_example.zip](https://github.com/hashicorp/terraform/files/282179/security_group_rule_example.zip)

**Comment by daveadams** [comment]
You need to use `var.release_eng_cidr_block` in the interpolation. You left out the `var.`

**Comment by achalupa74** [comment]
that was it.  Thanks!
