### ISSUE TITLE
aws_route_table_association created via count incorrectly removed

### ISSUE THREAD

**Issue by paulcollinsiii** [hashicorp/terraform#6882]
### Terraform Version
Terraform v0.6.15

### Affected Resources
* `aws_route_table`
* `aws_route_table_association`
* indirectly affects `aws_vpc_peering_connection`

### Terraform Configuration Files
Assumptions
* AWS Account A has one VPC
* AWS Account A's VPC has a variable number of subnets. In this case it's one subnet per availability zone
* AWS Account B has one VPC w/ TWO subnets you want to peer
* Those details are passed in via CSV separated vars

I've filled out the vars here with some sane values (account ID's have been scrubbed)

```
variable "vpc_ip_block" { default =  "172.31.0.0/16" }
variable "private_subnet_ip_block" { default =  "172.31.2.0/24" }
variable "private_subnet_ip_block_aznewbits" { default =  2 }

variable "peer_aws_account_id" { default =  "AWSID1,AWSID2" }
variable "peer_vpc_id" { default =  "VPCID1,VPCID2" }
variable "peer_vpc_cidr" { default =  "10.0.0.0/24,10.1.0.0/24" }

variable "availability_zones" {
  default = {
    "count" = 4
    "0" = "a"
    "1" = "b"
    "2" = "d"
    "3" = "e"
  }
}

resource "aws_vpc" "vpc" {
  cidr_block = "${var.vpc_ip_block}"
}

resource "aws_internet_gateway" "gateway" {
  vpc_id = "${aws_vpc.vpc.id}"
}

resource "aws_subnet" "private" {
  count = "${var.availability_zones.count}"
  availability_zone = "${var.region}${lookup(var.availability_zones, count.index)}"
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "${cidrsubnet(var.private_subnet_ip_block, var.private_subnet_ip_block_aznewbits, count.index)}"
}

resource "aws_route_table" "private" {
  vpc_id = "${aws_vpc.vpc.id}"
  route {
    cidr_block = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.nat.id}"
  }
}

resource "aws_route_table_association" "private" {
  subnet_id = "${element(aws_subnet.private.*.id, count.index)}"
  route_table_id = "${aws_route_table.private.id}"
  count = "${var.availability_zones.count}"
}

resource "aws_vpc_peering_connection" "peer" {
  peer_owner_id = "${element(split(",", var.peer_aws_account_id), count.index)}"
  peer_vpc_id = "${element(split(",", var.peer_vpc_id), count.index)}"
  vpc_id = "${aws_vpc.vpc.id}"

  count = "${length(split(",", var.peer_vpc_id))}"
}

resource "aws_route" "peer" {
  route_table_id = "${aws_route_table.private.id}"
  vpc_peering_connection_id = "${element(aws_vpc_peering_connection.peer.*.id, count.index)}"
  destination_cidr_block = "${element(split(",", var.peer_vpc_cidr), count.index)}"

  count = "${length(split(",", var.peer_vpc_cidr))}"
}
```

### Expected Behavior
Routes created for the peer connections and remain stable

### Actual Behavior
This error takes a couple runs to show
1. First run of `terraform plan --out test.plan && terraform apply test.plan` it creates all the routes correctly 
2. Next run it removes all the routes created via a `count`
3. Next run it creates some / all the routes created via `count` and adds them back in to the route table
4. Same as run 2
5. Same as run 3
6. ... cycle

### References
Somewhat related to #6611 however that issue describes the problem happening across separate MODULES, where-as this happens all in the same module.

**Comment by paulcollinsiii** [comment]
v0.6.16 has this issue as well

**Comment by lesaux** [comment]
I am seeing the same thing. Reproducible with https://github.com/terraform-community-modules/tf_aws_vpc

**Comment by krisdigitx** [comment]
not sure if this is the same case, but using  https://github.com/terraform-community-modules/tf_aws_vpc

I can see from the ouput that it associated the subnet to route table, however on the AWS console its not associated.....

module.aws_vpc.aws_route_table_association.private.0: Creation complete
module.aws_vpc.aws_route_table_association.private.1: Creation complete

any ideas?

**Comment by catsby** [comment]
Hey Friends –

I dug into this and found what I believe is the issue: using routes defined in-line in `aws_route_table` as well as `aws_route` resources.  These are documented to be incompatible:

> NOTE on Route Tables and Routes: Terraform currently provides both a standalone Route resource and a Route Table resource with routes defined in-line. At this time you cannot use a Route Table with in-line routes in conjunction with any Route resources. Doing so will cause a conflict of rule settings and will overwrite rules.

- https://www.terraform.io/docs/providers/aws/r/route_table.html

I took the above example and moved the Nat Gateway route out:

```
  route {
    cidr_block = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.nat.id}"
  }
```

Into it's own route:

```
resource "aws_route" "nat" {
  route_table_id         = "${aws_route_table.private.id}"
  nat_gateway_id         = "${aws_nat_gateway.nat.id}"
  destination_cidr_block = "0.0.0.0/0"
}
```

And it worked as expected! 
In order to do this though, I had to manually remove the Nat route in the AWS Console. Because `route` is a computed value, removing the last one hits a bug in Terraform where it won't modify the Route Table and remove it :( 

Please let me know if you have any other questions!

**Comment by paulcollinsiii** [comment]
@catsby I'm updating my scripts now to test this but since this (and one other case dealing with security group rules I believe) have problems like this can this be added as a check to the parser? If this is known to be incompatible it would have saved me a LOT of trouble if there had been a warning, or ideally in this case and outright error, when trying to `plan`.

**Comment by paulcollinsiii** [comment]
Also just to confirm, yep. That was the issue. Thanks for catching that!

**Comment by catsby** [comment]
> Also just to confirm, yep. That was the issue. Thanks for catching that!

Awesome!  Thanks for confirming

> If this is known to be incompatible it would have saved me a LOT of trouble if there had been a warning, or ideally in this case and outright error, when trying to plan.

I'm sorry for the trouble here. Unfortunately at this time we don't have any kind of inter-resource validations available. Each resource is treated independently with no knowledge of other resources in the graph.
