### ISSUE TITLE
Duplicate AWS SG error causes LC to lose state of SG on next apply.

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform#6883]
### Terraform Version

0.6.16
### Affected Resource(s)
- aws_security_group
- aws_launch_configuration
### Error Output

[Gist](https://gist.github.com/dfoltin-bc/fbe56aa3ebbc7693366c7c83a572587d)
### Expected Behavior

On the third run terraform should have continued where the second run left off and replaced the security groups and launch configurations.
### Actual Behavior

I have a few AWS launch configurations and each has an associated security group. All LCs and SGs are create_before_destroy lifecycles. The first run was successfully applied to AWS. I changed the SG config to accidentally have every SG be the same name. This caused the next apply (second run) to error out as expected on duplicate SG names. However, after I fixed the SGs to have unique names and applied again for a third run, tf crashed, seemingly from something wonky happening to the state file after the second run. A `terraform refresh` fixes the issue and a fourth run runs.

**Comment by stack72** [comment]
Hi @ghost

My apologies this has happened and that we have taken a long time to get back to you on this. I just tried to look at the gist and it seems that the link is broken. Is this still an issue for you? If so, please can you share the config that is causing the problem

Apologies again for the time taken to get back to you here

Paul
