### ISSUE TITLE
docs: aws_opsworks_instance ebs_block_device errata

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#6885]
I very painfully discovered an issue with the docs on https://www.terraform.io/docs/providers/aws/r/opsworks_instance.html

`encrypted` is not a valid option for block device mappings in opsworks

this can be confirmed by looking up the docs for the opsworks ebs block device model in their various apis (.NET or java, for example)

attempting to use the flag results in an error (unsupported)

I believe it was copied from the aws_instance section, and thus just needs to be updated to remove the erroneous `encrypted` option.

**Comment by eedwardsdisco** [comment]
also for anyone that might discover this that ran into the same issue - a workaround is to create an encrypted ebs snapshot in the same region and then use that snapshot_id for the ebs_block_device in your aws_opsworks_instance

it can be a small, unformatted raw ebs volume snapshot, as long as it's encrypted, and it can be sized larger and formatted at launch

**Comment by stack72** [comment]
Hi @eedwardsdisco 

My apologies for the errors in the documentation here. I have just merged a PR that will fix this and I will get that to the website today

Thanks

Paul
