### ISSUE TITLE
RDS resources with passwords always get destroyed / rebuilt

### ISSUE THREAD

**Issue by dhobbs** [hashicorp/terraform#689]
If you run `terraform plan` immediately after a clean `terraform apply` with an RDS resource, the presence of a password field causes terraform to report the following:

`password:                  "" => "foobarfoobar" (forces new resource)`

I'm guessing because the interrogation it does of running resources doesn't bring the password back.

**Comment by bronislav** [comment]
I also have this issue. Actually this particular issue stops me from using terraform for production. I have switched to Ansible, but completely unhappy with it.

**Comment by phinze** [comment]
It's worth noting that the [RDS API's `ModifyDbInstance` operation](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html) supports updating the master password without replacing the whole DB Instance. Unfortunately it looks like `mitchellh/goamz` does [not yet support](https://github.com/mitchellh/goamz/blob/703cfb45985762869e465f37ed030ff01615ff1e/rds/rds.go) that API call.

I too like @jlund's proposal that we store a hash of the password in the state file to detect changes. Then if we can add Update support to the `aws_db_instance` resource, we also won't have to force DB instance replacement for a password update.

**Comment by chipi** [comment]
+1 for this to get somehow solved. Maybe worth looking into how Ansible deals with confidential information through a concept of a vault

**Comment by phinze** [comment]
Alright the fix for this was just merged and should come out with 0.3.7! :dancer: 

For now we are storing the password in plaintext in the state file and documenting that fact. Further discussion around the general topic sensitive values in the state file can be found over at #516 .

**Comment by ipmb** [comment]
:tada:

**Comment by alex-pw** [comment]
I see this is closed, but it seems like I am getting the same behavior.  

This is the only change I am noticing:
```
password:                          "<sensitive>" => "<sensitive>" (attribute changed)
```

Thanks for any help:

```
-/+ aws_db_instance.arbiter_rds_instance
    address:                           "arbiter-staging.cbblbocgollf.us-west-2.rds.amazonaws.com" => "<computed>"
    allocated_storage:                 "5" => "5"
    allow_major_version_upgrade:       "false" => "false"
    apply_immediately:                 "" => "<computed>"
    arn:                               "arn:aws:rds:us-west-2:488411906022:db:arbiter-staging" => "<computed>"
    auto_minor_version_upgrade:        "false" => "false"
    availability_zone:                 "us-west-2a" => "<computed>"
    backup_retention_period:           "35" => "35"
    backup_window:                     "15:16-15:46" => "15:16-15:46"
    character_set_name:                "" => "<computed>"
    copy_tags_to_snapshot:             "false" => "false"
    db_subnet_group_name:              "arbiter-staging-subnetgroup" => "arbiter-staging-subnetgroup"
    endpoint:                          "arbiter-staging.cbblbocgollf.us-west-2.rds.amazonaws.com:5432" => "<computed>"
    engine:                            "postgres" => "postgres"
    engine_version:                    "9.5.4" => "9.5.4"
    identifier:                        "arbiter-staging" => "arbiter-staging"
    instance_class:                    "db.t2.large" => "db.t2.large"
    kms_key_id:                        "arn:aws:kms:us-west-2:488411906022:key/6d72361d-7667-48bb-9e7c-56ac44ddf23b" => "6d72361d-7667-48bb-9e7c-56ac44ddf23b" (forces new resource)
    license_model:                     "postgresql-license" => "<computed>"
    maintenance_window:                "mon:16:16-mon:16:46" => "mon:16:16-mon:16:46"
    monitoring_interval:               "0" => "0"
    monitoring_role_arn:               "" => "<computed>"
    multi_az:                          "true" => "true"
    name:                              "" => "<computed>"
    option_group_name:                 "default:postgres-9-5" => "<computed>"
    parameter_group_name:              "default.postgres9.5" => "default.postgres9.5"
    password:                          "<sensitive>" => "<sensitive>" (attribute changed)
    port:                              "5432" => "<computed>"
    publicly_accessible:               "false" => "false"
    replicas.#:                        "1" => "<computed>"
    skip_final_snapshot:               "true" => "true"
    status:                            "available" => "<computed>"
    storage_encrypted:                 "true" => "true"
    storage_type:                      "gp2" => "gp2"
    username:                          "arbiter" => "arbiter"
    vpc_security_group_ids.#:          "2" => "2"
    vpc_security_group_ids.2916709402: "sg-9bf932e2" => "sg-9bf932e2"
    vpc_security_group_ids.757519782:  "sg-431dd63a" => "sg-431dd63a"
```

**Comment by djandruczyk** [comment]
This issue has re-appeared with TF 0.9.4
A new instance that was created with 0.9.4, is repeatedly destroyed.
terraform plan shows:
-/+ aws_db_instance.my_dev_db (tainted)
...
    password:                          "<sensitive>" => "<sensitive>" (attribute changed)
..

**Comment by hsanjuan** [comment]
Same in 0.9.5

**Comment by slajax** [comment]
@djandruczyk I'm also seeing this. Have you found a work around?
