### ISSUE TITLE
Removing Elastic Beanstalk Environment Variables

### ISSUE THREAD

**Issue by tecnobrat** [hashicorp/terraform#6890]
On terraform 0.6.16

If I remove a `setting` with the namespace of `aws:elasticbeanstalk:application:environment`, terraform says its removed, however the AWS console still has that setting, as well as the API still returns a value for that setting.

Also, if I add a environment variable manually in the AWS console and then re-run a plan, terraform doesn't seem to see that value and try to remove it.

It looks like when terraform refreshes its state from AWS, it doesn't properly catalog `aws:elasticbeanstalk:application:environment` keys, certainly not ensuring that there are not extra or missing keys.

**Comment by parabolic** [comment]
+1 I just ran into this problem, can we see to it that it's fixed.
```
terraform --version
Terraform v0.6.16
```
Thanks.
