### ISSUE TITLE
"aws_elb" "cross_zone_load_balancing" set default to true

### ISSUE THREAD

**Issue by danbf** [hashicorp/terraform#6891]
Can we set `Default,: true,` in https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elb.go#L45-L48 ?

This is the default now for all ELB's created via the AWS console.
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_elb

### Expected Behavior
elb should be created with cross_zone_load_balancing enabled

### Actual Behavior
elb is created with cross_zone_load_balancing disabled

### Steps to Reproduce
1. `terraform apply` of the example in https://www.terraform.io/docs/providers/aws/r/elb.html without the `cross_zone_load_balancing = true` line

```
# Create a new load balancer
resource "aws_elb" "bar" {
  name = "foobar-terraform-elb"
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]

  access_logs {
    bucket = "foo"
    bucket_prefix = "bar"
    interval = 60
  }

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 443
    lb_protocol = "https"
    ssl_certificate_id = "arn:aws:iam::123456789012:server-certificate/certName"
  }

  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 2
    timeout = 3
    target = "HTTP:8000/"
    interval = 30
  }

  instances = ["${aws_instance.foo.id}"]
  idle_timeout = 400
  connection_draining = true
  connection_draining_timeout = 400

  tags {
    Name = "foobar-terraform-elb"
  }
}
```

**Comment by stack72** [comment]
Hi @danbf 

just a FYI, we have just merged a PR that does exactly this. It will be released as part of TF 0.7 :)

Paul

**Comment by danbf** [comment]
@stack72 awesome.  thanks for getting this done.

**Comment by danbf** [comment]
![giphy-1](https://cloud.githubusercontent.com/assets/5041307/20449032/fc23cf52-adb4-11e6-98b5-805f4907ebe7.gif)
