### ISSUE TITLE
Possibility to concate in array ()

### ISSUE THREAD

**Issue by VAdamec** [hashicorp/terraform#6896]
Is there any possibility to do this ? Use case is F5 bigip_ltm_pool members (terraform-provider-bigip), you need to add their names/IP with port in array.

### 
```hcl
app_nodes = "10.0.0.2,10.0.03"
app_port = "8080"

nodes = ["${split(",", var.app_nodes)}:${var.app_port}"]
or this:
nodes = ["formatlist('%s:%s', ${split(',', var.app_nodes)}, var.app_port)"]
```

### Needed result:
["10.0.0.2:8080","10.0.0.3:8080"]

* Terraform v0.7.0-dev (283e3ae6b5a9ba17092ca416ba412018f139e7e8)

**Comment by VAdamec** [comment]
Tried this:

```
nodes = ["formatlist('%s:%s', vsphere_virtual_machine.app_nodes.*.network_interface.ipv4_address, app_port)"]
```
and result is not accepted by bigip balancer (pool is empty)

```
module.vsphere-app.bigip_ltm_pool.web_pool: Modifying...
  monitors.2541227442: "" => "http"
  monitors.576276785:  "/Common/http" => ""
  nodes.#:             "2" => "1"
  nodes.1295358086:    "" => "formatlist('%s:%s', vsphere_virtual_machine.app_nodes.*.network_interface.ipv4_address, app_port)"
  nodes.1703785393:    "10.4.21.142:8080" => ""
  nodes.3810115871:    "10.4.21.141:8080" => ""
```

**Comment by aburnett** [comment]
This is how I've managed it on my projects

```
resource "bigip_ltm_pool" "pool" {
  ...
  nodes = ["${formatlist("%s:%d", bigip_ltm_node.node.*.name, var.app_port)}"]
}

resource "bigip_ltm_node" "node" {
  count = "${length(split(",", var.app_nodes))}"
  name = "${format("node%02d", count.index+1)}"
  address = "${element(split(",", var.app_nodes), count.index)}"
}
```

**Comment by jen20** [comment]
Hi @VAdamec! I believe @aburnett's answer should be what you need - you should also be able to include that in a variable as of Terraform 0.7rc1! If you have further questions please feel free to reopen this issue.

**Comment by VAdamec** [comment]
Looks ok, thanks a lot. Maybe some extensive examples should speed up Terraform usage and spread between IT community. I'll try to prepare it and share it on github.
