### ISSUE TITLE
0.7 release schedule

### ISSUE THREAD

**Issue by BillBrady** [hashicorp/terraform#6903]
Greetings!

The 0.7 release addresses an issue (https://github.com/hashicorp/terraform/issues/2143 dot in tagname) that is in the critical path for us.  We can work around it for now, but it would be very helpful if we had a date that we could point to to stop using the workaround.  Could you kindly share the ETA for 0.7 to be released?  

Thanks much!  
Bill

**Comment by jen20** [comment]
Hi @BillBrady! I'm about to cut rc1 of Terraform 0.7 now, so you can expect to see it available soon.

**Comment by BillBrady** [comment]
That's excellent news!  Thanks much!

**Comment by jen20** [comment]
Hi @BillBrady! You can find the RC at https://releases.hashicorp.com/terraform/! I'll go ahead and close this issue - the exact release date of the final version of 0.7 depends to an extent on what users find in the RC series, but we do not expect it to be long from here out.

**Comment by BillBrady** [comment]
So great!  Thanks much!!

**Comment by ocsi01** [comment]
Is there any update on the state of the final release?

**Comment by dfoltin-bc** [comment]
@ocsi01 rc-2 has been out for a bit, and I've been told by Hashicorp people that ga could be something like next week.

**Comment by apparentlymart** [comment]
For the moment I think the best guide is [the list of issues blocking the release](https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-0.7).
