### ISSUE TITLE
 Terraform tries to delete a disk after it deletes a compute with the disk

### ISSUE THREAD

**Issue by noralife** [hashicorp/terraform#6908]
Hi there,

I've encountered an error when Terraform destroys a disk which Terraform creates and attaches to a new compute. This happens because when Terraform destroys the compute with the disk and then Terraform tries to delete the disk which no longer exists.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- google_compute_instance
- google_compute_disk
### Terraform Configuration Files

``` hcl
provider "google" {
  credentials = "${file("credentials.json")}"
  project     = "****"
  region      = "asia-east1"
}

resource "google_compute_disk" "extdisk" {
  name  = "terraform-ext"
  type  = "pd-ssd"
  zone  = "asia-east1-a"
  size  = 20
}

resource "google_compute_instance" "test-server" {
  name         = "terraform"
  machine_type = "n1-standard-1"
  zone         = "asia-east1-a"
  disk {
    image = "ubuntu-1404-trusty-v20160516"
  }
  disk {
    disk = "${google_compute_disk.extdisk.name}"
    device_name = "extdisk"
    auto_delete = false
  }
  network_interface {
    network = "default"
  }
  metadata_startup_script = "${file("boot.sh")}"
}
```
### Debug Output

https://gist.github.com/noralife/c24255963abb0b3d6825815f977311c8
### Expected Behavior

> Apply complete! Resources: 0 added, 0 changed, 2 destroyed.
### Actual Behavior

> Error applying plan:
> 
> 1 error(s) occurred:
> - google_compute_disk.extdisk: Error deleting disk: googleapi: Error 404: The resource 'projects/***/zones/asia-east1-a/disks/terraform-ext' was not found, notFound
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy -force`
### Workaround

If `auto_delete` is false, this error is avoidable.

``` hcl
  disk {
    disk = "${google_compute_disk.extdisk.name}"
    device_name = "extdisk"
    auto_delete = false // add this line
  }
```
### Important Factoids

None
### References

None

**Comment by sl1pm4t** [comment]
Pretty sure this is fixed by f075b0214da36bd1cf728f1a295a767169341c56 that is part of 0.7
