### ISSUE TITLE
when `aws_instance` `security_groups` is not a list, terraform crashes

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#691]
It seems that if `aws_instance` is provided a string (not a list) for `security_groups`, [terraform crashes][1] on `plan` or `apply`.

Example:

    resource "aws_instance" "coreos" {
        ami = "${lookup(var.coreos-ami, var.region)}"
        instance_type = "t2.micro"
        count = "${var.cluster-size}"
        subnet_id = "${element(aws_subnet.core.*.id, count.index)}"
        key_name = "phil"
        associate_public_ip_address = true
        user_data = "${file(\"cloud-config\")}"
        security_groups = "${aws_security_group.ssh.id}"
    
        tags {
            Name = "terraform test"
        }
    }

if that's changed to

        security_groups = ["${aws_security_group.ssh.id}"]

then there is no crash.

  [1]: https://gist.github.com/bitglue/b0930d890d6001e87f39

**Comment by mitchellh** [comment]
I'm not sure when this was fixed, but it was fixed in 0.3.6:

```
terraform master → terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 'aws_instance.coreos' error: security_groups: should be a list
```

**Comment by yahyapo** [comment]
Yes, it is fixed. Thanks!

**Comment by ceh** [comment]
@mitchellh It was never fixed.

I can reproduce this on both Terraform v0.3.6 and Terraform v0.3.7.dev (a909ce88ab45eea3771fa4c3b3cbac4670f3aac1) by running `terraform plan` on

```
provider "aws" {
    access_key = "a"
    secret_key = "b"
    region = "us-east-1"
}

resource "aws_instance" "foo" {
    ami = "ami-foo"
    instance_type = "t2.micro"
    security_groups = "${aws_security_group.foo.name}"
}

resource "aws_security_group" "foo" {
    name = "foobar"
    description = "foobar"
}
```

Reopen the issue?

**Comment by mitchellh** [comment]
@ceh Sure, opening it. It was fixed for the repro case in the root comment, but this is new. :)

**Comment by mitchellh** [comment]
Fixed by #773

**Comment by cheburakshu** [comment]
This seems to be happening still.
I am on Terrform v0.9.2

```
module "launch_configuration" {
  source = "./modules/aws_launch_configuration"
  name = "${module.cluster.asg_name}"
  image_id = "${var.images[var.region]}"
  iam_instance_profile = "${module.cluster.id}"
  instance_type = "${var.size["minion"]}"
  key_name = "${module.key_pair.key_name}"
# There is a bug. This is not allowing me to send a list.
  security_groups = ["${module.minion_security_group.id}"]
  associate_public_ip_address = "${var.associate_public_ip_address}"
  spot_price = "${var.spot_price}"
  user_data = ""
}
```
Module:
```
variable "name" {}
variable "image_id" {}
variable "iam_instance_profile" {}
variable "instance_type" {}
variable "key_name" {}
variable "security_groups" {type="list"}
variable "associate_public_ip_address" {}
variable "spot_price" {}
variable "user_data" {}

resource "aws_launch_configuration" "aws_launch_configuration" {
  name = "${var.name}"
  image_id = "${var.image_id}"
  iam_instance_profile = "${var.iam_instance_profile}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key_name}"
  security_groups = "${var.security_groups}"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  spot_price = "${var.spot_price}"
  user_data = "${var.user_data}"
}
```
Output:
```
1 error(s) occurred:

* module.launch_configuration.aws_launch_configuration.aws_launch_configuration: security_groups: should be a list

```

Change security groups as a list, explicitly in module:

```
variable "name" {}
variable "image_id" {}
variable "iam_instance_profile" {}
variable "instance_type" {}
variable "key_name" {}
variable "security_groups" {type="list"}
variable "associate_public_ip_address" {}
variable "spot_price" {}
variable "user_data" {}

resource "aws_launch_configuration" "aws_launch_configuration" {
  name = "${var.name}"
  image_id = "${var.image_id}"
  iam_instance_profile = "${var.iam_instance_profile}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key_name}"
# Change as explicit list
  security_groups = ["${var.security_groups}"]
  associate_public_ip_address = "${var.associate_public_ip_address}"
  spot_price = "${var.spot_price}"
  user_data = "${var.user_data}"
}
```
And it works!
```
Get: file:///home/sud/cloud/projects/terrakube/modules/aws_launch_configuration
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

```

**Comment by niralkk** [comment]
> thwarted



> Googling attempts and I thought the glob syntax was the only way to make a list until I performed an exhaustive read of the documentation and found the solution by coincidence.

Hi @bitglue (Phil) would you mind sharing your finding by that example. I'm in the same basket.

**Comment by bitglue** [comment]
I don't think I have any configs left still using `security_groups` -- they all use `vpc_security_group_ids` now. I don't remember experiencing any crashes in a long time, so I assume it was fixed some time in the past five years.
