### ISSUE TITLE
`aws_instance` `security_groups` ignores changes when using a security group `id` and not `name`

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#692]
Related: #194, #595.

If an instance is created with some security group by ID, everything is peachy:

    resource "aws_instance" "coreos" {
        ami = "${lookup(var.coreos-ami, var.region)}"
        instance_type = "t2.micro"
        count = "${var.cluster-size}"
        subnet_id = "${element(aws_subnet.core.*.id, count.index)}"
        key_name = "phil"
        associate_public_ip_address = true
        user_data = "${file(\"cloud-config\")}"
        security_groups = ["${aws_security_group.http.id}"]
    
        tags {
            Name = "terraform test"
        }
    }

Through AWS web console I can confirm that the instance was indeed associated with the `http` security group. If I then try to change the security group to something else:

        security_groups = ["${aws_security_group.ssh.id}"]

Then `terraform plan` will show no changes to be made, even though the instances are still using the `http` security group and I've changed it to `ssh`.

Not directly the issue here, but perhaps a relevant hint: If I instead try to change the security group and reference by name:

        security_groups = ["${aws_security_group.ssh.name}"]

`terraform plan` will realize that changes need to be made, but I run into #194:

```
-/+ aws_instance.coreos.2
    ami:                         "ami-705d3d18" => "ami-705d3d18"
    associate_public_ip_address: "true" => "1"
    availability_zone:           "us-east-1d" => "<computed>"
    instance_type:               "t2.micro" => "t2.micro"
    key_name:                    "phil" => "phil"
    private_dns:                 "ip-10-2-3-251.ec2.internal" => "<computed>"
    private_ip:                  "10.2.3.251" => "<computed>"
    public_dns:                  "" => "<computed>"
    security_groups.#:           "1" => "1" (forces new resource)
    security_groups.0:           "sg-10c13c74" => "http" (forces new resource)
    subnet_id:                   "subnet-9563a3be" => "subnet-9563a3be"
    tags.Name:                   "terraform test" => "terraform test"
    tenancy:                     "default" => "<computed>"
```

**Comment by catsby** [comment]
Hey @bitglue – Thanks for reporting this. 
As of `master` on dc4abb4 , I can no longer reproduce this. Changing to `ssh.id` for me worked as expected, so I'm closing this for now. Unfortunately no solution to 194 for you :frowning: , yet

Thanks again, let me know if you need anything else or feel this is still an issue.

**Comment by bitglue** [comment]
@catsby  If the solution is to always use `id` and never `names`, shouldn't [the documentation](https://terraform.io/docs/providers/aws/r/instance.html#security_groups) say that, or better, raise an error if someone tries to use a security group name when they should be using an ID?

**Comment by catsby** [comment]
Hey @bitglue , I apologize for not being clearer. I'm not suggesting that as a solution, both should work fine.

From the original post: 

> Then terraform plan will show no changes to be made, even though the instances are still using the http security group and I've changed it to ssh.

I'm saying that as of `master` (dc4abb4) I can no longer reproduce this. Changing from `*.http.id` to `*.ssh.id` worked as expected (`plan` showed a change). Same with changing to `ssh.name`. 

That was my interpretation of what this issue represented, and I couldn't reproduce that. If I've made an error please let me know.
