### ISSUE TITLE
aws_cloudwatch_event_target - Getting around ResourceNotFoundException

### ISSUE THREAD

**Issue by sm-azure** [hashicorp/terraform#6928]
An AWS lambda function was not being updated on apply/plan. So I tainted the lambda and ran apply. This led to the following error. 

> Error applying plan:
> 1 error(s) occurred:
> 
> * aws_cloudwatch_event_target.backup-cleanup_deregister: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
> 
> Please include the following information in your report:
> 
>     Terraform Version: 0.6.14
>     Resource ID: aws_cloudwatch_event_target.backup-cleanup_deregister
>     Mismatch reason: attribute mismatch: arn
>     Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:eu-west-
> 1:XXXXXXXX:function:OPS-Deregister-AMI", New:"${var.lambda_deregister_arn}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:
> 0x0}}, Destroy:false, DestroyTainted:false}
>     Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
> 

And from then I keep getting the `ResourceNotFoundException` for every command. I have tried `terraform destroy -refresh=false` but to no avail. Is there a way to get around this problem? I am sure, this is going to be a common occurrence in our daily operations. Thanks.

**Comment by sm-azure** [comment]
Could fix the issue by manually updating the statefile (removing the resource responsible for the `ResourceNotFoundException` exception) and updating the version. However, I am sure this is a poor solution.

**Comment by radeksimko** [comment]
Hi @sm-azure 
see https://github.com/hashicorp/terraform/pull/6924 which is fixing this bug.

**Comment by radeksimko** [comment]
Actually I was wrong, #6924 is only fixing `aws_lambda_function`, but not `aws_cloudwatch_event_target`.
