### ISSUE TITLE
Terraform destroy  destroys all the resources.

### ISSUE THREAD

**Issue by ankur2807** [hashicorp/terraform#6943]
Hi there,
I created a ec2 instance and ami of that ec2 instance with terraform template. But when I am applying terraform destroy command it is deleting both instance and the ami created with this instane. I want to delete only instance and want to keep the ami as it is. Please help me in this. 

Regards,
Ankur Goyal

**Comment by Mongey** [comment]
@ankur2807 can you supply the terraform code used to reproduce the problem?

**Comment by ankur2807** [comment]
this is my  ec2 instance creation code.
variable "access_key"{
	type="string"
	default=""
}

variable "secret_key"{
	type="string"
	default=""
}

variable "region"{
	type="string"
	default=""
}

variable "key_name"{
	type="string"
	default="AG"
}

variable "public_key_path"{
	type="string"
	default="AG.pem"
}

provider "aws"{
	access_key = "${var.access_key}"
	secret_key = "${var.secret_key}"
	region = "${var.region}"
}

resource "aws_instance" "webserver"{
	ami = "ami-b8c5bcd8"
	instance_type="t2.micro"
	security_groups = ["default"]
	key_name="AG"
	user_data= "${file("userpermissions.txt")}"
	connection{
		type="winrm"
		timeout="10m"
		user="terraform"
		password="Password01"
		
	}
	
	provisioner "file"{
		source="installIIS.ps1"
		destination = "C:\\IISinstall.ps1"
	}

	provisioner "remote-exec"{
		inline = [
			"sleep 30",
			"powershell C:\\IISinstall.ps1"
		]
	}

	provisioner "file"{
		source="index.html"
		destination = "C:\\inetpub\\wwwroot\\index.html"
	}
}

**Comment by ankur2807** [comment]
This code is for ami creation which is in different folder. 
variable "access_key"{
	type="string"
	default=""
}

variable "secret_key"{
	type="string"
	default=""
}

variable "region"{
	type="string"
	default=""
}

variable "key_name"{
	type="string"
	default=""
}

variable "public_key_path"{
	type="string"
	default=""
}
provider "aws"{
	access_key = "${var.access_key}"
	secret_key = "${var.secret_key}"
	region = "${var.region}"
}
resource "aws_ami_from_instance" "webserver" {
    name = "webserver"
	source_instance_id =" "
	}

**Comment by catsby** [comment]
Hello – 

Terraform is designed to manage your infrastructure as defined in your configuration file, so it makes sense that `destroy` would remove all the resources specified. If you need to preserve some of the resources, you could try removing the `aws_ami_from_instance` from both the Statefile and the configuration file. 

I do not know your use case, but if this is a common task you'd like to perform to create AMIs, you may find Packer to be a more suitable tool:

- https://www.packer.io

In the future please utilize other community resources for this kind of request, as our issue tracker is meant to help us track and fix issues as well as develop features. You can find some community links like IRC, or the mailing list, here:

- https://www.terraform.io/community.html
