### ISSUE TITLE
Missing healthcheck support in fastly provider

### ISSUE THREAD

**Issue by tfheen** [hashicorp/terraform#6944]
### Terraform Version

`Terraform v0.6.16`
### Affected Resource(s)
- fastly_service_v1
### Terraform Configuration Files

``` hcl

resource "fastly_service_v1" "test" {
  name = "test"

  domain {
    name = "example.org"
  }

  backend {
    name = "test"
    address = "backend.example.org"
  }

  healtcheck {
        name = "main"
        method = "GET"
        path = "/.heartbeat"
  }
}
```
### Debug Output

N/A
### Expected Behavior

A service with a healthcheck should have been created.
### Actual Behavior

```
> ./terraform plan test
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * fastly_service_v1.test: : invalid or unknown key: healtcheck
```
### Steps to Reproduce
1. `terraform plan`

**Comment by acme** [comment]
This would be fabulous. That should probably be called `healthcheck` not `healtcheck`.

**Comment by blinohod** [comment]
I've tried to add minimal healthcheck support:
https://github.com/blinohod/terraform/commit/cbdc40d64b74b917b69874979139d745619099d5

Works for me but need extra work before submitting pull request.

**Comment by udryan10** [comment]
I do not currently see a way to associate a healthcheck with a backend. Am I correct that this is not yet implemented, or have I overlooked something?

**Comment by Kelrak** [comment]
@udryan10 I noticed the same.
@blinohod Are you still working on this? Looks like your changes do solve our issues

**Comment by blinohod** [comment]
@Kelrak Currently I'm not working on this. Possibly will return to this in couple weeks if not yet fixed in upstream code, seems it already contains most part of required changes.

**Comment by udryan10** [comment]
hey @blinohod, my team would be happy to pick up the remainder of this implementation from you if you don't mind.

**Comment by blinohod** [comment]
@udryan10 : if you can hand over remainder I would be just happy 👍
