### ISSUE TITLE
Missing terraform output on first apply

### ISSUE THREAD

**Issue by Bowbaq** [hashicorp/terraform#6945]
### Terraform Version
`Terraform v0.7.0-dev (630f9011103a187c8c4455d40fa82493267fad61+CHANGES)`

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_public_ip
- core

### Terraform Configuration Files + Output
https://gist.github.com/Bowbaq/e4c31232301c0872f0b86178a949a270

### Expected Behavior
The `inventory` output should be present after the first apply. If that's not possible, then an error should be surfaced.

### Actual Behavior
The `inventory` output is not present but `apply` succeeded. I believe this is the result of two separate bugs:
- the `ip_address` attribute of `azurerm_public_ip` is sometimes not present when using a `dynamic` allocation type
- missing variables in the output causes the interpolation to silently fail

### Steps to Reproduce
See [gist](https://gist.github.com/Bowbaq/e4c31232301c0872f0b86178a949a270)

### Important Factoids
I'm running a slightly modded version of `master`, but no changes to `core` or the `azurerm_public_ip` resource.

**Comment by jrhoward** [comment]
I am having the same issue with Terraform v0.6.16. Running apply a second time works to get the ip_address

**Comment by stack72** [comment]
Hi @Bowbaq 

this is another instance of https://github.com/hashicorp/terraform/issues/6634

I have explained there that new changes in the Azure SDK will allow us to fix this. I am waiting on a PR to be merged for that

I am going to close this request and track the changes / fix in that other issue (only as i answered there first and my WIP is linked to that code)

Thanks for raising the issue

Paul
