### ISSUE TITLE
OpenStack Error creating Floating IP

### ISSUE THREAD

**Issue by vmorris** [hashicorp/terraform#6950]
### Terraform Version

Terraform v0.6.16-dev (14be5a0f86dd986947d9449c6b2c1222406b1a59)
### Affected Resource(s)

Please list the resources as a list, for example:
- openstack_compute_floatingip_v2.floating_ip_vm1
### Terraform Configuration Files

https://gist.github.com/vmorris/39a38f8b76ea569cb51f68f781de2c43
### Debug Output

https://gist.github.com/vmorris/470be7a7ae27b23c7915d22b9aefcee7
### Expected Behavior

Terraform ought to use an available floating IP rather than attempt to provision a new one.
### Actual Behavior

Terraform attempts to create a floating IP in the pool, even though there are many unassociated FIPs already created.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create all floating IPs in a pool but leave them unassociated.
2. `terraform apply` on a new floating IP
### Important Factoids

Openstack Kilo

I suspect this is a perfectly fine approach, but it appears that the underlying issue is really that TF is not actually deleting floating IPs that it creates; leaving them created but unassociated. A better approach (and one that follows OpenStack behaviour) would be to use the first unassociated FIP before trying to create a new one.

**Comment by jtopjian** [comment]
@vmorris This is a good point. Perhaps adding an argument like `allocate`, that when set to `false` will attempt to use an existing allocated IP and error out if none are available.

In the meantime, as an aside, it's possible to specify an available IP by doing:

```hcl
openstack_compute_floatingip_v2 {
  address = "existing floating ip"
}
```

**Comment by vmorris** [comment]
@jtopjian I would prefer to see Terraform clean up after itself. If it allocated the FIP, it should delete it upon destroy, right?

Having an allocate false option as the default would mirror openstack behaviour, if followed up by an allocate true attempt if none are readily available.

I own the cloud, so I have no qualms about manually deleting allocated FIPs, I just wasn't expecting to have to do it!

**Comment by jtopjian** [comment]
@vmorris Oops - actually, the example I gave was incorrect and I've since deleted it.

What I meant was that it's possible to specify a pre-allocated floating IP within the instance:

```hcl
openstack_compute_instance_v2 "foo" {
  ...
  floating_ip = "1.2.3.4"
}
```

No idea where my head was.

**Comment by jtopjian** [comment]
@vmorris I just re-read this issue and have some questions / comments:

> I suspect this is a perfectly fine approach, but it appears that the underlying issue is really that TF is not actually deleting floating IPs that it creates; leaving them created but unassociated.

and

> If it allocated the FIP, it should delete it upon destroy, right?

This is the current behavior. Are you seeing otherwise? 

> Having an allocate false option as the default would mirror openstack behaviour, if followed up by an allocate true attempt if none are readily available.

By default, Nova requires both an instance ID and floating IP, even if the user has a floating IP allocated but not associated:

```
$ nova floating-ip-associate 1ced8cb9-d336-4c6f-91a3-9ebf375b881a
usage: nova floating-ip-associate [--fixed-address <fixed_address>]
                                  <server> <address>
error: too few arguments
Try 'nova help floating-ip-associate' for more information.
```

I'm curious about how you're seeing floating IPs handled in your cloud. Is the behavior different?

**Comment by theratboss** [comment]
I think the best approach would be to check if there is a not associated IP in the pool, if there is at least one, pick the first and associate it. If there are none then try to create a new one.
Otherwise for not destroyed stacks where the machines have been terminated even if the IP is de-associated it will not be re-used by terraform.

**Comment by jtopjian** [comment]
I've been thinking about that scenario and I'm not sure it's a good idea.

It's best when Terraform controls the entire lifecycle of a resource. For a Floating IP, this would include both allocation and association. If the Floating IP has already been allocated, that means action on the resource has been done out of band of Terraform. This always complicates things. In addition, terraform needs to be mindful of to only disassociate the IP upon during the destroy phase - not disassociate and deallocate it.

Given the above, I'm not totally against this kind of scenario. I'm curious about what use-cases this would be useful - more to the point: what kinds of environments are users working in where they need to allocate an IP out of band of Terraform? In addition, if someone wanted to give a first run at adding this logic into the Floating IP resource, I would be more than happy to review it and test it out.

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
