### ISSUE TITLE
Terraform thinks S3 policy has changed when it hasn't.

### ISSUE THREAD

**Issue by fields** [hashicorp/terraform#6952]
Even after terraform apply, terraform plan still sees policy changes in the aws_s3_bucket resource.

### Terraform Version
0.6.15

### Affected Resource(s)
- aws_s3_bucket

### Expected Behavior
terraform plan should recognize that the policy hasn't changed.

### Actual Behavior
terraform plan sees changes in the policy.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

https://gist.github.com/fields/1af00ad7608246035e93e7813bd30571

**Comment by catsby** [comment]
Hey @fields – looks like you're missing the `Sid` attribute:

What AWS is returning:

```
{
  "Statement": [
    {
      "Action": "s3:PutObject",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::xxxxx:root"
      },
      "Resource": "arn:aws:s3:::bucketname/*",
      "Sid": ""
    }
  ],
  "Version": "2012-10-17"
}
```

What Terraform is trying to change it back to:

```
{
  "Statement": [
    {
      "Action": "s3:PutObject",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam:xxxx:root"
      },
      "Resource": "arn:aws:s3:::bucketname/*"
    }
  ],
  "Version": "2012-10-17"
}
```

Can you try adding `"Sid": ""` ?

**Comment by catsby** [comment]
Going to close this for now, the issue seems to be in the config file and not Terraform itself. Please comment/reopen if you feel otherwise.

Thanks!
