### ISSUE TITLE
Dynamic values in integration tests

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#6959]
Hi all

We are getting hashed values back from different data structures in the TF files during integration testing.  How can we programicatically calculate the has value?

For instance:
```
DESTROY: vsphere_virtual_machine.foo

STATE:
vsphere_virtual_machine.foo:
  ID = terraform-test
  cluster = Engpipeline-cluster
  datacenter = Engpipeline Datacenter
  disk.# = 1
  disk.2433685196.bootable = false
  disk.2433685196.controller_type = scsi
  disk.2433685196.datastore = BEL-SDRS-VMAX1789-POOL01
  disk.2433685196.iops = 0
  disk.2433685196.keep_on_remove = false
  disk.2433685196.key = 0
  disk.2433685196.name =
  disk.2433685196.size = 0
  disk.2433685196.template = centos-clove-tpl
  disk.2433685196.type = eager_zeroed
  disk.2433685196.uuid =
  disk.2433685196.vmdk =
  domain = vsphere.local
  linked_clone = false
  memory = 1024
  memory_reservation = 0
  name = terraform-test
  network_interface.# = 1
  network_interface.0.adapter_type =
  network_interface.0.ip_address =
  network_interface.0.ipv4_address = 10.192.71.157
  network_interface.0.ipv4_gateway = 10.192.71.1
  network_interface.0.ipv4_prefix_length = 24
  network_interface.0.ipv6_address =
  network_interface.0.ipv6_gateway =
  network_interface.0.ipv6_prefix_length = 0
  network_interface.0.label = VM-vlan409
  network_interface.0.subnet_mask =
  skip_customization = false
  time_zone = Etc/UTC
  use_sdrs = true
  vcpu = 2
```
Is returned after a test.  How can we calculate the hash that is coming back on the disks?  For the example above ` disk.2433685196.datastore` is being returned.  We need to calc that number because depending on the testers environment the value may change.

**Comment by chrislovecnm** [comment]
@stack72 @jen20 @catsby any ideas on this guys?

**Comment by apparentlymart** [comment]
The hash is derived from the data, so there is a chicken-and-egg problem preventing you from calculating the hash in order to look up the data to calculate the hash.

I think the only meaningful operation you can do on a set like this is to iterate over all of its members, ignoring the hash entirely and considering only the data.

**Comment by thetuxkeeper** [comment]
IMO the best would be if there was a way to get the name vmware assigns to the device as return value when we create it.
Something like that:
```
for(index = 0; index < len(devices); index++) {
    devices[index]["name"] = createDevice(devices[index])
}
```
I haven't seen something like that in govmomi (or vmware api), though there is a way to get the device name.
Perhaps you can create one device after another and look which one was added and save the vmware-internal name as ID for all following operations in TF.

**Comment by chrislovecnm** [comment]
@thetuxkeeper are those values from vsphere, or does TF calc them?

**Comment by chrislovecnm** [comment]
So I am in the guts of `Attributes`  and `Resources`.  How do one loop through all `disk.*` values?  I would have thought `disk` was a map ... but NOPE

**Comment by jen20** [comment]
@chrislovecnm The hash is specified by SetFunc in the schema - you can verify in the test that the hash is correct for the data by recalculating it - but as @apparentlymart says the only meaningful thing you can do here is to range over the entire set as without the data you can't compute the hash! I'll close this for now, but feel free to reopen if you have further questions on this.
