### ISSUE TITLE
Concatenation of same string for defined number of times

### ISSUE THREAD

**Issue by chiranjitdatta** [hashicorp/terraform#6962]
I have a string like "/data,/log". Now I want to make variable in terraform with appending this string number of time as per my defined count.
Like if my count is 2
then the value of that variable would be "/data,/log,/data,/log" and like so.
Now how to do that in terraform?
In Join itself, i can't mention the number of times I want to join this not even in concat.

**Comment by catsby** [comment]
Hello –

Questions like this are better suited for our mailing list, or being asked directly to the community. Our issue tracker is meant to help us track and fix issues as well as develop features. You can find some community links like IRC, or the mailing list, here:

- https://www.terraform.io/community.html

**Comment by chiranjitdatta** [comment]
Thanks catsby for the suggestion.
I have posted the same query in the Mailing List with the same subject.
