### ISSUE TITLE
reference modules: config: unknown module referenced

### ISSUE THREAD

**Issue by xueshanf** [hashicorp/terraform#697]
I am trying to make module references between two subfolders to work, but could not get it to work. I might have missed something really simple.

There is simplified setup:

    %terraform get
    Get: file:///Users/..../projects/vpc
    Get: file:///Users/..../projects/etcd

Under projects (root level), main.cf

     module "vpc" {
       source = "./vpc"
    }
    module "etcd" {
       source = "./etcd"
    }

Subfolder ./vpc/subnet-etcd.tf, in addition to an empty main.cf:

    resource "aws_subnet" "docker-etcd-a" {
        vpc_id = ....
        cidr_block = ...
    }
    output "docker_etcd_a" {
      value = "${aws_subnet.docker-etcd-a.id}"
    }

Subfolder ./etcd/etcd-a-01.tf

    resource "aws_instance" "etcd-a-01" {
        ami = ...
        instance_type = ..
        subnet_id = "${module.vpc.docker_etcd_a}"
    }

%terraform plan --module-depth=-1

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * module etcd.root: 1 error(s) occurred:

* resource 'aws_instance.etcd-a-01' config: unknown module referenced: vpc

Any ideas what's wrong with the setup? Thanks!

**Comment by mitchellh** [comment]
Hi @xueshanf! This looks to be working as intended: you can only reference modules that are defined within your own module scope. It looks like the `etcd` module is trying to access the `vpc` module which was defined in the `root` module. This can't happen. You'll have to pass in the VPC ID as a parameter to the module. HTH!

**Comment by xueshanf** [comment]
Got it. Thanks. I used a script to generate tf vars from the output of the vpc's module so they are available to other modules.

Xueshan
