### ISSUE TITLE
 Failure associating EIP: InvalidAllocationID.NotFound: 

### ISSUE THREAD

**Issue by nicocesar** [hashicorp/terraform#6970]
Usin Terraform v0.6.16  ;  the error is here https://gist.github.com/nicocesar/8edb46f740e581b869021ff22bb791cb

This is was terraform apply from scratch, creating from the VPC up, and the eip's failed because 

>  Failure associating EIP: InvalidAllocationID.NotFound: The allocation ID 'eipalloc-3608904f' does not exist

but 2 seconds later 'eipalloc-3608904f'  was there. 

I executed the same terraform apply and installation finish up perfectly. 

Which makes me think that the problem is just not waiting for the eip to show up when creating a fresh VPC

**Comment by catsby** [comment]
Hey @nicocesar – do you have a sample configuration that demonstrates this? We have acceptances tests that create VPCs and EIPs regularly, so any more specific information would be helpful. Thanks!

**Comment by nicocesar** [comment]
@catsby I dumped some more files here:   https://gist.github.com/nicocesar/3f7408171e1377afbf3c3ef609538f38

**Comment by catsby** [comment]
Hey @nicocesar – I wasn't able to reproduce, but I believe you 😄 

I've added some retry logic in https://github.com/hashicorp/terraform/pull/7186 which should retry the association, in the event that the first attempt fails for this error.

**Comment by catsby** [comment]
I merged #7186 which should help. If you still can reliably reproduce this after the next Terraform release, please try to share a config that reproduces it and I'll take another look. 

Thanks!
