### ISSUE TITLE
Error when modifying an aws_elasticache_cluster (redis)

### ISSUE THREAD

**Issue by kinetic-tim-cheung** [hashicorp/terraform#6971]
Error applying plan:

1 error(s) occurred:

* aws_elasticache_cluster.litacache: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.16
    Resource ID: aws_elasticache_cluster.litacache

### Debug Output
https://gist.github.com/kinetic-tim-cheung/e6aac12affd6dba55ca4651d68862f31

a .tf file defining 2 resources (an ec2 instance and an elasticache redis cluster) was applied and resources were created successfully.  The .tf file was modified to create an s3 bucket to store redis snapshots.  When 'terraform apply' was run, it generated the output in the gist linked above.  The bucket was created.

**Comment by stack72** [comment]
Hi @kinetic-tim-cheung 

Apologies for the error you are getting here. Please can you provide the config you are using (minus secrets) so I can try and reproduce this error?

Thanks

Paul

**Comment by stack72** [comment]
Hi @kinetic-tim-cheung 

ping :)

**Comment by stack72** [comment]
Hi @kinetic-tim-cheung 

I am going to close this out as I haven't heard back from you in 24 days.

Hopefully this isn't an issue any more

thanks

Paul
