### ISSUE TITLE
support for throughput optimised volumes in terraform (st1)

### ISSUE THREAD

**Issue by varuns-zetaris** [hashicorp/terraform#6975]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
 v0.6.16

### Affected Resource(s)
- aws_instance
     ebs_block_device
           volume_type

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behaviour
Need to support st1 for volume types. Which is throughput optimised drives.

### Actual Behaviour
Currently not supported

**Comment by catsby** [comment]
Hello –

`st1` type is currently supported; we don't actually have any code that validates the types here. The documentation was out of date, but I've updated https://www.terraform.io/docs/providers/aws/r/ebs_volume.html accordingly. 

Thanks!

**Comment by timvisher** [comment]
On 0.7.10 I just ran into this. Is it possible it resurfaced?

```hcl
resource "aws_opsworks_custom_layer" "charnock" {
  …
  ebs_volume {
    …
   type = "st1"
  }
}
```

`terraform apply =>`

```
* aws_opsworks_custom_layer.charnock: ValidationException: Volume Configurations: Volume Type: is not a valid volume type…
```

**Comment by timvisher** [comment]
ping

**Comment by timvisher** [comment]
@catsby maybe?

**Comment by catsby** [comment]
Hey @timvisher – the AWS API docs suggest that `st1` is not a valid type for OpsWorks layers: 

- http://docs.aws.amazon.com/en_en/opsworks/latest/APIReference/API_VolumeConfiguration.html

**Comment by timvisher** [comment]
@catsby Thanks for the response. That's weird. I'm looking at [this document](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html) which is linked to from the OpsWorks add instance wizard and `st1` is listed there as one of the magnetic disk options. There's also [this doc](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html) which mentions that the API supports it.

I guess this is an instance maybe of the OpsWorks platform being narrower than generic AWS?

**Comment by aviggiano** [comment]
[This page](https://www.terraform.io/docs/providers/aws/r/instance.html) is also out of date:

> `volume_type` - (Optional) The type of volume. Can be "standard", "gp2", or "io1". (Default: "standard").
