### ISSUE TITLE
resource meta-parameter count result in error when providing a map item

### ISSUE THREAD

**Issue by Djuke** [hashicorp/terraform#6983]
### Terraform Version
Terraform v0.7.0-dev (553e7534cfd09d01f8ca739784fd0585ea8a125b)

### Affected Resource meta-parameter
- count

### Terraform Configuration Files
```hcl
variable "instances" {
  default = {
    number = "1"
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_instance" "my_instance" {
  count = "${var.instances[number]}"
  ami = "ami-d3c022bc"
  instance_type = "t2.micro"
  tags {
    name = "my_instance"
  }
}
```

### Debug Output
https://gist.github.com/Djuke/48844fc7610e5ffb1520e46f3043c63d

### Expected Behavior
`"${var.instances[number]}"` should result into `1`

### Actual Behavior
```
Error configuring: 1 error(s) occurred:

* strconv.ParseInt: parsing "${var.instances[number]}": invalid syntax
```

### Steps to Reproduce
`terraform plan`

**Comment by Djuke** [comment]
It works fine, just forgot to add the `"` around `number`.

**Comment by jen20** [comment]
Hi @Djuke! Thanks for opening an issue - looks like you found the issue in the end. Hopefully one day we can provide better error messages around HIL by rewriting the parser, but for now we're pretty much stuck with "syntax error" unfortunately!
