### ISSUE TITLE
DigitalOcean Block Storage resource

### ISSUE THREAD

**Issue by troyswanson** [hashicorp/terraform#6985]
Looks like the folks at DigitalOcean just released a beta of their Block Storage product.

https://developers.digitalocean.com/documentation/v2/block-storage-beta/

**Comment by troyswanson** [comment]
It looks like the easiest flow would be to create the drive and then include it in the Droplet creation, a lot like how SSH Keys work. Here's an example from the documentation:

```json
{
  "name": "example.com",
  "region": "nyc1",
  "size": "512mb",
  "image": "ubuntu-14-04-x64",
  "drives": [
    {
      "id": "506f78a4-e098-11e5-ad9f-000f53306ae1"
    }
  ],
  "ssh_keys": null,
  "backups": false,
  "ipv6": true,
  "user_data": null,
  "private_networking": null
}
```

**Comment by troyswanson** [comment]
Looks like the DigitalOcean provider uses the `godo` package, which doesn't have support for this feature yet.

Upstream issue: digitalocean/godo#95

**Comment by rafaelrosafu** [comment]
Hello. I'm the product manager for the product, we're happy that it got picked up already, I would just like to clarify that it is still in beta, launch is scheduled for the summer, but we do want to support Terraform and other projects. I'll point our engineers to this thread. Cheers.

**Comment by aybabtme** [comment]
Hey @troyswanson! We have an internal fork of terraform were we've implemented support for drives! So as soon as we go public, support in terraform should land very quickly. We use terraform a lot, so this is something we took care of doing early for internal testing.

**Comment by troyswanson** [comment]
@rafaelmagu @aybabtme I definitely understand. I just wanted to test out the Block Storage stuff in Terraform since that's the primary way I interact with DigitalOcean.

**Comment by aybabtme** [comment]
I think we should be able to push our internal fork on our public Github org, so you could use that in the meantime =]

**Comment by troyswanson** [comment]
@aybabtme That'd be awesome. Thanks!

**Comment by stack72** [comment]
@aybabtme 

Have you thought about opening a PR to the main repo? We have had support for things like EFS before it went GA :)

P.

**Comment by troyswanson** [comment]
Well, now that block storage is live, it's probably appropriate to bump this issue.

**Comment by aybabtme** [comment]
@troyswanson yup https://github.com/hashicorp/terraform/pull/7560 =P

**Comment by troyswanson** [comment]
Closing this in lieu of #7560
