### ISSUE TITLE
name_prefix in aws_launch_configuration

### ISSUE THREAD

**Issue by joysarkarhub** [hashicorp/terraform#6988]
I am encountering an error with name_prefix on aws_launch_configuration resource:

resource "aws_launch_configuration" "launch_config" {
  name_prefix = "${var.app_name}_${var.app_type}_${var.app_env}_lc_"
 #name = "${var.app_name}"
  image_id = "${var.ec2_machine_image}"
  key_name = "${var.ec2_user_login_key}"
  iam_instance_profile = "${var.ec2_iam_instance_role}"
  instance_type = "${var.ec2_instance_type}"
  security_groups = ["${split(",", var.security_group)}"]
  user_data = "${file(var.ec2_user_data)}"
  lifecycle {
    create_before_destroy = true
  }
}

Errors:

  * aws_launch_configuration.launch_config: : invalid or unknown key: name_prefix

My terreform version is:

Terraform v0.6.0

**Comment by stack72** [comment]
Hi @joysarkarhub 

This version of Terraform didn't support the name_prefix. This was only added in a recent version of Terraform

Please upgrade to at least version `0.6.7` to take advantage of this feature

thanks

Paul
