### ISSUE TITLE
name_prefix in aws_launch_configuration

### ISSUE THREAD

**Issue by joysarkarhub** [hashicorp/terraform#6992]
Hi there,

I am having issue with name_prefix in resource aws_launch_configuration.

Errors:

  * aws_launch_configuration.launch_config: : invalid or unknown key: name_prefix
$ terraform -v
Terraform v0.6.0

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by stack72** [comment]
Hi @joysarkarhub

I commented in the other issue you opened. This version of Terraform didn't support the name_prefix. This was only added in a recent version of Terraform

Please upgrade to at least version 0.6.7 to take advantage of this feature

thanks

Paul
