### ISSUE TITLE
Error waiting for internet gateway to detach

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#6994]
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

aws_internet_gateway
### Terraform Configuration Files

``` hcl
resource "aws_internet_gateway" "default" {
  vpc_id = "${aws_vpc.default.id}"
  tags {
    Name = "gateway"
  }
}
```
### Expected Behavior

The Internet gateway resource should have been destroyed
### Actual Behavior

Received the following error:
`aws_internet_gateway.default: Error waiting for internet gateway (igw-96aeb9f3) to detach: couldn't find resource`
### Steps to Reproduce
1. `terraform destroy`
### Important Factoids

Using modules (non-nested). When I run the destroy command a second time, the gateway resource is destroyed.
### References

There are too many to list. It seems this is an ongoing issue that affects many users. Please advise and fix asap so we don't have to run the destroy command twice to clean up resources.

**Comment by jrnt30** [comment]
Do the logs indicate that it did attempt to retry/wait for 15 minutes for the IGW to detach?  Was this different than any of the other issues you are saying are already opened?

**Comment by toddrosner** [comment]
Hi @jrnt30, thanks for replying. I've increased the verbosity of the logging (trace) and have managed to reproduce the issue. The only thing I can see that's worth mentioning in the log is below.

```2016/06/07 10:52:09 [DEBUG] terraform-provider-aws: 2016/06/07 10:52:09 [INFO] Detaching Internet Gateway 'igw-74263511' from VPC 'vpc-709b0e14'```
```2016/06/07 10:52:09 [DEBUG] terraform-provider-aws: 2016/06/07 10:52:09 [DEBUG] Waiting for internet gateway (igw-74263511) to detach```
```2016/06/07 10:52:09 [DEBUG] terraform-provider-aws: 2016/06/07 10:52:09 [DEBUG] Waiting for state to become: [detached]```

This issue seems to happen about 70% of the time, which leads me to believe it's not simply an issue with Terraform.

**Comment by jrnt30** [comment]
@toddrosner You're welcome.  In the trace log, does that occur for the full 15 minutes (indicating an issue with the AWS response and potentially a need for an even *longer* wait)?

**Comment by toddrosner** [comment]
@jrnt30 I'm not really seeing requests repeating for the full 15 minutes, but I do have log info suggesting that the destroy operation happens for about 5 minutes...but what I'm looking at right now is the following:

```
2016/06/09 15:41:42 [DEBUG] terraform-provider-aws: <Response><Errors><Error><Code>DependencyViolation</Code><Message>Network vpc-6ae97e0e has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.</Message></Error></Errors><RequestID>59ea3723-e45a-43b2-ac6f-796c1500ffd1</RequestID></Response>
```

This happens after there's an attempt to detach the IGW, and what this makes me think is that those public addresses are mapped to the NAT gateways which is creating a race condition. It seems that about 15% of the time the addresses are unmapped in time so that the IGW can be destroyed...at least this is the case in us-west-2.
