### ISSUE TITLE
aws_instance security_group resource definition causes flapping

### ISSUE THREAD

**Issue by kerr23** [hashicorp/terraform#6996]
Terraform v0.6.16

My module def looks like:

```
resource "aws_instance" "vpn" {
   [...]
   subnet_id = "${element(split(",", module.vpc-admin.public_subnets), 0)}"
}
```
My VPC module outputs:
```
output "public_subnets" {
  value = "${join(",", aws_subnet.public.*.id)}"
}

```

Every time i apply i get a new server because it things the security group changes
(however it doesn't change)
```
> terraform apply
security_groups.#:           "0" => "1" (forces new resource)
security_groups.2089239738:  "" => "sg-8af132ec" (forces new resource)
---------------------------
> grep vpc_security_group_ids terraform.tfstate
"vpc_security_group_ids.#": "1",
"vpc_security_group_ids.2089239738": "sg-8af132ec"
---------------------------
> terraform apply
security_groups.#:           "0" => "1" (forces new resource)
security_groups.2089239738:  "" => "sg-8af132ec" (forces new resource)
```

**Comment by jrnt30** [comment]
Are you using the `security_groups` or `vpc_security_group_ids` attribute?  If using a VPN (as subnet indicates) the `vpc_security_group_ids` is the correct parameter to use.  There are a few other issues about this you can find, but that is the jist as https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups explains

**Comment by kerr23** [comment]
Thanks that worked!

I also just realized that my example is totally borked and i was conflating security_groups with subnets
