### ISSUE TITLE
new terraform: Unknown refresh result: Local and remote state conflict, manual resolution required

### ISSUE THREAD

**Issue by arcadiatea** [hashicorp/terraform#6999]
Terraform v0.7.0-dev 
Using new terraform for existing terraform plan, getting error
`new terraform: Unknown refresh result: Local and remote state conflict, manual resolution required`
It seems caused by new terraform write version 2 in local and previous version use version 1, even other information are same.
tfstate file for new version:
`{
    "version": 2,
.... 
`
tfstate file for old version
`{
    "version": 1,
...
`

**Comment by jen20** [comment]
Hi @arcadiatea! Thanks for reporting this, the actual bug here is that we don't increment the serial number on upgrade. I'll open a pull request to correct this now, as it's a fairly nasty bug. A workaround is to open the `.tfstate` file and increment the `serial` field by one.

**Comment by jen20** [comment]
Hi @arcadiatea - actually I was mistaken about this fix, I read too quickly! Some further investigation suggests this is an issue elsewhere. Let me do some testing and come back to you on this.

**Comment by bigkraig** [comment]
@jen20 We had some related discussion on #6732

**Comment by bigkraig** [comment]
It looks like this was addressed in #7402

**Comment by arcadiatea** [comment]
It is not a problem anymore.
