### ISSUE TITLE
Cannot Create Windows Opswork Stack

### ISSUE THREAD

**Issue by oldbag** [hashicorp/terraform#7003]
Hi there,

I'm trying to create an AWS opsworks Windows Stack and have the following in my terraform file:

```
resource "aws_opsworks_stack" "Domain-Controller" {
    name = "Domain Controller"
    region = "eu-west-1"
    service_role_arn = "${aws_iam_role.aws-opsworks-service-role.arn}"
    default_instance_profile_arn = "${aws_iam_instance_profile.aws-opsworks-ec2-instance-role.arn}"
    agent_version = "LATEST"
    configuration_manager_name = "Chef"
    configuration_manager_version = "12"
    default_os = "Microsoft Windows Server 2012 R2 Base"
    vpc_id = "${aws_vpc.default.id}"
    default_subnet_id = "${aws_subnet.zone-a.id}"
    hostname_theme = "Greek_Deities_and_Titans"
    color = "rgb(135, 61, 98)"
    default_root_device_type = "ebs"
    use_opsworks_security_groups = "false"
    manage_berkshelf = "false"
    use_custom_cookbooks = "true"
    custom_cookbooks_source {
      type = "git"
      url = "https://github.mydomain.com/myrepo.git"
    }
    custom_json = <<EOT
{
 "foobar": {
    "version": "1.0.0"
  }
}
EOT
}
```

And when try and apply this, I get:

Error applying plan:

1 error(s) occurred:

* aws_opsworks_stack.Domain-Controller: ValidationException: Chef Configuration's Berkshelf Version: is unsupported prior to Chef 11.10, Default Os: Microsoft Windows Server 2012 R2 Base is unsupported with Chef::12. Please consult the AWS OpsWorks documentation at http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-os.html to learn more about the current supported combinations, Configuration Manager: can't be changed
      
I was running terraform v0.6.16.

From what i've seen, it appears that the code tries to create a linux stack by default and a default_os parameter was added to resolve this (it was present in terraform v0.6.16), but it doesn't seem to be working.

I then tried to compile the latest dev version: Terraform v0.7.0-dev (e7c9031dd4054060d71c636b91fc7e88d6b974e8) and the issue still occurs.

Does anyone have a fix for this?

Cheers,
Simon.

**Comment by u2mejc** [comment]
Hi @oldbag, sorry to beat the dead horse, but it's really important that you include the full GitHub template that is inline when you open a new issue for any project. You get help faster and engineers don't waste cycles. Please include the template `ISSUE_TEMPLATE.md` and a full gist of the output of `export TF_LOG=debug`, if this issue persists for you.

Your resource block has two issues: Windows stacks require `configuration_manager_version = "12.2"`. Also, drop `agent_version`, it appears unsupported for Windows. Dropping those two allows your code snippet to apply without issue.

Please let me know if that works for you and feel free to shoot over a PR if you'd like to update the docs.

**Comment by u2mejc** [comment]
I believe this was a usage question that I answered above, @stack72 can you please close this?

**Comment by stack72** [comment]
Closed on request :) Thanks @u2mejc!
