### ISSUE TITLE
creating azure rm storage container fails after creating azure rm storage 

### ISSUE THREAD

**Issue by isamuelson** [hashicorp/terraform#7005]
using terraform (master branch) 

```
Error applying plan:

1 error(s) occurred:
azurerm_storage_account.storage: Creating...
  account_type:             "" => "Premium_LRS"
  location:                 "" => "eastus2"
  name:                     "" => "storagexxx"
  primary_access_key:       "" => "<computed>"
  primary_blob_endpoint:    "" => "<computed>"
  primary_file_endpoint:    "" => "<computed>"
  primary_location:         "" => "<computed>"
  primary_queue_endpoint:   "" => "<computed>"
  primary_table_endpoint:   "" => "<computed>"
  resource_group_name:      "" => "test-compute"
  secondary_access_key:     "" => "<computed>"
  secondary_blob_endpoint:  "" => "<computed>"
  secondary_location:       "" => "<computed>"
  secondary_queue_endpoint: "" => "<computed>"
  secondary_table_endpoint: "" => "<computed>"
azurerm_storage_account.storage: Still creating... (10s elapsed)
zurerm_storage_account.storage: Refreshing state... (ID: /subscriptions/xxx/resourceGroups/devforge-compute/providers/Microsoft.Storage/storageAccounts/storagexxx)
azurerm_storage_account.storage: Creation complete
azurerm_storage_container.container: Creating...
  container_access_type: "" => "private"
  name:                  "" => "devforgecontainer"
  properties.#:          "" => "<computed>"
  resource_group_name:   "" => "devforge-compute"
  storage_account_name:  "" => "devforgestorage"
Error applying plan:

1 error(s) occurred:

* azurerm_storage_container.container: Error creating container "devforgecontainer" in storage account "devforgestorage": storage: service returned error: StatusCode=404, ErrorCode=ResourceNotFound, ErrorMessage=The specified resource does not exist.
RequestId:
Time:2016-06-03T18:15:01.9436803Z, RequestId=0c0e7271-001c-0001-62c3-bd797b000000, QueryParameterName=, QueryParameterValue=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by isamuelson** [comment]
http trace:

#             Result   Protocol               Host       URL        Body      Caching Content-Type    Process Comments          Custom
114         202         HTTPS   management.azure.com              /subscriptions/xxx/resourceGroups/xxx-compute/providers/Microsoft.Storage/storageAccounts/storagexxx?api-version=2015-06-15 0              no-cache; Expires: -1                       terraform:16664                                              
160         200         HTTPS   management.azure.com              /subscriptions/xxx/resourceGroups/xxx-compute/providers/Microsoft.Storage/storageAccounts/storagexxx?api-version=2015-06-15 461         no-cache; Expires: -1       application/json               terraform:16664                                              
162         200         HTTPS   management.azure.com              /subscriptions/xxx/resourceGroups/xxx-compute/providers/Microsoft.Storage/storageAccounts/storagexxx?api-version=2015-06-15 461         no-cache; Expires: -1       application/json               terraform:16664                                              
164         200         HTTPS   management.azure.com              /subscriptions/xxx/resourceGroups/xxx-compute/providers/Microsoft.Storage/storageAccounts/storagexxx/listKeys?api-version=2015-06-15            348                no-cache; Expires: -1       application/json               terraform:16664                                              
166         200         HTTPS   management.azure.com              /subscriptions/xxx/resourceGroups/xxx-compute/providers/Microsoft.Storage/storageAccounts/storagexxx/listKeys?api-version=2015-06-15            348                no-cache; Expires: -1       application/json               terraform:16664                                              
168         404         HTTPS   storagexxx.blob.core.windows.net /xxxcontainer?restype=container  188                         application/xml terraform:16664

**Comment by jen20** [comment]
@IBootstrap Thanks for opening an issue. This looks to me like we follow the expected path:

### Inside the (MS) SDK
1. Create the storage account - get a 202 Accepted back
2. Poll and get a 200 back, should mean the account is created

### Inside Terraform
3. Read the account to get the ID (the requirement for this is poor design on behalf of the MS SDK - Riviera for example does not require this extra potential point of failure)
4. Get the keys for the account - 200 and the keys are listed so we should be able to assume this is created.

### In the Container resource:

5. 404 on the accout.

This looks very much to me like eventual (perhaps) consistency in the Azure API. If you reapply a few times does it eventually create? I think this one will need passing over to Microsoft to advise on how we should know the account is created - it's possible we have to wait for some provisioning state to reach a different status post creation.

**Comment by isamuelson** [comment]
Yes @jen20, you are correct. if i apply again it will work.

**Comment by jen20** [comment]
@isamuelson My guess here is that we need to wait on ProvisioningState or similar.

**Comment by isamuelson** [comment]
@jen20 do we need to open a ticket on the ms-azure-for-go ?
