### ISSUE TITLE
Upgrading to v0.6.16 will delete and rebuild all vSphere hosts

### ISSUE THREAD

**Issue by tmlink** [hashicorp/terraform#7008]
Upgraded to `Terraform v0.6.16` .  Changelog mentions:
provider/vsphere: Add skip_customization option to vsphere_virtual_machine resources (#6355)

All of the resources of this vsphere  are showing:
```
 skip_customization:                     "" => "false" (forces new resource)
```
even explicitly setting `skip_customization = ""` doesn't help.   All of the servers will be delete and rebuild -- data loss.

**Comment by stack72** [comment]
@tmlink have you tried `skip_customization = true` ?

P.

**Comment by tmlink** [comment]
`skip_customization = true` leads to: 
```
   skip_customization:                     "" => "true" (forces new resource)
```

**Comment by stack72** [comment]
Hi @tmlink 

So this was an oversight and we missed a statemigration. Therefore, in order to unblock you and to stop your infra being destroyed, we need to manually change your state

Can you post the contents of the your TFstate file (minus secrets) for one of your virtual machines and I can help you with the state change

Thanks

Paul

**Comment by tmlink** [comment]
I can probably fix my tfstate file, but that's not fixing the problem.   It needs to be handled in side of terraform

1) We have several customers who have built their infrastructures using our modules, they will need remedy.   Which will be a pain since they run terraform from multiple platform.
- I'm telling them to NOT upgrade to 0.6.16 
- They are already having problems with 0.6.15 and an issue ipv4_gateway is being set every apply. https://github.com/hashicorp/terraform/issues/6590
2) We already lost a cluster after `linked_clone` was introduced in 0.6.15, so this is one-time thing

Terraform shouldn't set a var from not-set to setting it on it's own.   Binary vars should use not-set or "" to mean, don't change.

**Comment by stack72** [comment]
Hi @tmlink 

Yes, we will be fixing this on the TF side (there is an open PR for this - https://github.com/hashicorp/terraform/pull/7023). I only suggested fixing your state file to unblock you right now

This migration was missed - going forward, migrations like this will be added by default

Paul

**Comment by tmlink** [comment]
Thanks Paul,    I can get myself unblocked.   I believe that #7023 addresses my concerns.

**Comment by jare19** [comment]
` lifecycle {
    ignore_changes = ["linked_clone", "skip_customization"]
  }`
insert this block into the vsphere_virtual_machine resource block and it will fix the upgrade problem.
