### ISSUE TITLE
aws_db_instance resets monitoring_interval on every run

### ISSUE THREAD

**Issue by justintime** [hashicorp/terraform#7016]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "blcdb" {
  identifier                 = "xxxxx"
  allocated_storage          = "100"
  storage_type               = "gp2"
  engine                     = "mysql"
  engine_version             = "5.6.33"
  instance_class             = "m4.large"
  monitoring_interval        = 60
  monitoring_role_arn        = "<role managed by tf>"
  skip_final_snapshot        = false
  name                       = "xxx"
  username                   = "xxx"
  password                   = "xxxx"
  port                       = 3306
  publicly_accessible        = false
  vpc_security_group_ids     = [xxx]
  db_subnet_group_name       = "xxx"
  parameter_group_name       = "xxx"
  multi_az                   = "true"
  backup_retention_period    = "7"
  backup_window              = "07:04-07:34"
  maintenance_window         = "wed:05:25-wed:05:55"
  auto_minor_version_upgrade = "true}"
  final_snapshot_identifier  = "xxx"
  tags {
    "provisioned_by" = "Terraform"
    "environment" = "xxx"
  }
}
```

### Expected Behavior
It should create the db on the first run, and on subsequent runs, it should do nothing.

### Actual Behavior
On every subsequent run, it tries to reset the monitoring_interval:
```    monitoring_interval: "0" => "60" ```

However, the AWS Console shows that the interval is already set to 60.  I think TF is setting the right property, but reading from the wrong one to determine current state.

**Comment by stack72** [comment]
Hi @justintime 

RDS instances can either have changes applied to them instantly or at the next reboot time. Right now, your config doesn't have `apply_immediately = true`, therefore, Terraform is telling the RDS instance to wait till the next reboot time for the monitoring_interval change to kick in

If you want this to be immediate, then add `apply_immediately = true` to the config and apply it. That will then take care of the associated change

There is a [note](https://www.terraform.io/docs/providers/aws/r/db_instance.html) at the top of the documentation about this specific instance. Please be careful making this change :)

I believe this will fix the issue. If it doesn't , then please feel free to get back in touch

Paul

**Comment by justintime** [comment]
I toggled ```apply_immediately = true``` and I'm still seeing the same behavior.

**Comment by justintime** [comment]
I may have found the problem.  I'm using a TF-managed role, and it may not have the appropriate permissions to enable monitoring.  I'll report back later.

**Comment by justintime** [comment]
Yep, that was it.  Sorry for the noise!

**Comment by rahuljain1311** [comment]
same reason for me
`resource "aws_iam_role" "enhanced_monitoring" {
  name               = "${local.base_name}-monitoring1"
  assume_role_policy = "${data.aws_iam_policy_document.enhanced_monitoring.json}"
}

data "aws_iam_policy_document" "enhanced_monitoring" {
  statement {
    actions = [
      "sts:AssumeRole",
    ]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

data "aws_iam_policy" "AmazonRDSEnhancedMonitoringRole" {
  arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

resource "aws_iam_role_policy_attachment" "enhanced_monitoring" {
  role       = "${aws_iam_role.enhanced_monitoring.name}"
  policy_arn = "${data.aws_iam_policy.AmazonRDSEnhancedMonitoringRole.arn}"
}`
