### ISSUE TITLE
Stickyness Policy is created, but isn't assigned to the ELB

### ISSUE THREAD

**Issue by justintime** [hashicorp/terraform#7017]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_app_cookie_stickyness_policy

### Terraform Configuration Files
```hcl
resource "aws_app_cookie_stickiness_policy" "blc-admin-80" {
  name = "xxx"
  load_balancer = "xxx"
  lb_port = 80
  cookie_name = "JSESSIONID"
}
```

### Expected Behavior
TF should create the policy, and assign it to the ELB

### Actual Behavior
On first run, it "creates" the policy.  On subsequent runs, it does nothing.  However, the ELB is not modified to use the policy on the listener.

**Comment by stack72** [comment]
Hi @justintime 

What is the value you are passing to the load_balancer parameter? Is it a load_balancer name or an ARN?

Paul

**Comment by justintime** [comment]
It's the load balancer name.

**Comment by jbardin** [comment]
Hi @justintime 

I'm not able to reproduce this with either v0.6.16 or master.
Is it possible for you to create a couple standalone configs that reproduce the issue?

**Comment by justintime** [comment]
In making the testcase, I found the true bug.

Given this tf:

``` hcl
resource "aws_elb" "elb" {
  name = "testcase"
  subnets = ["<<your subnet id here>>"]
  internal = "true"
  security_groups = ["<<your security group id here>>"]

  listener {
    instance_port = "80"
    instance_protocol = "http"
    lb_port = "80"
    lb_protocol = "http"
  }

  health_check {
    healthy_threshold = 4
    unhealthy_threshold = 2
    timeout = 5
    target = "HTTP:80/"
    interval = 10
  }

  cross_zone_load_balancing = "true"
  idle_timeout = "60"
  connection_draining = true
  connection_draining_timeout = "90"

}

resource "aws_app_cookie_stickiness_policy" "sticky" {
  name = "sticky"
  load_balancer = "${aws_elb.elb.name}"
  lb_port = 80
  cookie_name = "JSESSIONID"
}
```

Run it once.  It will create the ELB and attach the policy as it should.

However, if you go into the console and manually disable the policy on the ELB, it will fail to discover that and re-attach it on the next (and all subsequent) run.
