### ISSUE TITLE
How VPC to launch is decided for aws_instance resource

### ISSUE THREAD

**Issue by shanmugakarna** [hashicorp/terraform#7021]
How VPC to launch is decided for aws_instance resource. Docs shows no option to specify VPC

https://www.terraform.io/docs/providers/aws/r/instance.html

**Comment by stack72** [comment]
Hi @shanmugakarna 

To launch an AWS instance in a VPC, you need to specify the specific `subnet_id`. A subnet is specific to a VPC

Hopefully this helps

Paul
