### ISSUE TITLE
Terraform multiblock variables interpolation

### ISSUE THREAD

**Issue by papiveron** [hashicorp/terraform#7022]
Hi,

I would like to know if it is  possible and how to define variables in recursive dictionnary way with terraform like this :

```
var "my_var" {
     block1 {
            param1 = "value1"
            param2 = "value2"
     }

     block2 {
            param3 = "value3"
            param4 = "value4"
     }
}
```

And then access variable this way : **${var.my_var.block1.param2}**

Thank you

**Comment by jen20** [comment]
Hi @papiveron! Thanks for opening an issue here. Currently this is not supported - however the infrastructure is mostly in place as of 0.7 to make it possible in a future version. In the meantime however you can use the element function in concert with a list of map keys to get a similar effect.
