### ISSUE TITLE
Launch Configuration unable to create instances in an Auto Scaling Group from a custom snapshot AMI

### ISSUE THREAD

**Issue by hazim1093** [hashicorp/terraform#7024]
We're facing issues while launching an instance from our AMI, in an autoscaling group.
We do the following through terraform (basic steps): 

1. Create an instance through
2. Create an AMI from that instance.
3. Create a launch configuration and autoscaling group to launch instances from our AMI.

repo: [https://github.com/stakater/stakater](https://github.com/stakater/stakater)
(the command `make application` would trigger the above mentioned process) 

We were using Terraform version 0.6.12, so encountered the known issue of `encrypted` flag in `ebs_block_device ` ([reference](https://github.com/hashicorp/terraform/issues/5360))

After that I tried different terraform versions and encountered the following issues with different terraform versions: 

------------------------
Terraform 0.6.12: 
Times out while creating Autoscaling group, due to the bug mentioned above. (related to `encrypted` flag)

Describing the auto scaling group via the AWS CLI, it tells that the encrypted flag is not allowed.
This is a bug in this terraform version which has been fixed in later versions.

------------------------
Terraform 0.6.16: 
Completes the whole process successfully, creates an instance in an autoscaling group from our AMI. Just like we want to

Issue: 
The instance created, does not have the cloud-config or any data from our original instance. In fact ANY instance created from that AMI (even manually) does not have any data or cloud-config from the initial instance.

I realized in Terraform 0.6.15 and 0.6.16, at every step after the initial instance is created, our initial instance is destroyed than created, and after the AMI has been created, every step after that it also destroys and creates the original instance AND the AMI as well. I did not understand this behavior, But I suspect it to be the reason why the any instance created from our AMI is (sort of) empty.

------------------------
Terraform 0.6.9: 
Most people suggested reverting back to this version, a few referred it as the most stable version. The whole process completes successfully and creates an instance in an auto scaling group from our AMI. 

issue: 
The instance that is created in an auto scaling group OR any instance created from the AMI (even manually) cannot be ssh-ed into.
It always asks for password, even after providing key while doing ssh (with the right permissions)

-------------------------
Terraform 0.6.15: 
behaves just as 0.6.16 (the destroying and creating cycle)
but does not complete the process successfully, results in the same error as in 0.6.12

-------------------------
Issues I have seen and explored: 
https://github.com/ansible/ansible-modules-core/issues/1693
https://github.com/hashicorp/terraform/issues/5608
https://github.com/hashicorp/terraform/issues/5360
https://github.com/hashicorp/terraform/issues/5108

**Comment by catsby** [comment]
Hey @hazim1093 – https://github.com/hashicorp/terraform/pull/6512 was just merged and should resolve the `encrypted` error you were seeing. Are you able to build from master and see if that addresses any of your problems?

**Comment by catsby** [comment]
Hello –

I'm going to close this issue for now. If you have more information or configurations that can help me reproduce this procedure:

> I realized in Terraform 0.6.15 and 0.6.16, at every step after the initial instance is created, our initial instance is destroyed than created, and after the AMI has been created, every step after that it also destroys and creates the original instance AND the AMI as well. I did not understand this behavior, But I suspect it to be the reason why the any instance created from our AMI is (sort of) empty.

I would be happy to investigate. Thanks!

**Comment by hazim1093** [comment]
Tested with release 0.7.0, works well!
