### ISSUE TITLE
Invalid syntax leads to a crash

### ISSUE THREAD

**Issue by ApsOps** [hashicorp/terraform#7025]
Missed `var.` when referencing a variable causes crash.

### Terraform Version
Terraform version: 0.6.16  6e586c89394f5474b6c5f3217a4a75ce80c3fd6c

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "temp" {
  ami = "ami-408c7f28"
  instance_type = "t2.micro"
  associate_public_ip_address = "${associate_public_ip}"
}
```

### Panic Output
https://gist.github.com/ApsOps/cd88a44acf00ef8903b241650136d235

### Expected Behavior
It should just throw an error saying `Invalid syntax`, probably suggest what format it should be in.

### Actual Behavior
It said `unexpected EOF` and crashed.

### Steps to Reproduce
1. `terraform plan`

**Comment by catsby** [comment]
Hey @ApsOps thanks for the report! 
We have an identical report in https://github.com/hashicorp/terraform/issues/5338 so I'm going to close this one. Please follow along there if you want to stay up on any progress there
