### ISSUE TITLE
jsonencode does not create JSON structure

### ISSUE THREAD

**Issue by rkulagowski** [hashicorp/terraform#7028]
### Terraform Version

0.6.16
### Affected Resource(s)

jsonencode
### Expected Behavior

What should have happened?

```
jsonencode("email:foo@bar.baz, dept:Development")
```

should have (?) turned into

```
{"email": "foo@bar.baz","dept": "Development" }
```
### Actual Behavior

What actually happened?

```
"\"email:foo@bar.baz, dept:Development\""
```
### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-5890

**Comment by jen20** [comment]
Hi @rkulagowski! I agree the behaviour here is slightly weird. It's actually unclear to me what should happen when you JSON-encode a string without a key. I think we need to go back to the drawing board with this interpolation function and figure out what the semantics should be and get them documented. Thanks for bringing this to our attention!

cc @phinze.

**Comment by mitchellh** [comment]
This is working as expected I believe. With first-class map/list support in 0.7 you can now give it a map and get the proper value and other interpolation functions exist to help convert strings to maps.
