### ISSUE TITLE
Crash when using concat on lists of maps

### ISSUE THREAD

**Issue by oillio** [hashicorp/terraform#7030]
### Terraform Version
Terraform v0.7.0-rc1 (301da85f30239e87b30db254a25706a6d41c2522)

### Terraform Configuration Files
Module:
```hcl
variable "foo" {
  type = "list"
}
variable "bar" {
  type = "list"
}

output "outFoo" {
  value = "${concat(var.foo,var.bar)}"
}
```

Calling:
```hcl
module "envTesting" {
  source = "../modules"
  foo {
    value     = "aVal"
  }
  foo {
    value     = "anotherVal"
  }
  bar {
    value     = "thirdVal"
  }
  bar {
    value     = "finalVal"
  }
}
```

### Panic Output
https://gist.github.com/oillio/ad293c464de43f7ff10efe8b0ceac466

**Comment by phinze** [comment]
Hi @oillio - thanks for this report. I've reproduced and fixed up the crash with a quick solution for now in #7145, which turns it into an error message. Getting `concat()` to support lists of complex types is its own task that I'm spinning up into a fresh issue, which I'll link back here. 👍

**Comment by phinze** [comment]
Ok just double checked that the crasher is now fixed. Continued discussion of expected behavior can happen over in #7146
