### ISSUE TITLE
move command?

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform#7033]
Has there ever been discussion around creating a `terraform mv` command? I have found myself editing my `.tfstate` file manually on more than a few occasions to move a resource between modules for organizational purposes. It's a pretty painful experience.

It would be nice (and seemingly trivial) to support something like:
`terraform mv moduleA.type.name moduleB.type.name`

Importantly, this would only re-structure the `.tfstate` file. The user would be responsible for actually moving the resource declarations to the correct location.

**Comment by phinze** [comment]
This is coming in Terraform 0.7 w/ `terraform state mv`! 😄 

https://github.com/hashicorp/terraform/blob/master/website/source/docs/commands/state/mv.html.md

**Comment by tkellen** [comment]
SWEET!
