### ISSUE TITLE
DigitalOcean - droplet destruction

### ISSUE THREAD

**Issue by bchelli** [hashicorp/terraform#7042]
Hi Guys,

First of all thanks for the amazing product. I'm having a lot of fun piloting my infra using Terraform, this is a game changer for me and for my company.

I was wondering if it was possible to have a graceful destruction of the droplet using the [shutdown API from DigitalOcean](https://developers.digitalocean.com/documentation/v2/#shutdown-a-droplet) prior the deletion of the droplet. Currently, the code seems to be [deleting the droplet directly](https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L397), also if I'm reading that right on AWS the instances are deleted using [TerminateInstances](http://docs.aws.amazon.com/sdk-for-go/api/service/ec2/EC2.html#TerminateInstances-instance_method) which is gracefully shutting down the instance.

Here is the use case I'm trying to solve, I have a mesos cluster and when I scale down the cluster the nodes are being destroyed without notifying properly the master nodes, therefore, marathon or any other framework running on mesos is not re-launching the lost tasks and the cluster is on an unknown state for quite a long time until it stabilizes itself (about one hour).

Thanks,

**Comment by stack72** [comment]
Hi @bchelli 

Thanks for raising the question here. I just have a look into this. DO are not doing a kill -9 - it is a graceful deletion of the droplet. Therefore I don't know what Powering off the node will even be able to protect against. 

You could try something like setting the node to execute a script on instance shutdown to remove it from the mesos cluster - but this is something you would have to script 

Hope this helps

Paul
