### ISSUE TITLE
terraform plan generates no-op s3 bucket policy modifications

### ISSUE THREAD

**Issue by giladwolff** [hashicorp/terraform#7045]
Hi there,

### Terraform Version
v0.6.16

### Affected Resource(s)
- aws_s3_bucket

### Terraform Configuration Files
For brevity I removed comments, variables definitions, and outputs.
```hcl
resource "aws_s3_bucket" "console_app_bucket" {
    bucket = "${var.console_app_bucket_name}"
    acl = "private"
    region = "${var.region}"
    policy = <<EOF
{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "s3:GetObject",
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::${var.console_app_bucket_name}/*",
          "Principal": {
            "AWS": "${var.cloudfront_origin_s3_canonical_user_id}"
          },
          "Sid": ""
        },
        {
          "Action": ["s3:PutObject", "s3:List*"],
          "Effect": "Allow",
          "Resource": ["arn:aws:s3:::${var.console_app_bucket_name}",
                       "arn:aws:s3:::${var.console_app_bucket_name}/*"],
          "Principal": {
            "AWS": "${aws_iam_role.console_bucket_publisher_role.arn}"
          },
          "Sid": ""
        }
      ]
    }
EOF
}
```

### Debug Output
This is the output of terraform plan. I changed the actual values with '<some replacement>', but you can see from the plan that the source and the target are the same. 'terraform apply' and then immediately thereafter terraform plan produces the same output.

 policy:"{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity <distribution id>\"},\"Resource\":\"arn:aws:s3:::<s3-bucket-name>/*\",\"Sid\":\"\"},{\"Action\":[\"s3:PutObject\",\"s3:List*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::<account-id>:role/<role name>\"},\"Resource\":[\"arn:aws:s3:::<s3-bucket-name>/*\",\"arn:aws:s3:::s3-bucket-name>\"],\"Sid\":\"\"}],\"Version\":\"2012-10-17\"}"=>"{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity <distribution id>\"},\"Resource\":\"arn:aws:s3:::<s3-bucket-name>/*\",\"Sid\":\"\"},{\"Action\":[\"s3:PutObject\",\"s3:List*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::<account id>:role/<role name>\"},\"Resource\":[\"arn:aws:s3:::<s3 bucket name>\",\"arn:aws:s3:::<s3 bucket name>/*\"],\"Sid\":\"\"}],\"Version\":\"2012-10-17\"}"

### Expected Behavior
The plan should produce no modifications.

### Actual Behavior
See above plan.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. 'terraform plan'

**Comment by geekq** [comment]
I hat the same problem with S3 bucket and policy.

Once I switched two lines in the policy though, the endless modification loop went away:

```
"Resource": [
  "arn:aws:s3:::${var.console_app_bucket_name}/*",
  "arn:aws:s3:::${var.console_app_bucket_name}"
],
```

The cause is probably, that once you submit your policy, AWS sorts the lines it's way. On subsequent reading of the current state from AWS terraform gets a divergent policy content.

You can debug this situation by looking inside the terraform.tfstate file

**Comment by catsby** [comment]
I think @geekq is on the right track here.
I diff'd the output, here was the difference. 

Terraform read from AWS:

```
      "Resource": [
        "arn:aws:s3:::/",
        "arn:aws:s3:::s3-bucket-name>"
      ],
```

Terraform had in state:

```
      "Resource": [
        "arn:aws:s3:::",
        "arn:aws:s3:::/"
      ],
```

Does `var.console_app_bucket_name` have a value? 
Either way, this appears to be a misconfiguration rather than a bug in Terraform, so I'm going to close for now.

**Comment by giladwolff** [comment]
@geekq is absolutely right and this is the ordering of resources in the policy statement that is causing problem. Thanks for the tip, I changed the order and now terraform is not trying to reapply the same again and again. But this is absolutely a bug in terraform and not a misconfiguration.
