### ISSUE TITLE
keys() interpolation function ordering

### ISSUE THREAD

**Issue by imbriaco** [hashicorp/terraform#7057]
Hi Terraform Team,

In [[1]](https://github.com/hashicorp/terraform/blob/master/config/interpolate_funcs.go#L613) I see an `interpolationFuncKeys` function defined that returns a list of keys from a map. This is very useful! 

After reviewing the implementation, it seems that the keys are sorted before they are returned. I'm wondering whether it is safe for me to rely upon this behavior or if I need to treat the order of results that I get back from `keys()` as undefined? Unfortunately, this function does not appear to be documented (though I found some confirmation in another issue that it is at least intended to be public) so I wasn't able to answer this for myself.

I'd like to advocate for defining the result of `keys()` as sorted (or at least as having consistent ordering) and updating the documentation and test cases to reflect this as necessary. My justification is that when I think about ways that I might like to make use of this, an obvious case might look something like the following.

This code is off the top of my head without a real editor, so please excuse any typos or missing parens. I think the idea should come across at least.

```
variable "subnets" {
  default = {
    us-east-1a = "1.2.3.4/24"
    us-east-1b = "1.2.3.5/24"
  }
}

resource "aws_subnet" "subnet" { 
  ...
  availability_zone = "${element(keys(var.subnets), count.index)}"
  cidr_block = "${lookup(var.subnets, element(keys(var.subnets), count.index))}"
  count = "${length(keys(var.subnets))}"
}
```

If the ordering of the list of keys were to change, this could some undesirable (and unpredictable) effects on resources that are constructed in a similar way.

Thanks!

cc: @phinze

**Comment by phinze** [comment]
Thanks for filing this @imbriaco - agreed that the `keys()` and `values()` functions become much more useful if their ordering is consistent.

**Comment by jen20** [comment]
The missing documentation here is not good - we will resolve that also. You can rely on the output of keys being sorted alphabetically. If you need `values()` to be in a deterministic order you can use the new `sort()` interpolation function, though I'm not necessarily opposed to making that sorted either. Thoughts @phinze?

**Comment by apparentlymart** [comment]
Given that the `sort` function exists to help sorting the values by themselves, I'd vote for `values()` by default using the same ordering as `keys()`, since that way the two will be "aligned" by default.

**Comment by josephholsten** [comment]
+1 to returning `values()` in matched order to `keys()`

**Comment by jbardin** [comment]
This is taken care of in #7418

We added a unit test to make sure the order of keys and values don't break, and added those interpolation functions to the docs.
