### ISSUE TITLE
Heroku Spaces Support

### ISSUE THREAD

**Issue by ethangunderson** [hashicorp/terraform#7059]
Is support for Heroku Spaces in the works? I searched open issues, but couldn't find anything. I've started work on this already but figured I would check to see if this is on someone else's radar being going any further.

**Comment by ethangunderson** [comment]
I started to work on this, and got pretty far. However, the issue I found is that the Heroku API client that Terraform uses appears to be abandoned. More so, the tool that's used to generate the client can no longer handle the schema provided by Heroku. https://github.com/interagent/schematic/issues/29

I've hand edited the client code so that I can continue working on this provider enhancement, but is this a dependency that the Terraform team wishes to keep around? Should I look at replacing it?

**Comment by phinze** [comment]
Hey hey @ethangunderson! 👋 

We are not at all committed to the current dependency for any other reason than it is currently implemented and it passes the tests 😁 . I've bumped into its abandoned-ness before trying to figure out how to get a bug fixed or feature added to the Heroku provider. It's definitely preventing us from making more forward progress on the provider.

If you find a better client for us to lean on, I'd be all for replacing it. 👍

**Comment by ethangunderson** [comment]
From what I can find, all of them are abandoned. 😆 😢

**Comment by phinze** [comment]
Ha welp!

So Heroku publishes a "JSON Schema"

http://json-schema.org/

Is https://github.com/xeipuuv/gojsonschema any help?

**Comment by OJFord** [comment]
@phinze That's essentially just a validator as far as I can tell? The broken dependency actually generates the client, but it's choking on (valid) syntax that must be new since whenever it was last run.

This will block other Heroku FRs (#5649; #10350; #11326) - as I said in the latter:

> Given that the library's generated from a schema, and that generator has been broken since 2014 (cf. cyberdelia/heroku-go#9; interagent/schematic#29) might it be worth abandoning it in favour of HTTP requests at this point?

Or for new features, at least? I'd be happy to work on one or two if so.
