### ISSUE TITLE
Vsphere: Terraform forces new resource everytime I run plan

### ISSUE THREAD

**Issue by Shruti29** [hashicorp/terraform#7066]
I have tested the below with terraform versions 0.6.13, 0.6.15, 0.6.16 and the dev build (0.7.0)
I am trying to create a resource on vcenter with the following template file.

```
resource "vsphere_virtual_machine" "test" {
    folder = "myfolder"
    name   = "test-vm"
    datacenter    = "dc-1"
    cluster       = "cluster-1"
    vcpu   = "4"
    memory = "16384"
    gateway = "10.10.10.1"
    domain = "test.domain.com"

    network_interface {
        label = "vDC/INT-TEST"
        ipv4_address = "10.10.10.18"
        ipv4_prefix_length = "24"
    }
    disk {
        template = "centos-base"
        datastore = "datstore-test"
        type = "thin"
    }
```

The terraform resource gets created fine. But when I run terraform show command, the network label is not saved as expected.

```
network_interface.label = INT-TEST
```

The label should be saved as ```vDC/INT-TEST``` instead.
Every time I run terraform plan, it forces a new resource creation because of change in label name.

**Comment by ricardclau** [comment]
Just confirming we are seeing the exact same issue in our stack. 
Apparently, when the network interfaces are within a "folder" the terraform state gets a bit confused

Will try to have a look at both the code and the vsphere api responses

**Comment by chrislovecnm** [comment]
@ricardlau this may be a duplicate issue. We are using a wild card to lookup out networks.

**Comment by Shruti29** [comment]
@chrislovecnm My bad! I have created a duplicate of #5843 :) 
@ricardclau I have provide my comments in #5843.
