### ISSUE TITLE
Run same command on multiple instances from remote

### ISSUE THREAD

**Issue by JustLeo** [hashicorp/terraform#7084]
Hello all, this is what I'm trying to do: From "mesos_bootstrap" I need to reboot the other instances created as mesos_agents. The problem is that the interpolation I'm using is only returning one element and due to this, only one mesos_agent is being reboot. Am I missing something here? Is this possible with the tool? Thanks.

```
resource "aws_instance" "mesos_bootstrap" {
   ...
   provisioner "remote-exec" {
           inline = [
          "sudo shutdown -r"
        ]
        connection {
                user = "user"
                private_key = "${file(var.private_key_path)}"
        host = "${element(aws_instance.mesos_agents.*.private_ip, count.index)}"
        }
    }
}

resource "aws_instance" "mesos_agents" {
   ...
   count = "${var.mesos_agents}"
}
```

**Comment by mitchellh** [comment]
You can do this by using a null_resource with `count` set and then using the remote-exec provisioner on that. Not super ideal but it works!
