### ISSUE TITLE
aws_db_instance appears to be unable to restore Aurora DB from snapshot

### ISSUE THREAD

**Issue by kcrawley** [hashicorp/terraform#7089]
```
resource "aws_db_instance" "db_instance" {
  instance_class = "db.r3.large"
  snapshot_identifier = "rds:xxxx_xxx_xx-2016-06-07-10-20"
  db_subnet_group_name = "<calculated>"
  vpc_security_group_ids = ["<calculated>"]
  skip_final_snapshot = true
}
```

I am receiving this error:

```
* aws_db_instance.db_instance: Error creating DB Instance: DBSnapshotNotFound: DBSnapshot not found: rds:xxxx_xxx_xx-2016-06-07-10-20
	status code: 404, request id: fb34fa7e-2e3b-11e6-928c-edf687e6e57c
```

Things that might be helpful:

* The VPC the snapshot was created in is not the same as the VPC I'm targeting to restore (this is inconsequential in the UI, where this works as expected, I just thought it'd be worth noting)
* I'm attempting to restore an Aurora cluster snapshot
* FWIW, the snapshot does actually exist.

**Comment by catsby** [comment]
Hello –

I'm not sure restoring a RDS Aurora Cluster snapshot into a regular RDS instance is something that is supported, do you have any links to the AWS docs that detail this?

What I think we're missing is a `snapshot_identifier` on the `aws_rds_cluster` resource, allowing you to restore an Aurora snapshot into a new Aurora cluster. Currently that is not supported. 

Let me know if I'm on the same page, or if I'm missing something.

Thanks!

**Comment by kcrawley** [comment]
@catsby I believe you're right, as I've experienced the same 404 when attempting to execute the command on the CLI.

It appears the AWS console does some extra steps with recreating a cluster and an instance through the `aws_rds_cluster` set of endpoints. I don't see this issue being addressed currently, so I might take a stab at it.

**Comment by kcrawley** [comment]
@catsby i was able to add support for restoring RDS cluster snapshots in the `aws_rds_cluster` resource. (creating a new instance in the restored cluster seems to address my use case). https://github.com/kcrawley/terraform/tree/aws/add-rds-snapshot-support

i would like to add tests and documentation for my changes. i expect i will have time next week to research the testing patterns in this application. this was my first attempt at golang.

**Comment by catsby** [comment]
Thanks @kcrawley – feel free to post your work in a PR if you have any questions or need guidance anywhere

**Comment by catsby** [comment]
I'm going to close this issue for now. I'll keep my eyes open for a PR here :)

**Comment by kcrawley** [comment]
PR #7158
