### ISSUE TITLE
Execute scripts on remote VM after reboot

### ISSUE THREAD

**Issue by siddheshwar-more** [hashicorp/terraform#7093]
Hello 

@sethvargo 

I've scenario of dc setup on windows vm (GCE) which causing the reboot of vm after setup. I've run some scripts on same after reboot- could you please suggest the solution for this in terraform!

Thanks

**Comment by dandunckelman** [comment]
@stack72 This was closed w/ no explanation.

I'm looking for this as well.  Is there a workaround or is this considered a "won't fix" issue w/ Terraform?
