### ISSUE TITLE
Best way to find out what provider resources I can `terraform import`?

### ISSUE THREAD

**Issue by PaulCapestany** [hashicorp/terraform#7099]
So far, the best way I've found for figuring out what provider resources might be importable via `terraform import` has been running this command from the terraform repo: 

`find builtin -iname "*import*test.go"`

↑ would that currently be the easiest approach for finding out what's importable, or am I missing something way more obvious?

P.S. this new `import` feature totally rocks, so I'm in no way complaining, just very much looking forward to kicking the tires on all the possible importable resources :)

**Comment by jen20** [comment]
Hi @PaulCapestany! Right now we haven't added this to the documentation, but we will do. There is also a plan to expose this via the CLI. In the meantime, you can tell whether a given resource has import functinoality implemented by looking at the code for an `Importer` - for example:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_vpc.go#L21-L23

Sorry this isn't more discoverable right now!

**Comment by PaulCapestany** [comment]
@jen20 thanks for the tip!

For anyone else looking for a simple bash one-liner in the meantime, this does the trick for me:

`find ./builtin/providers -type f | xargs grep -l ResourceImporter`

Sample output of all (current) importable resources:

```
./builtin/providers/aws/resource_aws_autoscaling_group.go
./builtin/providers/aws/resource_aws_customer_gateway.go
./builtin/providers/aws/resource_aws_ebs_volume.go
./builtin/providers/aws/resource_aws_eip.go
./builtin/providers/aws/resource_aws_elb.go
./builtin/providers/aws/resource_aws_flow_log.go
./builtin/providers/aws/resource_aws_instance.go
./builtin/providers/aws/resource_aws_internet_gateway.go
./builtin/providers/aws/resource_aws_key_pair.go
./builtin/providers/aws/resource_aws_launch_configuration.go
./builtin/providers/aws/resource_aws_nat_gateway.go
./builtin/providers/aws/resource_aws_network_acl.go
./builtin/providers/aws/resource_aws_network_interface.go
./builtin/providers/aws/resource_aws_placement_group.go
./builtin/providers/aws/resource_aws_route53_delegation_set.go
./builtin/providers/aws/resource_aws_route53_health_check.go
./builtin/providers/aws/resource_aws_route53_zone.go
./builtin/providers/aws/resource_aws_route_table.go
./builtin/providers/aws/resource_aws_security_group.go
./builtin/providers/aws/resource_aws_subnet.go
./builtin/providers/aws/resource_aws_vpc.go
./builtin/providers/aws/resource_aws_vpc_dhcp_options.go
./builtin/providers/fastly/resource_fastly_service_v1.go
./builtin/providers/triton/resource_firewall_rule.go
./builtin/providers/triton/resource_key.go
./builtin/providers/triton/resource_machine.go
./builtin/providers/triton/resource_vlan.go
```
