### ISSUE TITLE
Error Attaching Subnet with Route Table

### ISSUE THREAD

**Issue by smmnazar** [hashicorp/terraform#7100]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform Version: 0.6.16

### Affected Resource(s)
aws_route_table_association.public-rtb.0

### Terraform Configuration Files

```
resource "aws_subnet" "public" { 
   vpc_id                  = "${var.vpc_id}"
   count                   = "${var.pub_count}"
   cidr_block              = "${cidrsubnet(var.vpc_cidr, 6, count.index + var.pub_offset)}"  
    availability_zone      = "${element(split(",", var.availability_zones), count.index)}"
   map_public_ip_on_launch = false
}

resource "aws_internet_gateway" "igw" {
    vpc_id = "${var.vpc_id}"
 }

resource "aws_route_table" "public-route-table" {
   vpc_id = "${var.vpc_id}"
   route {
      cidr_block = "0.0.0.0/0"
      gateway_id = "${aws_internet_gateway.igw.id}"
   }
}
resource "aws_route_table_association" "public-rtb" {
   count          = "${var.pub_count}"
   subnet_id      = "${element(split(",",aws_subnet.public.*.id), count.index)}"
   route_table_id = "${aws_route_table.public-route-table.id}"
}
```

### Debug Output
* aws_route_table_associatiton.public-rtbe_table_association.public-rtb.3: Creat
ion c.0: diffs didn'ot match mduring apply. This is a plete
bug with Terraform and should be reported as a GitHub Issue.

### Panic Output
    Mismatch reason: diff RequiresNew; old: true, new: false
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]
*terraform.ResourceAttrDiff{"subnet_id":*terraform.ResourceAttrDiff{Old:"", New:
"${element(split(\",\",aws_subnet.public.*.id), count.index)}", NewComputed:fals
e, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "r
oute_table_id":*terraform.ResourceAttrDiff{Old:"", New:"${aws_route_table.public
-route-table.id}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(ni
l), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string
]*terraform.ResourceAttrDiff{"route_table_id":*terraform.ResourceAttrDiff{Old:""
, New:"rtb-7ba98b1c", NewComputed:false, NewRemoved:false, NewExtra:interface {}
(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

### Expected Behavior
The subnets has to be associated with route table. 

### Actual Behavior
4 subnets were created among them only 3 subnets were associated with route table successfully and getting error while associating the 4th subnet with route table

### Steps to Reproduce
1. `terraform apply`

**Comment by catsby** [comment]
Hey @smmnazar – sorry for the trouble here. I believe the way you're referencing `subnet_id` in `aws_route_table_association.public-rtb` could be at fault here. I believe you'll want this:

```
subnet_id      = "${element(aws_subnet.public.*.id, count.index)}"
```

When I tried to use your format, I received a syntax error. 

I modified your example slightly to stand alone, like so:

```hcl
resource "aws_vpc" "tester" {
  cidr_block = "10.0.0.0/16"

  tags {
    name = "tf_test_sub_rt"
  }
}

variable "aws_availability_zones" {
  default = "us-west-2a,us-west-2b,us-west-2c"
}

resource "aws_subnet" "public" {
  vpc_id = "${aws_vpc.tester.id}"
  count  = "${length(split(",", var.aws_availability_zones))}"

  #cidr_block              = "${cidrsubnet(aws_vpc.tester.cidr_block, 6, count.index + var.pub_offset)}"
  cidr_block              = "10.0.${count.index}.0/24"
  availability_zone       = "${element(split(",",var.aws_availability_zones), count.index)}"
  map_public_ip_on_launch = false
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.tester.id}"
}

resource "aws_route_table" "public-route-table" {
  vpc_id = "${aws_vpc.tester.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.igw.id}"
  }
}

resource "aws_route_table_association" "public-rtb" {
  count          = "${length(split(",", var.aws_availability_zones))}"
  subnet_id      = "${element(aws_subnet.public.*.id, count.index)}"
  route_table_id = "${aws_route_table.public-route-table.id}"
}
```

The main modification being the `subnet_id` reference. I'm able to create Routes with the Subnets without trouble. 

I'm going to close this issue for now. Please let me know if you have more information that can help me reproduce this.
