### ISSUE TITLE
Overriding aws_route with aws_vpn_connection_route: fail to delete aws_route ressources

### ISSUE THREAD

**Issue by DjinnS** [hashicorp/terraform#7102]
Hi there,

### Contexte
I want to update my configuration by using route propagation between VPN Connection and Route Table instead of setting routes both in Route Table and VPN Connection (AWS best practice).

### Terraform Version
$ terraform -v
Terraform v0.6.16

### Affected Resource(s)
- aws_vpn_connection_route 
- aws_route issue

### Terraform Configuration Files

New configuration:
```
resource "aws_vpn_connection_route" "route_is" {
    destination_cidr_block = "10.1.71.0/24"
    vpn_connection_id = "${aws_vpn_connection.main.id}"
}
resource "aws_vpn_connection_route" "route_mon" {
    destination_cidr_block = "10.255.0.0/16"
    vpn_connection_id = "${aws_vpn_connection.main.id}"
}
```

Old configuration (disable at runtime):
```
resource "aws_route" "route_mon" {
    route_table_id = "${aws_route_table.route_table.id}"
    destination_cidr_block = "10.255.0.0/16"
    gateway_id = "${aws_vpn_gateway.vpn_gateway.id}"
    depends_on = ["aws_route_table.route_table"]
}

resource "aws_route" "route_is" {
    route_table_id = "${aws_route_table.route_table.id}"
    destination_cidr_block = "10.1.71.0/24"
    gateway_id = "${aws_vpn_gateway.vpn_gateway.id}"
    depends_on = ["aws_route_table.route_table"]
}
```

### Expected Behavior
First delete "route_mon" and "route_is" on "aws_route" then create "route_mon" and "route_is" on "aws_vpn_connection_route".

### Actual Behavior
First create "route_mon" and "route_is" on "aws_vpn_connection_route" and then try to delete "route_mon" and "route_is" on "aws_route" and fail:

```
Error applying plan:


2 error(s) occurred:


* aws_route.route_is: InvalidRoute.NotFound: no route with destination-cidr-block 10.1.71.0/24 in route table rtb-508b0f34
        status code: 400, request id: f64e3edd-0376-4c6d-9c7d-fc1c47ffcfef
* aws_route.route_mon: InvalidRoute.NotFound: no route with destination-cidr-block 10.255.0.0/16 in route table rtb-508b0f34
        status code: 400, request id: 3cc4c1fb-ee01-4168-84c2-c3079c758c98
```

### Steps to Reproduce
1. add route to a route table
2. add new configuration to terraform to add route on aws_vpnc_connection_route (the same route)
3. delete old configuration for route table in terraform
4. terraform apply

**Comment by catsby** [comment]
Hey @DjinnS – sorry for the trouble here. I did some investigating but wasn't able to reproduce your findings. 

Here's the config I used:

```hcl
resource "aws_vpc" "tiger" {
  cidr_block = "10.16.0.0/16"

  enable_dns_support   = true
  enable_dns_hostnames = true

  tags {
    Name = "tiger"
  }
}

resource "aws_vpn_gateway" "vpn_gateway" {
  vpc_id = "${aws_vpc.tiger.id}"
}

resource "aws_subnet" "tiger" {
  vpc_id                  = "${aws_vpc.tiger.id}"
  cidr_block              = "10.16.0.0/16"
  map_public_ip_on_launch = true
}

resource "aws_internet_gateway" "tiger" {
  vpc_id = "${aws_vpc.tiger.id}"
}

resource "aws_route_table" "public" {
  vpc_id = "${aws_vpc.tiger.id}"
}

resource "aws_customer_gateway" "customer_gateway" {
  bgp_asn    = 60000
  ip_address = "172.0.0.1"
  type       = "ipsec.1"
}

resource "aws_vpn_connection" "main" {
  vpn_gateway_id      = "${aws_vpn_gateway.vpn_gateway.id}"
  customer_gateway_id = "${aws_customer_gateway.customer_gateway.id}"
  type                = "ipsec.1"
  static_routes_only  = true
}

 resource "aws_route" "route_mon" { */
   route_table_id = "${aws_route_table.public.id}" */
   destination_cidr_block = "10.255.0.0/16" */
   gateway_id = "${aws_vpn_gateway.vpn_gateway.id}" */
   depends_on = ["aws_route_table.public"] */
}

#resource "aws_vpn_connection_route" "route_mon" {
# destination_cidr_block = "10.255.0.0/16"
#
#  vpn_connection_id = "${aws_vpn_connection.main.id}"
#}
```

This applied successfully. If I comment out `aws_route.route_mon` and uncomment `aws_vpn_connection_route.route_mon`, Terraform `plan` shows removing the route and adding the vpn connection route as I expect. Applying the plan succeeds. Can you help me spot what I'm missing?

**Comment by DjinnS** [comment]
Hi @catsby, thank you for your time.

I use the same config as you and, as you, no errors, "plan" and "apply" works fine.

I need to compare your and mine configuration. May be I miss something :)

**Comment by catsby** [comment]
I'm going to close this for now then. Please let me know if you are able to pinpoint anything here.

Thanks!

**Comment by DjinnS** [comment]
Hi,

You can ignore this issue. After many tests I find a mistake on my VPC causing theses errors.

Sorry about that :/

**Comment by catsby** [comment]
@DjinnS no worries! Thanks for following up
