### ISSUE TITLE
Cut v0.3.6 please?

### ISSUE THREAD

**Issue by drnic** [hashicorp/terraform#711]
There is some sweet goodness on HEAD that I'd love in a new cut release, if you're looking for Happy Holiday gifts to give away :)

**Comment by drnic** [comment]
Can we reopen this issue until v0.3.6 is released? Am trying to document in our README the upstream issues we're blocked on/working around/excited about (via https://blog.starkandwayne.com/2014/12/30/live-github-pr-status-in-your-blogs-docs/)

**Comment by armon** [comment]
Sure!

**Comment by mitchellh** [comment]
This might be possible now because the BC changes were fixed over the past couple weeks. I'll take a look shortly and see if we can get a release out.

**Comment by mitchellh** [comment]
Released!

**Comment by drnic** [comment]
Thanks!
