### ISSUE TITLE
Remote state cache has no remote info

### ISSUE THREAD

**Issue by OllyGinger** [hashicorp/terraform#7112]
Hi,

I've recently started converting my monolithic configurations to modules so that I can support multiple environments, as described here: https://atlas.hashicorp.com/help/intro/use-cases/multiple-environments

I'm not using the remote state config stuff, and running `terraform remote config -disable` mentions that it's already disabled

But after module'fying my configs and attempting a plan/apply I just get the following error: 'Remote state cache has no remote info'

I supply a state file using -state if that makes any difference.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

core
### Terraform Configuration Files

``` hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
### Debug Output

https://gist.github.com/OllyGinger/daa1e9cf7d20c0fd293c6f93579b2756
### Expected Behavior

Plan/apply should have run
### Actual Behavior

'Remote state cache has no remote info'
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
### Important Factoids

EC2

**Comment by OllyGinger** [comment]
For what it's worth, none of the remote state has changed between the monolithic and module version

**Comment by phinze** [comment]
Hi @OllyGinger - sorry for the trouble here! That error message only shows up in a few cases:

 * If a plan saved via `terraform plan -out=foo.tfplan` is created w/ remote state configured and applied without it
 * If a `.terraform/terraform.tfstate` (the state cache file when using remote state) file is present.

My guess in this case would be the latter - can you check to see if there is a `.terraform/terraform.tfstate` file on disk? If so, moving that out of the way should fix the error message.

**Comment by phinze** [comment]
(Removing the `release-0.7` tag since this is not 0.7.x specific.)

**Comment by ajcrites** [comment]
@phinze I am having a similar issue with remote state in terraform 0.7.4. I already created an infrastructure and a local state file that I uploaded to s3. Then, I tried adding remote state in the config with `data`, but this didn't seem to do anything. When I run `terraform remote config` with appropriate settings, it creates a `.terraform/terraform.tfstate` file that looks correct -- it's the same file as the one I uploaded to S3, but now I get

    Remote state cache has no remote info

whenever I try to do anything. I can't proceed unless I remove the `.terraform/terraform.tfstate` file, but when I do that it says there is no remote config anymore. More details in #9089

**Comment by myoung34** [comment]
I fixed this with some work.
Our apply was done through CI, and it errored on the `terraform remote config` command.

From CI i moved the `terraform.tfstate.backup` to `.terraform.tfstate` and got this error. I fixed it by editing `terraform.tfstate` after the move and adding the missing 

```
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "bucket",
            "key": "path/to/terraform.tfstate",
            "region": "us-east-1"
        }
    },
```

inside of it above the `modules` key. I pushed this to where it needs to be in s3 via `aw s3 cp`, did `rm -rf .terraform`, then proceeded as normal, running `terraform remote config` and everything started working.

**Comment by riponbanik** [comment]
I am using terraform 0.7.13, first time I put the above config like below can run terraform plan but it remote remote config automatically from terraform.tfstate. Next time I run it it shows error "Remote state cache has no remote info"

{
    "version": 3,
    "terraform_version": "0.7.13",
    "serial": 3,
    "lineage": "xxx",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ],
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "xx-remote-state",
            "key": "xxxx,
            "region": "ap-southeast-2"
        }
    }
}

**Comment by fgimian** [comment]
Same exact problem here and this one i is a pretty big one .  The `remote` section of terraform.tfstate is not added when adding the remote!

**Comment by tamsky** [comment]
In my case the error message resolved after a few minutes.

I believe my issue may stem from the read-after-write semantics of S3,
which, I believe, states that even though I successfully `put` the object
it may not immediately have a value to return for a `get` operation.

**Comment by myoung34** [comment]
S3 has read after write consistency in the last while: http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#Regions

**Comment by fgimian** [comment]
Yeah, after I added that config in manually, it's been OK since.  Thanks guys!

**Comment by tamsky** [comment]
Maybe this is it:
> Amazon S3 offers eventual consistency for overwrite PUTS and DELETES in all regions.

If the original object was empty (or its nearest equivalent empty tfstate struct), and it was overwritten, then maybe?

**Comment by apparentlymart** [comment]
Hi @OllyGinger, and everyone else who commented here! Sorry for these issues and sorry we've let this issue languish for so long.

The good news is that the mechanism for remote state was completely redesigned in 0.9, eliminating the local cache file and placing the remote configuration in its own configuration file separately from the state.

As a consequence, this issue can no longer occur since the codepath that raised it no longer exists. Therefore I'm going to close this issue out. If anyone happens to encounter similar-looking issues with the new system (post-0.9) then I'd ask that they be opened as new issues so we can triage and investigate them separately. Thanks again!
