### ISSUE TITLE
Connection isn't configured for provisioners to use inside of azurerm_virtual_machine

### ISSUE THREAD

**Issue by colemickens** [hashicorp/terraform#7122]
`Terraform v0.7.0-rc1 (301da85f30239e87b30db254a25706a6d41c2522)`
- azurerm_virtual_machine
- remote_exec
### Expected Behavior

It would use the information given during configuration to `SetConnInfo` so that provisioners can connect automatically.
### Actual Behavior

This isn't implemented and so it can't connect and just fails in an infinite loop.

```
azurerm_virtual_machine.master_vm (remote-exec): Connecting to remote host via SSH...
azurerm_virtual_machine.master_vm (remote-exec):   Host:
azurerm_virtual_machine.master_vm (remote-exec):   User: root
azurerm_virtual_machine.master_vm (remote-exec):   Password: false
azurerm_virtual_machine.master_vm (remote-exec):   Private key: false
azurerm_virtual_machine.master_vm (remote-exec):   SSH Agent: false
```

**Comment by stack72** [comment]
Hi @colemickens 

I'm not quite following what the issue is here?

When you give a virtual_machine a username and a password and a static ip then you can connect to it with a remote-exec for provisioning

Is there something different you need?

P.

**Comment by colemickens** [comment]
I was thinking that this, in the `google` provider lets the file provisioner work without having to manually specify the connection details: https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance.go#L719

And I was hoping something similar could be done in the Read function for the azurerm_virtual_machine.

**Comment by colemickens** [comment]
Hi @jen20. Is it possible the wrong issue got closed? The NSG/polling issue was https://github.com/hashicorp/terraform/issues/7153 rather than this one.

**Comment by stack72** [comment]
sorry, my fault! I had the wrong issue in my PR

**Comment by josephholsten** [comment]
@stack72 is this a thing we should solve with better documentation? seems like the current approach is to
```
  provisioner "remote-exec" {
    inline = [
      "/tmp/init.sh",
    ]
    connection {
      host = "${element(azurerm_public_ip.node.*.ip_address, count.index)}"
    }
  }
```

Does that seem correct?

**Comment by josephholsten** [comment]
well, if https://github.com/hashicorp/terraform/issues/6634 is still an issue then my approach won't work
