### ISSUE TITLE
Openstack - graceful instance termination

### ISSUE THREAD

**Issue by alkersan** [hashicorp/terraform#7129]
Hello @jtopjian. Is it possible to make removal of compute instances graceful? Currently Openstack provider destroys instances with [`Delete`](http://gophercloud.io/docs/compute/#delete-server) call (a.k.a. `terminate`) which don't give a chance for vm to stop it's services. E.g. consul agent, if configured with [`leave_on_terminate`](https://www.consul.io/docs/agent/options.html#leave_on_terminate) will not receive `SIGTERM` and will not deregister itself, thus leaving unhealthy node visible to cluster members.

What if prior to deletion, call [Stop](http://gophercloud.io/docs/compute/#stop-server) (from [`extensions/startstop`](https://godoc.org/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/startstop) package), which should transit machine to `SHUTOFF`? This can be done at best effort basis, with lower timeout (say 1~3 mins, instead of default 10 mins for creation/deletion), doing deletion in any case afterwards.

**Comment by jtopjian** [comment]
@alkersan interesting idea!

What do you think of having this as an opt-in feature? For example, a new argument called `stop_before_destroy`?

**Comment by alkersan** [comment]
Yes, this enhancement is behavior changer and opt-in is needed. And as far as I understand, `start\stop` lives in `extensions` namespace because it was added later to `nova` api, thus it may simply not work for every openstack installation.

I've started working on it, will add PR soon.

**Comment by jtopjian** [comment]
Closing this as it was fixed in #7184
