### ISSUE TITLE
Deleted aws_customer_gateway is not re-created

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7137]
Terraform does not re-create a deleted AWS customer gateway (CGW). If I create a CGW with Terraform, then delete it out-of-band of Terraform (via CLI or the AWS console), Terraform will fail with a _Error finding CustomerGateway_ error on the next refresh, plan, or apply, rather than re-creating the CGW.

### Terraform Version
```
$ terraform version
Terraform v0.6.16
```

### Affected Resource(s)
- aws_customer_gateway

### Terraform Configuration Files
```hcl
resource "aws_customer_gateway" "main" {
  bgp_asn    = 60000
  ip_address = "172.83.124.10"
  type       = "ipsec.1"

  tags {
    Name = "recreate-test"
  }
}

output "cgw_id" {
  value = "${aws_customer_gateway.main.id}"
}
```

### Expected Behavior
Terraform should recognize that the CGW has been deleted and re-create it if still present in my configuration.

### Actual Behavior
Terraform fails to refresh, plan, or apply with a _Error finding CustomerGateway_ error.

### Steps to Reproduce
1. `terraform apply`
1. `aws ec2 describe-customer-gateways --customer-gateway-id $(terraform output cgw_id)`
1. `aws ec2 delete-customer-gateway --customer-gateway-id $(terraform output cgw_id)`
1. `aws ec2 describe-customer-gateways --customer-gateway-id $(terraform output cgw_id)`
1. Repeat previous step until the CGW is no longer present. Note: It will stay in `deleted` state for 30 minutes or more. To reproduce, you must wait until after the CGW is no longer present in the response.
1. `terraform apply`
1. Observe Terraform fail with an error.

### Output

```
$ terraform plan
Refreshing Terraform state prior to plan...

aws_customer_gateway.main: Refreshing state... (ID: cgw-48cb2521)
Error refreshing state: 1 error(s) occurred:

* aws_customer_gateway.main: [ERROR] Error finding CustomerGateway: cgw-48cb2521
$
```

### References
- _Deleted aws_customer_gateway is still updated_ #7136

**Comment by stack72** [comment]
This will be fixed by the solution as provided in #7136 

Closing this to track the changes / requests there
