### ISSUE TITLE
aws_api_gateway_integration missing "Request Body Passthrough" feature

### ISSUE THREAD

**Issue by forbesmyester** [hashicorp/terraform#7141]
**version:** 0.6.16
**resource:** aws_api_gateway_integration
**missing feature:**

In the UI there is a tick box in "Body Mapping Templates > Request Body Passthrough" which has possible values of "When no template matches the request Content-Type header", "When there are no templates defined (recommended)" or "Never". I wish to select "Never" but this seems impossible in Terraform.

In the CLI client it is documented at [http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-integration.html](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-integration.html) and is the parameter `--passthrough-behavior`

**Comment by iceycake** [comment]
Looks like we have to update to aws sdk 1.2.7 in order to use the new API for PassthroughBehavior

**Comment by stack72** [comment]
Closed via #7801
