### ISSUE TITLE
Add support for encryption and logging to Amazon Kinesis Firehose

### ISSUE THREAD

**Issue by ap-dji** [hashicorp/terraform#7152]
Firehose supports encryption for data delivered to s3 and error logging to cloudwatch logs.

http://docs.aws.amazon.com/firehose/latest/dev/basic-create.html
http://docs.aws.amazon.com/firehose/latest/dev/monitoring-with-cloudwatch-logs.html

**Comment by morgante** [comment]
@stack72 Was this fixed?

**Comment by stack72** [comment]
Hi @morgante this will be in Terraform 0.7.5 :)
