### ISSUE TITLE
Terraform against local Triton lab setup

### ISSUE THREAD

**Issue by neuroserve** [hashicorp/terraform#7155]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
triton_machine

### Terraform Configuration Files
provider "triton" {
  account      = ""
  key_id       = ""
  key_material = ""
  url          = ""
}

resource "triton_machine" "dcos-bootstrap" {
  name    = "dcos-bootstrap"
  image   = "d8e65ea2-1f3e-11e5-8557-6b43e0a88b38"
  package = "sample-2G-kvm"

  tags {
    role = "bootstrap"
  }

  connection {
    host        = "${self.primaryip}"
    private_key = "${file("/root/.ssh/sdc-docker-bla.id_rsa")}"
  }

  provisioner "remote-exec" {
    inline = ["/bin/true"]
  }
}

### Panic Output
https://gist.github.com/neuroserve/6d900714fab98a1e496236c8bacbf3bb

### Expected Behavior
I would have expected to see the provisioning of a triton kvm-instance

### Actual Behavior
Terraform crashed.

### Important Factoids
I'm running terraform against my local Triton Lab (not against Joyents public cloud). I'm not sure, whether that could be a factor.

**Comment by jen20** [comment]
Hi @neuroserve! Can you confirm what the URL you are using for your local setup is? The crash to me suggests a bug in Joyent's gosign library which is incorrectly detecting local setups:

https://github.com/joyent/gosign/blob/master/auth/auth.go#L117-L122

cc @BrianHicks, @misterbisson

**Comment by neuroserve** [comment]
It is a local URL. It does not resolve in DNS. Its configured in /etc/hosts in the VM that's running terraform. It's like https://cloudapi.my-dc-1.cns.mylab.de/

**Comment by sodre** [comment]
@neuroserve This is almost surely the issue in joyent/gosign#8. Can you remove the "trailing slash" in your SDC_URL and try again?

@jen20, I will put a PR to update gosign to the latest version which has the fix.

**Comment by neuroserve** [comment]
Removing the trailing slash works! Provisioning is now possible. Thx.
