### ISSUE TITLE
Add encryption to aws_ami_copy

### ISSUE THREAD

**Issue by davidbailey** [hashicorp/terraform#7157]
AWS has added the ability to encrypt an ami with kms during the copy.
```
$ aws ec2 copy-image -r source_region -s source_ami_id \
  [-n ami_name] [-d ami_description] [-c token] \
  [--encrypted] [--kmsKeyID keyid]
```
Can we add the encrypted and kmsKeyID options to the aws_ami_copy module?

### Terraform Configuration Files
```hcl
resource "aws_ami_copy" "ami_copy" {
    name = "ami_copy"
    source_ami_id = "${var.ami}"
    source_ami_region = "${var.aws_region}"
    tags {
        Creator = "${var.creator}"
    }   
}
```
### References
- https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/

**Comment by stack72** [comment]
Hi @rbuels 

Thanks for the poke on this one - opened #7988 for this

Will get it to the site shortly

Paul
