### ISSUE TITLE
Using lists in template_file doesn't work

### ISSUE THREAD

**Issue by jtopper** [hashicorp/terraform#7160]
The new support for structured variables appears not to be usable in `template_file` resources.

### Terraform Version
Current HEAD:
`Terraform v0.7.0-dev (8f216563aa4a7c000056ea9ae98dfc526b595f5c)`

### Affected Resource(s)

* template_file

### Terraform Configuration Files
```hcl
resource "template_file" "repo_bucket_iam_policy" {
    template = "${join(",",test)}"
    vars = {
        test = [ "one", "two" ]
    }
}
```

### Debug Output
Probably unnecessary, but ask if you need it.

### Panic Output
None

### Expected Behavior
Plan should have completed cleanly.

### Actual Behavior
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


Error running plan: 1 error(s) occurred:

* vars: 1 error(s) decoding:

* '[test]' expected type 'string', got unconvertible type '[]interface {}'

```

### Steps to Reproduce
`terraform plan`

**Comment by phinze** [comment]
Calling this a core bug, since it's not a template specific thing.

**Comment by phinze** [comment]
For now we're going to validate that all `vars` are strings. Eventually we can look into upgrading the template language.

**Comment by bernadinm** [comment]
@phinze is this related to https://github.com/hashicorp/terraform/issues/9488 as well?
