### ISSUE TITLE
init_type not recognized for vsphere virtual disk resource

### ISSUE THREAD

**Issue by sputnik13** [hashicorp/terraform#7165]
[virtual disk resource docs](https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/vsphere/r/virtual_disk.html.markdown) indicates that a virtual disk can be specified as a "thin" disk with an "init_type" key but this does not work.

TF version = v0.7.0-dev (8f216563aa4a7c000056ea9ae98dfc526b595f5c)

TRACE level log posted in [gist](https://gist.github.com/sputnik13/fc8e0c52802bc6b87f68a3e1bd5612b8)

**Comment by mixacha** [comment]
This works in 0.6.15
@chrislovecnm could this be related to thing I saw with acct tests in DRS pr?

**Comment by chrislovecnm** [comment]
Yah ... Need to tag this with the developers name when I am not on mobile.

**Comment by mixacha** [comment]
Looking at the code it seems that init_type was changed to type
`				if v, ok := disk["type"].(string); ok && v != "" {
					newDisk.initType = v
				}`

@sputnik13 can you test using 'type' instead of 'init_type' in your resource definition ?

**Comment by dkalleg** [comment]
@sputnik13 @mixacha @chrislovecnm 
Looks like a simple oversight when refactoring some arguments, this should do it:
https://github.com/hashicorp/terraform/pull/7200
