### ISSUE TITLE
aws  instance/subnet implicit dependency not established when subnet is dynamic

### ISSUE THREAD

**Issue by russroy** [hashicorp/terraform#717]
Terraform recognizes an implicit dependency between an aws instance and its associated subnet resource when the subnet arg has a static value:

  subnet_id = "${aws_subnet.cd_sandbox.subnet_id}"

But when the value is expressed as a lookup function (though the expression evaluates correctly to the above in the "plan") the dependency is *not* recognized:

  subnet_id = "${aws_subnet.${lookup(var.tbl, \"env_name\")}.id}"

The error:
aws_instance.rundeck: Error: Error launching source instance: The subnet ID '${aws_subnet.cd-sandbox.id}' does not exist (InvalidSubnetID.NotFound)

**Comment by pmoust** [comment]
I think this has been fixed

**Comment by phinze** [comment]
(a) I also believe this has been fixed
(b) We generally discourage using dynamic values in resource names and point users to Modules instead as units of dynamic reuse

Anybody on this thread can feel free to follow up if you believe there's more to track here.
