### ISSUE TITLE
aws_ecr_repository missing identifier that works for image param in task.json

### ISSUE THREAD

**Issue by aarcro** [hashicorp/terraform#7180]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_ecr_repository

### Terraform Configuration Files
```hcl
resource "aws_ecr_repository" "webapp" {
  name = "webapp"
}

output "registry.dns_name" {
  value = "${aws_ecr_repository.webapp.repository_url}"
}
```

### Expected Behavior
url should not have a protocol on it eg: `<account_id>.dkr.ecr.us-east-1.amazonaws.com/webapp`

### Actual Behavior
url has protocol: `https://<account_id>.dkr.ecr.us-east-1.amazonaws.com/webapp`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Because the protocol is there you cannot pass the value into a json task definition. Because there's no output values in the appropriate format you have to use variables and build something like:
```json
[{
"image": "${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/${webapp_name}:${webapp_tag}"
}]
```

**Comment by stack72** [comment]
Hi @aarcro 

So we have weird situation on this one. Firstly, I see the fact that people use that output of the URL for other purposes and need to add the protocol to it. Secondly, I can see your specific use-case here.

I *think* the right way to go may to be use an interpolation function when you are adding the variable to the your task definition. If we don't use an interpolation func here, then we may actually need to keep 2 variables that can be access e.g. `repository_url` and something like `raw_url`

What do you think here?

Paul

**Comment by aarcro** [comment]
Yeah, I'm perfectly fine with a new output param. Honestly wouldn't want to change the behavior for people depending on it.

Is there a interpolation func that can apply a regex to remove the protocol?

**Comment by shinzui** [comment]
@aarcro I just use `"${replace(var.some_ecr_repository_url, "https://", "")}"`

**Comment by stack72** [comment]
@aarcro are you good with the example that @shinzui gave above?

P.

**Comment by aarcro** [comment]
@stack72 Yeah, that's a good stop gap.

**Comment by stack72** [comment]
Thanks for the fast response @aarcro

**Comment by RyanBowlby-Reflektion** [comment]
It's odd, passing this output into a task definition seems like the most often used pattern. Yet, doing so requires use of the replace() func?

Perhaps I will create a simple aws_ecr_repository module that does the replace on the output and additionally adds some policy defaults. :/

**Comment by ligustah** [comment]
Is replacing (removing) the "https://" still the recommended way of doing this? If so, are there any plans on making it easier to use the aws_ecr_repository with ecs_task_definition resources? Or, to be more precise: will the aws_ecr_repository resource provide support for a URI that can be directly handed to the docker dameon?
```
docker pull https://<ID>.dkr.ecr.<REGION>.amazonaws.com/<IMAGE>:latest

Error parsing reference: "https://<ID>.dkr.ecr.<REGION>.amazonaws.com/<IMAGE>:latest" is not a valid repository/tag
```
