### ISSUE TITLE
panic on 0.7.0rc2 terraform show

### ISSUE THREAD

**Issue by trauts2** [hashicorp/terraform#7187]
Attached crash log with scripts including state

[failing-script.zip](https://github.com/hashicorp/terraform/files/317226/failing-script.zip)
[modules.zip](https://github.com/hashicorp/terraform/files/317229/modules.zip)
Hi there,

### Terraform Version

`0.7.0-rc2`

**Comment by trauts2** [comment]
Here's trace output

Stus-MacBook-Air-5:with-bastion stu$ terraform show
2016/06/15 16:14:18 [INFO] Terraform version: 0.7.0 rc2 46a0709bba004d8b6e0eedad411270b3ae135a9e
2016/06/15 16:14:18 [DEBUG] Detected home directory from env var: /Users/stu
2016/06/15 16:14:18 [DEBUG] Detected home directory from env var: /Users/stu
2016/06/15 16:14:18 [DEBUG] Attempting to open CLI config file: /Users/stu/.terraformrc
2016/06/15 16:14:18 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/06/15 16:14:18 [DEBUG] Detected home directory from env var: /Users/stu
2016/06/15 16:14:18 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x95beb]

goroutine 1 [running]:
panic(0x2e07080, 0xc8200120e0)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/command.formatStateModuleExpand(0xc8202d9180, 0xc8202df880, 0xc820157980)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format_state.go:114 +0x54b
github.com/hashicorp/terraform/command.FormatState(0xc820157980, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format_state.go:43 +0xb12
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc8201ee2d0, 0xc82000a310, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/show.go:107 +0xc08
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200dce40, 0xc8202d0390, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xb02
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x95beb]

goroutine 1 [running]:
panic(0x2e07080, 0xc8200120e0)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/command.formatStateModuleExpand(0xc8202d9180, 0xc8202df880, 0xc820157980)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format_state.go:114 +0x54b
github.com/hashicorp/terraform/command.FormatState(0xc820157980, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/format_state.go:43 +0xb12
github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc8201ee2d0, 0xc82000a310, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/show.go:107 +0xc08
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200dce40, 0xc8202d0390, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xb02
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by phinze** [comment]
Hi @trauts2 - thanks for the report!

This has been fixed in 75ab4a99702d3e31cbd295f5ee74f60b440a8912 and will show up in the next release. 👍
