### ISSUE TITLE
AWS Provider: support ~/.aws/config

### ISSUE THREAD

**Issue by cjeanneret** [hashicorp/terraform#7192]
Hello,

Currently, aws provider supports the "profile" setting, allowing to pass directly a profile instead of the access keys. That works well.
Apparently, it directly goes in the ~/.aws/credentials file in order to take the matching authentication information. The file format is as follow:

``` Ini
[profile_name1]
aws_access_key_id= ....
aws_secret_access_key = ...
[profile_name2]
aws_access_key_id= ....
aws_secret_access_key = ...
```

So far, so good, it just works.

Now, there's a second file in ~/.aws directory: config.
This one has a small difference regarding its structure and information:

``` Ini
[profile profile_name1]
region = eu-west-1
[profile profile_name2]
region = us-west-1
```

As you might guess, credentials shouldn't be in that file, but there are other stuff, like the region.
Currently, when we use the AWS provider, we ask the user for the profile name in order to get the credentials, but we still have to fix the region on the tf file.

It would be great if Terraform could take advantage of the ~/.aws/config file as well in order to find the region and, maybe, other specificities we might put in there in order to auto-complet the provider configuration.

Apparently, [there are a lot](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/provider.go#L20-L73) of possibilities, and that would also allow to set the "region" to non-required, like the profile and access keys.

Thank you!

Cheers,

C.

**Comment by bellkev** [comment]
I'm seeing this too. It looks like https://github.com/hashicorp/terraform/blob/1bd8b449e00bba44fd74bd2ea35677b4feb0dae3/builtin/providers/aws/provider.go#L59-L62 only handles env vars, so "or via a shared credentials file if profile is specified." in the docs is currently inaccurate for AWS region.

**Comment by jamielennox1** [comment]
I think this could be related to #6819

**Comment by syedaali** [comment]
+1 on Terraform reading region from AWS config file for the 'provider' loop instead of hard coding it in the Terraform file, or inputting as a variable through some other means. Right now I am doing something like this:

provider "aws" {
    profile 	    = 	"${var.awsprofile}"
    region          =   "us-west-2"
}

I would like to be able to do:

provider "aws" {
    profile 	    = 	"${var.awsprofile}"
    region          =   "${var.awsprofile.region}"
}

My AWS config file looks like this:

[profile my_aws_profile_name]
output=json
region=us-west-2

**Comment by evanstachowiak** [comment]
For what it's worth, this also makes the "aws_region" data source useless (which would have been great to use). Trying to use the provider with the aws_region data source results in a cycle:
`* Cycle: provider.aws, data.aws_region.current`

**Comment by craiglink** [comment]
just submitted this pull request to add support for .aws/config - https://github.com/hashicorp/terraform/pull/11734

**Comment by sirditschonweg** [comment]
Hello everybody,
I'm trying to install a server by Terraform automatically and then to raise the domain.
Everything works but I can not find the point Domain Join.
Thank you for any idea.
greeting
Jan
