### ISSUE TITLE
0.7-rc2: cannot pass "indexed" output from splat resources within module A to module B

### ISSUE THREAD

**Issue by modax** [hashicorp/terraform#7195]
Hi,

I think there is a problem with outputting attributes from splat resources from modules. When I later try to pass such an output to another module by extracting element from it, terraform fails to do that. I attach a test case which triggers this bug.

### Terraform Version
v0.7.0-rc2-22-g5fdcf5d

### Affected Resource(s)

Core issue. Related to support for lists in module parameters.

### Terraform Configuration Files

mod/mod.tf
```hcl
variable "param" {
  type = "list"
}

resource "template_file" "tmpl" {
  count = "2"
  template = "doesnt"
}

output "out_from_splat" {
  type = "list"
  value = [ "${template_file.tmpl.*.rendered}" ]
}
```

test.tf
```hcl
module "mod1" {
  source = "mod"
  param = [ "this", "one", "works" ]
}

module "mod2" {
  source = "mod"
  param = [ "${module.mod1.out_from_splat[0]}" ]
  #param = [ "${element(module.mod1.out_from_splat, 0)}" ]
}
```

### Expected Behavior
`terraform plan` should have succeeded.

### Actual Behavior
`terraform plan` fails with:

```
Error configuring: 1 error(s) occurred:

* At column 3, line 1: list "module.mod1.out_from_splat" does not have any elements so cannot determine type. in:

${module.mod1.out_from_splat[0]}
```

### Steps to Reproduce
1. `terraform get`
2. `terraform plan`

### Important Factoids
If you try the same with ${element} (uncomment the line in `test.tf`), terraform will panic with division by 0.

**Comment by phinze** [comment]
Thanks for the detailed report here @modax, we'll definitely look at this soon. :ok_hand:

**Comment by jen20** [comment]
We should try to reproduce this once the fix for #7143 is merged (shortly).

**Comment by modax** [comment]
Hi @jen20,

I have tested current build and the bug is fixed. However, #7143 is not a PR which fixes it. I have bisected the commit to:

```
2356afde84ba499a2d977360f5a52dfe205227e3 is the first new commit
commit 2356afde84ba499a2d977360f5a52dfe205227e3
Author: James Nugent <james@jen20.com>
Date:   Thu Jun 23 21:14:09 2016 +0100

    core: Fix interpolation of unknown multi-variables
    
    This commit test "TestContext2Input_moduleComputedOutputElement"
    by ensuring that we treat a count of zero and non-reified resources
    independently rather than returning an empty list for both, which
    results in an interpolation failure when using the element function or
    indexing.
```

**Comment by jen20** [comment]
Thanks @modax - I mistyped here, I meant the pull request which was addressing #7143, which at that stage had no number! Thank you for confirming the fix, I'm going to take this and make it into a regression test to improve our test coverage in this area.

**Comment by jen20** [comment]
I've added the test in #7628, so will go ahead and close this. Thanks for your work here @modax!
