### ISSUE TITLE
vSphere Virtual Machine Resource - Cannot specify type of scsi controller

### ISSUE THREAD

**Issue by dkalleg** [hashicorp/terraform#7202]
Hi there,

Today we can only specify the controller types 'ide' and 'scsi', but govmomi supports 4 types of scsi controllers:
LSI Logic, BusLogic, VMWare Paravirtual, and LSI Logic SAS

[https://github.com/hashicorp/terraform/blob/master/vendor/github.com/vmware/govmomi/object/virtual_device_list.go#sourcegraph&def=GoPackage/github.com/vmware/govmomi/object/-/SCSIControllerTypes&L43-56](url)

Today, Terraform defaults to LSI Logic when the user specifies SCSI.  Terraform should support each.

Regarding implementation, I believe a `scsi_type` attribute should be a vm level attr not a disk level attr so that each scsi device is uniformly connected to the same type of controller.

**Comment by chrislovecnm** [comment]
`scsi_type` at vm level.  Does that mean that we only can have one type per vm?

**Comment by dkalleg** [comment]
Yes.  My understanding is that there is no use case for having multiple different types of scsi controllers on a vm.

**Comment by chrislovecnm** [comment]
I have done it before :P Some disks paravirtual some lsi

**Comment by chrislovecnm** [comment]
Maybe I should not have

**Comment by mixacha** [comment]
I believe Microsoft recommends Lsi controllers when doing MSC in virtual environments. IT would be great if we could do at disk level, as I'm sure that as Terraform gains momentum in the enterprises this will be a good "selling" point.

**Comment by sputnik13** [comment]
@mixacha I'm sure that's LSI SAS not LSI Parallel, we tested windows server 2012 r2 on vsphere 5.5 today and it (windows) didn't even recognize an LSI Parallel controller out of the box while LSI SAS was recognized and worked right away.  The issue we're seeing is that LSI Parallel was being selected as default.

**Comment by mixacha** [comment]
@sputnik13  Yeah, thanks for additional clarification.

**Comment by stack72** [comment]
Closed via #7525

**Comment by stack72** [comment]
Closed via #7525
