### ISSUE TITLE
Applying null_resource first time broken due to diff mismatch of computed values

### ISSUE THREAD

**Issue by chandy** [hashicorp/terraform#7215]
### Terraform Version
Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource

### Terraform Configuration Files
```hcl
variable "region" { default="us-west-2" }
variable "profile" { default="wmdevops" }
variable "name" { default="nulltest" }
variable "cidr" { default="10.130.0.0/16" }


provider "aws" {
    region   = "${var.region}"
    profile  = "${var.profile}"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "${var.cidr}"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags      { Name = "${var.name}" }
  lifecycle { create_before_destroy = true }
}

resource "null_resource" "test" {
  # Changes to any instance of the cluster requires re-provisioning
  triggers {
    cluster_instance_ids = "${aws_vpc.vpc.id}"
  }

  provisioner "local-exec" {
      command = "echo 'success'"
  }
}

```

### Debug Output
https://gist.github.com/chandy/a30e416b0c8397ec39e20d5a75b1b671

### Expected Behavior
null_resource should have not mismatched, apply should have worked

### Actual Behavior
The diff failed when I ran it the first time.  But when I ran it a second time it passed, probably because the trigger value was now present.  This works in 0.6.x

### Steps to Reproduce
`terraform apply`

**Comment by jbardin** [comment]
Hi @chandy,

Thanks for the bug report! This bug should be taken care of on master now. I applied the config you provided with no issues.

    ...
    null_resource.test (local-exec): success
    null_resource.test: Creation complete
    
    Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

**Comment by chandy** [comment]
Yes, appears to be working now.  Thanks!
