### ISSUE TITLE
Artifactory remote state stores sensitive data

### ISSUE THREAD

**Issue by imduffy15** [hashicorp/terraform#7226]
When using the artifactory remote state via the remote state resource the credentials for authenticating with artifactory are stored into the state.

**Comment by apparentlymart** [comment]
Hi @imduffy15!

This is unfortunately true of all of the remote state backends when the credentials are provided directly in the config.

The usual way to use remote state, which avoids this problem, is to provide credentials instead via environment variables. In this case `ARTIFACTORY_USERNAME` and `ARTIFACTORY_PASSWORD` are the environment variables to use.

The docs could do a better job of explaining this, both for Artifactory in general and for all of the remote state backends generally.

**Comment by imduffy15** [comment]
Thanks!
