### ISSUE TITLE
AzureRM computerName is mandatory

### ISSUE THREAD

**Issue by MansM** [hashicorp/terraform#7229]
terraform version up to 0.7 rc2
Error message: 
 azurerm_virtual_machine.puppetmaster: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: azure: Service returned an error. Code="InvalidParameter" Message="Required parameter 'computerName' is missing (null)." Status=400

2 things needs to be fixed: 
docs (mentioning it as optional)
code: needs to error out before attempting to create with ComputerName parameter

Unfortunately I dont have the time to fix any of it

**Comment by jen20** [comment]
Hi @MansM! Thanks for opening an issue. It seems that the error you are receiving is in direct contravention to the [documentation for the Azure VM API](https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx) which lists `computerName` as optional. I wonder whether this is actually dependent on whether some other combination of fields is set?

**Comment by majormoses** [comment]
@jen20 I ran into this before I cant remember too much on replicating it. I am looking at what I have in git and it looks like you can probably work around it by setting it to an empty string...

**Comment by MansM** [comment]
Actually we had it in the config as empty string ( = "" )

**Comment by stack72** [comment]
I am going to update the documentation here to suggest this is a Required field. The  Azure docs are obviously wrong in this case
