### ISSUE TITLE
External API data for configuration (e.g., GitHub’s Meta API)?

### ISSUE THREAD

**Issue by jonathanmarvens** [hashicorp/terraform#7232]
Hey, y’all.

This *might be* a really stupid question but say I wanted to grab GitHub’s most up-to-date list of IP addresses (*currently* __192.30.252.0/22__) via their [API](https://developer.github.com/v3/meta "Meta | GitHub Developer Guide") to whitelist them (whether individually or using the CIDR notation) in an AWS network ACL for a public subnet with very restricted access, what’s the best way to do something like that right now?

Thank you in advance!!!

\- Jonathan

**Comment by welearnednothing** [comment]
The easy way: Write a script that fetches that data and passes it into Terraform as a variable.

The cooler way: Submit a pull request for the [GitHub provider](https://www.terraform.io/docs/providers/github/index.html) that provides that information giving everyone easy access to that functionality :)

**Comment by jen20** [comment]
Hi @jonathanmarvens! Thanks for opening an issue. As @welearnednothing says, the easiest way right now is to use a wrapper script that uses the API to set a variable. However, this kind of thing is perfect for the new concept of a data source which is in Terraform 0.7 - these are sources of read-only reference data which can then be used in other resources. Writing them is fairly straightforward, however does require writing some code in Go. A great example is the `aws_availability_zones` data source, which fetches a list of the AZs the configured account has access to - the source is here: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/data_source_availability_zones.go. If you have any questions on doing this, please feel free to reopen the issue!
