### ISSUE TITLE
Increase EBS Volume Size on instance launch

### ISSUE THREAD

**Issue by smmnazar** [hashicorp/terraform#7233]
Hi there,

### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_instance
- ebs_block_device

### Terraform Configuration Files
resource "aws_instance" "db1" {
    ami = "ami-1234x123"
    instance_type = "t2.micro"
	key_name = "test"
	subnet_id = "subnet-1234x123"
	vpc_security_group_ids = ["sg-1234x1234"]
	root_block_device {
		volume_type = "gp2"
		volume_size = "100"
		delete_on_termination = "true"
	}
	ebs_block_device {
		device_name = "/dev/xvdb"
		volume_size = 60
		volume_type = "gp2"
		delete_on_termination = false
		snapshot_id = "snap-x123x123"
  }
    tags {
        Name = "TEST"
    }
	
}

### Debug Output
Error applying plan:

1 error(s) occurred:

* aws_instance.db1: Error launching source instance: InvalidBlockDeviceMapping:
The device 'xvdb' is used in more than one block-device mapping
        status code: 400, request id: 2b9ec364-9fd3-4ed3-aeb0-dda84fb33044

### Expected Behavior
The AMI what we trying to launch the instance is contains root volume as a C Drive and ebs volume as a D Drive 30GB.. We are trying to increase the size of EBS Volume D Drive (/dev/xvdb) from 30GB to 60GB while launching the instance, but it failed.

### Actual Behavior
Instance is not launching and getting the below error. 

1 error(s) occurred:

* aws_instance.db1: Error launching source instance: InvalidBlockDeviceMapping:
The device 'xvdb' is used in more than one block-device mapping
        status code: 400, request id: 2b9ec364-9fd3-4ed3-aeb0-dda84fb33044

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jbardin** [comment]
Hi @smmnazar,

What does the output of `terraform plan` say regarding the changes?

**Comment by smmnazar** [comment]
Please find the terraform plan output below.

>terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_instance.db1
    ami:                                               "" => "ami-123456"
    availability_zone:                                 "" => "<computed>"
    ebs_block_device.#:                                "" => "1"
    ebs_block_device.3320117935.delete_on_termination: "" => "false"
    ebs_block_device.3320117935.device_name:           "" => "/dev/xvdb"
    ebs_block_device.3320117935.encrypted:             "" => "<computed>"
    ebs_block_device.3320117935.iops:                  "" => "<computed>"
    ebs_block_device.3320117935.snapshot_id:           "" => "snap-1234567"
    ebs_block_device.3320117935.volume_size:           "" => "60"
    ebs_block_device.3320117935.volume_type:           "" => "gp2"
    ephemeral_block_device.#:                          "" => "<computed>"
    instance_state:                                    "" => "<computed>"
    instance_type:                                     "" => "t2.micro"
    key_name:                                          "" => "TEST"
    placement_group:                                   "" => "<computed>"
    private_dns:                                       "" => "<computed>"
    private_ip:                                        "" => "<computed>"
    public_dns:                                        "" => "<computed>"
    public_ip:                                         "" => "<computed>"
    root_block_device.#:                               "" => "1"
    root_block_device.0.delete_on_termination:         "" => "true"
    root_block_device.0.iops:                          "" => "<computed>"
    root_block_device.0.volume_size:                   "" => "100"
    root_block_device.0.volume_type:                   "" => "gp2"
    security_groups.#:                                 "" => "<computed>"
    source_dest_check:                                 "" => "true"
    subnet_id:                                         "" => "subnet-1234567"
    tags.#:                                            "" => "1"
    tags.Name:                                         "" => "TEST"
    tenancy:                                           "" => "<computed>"
    vpc_security_group_ids.#:                          "" => "1"
    vpc_security_group_ids.2441675374:                 "" => "sg-1234567"


Plan: 1 to add, 0 to change, 0 to destroy.

**Comment by jbardin** [comment]
Thanks for the update. I think this has to do with the way AWS maps device names to the instance. 

Can you verify the output of `aws ec2 describe-images --image-ids ami-1234x123` for your AMI, and see what the device name listed for the block device is? (i.e. is it `/dev/sdb` or similar?)

I've found that if the device name doesn't match exactly what is stored in the AMI, a new block device is created but the launch fails because you can't change that device mapping.

**Comment by smmnazar** [comment]
![image](https://cloud.githubusercontent.com/assets/11322262/16214077/548b6196-3772-11e6-9cac-5c25f04dac09.png)

Please find the AMI details in above image. We would like to increase the EBS size of xvdb from 30G to 60G.

**Comment by jbardin** [comment]
Hi,

This failure is cause when the block device mapping doesn't match what is stored in the AMI. The drives for windows get mapped differently, and you can see that the second device is called `xvdb`. 

I tested this resizing a windows volume using `device_name=xvdb` and it worked as expected. 

I'm going to close this issue, as resizing works as expected, but I'll open a new issue to see if we can do better at detecting this failure mode.
