### ISSUE TITLE
[resource_aws_codedeploy_deployment_group] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sp-adan-lobato** [hashicorp/terraform#7234]
Terraform: 0.6.16

Output & crash.log: https://gist.github.com/sp-adan-lobato/38ca94244902a6bcec7bf9bd62f41d8a

**Comment by catsby** [comment]
Hey @sp-adan-lobato thanks for reporting this!
Do you happen to have a config handy that shows this? It looks like the crash is coming from a Tag Filter that has no value associated with it

**Comment by catsby** [comment]
Ok, so, I guess that's just it... the UI lets you create a Filter tag with a key and no value ¯\\\_(ツ)_/¯

**Comment by catsby** [comment]
Fixed in ecc455ebb4d7e51ad37cf963f2f21c52d270b394 , thanks!

**Comment by sp-adan-lobato** [comment]
Hi @catsby ! Yes, we where using only the key.

Thank you so much for being that quick! 💯
