### ISSUE TITLE
terraform init blanks files

### ISSUE THREAD

**Issue by agonzalezro** [hashicorp/terraform#7238]
### Terraform Version

    Terraform v0.7.0-dev (fe540b408f590ee2e410537672160598e300d056)

### Affected Resource(s)

- local files

### Expected Behavior

From `terraform init` documentation:

> Init will download the module from SOURCE and copy it into the DIR (which defaults to the current working directory). Version control information from the module (such as Git history) will not be copied.

> The directory being initialized must be empty of all Terraform configurations. If the module has other files which conflict with what is already in the directory, they will be overwritten.

### Actual Behavior

If you check the second paragraph that I mentioned earlier it shouldn't blank any file that doesn't conflict. Or at least this is what I understand from reading it.

### Steps to Reproduce

```
$ mkdir tf

$ echo "alex was here" > tf/1

$ ls -l tf
total 8
-rw-r--r--  1 alex  wheel  14 20 Jun 15:57 1

$ terraform init tf

$ ls -l tf
total 8
-rw-r--r--  1 alex  wheel  14 20 Jun 15:57 1

$ cd tf

$ terraform init .

$ ls -l
total 0
-rw-r--r--  1 alex  wheel  0 20 Jun 15:57 1
```

If I run the `init` from outside the folder it doesn't blank the files.

**Comment by jen20** [comment]
Hi @agonzalezro! This sounds like a nasty bug or mismatched documentation. I'll need to look into how this is implemented, but I would tend to agree that the quoted paragraph implies that files which are not in conflict should remain untouched.

**Comment by agonzalezro** [comment]
I was lucky that I run it in my `Desktop`, but it broke recursively one folder that I had there. I wonder what would happen if I run this in my `$HOME`, if you need some help with it let me know and I can PR but I need some insight in advance. Thanks!
