### ISSUE TITLE
Using "computed" values in maps not possible

### ISSUE THREAD

**Issue by Alars-ALIT** [hashicorp/terraform#7241]
### Terraform Version
Terraform v0.7.0-rc2 

### Affected Resource(s)
Terraform core

### Terraform Configuration Files
```hcl
resource "null_resource" "intermediates" {
    triggers = {
        test = "testing..."
    }
}


module "test_mod" {
  source = "./mod"

  services = {
    "name"             = "user-service"
    "min"              = "1"
    "max"              = "1"
    "desired"          = "1"
    "instance_type"    = "t2.small"
    "elb"              = "${null_resource.intermediates.triggers.test}" 
  }
}
```

```hcl
variable "services"                { type = "list" }

resource "aws_autoscaling_group" "asg-test" {
  count                     = "${length(var.services)}"
  availability_zones        = ["test"]
  min_size                  = "${lookup(var.services[count.index], "min")}"
  max_size                  = "${lookup(var.services[count.index], "max")}"
  desired_capacity          = "${lookup(var.services[count.index], "desired")}"
  launch_configuration      = "any"
  vpc_zone_identifier       = ["any"]
  load_balancers            = ["${lookup(var.services[count.index], "elb")}"]  
}
```
### Expected Behavior
Expected the map to contain a entry for "elb". I seems like "computed" values can't be passed in maps

### Actual Behavior
Errors:

  * lookup: lookup failed to find 'elb' in:

${lookup(var.services[count.index], "elb")}

### Steps to Reproduce
terraform plan

**Comment by jen20** [comment]
Hi @Alars-ALIT! I can reproduce this - thanks for the concise example. I'll investigate what is going on here, as I see no reason in principle that this should not work.

**Comment by jen20** [comment]
Note to self for investigative context - in `interpolationFuncLookup`:

```
2016/06/24 14:49:03 [INFO] args: ([]interface {}) (len=2 cap=2) {
 (map[string]ast.Variable) (len=5) {
  (string) (len=3) "min": (ast.Variable) {Variable (TypeString): 1},
  (string) (len=3) "max": (ast.Variable) {Variable (TypeString): 1},
  (string) (len=7) "desired": (ast.Variable) {Variable (TypeString): 1},
  (string) (len=13) "instance_type": (ast.Variable) {Variable (TypeString): t2.small},
  (string) (len=4) "name": (ast.Variable) {Variable (TypeString): user-service}
 },
 (string) (len=3) "elb"
}
```

**Comment by jen20** [comment]
The issue here is that this value is not being passed through as a computed key.

**Comment by coutotyler** [comment]
I'm seeing the same issue on 0.6.16. Is this related?

**Comment by jen20** [comment]
@coutotyler Can you show a configuration for 0.6.16? I suspect this was always broken and people are discovering it now that maps are a more prominent feature. I have a fix in the works for the 0.7 at the moment.

**Comment by coutotyler** [comment]
yup, here you go: https://gist.github.com/coutotyler/42c6d82cc6f202adf21255fbeb16c041

**Comment by ocsi01** [comment]
Is it possible at all ( in v0.7rc-2) to define a list of maps? ( If I understand it well, the 'services' variable is a list, where each element of the list is a map.) 
The question is also open for nested maps.

**Comment by jen20** [comment]
@ocsi01 Yes - the services variable in this example is a list of maps, where each element is a map. Nested maps _are_ supported internally but are not exposed via HCL syntax at the moment.

**Comment by ocsi01** [comment]
@jen20 Does it mean at the moment it's not possible to define multiple element in the 'services' list?
For example:
```
vpc_info          = [{      
"name"= "vpc1"
"cidr"= "10.3.0.0/16"
},{      
"name"= "vpc2"
"cidr"= "10.2.0.0/16"
}
]
```

I'm getting syntax error:

> unexpected token while parsing list: LBRACE
