### ISSUE TITLE
provider/aws: make an elb_listener top level resource

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#7246]
From issue #7235, when a listener changes, there no way to catch that in the stickiness policies so that they can be reapplied. This can be solved in the short term by breaking ELB Listeners out into their own top level resource.

This related to #2275 as well. A solution there would allow dependencies on nested resource in the same manner as top level resources.

**Comment by advanderveer** [comment]
Is there any progress on this? I would like to make elb listeners based on a variable map of ports.

**Comment by catsby** [comment]
Hello all – 

Unfortunately we can't (yet) make a top-level ELB Listener resource. The AWS API requires a `listener` block when creating an ELB; you cannot create an ELB without them.

**Comment by jsalva** [comment]
+1
