### ISSUE TITLE
[azurerm] 0.7.0-rc2 regression from rc1! template_file.configure_vm: diffs didn't match during apply

### ISSUE THREAD

**Issue by colemickens** [hashicorp/terraform#7248]
Same input/plan as in https://github.com/hashicorp/terraform/issues/7153

This works under `0.7.0-rc1` (albeit with manual retries due to the 429 issue)... but does not work at all under `0.7.0-rc2`.

When I try to `terraform apply` this in `0.7.0-rc2` I get an error that Terraform even recognizes as an internal error as it tells me to file an issue for it. Here's the full log: https://gist.github.com/64cea17cf169daa498c699aa5ab222cd

I'm not sure what's going on. I am having to execute this twice, the second time to get around the issue in #7153. Retries under rc1 worked fine. Now I'm getting this "diff didn't match" error.

**Comment by jbardin** [comment]
Hi, thanks for reporting the issue!

This looks to be a duplicate of #7244. We can follow the status through that issue.
