### ISSUE TITLE
Error for chained template_file resources - "diffs didn't match during apply"

### ISSUE THREAD

**Issue by tintoy** [hashicorp/terraform#7250]
Hi.

I've been trying to use chained file_template resources with a local_exec provisioner to generate a JSON file during deployment, but running `terraform apply` fails with "diffs didn't match during apply".

### Terraform Version
Terraform v0.7.0-dev (820c7ca519a6c5cda36d7a0620300ef435342df4)

### Affected Resource(s)
- `template_file`

### Terraform Configuration Files
```hcl
resource "template_file" "vm-winrm-bootstrap-public" {
template = <<EOT
{
	"foo": "bar",
	"baz": 3
	"tpl": "${greeting}, World"
}
EOT

	vars {
		greeting = "Hello"
	}
}

resource "template_file" "vm-winrm-bootstrap-public-cmd" {
template = <<EOT
cat <<TMPLT > ./vm-winrm-public.json
${tpl}
TMPLT
EOT

	vars {
		tpl = "${template_file.vm-winrm-bootstrap-public.rendered}"
	}

	provisioner "local-exec" {
		command = "${template_file.vm-winrm-bootstrap-public-cmd.rendered}"
	}
}
```

### Debug Output
https://gist.github.com/tintoy/a78a5caf37653ed3fdb0f994fb6531d9

### Expected Behavior
Expected a file to be written containing the rendered "vm-winrm-bootstrap-public" template.

### Actual Behavior
Terraform fails to create the second resource (i.e. render its template). Interestingly, if I then run `terraform apply` again, it does indeed create the second resource and execute its provisioner.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I'm running this against the head of the `master` branch.

### References
Might relate to GH-7244

**Comment by jbardin** [comment]
Hi @tintoy, Thanks for the standalone repro! 

I'm closing this to work on the issue through #7244
