### ISSUE TITLE
provider/aws: block device name mismatch causes instance to fail during launch

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#7256]
### Terraform Version

0.7.0
### Affected Resource(s)
- aws_instance
### Terraform Configuration Files

``` hcl
resource "aws_instance" "tf-test" {
  ami                    = "ami-12345678"
  instance_type          = "t2.micro"
  key_name               = "aws-key"
  subnet_id              = "subnet-12345678"
  vpc_security_group_ids = ["sg-12345678"]

  root_block_device {
    volume_type           = "gp2"
    volume_size           = 30
    delete_on_termination = true
  }

  ebs_block_device {
    device_name           = "/dev/xvdb"
    volume_size           = 20
    volume_type           = "gp2"
    delete_on_termination = false
    snapshot_id           = "snap-12345678"
  }
}
```
### Expected Behavior

The AMI `ami-12345678` contains a root device and second block device. We want to launch the instance specifying different options for the second block device, i.e. resize it , change iops, etc. 
### Actual Behavior

Instance fails to launch. No useful information from terraform. 
### Root Cause

The block device name are often mapped differently on the actual instances. The device may be named `/dev/sdb`, but mapped in the AMI as `/dev/xvdb` on Linux, or name `/dev/xvdb` and mapped as just `xvdb` on Windows. 

If the block device naming configuration to run an instance conflicts with the names in the AMI, the instance will fail during launch.

This is the expected behavior of the AWS API, but we may be able to vet this when creating images by inspecting the AMI, or provide better feedback about the failure. 

Reported in #7233

**Comment by anthcor** [comment]
I'm working with a similar issue.

## Terraform Version
- 0.6.15

## Affected Resources
- aws_instance
- possibly aws_ebs_volume
- possibly aws_ebs_attachment

## Terraform Used (consumed as a module)
```hcl
# main.tf
provider "aws" {
  region = "${var.aws_region}"
}

resource "aws_instance" "ec2_instance" {
  ami = "${var.ec2_machine_image}"
  count = "${var.number_of_instances}"
  instance_type = "${var.ec2_instance_type}"
  key_name = "${var.ec2_user_login_key}"
  iam_instance_profile="${var.ec2_iam_instance_role}"
  user_data = "${file(var.ec2_user_data)}"
  subnet_id = "${var.subnet_id}"
  vpc_security_group_ids = ["${split(",", var.security_groups)}"]

  ebs_block_device {
    device_name = "${var.app_name}${var.app_type}ec2${var.app_env}ebsblock"
    volume_type = "${var.volume_type}"
    volume_size = "${var.volume_size}"
    encrypted = "${var.encrypted}"
    delete_on_termination =  "${var.delete_on_termination}"
  }

  tags {
    OwnerContact = "${var.OwnerContact}"
    Name = "${var.app_name}${var.app_type}ec2${var.app_env}"
    role = "${var.app_name}_${var.app_type}_${var.app_env}"
    stack = "${var.app_name}_${var.app_type}_${var.app_env}_stack"
    envtype = "${var.app_env}"
    SNSTopicARN = "${var.snstopicarn}"
  }
}

```

## Expected Behavior
An aws_instance is created, an ebs_block_device is created, and then they are attached.

## Actual Behavior
```sh
Error applying plan:

1 error(s) occurred:

* aws_instance.ec2_instance: Error launching source instance: InvalidBlockDeviceMapping: Invalid device name ec2withebsblock
	status code: 400, request id: 1429f721-b711-43b7-9be7-25da66ed1821

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This might be my misuse of the service, and instead would have to create an ec2, ebs, and attachment as separate resources, but this is the mental model I had when I wanted to create an "ec2 backed by ebs module" for the projects I'm working on.

**Comment by jbardin** [comment]
Hi @anthcor,

This isn't related to the issue above. The error you have is correct : `ec2withebsblock` isn't a valid device name. You can view the documentation for EC2 instance device naming here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html

What you may be looking for is the ability to tag ebs block devices, and there is an open issue at #3531 you can follow. 

If you still have any problems working this out, please feel free to open a new issue!

**Comment by anthcor** [comment]
@jbardin wow thanks completely missed that - thanks for the heads up. I'm a little too excited for the weekend I suppose 🎉

Feel free to remove my comments. Thanks!
