### ISSUE TITLE
service unavailable creating aws_route53_health_check

### ISSUE THREAD

**Issue by bfallik** [hashicorp/terraform#7263]
### Terraform Version
`Terraform v0.6.16`

### Affected Resource(s)
- aws_route53_health_check

### Terraform Configuration Files
```hcl
resource "aws_route53_health_check" "health_check_ui_lb" {
  fqdn = "${aws_elb.ui_lb.dns_name}"
  port = 80
  type = "HTTP"
  resource_path = "/"
  failure_threshold = "5"
  request_interval = "30"

  tags = {
    Name = "health check ${aws_elb.ui_lb.dns_name}"
  }
}
```

### Debug Output
gist: https://gist.github.com/bfallik/6c9d320ffdc88d8686c6869550d8f092

### Expected Behavior
The route53 health check was created.

### Actual Behavior
ServiceUnavailable response

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None that I can think of.

**Comment by bfallik** [comment]
Amazon reached out to explain the issue is on their side:
{noformat}
Your CreateHealthCheck request is failing because of a bug on our side: we do not support user principal names longer than 64 characters. While we will fix the problem promptly, you can make the requests succeed by using a shorter principal name. The current principal name I see is AROAIVLAZE4QXFWADUR32:brian-2016-06-21-Brians-MacBook-Pro-3.local
{noformat}

**Comment by bfallik** [comment]
Actually, this response just raises further questions. How is the principal name set in Terraform and how can I shorten this value?

**Comment by bfallik** [comment]
I tracked this down to a call to STS AssumeRole with an excessive role-session-name. Closing this issue, it has nothing to do with Terraform, except that TF_LOG=1 helped tremendously with debugging.

**Comment by catsby** [comment]
Thanks for following up @bfallik 😄
