### ISSUE TITLE
openstack_compute_secgroup_v2 across multiple regions

### ISSUE THREAD

**Issue by gvenka008c** [hashicorp/terraform#7274]
Hi,

Is there a way we can use openstack_compute_secgroup_v2 across multiple regions to create security groups?  Thanks.

For Example:
resource "openstack_compute_secgroup_v2" "dc1" {
 region = "${var.dc1}"    => any way to specify multiple regions separated with commas?
 
Thanks,
Govind

**Comment by jtopjian** [comment]
@gvenka008c The region argument only supports one value, so there are two ways to go about this:

1. If your regions share the same tokens, you can specify two security group resources, each with a separate region argument.

2. If you need to authenticate at each region, you can use multiple providers as described here:

https://www.terraform.io/docs/configuration/providers.html

In both cases, you'll have two sets of rules, but at least it can all be in the same Terraform configuration 😄 

Feel free to re-open if you have further questions or issues implementing this!
