### ISSUE TITLE
Modules installed in current directory and not the path specified

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#7301]
### Terraform Version

```
> ./terraform_0.6.16_darwin_amd64/terraform version
Terraform v0.6.16
```
### Expected Behavior

Modules installed under the specified path.
### Actual Behavior

Modules installed in the current directory.
### Steps to Reproduce

```
> mkdir test

> cat > test/main.tf
module "ubuntu_ami" {
    source       = "github.com/errordeveloper/tf_aws_ubuntu_ami"
    region       = "${var.aws_region}"
    distribution = "xenial"
    architecture = "amd64"
    virttype     = "hvm"
    storagetype  = "ebs-ssd"
}

^D
> ls -la .terraform
ls: .terraform: No such file or directory

> ./terraform_0.6.16_darwin_amd64/terraform get test/
Get: git::https://github.com/errordeveloper/tf_aws_ubuntu_ami.git

> ls -la .terraform/
total 0
drwxr-xr-x   3 ilya  staff   102 23 Jun 18:20 .
drwxr-xr-x  40 ilya  staff  1360 23 Jun 18:20 ..
drwxr-xr-x   3 ilya  staff   102 23 Jun 18:20 modules

> ls -la test
total 8
drwxr-xr-x   3 ilya  staff   102 23 Jun 18:19 .
drwxr-xr-x  40 ilya  staff  1360 23 Jun 18:20 ..
-rw-r--r--   1 ilya  staff   238 23 Jun 18:19 main.tf

>
```

**Comment by u2mejc** [comment]
Since this is an expected result, maybe you can elaborate why you expected something different and if the documentation can be updated?

PATH is the path to pull from and can also be a remote path.

**Comment by errordeveloper** [comment]
The [docs don't mention anything](https://www.terraform.io/docs/commands/get.html) about remote path, in fact there it says `terraform get [options] [dir]` and built-in usage message says `terraform get [options] PATH`, which is already a bit inconsistent... So I really don't know what's _remote path_. Anyhow, I think docs should state that modules are always installed in the working directory, if this is a bug and not a feature.

My expectations where based on the behaviour of `terrafrom apply dir`, which parses the content of `dir`  and reads or creates `dir/terraform.tfstate`. So I've though `terraform get dir` should behave  the same, and it does actually parse the content of `dir`, however that's not where it saves the modules. I was very surprised by this, to be honest.

**Comment by errordeveloper** [comment]
Also, at the very least, it'd be great if `terraform get` printed the name of the directory it created, that would this clearer.

**Comment by u2mejc** [comment]
Sorry for the confusion, by remote path, I meant outside the current working directory. Hopefully I didn't confuse it with module source when I typed that yesterday.

>My expectations where based on the behaviour of terrafrom apply dir, which parses the content of dir and reads or creates dir/terraform.tfstate. 

It appears your expectations based on `terraform apply` seem inconsistent? `terraform apply` also creates and reads the local (current working directory) terraform.tfstate, as does `terraform destroy` and `terraform plan`, etc.


* `terraform get <PATH>` - Parses the config found at PATH and always creates the `./.terraform` that contains either hardlinks (local file system) or clones of remote (git, http, etc)
* `terraform apply <PATH>` - Parses the config found at PATH and creates the `./terraform.tfstate`, also located in the current working directory.

Apply's `-state=path` and `-state-out=path` allow you the change the location of the terraform.tfstate. To my knowledge the only command that doesn't actually follow this scheme is `terraform init`.

**Comment by errordeveloper** [comment]
> It appears your expectations based on `terraform apply` seem inconsistent?

Hm... looks like I was wrong. I suppose there is a little unclarity somewhere, and it needs to be communicated. As I said earlier, it'd be nice to at least see a message like `Modules saved in ./.terrarform`,

**Comment by jen20** [comment]
Hi @errordeveloper! Thanks for opening an issue. The behaviour is actually correct, but we have a documentation divergence at minimum which is causing some confusion. I'll aim to get that resolved.

**Comment by mitchellh** [comment]
Updated docs. I agree this is weird/inconsistent behavior. For now, we'll keep it as-is. We're going to take a bigger look at the whole ".terraform" folder structure soon and as part of that we may consider changing this.
