### ISSUE TITLE
TF Developer Question - ForceNew

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#7302]
Question is in regards to using `ForceNew` in a resources schema.

Reference:
```golang
schema.Schema {
  ForceNew bool
}
```

When does using `ForceNew: true` cause a virtual machine to be deleted and recreated?  We have numerous uses of this in the vsphere provider, and I am thinking that many are incorrect.

For example: 

https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L182

```golang

			"domain": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Default:  "vsphere.local",
			},

			"time_zone": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Default:  "Etc/UTC",
			},
```

There is no reason that changes a vm's TZ would cause a rebuild, and I am checking on domain.

cc: @stack72 @jen20 @phinze @dkalleg @thetuxkeeper

**Comment by jen20** [comment]
Hi @chrislovecnm - the answer here is straightforward modulo any edge conditions: whenever the value of a field marked `ForceNew` changes, the entire resource is recreated with the new value. If you want the new value to be reflected, there must be an Update defined for the resource, and it must check for changes in each field and apply them as necessary. Please feel free to reopen if you have further questions here!

**Comment by chrislovecnm** [comment]
@jen20 nope that answered it ... we need some MAJOR changes 😦

**Comment by chrislovecnm** [comment]
@jen20 there is no reopen button btw ...

**Comment by stack72** [comment]
@chrislovecnm a little more specific to you, when we use ForceNew and introduce a new scheme parameter without a state migration, TF sees that as a change and thus ForcesNew ;)
