### ISSUE TITLE
Add "@generated" to state file

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#7313]
We use Differential for code review and this tool hides files containing `@generated` by default (although the file can be reviewed by clicking a button). This makes sense for us because we commit our `tfstate` files to git but don't want to code review them. Currently we deal with this by using `jq` to append to the `tfstate` file and using a `Makefile` instead of running `terraform` commands directly.

Would you be open to adding `@generated: true` to the state file? If so, I can submit a PR.

**Comment by jen20** [comment]
Hi @joshuaspence! I think we'd rather not add this - it's not actually used by Terraform, and it would open up a whole bunch of requests to add other things I suspect. Is there an option within Differential to ignore based on file extension or name pattern as in `.gitignore` (for example)?
