### ISSUE TITLE
docker_container ports block should support only specifying the internal port

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform#7314]
### Affected Resource(s)
- docker_container
### Terraform Configuration Files

``` hcl
resource "docker_image" "mongo" {
  name         = "mongo:2.6"
  keep_updated = true
}

resource "docker_container" "mongo" {
  image             = "${docker_image.mongo.latest}"
  name              = "mongo"
  ports {
    internal = "27017"
  }
}
```
### Debug Output
- docker_container.mongo: cannot parse '' as int: strconv.ParseInt: parsing "": invalid syntax
### Expected Behavior

Terraform should allow the Docker behaviour of only specifying the containers internal inbound port and assigning a random port for host. Even better it would be if setting the external port as empty would have the same behaviour as omitting it.
### Actual Behavior

The above error
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
### Important Factoids

See for instance the Compose File reference
https://docs.docker.com/compose/compose-file/#ports

**Comment by dmportella** [comment]
i am going to see if i can reproduce this.. i did on current life 0.6.16 and it works

**Comment by dmportella** [comment]
currently working on Terraform v0.7.0-dev (e4ff7649d85015a740cf5703ba349daaea74e6fe)

**Comment by dmportella** [comment]
building v0.7.0-rc2 now

**Comment by dmportella** [comment]
It is working on Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e) too

**Comment by dmportella** [comment]
I am running the exact some script as you @sky-ricardoreis
