### ISSUE TITLE
aws_s3_bucket policy: heredoc parsing complaint, but file applies just fine

### ISSUE THREAD

**Issue by rmldsky** [hashicorp/terraform#7316]
### Terraform Version
Terraform v0.6.16 (on OSX El Capitan)

### Affected Resource(s)
aws_s3_bucket

### Resources configuration 
```
[...]
policy = <<JSON
{
    "Version": "2012-10-17",
    [...]
}
JSON
[...]
```

### Expected Behavior
The above resources configuration with heredoc under `policy` in `aws_s3_bucket` should work as the similar thing under `aws_iam_group_policy` resource.

### Actual Behavior
Using heredoc in `policy` under `aws_s3_bucket` shouts an error
```
$ terraform plan -var-file production.tfvars
illegal
Error loading config: Error parsing XXX.tf: At 17:12: illegal char
```

### Important Factoids
When using the same JSON in a file and referencing it through: `policy = "${file("policies/policy.json")}"` it works as expected.

### References
Not sure but might be related:
- GH-5505

**Comment by jen20** [comment]
Hi @rmldsky! Could you paste the entire policy as a gist? This looks related to the HEREDOC parser, but a reproduction case would be particularly useful here. If it contains sensitive information you can email it to me as well. Thanks!

**Comment by rmldsky** [comment]
Grr, I just did some more testing and it worked. It must have been me with all that copy-pasting and stuff.

Sorry for all the trouble and bothering.

Mea culpa.
