### ISSUE TITLE
Documentation for azurerm_public_ip contains copy/paste from azurerm_availability_set

### ISSUE THREAD

**Issue by dabdine-r7** [hashicorp/terraform#7334]
For the documentation here:
https://www.terraform.io/docs/providers/azurerm/r/public_ip.html

Both `name` and `resource_group_name` mention availability sets, instead of the public ip resource:

~~~
* `name` - (Required) Specifies the name of the availability set. Changing this forces a
    new resource to be created.

* `resource_group_name` - (Required) The name of the resource group in which to
    create the availability set.
~~~

https://raw.githubusercontent.com/hashicorp/terraform/master/website/source/docs/providers/azurerm/r/public_ip.html.markdown

If I can get around to it, I'll submit a PR.

**Comment by dabdine-r7** [comment]
FWIW, this was a temporary source of confusion, as I initially thought it implied you couldn't have a public ip without an availability set.

**Comment by stack72** [comment]
Hi @dabdine-r7 

MY apologies for the confusion that this has caused. I have just opened a PR that will fix this. I will get it pushed to the main site tomorrow when the HC staff are working

Sorry again

Paul

**Comment by dabdine-r7** [comment]
No problem! Thank you for the quick response!
