### ISSUE TITLE
user input (variable) not working

### ISSUE THREAD

**Issue by lielran** [hashicorp/terraform#736]
I was trying to do the same thing as this tutorial - [Terraform Deploying Consul Cluster in One Command](https://vimeo.com/108755280)

by running this command ``` terraform  apply  github.com/hashicorp/consul/terraform/aws```
the output is :  
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:
  * Required variable not set: key_name
  * Required variable not set: key_path
  * Provider 'aws' error: access_key: required field is not set
  * Provider 'aws' error: secret_key: required field is not set
  * Provider 'aws' error: region: required field is not set
```
also try to add -input=true flag

Spec- terraform_0.3.5_linux_amd64

**Comment by mitchellh** [comment]
Confirmed. Must be some regression somewhere... will find a test case and fix this.

**Comment by mitchellh** [comment]
Fixed
