### ISSUE TITLE
Proposal: add "resource_config" to facilitate separation of infrastructure creation and configuration

### ISSUE THREAD

**Issue by tobiasmcnulty** [hashicorp/terraform#7363]
### The Problem
- Self-references aren't supported by resources, so I can't, for example, include the `cname` of my Elastic Beanstalk (EB) environment in the application environment variables for that EB environment.
- If I set up an RDS or ElastiCache instance and need to pass the endpoint for those into an Elastic Beanstalk (or any other) resource, that effectively delays the creation of those resources. It would be faster to create everything in parallel, and then do the (re)configuration after the fact.
### Proposed Solution

I'm proposing, for discussion, the idea of a `resource_configuration` item in TerraForm that would function like a `resource` but take only settings-related attributes (assuming such a distinction exists, or could exist). For example:

```
resource "aws_elastic_beanstalk_environment" "eb_env" {
  name = "${var.app_name}-${var.env_name}-env"
  application = "${aws_elastic_beanstalk_application.eb_app.name}"
}
resource_config "aws_elastic_beanstalk_environment" "eb_env_settings" {
  resource = "${aws_elastic_beanstalk_environment.eb_env.id}"

  setting = {
    namespace = "aws:elasticbeanstalk:application:environment"
    name = "DATABASE_URL"
    value = "postgres://${aws_db_instance.rds.username}:${aws_db_instance.rds.password}@${aws_db_instance.rds.address}:${aws_db_instance.rds.port}/postgres"
  }
  setting = {
    namespace = "aws:elasticbeanstalk:application:environment"
    name = "ALLOWED_HOSTS"
    value = "${aws_elastic_beanstalk_environment.eb_env.cname}"
  }
}
```
### Terraform Version

$ terraform -v
Terraform v0.6.16
### Affected Resource(s)

I want this for:
- `aws_elastic_beanstalk_environment`

I've seen at least one other ticket that could benefit from this more general approach:
- `elb_listener` (#7246)

And it could work just as well for others
- `aws_instance`
### References
- Similar idea: GH-7246
- Inverse problem: GH-2275

**Comment by teamterraform** [comment]
Hi @tobiasmcnulty! Sorry for the long silence here.

We considered this feature as part of the language improvement work in the 0.12.0 release, but ultimately decided not to move forward with it.

The main technical blocker for this idea is that Terraform is ultimately modelling upstream APIs and most upstream APIs don't themselves provide for a distinction between creating and configuring an object. In some rare cases where that _is_ technically feasible, providers can represent that by splitting the problem into two resource types themselves, and we already have a few examples of this in providers where a specific use-case called for it.

Taking the Elastic Beanstalk CNAME example that motivated this issue in particular, to support that would require a distinction at the Elastic Beanstalk API level between creating an environment (and, as part of that, determining its `cname` value) vs. writing the settings for it. The Terraform Core team isn't sure if that distinction exists at the API level in this _particular_ case, but if it does then the AWS provider could potentially provide for the distinction you are requesting by offering a separate `aws_elastic_beanstalk_environment_setting` resource type that allows writing an environment setting independently of creating the environment.

It doesn't seem like there is a reasonable way to generalize this idea to apply to _all_ resource types, so we intend to leave this as a case-by-case situation for providers to model when possible and warranted. With that said, if you or anyone else finds further use-cases of this kind we'd suggest to open an issue in the relevant provider repository to discuss that use-case in particular, to see if the provider may be able to support the use-case.

Thank you for starting this discussion! We hope the above is a satisfying rationale for why we ultimately decided not to generalize this as a Terraform Core feature.
