### ISSUE TITLE
crash while running "plan"

### ISSUE THREAD

**Issue by jbayer** [hashicorp/terraform#737]
while running `terraform plan` on a simple .tf file there was a panic.

the crash contents are here: https://gist.github.com/jbayer/fa846d7775943a8395a8

**Comment by frodenas** [comment]
I've been debugging this with @jbayer. Seems this is related to https://github.com/hashicorp/terraform/issues/624.

**Comment by mitchellh** [comment]
Can you share a configuration that will reproduce this?

**Comment by jbayer** [comment]
this one had reproduced it before...but @frodenas i believe made some changes. when we changed 
`num_cells = 3` to `num_cells = "3"` i believe that's when it started working.

```
module "lattice" {
    source = "github.com/cf-platform-eng/lattice-terraform/aws"

    # AWS access key
    aws_access_key = "MYACCESSKEY"

    # AWS secret key
    aws_secret_key = "MYSECRETKEY"

    # The SSH key name to use for the instances
    aws_key_name = "lattice-key"

    # Path to the SSH private key file
    aws_ssh_private_key_file = "/Users/jamesbayer/.ssh/lattice-key.pem"

    # The number of Lattice Cells to launch
    num_cells = 3
}
```

**Comment by jbayer** [comment]
confirmed that terraform 0.3.6 addresses the issue and it no longer crashes with an integer. closing.
