### ISSUE TITLE
vsphere_virtual_machine resource provider getting confused with multiple disks

### ISSUE THREAD

**Issue by ricardclau** [hashicorp/terraform#7372]
Hi

I am having issues when adding disks to vsphere vms, not sure if this is expected but I think I may have hit a bug here, happy to provide more info, etc...
### Terraform Version

0.7.0-rc2 (also tested last master Terraform v0.7.0-dev (85ccf3b6b45478677aa3f10bb83edfaa246ee238))
### Affected Resource(s)

Please list the resources as a list, for example:
- vsphere_virtual_machine
### Terraform Configuration Files

Adding an extra disk with something like

```
  disk {
    datastore = "SOME_DATASTORE"
    size = 50
    name = "d_drive"
  }
```
### Debug Output

terraform plan will try to recreate the box but most importantly the state gets confused in existing disks showing this:

```
disk.2348006000.controller_type:        "scsi" => "scsi" (forces new resource)
```

No other changes in say the OS drive, just adding an extra disk
### Expected Behavior

Not forcing a new resource or at least not show a problem in a disk that has not changed
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan` after adding the extra disk to the tf file

**Comment by mo-man** [comment]
I see this bug is still open and reproducible in 0.9.3.
