### ISSUE TITLE
AZURERM_DNS_ZONE attribute to output attribute name_servers

### ISSUE THREAD

**Issue by isamuelson** [hashicorp/terraform#7374]
# dns

```
resource "azurerm_dns_zone" "dns" {
   name = "${var.environment}.local"
   resource_group_name = "${azurerm_resource_group.compute.name}"
}
resource "azurerm_dns_a_record" "dns-record" {
   name = "${var.name}"
   zone_name = "${azurerm_dns_zone.dns.name}"
   resource_group_name = "${azurerm_resource_group.compute.name}"
   ttl = "300"
   records = ["${azurerm_network_interface.nic.*.private_ip_address}"]
}


resource "azurerm_virtual_network" "network" {
    name = "virtual-network"
    address_space = ["10.0.0.0/16"]
    location = "${azurerm_resource_group.compute.location}"
    resource_group_name = "${azurerm_resource_group.compute.name}"
    dns_servers = **[${azurerm_dns_zone.dns.name_servers}]**
}
```

**Comment by stack72** [comment]
Hi @isamuelson 

the Azure go-sdk doesn't seem to expose the name servers when a zone is created. I will raise a ticket with Azure now but this will take a while AFAICT

Paul

**Comment by isamuelson** [comment]
ok thanks, meanwhile is there a way to execute a command and get the results as an output ? 
```"azure network dns record-set show ${azurerm_resource_group.compute.name} ${azurerm_dns_zone.dns.name} @ NS --json | jq '.properties.nsRecords | map(.nsdname)'"
  ```

**Comment by stack72** [comment]
Fraid not :(

FYI, the issue is being tracked here https://github.com/Azure/azure-sdk-for-go/issues/346

**Comment by isamuelson** [comment]
thank you

**Comment by isamuelson** [comment]
v3.0.0-beta release has the changes

**Comment by stack72** [comment]
@isamuelson yeah, the SDK has a lot of breaking changes so i am trying to make my way through to make sure that all works as expected

**Comment by isamuelson** [comment]
@stack72 is there a way to resolve the name_servers to list of IPs so it can be used on Virtual Network or Network Interface dns_servers?

**Comment by stack72** [comment]
Hi @isamuelson 

These are the only things that come back from the API - you will need to resolve them on your side I'm afraid. Terraform has nothing that can do that

Paul

**Comment by isamuelson** [comment]
can we create a util function on terraform to resolve dns to ip ?

**Comment by stack72** [comment]
@isamuelson IMO i think it's best to not try and resolve the IPs. The IPs may be subject to change. Feel free to open a PR that proposes such a function though

Paul

**Comment by isamuelson** [comment]
the name servers ip are static...they do not change.

On Thu, Jul 7, 2016 at 10:44 AM, Paul Stack <notifications@github.com>
wrote:

> @isamuelson <https://github.com/isamuelson> IMO i think it's best to not
> try and resolve the IPs. The IPs may be subject to change. Feel free to
> open a PR that proposes such a function though
>
> Paul
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/terraform/issues/7374#issuecomment-231099303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABX8VBjK_a_RMxIvGJy8EqXYc4MXDEDbks5qTRDUgaJpZM4I_cF1>
> .
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by stack72** [comment]
@isamuelson if they can guarantee you that the ips will not change then please do feel free to write something that will do the reverse lookup of the IPs. I am assuming, that as MSFT use a global set of NameServers, that they could potentially fail over at some point. But as I said, this is an assumption
