### ISSUE TITLE
Terraform Crashes - 0.6.16 - Mac

### ISSUE THREAD

**Issue by mohnishbasha** [hashicorp/terraform#7380]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
Debug log
https://gist.github.com/mohnishbasha/e3d44ba82fe2207e2ba825136ef1cc66

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
Crash Log
https://gist.github.com/mohnishbasha/0684e8198850c8e62c41e43651ba3a94

### Expected Behavior
What should have happened?
Should complete instance creation

### Actual Behavior
What actually happened?
Plugin just crashes

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
<path>/terraform apply

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
Custom Endpoints to AWS
endpoints {
    ec2 = "${var.ec2}"
    elb = "${var.elb}"
    iam = "${var.iam}"
  }

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by catsby** [comment]
Thank you @mohnishbasha – I wasn't immediately able to reproduce your issue here, do you by chance have a Terraform configuration that demonstrates this, that you could share? If so please be sure to omit any secrets!

Thanks!

**Comment by catsby** [comment]
Hey @mohnishbasha I'm going to close this for now, as we haven't heard back and haven't been able to reproduce the issue.

If you are still hitting this please let us know. Any additional information would be great. Thanks!
