### ISSUE TITLE
Use Terraform variable on Powershell

### ISSUE THREAD

**Issue by smmnazar** [hashicorp/terraform#7382]
Hi there,

I would like to reuse the variables which are declared in terraform to powershell. The values like access_key and secret_key has to be accessed in powershell bootstrap script for getting EC2 tagging values.

Please help how to achieve this

**Comment by catsby** [comment]
Hello @smmnazar – 

I'm not quite sure I follow your question here, but we do kindly ask you direct general usage questions that are not answered in our documentation (https://www.terraform.io/docs/index.html)  to our community resources for this kind of request, as our issue tracker is meant to help us track and fix issues as well as develop features. You can find some community links like IRC, or the mailing list, here:

- https://www.terraform.io/community.html

Thanks!
