### ISSUE TITLE
vSphere: bad documentation for network_interface.label

### ISSUE THREAD

**Issue by ChloeTigre** [hashicorp/terraform#7385]
### Abstract

This is either a documentation bug or a badly named field.
### Terraform Version

I run 
Terraform v0.7.0-dev (f312ba1f28b91deb988e41778f840703f418bcdc+CHANGES)
### Affected Resource(s)

vsphere_virtual_machine
### Terraform Configuration Files

``` hcl
resource "vsphere_folder" "testfolder" {
  path       = "dev0/test-tf"
  datacenter = "dc0"
}

resource "vsphere_virtual_machine" "testvm2" {
  name       = "testvm-chloe2"
  folder     = "${vsphere_folder.testfolder.path}"
  vcpu       = 2
  memory     = 512
  datacenter = "dc0"
  cluster    = "cluster0"

  disk {
    template = "DEV/templates/debian-jessie-template-01"
    datastore  = "DOM1_DEV01"
  }

  network_interface {
    label = "dvpg0/portgroup1"
  }

  skip_customization = true
}

```
### Expected Behavior

The `label` should be the label of the nic OR the field shall be renamed as `connect_to` or something approaching.
### Actual Behavior

The `label` field designates which network you want to connect the NIC to. There is no way to specify a name for the NIC.
### Steps to Reproduce

`terraform apply`
### Important Factoids

vSphere 5.5, Terraform in a dev branch (working on the vSphere provider)
### References

None.

**Comment by angelichorsey** [comment]
I would like to add that the label documentation should more clearly explain the NIC you want to interface to connect to. At the same time, perhaps the deviceName could actually be utilized in the script so we can name our interfaces.

```
type networkInterface struct { 
	deviceName       string
	label            string
	ipv4Address      string
	ipv4PrefixLength int
	ipv4Gateway      string
	ipv6Address      string
	ipv6PrefixLength int
	ipv6Gateway      string
	adapterType      string // TODO: Make "adapter_type" argument
	macAddress       string
}
```
