### ISSUE TITLE
one space to much .-> crash

### ISSUE THREAD

**Issue by jerryivanhoe** [hashicorp/terraform#7386]
Hi,

# terraform -v
Terraform v0.6.16

```
terraform remote config -backend=s3 -backend-config="bucket=terraform-versioning" -backend-config="key=jerryivanhoe/terraform.tfstate" -backend-config="region=eu-central-1 "
```

This crashes due to the space between eu-central-1 and the  "

This works fine:

```
terraform remote config -backend=s3 -backend-config="bucket=terraform-versioning" -backend-config="key=jerryivanhoe/terraform.tfstate" -backend-config="region=eu-central-1"
Remote configuration updated
Remote state configured and pulled.   
```

**Comment by mitchellh** [comment]
Just verified this doesn't or no longer crashes.

This does result in an error but I believe that is the correct behavior: the values are double quoted so I think its reasonable to expect the space will count as part of the value and a region with a space is invalid.
