### ISSUE TITLE
StorageAccountNotRecognized - Please use a storage account managed by Storage Resource Provider.

### ISSUE THREAD

**Issue by Eimert** [hashicorp/terraform#7387]
Azure or Terraform complains about a storage account that is not recognized. The storage account exists in Azure.

### Terraform Version
Terraform v0.7.0-rc2

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_storage_account

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "devops" {
    name = "devopsstorage"
    resource_group_name = "${azurerm_resource_group.vmgroup.name}"
    
    location = "West Europe"
    account_type = "Standard_LRS"

    tags {
        environment = "development"
    }
}
```

### Debug Output
* azurerm_virtual_machine.buildserver: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: azure: Service returned an error. Code="StorageAccountNotRecognized" Message="Please use a storage account managed by Storage Resource Provider. Use of devopsstorage is not supported." Status=400

### Expected Behavior
Storage account creation without errors.

### Actual Behavior
Error.

### Steps to Reproduce
1. `terraform apply ./infra-terraform`

### Important Factoids
-

**Comment by stack72** [comment]
Hi @Eimert 

this may be a case of eventual consistency. We have identified a potential issue where we do not wait on a storage account being marked as `succeeded` in it's provisioning state

There is a PR open that should solve this https://github.com/hashicorp/terraform/pull/7329

This will go live for 0.7 release

Thanks

Paul

**Comment by stack72** [comment]
Fixed via #7387

**Comment by kamoljan** [comment]
Looks like the bug still exists

**Comment by Gesthemene** [comment]
Just occurred for me too

**Comment by tombuildsstuff** [comment]
Hi @gesthemene @Eimert

Just to check - is the storage account you're referencing a Classic (i.e. formally old portal) Storage Account, or one created in the new (Resource Manager) Portal?

Thanks!
Tom

**Comment by Gesthemene** [comment]
Resource Manager.
`resource "azurerm_storage_account" "test" {
  name                = "terraformtestsa"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "West Europe"
  account_type        = "Standard_LRS"

  tags {
    environment = "Test"
  }
}`

**Comment by tombuildsstuff** [comment]
@Gesthemene thanks for that, and to clarify, is this an existing storage account now managed by Terraform, or a brand new one?

**Comment by Gesthemene** [comment]
Sorry for the delay. It was a brand new one. Interestingly enough, it hasn't reoccurred again. I'm seeing storage account creation times vary wildly from about a minute to 20 minutes, but at this point, Terraform is playing nicely and waiting for it to complete no matter the time it takes.

**Comment by stack72** [comment]
Hi @Gesthemene 

The creation of the resource is handled by Azure itself. Terraform just talks to the SDK. The SDK then handles the waiting for the resource to be created. Therefore, this sounds like an SDK / API bug to me rather than Terraform

Thanks

Paul

**Comment by Gesthemene** [comment]
Good to know. Thanks very much for getting back to me!
