### ISSUE TITLE
Google CloudSql instance creation 2nd Gen no longer works/fails

### ISSUE THREAD

**Issue by hjfbynara** [hashicorp/terraform#7391]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
### Terraform Version

0.6.16
### Affected Resource(s)

Resource:google_sql_database_instance
### Terraform Configuration Files

``` hcl
# variables

variable "cloudsql_activation_policy" {
  default = "ALWAYS"
  description = "The default MySQL activation policy for CloudSQL"
}

variable "cloudsql_pricing_plan" {
  default = "PER_USE"
  description = "The default MySQL pricing plan for CloudSQL"
}

variable "cloudsql_region" {
  default = "us-central"
  description = "The CloudSQL region"
}

variable "cloudsql_require_ssl" {
  default = "true"
  description = "SSL require flag"
}

variable "cloudsql_replication_type" {
  default = "SYNCHRONOUS"
  description = "The default MySQL replication type for CloudSQL"
}

variable "cloudsql_version" {
  default = "MYSQL_5_6"
  description = "The default MySQL version for CloudSQL"
}
variable "instance_size_cloudsql_cromwell" {
  default = "db-n1-standard-8"
  description = "The default instance size for cromwell cloudsql instances"
}
variable "num_cromwell_cloudsql_instances" {
   default = “2"
   description = "number of cromwell database instances"
}

#
# CloudSQL instance
#
resource "google_sql_database_instance" "cromwell-mysql1" {
    count = "${var.num_cromwell_cloudsql_instances}"
    region = "${var.cloudsql_region}"
    database_version = "${var.cloudsql_version}"

    settings {
        activation_policy = "${var.cloudsql_activation_policy}"
        pricing_plan = "${var.cloudsql_pricing_plan}"
        replication_type = "${var.cloudsql_replication_type}"
        tier = "${var.instance_size_cloudsql_cromwell}"

        backup_configuration {
            binary_log_enabled = false
            enabled = true
            start_time = "06:00"
        }

        ip_configuration {
            ipv4_enabled = true
            require_ssl = "${var.cloudsql_require_ssl}"
        }
    }
}
```
### Debug Output

Trace output is over 12MB in size - not conducive to Gist.  If you have an alternative suggestion for the trace files let me know.
### Panic Output

NONE
### Expected Behavior

What should have happened?

I was increasing the number of cloudsql instances from 1 to 2.  I expected terraform to build another cloudsql instance just like the first one that was created about a month ago.  
### Actual Behavior

What actually happened?

Creation failed.  Google  Console showed:
<img width="1010" alt="screen shot 2016-06-26 at 3 39 27 pm" src="https://cloud.githubusercontent.com/assets/6640829/16416266/7606cd7c-3d0f-11e6-9056-2ccf7fdbef9c.png">

PLAN APPLY OUTPUT
Terraform v0.6.16

Setting up remote state...
Downloading remote modules...
Refreshing Terraform state prior to plan...
google_sql_database_instance.cromwell-mysql1.1: Creating...
  database_version:                                     "" => "MYSQL_5_6"
  ip_address.#:                                         "" => "<computed>"
  name:                                                 "" => "<computed>"
  region:                                               "" => "us-central"
  self_link:                                            "" => "<computed>"
  settings.#:                                           "" => "1"
  settings.0.activation_policy:                         "" => "ALWAYS"
  settings.0.backup_configuration.#:                    "" => "1"
  settings.0.backup_configuration.0.binary_log_enabled: "" => "false"
  settings.0.backup_configuration.0.enabled:            "" => "true"
  settings.0.backup_configuration.0.start_time:         "" => "06:00"
  settings.0.ip_configuration.#:                        "" => "1"
  settings.0.ip_configuration.0.ipv4_enabled:           "" => "true"
  settings.0.ip_configuration.0.require_ssl:            "" => "true"
  settings.0.pricing_plan:                              "" => "PER_USE"
  settings.0.replication_type:                          "" => "SYNCHRONOUS"
  settings.0.tier:                                      "" => "db-n1-standard-8"
  settings.0.version:                                   "" => "<computed>"
google_sql_database_instance.cromwell-mysql1.1: Still creating... (10s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (20s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (30s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (40s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (50s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (1m0s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (1m10s elapsed)
google_sql_database_instance.cromwell-mysql1.1: Still creating... (1m20s elapsed)
Error applying plan:

1 error(s) occurred:
- google_sql_database_instance.cromwell-mysql1.1:

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create any cloudsql config using 2nd gen google cloudsql
2. Run terraform plan -out=plan.out
3. run terraform apply plan.out
### Important Factoids

I have created cloudsql instances using this exact same configuration numerous times prior.

If you look at the Google console after terraform failure it shows database size of 1G.  However if I manually create a new 2nd Gen cloudSql through the Google console - the minimum size is 10G.  I know previously when I created 2nd gen cloudSql with terraform - the size was 1G.  So I suspect that Google updated their requirements that minimum size must be 10G and terraform is suppling 1G instead.  Hence the failure.

<img width="495" alt="screen shot 2016-06-26 at 3 39 54 pm" src="https://cloud.githubusercontent.com/assets/6640829/16416410/1f620cb0-3d10-11e6-8abf-5a5fd4a4f7e0.png">
### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by jaydubsjay** [comment]
I just tested creating a Generation 2 SQL instance and it succeeded for me.

Terraform file:
```
### MySQL configuration
resource "google_sql_database_instance" "rancher-ha" {
  name = "rancher-ha"
  database_version = "MYSQL_5_7"
  region = "us-east1"

  settings = {
    tier = "db-n1-standard-2"
  }
}
```
Output:
```
google_sql_database_instance.rancher-ha: Creating...
  database_version:   "" => "MYSQL_5_7"
  ip_address.#:       "" => "<computed>"
  name:               "" => "rancher-ha"
  region:             "" => "us-east1"
  self_link:          "" => "<computed>"
  settings.#:         "" => "1"
  settings.0.tier:    "" => "db-n1-standard-2"
  settings.0.version: "" => "<computed>"
google_sql_database_instance.rancher-ha: Still creating... (10s elapsed)
.....
google_sql_database_instance.rancher-ha: Still creating... (1m50s elapsed)
google_sql_database_instance.rancher-ha: Creation complete
```

It successfully created a Google SQL Generation 2 instance with a default of 10GB of storage capacity, as seen from the Google Cloud Console:

![image](https://cloud.githubusercontent.com/assets/20867907/17453475/46295116-5b4a-11e6-9de4-adf132c9f605.png)

**Comment by danawillow** [comment]
I'm going to go ahead and close this. Feel free to reopen if this is still a problem, @hjfbynara.
