### ISSUE TITLE
Remote-Exec not working with domain credentials

### ISSUE THREAD

**Issue by siddheshwar-more** [hashicorp/terraform#7397]
Hi there,

w.r.t https://github.com/hashicorp/terraform/issues/2918 

I've working DC setup. My requirement is to run powershell scripts on domain member. I;ve added domain user as local admin to domain member server.

I've tried all permutation combination of user:
domain/user, user@domain but no luck.

In-fact same creds working with below code-

```
$txtPassword = "password" | ConvertTo-SecureString -AsPlainText -Force
$plainPassword = ConvertFrom-SecureString $txtPassword
$securePassword = $plainPassword| ConvertTo-SecureString 


$Credentials = New-Object System.Management.Automation.PSCredential -ArgumentList 'corp\install', $securePassword

$connUri = "http://<ip>:5985/wsman"

$out = Invoke-Command -ConnectionUri $connUri -Credential $Credentials -SessionOption( New-PSSessionOption -SkipCACheck ) -ScriptBlock{  hostname }

```

Here's my terraform connection block-

```
  connection {
    type = "winrm"
    user = "domain\\user"
    password = "password"
    insecure = true
    port = 5985
    host = "<ip>"
    timeout = "10m"
  }

```

Please help here- this is killing time!

thanks.

**Comment by stack72** [comment]
Hi @siddheshwar-more 

Is the machine you are connecting to part of the domain?

Paul

**Comment by siddheshwar-more** [comment]
@stack72  

Any updates on this ?

We are blocked because of this- our installation/configuration has to be done by using domain user.

**Comment by stack72** [comment]
Hi @siddheshwar-more

Unfortunately there is no way i can replicate this as I do not have a windows domain. Can you post the terraform output (minus the secrets and in a gist) so we can see if there is anything suspect there?

Paul

**Comment by siddheshwar-more** [comment]
Hello @stack72 

Here;s the output- 

```

2016/07/04 17:51:41 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:41 connecting to remote shell using WinRM
null_resource.setupsb1: Creating...
null_resource.setupsb1: Provisioning with 'remote-exec'...
null_resource.setupsb1 (remote-exec): Connecting to remote host via WinRM...
null_resource.setupsb1 (remote-exec):   Host: 104.197.123.197
null_resource.setupsb1 (remote-exec):   Port: 5985
null_resource.setupsb1 (remote-exec):   User: corp\install
null_resource.setupsb1 (remote-exec):   Password: true
null_resource.setupsb1 (remote-exec):   HTTPS: false
null_resource.setupsb1 (remote-exec):   Insecure: true
null_resource.setupsb1 (remote-exec):   CACert: false
2016/07/04 17:51:42 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:42 connection error: http error: 401 -
2016/07/04 17:51:42 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:42 Retryable error: http error: 401 -
null_resource.setupsb1 (remote-exec): Connecting to remote host via WinRM...
null_resource.setupsb1 (remote-exec):   Host: 104.197.123.197
null_resource.setupsb1 (remote-exec):   Port: 5985
null_resource.setupsb1 (remote-exec):   User: corp\install
null_resource.setupsb1 (remote-exec):   Password: true
null_resource.setupsb1 (remote-exec):   HTTPS: false
null_resource.setupsb1 (remote-exec):   Insecure: true
null_resource.setupsb1 (remote-exec):   CACert: false
2016/07/04 17:51:45 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:45 connecting to remote shell using WinRM
2016/07/04 17:51:46 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:46 connection error: http error: 401 -
2016/07/04 17:51:46 [DEBUG] terraform-provisioner-remote-exec.exe: 2016/07/04 17:51:46 Retryable error: http error: 401 -
2016/07/04 17:51:46 [DEBUG] vertex root, waiting for: provider.null (close)
2016/07/04 17:51:46 [DEBUG] vertex provider.null (close), waiting for: null_resource.setupsb1
2016/07/04 17:51:46 [DEBUG] vertex provisioner.local-exec (close), waiting for: null_resource.setupsb1


```

**Comment by stack72** [comment]
@siddheshwar-more 

Unfortunately, I don't believe this to be a bug with Terraform. The 401 suggests that Terraform is making the connection as expected but that the auth details are not working. 

I don't have a windows machine or domain controller that can help me diagnose this though I am afraid

Can you try and rdp directly into the machine using the same host ip and credentials?

Paul

**Comment by jen20** [comment]
Hi @siddheshwar-more - this does indeed look like some form of configuration error with your domain/credentials which we can't really help to diagnose. You can try using the `winrm` command which is part of the `masterzen/winrm` repository to troubleshoot this locally without Terraform confusing matters. Once that can connect you should be OK. Sorry we can't be of more assistance here!

**Comment by siddheshwar-more** [comment]
@stack72 -

[masterzen/winrm](https://github.com/masterzen/winrm#winrm-for-go)  This say's - lib doesn't support  domain users.

Can you suggest any alternative available in  terraform ?

**Comment by justdan96** [comment]
As a workaround you can locally execute a Powershell script that will run the required script on the remote server. You can set parameters for the Powershell script for the host, username, etc. It's a hacky way of doing it but at this current time the only possible workaround.

**Comment by chris-alation** [comment]
I've tried the above suggestion but it doesn't seem to work at all:

Here is my tf code:
```
provisioner "remote-exec" {
    connection = {
      host        = "${self.private_ip}"
      type        = "winrm"
      user        = "Administrator"
      password    = "${var.password}"
      agent       = "false"
      insecure    = "true"
    }
    inline = [
      "powershell.exe Set-ExecutionPolicy Bypass -force",
      "powershell.exe -ExecutionPolicy Bypass -File C:\\ps-scripts\\create_ad_users.ps1 -adPassword ${var.ad_password} -domain ${var.domain} -userPassword ${var.password}"
    ]
  }
```

and the shell script look like this:
```
Param(
   [string]$adPassword,
   [string]$domain,
   [string]$userPassword
)

Set-PSDebug -Trace 1
Enable-PSRemoting -force
Enable-WSManCredSSP -Role Server -Force
Enable-WSManCredSSP -Role Client -DelegateComputer locahost -Force
Enable-WSManCredSSP -Role Client -DelegateComputer $env:COMPUTERNAME -Force
Enable-WSManCredSSP -Role Client -DelegateComputer $domain -Force
Enable-WSManCredSSP -Role Client -DelegateComputer "*.$domain" -Force
Set-Item -Path "wsman:\localhost\service\auth\credSSP" -Value $True -Force
New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation -Name AllowFreshCredentialsWhenNTLMOnly -Force
New-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation\AllowFreshCredentialsWhenNTLMOnly -Name 1 -Value * -PropertyType String

# Run our commands as the domain admin!
$secpasswd = ConvertTo-SecureString $adPassword -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ("$domain\Admin", $secpasswd)
$adminSession = New-PSSession -Credential $credential -Authentication Credssp;

$sb = {
    param($p1, $p2)

    whoami
    $adpass = ConvertTo-SecureString -AsPlainText $p2 -Force
    New-ADUser -Name 'test user01' -GivenName 'Test User' -Surname User01 -SamAccountName testuser01 -UserPrincipalName test.user01@$p1 -AccountPassword $adpass -PassThru | Enable-ADAccount
}

Invoke-Command -Session $adminSession -Script $sb -ArgumentList $domain,$userPassword
```

The script executes fine, and but the invoke command doesn't execute when terraform runs it. Manually, it runs fine and as expected. 

Maybe there was another meaning of your post or someone can post an example of a script that connects as the local admin and then run commands as a domain user? 

I also tried using psexec and using that to open another powershell script as the AD user. Again that ran fine directly on the windows box, but when run over terrraform it failed.

**Comment by samtwilliams** [comment]
Chris did you manage to get this to work in the end, i have the same issue where a local-exec command works when running outside of terraform but it doesnt when run from local-exec

**Comment by fckbo** [comment]
Hi guys did anyone get this to work as I've got exactly the same problem ?
