### ISSUE TITLE
Terraform/Openstack: diffs didn't match during apply - reporting bug in Terraform

### ISSUE THREAD

**Issue by wells369** [hashicorp/terraform#7399]
I was able to successfully use a variable for count to create a dynamic number of openstack_compute_instance_v2 instances, with a corresponding number of openstack_blockstorage_volume_v1 being attached to the instances via volume_id. Increasing the count to create one more additional instance/volume produced an error.

In "terraform plan" it appeared to have changed the original instances so it would recompute the volume_ids to be attached. While running "terraform apply", it recognized there was nothing to change for the existing nodes, it successfully deployed the new instance/volume, and it gave an error output for the first two existing openstack_compute_instance_v2 stating the "diffs didn't match during apply".

** Note, I use the same syntax to reference the user_data template to be associated with instances, and that works. It is only the volume association that produces the errors.

### Terraform Version
Terraform v0.6.16 (latest released version)

### Affected Resource
- openstack_compute_instance_v2

### Terraform Configuration Files
variables.tf
```hcl
variable "node_count" {
  default = 2
}
...
```
main.tf
```hcl
#
# user data templates
#
resource "template_file" "node_user_data" {
  count = "10"
  template = "${file("${path.module}/templates/user_data.tpl")}"
  vars {
    hostname = "${format("%s%02d", var.hostname, count.index + 1)}"
  }
}

#
# Cinder block storage
#
resource "openstack_blockstorage_volume_v1" "node_storage" {
  count = "${var.node_count}"
  name = "${format("%s%02d", var.blockstorage_name, count.index + 1)}"
  description = "cinder block ${count.index + 1}"
  size = "25"
}

#
# Compute instances
#
resource "openstack_compute_instance_v2" "nodes" {
  count = "${var.node_count}"
  image_name = "<image_name>"
  name = "${format("%s%02d", var.hostname, count.index + 1)}"
  flavor_name = "<flavor_name>"
  key_pair = "<key_pair>"
  volume {
    volume_id =  "${element(openstack_blockstorage_volume_v1.node_storage.*.id, count.index)}"
  }
  security_groups = ["default"]
  user_data = "${element(template_file.node_user_data.*.rendered, count.index)}"
}
```

### Debug Output
* openstack_compute_instance_v2.nodes.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

```hcl
    Resource ID: openstack_compute_instance_v2.nodes.0
    Mismatch reason: attribute mismatch: volume.~2291066193.device
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"volume.~2291066193.id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~2291066193.volume_id":*terraform.ResourceAttrDiff{Old:"", New:"${element(openstack_blockstorage_volume_v1.node_storage.*.id, count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~2291066193.device":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```

### Expected Behavior
Create one additional instance and corresponding attached volume.

### Actual Behavior
Successfully created the desired instance/volume, but there is a discrepancy between 'terraform plan' and 'terraform apply' for the existing instances

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `node_count = 2`
2. `terraform apply`
3. `node_count = 3`
4. `terraform plan`
5. `terraform apply`

** Note: This also occurs without #4, just running apply produces the same result.

**Comment by jtopjian** [comment]
@wells369 Thanks for the report. This is a frustrating one... There's an existing issue (#3449) that has more details about this as well as a potential work around. I'd say keep an eye on that issue, but if you have any questions, or if this is actually a different issue than in #3449, please feel free to re-open this. 😄

**Comment by vmendoza** [comment]
This issue is happening in 0.10.2

* module.ecs_cluster.aws_autoscaling_group.ecs: aws_autoscaling_group.ecs: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.10.2
    Resource ID: aws_autoscaling_group.ecs
    Mismatch reason: attribute mismatch: availability_zones.1305112097
