### ISSUE TITLE
Mumbai - AP-South not supported

### ISSUE THREAD

**Issue by boxrick** [hashicorp/terraform#7408]
Not much info on this needed.

Terraform 0.6.16

New Indian Region is not supported in AWS ( ap-south-1 ). Should be a fairly simple fix. 

```Not a valid region: ap-south-1```

**Comment by stack72** [comment]
Hi @boxrick 

a PR was merged yesterday that get's this into master - it will be part of the 0.7 release

Paul

**Comment by radeksimko** [comment]
Added in https://github.com/hashicorp/terraform/pull/7383 which will be part of the next release (`0.7`).
