### ISSUE TITLE
Math Interpolation - floor & ceil

### ISSUE THREAD

**Issue by rjinski** [hashicorp/terraform#7409]
Is it possible to add math functions for floor(float) and ceil(float) ?

**Comment by kesor** [comment]
I would also add `min` and `max` to this request.

One example for usage of these would be -
```
resource "aws_nat_gateway" "nat" {
  count = "${min( length(var.azs), length(var.private_subnets) }"
}
```

**Comment by zdzolton** [comment]
(I have already had to hack an implementation for all four of these!)
