### ISSUE TITLE
Errors aren't always obvious in output and aren't always aggregated

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#742]
I ran an `apply` and had to scrollback to see why an instance wasn't created:

`aws_instance.mail: Error: Error launching source instance: EBS-optimized instances are not supported for your requested configuration. Please check the documentation for supported configurations. (Unsupported)`

It would be nice if this was color-coded or if it appeared in the error summary in the end.  I had a different error show up (related to another resource) in the summary.

**Comment by phinze** [comment]
We've made a bunch of improvements on error reporting in the time since this has been filed and I believe errors like this should be bubbled up today, feel free to follow up if you believe there's still a remaining TODO here on the latest Terraform version.
