### ISSUE TITLE
AWS provider: API gateway custom domain names

### ISSUE THREAD

**Issue by OliverCole** [hashicorp/terraform#7421]
### Terraform Version
Terraform v0.6.16

### Feature request?

Looking at the Terraform documentation, it doesn't seem to support custom domains on the AWS API gateway. Is that a feature yet to be developed?

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html

**Comment by apparentlymart** [comment]
At first glance it looks like this is just creating a cloudfront distribution in front of the API gateway, in which case it may be possible to replicate what the UI does here using the `aws_cloudfront_distribution` resource, though admittedly it would take some work to figure out what Cloudfront settings are used when creating it in order to mimic this in the Terraform configuration.

**Comment by OliverCole** [comment]
That's what I thought, but it isn't listed in the Cloudfront GUI.

I need to give https://github.com/dtan4/terraforming a go anyway, so I'll see if it shows up as Cloudfront there.

**Comment by OliverCole** [comment]
Scratch that. `terraforming` doesn't handle Cloudfront or API gateway as far as I can tell.

**Comment by stack72** [comment]
Hi folks

I think this requires a new resource:

`aws_api_gateway_custom_domain` as there is an entire section of this in the cli docs http://docs.aws.amazon.com/cli/latest/reference/apigateway/create-domain-name.html

Thoughts?

P.

**Comment by apparentlymart** [comment]
It does indeed seem that there is [a set of API endpoints specifically for this](https://docs.aws.amazon.com/apigateway/api-reference/resource/domain-name/), so I guess it *does* do something more than just creating a regular cloudfront distribution.

These are already exposed in the client library, so hopefully not too hard to add:
* [CreateDomainName](https://godoc.org/github.com/aws/aws-sdk-go/service/apigateway#APIGateway.CreateDomainName)
* [UpdateDomainName](https://godoc.org/github.com/aws/aws-sdk-go/service/apigateway#APIGateway.UpdateDomainName)
* [DeleteDomainName](https://godoc.org/github.com/aws/aws-sdk-go/service/apigateway#APIGateway.DeleteDomainName)
* [GetDomainName](https://godoc.org/github.com/aws/aws-sdk-go/service/apigateway#APIGateway.GetDomainName)

**Comment by gthole** [comment]
This will also want to include "BasePathMapping" resources for attaching Rest API resources to the custom domain.
