### ISSUE TITLE
AWS EFS support

### ISSUE THREAD

**Issue by zrml** [hashicorp/terraform#7425]
Hi,

I'm interested in TF support for the new AWS Elastic File System (EFS) announced yesterday.
Do you know when this new resource definition will be added?

Please see here
https://aws.amazon.com/efs/

Thank you very much

**Comment by stack72** [comment]
Hi @zrml 

EFS support has been in terraform for a while:

https://www.terraform.io/docs/providers/aws/r/efs_file_system.html

Paul

**Comment by zrml** [comment]
ops. Thank you @stack72

**Comment by seongyongkim** [comment]
But there's no data for efs or efs mount target.  This is really needed.
