### ISSUE TITLE
spinup 2 ELB in AWS by using terraform

### ISSUE THREAD

**Issue by srikanthgorrepatig** [hashicorp/terraform#7426]
Hai,
     i have to spinup 2 ELB in AWS by using terraform,i am grtting errors like permission denied please help me
Regards,
srikanth

**Comment by stack72** [comment]
Hi @srikanthgorrepatig 

Please can you post the config that you are using for the ELB here (remember to remove any secret information!) and an output of the Terraform plan / apply

This will help us to try and diagnose the error you are getting

Paul

**Comment by stack72** [comment]
Closing this as there is no information on which we can reproduce the error. Please comment if you need more help

Paul
