### ISSUE TITLE
New AWS region ap-south-1 (Mumbai) is not supported

### ISSUE THREAD

**Issue by vamsee** [hashicorp/terraform#7429]
Hi,

AWS just opened a new region ap-south-1 (Mumbai) and currently it gives this error when I run terraform plan (v0.6.16):

```
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Not a valid region: ap-south-1
```

Please add support for this region.

**Comment by stack72** [comment]
Hi @vamsee 

This has been added to the upcoming 0.7 release

Paul

**Comment by vamsee** [comment]
Thanks @stack72 !

**Comment by MangalickMitra** [comment]
Issue still persists in release 0.9.1

**Comment by stack72** [comment]
Hi @MangalickMitra 

We 100% support the `ap-south-1` region

What issues are you facing?

Paul

**Comment by MangalickMitra** [comment]
When passing the region "ap-south-1" to provider via a .tfvars file, it was giving error  **"Not a valid region: ap-south-1"**

However when I added a variable block and mentioned a default section like below and then passed the .tfvars file, terraform plan and apply executed successfully

variable "region" {
  type    = "string"
  default = "ap-south-1"
}

**Comment by stack72** [comment]
Can you show me your provider block?

**Comment by MangalickMitra** [comment]
######## instance.tf########
variable "abc" {
  type    = "string"
}
variable "def" {
  type    = "string"
}
variable "region" {
  type    = "string"
  default = "ap-south-1"
}
provider "aws" {
  access_key = "${var.abc}"
  secret_key = "${var.def}"
  region = "${var.region}"
  insecure = true
}

resource "aws_instance" "Nirvana" {
  ami = "ami-8f8afde0"
  instance_type = "t2.micro"
  tags {
    Name = "Nirvana"
  }

#########secret.tfvars#########

abc="accessKeyHere"
def="secretKeyHere"
region="ap-south-1"

**Comment by vamsee** [comment]
@MangalickMitra try using the full region - like "ap-south-1a" or "ap-south-1b".

**Comment by catsby** [comment]
I've verified `ap-south-1` works as expected:

- https://gist.github.com/catsby/e6af3b077cebbbfaaf48e7c92ef992ef

If you can take those configurations I've shared and reproduce in Terraform v0.9.1, please provide the full log of `terraform apply`.
