### ISSUE TITLE
consul_keys not exposing attribute for key

### ISSUE THREAD

**Issue by jniesen** [hashicorp/terraform#7438]
### Terraform Version

```
~ terraform -v
Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)
```
### Affected Resource(s)
- consul_keys
### Terraform Configuration Files

``` hcl
provider "consul" {
  address    = "${var.consul_addr}"
  datacenter = "${var.consul_dc}"
  scheme     = "${var.consul_scheme}"
}

resource "consul_keys" "ro" {
  key {
    name = "ami"
    path = "${var.ami_path}/${var.ami_version}"
  }
}

resource "aws_launch_configuration" "a" {
  name_prefix   = "artifactory-"
  instance_type = "t2.large"
  image_id      = "${consul_keys.ro.var.ami}"
  key_name      = "${var.ssh_key_name}"
  security_groups = [
    "${aws_security_group.a.id}"
  ]

  lifecycle {
    create_before_destroy = true
  }
}

```
### Debug Output

https://gist.github.com/jniesen/7997ba2f475a0d8637a1a58f16cbe2da
### Expected Behavior

Successful plan.
### Actual Behavior

```
~ terraform plan .
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.terraform_remote_state.manheim2_vpc: Refreshing state...

Error running plan: 1 error(s) occurred:

* Resource 'consul_keys.ro' does not have attribute 'var.ami' for variable 'consul_keys.ro.var.ami'
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by kuss** [comment]
Has there been any progress on this issue?

**Comment by apparentlymart** [comment]
Hi @jniesen! Sorry for the problems here.

Since 0.7.0-rc2 there were some changes to `consul_keys` to split off the "read" functionality to a data source, making the resource be just for writing.

In the process, some of the functionality was reworked such that this issue might now be fixed or changed in some way. Would you mind trying this again on 0.7.0 final, with the config updated to use the new data source?:

```hcl
provider "consul" {
  address    = "${var.consul_addr}"
  datacenter = "${var.consul_dc}"
  scheme     = "${var.consul_scheme}"
}

data "consul_keys" "ro" {
  key {
    name = "ami"
    path = "${var.ami_path}/${var.ami_version}"
  }
}

resource "aws_launch_configuration" "a" {
  name_prefix   = "artifactory-"
  instance_type = "t2.large"
  image_id      = "${data.consul_keys.ro.var.ami}"
  key_name      = "${var.ssh_key_name}"
  security_groups = [
    "${aws_security_group.a.id}"
  ]

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by jniesen** [comment]
I was hoping that was going to be the case. Tomorrow, I'll try this out and
let you know if I run into problems or just close the issue. Thank you for
the update @apparentlymart.
