### ISSUE TITLE
Add a wait parameter to aws_volume_attachment

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform#7450]
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

aws_volume_attachment
### Terraform Configuration Files

``` hcl
resource "aws_volume_attachment" "ebs_bootstrap" {
  device_name = "/dev/xvdc"
  volume_id = "${aws_ebs_volume.backend_storage.0.id}"
  instance_id = "${aws_instance.bootstrap_node.id}"
  force_detach = "${var.ebs_force_detach}"
}
```
### Expected Behavior

volume is detached from EC2 instance after waiting up to specified timeout value in aws_volume_attachment resource.
### Actual Behavior

Sometimes, EC2 instances take a long time to detach an EBS volume.  Terraform seems to have an internal timeout, as I usually get an error message stating that the volume did not become detached in the allotted time. I'd like to suggest adding a timeout property to aws_volume_attachment; whereby terraform will wait for the volume to become detached. Likewise, this property would affect the timeout while attaching the volume to the instance.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`

**Comment by jen20** [comment]
Hi @haidangwa! Thanks for opening an issue here. I have a question: is there a good reason to expose this versus turning up the internal timeout and fixing this transparently? Is there something about the specific attachments that allow you to predict it will take a long time to detach?

**Comment by haidangwa** [comment]
@jen20 If there is a better way to handle this, I'm all for it. It seems easy for me, if I can adjust the timeout, but I can understand the reasons for not using a timeout. In my use case, I don't think I am doing anything "special" or in a way I can predict when this happens. I am merely seeing symptoms that seem to occur on every destroy with an attached EBS volume. the detachment fails, because the instance has not fully been terminated. If I merely wait for the instance to be terminated, I can manually detach the volume, but terraform is still "stuck", thinking that it can't detach the volume or that the volume is still attached.

**Comment by jwadolowski** [comment]
I experienced sort of the same issue, but during EBS attachment. Attachment time can significantly increase if `aws_instnace` setup involves reboot:

```tf
resource "aws_instance" "backend" {
  ...
  provisioner "remote-exec" {
    inline = [
      "sudo reboot",
    ]
  }
}

resource "aws_ebs_volume" "backend-ebs" {
  availability_zone = "${var.availability_zone}"
  type                     = "${var.content_block_device_type}"
  size                      = "${var.content_block_device_size}"
}

resource "aws_volume_attachment" "backend-ebs-att" {
  device_name = "${var.content_block_device_name}"
  volume_id   = "${aws_ebs_volume.backend-ebs.id}"
  instance_id = "${aws_instance.backend.id}"
}
```

During `terrafrom apply` random amount of attachments always ends with

```
2017/01/06 21:03:59 [ERROR] root.backend: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
* aws_volume_attachment.backend-ebs-att: Error waiting for Volume (vol-093180e6dhaf5f313) to attach to Instance: i-00a53dga185k594ba, error: timeout while waiting for state to become 'attached' (last state: 'attaching', timeout: 5m0s)
```

In AWS panel I got information that one of my volumes stuck in `attaching` state and link to troubleshooting guidelines. At the end of the day (usually after less than a minute) transition from `attaching` to `attached` state always succeeded without any manual involvement. Despite of that `terraform apply` failed as built-in `aws_volume_attachment` timeout was reached.

5m sounds like a really sane default, but it'd be great to have an option to increase that (i.e as in `connection` provisioner).

PS. I'm on Terraform 0.8.2
