### ISSUE TITLE
Allow creating list in interpolations

### ISSUE THREAD

**Issue by wr0ngway** [hashicorp/terraform#7460]
### Terraform Version

Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)

### Affected Resource(s)

Interpolations

### Terraform Configuration Files
N/A
### Debug Output
N/A
### Panic Output
N/A
### Expected Behavior

I have some variables that I'd like to pass into a resource.  Sometimes, some of those variables can be empty string, so I'd like to be able to use compact.  However, I don't have those variables in a list format, so cannot use compact.  It would be nice if there was a varag list() for creating the list so that I could pass it into compact.

I can do something like:

    value = "${compact(split(",", format("%s,%s", var.var1, var.var2)))}"

So the capability is there, but would be much nicer if I could do:

    value = "${compact(list(var.var1, var.var2))}"

### Actual Behavior
N/A
### Steps to Reproduce
N/A
### Important Factoids
N/A
### References
N/A

**Comment by jen20** [comment]
Hi @wr0ngway! We had been discussing internally a representation of list literals in HIL but hadn't come up with anything satisfactory and implementable right now. This provides a nice easy way forward and I think a reasonable usability improvement as you say.

cc @phinze but I will put together an initial implementation of this shortly and PR for further discussion.
