### ISSUE TITLE
AWS provider: Support API gateway 'Body mapping templates' passthrough behaviour

### ISSUE THREAD

**Issue by OliverCole** [hashicorp/terraform#7475]
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-method-settings-execution-console.html - step 3

The **aws_api_gateway_integration** resource supports the body mapping templates, but neither the **aws_api_gateway_method** or **aws_api_gateway_integration** resources seem to support choosing one of the three defined behaviours:
 - When no template matches the request Content-Type header 
 - When there are no templates defined (recommended)
 - Never

**Comment by iceycake** [comment]
Anyone is going to work on this?

**Comment by iceycake** [comment]
Looks like we have to update to aws sdk 1.2.7 in order to use the new API for PassthroughBehavior

BTW, isn't this issue same as #7141 ?

**Comment by stack72** [comment]
Closed via #7801
