### ISSUE TITLE
diffs didn't match during apply (openstack/ovh)

### ISSUE THREAD

**Issue by joaocc** [hashicorp/terraform#7478]
### Terraform Version
0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2.servers

### Debug Output
```
module.docker-build.openstack_compute_instance_v2.servers.1: Creation complete
Error applying plan:

1 error(s) occurred:

* openstack_compute_instance_v2.servers.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.6.16
    Resource ID: openstack_compute_instance_v2.servers.0
    Mismatch reason: attribute mismatch: volume.~1100579671.device
    Diff One (usually from plan): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"volume.~3834767419.id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~3834767419.volume_id":*terraform.ResourceAttrDiff{Old:"", New:"${element(split(\",\", module.data_disk_2.volumes_id), count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~3834767419.device":*terraform.ResourceAttrDiff{Old:"", New:"/dev/vdc", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~1100579671.id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~1100579671.volume_id":*terraform.ResourceAttrDiff{Old:"", New:"${element(split(\",\", module.data_disk_1.volumes_id), count.index)}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "volume.~1100579671.device":*terraform.ResourceAttrDiff{Old:"", New:"/dev/vdb", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```

### Expected Behavior
Second server, disks and dns resources to be added.

### Actual Behavior
The crash mentioned above.

### Steps to Reproduce
didn't yet try to reproduce

### Important Factoids

I have been testing a quite complex (maybe unnecessarily so) set of TF scripts to setup N servers, each with 2 disks, and the corresponding DNS entries in Route53 and Cloudflare.

VM provider os OpenStack on OVH, and state is stored in S3 files.
Provisioning after install is made via ansible.

Everything runs inside a local docker image.

Things were stable with 1 machine, so I decided to try adding a second server by increasing the count to 2. Provisioning of the server went well

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform/issues/7477.

**Comment by jtopjian** [comment]
@joaocc I think this might be more related to #3449 than #7477. Any `diffs didn't match` error that involve `count`, `element`, and/or splat of any sort, I've been chalking up to #3449. So far, that has been a correct assumption.

You mentioned increasing the count, but I just want to confirm if you're using `element` or a splat (`*`)?

**Comment by joaocc** [comment]
To be honest, I am not sure where to look for the information you are asking about.
I believe I use both (element(.....*...., count.index)) and (....*.....) in different places.
If you can be more specific I can try to provide an accurate answer.
Thx

**Comment by jtopjian** [comment]
@joaocc sorry about the late reply on this. That's exactly what I was looking for: if you're using `element` within your Terraform configuration. It sounds like you are, so I'm thinking this is related to bug #3449. It's more of a Terraform core issue than an OpenStack-specific issue.

I'm going to close this in favor of #3449. If you'd like, subscribe to that issue and you'll get notified when it's been fixed. I believe there's also a workaround that has helped a few people described there.

Please feel free to re-open this issue if you'd like to discuss further or have any questions. 😄
