### ISSUE TITLE
Modifying main routing table in AWS

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#748]
I want to amend an auto-created AWS routing table with:
```
gateway_id = ${aws_internet_gateway.x.id}
```

According to the docs, I can currently access `${aws_vpc.x.main_route_table_id}`, but I cannot see a way of referring to it anywhere other then in `aws_route_table_association`, which doesn't help much here.

**Comment by phinze** [comment]
Just landed #918, which does not allow directly customizing the auto-created route table, but _does_ allow you to attach a user-defined route table that as the main route table for a VPC. I believe this should cover pretty much all use cases, with the minor caveat that we have to leave the auto-created route table chilling in the VPC :snowflake:. Feel free to reopen if this doesn't meet your needs.

This will come out in `0.3.7`, but you're welcome to take it for a spin on master - feedback is welcome!
