### ISSUE TITLE
provider/aws: destroying KMS key blocks terraform shutdown

### ISSUE THREAD

**Issue by bhuisgen** [hashicorp/terraform#7480]
Hello,

When a AWS KMS key needs to be destroyed, terraform waits the completion of the operation which is impossible as the key will enter the pending deletion period of 7 to 30 days. It's probably better to skip it :)

### Terraform Version

0.6.16

### Affected Resource(s)

aws_kms_key

### Terraform Configuration Files

```hcl
resource "aws_kms_key" "mykey" {
    description = "KMS key"
}
```

### Steps to Reproduce

After creation on AWS, remove the resource from your configuration file and apply modifications:

```
18:12 $ terraform plan <...>
- aws_kms_alias.mykey
- aws_kms_key.mykey
Plan: 0 to add, 0 to change, 2 to destroy.

18:12 $ terraform apply plan.out
aws_kms_alias.mykey: Destroying...
aws_kms_alias.mykey: Destruction complete
aws_kms_key.mykey: Destroying...
aws_kms_key.mykey: Still destroying... (10s elapsed)
aws_kms_key.mykey: Still destroying... (20s elapsed)
aws_kms_key.mykey: Still destroying... (30s elapsed)
aws_kms_key.mykey: Still destroying... (30s elapsed)
aws_kms_key.mykey: Still destroying... (40s elapsed)
aws_kms_key.mykey: Still destroying... (50s elapsed)
^CInterrupt received. Gracefully shutting down...
^CTwo interrupts received. Exiting immediately. Note that data
loss may have occurred.
```

**Comment by stack72** [comment]
Hi @bhuisgen 

Thanks for opening the issue here, sorry this is causing you some issues. Right now, we actually only wait for the key to go into the `pending deletion` state. We have automated tests that run every night to test that we can create, update and delete kms keys

If you let your example run a little longer. To create and delete a KMS Key in our tests takes about 140seconds

Hope this helps

Paul

**Comment by bhuisgen** [comment]
Ok, good for me.

```
18:34 $ terraform apply plan.out
aws_kms_key.mykey: Destroying...
aws_kms_key.mykey: Still destroying... (10s elapsed)
aws_kms_key.mykey: Still destroying... (20s elapsed)
aws_kms_key.mykey: Still destroying... (30s elapsed)
aws_kms_key.mykey: Still destroying... (40s elapsed)
aws_kms_key.mykey: Still destroying... (50s elapsed)
aws_kms_key.mykey: Destruction complete

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

**Comment by stack72** [comment]
Excellent :)
