### ISSUE TITLE
0.7.0 modules problem

### ISSUE THREAD

**Issue by evilezh** [hashicorp/terraform#7484]
Here is strange behavior (0.7.0-rc2, windows 10, powershell).
If I do terraform get ... and module fails to load:
PS C:...\terraform\basic-cloud> terraform get
Get: file://C:/....
...
Get: file://C:/....-mEersroosr- slpooatd-ivn2g- eTbesr
raform: Error downloading modules: module ....: Error loading .terraform\modules\87b8653db5e1460a0bc6e390566e25ac\main.tf: Error reading config for aws_spot_instance_request[instance_request]: parse error
: syntax error

After that i found that plenty of my module sources is deleted. Directories remains, but all .tf files is gone.

**Comment by jbardin** [comment]
Hi @evilezh,

I have a feeling this is the same root  issue that caused #7238, which was fixed by #7273.

Is it possible for you to test this behavior from the latest master branch? If not, can you provide me with a configuration to reproduce the issue?

Thanks!

**Comment by mitchellh** [comment]
This is either what @jbardin so or it can simply be a syntax error in a module and it rolling back everything (that's what the error seems to indicate). Regardless, there hasn't been a response in awhile so I'm going to close this.
