### ISSUE TITLE
No need to recreate aws instances to update security_groups

### ISSUE THREAD

**Issue by ojongerius** [hashicorp/terraform#749]
resource_aws_instance.go forces new creation of an instance when security groups change. According to the docs this is not need, and ModifyInstanceAttribute does support it on an running instance. See [AWS doco](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html) .

To do this we could remove ForceNew from security_groups and let resourceAwsInstanceUpdate handle it.

**Comment by mitchellh** [comment]
Yeah we did this temporarily since we didn't have the logic to update. I'll take a look at your PR soon! Thanks :)

**Comment by ojongerius** [comment]
@mitchellh do you agree with the approach mentioned the closing comment?

> If we want support for security_group names in the config and modify running instance we need to use the IDs.
> We can get the IDs from AWS, but it would imply another call out to AWS (DescribeSecurityGroups) and figure out what the IDs are.

**Comment by brycekahle** [comment]
It is worth noting that this only works in a VPC.

**Comment by matheeeny** [comment]
Just ran into this one. Would be nice to see it fixed.

**Comment by catsby** [comment]
Same as #194

**Comment by mitchellh** [comment]
This should be fixed for 0.5.0
