### ISSUE TITLE
Caching remote sources

### ISSUE THREAD

**Issue by samber** [hashicorp/terraform#7503]
Hi there,

Defining an external source is very powerful, but download an entire remote repository can take time.

It would be awesome to cache remote repositories in a `$HOME/.terraform` directory, different than the `.terraform/` of your project. What do you think ?

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
