### ISSUE TITLE
provider/openstack: Can not create firewall rule with "any" protocol

### ISSUE THREAD

**Issue by carlpett** [hashicorp/terraform#7507]
### Terraform Version
Terraform v0.7.0-rc2

### Affected Resource(s)
- openstack_fw_rule_v1

### Terraform Configuration Files
```hcl
resource "openstack_fw_rule_v1" "test-case" {
  name = "test-case"
  action = "allow"
  protocol = "any"
  destination_ip_address = "1.1.1.2"
  source_ip_address = "1.1.1.1"
  enabled = "true"
}
```

### Expected Behavior
Create rule with protocol `any`

### Actual Behavior
`Expected HTTP response code [201 202] when accessing [POST https://OPENSTACK-PROVIDER:9696/v2.0/fw/firewall_rules], but got 400 instead
{"NeutronError": {"message": "Firewall Rule protocol any is not supported. Only protocol values [None, 'tcp', 'udp', 'icmp'] and their integer representation (0 to 255) are supported.", "type": "FirewallRuleInvalidProtocol", "detail": ""}}`

Setting `protocol = ""` gives `A protocol is required (tcp, udp, icmp or any)`, and `protocol = "0"` (since the error message indicated that numerals would be accepted) gives `Invalid input for protocol. Reason: '0' is not in [None, 'tcp', 'udp', 'icmp']`

**Comment by carlpett** [comment]
Actually, this seems to be more of a Gophercloud issue. I created a matching issue there: https://github.com/rackspace/gophercloud/issues/605

**Comment by jtopjian** [comment]
@carlpett Looping back around to this one. I have a PR opened here: https://github.com/gophercloud/gophercloud/pull/162

**Comment by carlpett** [comment]
Great work!
