### ISSUE TITLE
Support for vSphere TAGS and Categories

### ISSUE THREAD

**Issue by mistercaste** [hashicorp/terraform#7515]
Hi there,

Is it possible to provide support for the new VMWare vSphere Tags and Categories?
[Ref: Tagging Objects in the vSphere Web Client](https://pubs.vmware.com/vsphere-51/index.jsp#com.vmware.vsphere.vcenterhost.doc/GUID-E8E854DD-AA97-4E0C-8419-CE84F93C4058.html)
My company uses Tags to apply backup plans on the VMs and having Terraform handling this would really be a feature driving us towards it!

Thank you

**Comment by jbilbro** [comment]
This would also be beneficial when using the Ansible dynamic inventory scripts against my vsphere terraform files.

**Comment by shravanpn7** [comment]
We are currently using VM's "Configuration parameters" to add custom parameters thru terraform and then making ansible's dynamic inventory to fetch the "Configuration parameters" from the state file. Hope it helps @jbilbro

**Comment by jbilbro** [comment]
@shravanpn7 Mind elaborating a bit more?  

I've got something like this in the .tf file:

  custom_configuration_parameters {
    "ssh_user" = "vagrant",
    "role" = "webserver",
  }

and then using https://github.com/CiscoCloud/terraform.py to try and use the 'role' parameter as a dynamic group.  Not having a lot of luck so far.

**Comment by spapanaidu** [comment]
@jbilbro 

I am not familiar with CiscoCloud's Mantl but we have similar parameters in the .tf file :
```
custom_configuration_parameters {
    terraform_customer_name     = "customer_name"
    terraform_datacenter        = "dc_name"
    terraform_product           = "product_name"   
    terraform_role              = "app"
    terraform_node              = "1"
  }
```
We then have a custom [dynamic inventory script](http://docs.ansible.com/ansible/developing_inventory.html) for ansible to build the dynamic inventory.

This dynamic inventory script basically fetches the tfstate file and populates the ansible inventory with groups. The script should do something like below:

`group = "%s_%s" %(
                        custom_opt['custom_configuration_parameters.terraform_product'],
                        custom_opt['custom_configuration_parameters.terraform_role']
                     )`

So, my ansible inventory host file looks like

`
[productname1_rolename1]
[productname2_rolename2]
`
