### ISSUE TITLE
Error when adding multiple Security Group rules at once with OpenStack provider

### ISSUE THREAD

**Issue by qubitrenegade** [hashicorp/terraform#7519]
Hello,

I'm brand new to Terraform and am trying to convert some HEAT templates we have to Terraform.  One of my simplest HEAT templates just creates wide open firewall rules for debugging.  I am able to create the four rules, but it takes running `terraform apply` four times to do so.  What's interesting is the first run, it has three errors (four rules, creates one, generates three errors).  The second run it has two errors, but still only creates one rule (four rules, creates one, one was already generated, and generates two errors).  Third run is one error, one rule created and two rules preexisting.  And the fourth run creates the final rule.

If I comment out everything after the first `openstack_networking_secgroup_rule_v2` it runs every time without issue.
### Terraform Version

```
$ terraform -v
Terraform v0.6.16
```
### Affected Resource(s)
- openstack_networking_secgroup_rule_v2

It seems to be only multiple instances of `openstack_networking_secgroup_rule_v2` that cause the issue.
### Terraform Configuration Files

``` hcl
## =====  OpenStack Auth Boilerplate...
# Note to self:
# Really like to abstract this since it'll be used everywhere
#
# Set attributes in .tfvars file or terraform will prompt when
# you run `terraform plan`

variable "user_name" {
  type = "string"
  description = "OpenStack username"
}

variable "password" {
  type = "string"
  description = "OpenStack password"
}

variable "tenant_name" {
  type = "string"
  description = "OpenStack Tenant Name"
}

variable "auth_url" {
  type = "string"
  description = "OpenStack API Endpoint, see openrc file"
  default = "https://openstack.myexample.com:5000/v2.0"
}

variable "insecure" {
  type = "string"
  description = "Accept self signed SSL certificates?"
  default = "true"
}

# Configure the OpenStack Provider
provider "openstack" {
  user_name = "${var.user_name}"
  password = "${var.password}"
  tenant_name = "${var.tenant_name}"
  auth_url = "${var.auth_url}"
  insecure = "${var.insecure}"
}

## ===== End Boilerplate ===========  ##

variable "secgroup_name" {
  type = "string"
  description = "Unique name of the security group"
}

variable "secgroup_description" {
  type = "string"
  description = "Short description of sec group"
}

resource "openstack_networking_secgroup_v2" "secgroup" {
  name = "${var.secgroup_name}"
  description = "${var.secgroup_description}"
}

resource "openstack_networking_secgroup_rule_v2" "rule_ingress_all-v4-tcp" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
}

resource "openstack_networking_secgroup_rule_v2" "rule_egress_all-v4-tcp" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
}
resource "openstack_networking_secgroup_rule_v2" "rule_ingress_all-v6-tcp" {
  direction = "ingress"
  ethertype = "IPv6"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "::/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
}
resource "openstack_networking_secgroup_rule_v2" "rule_egress_all-v6-tcp" {
  direction = "egress"
  ethertype = "IPv6"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "::/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
```
### Debug Output

https://gist.github.com/qubitrenegade/67c04a53ebf9d5cb5efb16a63e710211

Because github, these are out of order.  I have named them "Run 1", "Run 2", etc. in the order they run.
### Panic Output

N/A
### Expected Behavior

First Run should create all four secgroup rules.
### Actual Behavior

Each subsequent run is able to create one secgroup rule, to create all four secgroup rules I have to run `terraform apply` four times.
### Steps to Reproduce

Please list the steps required to reproduce the issue:
1. `terraform apply`

This happens with a simple terraform apply.
### Important Factoids

We are using VIO (VMware Integrated OpenStack), but all the APIs should be the same...
### References

I had originally posted this to the mailing list here:  https://groups.google.com/forum/#!topic/terraform-tool/mvNH8fUbYGA

I wanted to confirm this wasn't expected behavior since I'm brand new to Terraform.

Thanks!
- Q

**Comment by sagg55** [comment]
I can second that we are also hitting this issue during testing - Not sure if it's related but we are also using VIO (VMware Integrated OpenStack)

**Comment by jtopjian** [comment]
I'm sorry for the delay on this. I reviewed the logs and it I suspect this might be limited to vmware. I'm seeing 500 errors in the debug output so something is failing on the server.

Can either of you try making the next security group depend on the previous one so that they are all created in serial? For example:

```hcl
resource "openstack_networking_secgroup_rule_v2" "rule_ingress_all-v4-tcp" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
}

resource "openstack_networking_secgroup_rule_v2" "rule_egress_all-v4-tcp" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = "1"
  port_range_max = "65535"
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"

  depends_on = ["openstack_networking_secgroup_v2.rule_ingress_all-v4-tcp"]
}
```

Additionally, are you able to obtain any server logs that might give more details to why the subsequent groups are not being created?

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!

**Comment by qubitrenegade** [comment]
For the sake of [documenting a solution](https://xkcd.com/979/), I was able to resolve the issue by declaring dependencies on previous rules.

   provider "openstack" {
      insecure = "true"
    }
    
    
    variable "secgroup_name" {
      type = "string"
      description = "Unique name of the security group"
      default = "testing-secgroup"
    }
    
    variable "secgroup_description" {
      type = "string"
      description = "Short description of sec group"
      default = "Testing creating secgroups with terraform"
    }
    
    resource "openstack_networking_secgroup_v2" "secgroup" {
      name = "${var.secgroup_name}"
      description = "${var.secgroup_description}"
    }
    
    resource "openstack_networking_secgroup_rule_v2" "rule_ingress_all-v4" {
      direction = "ingress"
      ethertype = "IPv4"
      protocol = "tcp"
      port_range_min = "1"
      port_range_max = "65535"
      remote_ip_prefix = "0.0.0.0/0"
      security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
      depends_on = ["openstack_networking_secgroup_v2.secgroup"]
    }
    
    resource "openstack_networking_secgroup_rule_v2" "rule_egress_all-v4" {
      direction = "egress"
      ethertype = "IPv4"
      protocol = "tcp"
      port_range_min = "1"
      port_range_max = "65535"
      remote_ip_prefix = "0.0.0.0/0"
      security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
      depends_on = [
        "openstack_networking_secgroup_v2.secgroup",
        "openstack_networking_secgroup_rule_v2.rule_ingress_all-v4"
      ]
    }
    resource "openstack_networking_secgroup_rule_v2" "rule_ingress_all-v6" {
      direction = "ingress"
      ethertype = "IPv6"
      protocol = "tcp"
      port_range_min = "1"
      port_range_max = "65535"
      remote_ip_prefix = "::/0"
      security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
      depends_on = [
        "openstack_networking_secgroup_v2.secgroup",
        "openstack_networking_secgroup_rule_v2.rule_egress_all-v4"
      ]
    }
    resource "openstack_networking_secgroup_rule_v2" "rule_egress_all-v6" {
      direction = "egress"
      ethertype = "IPv6"
      protocol = "tcp"
      port_range_min = "1"
      port_range_max = "65535"
      remote_ip_prefix = "::/0"
      security_group_id = "${openstack_networking_secgroup_v2.secgroup.id}"
      depends_on = [
        "openstack_networking_secgroup_v2.secgroup",
        "openstack_networking_secgroup_rule_v2.rule_ingress_all-v6"
      ]
    }

@sagg55 does that work for you?  We've just recently upgraded to VIO 3.0, but was still experiencing the same issue before declaring the `depends_on` block, so I don't think the upgrade to VIO 3.0 had any impact.

@mitchellh I can certainly open a new ticket, the workaround works though, it does seem to be a bit hackish to me.

**Comment by insidepacket** [comment]
I have the same issue in our Openstack deployment when adding multiple rules. In addition, we can see the similar issue when we try to destroy the security group and its rules.
[dzhang@OPS SecurityGroup]$ terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.
 
  Enter a value: yes
 
openstack_networking_secgroup_v2.secgroup_2: Refreshing state... (ID: 452f350d-caf0-447c-9d4f-2a03f1aef15c)
openstack_networking_secgroup_rule_v2.secgroup_rule_2: Refreshing state... (ID: 02d2f0af-ac26-4a4b-bc20-b95cfff8674a)
openstack_networking_secgroup_rule_v2.secgroup_rule_4: Refreshing state... (ID: 1f7efe77-a5a9-44ba-aef4-fa31b7422bbf)
openstack_networking_secgroup_rule_v2.secgroup_rule_3: Refreshing state... (ID: 420669d9-38c3-4e19-b19e-90f76701d2df)
openstack_networking_secgroup_rule_v2.secgroup_rule_5: Refreshing state... (ID: 3455beed-7f84-4d8e-bb96-6c44ed2c22ca)
openstack_networking_secgroup_rule_v2.secgroup_rule_1: Refreshing state... (ID: dc4e63cc-b227-4046-b0fd-9daf4b8b21d5)
openstack_networking_secgroup_rule_v2.secgroup_rule_4: Destroying...
openstack_networking_secgroup_rule_v2.secgroup_rule_3: Destroying...
openstack_networking_secgroup_rule_v2.secgroup_rule_2: Destroying...
openstack_networking_secgroup_rule_v2.secgroup_rule_1: Destroying...
openstack_networking_secgroup_rule_v2.secgroup_rule_5: Destroying...
openstack_networking_secgroup_rule_v2.secgroup_rule_5: Destruction complete
Error applying plan:
 
4 error(s) occurred:
 
* openstack_networking_secgroup_rule_v2.secgroup_rule_2: Error deleting OpenStack Neutron Security Group Rule: Internal Server Error
* openstack_networking_secgroup_rule_v2.secgroup_rule_3: Error deleting OpenStack Neutron Security Group Rule: Internal Server Error
* openstack_networking_secgroup_rule_v2.secgroup_rule_4: Error deleting OpenStack Neutron Security Group Rule: Internal Server Error
* openstack_networking_secgroup_rule_v2.secgroup_rule_1: Error deleting OpenStack Neutron Security Group Rule: Internal Server Error
 
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jtopjian** [comment]
@insidepacket Does the above mentioned dependency fix work for you? If not, can you open a new issue describing this.

As well, the latest release of Terraform includes an extra debugging option for OpenStack:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply/destroy
```

This will print out the OpenStack requests and responses which will be helpful for debugging the issue.

Thanks,
Joe

**Comment by insidepacket** [comment]
Hi Joe,

adding depnedency fix work for me as well. Thank you!

**Comment by insidepacket** [comment]
Hi Joe,


Thank you very much for reaching out.


As my update in Git, your solution of dependency works for me.


But I do have another issue around Terraform with Openstack.


When we add a new rule via Terraform, we will see the issue below the rule which we are going to add is the same as one of existing rules. I know this is kind of human error.


[dzhang@ausls1sd0011 SecurityGroupAdvance]$ terraform apply
openstack_networking_secgroup_v2.sg_db: Refreshing state... (ID: 505b6e3c-ed88-4747-a838-e413d0056777)
openstack_networking_secgroup_v2.sg_app: Refreshing state... (ID: b8839fe2-4599-48f6-b08b-14ab2507e669)
openstack_networking_secgroup_v2.sg_web: Refreshing state... (ID: 6c6a894c-ab2f-478a-a333-f538948128f6)
openstack_networking_secgroup_rule_v2.sg_db_rule_1: Refreshing state... (ID: ee6a5726-ad34-49d9-a0d2-642e46864818)
openstack_networking_secgroup_rule_v2.sg_db_rule_2: Refreshing state... (ID: f2fafe73-0cee-4bcf-a114-80f599cd3fec)
openstack_networking_secgroup_rule_v2.sg_web_rule_1: Refreshing state... (ID: cfed936f-cbb6-4865-bdde-dbc080628405)
openstack_networking_secgroup_rule_v2.sg_app_rule_1: Refreshing state... (ID: e6e12394-fcf5-4991-8f8d-b160243e4ebf)
openstack_networking_secgroup_rule_v2.sg_app_rule_2: Refreshing state... (ID: 8d912d77-b4b4-475e-a858-dcd5209b0849)
openstack_networking_secgroup_rule_v2.sg_web_rule_2: Refreshing state... (ID: 8e1dcfb9-f2db-4ea1-98bf-a03be55eab02)
openstack_networking_secgroup_rule_v2.sg_app_rule_3: Refreshing state... (ID: c400ad9d-d667-420b-9a98-03d3952facd5)
openstack_networking_secgroup_rule_v2.sg_web_rule_3: Refreshing state... (ID: fb4f2240-cd93-4d1c-9565-c5b7cfc6e6d5)
openstack_networking_secgroup_rule_v2.sg_web_rule_4: Refreshing state... (ID: deb39d06-251e-42cb-b345-c2c5d8d8c42a)
openstack_networking_secgroup_rule_v2.sg_app_rule_4: Creating...
  direction:         "" => "ingress"
  ethertype:         "" => "IPv4"
  port_range_max:    "" => "22"
  port_range_min:    "" => "22"
  protocol:          "" => "tcp"
  remote_group_id:   "" => "505b6e3c-ed88-4747-a838-e413d0056777"
  remote_ip_prefix:  "" => "<computed>"
  security_group_id: "" => "b8839fe2-4599-48f6-b08b-14ab2507e669"
  tenant_id:         "" => "2b8d09cb778346a4ae70c16ee65a5c69"
Error applying plan:

1 error(s) occurred:

* openstack_networking_secgroup_rule_v2.sg_app_rule_4: Expected HTTP response code [201 202] when accessing [POST http://controller.ops.com.au:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is c400ad9d-d667-420b-9a98-03d3952facd5.", "type": "SecurityGroupRuleExists", "detail": ""}}ops

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure..

This error created a big issue to us as we are using Openstack with VMware NSX via nsxv plugin.

When this error happened, all existing firewall rules in that security group are deleted in VMWare NSX although the delete rules are still in Openstack neutron security group configuration.

Is possible that we Terraform pre-check with state file and avoid this error?

It is highly appreciated if you can help a bit or give us some suggestions.

Best Regards,

David Zhang


________________________________

**Comment by jtopjian** [comment]
@insidepacket For existing rules, you should be using Terraform's "import" feature:

https://www.terraform.io/docs/import/index.html
https://www.terraform.io/docs/providers/openstack/r/networking_secgroup_rule_v2.html

If you have any further questions or issues, could you kindly open a new issue on Github?

Thanks,
Joe

**Comment by tomasquith** [comment]
I'm also getting the same issue using VIO 3.0!
