### ISSUE TITLE
Support for Google Cloud Router for VPN

### ISSUE THREAD

**Issue by cblecker** [hashicorp/terraform#7520]
Currently Terraform only supports GCP VPNs using static routing. I'd like to request an enhancement to support the Google Cloud Router which adds support for dynamic routing via BGP.

https://cloud.google.com/compute/docs/cloudrouter
https://cloud.google.com/compute/docs/reference/latest/routers

**Comment by codyrat** [comment]
I am also looking for this functionality in order to create full redundancy via BGP. In addition, the static VPN gateway has some deficiencies with CHILD_SA compatibility. I'll need to use an alternate platform if Terraform doesn't have plans to implement.

**Comment by cblecker** [comment]
@codyrat Is the issue you're seeing with CHILD_SA's on the Terraform side, or on the Google side? If it's the Terraform side you may wish to open a separate issue with details so it can get fixed (and doesn't get lost in this enhancement request).

**Comment by sherabi** [comment]
Would definitely love to see cloud router and dynamic BGP routing options. While these resources aren't critical when it comes to maintaining Infrastructure as code their absence leaves a gaping hole.

**Comment by drebes** [comment]
This is now supported as of 0.9.6.

**Comment by cblecker** [comment]
Fixed in #12411.

Thanks, @drebes !
