### ISSUE TITLE
Error refreshing state

### ISSUE THREAD

**Issue by hexedpackets** [hashicorp/terraform#753]
I just tried to use terrraform for the first time since mid-December and am getting "Error refreshing state:" with no additional error information. Nothing has changed in my state file or tf files since the last time I used it, so I'm really stumped by what could be happening here.

Running with TF_LOG=1 isn't very helpful. For multiple nodes I see:
`2015/01/07 11:07:06 [ERROR] Error walking 'aws_instance.api_dev':`

Again, with no additional error text after that. All of the "error walking" messages are related to an aws_instance, but the instances aren't related - they are across different environment, different dependancies, etc.

Tried on 0.3.1, 0.3.5, and 0.3.6 with the same result. I was previously using 0.3.5 successfully.

**Comment by hexedpackets** [comment]
Seems to have been a temporary error, refreshing is working now. Still, I wonder why there was no error information. Is it possible to get a more descriptive error in case this comes up again?

**Comment by mitchellh** [comment]
If that comes up again and you can reproduce it, please run with `TF_LOG=1`!

**Comment by aravind** [comment]
This is closed, but I ran into this same issue today - with a fairly simple setup.  Here is the output from plan.

$ TF_LOG=1 terraform plan
2015/01/30 12:51:15 [INFO] Terraform version: 0.3.6  4e11ed4327fa638a4c2587489a8660c69beb4047+CHANGES
2015/01/30 12:51:15 Detected home directory from env var: /home/aravind
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: atlas = /usr/bin/terraform-provider-atlas
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: aws = /usr/bin/terraform-provider-aws
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: cloudflare = /usr/bin/terraform-provider-cloudflare
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: cloudstack = /usr/bin/terraform-provider-cloudstack
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: consul = /usr/bin/terraform-provider-consul
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: digitalocean = /usr/bin/terraform-provider-digitalocean
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: dnsimple = /usr/bin/terraform-provider-dnsimple
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: google = /usr/bin/terraform-provider-google
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: heroku = /usr/bin/terraform-provider-heroku
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: mailgun = /usr/bin/terraform-provider-mailgun
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: null = /usr/bin/terraform-provider-null
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: file = /usr/bin/terraform-provisioner-file
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: local-exec = /usr/bin/terraform-provisioner-local-exec
2015/01/30 12:51:15 [DEBUG] Discoverd plugin: remote-exec = /usr/bin/terraform-provisioner-remote-exec
2015/01/30 12:51:15 Detected home directory from env var: /home/aravind
2015/01/30 12:51:15 Detected home directory from env var: /home/aravind
2015/01/30 12:51:15 [DEBUG] Attempting to open CLI config file: /home/aravind/.terraformrc
2015/01/30 12:51:15 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2015/01/30 12:51:15 [DEBUG] Creating graph for path: [root]
2015/01/30 12:51:15 [DEBUG] Starting plugin: /usr/bin/terraform-provider-aws []string{"/usr/bin/terraform-provider-aws"}
2015/01/30 12:51:15 [DEBUG] Waiting for RPC address for: /usr/bin/terraform-provider-aws
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 Plugin address: unix /tmp/tf-plugin274336115
2015/01/30 12:51:15 [DEBUG] Graph [root] created and valid. 5 nouns.
2015/01/30 12:51:15 [INFO] Validating provider: aws
2015/01/30 12:51:15 [DEBUG] aws_instance.sm: expanding to count = 1
2015/01/30 12:51:15 [INFO] Validating resource: aws_instance.sm
2015/01/30 12:51:15 [DEBUG] aws_route53_record.salt_master: expanding to count = 1
2015/01/30 12:51:15 [DEBUG] aws_eip.sm_ip: expanding to count = 1
2015/01/30 12:51:15 [INFO] Validating resource: aws_route53_record.salt_master
2015/01/30 12:51:15 [INFO] Validating resource: aws_eip.sm_ip
2015/01/30 12:51:15 [DEBUG] Creating graph for path: [root]
2015/01/30 12:51:15 [DEBUG] Graph [root] created and valid. 5 nouns.
2015/01/30 12:51:15 [DEBUG] Creating graph for path: [root]
Refreshing Terraform state prior to plan...

2015/01/30 12:51:15 [DEBUG] Graph [root] created and valid. 5 nouns.
2015/01/30 12:51:15 [INFO] Configuring provider: aws
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Building AWS auth structure
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Building AWS region structure
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing EC2 connection
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing ELB connection
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing AutoScaling connection
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing S3 connection
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing RDS connection
2015/01/30 12:51:15 terraform-provider-aws: 2015/01/30 12:51:15 [INFO] Initializing Route53 connection
2015/01/30 12:51:15 [DEBUG] aws_instance.sm: expanding to count = 1
aws_instance.sm: Refreshing state... (ID: i-e4749c1e)
2015/01/30 12:51:15 [INFO] Module root walking: aws_instance.sm (Graph node: aws_instance.sm)
2015/01/30 12:51:20 [ERROR] Error walking 'aws_instance.sm': Request has expired. Timestamp date is 2015-01-30T20:51:15Z (RequestExpired)
2015/01/30 12:51:20 waiting for all plugin processes to complete...
Error refreshing state: Request has expired. Timestamp date is 2015-01-30T20:51:15Z (RequestExpired)
2015/01/30 12:51:20 [DEBUG] /usr/bin/terraform-provider-aws: plugin process exited
$

**Comment by aravind** [comment]
found my problem..  Sorry for the noise.  The time on my machine was off.  Fixing my time resolved the issue.
