### ISSUE TITLE
file keyword add newline to content

### ISSUE THREAD

**Issue by gambol99** [hashicorp/terraform#7531]
Version: Terraform v0.6.16

Hi, i'm trying to read in the password from the file using the 'file' keyword, the problem is the content has a newline always appended when read (definitely no newline in the file), causing the rds declaration to break. Is there any way I can drop the newline? ... 

```HCL
#
## PostgreSQL Database for Kong
#
resource "aws_db_instance" "postgres" {
  allocated_storage       = "${var.kong_database_size}"
  db_subnet_group_name    = "${aws_db_subnet_group.proxy.name}"
  engine                  = "postgres"
  engine_version          = "9.5.2"
  instance_class          = "db.t2.large"
  multi_az                = false
  storage_encrypted       = true
  vpc_security_group_ids  = [ "${aws_security_group.database.id}" ]

  name                    = "kong"
  username                = "kong"
  password                = "${file(\"../secrets/db.credentials\")}"

  tags {
    Name        = "${var.environment}-proxy-database"
    Environment = "${var.environment}"
    Role        = "database"
  }
}
```

**Comment by jotacepea** [comment]
@gambol99 , this could be a "not so beautiful" workaround. And there could be side effects depending on your password (if contain white spaces). But could fix the problem for the time being:

`password                = "${replace(file(\"../secrets/db.credentials\"), "\n", "")}"`

**Comment by gambol99** [comment]
cheers @jotacepea ... I'll give it a go

**Comment by apparentlymart** [comment]
We also have an interpolation function `trimspace`, which removes leading and trailing whitespace, including newlines.

**Comment by mike-marcacci** [comment]
Why is this closed? I see that there are workarounds, but I can't see how this the intended behavior... is there a well-reasoned argument for adding a newline, or has this just "always been the case" here?

**Comment by mike-marcacci** [comment]
Indeed, [the docs](https://www.terraform.io/docs/configuration-0-11/interpolation.html#file-path-) explicitly state that:

> The contents of the file are read as-is.
