### ISSUE TITLE
Intermittent diff errors on aws_instance and aws_route53

### ISSUE THREAD

**Issue by joshpurvis** [hashicorp/terraform#754]
Platform: Terraform v0.3.5 (also just tried 0.3.6 as well), Ubuntu 14.04 64 bit

```
resource "aws_instance" "cass1" {
    ami = "ami-5ceb8034"
    instance_type = "m3.large"
    subnet_id = "${aws_subnet.private.id}"
    key_name = "MYKEY"
    availability_zone = "us-east-1a"
    tags {
        Name = "cass1"
    }
}
```

This was previously much more complicated (user_data, security_groups, iam_instance_profile, etc..), but I've reduced it to the barebones as shown above and still receiving this error intermittently:

```
aws_instance.cass1: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.
```

If I have multiple `aws_instance` resources it appears to be more likely to fail and It's not always the same resource that fails. It's also happening to the route53 resources associated with these instances, though I've removed these while trying to isolate the problem.

Very rarely it'll apply everything the first try with no errors. However, usually I have to run apply 3-4 times before it successfully launches my full infrastructure (5 instances and 5 dns records)

Also, I've actually destroyed my entire infrastructure (VPC, subnets, etc), and started a fresh tfstate file, and I'm experiencing the same issue.

Is there a way I can inspect more verbose logs as to what's going on with this diff error? The intermittent nature of the problem is making it very difficult to isolate.

Thanks!

**Comment by svanharmelen** [comment]
@joshpurvis if you `export TF_LOG=1` and run your test again, it should give much more output including both diffs... That should give you the info you need to understand what happens.

**Comment by joshpurvis** [comment]
Thanks @svanharmelen, that was the flag I was looking for.

Upon further investigation it looks like the underlying goamz library doesn't support private route53 hosted zones yet, so I'm guessing terraform doesn't know how to do a diff on the response. 

Terraform is actually is able to create them, it seems, but doesn't know how to properly do the diff, so it errors out on the first pass. Then on the second pass it sees that they exist and updates the state.

I assume this is because the API is very similar to the public DNS, except that the private hosted zones require a VPC to be associated:

http://docs.aws.amazon.com/Route53/latest/APIReference/API-create-hosted-zone-private.html

Here's the resource that caused the error (note I'm not using terraform to manage my hosted zones only the associated route53 records):

```
resource "aws_route53_record" "cass3" {
    zone_id = "Z2886Q6JFFEPRR"  # *.private.REDACTED.com
    name = "cass3.private.REDACTED.com"
    type = "A"
    ttl = "300"
    records = ["${aws_instance.cass3.private_ip}"]
}
```

Here's the output of my log:

2015/01/07 16:45:58 terraform-provider-aws: 2015/01/07 16:45:58 [TRACE] Waiting 3.2s before next try
2015/01/07 16:45:59 terraform-provider-aws: 2015/01/07 16:45:59 [DEBUG] Creating tags: []ec2.Tag{ec2.Tag{Key:"Name", Value:"cass3"}, ec2.Tag{Key:"Seed", Value:"10.0.1.149"}, ec2.Tag{Key:"#", Value:"2"}}
2015/01/07 16:45:59 [DEBUG] aws_route53_record.cass3: expanding to count = 1
2015/01/07 16:45:59 [INFO] Module root walking: aws_route53_record.cass3 (Graph node: aws_route53_record.cass3)
aws_instance.cass3: Creation complete
2015/01/07 16:45:59 [ERROR] Diffs don't match.

Diff 1: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"records.#":*terraform.ResourceAttrDiff{Old:"1", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

Diff 2: &terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"records.570719194":*terraform.ResourceAttrDiff{Old:"", New:"10.0.1.241", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"cass3.private.REDACTED.com", New:"cass3.private.REDACTED.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "type":*terraform.ResourceAttrDiff{Old:"A", New:"A", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "zone_id":*terraform.ResourceAttrDiff{Old:"Z2886Q6JFFEPRR", New:"Z2886Q6JFFEPRR", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "ttl":*terraform.ResourceAttrDiff{Old:"300", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}, "records.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Type:0x0}}, Destroy:false, DestroyTainted:false}

2015/01/07 16:45:59 [ERROR] Error walking 'aws_route53_record.cass3': aws_route53_record.cass3: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.

**Comment by mitchellh** [comment]
This is fixed thanks to @catsby's PR earlier this week #967
