### ISSUE TITLE
aws_cloudwatch_log returns an error "not found" on refresh.

### ISSUE THREAD

**Issue by alaimo** [hashicorp/terraform#7543]
I created an aws_cloudwatch_log_group using the command below.

```
resource "aws_cloudwatch_log_group" "consul" {
  name = "${var.name}/consul"
  retention_in_days = "14"
}
```

What I did: 
Issued a terraform refresh command to sync aws and my state file

Expected Result: 
The state file would remove its reference to the log group

Actual Result: 
The command failed with an error that the log group was "not found".

This is on Terraform version 0.6.16

**Comment by stack72** [comment]
Hi @alaimo 

I just opened a PR that fixes this up

Paul
