### ISSUE TITLE
aws_security_group

### ISSUE THREAD

**Issue by Andy--Rose** [hashicorp/terraform#7544]
Hi there,

This was unexpected behavior for creating a resource with poorly formed JSON. Notice the typo on the 2nd ingress between " and ]. 
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- aws_security_group
### Terraform Configuration Files

``` hcl
resource "aws_security_group" "netscaler_manager" {
  name = "${var.clustername}-netscalerEniManagement-${var.region}-node-sg"
  description = "Security Group for Management ENI"
  vpc_id = "${aws_vpc.fabric_vpc.id}"
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    security_groups = ["${aws_security_group.netscaler.id}"]
  }
  ingress {
    from_port = 443
    to_port = 443
    protocol = "tcp"
    security_groups = ["${aws_security_group.netscaler.id}]"
  }
}
```
### Debug Output

NONE
### Panic Output

NONE
### Expected Behavior

Terraform should have shown an error describing the mistake in the JSON and should not have completed the build.
### Actual Behavior

No error was shown and Terraform created the resource in AWS as if nothing was wrong. The ingress rule with the error did not appear in the provisioned AWS resource.
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

Nothing abnormal going on here.
### References

NONE

**Comment by mitchellh** [comment]
On master this reports a syntax error properly. :)
