### ISSUE TITLE
RDS instance size change does not actually apply

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#7546]
Terraform reports a change to an RDS Postgres DB instance size as successful but the change does not actually get applied.

We changed the `postgres_instance_type` variable:

```diff
 variable "instance_type" {
     default = {
         stage = "t2.micro"
-        prod = "t2.micro"
+        prod = "t2.medium"
     }
 }
```

Here is the end state config which results in change not being applied:

```hcl
variable "postgres_instance_type" {
    default = {
        stage = "db.t2.micro"
        prod = "db.t2.medium"
    }
}

resource "aws_db_instance" "postgres" {
    engine = "postgres"
    identifier = "postgres-${var.app_name}"
    name = "kong"

    username = "${var.rds_username}"
    password = "${var.postgres_password}"

    allocated_storage = "${lookup(var.rds_storage, var.env)}"
    apply_immediately = "${var.rds_apply_immediately}"
    backup_retention_period = "${var.rds_backup_retention_period}"
    backup_window = "${var.rds_backup_window}"
    db_subnet_group_name = "${aws_db_subnet_group.postgres.name}"
    final_snapshot_identifier = "postgres-${var.app_name}-final-snapshot"
    instance_class = "${lookup(var.postgres_instance_type, var.env)}"
    maintenance_window = "${var.rds_maintenance_window}"
    multi_az = "${lookup(var.rds_multi_az, var.env)}"
    publicly_accessible = false
    storage_type = "gp2"
    vpc_security_group_ids = [ "${aws_security_group.postgres.id}" ]

    lifecycle { prevent_destroy = true }

    tags {
        App = "${var.app_name}"
        Env = "${var.env}"
        Name = "${var.app_name}-postgres"
    }
}
```

Terraform apply tells me the resources were modified. It transitions from Modifying to Modifications complete within a few seconds so there is no way this can be right since RDS takes years to apply any change 😄 

```
module.kong.aws_db_instance.postgres: Modifying...
  instance_class: "db.t2.small" => "db.t2.medium"
module.kong.aws_db_instance.postgres: Modifications complete
```

This should have changed the db instance from a t2.small to t2.medium but RDS still shows t2.small.

<img width="623" alt="2016-07-07 at 9 04 40 pm" src="https://cloud.githubusercontent.com/assets/550256/16674467/7dc1c4bc-4486-11e6-8722-0c80449801e3.png">

We are running Terraform 0.6.16 in an Atlas environment.

**Comment by fromonesrc** [comment]
`apply_immediately = "${var.rds_apply_immediately}"` was getting set to false in prod so the modifications were pending

**Comment by catsby** [comment]
Hey @fromonesrc sorry for not getting back to you sooner ! I'm glad you figured this out. Please let me know if you need anything else
