### ISSUE TITLE
Enforcing state with aws_security_group_rule

### ISSUE THREAD

**Issue by kbruner** [hashicorp/terraform#7547]
Because of multiple circular dependencies among our AWS security groups, we're forced to create the groups with `aws_security_group` and then populate the rules with multiple `aws_security_group_rule` resources.  However, this method apparently does not enforce a Terraform-managed state for the security groups.  Rules that are added to a group outside of Terraform are ignored and not deleted.

Is there a way I'm missing to get Terraform to delete the out-of-band rules from security groups managed this way?  I would rather not have to manage a separate method that goes through and removes the rules.  Am I alone in thinking Terraform should be able to maintain an absolute state reflecting the contents of the Terraform configuration for this sort of resource?

**Comment by catsby** [comment]
Hey @kbruner – 

The short answer here is that `aws_security_group` with rules defined inline will enforce the state, such that rules defined out of band will be flagged and removed on the next plan/apply cycle. `aws_security_group_rule` are an additive resource, such that they are not concerned about what rules the security group they are assigned to has, so long as it has _this_ rule. 

Naturally, the two conflict. 

> Because of multiple circular dependencies among our AWS security groups, we're forced to create the groups with aws_security_group and then populate the rules with multiple aws_security_group_rule resources.

I'm curious, could you possibly give a concrete example of this? It sounds like you're defining your security groups in two phases (two plan/applies) to get this to work, is that the case? If we had an example config that demonstrates the problem perhaps we could help come to a solution for you.

Let us know!

**Comment by kbruner** [comment]
Hrm... each application type has its own .tf file (they are generated via Ruby ERB templating from a master config), and there are a lot of cross-dependencies, but here's a subset example:

```
// core-core-staging

resource "aws_security_group" "core-core-staging-sg" {
  name = "core-core-staging"
  description = "core-core group - "
  vpc_id = "${module.vpc.vpc_id}"

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks  = ["0.0.0.0/0"]
  }

  tags {
    "environment" = ""
    "Name" = "core_core_staging"
    "vpc" = "${var.vpc_name}"
  }
}

resource "aws_security_group_rule" "core-core-staging-8080-elb-core-core-staging" {
  type = "ingress"
  from_port = 8080
  to_port = 8080
  protocol = "tcp"

  security_group_id = "${aws_security_group.core-core-staging-sg.id}"
  source_security_group_id = "${aws_security_group.elb-core-core-staging-sg.id}"
}

resource "aws_security_group" "elb-core-core-staging-sg" {
  name = "elb-core-core-staging"
  description = "ELB for core-core group - "
  vpc_id = "${module.vpc.vpc_id}"

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    "environment" = "staging"
    "Name" = "elb-core_core_staging"
    "vpc" = "${var.vpc_name}"
  }
}

resource "aws_security_group_rule" "elb-core-core-staging-443-ds-staging" {
  type = "ingress"
  from_port = 443
  to_port = 443
  protocol = "tcp"

  security_group_id = "${aws_security_group.elb-core-core-staging-sg.id}"
  source_security_group_id = "${aws_security_group.ds-staging-sg.id}"
}

resource "aws_launch_configuration" "core-core-staging-lc" {
  name_prefix = "core-core-staging-"
  security_groups = ["${aws_security_group.core-core-staging-sg.id}", "${aws_security_group.all-staging-sg.id}"]
  [...]
}

[...]

// ds

resource "aws_security_group" "ds-staging-sg" {
  name = "ds-staging"
  description = "ds group - staging"
  vpc_id = "${module.vpc.vpc_id}"

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks  = ["0.0.0.0/0"]
  }

  tags {
    "environment" = ""
    "Name" = "ds_staging"
    "vpc" = "${var.vpc_name}"
  }
}

resource "aws_security_group_rule" "ds-staging-8443-elb-ds-staging" {
  type = "ingress"
  from_port = 8443
  to_port = 8443
  protocol = "tcp"

  security_group_id = "${aws_security_group.ds-staging-sg.id}"
  source_security_group_id = "${aws_security_group.elb-ds-staging-sg.id}"
}

resource "aws_security_group" "elb-ds-staging-sg" {
  name = "elb-ds-staging"
  description = "ELB for ds group - "
  vpc_id = "${module.vpc.vpc_id}"

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    "environment" = "staging"
    "Name" = "elb-ds_staging"
    "vpc" = "${var.vpc_name}"
  }
}

resource "aws_security_group_rule" "elb-ds-staging-8443-core-core-staging" {
  type = "ingress"
  from_port = 8443
  to_port = 8443
  protocol = "tcp"

  security_group_id = "${aws_security_group.elb-ds-staging-sg.id}"
  source_security_group_id = "${aws_security_group.core-core-staging-sg.id}"
}

[...]

resource "aws_launch_configuration" "ds-staging-lc" {
  name_prefix = "ds-staging-"
  security_groups = ["${aws_security_group.ds-staging-sg.id}", "${aws_security_group.all-staging-sg.id}"]
  [...]
}

[...]

```

**Comment by kbruner** [comment]
Any thoughts on this?
