### ISSUE TITLE
aws_instance security_groups state not getting refreshed correctly

### ISSUE THREAD

**Issue by bellkev** [hashicorp/terraform#7548]
Using  0.6.16.

`terraform show` after `terraform refresh` shows the following for security_groups:
```
  security_groups.# = 0
```

There are clearly security groups applied to the instance according to the AWS console though.

**Comment by catsby** [comment]
Hey @bellkev – if this is an Instance inside a VPC, and using the `vpc_security_group_ids` attribute in the configuration, then the values will show up there. `security_groups` is a sort of legacy attribute that should now only apply to Instances in EC2 Classic.

If you are using EC2 Classic and have a example configuration that is not using `vpc_security_group_ids` and still not showing in `security_groups`, I'll gladly take a look! 

Please check the state to verify `vpc_security_group_ids` are populated, and if so let me know and we can close this 😄 

Thanks!

**Comment by bellkev** [comment]
Ah, that does appear to do it. It looks like the different behavior for non-default vpcs is why I haven't seen this before (I usually test with the default).

In checking this, I noticed a couple other interesting things about security_group config:

1. LCs don't appear to support `vpc_security_group_ids`... Should they?
2. It looks like we're using an undocumented format for ingress/egress in SG rules: `security_groups = [...]`. Is that maybe old/deprecated? I don't suppose the `vpc_security_group_id` distinction is needed here?

**Comment by bellkev** [comment]
Also, it is weird that `security_groups` could be used to set security groups okay on a non-default VPC, but couldn't be read back on `refresh`. It sounds like that may be AWS API related though?

**Comment by bellkev** [comment]
Oh, and re-reading your original response, this is indeed the case:

> If you are using EC2 Classic and have a example configuration that is not using vpc_security_group_ids and still not showing in security_groups, I'll gladly take a look!

But switching to using `vpc_security_group_ids` seems to resolve the disparity.

**Comment by catsby** [comment]
Sorry for the trouble @bellkev – I'm going to close this for now. Let me know if you need anything else!
