### ISSUE TITLE
Would be nice to be able to see why resources need to be destroyed, even if errors occur

### ISSUE THREAD

**Issue by bellkev** [hashicorp/terraform#7549]
Using 0.6.16.

I recently ran `terraform plan` on a stack with an LC that depended on an ec2 instance. It resulted in a cycle with an error message like this:

```
* Cycle: aws_autoscaling_group.builder_asg, aws_launch_configuration.builder_lc (destroy), aws_instance.services (destroy), aws_instance.services, aws_launch_configuration.builder_lc
```

I believe the cycle makes sense as Terraform thinks it needs to destroy the instance, and the LC is create_before_destroy. However, in this case, it appeared to be an error that the instance should be changed/destroyed (see https://github.com/hashicorp/terraform/issues/7548), which made the cycle very difficult to understand, even with debug output.

Ultimately, I was able to remove the create_before_destory parameter on the LC and rerun `terraform plan`, which succeeded (even though it would fail if run because of the LC being in use), and the new plan output showed that Terraform thought (incorrectly) that the security groups on the instance were wrong.

It would have helped a lot to have the "(forces new resource)" type of output even when the cycle errors were happening, or some other way of asking "why do you think you need to destory this resource?"

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
