### ISSUE TITLE
provider/fastly: Implement condition support for Headers, others

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#7554]
For the first phase of development in the Fastly provider, support for `conditions` on attributes like `headers` or `gzip` (probably others) was not implemented. The various `condition`s each could use was left as a computed, not user specifiable attributes. 

When `request_settings`, support for `conditions` needed to be available, and at that point `conditions` were added, but I did not circle back and add support for them in `headers`, et.al. 

Now that `conditions` are available, we need to support them across all attributes possible.

**Comment by heythisisnate** [comment]
+1

Also Fastly supports applying `conditions` to a `backend`, which I would love to see supported here as well.

**Comment by hernan82arg** [comment]
+1

**Comment by invizinviz** [comment]
+1

**Comment by jeremylivingston** [comment]
This would be a great addition, as I'm unable to import quite a few of my services due to this limitation. Is there a timeframe for when this addition is expected? I'd be happy to help with any development if it's needed.

**Comment by msuterski** [comment]
@heythisisnate `request_condition` in `backend` is now in master

**Comment by catsby** [comment]
Hey looks like this was all addressed in #11843, thanks! And sorry for the delay on my part :/
