### ISSUE TITLE
Terraform crash when creating ELB in Eucalyptus

### ISSUE THREAD

**Issue by iamfuzz** [hashicorp/terraform#7555]
### Terraform Version
0.6.15 - Have also tried with latest development version

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_security_group
- aws_elb

### Panic Output
https://gist.github.com/iamfuzz/0bb957c743210793595fdaead348275d

### Expected Behavior
What should have happened?

Security group created
Instance spawned
nginx installed on instance
ELB created
ELB modified to front instance

### Actual Behavior
Everything worked except for the ELB, which came up, but does not respond.  It appears ha-proxy never started on it which is strange as if I create one manually, it's fine.

### Steps to Reproduce
1. Modify region list to include "eucalyptus"
2. Build and install terraform
3. `terraform apply`

[terraform-files.zip](https://github.com/hashicorp/terraform/files/354600/terraform-files.zip)

**Comment by catsby** [comment]
Hey @iamfuzz – We don't officially support Eucalyptus; we don't have any acceptance tests running for Eucalyptus _directly_, so we cannot guarantee Terraform will work with it. 

That said, the bug you reported stems from a nil pointer dereference with a property of the load balancer, according to the gist you shared. I've opened #7585 to address this, as it was a simple adjustment on our end for a bit of extra safety.
