### ISSUE TITLE
Compute instance doesn't remember it's network.port in Openstack.

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#7558]
### Terraform Version

0.6.16
### Affected Resource(s)

Please list the resources as a list, for example:
- openstack_compute_instance_v2
### Terraform Configuration Files

``` hcl
resource "openstack_compute_instance_v2" "test" {
  region = "ndc_as_b"
  name = "test_ports"
  image_name = "ubuntu"
  flavor_name = "m1.medium"

  network  {
    name = "Public_AGILE"
  }
  key_pair = "test"
}
```
### Expected Behavior

I should be able to reference a VIPs `self.network.0.port`
### Actual Behavior

Port isn't defined:

```
terraform show
terraform show
openstack_compute_instance_v2.k8s_vip:
...
  network.# = 1
  network.0.access_network = false
  network.0.fixed_ip_v4 = 96.118.55.135
  network.0.fixed_ip_v6 = [2001:558:fc11:1:f816:3eff:fea6:8ce0]
  network.0.floating_ip =
  network.0.mac = fa:16:3e:a6:8c:e0
  network.0.name = Public_AGILE
  network.0.port =
  network.0.uuid = 3ab7132d-d0b7-4cb2-94a2-e105f728c796
```

Note that the uuid listed is the network uuid.  The port UUID is undefined.

My current work around is to 1) create a port resource 2) assign that port resource to the network.  This doesn't really work very well.  At least in my OS install, when a compute instance gets deleted, it cascade deletes the attached port.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
At the moment, this is the correct behavior.

Configuring an instance's network by port ends up having different information available than configuring via network uuid or name. At the moment, port and name/uuid are almost mutually exclusive.

See #7401 and #6874 for some supplemental information.

You mention something about a VIP - can you provide an entire terraform configuration that would reference all components? Perhaps there is an alternative way to create the stack or maybe Terraform could be updated to have this work.

**Comment by matthughes** [comment]
Yeah, unfortunately this prevents being able to use local-exec provisioner to modify the neutron port.  I want to do something like this:

```
resource "openstack_compute_instance_v2" "test" {
  region = "ndc_as_b"
  name = "test_ports"
  image_name = "ubuntu"
  flavor_name = "m1.medium"

  network  {
    name = "Public_AGILE"
  }
  key_pair = "test"
  provisioner "local-exec" {
    command = "neutron --os-region-name ${var.os_region} --os-tenant-name ${var.os_tenant} port-update ${self.network.0.port} --allowed_address_pairs list=true type=dict ip_address=someOtherIp"
  }
}
```

A workaround is to create the port using openstack_networking_network_v2 and then assign that to the compute_instance via `network.port`.  This works...until you need to rebuild the compute instance.  In my openstack environment (Icehouse), when an instance is destroyed, it destroys the port.  

It doesn't appear terraform knows about this.  You rebuild the node, but in destroying the old node, you've destroyed the port.  This, in turn, means the new node can't be built because you're trying to assign a non-existent port to it.   So the first time you build everything, it works.  But rebuilding is a real PITA.

**Comment by jtopjian** [comment]
@matthughes That's a good point. There are some areas of the OpenStack provider that are starting to look like they need redesigned -- this is probably one of them. 

Thank you for the info. I'll keep this one open and hope to visit it at some point soon.

**Comment by matthughes** [comment]
My workaround for the time being is some scripting magic doing the port lookup via neutron:


```
> cat instanceToPort.sh
os_tenant=$1; shift
os_region=$1; shift
device_id=$1

neutron --os-tenant-name=$os_tenant --os-region-name=$os_region port-list -c device_id -cid | grep $device_id | sed 's/|.*| \(.*\) |/\1/g'
```

```
exec = "neutron port-update $(portToInstance.sh ${var.os_tenant} ${var.os_region} ${self.id}) ..."
```

Not ideal, but it works.
