### ISSUE TITLE
aws_launch_configuration:  block_device support 

### ISSUE THREAD

**Issue by xueshanf** [hashicorp/terraform#756]
Thanks to add  block_device support for aws_instance resource.  Any plan to add to aws_launch_configuration?

**Comment by skippy** [comment]
+1

**Comment by jschneiderhan** [comment]
Has anyone made any progress on this yet? I have a branch with it *almost* working https://github.com/jschneiderhan/terraform/tree/block-device-mapping-launch-configuration, but it istn't quite there. It creates the Launch Configuration with the Block Device Mappings, and I can see the DeviceName/VolumeSize/etc. in the AWS console, but on subsequent `terraform plan` calls it keeps trying to modify it, so I must be doing something wrong:

```
-/+ module.jschneiderhan.aws_launch_configuration.test
    ...
    block_device.1139171820.delete_on_termination: "" => "1" (forces new resource)
    block_device.1139171820.device_name:           "" => "/dev/sda1" (forces new resource)
    block_device.1139171820.encrypted:             "" => "<computed>" (forces new resource)
    block_device.1139171820.snapshot_id:           "" => "<computed>" (forces new resource)
    block_device.1139171820.virtual_name:          "" => "" (forces new resource)
    block_device.1139171820.volume_size:           "" => "150" (forces new resource)
    block_device.1139171820.volume_type:           "" => "<computed>" (forces new resource)
    ...
```

**Comment by jschneiderhan** [comment]
It looks like the problem that I was having with that branch is related to a different issue (https://github.com/hashicorp/terraform/issues/913). I submitted the updates as a PR, although it's dependent on https://github.com/mitchellh/goamz/pull/210 so it's currently marked as DON'T MERGE.

**Comment by josh-padnick** [comment]
#1 on this feature.  I have to manually create my Launch Config's until this is implemeneted :disappointed:

**Comment by xuwang** [comment]
+1 on this feature.

**Comment by ketzacoatl** [comment]
+1

**Comment by catsby** [comment]
I believe #1271 is a pull request for this, agree?

**Comment by jschneiderhan** [comment]
@catsby correct. #935 was the original PR, but it's since become out of date. @jwaldrip was awesome enough to fork it and bring it up to date #1271. I'm going to close #935 since #1271 is definitely the better PR at this point.

**Comment by catsby** [comment]
Closing this as well then in favor of #1271
