### ISSUE TITLE
Support for GCP Image Family when provisioning instances

### ISSUE THREAD

**Issue by cblecker** [hashicorp/terraform#7562]
When provisioning GCP instances off of public images, it appears that Google is moving to the use of the "image family" api, rather than the specific project/image format. This is shown in their documentation both [here](https://cloud.google.com/compute/docs/instances/create-start-instance#publicimage) and [here](https://cloud.google.com/compute/docs/images).

In addition to the current [image](https://www.terraform.io/docs/providers/google/r/compute_instance.html#image) argument in the google_compute_instance.disk block, there should be the option to instead use the [image family api endpoint](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb#L477-L494)

**Comment by zbjornson** [comment]
This already works if you specify a full URL in the `disk { image = ... }` field.

For a public image family:

`https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-8`

For a private image family:

`https://www.googleapis.com/compute/v1/projects/my-project/global/images/family/my-family`

It might be nice if it worked without the full URL though.

**Comment by cblecker** [comment]
Thanks for this, @zbjornson. Confirmed that specifying the full URL does indeed work.

**Comment by stack72** [comment]
Closed via #8083
