### ISSUE TITLE
provider/google: Disk size ignored during an instance creation

### ISSUE THREAD

**Issue by ehmo** [hashicorp/terraform#7565]
Hi guys,

I'm currently running on Terraform v0.6.16.

I want to create my own instance based on the public image and define my own disk. While `terraform apply` shows the correct size for the new disk, the disk created for the instance is of a different size (default) based on the size of the server.

```
  disk.#:                                              "" => "1"
  disk.0.auto_delete:                                  "" => "false"
  disk.0.image:                                        "" => "ubuntu-os-cloud/ubuntu-1604-xenial-v20160627"
  disk.0.size:                                         "" => "20"
  disk.0.type:                                         "" => "pd-ssd"
```

**Comment by sl1pm4t** [comment]
@ehmo - can you provide the config you used?
How are you determining the size of the disk after instance creation? From Google UI or using `df -h` (or similar) from within the VM? 
The reason I ask, is that for a while the base images didn't auto resize the root partition to fill the available disk.

**Comment by ehmo** [comment]
I just tried it and it is working now. It can be because of the reason you wrote. Anyway, all is good now.
