### ISSUE TITLE
GCE Error 400: Invalid value for field 'resource.metadata.items[1].key'

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#757]
I am seeing this with 0.3.6.
```
google_compute_instance.weave.1: Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.metadata.items[1].key': '#'.  Must be a match of regex '[a-zA-Z0-9-_]{1,128}', invalid
google_compute_instance.weave.2: Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.metadata.items[1].key': '#'.  Must be a match of regex '[a-zA-Z0-9-_]{1,128}', invalid
google_compute_instance.weave.0: Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.metadata.items[0].key': '#'.  Must be a match of regex '[a-zA-Z0-9-_]{1,128}', invalid
```

This is how I pass metadata ([see entire configuration](https://github.com/errordeveloper/weave-demos/blob/a843a5c2f4b03b2cc597b29d0aa85adfa5be941a/terraform-example/infra/main.tf#L2-L52)):
```
    metadata {
        user-data = "${file("cloud-config.yaml")}"
    }
```

**Comment by asbjornenge** [comment]
I'm also being hit by this. **startup-script** is another that fails because of this.

**Comment by sparkprime** [comment]
This can be worked around by adding an if block to avoid the erroneous "#" key, but I do not know if this is the right solution, as I am confused why this "#" key is appearing in the map in the first place.

http://codepad.org/4xCM3gWh

**Comment by svanharmelen** [comment]
@mitchellh shouldn't this be considered to be a bug in core? As this is due to adding the count (#) attribute to maps. So if you now get the map and iterate over it, the pound sign will be one of the keys... For sets this works differently as the count is not actually saved in the set.

I think maps should have the same behaviour and you should not contain the count in the returned/fetched map. What do you think?

**Comment by knuckolls** [comment]
Yeah i'd call it a bug. While it may be nice to have the count on the map, I agree that it shouldn't show up as a key in the map.
