### ISSUE TITLE
Sequence number format

### ISSUE THREAD

**Issue by jnst** [hashicorp/terraform#758]
I want to be able to using sequence number format.

For example, 
```
resource "aws_instance" "dev-web" {
  ami = "ami-xxxxxxxx"
  instance_type = "t2.micro"
  count = 11
  tags {
    Name = "dev-web${count.index}"
  }
}
````
This means to below..
- dev-web0
- dev-web10
- dev-web1
- dev-web2
- dev-web3
- dev-web4
- dev-web5
- dev-web6
- dev-web8
- dev-web9

Not good. Because,
- I want to start by 1
- I want to see by dictionaly order.

Ideal is..
- dev-web01 
- dev-web02
- dev-web03
- dev-web04
- dev-web05
- dev-web06
- dev-web07
- dev-web08
- dev-web09
- dev-web10
- dev-web11

As one of the solution, there is an additional Build Function and Four arithmetic operations.
```
format("", args)
```
```
Name = "dev-web${format("%02d", count.index + 1)}"
```

**Comment by mitchellh** [comment]
Where is the name sorting happening that you're seeing? Plans?

And yes, there is another issue somewhere that brought this up... I can't find it rigth now so I'll leave this open but its likely a dup.

**Comment by jnst** [comment]
Yes, plan.
I'm sorry, It was this order.
- dev-web0
- dev-web1
- dev-web10
- dev web2

**Comment by mitchellh** [comment]
Changing this to an enhancement for a `format` function, probably `sprintf`
