### ISSUE TITLE
Unable to create aws instance

### ISSUE THREAD

**Issue by ranjitshinde91** [hashicorp/terraform#7580]
I am using Terraform to create aws instance. But it says 
UnAuthorisedOperation: status code 403
you dont have to permisssion to perfork this operation.
However i can create instance, describe-instance using CLI with --no-verify-ssl option in the end of command.
Using Terraform resource gets tainted, and it displays same message while refreshing the state.
Is their any way to do tset --no-verify-ssl  in Terraform.

**Comment by catsby** [comment]
Hey @ranjitshinde91 – there is no way to use Terraform with the `--no-verify-ssl` equivalent as it stands; can you describe the use case for this? 

I'm going to go ahead and close this but please do let me know what kind of usage this is for

**Comment by ranjitshinde91** [comment]
@catsby : I am creating new instance, its creating it but after creation it prints error.
What are minimal permissions required to launch instance using Terraform?

**Comment by catsby** [comment]
Hey @ranjitshinde91 I just noticed that we do offer an `insecure` option to the AWS provider:

- https://www.terraform.io/docs/providers/aws/index.html

you should be able to provide `insecure` to your configuration and get the same results as `--no-verify-ssl`:


```hcl
provider "aws" {
  insecure = true
}
```

**Comment by ranjitshinde91** [comment]
@catsby Thank you man, will try that
