### ISSUE TITLE
plan/apply does not cleanup module output from tfstate files

### ISSUE THREAD

**Issue by olenm** [hashicorp/terraform#7598]
Terraform v0.6.16
aws_instance
- terraform does not cleanup deleted outputs from subfolder modules (at least)
### Terraform Configuration Files
- main.tf
- outstest\outputs.tf
#### main.tf

```
module "outstest" {
  source = "./outstest"
}
```
##### (iteration 1)

```
output "outstest" {
  value = "iteration 1"
}
```

exec: 
`terraform get`
`terraform plan`
`terraform apply`
`terraform output -module=outstest`
##### (iteration 2)

```
output "outstest2" {
  value = "iteration 2"
}
```

exec: 
`terraform plan`
`terraform apply`
`terraform output -module=outstest`
###### (from iteration 2)

```
outstes2 = iteration 2
```
###### (from iteration 2)

```
outstes2 = iteration 2
outstest = iteration 1
```
### Steps to Reproduce
1. populate module outputs file with data set 1 (example iteration 1)
2. `terraform get`
3. `terraform plan`
4. `terraform apply`
5. `terraform output -module=outstest`
6. remove/replace module outputs file with another data set (example iteration 2)
7. `terraform plan`
8. `terraform apply`
9. `terraform output -module=outstest`

**Comment by jellevandenhooff** [comment]
Perhaps related: Adding a new output to a module and then running `terraform apply` does not add the newly added output (that, is `terraform output -module=...` does not show the new output) unless I modify a resource in the module.

**Comment by mitchellh** [comment]
Both adding and removing outputs works with the new apply graph `-Xnew-apply` which will be on by default in 0.8.

**Comment by olenm** [comment]
@mitchellh: so will the steps be the following (or are any needed/missing)?
0. `terraform get`
1. `terraform plan`
2. `terraform apply`
3. `terraform graph -Xnew-apply`
4. `terraform output -module=somemodule`

**Comment by mitchellh** [comment]
@olenm If you're on TF 0.7.x: `terraform apply -Xnew-apply`. If you're on TF 0.8.x, it is just `terraform apply`
