### ISSUE TITLE
Fastly provider: backends not mandatory when VCL defined

### ISSUE THREAD

**Issue by aerostitch** [hashicorp/terraform#7609]
Hi there,

I'm using terraform 0.7.0-dev to use the vcl management capabilities added by @mattmoyer and @catsby (thanks a lot for that! :) )!

The thing is that it is not mandatory to have backends defined when you have VCLs (we manage several backends inside the VCL itself). We have several services with the backends defined only in the VCL.

Do you think it would be possible to have the backends not mandatory in the config when there is a VCL?

Thanks for your help,
Joseph

**Comment by albertsun** [comment]
I just ran into this bug as well. Any updated on if/when it might be fixed?

**Comment by catsby** [comment]
Should be fixed up in https://github.com/hashicorp/terraform/pull/12025
