### ISSUE TITLE
GCE Autoscaler: terraform only lets you select one policy while gce allows multiple, metric target types don't match gce

### ISSUE THREAD

**Issue by nwwebb** [hashicorp/terraform#7614]
Terraform Version:
v0.6.16

Affected Resource:
google_compute_autoscaler

Expected Behavior:
- GCE allows multiple policies to be applied to an autoscaler. The user can specify cpu utilization, load balancing utilization and multiple metrics utilizations if they choose. 
- The  metric utilization target types in GCE are gauge, delta/min, delta/sec.

Actual Behavior:
- Terraform doesn't support multiple policies for an autoscaler in a config file.
- When Terraform attempts to update an autoscaler with a new policy (ex: changing from cpu utilization to load balancer utilization) it creates an autoscaler with both policies.
- The metric utilization target types for a Terraform config file are gauge, delta, cumulative

Steps to Reproduce:

The following resource will cause Terraform to complain because multiple policies are specified, although gce lets the user select multiple policies.

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    cpu_utilization {
      target = 0.5
    }
    load_balancer_utilization {
      target = 0.5
  }
}
```

Also, if you were to apply this autoscaler:

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    cpu_utilization {
      target = 0.5
    }
  }
}
```

Followed by this: 

```
resource "google_compute_autoscaler" "foobar" {
  name   = "foobar"
  zone   = "us-central1-f"
  target = "${google_compute_instance_group_manager.foobar.self_link}"

  autoscaling_policy = {
    max_replicas    = 5
    min_replicas    = 1
    cooldown_period = 60

    load_balancing_utilization {
      target = 0.5
    }
  }
}
```

Terraform will create an autoscaler with load balancing and cpu utilization set rather than remove the cpu utilization.

@lwander

**Comment by thecodeassassin** [comment]
Confirmed this behaviour
