### ISSUE TITLE
[terraform_remote_state] encrypt is not working

### ISSUE THREAD

**Issue by jacknagz** [hashicorp/terraform#7618]
### Terraform Version
`Terraform v0.6.16`

### Affected Resource(s)
- terraform_remote_state

### Terraform Configuration Files
main.tf
```hcl
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}

# statefile s3 bucket
resource "aws_s3_bucket" "tfstate" {
    bucket = "my-bucket-name"
    acl = "private"
    versioning {
        enabled = true
    }
    tags {
        Name = "my-bucket-name"
    }
}

# store tfstate file in s3
resource "terraform_remote_state" "tfstate_kinesis" {
    backend = "s3"
    config {
        bucket     = "${aws_s3_bucket.tfstate.id}"
        key        = "kinesis/terraform.tfstate"
        region     = "${var.region}"
        encrypt    = true
        kms_key_id = "${aws_kms_key.terraform_tfstate_key.key_id}"
        acl        = "private"
    }
    depends_on = [
      "aws_kms_key.terraform_tfstate_key",
      "aws_kms_alias.terraform_tfstate_key_alias"
    ]
}

resource "aws_kms_key" "terraform_tfstate_key" {
    description = "kms_key for terraform tfstate"
    deletion_window_in_days = 10
    enable_key_rotation = true
    policy = OMITTED
}

resource "aws_kms_alias" "terraform_tfstate_key_alias" {
    name = "alias/terraform_tfstate_key"
    target_key_id = "${aws_kms_key.terraform_tfstate_key.key_id}"
}
```

### Expected Behavior
Enable server side encryption of the `kinesis/terraform.tfstate` object via SSEKMS.

### Actual Behavior
From the UI, the objects upload to the bucket are listed as unencrypted.  This behavior is also verified on the CLI with the following command:

```python
s3 = boto3.resource('s3')
bucket = s3.Bucket('my-bucket-name')
for obj in bucket.objects.all():
    key = s3.Object(bucket.name, obj.key)
    print obj.key, key.server_side_encryption, key.ssekms_key_id
```

returns `kinesis/terraform.tfstate None None`

**Comment by jamielennox1** [comment]
correct me if I'm wrong but isn't terraform_remote_state read only until v0.7.0?
So, you must be pushing that remote state to s3 unencrypted.

terraform remote/init are completely unrelated to terraform_remote_state for your version

**Comment by kjmkznr** [comment]
@jacknagz 
Could you show me this command result?

```bash
$ jq .remote.config.kms_key_id terraform.tfstate
```

If returns `null`, I think you need to run this command.

```bash
$ terraform remote config \
    -backend=s3 \
    -backend-config="region=<region>"  \
    -backend-config="bucket=my-bucket-name" \
    -backend-config="key=kinesis/terraform.tfstate" \
    -backend-config="kms_key_id=alias/terraform_tfstate_key" \
    -backend-config="encrypt=true"
```

**Comment by jacknagz** [comment]
@kjmkznr that worked!

Something that's slightly confusing is that the `terraform_remote_state` resource has a config attribute called `kms_key_id`, but the description in the docs says the value should be an ARN.  Also, what's the relationship between the `terraform_remote_state` resource itself and running the `terraform remote config` command? It seems it only works when I do both (via a wrapper script).

**Comment by kjmkznr** [comment]
Hi @jacknagz,

`terraform remote config` command will use to synchronize the local tfstate and remote tfstate.
If upload local tfstate to S3 with SSE-KMS, you have to add `encrypt` and` kms_key_id` option.

`terraform_remote_state` data source will only download remote tfstate.
In this case, even if Server-Side-Encryption is enabled, not required `encrypt` and `kms_key_id`.
