### ISSUE TITLE
vsphere resources are... not documented

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#7622]
Terraform v0.6.16

If you look in the code, you will see 5 resources.

If you look in the docs on the terraform website, you will see 2 resources.

The docs are not uptodate, someone has forgotten to do them.

Thanks!

**Comment by stack72** [comment]
Hi @gtmtech 

the website is only updated as of the last stable release (i.e. 0.6.16) - the code in the repo will be all the work that is going on for version 0.7

Paul
