### ISSUE TITLE
Inline routes not removed from aws_route_table.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7632]
When an inline `route` is removed from an `aws_route_table` resource. Terraform does not notice the change and the route is never removed from the route table at AWS. If an inline `route` is added, Terraform adds the route as expected.
### Terraform Version
- 0.6.10
- 0.6.16
- v0.7.0-rc2
### Affected Resource(s)
- aws_route_table
### Terraform Configuration Files

``` hcl
resource "aws_vpc" "main" { cidr_block = "10.0.0.0/16" }
resource "aws_internet_gateway" "main" { vpc_id = "${aws_vpc.main.id}" }

resource "aws_route_table" "private" {
  vpc_id = "${aws_vpc.main.id}"

  // Comment out this route block after creation to reproduce behavior.
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.main.id}"
  }
}
```
### Debug Output

https://gist.github.com/clstokes/884d65b4b75dfa419174cc2a5b4e8a21
### Expected Behavior

The route should have been removed from the route table.
### Actual Behavior

No changes were planned or applied.
### Steps to Reproduce
1. `terraform apply`
2. Comment out or remove `route { ... }`
3. `terraform apply` again and see _no_ changes.

**Comment by catsby** [comment]
This is a known issue with attributes that are `Computed` and `Optional`; removing the last one from the config doesn't register as clearing it out

**Comment by moofish32** [comment]
@catsby Is this a will not fix? or is there a broader issue that can be tracked and we can close this? Off the top of my head I can not name all the scenarios that would match this, but I would expect multiple places where this issue would show up.

**Comment by grimm26** [comment]
help?
