### ISSUE TITLE
Add support for aws_ecs_task_definition to have task_role_arn

### ISSUE THREAD

**Issue by grepory** [hashicorp/terraform#7633]
### Terraform Version
As of current HEAD of master (30ff7df95437d4e36e480278e17fdb185fa0dacc), the aws_ecs_task_definition resource does not have support for the TaskRoleArn CreateTask field.

### Affected Resource(s)
- aws_ecs_task_definition

### Expected Behavior
aws_ecs_task_definition should accept a top-level attribute "task_role_arn" that can be used to define the `TaskRoleArn` field in the `ecs.CreateTaskDefinitionInput{}` object available 

### Important Factoids
The AWS SDK v1.2.5 was just released: https://github.com/aws/aws-sdk-go/releases/tag/v1.2.5

This includes support for assigning these values during task definition registration. So, the vendored AWS SDK would need to be updated and support added. I do not mind trying that, but... updating aws sdks... Woof.

**Comment by stack72** [comment]
Hi 

I have a WIP on this right now - I am running into a small bug where the AWS SDK doesn't return the full ARN - only the iam role name. Looking into this now

Paul

**Comment by stack72** [comment]
Just a FYI on this https://github.com/aws/aws-sdk-go/issues/757

**Comment by grepory** [comment]
Yooouuuu arrreee soooo beautifulllllll to meeeeeeeee.
