### ISSUE TITLE
Azure server disks not removed one server removal

### ISSUE THREAD

**Issue by timhaak** [hashicorp/terraform#7651]
Not sure if this is a bug or intended.

When reducing server count the server's disks aren't removed. 

This causes a problem when you then increase the count and the server creation fails as disks already exist.

Otherwise rc2 is working really nicely.

### Terraform Version
Terraform v0.7.0-rc2

### Affected Resource(s)
Please list the resources as a list, for example:
- azure arm

**Comment by stack72** [comment]
Hi @timhaak 

This was literally merged to master yesterday :) https://github.com/hashicorp/terraform/pull/7584

Apologies this has caused issues. It will be in the final release

Paul

**Comment by timhaak** [comment]
Awesome :)

No issues for me. 

Just thought I should mention in case it would cause others problems.
