### ISSUE TITLE
Support for `kms_key_id` in RDS cluster resources

### ISSUE THREAD

**Issue by xatnys** [hashicorp/terraform#7655]
The 0.7 release will feature `kms_key_id` support in `aws_db_instance` resources. If this support can be extended to the RDS cluster related resources:

- `aws_rds_cluster`
- `aws_rds_cluster_instance`

It would be very useful for us.

**Comment by stack72** [comment]
Hi @xatnys 

Just a FYI, the first PR for this is open (#7662) and the second is currently being tested

Paul

**Comment by stack72** [comment]
ok, @xatnys 

So, we actually don't need to support KMS Key Id for rds_cluster_instance. When we add the specific parameter, we end up with this in the tests:

```
	* aws_rds_cluster_instance.cluster_instances: InvalidParameterCombination: The requested DB Instance will be a member of a DB Cluster and its storage encryption key should not be set directly.
			status code: 400, request id: ac5467c6-4a84-11e6-b09a-6334c9c9bc85
```

So, by supporting KMS Key ID and Storage Encryption on the Cluster, we get it on the instances as well it seems

Paul

**Comment by xatnys** [comment]
Ah, okay my mistake so we only need it for `aws_rds_cluster`. Thanks for working on this! I really appreciate the prompt response. :)

**Comment by stack72** [comment]
ok @xatnys 

I take that back - you need to set it on both the cluster and the instances :)

Almost got this test done

P.
