### ISSUE TITLE
AWS SQS Resource based Policy does not get applied but there are no errors logged

### ISSUE THREAD

**Issue by rajinders** [hashicorp/terraform#7658]
Hi there,

I am using terraform v0.6.16

I had to use resourced based policy for SQS queue for the first time.
I am aware of the need to provide values of region and aws account number.
terraform apply showed that it modified the configuration.
terraform state showed the new Policy but in AWS Management Console I failed to see any policy for me queue.

I manually added the policy to the queue using management console.
It failed and told me that I had more than 7 permissions.
I updated Terraform config so I had just 3 permissions. 
Terraform apply successfully created the policy on the queue.

If my policy failed to apply successfully I want to see the errors.

My SQS config is shown below. If you try to apply this policy it will show you no failure but will not create the policy on the queue.
If you reduce the number permission to less than 7 the policy will successfully apply and you will see it in AWS console.

```
resource "aws_sqs_queue" "send_queue" {
  name = "${var.send_tocms_queue_name}"
  max_message_size = "${var.send_tocms_queue_max_message_size}"
  message_retention_seconds = "${var.send_tocms_queue_message_retention_seconds}"
  receive_wait_time_seconds = "${var.send_tocms_queue_receive_wait_time_seconds}"
policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "arn:aws:sqs:${var.region}:${var.aws_account_id}:${var.send_tocms_queue_name}/SQSPolicy",
  "Statement": [        
        {
            "Sid":"QueuesQA_AllActions",
            "Effect": "Allow",
            "Principal": {
                "AWS": ["arn:aws:sts::${var.aws_account_id}:assumed-role/developers/devname"]
            },            
            "Action": [
            "sqs:ChangeMessageVisibility",
            "sqs:ChangeMessageVisibilityBatch",
            "sqs:GetQueueAttributes",
            "sqs:GetQueueUrl",
            "sqs:ListDeadLetterSourceQueues",
            "sqs:ListQueues",
            "sqs:ReceiveMessage",
            "sqs:SendMessage",
            "sqs:SendMessageBatch",
            "sqs:SetQueueAttributes"
            ],
            "Resource": [
                "arn:aws:sqs:${var.region}:${var.aws_account_id}:${var.send_tocms_queue_name}"
            ]
        }
    ]
}
POLICY
}
```

**Comment by catsby** [comment]
Hey @rajinders – 

I'm sorry to say I'm unable to reproduce this. 
I'm using this config (a slightly modified version of yours, I removed the `Principal`):

```hcl
resource "aws_sqs_queue" "send_queue" {
  name                       = "somename"
  delay_seconds              = 90
  max_message_size           = 2048
  message_retention_seconds  = 86400
  receive_wait_time_seconds  = 10
  visibility_timeout_seconds = 60

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "arn:aws:sqs:us-west-2:<myaccountid>:somename/SQSPolicy",
  "Statement": [
    {
      "Sid": "QueuesQA_AllActions",
      "Effect": "Allow",
      "Action": [
        "sqs:ChangeMessageVisibility",
        "sqs:ChangeMessageVisibilityBatch",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ListDeadLetterSourceQueues",
        "sqs:ListQueues",
        "sqs:ReceiveMessage",
        "sqs:SendMessage",
        "sqs:SendMessageBatch",
        "sqs:SetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:us-west-2:<myaccountid>:somename/SQSPolicy"
    }
  ]
}
POLICY
}
```

I received no errors in applying, and all the expected permissions show on the queue in the console:

![screen shot 2016-07-21 at 4 28 31 pm](https://cloud.githubusercontent.com/assets/61721/17039452/3330b2e8-4f60-11e6-9683-d61ecfad1b69.png)


Do you have any more information? Does your example still fail for you? Can you try capturing log output by running Terraform with debug logs? 

    $ TF_LOG=1 terraform plan|apply 

does that provide any more information?

**Comment by rajinders** [comment]
Thanks for getting back to me so promptly. I was swamped with too many
other things and I was able to work around this issue by reducing the
number of actions. I will try to reproduce this error again and enable
logging. I will share the details back with you.

**Comment by rajcheval** [comment]
I tried to create the queue again. I used the HCL config your listed above. The only difference is that I did add a service principal. We use azure active directory for single sign on.

resource "aws_sqs_queue" "send_queue" {
  name                       = "somename8887"
  delay_seconds              = 90
  max_message_size           = 2048
  message_retention_seconds  = 86400
  receive_wait_time_seconds  = 10
  visibility_timeout_seconds = 60

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "arn:aws:sqs:us-east-1:acc_nbr:somename8887/SQSPolicy",
  "Statement": [
    {
      "Sid": "QueuesQA_AllActions",
      "Effect": "Allow",
      "Principal": {
                "AWS": ["arn:aws:sts::acc_nbr:assumed-role/myadmins/rsingh"]
            },    
      "Action": [
        "sqs:ChangeMessageVisibility",
        "sqs:ChangeMessageVisibilityBatch",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ListDeadLetterSourceQueues",
        "sqs:ListQueues",
        "sqs:ReceiveMessage",
        "sqs:SendMessage",
        "sqs:SendMessageBatch",
        "sqs:SetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:us-east-1:acc_nbr:somename8887/SQSPolicy"
    }
  ]
}
POLICY
}

I did turn of TF logging.

I got these errors.


2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: -----------------------------------------------------
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: 2016/07/27 15:28:12 [DEBUG] [aws-sdk-go] DEBUG: Response sqs/CreateQueue Details:
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: ---[ RESPONSE ]--------------------------------------
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: HTTP/1.1 500 Internal Server Error
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: Connection: close
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: Content-Length: 303
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: Content-Type: text/xml
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: Date: Wed, 27 Jul 2016 20:28:12 GMT
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: Server: Server
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: X-Amzn-Requestid: 0e1490ef-6145-53f0-93d0-c0fc7ad96ce4
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: 
2016/07/27 15:28:12 [DEBUG] terraform-provider-aws: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Receiver</Type><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Detail/></Error><RequestId>0e1490ef-6145-53f0-93d0-c0fc7ad96ce4</RequestId></ErrorResponse>


* aws_sqs_queue.send_queue: Error creating SQS queue: InternalError: We encountered an internal error. Please try again.
	status code: 500, request id: c254f57d-bce6-5222-94f1-a56ea7284a60
2016/07/27 15:29:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_sqs_queue.send_queue: Error creating SQS queue: InternalError: We encountered an internal error. Please try again.
	status code: 500, request id: c254f57d-bce6-5222-94f1-a56ea7284a60
2016/07/27 15:29:02 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* aws_sqs_queue.send_queue: Error creating SQS queue: InternalError: We encountered an internal error. Please try again.
	status code: 500, request id: c254f57d-bce6-5222-94f1-a56ea7284a60
2016/07/27 15:29:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:



I reduce the number of permissions and I was able to create the queue successfully

HCL that worked was:

{
      "Sid": "QueuesQA_AllActions",
      "Effect": "Allow",
      "Principal": {
                "AWS": ["arn:aws:sts::acc_nbr:assumed-role/myadmins/rsingh"]
            },    
      "Action": [
        "sqs:ChangeMessageVisibility",
        "sqs:GetQueueAttributes"
      ],
      "Resource": "arn:aws:sqs:us-east-1:acc_nbr:somename8887/SQSPolicy"
    }

**Comment by Aubtin** [comment]
I had a similar issue applying the SQS permissions policy. I found the problem was AWS added `  "Version": "2008-10-17"` in the policy and Terraform does not. Adding that to the policy in Terraform resolved the problem.
