### ISSUE TITLE
module - breaking changes to a module source not reflected by 'terraform get' 

### ISSUE THREAD

**Issue by jimsheldon** [hashicorp/terraform#7664]
Greetings!  I am seeing an issue where breaking changes to a module's git source are not reflected when running `terraform get`.
### Terraform Version

```
$ terraform --version
Terraform v0.6.16

$ git --version
git version 2.1.4

$ uname -a
Linux jsheldon-debianvm 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```
### Affected Resource
- module
### Terraform Configuration Files

Good config with a git repo that does exist:

``` hcl
module "mymodule" {
  source = "git::ssh://git@github.com/owner/awesome-terraform-module//module-name?ref=master"
  ...
}
```

Broken config with a git repo that does not exist:

``` hcl
module "mymodule" {
  source = "git::ssh://git@github.com/owner/i_do_not_exist//module-name?ref=master"
  ...
}
```
### Debug Output

Successful initial `terraform get` with the good config:

```
$ terraform get
Get: git::ssh://git@github.com/owner/awesome-terraform-module?ref=master
```

After changing to the "broken config" above, which I believe should fail, it succeeds again:

```
$ terraform get
Get: git::ssh://git@github.com/owner/i_do_not_exist?ref=master
```

It still succeeds even when adding `--update`:

```
$ terraform get --update
Get: git::ssh://git@github.com/owner/i_do_not_exist?ref=master (update)
```

Only when removing the `.terraform` directory does the error appear:

```
$ rm -rf .terraform
$ terraform get
Get: git::ssh://git@github.com/owner/i_do_not_exist?ref=master
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@github.com/meltwater/i_do_not_exist?ref=master': /usr/bin/git exited with 128: Cloning into '.terraform/modules/f29b029ff643fa761d645893fef44fe2'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
### Expected Behavior

The `terraform get` with the broken config should tell me that the git repo does not exist and error.
### Actual Behavior

Terraform applied the config successfully even though the git repo did not exist.
### Steps to Reproduce
1. Find a terraform module in a git repository.
2. Create a `module` definition which uses the module.
3. Run `terraform get`.
4. Change the `module` definition to a git repository that does not exist.
5. Run `terraform get`.
6. Observe that no error is given.
### Important Factoids

This problem surfaced when a developer had made a breaking change to a module's git URL unintentionally, and it did not appear until that developer removed the `.terraform` directory and ran `terraform get` a few days later.

**Comment by mitchellh** [comment]
This should no longer happen since the source is part of the key now.
