### ISSUE TITLE
docker_container: crash on invalid syntax in volumes

### ISSUE THREAD

**Issue by IlyaSemenov** [hashicorp/terraform#7675]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
resource "docker_container" "test" {
        image = "test"
        name = "test"
        volumes {
                host_path = /
        }
}
```

### Debug Output & Panic Output
https://gist.github.com/IlyaSemenov/fe8c1a3e4ac21a43a1c816997f694f20

### Expected Behavior
Something like:
`Error loading config: Error parsing /Users/semenov/tmp/terra-bug/bug.tf: At 5:15: Unknown token: 5:15 IDENT /`

### Actual Behavior
Terraform crashes.

### Steps to Reproduce
1. `terraform plan`

**Comment by mitchellh** [comment]
This no longer crashes. It was fixed at some point between this issue and now.
