### ISSUE TITLE
terraform.tfvars and modules not workingTerraform 0.6.16

### ISSUE THREAD

**Issue by P13612** [hashicorp/terraform#7676]
I'm trying to set up general modules configurable with terraform.tfvars

This is how the module tree looks like

```
modules/
├── subnets
│   ├── private
│   │   ├── main.tf
│   │   └── outputs.tf
│   └── public
│       ├── main.tf
│       └── outputs.tf
└── vpc
    ├── main.tf
    └── outputs.tf
```

This is how the infrastructure for `terraform apply` looks like:

```
infrastructure/
├── private.tf
├── public.tf
└── vpc.tf
```

and here are my `terraform.tfvars`

```
vpc_cidr_block = "10.130.0.64/26"
zonea          = "us-west-1a"
zoneb          = "us-west-1b"
```

here is module `vpc.tf`

```
module "vpc" {
  source = "../../../modules/vpc"
  vpc_cidr_range = "${var.vpc_cidr_range}"
}
```

the variable is unknown

``` Shell
terraform plan infrastructure
* module.vpc: missing dependency: var.vpc_cidr_range
```

I added `variables.tf` to the module tree:

```
modules/
└── vpc
    ├── main.tf
    ├── outputs.tf
    └── variables.tf
```

```
# file: modules/vpc/variables.tf
variable vpc_cidr_range {
  default = "10.130.0.0/24"
}
```

The variable is still unknown

``` Shell
terraform plan infrastructure returns:
* module.vpc: missing dependency: var.vpc_cidr_range
```

with a variable definition on top of module vpc.tf terraform plan will ask
for vpc_cidr_range

```
variable vpc_cidr_range {}
module "vpc" {
  source = "../../../modules/vpc"
  vpc_cidr_range = "${var.vpc_cidr_range}"
}
```

``` Shell
terraform plan infrastructure
var.vpc_cidr_range
  Enter a value: 
```

But

```
variable vpc_cidr_range {
  default = "10.130.0.0/24"
}

module "vpc" {
  source = "../../../modules/vpc"
  vpc_cidr_range = "${var.vpc_cidr_range}"
}
```

is working, but this is not very useful.

Using `variables.tf` instead of `terraform.tfvars` isn't working either. But variables from module outputs do work, but the variables from `terraform.tfvars` do not, This is why the variables zonea, zoneb here are assigned explicitly.

```
module "private" {
  source = "../../../modules/subnets/private"
  vpc_id = "${module.vpc.GitLab_vpc_id}"
  zonea  = "us-west-1a"
  zoneb  = "us-west-1b"
}
```

There have been issues discussing this topic, but they all say, this has been sorted.

What am I doing wrong?

Thank you

Peter

**Comment by LeslieCarr** [comment]
Hi - I'm not a terraform expert by any means! But in your .tfvars file I noticed that you have named the variable `vpc_cidr_block` when you probably want `vpc_cidr_range`

**Comment by P13612** [comment]
Thank you Leslie. Your hint was right, but actually on top of this the major flaw turned out to be another misconception and I explain it here just in case somebody else stumbles over this.

In the module tree variables.tf file can be omitted!

```
modules/
└── vpc
    ├── main.tf
    └── outputs.tf
```

in `terraform.tfvars` the variables are defined as explained

```
#file: terraform.tfvars
vpc_cidr_block = "10.130.0.64/26"
zonea          = "us-west-1a"
zoneb          = "us-west-1b"
```

In the file `infrastructure/vpc.tf` you have to define a variable with or without default section. Preferably without.

```
# file: infrastructure/vpc.tf
variable vpc_cidr_block {}

module "vpc" {
  source = "../../../modules/vpc"
  vpc_cidr_block = "${var.vpc_cidr_block}"
}
```

And in addition you have to define a file `variables.tf` next to `terraform.tfvars` with or without default section. In this case a default section might be useful but it is not required. But to make things really work one has to provide both `terraform.tfvars` and `variables.tf`.

```
# file: variables.tf
variable "vpc_cidr_block" {
   default =  "10.130.0.64/26"
}
```

**Comment by mitchellh** [comment]
We've clarified this error message. Since early versions of Terraform we've always required that variables be defined, and at some point that regressed. We fixed that and turns out a lot of people depended on that broken behavior! The error message however is a lot clearer now.
