### ISSUE TITLE
aws_autoscaling_notification timing issue / race condition ?

### ISSUE THREAD

**Issue by peterticketfly** [hashicorp/terraform#7683]
when using the aws_autoscaling_notification resource to create lifecycle notifications for an ASG, I expect the notifications to be triggered for the initial 3 nodes that are spun up when the ASG is created (as is the case when done with Cloudformation). However, I usually only see a TEST_NOTIFICATION (even though it's not subscribed to that notification type). Once the ASG is up and the initial nodes are up, future resize events are published to the SNS topic. If the ASG is deleted, I don't see the TERMINATE notifications anymore either. 

Is the ASG created first and then mutated to add the lifecycle notification? It appears to be done in one "operation" when done through Cloudformation. 
### Terraform Version

$ terraform -v
Terraform v0.6.16
### Affected Resource(s)

aws_autoscaling_notification
### Terraform Configuration Files

`````` hcl
resource "aws_autoscaling_group" "zookeeper_asg" {
  vpc_zone_identifier = ["${terraform_remote_state.vpc.output.vpc_subnet-privateA}", "${terraform_remote_state.vpc.output.vpc_subnet-privateB}", "${terraform_remote_state.vpc.output.vpc_subnet-privateC}"]
  name = "zookeeper_asg-${terraform_remote_state.vpc.output.vpc_name}"
  max_size = 5
  min_size = 3
  desired_capacity = 3
  health_check_grace_period = 300
  health_check_type = "ELB"
  force_delete = true
  launch_configuration = "${aws_launch_configuration.zookeeper_lc.name}"

  tag {
    key = "Name"
    value = "zookeeper-${terraform_remote_state.vpc.output.vpc_name}"
    propagate_at_launch = true
  }

  tag {
    key = "environment"
    value = "${terraform_remote_state.vpc.output.vpc_name}"
    propagate_at_launch = true
  }

  tag {
    key = "group"
    value = "apps/infrastructure/zookeeper"
    propagate_at_launch = true
  }
}

resource "aws_autoscaling_notification" "zookeeper_asg_notifications" {
  group_names = [
    "${aws_autoscaling_group.zookeeper_asg.name}"
  ]
  notifications  = [
    "autoscaling:EC2_INSTANCE_LAUNCH",
    "autoscaling:EC2_INSTANCE_TERMINATE",
    "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
  ]
  topic_arn = "${terraform_remote_state.vpc.output.infrastructure_events_sns_topic_arn}"
}```

``````

**Comment by peterticketfly** [comment]
Also, this always happens:

**Comment by mtougeron** [comment]
Yes, the notification is created after the autoscaling group is created. The autoscaling API does not allow setting the notification at [creation time](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CreateAutoScalingGroup.html), you have to do it [after it has been created](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_PutNotificationConfiguration.html).

**Comment by SingleMalt** [comment]
So, is there a command in Terraform to call [SetDesiredCapacity](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_SetDesiredCapacity.html) separately?

**Comment by SingleMalt** [comment]
I'm in no way a Go programmer, but I threw together [this](https://github.com/SingleMalt/terraform/commit/b7e62ecada5497219b8e450f60d5077c5313733a) to get past this locally. Called like this:

```
resource "aws_autoscaling_desired_capacity" "asg_dc" {
  group_name = "${aws_autoscaling_group.asg.name}"
  desired_capacity = 2

  depends_on = ["aws_autoscaling_group.asg", "aws_autoscaling_notification.launch_notifications"]
}```

It's working for me enough to move on. If this is something that you guys want I can add tests and submit a pull request.

**Comment by jrnt30** [comment]
There is a little bit of work done for a similar issue with lifecycle hooks on ASGs also.  The current `resource_aws_autoscaling_group` does take in (which is somewhat hidden) [`initial_lifecycle_hook`](https://www.terraform.io/docs/providers/aws/r/autoscaling_lifecycle_hooks.html). 

If this is present, the ASG creation is done in two passes, the first with everything set to a count of 0 instances to get the ASG ID, the lifecycle hooks are created and then finally the scaling parameters are applied to ensure the lifecycle hooks occur for the first ASG instances.

I think it may be possible then to apply the same type of logic to associate the notification

**Comment by sgran** [comment]
any chance of this making a release soonish?  I have a bunch of things that rely on SNS notifications during initial bringup that I'd like to migrate to terraform, but can't easily while this is still not working.
