### ISSUE TITLE
terraform import in 0.7 does not work as expected for count[] resource addresses

### ISSUE THREAD

**Issue by WolverineFan** [hashicorp/terraform#7691]
### Terraform Version
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)

### Affected Resource(s)
- aws_instance is all I've tested

### Terraform Configuration File
N/A

### Steps to Reproduce
1. `terraform import 'aws_instance.example[0]' i-xxxx`
2. `terraform import 'aws_instance.example[1]' i-yyyy`

### Expected Behavior
Two entries in the terraform.tfstate file: 
- aws_instance.example.0
- aws_instance.example.1

### Actual Behavior
One entry in the terraform.tfstate file, and no warning that it was overwriting the existing entry: 
- aws_instance.example

### Additional info
I also tried with `aws_instance.example.0` which fails as expected:
Error importing: failed to parse resource address 'aws_instance.example.0': Unexpected value for InstanceType field: "0"

**Comment by WolverineFan** [comment]
If this isn't going to make it into 0.7, I think the current behavior should be documented somewhere (namely that terraform import doesn't support counts)

**Comment by Malet** [comment]
Also having the same issue with digitalocean

**Comment by lbernail** [comment]
I encountered the same issue while importing a list of instances
I found a work around that seems ok for me:

```
terraform import 'aws_instance.example0' i-xxxx
terraform state mv 'aws_instance.example0' 'aws_instance.example[0]'
terraform import 'aws_instance.example1' i-xxxx
terraform state mv 'aws_instance.example1' 'aws_instance.example[1]'
```

**Comment by mengesb** [comment]
@lbernail How did you populate the 'count'.  I'm trying something similar and I was using a map:

```hcl
resource "aws_subnet" "chef-ha-subnet" {
  count                   = "${length(keys(var.subnets))}"
  vpc_id                  = "${aws_vpc.chef-ha-vpc.id}"
  availability_zone       = "${element(keys(var.subnets), count.index)}"
  cidr_block              = "${element(values(var.subnets), count.index)}"
}
```

When I run this, I then have to populate `var.subnets` map with matching data instead of the import taking care of it. Have you run into this as well?

**Comment by mitchellh** [comment]
Fix is in referenced PR #8335

**Comment by SydOps** [comment]
So if you need import resource for count[] resource, use below format:

    terraform import aws_instance.bar[0] i-abcd1234

**Comment by SandyKapil** [comment]
terraform import 'aws_instance.example0' i-xxxx
the above one you are saying if you are doing via command line but if you are doing it in en editor say Atom which I am using then you just need to specify 
import 'aws_instance.example0' i-xxxx
correct? 

am still getting error 

this is my code:

data "aws_instance" "dataimport" {
  instance_id = "i-0d475561b94bc95d5"

  filter {
    name   = "instance-state-name"
    values = ["running"]
  }
}

import aws_instance.dataimport i-0d475561b94bc95d5

**Comment by SandyKapil** [comment]
also i have tried like this:
import{
  aws_instance.dataimport "i-0d972420b94bc95d5"
}

Error: Error parsing aws_instances.tf: key 'aws_instance.dataimport "i-0d475561b94bc95d5"' expected start of object ('{') or assignment ('=')

Any clue anyone please??

**Comment by SandyKapil** [comment]
I figured it out that I have to run it from command prompt only...
