### ISSUE TITLE
Unable to add metrics to existing autoscaling group

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#7693]
I think that I have found a bug with the `enabled_metrics` parameter of the `aws_autoscaling_group` resource. It seems that the `enabled_metrics` parameter only works for non-existing autoscaling groups (i.e. it can't be used to add metrics to existing autoscaling groups). Consider the following Terraform code:

    resource "aws_autoscaling_group" "test" {
      name                 = "metrics-test"
      max_size             = 0
      min_size             = 0
      availability_zones   = ["us-east-1a", "us-east-1d", "us-east-1e"]
      launch_configuration = "${aws_launch_configuration.test.name}"

      /*    
      enabled_metrics = [
        "GroupDesiredCapacity",
        "GroupInServiceInstances",
        "GroupMaxSize",
        "GroupMinSize",
        "GroupPendingInstances",
        "GroupStandbyInstances",
        "GroupTerminatingInstances",
        "GroupTotalInstances",
      ]
      */
    }
    
    resource "aws_launch_configuration" "test" {
      name_prefix       = "metrics-test-"
      image_id          = "ami-59ce434e"
      instance_type     = "c3.xlarge"
      enable_monitoring = true
    
      lifecycle {
        create_before_destroy = true
      }
    }

Running `terraform apply` creates the autoscaling group and launch configuration, as expected. Now, uncomment the `enabled_metrics` and run `terraform apply` again. The output is as follows.

    aws_autoscaling_group.test: Modifying...
      enabled_metrics.#:          "0" => "8"
      enabled_metrics.119681000:  "" => "GroupStandbyInstances"
      enabled_metrics.1940933563: "" => "GroupTotalInstances"
      enabled_metrics.308948767:  "" => "GroupPendingInstances"
      enabled_metrics.3267518000: "" => "GroupTerminatingInstances"
      enabled_metrics.3394537085: "" => "GroupDesiredCapacity"
      enabled_metrics.3551801763: "" => "GroupInServiceInstances"
      enabled_metrics.4118539418: "" => "GroupMinSize"
      enabled_metrics.4136111317: "" => "GroupMaxSize"
    aws_autoscaling_group.test: Modifications complete

However, the metrics were not actually enabled:

    > aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name metrics-test | jq '.AutoScalingGroups[].EnabledMetrics'
    []

**Comment by stack72** [comment]
Hi @joshuaspence 

Just been able to recreate this - will look into the issue asap! Think i have a hunch on what it is

Paul

**Comment by stack72** [comment]
Hi @joshuaspence 

If you run a `terraform refresh`, does Terraform show you that you need to re-add all metrics?

paul

**Comment by joshuaspence** [comment]
No, running `terraform refresh` and then `terraform plan` shows no changes to be applied.

**Comment by stack72** [comment]
ok, fix on it's way. You will have to comment out the enabled_metrics, terraform apply, then re-enable them. For some reason, the state believed they were added

**Comment by joshuaspence** [comment]
OK, thanks for the quick turnaround.

**Comment by stack72** [comment]
Sorry for the bug - FYI, the issue was only when running on Update. I wasn't passing the metrics_granularity parameter to the API and the API was silently failing. The fact there was no error accounted for the fact that the metrics were still being added to the state :(

Tests are just running and then PR should be open

P.

**Comment by twm-tt** [comment]
This still doesn't seem to work for me.  I created an autoscaling group and applied the changes, then later came and enabled metrics, but metrics were never enabled for that asg.  Refresh/plan/apply shows no changes.

Terraform v0.9.5

State Snippet:
```
                    "primary": {
                        "id": "development-ecs-asg",
                        "attributes": {
                            "arn": "arn:aws:autoscaling:us-west-2:767177213176:autoScalingGroup:b6bd88fd-0112-40b1-b98b-4f78e118725c:autoScalingGroupName/development-ecs-asg",
                            "availability_zones.#": "3",
                            "availability_zones.2050015877": "us-west-2c",
                            "availability_zones.221770259": "us-west-2b",
                            "availability_zones.2487133097": "us-west-2a",
                            "default_cooldown": "300",
                            "desired_capacity": "8",
                            "enabled_metrics.#": "8",
                            "enabled_metrics.119681000": "GroupStandbyInstances",
                            "enabled_metrics.1940933563": "GroupTotalInstances",
                            "enabled_metrics.308948767": "GroupPendingInstances",
                            "enabled_metrics.3267518000": "GroupTerminatingInstances",
                            "enabled_metrics.3394537085": "GroupDesiredCapacity",
                            "enabled_metrics.3551801763": "GroupInServiceInstances",
                            "enabled_metrics.4118539418": "GroupMinSize",
                            "enabled_metrics.4136111317": "GroupMaxSize",
```


![screenshot from 2017-05-26 16-55-10](https://cloud.githubusercontent.com/assets/22602451/26515892/241d190a-4234-11e7-8fcf-4cfa840aa5b6.png)

**Comment by stack72** [comment]
Hi @twm-tt 

Thanks for reporting this - I am just about to open a support case with AWS for this. From everything I can see, this is a UI bug. The API and the CLI return that metrics are enabled but the UI doesn't

IF you can, try the AWS CLI and see what the autoscaling group tells you

e.g. 

```
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names development-ecs-asg --region us-west-2
```

**Comment by tomelliff** [comment]
@stack72 I'm guessing you haven't heard anything back from AWS about this?

**Comment by tomelliff** [comment]
Just seems to be a timing thing for me. Came in this morning and the metrics I enabled on Friday are displaying properly in the console so I guess this is no longer a problem?

**Comment by donbecker** [comment]
I am having this same issue myself. 

I have tried ```terraform refresh``` then ```terraform plan``` and it does not indicate that it needs to add the metrics. 

Checking using ```aws autoscaling describe-auto-scaling-groups``` shows: 

```
"EnabledMetrics": [],
```

I've tried adding ```metrics_granularity = "1Minute"``` but this has no effect. 

Each time I create my ASG's, I have to go into the console and hit "Enable Group Metrics Collection". 

Any ideas on how I can work around this? 

tf version is 0.11.3

**Comment by donbecker** [comment]
Just to clarify, I get this on new ASG's, as well as trying to add metrics to an existing ASG.

**Comment by donbecker** [comment]
Commenting out the metrics parameters and running ```terraform plan```:

```
  ~ module.vpc.aws_autoscaling_group.asg_iwebapp
      enabled_metrics.#:          "8" => "0"
      enabled_metrics.119681000:  "GroupStandbyInstances" => ""
      enabled_metrics.1940933563: "GroupTotalInstances" => ""
      enabled_metrics.308948767:  "GroupPendingInstances" => ""
      enabled_metrics.3267518000: "GroupTerminatingInstances" => ""
      enabled_metrics.3394537085: "GroupDesiredCapacity" => ""
      enabled_metrics.3551801763: "GroupInServiceInstances" => ""
      enabled_metrics.4118539418: "GroupMinSize" => ""
      enabled_metrics.4136111317: "GroupMaxSize" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by donbecker** [comment]
After uncommenting, and rerunning they show applied. 

I have an issue with instance health on creation that causes an error on my ASG creation, so ignore my report for now, I think this isn't a Terraform issue.

**Comment by SantoshKumarA** [comment]
I'm also facing the same issue today.
![image](https://user-images.githubusercontent.com/19463161/59708154-ccdb2200-9221-11e9-9f9f-1fcfbed00da1.png)
