### ISSUE TITLE
Error setting up client

### ISSUE THREAD

**Issue by ACluelessOne** [hashicorp/terraform#7696]
Terraform 0.6.16

### Terraform Configuration Files
```
provider "vsphere" {
  vsphere_server = "intern-vcenter.openberl.in"
  user = ""
  password = ""
  allow_unverified_ssl = "true"

```

### Expected Behavior
Completion of terraform plan

### Actual Behavior
```
Error refreshing state: 1 error(s) occurred:

* Error setting up client: Post https://intern-vcenter.openberl.in/sdk: dial tcp: lookup intern-vcenter.openberl.in on [::1]:53: read udp [::1]:52800->[::1]:53: read: connection refused
```
### Steps to Reproduce
terraform plan

### Important Factoids
CentOS 7 in vcenter

**Comment by stack72** [comment]
Hi @ACluelessOne 

Can you tell me if the vsphere machine you are trying to configure can be accessed from the machine that terraform is running on? 

Paul

**Comment by ACluelessOne** [comment]
sorry but how do i check that?

**Comment by stack72** [comment]
Hi @ACluelessOne 

If you ping / curl / nslookup the address of the vsphere server then it should tell you if your machine can contact it

This feels like a networking issue rather than a terraform issue

Paul

**Comment by ACluelessOne** [comment]
o yes, its a network issue. thanks
