### ISSUE TITLE
Integer divide by 0 panic

### ISSUE THREAD

**Issue by pporada-gl** [hashicorp/terraform#7701]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- variable definition
- output with arithmetic

### Terraform Configuration Files
```hcl
variable "test0" { default = 0 }
variable "test1" { default = 1 }

output "modulo 0%1"         { value = "${var.test0 % 1}" }
output "modulo 0%0"         { value = "${var.test0 % 0}" }
output "module 1%0"         { value = "${var.test1 % 0}" }
output "module 1%1"         { value = "${var.test1 % 1}" }
```

### Panic Output
https://gist.github.com/greenlancer/fe89042fa86bb24903eccf0314285af6

### Expected Behavior
While it's expected that a divide by 0 causes a failure, Terraform should display a nicer error message instead of blowing up all over the screen.

### Actual Behavior
Terraform exploded

### Steps to Reproduce
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?
Not that I could find.

**Comment by mitchellh** [comment]
Fix queued up in HIL repo.
