### ISSUE TITLE
vCD provider does not seem to work with vCD 5.6

### ISSUE THREAD

**Issue by poluvex** [hashicorp/terraform#7702]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
vcd provider

### Terraform Configuration Files
provider "vcd" {
	user = "XXX"
	password = "XXX"
	org = "XXX"
	url = "https://blah/api/"
	vdc = "XXX"
        allow_unverified_ssl = "true"
}

### Debug Output
2016/07/19 15:10:22 [ERROR] root.blah: eval: *terraform.EvalConfigProvider, err: Something went wrong: error authorizing: error parsing error body for non-200 request: EOF
2016/07/19 15:10:22 [ERROR] root.blah eval: *terraform.EvalSequence, err: Something went wrong: error authorizing: error parsing error body for non-200 request: EOF
2016/07/19 15:10:22 [ERROR] root.blah: eval: *terraform.EvalOpFilter, err: Something went wrong: error authorizing: error parsing error body for non-200 request: EOF
2016/07/19 15:10:22 [ERROR] root.blah: eval: *terraform.EvalSequence, err: Something went wrong: error authorizing: error parsing error body for non-200 request: EOF

### Panic Output
N/A

### Expected Behavior
terraform is expected to authorize against API endpoint and start making calls to deploy infrastructure

### Actual Behavior
Fails to authorize against API endpoint and quits

### Steps to Reproduce
terraform apply

### Important Factoids
Running against vCD 5.6, (Skyscape Cloud)

### References
N/A

**Comment by poluvex** [comment]
false alarm - problem turned up to API user permission issues, though I guess it would be nice if the error message have been a bit more informative...

**Comment by poluvex** [comment]
false alarm - problem turned up to API user permission issues, though I guess it would be nice if the error message have been a bit more informative...

**Comment by poluvex** [comment]
false alarm - problem turned up to be API user permissions issue, though I guess it would be nice if the error message have been a bit more informative...

**Comment by s1dhart** [comment]
hi , i am having the same problem, how did you fix the API user permission issue?

**Comment by gionn** [comment]
For me, it was the missing "/api" at the end of the URL.
