### ISSUE TITLE
Documentation fixups for new cloudstack provider

### ISSUE THREAD

**Issue by russroy** [hashicorp/terraform#771]
I notice a few minor documentation fixups needed for the recently added builtin cloudstack provider:

1.  A cloudstack link is missing from the Providers page https://terraform.io/docs/providers/index.html (though the documentation _does_ exist and is accessible via url here:  https://terraform.io/docs/providers/cloudstack/index.html)
2.  Background on all of the CloudStack documentation pages is dark.
3.  Some of the resource usage examples are invalid in that they don't include all of required args (eg the cloudstack_instance sample is missing the service_offering, zone and template args.)

**Comment by svanharmelen** [comment]
Thanks for the feedback! Will have a look...

**Comment by svanharmelen** [comment]
See PR #779

**Comment by mitchellh** [comment]
Fixed by #779
