### ISSUE TITLE
Hot to parameterise the number of subresources?

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#7713]
Is there any way of parameterising the number of subresources within a resource?

For example, in the following vtm resource, I have 2 nodes defined:
### Terraform Configuration Files

``` hcl
resource "vtm_pool" "demo_pool" {
  name = "demo_pool"
  node = {
    node = "${var.ips.0}:${var.port}"
    weight = "3"
  }
  node = {
    node = "${var.ips.1}:${var.port}"
  }
  monitors = ["Ping"]
}
```

However, I want the number of node = {}  sections to be itself a parameter, so that through setting of variables, I might have 3 nodes, or 5 nodes, all with their own configuration.

You can seem to do this with top level resources fine, but it doesnt seem to be possible with these subresources. Does anyone know of a way?

**Comment by mitchellh** [comment]
This isn't possible, parameterization of "blocks" as they're being called is covered in a core enhancement issue.
