### ISSUE TITLE
Feature Request: Add Support for 'require_full_window' to datadog_monitor

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#7720]
Request to add support for api flag 'require_full_window' when creating a datadog monitor.

See: http://docs.datadoghq.com/api/?lang=python

>require_full_window a boolean indicating whether this monitor needs a full window of data before it's evaluated. We highly recommend you set this to False for sparse metrics, otherwise some evaluations will be skipped.
>Default: True for "on average", "at all times" and "in total" aggregation. False otherwise.

**Comment by stack72** [comment]
Hi @eedwardsdisco 

This has actually been added and will be available in 0.7 when it is released :) #6738

Paul

**Comment by eedwardsdisco** [comment]
@stack72 

Thanks so much Paul, apologies, I had searched all issues (open and closed) for 'require_full_window' but didn't search for 'require full window' :P

**Comment by stack72** [comment]
Glad it's already in the pipeline for you :)
