### ISSUE TITLE
Undefined data value silently ignored in 0.7

### ISSUE THREAD

**Issue by WolverineFan** [hashicorp/terraform#7722]
I was playing around with the suggestions in #4084 and specifically the last comment with mentions the new null_data_source (#6717) and noticed this problem. It also happened when I tried to use
`data "terraform_remote_state" "network"`
so I don't think it's specific to null_data_source.  Essentially what happens is the output that tries to use an undefined piece of data fails to show up silently.  If I do the same thing with a resource or variable it fails with a good error.
### Terraform Version

Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
### Affected Resource(s)

Looks like a core issue with data.\* references
### Terraform Configuration Files

``` hcl
variable "test1" {
  default = "foo"
}

output "test1" {
  value = "${var.test1}"
}

data "null_data_source" "test2" {
    inputs = {
        myval = "${var.test1}bar"
        myval2 = "${var.test1}bar2"
    }
}

output "test2myval" {
  value = "${lookup(data.null_data_source.test2.inputs,"myval")}"
}

output "test2invalid1" {
  value = "${lookup(data.null_data_source.test2.inputs,"notthere")}"
}

output "test2invalid2" {
  value = "${data.null_data_source.test2.inputs.notthere}"
}

output "test2all" {
  value = "${data.null_data_source.test2.inputs}"
}
```
### Expected Behavior

And error of some sort for test2invalid1 and test2invalid2
### Actual Behavior

```
Outputs:

test1 = foo
test2all = {
  myval = foobar
  myval2 = foobar2
}
test2myval = foobar
```
### Steps to Reproduce
1. `terraform apply`
### References
- GH-4084
- GH-6717

**Comment by WolverineFan** [comment]
Looks like this is still happening in 0.7.7.  I noticed when running with TF_LOG=1 that there's a warning being printed.  Would it be a problem to convert that to an error?
```
2016/10/25 11:55:46 [DEBUG] Interpolating computed map element attribute inputs (2)
2016/10/25 11:55:46 [WARN] Output interpolation "test2invalid2" failed: Resource 'data.null_data_source.test2' does not have attribute 'inputs.notthere' for variable 'data.null_data_source.test2.inputs.notthere'
...
2016/10/25 11:55:46 [DEBUG] Interpolating computed map element attribute inputs (2)
2016/10/25 11:55:46 [WARN] Output interpolation "test2invalid1" failed: lookup: lookup failed to find 'notthere' in:

${lookup(data.null_data_source.test2.inputs,"notthere")}
```

**Comment by mitchellh** [comment]
Dup of #5334 where we've centralized this issue.
