### ISSUE TITLE
aws_ecs_task_definition.main: diffs didn't match during apply.

### ISSUE THREAD

**Issue by gregwebs** [hashicorp/terraform#7735]
```
* aws_ecs_task_definition.main: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:


    Terraform Version: 0.6.16
    Resource ID: aws_ecs_task_definition.main
    Mismatch reason: extra attributes: family

    Diff Two (usually from apply):
...

*terraform.InstanceDiff{Attributes:map[string]*terraform.ResourceAttrDiff{"family":*terraform.ResourceAttrDiff{Old:"", New:"diagonal-worker", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Type:0x0},
...
```

This if from using this terraform module: https://github.com/segmentio/stack/blob/master/task/main.tf#L72

Running apply a 2nd time seems to have fixed it.

**Comment by gregwebs** [comment]
This is happening very frequently (almost every time the task definition is updated). Just applying a 2nd time always fixes it.

**Comment by mitchellh** [comment]
Hm, if you can reproduce this again can you please post the `Diff One` output as well?

But because this was against such an older version of TF (our fault, its been awhile), please reopen an issue if this is still happening on the latest version. We've fixed many issues related to diff mismatches.
