### ISSUE TITLE
Autoscaling goups seem to brake subnets and more

### ISSUE THREAD

**Issue by Tomino2112** [hashicorp/terraform#7743]
Hi there,

### Terraform Version
v0.6.16

### Affected Resource(s)
* aws_subnet
* aws_autoscaling_group

### Expected Behavior
Autoscaling group should be "disabled" and all instances removed before updating subnet

### Actual Behavior
Subnet update (removing) times-out because you cannot remove subnet with resources assigned to it. But autoscaling groups are keeping their instances runnig in them.

**Comment by Tomino2112** [comment]
I have just verified this by manually setting desired capacity of Autoscaling group to 0 while terraform was waiting and once instances were gone, terraform went on without a problem

**Comment by catsby** [comment]
Hey @Tomino2112 – thanks for writing in. This is an interesting problem. Your diagnosis is correct, Terraform is only doing two things here:

- trying to destroy the subnet
- trying to remove it from the ASG's zones

We don't make any attempt to try and rebalance the instances that are in the zones being removed into other availability zones :/ 

I don't have a solution for you at this time. We'd have to introduce logic that identifies instances that are in any zones being removed, then terminate them, then trust the ASG to identify and add new instances (assuming we drop below the minimum / desired)

**Comment by Tomino2112** [comment]
Hi @catsby well it would help if my subnets would not be destroyed and re-created every single time I want to apply some change. Same is happening with quite a few of my resources.

Just to clarify I am making change to something completely different and subnets and other stuff that **were not changed** are getting destroyed and re-create again. 

If I would make a change to subnet then I will be happy to deal with it manually.

**Comment by catsby** [comment]
>  it would help if my subnets would not be destroyed and re-created every single time I want to apply some change

Perhaps there is a configuration optimization to be done here. Do you have a sample config that demonstrates the changes you're making, and them resulting in recreation? 

> Just to clarify I am making change to something completely different and subnets and other stuff that were not changed are getting destroyed and re-create again.

An example would help me greatly here. This may be legitimate, for various reasons, it just depends on the configuration.

**Comment by Tomino2112** [comment]
@catsby our terraform config has grown quite a lot, not sure what part of the config I should show you, but if you want I can give you read access to our repository (bitbucket) - need your email

**Comment by Tomino2112** [comment]
@catsby Hi, you will be happy to know that I managed to find out what was wrong with the subnets.

It was really issue on my side with subnets CIDRS, but its something you might want to check on your side as well.

In my subnets I had CIDR: `172.32.13.0/23` which resolves to `172.32.12.0 - 172.32.13.255`. When running terraform, Terraform (correctly) fixed my CIDR to `172.32.12.0/23`, but since this correction doesn't save into config every time I ran update it corrected itself again and because of that re-created the same subnets. 

You might want to treat it on your side somehow, either compare the corrected CIDR to whats on AWS or display some kind of warning about the autocorrection.

This solved the subdomains, but my instances are still being re-created on every `apply` and not sure why. Something to do with security groups and elastic ip.

Here is the output from `terraform plan`

```
~ aws_eip.vpn
    instance: "i-07df6e7945e907c40" => "${aws_instance.vpn.id}"

-/+ aws_instance.deploy
    ami:                        "ami-a85133db" => "ami-a85133db"
    availability_zone:          "eu-west-1a" => "<computed>"
    ebs_block_device.#:         "0" => "<computed>"
    ephemeral_block_device.#:   "0" => "<computed>"
    iam_instance_profile:       "deploy-profile" => "deploy-profile"
    instance_state:             "running" => "<computed>"
    instance_type:              "t2.small" => "t2.small"
    key_name:                   "" => "<computed>"
    placement_group:            "" => "<computed>"
    private_dns:                "ip-172-32-24-5.eu-west-1.compute.internal" => "<computed>"
    private_ip:                 "172.32.24.5" => "172.32.24.5"
    public_dns:                 "" => "<computed>"
    public_ip:                  "" => "<computed>"
    root_block_device.#:        "1" => "<computed>"
    security_groups.#:          "0" => "2" (forces new resource)
    security_groups.1866921452: "" => "sg-d33474b4" (forces new resource)
    security_groups.3863995409: "" => "sg-c03474a7" (forces new resource)
    source_dest_check:          "true" => "true"
    subnet_id:                  "subnet-f7901b93" => "subnet-f7901b93"
    tags.#:                     "1" => "1"
    tags.Name:                  "IPP-Deploy" => "IPP-Deploy"
    tenancy:                    "default" => "<computed>"
    vpc_security_group_ids.#:   "2" => "<computed>"

-/+ aws_instance.vpn
    ami:                        "ami-41076532" => "ami-41076532"
    availability_zone:          "eu-west-1a" => "<computed>"
    ebs_block_device.#:         "0" => "<computed>"
    ephemeral_block_device.#:   "0" => "<computed>"
    iam_instance_profile:       "vpn-profile" => "vpn-profile"
    instance_state:             "running" => "<computed>"
    instance_type:              "t2.micro" => "t2.micro"
    key_name:                   "" => "<computed>"
    placement_group:            "" => "<computed>"
    private_dns:                "ip-172-32-5-248.eu-west-1.compute.internal" => "<computed>"
    private_ip:                 "172.32.5.248" => "<computed>"
    public_dns:                 "" => "<computed>"
    public_ip:                  "52.17.97.106" => "<computed>"
    root_block_device.#:        "1" => "<computed>"
    security_groups.#:          "0" => "1" (forces new resource)
    security_groups.4017336896: "" => "sg-cc3474ab" (forces new resource)
    source_dest_check:          "true" => "true"
    subnet_id:                  "subnet-f5901b91" => "subnet-f5901b91"
    tags.#:                     "1" => "1"
    tags.Name:                  "IPP-VPN" => "IPP-VPN"
    tenancy:                    "default" => "<computed>"
    vpc_security_group_ids.#:   "1" => "<computed>"


Plan: 2 to add, 1 to change, 2 to destroy.
```

No changes in config have been made

**Comment by catsby** [comment]
Hey there –

> In my subnets I had CIDR: 172.32.13.0/23 which resolves to 172.32.12.0 - 172.32.13.255. When running terraform, Terraform (correctly) fixed my CIDR to 172.32.12.0/23, but since this correction doesn't save into config every time I ran update it corrected itself again and because of that re-created the same subnets.

this kind of correction is happening on Amazon's side, unfortunately there isn't a lot we can do about it. We would like to avoid Terraform altering your config transiently, thinking "the user said X but they really meant Y". Instead we want to enforce your view of X. Hopefully that makes sense. 

> This solved subnets, but my instances are still being re-created on every apply and not sure why. Something to do with security groups and elastic ip.

This sounds like an issue with Instances in a VPC using the `security_groups` attribute, instead of `vpc_security_group_ids`. IF your instances are in a VPC, please use `vpc_security_group_ids` to list your security groups. `security_groups` are reserved for instances running in EC2 Classic, and require recreation of the instance with any change, where as the vpc version does not. 

This was mentioned in our changelog a while back, but is still a more recent change:

- https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0615-april-22-2016

Please let me know if changing your configuration to use `vpc_security_group_ids` instead of `security_groups` resolves this!

**Comment by Tomino2112** [comment]
@catsby 
* CIDR - I see, didn't the correction was coming from AWS. 
* Security groups - yes that was the problem. I remember reading it in the docs, but its very easy to forget/make mistake. I would definitely suggest changing this, since you cannot create AWS classic anymore and it regards only to old accounts, I would imagine that classic gets special treatment rather than VPC. So I would suggest `security_groups` being the default for vpc security groups and something like `classic_security_group_ids` being for the classic instances. 

I do understand that this is braking change for lot of people, but it would be more logical.

Thank you for your help!

**Comment by catsby** [comment]
A change like that would definitely make sense in the long run, however I'm against doing it right now. `vpc_security_group_ids` and `security_groups` have been documented to function as they do for some time now. While Classic environments can no longer be created by traditional means, they do still exist for many users. At this time it wouldn't be a good idea to swap them out.

Thank you for your feedback, I'm glad to hear you've gotten things sorted. I do apologize for the confusion and trouble.
