### ISSUE TITLE
Support for Object ACL's on S3 Object Creation

### ISSUE THREAD

**Issue by blakestoddard** [hashicorp/terraform#7744]
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket_object

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket_object" "object" {
    bucket = "bucket-name"
    key = "test.txt"
    source = "./test.txt"
}.
```

Currently, when you control the lifecycle of a bucket with Terraform, the only place that you are able to set the ACL is at the bucket level, through the `aws_s3_bucket` resource. If you create a private bucket and want to upload an object that is publicly accessible, which is common, you are stuck to using the AWS Console to mark that object as public or edit the ACL for it. 

The AWS CLI supports a `put-object-acl` [command](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object-acl.html) which allows you to edit the ACL of an object that already exists in a bucket. Could something similar be implemented so that object permissions could be modified through Terraform?

**Comment by catsby** [comment]
Seems like a reasonable thing to provider here, thanks!

**Comment by JonRoma** [comment]
+1

I find this a rather large omission!

**Comment by stack72** [comment]
Closed via #8091

**Comment by dbeckham** [comment]
Issue #8091 addresses canned ACL's, but not object or bucket ACLs that can be set through the `put-object-acl` or `put-bucket-acl` API commands, which this ticket is specifically asking for.

**Comment by yermulnik** [comment]
Can this be re-opened?
