### ISSUE TITLE
Support Azure Container Service

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#7748]
Azure Container Service is now GA - the SDK has been updated to include the specs (3.1-beta)

https://msdn.microsoft.com/en-us/library/mt711470.aspx

**Comment by MarkWillems** [comment]
:+1:

**Comment by drsolaris** [comment]
+1

**Comment by darrickwaller** [comment]
any idea if there are plans to include this functionality in the near future?

**Comment by stack72** [comment]
Hi @darrickwaller 

This is currently not yet supported in the Azure SDK i'm afraid 

P.

**Comment by tombuildsstuff** [comment]
As of late last week, the latest Beta (v6) for the Azure SDK contains the Container Service (again 🎉)

**Comment by tombuildsstuff** [comment]
I started looking into this last night - building up an [object for the Container Service call](https://gist.github.com/tombuildsstuff/050d4f166c43ff477e27768017a9a257). However the documentation isn't clear on how to handle the OS's for Agent Pool's - so I've [had to open an issue around a usage clarification](https://github.com/Azure/azure-sdk-for-go/issues/439)

I've pushed the branch I was using - but I can't do much for the moment until that's clarified unfortunately :(

**Comment by darrickwaller** [comment]
Microsoft released the following on Monday (November 7th):

https://github.com/Azure/acs-engine/

Not sure if that changes what you are doing, or would help at all.

**Comment by tombuildsstuff** [comment]
@darrickwaller kinda - I've actually [started this work](https://github.com/hashicorp/terraform/compare/master...tombuildsstuff:azurerm-containerservice)

Right now it's only possible to provision Linux instances - so I'm implementing that - in the mean time there's a bug been opened for the `ostype`. The blocker for me is this doesn't come out of Azure credits - rather directly against a credit card which sucks :(

**Comment by moritzheiber** [comment]
@tombuildsstuff Are you saying development has stalled because you ran out of credits? Because if that's the case I'm sure we can figure something out.

**Comment by tombuildsstuff** [comment]
@moritzheiber it was, given that Azure Container Service isn't covered by any credits since it's a licensed product - instead it comes directly off your Card..

However I've now got a means of testing this & am looking into this atm :)

**Comment by moritzheiber** [comment]
@tombuildsstuff That's good news, thank you!

**Comment by rgardler** [comment]
ACS is not a licensed product. It is an installation of open source software components on Azure. We (I'm the PM for Azure Container Service) even open source the code behind the service. As long as you have credits that can be used to pay for Azure resources then you can use them to pay for ACS.

Perhaps I'm missing the point?

**Comment by tombuildsstuff** [comment]
@rgardler thanks for getting back to us here.

I get this screen when deploying a Container Service instance via the portal - which is so generic I'm interpreted it as meaning I'm going to be charged on my card?
<img width="960" alt="screen shot 2016-11-01 at 22 10 57" src="https://cloud.githubusercontent.com/assets/666005/21674092/292a7bf6-d324-11e6-8e6a-db1796e834c1.png">

If I'm not going to be charged, then surely it's misleading to display the screen?

**Comment by tombuildsstuff** [comment]
@darrickwaller @drsolaris @moritzheiber @stack72 FYI support for Container Service has been merged (PR #10820) - so it should be available in the next Terraform release :)

@rgardler great - thanks for the clarification 👍

**Comment by rgardler** [comment]
Awesome stuff... thank you 👍

**Comment by mongrelion** [comment]
@stack72 this issue can be closed since the support for ACS has already landed.

**Comment by stack72** [comment]
Thanks for the bump on this :)

**Comment by stack72** [comment]
Closed via #10820
