### ISSUE TITLE
Feature Request: CORE - delete only one machine

### ISSUE THREAD

**Issue by jare19** [hashicorp/terraform#7757]
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

-CORE
### Expected Behavior

What should have happened?
`$ terraform destroy -target=module.rundeck.vsphere_virtual_machine.vm.1`
I believe this should delete one indexed instance(vm) of a deployed module (including indexed dependencies)
### Actual Behavior

`$ terraform destroy -target=module.rundeck.vsphere_virtual_machine.vm.1`
`Do you really want to destroy?`
  `Terraform will delete the following infrastructure:`
`module.rundeck.vsphere_virtual_machine.vm.1`
`There is no undo. Only 'yes' will be accepted to confirm`

  `Enter a value: yes`

`Error configuring: Unexpected value for InstanceType field: "1"`
### Steps to Reproduce

Deploy more that one machine from a module, try to remove/redeploy just one machine.
### Important Factoids

standard vsphere deploy with a module
### References

not that I could find

**Comment by analbeard** [comment]
The same problem still exists in 0.7.4 :(

**Comment by analbeard** [comment]
@apparentlymart ah! That's exactly what I was after - thanks!

**Comment by james-flynn-ie** [comment]
@apparentlymart, it looks like we can close this issue.

**Comment by apparentlymart** [comment]
Indeed, things have been quiet here for a while, so I'm going to close this out and assume my previous response was sufficient here. Thanks for the nudge, @james-flynn-ie!
