### ISSUE TITLE
azurerm create/update dns record api changed in riviera resulting in empty dns cname record

### ISSUE THREAD

**Issue by cmsd2** [hashicorp/terraform#7758]
the azurerm rest api uses the property CNAMERecord instead of CNAMERecords as per
https://msdn.microsoft.com/en-us/library/azure/mt130640.aspx
https://github.com/jen20/riviera/commit/f4b44420efc25498b214a1a909f85da86ada0b13

terraform currently sends "CNAMERecords": [{"cname": "..."}] in the create/update operations,
instead of "CNAMERecord":{"cname":"..."}

the array property with the wrong spelling is ignored by the azurerm rest api.
the effect is that the value of the record is blanked out.

the current version of riviera looks like it has the correct implementation, and the azurerm provider in terraform needs updating to use it.

**Comment by stack72** [comment]
Hi @cmsd2

The work for this implementation is in terraform 0.7 (master)

It will be released ASAP.  Sorry if this is causing issues

Paul

**Comment by cmsd2** [comment]
ok thanks.
