### ISSUE TITLE
Intermittent timing issue causing issues with apply

### ISSUE THREAD

**Issue by teancom** [hashicorp/terraform#776]
Using https://github.com/cloudfoundry-community/terraform-aws-cf-install, with terraform HEAD (9c02a6e4f76e0d3c2eda823e351a0cc3e891c8b7), most of the time (4 out of 5? 9 out of 10?) it fails with the following error:

```
Error applying plan:

aws_security_group.cf: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
make: *** [apply] Error 1
```

This also fails with `0.3.5` and `0.3.6`. However! Good news, we happened to have a version that does work every time, a build of fd6382fbafe0b. The only other thing that *may* have an affect is that if we add TF_LOG=1, it seems to increase the odds of the `terraform apply` working, though not always (and I'm not 100% convinced it isn't a placebo effect). That it works some times and not others, with no other changes, is what leads us to believe it's a timing issue.

I'm sorry, I realize this is a bit of a mess - if there is anything else we can do to help troubleshoot, I would be glad to.

**Comment by mitchellh** [comment]
For this, can you get a `TF_LOG=1` output when this error happens? We'll need that to make any more progress here.

**Comment by mitchellh** [comment]
Closing due to lack of response but also there is a good chance that this error might be gone now as the core has undergone serious improvements. Please let us know if you see it again.
