### ISSUE TITLE
aws rds  Error: doesn't support update

### ISSUE THREAD

**Issue by xueshanf** [hashicorp/terraform#777]
When using aws_db_instance to create a mysql instance,  if I don't  specify
availability_zone,  backup_retention_period, backup_window, maintenance_window and port,  terraform will create default values for them and saved in terraform.tfstate file. The db instance will be created fine.

However,  if I run  terraform plan with nothing change against the same .tf file, it generates the following plan and suggests to change these attributes:

aws_db_instance.mydb: Refreshing state... (ID: mydb)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ aws_db_instance.mydb
    availability_zone:       "us-west-2c" => ""
    backup_retention_period: "1" => ""
    backup_window:           "09:19-09:49" => ""
    maintenance_window:      "fri:08:22-fri:08:52" => ""
    port:                    "3306" => ""

If I do run apply, it will generate:
aws_db_instance.mydb: Refreshing state... (ID: mydb)
aws_db_instance.mydb: Modifying...
  availability_zone:       "us-west-2c" => ""
  backup_retention_period: "1" => ""
  backup_window:           "09:19-09:49" => ""
  maintenance_window:      "fri:08:22-fri:08:52" => ""
  port:                    "3306" => ""
aws_db_instance.mydb: Error: doesn't support update

If I put these values in the original .tf file to match, then terraform plan command will be clean, no changes. 

It is a bug?

**Comment by bitglue** [comment]
There are two problems here:

  1. `aws_db_instance` doesn't support update, only delete/modify. There is [a RDS API](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html) for modifications, but [the go library Terraform uses](https://github.com/mitchellh/goamz/blob/master/rds/rds.go) doesn't support it yet.
  2. Terraform is deciding that it needs to do an update when in fact it does not. This is fixed in #874.

**Comment by catsby** [comment]
Considering this closed. 
I have a pull request up coming to address part of 1. above
