### ISSUE TITLE
Support AWS EFS performance modes

### ISSUE THREAD

**Issue by marcoamorales** [hashicorp/terraform#7773]
Hi,

There's currently no support for EFS performance modes. There's currently two performance modes: 
- General Purpose (default)

- Max I/O

By default Terraform will build a General Purpose EFS and there's no way to specify anything other than that.

### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_efs_file_system

**Comment by kwilczynski** [comment]
@marcoamorales this should be taken care of in #7791, and I hope it would resolve your issue.

**Comment by stack72** [comment]
closed via #7791 - thanks @kwilczynski!
