### ISSUE TITLE
Need to bump AWS SDK from 1.2.5 to 1.2.7

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#7780]
In order to implement the missing feature for api-gateway (passthrough_behavior), need to change to AWS SDK to 1.2.7.

I notice we are using govendor instead of godep now.  I wonder what is the correct procedure to bump up the SDK version.  Should I modify vendor.json and perform a sync or I manually do ``govendor fetch`` on each of the package?  Also, for 1.2.7, there are new dependencies packages (e.g. aws/signer/v4).

What's the best practice on dealing package management in Terraform now?  The README.md is too lean on this topic.

**Comment by stack72** [comment]
Hi @iceycake 

Sorry the README isn't very informative for you here. I personally use the [govendor cheat sheet](https://github.com/kardianos/govendor/wiki/Govendor-CheatSheet)

The specific command you would want to run in your case would be:

```
govendor fetch github.com/aws/aws-sdk-go/...@v1.2.7`
```

This will update all the packages (that we currently use!) in the 1.2.7 release. I just opened #7799 to address the upgrade

Paul
