### ISSUE TITLE
Terraform not waiting for GCE instance destruction to complete before destroying disks.

### ISSUE THREAD

**Issue by jim-raney-physiq** [hashicorp/terraform#7792]
Hello,

This is basically re-opening [#2785](https://github.com/hashicorp/terraform/issues/2785).  Terraform is not waiting for instances to be destroyed before attempting to destroy secondary disks in the Google Cloud Compute environment.  The project in  [#2785](https://github.com/hashicorp/terraform/issues/2785) works correctly, but it may be a matter of scale.  The project located [here](https://github.com/physIQ/turnkey-riak) issues the following error on a 'terraform destroy':

`* google_compute_disk.riakDiskMagnetic.1: Error deleting disk: googleapi: Error 400: The disk resource 'test-stack-01-riak-02-disk-02' is already being used by 'test-stack-01-riak-02', resourceInUseByAnotherResource`

Sometimes every disk generates this error, other times only a subset - it's probably just a matter of how fast google deletes the instances and whether or not the disk delete executes before the instance is gone.  Typically, re-executing 'terraform destroy' takes care of the leftover disks, but now we are trying to automate stack builds for integration testing in Jenkins and would rather have terraform delete the disks at the correct time (after instance destruction) and not exit with an error.

The [project](https://github.com/physIQ/turnkey-riak) builds 9 servers, five of which are riak servers with a pair of secondary disks.  We see this in our full-stack environment as well, including on servers that are not built via modules.  The above linked project has instructions in the README file to build.

We are running terraform 0.6.16.

**Comment by mengesb** [comment]
From what I can see, it is a problem with your plan.

For example...
```hcl
resource "google_compute_disk" "riakDiskSSD" {
        name = "${format("${var.StackName}-${var.name}-%02d-disk-01", count.index+1)}"
        size = "${var.diskSSD}"
        type = "pd-ssd"
        count = "${var.count}"
        zone = "us-central1-b"
}
```
and
```hcl
resource "google_compute_instance" "instance" {
		name = "${format("${var.StackName}-${var.name}-%02d", count.index+1)}"
		machine_type = "${var.machine_type}"
		zone = "${var.zone}"
		count = "${var.count}"

		disk {
			image = "${var.google_image}"
		}
		disk {
                        disk = "${format("${var.StackName}-${var.name}-%02d-disk-01", count.index+1)}"
                        device_name = "tsSSD"
                        auto_delete = false
                }
<SNIP>
```

There's nothing for Terraform to establish the relationship here. You're using format to construe a name where you should be using the relative identifier

```hcl
		disk {
                        disk = "${element(google_compute_disk.riakDiskSSD.*.name, count.index)}"
                        device_name = "tsSSD"
                        auto_delete = false
                }
``` 

Not exactly sure on GCE provider usage, however that would appear to more correctly establish the relationship.

**Comment by jim-raney-physiq** [comment]
You are 100% correct.  After I modified the project to follow the above configuration directives it deleted the disks in the proper order.  I had inherited this codebase and thought that was the correct way to identify the disks - thanks!
