### ISSUE TITLE
Crash when using splat on aws_availability_zones data source.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7796]
When using a splat on the `aws_availability_zones` data source (erroneously?), Terraform crashes. Strangely, using the same splat reference in an output works without error.
### Terraform Version

```
$ ~/Downloads/terraform-0.7-rc3/terraform version
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
```
### Affected Resource(s)
- `aws_availability_zones` data source
### Terraform Configuration Files

```
# offending line in an aws_subnet...
availability_zone = "${element(data.aws_availability_zones.zones.*.names,count.index)}"
```

Full config is here - https://gist.github.com/clstokes/c969c76d212f0fa791cfbbfd9c2c0381#file-main-tf.
### Panic Output

https://gist.github.com/clstokes/c969c76d212f0fa791cfbbfd9c2c0381#file-crash-log
### Expected Behavior

I think the splat usage is erroneous (user error on my part), so I would expect Terraform to exit with an error about incorrect syntax. However, it works as the output, so I'm not sure if it should work or not.
### Actual Behavior

Terraform crashes.
### Steps to Reproduce
1. `terraform apply`

**Comment by radeksimko** [comment]
Looking at the crash log I think that splat doesn't work for any data source due to the ordering of operations in the lifecycle (interpolation specifically).
It may be related to https://github.com/hashicorp/terraform/issues/3449

**Comment by mitchellh** [comment]
This is fixed on master.
