### ISSUE TITLE
State mv command is overly aggressive on name matching.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7797]
Terraform is overly aggressive on name matching when doing `state mv` commands resulting in resources being lost in my state. If I have `aws_vpc.main[0]` and `aws_vpc.main[1]` in my state, and `state mv aws_vpc.main` without the brackets my first vpc is moved and the rest are removed from my state.

### Terraform Version
```
$ ~/Downloads/terraform-0.7-rc3/terraform version
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
```

### Affected Resource(s)
All resources I believe.

### Terraform Configuration Files
```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  tags {
    Name = "import-${count.index}"
  }
  count = 2
}
```

https://gist.github.com/clstokes/d1b7cc64a310dd7d2e29d7176e613bf3#file-main-tf

### Debug Output
https://gist.github.com/clstokes/d1b7cc64a310dd7d2e29d7176e613bf3#file-log-log

### Expected Behavior
Terraform show have exited with an error that the resource was not found or that more than one resource was found.

### Actual Behavior
Terraform moved the first resource it found and removed the others.

### Steps to Reproduce
1. `terraform apply`
1. `terraform state list` <- See 2 VPCs
1. `terraform state mv aws_vpc.main aws_vpc.renamed` <- See _only_ 1 VPC remains

**Comment by mitchellh** [comment]
Fix for this is in the referenced PR now!
