### ISSUE TITLE
Import doesn't support indexed resources but state mv does.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7798]
If I try to import a resource to an indexed position (e.g. `import aws_vpc.main[0] vpc-abc123, the import completes successfully but my index is ignored (e.g. imported to `aws_vpc.main`), while `state mv` honors the index.

### Terraform Version
```
$ ~/Downloads/terraform-0.7-rc3/terraform version
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
```

### Affected Resource(s)
All resources I believe.

### Terraform Configuration Files
None. Can start with an empty config.

### Debug Output
https://gist.github.com/clstokes/c218e41ffeab77e521e3de9ab7aea980#file-log-log

### Expected Behavior
Terraform should have honored my index for the location in my state.

### Actual Behavior
Terraform imported the resource into a non-indexed location in my state.

### Steps to Reproduce
1. `terraform import aws_vpc.main[0] vpc-abc123`
1. `terraform state list`

### References
- https://github.com/hashicorp/terraform/issues/7797 - Perhaps related as similar to name matching issue there.

**Comment by mitchellh** [comment]
Dup #7691, I'm working on that now though.
