### ISSUE TITLE
Error removing security group from Open Stack compute instance

### ISSUE THREAD

**Issue by lexsys27** [hashicorp/terraform#7807]
Hello!

I see and error while removing security group from compute instance in Open Stack and deleting this security group. Changes are actually applied.

### Terraform Version

Terraform v0.6.16

### Affected Resource(s)

- openstack_compute_secgroup_v2
- openstack_compute_instance_v2

### Terraform Configuration Files

From 

```hcl
resource "openstack_compute_instance_v2" "vm" {
    count = 4
    name = "vm/${count.index}" # vm/1
    security_groups = ["ssh", "inner", "tomcat", "eureka"]
```

To

```hcl
resource "openstack_compute_instance_v2" "vm" {
    count = 4
    name = "vm/${count.index}" # vm/1
    security_groups = ["ssh", "inner", "tomcat"]
```

### Debug Output

I have removed 3 more instances from the output - they show identical behavior.

https://gist.github.com/lexsys27/79d7a5161e9fdde1c28fd991f6d52275

### Expected Behavior

1. Security group `eureka` deleted
2. Instance `vm/0` has no security group `eureka` associated with it
3. No errors

### Actual Behavior

1. Security group `eureka` deleted
2. Instance `vm/0` has no security group `eureka` associated with it
3. Terraform shows an error

```
Error applying plan:

1 error(s) occurred:

* openstack_compute_instance_v2.vm.0: Error removing security group from OpenStack server (b0e0728a-da9e-4998-bd3a-5e8f0f2314aa): EOF
```

**Comment by jtopjian** [comment]
@lexsys27 Thanks for reporting this! This has been fixed and is currently available in a [0.7 rc release](https://releases.hashicorp.com/terraform/0.7.0-rc3/) or will be available in the official 0.7 release.
