### ISSUE TITLE
Associate VPC with an existing VPN gateway

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/terraform#7810]
When you create a new VPC in TerraForm, is there a way to associate it with an already existing VPN gateway?

Something similar to how "aws_route_table_association" can be used to associate an existing routing table to a subnet?

**Comment by stack72** [comment]
Hi @jeroenjacobs1205 

there is currently no such resource for this. A simple `aws_vpn_gateway_attachment` resource could be added that effectively uses this call http://docs.aws.amazon.com/cli/latest/reference/ec2/attach-vpn-gateway.html

This isn't going to be high on the list right now, so if you feel you could open a PR for this, then it would be gratefully received :)

Paul

**Comment by kwilczynski** [comment]
To add.

API documentation for posterity:

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AttachVpnGateway.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcAttachment.html

Go SDK:

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/

This should not be hard to add, I will have a look at it.

**Comment by dhait** [comment]
As per @stack72, we use a separate bash script to do the attachment, which is attached to a null_resource and triggered by the creation of the vpc.

Here's the idea:
[https://gist.github.com/dhait/900852d794aa17140a148af03fc81b30](url)

**Comment by kwilczynski** [comment]
To add.

The `aws_vpn_gateway` resource will be updated to make the VPC ID a computed attribute. Since upon the attachement it would refresh VPN Gateway state and then notice that it now is attached and the VPC ID was populated.

**Comment by kwilczynski** [comment]
I am working on this in #7870.

**Comment by stack72** [comment]
Closed via #7870
