### ISSUE TITLE
Crash and terraform plan on aws rds security group

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform#7812]
### Terraform Version

Terraform v0.6.16

### Affected Resource(s)

- `aws_db_security_group`

### Terraform Configuration Files

`empty.tf`:

```hcl
# Empty
```

`terraform.tfstate`:

```json
{
  "version": 1,
  "serial": 1,
  "modules": [
    {
      "path": [
        "root"
      ],
      "outputs": {
      },
      "resources": {
        "aws_db_security_group.qa": {
          "type": "aws_db_security_group",
          "primary": {
            "id": "qa",
            "attributes": {
              "db_subnet_group_name": "qa",
              "id": "qa",
              "ingress.#": "2",
              "name": "qa"
            }
          }
        }

      }
    }
  ]
}
```

### Debug Output

- `terraform plan`: https://gist.github.com/lra/393e2ea8146d435ab5d35b1cba2717fd
- Extract of `TF_LOG=DEBUG terraform plan`: https://gist.github.com/lra/f8eb52e8caac9e656ce3bce56496df31 (cut some info out)

### Panic Output

https://gist.github.com/lra/2a18d84de6cfdc168bb7adb8fc6be972

### Expected Behavior

`terraform plan` should not crash

### Actual Behavior

`terraform plan` crashed

### Steps to Reproduce

1. `terraform plan`

**Comment by stack72** [comment]
Hi @lra 

Sorry this is causing an issue for you. The empty.tf suggests you are trying to plan on an empty terraform file? Is this correct? If not, please can you provider the configuration you are using (minus secrets) so that I can try and reproduce this error?

Thanks

Paul

**Comment by lra** [comment]
In a clean folder with an empty `empty.cf` and the given `terraform.tfstate`, it crashes. So I'm not sure if giving you our conf will help.

Here's what I had to comment out in our tf:
```
# Commented out as it crashes terraform
# https://github.com/hashicorp/terraform/issues/7812
# TODO: enable again once the bug is fixed
#
# resource "aws_db_security_group" "qa" {
#     name        = "qa"
#     description = "Blah Blah"

#     ingress {
#         cidr                    = ""
#         security_group_name     = "qa"
#         security_group_id       = ""
#         security_group_owner_id = "123456789"
#     }

#     ingress {
#         cidr                    = ""
#         security_group_name     = "somegrp"
#         security_group_id       = "sg-123456"
#         security_group_owner_id = "123456789"
#     }

# }
```

**Comment by stack72** [comment]
Hi @lra 

ok, I still haven't been able to recreate this issue BUT i have just opened #7893 that will defensively code around the issue to makes sure it doesn't happen

Paul

**Comment by lra** [comment]
confirmed to be fixed, thanks

**Comment by stack72** [comment]
Thanks for checking and letting me know @lra :)
