### ISSUE TITLE
Terraform output disappearing when running targeted plan

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#7820]
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

`terraform output` (does not appear to be resource dependent)
### Terraform Configuration Files

``` hcl
provider "aws" {
    region = "us-east-1"
}

variable "foo" { default = "foo,bar" }

resource "aws_security_group" "allow_none" {
  name = "bug_allow_none"
  description = "Allow no inbound traffic"
}

resource "aws_eip" "default" {
  count = "${length(split(",", var.foo))}"
}

output "eip_ips" {
  value = "${join(",", aws_eip.default.*.public_ip)}"
}

output "allow_none_id" {
  value = "${aws_security_group.allow_none.id}"
}
```
### Debug Output

https://gist.github.com/jszwedko/c792c6cce535f22135ff5e5fe3eb3c43
### Expected Behavior

`terraform output` has both `allow_none_id` and `eip_ips`
### Actual Behavior

`terraform output` has only `allow_none_id`
### Steps to Reproduce

```
terraform plan
terraform apply
terraform output # note output values
terraform plan -target aws_security_group.allow_none
terraform output # note lack of eip_ips output
```
### Important Factoids

This issue appears to be related to using an interpolated value as the `count` for the `aws_eip` resource. If we hardcode the count to `2` the issue does not present itself.

/cc @stephenchu

**Comment by mitchellh** [comment]
Same issue as #5334, closing as dup.
