### ISSUE TITLE
Feature Proposal: Subfolder support that is backward compatible

### ISSUE THREAD

**Issue by KieranP** [hashicorp/terraform#7823]
We have a big infrastructure. We want to split it up by folders, but Terraform currently doesn't support this. So having thought about it, how about a new structure for importing folders:

Given folder structure of:

```
./main.tf
./core/aws.tf
./core/vpc.tf
./ec2/bastion.tf
./ebs/app1.tf
./ebs/app2.tf
./rds/app1.tf
./rds/app2.tf
```

and a ./main.tf file of:

```
import { path = './core' }
import { path = './ec2' }
import { path = './ebs' }
import { path = './rds' }
```

With this proposal, it doesn't change current behaviour incase people have nested terraform configs they don't want loaded, and under the hood, all the import directive would need to do is load all files in that directory.

Though not necessary, you could add glob support as well. `import { path = './apps/*/app.tf' }`

And files it imports could also import things:

./main.tf: `import { path = './core' }`
./core/main.tf: `import { path = './misc' }`
./core/misc/main.tf: `resource { .... }`

Please give this consideration, as it would greatly increase the organisation of larger Terraform backed infrastructures.

**Comment by KieranP** [comment]
Should also point out that many articles point at modules to help with this. However, it creates extra work, as a module ends up isolating references, so suddenly, everything needs to reference `module.core.aws_vpc` or similar through the whole codebase rather than just `aws_vpc`. The approach above would be similar as if all imported scripts simply got appended to make one big script.

**Comment by mitchellh** [comment]
There is an "include" core enhancement request that I agreed with so I think we will eventually support something like this.

**Comment by sandyfox** [comment]
+1

**Comment by Constantin07** [comment]
Completely agree, modules are not very convenient when there is no actually need to re-use the code but rather include files from sub-directories purely from structure organization point of view.
+1

**Comment by jordiclariana** [comment]
Hey @mitchellh , can you point to the "include" core enhancement issue, please? I would like to keep track on that. Thanks.

**Comment by coryodaniel** [comment]
@jordiclariana I believe it is https://github.com/hashicorp/terraform/issues/1478

**Comment by danielsand** [comment]
👍

**Comment by thakkerdhawal** [comment]
+1

**Comment by wesback** [comment]
+1

**Comment by jasimmk** [comment]
+1
