### ISSUE TITLE
TF Crash

### ISSUE THREAD

**Issue by robrankin** [hashicorp/terraform#7824]
### Terraform Version
Terraform v0.7.0-dev (35b714e687fb93604d82c8fed9c0be3321cd91c7)

### Affected Resource(s)
Apply a plan file

### Terraform Configuration Files
```hcl
variable "test" {
    type = "map"
    default = {
      "test" = "1"
    }
}
```

### Panic Output
https://gist.github.com/robrankin/4e5fb3cf61b36d6a67b39438320bc97a

### Expected Behavior
```
terraform apply plan.out

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Actual Behavior
Terraform crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out plan.out`
2. `terraform apply plan.out` 

### Important Factoids
TF version compiled from master today.  Older versions (last week) are working correctly.

### References
Unknown

**Comment by stack72** [comment]
Hi @robrankin 

Thanks for reporting this issue. In order to help us debug the issue, can you tell me what configuration you were using that caused the panic? 

Thanks

Paul

**Comment by robrankin** [comment]
@stack72 Not sure what you want to know?  All thats required is 1 TF file with the example variable declared, run `terraform plan -out <outfile>`, then run `terraform apply <outfile>` .  No other configuration is involved.

If you however just run `terraform apply` without a plan file, it works fine, suggesting its something to do with the plan file.

**Comment by stack72** [comment]
Hi @robrankin 

Thanks for that, I have indeed been able to reproduce this :)

Let's see what we can get fixed

Paul

**Comment by robrankin** [comment]
Working for me... TF compiled from master.

```
[robrankin@host TF7824]$ ls
variable.tf

[robrankin@host TF7824]$ cat variable.tf
variable "test" {
    type = "map"
    default = {
      "test" = "1"
    }
}

[robrankin@host TF7824]$ terraform plan -out plan.out
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.

[robrankin@host TF7824]$ terraform apply plan.out

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

[robrankin@host TF7824]$ terraform version
Terraform v0.7.0-dev (bad37a57cbea29d96753750bf95f23241f520681)
```
