### ISSUE TITLE
An output ends up being removed when refreshing with target

### ISSUE THREAD

**Issue by kamatama41** [hashicorp/terraform#7825]
I have the behavior written in title with an output approach that uses join

```
output "subnet_ids" {
  value = "${join(",", aws_subnet.examples.*.id)}"
}
```

but it does not happen with an approach that uses index directly

```
output "subnet_ids" {
  value = "${aws_subnet.examples.0.id},${aws_subnet.examples.1.id}"
}
```

So I'm confused 😕 
Thank you.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- aws_vpc
- aws_subnet
### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "example" {
  cidr_block = "10.1.0.0/16"
  tags { Name = "example" }
}

variable "subnet_count" {}
resource "aws_subnet" "examples" {
  count = "${var.subnet_count}"
  vpc_id = "${aws_vpc.example.id}"
  cidr_block = "${format("10.1.%d.0/24", count.index)}"
  availability_zone = "us-east-1a"
  tags { Name = "${format("example-%d", count.index)}" }
}

output "subnet_ids" {
  value = "${join(",", aws_subnet.examples.*.id)}"
#  value = "${aws_subnet.examples.0.id},${aws_subnet.examples.1.id}"
}
```
### Debug Output

https://gist.github.com/kamatama41/7a4084cff258c716c13abb0068d24f96
### Expected Behavior

`subnet_ids` remains 

```
% terraform output
subnet-xxxxx,subnet-yyyyy
```
### Actual Behavior

the output is missed

```
% terraform output
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
```
### Steps to Reproduce
1. `terraform apply -var 'subnet_count=2'`
2. `terraform refresh -target=aws_vpc.example -var 'subnet_count=2'`
3. `terraform output`

**Comment by mitchellh** [comment]
Same issue as #5334, closing as dup.
