### ISSUE TITLE
GCE instance template support for metadata_startup_script

### ISSUE THREAD

**Issue by ashmere** [hashicorp/terraform#7827]
Currently the gce provider support metadata_startup_script for google_compute_instance but not google_compute_instance_template.

The GCE API support this for both
https://cloud.google.com/compute/docs/instance-templates

could we please have this feature supported.

**Comment by baskaran-md** [comment]
@mitchellh Any updates on this feature request?

**Comment by paddyforan** [comment]
This should be supported by #10537.
