### ISSUE TITLE
Implementation for Route 53 CloudWatch health check 

### ISSUE THREAD

**Issue by dlyub** [hashicorp/terraform#7830]
I need to create a Route 53 health check that's tied to the CloudWatch alarm. Looking at Terrafrom documentation I only see mechanisms for creating endpoint and calculated checks:
https://www.terraform.io/docs/providers/aws/r/route53_health_check.html

I've checked Amazon API documentation and it does support 'CLOUDWATCH_METRIC' health check type:
http://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHealthCheck.html

Does Terraform support 'CLOUDWATCH_METRIC' type? If not, are there any plans to support it?

Thank you!

**Comment by brendonmartino** [comment]
+1

**Comment by stack72** [comment]
Hi @dlyub 

there is technically nothing stopping a CLOUDWATCH METRIC healthcheck type. Have you tried to write one?

Paul

**Comment by achalupa74** [comment]
+1

**Comment by dlyub** [comment]
Hi @stack72 

Any ideas on what to do about ip / fqdn? documentation says one of them is required. Also, suggestions on the syntax for providing alarm name to the health check?

Thank you!

**Comment by stack72** [comment]
ok, I take that back, on spending 5 mins looking into the Go-SDK for AWS, I can see that we are missing:

```
// A complex type that contains information to uniquely identify the CloudWatch
// alarm that you're associating with a Route 53 health check.
AlarmIdentifier *AlarmIdentifier `type:"structure"`

// The status of the health check when CloudWatch has insufficient data about
// the state of associated alarm. Valid values are Healthy, Unhealthy and LastKnownStatus.
InsufficientDataHealthStatus *string `type:"string" enum:"InsufficientDataHealthStatus"`
```

That would allow us to pass in the correct values. IF anyone wants to take a shot at this, we would love a PR :)

Paul

**Comment by optimisticanshul** [comment]
@stack72 I will do.

**Comment by stack72** [comment]
@optimisticanshul don't worry - i am just opening a PR for this as we speak
