### ISSUE TITLE
aws_sns_platform_application support

### ISSUE THREAD

**Issue by jedi4ever** [hashicorp/terraform#7835]
Aloha TF<3ers,

one of the resources we're using that is still missing is the SNS platform_application_support.
Doing it from the shell looks like:

```
aws sns --region eu-west-1 create-platform-application --platform "APNS" --name "$1" --attributes PlatformCredential="\"$(openssl pkcs12 -in "$p12" -nodes -nocerts)\"",PlatformPrincipal="\"$(openssl pkcs12 -in "$p12" -nodes -nokeys)\""
```

I could probably cobble this together. Just creating this ticket if someone else might be working on it.

**Comment by stack72** [comment]
Looks like #4951 already solves this

**Comment by jedi4ever** [comment]
closing it here -
