### ISSUE TITLE
Need ElasticSearch 2.3 support

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#7836]
### Terraform Version
Terraform v0.7.0-dev

### Affected Resource(s)
- aws_elasticsearch_domain

ElasticSearch now supports 2.3 and the API has additional fields to pick the new version.  However, `aws-sdk-go` is missing the API though.

**Comment by stack72** [comment]
Hi @iceycake 

I'm kind of confused as to what the request is here? Is there something that needs to change on the Terraform side?

Paul

**Comment by iceycake** [comment]
Terraform is missing the following fields for the new ElasticSearch (2.3, AWS just announced about an hour ago)

http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain

New: `ElasticsearchVersion`
Changed: `CreateElasticsearchDomainInput`

I would like to work on a PR but the aws-sdk-go doesn't have those yet.  We have someone working on a PR on aws/aws-sdk-go at the moment.

**Comment by stack72** [comment]
Got it! So we are currently waiting on the SDK upgrade before this can be added

P

**Comment by iceycake** [comment]
Correct.  Just open this issue to make sure we will need to add it once the SDK is ready.

**Comment by ledor473** [comment]
Here's the PR in aws-sdk-go 
https://github.com/aws/aws-sdk-go/pull/778

**Comment by jasdel** [comment]
HI all, Jason from the AWS SDK for Go, I closed the linked PR aws/aws-sdk-go#778 since the service clients are generated. We're working on getting these updates out, and will update on aws/aws-sdk-go#779 when they are available. Thanks!

**Comment by dhawal55** [comment]
+1

**Comment by vhiairrassary** [comment]
They just released aws/aws-sdk-go `v1.2.9` & `v1.2.10` with [support for Elasticsearch 2.3](https://aws.amazon.com/releasenotes/6431367547946551)

**Comment by chrisburrell** [comment]
Great stuff :) Do we know if there a specific release date? Or I can obtain a snapshot version before the release?

**Comment by jedi4ever** [comment]
+1 on releasing this
