### ISSUE TITLE
Allow creating MultiAZ memcached cluster in a single terraform apply where number nodes > number of AZ's

### ISSUE THREAD

**Issue by msroest** [hashicorp/terraform#7850]
Currently a aws_elasticache_cluster using MultiAZ setup with num_cache_nodes > then count of availability_zones.

AWS validation will fail with the following error:
 aws_elasticache_cluster.swimlane-memcache: Error creating Elasticache: InvalidParameterCombination: Must specify the same number of preferred availability zones as requested number of nodes.
    status code: 400, request id: 63124b02-54f6-11e6-95b5-3960d6e4870c

It can be done in 2 stages by setting num_cache_nodes to the same as the number of AZ's then after creation is complete change the num_cache_nodes to the final desired number.

It would be nice if terraform would do this itself.

**Comment by stack72** [comment]
Hi @msroest 

Thanks for opening the issue here - have you got a sample configuration that demonstrates the error you are getting?

thanks

Paul

**Comment by msroest** [comment]
Do you want just a snippet with just the memcache resource?  Or would you like a full definition with everything that's needed (vpc, subnet group etc)

**Comment by stack72** [comment]
Hi @msroest 

Sorry for not getting back to you sooner - we are looking at ways of being better notified if a response to a question is sent

Just the memached resource would be useful - please let me know how many subnets that you are passing to it as well so i can try and replicate :)

P.

**Comment by msroest** [comment]
resource "aws_elasticache_cluster" "swimlane-memcache" {
    cluster_id = "clusterid"
    engine = "memcached"
    node_type =  "cache.t2.small" 
    port = 11211
    num_cache_nodes = "6"
    parameter_group_name = "test-param-group"
    subnet_group_name = "test-subnet-group"
    security_group_ids = ["sg.xxxxxx"]
    availability_zones = ["us-west-2a","us-west-2b"]
}

This will give the error that number of nodes must match.   If you change number of nodes  to 2 for initial creation then update with the larger number it works.  If you just repeat the zones to get the same number it will still fail with the same validation.

**Comment by stack72** [comment]
perfect! thanks - i will start looking at this!

**Comment by stack72** [comment]
Hi @msroest 

So on looking at this, this is actually an AWS limitation. From the [documentation](http://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html), I can see the following:

```
##PreferredAvailabilityZones.PreferredAvailabilityZone.N
The number of Availability Zones listed must equal the value of NumCacheNodes.
```

I am going to have to label this as an enhancement again and see if we can schedule some time for this. Basically, the flow for Terraform on a db_instance is:

Create -> Read
Update -> Read

For this to work, we would have to change to:

Create -> Update - >Read
Update -> Read

Where those names are the names of the API calls involved. This would involve a schema change to be something like we use the number of AZs specified to be used as the number of cache nodes on the Create and then in the Update we use the `num_cache_nodes` param. As you can see, a lot more thought is needed here

Paul
