### ISSUE TITLE
aws_instance always thinks there are no assigned security groups

### ISSUE THREAD

**Issue by orclev** [hashicorp/terraform#7853]
When running `terraform plan` or `terraform apply` terraform will always re-create ec2 instance resources because it incorrectly detects that they have 0 assigned security groups.

### Terraform Version
Confirmed in v0.6.16, possibly present in earlier builds.

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
Example config:
```hcl
resource "aws_instance" "jump_server" {
  ami = "${var.centos_ami}"
  instance_type = "t2.micro"
  key_name = "${var.key_name}"
  source_dest_check = false
  associate_public_ip_address = true
  subnet_id = "${var.subnet_id}"
  security_groups = ["${var.jump_sg}"]

  root_block_device {
    volume_size = "10"
    volume_type = "standard"
    delete_on_termination = true
  }

  tags {
    Application = "${var.stack_name}"
    Name = "jump"
  }
}
```

### Debug Output
When running `terraform plan` will receive output similar to the following:
```
security_groups.#:                         "0" => "1" (forces new resource)
security_groups.1507261234:                "" => "sg-753b1c2d" (forces new resource)
```

### Expected Behavior
Resources should only be re-created if the specified security group actually changes.

### Actual Behavior
Terraform believes that no instances ever have a assigned security group and that the instance needs to be re-created.

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

### Important Factoids
Applying ignore_changes to security_groups on aws_instance resources will prevent the resource from being re-created on every run, but it also forces you to manually taint the resource if you do modify the security group.

### References
- GH-6993

**Comment by stack72** [comment]
Hi @orclev 

My apologies this has caused an issue for you. I can look straight away and see that your config should be as follows:

```
resource "aws_instance" "jump_server" {
  ami = "${var.centos_ami}"
  instance_type = "t2.micro"
  key_name = "${var.key_name}"
  source_dest_check = false
  associate_public_ip_address = true
  subnet_id = "${var.subnet_id}"
  vpc_security_group_ids = ["${var.jump_sg}"]

  root_block_device {
    volume_size = "10"
    volume_type = "standard"
    delete_on_termination = true
  }

  tags {
    Application = "${var.stack_name}"
    Name = "jump"
  }
}
```

Notice that I changed `security_groups` to `vpc_security_group_ids`. Looking at the docs:

```
security_groups - (Optional) A list of security group names to associate with. If you are within a non-default VPC, you'll need to use vpc_security_group_ids instead.
```

Security Groups should only be used when we do not specify a subnet 

This will fix the problem

Please let me know if it doesn't

Paul

**Comment by orclev** [comment]
That change appears to have fixed this. I hadn't looked at the docs for aws_instance since that resource hadn't changed and it was working previously. Do you know when the vpc_security_group_ids attribute was introduced?

**Comment by stack72** [comment]
Hi @orclev 

this change was introduced in 0.6.15 (looking back at the changelog) - apologies this caused the issue

Paul
