### ISSUE TITLE
Failed to "make" on master branch

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#7866]
### Terraform Version
master branch

### Go Version
go1.6.3 darwin/amd64

### Affected Resource(s)
resource_aws_appautoscaling_policy

### Debug Output
https://gist.github.com/iceycake/6bb8f87b938adfd310cb685bd2534597

### Steps to Reproduce
1. git checkout master
2. make

**Comment by stack72** [comment]
Closed via #7876
