### ISSUE TITLE
core: Optional, Computed attributes cannot be used in ConflictsWith

### ISSUE THREAD

**Issue by spkane** [hashicorp/terraform#7869]
An AWS ELB resource that defines both _availability_zones_ and _subnets_ does not generate and error during `terraform plan` but does generate an error during `terraform apply`
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- aws_elb
### Terraform Configuration Files

``` hcl
resource "aws_elb" "masters_lb" {
  name = "masters-lb"
  availability_zones = ["${var.aws_region}"]
  security_groups = ["${split(",", var.aws_security_group)}"]
  subnets = ["${var.aws_subnet_id}"]
  instances = ["${aws_instance.master.*.id}"]
  cross_zone_load_balancing = false
  idle_timeout = 400
  connection_draining = true
  connection_draining_timeout = 400
...
}
```
### Expected Behavior

I would expect the to see the error during ``terraform plan`
### Actual Behavior

An AWS ELB resource that defines both _availability_zones_ and _subnets_ does not generate and error during `terraform plan` but does generate an error during `terraform apply`
### Steps to Reproduce
1. Create an ELB resource with both _availability_zones_ and _subnets_  defined.
2. `terraform plan`
3. `terraform apply`

**Comment by catsby** [comment]
Hey @spkane – 

the root of this issue is that in our Schemas, attributes that are both `Optional` and `Computed` cannot be used in any `ConflictsWith` statements. 

I'm relabeling this issue to reflect the root problem here, as this isn't particular to AWS ELBs

**Comment by mitchellh** [comment]
Runnable repro:

```
resource "aws_elb" "masters_lb" {
  name = "masters-lb"
  availability_zones = ["us-east-1b"]
  subnets = ["abcd"]

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}
```
