### ISSUE TITLE
aws_ecs_service: iam_role does not handle IAM roles with paths correctly

### ISSUE THREAD

**Issue by ziggythehamster** [hashicorp/terraform#7881]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_ecs_service

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "ecs-scheduler" {
  name = "foo_www_ecs_service_scheduler"
  path = "/foo/bar/"
  assume_role_policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_ecs_service" "foo" {
  name = "foo-service"
  cluster = "XXX"
  task_definition = "XXX"
  desired_count = "1"
  iam_role = "foo/bar/${aws_iam_role.ecs-scheduler.id}"

  load_balancer {
    elb_name = "XXX"
    container_name = "XXX"
    container_port = 80
  }
}
```

### Debug Output
```
-/+ module.www.aws_ecs_service.foo
---snip---
    iam_role:                               "foo" => "foo/bar/foo_www_ecs_service_scheduler" (forces new resource)
---snip---
```

### Expected Behavior
This resource should not be recreated every time you plan.

### Actual Behavior
This resource wants to be updated every time you plan even though there is no change.

### Steps to Reproduce

1. Create the necessary terraform configuration to support the IAM role and ECS service above.
2. `terraform plan` -> `terraform apply` because you initially try to transition from `""` to `"foo/bar/XXX"` and that's fine
3. `terraform plan` again and note that you've got a change because it only picks up the first part of the IAM role instead of the entire thing.

### Important Factoids
This may be caused by a bug in ECS, because it's weird that you have to pass the entire path to the role. But, you do, and then Terraform is probably splitting on `/` and picking the first token, which gets you this result.

This obviously doesn't occur if you use an IAM role with no path set.

**Comment by stack72** [comment]
Hi @ziggythehamster 

thanks for opening the issue here. Luckily, you don't have to specify the path as part of the role :)

When i create the IAM role (as per your config) and then output the ARN (id), I see the following:

```
% terraform apply
provider.aws.region
  The region where AWS operations will take place. Examples


  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: us-west-2

aws_iam_role.ecs-scheduler: Creating...
  arn:                "" => "<computed>"
  assume_role_policy: "" => "{\n  \"Version\": \"2008-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Service\": \"ecs.amazonaws.com\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n"
  name:               "" => "foo_www_ecs_service_scheduler"
  path:               "" => "/foo/bar/"
  unique_id:          "" => "<computed>"
aws_iam_role.ecs-scheduler: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

Outputs:

test = arn:aws:iam::<redacted>:role/foo/bar/foo_www_ecs_service_scheduler
```

Therefore, the ECS service code (for you) just needs to be the following:

```
resource "aws_ecs_service" "foo" {
  name = "foo-service"
  cluster = "XXX"
  task_definition = "XXX"
  desired_count = "1"
  iam_role = "${aws_iam_role.ecs-scheduler.id}"

  load_balancer {
    elb_name = "XXX"
    container_name = "XXX"
    container_port = 80
  }
}
```

Hope this helps

Paul

**Comment by ziggythehamster** [comment]
> Luckily, you don't have to specify the path as part of the role

You actually do. ECS won't see the IAM role unless you specify the path (and then it will complain that it can't become that role and can't create the service). If you create the service in the ECS console, you'll see the role contains the path. I suspect this is a bug in ECS, but Terraform should be doing the right thing here even if ECS isn't.

**Comment by stack72** [comment]
Hi @ziggythehamster 

The ARN for the role already contains the path though:

```
Outputs:

test = arn:aws:iam::<redacted>:role/foo/bar/foo_www_ecs_service_scheduler
```

AFAICT, the ecs_service only requires the ARN and as that ARN already have the path embedded, then it should already work

Is this not the case for you?

**Comment by ziggythehamster** [comment]
I'm not seeing that:

```
    iam_role:                               "foo" => "foo_www_ecs_service_scheduler" (forces new resource)
```

But it should be `foo/bar/foo_www_ecs_service_scheduler` or this happens:

```
module.www.aws_ecs_service.nginx: Creating...
  cluster:                                "" => "arn:aws:ecs:us-east-1:redacted:cluster/foo-www"
  deployment_maximum_percent:             "" => "200"
  deployment_minimum_healthy_percent:     "" => "50"
  desired_count:                          "" => "2"
  iam_role:                               "" => "foo_www_ecs_service_scheduler"
  load_balancer.#:                        "" => "1"
  load_balancer.694440105.container_name: "" => "nginx"
  load_balancer.694440105.container_port: "" => "80"
  load_balancer.694440105.elb_name:       "" => "foo-www-lb"
  name:                                   "" => "foo-nginx"
  task_definition:                        "" => "arn:aws:ecs:us-east-1:redacted:task-definition/foo-nginx:1"
module.www.aws_ecs_service.nginx: Still creating... (10s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (20s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (30s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (40s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (50s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m0s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m10s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m20s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m30s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m40s elapsed)
module.www.aws_ecs_service.nginx: Still creating... (1m50s elapsed)
Error applying plan:

1 error(s) occurred:

* aws_ecs_service.nginx: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.
	status code: 400, request id: 4c8b64a3-58d9-11e6-8e76-df0dd69fc333
```

Of course, it works perfectly if I use `aws_iam_role.ecs-scheduler.arn` instead of `.id`:

```
module.www.aws_ecs_service.nginx: Creating...
  cluster:                                "" => "arn:aws:ecs:us-east-1:redacted:cluster/foo-www"
  deployment_maximum_percent:             "" => "200"
  deployment_minimum_healthy_percent:     "" => "50"
  desired_count:                          "" => "2"
  iam_role:                               "" => "arn:aws:iam::redacted:role/foo/bar/foo_www_ecs_service_scheduler"
  load_balancer.#:                        "" => "1"
  load_balancer.694440105.container_name: "" => "nginx"
  load_balancer.694440105.container_port: "" => "80"
  load_balancer.694440105.elb_name:       "" => "foo-www-lb"
  name:                                   "" => "foo-nginx"
  task_definition:                        "" => "arn:aws:ecs:us-east-1:redacted:task-definition/foo-nginx:1"
module.www.aws_ecs_service.nginx: Creation complete
```

I'll go ahead and leave it at `.arn`. I'm thinking that the docs probably need to mention that `iam_role` can take an ARN and that it's recommended that you pass it an ARN. Maybe make it mandatory to pass an ARN, but that probably hurts semver :).

**Comment by stack72** [comment]
Hi @ziggythehamster 

you are indeed correct - the docs should show this should be ARN not ID. Updating the docs now and will push this straight to the site

Sorry this has caused so many issues for you!

**Comment by stack72** [comment]
Resolved via 9a4c0c24555f1a5dd1127c3b833bc43aeac16fce

**Comment by ziggythehamster** [comment]
@stack72 No worries! This is the first project I've done where it's been Terraformed from the start, so I've begun to use organization features like IAM paths and have found in this case that the way that I had been doing it isn't exactly correct. :) Thanks for the help and for updating the docs!

**Comment by stack72** [comment]
:)
