### ISSUE TITLE
Unknown variables used in interpolation should fail at plan time

### ISSUE THREAD

**Issue by ottumm** [hashicorp/terraform#7888]
Forgetting to include `var.` when using variable interpolation is a common mistake (for me, anyway), and it would be helpful for terraform to catch this at plan time instead waiting apply time.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

Terraform core
### Terraform Configuration Files

``` hcl
variable "foo" { default = "bar" }

resource "template_file" "template" {
    template = <<EOF
${foo}
EOF

    vars {
        foo = "${foo}"
    }
}

output {
    value = "${template_file.template.rendered}"
}
```
### Debug Output

https://gist.github.com/ottumm/22be053bae76dba9dcf5a058032153e9
### Expected Behavior

The `"${foo}` interpolation should fail when `terraform plan` is run, because `foo` is not a valid resource.
### Actual Behavior

`terraform plan` succeeds, and the error is only caught when `terraform apply` is run.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by mitchellh** [comment]
Fixed in 0.8
