### ISSUE TITLE
provider vSphere lazy disk type support and consistency in type specifiers

### ISSUE THREAD

**Issue by sputnik13** [hashicorp/terraform#7897]
vSphere virtual disk and virtual machine resources do not support specification of a thick lazy zeroed disk type, only "thin" and "eager_zero" are supported in virtual machine resource and "thin" and "eagerZeroedThick" are supported in the virtual disk resource.

The type specifier for these two resources should be consistent.  These two resources should also support a thick lazy zeroed disk type.

Users want to be able to specifi thick provisioned disks without the time penalty of an eager zeroed disk (which would need to zero the entire disk before it's made available).

**Comment by dkalleg** [comment]
@sputnik13 This can be closed since https://github.com/hashicorp/terraform/pull/7916 merged.
