### ISSUE TITLE
core: modify log output for unit tests

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#7898]
The main terraform binary captures and filters all log output according to the log level, but when running unit tests the log output is unfiltered. 

It would be useful to be able to set output levels during tests in the same manner as the main program (even if that method were to change in the future).

**Comment by kwilczynski** [comment]
@jbardin I use the `TF_LOG` environment variable for this.

**Comment by jbardin** [comment]
@kwilczynski: That's OK when it works, but log output isn't filtered or redirected when running unit tests in core packages.
