### ISSUE TITLE
Feature Request for "MFA Delete" on S3 buckets

### ISSUE THREAD

**Issue by LeslieCarr** [hashicorp/terraform#7902]
Hello! 

This is a feature request.  I'm using Terraform version v0.6.16 and would like to be able to set "MFA Delete" on S3 buckets ( as described in https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html#MultiFactorAuthenticationDelete )
### Terraform Version

v0.6.16
### Affected Resource(s)
- aws_s3_bucket

**Comment by jen20** [comment]
Hi @LeslieCarr! I didn't release that was an option on the API, but I think it's a good idea to add this. It will likely prevent Terraform destroying the bucket (which is probably the aim here) unless you are operating under an assumed role which was authorised with MFA. However, we are no longer back porting new features to the 0.6.x series of releases, so this will likely appear in the 0.7.x series. Thanks for bringing this to our attention!
