### ISSUE TITLE
It seems d.GetOk() now returns `true`, even if the value is not given but is computed

### ISSUE THREAD

**Issue by svanharmelen** [hashicorp/terraform#791]
I would think this has something to do with the changes in the helper package, but just noticed it when running the ACC tests... Will have a closer look later today.

**Comment by mitchellh** [comment]
@svanharmelen I'll take a look since its likely to do with my crazy `helper/schema` refactor awhile back. Thanks for pointing this out. I'll add tests!

**Comment by mitchellh** [comment]
@svanharmelen So actually there are tests. So it might just be in a specific case/type. Can you try to get `TestResourceDataGetOk` to fail?

**Comment by svanharmelen** [comment]
@mitchellh sure, will have a closer look at the exact cause in a hour or two when I'm back behind my desk...

**Comment by svanharmelen** [comment]
@mitchellh: Just added a test in PR #796 The tests is successful when running with commit 47f02f80bca83ebde01959be840de800fc639a04 from about 7 days ago, but fails on master...

**Comment by mitchellh** [comment]
Fixed: https://github.com/hashicorp/terraform/commit/db02541d31e873ccf675ae65d49aa903db250585
