### ISSUE TITLE
Request: Sign the releases

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#7918]
Hi!

I'm currently packaging terraform for arch linux. Could you pgp-sign the releases and/or the associated tarball? example: `git tag -sm "Release 0.7.0" 0.7.0` will produce a signed tag.

**Comment by phinze** [comment]
Hi @jleclanche - the tag is signed with the official HashiCorp PGP Key available here:

https://www.hashicorp.com/security.html

The release binaries are signed as well via their checksums. See the section on "Checksum Verification" in the link above for details.

I hope this helps! Let me know if you have further questions.

**Comment by jleclanche** [comment]
@phinze Oh! I didn't realize the tag was signed; the github UI shows it as "unverified" because the PGP key isn't linked to the account:

https://github.com/hashicorp/terraform/releases

**Comment by phinze** [comment]
Yeah - GitHub does not support organization-level PGP keys just yet, only per-user. We have an outstanding request to them for this feature, so we have high hopes that this will be resolved soon!
