### ISSUE TITLE
Usage of $(CURDIR) in Makefile makes shadow builds impossible

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#7920]
Continuing packaging terraform, trying to do a shadow build (a build in a different directory) for terraform breaks due to usage of `$(CURDIR)` in the Makefile.

Reproduce with `mkdir ~/temp-terraform; cd ~/temp-terraform; make bin -f ~/real-terraform-folder/Makefile`

I recommend setting the following at the top of the makefile and using `$(BASE_DIR)` instead of `$(CURDIR)` wherever it occurs:

```make
MAKEFILE := $(lastword $(MAKEFILE_LIST))
BASE_DIR := $(realpath $(dir $(MAKEFILE)))
```

**Comment by jleclanche** [comment]
`gofmtcheck.sh` also needs to be changed not to use `find .`. Similarly, you can set a `BASEDIR` variable with the value `$(readlink -f $(dirname $0))` and use `find $BASEDIR/../../` (as the basedir would be the scripts dir).

**Comment by jleclanche** [comment]
Ok it looks like shadow builds won't be possible at the moment due to other issues in the vendor dependencies. Shame. I'll PR the changes here, it's better than nothing.

**Comment by jen20** [comment]
As per #7922, we can't really deal with this issue in a portable manner right now. Consequently I'm going to close this issue until such time as there is a more portable proposal. Thanks for opening an issue - sorry we can't be of more assistance right now.
