### ISSUE TITLE
Keys in a map need to be explicitly declared

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#7924]
I'm not sure if this is intentional or a regression, but we came across this issue whilst upgrading to Terraform 0.7. It seems that keys in a `map` variable now need to be explicitly declared. For example:

```
variable "foo" {
  type    = "map"
  default = {
    bar = ""
  }
}

resource "null_resource" "test" {
  provisioner "local-exec" {
    inline = "echo ${var.foo["baz"]}"
  }
}
```

In Terraform 0.6.16, this code snippet worked fine if `var.foo.baz` was defined in a `variables.tfvars.json` file, but in Terraform 0.7 this produces an error:

```
Errors:

  * key "baz" does not exist in map var.foo in:

echo ${var.foo["baz"]}
```

**Comment by phinze** [comment]
Hi @joshuaspence - thanks for the report.

This behavior is definitely intentional for the square brackets. I'll think on this a little bit more to see if there's a different way we want to handle this.

In the meantime, the three argument variant of the `lookup()` function should do the trick, provided you're using flat maps (no nested maps/lists).

```tf
variable "foo" {
  type    = "map"
  default = {
    bar = ""
  }
}

resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "echo ${lookup(var.foo, "baz", "")}"
  }
}
```

**Comment by joshuaspence** [comment]
It's only somewhat related, but it would be nice to be able to specify a `default` value on the `map` itself rather than needing to pass a third parameter to the `lookup` function. Something like this:

    variable "counts" {
      type          = "map"
      default_value = 1
      default       = {
        a = 2
      }
    }

**Comment by mitchellh** [comment]
Hey there, 

The original issue here is definitely the intended behavior and should fail. I agree with @joshuaspence that a default value option would be great to have. Do you mind opening a new issue to track that and we'll tag for enhancement? Thanks!

**Comment by apparentlymart** [comment]
I think that enhancement suggestion is the same thing as is already captured in #2312.
