### ISSUE TITLE
Homebrew formula stuck on v0.6.16

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#7925]
The [brew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb) has not yet been updated for v0.7

**Comment by phinze** [comment]
Hi @OJFord - we don't officially maintain that distribution mechanism. You're welcome to open an issue on their side if you like. 👍

**Comment by phinze** [comment]
(p.s. homebrew-cask distributes the binaries instead of compiling, and it [has 0.7](https://github.com/caskroom/homebrew-cask/pull/23370))
