### ISSUE TITLE
Update bundled examples to showcase 0.7.x features

### ISSUE THREAD

**Issue by kwilczynski** [hashicorp/terraform#7929]
The [examples](https://github.com/hashicorp/terraform/tree/master/examples) directory content is referenced often as a source of invaluable examples on how to get started and use Terraform correctly, same goes for [hashicorp/best-practices](https://github.com/hashicorp/best-practices/tree/master/terraform).

It would be a nice touch to update these example so that they include a showcase of new features and/or changes introduced in 0.7.x family.

Code can also be documentation, and a lot can be learned from a nice set of useful code snippets.

**Comment by jen20** [comment]
Hi @kwilczynski! I agree this is necessary - we'll look at updating this, and the best practices repository in the near future.

**Comment by kwilczynski** [comment]
Closing as Terraform moved far beyond 0.7 now.
