### ISSUE TITLE
Encryption for Variables

### ISSUE THREAD

**Issue by lcacciagioni** [hashicorp/terraform#7935]
I want to know if there is any plan to support native encryption? (Like [ansible vault](http://docs.ansible.com/ansible/playbooks_vault.html)). This can be great for storing passwords and sensitive data alongside code.

**Comment by jen20** [comment]
Hi @lcacciagioni! Currently there is no timeframe for supporting this - any encryption will likely be via [HashiCorp Vault](https://vaultproject.io). There is work underway for this which will continue now that Terraform 0.7 is released, so I'll go ahead and close this issue for now.

**Comment by lcacciagioni** [comment]
Wow that was fast!!! Thanks for the answer man!!! and continue with this great work!!!
