### ISSUE TITLE
Add support apply for custom authorizers to AWS API Gateway methods

### ISSUE THREAD

**Issue by swestcott** [hashicorp/terraform#7936]
As noted on [issue 3675](https://github.com/hashicorp/terraform/issues/3675#issuecomment-207123704), custom authorizers for API Gateway cannot be applied to methods.

According to the [API Gateway docs](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-method.html) when authorization-type is set to CUSTOM, the authorizer-id must be supplied. Terraform only accepts the [authorization-type parameter](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_api_gateway_method.go#L84)

**Comment by zanona** [comment]
Agreed, the documentation is certainly misleading unfortunately.

**Comment by zanona** [comment]
`authorization_type: CUSTOM` and `authorizer_id` have been added to master https://github.com/hashicorp/terraform/commit/cc38378870a9a99d07802c52c980ef05b8db1139 now based on https://github.com/hashicorp/terraform/pull/8535 should be released soon 👌
