### ISSUE TITLE
aws_internet_gateway does not support the name key

### ISSUE THREAD

**Issue by noahwhite** [hashicorp/terraform#7942]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_internet_gateway

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_internet_gateway" "internet_gw" {
  vpc_id = "${aws_vpc.foo-bar-vpc.id}"
  name = "Foo bar Internet GW"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Internet gateway should have been provisioned with the **name** tag

### Actual Behavior
What actually happened?

Errors:

  * aws_internet_gateway.internet_gw: : invalid or unknown key: name

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Nothing atypical.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 

Not that I know of. A quick search did not turn any up.

**Comment by jen20** [comment]
Hi @noahwhite! Thanks for opening an issue. Tags must be defined within a map block for most AWS resources where naming is not explicitly supported (sometimes hidden by the UI, but revealed by looking at the underlying API) - as per the documentation for `aws_internet_gateway` resources, the correct formatting for the resource is:

```
resource "aws_internet_gateway" "internet_gw" {
  vpc_id = "${aws_vpc.foo-bar-vpc.id}"

  tags {
    Name = "Foo bar Internet GW"
  }
}
```

**Comment by noahwhite** [comment]
Yes I just realized I dorked up my tag defin, but you beat me to closing this. bleh. Sorry for the time sync.
