### ISSUE TITLE
v0.7.0 now breaks how variables are called.

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#7953]
Error

Error reading config for 
aws_instance[CI03T02QSLRS]: Invalid dot index found: 'var.ami.Ubuntu12.04'. Values in maps and lists can be 
referenced using square bracket indexing, like: 'var.mymap["key"]' or 'var.mylist[1]'. in:
At line:1 char:1
+ terraform plan
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([31mError load...mylist[1]'. in::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
${var.ami.Ubuntu12.04}[0m[0m

Resource

resource "aws_instance" "CI03T02QSLRS" {
  count             = 2
  ami               = "${var.ami.Ubuntu12.04}"
  availability_zone = "${var.availability_zone.AZb}"
  key_name          = "${var.aws_key_name}"
  instance_type     = "r3.large"

  vpc_security_group_ids = ["sg-1b7f7e7f", "sg-e47f7e80", "sg-e57f7e81", "${module.ci_slrs_sg.CI_SLRS_SG_ID}"]

  subnet_id            = "${var.subnet_private}"
  iam_instance_profile = "S3-SSI-ISO-RO-ACCESS"

 

Variable map

variable "ami" {

  default = {
    Server2k12R2 = "ami-4653db35"
    Server2k8R2  = "ami-4f1ca23c"
    Ubuntu12.04  = "ami-9f15aeec"
    Ubuntu14.04  = "ami-f95ef58a"
    Ubuntu16.04  = "ami-0ae77879"
  }
}

**Comment by davyt10** [comment]
Fix is to call var as

ami = "${var.ami["Ubuntu12.04"]}"

**Comment by chiefy** [comment]
@phinze is this documented anywhere? it's a breaking change, had to revert back to `0.6.16` this morning.

**Comment by jrnt30** [comment]
@chiefy In the "BACKWARDS INCOMPATIBILITIES / NOTES" section of https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md for 0.7.0 it is

**Comment by chiefy** [comment]
@jrnt30 I'm talking more about the web docs, no mention that I see of the new bracket format in the map type docs?
