### ISSUE TITLE
Resource 'aws_elasticache_cluster.redis' does not have attribute 'cache_nodes.*.address' for variable 'aws_elasticache_cluster.redis.cache_nodes.*.address'

### ISSUE THREAD

**Issue by iroller** [hashicorp/terraform#7957]
### Terraform Version

`0.7.0`
### Affected Resource(s)
- aws_elasticache_cluster
- module outputs
### Terraform Configuration Files

``` hcl

## Module
resource "aws_elasticache_cluster" "redis" {
  engine               = "redis"
...
}

// Addresses
output "addresses" {
  value = "${join(",", aws_elasticache_cluster.redis.cache_nodes.*.address)}"
}


## Using module
module "redis" {
...
}

output "redis_endpoint_addresses" {
  value = "${module.redis.addresses}"
}
```
### Debug Output

```
[WARN] Output interpolation "addresses" failed: Resource 'aws_elasticache_cluster.redis' does not have attribute 'cache_nodes.*.address' for variable 'aws_elasticache_cluster.redis.cache_nodes.*.address'
```
### Expected Behavior

I expected a string outout, e.g. "10.10.0.1,10.10.0.2"
### Actual Behavior

No output at all.
### References
- https://github.com/hashicorp/terraform/issues/4703 - similar, but not sure if it's the same issue

**Comment by iroller** [comment]
The same happens when using memcached engine:
```
"${formatlist("%s:%s", aws_elasticache_cluster.memcached.cache_nodes.*.address, aws_elasticache_cluster.memcached.cache_nodes.*.port)}"

^^gives no output
```

**Comment by sumerman** [comment]
I had the same issue with my plugin and [this is](https://github.com/sumerman/terraform-provider-awsx/commit/28a8b9be2cf909f0abe87b9279d4e33ce1f26534) my workaround. The way I made it work leads me to believe that there is an issue with nested computed attributes in `core`.

**Comment by sumerman** [comment]
I believe this issue is related to #7241 and #3679
