### ISSUE TITLE
vSphere: mock framework for unit tests ?

### ISSUE THREAD

**Issue by ChloeTigre** [hashicorp/terraform#7973]
Hello,

I'm a contributor to the vSphere provider. I can perform tests on my work environment however I have no idea how it runs in the CI env on Github.

Ideally I'd love to get a mock framework so we could just run them without the costly env (and implications).

Anyone interested in contributing such a module? I have checked what's around and noticed the SimDK project but it seems unmaintained as of today and only supports the 4.x branch of the vSphere API. Any hints?

**Comment by ringods** [comment]
@ChloeTigre I have been looking at this myself and found this:
https://dantehranian.wordpress.com/2014/07/08/vagrant-vmware-vcenter-simulator/
https://github.com/tehranian/vagrant-vcenter-simulator

This is a real vCenter running in simulator mode.
http://www.virtuallyghetto.com/2012/12/vcenter-server-simulator.html
http://www.virtuallyghetto.com/2013/09/new-vcenter-server-simulator-20.html
http://www.shogan.co.uk/vmware/working-with-the-vcenter-server-simulator-configuring-custom-esxi-hosts/

I'm trying to find time to test this setup...

**Comment by mitchellh** [comment]
We're working on setting up a test vSphere cluster as well. Unfortunately we prefer not to mock for our acceptance test suite.
