### ISSUE TITLE
docker_container isn't updated when updating docker_image referenced by it

### ISSUE THREAD

**Issue by patresi** [hashicorp/terraform#7974]
### Terraform Version
0.7.0

### Affected Resource(s)
- docker_image
- docker_container

### Terraform Configuration Files
```hcl
provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_image" "mongo" {
  name = "mongo:2.6"
}

resource "docker_container" "mongo" {
  image = "${docker_image.mongo.latest}"
  name  = "mongo"
}
```

```hcl
provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_image" "mongo" {
  name = "mongo:3.2"
}

resource "docker_container" "mongo" {
  image = "${docker_image.mongo.latest}"
  name  = "mongo"
}
```

### Expected Behavior
When running `terraform plan` with the first configuration and the with the second configuration, terraform should plan to update both the image and the container.

### Actual Behavior
After applying the first configuration, changing it to the second and running `terraform plan` only generates an update to the `docker_image` resource. After doing a `terraform apply` followed by another `terraform plan` will then generate the plan to update the `docker_container` resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. Update configuration to the second example
4. `terraform plan`
5. `terraform apply`
6. `terraform plan`
7. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @patresi!

As of Docker 0.7.0 there is a new pattern for this that I believe will resolve the problem you're seeing:

```hcl
provider "docker" {
  host = "unix:///var/run/docker.sock"
}

data "docker_registry_image" "mongo" {
  name = "mongo:2.6"
}

resource "docker_image" "mongo" {
  name         = "${data.docker_registry_image.mongo.name}"
  pull_trigger = "${data.docker_registry_image.mongo.sha256_digest}"
}

resource "docker_container" "mongo" {
  image = "${docker_image.mongo.latest}"
  name  = "mongo"
}
```

The introduction of the `docker_registry_image` data resource into the mix means that Terraform is able to detect before `plan` that a new version of the image is available, which then allows the plan to include both the update of the `docker_image` resource and in turn the update of the `docker_container`.

In this pattern, the roles of the different resources are as follows:

* `data.docker_registry_image.mongo`: determines the sha256 digest corresponding to the tag `mongo:2.6`, refreshing this result each time `terraform refresh` is run, or we implicitly refresh during `terraform plan`.
* `docker_image.mongo`: actually retrieves the discovered image from the registry and adds it to the local image cache. If `pull_trigger` changes it will re-fetch into the local cache.
* `docker_container.mongo`: creates a docker container using the cached copy of the image that was created by `docker_image.mongo`.

Could you give that a try and let me know if it solves your problem?

Thanks!

**Comment by patresi** [comment]
Hello @apparentlymart  and thank you for the quick response!

I can inform you that yes, this solves it for this case! 👍 

Unfortunately `docker_registry_image` this only works for "(...) public images from the official Docker Hub Registry." 😞 

Is there a timeline on when it will support other docker registries?

Thank you once again!

**Comment by apparentlymart** [comment]
I believe #7949 is at least a step in that direction; the intent here was to make small steps so we could get the simple case (public only) working first and then iteratively address more complex use-cases like private registries, etc, but there isn't any specific timeline for this.
