### ISSUE TITLE
Garbage output with `terraform plan -out`

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#7976]
`terraform plan -out=out.tfstate` produces garbage output in the out file. This makes future use of the file (with `terraform plan -out` or `terraform apply -state`) unusable.

### Terraform Version
0.7

### Affected Resource(s)
core

### Terraform Configuration Files
This is reproducible with any configuration, e.g. `resource "null_resource" "dummy" {}`

### Debug Output
`plan` succeeds and produces normal output to the console.

Example of resulting out file with the above config:
https://gist.github.com/ajcrites/f0aa95114dac6aaa67c47c33b789710f

### Expected Behavior
`out` files should be usable by future `terraform plan` and `terraform apply`.

### Actual Behavior
Garbage in the out file prevents using it for other terraform commands.

### Steps to Reproduce
Run `terraform plan` with the config above

**Comment by apparentlymart** [comment]
Hi @ajcrites. Sorry for the problems here.

Could you share what error/result you get from `terraform apply planfile` when using the plan file that was generated? This would be helpful to understand what's going on here.

Thanks for this report!

**Comment by phinze** [comment]
Hi @ajcrites - the `-out` parameter generates a binary execution plan. This plan file can then be provided as an argument to `apply` to establish a contract between the reviewed plan and what actually happens during terraform apply.

Here's an example of usage. Given config:

```tf
resource "null_resource" "foo" {}
```

If you run:

```
terraform plan -out example.tfplan
```

You'll see as part of the output message:

```
Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: example.tfplan
```

You can then run:

```
terraform apply example.tfplan
```

This executes the plan and will bail if anything in the environment changed since the planfile was generated that might invalidate the plan.

I hope this helps to clarify! Let me know if you have any further questions on this.

**Comment by ssubraman224** [comment]
I will be unable to provide you the complete logs, But would like to let  you know that we are not able to execute the script from within the  private network. It works fine with public network. I have placed the provider plugins - aws in the following path : ~/. terraform.d/plugins/linux_amd64

Terraform init was successful.

But terraform plan didn't execute, it was in an infinite loop.
If we open the right ports for the endpoints, we should be able to execute the scripts successfully.Is what we believe could you please tell us what the endpoints and ports that our firewall is to open for?

[TRACE] dag/walk: vertex "xx", waiting for: "meta.count-boundary (count boundary fixup)"
[TRACE] dag/walk: vertex "aws_network_interface.xx", waiting for: "provider.aws"
 [TRACE] dag/walk: vertex "aws_network_interface.xx", waiting for: "provider.aws"

it fails and repeats the steps again and again.

**Comment by ssubraman224** [comment]
@mildwonkey right, wrong window... typed here by mistake. thanks for notifying.
