### ISSUE TITLE
Unexpected variable interpolation in v0.7.

### ISSUE THREAD

**Issue by carrete** [hashicorp/terraform#7981]
Pre v0.7 something like `terraform apply -var aws_secret_key=1234abcdef` worked. With v0.7, because it seems that the variable starts with a number, terraform tries to turn this variable into an actual number, which fails of course. Adding `type = "string"` to the variable definition didn't help. I had to add escaped quotes, like `terraform apply -var aws_secret_key=\"1234abcdef\"`.

**Comment by SoMuchToGrok** [comment]
Related [issue 7962](https://github.com/hashicorp/terraform/issues/7962).

**Comment by phinze** [comment]
Yep closing as dup of #7962 - #7977 landing shortly!
