### ISSUE TITLE
CLI subcommands prob

### ISSUE THREAD

**Issue by robrankin** [hashicorp/terraform#7983]
Terraform subcommands with parameters will still run if theres a space missing.  Example:

`terraform destroy-target=<module>`

Space missing between `destroy` and `-target=<module>`

You'd expect this to error out, but instead:

```
[robrankin@host]$ terraform destroy-target=<module>
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes
```

If you don't look carefully you can miss the fact that its going to destroy all the resources, not just the module targeted.

If you then tell it yes, it will proceed to nuke the world.

### Terraform Version
`Terraform v0.7.0-dev (bad37a57cbea29d96753750bf95f23241f520681)`

### Affected Resource(s)
Subcommands

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Terraform should have exited as the command line params/subcommand was incorrect, as it was missing a space between the `destroy` subcommand and `-target` parameters

### Actual Behavior
Terraform proceeded to destroy all resources in the current state.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy-target=<module>`

### Important Factoids
N/A

### References
N/A

**Comment by kwilczynski** [comment]
This has indeed changed from 0.6.x to 0.7.x, as per:

* v0.6.16

```
$ /usr/local/bin/terraform version123
usage: terraform [--version] [--help] <command> [<args>]

Available commands are:
    apply       Builds or changes infrastructure
    destroy     Destroy Terraform-managed infrastructure
    fmt         Rewrites config files to canonical format
    get         Download and install modules for the configuration
    graph       Create a visual graph of Terraform resources
    init        Initializes Terraform configuration from a module
    output      Read an output from a state file
    plan        Generate and show an execution plan
    push        Upload this Terraform module to Atlas to run
    refresh     Update local state file against real resources
    remote      Configure remote state storage
    show        Inspect Terraform state or plan
    taint       Manually mark a resource for recreation
    untaint     Manually unmark a resource as tainted
    validate    Validates the Terraform files
    version     Prints the Terraform version
```

* v0.7.0 (from master)

```
$ ./pkg/darwin_amd64/terraform version123
Terraform v0.7.0-dev (6d927a40db1f46dd7d840d884af9ce8d7ec14931+CHANGES)

Your version of Terraform is out of date! The latest version
is 0.7.0. You can update by downloading from www.terraform.io
```

**Comment by mitchellh** [comment]
Fixed here: https://github.com/mitchellh/cli/pull/40

Once reviewed and merged will update the deps for Terraform and will be fixed.
