### ISSUE TITLE
google_compute_instance service_account

### ISSUE THREAD

**Issue by lesaux** [hashicorp/terraform#7985]
How can I assign a service_account (not scopes to the default compute engine service account) to a google_compute_instance. It seems this feature has been removed?

**Comment by phinze** [comment]
Not sure on this one offhand. @lwander or @evandbrown - you in the neighborhood to be able to comment here?

**Comment by evandbrown** [comment]
@lesaux, I'm not sure if non-default service accounts were ever supported, but I'll look into adding them now.

**Comment by lwander** [comment]
@lesaux you can use the email field, I believe: https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance.go#L257

Let me know if that works.

**Comment by evandbrown** [comment]
@lwander email can't be set as it's computed (maybe computed fields were settable previously?)

I'm testing a patch that fixes this and will submit a PR shortly.

**Comment by evandbrown** [comment]
@lesaux You should be set. #7991 will allow you to specify a custom service account in the `email` field. Thanks for raising this issue, especially as it's motivated me to get to work on the IAM resources :)

**Comment by lesaux** [comment]
@evandbrown Thanks a lot for you quick update! I will test this tomorrow morning. Looking forward  to more IAM resources!!
