### ISSUE TITLE
Issue with count and aws_instance

### ISSUE THREAD

**Issue by joshgarnett** [hashicorp/terraform#7987]
While trying to spin up 3 servers of the same type, I ran into the following error:

```
Error applying plan:

1 error(s) occurred:

* aws_instance.server.2: Error launching source instance: timeout while waiting for state to become 'success'. last error: %!s(<nil>)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This failed on a subsequent apply with the same failure.  When I set TF_LOG=DEBUG it actually worked.

**Comment by phinze** [comment]
Hi @joshgarnett, thanks for the report.

Does it consistently fail without `TF_LOG=debug` and pass with it? That's going to make it tough to track down!

If it is a timing issue, you can try also adding `TF_LOG_PATH=/tmp/tfdebug.log` to move the debug logging into a file, which might speed up the timing enough for you to reproduce and get a debug log for us to look at.

**Comment by joshgarnett** [comment]
I'll give that a try in a bit and see if I can track it down.

**Comment by joshgarnett** [comment]
I'm going to close this out, since I'm having trouble duplicating it after a destroy.   I'll keep an eye out though for similar issues.

**Comment by eyalzek** [comment]
I got the following error a few times:
```
Error applying plan:

1 error(s) occurred:

* aws_instance.monitor: Error launching source instance: timeout while waiting for state to become 'success'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Turned out to be because I was trying to start it on a region and availability zone which was full and didn't have more room for T2 instances.

**Comment by NicolasMas** [comment]
@eyalzek how did you come to that conclusion?

> Turned out to be because I was trying to start it on a region and availability zone which was full and didn't have more room for T2 instances.

Am having the same error, but I can't relate it to anything.

**Comment by eyalzek** [comment]
@NicolasMas I tried doing so through the aws console and got those errors... When I tried starting the instances on another zone (b instead of a) it worked as expected.

**Comment by NicolasMas** [comment]
Hum. Ok. I am honestly having a hard time to think an AZ could run out of instances. Which zone where you on?

**Comment by eyalzek** [comment]
Yeah, but it actually does ;) In this case it's `eu-central-1` (Frankfurt).

**Comment by NicolasMas** [comment]
Will look at that. My case would be `ap-southeast-1a`

**Comment by nh2** [comment]
> I am honestly having a hard time to think an AZ could run out of instances.

This seems to be exactly what's happening: https://github.com/hashicorp/terraform/issues/9450#issuecomment-259892660
