### ISSUE TITLE
alreadyExists error on google_compute_instance with existing disk

### ISSUE THREAD

**Issue by mikudeko** [hashicorp/terraform#7998]
### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
`google_compute_instance`

### Terraform Configuration Files
```hcl
resource "google_compute_disk" "storage" {
  name  = "storage"
  type  = "pd-ssd"
  zone  = "us-central1-c"
  size = "100"
}


resource "google_compute_instance" "storage" {
  name         = "storage"
  machine_type = "n1-highmem-2"
  zone         = "us-central1-c"

  depends_on = [
    "google_compute_disk.storage"
  ]

  disk {
    image = "debian-8-jessie-v20160718"
    size = "10"
  }

  disk {
    disk = "storage"
    auto_delete = "0"
  }

  network_interface {
    network = "default"
  }
}
```

### Debug Output
https://gist.github.com/mikudeko/f68653cd14bcf3f918b4ed5e700189f4

### Panic Output
No panic.

### Expected Behavior
The resource using the already existing disk, wether it is managed by  `google_compute_disk` or manually. 

### Actual Behavior
Apply stops with the resource returning an `alreadyExists` error.

### Steps to Reproduce
1. `terraform apply` of the above config.

**Comment by simontesar** [comment]
Of course GCE names the boot disk after the instances name and I can't create another disk with the same name. Please excuse the ticket, I've wasted two days on this.

**Comment by mikudeko** [comment]
Of course GCE names the boot disk after the instances name and I can't create another disk with the same name. Please excuse the ticket, I've wasted two days on this.

**Comment by stack72** [comment]
Hi @mikudeko 

Sorry this has caused you some issues here - is this a ticket we can close or is this a bug you need looked at? The follow up comment isn't very clear

Thanks

Paul

**Comment by mikudeko** [comment]
The ticket can be closed - thank you.
