### ISSUE TITLE
aws_spot_fleet_request: panic on a minimal configuration

### ISSUE THREAD

**Issue by laggyluke** [hashicorp/terraform#8000]
### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
- aws_spot_fleet_request

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_spot_fleet_request" "test" {
  iam_fleet_role  = "test"
  spot_price      = "0.10"
  target_capacity = 1

  launch_specification {
    instance_type = "c3.large"
    ami           = "ami-98e114f8"
  }
}
```

### Debug Output
https://gist.github.com/laggyluke/93ab4e4f00e2259040514a9606738412

### Panic Output
https://gist.github.com/laggyluke/d7339509497f6ec76f37beff26e7aa0e

### Expected Behavior
No crash.

### Actual Behavior
Crash on both `terraform plan` and `terraform apply`.

### Steps to Reproduce
Using the above configuration, run `terraform plan`.

### Important Factoids
Not sure if this is relevant, but I discovered this while trying to create a spot feet request that launches instances in a default VPC, without explicitly specifying AZs / subnets.
Then I've tried to remove all non-required fields to get a minimal test case until I ended up with the above config.

### References
- GH-7243 - original PR that added `aws_spot_fleet_request` resource

**Comment by webdestroya** [comment]
It shouldn't panic and crash, but I got this same problem, the solution is to specify a `subnet_id` or `availability_zone`

```
2016/08/05 09:35:33 [DEBUG] plugin: terraform: panic: Must set one of:
2016/08/05 09:35:33 [DEBUG] plugin: terraform: availability_zone ""
2016/08/05 09:35:33 [DEBUG] plugin: terraform: subnet_id: ""
```

**Comment by stack72** [comment]
Hi @laggyluke and @webdestroya 

Thanks for the bug report and showing the fix. This is something that we should gracefully error out on. I will add a fix to this now

Paul
