### ISSUE TITLE
google provider does not support to set private ip while creating instance

### ISSUE THREAD

**Issue by syed2** [hashicorp/terraform#8006]
Hi,

Issue: google provider does not support to set private ip while creating instance

$ /opt/terrafrom2/terraform -v
Terraform v0.7.0

### Snippet from tf config ###
```
network_interface {
    network = "default"
    address = "10.128.0.55"
    access_config {
      # Ephemeral
      nat_ip = "${google_compute_address.default.address}"
    }
  }
```

$ /opt/terrafrom2/terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * google_compute_instance.guest2: "network_interface.0.address": this field cannot be set

=========
As per GCE API

To create an instance with a static internal IP address, use the Compute Engine API. Make a request to create a new instance, as you would normally but explicitly provide the networkInterfaces[].networkIP property with the internal IP you want to use. For example:
```
{
  "name": "[INSTANCE_NAME]",
  "machineType": "zones/us-central1-f/machineTypes/f1-micro"
  "networkInterfaces": [{
    "accessConfigs": [{
      "type": "ONE_TO_ONE_NAT",
      "name": "External NAT",
     }],
    "network": "global/networks/default",
    "networkIP": [IP_ADDRESS]
  }],
  "disks": [{
     "autoDelete": "true",
     "boot": "true",
     "type": "PERSISTENT",
     "initializeParams": {
        "sourceImage": "projects/debian-cloud/global/images/v20150818"
     }
   }]
 }
```

**Comment by radeksimko** [comment]
Hi @syed2 
I believe https://github.com/hashicorp/terraform/pull/6310 implemented what you're asking for, that patch will be available in the next release (0.7.1) and you should be able to just use the same tf config as you mentioned above.
