### ISSUE TITLE
"Unexpected EOF" and "connection is shut down" with Cloudflare provider 

### ISSUE THREAD

**Issue by catufunwa** [hashicorp/terraform#8011]
Hi there,

### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
cloudflare_record

### Debug Output
`* cloudflare_record.sql_redis_sessions_internal: unexpected EOF
2016/08/05 13:37:45 [DEBUG] vertex provider.aws.main (close), got dep: aws_autoscaling_group.ftp_sftp
2016/08/05 13:37:45 [DEBUG] vertex provider.aws.main (close), got dep: aws_security_group.cfg

....

2016/08/05 13:37:45 [DEBUG] vertex provider.aws.main (close), got dep: aws_route_table_association.private_route_table_mon1
2016/08/05 13:37:45 [DEBUG] vertex provider.aws.main (close), got dep: aws_se* cloudflare_record.ssh_bastion_public: connection is shut down
curity_group.prx_elb
`

### Expected Behavior
Terraform should report or execute the plan for cloudflare_records

### Actual Behavior
Any cloudflare_record throws either a "Unexpected EOF" and "connection is shut down" error.

### Steps to Reproduce
1. `terraform plan` or `terraform apply`

**Comment by jen20** [comment]
Hi @catufunwa! I can't reproduce this - normally the `connection shut down` and `Unexpected EOF` are the result of the provider crashing, and there will be a more detailed log. Do you have any additional output you can share, or a configuration which demonstrates the problem? Our acceptance tests for CloudFlare have been passing each night, so I'm fairly confident this is an edge case which should be easy enough to clear up once reproduced. Thanks!

**Comment by catufunwa** [comment]
I think I have something for you @jen20. 

`
2016/08/09 12:03:50 [DEBUG] plugin: terraform: fatal error: concurrent map writes
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 
2016/08/09 12:03:50 [DEBUG] plugin: terraform: goroutine 90 [running]:
2016/08/09 12:03:50 [DEBUG] plugin: terraform: runtime.throw(0x3ae7f10, 0x15)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:547 +0x90 fp=0xc820455118 sp=0xc820455100
2016/08/09 12:03:50 [DEBUG] plugin: terraform: runtime.mapassign1(0x339b820, 0xc8203b1dd0, 0xc8204551e0, 0xc8204551f0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8204551c0 sp=0xc820455118
2016/08/09 12:03:50 [DEBUG] plugin: terraform: net/textproto.MIMEHeader.Set(0xc8203b1dd0, 0x3808840, 0xa, 0xc8203b1c20, 0x25)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/net/textproto/header.go:22 +0xc2 fp=0xc820455210 sp=0xc8204551c0
2016/08/09 12:03:50 [DEBUG] plugin: terraform: net/http.Header.Set(0xc8203b1dd0, 0x3808840, 0xa, 0xc8203b1c20, 0x25)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/net/http/header.go:31 +0x49 fp=0xc820455240 sp=0xc820455210
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go.(*API).request(0xc820441040, 0x37c4da0, 0x3, 0xc8203f7740, 0x54, 0x0, 0x0, 0x3, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go/cloudflare.go:123 +0x190 fp=0xc8204552a8 sp=0xc820455240
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go.(*API).makeRequest(0xc820441040, 0x37c4da0, 0x3, 0xc8203f7740, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go/cloudflare.go:83 +0x225 fp=0xc820455420 sp=0xc8204552a8
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go.(*API).DNSRecord(0xc820441040, 0xc820559ea0, 0x20, 0xc8201afa00, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/cloudflare/cloudflare-go/dns.go:70 +0x10a fp=0xc8204555c8 sp=0xc820455420
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/cloudflare.resourceCloudFlareRecordRead(0xc8203f6f00, 0x377ac20, 0xc820441040, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/cloudflare/resource_cloudflare_record.go:128 +0x39c fp=0xc820455858 sp=0xc8204555c8
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc8203a69c0, 0xc820443180, 0x377ac20, 0xc820441040, 0xc8203a88a8, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0x432 fp=0xc820455928 sp=0xc820455858
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc8203b12f0, 0xc820443140, 0xc820443180, 0x1, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:201 +0x1da fp=0xc8204559a0 sp=0xc820455928
2016/08/09 12:03:50 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc8203acfe0, 0xc820444900, 0xc820444af0, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:482 +0x6a fp=0xc820455a10 sp=0xc8204559a0
2016/08/09 12:03:50 [DEBUG] plugin: terraform: runtime.call64(0xc820442fc0, 0x3650738, 0xc8201a7d40, 0x1800000028)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc820455a58 sp=0xc820455a10
2016/08/09 12:03:50 [DEBUG] plugin: terraform: reflect.Value.call(0x2c6c740, 0x3650738, 0x13, 0x37c3bf8, 0x4, 0xc820455ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:435 +0x120d fp=0xc820455da8 sp=0xc820455a58
2016/08/09 12:03:50 [DEBUG] plugin: terraform: reflect.Value.Call(0x2c6c740, 0x3650738, 0x13, 0xc820455ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:303 +0xb1 fp=0xc820455e08 sp=0xc820455da8
2016/08/09 12:03:50 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc820440800, 0xc8204407c0, 0xc82043edf8, 0xc8203bf200, 0xc8204740a0, 0x2540fc0, 0xc820444900, 0x16, 0x2541020, 0xc820444af0, ...)
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x1c2 fp=0xc820455f28 sp=0xc820455e08
2016/08/09 12:03:50 [DEBUG] plugin: terraform: runtime.goexit()
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820455f30 sp=0xc820455f28
2016/08/09 12:03:50 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x49d
2016/08/09 12:03:50 [DEBUG] plugin: terraform: 
`

I'm also checking out #7570, but the problem seems to still show up.

**Comment by catufunwa** [comment]
It also seems to only happen when parallelism is enable. I'm guessing a map doesnt have a mutex on it when writes are happening to it.

**Comment by ldanz** [comment]
I'm having the same problem.  Thanks for the tip about parallelism @catufunwa; that gave me a usable workaround.

Seems that the probability of the problem increases with higher parallelism; I get an error some of the time with default parallelism (10), more often when I raise it, and less often when I lower it.  My configuration has 4 cloudflare records that are among the first 10 resources configured according to `terraform plan`.

**Comment by catufunwa** [comment]
@ldanz glad it worked for you. I'm also using the -target flag. Not ideal, but it also works.

**Comment by joshuajabbour** [comment]
I am/was having this problem as well (with four Cloudflare records). Using `terraform plan -parallelism=1` makes the plan succeed.

**Comment by makered** [comment]
Same problem here (v0.7.3) for 6 CF records in a script that ran successfully under v0.6.x. 
Limiting parallelism to 1 worked for me. Thanks!

**Comment by tboerger** [comment]
Latest terraform still got this issue, setting `-parallelism=1` is the only way to get it reliable working...

**Comment by tboerger** [comment]
I have updated the used client library for cloudflare and rebuilt terraform, this seems to solve the problem so it's possible that a fix like https://github.com/cloudflare/cloudflare-go/issues/88 solved the issue.
