### ISSUE TITLE
Terraform docs don't show Data Sources section depending on the URL

### ISSUE THREAD

**Issue by benjisg** [hashicorp/terraform#8012]
Looks like the new Data Sources documentation is URL dependent currently. So you can see them when you visit the AWS provider docs without the index.html (https://www.terraform.io/docs/providers/aws/) but not when it is included (https://www.terraform.io/docs/providers/aws/index.html).

The second URL is what is linked to by default for the AWS Provider link

<img width="1190" alt="terraform_docs" src="https://cloud.githubusercontent.com/assets/308887/17445577/745f1cc8-5afa-11e6-8b8a-85c3f825fab3.png">

<img width="1201" alt="screen shot 2016-08-05 at 10 51 03 am" src="https://cloud.githubusercontent.com/assets/308887/17445605/94c37d06-5afa-11e6-97b5-7ac82951383c.png">

**Comment by apparentlymart** [comment]
Hi @benjisg! Thanks for this report.

I wasn't able to reproduce this, unfortunately.

I've noticed before that the cache headers on the Terraform manual specify some quite aggressive caching, so after a new release it's sometimes necessary to force-refresh the page to see the latest changes. Could you give that a try and see if that resolves this inconsistency for you?

**Comment by benjisg** [comment]
Haha oops, yep looks like that was it. Tried it out in Chrome and it showed it just fine. Sorry about that! Thanks @apparentlymart !
