### ISSUE TITLE
provider/openstack: Can Heat and Ceilometer be used with Terraform for autoscaling?

### ISSUE THREAD

**Issue by jtopjian** [hashicorp/terraform#8022]
This issue is a result of a discussion at #6161.

The OpenStack Heat and Ceilometer projects can be used to provide autoscaling functionality for OpenStack resources. Can these two projects be integrated into the Terraform OpenStack provider in order to provide autoscaling in a similar manner way of Terraform's AWS autoscaling support?

**Comment by mitchellh** [comment]
I believe autoscaling like this is outside the scope of Terraform directly, but may be mimicable using data sources and count? I'm open to it if you can find a way that fits into the current TF model.

**Comment by splashx** [comment]
I'm looking into implementing something like [this](https://robmorgan.id.au/posts/rolling-deploys-on-aws-using-terraform/) in openstack, so basically missing the `openstack_autoscaling` resource implementation?

**Comment by jtopjian** [comment]
@splashx Yeah, I think that would work well. :)

**Comment by remyje** [comment]
To quote @FransUrbo, "Please reopen this!"

I don't understand how supporting OpenStack autoscaling is outside the scope of Terraform if Terraform supports this for AWS, GCP, and Azure.

**Comment by jtopjian** [comment]
@remyje I understand your concern, but there's really no reason to reopen this. As mentioned above, creating resources for the OpenStack provider that work with the Heat and Ceilometer services is the best way forward for this. 

Additionally, discussion of the OpenStack provider has now moved to https://github.com/terraform-providers/terraform-provider-openstack. I would be happy to answer any questions you might have about this over there :)
