### ISSUE TITLE
google_sql_user doesn't work with 2nd generation sql instances.

### ISSUE THREAD

**Issue by lesaux** [hashicorp/terraform#8025]
There doesn't seem to be a way of setting up users (including root) through terraform on 2nd gen SQL instances.

**Comment by sjourdan** [comment]
Same error here with Terraform 0.7.3: 

`* google_sql_database.wordpress: Error, failed to getdatabase wordpress in instance m-mysql: googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation`

Using the following basic code: 

```
resource "google_sql_database" "wordpress" {
  name     = "wordpress"
  instance = "${google_sql_database_instance.master.name}"
}

resource "google_sql_database_instance" "master" {
  name             = "m-mysql"
  region           = "${var.region}"
  database_version = "MYSQL_5_7"

  settings = {
    tier              = "db-n1-standard-1"

    ip_configuration {
      ipv4_enabled = true
    }
  }
}

```

However with a 1st gen SQL instance it still works well.

**Comment by devth** [comment]
I get:

```
google_sql_user.mysql: Error, failed to insert user mysql into instance prod-mysql: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

Even though the service account is Owner on the project and APIs are enabled.

**Comment by devth** [comment]
Does the generated API need to be updated?

Looks like latest [sqadmin-gen.go](https://github.com/google/google-api-go-client/blob/master/sqladmin/v1beta4/sqladmin-gen.go) was updated 2 months ago but the [vendored version](https://github.com/hashicorp/terraform/blob/master/vendor/google.golang.org/api/sqladmin/v1beta4/sqladmin-gen.go) was last updated 12/1/2016.

**Comment by winks** [comment]
I'm having this on Terraform 0.8.8 - but only sporadically.

also, 
```
* google_sql_database_instance.dbinfra: Error, the name dbinfra is unavailable because it was used recently.
```
This was just after a failed terraform run where `dbinfra` (2nd gen) was not created. Then on a 2nd `apply` the instance was created, but only with 1 user instead of too.

Sorry that I can't provide more details, will try to save logfiles if it happens again.

**Comment by arekkas** [comment]
@devth I'm hitting the same issue, where you able to resolve it?

**Comment by arekkas** [comment]
In case you didn't figure it out, I did, see: https://github.com/terraform-providers/terraform-provider-google/issues/685#issuecomment-341987172
