### ISSUE TITLE
Terraform v0.7.0 list output not working on Windows (aws_availability_zones)

### ISSUE THREAD

**Issue by shanmugakarna** [hashicorp/terraform#8027]
The issue is related to Terraform `v0.7.0` on Windows. The below config work on Linux (Ubuntu 16.04), while the same exact copy fails on windows (64-bit).
```
data "aws_availability_zones" "available" {}
output "azs" {
  vaule = "${data.aws_availability_zones.available.names}"
}
```
The above config when executing `terrafrom plan` on Ubuntu works perfectly
```
az = [
    us-west-2a,
    us-west-2b,
    us-west-2c
]
```
On Windows 10 64-bit same Teraaform version `0.7.0` 64-bit throws following errors
```
Errors:
  * 1 error(s) occurred:
* module root: 2 error(s) occurred:
* az: output has invalid keys: vaule
* az: output is missing required 'value' key
```
Neither getting single value works `"${data.aws_availability_zones.available.names[0]}"`

**Comment by stack72** [comment]
Hi @shanmugakarna 

This seems to be a spelling issue AFAICT

```
data "aws_availability_zones" "available" {}
output "azs" {
  vaule = "${data.aws_availability_zones.available.names}"
}
```

Notice the word `vaule` not `value`

Please can you have a look and see if that helps?

Paul

**Comment by shanmugakarna** [comment]
My Bad, Thanks @stack72 

I'm not sure how this happened. I copied over from my Ubuntu system to windows.
The issue can be closed. Sorry for the bad alert

Thanks,

**Comment by stack72** [comment]
No worries at all :) Always useful to have a second set of eyes!

Paul
