### ISSUE TITLE
Problem passing map variables to modules -  regression between 0.7-RC3 and 0.7 release

### ISSUE THREAD

**Issue by bfgoodrich** [hashicorp/terraform#8036]
Problem with passing map variables to modules in 0.7 release. Terraform 0.7 RC3 was able to pass map variables to modules without issue. 
### Terraform Version

Terraform v0.7.0
Terraform v0.7.0-rc3 (3f4857a07a24f3c9e2db6b4458fbf5be19a8b256)
### Affected Resource(s)

Terraform Core
### Terraform Configuration Files

module-test/test.tf

``` hcl
output "map-test" {
    value = "${var.map-test}"
}

output "string-test" {
    value = "${var.string-test}"
}
```

module-test/variables.tf

``` hcl
variable "string-test" {
   type = "string"
   default = ""
}

variable "map-test" {
    type = "map"
    default = {}
}
```

terraform.tfvars

``` hcl
map-test.0 = "this"
map-test.1 = "is"
map-test.2 = "a"
map-test.3 = "map"
string-test = "this is a test string"
```

test.tf

``` hcl
module "module-test" {
    source = "module-test"

    map-test = "${var.map-test}"
    string-test = "${var.string-test}"
}

output "map-test" {
    value = "${var.map-test}"
}

output "string-test" {
    value = "${var.string-test}"
}
```

variables.tf

``` hcl
variable "string-test" {
   type = "string"
   default = ""
}

variable "map-test" {
    type = "map"
    default = {}
}
```
### Output

terraform 0.7 RC3

```
$./terraform-old apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

map-test = {
  0 = this
  1 = is
  2 = a
  3 = map
}
string-test = this is a test string
```

terraform 0.7 release

```
$./terraform-new apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

map-test = {}
string-test = this is a test string
```
### Expected Behavior

Map variable is passed to module
### Actual Behavior

Map variable is not passed to module, only string variables
### Steps to Reproduce
1. `terraform apply`

**Comment by bfgoodrich** [comment]
Anyone have a chance to look at this bug? We are still using RC2 version of Terraform 0.7 to avoid this behavior.

**Comment by redbaron** [comment]
+1

**Comment by bfgoodrich** [comment]
Any update on this? I am still literally unable to use any version of Terraform but this specific RC release?!

**Comment by mitchellh** [comment]
This is actually fixed, sorry. We removed (in 0.7) the `map.key = value` syntax from terraform.tfvars. So if you change the above to look like this: 

```
map-test = {
  "0" = "this"
  "1" = "is"
  "2" = "a"
  "3" = "map"
}

string-test = "this is a test string"
```

Then this works!
