### ISSUE TITLE
Can't set root password of Google Cloud SQL 2nd generation instance

### ISSUE THREAD

**Issue by mstrzele** [hashicorp/terraform#8039]
When creating `google_sql_database_instance` using second generation of Google Cloud SQL there is no ability to set the root password required for future usage.

The workaround for me was to use `gcloud` CLI in `local-exec` provider:

``` hcl
resource "google_sql_database_instance" "default" {
  region = "${var.region}"

  settings {
    tier = "${var.tier}"
  }

  database_version = "MYSQL_5_7"

  provisioner "local-exec" {
    command = "gcloud -q sql instances set-root-password ${google_sql_database_instance.default.name} --password ${var.root_password}"
  }
}
```

I'm using Terraform v0.7.0.

**Comment by danawillow** [comment]
Sorry for taking so long to get to this! Have you tried using google_sql_user for this? I'm not positive it'll work with root but it's worth a shot: https://www.terraform.io/docs/providers/google/r/sql_user.html.

**Comment by mstrzele** [comment]
Unfortunately, 2nd Generation doesn't allow to create users using Google Cloud SQL API (I assume that both `google_sql_database` and `google_sql_user` use it).

**Comment by mstrzele** [comment]
The password can be set using `google_sql_user`. Don't know when it was fixed, but I'm glad that it works!
