### ISSUE TITLE
azurerm - feature req - vnet peering

### ISSUE THREAD

**Issue by tasquith** [hashicorp/terraform#8041]
Hi,

Are there any plans to support virtual network peering (currently in preview), As I can see the virtual network gateway resource is not supported, this should cover both use cases.

https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-create-vnetpeering-arm-template-click/

It doesn't look like the API docs have been updated, or I'm looking in the wrong place!

https://msdn.microsoft.com/en-us/library/azure/mt163661.aspx

Kind Regards,
Tom

**Comment by stack72** [comment]
Hi @tasquith 

If this is not yet supported by the SDK, then we need to request that first before Terraform can even think about it

Paul

**Comment by tasquith** [comment]
Thanks @stack72 

Tom

**Comment by pmcatominey** [comment]
The API for peering is defined in the REST specifications repo but hasn't been made available in the Go SDK yet, I've raised Azure/azure-sdk-for-go#377 for this.

I plan to work on the Terraform resource when it's available in the SDK.

**Comment by stack72** [comment]
Closed via #8168
