### ISSUE TITLE
Can't reference template_file data source in own provisioner

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform#8046]
### Terraform Version

0.7
### Affected Resource(s)
- `template_file` as data source
### Terraform Configuration Files

``` hcl
data "template_file" "admin_kubeconfig" {
  template = "${file("${path.module}/resources/admin-kubeconfig.yaml")}"

  vars {
...
  }

  provisioner "local-exec" {
    command = "echo '${data.template_file.admin_kubeconfig.rendered}' > ${path.module}/outputs/kubeconfig.yml"
  }
}
```
### Debug Output

```
Error configuring: 1 error(s) occurred:

* Self reference: data.template_file.admin_kubeconfig
```
### Expected Behavior

In versions previous to 0.7, this kind of usage resulted in the rendered template being interpolation-replaced in the echo command line.
### Actual Behavior

After the switch of template_file from resource to data provider the interpolation of the rendered template in a provisioner command results in a cyclic reference error (see debug output).
This looks like a regression from 0.6.x
### Steps to Reproduce
1. Create a terraform template with a `template_file` resource with a provisioner and reference the the resource`s output attributes in the provisioner.
2. `terraform apply`

**Comment by antonosmond** [comment]
Also have the same issue with a slightly different error using the provisioner 'self' reference i.e:
```
variable "username" {
  default = "bob"
}

data "template_file" "user" {
  template = "${file("user.tmpl")}"
  vars {
    USERNAME = "${var.username}"
  }
  provisioner "local-exec" {
    command = "echo ${self.rendered} > user.txt"
  }
}
```
```
Errors:

  * 1 error(s) occurred:

* module root: 1 error(s) occurred:

* resource 'data.template_file.user' config: cannot contain self-reference self.rendered
```

**Comment by mitchellh** [comment]
Actually a core bug. Reproduced.
