### ISSUE TITLE
core: the count (#) for computed maps doesn't show a value

### ISSUE THREAD

**Issue by svanharmelen** [hashicorp/terraform#805]
I noticed that (at least) for computed maps, it shows the correct info during the plan fase, but saves an empty value to the state after the apply fase:

```
PLAN:

<snip>
  rule.2759665100.uuids.#:           "" => "<computed>"
<snip>
```

```
STATE after APPLY:

<snip>
  rule.2759665100.uuids.# =
  rule.2759665100.uuids.80 = c983004b-b61a-4924-a50d-4ee09c926a4f
<snip>
```

Will try to make a test later, but have some organisational issues today...

**Comment by svanharmelen** [comment]
/CC @mitchellh 

I think this issue is bigger then just the count for computed maps... It almost seems that *all* fields are saved to the state, even if they are not set... Take this for example:

```
PLAN: 

+ cloudstack_ipaddress.foo
    ipaddress: "" => "<computed>"
    vpc:       "" => "terraform-vpc"

+ cloudstack_vpc.foobar
    cidr:         "" => "172.16.0.0/16"
    display_text: "" => "<computed>"
    name:         "" => "terraform-vpc"
    vpc_offering: "" => "Default VPC offering"
    zone:         "" => "zone-1"
```

```
STATE after APPLY:

cloudstack_ipaddress.foo:
  id = fe962b27-0cee-4da2-a793-05b24bd789cc
  ipaddress = 31.22.81.169
  network =
  vpc = terraform-vpc
cloudstack_vpc.foobar:
  id = 4e1b28c0-f61a-478e-a574-37103213cadd
  cidr = 172.16.0.0/16
  display_text =
  name = terraform-vpc
  vpc_offering = Default VPC offering
  zone = zone-1
```

Where `display_text` is computed and set during the apply fase and `network` is an unset optional parameter...

/CC @mitchellh

**Comment by mitchellh** [comment]
So, something new with it is that even if its _not_ set, since you said its computed, it will result in the zero value to be set. For network, that is the empty string, so that isn't an issue. This actually fixes other bugs.

For display text though, if its set, then it shouldn't be blank.

**Comment by svanharmelen** [comment]
@mitchellh I don't agree that it isn't an issue... When you do a d.GetOk("network") and it returns `true` because it's empty value is in the state, that sounds not right to me...

**Comment by svanharmelen** [comment]
But it could all be related to the d.GetOk() still not working a 100% as the code to actually set the `display_text` looks like this:

```
	// Set the display text
	displaytext, ok := d.GetOk("display_text")
	if !ok {
		displaytext = d.Get("name")
	}
```

So it actually depends on the result of d.GetOk(). And that's the same call that now gives me problems for checking if a `network` value is been set:

```
if network, ok := d.GetOk("network"); ok {
		// Retrieve the network UUID
		networkid, e := retrieveUUID(cs, "network", network.(string))
		if e != nil {
			return e.Error()
		}
<snip>
```

So maybe I'm thinking in the wrong direction.

**Comment by svanharmelen** [comment]
So this check (added in TestResourceDataGetOk) fails, which I would think is correct because it is present:

```
		{
			Schema: map[string]*Schema{
				"availability_zone": &Schema{
					Type:     TypeString,
					Required: true,
				},
			},

			State: &terraform.InstanceState{
				Attributes: map[string]string{
					"availability_zone": "",
				},
			},

			Diff: nil,

			Key:   "availability_zone",
			Value: "",
			Ok:    false,
		},
```

**Comment by mitchellh** [comment]
Ah okay, so I agree its probably a `GetOk` issue. I'll think about this...

**Comment by mitchellh** [comment]
I have a failing test so I think I can fix this.

**Comment by svanharmelen** [comment]
All the trailing findings in the issue are solved by PR #808, so only the initial issue (the count (#) not being set correctly for computed maps) still needs to be solved...

**Comment by mitchellh** [comment]
@svanharmelen I got a failing test for that too, fix incoming...

**Comment by svanharmelen** [comment]
Nice! And of course didn't meant to close this issue by closing PR #808. Must be a GH feature I don't know about...
