### ISSUE TITLE
provider/aws: aws_rds_cluster create may take > 15 minutes

### ISSUE THREAD

**Issue by kcrawley** [hashicorp/terraform#8051]
When restoring large db snapshots within a RDS cluster, I've witnessed create actions take > 30 minutes. I propose we bump the timeout to 40 minutes, which corresponds with the maximum timeout on aws_rds_cluster_instance create actions.

I have submitted a PR to address this issue.

**Comment by catsby** [comment]
Closed by #8052, thanks!
