### ISSUE TITLE
Documentation issue: Firehose S3 configuration - compression format should be UNCOMPRESSED, not NOCOMPRESSION

### ISSUE THREAD

**Issue by ccampo133** [hashicorp/terraform#8054]
https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#compression_format

Notice that the documentation states that the default is `NOCOMPRESSION`, however when you run Terraform and explicitly set the `compression_format` to `NOCOMPRESSION`, it fails and complains that the value should instead be `UNCOMPRESSED`.

Pretty sure this is just a documentation update.

**Comment by stack72** [comment]
Hi @ccampo133 

Thanks for the bug report here. You are indeed correct - the docs should have said UNCOMPRESSED :)

I have fixed this and it will be live on the site very shortly

Paul
