### ISSUE TITLE
Not accepting maps from a var file!

### ISSUE THREAD

**Issue by jsonmaur** [hashicorp/terraform#8057]
Terraform Version: **v0.7.0**
Affected Resource: **Terraform Core**

###### terraform.tvfars
```hcl
somemap = {
  foo = "bar"
  baz = "qux"
}
```

###### main.tf
```hcl
variable "somemap" {
  type = "map"
}

output "somemap" {
  value = "${var.somemap}"
}
```

This should simply output the map. But instead, I get this error:
`variable somemap should be type map, got list`

It works as expected if I run `TF_VAR_somemap='{foo = "bar", baz = "qux"}' terraform apply`. Another interesting tidbit--if I change the var type to `variable "somemap" { type = "list" }`, I get the error: `variable somemap should be type list, got list`.

According to the docs [here](https://www.terraform.io/docs/configuration/variables.html), this should work.

**Comment by lamanotrama** [comment]
Though this is just a workaround, I was able to avoid this kind of error when set `default = {}`.

e.g.

```tf
variable "somemap" {
  type = "map"
  default = {}
}
```

I comfirmed it in ver 0.7.0 and 0.7.1

**Comment by brikis98** [comment]
Just hit the same issue trying to pass an empty map from the command-line. The Terraform template:

```hcl
variable "foo" {
  type = "map"
}
```

Trying to set the variable from the command-line:

```
terraform apply -var 'foo = {}'
```

This caused the error:

```
* variable foo should be type map, got list
```

@lamanotrama's workaround helped: 

```hcl
variable "foo" {
  type = "map"
  default = {}
}
```

**Comment by jamtur01** [comment]
Hi - just wondering if there's plans to work on this - if not - I'd be happy (and would suggest) a docs update - because this is very counter-intuitive. :)
