### ISSUE TITLE
vSphere provider: sparse VMDK is not completely cleaned up with vsphere_file

### ISSUE THREAD

**Issue by sputnik13** [hashicorp/terraform#8058]
When a sparse VMDK is uploaded with vsphere_file and used with a vsphere_virtual_machine, additional files get generated due to the VMDK being a sparse VMDK.  If I have keep_on_remove = "true" on the VM so that terraform destroy can delete the vsphere_file, the additional files generated for the sparse VMDK is not cleaned up properly.  This results in subsequent runs of terrform apply failing.

Sample terraform template below...

```
resource "vsphere_file" "k8s-master-bootdisk" {
    datacenter = "${var.datacenter}"
    datastore = "${var.datastore}"
    source_file = "${var.linux_vmdk_source}"
    destination_file = "${var.prefix}/master-bootdisk.vmdk"
}

resource "vsphere_virtual_machine" "k8s-master" {
    name = "${var.prefix}-master"
    #folder = "${vsphere_folder.k8s_folder.path}"
    datacenter = "${var.datacenter}"
    cluster = "${var.cluster}"

    connection {
        user = "ubuntu"
        key_file = "${var.key_file}"
    }

    network_interface {
        label = "${var.network}"
    }

    cdrom {
        datastore = "${var.datastore}"
        path = "${vsphere_file.cidata.destination_file}"
    }

    disk {
        controller_type = "ide"
        datastore = "${var.datastore}"
        vmdk = "${vsphere_file.k8s-master-bootdisk.destination_file}"
        bootable = "true"
        keep_on_remove = "true"
    }
}
```

**Comment by jbilbro** [comment]
@sputnik13 Can you please tell me the value of the variable var.prefix?  I'm trying to duplicate your issue and haven't tried vsphere_file before - I typically use a template.  I can't tell how to discern the path from looking at documentation.  Also, are you pointing this at a vcenter server or directly at a ESXi host?

**Comment by jbilbro** [comment]
@sputnik13 ?
