### ISSUE TITLE
vSphere provider:  diskpaths format not valid for datastore in datastore cluster

### ISSUE THREAD

**Issue by dagnello** [hashicorp/terraform#8059]
virtual_disk and virtual_machine resources, make use of Sprintf to compile vmdk/iso paths:
diskPath := fmt.Sprintf("[%v] %v", vDisk.datastore, vDisk.vmdkPath)

These paths should be compile with the finder.Datastore object instead, e.g:
ds, err := getDatastore(finder, "myDataStore")
dsPath := ds.Path(pathInDatastore)

**Comment by chrislovecnm** [comment]
please put in a PR if you are able to!

**Comment by stack72** [comment]
@dagnello I believe this can be closed via #8075

Correct?
