### ISSUE TITLE
Use of count.index with variable interpolation forces new instances

### ISSUE THREAD

**Issue by cbarbour** [hashicorp/terraform#8061]
### Terraform Version
- Terraform v0.7.0 (Built from tag using go get, etc.)
- go version go1.6.3 darwin/amd64
- Reproducible with downloadable binary from terraform website
### Affected Resource(s)
- aws_instance
- template_file
- Many others

This issue appears to affect multiple resources, and may be an issue with terraform's core
### Terraform Configuration Files

``` hcl
variable "node_count" {
  description = "The number of EC2 instances to create. Scale this up and down to expose issues."
  type = "string"
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "node" {
  count = "${var.node_count}"
  ami = "ami-7172b611" #Amazon Linux AMI 2016.03.3 (HVM), SSD Volume Type
  instance_type = "t2.micro"
  user_data = "${template_file.cloudinit.*.rendered[count.index]}"
}

resource "template_file" "cloudinit" {
  count = "${var.node_count}"
  vars {
    demo = "${count.index}"
  }

  template = <<EOF
runcmd:
- "echo I am node ${demo}"

EOF
}
```
### Debug Output

https://gist.github.com/cbarbour/2ae26c2081bbd545d3e904b96340e8bc
### Expected Behavior
- New instance should have been created with new user-data
- Existing instances should not have changed
### Actual Behavior
- New instances created with new user-data
- Existing instances destroyed and recreated
- Existing instances report same user_data hash as new instances in plan
### Steps to Reproduce
1. `TF_VAR_node_count=1 terraform apply`
2. `TF_VAR_node_count=2 terraform apply`
### Important Factoids

This is a simplified case to recreate my problem. I've seen this with numerous other resource types when using variable interpolation with count.index
### References
- GH-8005

**Comment by cbarbour** [comment]
=== Console output demonstrating behavior

https://gist.github.com/cbarbour/f377ffe0d4391def8ff27cdf385aa3db

**Comment by mitchellh** [comment]
Confirmed that this behavior is indeed broken. A reproduction that I had to change a bit since I have no default VPC in my account:

```
variable "node_count" {
  description = "The number of EC2 instances to create. Scale this up and down to expose issues."
  type = "string"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "node" {
  count = "${var.node_count}"
  ami = "ami-c481fad3" #Amazon Linux AMI 2016.03.3 (HVM), SSD Volume Type
  instance_type = "t2.micro"
  user_data = "${template_file.cloudinit.*.rendered[count.index]}"
  subnet_id = "subnet-5aa93813" # FILL THIS IN!
}

resource "template_file" "cloudinit" {
  count = "${var.node_count}"
  vars {
    demo = "${count.index}"
  }

  template = <<EOF
runcmd:
- "echo I am node ${demo}"

EOF
}
```

**Comment by mitchellh** [comment]
This is likely a dup of #3449.
