### ISSUE TITLE
Error creating a multi-AZ Autoscaling Group

### ISSUE THREAD

**Issue by adamar** [hashicorp/terraform#8064]
The ASG successfully start an instance in the first AZ.

Then it attempts to start an instance in the second AZ, but fails and the Activity History shows the following error:
> The placement group 'null' is in use in another availability zone: null. Launching EC2 instance failed.

Then, after failing a few more times starts another instance in the first AZ. Then it shows the following message:

>  instances were launched to balance instances in zones us-west-2b us-west-2a with other zones resulting in more than desired number of instances in the group. Availability zones us-west-2b us-west-2a had 0 2 instances respectively. An instance was launched to aid in balancing the group's zones.

The config for this ASG, placement group and launch config is shown below:

```
resource "aws_launch_configuration" "app_launch_conf" {
    name_prefix = "app-${var.vpc_name}-"
    image_id = "${var.ami}"
    instance_type = "m4.large"
    key_name = "${var.key}"
    security_groups = ["${split(",", var.app_sgs)}"]
}


resource "aws_placement_group" "app_pg" {
    name = "app-pg-${var.vpc_name}"
    strategy = "cluster"
}

resource "aws_autoscaling_group" "app_asg" {
    availability_zones = ["us-west-2a", "us-west-2b"]
    name = "app-${var.vpc_name}"
    max_size = "${var.max_size}"
    min_size = "${var.min_size}"
    min_elb_capacity = 0
    metrics_granularity = "1Minute"
    health_check_grace_period = 600
    health_check_type = "ELB"
    desired_capacity = "${var.desired_size}"
    termination_policies = ["OldestInstance"]
    force_delete = true
    placement_group = "${aws_placement_group.app_pg.id}"
    launch_configuration = "${aws_launch_configuration.app_launch_conf.name}"
    load_balancers = [ "${split(",", var.app_elbs)}" ]
}
```

Terraform version: Terraform v0.6.16

**Comment by clstokes** [comment]
@adamar, you're specifying a placement group on your `aws_autoscaling_group` and also specifying multiple zones. Placement groups are constrained to a single zone ([docs link](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html)) so this might be contributing to the error you're receiving.

Can you try with a single zone and see if it works?

**Comment by adamar** [comment]
Hi @clstokes, thanks, your right on the money. The placement group is not required. I removed it and it adds instances to multiple AZs now.
