### ISSUE TITLE
Interpolating invalid variables should be an error

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#8077]
### Terraform Version

v0.7.0
### Terraform Configuration Files

``` hcl
data "template_file" "foo" {
  template = "${bar}"
  vars {
    bar = "baz"
  }
}
```
### Expected Behavior

`bar` is not a valid interpolation variable, so Terraform should produce an error noting that.
### Actual Behavior

Terraform sees the `${bar}` interpolation, sees that there's no value of `bar` to substitute, and marks the `template` argument as containing computed variables.

The data resource lifecycle then sees that this resource has a computed config and so defers handling it until `apply`.

Eventually the `Read` function in the data source runs against the string still containing the `${bar}` interpolation, causing "baz" to be interpolated from the template variable context.

Thus this appears to do what the user wanted, but the middle step (where the refresh gets deferred until `apply`) effectively defeats the point of this being a data resource, since the template can't be populated during initial refresh.
### Steps to Reproduce
1. Run `terraform plan` with the above configuration
2. Note that a read for the data resource appears in the plan, rather than failing with an error.
3. Run `terraform apply` with the above configuration
4. Note that Terraform completes successfully, interpolating the value of `bar` from the template context.

In this example we're using `template_file` which happens to ultimately parse the string as an interpolation expression anyway. For any other attribute, the resource would likely use the raw interpolation expression as a real value, which would likely result in a confusing error about argument value syntax.
### References
- This was initially raised as a misunderstanding arising from this confusing behavor, #8021.

**Comment by glasser** [comment]
For what it's worth, I wish that I actually had access to a `template_file`-like resource that let me specify a template inline (not in a separate file) and just directly interpolate var and resource values, instead of having to indirect via a `vars` block. But I should accept that `template_file` is not that resource and not abuse it.

**Comment by apparentlymart** [comment]
#9698 is going to fix this, though it's being kept back until 0.8 because it has backward-compatibility implications.

**Comment by mitchellh** [comment]
I'm going to close this @apparentlymart because it dups a bunch of other issues, but #9698 as you said will fix this.
