### ISSUE TITLE
RDS: aws_db_instance not respecting parameter_group_name on first run

### ISSUE THREAD

**Issue by alkema** [hashicorp/terraform#8079]
When using `aws_db_instance` and setting the `parameter_group_name` it is presented in both `plan` and `apply` as being set with the correct value. However, after being applied the value is set to something else. When looking at the RDS instance in the AWS interface it is not set properly, it is set to  `default.mysql5.6`, not `mysql-params`. 

Upon an immediate subsequent `terraform plan` this diff is evident, then a subsequent `terraform apply` changes `parameter_group_name` to the correct value. I then need to do an RDS reboot to apply it too.
### Terraform Version

```
✗ terraform -v
Terraform v0.7.0
```
### Affected Resource(s)
- aws_db_instance
### Terraform Configuration Files

``` hcl
...
variable "parameter_group_name" {
  default = "mysql-params"
}

resource "aws_db_instance" "default" {
  lifecycle {
    create_before_destroy = true
  }
  instance_class = "${var.instance_class}"
  db_subnet_group_name = "${var.db_subnet_group_name}"
  snapshot_identifier = "${var.snapshot_identifier}"
  identifier = "${var.identifier}"
  parameter_group_name = "${var.parameter_group_name}"
  apply_immediately = true
  tags {
    Cluster = "${var.cluster}"
    Environment = "${var.environment}"
    App = "${var.app}"
  }
}
...
```
### Expected Behavior

I expect `parameter_group_name` to be applied with the value it was set within the config on first apply. I also expect to have to do an AWS RDS reboot as according to docs:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html

```
Parameter group name:
The name change is applied immediately. Any parameter value changes are applied to the DB instance after you manually reboot the DB instance.
```
### Actual Behavior

`parameter_group_name` is set to `default.mysql5.6` not `mysql-params`.
### Steps to Reproduce

`terraform plan`

```
...
-/+ module.hampton.aws_db_instance.default
...
    parameter_group_name:       "mysql-params" => "mysql-params"
```

`terraform apply`

```
...
  parameter_group_name:       "" => "mysql-params"
...
```

`terraform plan`

Note: this is the only change reported.

```
~ module.hampton.aws_db_instance.default
    parameter_group_name: "default.mysql5.6" => "mysql-params"
```

`terraform apply`

Note: this is the only change reported.

```
module.hampton.aws_db_instance.default: Modifying...
  parameter_group_name: "default.mysql5.6" => "mysql-params"

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Now a manual RDS reboot needed to apply change and finally get a proper `parameter_group_name`.

**Comment by kxseven** [comment]
Confirming issue still present in v0.7.7 and v0.7.9

**Comment by jhoblitt** [comment]
This issue appears to still be present under `0.8.8`.  In the aws console, it shows the parameter group name correctly but followed by `(pending-reboot )`.  A manual reboot applies the parameter group name change.

**Comment by estheban** [comment]
Still present in Terraform v0.9.6
