### ISSUE TITLE
Has anyone thought about pricing?

### ISSUE THREAD

**Issue by bigkraig** [hashicorp/terraform#8085]
I've been looking for ways of connecting end users of terraform with the costs associated with the changes they are making with TF. One obvious way is to calculate an estimated pricing based on the resources defined in the TF configuration.

I'm thinking something along the lines of an output of plan that would show you the change in cost from current resources to future resources, a lot like what we do now for the resourced added/changed/destroyed but with a dollar figure attached.

Some things like ASG's may be a little complicated since their size can change, but an estimated min/max/max hourly charge could be good enough.

I wanted to gather some thoughts on this before I started to write any code to make sure it was in line with others use.

Thanks!

**Comment by cbarbour** [comment]
Yes. In our case, we're using terraform to provide self-service provisioning. However, our plan involves wrapping terraform in a user-friendly script.

Our approach is to pull the libcloud pricing matrix into the script, notifying the user how much their instances will cost. We also intend to integrate with cloudwatch and the billing reports to show the current accumulated bill.

**Comment by mitchellh** [comment]
We believe 3rd parties should support this but to help enable that we plan on allowing machine readable output to query the state and TF metadata.
