### ISSUE TITLE
Write a rendered template on a local file

### ISSUE THREAD

**Issue by sbourlon** [hashicorp/terraform#8090]
Hi there,

I am trying to write a rendered template containing a cloud-init user-data in a local file. Then, I can use this file to generate an ISO for VMware vSphere.

If I understand correctly the documentation, I should be able to write in a file with the resource/data source `template_cloudinit_config` (https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) thanks to the `filename` key.

Thanks for your help!

### Terraform Version
Tried with Terraform v0.6.16 and v0.7.0.

### Affected Resource
- template_cloudinit_config

### Terraform Configuration Files
```
resource "template_cloudinit_config" "test" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "user-data.txt"
    content      = "my userdata content"
  }
}
```

### Expected Behavior
The file `user-data.txt` should have been created with the content `my userdata content`.

### Actual Behavior
The file `user-data.txt` is not created.

### Steps to Reproduce
1. `terraform apply`

**Comment by kwilczynski** [comment]
@sbourlon hello! I am not entirely sure if your use case is something I understood correctly, especially with writing the file locally (where I assumed that you meant the host onto which you run Terraform).

Consider the following example, it would give you some idea how to do it (uses 0.7.x data sources):

```
variable "hostname"    {}
variable "domain_name" {}

variable "filename" {
  default = "cloud-config.cfg"
}

data "template_file" "test" {
  template = <<EOF
#cloud-config
hostname: ${hostname}
fqdn: ${fqdn}
mounts:
  - [ ephemeral, null ]
output:
  all: '| tee -a /var/log/cloud-init-output.log'
EOF

  vars {
    hostname = "${var.hostname}"
    fqdn     = "${format("%s.%s", var.hostname, var.domain_name)}"
  }
}

data "template_cloudinit_config" "test" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "${var.filename}"
    content_type = "text/cloud-config"
    content      = "${data.template_file.test.rendered}"
  }
}

resource "null_resource" "local" {
  triggers {
    template = "${data.template_file.test.rendered}"
  }

  provisioner "local-exec" {
    command = "echo \"${data.template_file.test.rendered}\" > ${var.filename}"
  }
}
```

The `template_cloudinit_config` data source (or a resource in the 0.6 speak) would render a cloud-init template (which should be assembled correctly for cloud-init to consume) in memory, so that its rendered content can be used somewhere else. The `filename` attribute is used to assemble a multi-part payload which cloud-init would understand and in turn deploy multiple files into desired locations - neither it does not save the file onto the remote machine itself nor on the node where you run Terraform from.

If you need to create file on a remote machine, then have a look at the [file](https://www.terraform.io/docs/provisioners/file.html) provisioner which would definitely help.

Hope this helps.

**Comment by sbourlon** [comment]
Thank you @kwilczynski! It worked!

**Comment by sbourlon** [comment]
I am reopening this issue because the example given by @kwilczynski is using Shell to write to the file. Is `data "template_cloudinit_config"` supposed to write the `content` key value into the file given by the key `filename`?

```
resource "null_resource" "local" {
  triggers {
    template = "${data.template_file.test.rendered}"
  }

  provisioner "local-exec" {
    command = "echo \"${data.template_file.test.rendered}\" > ${var.filename}"
  }
}
```

**Comment by kwilczynski** [comment]
@sbourlon if you look at the bottom of my reply, you will get an idea what the `filename` is used for, also pay attention to the multi-part payload content, example:

```
Content-Disposition: attachment; filename=cloud-config.cfg
```

I think, we need to update documentation to mention that this data source would not save anything locally, and the `filename` is only valid within the `part` section, which in turn is used for the multi-part payload.

For posterity: https://help.ubuntu.com/community/CloudInit

**Comment by sbourlon** [comment]
Thanks @kwilczynski for your patience and clarification :-)

I was indeed able to write my user-data locally thanks to your example and convert it into an ISO.

**Comment by kwilczynski** [comment]
@sbourlon any time! If you have any other question, feel free to ask!

Also, apologies for previous message being so terse in details.

**Comment by keymon** [comment]
I did this approach, because I am not sure if that `echo` is safe for special chars:

```
variable "filename" {
  default = "container_env.json"
}

resource "null_resource" "test" {
  triggers {
      test = "${data.template_file.container_env.rendered}"
  }
  provisioner "local-exec" {
    command = "${format("cat <<\"EOF\" > \"%s\"\n%s\nEOF", var.filename, data.template_file.container_env.rendered)}"
  }
}
```

**Comment by kwilczynski** [comment]
@keymon good point, actually. Since it was just an example (with the `echo`) I didn't really thought much about escaling (shell-safe) the special characters.

**Comment by Remigius2011** [comment]
@keymon and @kwilczynski works like a charm! thanks. :+1:

In my case I had to use a template file in the module directory as follows (for reference - in case someone stumbles upon this thread):

    data "template_file" "interfaces" {
      template = "${file("${path.module}/my_template.tpl")}"
      vars {
        my_var = "my_value"
      }
    }

**Comment by ehaselwanter** [comment]
@sbourlon: do you have a complete example. especially on how you push out the iso to the vm ?

**Comment by flmmartins** [comment]
I bumped in this issue because I needed to generate a file and the pass it as an argument to a command I was going to execute locally.
After some researching, instead doing like this:

```
 provisioner "local-exec" {
    command = "${format("cat <<\"EOF\" > \"%s\"\n%s\nEOF", var.filename, data.template_file.container_env.rendered)}"
  }
```

I opted for:

```
resource "local_file" "saved-manifesto" {
  content = "${data.template_file.cluster-manifesto.rendered}"
  filename = "${local.cluster_manifesto_path}"
}

resource "null_resource" "run" {
  triggers {
    file = "${data.template_file.cluster-manifesto.rendered}"
  }

  provisioner "local-exec" {
    command = "cat ${local.cluster_manifesto_path}"
  }
}
```
