### ISSUE TITLE
vsphere provider fails to create multiple nested folders

### ISSUE THREAD

**Issue by jasonk** [hashicorp/terraform#8106]
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- vsphere_folder
### Terraform Configuration Files

``` hcl
resource "vsphere_folder" "ci-dev" {
  path = "DevOps/CI/Development"
  datacenter = "Datacenter"
} 

resource "vsphere_folder" "ci-prod" {
  path = "DevOps/CI/Production"
  datacenter = "Datacenter"
} 

resource "vsphere_folder" "ci-test" {
  path = "DevOps/CI/Test" 
  datacenter = "Datacenter"
} 
```
### Expected Behavior

Prior to applying this configuration, the DevOps folder already existed, and I expected that terraform would create the CI folder and then the three subfolders.
### Actual Behavior

The CI folder was created, and the Test folder was created underneath it, but errors were thrown for the other two, because apparently terraform tried to create the parent folder three times:

```
2 error(s) occurred:

* vsphere_folder.ci-prod: Failed to create folder at DevOps/CI; ServerFaultCode: The name 'CI' already exists.
* vsphere_folder.ci-dev: Failed to create folder at DevOps/CI; ServerFaultCode: The name 'CI' already exists.
```
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

Provisioning against vSphere 5.5, but otherwise a pretty standard setup.

**Comment by sitle** [comment]
I have the same issue with VSphere 6.

**Comment by palmertime** [comment]
I have same issue.

VSphere 6.5
Terraform v0.8.8
