### ISSUE TITLE
aws_s3_bucket: Removing lifecycle_rule fails

### ISSUE THREAD

**Issue by asicoe** [hashicorp/terraform#8113]
Hi,

Terraform POSTs the "<LifecycleConfiguration></LifecycleConfiguration>" xml when a lifecycle policy is removed - this is wrong according to http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html which states that there are required xml tags/fields.

### Terraform Version
terraform -v
Terraform v0.6.16

### Affected Resource(s)
- aws_s3_bucket

### Terraform Configuration Files

```hcl
# Step 1: Initial config that got deployed successfully.
resource "aws_s3_bucket" "logs" {
    bucket = "bucket-xxx"
    acl    = "log-delivery-write"
    lifecycle_rule {
        id = "lcr-1"
        prefix = ""
        enabled = true
        transition {
            days = 30
            storage_class = "STANDARD_IA"
        }
        transition {
            days = 90
            storage_class = "GLACIER"
        }
        abort_incomplete_multipart_upload_days = 7
    }
}
```

```hcl
# Step 2: Reverted the policy changes which fails the terraform deploy.
resource "aws_s3_bucket" "logs" {
    bucket = "bucket-xxx"
    acl    = "log-delivery-write"
}
```

### Debug Output
https://gist.github.com/asicoe/034a1fc105bd958fa1a8eb07e6216440

### Expected Behavior
Terraform should have had a successful run and change the S3 bucket configuration by removing the lifecycle policy.

### Actual Behavior
Terraform failed the run and did not remove the lifecycle policy from the S3 bucket.

### Steps to Reproduce
1. `terraform apply` for the first terraform hcl above.
2. `terraform apply` for the second terraform hcl above.

**Comment by karoldrazek** [comment]
Issue still persists in version v0.7.4
