### ISSUE TITLE
Crash Log: Terraform State Show Wildcard

### ISSUE THREAD

**Issue by jvasallo** [hashicorp/terraform#8117]
Hi folks,

Got a crash trying to use the `terraform state show` using a wildcard character. Not sure if this issue has been reported but I figured I'd submit it just in case as per the output.

### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
This is an issue against the `terraform state show` command. If I put a wildcard, TF appears to crash.

### Terraform Configuration Files
N/A

### Debug Output
Refer to crash.log

### Panic Output
https://gist.github.com/jvasallo/971294da2525ef311299bd9ca17798c7

### Expected Behavior
Not exactly sure, but I would have suspected show of all the resources that match the top level resource. At the very least it should toss an error instead of crash?

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform state list aws_security_group.*`

### Important Factoids
N/A

### References
N/A

**Comment by EcofitBrendan** [comment]
I have also encountered this issue.

**Comment by mitchellh** [comment]
I'm having trouble reproducing on master so this may have been fixed. Your stack trace no longer matches reasonable lines in master where it happened so I'm assuming it is fixed. I tried your exact case with the same resource type so hopefully! If you can repro on master _please_ correct me. Thanks!
