### ISSUE TITLE
crashed during terraform apply w/ panic: interface conversion: interface is nil, not *schema.Set

### ISSUE THREAD

**Issue by gosuri** [hashicorp/terraform#813]
Crash log - https://gist.github.com/gosuri/43e258c4f647c9dbfb2b

**Comment by svanharmelen** [comment]
I see the problem, but this solution also prevents the set count (.#) to be written to the state... So it would be better to have something like this:

```
254: k := strings.Join(addr, ".")
255:
256: if value == nil {
257:    w.result[k+".#"] = "0"
258:    return nil
259: }
```

If your up to refactor this it's all yours, otherwise I'll put something like this in a few...

Thx!
