### ISSUE TITLE
Support AWS Application Load Balancers (ALB)

### ISSUE THREAD

**Issue by tpounds** [hashicorp/terraform#8137]
AWS just announced Layer 7 load balancing. According to the FAQ provisioning an Application Load Balancers requires calling new APIs so a new top-level resource will need to be created.

see:
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/
https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/faqs/

**Comment by catsby** [comment]
We'll see what we can do 😉

**Comment by jen20** [comment]
I'm working on this at the moment - expecting to have it in time for 0.7.1.

**Comment by kamoljan** [comment]
@jen20 where do you think you can make it?

**Comment by anosulchik** [comment]
@jen20 THanks for update, looking forward to start using it will terraform.

**Comment by catsby** [comment]
> @jen20 where do you think you can make it? 

It's in the works right now, though we don't promise any timelines on deliveries in general. As soon as we can!

**Comment by robmorgan** [comment]
thanks guys! looking forward 👍

**Comment by llarsson** [comment]
Just going to write the word "elb" here to make this issue show up in searches for that term. ;)

**Comment by stekershaw** [comment]
It may be implied but just to be safely explicit: the _ecs_aws_service_ resource would ideally also support the new _Application Load Balancers_.

**Comment by catsby** [comment]
@stekershaw that may not come in the initial Application Load Balancers PR, but it will follow shortly, same for integrating the new ALBs with AutoScaling Groups

**Comment by morgante** [comment]
What's the status of this?

**Comment by bronislav** [comment]
@morgante Terraform 0.7.1 added ALB support

**Comment by radeksimko** [comment]
@bronislav correct, ALB is supported in `0.7.1`. [ECS integration](https://github.com/hashicorp/terraform/pull/8190) is coming, besides that Terraform should now support all the ALB related functionality.

Do let us know if you find any other missing features or bugs in ALB related resources. I'd close this issue once we merge that linked ECS PR.

**Comment by kamoljan** [comment]
@bronislav and @radeksimko thank you guys!

**Comment by kesor** [comment]
Notably missing from 0.7.1 is support for target groups in AutoScaling, this is quite essential.
https://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_AttachLoadBalancerTargetGroups.html

**Comment by radeksimko** [comment]
@kesor I believe this is already supported, see https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#target_group_arns

**Comment by kesor** [comment]
@radeksimko awesome! guess I missed seeing it in the changelog.

**Comment by kesor** [comment]
The `alb_target_group` should support `tag` or `tags` like `aws_elb` does.

**Comment by stack72** [comment]
Hi @kesor you are correct - I have opened another issue to track the work on that

#8420

Going to close this for now and make all followup work separate :)

P.
