### ISSUE TITLE
Add support for the new Amazon Application Load Balancer (ALB)

### ISSUE THREAD

**Issue by josh-padnick** [hashicorp/terraform#8138]
AWS [just announced](https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/) the Application Load Balancer, or ALB. This is a significant improvement on the classic ELB and makes working with ECS a lot nicer.

The ALB appears to be already available through the AWS Web Console, but I don't see it in any of the SDKs or awscli yet, but I'm sure they'll release those updates soon.

**Comment by abtreece** [comment]
+1 (quick draw @josh-padnick)

**Comment by tpounds** [comment]
Duplicates #8137.

**Comment by josh-padnick** [comment]
Looks like @tpounds and I submitted this at the same time! Closing in favor of #8137.
