### ISSUE TITLE
core: names produced via name_prefix should start with a timestamp

### ISSUE THREAD

**Issue by glasser** [hashicorp/terraform#8143]
This looks similar to #494 but is not the same.

Many resources have a `name_prefix` attribute which uses `resource.PrefixedUniqueId` to generate random names for their resources.  This function adds 26 random base32 characters after the prefix.

This works really well. But because the varying part is truly random, it's difficult (when, eg, looking at a list of ASGs in the EC2 console) to know which one is the "new one" and which one is the "old one".

I propose that the varying string returned by `resource.PrefixedUniqueId` should begin with a UTC timestamp like 20160811105022 before a shorter random portion.  This is only calculated when a new ID is required (it doesn't present ignore_changes issues like in #494).  This should ensure that in most practical situations, you can tell which resource is "new" vs "old" just by sorting their names.

I don't think there's real backwards compatibility concerns here, as long as the lengths are the same. I assume that the names generated here are rarely shown to end users of your infrastructure so it's unlikely to reveal secrets.

Happy to send a PR for this if it would be accepted.

**Comment by mitchellh** [comment]
I agree with this, if you can make a PR that'd be lovel.

**Comment by glasser** [comment]
@mitchellh Done, https://github.com/hashicorp/terraform/pull/8249.
