### ISSUE TITLE
Concat in output

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#8148]
Any suggestions around how to get concat working in output. Ive a multi count resource and want to output the name tag and IP.

output "CACH01" {
  value = "${concat(aws_instance.CI03T02QCACH._.tags.Name}","${aws_instance.CI03T02QCACH._.private_ip)}"
}

**Comment by KevinBusse** [comment]
Are you using terraform 0.7.0? `concat()` interpolation function can no longer be used to join strings.

You should yield the expected results with:

    output "CACH01" {
      value = "${aws_instance.CI03T02QCACH..tags.Name}${aws_instance.CI03T02QCACH..private_ip}"
    }

**Comment by davyt10** [comment]
Yes, I am using 0.7.0 and your suggestion does work but it kind of clunky that there is no way to iterate through more than 1 instance. I am having to do;

output "CACH01" {
  value = ["${aws_instance.DV03T02QCACH.0.tags.Name} Private IP -   ${aws_instance.DV03T02QCACH.0.private_ip}"]
}
output "CACH02" {
  value = "${aws_instance.DV03T02QCACH.1.tags.Name} Private IP -   ${aws_instance.DV03T02QCACH.1.private_ip}"
}
output "CACH03" {
  value = "${aws_instance.DV03T02QCACH.2.tags.Name} Private IP -   ${aws_instance.DV03T02QCACH.3.private_ip}"
}

**Comment by mitchellh** [comment]
Please ask usage questions on the mailing list or chat rooms. The issues [as you've found] are not a good place to go for quick feedback! We get dozens of issues per day and we're generally triaging them and focused on fixing bugs or improving TF. Finding the time to respond to Q&A in issues is diffulclt. Sorry :(
