### ISSUE TITLE
aws_spot_fleet_request crashes when launch_specification contains only subnet_id and not availability_zone

### ISSUE THREAD

**Issue by borgstrom** [hashicorp/terraform#8150]
Hi,

Given the following:

```
resource "aws_spot_fleet_request" "packer" {
    lifecycle {
        create_before_destroy = true
    }

    iam_fleet_role = "${aws_iam_role.spot_fleet.arn}"
    target_capacity = 1
    spot_price = "0.001"
    valid_until = "2017-01-31T17:00:00Z"
    terminate_instances_with_expiration = false

    launch_specification {
        instance_type = "c3.large"
        spot_price = "0.105"
        ami = "ami-a52ab4b2"
        subnet_id = "${element(data.terraform_remote_state.vpc.private_subnet_ids, 0)}"
        key_name = "nw-prod"
        vpc_security_group_ids = ["${aws_security_group.ecs_sg.id}"]
    }
}
```

Results in a crash during application, but the fleet is actually created.

```
* aws_spot_fleet_request.packer: unexpected EOF
2016/08/11 15:17:29 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

By simply adding `availability_zone = "${element(data.terraform_remote_state.vpc.azs, 0)}"` then the apply succeeds.

Per the docs we should be able to supply just a subnet ID: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-examples.html#fleet-config2

PS.  It would GREAT if `launch_specification` supported count so we can map it to our subnets.

**Comment by stack72** [comment]
Hi @borgstrom 

Apologies that is is causing you some pain - I am currently working on this

https://github.com/hashicorp/terraform/pull/8320

Please note that my work will not include the count addition to launch_configuration - this isn't supported outside of top level resources atm

Paul
