### ISSUE TITLE
State always needs refresh

### ISSUE THREAD

**Issue by justin8** [hashicorp/terraform#8152]
When creating a large security group (in this case 25 IPs) it always thinks it needs to refresh/change the security group on every plan/apply, regardless of there being no changes. I'm getting them from a comma seperated variable and setting the cidr_blocks using the split function.
### Terraform Version

0.6.616
### Affected Resource(s)
- aws_security_group
### Terraform Configuration Files

```
resource "aws_security_group" "allow-from-vpn" {
    name = "allow-from-vpn"
    description = "Allow traffic from the VPN"
    vpc_id = "${aws_vpc.vpc.id}"

    ingress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["${split(",",var.allow_from_vpn)}"]
    }
}

variable "allow_from_vpn" {
    type = "string"
    description = "A comma seperated list of CIDR blocks to allow access to resources in the VPC. Default to SEA/FRA/DUB/SYD VPN endpoints"
    default = "1.1.1.1/32,2.2.2.2/32,3.3.3.3/32,4.4.4.4/32,5.5.5.5/32,6.6.6.6/32,7.7.7.7/32,8.8.8.8/32,9.9.9.9/32"
}
```

Actual IP list is of real corporate IPs and I didn't want to share them, but there are 25 in the list in total
### Expected Behavior

After initial apply no more changes are seen when nothing is being changed
### Actual Behavior

The security group is refreshed every single time and makes it hard to see what changes are actually going to apply
### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @justin8 

The is by default. The apply (and plan) command has the ability to not refres

`terraform apply -refresh=false`

Paul

**Comment by justin8** [comment]
@stack72 Why does this only seem to happen to a security group and a launch configuration while the other 30+ resources are only applied once?

Just to be clear, I'm not talking about apply picking up changes or something that weren't in plan, even in `terraform plan` it shows that it is going to change a security group like this:

```
module.vpc.aws_security_group.allow-from-vpn: Modifying...
  ingress.2314205417.cidr_blocks.#:     "25" => "0"
  ingress.2314205417.cidr_blocks.0:     "1.1.1.1/32" => ""
...
  ingress.2314205417.cidr_blocks.24:    "2.2.2.2/32" => ""
  ingress.2314205417.from_port:         "0" => "0"
  ingress.2314205417.protocol:          "-1" => ""
  ingress.2314205417.security_groups.#: "0" => "0"
  ingress.2314205417.self:              "false" => "false"
  ingress.2314205417.to_port:           "0" => "0"
  ingress.3461317177.cidr_blocks.#:     "0" => "25"
  ingress.3461317177.cidr_blocks.0:     "" => "1.1.1.1/32"
...
  ingress.3461317177.cidr_blocks.24:    "" => "2.2.2.2/32"
  ingress.3461317177.from_port:         "" => "0"
  ingress.3461317177.protocol:          "" => "-1"
  ingress.3461317177.security_groups.#: "0" => "0"
  ingress.3461317177.self:              "" => "false"
  ingress.3461317177.to_port:           "" => "0"
```

All 25 IPs are the same and in the same order

**Comment by justin8** [comment]
So I've done some further testing on this.

I removed the variable expansion and statically added the array to the state file and the issue remains.

It seems to work as expected up to 23 IP addresses, as soon as I add the 24th or 25th IP it will recreate the group every single time.

It seems to depend on the IP being added as well. if I use a different IP address it doesn't try to recreate it

**Comment by mitchellh** [comment]
Its been awhile and this looks like an AWS provider bug.

We've had almost 20 releases since this though so if you could try again and open a new issue if it still works that'd great. sorry!
