### ISSUE TITLE
Terraform state show crashes

### ISSUE THREAD

**Issue by prateek2408** [hashicorp/terraform#8154]
Hi there,

### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
- openstack_instance

### Panic Output
terraform state show
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x4bc772]

goroutine 1 [running]:
panic(0x33b5860, 0xc8200100c0)
        /opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/terraform/command.(*StateShowCommand).Run(0xc8200abb00, 0xc82000a160, 0x0, 0x0, 0xc8201bb130)
        /opt/gopath/src/github.com/hashicorp/terraform/command/state_show.go:53 +0x702
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200b0d80, 0xc82026c630, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:153 +0x56e
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:144 +0xaf9
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:80 +0xa10
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:23 +0x28

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Expected Behavior
it should show the state of the resources 

### Actual Behavior
It crashed 

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy'
3. `terraform state show`

**Comment by jbardin** [comment]
Fixed via #8164
