### ISSUE TITLE
Lifecycle hook with notification target sqs in another region

### ISSUE THREAD

**Issue by MightyPixel** [hashicorp/terraform#8159]
Hi there,
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- aws_autoscaling_lifecycle_hook
- aws_sqs_queue
### Terraform Configuration Files

```
resource "aws_sqs_queue" "graceful_termination_queue" {
  name = "graceful_termination_queue"
}

resource "aws_autoscaling_lifecycle_hook" "graceful_shutdown_asg_hook" {
  provider = "aws.eu_uk"

  name = "graceful_shutdown_asg"
  autoscaling_group_name = "${aws_autoscaling_group._auto_scaling.name}"
  default_result = "CONTINUE"
  heartbeat_timeout = 360
  lifecycle_transition = "autoscaling:EC2_INSTANCE_TERMINATING"
  notification_target_arn = "${aws_sqs_queue.graceful_termination_queue.arn}"
  role_arn = "${aws_iam_role.autoscaling_role.arn}"
}
```
### Expected Behavior

Create a lifecycle hook that posts in the sqs queue
### Actual Behavior

The interpolated arn is correct. The creation of the lifecycle hook doesn't end.
### Steps to Reproduce
1. `terraform apply`

**Comment by joshpurvis** [comment]
I ran into this as well. I don't believe the problem is with Terraform specifically, but rather something to do with the assumed role not having access to the autoscaling service.

To fix, you basically just need to add a `Service` section for `autoscaling.amazonaws.com`, as well as the `ec2.amazonaws.com` that's probably already in your `aws_iam_role`. Mine looks something like this now:

```
resource "aws_iam_role" "asg-role" {
    name = "asg-role"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    },
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "autoscaling.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}
```

**Comment by jjshoe** [comment]
@joshpurvis you can clean that up a bit:

`
resource "aws_iam_role" "asg-role" {
    name = "asg-role"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": [
          "ec2.amazonaws.com",
         "autoscaling.amazonaws.com"
        ]
      },
      "Effect": "Allow",
      "Sid": ""
    }
POLICY
}
`
