### ISSUE TITLE
Make updatedeps while on any branch switches to master branch

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#816]
At some point during `make updatedeps`, we are getting switched to master branch.
Caused a lot of headaches on the subsequent `make dev` spitting different binaries than the ones we assumed were being built.

**Comment by mitchellh** [comment]
This is `go get` doing this. I actually don't know how to prevent it from doing this... let me play around and see if I can get something to work.

**Comment by mitchellh** [comment]
I did some shell-fu in the Makefile and hopefully this works?

**Comment by knuckolls** [comment]
Confirmed that this works. Thanks for the fix.

**Comment by pmoust** [comment]
:+1:
