### ISSUE TITLE
Provisioner SSH connection is failin after upgrading to v0.7.0

### ISSUE THREAD

**Issue by jkopacze** [hashicorp/terraform#8160]
Hi there,

After upgrading Terraform version from  v0.6.16  to v0.7.0 my ec2 module suddenly stopped connecting to the instance by SSH while using provisioner connection.

### Terraform Version
Terraform v0.7.0
Terraform v0.7.1-dev (e251d5c7bd39699ea55daeb9585f11d862176049)

### Affected Resource(s)

- provisioner "remote-exec"
- provisioner "chef"
-  ... ( probably all provisioners )

### Terraform Configuration Files
```hcl

    provisioner "remote-exec" {
        inline = [
          "sleep 2",
          "sudo apt-get update",
          "sudo apt-get install curl --yes"
        ]
       connection {
            user = "${var.ssh_admin}"
            host = "${self.public_ip}"
    //        bastion_host = "${var.bastion_host}"
    //        bastion_port = "${var.bastion_port}"
    //        bastion_user = "${var.bastion_user}"
        }
    }

// Connection
variable "ssh_admin" { default = "admin" }
variable "bastion_host" { default = "xx.xx.xx.xx" }
variable "bastion_port" { default = 22 }
variable "bastion_user" { default = "admin" }

```

### Debug Output
...
module.ec2_bastion.aws_instance.one_instance: Still creating... (1m30s elapsed)
2016/08/12 15:15:42 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2016/08/12 15:15:42 connecting to TCP connection for SSH
module.ec2_bastion.aws_instance.one_instance (remote-exec): Connecting to remote host via SSH...
module.ec2_bastion.aws_instance.one_instance (remote-exec):   Host: xx.xx.xx.xx
module.ec2_bastion.aws_instance.one_instance (remote-exec):   User: admin
module.ec2_bastion.aws_instance.one_instance (remote-exec):   Password: false
module.ec2_bastion.aws_instance.one_instance (remote-exec):   Private key: false
module.ec2_bastion.aws_instance.one_instance (remote-exec):   SSH Agent: true
2016/08/12 15:15:42 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2016/08/12 15:15:42 handshaking with SSH
2016/08/12 15:15:44 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2016/08/12 15:15:44 handshake error: ssh: handshake failed: ssh: unexpected message type 1 (expected 52)
2016/08/12 15:15:44 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2016/08/12 15:15:44 Retryable error: ssh: handshake failed: ssh: unexpected message type 1 (expected 52)
....

### Expected Behavior
The same code ran on  Terraform v0.6.16

### Actual Behavior
Error applying plan:

1 error(s) occurred:

* ssh: handshake failed: ssh: unexpected message type 1 (expected 52)

### Steps to Reproduce
`terraform apply`

### Important Factoids
Standard VPC deployment

**Comment by jbardin** [comment]
Hi @jkopacze

The ssh message type 1 is a simply a disconnect, which was happening during the auth handshake. It's kind of hard to tell what was going on from the output here, is there any information in the server auth logs?

**Comment by swinterberger** [comment]
How many ssh keys do you have added to your agent? The max is five by default I believe. Try re-adding your bastion key to the ssh agent or clearing the ones currently set.

**Comment by jkopacze** [comment]
Right, this may be it as I might have 6 keys there.
Unfortunately will be able to test it earlier on Thursday. Thanks for your suggestion, will keep you posted!

Jerzy

**Comment by svanharmelen** [comment]
@jkopacze any updates on this? Did you manage to test/confirm if this was due to the number of SSH keys added to your agent?

Thx!

**Comment by jkopacze** [comment]
Yes  @svanharmelen, you were right as I had 6 keys in use.
Bdw ... where is this limit coming from ? 

I'm closing this case.
Thanks!
Jerzy

**Comment by svanharmelen** [comment]
Thanks for closing the issue!

And I'm not sure, maybe @swinterberger knows as he was the one smart enough to think about this :wink:
