### ISSUE TITLE
Support for Application ELB

### ISSUE THREAD

**Issue by llarsson** [hashicorp/terraform#8182]
Hello Terraform!

AWS released [AWS Application Load Balancer](https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/) on August 11th, and it would be great to manage these directly via Terraform.

**Comment by radeksimko** [comment]
Hi @llarsson 
see https://github.com/hashicorp/terraform/issues/8137 which was raised last week. That's where we track the progress & interest.

Closing as duplicate. 😉
