### ISSUE TITLE
Include/Glob directories from command line?

### ISSUE THREAD

**Issue by robrankin** [hashicorp/terraform#8186]
It’d be quite useful to be able to include a set of TF files from a directory specified on the command line.

In our case, we’ve developed a set of modules that describe various resources in Azure; some storage accounts, a virtual network, sets of VMs or Scale Sets, and some network connectivity (peering or VPN gateways).  All together this forms the base of an environment.  The only real differences are in the size and count of VMs in the set/scale sets, network ranges, domain name info, peering config, etc.

The specific differences between environments have been abstracted out of the main templates into sets of TF override files.

Obviously, in order to utilize these override files, they need to be in the same directory as the TF templates they’re overriding.

However, keeping them in the same directory can’t be done as it's a different set of overrides per environment.  Separation of code and config basically.

We’re using Makefiles and symlinks/file copying currently, but would prefer a TF native solution.

Therefore, it’d be quite useful to be able to specify a directory of TF files to “include”, something like:

`terraform plan -include-dir=../../../Configs/overrides`

Would also be quite useful if the `-var-file` parameter would take a directory, similar reasons to above.

Any plans on this?

**Comment by mitchellh** [comment]
When we do the general include functionality for TF config files I think adding this would make sense!
