### ISSUE TITLE
Refresh state by default prior to (un) tainting resource

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#8188]
Both `apply` and `destroy` commands/operations by default perform refresh prior to applying changes and allow the user to disable this behaviour via `-refresh=false` flag.

`taint`/`untaint` commands do not refresh the state which could potentially lead to tainting a resource which is gone or tainted or generally out of sync in any other way.

Basically this is what I'd expect from `terraform untaint/taint` by default:

```
terraform refresh
terraform untaint/taint ...
```

Are there any reasons why not do this? If not I'd be happy to implement it & send a PR.

---

Theoretically `import` command IMO _should_ do refresh prior to importing the resource, but that's probably a topic for a separate discussion.

**Comment by mitchellh** [comment]
Is there a benefit to this since running `apply` on a tainted resource will find it gone very quickly anyways? I don't mind the idea but I also just want to understand the "why?" further.

**Comment by artburkart** [comment]
Was there any more thought on this one? Is it worth implementing? The "why" for me would be more consistent behavior, but I don't actually know if that's a priority (of any value) for the terraform community.

**Comment by radeksimko** [comment]
This is mostly to prevent cases where the resource doesn't exist anymore (in reality), yet still remains in the state. In such case user is able to successfully taint the resource to find out later that it wasn't necessary during `apply`.

Looking back now I'm feeling the value added may be low for most users, so I'm happy to close this issue.

**Comment by jbardin** [comment]
Closing out old issues. The `taint` command is remaining a state-only operation for now. Viewing the plan will indicate if `taint` is necessary.

Thanks!
