### ISSUE TITLE
Proposal: naming convention provider / datasource

### ISSUE THREAD

**Issue by yawn** [hashicorp/terraform#8193]
Think out loud: what do you guys think about manifesting a *naming convention* (or multiple ones) in Terraform? In no particular order features would be:

1. ability to configure a naming convention that consists out of certain fixes parts (such as `Customer` or `Environment`) as well as dynamic parts (maybe derivable from resources themselves?)
* allow the parts to be reused / exported as attributes (e.g. for usage as AWS tags)
* Use whitelists and/or regular expressions as value constraints for the parts
* Export full names matching various constraints (e.g. parts joined by underscores or dashes, parts restricted to up to 64 chars etc.)
* Maybe extend Terraform to allow variable interpolation in resource names

This would eliminate a number of bugs in environments where names matter (e.g. AWS) and make it easier to formalize infrastructure conventions. It could also be used to formalize the current process of auto-generating names and descriptions for (some) resources.

**Comment by mitchellh** [comment]
This is quite clever. I like the idea.

I think there are some fundamental blockers for it at the moment that I don't think we plan on addressing soon, but if you have ideas for ways around them I'm all ears! Fundamentally, the biggest issue is that Terraform doesn't have a way to have "dynamic" outputs from a data source (or resource).

Actually, one way around this would be potentially coming up with a common prefix and just using that.

I think ultimately at this point in time this is best left to individual organizations if they find it important to implement (very simple). There are core issues around that want dynamic variables (whose values can come from resource interpolations and such) to be available. That would provide a very easy stopgap to this as well.
