### ISSUE TITLE
AWS: Role for Cross-Account Access support

### ISSUE THREAD

**Issue by pdakhane** [hashicorp/terraform#8196]
Any idea if and when AWS: Role for Cross-Account Access" in Terraform's IAM resource "aws_iam_role" will be supported in Terraform???

**Comment by geekifier** [comment]
This is currently supported. We use it extensively in an MSP environment. You simply create an IAM role, and assign the appropriate assume_role_policy.

`resource "aws_iam_role" "MSPAdmin" {
  name = "MSP-Admin"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Principal": {
      "AWS": "arn:aws:iam::ACCOUNT_NUMBER_HERE:root"
    },
    "Action": "sts:AssumeRole"
  }
}
EOF
}`

**Comment by mitchellh** [comment]
Closing since @geekifier is a hero.
