### ISSUE TITLE
Bug in docs - aws_ebs_volume size is in GiB, not GB as stated

### ISSUE THREAD

**Issue by ttmc** [hashicorp/terraform#8198]
### Terraform Version
Terraform v0.7.0 (and the online Terraform documentation as of minutes before I posted this)

### Affected Resource(s)
- aws_ebs_volume

### Terraform Configuration Files
```hcl
resource "aws_ebs_volume" "db_storage" {
  type = "gp2"
  availability_zone = "eu-central-1b"
  size = 40
}
```

### Expected Behavior
An EBS volume of size 40 GB, as stated in the documentation at https://www.terraform.io/docs/providers/aws/r/ebs_volume.html

### Actual Behavior
An EBS volume of size 40 GiB, not 40 GB, according to the EC2 web console.

### Steps to Reproduce
1. `terraform apply`
2. Look at what got created in the EC2 web console

### Important Factoids
https://en.wikipedia.org/wiki/Gibibyte

**Comment by stack72** [comment]
Hi @ttmc 

Thanks for pointing out the error here. I have just opened #8240 to fix this :)

Paul
