### ISSUE TITLE
SSH Connection Refused when using template_cloudinit_config instead of template_file

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#8201]
### Terraform Version
0.7.1-dev (master branch)

### Affected Resource(s)
- template_cloudinit_config

### Terraform Configuration Files
```hcl
data "template_file" "cloudconfig" {
  template = "${file("cloud-config.yml")}"
}

data "template_cloudinit_config" "cloudconfig" {
  gzip          = false
  base64_encode = false

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.cloudconfig.rendered}"
  }
}
```

### Expected Behavior
Able to ssh to the ec2 instance

### Actual Behavior
Unable to ssh to the ec2 instance when using this setup.  If I switch back to the old `template_file` resource, everything behaves normal again.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
* Running within VPC

### References
Not as I can find.

**Comment by apparentlymart** [comment]
Hi @iceycake! I'm sorry things didn't work out for you here.

I'm understanding that you've found that setting the EC2 instance `user_data` to just a standalone YAML file works as you expected, but when you wrap it in a multipart MIME payload using `template_cloudinit_config` it is no longer behaving as you want.

If possible, it would be helpful if you could share what's appearing in the EC2 instance system log in the case where it doesn't work. You can find the log via the EC2 console here:
![ec2_instance_log](https://cloud.githubusercontent.com/assets/20180/17684436/7f9b8c02-6310-11e6-8fb7-e8cf0954e99d.png)

Within that log you should find log entries related to `cloud-init` which I'm hoping will include some indication of what problem was encountered when parsing the multipart MIME form.

If you *do* share the log here on github, please be sure to check and filter any sensitive information the system may have logged while it booted. (SSH key info, access keys, information about your VPC's private IP ranges, etc.)

**Comment by iceycake** [comment]
Nothing is really interesting in the system log (at least for me) ...

Here is a copy of it:

https://gist.github.com/iceycake/25eff06ce492d1f3e53bfe964c0c5c0a

**Comment by apparentlymart** [comment]
I can infer from your output that you're using CoreOS... I don't have much experience with that, but I notice that CoreOS has its own alternative to [cloud-init](https://cloudinit.readthedocs.io/en/latest/), called [cloud-config](https://coreos.com/os/docs/latest/cloud-config.html). It seems like cloud-config's config is *inspired by* cloud-init, but not 100% compatible with it.

I found coreos/bugs#912 which suggests that cloud-config does not support MIME multipart configurations in the same way that cloud-init does. Thus I think that `template_cloudinit_config` is not compatible with cloud-config and you should probably just stick with using `template_file` directly.

**Comment by iceycake** [comment]
I see.  Thanks for the explanation.  In that case, I will just use the `template_file` data source without using `template_cloudinit_config` data source.

**Comment by blurrcat** [comment]
That's the path I've taken. But with `template_file` you can't gzip it and it's easy to hit the size limit of user data. Any chance that #3858 can be merged any time soon?

Meanwhile Is there any workaround here?
