### ISSUE TITLE
Spot fleet request failed with compatible availability zone and subnet

### ISSUE THREAD

**Issue by qnu** [hashicorp/terraform#8203]
With Terraform v0.7.0, we got following error messages when request spot fleet.

* aws_spot_fleet_request.chunkserver.1: Error requesting spot fleet: [WARN] Error creating Spot fleet request, retrying: InvalidSpotFleetRequestConfig: The specified Subnet: subnet-XYZ cannot be used with the specified Availability Zone: us-west-2a.

While subnet-XYZ and us-west-2a is our default settings when we use WebUI and command tools to request spot fleet and they worked. But it failed with Terraform. TF_LOG=TRACE also shows the request string contains the correct availability zone and subnet id.

**Comment by stack72** [comment]
Hi @qnu 

sorry this is causing you some pain - I am currenltly working on this

https://github.com/hashicorp/terraform/pull/8320

Paul

**Comment by qnu** [comment]
Thank you!
Do you have a plan for minor release including this fix? We are kind of depending on spot fleet for our routine operations so we don't have to wait until next major release.

Nan

**Comment by qnu** [comment]
@stack72 I installed terraform v0.7.2, but this issue still exists.

**Comment by stack72** [comment]
Hi @qnu I am trying to reproduce this right now

P.

**Comment by stack72** [comment]
Hi @qnu 

i have been able to run with the following:

```
resource "aws_vpc" "foo" {
    cidr_block = "10.1.0.0/16"
}

resource "aws_subnet" "foo" {
    cidr_block = "10.1.1.0/24"
    vpc_id = "${aws_vpc.foo.id}"
    availability_zone = "us-west-2a"
}

resource "aws_spot_fleet_request" "foo" {
    iam_fleet_role = "${aws_iam_role.test-role.arn}"
    spot_price = "0.005"
    target_capacity = 4
    valid_until = "2019-11-04T20:44:20Z"
    terminate_instances_with_expiration = true
    launch_specification {
        instance_type = "m3.large"
        ami = "ami-d0f506b0"
        key_name = "${aws_key_pair.debugging.key_name}"
	subnet_id = "${aws_subnet.foo.id}"
	availability_zone = "us-west-2a"
    }
    depends_on = ["aws_iam_policy_attachment.test-attach"]
}
```

And I do not get such an error, notice that I am using both a subnet_id *and* an availability_zone

Paul

**Comment by qnu** [comment]
@stack72 Just sent you an email with large trace log. Please take a look at it.
