### ISSUE TITLE
Detect changes to module sources and warn about stale modules

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#8214]
Terraform does not provide a mechanism for ensuring a developer has the most updated version of modules referenced in their Terraform configuration. Determining _up-to-date_ might be problematic, but at the very least Terraform should detect changes to a module's source and then warn or error out if the source has changed since the last time a module was downloaded with `terraform get -update`. This allows the use of `?ref=<tag_or_sha>` to _pin_ module versions and allow developers to get notified of stale downloaded modules if the module source changes.
### Terraform Version

Terraform v0.7.0 and previous.
### Affected Resource(s)

`module`
### Terraform Configuration Files

``` hcl
module "instance" {
  source = "git::ssh://git@github.com/clstokes/example-terraform-module-instance.git?ref=t2.medium"
}

output "id" {
  value = "${module.instance.instance_id}"
}
```
### Actual Behavior

I can change a module's source to anything, even an invalid URL, and Terraform will not indicate anything.
### Ideal Behavior

Ideally, Terraform would warn and exit with an error if a module's source had changed without a `get -update` being performed.
### Steps to Reproduce
1. `terraform apply`
2. Change the module source to `source = "asdf"` or `source = "<url>?ref=other`.
3. `terraform apply` and see Terraform use the _old_ module version.

**Comment by mitchellh** [comment]
Ah, this was fixed a few versions ago! :)
