### ISSUE TITLE
Unused commented variables must still be declared

### ISSUE THREAD

**Issue by cohenaj194** [hashicorp/terraform#8216]
When using a terraform if a terraform variable that is only called in comments is not declared terraform will produce errors and refuse to run.  

To fix this either the variable must be declared or any lines using that variable must be removed.

For example this will occur if I comment out the count in a `resource "aws_instance"`:

    resource "aws_instance" "example" {
        # count = ${var.count}
        ami = "ami-2d39803a"
        instance_type = "t2.micro"
        key_name = "keypair_name"
    }

Even if `${var.count}` is only used in commented sections of code `${var.count}` must be declared, otherwise terraform will refuse to complete a plan or apply.

**Comment by mitchellh** [comment]
I just used your exact example and couldn't reproduce this with master. It was either fixed or something else in your configuration is causing this. I get a full, normal plan:

```
+ aws_instance.example
    ami:                      "ami-2d39803a"
    availability_zone:        "<computed>"
    ebs_block_device.#:       "<computed>"
    ephemeral_block_device.#: "<computed>"
    instance_state:           "<computed>"
    instance_type:            "t2.micro"
    key_name:                 "keypair_name"
    network_interface_id:     "<computed>"
    placement_group:          "<computed>"
    private_dns:              "<computed>"
    private_ip:               "<computed>"
    public_dns:               "<computed>"
    public_ip:                "<computed>"
    root_block_device.#:      "<computed>"
    security_groups.#:        "<computed>"
    source_dest_check:        "true"
    subnet_id:                "<computed>"
    tenancy:                  "<computed>"
    vpc_security_group_ids.#: "<computed>"
```

If you can find a way to reproduce this consistently with a minimal config then please let me know. I tried a few different things locally to try to get it to go and couldn't. :(
