### ISSUE TITLE
Multiple var files with maps behaviour with 0.7.0

### ISSUE THREAD

**Issue by gwilym** [hashicorp/terraform#8219]
In updating some existing 0.6.x files to 0.7.x I'm running into a problem with multiple var files and maps. Previously I had one public vars file and one secret vars file, the result would be merged together for a full set, like so:

`a.tfvars`:

``` hcl
mymap.foo = "foo"
```

`b.tfvars`:

``` hcl
mymap.bar = "bar"
```

But when I've updated this to the newer syntax, it seems the merging behaviour has been lost. So this is either a bug report or a usage question, I'm not sure which. I looked but did not find documentation on this change coming into 0.7.x.

I believe I can work around this for now by using top level vars for secrets instead of trying to partially apply / marge a map like this, but I'd like to know the proper approach for this if this is not a bug.
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)

Terraform core
### Terraform Configuration Files

`test.tf`:

``` hcl
variable "mymap" {
  default = {
    foo = "DEFAULT"
    bar = "DEFAULT"
  }
}

output "foo" {
  value = "${var.mymap["foo"]}"
}

output "bar" {
  value = "${var.mymap["bar"]}"
}
```

`a.tfvars`:

``` hcl
mymap = {
  foo = "foo"
}
```

`b.tfvars`:

``` hcl
mymap = {
  bar = "bar"
}
```
### Debug Output

https://gist.github.com/gwilym/63bcab48720682e868043c5cc177f1cc
### Expected Behavior

```
$ terraform apply -var-file=a.tfvars -var-file=b.tfvars

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar = bar
foo = foo
```
### Actual Behavior

```
$ terraform apply -var-file=a.tfvars -var-file=b.tfvars

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar = bar
foo = DEFAULT
```
### Steps to Reproduce
1. `terraform apply -var-file=a.tfvars -var-file=b.tfvars` with the above files

If further information is required I'm happy to provide.

**Comment by gwilym** [comment]
For completeness, it should be noted that `map["KEY"] = assignment` is not available in tfvars:

```
mymap["bar"] = "bar"

=

invalid value "b.tfvars" for flag -var-file: Error parsing b.tfvars: At 1:6: expected: IDENT | STRING | ASSIGN | LBRACE got: LBRACK
```

While the previous syntax of `mymap.bar = "bar"` does not apply any change, with the output being:

```
bar = DEFAULT
foo = foo
```

**Comment by aurelienmaury** [comment]
+1

**Comment by pasc-ed** [comment]
+1

**Comment by mitchellh** [comment]
Have a fix queued up in referenced PR.
