### ISSUE TITLE
Lookup plan does not fail with missing variable

### ISSUE THREAD

**Issue by jeffastorey** [hashicorp/terraform#8234]
Running a `terraform plan` on an AWS security group rule that references an undefined variable still successfully creates a plan. In the example below, the variable named `somevariable` is missing the `var` - it should be `var.somevariable`. When the `var` is omitted, the plan still succeeds, but the apply fails. I don't think the plan should successfully be created when there is a syntax error.

```
resource "aws_security_group_rule" "dummy_rule" {
  security_group_id = "sg-xxxxxx"

  type = "egress"

  cidr_blocks = ["${split(",", lookup(somevariable, "string"))}"]
  protocol    = "tcp"
  from_port   = 1234
  to_port     = 1234
}
```

Terraform version is 0.6.16

**Comment by mitchellh** [comment]
This is fixed in 0.8
