### ISSUE TITLE
Feature Request: Support tags in spot fleet request and instances

### ISSUE THREAD

**Issue by wjiang-qc** [hashicorp/terraform#8237]
It would be great if we can add tags in the spot fleet request and the tags can also be carried over to the spot fleet instances after initially launched or re-spawned.

**Comment by stack72** [comment]
Hi @wjiang-qc 

This is a duplicate issue - there is a current PR open for this but unfortunately it isn't a scalable solution as there is no way to propagate tags to instances that are fulfilled

https://github.com/hashicorp/terraform/pull/4380

Thanks for getting in touch :)

Paul

**Comment by wjiang-qc** [comment]
@stack72 I am new to AWS and terraform, so I'm not sure if I understand it correctly. But the PR #4380 is to support tags in spot instance request, not the spot fleet request I wanted. The spot fleet support seems to be recently added in terraform 0.7.0. Can you clarify?

**Comment by stack72** [comment]
@wjiang-qc you are correct - reopening :)

**Comment by richardbowden** [comment]
hey, i needed this and created a patch a while back which i have been using myself, i have spruced it up a bit and committed to my fork to see if this would be an acceptable fix for this issue, see https://github.com/richardbowden/terraform/commit/62de4dcc6f5a44c12771ad6f800f1ff2e1e2604b i can create a pull request if required.

**Comment by defender** [comment]
+1

**Comment by ahaiong** [comment]
+1
