### ISSUE TITLE
default value hashing error for AWS block_device (schema error?)

### ISSUE THREAD

**Issue by buth** [hashicorp/terraform#824]
The  AWS `instance` resource allows for listing a set of block device mappings under `block_device`. I've run into an odd issue where if you do not specify the `delete_on_termination` attribute explicitly, the hash values computed from a Terraform file will never match one computed from the refreshed state.

In the case where you allow this attribute to be set to its default, you'll notice a line like this in the plan output.

```
block_device.1351955162.delete_on_termination: "" => "1" (forces new resource)
```

However if you look at the state file after applying the plan it reads slightly differently.

```json
"block_device.2966244962.delete_on_termination": "true"
```

Not only is the saved value of the attribute different but because that value is [included in the set hashing method](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L505) Terraform reads this as a different block device all together. The result is that Terraform will never acknowledge that it has already correctly created the resource.

As mentioned above, you can fix this by explicitly setting the attribute.

```
delete_on_termination = true
```

I'm not totally sure where the bug is here. The hashing function itself seems sound, and I can't account for the different result. It does seem that perhaps this is a larger issue with the schema code and not just an idiosyncrasy of this resource.

**Comment by mitchellh** [comment]
Notes: I would add a test in two places

* `TestResourceDataState` - To test that setting a bool in a set to `true` results in `"true"`
* `TestSchemaMap_Diff` - To test that the diff of a bool in a set results in `"true"` (instead of "1")

I expect the first will pass right now and the second will fail, but we want both tests in there to make sure we don't regress.

**Comment by egarbi** [comment]
Happening to me as well, as a workaround I need to run once with block defined and after that remove block_device from my code.
