### ISSUE TITLE
Add support for AWS elasticsearch service version

### ISSUE THREAD

**Issue by marcosnils** [hashicorp/terraform#8246]
Elasticsearch service now supports different ES versions

https://aws.amazon.com/about-aws/whats-new/2016/07/amazon-elasticsearch-service-now-supports-elasticsearch-2-3/

It'd be nice to have new API parameters so different versions can be managed through terraform.

**Comment by kwilczynski** [comment]
@marcosnils support for Elasticsearch version was added in #7860 (see #7836 for the discussion).

I believe it would be included in upcoming release.

**Comment by marcosnils** [comment]
@kwilczynski thx for pointing that out. Totally missed it.
