### ISSUE TITLE
Terraform show state crash when inspecting an aws_iam_policy_attachment

### ISSUE THREAD

**Issue by hamstah** [hashicorp/terraform#8255]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.7.0

### Affected Resource(s)

aws_iam_policy_attachment

### Terraform Configuration Files
```hcl
resource "aws_iam_policy_attachment" "attach_admin" {
    provider = "aws.ops"

    name = ""
    groups = [
      "${aws_iam_group.ops_admin.name}"
    ]
    policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

```

### Debug Output
https://gist.githubusercontent.com/hamstah/c61c571e0cfc247c4a8cf8d744fe9caa/raw/513ae9af96c778b6f7c13641e9de64828d7b2269/terraform%2520crash

### Panic Output
N/A

### Expected Behavior
I should see the state

### Actual Behavior
Crash

### Steps to Reproduce
1. create the resource with `terraform apply`
2. try to inspect it `TF_LOG=DEBUG terraform state show aws_iam_policy_attachment.attach_admin`

### Important Factoids
N/A

### References
N/A

**Comment by mitchellh** [comment]
I just tried reproducing this with master (effectively 0.7.1) and wasn't able to get a crash in any case. Can you please check if you're still getting this with the latest version and let me know? Thanks!

**Comment by hamstah** [comment]
Hey,

Unfortunately I can't reproduce the issue anymore, even with 0.7.0.
If it shows up again reliably I will give 0.7.1 a try.
Thanks
