### ISSUE TITLE
Terraform module pull failing on Gitlab repository

### ISSUE THREAD

**Issue by cprenzberg** [hashicorp/terraform#8256]
Hi guys,

I am having some errors pulling a module from a gitlab repository. I am running terraform 0.7.0

``` javascript
nnamdi@worklaptop:~/test/ide/geppetto-workspace/foo-portal$ terraform get -update

Get: git::ssh://git.nnamdi.com:practice/aws-dhcp-options.git (update)
Error loading Terraform: Error downloading modules: error downloading 'ssh://git.nnamdi.com:practice/aws-dhcp-options.git': /usr/bin/git exited with 128: fatal: Not a git repository (or any of the parent directories): .git
```

But that repository is a valid git repository from which I can clone

```
nnamdi@worklaptop:~/test/ide/geppetto-workspace/foo-portal$ git clone git@git.nnamdi.com:practice/aws-dhcp-options.git

Cloning into 'aws-dhcp-options'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (14/14), 6.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
```

Does anyone know whats going on here? My module files are laid out in the root of the repository btw.

**Comment by mitchellh** [comment]
Hello! Can you share the exact value (or exact format of the value) for your module `source` so I can start trying to reproduce this? Can you repro this against a private GitLab repo that is hosted on GitLab.com itself? Just trying to find an easy way for me to repro this.

**Comment by mitchellh** [comment]
Also, I saw you posted on #4004 that this was the same problem but I believe that was a different problem and I couldn't reproduce that at all. I'll wait for you to learn more about your source URL to see if I can reproduce this. 

One option: have you tried deleting your `.terraform/modules` directory and doing a `terraform get` again? It looks like there is a chance it somehow could've gotten corrupted.

**Comment by hugoduncan** [comment]
I'm seeing a similar issue using terraform 0.7.1 running on travis against a private github repo, using https and a github key:

```
Error loading Terraform: Error downloading modules: error downloading 'https://user:key@github.com/org/repo': /usr/bin/git exited with 128: Cloning into '.terraform/modules/46dab912acf7df7c11e5ee2d5394c8c7'...
```

The  module source is:

```
module "cross_project" {
  source = "git::https://user:key@github.com/org/repo//modules/mymodule"
}
```

The `terraform get` command runs successfully when run locally.

Is there a version requirement on `git` command line, or similar? or could this be an SSH host key verification issue?

**Comment by mitchellh** [comment]
Git exiting with code 128 just seems like Git itself failed. Terraform doesn't do anything fancy here, it is literally cloning with `git clone URL` where the URL is shown there in the error message...

**Comment by hugoduncan** [comment]
Adding an explicit `git clone URL` to the travis build steps, using the URL shown in the error message, succeeds without any issue.

The travis build is using `git version 1.8.5.6`.

**Comment by mitchellh** [comment]
Hm, can you share debug logs and let me see if that helps me at all.

**Comment by hugoduncan** [comment]
```
2016/08/22 21:52:45 [INFO] Terraform version: 0.7.1  55ba6ebd3d0e7800bc3755690ab60f6e4ca8bf94
2016/08/22 21:52:45 [INFO] CLI args: []string{"/tmp/terraform/terraform", "get", "infra"}
2016/08/22 21:52:45 [DEBUG] Detected home directory from env var: /home/travis
2016/08/22 21:52:45 [DEBUG] Detected home directory from env var: /home/travis
2016/08/22 21:52:45 [DEBUG] Attempting to open CLI config file: /home/travis/.terraformrc
2016/08/22 21:52:45 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/08/22 21:52:45 [DEBUG] Detected home directory from env var: /home/travis
2016/08/22 21:52:45 [TRACE] Preserving existing state lineage "7480f155-a3d0-4322-86a1-58da133f6c23"
2016/08/22 21:52:45 [TRACE] Preserving existing state lineage "7480f155-a3d0-4322-86a1-58da133f6c23"
2016/08/22 21:52:45 [WARN] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
Error loading Terraform: Error downloading modules: error downloading 'https://user:key@github.com/org/project': /usr/bin/git exited with 128: Cloning into '.terraform/modules/46dab912acf7df7c11e5ee2d5394c8c7'...
```

**Comment by mitchellh** [comment]
Darn, nothing :( I'll give it a shot locally to try to repro.

**Comment by cprenzberg** [comment]
Hi,

I still have this issue unfortunately. 

Here is how I am trying to use my module:

`
provider "aws" {
  region = "eu-west-1"
}

module "key-pair {
  source = "git::ssh://git@github.com:cprenzberg/infrastructure-aws-key-pairs.git"
  name = "my-key-pair"
  environment  = "test"
  logs_bucket_id  = "logs-bucket"
}

`

When I run terraform get, I see

`
ubuntu@agent:~/lambda$ export TF_LOG=DEBUG
ubuntu@agent:~/lambda$ terraform get
2016/09/08 01:17:02 [INFO] Terraform version: 0.7.3  0dd7c657d6d60d2e7392b66ae6f74fb84582cab9
2016/09/08 01:17:02 [INFO] CLI args: []string{"/usr/bin/terraform", "get"}
2016/09/08 01:17:02 [DEBUG] Detected home directory from env var: /home/ubuntu
2016/09/08 01:17:02 [DEBUG] Detected home directory from env var: /home/ubuntu
2016/09/08 01:17:02 [DEBUG] Attempting to open CLI config file: /home/ubuntu/.terraformrc
2016/09/08 01:17:02 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
Get: git::ssh://git@github.com:cprenzberg/infrastructure-aws-key-pairs.git
2016/09/08 01:17:02 [DEBUG] Detected home directory from env var: /home/ubuntu
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@github.com:cprenzberg/infrastructure-aws-key-pairs.git': /usr/bin/git exited with 128: Cloning into '.terraform/modules/de45fb50a4ceeada08ea4ccd1720b924'...
2016/09/08 01:17:06 [DEBUG] plugin: waiting for all plugin processes to complete...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

` 

However git clone works just fine

`
ubuntu@agent:~/lambda$ git clone git@github.com:cprenzberg/infrastructure-aws-key-pairs.git
Cloning into 'infrastructure-aws-key-pairs'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), 6.22 KiB | 0 bytes/s, done.
Checking connectivity... done.

`

github.com:cprenzberg/infrastructure-aws-key-pairs is a private github repo

Those were run Ubuntu 14.04 and the git client version was 1.9.1


When I try the same terraform get using the same module but from my private gitlab repo on a different machine, I see

`
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@git.nnamdi.com:practice/infrastructure-aws-key-pairs.git': /usr/bin/git exited with 128: Cloning into '.terraform/modules/a70229b6b518a2608fa5a5b8ac41b151'...
ssh: Could not resolve hostname git.nnamdi.com:practice: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

And of course a regular git clone works

`
nnamdi@worklaptop:$ git clone git@git.nnamdi.com:practice/infrastructure-aws-key-pairs.git
Cloning into 'dia-infrastructure-aws-key-pairs'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (12/12), 5.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
`

This other machine i used runs ubuntu 16.04 and git client 2.7.4

Hope this helps.

**Comment by mitchellh** [comment]
Great to hear! Thanks!

**Comment by stonefury** [comment]
Had a similar issue, wanted to use ssh auth. This is a gitlab deployed on-prem, so not sure if if this works the same as the cloud.

git::ssh://git@host/pathstuff/repo.git//networking?ref=0.0.1"

**Comment by danielhoherd** [comment]
For gitlab and Terraform 0.12.6, the correct syntax for hosted gitlab is `git::git@gitlab.com:/whatever.git?ref=someref`

**Comment by craigvanaman** [comment]
> Had a similar issue, wanted to use ssh auth. This is a gitlab deployed on-prem, so not sure if if this works the same as the cloud.
> 
> git::ssh://git@host/pathstuff/repo.git//networking?ref=0.0.1"

This fixed it for me in the cloud.  Thank you!

**Comment by ivan-sukhomlyn** [comment]
@danielhoherd Thank you for the suggestion 👍
