### ISSUE TITLE
RDS instances try to be recreated when associated with a KMS Alias

### ISSUE THREAD

**Issue by rcostanzo** [hashicorp/terraform#8259]
You can properly create a RDS instance with the KMS Alias ARN as the kms_key_id, but subsequent runs then want to recreate that resource because the AWS returned value is the actual KMS Key's ARN, not the Alias's.
### Terraform Version

0.7.0
### Affected Resource(s)
- aws_db_instance
- aws_kms_alias
### Terraform Configuration Files

```
resource "aws_kms_key" "rds" {
    ...
}

resource "aws_kms_alias" "rds" {
    name = "alias/key-rds-qa"
    target_key_id = "${aws_kms_key.rds.key_id}"
}

resource "aws_db_instance" "db-profile-2" {
    kms_key_id = "${aws_kms_alias.rds.arn}"
}
```
### Expected Behavior

No changes should be detected
### Actual Behavior

Terraform detects that the KMS Key changed and wants to recreate the RDS db resource:
`kms_key_id:                        "arn:aws:kms:stuff:key/keyid" => "arn:aws:kms:stuff:alias/key-rds-qa" (forces new resource)`
### Steps to Reproduce
1. Create a RDS instance with the kms_key_id equal to an alias
2. Run a plan afterwards and see it wants to recreate it vs. being a no-op

**Comment by cprenzberg** [comment]
+1 Seeing this issue too but for a redshift cluster

**Comment by alex-pw** [comment]
Also experiencing this issue, thanks for any help

**Comment by mboret** [comment]
+1

**Comment by justyns** [comment]
Just ran into this with `Terraform v0.8.2`
