### ISSUE TITLE
feature request: template file comments

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform#8260]
**Terraform Version:** Terraform v0.7.0
**Affected Resource(s):** template files
**Idea:**

I recently moved some AWS policies to template files to DRY up my configuration.

For example:
```
resource "aws_s3_bucket" "bucket-name" {
  bucket = "bucket-name"
  acl = "public-read"
  # the s3:ListBucket action allows s3 to return 404s
  # insetad of 403s on missing files.
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "s3:GetObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::bucket-name",
        "arn:aws:s3:::bucket-name/*"
      ]
    }
  ]
}
EOF
}
```

...became:
```
data "template_file" "bucket-name-policy" {
  template = "${file("${path.module}/../templates/public_read_bucket.tpl")}"
  vars {
    bucket_name = "bucket-name"
  }
}

resource "aws_s3_bucket" "bucket-name" {
  bucket = "bucket-name"
  acl = "public-read"
  policy = "${data.template_file.bucket-name-policy.rendered}"
}
```

In doing this, I lost the ability to document the template:
```
  # the s3:ListBucket action allows s3 to return 404s
  # insetad of 403s on missing files.
```
^ this can't go into the template because AWS policies are JSON and JSON doesn't support comments.

Would ya'll be open to adding a comment block of some form for templates that are NOT included in the rendered output?

If yes, I'd be happy to attempt a PR! We'd need to decide what the prefix is though. `#` doesn't seem like a good idea since it is such a common comment character and I assume some folks are already using it in template files an expecting it to wind up in the deployed resource?

**Comment by mitchellh** [comment]
I'd rather not annotate the template more or introduce any new language constructs there. Instead, one thing we've talked about is just supporting other template languages (and there is an enhancement request floating around for that). Until then, I would recommend putting the comment on the template resource itself.

**Comment by tkellen** [comment]
Thanks @mitchellh! Any chance you could reference the issue you're speaking of?

**Comment by mitchellh** [comment]
Unfortunately with over 1,000 issues at the moment I'd have a hard time finding it. Is one of the older issues (probably in 2015 sometime). Sorry I can't clarify I just don't have the time to search for it atm. :(

**Comment by tkellen** [comment]
No worries, I understand! I did some hunting but wasn't able to turn it up.

**Comment by jugglinmike** [comment]
Here's a terrible way to insert comments into Terraform templates

e.g. `public_read_bucket.json.tpl`

    {
      "Statement": [
        {
          "Action": [
            ${replace("
              The `s3:ListBucket` action allows S3 to return 404 errors instead of
              403s in response to missing files.
            ", "/.*/", "")}
            "s3:GetObject",
            "s3:ListBucket"
          ],
          "Resource": [
            "arn:aws:s3:::${bucket_name}",
            "arn:aws:s3:::${bucket_name}/*"
          ]
        }
      ]
    }

It would be easier to follow (and more efficient) to use a Terraform comment, e.g.

    ${ /* comment */"" }`

Unfortunately, the parser doesn't recognize comments within substitutions. I've requested that functionality via gh-19725, but I don't have very high hopes (it seems likely that modifying the grammar in this way may be prohibitively complicated).
