### ISSUE TITLE
aws_intances tags with space and / caracters

### ISSUE THREAD

**Issue by matthieudolci** [hashicorp/terraform#8265]
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_instance
### Terraform Configuration Files

```
resource "aws_instance" "name" {
    ami = ""
    availability_zone = "us-west-2a"
    instance_type = "m4.4xlarge"
    key_name = ""
    vpc_security_group_ids = [""]
    subnet_id = ""
    associate_public_ip_address = false
    monitoring = true

    root_block_device {
        delete_on_termination = "true"
    }

    tags {
        Name = "name"
        Application/Service  = "PostgreSQL"
        Business/Project ID = ""
        Description = ""
        Environment  = "Production"
        Location = "AWS (US-WEST-2)"
        OS = "CentOS 6.7 x86_64"
        Segment-Tier = ""
        Type = "Server"
        Misc = ""
    }
}
```
### Debug Output

https://gist.github.com/matthieudolci/b7f24df1910d1452c236e01678f63e1d
### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
### Expected Behavior

Tags should be applied to instances.
### Actual Behavior

`Error downloading modules: module instances: Error parsing .terraform/modules/31a6e7f3bf0f3e52d19b08fbecc2b306/postgresql.tf: At 19:21: nested object expected: LBRACE got: ASSIGN`
### Steps to Reproduce

terraform plan or get or apply

**Comment by myhro** [comment]
Hi Matthieu,

I've faced this problem when importing a node provisioned by Docker Cloud. Actually you can enclose them on double quotes, e.g.:

    tags = {
      UUID                 = "be2a649f-8c49-42ed-8493-d1a03ad76df2"
      Name                 = "be2a649f-8c49-42ed-8493-d1a03ad76df2.node.dockerapp.io"
      "Node Cluster Name"  = "node-cluster"
      "Docker ID username" = "organization"
    }

It's kinda strange (like attributing a string to another string) and I'm not sure if this is expected by the HCL format at all. Anyway, it worked by now.

Regards,
Tiago.

**Comment by mroark-exp** [comment]
I hope this is not reverted in the future since we are now depending on it.

I verified this works in aws in both 0.6.16 and 0.7.4

**Comment by matthieudolci** [comment]
@myhro Thanks, that is going to help.

@mroark-exp same here, i will try with the "/".

**Comment by matthieudolci** [comment]
@myhro Thanks it works perfectly.
