### ISSUE TITLE
provider/fastly: Support for origin shielding

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#8279]
Fastly supports [Origin Shielding](https://docs.fastly.com/guides/performance-tuning/shielding) to gain performance benefits by utilizing Fastly's POP as a shield node. 

According to Fastly's API Documentation, it seems [possible](https://docs.fastly.com/api/config#backend) to configure shield variable via an existing API endpoint.
#### More info
- Fastly Documentation: [About Fastly's Origin Shielding features](https://docs.fastly.com/guides/about-fastly-services/about-fastlys-origin-shielding-features)
- Fastly Documentation: [Shielding](https://docs.fastly.com/guides/performance-tuning/shielding)

**Comment by heythisisnate** [comment]
+1
