### ISSUE TITLE
networkMode in aws_ecs_task_definition

### ISSUE THREAD

**Issue by kkarimi** [hashicorp/terraform#8281]
It is now possible to use networkMode as a task definition parameter in Amazon ECS per documentation [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#network_mode) and [here](http://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html), is anyone working to implement this feature on terraform?
Thank you

**Comment by stack72** [comment]
Hi @kkarimi 

No one is currently working on this - I just opened a PR that bumps the SDK for this (#8285) - once this is merged, then the repo has the correct API version to implement the new func :)

Paul

**Comment by kkarimi** [comment]
@stack72 Thanks 👍
