### ISSUE TITLE
Documentation issue for cloudtrail

### ISSUE THREAD

**Issue by hamstah** [hashicorp/terraform#8287]
Hi,

The [website example](https://www.terraform.io/docs/providers/aws/r/cloudtrail.html) is showing an incorrect example of cloudtrail usage.

This leads to the following error
```
* aws_cloudtrail.cloudtrail: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: XXXX
    status code: 400, request id: XXXX
```

I suggest to update it with the following, taken from [the official documentation](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-set-bucket-policy-for-multiple-accounts.html)

```
resource "aws_cloudtrail" "foobar" {
    name = "tf-trail-foobar"
    s3_bucket_name = "${aws_s3_bucket.foo.id}"
    s3_key_prefix = "yourprefix"
    include_global_service_events = false
}
```

With a more explicit S3 policy
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AWSCloudTrailAclCheck20131101",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "s3:GetBucketAcl",
      "Resource": "arn:aws:s3:::myBucketName"
    },
    {
      "Sid": "AWSCloudTrailWrite20131101",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "s3:PutObject",
      "Resource": [
        "arn:aws:s3:::myBucketName/yourprefix/AWSLogs/youraccountid/*",
      ],
      "Condition": { 
        "StringEquals": { 
          "s3:x-amz-acl": "bucket-owner-full-control" 
        }
      }
    }
  ]
}
```

If possible add a note about allowing cross account cloudtrail logs in s3 by adding new resources in the S3 policy with the different account ids.

Thanks

**Comment by radeksimko** [comment]
Hi @hamstah 
the example is intentionally simple - i.e. allowing single AWS account only. Is it not working for you in that context either?

**Comment by hamstah** [comment]
Hi
Sorry my ticket was a bit confusing.
The main issue is the prefix itself, it should be changed from "/prefix" to "prefix", ie remove the /.

The policy itself is probably ok but doesn't match the policies generated by cloudtrail itself or the documentation, so it can be a bit confusing IMO.
1. The fact that it uses `"Resource": "XXX"` instead of the array version doesn't make it obvious you can extend it unless you've used to IAM. 
2. The resource is using `/*` which is very broad and doesn't highlight how the prefix from cloudtrail interacts with it.
