### ISSUE TITLE
DNS Made Easy provider

### ISSUE THREAD

**Issue by soniah** [hashicorp/terraform#829]
I've written a Terraform provider for [DNS Made Easy](http://www.dnsmadeeasy.com/) called [terraform-provider-dme](https://github.com/soniah/terraform-provider-dme).

Is the Terraform project going to keep a list of third party providers? Or (if it's good enough...) will you incorporate it as Terraform built-in provider?

**Comment by knuckolls** [comment]
i perused the code and it looks clean, well documented, and well tested. this is just my opinion but the more providers the better. i'd go ahead and pull request it to the builtin folder like the others just to see if it's acceptable in it's current form.

**Comment by pearkes** [comment]
Yup, I agree with what @knuckolls said, would be great to see a pull request!

**Comment by soniah** [comment]
Thanks guys. I'm not sure what you mean though - who would be pulling?

Or is there some code in TF mainline I need to modify in order to get this added under TF? Hence a pull request from me?

**Comment by armon** [comment]
@soniah Basically if you could make a PR against this repo, and the DNS Made Easy stuff into the `builtin/provider/dns-made-easy/` path, and add the documentation to `source/docs/providers/dns-made-easy` then we can add this into core!

**Comment by phinze** [comment]
This has been in for awhile. Hooray! Closing...

**Comment by soniah** [comment]
:+1:
