### ISSUE TITLE
Remote state variables present in root and not under output

### ISSUE THREAD

**Issue by ivanjaros** [hashicorp/terraform#8296]
So according to the documentation in here https://www.terraform.io/docs/providers/terraform/d/remote_state.html#output the variables in the remote state should be accessed under the `output` key but in reality they are present at the root level.

I was getting error about unknown attribute but running `terraform show` luckily showed me the real structure of the state and then I saw the issue.

**Comment by jen20** [comment]
Hi @ivanjaros! Sorry about this, we apparently missed updating that page in the documentation when we changed this to support lists and maps as remote state attributes. There was a note in the CHANGELOG under backwards compatibility but this one slipped past. I'll get it fixed up - thanks for reporting the issue!
