### ISSUE TITLE
Provide ability to specify a name_prefix for google cloud sql.

### ISSUE THREAD

**Issue by hjfbynara** [hashicorp/terraform#8302]
currently terraform will generate names like: terraform-qfarbd43lrexcck5htofjs5z6m when creating cloudsql instances.  I would like the ability to specify my own prefix.   It becomes very difficult to differentiate between all my instances in my project.  Being able to specify my own prefix - I can at least precede each instance with my own identifier.   You have this feature for:
https://www.terraform.io/docs/providers/aws/r/launch_configuration.html 

Personally I think everywhere terraform will generate unique names - it should allow the ability to pass in my own prefix.  Obviously if it is not specified default to "terraform-".

**Comment by eveld** [comment]
This can also be achieved by setting the name yourself and using the random_id provider.

e.g.
```
resource "random_id" "instance-id" {
  byte_length = 3 // or more for longer hex
}

resource "google_sql_database_instance" "database-instance" {
  name = "${var.prefix}-${random_id.instance-id.hex}"
  ...
}
```
