### ISSUE TITLE
Data source "template_file" doesn't support "count"?

### ISSUE THREAD

**Issue by antimack** [hashicorp/terraform#8317]
Hi.
I'm refactoring my terraform configuration files and realized that after switching "template_file" from resource type to data I have an error:
Errors:

  * data.template_file.mount_ebs_volumes: : invalid or unknown key: count
  * data.template_file.iam_policy_templates: : invalid or unknown key: count

Terraform v0.7.0

Previously I've used "count" in templates files according to documentation to create multiply template files per dynamic created instances.

**Comment by marcboudreau** [comment]
I was just about to log the same issue.  In our case, we have multiple aws_launch_configuration resources, which used to set the user_data key with `"${element(template_file.user_data.*.rendered, count.index)}"`.  Having multiple instances of the template_file allowed us to pass along the index to the template.

**Comment by steven-collins-omega** [comment]
Ha! I was literally just about to post the same question/issue to the Google group. So "me too".

**Comment by marcboudreau** [comment]
Keeping the template_file as a resource is fine for now (aside from the warnings).  Hopefully, there will be some kind of resolution before that's no longer possible.

**Comment by jen20** [comment]
Hi @antimack! Thanks for opening an issue - we are intending to support the `count` metaparameter on data sources fairly soon, but I can't commit to an exact release number at this point. This is being tracked at #7919, so I'll close this in favour of keeping the discussion there.
