### ISSUE TITLE
Error creating new Instance using Terraform on Ubuntu Machine.

### ISSUE THREAD

**Issue by pavanpro** [hashicorp/terraform#8328]
Hi There,

We are working on creating AWS Stacks using Terraform v0.6.0, and we are getting the below error while spinning up Stack,

**Launching a new EC2 instance. Status Reason: Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping. Launching EC2 instance failed.**

Really appreciate your help in getting this issue resolved.

**Comment by mitchellh** [comment]
Hello!

Can you please resubmit this issue following the issue template? This would help us greatly and without it I'll end up asking you the same questions anyways. :) 

While doing so, can you please test that this is still happening on the latest version (0.7.1)? Your original message says 0.6 which may be a typo but if it is indeed 0.6 there have been hundreds if not thousands of improvements to the AWS provider between then and now and it may have been fixed already.

Thanks!
