### ISSUE TITLE
Error: <resource> does not have attribute '<attrib>.0' for variable '<resource>.*.<attrib>.0'

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#8329]
### Terraform Version

0.7.0
### Affected Resource(s)

All, but using test provider to demonstrate
### Terraform Configuration Files

``` hcl
resource "test_resource" "test" {
  count    = 2
  required = "${count.index}"

  required_map {
    key1 = "value1"
  }

  set = ["value1", "value2"]
}

resource "test_resource" "breaks" {
  required = "foo"

  required_map {
    foo = "foo"
  }

  set      = ["${test_resource.test.*.set.0}"]                           #BREAKS
#  set      = ["${test_resource.test.*.computed_list.0}"]       #BREAKS TOO
  optional = "${test_resource.test.0.computed_list.0}"        #WORKS
}

output "works" {
  value = ["${test_resource.test.*.computed_list.0}"] # WORKS
}

provider "test" {}
```
### Debug Output

https://gist.github.com/samjwlee/1f1a83380ed22035962df800fb7a673c
### Panic Output

n/a
### Expected Behavior

terraform plan succeeds
### Actual Behavior

Error running plan: 1 error(s) occurred:
- Resource 'test_resource.test' does not have attribute 'set.0' for variable 'test_resource.test.*.set.0' 
### Steps to Reproduce
1. `terraform plan`
### Important Factoids

n/a
### References

none

**Comment by mitchellh** [comment]
This is reproduced somewhere elsewhere but the discussion there is: what do we do about ordering? what does "0" here mean? A set is naturally unordered. We mentioned just using the explicit order if it is user-specified, but if it isn't it becomes more confusing...

**Comment by sjwl** [comment]
The failure also occurs on computed lists (as depicted in the sample HCL, commented out)

**Comment by lyxalig** [comment]
Did you ever resolve this issue? I am unable to get the second ip address of every instance.
I am using vSphere provider, and it creates a guest_ip_addresses list.
If i try to use splat referencing and index 1, I will get the second instance, not the second ip.
