### ISSUE TITLE
Terraform does not read AWS profile from environment variable

### ISSUE THREAD

**Issue by boompig** [hashicorp/terraform#8330]
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)

Probably all of AWS, observed with S3.
### Terraform Configuration Files

``` hcl
variable "region" {
    default = "us-west-2"
}

provider "aws" {
    region = "${var.region}"
    profile = "fake_profile"
}

resource "aws_s3_bucket" "bucket" {
    bucket = "fakebucket-something-test-1"
    acl = "private"
}
```
### Debug Output

https://gist.github.com/boompig/f05871140b928ae02b8f835d745158ac
### Expected Behavior

Should successfully login then give "noop" text.
### Actual Behavior

Does not read the correct profile from environment variable. Works if you provide the profile name in the file, though.
### Steps to Reproduce
1. export AWS_PROFILE= `your_real_profile`
2. create a terraform file similar to mine with a fake profile in the name
3. `terraform apply`

**Comment by mattwillsher** [comment]
I'm seeing similar behaviour when profile is unset in the provider. 

~/.aws/credentials:

```ini
[prod]
aws_access_key_id = ....
aws_secret_access_key = ...
[dev]
aws_access_key_id = ....
aws_secret_access_key = ...
```

prod has AWS account id 999888666555
dev has AWS account id 123456789012

```hcl
provider "aws" {
    allowed_account_ids = ["123456789012"]
}
```
```sh
$ AWS_PROFILE=dev terraform plan
```
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Account ID not allowed (999888666555)
```

**Comment by dsavinkov** [comment]
The same issue with `v0.7.7`, it just shows default one.
File `~/.aws/config`:
```properties
[default]
region = us-west-2
aws_access_key_id = ...
aws_secret_access_key =...
[au]
region=ap-southeast-2
```
Sample `.tf`:
```tf
provider "aws" {
  shared_credentials_file = "/.aws/config"
  profile = "au"
}

resource "aws_vpc" "ozzieVPC" {
  ...
}
```

**Comment by bitpusher-real** [comment]
Same problem here with 0.8.0-beta2

**Comment by jkpindahbc** [comment]
still an issue, any update on a fix?

**Comment by xakraz** [comment]
Same problem here with the latest `0.8.7`

**Comment by carpenterm** [comment]
Also having this issue with v0.9.2.

Can't use TF with assume role configured via environment variables due to this which makes kubernetes deployments with kops difficult when using TF as the provisioner (it outputs `provider "aws" {}` and expects env var configuration).

**Comment by craigmonson** [comment]
Having same issue with 0.9.6

**Comment by viveksatasiya** [comment]
Having same issue with 0.9.8

**Comment by usowmyas** [comment]
Having the same issue with 0.9.8 . In fact , how do we read environment variables in a tfvar file 
foo = "${env.FOO}"  
does not work

**Comment by usowmyas** [comment]
Uhh , for now , having this work around like below in tfvar file 

foo = "@JENKINS_PARAM_FOO@"
doo = "@JENKINS_PARAM_DOO@" 

then , just before we run terraform plan , having a sed cmd like below to replace the defined keys with environment variables set by jenkins . 

sed -i "s;@JENKINS_PARAM_FOO@;$JENKINS_PARAM_FOO;g" ./terraform/dev.tfvars
sed -i "s;@JENKINS_PARAM_DOO@;$JENKINS_PARAM_DOO;g" ./terraform/dev.tfvars
// once the tfvars file has been replaced with needed vars , then apply cmd 
terraform plan -state="dev.tfstate" -var-file="dev.tfvars"

**Comment by usowmyas** [comment]
But , this file with variables replaced cant stay in jenkins workspace  ( especially if we are reading aws keys or rds passwords . it has to be deleted once plan is successful )

**Comment by Puneeth-n** [comment]
I think its better to discuss it [here](https://github.com/terraform-providers/terraform-provider-aws) since the way terraform project handles providers from now on.

**Comment by Puneeth-n** [comment]
@usowyas there are a couple of ways to handle different credential pair in Jenkins. [cloudbees plugin](https://plugins.jenkins.io/aws-credentials) and have terraform code something like this:

**Comment by usowmyas** [comment]
but , if i have several variables , terraform plan -var ( say > 12 variables ) , we get below error 

`Too many command line arguments. Configuration path expected.`

and looks like we cant use a combination of -var and -var-file . 

Also , i tried using Jenkins credentials plugin , we are in fact saving the password . The idea is to have the user enter this AWS credentials / passwords when a Jenkins task is triggered .

**Comment by usowmyas** [comment]
well at least for more secure stages ( prod ) , if not for dev , test stages . i guess Jenkins credentials plugin can be used for dev and test stages

**Comment by apparentlymart** [comment]
Hi all,

This issue has been closed and migrated to the AWS provider repository and is no longer being monitored. You should find the link to the new issue above.
