### ISSUE TITLE
Missing PagerDuty support

### ISSUE THREAD

**Issue by StyleT** [hashicorp/terraform#8339]
Hi there,

### Terraform Version
0.7.1

### Expected Behavior
Support for PagerDuty Services

### Actual Behavior
Not supported yet

### References
- https://v2.developer.pagerduty.com/v2/page/api-reference
- https://github.com/PagerDuty/go-pagerduty
- https://github.com/underarmour/terraform-provider-pagerduty

### Question
Is anybody already working on this? Is it good idea, to implement such feature?

**Comment by kwilczynski** [comment]
@StyleT not that I know of, but some people did plan, as per:

https://github.com/underarmour/terraform-provider-pagerduty

**Comment by StyleT** [comment]
@kwilczynski yeah, I saw this and forget to mention in 1st post :( We can use this plan as a first stop.

**Comment by dharrisio** [comment]
@StyleT I this is an interesting idea for a provider, it's something that I have been thinking about the last few months. The underarmour link looks like a good start to me, the only other one I would be particularly interested in is an "integration" resource. 

There is one issue I would need to look into before committing to working on a PagerDuty provider though:

- The different plan types are currently a bit confusing. The info they have on the pricing page vs the FAQ seems to conflict concerning the number of API calls allowed per month. From the FAQ it sounds like the BASIC and below accounts are limited to 500 rest api calls per month. However, on the pricing page the BASIC account type has "Unlimited API calls". I'll need to find out some more about what this means from them, but I think 500 api limit would be problematic in Terraform.

One other point to consider is that the v2 API is somewhat recent, and I don't think there is currently a go sdk yet. So, that would need to be created (with at least partial functionality) before work on a PagerDuty provider could begin. 

I'll let you know once I find out the account info and figure out if I can do this or not. If not, hopefully there is someone else who can 😄 . In that case, I would still be happy to help out with testing it, but may have a limited account which effects which resources I could use.

**Comment by StyleT** [comment]
@dharrisio Hi! I don't think that we should care about API calls amount limit in Terraform. From my point of view we should just correctly handle `429 Too Many Requests` error and maybe limit amount of simultaneous requests.

Also here is Go library for APIv2 https://github.com/PagerDuty/go-pagerduty

P.S.: I have account with Basic subscription (and maybe it can be upgraded to the Standard) and happy to help with testing if needed.

**Comment by esigler** [comment]
Howdy!  (Disclosure: PagerDuty employee) As a quick update on the comment from @dharrisio:

> From the FAQ it sounds like the BASIC and below accounts are limited to 500 rest api calls per month. However, on the pricing page the BASIC account type has "Unlimited API calls".

We've removed the incorrect FAQ answer, BASIC account types (& others) have unlimited API calls.

**Comment by heimweh** [comment]
I started playing around with a basic PagerDuty provider (supporting only CRUD operations on a `User`) https://github.com/heimweh/terraform/pull/1/files

**Comment by heimweh** [comment]
I opened a pull request here (https://github.com/hashicorp/terraform/pull/9022). 
This is a WIP but should hopefully cover the basics. Any feedback is more than welcome.

**Comment by stack72** [comment]
Very pleased to say that this is now closed via #9022 - thanks so much @heimweh for the work on that :)

First night's acceptance tests are green https://travis-ci.org/hashicorp/terraform/builds/170372974
