### ISSUE TITLE
AWS ECS auto-scaling

### ISSUE THREAD

**Issue by trungnguyen** [hashicorp/terraform#8342]
Hi there,

### Terraform Version
0.7.0

### Expected Behavior
Support for AWS ECS auto-scaling (not to confuse with standard AWS auto-scaling group)

### Actual Behavior
Create an ECS cluster
Fire up a service to run, say, httpd
Can configure auto-scaling for the service in AWS console, but not with Terraform 0.7.0

**Comment by stack72** [comment]
Hi @trungnguyen 

Luckily, this feature is already included in Terraform. The ECS Autoscaling falls under the category of Application Autoscaling in AWS (and now Terraform)

You can find the resources here:

* https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html
* https://www.terraform.io/docs/providers/aws/r/appautoscaling_target.html

You can also find examples in our nightly acceptance tests:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_appautoscaling_policy_test.go#L88
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_appautoscaling_target_test.go#L119

Paul
