### ISSUE TITLE
provider/aws: warn when IAM policy is referenced in two attachments

### ISSUE THREAD

**Issue by 41jules1967** [hashicorp/terraform#8346]
Hi there,
Been struggling with inconsistent behaviour using the aws_iam_policy_attachment comand. Sometimes it worked, more often it told me something didn't exist when it did. Turns out I was referencing the same policy in 2 separate attach commands. My bad.
Now I (now) know there's a big note on the docs to advise of the issue but firstly it's quite easy to slip up on a complex definition and replicate for a second role and secondly, AWS/Terraform rookies (like me) are already struggling with all the new terminology and concepts and the note, as blindingly obvious as it is to me now, doesn't always click. Given the odd and inconsistent behaviour you get when you do make this mistake, it's not always obvious what's going on.
It strikes me that it wouldn't be too difficult to add a check into pre-run validation looking for duplicate references to policies in attach commands.
Would have saved me a day of head scratching ;-)
Any chance?
Thanks.

**Comment by jen20** [comment]
Hi @41jules1967! Thanks for opening an issue - I agree it would be good to provide a plan (or even an apply) time warning about this. However, I don't know without investigating the resources in question whether this is possible to detect. Do you have a snippet of config showing the problem you were observing in order that I can reproduce it?

**Comment by 41jules1967** [comment]
Hi,
The example would be


resource "aws_iam_policy" "ECS-CloudWatchLogs" {
    name = "ECS-CloudWatchLogs"
	path = "/"
    description = "ECS-CloudWatchLogs"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams"
            ],
            "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
    ]
}
EOF
}

resource "aws_iam_role" "CloudTrail_CloudWatchLogs_Role" {
    name = "CloudTrail_CloudWatchLogs_Role"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudtrail.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_policy_attachment" "CL1" {
    name = "Config-Role-Attach1"
    roles =["${aws_iam_role.CloudTrail_CloudWatchLogs_Role.name}"]
    policy_arn = "${aws_iam_policy.ECS-CloudWatchLogs.arn}"
}


resource "aws_iam_role" "Config-Role" {
    name = "Config-Role"
	path = "/service-role/"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "config.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_policy_attachment" "CL2" {
    name = "Config-Role-Attach2"
    roles =["${aws_iam_role.Config-Role.name}"]
    policy_arn = "${aws_iam_policy.ECS-CloudWatchLogs.arn}"
}


So create a policy, create 2 roles and use 2 aws_iam_policy_attachment commands to link them. I've not run the above directly as my work proxy access has died and my issue was part of larger build piece but the principle is sound. 
The problem is that it doesn't error as such but throws odd issues, such as complaining the policy doesn't exist when it can be seen in the console, running the first attach fine and failing on the second etc. A second run will often resolve it. Destroy has similar issues.
The command is not being used as intended so an error is a reasonable result but it's certainly confusing if you don't know what you're looking for. 
So I was thinking as part of initial validation to check that there aren't 2 aws_iam_attach_policy commands with the same policy_arn. 
Thanks.

**Comment by catsby** [comment]
Hey there – sorry you ran into this and had a bad time. Unfortunately we don't have a means of providing this kind of validation at this time. The core of Terraform handles each resource in a separate process, so besides building a dependency graph to know what must be created first, the ordering, and what can be made in parallel, we don't yet have the concept of intra-resource validations. While we want to provide this in the future, it's not available now :(

In the meantime, I believe you want to use `aws_iam_role_policy_attachment`:

- https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html

Sorry again for the trouble. Please let us know if there's anything else
