### ISSUE TITLE
Terraform 0.7.1 release is not on terraform.io

### ISSUE THREAD

**Issue by arbabnazar** [hashicorp/terraform#8351]
Terraform 0.7.1 release is not on terraform.io, can you please upload the latest release on terraform.io

Thanks,

**Comment by ajlanghorn** [comment]
@arbabnazar I can see it at https://www.terraform.io/downloads.html; where are you not seeing it?

**Comment by jen20** [comment]
Hi @arbabnazar! I've just accessed terraform.io and it appears to have 0.7.1 available. Perhaps it might be worth checking your cache settings. As of 16:55 CET, it looks like this (note the address in the status bar):

![071](https://cloud.githubusercontent.com/assets/548524/17837940/368a4a1c-67c0-11e6-8428-6574f80aedf5.png)

Consequently I'll close this issue for now - if you are still having problems having cleared your cache please comment again!

**Comment by arbabnazar** [comment]
I am still seeing the (0.7.0) on the official website :(
![screen shot 2016-08-21 at 8 13 58 pm](https://cloud.githubusercontent.com/assets/7621775/17838029/0f6b8be6-67dc-11e6-9030-140cac58b582.jpg)

**Comment by apparentlymart** [comment]
@arbabnazar the Terraform website has some pretty aggressive caching specified for it. I usually find that after a release I need to force refresh (hold the Ctrl or Shift key and press the reload button, in most browsers) to see the new changes.

**Comment by arbabnazar** [comment]
@apparentlymart thanks that did the trick.
