### ISSUE TITLE
Suppress/truncate long things in output

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#8355]
This is more of a discussion issue that Paul asked me to open. When using iam policies, long templates, or even SSH keys, the `terraform show` output can be troublesome to parse. It's grepability declines and it's not the best experience. This issue is to potentially discuss some options like:
- truncation of long strings
- ability to filter or hide certain keys (like marking them as sensitive, but just for the purposes of hiding them)
### Affected Resource(s)

Please list the resources as a list, for example:
- core

**Comment by mitchellh** [comment]
I think `terraform show` is broken from a UX perspective regardless. We need to take a look at this since as Terraform usage has grown, the usage of this command hasn't grown with it. I agree that after a certain length we should probably truncate unless a `-v` type flag is given.

**Comment by sethvargo** [comment]
Cross-linking with https://github.com/hashicorp/terraform/issues/8380

**Comment by sethvargo** [comment]
Individual resources can do this diffsuppressfunc now
