### ISSUE TITLE
Pass ebs_block_device settings as variable

### ISSUE THREAD

**Issue by dene14** [hashicorp/terraform#8356]
Is it possible at all to define resources like *_block_device with variables? https://www.terraform.io/docs/providers/aws/r/instance.html#block-devices

I've tried to declare variable's default as follows

```
variable "root_block_device" {
    type = "map"
    default = { 
      device_name = "/dev/xvda"
      volume_type = "standard"
      volume_size = "8"
      delete_on_termination = true
    }
    description = "Settings for root volume"
}
```

and pass it to corresponding resource in different ways w/o any luck, the most expected expression is something like this:

```
root_block_device "${var.root_block_device}"
```

**Comment by subtleenergies** [comment]
@dene14 did you find an answer to this?  I'm trying to do exactly the same thing.

**Comment by mitchellh** [comment]
This is not currently possible.

There is a core issue requesting parameterized blocks. Please find/see that. Thanks!
