### ISSUE TITLE
Docs were not updated with last release

### ISSUE THREAD

**Issue by samdunne** [hashicorp/terraform#8358]
Hey,

I can see in Terraform 0.7.1 we have a number of new changes (i.e. the ```archive``` provider and the ```terraform state rm``` command).

The site doesn't seem to have any of the new documentation however.

**Comment by apparentlymart** [comment]
@samdunne it's often necessary to "force-refresh" in your browser to see the new changes after a release, due to some rather-aggressive caching headers on the Terraform site.

**Comment by jen20** [comment]
Hi @samdunne! I am seeing the changes for the `state rm` command, but indeed you appear to be correct about the sidebar missing a link for the archive provider documentation. I'll get that fixed up now. Thanks for opening an issue!
