### ISSUE TITLE
AWS: eu-central-1 and cn-north-1 requires signature version 4 to sign AWS query API requests

### ISSUE THREAD

**Issue by ceh** [hashicorp/terraform#836]
As already mentioned in #525, `eu-central-1` (EU Frankfurt) and `cn-north-1` (China Beijing) requires signature version 4 to sign AWS query API requests.

goamz does not support signature version 4: mitchellh/goamz#120

Hence, Terraform cannot talk to `eu-central-1`, nor `cn-north-1`.

See also http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

**Comment by chipi** [comment]
This issue is fully blocking any activities in these new AWS regions, so there is actually no support for them.

**Comment by mitchellh** [comment]
This will be fixed in 0.4.0 as we move to aws-go.

**Comment by catsby** [comment]
This is fixed in the `master` branch and will be released in 0.4.0. 

Thanks!
