### ISSUE TITLE
build: Exclude darwin/amd64 from targets

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#8365]
We don't need to build for `darwin/amd64` and it presents alarming errors when making release builds. Consequently we should modify the build script to opt in to supported OS/Architecture pairs.

**Comment by mitchellh** [comment]
If we're using gox you can negative an osarch combo in the short term to make this super easy. Just add this (the flags are additive):

```
-osarch="!darwin/amd64"
```

**Comment by jen20** [comment]
Thanks for the note on this @mitchellh, that is indeed easier than enumerating the valid options.

**Comment by jen20** [comment]
Edited all of the above to fix typo of `amd64` to `arm`.
