### ISSUE TITLE
Download page still lists 0.7.0 as latest version

### ISSUE THREAD

**Issue by llarsson** [hashicorp/terraform#8369]
https://www.terraform.io/downloads.html still lists 0.7.0 as the latest version, but running `terraform -version` tells me that 0.7.1 is out.

**Comment by stack72** [comment]
Hi @llarsson 

I have just checked on this and see the following:

<img width="757" alt="screen shot 2016-08-22 at 10 04 03" src="https://cloud.githubusercontent.com/assets/227823/17849244/d325067a-684f-11e6-8bb9-40a0efcf6fe4.png">

The 64-bit link for OSX links to https://releases.hashicorp.com/terraform/0.7.1/terraform_0.7.1_darwin_amd64.zip

Can you try it on another browser and make sure that it isn't cached or something?

Paul

**Comment by stack72** [comment]
ping @llarsson :)

**Comment by llarsson** [comment]
Sorry, yeah, maybe it was just cached. Working now for me, too. 

Paul Stack <notifications@github.com> skrev: (22 augusti 2016 16:10:28 CEST)
>ping @llarsson :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hashicorp/terraform/issues/8369#issuecomment-241424522

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
