### ISSUE TITLE
VPC - Instances unreachable with the following config

### ISSUE THREAD

**Issue by gkze** [hashicorp/terraform#837]
I'm trying to stand up a cross-AZ VPC in AWS, with each AZ having 1 public subnet, and 1 instance in each subnet. Here's the config: https://gist.github.com/0a6f27bf9b306d9743ff

When I do all of that by hand, I can ping and SSH to the instances, but when I run `terraform apply`, everything seems green and I get a `0` exit status, however I can't ping or SSH to the instances. I have compared every resource config that I created by hand and with terraform, and they are identical.

Here's the graph: http://i.imgur.com/qHlzrcv.png

Hope I'm not missing anything simple here, I've triple-checked this config.

Thanks!

**Comment by wolfspyre** [comment]
I’ve not yet written any TF configs, but don’t you also need to specify egress rules? The config you list, AFAICT only specifies ingress rules. I could be totally off base however.

**Comment by gkze** [comment]
There seems to be neither any documentation for `egress` for the `aws_security_group` resource, nor do I see it anywhere in the code. However, I do see an `egress` block being available for the `aws_network_acl` resource. The default for any Network ACLs that I have seen is allow all/all, but I will try explicitly adding the resource with the `egress` blocks and see what happens.

Thanks!

**Comment by mitchellh** [comment]
We just added egress to security groups. They will be part of 0.3.7.

I don't know if this is the problem, but this issue unfortunately sounds like an AWS configuration issue. You'll get more luck asking the mailing list! The AWS console ("by hand") does a lot of helpful defaults that Terraform doesn't do (instead doing exactly what you ask of it). This is probably the disparity.

**Comment by gkze** [comment]
Thanks @mitchellh!
