### ISSUE TITLE
Create a virtual_network_gateway with azurerm

### ISSUE THREAD

**Issue by dpnl87** [hashicorp/terraform#8372]
I would like to have to possibility to create virtual network gateways with Terraform and the Azurerm provider. Currently there is no support for it so we still need to do manual actions on Azure.

Its used to link a network interface to a ExpressRoute.

If you need any additional information or require testing assistance I'm more then happy to help out.

**Comment by pmcatominey** [comment]
Hi @dpnl87 

I've got a work in progress PR #9255 which implements the gateway and connection resource.

**Comment by dpnl87** [comment]
Thnx @pmcatominey 👍 .
If you need any extra testing please let me know.

**Comment by avdhoot** [comment]
@pmcatominey When this will be released?

**Comment by holmesb** [comment]
+1 any news?  Will be a great new feature.

**Comment by glennmate** [comment]
+1, this is sorely needed

**Comment by amassara** [comment]
+1, very appreciate this feature

**Comment by dominik-lekse** [comment]
Hi everyone, I recently files the above mentioned pull request to add this feature. Would be great if you could contribute by reviewing and testing.

**Comment by AntonioM73** [comment]
Hi
How can I help you?

Regards
Antonio Massara

**Comment by dominik-lekse** [comment]
@AntonioM73 You could test the resources of the pull request for your use case. Especially, if your use case consists of an ExpressRoute setup, this would be helpful since I had no chance to test this. Also, the documentation needs review.

**Comment by AntonioM73** [comment]
Our case is not for express route,
Where can I found directly the .exe terraform?

A.

**Comment by dominik-lekse** [comment]
@AntonioM73 I cannot provide you with an executable. You could build this pull request on your own. The following links might help you:

- https://help.github.com/articles/checking-out-pull-requests-locally/
- https://github.com/hashicorp/terraform#developing-terraform
