### ISSUE TITLE
ResourceNotFoundException on a deleted aws_lambda_event_source_mapping

### ISSUE THREAD

**Issue by alexkappa** [hashicorp/terraform#8375]
Hello,

After manually deleting a lambda function (and its associated event source mapping) from the AWS Console I am unable to get terraform to work.

I've tried to taint the resource and destroy as per a suggestion in [this comment](https://github.com/hashicorp/terraform/issues/4888#issuecomment-176608033) but no luck.

### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
- aws_lambda_event_source_mapping

### Terraform Configuration Files
```hcl
resource "aws_lambda_event_source_mapping" "dmp_enrichment_event_source_mapping" {
    batch_size = 10
    event_source_arn = "${aws_kinesis_stream.dmp_event_raw_stream.arn}"
    function_name = "${aws_lambda_function.dmp_enrichment_event_lambda.arn}"
    starting_position = "LATEST"
    enabled = true
}
resource "aws_lambda_function" "dmp_enrichment_event_lambda" {
    filename = "${lookup(var.aws_lambda_functions, "event_enrichment")}"
    function_name = "enrichment_event_lambda"
    role = "${aws_iam_role.dmp_lambda_function.arn}"
    handler = "_apex_index.handle"
    source_code_hash = "${base64sha256(file(lookup(var.aws_lambda_functions, "event_enrichment")))}"
}
```

### Debug Output

https://gist.github.com/alexkappa/35ee3871e250680a4b69fe512e777166

### Actual Behavior

Terraform fails with

```
Error refreshing state: 1 error(s) occurred:

* aws_lambda_event_source_mapping.dmp_enrichment_event_source_mapping: ResourceNotFoundException: The resource you requested does not exist.
	status code: 404, request id: a17c641d-6868-11e6-accf-3d0ea71934fa
```

### Steps to Reproduce

1. Create a lambda and event source mapping using terraform
2. Delete lambda from AWS Console
3 Apply terraform changes

### References

- #4888
- #6625

**Comment by alexkappa** [comment]
To work around the issue I've compiled terraform and set the id to empty.

Changed [this file](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_lambda_event_source_mapping.go#L135-L138) temporarily to the following:

```go
eventSourceMappingConfiguration, err := conn.GetEventSourceMapping(params)
if err != nil {
	d.SetId("")
	return nil
}
```

Then running `terraform apply` I was able to re-create the resource. It would still be nice to have an easy workaround for this.

**Comment by stack72** [comment]
Hi @alexkappa 

I am working on this right now - this fix is almost right, this specific change above will remove the item from state on *any* error. This isn't quite right

Keep the eyes peeled for a PR in a few mins

Paul

**Comment by alexkappa** [comment]
Hi Paul, thanks for looking into it so quickly! Looking forward to that PR
