### ISSUE TITLE
resource AWS_ELASTICACHE_REPLICATION_GROUP should at least output the primary endpoint address and its portt

### ISSUE THREAD

**Issue by martin-flaregames** [hashicorp/terraform#8377]
### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
- AWS_ELASTICACHE_REPLICATION_GROUP

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The resource should output the primary endpoint address and the service port as in 
`aws elasticache describe-replication-groups`

### Actual Behavior
The resource is only providing the the replication group id, which is not really informative.

### Steps to Reproduce
terraform apply

### Important Factoids
n/a

### References
n/a

**Comment by stack72** [comment]
Hi @martin-flaregames 

Apologies for this not being included - I am looking into this right now - I worked on this resource recently so know it pretty well :)

Paul

**Comment by stack72** [comment]
Hi @martin-flaregames 

Jsut a FYI, the functionality will allow us to do the following:

```
% terraform apply
...................
aws_elasticache_replication_group.bar: Creation complete

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

primary_endpoint_address = tf-11111.d5jx4z.ng.0001.use1.cache.amazonaws.com
```

The port is already an output - everything that can be set, is already an output :)
