### ISSUE TITLE
Provide -json to show command

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#8380]
In talking with Paul, it would be great if Terraform supported a `-format=json` flag to `terraform show`. Right now, it's easy to `cat terraform.tfstate` (for local state), but it would be nice to have a jq-able API for querying information.
### Terraform Version

0.7.1 (3af6796)
### Affected Resource(s)
- core

**Comment by devth** [comment]
Any plans to impl this?

**Comment by apparentlymart** [comment]
Since Terraform 0.9 there has been a command to retrieve the state and print it to `stdout`:

```
$ terraform state pull
```

This then gives the same result as accessing the `terraform.tfstate` file but works for all state storage backends.

I think that takes care of the use-case that originally motivated this request, so I'm going to close this. (@devth, thanks for bumping this so that I could notice that it's actually been addressed!)

**Comment by devth** [comment]
I don't see an option to format it as json though. Wasn't the point to be able to slice up state with `jq`?

**Comment by apparentlymart** [comment]
The output of that command is the raw state data, which is itself JSON-serialized.

I should note that the exact structure of state is _not_ currently considered a compatibility constraint, so anyone parsing it should be prepared for it to change in future, though in practice so far it has changed pretty infrequently and only in minor ways.

**Comment by cornfeedhobo** [comment]
I don't think this should have been closed. Asking someone to parse `terraform.tfstate` is a drastically different task than adding `-json` to `state show` and parsing that.
Thoughts?

**Comment by Nowaker** [comment]
+1 for @cornfeedhobo. Getting `state show -json` would be really appreciated.

**Comment by ThisGuyCodes** [comment]
alsoalso for outputing terraform plan information

**Comment by mstancombe** [comment]
terraform state pull will dump the entire state, correct? including any sensitive info, which terraform currently stores.

I think there is definitely a need to selectively get specific resources that don't involve handling all the state, and adding a 'json' flag to 'show' would certainly cover that need.
