### ISSUE TITLE
Add support for memoryReservation to aws_ecs_container_definition

### ISSUE THREAD

**Issue by jdrake** [hashicorp/terraform#8389]
This is a new AWS feature released last week.

AWS description: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#standard_container_definition_params

I noticed only `memory` is included in the data source: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/data_source_aws_ecs_container_definition.go#L40

### Terraform Version
0.7.1

### Affected Resource(s)
- aws_ecs_container_definition

### Debug Output
See Actual Behavior

### Expected Behavior
`memoryReservation` should be allowed in place of `memory`

### Actual Behavior
```
ClientException: Invalid setting for container '***'. At least one of 'memory' or 'memoryReservation' must be specified.
```

### Steps to Reproduce
`terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by stack72** [comment]
Closed via #8437
