### ISSUE TITLE
`terraform apply` has a weird behavior using Cygwin

### ISSUE THREAD

**Issue by thasmo** [hashicorp/terraform#839]
I have a configuration file `droplet.tf` in the working directory and when executing `terraform apply`, this gets printed:
```shell
The destination path has Terraform configuration files. The init command can only be used on a directory without existing Terraform files.
```
When running `terraform apply` in an empty directory it prints:
```shell
module download not supported for scheme 's'
```

Seems I can't get it running; or am I doing something wrong?

**Comment by pouicr** [comment]
Same for me on both win cmd and cygwin (through Babun)

**Comment by ceh** [comment]
I fixed numerous Windows file path handling issues in #872 and #876, which should address the reported issues.

@thasmo, @pouicr: Please try a current build of the master branch by building it locally.
(The Makefile bin target generates binaries for multiple platforms.)

I can add a `bin` and `dev` target to the pending PR in #888, to simplify building binaries on Windows, if that helps.

**Comment by mkuzmin** [comment]
Yes, I've built current trunk on Windows, and can confirm those PRs fix the issue.

**Comment by ceh** [comment]
Sorry, broken again by 2d9dd254938fc7d3741243bd46ad41b9c6941ab9. I'll have a look when I get some time over.

**Comment by mitchellh** [comment]
Glad this is fixed. Sorry @ceh, but I think if we had that test case in there to start we would've avoided all this, so my fault.

**Comment by ceh** [comment]
@mitchellh No worries. I learned a lot and had fun.
