### ISSUE TITLE
Terraform hangs when IAM API returns 503

### ISSUE THREAD

**Issue by Dchamard** [hashicorp/terraform#8402]
Hi there,

Terraform is hanging at plan,destroy or apply command.
After enabling logging, I found out that the AWS AMI API is down and returning 503.
I would expect terraform to fail instead of hanging in this situation.
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)

Multiple resources affected.
Terraform just hangs
### Debug Output

Related debug output. 
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: 2016/08/22 15:49:27 [DEBUG] [aws-sdk-go] DEBUG: Response iam/GetUser Details:
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: ---[ RESPONSE ]--------------------------------------
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: HTTP/1.1 503 Service Unavailable
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: Connection: close
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: Content-Length: 0
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: Date: Mon, 22 Aug 16 22:49:27 GMT
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: X-Amz-Id-2: sddssdsdds323NHwcBgAum6AKPW0OOjTbng==
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: X-Amz-Request-Id: FDJHDIJHFD
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: 
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: 
2016/08/22 15:49:27 [DEBUG] terraform-provider-aws: --------------
### Expected Behavior

I would expect terraform to fail since its not able to get proper responses  of Aws AMI API.
### Actual Behavior

Terraform just hangs (left it over 5 minutes.) It did it on plan,apply and destroy commands
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan` when aws ami api is down

**Comment by usultis** [comment]
I'm experiencing the same problem:
terraform/0.6.16 () aws-sdk-go/1.1.23 (go1.6.2; linux; amd64)

**Comment by Dchamard** [comment]
Terraform finally failed with this error after a while: Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* SerializationError: failed to decode query XML error response
caused by: EOF

**Comment by cmosetick** [comment]
I'm getting the same behavior as reported in the initial report but pointed to AWS `us-west-2` region.

**Comment by cmosetick** [comment]
Switching back to terraform version 0.7.0 seems to work correctly for me.

**Comment by chadgrant** [comment]
Yeah, mine is hanging on route53 503 errors in us-west-2 apparently, it just hangs and even when hitting cntrl-c it does not "Gracefully shutdown" and I have to manually delete everything before I can retry an apply.

module.ecs_service.aws_route53_record.api: Still creating... (10s elapsed)
2016/11/05 06:09:58 [DEBUG] vertex "provider.module.ecs_service.aws (close)", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:09:58 [DEBUG] vertex "root", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:10:03 [DEBUG] vertex "provider.module.ecs_service.aws (close)", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:10:03 [DEBUG] vertex "root", waiting for: "module.ecs_service.aws_route53_record.api"
module.ecs_service.aws_route53_record.api: Still creating... (20s elapsed)
2016/11/05 06:10:08 [DEBUG] vertex "provider.module.ecs_service.aws (close)", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:10:08 [DEBUG] vertex "root", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:10:11 [ERR] Checkpoint error: Unknown status: 503
2016/11/05 06:10:12 [DEBUG] plugin: terraform: template-provider (internal) 2016/11/05 06:10:12 [ERR] Checkpoint error: Unknown status: 503
2016/11/05 06:10:12 [DEBUG] plugin: terraform: aws-provider (internal) 2016/11/05 06:10:12 [ERR] Checkpoint error: Unknown status: 503
2016/11/05 06:10:13 [DEBUG] vertex "provider.module.ecs_service.aws (close)", waiting for: "module.ecs_service.aws_route53_record.api"
2016/11/05 06:10:13 [DEBUG] vertex "root", waiting for: "module.ecs_service.aws_route53_record.api"
module.ecs_service.aws_route53_record.api: Still creating... (30s elapsed)

**Comment by jtopper** [comment]
I've come up against something similar today, in my case hanging on refreshing state for `aws_iam_policy_document`. I also saw "Checkpoint error: Unknown status: 503" but I think that's a red herring: it relates to https://github.com/hashicorp/go-checkpoint and I was still seeing the problem when I used `CHECKPOINT_DISABLE=1`

I have a tf.log here with a bunch of ```Getting account ID via iam:GetUser failed: ValidationError: Must specify userName when calling with non-User credentials``` and similar in it, which leads me to suspect that this is something relating to configuring the provider, but I haven't been able to gain any more insight than that, and turning this into a minimal test case is likely to require more time than I have.  Happy to provide a copy of tf.log if @stack72 wants to grab me on Slack this week :)

Going from Terraform 0.7.9 back to the 0.7.7 I'd previously been using seems to have solved the issue for now.

**Comment by jtopper** [comment]
To follow up my previous comment, I think my `iam:GetUser failed` errors are expected, since the provider code for `GetAccountInfo` falls back to using STS methods in that failure case.  So, the behaviour I'm seeing here may be unrelated, and I'll open a new issue to capture it.

**Comment by radeksimko** [comment]
Hi,
I'm sorry to hear you're experiencing issues.

The `503` HTTP code belongs into a range of codes that are considered as retryable in the underlying AWS Go SDK Terraform uses, see
https://github.com/aws/aws-sdk-go/blob/b2dc98bb584e48b0f5f39c93110633173c5da43c/aws/client/default_retryer.go#L55-L71

As described by the [relevant RFC](https://tools.ietf.org/html/rfc7231#section-6.6.4) `503 Service Unavailable` should be considered as **temporary** outage of the service - therefore I believe that retrying in this case is most logical behaviour for clients talking to the API. The service may or may not come back online during the timeout period.

@Dchamard I believe there is no dataloss in your specific case (`iam:GetUser` method) as it's read method. Correct me if I'm wrong.

@chadgrant 

> it just hangs forever, leaving no statefile, at which point you are left to destroying everything manually to attempt to re-apply.

This shouldn't be happening unless you press `Ctrl+C` twice in row - in which case Terraform also warns you about the dataloss:

```
^C^CTwo interrupts received. Exiting immediately. Note that data
loss may have occurred.
```

If a dataloss occurred after genuine timeout and no user interruption was involved then it's almost certainly a serious bug and as such deserves to be fixed - if that's the case please open a new issue and attach some details.

The default timeout for `>500` retries is 5 mins. If you're creating more resources during an outage this may unfortunately result in long hanging, but you should not wait more than ~5-10mins per 1 resource (as some resources may require 2 API calls for creation).

Generally speaking if the initial *creation* API method responds positively (HTTP code `2xx`) Terraform will consider that as success and the resource is saved into the statefile even if other following API requests time out. This is however resource-specific logic - so if you do notice any resource that doesn't behave as described do let us know by creating a new issue and ideally attaching debug log.

Should the creation method however keep responding `5xx` until the timeout expiration or you interrupt Terraform during that specific moment we do **not** save the resource to the statefile - we do not know whether API call _actually_ reached the backend AWS systems and whether the resource was created or not.

All that being said graceful shutdown in case of interruption via **single** `Ctrl+C` may still not work as we'd like, which is being addressed in a few separate issues/PRs:

 - https://github.com/hashicorp/terraform/pull/9536
 - https://github.com/hashicorp/terraform/pull/10616
 - https://github.com/hashicorp/terraform/issues/11353
 - https://github.com/hashicorp/terraform/issues/11350

I'm going to close this issue for now as we can address remaining, more specific problems in mentioned issues.

Thanks for the report.

**Comment by chadgrant** [comment]
It definitely hangs indefinitely, unless you don't think waiting 3-4hrs was long enough
