### ISSUE TITLE
panic with "unexpected EOF" and "connection is shut down" in 0.7.1

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#8409]
### Terraform Version
Terraform 0.7.1

### Affected Resource(s)
aws_vpc_peering_connection
and probably few more

### Panic Output
https://gist.github.com/antonbabenko/a8da9729b29a5ef42379bf19ea3c659d

### Steps to Reproduce
`terraform plan -refresh=true`

### References
- https://github.com/hashicorp/terraform/issues/8341

**Comment by kwilczynski** [comment]
Related to #8334. Work on fix in #8338. Original commit #8310.

**Comment by jen20** [comment]
Hi @antonbabenko! This is being tracked in a few other places - in order to cut down on repo noise, let's continue to track this on the earliest report, #8334, and on the WIP pull request with the fix, #8338. Thanks for reporting!
