### ISSUE TITLE
`terraform get` fails to get modules when "%2F" in directory name

### ISSUE THREAD

**Issue by andreub** [hashicorp/terraform#8418]
### Terraform Version
0.7.0

### Affected Resource(s)
- terraform get

### Terraform Configuration Files
```hcl
module "whatever" {
   source    = "../modules/mymodule"
   othervar  = "whatever"
} 
```

### Debug Output
http://pastebin.com/j3WuxMiy
(check RAW output, regular text is messed up)

### Expected Behavior
It should import the module stored in the relative path

### Actual Behavior
Terraform fails as it seems is decoding "%2F" as "/" instead of using it as literal value

### Steps to Reproduce
1.  rename directory to have "%2F" in it's name
2. `terraform get`

### Important Factoids
It's an Ubuntu machine, ext4 filesystem

**Comment by mitchellh** [comment]
Fix pending in this PR: https://github.com/hashicorp/go-getter/pull/30

**Comment by mitchellh** [comment]
Fixed!
