### ISSUE TITLE
Azure azurerm_template_deployment Deletes Other Resources

### ISSUE THREAD

**Issue by ritasker** [hashicorp/terraform#8429]
I am using the `azurerm_template_deployment` to create WebApps, because there isn't a resource template to do so yet.

When I run `terraform apply` I can see SQL servers, and storage accounts, etc being provisioned but Terraform will complete with resource x can't be found errors. 

Looking in the Azure portal, I can see the only resources that have been provisioned are the resources in the  `azurerm_template_deployment` resource template.

![azureportal](https://cloud.githubusercontent.com/assets/344357/17908611/238c7858-6979-11e6-895b-c804a638f33e.png)

In the activity log, you can see resources being created then deleted.

![azureactivity](https://cloud.githubusercontent.com/assets/344357/17908706/718fd3ec-6979-11e6-94bd-90b6cc5f69c0.png)

```
terraform -v
Terraform v0.7.1
```

Files and cli output
https://gist.github.com/ritasker/f1cdcbde10d35aff90423cbdbe14913b

**Comment by enieuw** [comment]
Try setting your deployment_mode to Incremental on your azurerm_template_deployment. Right now the deployment_mode is set to Complete which destroys all resources not defined in the template.

**Comment by ritasker** [comment]
Changing the deployment_mode to Incremental worked.
