### ISSUE TITLE
Set new routing tables as main in AWS

### ISSUE THREAD

**Issue by sbward** [hashicorp/terraform#843]
Related to #748 but not the same issue.

A VPC's main routing table can be swapped out for another existing routing table in the AWS console. It would be nice if Terraform could assign a routing table resource as the main routing table of a VPC.

I think that this issue, combined with #748, might be preventing Terraform from setting an Internet Gateway in the main routing table.  Is that correct?

**Comment by sbward** [comment]
Here is the corresponding API command: http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-ReplaceRouteTableAssociation.html

**Comment by phinze** [comment]
Just landed this in master - will come out with `0.3.7` :tada:

Feel free to take it for a spin on master - feedback welcome!

**Comment by carimura** [comment]
:tada:
