### ISSUE TITLE
provider/aws limited to 1 instance

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#8435]
Hi there,

I'm trying to do something that involves mutliple AWS accounts (such as a segmented dev account and a production account holding things like route53

I created modules that deploy aws instances, and a module that modifies the DNS. The instances don't have `proivder "aws"` defined, therefore they use what's in the plan calling the modules. The DNS module, however, I pass a set of credentials where it defines it's own instance of `provider "aws"`. When it comes to running the dns module, it attempts to use the credentials from the master plan (parent) instead of the credentials I passed into the module to be used with the local instance

### Terraform Version
0.7.0

### Affected Resource(s)
- aws_*

### Terraform Configuration Files
SNIP of master main.tf
```hcl
provider "aws" {
  access_key = "${lookup(var.aws_settings, "access_key")}"
  region     = "${lookup(var.aws_settings, "region")}"
  secret_key = "${lookup(var.aws_settings, "secret_key")}"
}
module "app-server" {
  source           = "aws-server"
  ...
  ...
}
module "app-dns" {
  source           = "aws-dns"
  aws = {
    a = "${var.aws_settings["prod_access_key"]}"
    s = "${var.aws_settings["prod_secret_key"]}"
    r = "${var.aws_settings["region"]}"
  }
  r53_settings     = {
    zone           = "${var.r53_settings["zone"]}"
    host           = "${replace(module.app-server.fqdn,".domain.tld","")}"
    type           = "${var.r53_settings["type"]}"
    ttl            = "${var.r53_settings["ttl"]}"
    record         = "${module.app-server.private_ip}"
  }
}
```

SNIP of aws-server main.tf
```hcl
resource "aws_instance" "server" {
  ami = "${var.aws_ami_id}"
  instance_type = "${var.aws_flavor}"
  subnet_id = "${var.aws_subnet_id}"
  associate_public_ip_address = "${var.public_ip}"
  vpc_security_group_ids = ["${split(",",var.aws_sg)}"]
  key_name = "${var.aws_key_name}"
  tags = {
    Name = "${format("ec2-%s%s-%s-%s.%s", var.basename, var.service_count, var.server_count, var.environment, var.domain)}"
    Description = "${var.tags_description}"
  }
  root_block_device = {
    delete_on_termination = true
  }
  connection {
    host = "${self.private_ip}"
    user = "${var.aws_ami_user}"
    private_key = "${var.aws_private_key_file}"
  }
  ...
}
```

SNIP of aws-dns main.tf
```hcl
variable "aws" {
  default = {
    a = ""
    r = "us-east-1"
    s = ""
  }
}
variable "r53_settings" {
  default  = {
    host   = ""
    record = ""
    ttl    = ""
    type   = ""
    zone   = ""
  }
}

provider "aws" {
  access_key = "${var.aws["a"]}"
  region     = "${var.aws["r"]}"
  secret_key = "${var.aws["s"]}"
}

resource "aws_route53_record" "record" {
  zone_id = "${var.r53_settings["zone"]}"
  name    = "${var.r53_settings["host"]}"
  type    = "${var.r53_settings["type"]}"
  ttl     = "${var.r53_settings["ttl"]}"
  records = ["${var.r53_settings["record"]}"]
}
```

### Debug Output
https://gist.github.com/mengesb/0039c633f4829445f8a09eac4818580b

### Panic Output
N/A

### Expected Behavior
second provided `provider` instance followed with new inputs?

### Actual Behavior
uses first instance of `provider` given

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by mengesb** [comment]
When I updated each module to have its own `provider "aws"` call, the plan runs successfully, however with the provider defined int he outer plan, the inner module call doesn't restrict itself to it's own configured `provider "aws"` configuration

**Comment by richardbowden** [comment]
hey @mengesb, for this i think the provider alias may help, this is what i have used in the past to to multiple account work, https://www.terraform.io/docs/configuration/providers.html worth a try

**Comment by mengesb** [comment]
That may well be. I somehow didn't notice this in the docs! Must be recent.

**Comment by jaygorrell** [comment]
Provider alias is not new, but that is the correct way to do this!

**Comment by mengesb** [comment]
I'll close this or someone can it I'm slow
