### ISSUE TITLE
vsphere: Multiple cores per vcpu

### ISSUE THREAD

**Issue by datroup** [hashicorp/terraform#8446]
Hi,

I cannot find this in any of the documentation, but when creating vm's in vsphere with terraform we're unable to set the number of cores per vcpu. Is this possible, or can this be a feature request? I know from a technical point of view it doesn't matter but we have a requirement for this to be set.

D

**Comment by datroup** [comment]
It's been a while since I added this, does anyone have any comment?

D

**Comment by paveljeloudovski** [comment]
Hi. 
It says in the code to use 1 vcore per CPU.
https://github.com/hashicorp/terraform/blob/3840ff0f40138226bcea438f4155b2754d81f90d/builtin/providers/vsphere/resource_vsphere_virtual_machine.go
Line 1748
 This is also a way recommended by vMware AFAIK. The whole cores thing is for licensing sake. 

I will try to parameterise this, as we also have a need to change this for licensing.

**Comment by paveljeloudovski** [comment]
So I've made a small change that allows to modify the number of cores per cpu.
What happens is, that vsphere takes the number of vcpus devides it by the nuber of cores and that's the number of sockets that you have.
For example 
vcpu => 8
vcore => 4
makes a machine with 2 vsockets and 4 cores per cpu
What do you think? Is this OK for everyone?

**Comment by datroup** [comment]
Hi Pavel, thanks. But would it not be simpler to just set the number of sockets by a variable? I see in the code that there is a setting which states 1, replacing that with a variable would just make it possible to set the number directly, wouldn't that be simpler?

D

**Comment by paveljeloudovski** [comment]
Hi. 
This is exactly what i did at first.
However, after consulting with our vsphere SME,the documentation and some trial and error.
The only 2 parameters you can send the API is the total number of vcpus and how many cores per socket you need. 
And the number of sockets is calculated automatically. 
So unfortunately I can't see a ways to do the sockets and cores per socket without making a changes besides adding a parameter for vcore.

I guess I can try to remove the vcpu parameter, add a vsocket one and calculate the vcpu. 

Also, I'm thinking about adding a check that will update the cpu config on the fly if possible without rebooting the machine.

**Comment by paveljeloudovski** [comment]
If you want, I can share a pkg with the vcore parmeter and the number of vsockets is calculated by vsphere. 
This was enough for our guys to be happy, so I just want to know if this is really needed before I make the effort to implement the vsockes/vcores method.

**Comment by jasonmcintosh** [comment]
This would be a nice and hopefully relatively easy feature to add.  Per discussion on VMware boards (not tested the accuracy of the statements, but they make sense):

"The other is based off physical CPU cache.  If you select two virtual sockets with one core each your VM will see two one socket CPU's, multi threaded applications will not benefit from the processors onboard cache as it wont leave something from a thread on one core and expect to see it on the other. Whereas if you have if you configure it for a single socket with two cores it will be able to utilize the cache for multi threaded applications."

https://communities.vmware.com/thread/451767?start=0&tstart=0
