### ISSUE TITLE
Bug - aws provider security_group_rule resource does not properly import

### ISSUE THREAD

**Issue by brianbianco** [hashicorp/terraform#8447]
### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group" "internal" {
  description = "internal access rules for hoth VPC"
  tags {
    Name = "hoth-internal"
  }
}

#resource "aws_security_group_rule" "internal-allow-all-vpc" {
resource "aws_security_group_rule" "internal" {
    security_group_id = "${aws_security_group.internal.id}"
    type = "ingress"
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["172.16.4.0/22","172.16.8.0/22","172.16.16.0/22","${aws_security_group.internal.id}"]
}

#resource "aws_security_group_rule" "internal-allow-all-outgoing" {
resource "aws_security_group_rule" "internal-1" {
    security_group_id = "${aws_security_group.internal.id}"
    type = "egress"
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
What should have happened?
cidr_blocks_3 should be importing the sg-b44055de security group and it is not.

### Actual Behavior
-/+ aws_security_group_rule.internal
    cidr_blocks.#:            "3" => "4" (forces new resource)
    cidr_blocks.0:            "172.16.16.0/22" => "172.16.4.0/22" (forces new resource)
    cidr_blocks.1:            "172.16.8.0/22" => "172.16.8.0/22"
    cidr_blocks.2:            "172.16.4.0/22" => "172.16.16.0/22" (forces new resource)
    cidr_blocks.3:            "" => "sg-bb4055de" (forces new resource)
    from_port:                "0" => "0"
    protocol:                 "-1" => "-1"
    security_group_id:        "sg-bb4055de" => "sg-bb4055de"
    self:                     "true" => "false" (forces new resource)
    source_security_group_id: "sg-bb4055de" => "<computed>"
    to_port:                  "0" => "0"
    type:                     "ingress" => "ingress"

### Steps to Reproduce
Create a security group rule that uses a security group rule which has another security group as it's source
Try to import that security group after defining an HCL config for it.

**Comment by brianbianco** [comment]
It looks like this is likely the offending code line:
https://github.com/hashicorp/terraform/blob/4d126aaf6f905b5b8754542d50a12f9d823620b1/builtin/providers/aws/resource_aws_security_group_rule.go#L571

**Comment by brianbianco** [comment]
This was a mistake in my terraform configuration, not a code issue.

**Comment by stack72** [comment]
👍

**Comment by brianbianco** [comment]
I think there may actually still be issues with importing these rules.  After importing certain groups, it creates a state that is actually non reproducible through the HCL tf files, since it violates certain rules "E.G. Can't use self in the same rule as cidr block".

**Comment by brianbianco** [comment]
an example of what I was saying is this output from import

```
-/+ aws_security_group_rule.internal
    cidr_blocks.#:            "3" => "3"
    cidr_blocks.0:            "172.16.16.0/22" => "172.16.16.0/22"
    cidr_blocks.1:            "172.16.8.0/22" => "172.16.8.0/22"
    cidr_blocks.2:            "172.16.4.0/22" => "172.16.4.0/22"
    from_port:                "0" => "0"
    protocol:                 "-1" => "-1"
    security_group_id:        "sg-bb4055de" => "sg-bb4055de"
    self:                     "true" => "false" (forces new resource)
    source_security_group_id: "sg-bb4055de" => "<computed>"
    to_port:                  "0" => "0"
    type:                     "ingress" => "ingress"
```

Meanwhile if you try to use the self = true field in the same rule it will cause an error in terraform as that is not allowed.  Therefore you cannot match the remote state and will always have some sort of addition / delete in terraform plan.
