### ISSUE TITLE
aws_db_option_group IAM Role in SQL Options

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#8457]
### Terraform Version

0.7.1
### Affected Resource(s)
- aws_db_option_group

The `SQLSERVER_BACKUP_RESTORE` Option in the Options Group for SQL 12.00 requires that an IAM Role be supplied when setting it.

<img width="656" alt="screenshot 2016-08-24 13 39 57" src="https://cloud.githubusercontent.com/assets/4661524/17941311/bf0e90e0-6a00-11e6-9ba8-538e8c535038.png">

There doesn't seem to be an argument in the `aws_db_option_group` yet that's able to set the IAM Role needed.

**Comment by bmurtagh** [comment]
This is a blocker for my current project.
