### ISSUE TITLE
Unable to get remote state to work with terraform_0.7.1

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#8469]
terraform_0.7.1

I can not get remote state to work with terraform_0.7.1.

```
data "terraform_remote_state" "test1" {
  backend = "s3"
  config {
    bucket = "ssi-terraform-states"
    key = "env/test1/terraform.tfstate"
    region = "eu-west-1"
  }
}
```

repeatedly seeing this error - Anyone any ideas?

missing 'access_token' configuration or ATLAS_TOKEN environmental variable

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration

**Comment by davyt10** [comment]
Issue was my fault.Closing.

**Comment by jmakanjuola** [comment]
Do you still remember how you were able to resolve the issue? @davyt10
