### ISSUE TITLE
Plugin documentation discrepancy

### ISSUE THREAD

**Issue by jefferai** [hashicorp/terraform#847]
https://www.terraform.io/docs/plugins/basics.html says:

> While its not strictly necessary, Terraform plugins follow specific naming conventions. The format of the plugin binaries are terraform-TYPE-NAME. For example, terraform-provider-aws. We recommend you follow this convention to help make it clear what your plugin does to users.

However, https://www.hashicorp.com/blog/terraform-custom-providers.html says:

> The output name (the -o flag) is *very* important. Terraform looks for plugins in the format of terraform-TYPE-NAME to autoload plugins. In this case, our plugin is a "provider" type named "dummy."

Either it's not strictly necessary, or it's extremely important. Can't be either...

**Comment by armon** [comment]
@jefferai Thanks for the catch! I believe its the "extremely important" category :)

**Comment by jefferai** [comment]
Yeah, I figured that part out myself, but feels like the documentation should get an update :-)

**Comment by mitchellh** [comment]
Fixed. Will deploy with 0.4
