### ISSUE TITLE
Plugin resolution when terraform binary is a symlink

### ISSUE THREAD

**Issue by jefferai** [hashicorp/terraform#848]
After discussion with @ryanuber on IRC I'm filing this as a bug, although it might be a known feature.

When the terraform binary is a symlink, terraform will look for plugins in the target directory of the symlink, rather than the source directory. As a user I expected that I could symlink terraform and desired plugins into a directory and have things work.

It might be nice, if terraform is a symlink, to check both the target and source directories, prioritizing the source directory.

Also, as a note, the providers were on my $PATH, but the directory that terraform symlinked to, while on my $PATH, did not contain the providers.

**Comment by mitchellh** [comment]
This is probably working as intended, unless we can figure out a way to know we were executed as a symlink. We use `sysctl` to get the executable path, as you can see here: https://github.com/mitchellh/osext/blob/master/osext_sysctl.go (assuming you're on Mac or Linux). 

Given there are so many workarounds too, I don't think this is an issue we care to fix, but if there were a PR, I'd be happy to take a look.

**Comment by jefferai** [comment]
A combination of os.Getwd() and Argv[0], plus optionally walking the path, would give you enough information to figure out which terraform binary was invoked. Then os.Stat gets you the rest of the way there. (I know, path walking isn't the nicest.)

I looked at osext_sysctl; you are probably aware, but on Linux at least, using the sysctl syscall is one of those "you really shouldn't do it although probably it will never actually be removed" things...see http://man7.org/linux/man-pages/man2/sysctl.2.html

**Comment by mitchellh** [comment]
@jefferai Yeah, but its also the most reliable way to get the true executable that ran. `argv[0]` can be faked in quite a few ways. 

Again, I think there are ways to do this that I'd look into in a PR, but I don't really want to add those hacks into TF right now.
