### ISSUE TITLE
aws_cloudwatch_event_rule documentation is missing the name attribute

### ISSUE THREAD

**Issue by ziggythehamster** [hashicorp/terraform#8480]
### Terraform Version

0.7.1

### Affected Resource(s)

- aws_cloudwatch_event_rule
- aws_cloudwatch_event_target

### Expected Behavior

The documentation for `aws_cloudwatch_event_rule` should list `name` as an attribute (or, alternatively, the `aws_cloudwatch_event_target` module should support being passed an ARN instead of a name).

### Actual Behavior

If you pass an ARN to the `rule` attribute of `aws_cloudwatch_event_target` because `name` is not documented and you didn't know better, AWS gives you this error:

```
* aws_cloudwatch_event_target.lambda: "rule" cannot be longer than 64 characters: "arn:aws:events:us-east-1:1234567890:rule/my_lambda_function_name_which_is_quite_long"
* aws_cloudwatch_event_target.lambda: "rule" doesn't comply with restrictions ("^[\\.\\-_A-Za-z0-9]+$"): "arn:aws:events:us-east-1:1234567890:rule/my_lambda_function_name_which_is_quite_long"
```

Passing the undocumented `name` attribute of `aws_cloudwatch_event_rule` makes AWS happy.

Ideally, `aws_cloudwatch_event_target`'s `rule` accepts either an ARN or a name, but this could be solved with a simple documentation update as well.

**Comment by stack72** [comment]
Hi @ziggythehamster 

Sorry this is confusing, the `name` is actually available to use. In a documentation block as follows:

```
## Argument Reference

The following arguments are supported:

* `name` - (Required) The rule's name.
* `schedule_expression` - (Required, if `event_pattern` isn't specified) The scheduling expression.
	For example, `cron(0 20 * * ? *)` or `rate(5 minutes)`.
* `event_pattern` - (Required, if `schedule_expression` isn't specified) Event pattern
	described a JSON object.
	See full documentation of [CloudWatch Events and Event Patterns](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CloudWatchEventsandEventPatterns.html) for details.
* `description` - (Optional) The description of the rule.
* `role_arn` - (Optional) The Amazon Resource Name (ARN) associated with the role that is used for target invocation.
* `is_enabled` - (Optional) Whether the rule should be enabled (defaults to `true`).

## Attributes Reference

The following attributes are exported:

* `arn` - The Amazon Resource Name (ARN) of the rule.
```

Any of the above arguments are available to other resources. 

Hope this helps

Paul
