### ISSUE TITLE
aws_cloudformation_stack documentation should provide more detail for outputs

### ISSUE THREAD

**Issue by ziggythehamster** [hashicorp/terraform#8483]
### Terraform Version

0.7.1
### Affected Resource(s)
- aws_cloudformation_stack
### Expected Behavior

The documentation should adequately explain that `outputs` is a map/dictionary and that an output from CloudFormation can be accessed by going `outputs["OutputName"]`.
### Actual Behavior

The documentation says that `outputs` is a "list of output structures". I'm not a Go programmer, so maybe it makes sense in that context, but it doesn't for me. My first instinct was to access an output by going `outputs.OutputName`, since "structure" seems to imply that I could access it as a property of the `outputs` attribute. After that didn't work, I read the code and found that it's treated as a map, and then I accessed my output as `outputs["MyOutput"]`, which worked exactly as expected.

**Comment by aleuchanka** [comment]
I agree. It's not clear at all.
Could we access values that are not in terraform.tfstate?
As I understood we can access any values from terraform.tfstate
if you have 
resource "aws_cloudformation_stack" "network" {
}
then 
out.tf could be like this
output "id" {
  value = "${aws_cloudformation_stack.network.id}"
}

output "name" {
  value = "${aws_cloudformation_stack.network.name}"
}
if terraform.tfstate have structure below
{
    "version": 3,
    "terraform_version": "0.7.4",
    "serial": 2,
    "lineage": "blah",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
                "id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "arn:aws:cloudformation:ap-southeast-2:blahAwsId:stack/networking-stack/blah",
                },
                "name": {
                    "sensitive": false,
                    "type": "string",
                    "value": "networking-stack"
                }
            },
            "resources": {
                "aws_cloudformation_stack.network": {
                    "type": "aws_cloudformation_stack",
                    "depends_on": [],
                    "primary": {
                        "id": "arn:aws:cloudformation:ap-southeast-2:blahAwsId:stack/networking-stack/blah",
                        "attributes": {
                            "disable_rollback": "false",
                            "id": "arn:aws:cloudformation:ap-southeast-2:blahAwsId:stack/networking-stack/blah",
                            "name": "networking-stack",
                            "outputs.%": "0",
                            "parameters.%": "0",
                            "tags.%": "5",
                            "tags.ClientId": "blah",
                            "tags.Department": "blah",
                            "tags.EnvironmentId": "blah",
                            "tags.EnvironmentType": "blah",
                            "tags.name": "blah",
                            "template_body": "body",
                            "template_url": "url"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
            },
            "depends_on": []
        }
    ]
}

**Comment by aleuchanka** [comment]
My bad, I didn't specified outputs in cfn template

**Comment by cirocosta** [comment]
So, should this be closed?
