### ISSUE TITLE
aws_appautoscaling_target update detaches any aws_appautoscaling_policy's

### ISSUE THREAD

**Issue by charlesbjohnson** [hashicorp/terraform#8484]
Hi there,

Updating an `aws_appautoscaling_target` (which always forces a new resource) does not trigger dependent `aws_appautoscaling_policy`s to be recreated. As a result, updating `min_capacity` or `max_capacity` causes all dependent `aws_appautoscaling_policy`s to be deleted/detached, requiring a subsequent `terraform apply` to reattach them.
### Terraform Version

v0.7.0+
### Affected Resource(s)
- `aws_appautoscaling_target`
- `aws_appautoscaling_policy`
### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_ecs_cluster" "cluster" {
  name = "demo-85e6a168597c3fe593b335df4c11496afe5dea31"
}

resource "aws_ecs_service" "service" {
  name = "${aws_ecs_cluster.cluster.name}"
  cluster = "${aws_ecs_cluster.cluster.id}"
  task_definition = "${aws_ecs_task_definition.task_definition.arn}"
  desired_count = 1
}

resource "aws_ecs_task_definition" "task_definition" {
  family = "nginx"
  container_definitions = <<EOF
[
  {
    "name": "nginx",
    "image": "nginx:latest",
    "cpu": 10,
    "memory": 500,
    "essential": true
  }
]
EOF
}

resource "aws_appautoscaling_target" "target" {
  name = "${aws_ecs_cluster.cluster.name}"
  service_namespace = "ecs"
  resource_id = "service/${aws_ecs_cluster.cluster.name}/${aws_ecs_service.service.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  role_arn = "arn:aws:iam::428324370204:role/ecsAutoscaleRole"
  min_capacity = 1
  max_capacity = 2
}

resource "aws_appautoscaling_policy" "policy" {
  name = "${aws_appautoscaling_target.target.name}"
  resource_id = "service/${aws_ecs_cluster.cluster.name}/${aws_ecs_service.service.name}"
  adjustment_type = "ChangeInCapacity"
  cooldown = 300
  metric_aggregation_type = "Average"
  step_adjustment {
    metric_interval_lower_bound = 0
    scaling_adjustment = 1
  }
}
```
### Expected Behavior

The `aws_appautoscaling_target` would be updated and the `aws_appautoscaling_policy` would still be attached.
### Actual Behavior

The `aws_appautoscaling_target` was deleted and re-created, but the `aws_appautoscaling_policy` was lost in the process. A subsequent `terraform apply` will add it back, but it either should not have been removed or it should also have been recreated along with the `aws_appautoscaling_target`.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. change `aws_appautoscaling_target.target.max_capacity` to `3`
3. `terraform apply` (causes the policy detachment)
4. `terraform apply` (reattaches the policy)
### Important Factoids

According to the AWS docs, the `aws_appautoscaling_target` can be [created as well as updated via `RegisterScalableTarget`](https://github.com/aws/aws-sdk-go/blob/master/service/applicationautoscaling/api.go#L484-L501). Perhaps this could be used instead of recreating the `aws_appautoscaling_target` on update.

**Comment by redroot** [comment]
I just experienced this as well, +1

**Comment by mats116** [comment]
I also encountered this issue with v0.7.13

**Comment by yesteph** [comment]
Same issue with v0.8.1

**Comment by maxblaze** [comment]
We're seeing the same issue in v0.8.8.

**Comment by maxblaze** [comment]
Any update on this issue? This is still happening in v0.9.6 and is really critical for us.
