### ISSUE TITLE
Add gzip support for Consul remote state

### ISSUE THREAD

**Issue by christoe** [hashicorp/terraform#8491]
After adopting terraform more and more, we've now come to a point when the tfstate is too big to be stored in Consul (that we use for remote state):

`Failed to save state: Unexpected response code: 413 (Value exceeds 524288 byte limit)`

An idea, since the state is quite verbose, would be to allow for the state to be stored gzip'ed in Consul. I'm willing to implement this myself, but I would just like to verify that this sounds sane?
### Terraform Version

Any

**Comment by carlpett** [comment]
@stack72 I ran across this today, forcing me to now start making manual changes to our AWS resources since I can no longer use terraform to change anything. Is there something preventing this getting merged?

**Comment by christoe** [comment]
Closing this as the PR that resolves this has been merged.
