### ISSUE TITLE
VM not found on creating a VM with the vSphere provisioner

### ISSUE THREAD

**Issue by iarenzana** [hashicorp/terraform#8495]
### Terraform Version

Terraform v0.7.1
### Affected Resource(s)

Please list the resources as a list, for example:
- vsphere_file
- vsphere_virtual_machine
### Terraform Configuration Files

``` hcl
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "root"
  password           = "pass"
  vsphere_server         = "192.168.200.26"
  allow_unverified_ssl   = "true"

}

resource "vsphere_file" "matt-centos6_upload" {
         datastore = "slowHDD3TB"
         source_file = "~/templates/centos6/Matt-Cent6-disk1.vmdk"
         destination_file = "/vmfs/volumes/57bc3050-5394b941-b092-0cc47ac2a28c/iar-ngali6.vmdk"
         }

resource "vsphere_virtual_machine" "ngali" {
    name        = "iar-ngali6"
    vcpu        = 1
    memory      = 2048
    time_zone   = "America/New_York"

    network_interface {
        ipv4_gateway       = "192.168.175.1"
        label          = "VM Network"
        ipv4_address       = "192.168.175.9"
        ipv4_prefix_length = "26"
    }

    disk {
        datastore = "slowHDD3TB"
#        template  = "IAR-ngali5-192.168.175.8"
        vmdk  = "iar-ngali6.vmdk"



    }
}
```
### Debug Output

https://gist.github.com/iarenzana/7ccb9fdeeba62707040ee06033a346e1
### Panic Output

https://gist.github.com/iarenzana/aa633fd46cf8e4065551118519d9c8ed
### Expected Behavior

Create a VM called iar-ngali6
### Actual Behavior

VM not found error and crash.
### Steps to Reproduce
1. `terraform apply`

**Comment by synthesizerpatel** [comment]
Not to say that it's not a terraform bug, but this might be a contributing factor as noted in your crashlog.

` ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.`
