### ISSUE TITLE
aws_autoscaling_group has no arn value

### ISSUE THREAD

**Issue by TaiSHiNet** [hashicorp/terraform#8500]
Hi, 

I'm on terraform 0.7.1, and when trying to build an IAM role policy to allow CodeDeploy target an autoscaling group, I can't reference the ASG ARN.
When I run describe-auto-scaling-groups on awscli I do get the value.
Can this be added as an attribute to aws_autoscaling_group ?

Bests,
Juan

**Comment by catsby** [comment]
Simple enough! I added that in #8503

**Comment by TaiSHiNet** [comment]
@catsby you're the fairy tale of tickets!

**Comment by stack72** [comment]
Closed via #8503
