### ISSUE TITLE
Desktop providers (Virtualbox and VMWare)

### ISSUE THREAD

**Issue by mrjcleaver** [hashicorp/terraform#8518]
Hi there,

I note these are not listed on https://www.terraform.io/docs/providers/index.html:
- https://github.com/ccll/terraform-provider-virtualbox - Virtualbox
- https://github.com/hooklift/terraform-provider-vix - VMware Fusion, Workstation, Server and Player.

I did see https://github.com/hashicorp/terraform/issues?utf8=✓&q=virtualbox and https://github.com/hashicorp/terraform/issues?utf8=✓&q=vmware , only https://github.com/hashicorp/terraform/issues/102 seems close.

Is there something else in the works or should I go ahead with these?

Do you have a policy to only list your supported drivers? How about a '3rd party / caveat emptor' list too?

Thanks,
   Martin.

https://github.com/hooklift/terraform-provider-vix/issues/32
https://github.com/ccll/terraform-provider-virtualbox/issues/5

**Comment by stack72** [comment]
Hi @mrjcleaver 

The site itself only provides the documentation for the built in providers - i.e. those in the source here on github. For the other providers, there is a guide on how to install them [here](https://www.terraform.io/docs/plugins/basics.html)

It would be very difficult for us to continually stay up to date with what 3rd party providers work (have been tested) with what versions of Terraform. There are currently no official works in progress for the the providers you need I am afraid so the 3rd party one is your best bet for now

Sorry for not having better news here

Paul
