### ISSUE TITLE
MountTargetNotFound when trying to destroy EFS

### ISSUE THREAD

**Issue by HenryTheHamster** [hashicorp/terraform#8523]
### Terraform Version
0.7.2

### Affected Resource(s)
- aws_efs_mount_target

### Terraform Configuration Files
```hcl
resource "aws_efs_file_system" "efs" {
  creation_token = "${var.stack_name}"
  tags {
    Name = "${var.stack_name}"
  }
}

resource "aws_efs_mount_target" "efs" {
  count           = "${length(compact(split(",", var.public_subnets)))}"
  file_system_id  = "${aws_efs_file_system.efs.id}"
  subnet_id       = "${element(aws_subnet.public.*.id, count.index)}"
  security_groups = ["${aws_security_group.efs.id}"]
}
```

### Debug Output
https://gist.github.com/HenryTheHamster/714cd29b9b9325801508d6bfbd80c07e

### Expected Behavior
Mount targets that are not found are considered already deleted, and destroy finishes as normal.

### Actual Behavior
```
* aws_efs_mount_target.efs.0: MountTargetNotFound: Mount target does not exist.
       	status code: 404, request id: 91b18f21-6d9b-11e6-b50e-5d876ebd0646
* aws_efs_mount_target.efs.1: MountTargetNotFound: Mount target does not exist.
       	status code: 404, request id: 91b27923-6d9b-11e6-b3a9-bbb5cfda0da7
```
Checking in AWS shows that these mount targets no longer exist, and I would expect Terraform to handle this, rather than throwing the above error. We get the same error trying to `apply` from this state.

### Steps to Reproduce
1. `terraform destroy`

**Comment by stack72** [comment]
Closed via #8529
