### ISSUE TITLE
Strange parse error when interpolating count using another resource

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#8524]
### Terraform Version

terraform 0.7.2

### Affected Resource(s)

Not specific to a resource

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-1"
}

variable "azs" {
  type = "list"
  default = [ "us-west-1b", "us-west-1c" ]
}

variable "az_cidrs" {
  type = "list"
  default = [ "10.1.0.0/16", "10.2.0.0/16" ]
}

resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/8"
}

resource "aws_subnet" "private" {
  count = "${length(var.azs)}"

  vpc_id = "${aws_vpc.default.id}"
  availability_zone = "${var.azs[count.index]}"
  cidr_block = "${var.az_cidrs[count.index]}"
}

resource "aws_route_table_association" "private" {
  count = "${length(aws_subnet.private.*.id)}"
  subnet_id = "${element(aws_subnet.private.*.id, count.index)}"
  route_table_id = "${aws_route_table.private.id}"
}

resource "aws_route_table" "private" {
  vpc_id = "${aws_vpc.default.id}"
}
```

### Debug Output

https://gist.github.com/61c3dcbe1f3d64aedbf9b04da61d70de

### Expected Behavior

Either the count is correctly interpolated or a better error message is output if it is not possible to interpolate a count using the outputs of another resource.

### Actual Behavior

An incorrect error was output:

> * Error reading aws_subnet.private count: strconv.ParseInt: parsing "${length(var.azs)}": invalid syntax

### Steps to Reproduce
1. `terraform plan`

**Comment by martin-flaregames** [comment]
may be related to issue [8415](https://github.com/hashicorp/terraform/issues/8415)?

**Comment by jszwedko** [comment]
Hmm, it does feel like it could be related though the symptoms are different.

**Comment by jszwedko** [comment]
Thank you for the prompt response and resolution!
