### ISSUE TITLE
Terraform crash when adding route53 record

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#8525]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.7.1

### Affected Resource(s)

Not sure. I'm currently working with route53_record.

### Terraform Configuration Files

I'm trying to add this resource:

```hcl
resource "aws_route53_record" "domainkey" {
  zone_id = "${aws_route53_zone.main.id}"
  name = "google._domainkey"
  type = "TXT"
  records = ["v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkr4XEdl27nmFLeBaiDkLZL92zzh73Ys5DN8LMbpFfpt48VdZzCr/Y7dfoni0csKog4lfbVihqPIHiWPz+l87FHpD3ymiZSbdbXq+eMvnhaZ93E4WEV9J8uI9xewfLGPHmzMEJw+LjEEP4spTH6OjFPCa/q1C0uHQdMIh3lcqMI5msLtsNvGA7gdIhCm6q7V6OvOwbt5hm0yuG8itMi3lTrtBdvLwd6HKtF3BA0fC7u1Th7aLVEjzgQXdqkTlX1GHiMFrbrKj+lAPK2C384IJqSD659bLPj6Z5KSwz00csSPEly6yh2InEX+q0NjVTZ27d4JOaoXHNY88qgHNEux95QIDAQAB"]
  ttl = 3600

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output

https://gist.github.com/613d26efe58011b8a001d54c453b5385

### Panic Output

https://gist.github.com/anonymous/be0d7d3292d00d2e83c007d69e26fe50

### Expected Behavior

Not crashing. :)

### Actual Behavior

Crashing. :)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing too unusual. Just set up a new terraform config here.

**Comment by kwilczynski** [comment]
@ryanking apologies for troubles!

I can see that the route cause was an error from Rotue53 back-end (see below).

Prior to version 0.7.2 there was no error checking around errors coming from the Route53 change set request response, but this was revised in https://github.com/hashicorp/terraform/commit/a86f0a8425314b09122c67df11b3a8d37676cd9e and made it into 0.7.2.

I would recommend upgrading, albeit, the issue with string being too long would have to be resolved anyway.

Actually error:

```
2016/08/29 11:48:08 [DEBUG] plugin: terraform: <ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidChangeBatch</Code><Message>Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with '&quot;v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkr4XEdl27nmFLeBaiDkLZL92zzh73Ys5DN8LMbpFfpt48VdZzCr/Y7dfoni0csKog4lfbVihqPIHiWPz+l87FHpD3ymiZSbdbXq+eMvnhaZ93E4WEV9J8uI9xewfLGPHmzMEJw+LjEEP4spTH6OjFPCa/q1C0uHQdMIh3lcqMI5msLtsNvGA7gdIhCm6q7V6OvOwbt5hm0yuG8itMi3lTrtBdvLwd6HKtF3BA0fC7u1Th7aLVEjzgQXdqkTlX1GHiMFrbrKj+lAPK2C384IJqSD659bLPj6Z5KSwz00csSPEly6yh2InEX+q0NjVTZ27d4JOaoXHNY88qgHNEux95QIDAQAB&quot;'</Message></Error><RequestId>b0b6c54b-6dcd-11e6-9481-dd015796fbaf</RequestId></ErrorResponse>
```

**Comment by ryanking** [comment]
Ok. I will upgrade when 0.7.2 hits homebrew.

**Comment by kwilczynski** [comment]
@ryanking 0.7.2 would resolve the panic, but you will still get error to ballon up.

I found this: https://forums.aws.amazon.com/thread.jspa?threadID=93940; not sure if this is going to be of any use to you.

**Comment by stack72** [comment]
Hi @ryanking 

Is this still an issue for you?

Paul

**Comment by ryanking** [comment]
It appears to be working now.

**Comment by stack72** [comment]
Thanks @ryanking :)

**Comment by 3j0s** [comment]
Greetings!
I use the follow version of terraform:
- Terraform v0.11.7
- provider.aws v1.16.0
- provider.template v1.0.0

When i try to load a new TXT "_dmarc" record i get the error as follow:

* aws_route53_record._dmarc: [ERR]: Error building changeset: InvalidChangeBatch: Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with

status code: 400, request id: ce8c7926-7b07-11e8-ba41-798a6ad710e8

Can you help me pelase?

**Comment by bngsudheer** [comment]
I have the same issue with 
```
Terraform v0.11.7
+ provider.aws v1.28.0
```

**Comment by bflad** [comment]
The current documentation for [`records` argument](https://www.terraform.io/docs/providers/aws/r/route53_record.html#records) hints how to accomplish building long records:
> * `records` - (Required for non-alias records) A string list of records. To specify a single record value longer than 255 characters such as a TXT record for DKIM, add `\"\"` inside the Terraform configuration string (e.g. `"first255characters\"\"morecharacters"`).

If the documentation can be improved here, please submit an issue in the [AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws/issues). Thanks!
