### ISSUE TITLE
Misleading documentation or a bug?

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#853]
The [documentation on the AWS provider](https://terraform.io/docs/providers/aws/index.html) (or any provider for that matter) seems to indicate I can specify the access keys via `-var` or `-var-file` on the command line:

![screen shot 2015-01-22 at 3 44 11 pm](https://cloud.githubusercontent.com/assets/408570/5864159/8aaca0de-a24d-11e4-9bcd-0e5a089e5291.png)

However, specifying the values via the command line does not work:

```text
$ terraform plan -var="access_key=ABC123"
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Module <...>: Provider 'aws' error: access_key: required field is not set
```

```text
$ cat .tfvars
access_key = "ABC123"

$ terraform plan -var-file=.tfvars
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Module <...>: Provider 'aws' error: access_key: required field is not set
```

I also tried specifying `aws_access_key`, `AWS_ACCESS_KEY`, and pretty much every other combination I could think of.

I'm not sure if this is a documentation bug or an actual bug in core, so I am not going to tag it as either, but it would be great to get some kind of direction.

The only thing that **DOES** work is specifying `AWS_ACCESS_KEY`, `AWS_SECRET_KEY`, and `AWS_DEFAULT_REGION` as environment variables, but I would like to specify the files via `-var`. Is this possible?

I have tried on Terraform v0.3.5, v0.3.6, and v0.3.6.dev (@a3faad4) and cannot get this to work. What am I missing?

**Comment by svanharmelen** [comment]
So what does your provider block look like and what variables did you define? If you use the basic example found [here](https://terraform.io/docs/providers/aws/index.html) you must have something like this in your config:

```
variable "aws_access_key" {}
variable "aws_secret_key" {}

provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region = "us-east-1"
}

...
```

With this config you should be able to call TF using `terraform plan -var "aws_access_key=ABC123" -var "aws_secret_key=ABC123"` without any issues.

What you are now trying to do is set the internal values used in the schema as variables on the command line. It's not supposed to work like that and personally I don't read it like that from the docs.

Please see [this page](https://terraform.io/intro/getting-started/variables.html) voor more info, details and examples.

Only thing you could argue is if this info should only exists in the `intro/getting-started/variables` section or maybe also (or only) in the [docs/configuration/variables](https://terraform.io/docs/configuration/variables.html) section. There is a link from `docs/configuration/variables` to `intro/getting-started/variables` but I think that one is easily overlooked. Yet it is there so maybe it's OK just as it is?

**Comment by sethvargo** [comment]
Okay, I think I figured it out. The part that is confusing is that `access_key` is a variable to the provider, but not a variable to the command line/var file. It still feels a bit weird to me.

**Comment by mitchellh** [comment]
Done
