### ISSUE TITLE
Add aws_api_gateway_usage_plan

### ISSUE THREAD

**Issue by felipemalinoski** [hashicorp/terraform#8532]
In the new version of aws cli is not possible to link **API Keys** and **API Stages** directly, as you can see [here](http://docs.aws.amazon.com/cli/latest/reference/apigateway/create-api-key.html):

> --stage-keys (list)
> DEPRECATED FOR USAGE PLANS - Specifies stages associated with the API key.

They have introduced a new configuration called **Usage plans** where you could link API Keys and yours API Stages.

I'm running in version v0.7.2.

Thanks

**Comment by felipemalinoski** [comment]
Any news about that??? Thanks

**Comment by sforcier** [comment]
Three months and no response. API keys are literally unusable without this fix.

**Comment by root-charris** [comment]
This is desperately needed!

**Comment by nkriegel** [comment]
I could really use this as well.  Can't deploy any of our API's with usage plans enabled.

**Comment by jochavez** [comment]
Is there any update on this feature? Thanks.

**Comment by Ninir** [comment]
Hi guys,

Started working on this. Will throw a PR for this very soon :)
There is a lot of work, especially for the update part, but not a big deal :)

**Comment by skarum** [comment]
Still working on this one?

**Comment by Ninir** [comment]
Just landed the work I started in a Pull Request. Still have some things to do, but I think it should be ok very soon. Sorry for the delay, lot of things going on :)

**Comment by Ninir** [comment]
Hey guys, the work on this is ended on my side. Played a lot with it, and works like a charm at the moment :)
Hope it will get merged soon!

**Comment by knaak** [comment]
Great job! Thank you!

**Comment by stack72** [comment]
Closed via #12542

**Comment by himanso** [comment]
In which version of terraform this Usage Plan changes are available? Also does it cover creation of API keys as well?

**Comment by Ninir** [comment]
Hi @himanso 
This will be in the next release I think. Regarding the API keys, I sent a PR about it here: https://github.com/hashicorp/terraform/pull/12851

It is almost OK: need to do real testing and bend the work in every possible manner to ensure everything is ok

**Comment by himanso** [comment]
Hi @Ninir 
Thanks. Please let me know when the new version of terraform with these changes are available for download?

Thanks
Himanshu

**Comment by Ninir** [comment]
Hi @himanso 

Sadly, I am not aware of this piece of information and can't provide any input. Should be in the next weeks, and really hope less than a month! :)
