### ISSUE TITLE
archive_file puts absolute path in state, causing changes for others users

### ISSUE THREAD

**Issue by manojlds** [hashicorp/terraform#8534]
### Terraform Version
0.7.2

### Affected Resource(s)
- archive_file

### Terraform Configuration Files
```hcl
resource "archive_file" "lambda" {
  type = "zip"
  source_content = "${data.template_file.lambda.rendered}"
  source_content_filename = "lambda.js"
  output_path = "${path.module}/lambda/lambda.zip"
}
```

### Expected Behavior
It should handle path such that it is relative and can be used by others to plan without having changes in the path being saved as absolute path. 

### Actual Behavior
tfstate has absolute path as `output_path`, and if `terraform plan` is run in another machine, it shows a diff just because of the different path.

**Comment by manojlds** [comment]
Should I avoid `path.module` and just use relative paths?

**Comment by Ninir** [comment]
@manojlds I guess this would be better I guess

**Comment by manojlds** [comment]
Using relative path solves my problem, so closing this.
