### ISSUE TITLE
Run `errcheck` in Travis

### ISSUE THREAD

**Issue by dtolnay** [hashicorp/terraform#8537]
[`errcheck`](https://github.com/kisielk/errcheck) is a static analyzer that detects calls to functions that return an error but the error is not checked.

``` go
func f() error { /* ... */ }

f() // <- does not check the error
```

**Comment by dtolnay** [comment]
This would have prevented the longstanding bug in #7448 as well as many many many other bugs.

**Comment by catsby** [comment]
Thanks @dtolnay ! I'll look into integrating `errcheck` into the project

**Comment by pkolyvas** [comment]
We no longer use Travis for better or worse. Closing.
