### ISSUE TITLE
[provider/aws] aws_elasticsearch_domain delete timeout too "short" ?

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#8541]
### Terraform Version
0.7.2-dev (master)

### Affected Resource(s)
- aws_elasticsearch_domain

The current Terraform implement has a timeout set at 60 mins for create/update/delete.  It is enough for create and update.  However, I notice delete can take over an hour (it's never definied in AWS documentation).  I wonder if it makes sense to increase the delete timeout on Terraform.

**Comment by stack72** [comment]
Hi @iceycake 

I agree with you on the delete timeout issue - just opened a PR that will fix the issue here

Paul
