### ISSUE TITLE
Feature Request: Spot fleet defaults

### ISSUE THREAD

**Issue by jlambert121** [hashicorp/terraform#8545]
I just created a spot fleet with `aws_spot_fleet_request` and ran into an issue of having to copy and paste `launch_specification` blocks over and over.  Five instances types in 4 different AZs means 20 copy/paste of launch configurations with the only differences being AZs, instance sizes, and weightings.

Maybe something like this that would set `launch_specification` to `launch_specification_default` and then iterate over the matrix instances and subnets to set the final parameters for each `launch_specification`.  Thoughts?

```
resource "aws_spot_fleet_request" "spot_fleet" {
  iam_fleet_role      = "role_name"
  spot_price          = "0.03"
  allocation_strategy = "diversified"
  target_capacity     = 6

  launch_configuration_matrix {
    instance_type = {
      instance_type = "c3.large"
    }
    instance_type = {
      instance_type = "c4.large"
    }
    instance_type = {
      instance_type = "c3.xlarge"
      weighted_capacity = 2
    }
    instance_type = {
      instance_type = "c4.xlarge"
      weighted_capacity = 2
    }
    instance_type = {
      instance_type = "m4.large"
      weighted_capacity = 2
    }
    availability_zone = ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d"]
  }

  launch_specification_default {
    weighted_capacity    = 1
    image_id             = "ami-123456"
    key_name             = "mykey"
    security_groups      = ["sg-abcdef"]
    user_data            = "user_data.rendered"

    root_block_device {
      delete_on_termination = true
      volume_type           = "gp2"
    }
  }
}
```

**Comment by justintime** [comment]
I think that #7034 would be a more elegant solution to the problem described here.

**Comment by jlambert121** [comment]
I think that gets some of it, not sure if it gets all of the defaults though.
