### ISSUE TITLE
Network interface private ip output

### ISSUE THREAD

**Issue by belindac** [hashicorp/terraform#8548]
Hello

I cannot upgrade because it would have to be a coordinated process, I am using v0.6.16.

### Affected Resource(s)
- output for aws_network_interface private ip

This statement
output "app_private_ip" { value = "${aws_network_interface.app.0.private_ips}" }

Produces this output
app_private_ip  = B780FFEC-B661-4EB8-9236-A01737AD98B6172.24.36.212B780FFEC-B661-4EB8-9236-A01737AD98B6

Yet, with the aws_route53_record, it correctly outputs/provides the ip address for the dns record
records = ["${aws_network_interface.app.0.private_ips}"]

### Expected Behavior
output should just have ip
app_private_ip  = 172.24.36.212

### Actual Behavior
ip is wrapped 
app_private_ip  = B780FFEC-B661-4EB8-9236-A01737AD98B6172.24.36.212B780FFEC-B661-4EB8-9236-A01737AD98B6

### Steps to Reproduce
1. Add a network interface to an instance and output the private ip

**Comment by mitchellh** [comment]
This should be fixed on 0.7 or at the very least the result would be very different. We changed the internal representation of lists to be native lists in 0.7. Please try to reproduce this on 0.7 and if it is still an issue please reopen an issue. thanks!

**Comment by belindac** [comment]
FYI, version 0.7.4 shows the same config now as the following
app_private_ip = [
    10.10.10.3
]

If you use the following, you get what I was looking for originally
output "app_private_ip" { value = "${element(aws_network_interface.app.0.private_ips,0)}" }
