### ISSUE TITLE
azurerm_storage_account: add support for kind (Storage/BlobStorage) and  access tier (Hot/Cool) 

### ISSUE THREAD

**Issue by nicocesar** [hashicorp/terraform#8558]
### Terraform Version

terraform 0.7.2
### Affected Resource(s)

azurerm_storage_account
### Expected Behavior

Terraform should support 
- the account kind (Storage/BlobStorage)
- the access tier for Blob storage accounts (Hot/Cool)

Note: this is **different** from SKU Name (LRS/ZRS/GRS/RAGRS/PLRS) which terraform already supports
### Actual Behavior

It supports SKU name via "type" attribute  (note that azure added "kind" which isn't "type", yes, I know it confusing)
### Steps to Reproduce

You can see this in the azure CLI:

```
$ azure --version
0.10.3 (node: 0.10.40)
$ azure storage account create --help
help:    Create a storage account
help:    
help:    Usage: storage account create [options] <name>
(..)
help:      --sku-name <skuName>                                   the SKU name (LRS/ZRS/GRS/RAGRS/PLRS)
help:      --kind <kind>                                          the account kind (Storage/BlobStorage)
help:      --access-tier <accessTier>                             the access tier for Blob storage accounts (Hot/Cool)
(..)
help:    Current Mode: arm (Azure Resource Management)
```
### References

https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.storage.models.storageaccount.accesstier.aspx

**Comment by nicocesar** [comment]
Any updates on this?

**Comment by stack72** [comment]
Added via #9408
