### ISSUE TITLE
aws_alb "name" optional attribute is required, preventing create_before_destroy = true

### ISSUE THREAD

**Issue by levinse** [hashicorp/terraform#8561]
Using v0.7.2, an aws_alb with the name attribute omitted and with 
`lifecycle { create_before_destroy = true }`

results in an error:

> Errors:
>
>  * aws_alb.lb: "name": required field is not set

This is in spite of the fact that https://www.terraform.io/docs/providers/aws/r/alb.html#name documents the name attribute as optional.

This is preventing me from using create_before_destroy = true because if I specify the name attribute, I receive an error that the ALB already exists with that name.

**Comment by stack72** [comment]
Hi @levinse 

Please can you give us an idea of the configuration for this so that we can try and recreate it and work out the bug. Please exclude any sensitive information :)

Thanks

Paul

**Comment by levinse** [comment]
Paul, this is trivially reproducible, as I explained. The docs say name is optional but Terraform yields an error when it's omitted. This line in the code is causing it: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_alb.go#L32

```
resource "aws_alb" "lb" {

lifecycle {
    create_before_destroy = true
}

  internal        = true
  security_groups = ["${var.sg_ids}"]
  subnets         = ["${var.subnet_ids}"]

  idle_timeout = 300
}

```

**Comment by stack72** [comment]
Sorry, @levinse, I was mistaken in what the issue was - i thought it was due to something else :)

I totally see the error now. The name *is required* as per the AWS API. I am updating the documentation right now

Paul

**Comment by stack72** [comment]
Hi @levinse 

A new version of the documentation has been pushed to the site - sorry about the issue here

Paul

**Comment by levinse** [comment]
Sorry I don't get why Terraform can't auto-generate name like it does with other resources where create_before_destroy = true is allowed (e.g. LCs, ELBs) etc.?

**Comment by levinse** [comment]
@mitchellh can you please look into this? Changing the docs clearly isn't the correct fix here...

Thanks

**Comment by stack72** [comment]
Hi @levinse 

Sorry for not getting back to you on this sooner - i didn't see the notification in inbox - apologies for this!

With regards to this specific bug, changing the docs is the correct fix - the documentation suggests the name was optional but the code wasn't. therefore, in order to stop anyone being impacted further, the site needed to be updated

Now, the issue at hand, we can indeed allow the name to be auto-generated. This is an enhancement to the resource rather than the bug fix. I will try and get this in place today. This will make a 0.7.4 release

Hope this helps

Paul

**Comment by levinse** [comment]
Perfect, thanks!

**Comment by levinse** [comment]
Hi @stack72, just following up on this - any chance to get the auto-generated names in? Would really appreciate that.

Thanks

Erik
