### ISSUE TITLE
mysql provider at terraform 0.7.2 incompatible with AWS RDS MySQL

### ISSUE THREAD

**Issue by ronaldtse** [hashicorp/terraform#8570]
The mysql provider at TF 0.7.2 became incompatible with AWS RDS MySQL due to #8251.

RDS MySQL versions are like this "5.7.11-log", in which the last part "11-log" will fail to be parsed as uint causing this cryptic message:

```
Error refreshing state: 1 error(s) occurred:
* Invalid major.minor.patch in "5.7.11-log"
```

**Comment by protomouse** [comment]
Hey @ronaldtse. Apologies for this.

**Comment by ronaldtse** [comment]
Thanks @protomouse !
