### ISSUE TITLE
Reporting crash

### ISSUE THREAD

**Issue by carlosduclos** [hashicorp/terraform#8572]
The configuration files are not public, but if you contact me I can send you a link so you can debug the issue. Notice that we use terraform to control some internal infrastructure, that is why I cannot share them publicly.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

https://gist.github.com/carlosduclos/68e43ef9f29ff806b0c118fe0160235b

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Interacting with azurerm.

**Comment by stack72** [comment]
Hi @carlosduclos 

Thanks for reporting the issue. Sorry you are running into this :( From the crash log, I can see the following:

```
2016/08/31 11:50:20 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9fa464]
2016/08/31 11:50:20 [DEBUG] plugin: terraform: 
2016/08/31 11:50:20 [DEBUG] plugin: terraform: goroutine 203 [running]:
2016/08/31 11:50:20 [DEBUG] plugin: terraform: panic(0x27f4e60, 0xc4200100e0)
2016/08/31 11:50:20 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/08/31 11:50:20 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/azurerm.resourceArmNetworkSecurityGroupRead(0xc420956c60, 0x2995620, 0xc4200a5000, 0x0, 0x1e)
2016/08/31 11:50:20 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/azurerm/resource_arm_network_security_group.go:194 +0x1e4
2016/08/31 11:50:20 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4203f4180, 0xc42019e040, 0x2995620, 0xc4200a5000, 0xc4200784a8, 0x1, 0x18)
```

In the resource_arm_network_security_group.go file, I can see this relates to the following line:

```
resp, err := secGroupClient.Get(resGroup, name, "")
if resp.StatusCode == http.StatusNotFound {
	d.SetId("")
	return nil
}
```

The error happens when we try and check the statusCode. This suggests that there was no response from the API. By any chance did you have network problems while trying to run this?

We have a lot of nightly tests that run and each of them will always evaluate that line - had there been library problems, we would have definitely ran into this before

Can you try and recreate this?

Thanks

Paul

**Comment by carlosduclos** [comment]
I don't recall any particular network problems when running this, but I'll keep on eye on this.

This runs several times a day, since this is how we recreate our test infrastructure and this is the first time we saw this. There might be a one-off problem.

**Comment by stack72** [comment]
@carlosduclos ok, this could have been an issue on the Azure side. I *think* we are safe with this.

I will close this - but please report back immediately (mention my handle) and I can get it reopened and look at it as a matter of urgency. We want to make sure that users don't see these types of crash 

Paul
