### ISSUE TITLE
Templates to create Cloudwatch alarm

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#8575]
Hi there,

Terraform v0.7.1

I am attempting to use a template file to create a CloudWatch alarm for many instances. Since modules do not allow count, I am not able to iterate through all my instances hence I am investigating if a template file comprising of a Cloudwatch alert could server this purpose. I am getting 
## the following error. I am unsure if I am even using templates in the correct manner.

terraform : [31mError loading config: Error parsing C:\repos\Architecture\quest-cc\terraform\tongetest1\template.tf: At 5:13: illegal char[0m[0m
At line:1 char:1
- terraform plan
- ~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: ([31mError load...al char[0m[0m:String) [], RemoteException
  ## \+ FullyQualifiedErrorId : NativeCommandError

data "template_file" "cloudwatch-ec2" {
  count = "2"
  template = "${file("cloudwatch-ec2.tf")}
  vars {
    name = "${element(aws_instance.TestByraN._.tags.Name, count.index)}"
    instID = "${element(aws_instance.TestByraN._.id, count.index)}"
   }
}

resource "aws_cloudwatch_metric_alarm" "cpu_credits" {
  alarm_name = "${var.name} - Low CPU Credits"
  comparison_operator = "LessThanOrEqualToThreshold"
  dimensions { InstanceId = "${var.instID}" }
  evaluation_periods = "10"
  metric_name = "CPUCreditBalance"
  namespace = "AWS/EC2"
  period = "120"
  statistic = "Average"
  threshold = "200"
  alarm_description = "This metric monitors low ec2 cpu credits for T2 instances"
  insufficient_data_actions = []
  alarm_actions = ["arn:aws:sns:eu-west-1:XXXXXXXXXXX:CloudwatchAlerts"]
}

variable "instID" { description = "InstanceId" }
variable "name" { description = "Name tag of instance" }

**Comment by pporada-gl** [comment]
@davyt10 Can you put your code into a code block so it's easier to parse.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

It looks like you've got extra periods in the following block. Respectively they are lines 5 and 6 which Terraform is yelling about in the error message.
```
name = "${element(aws_instance.TestByraN ====>.. <==== tags.Name, count.index)}"
instID = "${element(aws_instance.TestByraN ====>.. <==== id, count.index)}"
```

**Comment by davyt10** [comment]
This should have read, the asterisk was removed for some reason.

```
data "template_file" "cloudwatch-ec2" {
count = "2"
template = "${file("cloudwatch-ec2.tf")}
vars {
name = "${element(aws_instance.TestByraN.*.tags.Name, count.index)}"
instID = "${element(aws_instance.TestByraN.*.id, count.index)}"
}
}
```
