### ISSUE TITLE
vSphere network label inconsistency with VDS in vCenter folder

### ISSUE THREAD

**Issue by qvallance-ctc** [hashicorp/terraform#8584]
Running into an issue with networking in the vsphere provider:

Terraform cannot locate the network interface label when the virtual distributed switch (vds) is located in a folder, unless the folder is added to the label path (e.g., 'folder/label').  Once the VM is deployed, if another Terraform plan/apply is run against the resource it will identify the network interface label as not containing the folder, thus requiring the resource to be recreated or config changed.
### Terraform Version

Terraform v0.7.2
### vSphere Version

vSphere 6.0
### Affected Resource(s)
- vsphere_virtual_machine
### Error Example

When the config includes just the label it cannot find the label:

``` hcl
  network_interface {
      label = "label"
      ipv4_address = "10.0.0.10"
      ipv4_prefix_length = "24"
      ipv4_gateway = "10.0.0.1"
  }
```

```
terraform apply
[...]
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.rhl7: network '*label' not found
```

When the label includes folder, it deploys fine but it does not match the label returned when planning/applying:

``` hcl
  network_interface {
      label = "folder/label"
      ipv4_address = "10.0.0.10"
      ipv4_prefix_length = "24"
      ipv4_gateway = "10.0.0.1"
  }
```

```
terraform plan
[...]
    network_interface.0.label:              "label" => "folder/label" (forces new resource)
```

**Comment by Guismo1** [comment]
same for me here

**Comment by becks** [comment]
I have the same problem. Thanks!

**Comment by sizgiyaev** [comment]
Hi, is there a solution for the issue?

**Comment by lvlie** [comment]
+1
This is still the same in 0.9.1. We use a workaround to be able to add resources without existing resources being recreated, but this adds other problems if you would want to change the network (requires a taint first):
`lifecycle {
  ignore_changes = ["network_interface"]
} `

**Comment by sidhurana** [comment]
Hi,

My network label is "v686 10.10.0.0/16" So, it contains space and forward slash. While executing i am getting same error : Network not found. 

Any idea how to get rid of this ? 

Thanks,
Sudhir

**Comment by stravze** [comment]
Hello

What version of terraform you running ?

Regards

James

**Comment by sidhurana** [comment]
Hi James,

 Terraform version: 0.9.2

**Comment by sidhurana** [comment]
Just tried with latest version. Got same results.

**Comment by stravze** [comment]
yeah was  thinking in a later version might fix this

**Comment by Malet** [comment]
I've also run into this same issue on the latest version 0.10.6 @lvlie thanks for the workaround!

There is also a bug report in the provider repo: https://github.com/terraform-providers/terraform-provider-vsphere/issues/11
