### ISSUE TITLE
Terraform crash when adding aws_route53_record

### ISSUE THREAD

**Issue by ultra70** [hashicorp/terraform#8587]
### Terraform Version
0.7.1

### Affected Resource(s)
aws_route53_record

### Terraform Configuration Files
https://gist.github.com/ultra70/9f4cf53478dcf506a956577928ea3d9b

### Debug Output
https://gist.github.com/ultra70/8a3164f9e7342053562bd0815dd0da3c

### Panic Output
https://gist.github.com/ultra70/1a538ab2fe903474673712b7b9a7f563

### Expected Behavior
aws_route53_record.m1_txt created in AWS Route53

### Actual Behavior
Nothing happened on the AWS side.

### Steps to Reproduce
Add a . to the end of name = "m1._domainkey" in resource "aws_route53_record" "m1_txt" then run terraform apply

### Important Factoids
None

### References
None

**Comment by stack72** [comment]
Hi @ultra70 

Sorry this has caused you problems - this is actually something we have already fixed as part of Terraform 0.7.2 #8399

Hope this helps

Paul

**Comment by ultra70** [comment]
Thanks stack72, I'll update and try again.

**Comment by ultra70** [comment]
Looking good, thank you.

**Comment by ultra70** [comment]
Looking good, thank you.

**Comment by stack72** [comment]
👍
