### ISSUE TITLE
Error setting up client: dial tcp: no suitable address found when connecting to vsphere

### ISSUE THREAD

**Issue by byronrau** [hashicorp/terraform#8592]
Hi,

I am having an issue with Terraform versions 0.7.1 and 0.7.2 when connecting to vsphere server.  It worked in 0.7.0.  When I upgraded to  0.7.1 or 0.7.2, whenever I run any of the terraform commands plan, refresh, apply it gives an error:

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:
- Error setting up client: Post https://server/sdk: dial tcp: no suitable address found

I am using local variables.tf in the directory running terraform from and including a global.tfvars one directory up.

global.tfvars:
###### 
# vSphere Global Variables
# export TF_VAR_vsphere_password=
# export TF_VAR_vsphere_user=

vsphere_server                = "server.domain.local"
vsphere_folder                = "Folder"
###### 
# Networking Vlans

lab_vlans             = "vlan"
###### 
# Templates variables

template_centos               = "CentOS7Template"
template_winrm2k8             = "Win2008R2"
template_winrm2k12            = "Win2012Template"
template_datastore            = "datastore"

local variables.tf:
###### 
# vSphere Global Variables
# export TF_VAR_vsphere_password=
# export TF_VAR_vsphere_user=

variable "vsphere_user" {}
variable "vsphere_password" {}

variable "vsphere_server" {}
variable "vsphere_folder" {}
###### 
# Networking Vlans

variable "lab_vlans" {}
###### 
# Templates variables

variable "template_centos" {}
variable "template_winrm2k8" {}
variable "template_winrm2k12" {}
variable "template_datastore" {}
# Windows domain credentials for vm

variable "domain_user" {}
variable "domain_user_password" {}

Now when I change the vsphere_server in global.tfvars to use an IP address it works, but when using the domain name is when the error occurs.
### Debug Output

https://gist.github.com/byronrau/8323ee06c8e9c0ab2ad1659e5d07afc6
### Panic Output

NA
### Expected Behavior

Terraform commands should work.
### Actual Behavior

Error setting up client
### Steps to Reproduce

Run any of the terraform commands connecting to a vsphere server.
### Important Factoids

NA
### References

NA

**Comment by piwi3910** [comment]
any news? same issue here

**Comment by Bhuwan** [comment]
I'm seeing the same error on 0.7.1 and higher (works fine on 0.7.0) when attempting to output data to consul.  As such, I do not believe this error specifically relates to vSphere.

**Comment by Bhuwan** [comment]
Could this issue be related to Go 1.7 (https://github.com/golang/go/issues/16739) ?

**Comment by Bhuwan** [comment]
Workaround: 

I went ahead and built v0.7.4 of Terraform using Go 1.7.1 (vs 1.7) by editing the Vagrantfile.  The issue above is gone.  I'm now fairly confident that this bug is related to the previously mentioned GoLang bug.
