### ISSUE TITLE
aws_ecr_repository apply delete race condition

### ISSUE THREAD

**Issue by hendrik-rebuy** [hashicorp/terraform#8597]
### Terraform Version
terraform v0.7.1

### Affected Resource(s)
- aws_ecr_repository

### Terraform Configuration Files
```hcl
resource "aws_ecr_repository" "repository" {
  name = "repository-name"
}
```

### Expected Behavior
On an apply and a following destroy the resource should always be created and destroyed

### Actual Behavior
sometimes the resource is not destroyed but still removed from the state file.
(Conjecture: Could be a race on Amazon side when creating a resource in that case the create should make sure the resource is up and usable).

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`
3. repeat until error occurs (tried with 27 repositories up to 40 runs may be necessary)

We are running into this issue on our testing environment.  Our clean up step doesn't always clean up the freshly created repositories.

**Comment by bjoernhaeuser** [comment]
Hi! We would love to contribute a patch for this. Is there any preferred solution for this? Waiting for  the destroy or waiting for the creation of the repos?

**Comment by stack72** [comment]
Hi @hendrik-rebuy (and @bjoernhaeuser)

I have just this minute added a retry to the logic for the ECR Repository deletion. This will try, for a period of 20minutes, to make sure that the ECR repository has been deleted by checking it doesn't actually exist

This will be released (hopefully) in Terraform 0.7.5

Paul

**Comment by hendrik-rebuy** [comment]
awesome I'll test it immediately

**Comment by hendrik-rebuy** [comment]
@stack72 I could not reproduce the issue with your branch, the retry logic fixed it.

**Comment by stack72** [comment]
Success! :) thanks for testing this :)

**Comment by hendrik-rebuy** [comment]
thanks for fixing it!
