### ISSUE TITLE
OpenStack provider: operations fail after provider-side change.

### ISSUE THREAD

**Issue by shockinghobby** [hashicorp/terraform#8608]
There was a change at the provider side since I last run `terraform apply`. Specifically, a new region was introduced and most resources now require a new resource argument to be specified, which is not in the tfstate or tf file.

Terraform provider used is OpenStack.

Error is the same for all resources:
```
...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

openstack_blockstorage_volume_v1.root: Refreshing state... (ID: )
Error refreshing state: 13 error(s) occurred:

* openstack_blockstorage_volume_v1.root: Error creating OpenStack block storage client: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"", Region:"ru-1", Interface:"public", URL:""}, tokens.Endpoint{ID:"", Region:"ru-2", Interface:"public", URL:""}}
...
```
Affected resources:
- openstack_blockstorage_volume_v1
- openstack_compute_keypair_v2
- openstack_networking_network_v2
- openstack_networking_router_v2
- openstack_compute_instance_v2

**Comment by jtopjian** [comment]
Each resource has a `region` attribute. Are you specifying the region in each resource?

If your Keystone catalog contains multiple regions, this will now be a requirement.

**Comment by shockinghobby** [comment]
@jtopjian My original tf file doesn't have this attribute in any of the resources. The provider didn't have any regions at the time and `apply` worked without specifying one. My guess is that it wasn't (required) then.

**Comment by jtopjian** [comment]
@shockinghobby The OpenStack provider has never had a `region` attribute, but all resources in the OpenStack provider have always had a `region` attribute.

Another way of getting around not specifying region is to set the environment variable `OS_REGION_NAME`.

**Comment by shockinghobby** [comment]
@jtopjian I guess the default one was used, because neither tf nor tfstate have any mentions of `region`.

Setting the variable doesn't do anything now. I also updated my first comment to include that it fails on 'refreshing' resources.

**Comment by jtopjian** [comment]
Sorry, perhaps we're confusing terms. When you say "provider", do you mean your cloud provider or the Terraform OpenStack provider? :)

Prior to your cloud provider adding a new region, correct, the single region in the catalog was being used by default.

So your resources currently look something like this:

```
resource "openstack_compute_keypair_v2" "mykey" {
  name = "mykey"
}
```

And when you run Terraform, it's failing with a token error. This makes sense and is normal.

But, just to clarify, when you change your resources to:

```
resource "openstack_compute_keypair_v2" "mykey" {
  name = "mykey"
  region = "ru-1"
}
```

Terraform is still failing?

**Comment by shockinghobby** [comment]
Possible :-)

Yes, by "provider" I meant our cloud provider.

And yes, it is failing even if I add `region` attribute to all of the affected resources in the original tf file.

**Comment by jtopjian** [comment]
OK, are you getting the same error message when you add `region` or a different message?

**Comment by shockinghobby** [comment]
The message is identical in both cases.

**Comment by jtopjian** [comment]
OK, I'll dig into the token code and see if I can figure out what's going on. Thank you for the info :)

**Comment by jtopjian** [comment]
@shockinghobby quick question: what happens if you were to manually add the `region` setting to the terraform state file?

**Comment by shockinghobby** [comment]
@jtopjian Hey. It works as expected then. `terraform plan` schedules a lot of updates due to configuration drift and server-side changes. For example, `volume_type: "basic.ru-1a" => "basic"`, but this is expected and can be easily fixed.

**Comment by jtopjian** [comment]
Awesome! OK, I'm going to consider this issue closed. Directly modifying the state isn't the best way to go about things, but considering the cloud provider changes, it looks like that's the only solution available.

However, please re-open if you're still having problems or if you have any questions.
