### ISSUE TITLE
Terraform panics when running plan after upgrading from 0.6.16 -> 0.7.2

### ISSUE THREAD

**Issue by conord33** [hashicorp/terraform#8609]
I am attempting to upgrade terraform for a Google project from 0.6.16 -> 0.7.2. So far I have been unsuccessful in doing so. After making the necessary syntax updates, I consistently receive a panic when running plan or apply on the project. If I destroy the project and then rebuild the whole thing with 0.7.2 there is no issue. The panic only occurs when project is built with 0.6.16, the state file still exists, and then a terraform command is run with version 0.7.2.

### Terraform Version
Updating from 0.6.16 -> 0.7.2. Issues happen when running 0.7.2 with a state file from 0.6.16.

### Affected Resource(s)
Crashes

### Panic Output
https://gist.github.com/conord33/ed26056e5165b126ffa564af2e85f579

### Expected Behavior
When running plan with the upgraded version, I should see a plan with no actions to take.

### Actual Behavior
Crash

**Comment by jen20** [comment]
Hi @conord33! I've taken a look here and I think fixed the issue - could you verify whether this fixes the issue for you? There is an alternate (probably better) way to fix this by fixing the state migration, but I just want to verify this is the correct behaviour before making that change.

**Comment by conord33** [comment]
Hey @jen20 it worked! Any idea when this fix will get released?

**Comment by conord33** [comment]
Hey @jen20 has there been any movement on this fix?

**Comment by conord33** [comment]
@jen20 @stack72 Just wanted to check in. Is this getting fixed any time soon?

**Comment by caseylang** [comment]
There have been a few releases of Terraform so far which don't seem to include this fix. Any chance the resolving commit will be merged soon?
