### ISSUE TITLE
aws_alb_listener - ssl_policy attribute is always shown as changed when omitted

### ISSUE THREAD

**Issue by bsiegel** [hashicorp/terraform#8612]
### Terraform Version
0.7.1

### Affected Resource(s)
- aws_alb_listener

### Terraform Configuration Files
```hcl
resource "aws_alb_listener" "web_https" {
  load_balancer_arn = "${aws_alb.web.arn}"
  port              = 443
  protocol          = "HTTPS"
  certificate_arn   = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:server-certificate/my_cert"

  default_action {
    target_group_arn = "${aws_alb_target_group.upstream_http.arn}"
    type             = "forward"
  }
}
```

### Expected Behavior
After applying the change, a subsequent `plan` should show no changes required.

### Actual Behavior
```
~ aws_alb_listener.web_https
    ssl_policy: "ELBSecurityPolicy-2015-05" => ""
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### References
- GH-8268

**Comment by stack72** [comment]
Hi @bsiegel 

Is `ELBSecurityPolicy-2015-05` something you created? Or is this a default SSL policy being applied?

Paul

**Comment by bsiegel** [comment]
Hi Paul - that's the default (and currently only) available SSL policy for ALBs.






On Fri, Sep 2, 2016 at 9:31 AM -0400, "Paul Stack" <notifications@github.com> wrote:












Hi @bsiegel 



Is ELBSecurityPolicy-2015-05 something you created? Or is this a default SSL policy being applied?



Paul

**Comment by stack72** [comment]
@bsiegel 

Got it - will change that field to computed as well then :)

P.
