### ISSUE TITLE
Terraform crashed after adding a variable map - apparently a restricted value

### ISSUE THREAD

**Issue by wingnut128** [hashicorp/terraform#8614]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
v0.7.2
### Affected Resource(s)

Please list the resources as a list, for example:
-aws_instance
It actually barfed before it got to any resources.
### Terraform Configuration Files

``` hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

I didn't include my config - and honestly I wasn't going to open a ticket - because I realized I did a bone-headed maneuver (I created a variable map with the name account_id ... that apparently has special meaning ... I renamed the map and the plan worked).

I just opened a ticket because the software told me too 😬 And if it's something that can be caught somewhere in the evaluation ... cool.
### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
https://gist.github.com/wingnut128/9e3b8e26a1f49ee9e569c63563e9bbe9
### Expected Behavior

What should have happened?
Plan should have accomplished nothing
### Actual Behavior

What actually happened?
Crashed
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
Output from make
Creating a plan: terraform plan -var profile=production -var aws_region=us-west-2 -var environment=production-us-west-2 -var-file=./production.tfvars  -out tf.plan

**Comment by mitchellh** [comment]
I couldn't reproduce this anymore and I think its a dup of #8736. Fixed!
