### ISSUE TITLE
attaching a virtual private gateway to a vpc exceeds timeout default

### ISSUE THREAD

**Issue by lukasbernat** [hashicorp/terraform#8632]
details below, in real life scenario, attachment takes sometimes more then 5minutes (noticed up to 8minutes so far)
recommend timeout value of 10min, or a way to configure defaults

Terraform v0.7.2

"aws_vpn_gateway_attachment" 
...
module.payletter-vpc-usw1.aws_vpn_gateway_attachment.vpn_attachment: Still creating... (5m0s elapsed)
Error applying plan:

1 error(s) occurred:

aws_vpn_gateway_attachment.vpn_attachment: Error waiting for VPN Gateway "vgw-*****" to attach to VPC "vpc-****": timeout while waiting for state to become 'attached'

**Comment by kwilczynski** [comment]
@lukasbernat apologies for the issue!

I will resolve this right away.

**Comment by stack72** [comment]
Closed via #8638

**Comment by Z3r0Sum** [comment]
@stack72 Can we re-open this?  I think the timeout should be bumped to at least 20 minutes.  I can make the adjustment if you would like.
