### ISSUE TITLE
Block Device Mapping support for AWS Launch Configurations

### ISSUE THREAD

**Issue by jschneiderhan** [hashicorp/terraform#865]
It would be nice to be able to specify `block_device_mappings` for `aws_launch_configuration` resources.

I'm working on a PR to add support.

**Comment by xueshanf** [comment]
See #756.  It  is accepted as an enhancement.

**Comment by jschneiderhan** [comment]
Oh OK, thanks @xueshanf. I'll close this as a duplicate.
