### ISSUE TITLE
Waiting for ELB Capacity does not work with the ALB

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#8655]
### Terraform Version

Terraform v0.7.2
### Affected Resource(s)
- aws_autoscaling_group
- aws_alb
- aws_alb_target_group
### Terraform Configuration Files

I'm trying to create an Auto Scaling Group that supports rolling deployment following the approach described by @phinze [here](https://groups.google.com/forum/#!msg/terraform-tool/7Gdhv1OAc80/iNQ93riiLwAJ). The basic idea is to make the `aws_autoscaling_group` resource name directly depend on the `aws_launch_configuration` name and to add a `create_before_destroy = true` to each one so that for any change, a new ASG is created before the old one is deleted. As part of this process, we've been using the `min_elb_capacity` parameter to ensure that the old ASG isn't deleted before at least `min_elb_capacity` instances have registered as "healthy" with the load balancer. 

This worked fine with the ELB, but does not seem to work with the ALB and ALB Target Groups. With the ALB, Terraform starts deleting the old ASG _before_ all the instances have registered as healthy with the ALB's Target Group. I believe this is because the [waitForASGCapacity function](https://github.com/hashicorp/terraform/blob/e3e4b6c2ac3eb69036dba32dc0351a42a67e7c0d/builtin/providers/aws/resource_aws_autoscaling_group_waiting.go#L19) uses [getLBInstanceStates](https://github.com/hashicorp/terraform/blob/e3e4b6c2ac3eb69036dba32dc0351a42a67e7c0d/builtin/providers/aws/resource_aws_autoscaling_group.go#L806), which fetches the status from the ELBs in the `load_balancers` parameter but does NOT take into account the ALB Target Groups in the `target_group_arns` parameter.

Some sample code:

``` hcl
resource "aws_autoscaling_group" "autoscaling_group" {
  name = "${aws_launch_configuration.launch_configuration.name}"
  launch_configuration = "${aws_launch_configuration.launch_configuration.name}"

  min_size = 4
  max_size = 4
  min_elb_capacity = 4

  target_group_arns = ["${aws_alb_target_group.default_group.arn}"]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_launch_configuration" "launch_configuration" {
  name_prefix = "my-launch-config-"
  image_id = "ami-abcd1234"
  instance_type = "t2.micro"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_alb_target_group" "default_group" {
  name = "default-group"
  port = 8080
  protocol = "HTTP"

  health_check {
    path = "/health"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
### Expected Behavior

When I make a change to the `aws_launch_configuration` above, it should create a new ASG, wait for 4 instances in that ASG to show up as "Healthy" in the ALB, and then delete the old ASG. 
### Actual Behavior

It creates a new ASG, seems to wait for a little while, perhaps just for the instances to show as as "Healthy" according to EC2 (but NOT the ALB), and then deletes the ASG. As a result, my app has a brief downtime.

Note that if I replace the `target_group_arns` parameter in the `aws_autoscaling_group` with `load_balancers` parameter pointing at a standard ELB (`aws_elb`), it waits correctly.
### Steps to Reproduce
1. `terraform apply`
2. Wait for everything to come up
3. In the background launch an infinite loop to hit the ALB once per second:
   
   ```
   while true; do curl http://<alb_dns_name>; sleep 1; done
   ```
4. Make some change to the launch configuration 
5. `terraform apply`
6. You'll see 200 OK responses from the ALB for most of the time, but just as the old ASG is being deleted, you'll see some number of 502's and 504's.

**Comment by brikis98** [comment]
Update: It's possible that this is actually a bug with the ALB (although the `getLBInstanceStates` function is probably buggy too). Instead of using Terraform, I tried to do a zero-downtime rolling update of an ASG with CloudFormation and saw the same problem: 504 and 502 errors. After doing more digging, my suspicion is that the EC2 Instances are not being deregistered from the ALB correctly and allowed to drain their connections. Instead, they are being suddenly shut down, even with requests potentially in progress, which is what causes the 502 and 504 errors.

I've asked a question on the AWS forum to see if I can get more info: https://forums.aws.amazon.com/thread.jspa?messageID=739905&#739905

**Comment by brikis98** [comment]
Update: The ALB bug discussed in https://forums.aws.amazon.com/thread.jspa?threadID=238679#741887 has been fixed. However, the bug in the Terraform `aws_autoscaling_group` resource when used in conjunction with an `aws_alb_target_group` still remains. 

To repro the bug, try the following:

1. Create an ASG that can do "rolling deployments" as described by @phinze [here](https://groups.google.com/forum/#!msg/terraform-tool/7Gdhv1OAc80/iNQ93riiLwAJ).
1. Run a simple web server on each EC2 Instance in the ASG that just returns the text "Hello, World". Check out the [list of static server one-liners](https://gist.github.com/willurd/5720255) for easy ways to do that.
1. Attach an ALB to this ASG using the `target_group_arns` param.
1. Run `terraform apply` to deploy everything.
1. In a terminal tabs, run `curl` in a loop, hitting the ALB URL every 100ms: 

    ```
    while true; do curl http://<load_balancer_url>; sleep 0.1; done
    ```
1. You should now see the text "Hello, World" repeating over and over again.
1. Update the ASG in some way. For example, you could change the EC2 Instances to return "Goodbye, World".
1. Run `terraform apply` to deploy everything.
1. If you watch the `curl` loop while the deployment is happening, you'll see something like this:

    ```
    Hello, World
    Hello, World
    Hello, World
    <html>
    <head><title>504 Gateway Time-out</title></head>
    <body bgcolor="white">
    <center><h1>504 Gateway Time-out</h1></center>
    <hr><center>awselb/2.0</center>
    </body>
    </html>
    Goodbye, World
    Goodbye, World
    Goodbye, World    
    ```
1. Repeat the exact same experiment, but instead of using an ALB, attach an ELB via the `load_balancers` parameter. If you do a redeploy with this arrangement, you'll see something like this:

    ```
    Hello, World
    Hello, World
    Goodbye, World
    Goodbye, World
    Goodbye, World    
    ```

**Comment by stack72** [comment]
Hi @brikis98 

Please can you tell me if this is still an issue for you? The thread suggests that the rollout was in progress as this was commented out 

Paul

**Comment by brikis98** [comment]
@stack72 Yes, this is still an issue. When I run my ALB tests against an ASG created with CloudFormation, I can do a deployment with zero downtime. When I run the same ALB tests against an ASG created with Terraform, I always get 504's when doing a deployment. I believe this is because of bugs in the `waitForASGCapacity` and `getLBInstanceStates` functions, as explained above. If you try the repro steps I listed, you should see this bug very easily.

**Comment by michaelgrosser** [comment]
This is also causing me problems with several processes. Wait for capacity is not working properly with ALBs. The reason is because you're only using the elb AWS lib which uses the elb AWS API. You need to use the elbv2 lib which uses the elbv2 API when checking on the state of an instance in an ALB. As @brikis98 rightly points out, your current library just ignores the ALB status because it asks for a list of ELBs the instance is attached to, which is rightly empty. 

So, I noticed @stack72 labeled this as an upstream problem, but this isn't really an upstream problem and needs addressing in the Terraform source to use the new elbv2 lib, which is available in the Go SDK.

**Comment by plefebvre** [comment]
This is also causing me problems.  For now, we'll put an artificial sleep as a local-exec provisioner after the creation of the ASG but that is far from perfect since instances failing at startup wouldn't abort the destruction.

**Comment by michaelgrosser** [comment]
Is this getting any attention at all? The status hasn't changed at all in quite a while, so I'm concerned that this isn't getting more attention. This isn't a minor issue. It's a documented feature on ASGs that outright does not work correctly any longer.

**Comment by stack72** [comment]
Hi @michaelgrosser 

Apologies that you feel that this isn't getting any attention - I assure you it hasn't slipped through the cracks. One of the team will pick this up asap! As you can see, we have a lot of open issues to get through and triage. Please bear with us for a tiny bit longer

Thanks

Paul

**Comment by michaelgrosser** [comment]
@stack72 Thanks. I just wanted to make sure it hadn't fallen through the cracks since it hadn't gotten any further replies or status changes.

**Comment by vancluever** [comment]
Hey all!

If you are so able to, can you please try merging in #10243 and see if it fixes the problem for you? I have tested the test included manually against master and got a successful failure (heh), versus a passing test with the full PR.

Cheers!

**Comment by stack72** [comment]
testing this right now @vancluever....

**Comment by owenmorgan** [comment]
hello. im still seeing this issue on 0.8.4. When I replace an ASB which is behind an ALB, I will see a group of ec2s in the target group go from healthy to draining, until they all drop off the target group, leaving any requests to my application to fail, ill then start to see the new ec2s join the target group and eventually become healthy. causing a down time during the deployment.
