### ISSUE TITLE
how to refer tfstate in other directory

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#8659]
like:

````
- folderA
  - vpcA.tf
  - peering_connection.tf
  - terraform.tfstate
- folderB
  - vpcB.tf
  - terraform.tfstate
````

I need vpc id of vpcB to set in `peering_connection` in folderA, Now I
can only just hard coding vpcB id in that file. How to solve this situation?

Thank you for your time.

**Comment by jamielennox1** [comment]
```hcl
data "terraform_remote_state" "folderB" {
    backend = "local"
    config {
        path = "${path.module}/../folderB/terraform.tfstate"
    }
}
```

you can now reference like this: data.terraform_remote_state.folderB.vpc_id

**Comment by hanks** [comment]
Oh, awesome, thank you very much
Jamie Lennox <notifications@github.com>于2016年9月5日 周一22:32写道：
