### ISSUE TITLE
Deprecate old AWS_* variables

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#866]
See https://github.com/hashicorp/terraform/pull/851 for more information. The documentation is already updated, just need to print a nice deprecation warning when the old variables are used.

**Comment by mitchellh** [comment]
I'm actually going to say "let's just not do this" because deprecating and eventually removing will just cause pain to some users which is useless since its pretty harmless to support. As you said, its already documented, so no one will "learn" the old variables. I think that's good enough.
