### ISSUE TITLE
data source template_file fails with "read /: is a directory" when template attribute interpolation or literal returns a "/"

### ISSUE THREAD

**Issue by martin-flaregames** [hashicorp/terraform#8660]
Cannot see this in the documentation, so here I go. 

`terraform plan` fails with `read /: is a directory` when the value assigned to the `template` attribute of the `template_file` data source equals `/`.
### Terraform Version

`Terraform v0.7.2`
### Affected Resource(s)
- template_file
### Terraform Configuration Files

``` hcl
variable "ping_path_separator" {
  default = {
    HTTP = "/"
    HTTPS = "/"
    TCP = ""
    SSL = ""
  }
}

data "template_file" "ping_path_separator" { template = "${lookup(var.ping_path_separator, "HTTP")}" }
```

or simply

``` hcl
data "template_file" "broken" { template = "/" }
```
### Expected Behavior

It should not fail an `rendered` should return `/`
### Actual Behavior

It fails as described :)
### Steps to Reproduce

`terraform apply`

**Comment by jamielennox1** [comment]
I think you're meant to structure it like this:

```hcl
variable "ping_path_separator" {
  default = {
    HTTP = "/"
    HTTPS = "/"
    TCP = ""
    SSL = ""
  }
}

data "template_file" "ping_path_separator" {
  template = "${ping_path_separator}"

  vars {
    ping_path_separator = "${lookup(var.ping_path_separator, "HTTP")}"
  }
}
```

**Comment by martin-flaregames** [comment]
@jamielennox1 that works indeed. Thanks. Will use that workaround.

But I still fail to understand why this specific case fails.

I normally do interpolations directly in the `template` argument because according to the docs it is not forbidden to do so and it keep the descriptive code slim.

**Comment by jamielennox1** [comment]
Filename was deprecated for template. This means we can specify both inline templates and reference template files. / is a directory inside UNIX. So, it's going to assume you're trying to load a file instead of inline.

to prove that this is the case:
```hcl
variable "ping_path_separator" {
  default = {
    HTTP = "Test /"
    HTTPS = "/"
    TCP = ""
    SSL = ""
  }
}

data "template_file" "ping_path_separator" {
  template = "${lookup(var.ping_path_separator, "HTTP")}"
}
```

This should pass absolutely fine.

It's still a bug but hopefully, that helps you to understand why it's behaving the way it is.

**Comment by martin-flaregames** [comment]
Yeah. Actually I suspected something like that, but then to reproduce the error by using something like this

```hcl
data "template_file" "broken" { template = "/test/" }
```
or
```hcl
data "template_file" "broken" { template = "/test" }
```
or
```hcl
data "template_file" "broken" { template = "test/" }
```
or this
```hcl
data "template_file" "broken" { template = "/test/file.txt" }
```
but none of those failed, only this one
```hcl
data "template_file" "broken" { template = "/" }
```
that got me wondering and opened the ticket.

Feel free to close the ticket if this behavior is expected. And thanks again for saving the day :)
