### ISSUE TITLE
CloudFront expects different S3 website endpoint

### ISSUE THREAD

**Issue by llarsson** [hashicorp/terraform#8668]
I am creating an S3 bucket to host a static web page, and want to put CloudFront in front of it. Standard stuff.

To make the `origin` block in my `aws_cloudfront_distribution` resource work, I have to put the following hackish code into it for `domain_name`:

`domain_name = "${replace(aws_s3_bucket.origin.website_endpoint, aws_s3_bucket.origin.website_domain, "s3.amazonaws.com")}"`

The problem is that my `website_endpoint` includes a region-specific (`eu-west-1`) domain name, but CloudFront does not accept those.

How do people generally do this very standard thing (static web page on S3, distribute it via CloudFront)?

**Comment by mikereinhold** [comment]
According to http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html, CloudFront supports both formats depending on your bucket configuration. That said, my experience has been similar to yours - the _{bucket-name}.s3.amazonaws.com_ format has been most reliable for me.

I've approached it in Terraform using the following:

````hcl
domain_name = "${aws_s3_bucket.origin.bucket}.s3.amazonaws.com"
````

It's a little less verbose than your example, but it works.

It would be nice if Terraform exposed an S3 resource output that had this format natively as that would streamline configuration, but the above isn't too bad.

**Comment by llarsson** [comment]
Thank you, @mikereinhold. That is significantly easier to read. 

The point still remains, though -- it would be nice to just have Terraform wire the values together and never have to potentially worry about the format changing. :)
