### ISSUE TITLE
Support service modes on Cloudflare

### ISSUE THREAD

**Issue by ndarilek** [hashicorp/terraform#867]
The current Cloudflare DNS setup lets me assign names to IPs, but it doesn't seem to allow configuration of any features you'd actually want to use CF for.

For instance, while I can point a domain name to a Digital Ocean droplet or GCE compute unit, I can't mark the www subdomain as being proxied via CF.

In particular, I'm looking at section 5.2 of [this documentation](https://www.cloudflare.com/docs/client-api.html) which defines service modes and other parameters not yet supported by this provider. Without these, the CF provider seems to just be a simple DNS registry without any of CF's features.

Thanks.

**Comment by foxx** [comment]
Agreed, any idea when we can expect CloudFlare to be supported with Terraform? The tool is useless to us without this :/

**Comment by Phomias** [comment]
I want to make some A records which are proxied by CF (orange cloud as they call it).  I'm willing to work on a patch to add that functionality to terraform. I just need to find the terraform developers guide, learn go, etc.   Any pointers, encouragement, or warnings would be appreciated.

**Comment by devinrsmith** [comment]
+1

**Comment by abevoelker** [comment]
I can only concur that the CloudFlare module should at least support CloudFlare's acceleration/proxying, which is what a lot of people use it for (myself included).

I've never done Go before, but from poking around in the code, it seems that the CloudFlare provider uses this client for interacting with the CloudFlare API, which I think needs to be modified first to add this functionality (someone correct me if I'm wrong): https://github.com/pearkes/cloudflare

**Comment by pencoyd** [comment]
Please use the CURRENT CloudFlare APIs for any work done here:
https://api.cloudflare.com

Much more functionality. These are the same APIs we used in the rebuild of our customer-facing dashboard in spring 2015.

John
CloudFlare employee

**Comment by omarabid** [comment]
I concur. The current functionality is very limited (only records) while the cloudflare API allows much more than this :/

**Comment by maishsk** [comment]
Any news on this yet?

**Comment by ndarilek** [comment]
Would definitely like to see this land. Thanks to Terraform, setting a 
domain to be cloudflare-protected is just about the only thing I have to 
touch the CF web interface for.

**Comment by pencoyd** [comment]
Some of my colleagues are writing a Go library for the CloudFlare v4 API (current API) here https://github.com/jamesog/cloudflare-go in case it's useful.

**Comment by ziggythehamster** [comment]
A better Go library for CloudFlare would allow them to also fix this bug, FWIW: https://github.com/hashicorp/terraform/issues/2551

**Comment by pencoyd** [comment]
My colleagues are turning this into an official library for Go - https://github.com/cloudflare/cloudflare-go is new home.

**Comment by catsby** [comment]
Hello friends – I'm going to close this issue now:

- Terraform offers `proxied` support in the `cloudflare_record` resource: https://www.terraform.io/docs/providers/cloudflare/r/record.html
- We're using the official Cloudflare SDK

Thanks!
