### ISSUE TITLE
Terraform support to automate Azure App Gateway and auto scaling settings 

### ISSUE THREAD

**Issue by tgtshanika** [hashicorp/terraform#8670]
Hi there,

I have been trying to automate an Azure scale set deployment with App gateway. I could not find terraform configuration to automate App Gateway. IMO, it would be great if you can add App gateway automation support so that we can easity develop a solution to automate a complete deployment.

I referred [1] in automating scale sets, but I couldn't find any parameter to configure app gateway backend address pool ids for a given scale set. Further, there is no config to automate scale set settings (autoscaling rules etc) against a given scale set. 

Due to above limitations, we have to use template + terraform based automation, which is not clean.

[1] -https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_sets.html

**Comment by retheshnair** [comment]
Can we expect this support for application gateway soon

**Comment by bpoland** [comment]
Looks like @pmcatominey has worked on it: https://github.com/hashicorp/terraform/pull/10413
