### ISSUE TITLE
Not able to set caller reference in aws_route53_health_check

### ISSUE THREAD

**Issue by dlyub** [hashicorp/terraform#8679]
I have attempted to deploy a couple of Route 53 heath checks with terraform and got the following error:

`I, [2016-09-06T11:00:56.629375 #4836]  INFO -- : * aws_route53_health_check.healthstate.0: HealthCheckAlreadyExists: A different health check has already been created with the specified caller reference.
I, [2016-09-06T11:00:56.629375 #4836]  INFO -- : status code: 409`

I believe the issue it that aws_route53_health_check resource does not support 'reference_name' argument like 'aws_route53_delegation_set' does. Are there any plans to add support for that argument in the future?

Thank you!

**Comment by achalupa74** [comment]
+1

We are blocked by the same problem.

**Comment by zhefanlin** [comment]
+1
Same here

**Comment by stack72** [comment]
Hi @dlyub 

Please can you post a configuration that would allow us to try and re-create this error?

Thanks

Paul

**Comment by brendonmartino** [comment]
+1

**Comment by dlyub** [comment]
Hi Paul (@stack72)

Any time you'd use aws_route53_health_check with 'count' argument you'll probably see that. Here's the way I've tried to use it

`
resource "aws_route53_health_check" "healthstate" {

  depends_on = [ "aws_cloudwatch_metric_alarm.statuscheck" ]
  provider = "aws.instance_provider"
  count = "${var.instance_count}"

  type = "CLOUDWATCH_METRIC"
  cloudwatch_alarm_name = "${var.aws_instance_name}${count.index + var.index_offset + 1} status"
  cloudwatch_alarm_region = "${var.region}"
  insufficient_data_health_status = "Healthy"

  tags = {
    Name = "${var.aws_instance_name}${count.index + var.index_offset + 1}_health_check"
   }
}
`

I actually haven't tried passing 'reference_name' to this resource since it's not present in the documentation (https://www.terraform.io/docs/providers/aws/r/route53_health_check.html). Maybe it's just a documentation issue? I did see it listed for aws_route53_delegation_set resource (https://www.terraform.io/docs/providers/aws/r/route53_delegation_set.html).

**Comment by dlyub** [comment]
@stack72 - Paul, you have any updates on this? Thank you!

**Comment by stack72** [comment]
Hi @dlyub 
just submitted a PR that fixes this - apologies for the time taken here

Paul

**Comment by dlyub** [comment]
Thank you Paul! ( @stack72 )
