### ISSUE TITLE
vCD: Computer Name is not customised when deploying Windows VMs

### ISSUE THREAD

**Issue by poluvex** [hashicorp/terraform#8681]
Hi there,

We are having an issue where Computer Name property of a VM in vDC is not being customised by terraform on deployment of Windows VMs. This customisation does work correctly on CentOS/RH images.

We build all our images, both Linux and Windows using **_packer_**.

I was unable to identify any fundamental differences in templates meta-structure that could have caused that. Could still be vmware customisation/tools issue, perhaps it is expecting something different for Windows VMs.
### Terraform Version

Terraform v0.7.1
### Affected Resource(s)

Please list the resources as a list, for example:
- vdc_vapp
### Terraform Configuration Files

resource "vcd_vapp" "SOME_VM" {
  name                 = "SOME_VM"
  ip                       = "123.123.123.123"
  template_name  = "some_image"
  catalog_name    = "some_catalogue" 
  network_name   = "some_network"
  memory             = 4096
  cpus                  = 2
    metadata {
      role = "some_role"
  }
    power_on = true
}
### Debug Output

terraform completes with no errors
### Panic Output

N/A
### Expected Behavior

_**Computer Name**_ property of a VM instance in vCD should be changed to _**name**_ property during deployment
### Actual Behavior

Computer Name does not change from default placeholder name present in the template.
### Steps to Reproduce
1. `terraform apply`
### Important Factoids

OVF templated Windows 12 R2
### References

not aware

**Comment by emil0054** [comment]
I would like to +1 this but for the linux side. If it would set it the hostname field along the same as the name that would work great or a second variable I can set to apply the hostname. Then it is one step closer to being fully automateable.
