### ISSUE TITLE
Plan always includes change to aws_elasticsearch_domain after disabling dedicated master manually

### ISSUE THREAD

**Issue by looppair** [hashicorp/terraform#8682]
### Terraform Version

0.7.3
### Affected Resource
- aws_elasticsearch_domain
### Terraform Configuration Files

``` hcl
resource "aws_elasticsearch_domain" "foo" {
  […]
  cluster_config {
    instance_type = "r3.large.elasticsearch"
    instance_count = "3"
    zone_awareness_enabled = false
    dedicated_master_enabled = false
  }
  […]
}
```
### Steps to Reproduce
1. Set up ElasticSearch on AWS with three dedicated m3.medium.elasticsearch master hosts using Terraform
2. Manually disable dedicated master setting in the cluster node configuration
3. Modify the Terraform configuration to disable dedicated master
4. `terraform apply`
5. `terraform plan`
### Expected Behavior

`terraform plan` should report no changes planned after `terraform apply`.
### Actual Behavior

The plan output always includes the following:

```
~ aws_elasticsearch_domain.loop
    cluster_config.0.dedicated_master_count: "3" => "0"
    cluster_config.0.dedicated_master_type:  "m3.medium.elasticsearch" => ""
```

**Comment by nwalke** [comment]
Seeing the same thing only the opposite way.  I don't want dedicated masters in our staging environment, but do in production.  Setting `dedicated_master_enabled` to false, but leaving the instance type and count that I want for other environments results in the diff always noting that they're different.
