### ISSUE TITLE
Download page on the site still has the v0.7.0 links

### ISSUE THREAD

**Issue by levinse** [hashicorp/terraform#8683]
The download page is linking to v0.7.0 still, for all platforms.

**Comment by cblecker** [comment]
@levinse I'm not sure if this is a caching issue, but the website is showing the current version (v0.7.3) for me.

**Comment by levinse** [comment]
Hard refresh is showing 0.7.3 for me now too...likely false alarm (or they need to fix their caching!) :)

**Comment by mpas** [comment]
Local cache issue

**Comment by stack72** [comment]
Closing now this is ok :)
