### ISSUE TITLE
block storage in openstack error - attribute mismatch

### ISSUE THREAD

**Issue by sirajudheenam** [hashicorp/terraform#8686]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name   = "xxxxxx"
  tenant_name = "xxxxxx"
  password    = "xxxxxx"
  domain_name = "xxxxxx"
  auth_url    = "https://xxxxxxxx.eu-de-1.xxx.sap:xxx/v3"
}

resource "openstack_networking_floatingip_v2" "my_floatip_1" {
  pool = "CC External Zone2"
}

resource "openstack_blockstorage_volume_v1" "volume_1" {
  region = "eu-de-1"
  name = "terraform-volume-01"
  description = "terraform test volume 01"
  size = 3
}

resource "openstack_compute_instance_v2" "tf_instance_01" {
  name      = "tf_instance_01"
  region    = "eu-de-1"
  image_id  = "dd2d11ce-afc8-4e27-93f4-xxxxxxxxxxx"
  flavor_id = "2"
  key_pair  = "PERSONAL_I072278"

  network {
    uuid = "74109d28-130d-4500-b806-xxxxxxxxxxx"
    name = "CC Shared Internal"
  }

  network {
    name        = "my_second_network"
    floating_ip = "${openstack_networking_floatingip_v2.my_floatip_1.address}"
    # Terraform will use this network for provisioning
    access_network = true
  }
}
```

### Debug Output
https://gist.github.com/sirajudheenam/6a2cae7d51526ad6a89fcd4104e1e463

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should have provisioned block storage and compute instance with floating ip.

### Actual Behavior
Threw an error show in the gist.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Running at SAP Internal Cloud. OpenStack Mitaka.

**Comment by jtopjian** [comment]
Thank you for the report!

Can you try a quick test: either set the `OS_REGION_NAME` environment variable or fill in the `region` argument for all resources (notably, the `region` for the floating IP resource is missing).

**Comment by sirajudheenam** [comment]
Set region and removed tfstate files and executed plan and apply again. It worked. Please close this issue.
