### ISSUE TITLE
Documentation: Cloud-init config template example needed

### ISSUE THREAD

**Issue by bigmyx** [hashicorp/terraform#8694]
Hi,
In the following [page](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) there is a example of using a multipart data sources.
Also, there is a mention 

> The order of the parts is maintained in the configuration is maintained in the rendered template.

Can you please provide `init.tpl` file example?

In general, I would like to use one template file with the user data YAML and the user cloud-init Bash scripts.

Appreciate you help!

**Comment by mig5** [comment]
@bigmyx this super simple example might help you https://gist.github.com/mig5/b0e1b2192c9e3bae1a60191dd7eba132

Basically variable 'foo' set in the 'vars' of a template_file resource, is accessible in the tpl as ${foo}.
