### ISSUE TITLE
Indexing of computed lists does not work

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#8695]
### Terraform Version

`Terraform v0.7.3`
### Affected Resource(s)

`n/a` -- interpolation issue.
### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_network_interface" "foo" {
  count = "3"
  subnet_id = "SUBNET ID"
}

resource "aws_route53_record" "aws_dns" {
  name = "test.com"
  count = 3

  zone_id = "ZONE ID"
  type = "CNAME"
  ttl = 30
  records = ["${aws_network_interface.foo.*.private_ips[count.index]}"]
}
```
### Debug Output

https://gist.github.com/jszwedko/db8a5b43a61e7139fef6a195e1c588cb
### Expected Behavior

A route53 record is created using the private IPs from the created network interfaces.
### Actual Behavior

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


Error running plan: 3 error(s) occurred:

* At column 3, line 1: invalid index operation into non-indexable type: TypeString in:

${aws_network_interface.foo.*.private_ips[count.index]}
* At column 3, line 1: invalid index operation into non-indexable type: TypeString in:

${aws_network_interface.foo.*.private_ips[count.index]}
* At column 3, line 1: invalid index operation into non-indexable type: TypeString in:

${aws_network_interface.foo.*.private_ips[count.index]}
```
### Steps to Reproduce
1. `terraform plan`
### Important Factoids

If you comment out the `aws_route53_record`, `terraform plan` and `terraform apply` you can than uncomment it and it creates correctly (now that the value it is indexing is no longer computed).
### References
#7906 is a related issue

**Comment by mitchellh** [comment]
Have a fix queued in the referenced PR!

**Comment by jszwedko** [comment]
Awesome!
