### ISSUE TITLE
Using data template_file with count for repeating configuration elements

### ISSUE THREAD

**Issue by mikereinhold** [hashicorp/terraform#8698]
Some resources have optional, repeatable config elements, such as aws_cloudfront_distribution > custom_error_response config block. It is an optional configuration that can be specified 0 or more times. Alternatively, it can be assigned once using a list.

``` hcl
...
custom_error_response {
    error_caching_min_ttl = "300"
    error_code = "403"
    response_code = "404"
    response_page_path = "/index.html"
}
custom_error_response {
    error_caching_min_ttl = "300"
    error_code = "401"
    response_code = "404"
    response_page_path = "/index.html"
}
```

or

``` hcl
...
custom_error_response =[
{
    error_caching_min_ttl = "300",
    error_code = "403",
    response_code = "404",
    response_page_path = "/index.html"
},
{
    error_caching_min_ttl = "300",
    error_code = "401",
    response_code = "404",
    response_page_path = "/index.html"
}
]
```

From the documentation, it is not clear whether it should be possible to interpolate either syntax using template_file with count, however I think this would be an extremely useful scenario for this type of repeatable configuration block. 

Is either method described above expected to work? If not, is there an approach that would be reasonably easy to implement?
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)

General interpolation issue. Resources that benefit include any that have configs that can be repeated
- aws_cloudfront_distribution
  ..-custom_error_response
  ..-cache_behavior
  ..-origin (not optional, however multiple allowed)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
### Terraform Configuration Files

Scenario 1
Config block interpolation

``` hcl
data "template_file" "error-response" {
    template = "${file("${path.module}/cloudfront-error-response.tpl")}"
    vars {
        error_caching_min_ttl = "300"
        error_code = "403"
        response_code = "404"
        response_page_path = "/index.html"
    }
}
...
resource "aws_cloudfront_distribution" "s3_distribution" {
...
  "${data.template_file.error-response.rendered}"
...
}
```

Where cloudfront-error-response.tpl looks like:

``` hcl
custom_error_response {
    error_caching_min_ttl = "${error_caching_min_ttl}"
    error_code = "${error_code}"
    response_code = "${response_code}"
    response_page_path = "${response_page_path}"
}
```

Scenario 2
JSON array configuration
Config block interpolation

``` hcl
data "template_file" "error-response" {
    template = "${file("${path.module}/cloudfront-error-response.json")}"
    vars {
        error_caching_min_ttl = "300"
        error_code = "403"
        response_code = "404"
        response_page_path = "/index.html"
    }
}
...
resource "aws_cloudfront_distribution" "s3_distribution" {
...
  custom_error_response = "${data.template_file.error-response.rendered}"
...
}
```

Where cloudfront-error-response.json looks like:

``` hcl
{
    error_caching_min_ttl = "${error_caching_min_ttl}",
    error_code = "${error_code}",
    response_code = "${response_code}",
    response_page_path = "${response_page_path}"
}
```
### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
### Expected Behavior

Under both scenarios, expected change to the CloudFront distribution is:
    custom_error_response.#:                                 "0" => "1"
    custom_error_response.~3839147747.error_caching_min_ttl: "" => "300"
    custom_error_response.~3839147747.error_code:            "" => "403"
    custom_error_response.~3839147747.response_code:         "" => "404"
    custom_error_response.~3839147747.response_page_path:    "" => "/index.html"
### Actual Behavior

Scenario 1
Error downloading modules: module webhost: Error parsing .terraform/modules/eb7729f1664dbd08e1f769e19cbf77c1/main.tf: At 219:20: nested object expected: LBRACE got: ASSIGN

I assume this is because interpolations can only be on the right hand side of an assignment operation, not standalone like would be needed for direct templating of configuration blocks as tried for scenario 1.

Scenario 2
Errors:
- aws_cloudfront_distribution.distribution: custom_error_response: should be a list

If I try variations to interpolate the results of the render as a list, I get: 

Errors:
- aws_cloudfront_distribution.distribution: custom_error_response.0: expected object, got string
### Steps to Reproduce

Please list the steps required to reproduce the issue:
1. `terraform apply`
### Important Factoids

None
### References

Not exactly related, however GH-1336 would make passing complex structures like these custom_error_response objects into a module much easier.

**Comment by dcharbonnier** [comment]
this problem is not limited to aws but to all repeatable config elements of all providers, #9499 for scaleway and additional_volume suffer the same limitation

**Comment by supermethod** [comment]
Is there any workaround for this issue? I have a terraform configuration that creates multiple EC2 instances using variable interpolation and I need to create a separate CloudFront origin for each one inside a single distribution. Creating 1 distribution per instance does work but thats not ideal as we will potentially have 100+ instances in our setup.

I can reproduce the above on Terraform v0.8.0-rc3, even for a template without variables:

```hcl
data "template_file" "cloudfront-origin" {
  template = "${file("${path.module}/cloudfront-origin.tpl")}"
}
```

With:

```hcl
resource "aws_cloudfront_distribution" "origin_distribution" {
  origin = "${data.template_file.cloudfront-origin.rendered}"
  ...
```

I get:
```
Errors:
  * aws_cloudfront_distribution.origin_distribution: origin: should be a list 
```

and with:

```hcl
resource "aws_cloudfront_distribution" "origin_distribution" {
  origin = ["${data.template_file.cloudfront-origin.rendered}"]
  ...
```
I get: 
```
Errors:
  * aws_cloudfront_distribution.origin_distribution: origin.0: expected object, got string
```
