### ISSUE TITLE
Bad wording in website/source/docs/configuration/providers.html.md

### ISSUE THREAD

**Issue by willfaught** [hashicorp/terraform#8702]
>The primary use case for this for multiple cloud regions.

Should this be *The primary use case for this is multiple cloud regions* instead?

>Other use cases including targeting multiple Docker hosts, multiple Consul hosts, etc.

Should this be *Other use cases include targeting multiple Docker hosts, multiple Consul hosts, etc.* instead?

**Comment by cblecker** [comment]
Opened #8726 to reword this.
