### ISSUE TITLE
[Documentation] Security_groups parameter in aws_instance

### ISSUE THREAD

**Issue by fjromerom** [hashicorp/terraform#8714]
aws_instance from documentation:

> security_groups - (Optional) A list of security group names to associate with. If you are creating Instances in a VPC, use vpc_security_group_ids instead.

security_groups parameter does not work with names, It works with IDs.

If I set security groups names terraform prints:

`* aws_instance.bastion: Error launching source instance: InvalidParameterCombination: The parameter groupName cannot be used with the parameter subnet
    status code: 400, request id: XXXXXXXXXXXXXXXXXXX`

**Comment by stack72** [comment]
Reopening this as the original PR to fix it wasn't correct

**Comment by nwalke** [comment]
Is anything actually needed here?  The documentation now states that `security_groups` on the instance is for names which are EC2 classic and suggests using `vpc_security_group_ids` for VPC instances.
