### ISSUE TITLE
[aws_autoscaling_group] Attaching/Detaching a lot of loadbalancers fails

### ISSUE THREAD

**Issue by freeman** [hashicorp/terraform#8718]
Hello,

We heavily use modules in our terraform stacks.
When updating some core modules this resulted in massive updates to the load balancers attached to some of our autoscaling groups and we are getting this error:

```
* aws_autoscaling_group.web: [WARN] Error updating Load Balancers for AutoScaling Group (DEV-AS-XXX-WEB), error: ValidationError: Trying to update too many Load Balancers/Target Groups at once. The limit is 10
    status code: 400, request id: xxx3fc5c-751b-11e6-8d48-bf41d1251xxx
```
### Terraform Version

Using terraform v0.7.3
### Affected Resource(s)
- aws_autoscaling_group
### Expected Behavior

The update should have succeded
### Actual Behavior

We got the error mentionned earlier
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create an infrastructure with more than 10 load balancers attached to an autoscaling group
2. `terraform apply`
3. You will get the error mentionned

From looking at the source this happens [here](https://github.com/hashicorp/terraform/blob/v0.7.3/builtin/providers/aws/resource_aws_autoscaling_group.go#L539-L557)

According to [Auto Scaling Limits](https://docs.aws.amazon.com/autoscaling/latest/userguide/as-account-limits.html) this will also be an issue with target groups.

I guess the feature request is for terraform to proceed in batches of 10 modifications at a time.

**Comment by baskaran-md** [comment]
+1 for this issue. 

As this looks like the limitation on the AWS API side to associate only 10 ELBs at a time to the ASG, terraform can do batch processing if there are more than 10 ELBs to be associated.

**Comment by freeman** [comment]
#8755 would be another way of fixing the issue (but would need a refactor of your tf files)

**Comment by kwach** [comment]
+1
