### ISSUE TITLE
Stale modules persist in state

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#8723]
I've noticed that over time our `tfstate` files become very bloated with modules that are no longer in use. For example, I found the following in our state file:

```
    {
      "path": [
        "root",
        "REDACTED"
      ],
      "outputs": {},
      "resources": {},
      "depends_on": []
    },
```

Is this expected?

**Comment by mitchellh** [comment]
For now this happens and shouldn't negatively impact Terraform behavior. But I'll mark it as a bug as something we don't want long term.

**Comment by mitchellh** [comment]
This is now fixed
