### ISSUE TITLE
Creating aws_vpc_peering_connection with allow_remote_vpc_dns_resolution fails

### ISSUE THREAD

**Issue by WishCow** [hashicorp/terraform#8733]
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- aws_vpc
- aws_vpc_peering_connection
### Terraform Configuration Files

``` hcl
variable "kops_cidr_block" {}
variable "tf_cidr_block" {}
variable "peer_owner_id" {}

resource "aws_vpc" "kops" {
    cidr_block = "${var.kops_cidr_block}"
    enable_dns_hostnames = true
    tags {
        Name = "KOPS VPC"
        Managed = "Terraform"
    }
}

resource "aws_vpc" "tf" {
    cidr_block = "${var.tf_cidr_block}"
    enable_dns_hostnames = true
    tags {
        Name = "Terraform VPC"
        Managed = "Terraform"
    }
}

resource "aws_vpc_peering_connection" "kops-tf" {
    peer_owner_id = "${var.peer_owner_id}"
    peer_vpc_id = "${aws_vpc.tf.id}"
    vpc_id = "${aws_vpc.kops.id}"
    auto_accept = true

    accepter {
        allow_remote_vpc_dns_resolution = true
    }
    requester {
        allow_remote_vpc_dns_resolution = true
    }

    tags {
        Managed = "Terraform"
        Name = "kops-tf"
    }
}

```
### Debug Output

The debug output seems to contain some sensitive information, I'm not sure I'm allowed to share that (company policies).
### Panic Output

No panic output
### Expected Behavior

Expected the VPC peering connection to be made, with remote_vpc_dns_resolution enabled.
### Actual Behavior

The VPC peering connection is made, but the DNS resolution properties are disabled.
In addition, terraform outputs the following error:

Error applying plan:

1 error(s) occurred:
- aws_vpc_peering_connection.kops-tf: Error modifying VPC Peering Connection options: OperationNotPermitted: User 076506802325 is not permitted to perform this operation
  status code: 400, request id: 6e163e8d-d361-4e86-a629-9ea98685a59a

**If I leave out the accepter/requester blocks, everything is fine**
### Steps to Reproduce

`terraform apply`
### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
### References

No references.

**Comment by kwilczynski** [comment]
@WishCow hello there! Sorry for troubles!

At the first glance, based on the error message, it would seem that your user and/or IAM role does not have the permission to execute `ModifyVpcPeeringConnectionOptions` API call (on the IAM side it would be `ec2:ModifyVpcPeeringConnectionOptions`). Are you able to verify that you have necessary permissions, we can use this as a starting point.

**Comment by WishCow** [comment]
My account (the one I'm using TF with) has the "AdministratorAccess" managed policy attached to it, I believe that should cover `ec2:ModifyVpcPeeringConnectionOptions`?

**Comment by kwilczynski** [comment]
@WishCow thank you for getting back to me.

I cannot reproduce this manually (your example taken as-is and run within my account), plus the acceptance test we have to cover this is almost identical to your use-case, and it seem to complete this without any issues.

Would you be able to run Terraform again with the `TF_LOG=debug` added and only include the responses from the output? This is so I can see what the error message says in full, which would be very helpful.

**Comment by kwilczynski** [comment]
@WishCow hello there! Are you still having issues with this? Were you able to collect some of the debugging data I have asked?

**Comment by WishCow** [comment]
Sorry got a bit caught up, will try to reproduce again in the next few days.

**Comment by NandeeshHD** [comment]
I'm facing the same issue. It is still reproducible.
I have sufficient permission and I able to set this option manually on AWS Console.

**Comment by WishCow** [comment]
Sorry I don't have the configuration anymore (we ended up going a different way than linked vpcs) to try and confirm again :/

**Comment by kwilczynski** [comment]
@NandeeshHD hi there! I am sorry that you are having issues. Would you be able to provide a debug output for us?

**Comment by NandeeshHD** [comment]
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: -----------------------------------------------------
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/06 14:14:03 [DEBUG] VPC Peering Connection accept status: provisioning
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/06 14:14:03 [DEBUG] VPC Peering Connection modify options: {
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:   AccepterPeeringConnectionOptions: {
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowDnsResolutionFromRemoteVpc: true,
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowEgressFromLocalClassicLinkToRemoteVpc: false,
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowEgressFromLocalVpcToRemoteClassicLink: false
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:   },
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:   RequesterPeeringConnectionOptions: {
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowDnsResolutionFromRemoteVpc: true,
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowEgressFromLocalClassicLinkToRemoteVpc: false,
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:     AllowEgressFromLocalVpcToRemoteClassicLink: false
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:   },
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe:   VpcPeeringConnectionId: "pcx-6cec3105"
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: }
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/06 14:14:03 [DEBUG] [aws-sdk-go] DEBUG: Request ec2/ModifyVpcPeeringConnectionOptions Details:
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: ---[ REQUEST POST-SIGN ]-----------------------------
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: POST / HTTP/1.1
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Host: ec2.eu-central-1.amazonaws.com
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: User-Agent: terraform/0.7.4 aws-sdk-go/1.4.10 (go1.7; windows; amd64)
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Content-Length: 566
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXX/20161006/eu-central-1/ec2/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Content-Type: application/x-www-form-urlencoded; charset=utf-8
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: X-Amz-Date: 20161006T121403Z
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Accept-Encoding: gzip
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: AccepterPeeringConnectionOptions.AllowDnsResolutionFromRemoteVpc=true&AccepterPeeringConnectionOptions.AllowEgressFromLocalClassicLinkToRemoteVpc=false&AccepterPeeringConnectionOptions.AllowEgressFromLocalVpcToRemoteClassicLink=false&Action=ModifyVpcPeeringConnectionOptions&RequesterPeeringConnectionOptions.AllowDnsResolutionFromRemoteVpc=true&RequesterPeeringConnectionOptions.AllowEgressFromLocalClassicLinkToRemoteVpc=false&RequesterPeeringConnectionOptions.AllowEgressFromLocalVpcToRemoteClassicLink=false&Version=2016-04-01&VpcPeeringConnectionId=pcx-6cec3105


2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: -----------------------------------------------------
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: aws-provider (internal) 2016/10/06 14:14:03 [DEBUG] [aws-sdk-go] DEBUG: Response ec2/ModifyVpcPeeringConnectionOptions Details:
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: ---[ RESPONSE ]--------------------------------------
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: HTTP/1.1 400 Bad Request
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Connection: close
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Transfer-Encoding: chunked
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Date: Thu, 06 Oct 2016 12:14:03 GMT
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: Server: AmazonEC2
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 108
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: <?xml version="1.0" encoding="UTF-8"?>
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: <Response><Errors><Error><Code>OperationNotPermitted</Code><Message>User 123456789123 is not permitted to perform this operation</Message></Error></Errors><RequestID>f84ec4f9-f6bc-4c31-844d-85b277d615ab</RequestID></Response>
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 0
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: 
2016/10/06 14:14:03 [DEBUG] plugin: terraform.exe: -----------------------------------------------------
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalWriteState
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalIf
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalWriteState
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/10/06 14:14:03 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/10/06 14:14:03 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_vpc_peering_connection.dnt_peering_connection: Error modifying VPC Peering Connection options: OperationNotPermitted: User 123456789123 is not permitted to perform this operation
	status code: 400, request id: f84ec4f9-f6bc-4c31-844d-85b277d615ab
2016/10/06 14:14:03 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_vpc_peering_connection.dnt_peering_connection: Error modifying VPC Peering Connection options: OperationNotPermitted: User 123456789123 is not permitted to perform this operation
	status code: 400, request id: f84ec4f9-f6bc-4c31-844d-85b277d615ab
2016/10/06 14:14:03 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* aws_vpc_peering_connection.dnt_peering_connection: Error modifying VPC Peering Connection options: OperationNotPermitted: User 123456789123 is not permitted to perform this operation
	status code: 400, request id: f84ec4f9-f6bc-4c31-844d-85b277d615ab
2016/10/06 14:14:03 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_vpc_peering_connection.dnt_peering_connection: Error modifying VPC Peering Connection options: OperationNotPermitted: User 123456789123 is not permitted to perform this operation
	status code: 400, request id: f84ec4f9-f6bc-4c31-844d-85b277d615ab
2016/10/06 14:14:03 [TRACE] [walkApply] Exiting eval tree: aws_vpc_peering_connection.dnt_peering_connection
2016/10/06 14:14:03 [DEBUG] vertex output.peering_connection_id, got dep: aws_vpc_peering_connection.dnt_peering_connection
2016/10/06 14:14:03 [DEBUG] vertex aws_route_table.public_rt, got dep: aws_vpc_peering_connection.dnt_peering_connection
2016/10/06 14:14:03 [DEBUG] vertex aws_route_table.public_rt, got dep: provider.aws
2016/10/06 14:14:03 [DEBUG] vertex aws_route_table.public_rt, got dep: aws_vpc.dnt_vpc

**Comment by kwilczynski** [comment]
@NandeeshHD hi there! Thank you for the details!

This appears to be a genuine problem with permissions - the IAM user which you are using to manage the VPC peering using AWS Management Console might have elevated privileges, which is why it works, but the user that is being used to run Terraform might not have enough permission.

Can you verify that:

- the IAM user used to run Terraform has the right permissions add; and
- the IAM user used to run Terraform has permission to establish and/or modify the VPC peering in case it spans across different accounts.

You can also enable _CloudTrail_ to search for relevant events which could possibly be correlated to the time when the Terraform run has failed, so that you could verify what the problem is against details coming from the AWS back-ends.

An alternative troubleshooting step would be to use AWSCLI to try to reproduce this issue using the same credentials (same IAM user) as these used to run Terraform.

Hope this helps.

**Comment by NandeeshHD** [comment]
The issue is not produced on AWSCLI.

```
C:\Users\nandeesh.danehallera>aws ec2 modify-vpc-peering-connection-options --vpc-peering-connection-id pcx-d8e73ab1 --requester-peering-connection-options AllowDnsResolutionFromRemoteVpc=true --accepter-peering-connection-options AllowDnsResolutionFromRemoteVpc=true
-----------------------------------------------
|      ModifyVpcPeeringConnectionOptions      |
+---------------------------------------------+
||     AccepterPeeringConnectionOptions      ||
|+-----------------------------------+-------+|
||  AllowDnsResolutionFromRemoteVpc  |  True ||
|+-----------------------------------+-------+|
||     RequesterPeeringConnectionOptions     ||
|+-----------------------------------+-------+|
||  AllowDnsResolutionFromRemoteVpc  |  True ||
|+-----------------------------------+-------+|
```

**Comment by NandeeshHD** [comment]
Same IAM user is used in AWS Management Console, Terraform and also in AWSCLI.

**Comment by kwilczynski** [comment]
@NandeeshHD hi there! Thank you for this! I will have a look.

**Comment by sl1pm4t** [comment]
FWIW - I am also hitting this same issue. Even using my AWS root account I hit this error - but am able to make the change via the console.

**Comment by sl1pm4t** [comment]
This issue seems to depend on the AWS region. 
For example, I can successfully create a peering connection with DNS resolution enabled in us-east-1, but not us-east-2, using the same AWS access keys etc.
