### ISSUE TITLE
Private Custom Image with SoftLayer not working

### ISSUE THREAD

**Issue by pat610** [hashicorp/terraform#8734]
I've used the SoftLayer API to get the globalIdentifier of one of my private custom images. However, when I specify that image and run terraform apply I get an error:

softlayer_virtual_guest.terraform-sample-BDTGroup: Creating...
  backend_vlan_id:          "" => "559104"
  cpu:                      "" => "8"
  dedicated_acct_host_only: "" => "false"
  disks.#:                  "" => "1"
  disks.0:                  "" => "100"
  domain:                   "" => "somedomain.com"
  frontend_vlan_id:         "" => "559102"
  hourly_billing:           "" => "true"
  image:                    "" => "4b36e2f4-02f7-4830-8dd2-c37988c76783"
  ipv4_address:             "" => "<computed>"
  ipv4_address_private:     "" => "<computed>"
  local_disk:               "" => "false"
  name:                     "" => "terraform-vm"
  private_network_only:     "" => "false"
  public_network_speed:     "" => "1000"
  ram:                      "" => "32768"
  region:                   "" => "tor01"
Error applying plan:

1 error(s) occurred:
- softlayer_virtual_guest.terraform-sample-BDTGroup: Error creating virtual guest: softlayer-go: could not SoftLayer_Virtual_Guest#createObject, HTTP error code: '500'
### Terraform Version

Terraform v0.7.3
### Terraform Configuration Files

``` hcl
resource "softlayer_virtual_guest" "terraform-sample-BDTGroup" {
    name = "terraform-vm"
    domain = "somedomain.com"
    image = "4b36e2f4-02f7-4830-8dd2-c37988c76783"
    region = "tor01"
    public_network_speed = 1000
    hourly_billing = true
    private_network_only = false
    cpu = 8
    ram = 32768
    disks = [100]
    dedicated_acct_host_only = false
    local_disk = false
    frontend_vlan_id = 559102
    backend_vlan_id = 559104    
}
```
### Expected Behavior

Get a VM with my custom image
### Actual Behavior

Error applying plan:

1 error(s) occurred:
- softlayer_virtual_guest.terraform-sample-BDTGroup: Error creating virtual guest: softlayer-go: could not SoftLayer_Virtual_Guest#createObject, HTTP error code: '500'
### Steps to Reproduce
1. `terraform apply`

**Comment by pat610** [comment]
I've discovered a partially working workaround.  If I don't specify any disks terraform will begin creating the vm.  After 10 minutes I receive a timeout error however.  If I check in 30 minutes though my vm is up and available.

When I specify a disk I still receive a 500 error however.

**Comment by renier** [comment]
@pat610 The in-tree softlayer provider is way behind the times. Have you tried https://github.com/softlayer/terraform-provider-softlayer/ ?
