### ISSUE TITLE
Lack of variable type validation causes crash

### ISSUE THREAD

**Issue by ljankowski** [hashicorp/terraform#8736]
Hi there,

Just noticed that Terraform lacks type validation on (map) variables. Instead of printing error message about wrong variable type passed to module, it just crashed.
### Terraform Version

`Terraform v0.7.3`
### Affected Resource(s)

Doesn't matter which resource
### Terraform Configuration Files

Simplest config I could recreate it on:

``` hcl
variable amis {
  type = "map"
  default = {
    eu-west-1 = "ami-5968ec2a"
  }
}
```
### Debug Output

https://gist.github.com/ljankowski/3cd6e59694739716110b22ffbd7b403a
### Panic Output

https://gist.github.com/ljankowski/3cd6e59694739716110b22ffbd7b403a
### Expected Behavior

Throw an error
### Actual Behavior

Crashed
### Steps to Reproduce

`terraform plan -var "amis=ami-123456"`
### Important Factoids

none
### References

Probably: GH-8614

**Comment by mitchellh** [comment]
This is fixed in the latest version.
