### ISSUE TITLE
Support for AWS assume roles when configuring S3 remote state storage

### ISSUE THREAD

**Issue by adhodgson1** [hashicorp/terraform#8739]
Hi,

Since Terraform 0.7.3 we have been able to successfully use assume roles when dealing with the AWS provider.

It would be good if this functionality was also added to the Terraform state storage in S3, so we can use a combination of AWS credentials and assume role to access the S3 bucket.

**Comment by adhodgson1** [comment]
This also needs to apply to the remote state resources that use S3, as it is not possible to assume roles there either.

**Comment by jpluscplusm** [comment]
It was a surprise to me to discover that S3 remote state was pulled down using local AWS creds, even if a an `assume_role` was configured. I suggest that the necessary IAM roles/rules/etc could be somewhat cleaner if an `assume_role` was enacted *before* remote state was fetched.

**Comment by damacus** [comment]
Looks like the same is true for the `terraform import`command.

**Comment by daveadams** [comment]
Yeah this is going to bite us, too, as we are starting to roll out more cross-account stuff and eventually we hope to move our IAM creds out of the account where our resources are.

**Comment by mikereinhold** [comment]
I see the same things as @adhodgson1 and @damacus - both the state provider and the import command have the same problem

**Comment by dtserekhman** [comment]
Yes, please consider this enhancement/fix. Running into the same problem. In the "provider" section I use "assume_role" but this "assume_role" specification does not seem to apply to the "terraform_remote_state" where backend="s3".

**Comment by andrewerickson** [comment]
Just ran into this as well.

**Comment by LeSingeFou** [comment]
need assume role with import command. Possible ?

**Comment by darend** [comment]
Also ran into this when following [AWS Identity Account Structure](https://aws.amazon.com/answers/account-management/aws-multi-account-security-strategy/). We have multiple AWS accounts and the one that users login to just provides a means of assuming a role within the various sub-accounts. With local state the TF commands used the assumed role, ie targeted the sub account. However when we switch to s3 for state, it would always try to store it in a bucket under identity account, ignoring the assumed role.
