### ISSUE TITLE
aws_alb_target_group name/protocol change should force new resource

### ISSUE THREAD

**Issue by chrisminton** [hashicorp/terraform#8741]
Terraform version 0.7.3
### Affected Resource(s)
* aws_alb_target_group

### Expected Behaviour
After modifying an ALB target group name or protocol, I would expect Terraform to perform a _delete/recreate_ operation.

### Actual Behaviour
Terraform translates this change into an _update_ operation on the `aws_alb_target_group` resource. However, the update is not actually performed. terraform plan says it wants to update the existing resource:
```
~ module.web.aws_alb_target_group.instance
    name: "env-alb-tg" => "env-alb"
```

`terraform apply` claims to have successfully modified the target group: 
```
module.web.aws_alb_target_group.instance: Refreshing state... (ID: arn:aws:elasticloadbalancing:us-east-1:123412341234:targetgroup/env-alb-tg/fcf2ed95b9c0dc87)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
but no actual changes take place. This is true for modifications to the protocol option in aws_alb_target_group also. 
e.g. change protocol from HTTP to HTTPS

```hcl
resource "aws_alb_target_group" "instance" {
  name     = "env-alb-tg"
  port     = 443
  protocol = "HTTP"
  vpc_id   = "${var.vpc_id}"
}
```

to
```hcl
resource "aws_alb_target_group" "instance" {
  name     = "env-alb-tg"
  port     = 443
  protocol = "HTTPS"
  vpc_id   = "${var.vpc_id}"
}
```

Doing a destroy/create on the resource successfully makes the desired change.

**Comment by llarsson** [comment]
This interests me as well.

I would like to add, however, that the output from Terraform says that it just refreshed its state, not that it aimed to actually modify anything. See how the `Resources: 0 added, 0 changed, 0 destroyed.` says nothing about changes. So basically, Terraform thinks nothing needs to be done, and hence, does nothing.
