### ISSUE TITLE
bug report: plan not detecting all changes that will happen - "diffs didn't match during apply"

### ISSUE THREAD

**Issue by aerickson** [hashicorp/terraform#8743]
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- aws_instance
### Terraform Configuration Files

Please let me know if needed.
### Debug Output

https://gist.github.com/aerickson/b6f2e2a5fbeaf7178e51260266793f90
### Expected Behavior

Earlier TF's would detect all the changes and the apply would work.
### Actual Behavior

TF fails to detect all of the things that happen in the plan phase, and apply fails when run with the plan file.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan` - shows no changes
1. `terraform taint <instance`
1. `terraform plan -out=apply_file`
1. `terraform apply ./apply_file`
### Important Factoids

AWS EC2 with VPC. Nothing fancy.
### References

Seems similar to https://github.com/hashicorp/terraform/issues/8366.

**Comment by mitchellh** [comment]
Thanks! I still haven't been able to reproduce this so I'm going to consider it fixed. The core around tainted resource handling has changed quite a bit in the last few months so I think this needs to be completely revisited. Can you give 0.7.11 a shot and report if that didn't work? Thanks!
