### ISSUE TITLE
Amazon Application Load Balancer support

### ISSUE THREAD

**Issue by opokhvalit** [hashicorp/terraform#8752]
Hi!

Amazon has released new type of ELB : Application Load balancer https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/

Will terraform support this feature?

**Comment by stack72** [comment]
Hi @opokhvalit 

Thanks for opening the question here :) Luckily this was started to be supported as of Terraform 0.7.2 

https://www.terraform.io/docs/providers/aws/r/alb.html

Hope it works well for you - please do let us know any issues with it

Paul
