### ISSUE TITLE
Enhance ELB Attachment statement with autoscaling groups

### ISSUE THREAD

**Issue by DrSmirnov** [hashicorp/terraform#8755]
It's not possible to attach/detach an ELB to/from an existing Autoscaling Group without modifying the ASG. At the moment Terraform only provides an attachment statement for specific instances:

https://www.terraform.io/docs/providers/aws/r/elb_attachment.html

As it is possible to attach a loadbalancer to an existing Autoscaling Group (https://aws.amazon.com/es/blogs/aws/attach-and-detach-elastic-load-balancers-from-auto-scaling-groups/) Terraform should provide this option, too.

Don't know if it makes probably more sense to introduce a new command as the attachment is more a parameter in the autoscaling group data.

Btw. Here is my use case: I defined an autoscaling group with a few nodes in a core module and as the system evolves I deploy services on those instances. For each service I have a loadbalancer that should be attached to this running autoscaling group without having to modify the core module. Therefore it would be great to have something like:

```
# Create a new load balancer attachment
resource "aws_elb_attachment" "baz" {
  elb      = "${aws_elb.bar.id}"
  autoscaling_group = "${aws_autoscaling_group.server_group.id}"
}
```

**Comment by kwilczynski** [comment]
@DrSmirnov hi there! This is indeed a nice feature to have.

Consider it done.

I believe we would need to add an ability to `aws_alb_target_group_attachment` so that we can attach a target group to the load-balancer (ALB) in the same manner.

**Comment by DrSmirnov** [comment]
@kwilczynski Are there any news on this issue? Can we expect this in one of the next releases?

**Comment by kwilczynski** [comment]
@DrSmirnov hi there!

I believe the work has been completed by @jrnt30, who contributed a whole new resource. And, should there be no issues, it might be accepted by @stack72 to go into the next release.

Please stay put.

**Comment by DrSmirnov** [comment]
Great news. Thx.

**Comment by owenmorgan** [comment]
hello. are we now able to add an ASG to an aws_alb_target_group_attachment ? 

i get the below error when attempting to use the ASG id as the target_id property

Error registering targets with target group: ValidationError: Instance ID 'worker-hello-world-79dbe0c588aa58b3d5286f45b2d783a4' is not valid

**Comment by DrSmirnov** [comment]
It is possible. But only for ELB I think. From your question I get that you want to attach an ALB.

**Comment by owenmorgan** [comment]
From @kwilczynski comment he mentions an aws_alb_target_group_attachment

**Comment by owenmorgan** [comment]
can we re-open this please @kwilczynski  ?

**Comment by kwilczynski** [comment]
@owenmorgan hi there!

I cannot re-open this ticket, sadly. I am not HashiCorp employee. Please, feel free to open a new issue and mention this one in the new one.

**Comment by stack72** [comment]
Hi Folks

I just opened a PR that allows an ASG to be attached to an ALB Target Group - it will be part of Terraform 0.9.2

Paul

**Comment by owenmorgan** [comment]
Great!

**Comment by oskarpearson** [comment]
Just for clarity, in case someone else finds this ticket when figuring out now to associate ALBs with ASGs:

It *is* possible to attach an autoscaling group to an ALB with Terraform - it's just that this will perform an update of the autoscaling group, rather than being a standalone operation

(Yes, I know that this isn't what the original issue raiser wanted... it's just that the current wording seems to indicate that it's not possible to use ALBs and ASGs together with terraform... and you definitely can. The structure is just easy to miss since there's no clear example in the docs.)

You can do this using the 'target_group_arns' autoscaling group parameter https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#target_group_arns

You'll use this with something like this:

```
resource "aws_autoscaling_group" "asg" {
    target_group_arns    = ["${aws_alb_target_group.your_object_name_here.arn}"]
...
}
```

**Comment by prachikhadke** [comment]
@oskarpearson Your solution sounds like something I would do if I wanted to create an autoscaled group of ALBs. But right now I want to set the target of my ALB to an autoscaled group of t2.micro ec2 instances. How can I do that?

**Comment by stack72** [comment]
:) thanks for letting us know @ramkama

**Comment by jtopper** [comment]
Adding to @oskarpearson's comment above, it also looks possible to use `aws_alb_target_group_attachment` resources to link `aws_autoscaling_group`s to `aws_alb_target_group`s.  This is necessary if your target groups are created with count conditionals.
