### ISSUE TITLE
OpenStack provider does not use OS_USER_DOMAIN_NAME environment variable.

### ISSUE THREAD

**Issue by as0bu** [hashicorp/terraform#8757]
### Terraform Version

`Terraform v0.7.3`
### Affected Resource(s)

OpenStack Provider
### Expected Behavior

When setting the OS_USER_DOMAIN_NAME environment variable in lieu of OS_DOMAIN_NAME, terraform should not error out, but use the OS_USER_DOMAIN_NAME value.
### Actual Behavior

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* You must provide exactly one of DomainID or DomainName to authenticate by Username
```
### Steps to Reproduce

```
$ export OS_DOMAIN_NAME=
$ export OS_USER_DOMAIN_NAME="domainname"
$ terraform plan
```

**Comment by jtopjian** [comment]
Just a note: this isn't specific with Terraform, but the underlying Gophercloud library. This issue can stay open as a placeholder, but the ultimate fix will be in Gophercloud.

**Comment by jtopjian** [comment]
Quick update on this: It looks like Gophercloud has everything required for correct v3 authentication and scoping. An upcoming patch will set `DomainID` and `DomainName` by checking the following environment variables (in this order):

* `OS_USER_DOMAIN_*`
* `OS_PROJECT_DOMAIN_*`
* `OS_DOMAIN_*`
* `OS_DEFAULT_DOMAIN`
