### ISSUE TITLE
Feature request: AWS Application Load Balancer (ELB v2 API)

### ISSUE THREAD

**Issue by cgmartin** [hashicorp/terraform#8759]
Hello,
It would be wonderful to see support in Terraform for the new "Application Load Balancer" type with the ELB v2 API.

A link to the high-level info on the differences between the new Application Load Balancer (HTTP only) and the Classic Load Balancer (TCP):
<http://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html>

> This reference covers the 2015-12-01 API, which supports Application Load Balancers.
<http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/Welcome.html>

**Comment by kwilczynski** [comment]
@cgmartin hi there! I believe that support for ALB was added recently.

You can see documentation at https://www.terraform.io/docs/providers/aws/r/alb.html.

**Comment by mitchellh** [comment]
Yep, this is done!

**Comment by cgmartin** [comment]
This is great, thank you! Totally missed it, was looking for something related to`ELB`. Sorry to bother!
