### ISSUE TITLE
tls_cert_request forces recreating resources when count changes

### ISSUE THREAD

**Issue by RichardKnop** [hashicorp/terraform#8781]
This is related to https://github.com/hashicorp/terraform/issues/8764

However, a new issue for it might be created as it affects both `data` and `resource` usages. So just reverting from data source back to resource doesn't solve the actual problem.

So, let's say I use count meta-param to create several locally signed certificates:

```
resource "tls_cert_request" "server" {
  count = "2"
  key_algorithm = "${element(tls_private_key.server.*.algorithm, count.index)}"
  private_key_pem = "${element(tls_private_key.server.*.private_key_pem, count.index)}"

  subject {
    common_name = "coreos${count.index}"
    organization = "My company"
    country = "UK"
  }

  dns_names = [
    # hostname
    "coreos${count.index}",
  ]
}
```

When running `plan` command after increasing the count (from `2` to let's say `3`), all `tls_locally_signed_cert` resources are considered to be changed.

### Terraform Version

```
Terraform v0.7.4-dev (291f2985354454749e3e6da586c1ecd5d245c181)
```

### Affected Resource(s)

- `tls_cert_request `

### Debug Output

```
-/+ module.cluster.tls_cert_request.client_server.0
    cert_request_pem:       "-----BEGIN CERTIFICATE REQUEST-----\n ... \n-----END CERTIFICATE REQUEST-----\n" => "<computed>"
    dns_names.#:            "2" => "2"
    dns_names.0:            "10.0.1.10" => "10.0.1.10"
    dns_names.1:            "coreos0" => "coreos0"
    key_algorithm:          "ECDSA" => "ECDSA"
    private_key_pem:        "e6983a65e7c549f06a100867e11d36f25f673dc2" => "9ad8b3163b59f6437f32ee6202b76c66a8887ef0" (forces new resource)
    subject.#:              "1" => "1"
    subject.0.common_name:  "coreos0" => "coreos0"
    subject.0.country:      "UK" => "UK"
    subject.0.organization: "My company" => "My company"

-/+ module.cluster.tls_cert_request.client_server.1
    cert_request_pem:       "-----BEGIN CERTIFICATE REQUEST-----\n ... \n-----END CERTIFICATE REQUEST-----\n" => "<computed>"
    dns_names.#:            "2" => "2"
    dns_names.0:            "10.0.11.10" => "10.0.11.10"
    dns_names.1:            "coreos1" => "coreos1"
    key_algorithm:          "ECDSA" => "ECDSA"
    private_key_pem:        "f58442eea345848a8e1786959781b0ab1da89685" => "9ad8b3163b59f6437f32ee6202b76c66a8887ef0" (forces new resource)
    subject.#:              "1" => "1"
    subject.0.common_name:  "coreos1" => "coreos1"
    subject.0.country:      "UK" => "UK"
    subject.0.organization: "My company" => "My company"
```

### Expected Behavior

When I increase the count of `tls_locally_signed_cert` from `2` to `3`, the existing two certificate requests should be considered unchanged and only one new created.

### Actual Behavior

When I increase the count of `tls_locally_signed_cert` from `2` to `3`, the two certificate requests are considered changed and force recreation of resources.

### Steps to Reproduce

1. `terraform apply` with `tls_locally_signed_cert` with count set to `2`
2. Increase count to `3`
2. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @RichardKnop. Thanks for opening this issue, and sorry for the problems this caused.

I believe this is another example of the core issue being discussed in #3449, so I'm going to close this to consolidate the discussion over there.

According to that other issue this won't actually address the problem right now, but any fix to #3449 will depend on you using the new explicit indexing syntax that was introduced in 0.7:

```
  key_algorithm = "${tls_private_key.server.*.algorithm[count.index]}"
  private_key_pem = "${tls_private_key.server.*.private_key_pem[count.index]}"
```

Again, right now this will probably make no difference at all, but once this bug is fixed Terraform should be able to handle this situation correctly by knowing the semantics of indexing and knowing the value of `count.index`, whereas with `element` Terraform's core just sees a function call that takes the whole list and can't predict what that function is going to do with it.
