### ISSUE TITLE
aws_elasticache_replication_group does not provide cache_nodes output

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#8788]
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- aws_elasticache_replication_group

The `aws_elasticache_replication_group` resource only provides two outputs: `id` and `primary_endpoint_address`. But what about the IDs and addresses of each node in the cluster?

The `elasticache_cluster` resource provides a `cache_nodes` output, which provides the `id`, `address`, `port` and `availability_zone` of every node in the cluster. Is there a reason `aws_elasticache_replication_group` does not do the same? We need this data to use replication groups with Redis and we cannot get them from the `elasticache_cluster` resource, as that only creates single-node redis clusters.

Also, the ID of the underlying cluster is not available as an output either. The `id` output is the ID of the replication group (e.g. `foo`), but the underlying cluster will have a different id (e.g. `foo-001`).

**Comment by kwilczynski** [comment]
@brikis98 hi there! Sorry for all the troubles!

I am going to add these missing details. I am look at adding the following:

- `node_group_id` (string)
- `snapshotting_cluster_id` (string)
- `member_clusters` (list of strings)
- `node_group_members` (list of schema objects)
    - `current_role` (string)
    - `availability_zone` (string)
    - `cache_node_id` (string)
    - `read_endpoint` (string; port + address)
    - `port` (integer)
    - `address` (string)
    - `cache_cluster_id` (string)

Which is somewhat true to what the API returns. I think that's it? Unless you need something else?

**Comment by brikis98** [comment]
@kwilczynski I think those are exactly what we need. Thanks!

**Comment by zmw85** [comment]
has these been merged yet, these are not in the documentation.
