### ISSUE TITLE
"Edit this page" link on docs sometimes lands out of white background

### ISSUE THREAD

**Issue by paddyforan** [hashicorp/terraform#8798]
### Terraform Version

This is still an issue as of 454b12eeefe4733b5b0e93a626cb4f763e680595.
### Affected Resource(s)
- website
  - https://www.terraform.io/docs/providers/aws/d/ami.html
### Terraform Configuration Files

N/A
### Debug Output

N/A
### Panic Output

N/A
### Expected Behavior

The "Edit this page" link is supposed to be in the white background area.
### Actual Behavior

The "Edit this page" link instead appears in the dark background area, rendering it almost invisible.
### Steps to Reproduce
1. Visit https://www.terraform.io/docs/providers/aws/d/ami.html and search for "Edit this page".
### Important Factoids

This appears to be a problem on the pages that have a longer sidebar than the content on the pages. I'm investigating a root cause and possible fixes, but because they may be invasive, I wanted to open this issue to track discussion of it and possible avenues for remediation.

**Comment by stack72** [comment]
Closing  this for now as @paddyforan is joining the TF team and will discuss this internally :)
