### ISSUE TITLE
Consul service resources need ID attribute

### ISSUE THREAD

**Issue by cbarbour** [hashicorp/terraform#8799]
### Terraform Version

0.7.3
### Affected Resource(s)
- consul_service
- consul_agent_service
### Terraform Configuration Files

``` hcl
provider "consul" {
    address = "127.0.0.1:6500"
    datacenter = "local"
}

variable "web_ports" {
  address = "127.0.0.1"
  default = [ 80, 8080 ]
  type = "list"
}

resource "consul_service" "web" {
    name = "web"
    port = ${var.web_ports[count.index]}
}
```
### Expected Behavior

Two services named web should have been registered with Consul.
### Actual Behavior

ID collision prevents a single node from registering more than one service with a given name.
### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by cbarbour** [comment]
I was able to work around the issue completely by using a `consul_catalog_entry` resource instead of a `consul_service` resource.

This would be the resulting code:

```
provider "consul" {
    address = "127.0.0.1:6500"
    datacenter = "local"
}

variable "web_ports" {
  address = "127.0.0.1"
  default = [ 80, 8080 ]
  type = "list"
}

resource "consul_catalog_entry" "web" {
  count = "${length(web_ports)}"
  address = "${aws_instance.web.private_ip}"
  name = "${element(split(".", aws_instance.web.private_dns"), 0)}"
  service = {
    id = "web${count.index}"
    name = "web"
    port = "${web_ports[count.index]}"
}
```

**Comment by cbarbour** [comment]
I also looked into submitting a PR for the original request, but it seems like it was beyond my level of go knowledge (practically nothing past go template.)

From what I could gather, we would need to add logic to query all services with the appropriate node, name, etc. criteria, and parse through them to find the instance of the service matching the resource in our catalog.

Actually inserting an ID is easy enough, but simply throwing the ID at consul caused terraform plan/execution diff errors when I tried it.

**Comment by stack72** [comment]
Hi @cbarbour 

I believe this was fixed via #9366

Thoughts?

Paul

**Comment by cbarbour** [comment]
@stack72 

Hi Paul,

From a quick review, it looks like it would completely solve my issue. Unfortunately, I am not able to test; I ran into a lot of problems with the Consul provider and had to implement a solution using .json configured services and a Terraform file provisioner.

Regards,
Chris Barbour

**Comment by stack72** [comment]
No worries - I'll close this out and if you come back to it then we can reopen it if it doesn't 

Thanks for getting back in touch

Paul
