### ISSUE TITLE
s3 backend for remote state

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#880]
Talking about this in IRC. I feel like I heard somewhere that the HTTP backend is S3 compatible, but reading the [docs on auth via raw URL](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html) it seems like it would be nearly impossible without a first class backend.

We could do this as a specialization of the HTTP backend and interact with the S3 REST API or we could just use the S3 client itself.

@ryanuber you're remote state expert, ^^ does this sound right?

**Comment by armon** [comment]
@phinze I think we'd need a specific S3 backend, but that makes sense!

**Comment by kubek2k** [comment]
the only problem I see here is that s3 is eventually consistent, so either we would have to create some kind of separate mechanism of locking, or state it strongly in docs.

**Comment by CpuID** [comment]
@kubek2k only in us-east-1 (US Standard), other regions are read after write consistent...

**Comment by kubek2k** [comment]
@cpuid good to know :+1:. Btw after starting to implement this I realized that none of the backend cares to use conditional PUT, so it has to be addressed globally someday everywhere.

**Comment by CpuID** [comment]
might be worth restricting it to not use US Standard/us-east-1 to avoid the eventual consistency concerns? :)

**Comment by bitglue** [comment]
Is eventually consistent a problem? Arguably, even the local state isn't consistent already: https://github.com/hashicorp/terraform/issues/694

If I could be guaranteed that at least eventually zombie resources would be identified and rectified, that would be good enough for me, and an improvement over local state.

**Comment by apparentlymart** [comment]
New patch for this in MR #1723.

**Comment by mitchellh** [comment]
Fixed by #1723
