### ISSUE TITLE
Diff mismatch after moving iam configuration to module

### ISSUE THREAD

**Issue by sgraessle** [hashicorp/terraform#8801]
I moved my aws iam configuration into a module, then referenced the computed role arn. I think the apply succeeded (the actual arn hadn't changed), but the diff failed.
### Terraform Version

0.7.3
### Affected Resource(s)
- aws_lambda_function
### Terraform Configuration Files

module iam `outputs.tf`:

``` hcl
output "lambda_function_role_id" {
    value = "${aws_iam_role.role_lambda_dynamodb_datafull.arn}"
}
```

lambda config:

``` hcl
resource "aws_lambda_function" "heartbeat" {
    filename = "${path.module}/${var.jar_file}"
    function_name = "${var.env_prefix}${var.app_prefix}heartbeat"
    role = "${module.iam.lambda_function_role_id}"
    handler = "com.zynga.cuddlefish.roomservice.RoomController::heartbeat"
    source_code_hash = "${base64sha256(file("${path.module}/${var.jar_file}"))}"
    runtime = "java8"
}
```
### Debug Output

https://gist.github.com/sgraessle/8d7d1395ce171e74e8b35cd08c0a61f0
### Expected Behavior

The diff should have shown no changes.
### Actual Behavior

The diff was unable to dereference the module output?
### Steps to Reproduce
1. Write configuration without modules
2. `terraform apply`
3. Move iam configuration to module, reference computed role arn in lambda config
4. `terraform apply`

**Comment by mitchellh** [comment]
This is fixed in 0.8!
