### ISSUE TITLE
aws_iam_user with aws_iam_group_membership fails to add user

### ISSUE THREAD

**Issue by jsharp-drw** [hashicorp/terraform#8802]
When trying to add a new user at the same time as adding that user to a current group terraform fails

`terraform plan` showed the correct plan

### Terraform Version
Terraform v0.7.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_user
- aws_iam_group_membership

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "aws_iam_user" "some_user" {
  name = "some_user"
  path = "/"
}

resource "aws_iam_group_membership" "some_group" {
  name  = "some_group-group-membership"
  users = ["user1", "user1", "some_user"]
  group = "SomeGroup"
}
```

### Debug Output

aws_iam_user.some_user: Creation complete
Error applying plan:

1 error(s) occurred:

* aws_iam_group_membership.SomeGroup: NoSuchEntity: The user with name some_group cannot be found.
	status code: 404, request id: d9480c83-7924-11e6-9a3a-bf7b1425e59f

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output
 - None Produced

### Expected Behavior
Should have added the User: some_user to Group: SomeGroup

### Actual Behavior
It acted like the user was never created and failed to add them to the group

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
None that I know of

### References
Unable to find any other references to this

**Comment by stack72** [comment]
Hi @jsharp-drw 

Apologies this is causing you issues, strictly speaking, your terraform configuration is correct. But there are currently no relationships between your resources so Terraform doesn't understand the order in which to build them. By making the slightest changes (as below), I was able to get this to work as you would expect (create user, create group, then associate user to group)

```
resource "aws_iam_user" "some_user" {
  name = "some_user"
  path = "/"
}

resource "aws_iam_group" "group" {
    name = "SomeGroup"
    path = "/"
}

resource "aws_iam_group_membership" "some_group" {
  name  = "some_group-group-membership"
  users = ["${aws_iam_user.some_user.name}"]
  group = "${aws_iam_group.group.name}"
}
```

Notice the `aws_iam_group_membership` is what has changed. It uses the interpolation syntax to look up the users and the group resource names. This creates as graph as follows:

[graph.pdf](https://github.com/hashicorp/terraform/files/492905/graph.pdf)

This effectively means that IAM User and Groups need to be created before the group membership happens. Your old graph looked as follows:

[graph.pdf](https://github.com/hashicorp/terraform/files/492909/graph.pdf)

As you can see, there is no order and there is effectively a race to see what has to happen first

Hope this helps

Paul
