### ISSUE TITLE
feature request: mass instatiation of modules

### ISSUE THREAD

**Issue by vikstrous** [hashicorp/terraform#8804]
What I'm asking for might be a significant change in the way terraform works, but I don't know terraform well enough to be sure right now.

Based on what I read here https://www.terraform.io/docs/modules/usage.html you can instantiate a module once, or maybe a few times if you create a copy of the module definition and run `terraform get` again, but you can't instantiate it it `n` times with arbitrary configs. I have a module that defines a cluster of machines and I would like to be able to instantiate `n` of them easily.

Maybe this is not terraform's job? Maybe I should use a tool to output a terraform config as an intermediate state? What's the right way to deploy `n` clusters of an application with terraform?

### Terraform Version
Terraform v0.7.3

**Comment by cbarbour** [comment]
I believe there is an open feature request to support the count attribute for modules. That should allow you to get the module once, and invoke it multiple times with different parameters to build a massive number of clusters.

**Comment by apparentlymart** [comment]
There is indeed, @cbarbour! #953 is the issue you're thinking of.

In the mean time, having a separate program generate a Terraform config could be a reasonable workaround. I've never does this for `module` blocks, but I have several cases where I generate various `resource` blocks based on some higher-level data structure... it works okay as long as your deployment workflow can deal with having an extra pre-processing step.

**Comment by vikstrous** [comment]
Okay, sounds like a duplicate. Feel free to close.

**Comment by apparentlymart** [comment]
Thanks, @vikstrous!
