### ISSUE TITLE
Need "delete_on_termination" attribute on OpsWorks custom layer EBS volume resource

### ISSUE THREAD

**Issue by jrlonan** [hashicorp/terraform#8807]
### Terraform Version

0.7.3
### Affected Resource(s)
- aws_opsworks_custom_layer
- aws_opsworks_instance
### Terraform resource

```
resource "aws_opsworks_instance" "cluster01-1" {
    count = "${var.pico_instance_count}"
    stack_id = "${aws_opsworks_stack.pico-stack.id}"
    layer_ids = ["${aws_opsworks_custom_layer.pico-cluster01.id}"]
    root_device_type = "ebs"
    instance_type = "${lookup(var.pico_instance_type, var.env)}"
    hostname      = "mta-c01-10${count.index+1}"
    os            = "CentOS Linux 7"
    root_block_device {
        volume_type = "gp2"
        volume_size = "${lookup(var.pico_root_ebs_size,var.env)}"
        delete_on_termination = true
    }
    state         = "stopped"
    subnet_id     = "${aws_subnet.subnet01-1.id}"
}
```

```
resource "aws_opsworks_custom_layer" "pico-cluster01" {
    name = "pico-cluster01"
    short_name = "pico-cluster01"
    stack_id = "${aws_opsworks_stack.pico-stack.id}"
    elastic_load_balancer = "${aws_elb.pico-elb-cluster01.id}"
    drain_elb_on_shutdown = true
    auto_assign_elastic_ips = false
    custom_setup_recipes =["pico::env_config","pico::swap_config"]
    custom_configure_recipes = ["pico::hostsfile_config","pico::postfix_env_config","pico::postfix_config","pico::haproxy_config","pico::td-agent_config","pico::rsyslog_client_config","pico::mackerel_config","pico::awslogs_config"]
    custom_shutdown_recipes = ["pico::postfix_flush"]
    use_ebs_optimized_instances = true
    install_updates_on_boot  = true
    instance_shutdown_timeout = "360"
    auto_healing = false
    ebs_volume {
        mount_point = "/mnt"
        size = "${lookup(var.pico_ebs_size, var.env)}"
        number_of_disks = "1"
        raid_level = "None"
        type = "io1"
        iops = "${lookup(var.pico_ebs_iops, var.env)}"
    }
    custom_security_group_ids =["${aws_security_group.cluster.id}"]
    depends_on = ["aws_opsworks_stack.pico-stack"]
    custom_json = <<EOT
    {
    "aws": {
          "env" : "${lookup(var.pico_environment, var.env)}",
          "region" : "${var.region}"
         },
    "pico": {
        "role" : "mta",
        "domain" : "${lookup(var.pico_domain, var.env)}"
        }
    }
    EOT
}
```
### Expected Behavior

After updating the root ebs volume size in aws_opsworks_instance, a Terraform Apply should delete the instance and the EBS root volume (as delete_on_termination is set on the aws_opsworks_instance resource), while retaining non-root EBS volumes, which is the same behaviour when I delete the instance manually from the Console (there is a check mark if I want to delete all EBS volumes associated with the instance)
### Actual Behavior

Terraform Apply deletes all EBS volumes attached to the OpsWorks instance
### Important Factoids

I am not sure if the behaviour above is correct, but if it is, then may I request the ability to control whether the EBS volume attached to the OpsWorks instance can be deleted or not, similar to the option given by AWS console?

Thank you!

**Comment by optimisticanshul** [comment]
@jrlonan I think you are looking ```delete_ebs``` it's already there.

**Comment by jrlonan** [comment]
@optimisticanshul 
Which resource is this in? I checked the documentation for aws_opsworks_layer and I don't see that resource in the ebs_volume section
https://www.terraform.io/docs/providers/aws/r/opsworks_custom_layer.html

Note that I configured the EBS volume on the OpsWorks Layer level, and not the instance level.
