### ISSUE TITLE
terraform plan -out encoding

### ISSUE THREAD

**Issue by david-wells-1** [hashicorp/terraform#8810]
terraform version = 0.7.3

Am trying to use the terraform plan -out to save the plan to file, then use terraform apply -state to apply the plan.

1. terraform plan -out plan.tfstate
2. terraform apply -state plan.tfstate

The plan.tfstate file is created and terminal plan output is correct. The file appears, encoded as per online documentation.

When applying however - receive error:

Error reading local state: Decoding state file version failed: invalid character 'f' in literal true (expecting 'r')

Unable to apply the plan. Error does not occur with just a plan and then apply - resources deployed to AWS correctly.

Trace log file when running apply...

2016/09/13 09:38:32 [INFO] Terraform version: 0.7.3  0dd7c657d6d60d2e7392b66ae6f74fb84582cab9
2016/09/13 09:38:32 [INFO] CLI args: []string{"C:\\terraform\\terraform.exe", "apply", "-state", "plan.tfstate"}
2016/09/13 09:38:32 [DEBUG] Attempting to open CLI config file: C:\Users\wellsd\AppData\Roaming\terraform.rc
2016/09/13 09:38:32 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/09/13 09:38:32 [DEBUG] plugin: waiting for all plugin processes to complete...

**Comment by david-wells-1** [comment]
My mistake - amendment to command resolved issue

**Comment by bdangit** [comment]
hey @david-wells-1 what amendment to command did you do?  I'm getting the same error.

**Comment by david-wells-1** [comment]
Hi

File name...easy to misread the online docs....

1. terraform plan -out plan.out

2. terraform apply plan.out

Trick is not to use .tfstate as the file extension - the plan is not a state file

Hope this helps

**Comment by bdangit** [comment]
hrmm that actually didn't fix my problem.  `terraform plan -out plan.out` vs `terraform plan -out plan.tfstate` still results in the same error.  What I do have in my `cwd` are previous `terraform.tfstate` and `terraform.tfstate.backup`.  I moved those to a new dir and tried out the plan again.  It works.  So now I believe my tfstate is corrupt some how.

**Comment by david-wells-1** [comment]
If your terraform.tfstate which you moved is not readable (encoded) could be that you've over written it,

Running the plan then apply would have created a new terraform.tfstate if there was not file in the directory and will only include the resources detailed in the plan.

**Comment by bdangit** [comment]
ah makes sense.  I think what might have happen is that I am doing a `terraform import` of existing infrastructure and me not knowing the proper way to handle such items may have led to my own demise.

Thanks for your help.  I'll have to revisit my terraform workflow closely.
