### ISSUE TITLE
Mismatch in order of attaching multiple volumes to openstack instance using volume section of openstack_compute_instance_v2

### ISSUE THREAD

**Issue by milindchawre** [hashicorp/terraform#8812]
### Affected Resource(s)
- openstack_blockstorage_volume_v1
- volume section of openstack_compute_instance_v2 (where we attach the cinder volume to openstack instance)
### Terraform Configuration Files

``` hcl
# Creating two types of volumes worker_volume and workerebs_volume
resource "openstack_blockstorage_volume_v1" "worker_volume" {
  region = "${var.region}"
  count = "${var.instance_counts.worker}"
  name = "${var.clustername}-worker-volume-${count.index}"
  description = "Worker node volume"
  size = "15"
}

resource "openstack_blockstorage_volume_v1" "workerebs_volume" {
  region = "${var.region}"
  count = "${var.ebs_volume_count}"
  name = "${var.clustername}-worker-ebsvolume-${count.index}"
  description = "Worker node ebs volume"
  size = "10"
}

# Create worker nodes
resource "openstack_compute_instance_v2" "workerebs" {
-------------------
----- <code> -----
-------------------
volume {
    volume_id = "${ element(openstack_blockstorage_volume_v1.worker_volume.*.id, count.index)}"
    device = "/dev/vdc"
  }
  volume {
    volume_id = "${ element(openstack_blockstorage_volume_v1.workerebs_volume.*.id, count.index)}"
    device = "/dev/vdd"
  }
}

Using script in remote-exec to mount these two volumes.
mount /dev/vdc /mnt/docker
mount /dev/vdd /mnt/ebs
```
### Expected Behavior

This code should create two types of cinder volumes and attach it to /dev/vdc (15GB volume) and /dev/vdd (10 GB volume)
### Actual Behavior

The volumes get created and gets attached to /dev/vdc and /dev/vdd
But the 15GB volume gets attached to /dev/vdd and  10GB volume to /dev/vdc, which is wrong.
### Steps to Reproduce
1. Use above terraform configuration code.
2. terraform apply
3. Compare the contents of terraform.tfstate and df -h (or lsblk)

Attaching image showing output of df -h, lsblk and contents of terraform.tfstate
![terraformsnapshot](https://cloud.githubusercontent.com/assets/21288765/18468006/b1414dd0-79bf-11e6-8bb9-81e9b2e8e3cd.PNG)

**Comment by jtopjian** [comment]
Hi there,

Thanks for reporting this - it's definitely an ordering bug of some sort.

Just for clarification, though, are you sure your cloud supports attaching volumes with a specified device? It's my understanding that this is not supported in libvirt/KVM-based clouds -- though maybe that's been fixed.

Regardless of the above (more just a side question), if vdc and vdd are available, they should be chosen as the device letters and attached in the order.

**Comment by milindchawre** [comment]
I don't think the issue is from cloud side, because I can see the volumes with proper size getting created and attached to /dev/vdc (15 GB) and /dev/vdd (10 GB)
![capture1](https://cloud.githubusercontent.com/assets/21288765/18482147/a24a4c9a-79fc-11e6-8ac7-2b8c5381c00a.PNG)

**Comment by jtopjian** [comment]
So the volumes are attached correctly, but the device letter is being reported incorrectly in Terraform?

**Comment by milindchawre** [comment]
I can see the /dev/vdc and /dev/vdd volumes with 15 GB and 10 GB size in openstack_blockstorage_volume_v1 resource in terraform.tfstate file.

**Comment by jtopjian** [comment]
I apologize - I'm trying to correlate all of the information you've posted in your screenshots. To summarize:

* You are creating two volumes:
  * /dev/vdc of 15gb, which is getting a UUID of `456...`
  * /dev/vdd of 10gb, which is getting a UUID of `3d7...`
* OpenStack is showing the volumes are attached correctly.
* The instance is showing the volumes are attached correctly.
* Terraform and the Terraform state show the volumes attached as the opposite device.

Does that sound correct?

Perhaps a quick fix: have you tried using the latest version of Terraform?

**Comment by milindchawre** [comment]
Thanks for summarizing. Its correct.
I don't tried with latest version of terraform.
I can't test with latest version, since there are lot of changes need to be done in the code itself to work with latest version of terraform.

**Comment by jtopjian** [comment]
OK, sounds good. I'll do some testing and see if I can reproduce. Thank you for your patience and for reporting this :)

**Comment by milindchawre** [comment]
@jtopjian Any updates?

**Comment by jtopjian** [comment]
@milindchawre Sorry for the delay. I've been focusing on #9407. I hope to get to the backlog of OpenStack issues once that's been merged.

I understand that you're not able to test with the latest version of Terraform for your existing configuration, but is it possible to create a new configuration that just reproduces the issue you're seeing?

**Comment by Hoverbear** [comment]
We've run into the same problem as described here.

```
  volume {
    volume_id = "${openstack_blockstorage_volume_v1.volume-that-is-800.id}"
    device    = "/dev/vdb"
  }

  volume {
    volume_id = "${openstack_blockstorage_volume_v1.volume-that-is-40.id}"
    device    = "/dev/vdc"
  }

  volume {
    volume_id = "${openstack_blockstorage_volume_v1.volume-that-is-40.id}"
    device    = "/dev/vdd"
}
```

Results sometimes in:

```
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  242M  3.0G   8% /run
/dev/vda1        50G  2.8G   45G   6% /
tmpfs            16G  4.0K   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/vdb         40G  1.2G   37G   3% /var/lib/postgresql
/dev/vdc         40G   35G  3.0G  93% /var/apps/osm/flatnodes
/dev/vdd        788G   35G  714G   5% /var/apps/osm/planetfile
```

Sometimes it works correctly:

```
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  8.6M  3.2G   1% /run
/dev/vda1        50G  2.3G   45G   5% /
tmpfs            16G  4.0K   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/vdb        788G  105M  748G   1% /var/lib/postgresql
/dev/vdc         40G   48M   38G   1% /var/apps/osm/flatnodes
/dev/vdd         40G   48M   38G   1% /var/apps/osm/planetfile
```

This happened in 0.7.13 and 0.8.2.

**Comment by jtopjian** [comment]
@Hoverbear Thanks for the report! Would you be able to try the new [`openstack_compute_volume_attach_v2`](https://www.terraform.io/docs/providers/openstack/r/compute_volume_attach_v2.html) resource and see if this is still happening?

You should also be able to enforce a dependency chain on the attachments:

```hcl
resource "openstack_blockstorage_volume_v2" "vol_1"
  size = "800"
}

resource "openstack_blockstorage_volume_v2" "vol_2"
  size = "40"
}

resource "openstack_blockstorage_volume_v2" "vol_3"
  size = "40"
}

resource "openstack_compute_instance_v2" "instance_1" {
  ...
}

resource "openstack_compute_volume_attachment_v2" "vol_1"
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
  volume_id = "${openstack_blockstorage_volume_v2.vol_1.id}"
}

resource "openstack_compute_volume_attachment_v2" "vol_2"
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
  volume_id = "${openstack_blockstorage_volume_v2.vol_2.id}"
  depends_on = ["openstack_compute_volume_attachment_v2.vol_1"]
}

resource "openstack_compute_volume_attachment_v2" "vol_3"
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
  volume_id = "${openstack_blockstorage_volume_v2.vol_3.id}"
  depends_on = ["openstack_compute_volume_attachment_v2.vol_2"]
}
```

**Comment by Hoverbear** [comment]
@jtopjian So I tried the `blockstorage_volume_attach` as well yesterday:

```
resource "openstack_blockstorage_volume_v2" "size-800" {
  name        = "size-800"
  size        = 800
}

resource "openstack_blockstorage_volume_v2" "size-40-a" {
  name        = "size-40-a"
  size        = 40
}

resource "openstack_blockstorage_volume_v2" "size-40-b" {
  name        = "size-40-b"
  size        = 40
}

resource "openstack_blockstorage_volume_attach_v2" "size-800" {
  instance_id = "${openstack_compute_instance_v2.machine.id}"
  volume_id = "${openstack_blockstorage_volume_v2.size-800.id}"
  device = "/dev/vdb"
  attach_mode = "rw"
}


resource "openstack_blockstorage_volume_attach_v2" "size-40-a" {
  instance_id = "${openstack_compute_instance_v2.machine.id}"
  volume_id = "${openstack_blockstorage_volume_v2.size-40-a.id}"
  device = "/dev/vdc"
  attach_mode = "rw"
}


resource "openstack_blockstorage_volume_attach_v2" "size-40-b" {
  instance_id = "${openstack_compute_instance_v2.machine.id}"
  volume_id = "${openstack_blockstorage_volume_v2.size-40-b.id}"
  device = "/dev/vdd"
  attach_mode = "rw"
}
```

In this case the disks didn't mount at all. They were not listed by `lsblk` at all and did not mount in any way.

I cannot currently test the compute attach scheme, I will do this quite soon and report back.

**Comment by Hoverbear** [comment]
Unfortunately I cannot test the `compute_volume_attach` as my provider does not support it.

```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * openstack_compute_volume_attachment_v2.one: Provider doesn't support resource: openstack_compute_volume_attachment_v2
  * openstack_compute_volume_attachment_v2.two: Provider doesn't support resource: openstack_compute_volume_attachment_v2
  * openstack_compute_volume_attachment_v2.three: Provider doesn't support resource: openstack_compute_volume_attachment_v2
```

**Comment by jtopjian** [comment]
@Hoverbear You have a typo in the resource name. It's `openstack_compute_volume_attach_v2`.

**Comment by Hoverbear** [comment]
This is what I get for copying your block. :-P We've worked around the problem for now, I won't be able to follow up and test that method for quite some time.

**Comment by jtopjian** [comment]
@Hoverbear whoops - indeed the typo was originally in my code! No rush on testing, but let me know if it helps this.
