### ISSUE TITLE
dependency versions for building?

### ISSUE THREAD

**Issue by mavenraven** [hashicorp/terraform#882]
Hi there, I'm building terraform from source. Looking at "updatedeps" in the Makefile, it looks like it just grabs the head of all the dependent repositories. Are the versions of dependencies being recorded anywhere? Thank you!

**Comment by phinze** [comment]
Good question!

You have accurately represented the current state of things. Between releases, we track with `HEAD` of our dependencies. If one of them has problems or breaks an API contract, we either update Terraform to fix, work with upstream to resolve it, or fork the dependency to a known-good version. We are building terraform from master constantly, so any build issues tend to be resolved quickly.

Before a release, we build official binaries and test them extensively before they go out the door. Currently, we don't record the state of our dependencies when this happens, but it's a good idea for us to capture and publish that information.

Internally, we've discussed using something like `godep` to statically track dependencies in `master`, but we have decided against it for now. Given the state of the Go library ecosystem right now and our current portfolio of dependencies, we'd rather catch and fix build failures quickly than navigate things like upstream transitive version dependency conflicts.

Thanks for your question; I hope this helps explain things. Keep your eyes peeled for dependency snapshot information in the release notes for Terraform 0.3.7! :thumbsup:
