### ISSUE TITLE
unexpected EOFs with 0.7.3

### ISSUE THREAD

**Issue by n-my** [hashicorp/terraform#8826]
**Terraform version 0.7.3**

I got unexpected EOF errors running a `terraform apply`
```2 error(s) occurred:```
```*aws_vpc.main: unexpected EOF```
```*aws_eip.ng: unexpected EOF```

It runs well with 0.7.2

You will find attached the crash log [here](https://github.com/hashicorp/terraform/files/470301/crash.txt)

**Comment by jen20** [comment]
Relevant part of crash log:

```
2016/09/13 18:12:12 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is nil, not *aws.AWSClient
2016/09/13 18:12:12 [DEBUG] plugin: terraform: goroutine 148 [running]:
2016/09/13 18:12:12 [DEBUG] plugin: terraform: panic(0x28d0ae0, 0xc420797a00)
2016/09/13 18:12:12 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2016/09/13 18:12:12 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsVpcCreate(0xc420343860, 0x0, 0x0, 0x28d5d60, 0x414ab1)
```

@n-my - can you confirm if you are doing anything like assuming a role as part of the configuration of the provider here?

**Comment by n-my** [comment]
@jen20 there is no role assuming
Do you need the terraform file I was applying ?

**Comment by catsby** [comment]
Hey @n-my – if you have a terraform config file that reproduces this, that you don't mind sharing, we'd love to see it! Please be sure to omit any secret info 😄

**Comment by n-my** [comment]
I removed my tfstate file and ran it again. This time everything went well so I'm not sure how to reproduce the crash.

Anyway if it's helping you can find the code I was using [here](https://github.com/n-my/tf-issue8826)

**Comment by catsby** [comment]
Closing for now, thanks!
