### ISSUE TITLE
make vet is failing on resource aws_efs_mount_target_test.go

### ISSUE THREAD

**Issue by majormoses** [hashicorp/terraform#8839]
### Terraform Version
Attempting to build 0.7.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws/resource_aws_efs_mount_target

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
https://gist.github.com/majormoses/11e82ee56e3b1c2be1744a242d0b34ea

### Expected Behavior
Tests should pass and allow a release build to be compiled

### Actual Behavior
While `make test` suceeds it fails on `make vet`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. verify go 1.6+ `go version`
1. `cd $GOPATH/src/github.com/hashicorp/terraform`
1. `git checkout v0.7.3` (although I have reproduced on master)
1. `make` (will fail on target of `make vet`)

### Important Factoids
- go version 1.6.2

**Comment by jen20** [comment]
Thanks @majormoses, this is now fixed on `master`!
