### ISSUE TITLE
Add ssl_verify option to consul provider

### ISSUE THREAD

**Issue by gozer** [hashicorp/terraform#8841]
Right now, working around it by setting :

```
CONSUL_HTTP_SSL_VERIFY=1
```

in my environment, but would be so much cleaner if I could use the provider to do it explicitely:

```
provider "consul" {
  address    = "some.host.name:443"
  scheme     = "https"
  ssl_verify = "false"
}
```

**Comment by pll** [comment]
@jen20 I think this may be related to my issue here: https://github.com/hashicorp/terraform/issues/8690

**Comment by pll** [comment]
@gozer Thanks for the work-around!  I was trying everything a couple weeks back and gave up!  How did you find the CONSUL_HTTP_SSL_VERIFY=1 trick ?

**Comment by gozer** [comment]
It's hidden in the Consul go API library!

And,  yes,  same issue. I do like the more generic insecure solution !
