### ISSUE TITLE
forces new resource

### ISSUE THREAD

**Issue by zraja83** [hashicorp/terraform#8842]
Hi there,
I am new to Terraform so please excuse my mistakes, I started building resources as modules and I am using S3 for managing remote tfstate.

### Terraform Version
v0.7.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kinesis_stream
- aws_s3_bucket
- aws_ec2
- other_aws

### Terraform Configuration Files
```hcl
resource "aws_kinesis_stream" "stream" {
    name = "${var.kinesis_name}"
    shard_count = "${var.shard_count}"
    retention_period = "${var.retention_period}"
    shard_level_metrics = [
        "IncomingBytes",
        "OutgoingBytes"
    ]
    tags {
        env = "${var.env}"
    }
}
```

### Expected Behavior

Every time I create resource for the first time it works fine but when I use the same module on my next apply, it destroys my existing resource and replaces with new. If I add lifecyle {ignore_change or protect_destroy}, there is no action change.

Pleas advice if I missing anything.

### Actual Behavior
I created new kinesis stream “dev-terraform” which got working and then on another day I tried creating second stream “dev-2-terraform”, for which I updated my parameter stream-name(under tfvars) and ran the plan, it reports that it is going to "force new resource" as replacement, see attach screenshot (1 to add, 1 to destroy).

After applying terraform, my old stream got destroyed and the new stream was created.

Happens with other resource aswell creating_s3 bucket, setting up new-user, launching ec2_instance.

![image](https://cloud.githubusercontent.com/assets/16762135/18526558/fdcdc3de-7a8e-11e6-969f-48aeb67b02c4.png)

**Comment by jen20** [comment]
Hi @zraja83! This looks like it is behaving as expected to me - can you post more context of your configuration files? The reason the new resource is being forced is that you are changing the name of the existing Kinesis stream - which is not a permitted AWS API operation. Consequently the only option is to remove and recreate the stream. Since this looks to be behaving correctly right now, I'll go ahead and close this issue. If you have further context to demonstrate something behaving incorrectly I'd be happy to reopen it and take a second look! Thanks.

**Comment by zraja83** [comment]
Thanks @jen20 for getting back.

In my use case Terraform takes user input as a bucket name and the script creates s3 bucket with two IAM policies(ReadOnly and ReadWrite). I would like users to re-run this script whenever we need to create bucket and the policies, later another script to run and attach these policies to users.

We are trying to to limit users from going to the console and instead use Terraform to do admin tasks.
We would like to do the same for other cases such as launching ec2 instances, creating new users etc
 
So what I am understanding from your comment: Terraform is not meant to re-use the code in my case, correct?

Thanks Again.....
