### ISSUE TITLE
Tags for ALB target group resources doesn't work, updating priorities doesn't work

### ISSUE THREAD

**Issue by tomgoren** [hashicorp/terraform#8847]
Greetings! I am running into a couple of issues with the new ALB resources.
### Terraform Version

```
18:12 $ terraform -v
Terraform v0.7.3
```
### Affected Resource(s)
- aws_alb_target_group
- aws_alb_listener_rule
### Terraform Configuration Files

``` hcl
resource "aws_alb_target_group" "alb_target_group_alpha" {
  name     = "alb_target_group_alpha"
  port     = 80
  protocol = "HTTP"
  vpc_id = "${var.vpc_id}"
  tags {
    ExampleTag = "I_AM_A_VALUE"
  }
}
```

``` hcl
resource "aws_alb_listener_rule" "forward_traffic_alpha" {
  listener_arn = "${aws_alb_listener.alb_listener_alpha.arn}"
  priority = 1000

  action {
    type = "forward"
    target_group_arn = "${aws_alb_target_group.alb_target_group_alpha.arn}"
  }

  condition {
    field = "path-pattern"
    values = ["*"]
  }
}
```
### Expected Behavior

Priority should have been updated in AWS when changing value in config file.
`terraform plan` indicates that tags will be updated, and that priority will be changed.
### Actual Behavior

None of the above.
In order to change the priorities, the ALB had to be recreated (i.e. manually deleted and then run `terraform apply`).
Tags are not applied to the target group resource _at all_.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create an `aws_alb_target_group` resource with tags
2. Run `terraform apply`
3. Expect tags
4. Be disappointed

OR
1. Change priorities of listener rule
2. `terraform apply`
3. Nothing changed

Apologies if missing critical information - this is my first time opening a ticket.
Thanks!

**Comment by tomgoren** [comment]
Tags work as expected for `aws_alb` resources.

**Comment by rbuels** [comment]
I am also seeing that updating the "name" attribute of an `aws_alb_target_group` doesn't work.  terraform tries at every apply to change the name, but the name is never actually updated in AWS.

**Comment by tomgoren** [comment]
Good catch! Thanks for the follow up - I'm glad this is getting some traction.
I added an entry in `outputs.tf` to produce the ARN of the Target Group, and wrote a script in the meantime to apply the tags manually to that ARN.

**Comment by stack72** [comment]
Hi @tomgoren 

so i've lost track of what the issue here is - is it to do with tags or to do with priorities? 

Thanks

Paul

**Comment by tomgoren** [comment]
@stack72 sorry about that!

When I originally filed this issue - both were buggy, i.e. the tags weren't being updated and nor was the priority of the listener rule in question.

I'm going to do some testing with 0.7.7 today to verify that this is still pertinent (I suspect it is as I haven't seen anything in the Changelog referencing the ALB resources.

**Comment by tomgoren** [comment]
Indeed - tags still aren't set. In the interim I wrote a script and called it with `local_exec` to add the tags appropriately.

Verified that priorities aren't set as expected either.

BTW the output from `terraform plan` shows that the command _wants_ to make the changes, they just never take place in `terraform apply`.

**Comment by tomgoren** [comment]
Still getting:

```
~ module.environment.shizbot.aws_alb_target_group.shizbucket
    tags.%: "" => "<computed>"
```

This is despite the fact that the tags are _already_ set manually, and match the interpolated value. This just appears every single run of `terraform plan` no matter what.

**Comment by stack72** [comment]
@tomgoren just a FYI, I am working on this right now

**Comment by tomgoren** [comment]
Awesome, thanks @stack72!!!
