### ISSUE TITLE
Remote state is unable to fetch output for nested modules

### ISSUE THREAD

**Issue by hazim1093** [hashicorp/terraform#8853]
I'm trying to use terraform remote state as `data` with backend s3. The remote state consists of a module known as `network` and the output I am trying to access is inside that module. As per my understanding of the docs, that shouldn't matter:

> ... each output in the remote state appears as a top level attribute ...

the usage always results in the following error:

> Resource 'data.terraform_remote_state.my_state' does not have attribute 'vpc_id' for variable 'data.terraform_remote_state.my_state.vpc_id'

My code for using this is as follows 

`${data.terraform_remote_state.my_state.vpc_id}`

Terraform Version: 0.7.2
OS: Linux 16.04

**Comment by apparentlymart** [comment]
Hi @hazim1093. Sorry for the confusing documentation wording here.

It is expected and intended behavior that only the root outputs of the remote state would be exposed via the `terraform_remote_state` data source. Any resources or child modules of that configuration are considered implementation details of that resource and not something that outside configuration should be depending on.

If you want to expose a resource attribute or child module output via remote state then it's necessary to add an `output` block to the top-level module which exposes the desired value.

**Comment by hazim1093** [comment]
Oh ok, It really makes sense this way. I guess I just started thinking on a different line due to the wording. 

Thanks @apparentlymart :)
