### ISSUE TITLE
Docs for VSphere provider don't specify which attributes force new resources

### ISSUE THREAD

**Issue by partamonov** [hashicorp/terraform#8855]
I mentioned that a lot of values are forcing VM re-creation.

Some examples are dns servers list or windows domain user
`windows_opt_config.0.domain_user:          "" => "Domain\\partamonov" (forces new resource)`

Do we have any vision on what should force new VM and what should not?

**Comment by jen20** [comment]
Hi @partamonov! It's traditional for the documentation for each resource to mention whether changing an attribute will force a new resource. Unfortunately that doesn't appear to have been applied to the Vsphere resources, however. I'll adjust the title and categorisation of this issue to reflect what needs to happen. Thanks for opening an issue!
