### ISSUE TITLE
s3_bucket_notification for multiple lambda_function elements

### ISSUE THREAD

**Issue by a-h** [hashicorp/terraform#8856]
I've submitted a pull request #8854 to also clarify the behaviour with Lambda notifications in the documentation.

It's not obvious (to me!) that having multiple `s3_bucket_notification` configurations, each with a single `lambda_function` configuration will result in one taking precedence (at random?).

I'm not sure that this is desired behaviour. Shouldn't multiple `s3_bucket_notification` elements against the same `bucket` should be considered invalid?

This is a similar issue to #6934
### Affected Resource(s)
- s3_bucket_notification
- lambda_function
### Terraform Configuration Files

``` hcl
resource "aws_s3_bucket_notification" "dev_bucket_notification" {
     bucket = "${aws_s3_bucket.build_bucket.id}"
     lambda_function {
         lambda_function_arn = "${aws_lambda_function.dev_release.arn}"
         events = ["s3:ObjectCreated:*"]
         filter_prefix = "dev/"
         filter_suffix = ".zip"
     }
 }

resource "aws_s3_bucket_notification" "qa_bucket_notification" {
     bucket = "${aws_s3_bucket.build_bucket.id}"
     lambda_function {
         lambda_function_arn = "${aws_lambda_function.qa_release.arn}"
         events = ["s3:ObjectCreated:*"]
         filter_prefix = "qa/"
         filter_suffix = ".zip"
     }
 }
```
### Expected Behavior

An error should have been generated, or the two `lambda_function` elements applied.
### Actual Behavior

Only one of the notifications was applied, at random.
### References
- #6934
- #8854

**Comment by dcosson** [comment]
+1

My use case is that I have a module where I was passing in an s3_bucket and s3_prefix as a variable, and it would create a lambda function and hook up a notification from the s3 bucket (among other things). I unexpectedly ran into this issue once I tried to pass the same bucket but a different prefix to a new instance of this module.

It would be helpful for encapsulation if I could do this, for now I'll have to take the s3 bucket notification out of my module entirely.
