### ISSUE TITLE
`sql_mode` in an RDS parameter group always causes an update

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#886]
Given this:

```
resource "aws_db_parameter_group" "test" {
    name = "test"
    family = "mysql5.6"
    description = "just a test"

    parameter {
        name = "sql_mode"
        value = "STRICT_ALL_TABLES"
    }
}
```

You can apply that, and a parameter group will be made with sql_mode=STRICT_ALL_TABLES. The state file will reflect that fact:

```
                "aws_db_parameter_group.test": {
                    "type": "aws_db_parameter_group",
                    "primary": {
                        "id": "test",
                        "attributes": {
                            "description": "just a test",
                            "family": "mysql5.6",
                            "id": "test",
                            "name": "test",
                            "parameter.#": "1",
                            "parameter.1506707202.name": "sql_mode",
                            "parameter.1506707202.value": "strict_all_tables"
                        }
                    }
                },
```

But now do a plan:

```
~ aws_db_parameter_group.test
    parameter.2228267888.name:  "" => "sql_mode"
    parameter.2228267888.value: "" => "STRICT_ALL_TABLES"
```

If I'm reading this correctly, this means Terraform read the resource, and thinks that the parameter is empty and it needs to create it. I'm not expecting any update because the parameter group already exists with `sql_mode=STRICT_ALL_TABLES` in RDS.

Confusingly, my attempts to instrument the conversation with RDS indicates that Terraform is getting `sql_mode=STRICT_ALL_TABLES` from RDS, at least as far as `flattenParameters`. And oddly, I can reproduce this *only* with `sql_mode` -- every other parameter I've tried works fine. Not sure what's special about that one, and I'm out of ideas.

**Comment by catsby** [comment]
Fixed in #1225
