### ISSUE TITLE
aws_elasticache_cluster should force destroy when changing node_type with memcached engine

### ISSUE THREAD

**Issue by mblakele** [hashicorp/terraform#8865]
### Terraform Version

```
$ terraform -v
Terraform v0.7.3
```
### Affected Resource(s)
- aws_elasticache_cluster (with `engine=memcached`)
### Terraform Configuration Files

Original:

``` hcl
resource "aws_elasticache_cluster" "fubar" {
  cluster_id = "fubar"
  engine = "memcached"
  node_type = "cache.t2.micro"
}
```

Updated to:

``` hcl
resource "aws_elasticache_cluster" "fubar" {
  cluster_id = "fubar"
  engine = "memcached"
  node_type = "cache.t2.medium"
}
```
### Expected Behavior

Because AWS doesn't support changing the memcached node type, the terraform plan should destroy and recreate the resource.
### Actual Behavior

Running `terraform plan` shows resource modification:

```
~ aws_elasticache_cluster.fubar
    node_type:       "cache.t2.micro" => "cache.t2.medium"
```

Then `terraform apply` fails with:

```
InvalidParameterCombination: Scaling is not supported for engine memcached
```
### Important Factoids

I can't find clear AWS documentation for this limitation, but it seems to be real.

**Comment by johanneswuerbach** [comment]
The same should happen when the `node_type` is changed for redis as it also doesn't support changing the node_type.

**Comment by w32-blaster** [comment]
+1. 
@johanneswuerbach : Redis does support node_type change. Only memcached has this limitation.
