### ISSUE TITLE
Feature Request: support regional google instance group managers

### ISSUE THREAD

**Issue by mschroeder223** [hashicorp/terraform#8866]
The GCP docs and ui allow for the creation of regional (multi-zone) instance group managers.

After looking through the source I believe this actually tracks back to a limitation with the current google compute api library. In the current v1 only InstanceGroupManagersInsertCall exists, which in the beta v0.beta an additional set of calls for RegionInstanceGroupManagersInsertCall has been added.

InstanceGroupManagersInsertCall in v1 (stable)
https://code.googlesource.com/google-api-go-client/+/master/compute/v1/compute-gen.go#21873

RegionInstanceGroupManagersInsertCall in v0.beta
https://code.googlesource.com/google-api-go-client/+/master/compute/v0.beta/compute-gen.go#37848

Are there any current workarounds for this?

**Comment by cblecker** [comment]
@mschroeder223 
The docs actually specify that this functionality is in beta: https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups

Once Google promotes this out of beta, then it should get promoted into the v1 stable API and be available to be added as a resource to Terraform.

**Comment by JCFesantieu** [comment]
Hello, 

For information, Regional Instance Groups are now in G.A on GCP. 
https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups

**Comment by jaibheem** [comment]
Looks like the feature is GA now 
https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#creating_a_regional_managed_instance_group

Can we please make this available via terraform?

**Comment by ldelossa** [comment]
Big 👍 here.

**Comment by ardling** [comment]
+1

**Comment by baskaran-md** [comment]
Any updates on when this will be released?

**Comment by gburiola** [comment]
+1

**Comment by paddycarver** [comment]
We have a community PR open for this at the moment. We're working on getting that merged, one way or another. I can't provide any timeline on this, but it's on our radar and we'd like to add support for it. :) Progress can be tracked in #10907. Thanks for the interest!
