### ISSUE TITLE
aws_route_table changes applied indefinitely upon running plan/apply 

### ISSUE THREAD

**Issue by lukasbernat** [hashicorp/terraform#8873]
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- aws_route_table
#### output

terraform plan:

~ module.name-vpc-region.aws_route_table.ngw-az1
    route.2495587896.cidr_block:                "0.0.0.0/0" => "0.0.0.0/0"
    route.2495587896.gateway_id:                "" => ""
    route.2495587896.instance_id:               "" => ""
    route.2495587896.nat_gateway_id:            "nat-074166a9035f79ef4" => "nat-074166a9035f79ef4"
    route.2495587896.network_interface_id:      "" => ""
    route.2495587896.vpc_peering_connection_id: "" => ""
    route.2997578964.cidr_block:                "30.0.0.0/8" => ""
    route.2997578964.gateway_id:                "vgw-2b0e3d5f" => ""
    route.2997578964.instance_id:               "" => ""
    route.2997578964.nat_gateway_id:            "" => ""
    route.2997578964.network_interface_id:      "" => ""
    route.2997578964.vpc_peering_connection_id: "" => ""
    route.556279583.cidr_block:                 "" => "30.0.0.0/8"
    route.556279583.gateway_id:                 "" => ""
    route.556279583.instance_id:                "" => ""
    route.556279583.nat_gateway_id:             "" => "vgw-2b0e3d5f"
    route.556279583.network_interface_id:       "" => ""
    route.556279583.vpc_peering_connection_id:  "" => ""

terraform apply, and run terraform plan again without configuration changes:

~ module.name-vpc-region.aws_route_table.ngw-az1
    route.2495587896.cidr_block:                "0.0.0.0/0" => "0.0.0.0/0"
    route.2495587896.gateway_id:                "" => ""
    route.2495587896.instance_id:               "" => ""
    route.2495587896.nat_gateway_id:            "nat-074166a9035f79ef4" => "nat-074166a9035f79ef4"
    route.2495587896.network_interface_id:      "" => ""
    route.2495587896.vpc_peering_connection_id: "" => ""
    route.2997578964.cidr_block:                "30.0.0.0/8" => ""
    route.2997578964.gateway_id:                "vgw-2b0e3d5f" => ""
    route.2997578964.instance_id:               "" => ""
    route.2997578964.nat_gateway_id:            "" => ""
    route.2997578964.network_interface_id:      "" => ""
    route.2997578964.vpc_peering_connection_id: "" => ""
    route.556279583.cidr_block:                 "" => "30.0.0.0/8"
    route.556279583.gateway_id:                 "" => ""
    route.556279583.instance_id:                "" => ""
    route.556279583.nat_gateway_id:             "" => "vgw-2b0e3d5f"
    route.556279583.network_interface_id:       "" => ""

(can be repeated indefinitely)

**Comment by libertyy** [comment]
FYI, This happens when using a nat_gateway_id; this does not happen when using an internet gateway.

**Comment by libertyy** [comment]
As a temporary workaround, you can insert the following into your aws_route_table resource:

    lifecycle {
        ignore_changes = ["route"]
     }

**Comment by andor-pierdelacabeza** [comment]
Same for me @ Terraform v0.8.4
