### ISSUE TITLE
Concise syntax for outputting vars en masse

### ISSUE THREAD

**Issue by robert-stuttaford** [hashicorp/terraform#8876]
On recommendation from @phinze - https://twitter.com/phinze/status/776509212646051840

Please consider a syntax for outputting variables en masse. 

I mean something that replaces this:

```
output "aa" {
  value = "${var.aa}"
}

output "bb" {
  value = "${var.bb}"
}
```

with something like this (pseudocode, obviously):

```
output {
  variables = ["aa", "bb"]
}
```

It's not obvious with only a handful of variables, but with many variables, this would create great concision and remove boilerplate.

Thank you :-)

**Comment by mildwonkey** [comment]
This works in terraform 0.12:

```hcl
variable "aa" { default = "aa" }
variable "bb" { default = "bb" }

output "variables" {
  value = [var.aa,var.bb]
}
```

```
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

variables = [
  "aa",
  "bb",
]
```


Note that I am using bracket syntax `[]`, which creates a tuple, instead of `list()`, which requires that all elements have the same type, so that different variable types are supported:
```hcl
variable "aa" { default = "aa" }
variable "bb" { default = 42 }

output "variables" {
  value = [var.aa,var.bb]
}
```
```
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

variables = [
  "aa",
  42,
]
```
