### ISSUE TITLE
Create a terraform deport (analog of terraform import)

### ISSUE THREAD

**Issue by zapman449** [hashicorp/terraform#8880]
### Terraform Version
0.7.3

Feature Request

I needed to move some terraform resources from one Terraform State File to a different one to simplify some logic, without destroying the resources in the mean time.

Importing the resource into the new state file was easy and awesome: Just `terraform import`.  However, removing the old one required manually hacking the terraform state file, which was possible, but certainly sub-optimal.

Terraform should allow the 'deporting' of resources without destroying the resource.

Semantics would be identical to `terraform import`.

**Comment by radeksimko** [comment]
Hi @zapman449 
I believe this is already implemented as `state` subcommand:

```
terraform state rm TYPE.RESOURCE_ADDRESS
```

https://www.terraform.io/docs/commands/state/rm.html

Let us know if that solves the problem you're trying to solve or if not - what can be changed/improved.

**Comment by zapman449** [comment]
I never saw that, and I don't think I would have found that on my own.  Perhaps mentioning `state` in the `import` docs might be prudent.  Otherwise, issue can be closed.

**Comment by cblecker** [comment]
@zapman449 
State management commands are mentioned [here](https://www.terraform.io/docs/import/usage.html), but only in the context of renaming. Created #8885 to try an clarify it a bit.
