### ISSUE TITLE
Empty arrays interpreted as unset variable when reading from .tf.json formatted variable files

### ISSUE THREAD

**Issue by Fitzsimmons** [hashicorp/terraform#8886]
It seems empty arrays defined in .tf.json files are not interpreted as set variables. I was able to reduce this problem to a very small test case on Terraform v0.7.3.

**provision.tf**
```hcl
variable "foo" {
	type = "list"
}

provider "aws" {
	region = "us-east-1"
}

resource "aws_vpc" "vpcs" {
	count = "${length(var.foo)}"
	cidr_block = "${element(var.foo, count.index)}"
}
```

After `terraform plan`ing with an empty variable in an hcl-style config, the plan comes out as empty as expected:

**tfvars/variables.tfvars**
```hcl
foo = []
```
```
$ terraform plan -var-file=tfvars/variables.tfvars
[snip]
No changes. Infrastructure is up-to-date.
[snip]
```

However, if I try this with an equivalent json file, I'm prompted for input.

**json/variables.tf.json**
```json
{ "foo": [] }
```
```
$ terraform plan -var-file=json/variables.tf.json
var.foo
  Enter a value: ^C
Error configuring: Error asking for foo: interrupted
```
This is specifically a problem with empty arrays in json, because if I populate the array with a value, terraform becomes aware that it has been set.

**json/variables.tf.json**
```json
{ "foo": ["192.168.77.0/24"] }
```
```
$ terraform plan -var-file=variables.tf.json
[snip]
+ aws_vpc.vpcs
    cidr_block:                "192.168.77.0/24"
    default_network_acl_id:    "<computed>"
    etc ...
```

It would be great if empty arrays read from JSON files were actually interpreted as such.

**Comment by mitchellh** [comment]
Thanks! I have a PR open for the HCL project that will fix this. Once that is merged, I'll also add a failing test for your case here in Terraform (to avoid regressions in this project) and update the HCL vendor.
