### ISSUE TITLE
Can't execute File provisioner on AWS Windows EC2 Instance

### ISSUE THREAD

**Issue by sanket-t-shah** [hashicorp/terraform#8887]
Hi,

Am trying to create a Windows VM from Amazon AMI on AWS. The EC2 instance gets successfully created, but when am trying to copy file from local disk to Remote, am getting timeout error.

Am using latest terraform. Ports: 80, 5985 and 3389 are open in AWS Security Group and outbound traffic is allowed for all ports to all destinations. Here is my .tf file:

```
resource "aws_instance" "windows_ec2" {
    ami                     = "ami-d6f32ab5"
    availability_zone       = "ap-southeast-1b"
    monitoring              = "false"
    instance_type           = "t2.micro"
    key_name                = "terraformuser"
    security_groups         = ["${aws_security_group.windows_ec2_sg.id}"]
    subnet_id               = "${aws_subnet.windows_subnet.id}"
    tags {
        Name = "Windows Instance"
    }
    ebs_block_device {
        device_name         = "/dev/sdf"
        volume_type         = "standard"
        volume_size         = "1"
    }
    provisioner "file" {
        source              = "create-hello-world.html"
        destination         = "C:/inetpub/wwwroot/index.html"
        connection {
            type            = "winrm"
            user            = "administrator"
            https           = false
            insecure        = true
        }
    }
}

```
### Expected Behavior

Terraform should have copied file to remote EC2 Instance.
### Actual Behavior

Terraform is throwing timeout error.
![error](https://cloud.githubusercontent.com/assets/7502469/18597127/213df5dc-7c6a-11e6-96bd-e07f4a35ff42.png)

**Comment by jen20** [comment]
Hi @sanket-t-shah - you will need to configure WinRM on the instance as well as opening the port on the security group. It's worth also being aware that the file provisioner over WinRM is pretty weird - it's not a natively supported operation, so it's constructed out of a library [here](https://github.com/packer-community/winrmcp). I would only use file provisioners over WinRM as al last resort.

**Comment by danohalloran-starz** [comment]
So what would you suggest for a windows ami (aws ec2 windows instance) 
> I would only use file provisioners over WinRM as al last resort.

Trying to kick off some ps1 scripts to automate join domain and others but if WinRM is not the best do we install ssh and use ssh provisiners for remote execution?

**Comment by mitchellh** [comment]
WinRM properly configured will work, its just weird as @jen20 said (you can see how its down).

Setting up SSH would also work well.
