### ISSUE TITLE
Provider's CRUD functions are difficult to unit test

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#890]
This could be my inexperience with Go, but I find it very difficult to unit test provider CRUD functions. The reason is that they take a `*schema.ResourceData` parameter, but a lot of the fields in that type are private. Thus, it's not possible to construct a `ResourceData` out of tree for testing.

Would it make sense to define an interface for the thing given to the CRUD operations? Out-of-tree providers would then be able to make mock implementations and unit testing would be much simpler. I guess such a change would be an incompatible change to the provider API, but one that's easily fixed by changing the signature of the CRUD functions. Not sure how much of a concern that is.

I'll give implementing this a shot if it seems like a good idea.

**Comment by mitchellh** [comment]
This seems like a good idea. We focused on acceptance over unit for providers since based on our experience with Vagrant, Packer, and now this, MOST providers are pretty hard to unit test since ther aren't good mocking libraries for the API clients. 

But, that doesn't mean we shouldn't try to make it possible. Tagging.

**Comment by bitglue** [comment]
Cool. I'll give it a shot. I think it should be easy, but then everything seems easy until it isn't.

**Comment by phinze** [comment]
This conversation played out over in #908 - see that thread for context.

**Comment by bitglue** [comment]
So since the solution I proposed was rejected, what's the suggested solution? There is, so far as I've been able to tell, no way to unit test out of tree providers. A couple alternatives were discussed in #908 that could be implemented: were they? Is it just a matter of adding documentation so people like me, who want to implement providers but aren't experts in Terraform's internals, can know how they might write unit tests for their providers?

**Comment by phinze** [comment]
@bitglue ah sorry I've been flying through old issues and misread this description as encompassing the interface solution. We still don't have a good way of unit testing providers today, I'll reopen this until we come up with a story there. :+1:

**Comment by mitchellh** [comment]
You can use `schemaMap.Data` to create test data. This could easily be wrapped in some helper functions. We recommend this as the approach forward.

**Comment by dikhan** [comment]
Actually, I think I found a handy Test method that might just do exactly what I wanted :)

Putting it here for the reference, the [TestResourceDataRaw](https://godoc.org/github.com/hashicorp/terraform/helper/schema#TestResourceDataRaw) allows you to create a ResourceData object initialized with some schema and raw values that can then be used for unit testing purposes. 

For instance, I had a function with the following signature that I wanted to unit test:

````
func (r resourceFactory) createPayloadFromLocalStateData(resourceLocalData *schema.ResourceData) map[string]interface{} {
````

With the above TestResourceDataRaw I can easily create a schema.ResourceData object initialized the way I want and then perform assertions based on that:

````
func TestCreatePayloadFromLocalStateData(t *testing.T) {
        r := resourceFactory{}

	expectedValue := "someExpectedValue"
	resourceSchema := map[string]*schema.Schema{
		"existing_key": &schema.Schema{
			Type: schema.TypeString,
		},
	}
	resourceDataMap := map[string]interface{}{
		"existing_key": expectedValue,
	}
	resourceLocalData := schema.TestResourceDataRaw(t, resourceSchema, resourceDataMap)

	map := r.createPayloadFromLocalStateData(resourceLocalData)
        // some assertions here
}
````

Hope this helps, took me a while until I found this magical method :)

Dani

**Comment by nmiodice** [comment]
@dikhan this has been invaluable for us while working on the terraform provider for [Azure DevOps](https://github.com/microsoft/terraform-provider-azuredevops).

Have you found a way to mimic a change that would be needed during the `update` hook? I'd like to mock the following pseudo code:
```go
	if !d.HasChange("members") {
		return nil
	}
        old, new := d.Change("members")
        ...
```
