### ISSUE TITLE
"Diffs didn't match during apply" while setting up simple S3 website 

### ISSUE THREAD

**Issue by josh-padnick** [hashicorp/terraform#8914]
### Terraform Version

Terraform Version: 0.7.3
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_s3_bucket
- template_file
- aws_s3_bucket_object
### Terraform Configuration Files

``` hcl
provider "aws" {
  # The AWS region in which all resources will be created
  region = "${var.aws_region}"

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["${var.aws_account_ids}"]
}

resource "aws_s3_bucket" "webform" {
    bucket = "${var.website_domain_name}"
    acl = "public-read"
    policy = "${data.template_file.s3_bucket_policy.rendered}"

    # Configure S3 Static Website Hosting options
    website {
        index_document = "index.html"
        error_document = "error.html" 
    }

    versioning {
      enabled = true
    }
}

data "template_file" "s3_bucket_policy" {
    template = <<-EOF
    {
        "Version":"2012-10-17",
        "Statement":[{
            "Sid":"PublicReadGetObject",
            "Effect":"Allow",
            "Principal": "*",
            "Action":["s3:GetObject"],
            "Resource":["arn:aws:s3:::${website_domain_name}/*"]
        }]
    }
    EOF

    vars {
        website_domain_name = "${var.website_domain_name}"
    }
}

resource "aws_s3_bucket_object" "index" {
    bucket = "${aws_s3_bucket.webform.id}"
    key = "index.html"
    source = "${path.module}/web/index.html"
    etag = "${md5(file("${path.module}/web/index.html"))}"
    content_type = "text/html"
}
```
### Debug Output

https://gist.github.com/josh-padnick/a9fe0e1a8eaee550e507c6d1bd1bdae5
### Panic Output

N/A
### Expected Behavior

For the initial run, `terraform apply` worked fine. When I changed the content of the file at `file("${path.module}/web/index.html")`, terraform should have just uploaded the new file to S3.
### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.webform: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.3
    Resource ID: aws_s3_bucket.webform
    Mismatch reason: attribute mismatch: policy
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"policy":*terraform.ResourceAttrDiff{Old:"{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"arn:aws:s3:::payments.gruntwork-dev.io/*\",\"Sid\":\"PublicReadGetObject\"}],\"Version\":\"2012-10-17\"}", New:"${data.template_file.s3_bucket_policy.rendered}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```
### Steps to Reproduce
1. Create a file at the path `file("${path.module}/web/index.html")`.
2. Now `terraform apply` the above HCL. It should work as expected.
3. Change the contents of `index.html` file.
4. Run `terraform apply` again. You should receive diffs didn't apply.
### Important Factoids

Nothing unusual. Pretty straightforward setup.

**Comment by josh-padnick** [comment]
It appears that removing the `data.template_file.s3_bucket_policy` resource and instead just inlining the S3 Bucket Policy fixes the issue for me.

**Comment by jen20** [comment]
Hi @josh-padnick! Thanks for opening an issue. I'll investigate this, but you might also want to look into using an `aws_iam_policy_document` data source and an `aws_s3_bucket_policy` resource in this case.

**Comment by josh-padnick** [comment]
@jen20 That's a good point. I use `data.aws_iam_policy_document` all the time for IAM Policies but didn't consider it for S3 Bucket Policies! Didn't realize `aws_s3_bucket_policy` was a separate resource, too.

**Comment by mitchellh** [comment]
Just tested this in the latest version 0.7.11 with your fantastic repro case and everything worked!
