### ISSUE TITLE
provider/fastly: service_v1 gets updated every time even when attributes didn't change

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#8916]
Fastly Service gets updated every time when there is no change. For example, if you see the plan output below, 

``` shell
~ fastly_service_v1.test
    vcl.1103040989.content: "" => "1c5d0570f4f719a5dd0e54c638dcb5f947ee5463"
    vcl.1103040989.main:    "" => "true"
    vcl.1103040989.name:    "" => "Test"
    vcl.1605458872.content: "sub vcl_recv {\n#FASTLY recv\n\n  ... n\nsub vcl_pass {\n#FASTLY pass\n}\n" => ""
    vcl.1605458872.main:    "true" => "false"
    vcl.1605458872.name:    "Test" => ""
```

You can notice some odds, including:
- Previous VCL's `main` attribute changes to false, but the new VCL's `main` attribute changes to true again
- Previous VCL's `content` attribute is displayed in string format, but the new VCL's `content` attribute is displayed in hash-like format, making a plan hard to read (especially if you have multiple VCL files) 
### Environment information

Terraform Version: 0.7.2 (also tested on 0.7.0)
Affected Resources: fastly/service_v1
### Terraform configuration

``` hcl
resource "fastly_service_v1" "test" {
  name = "test"
  default_ttl = 0

  domain {
    ..
  }

  backend {
    ..
  }

  vcl {
    name = "Test"
    content = "${file("fastly/test.vcl")}"
    main = true
  }
}
```

**Comment by hc2p** [comment]
this seems to be a general problem. Happens for me on the `domain` set as well.

**Comment by zimbatm** [comment]
Can you try https://github.com/hashicorp/terraform/pull/9629 to see if it fixes your issue?

**Comment by premist** [comment]
Hi @zimbatm, I'll try out #9629 sometime this week and will let you know if it works.

**Comment by premist** [comment]
Seems like it doesn't work for me - I have `terraform-provider-fastly` in my PATH and using terraform v0.7.9. Tried altering header/vcl and it still returns result I described above in this issue.

**Comment by catsby** [comment]
Hello – 
I'm unable to reproduce the problem at this time, can anyone follow up with a configuration that demonstrates this?

**Comment by premist** [comment]
Hi @catsby, I had a chance to test this against the latest version of Terraform (v0.9.1). Seems like Terraform understands VCL is unchaged, which is good! I found another bug where Fastly provider doesn't update `default_ttl` accordingly, but it's separate from this issue so I created another one separately (#12910).

**Comment by catsby** [comment]
Thanks for the follow up and other issue, @premist
