### ISSUE TITLE
destroy fails if have empty state and invoking a module 

### ISSUE THREAD

**Issue by esword** [hashicorp/terraform#8918]
### Terraform Version
0.7.3

### Affected Resource(s)
module invocation when passing a variable. 

### Terraform Configuration Files
This originally happened with my real module and configuration, but I reproduced it with this much simplified config.

main.tf
```hcl

resource "random_id" "n2" {
  keepers {fixed="fixed"}
  byte_length = 8
}

//This fails if you call terraform plan -destroy=true with no statefile
module "something" {
  source = "modA"

  "passed_id" = "${random_id.n2.id}"
}
```

Module TF:
```hcl

resource "random_id" "sub" {
  keepers {fixed="fixed"}
  byte_length = 8
}

variable "passed_id" {
}
```

### Debug Output
https://gist.github.com/esword/efa2a7f65ea8f38e1a9e85e7f4f53e5c

### Panic Output
None

### Expected Behavior
Terraform should have taken no action or reported that there was nothing to destroy.

### Actual Behavior
What actually happened?

Error creating plan: 1 error(s) occurred:

2016/09/19 14:48:57 [DEBUG] plugin: waiting for all plugin processes to complete...
* variable "n2" is nil, but no error was reported

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy` with no state file or with a state file that contains no resources.  e.g. if you run destroy twice.

### Important Factoids
This may seem like a minor issue, but it directly impacts our CI system.  We're trying to use test-kitchen with this new [terraform plugin](https://github.com/newcontext/kitchen-terraform) and the normal procedures for tests is to call destroy first for each test run.

**Comment by chadgrant** [comment]
ugh, hit me too

**Comment by mitchellh** [comment]
Just tested this with the new destroy graph that we have coming in Terraform 0.8 and this is fixed. You can get this starting in the next version of Terraform by running destroy with the `-Xnew-destroy` flag. This will be on by default in Terraform 0.8.
