### ISSUE TITLE
aws_elb_attachment documentation error

### ISSUE THREAD

**Issue by rkulagowski** [hashicorp/terraform#8919]
Version: Terraform v0.7.3 running on Ubuntu

[https://www.terraform.io/docs/providers/aws/r/elb_attachment.html](url)

The example provided is:
```
# Create a new load balancer attachment
resource "aws_elb_attachment" "baz" {
  elb      = "${aws_elb.bar.id}"
  instance = ["${aws_instance.foo.id}"]
}
```

However, the instance needs to be specified directly; it's not a list parameter, so terraform throws an error:

```
* aws_elb_attachment.foo-instances-web02: instance must be a single value, not a list
```

Removing the brackets around 
```
["${aws_instance.foo.id}"]
```

Allows the resource to be created.

**Comment by jen20** [comment]
Fixed by #8845 (and now deployed to the website I believe). Thanks for opening an issue @rkulagowski!
