### ISSUE TITLE
Volume size is ignored if specified using a variable

### ISSUE THREAD

**Issue by j16r** [hashicorp/terraform#8920]
### Terraform Version
Terraform v0.7.3

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "test" {
  ami = "ami-2d39803a"
  count = 1
  instance_type = "t2.micro"
  key_name = "redacted"

  root_block_device {
    volume_size = "${volume_size}"
  }
}
```

### Debug Output
```
   root_block_device.~0.volume_size:           "0"
```

### Expected Behavior
I would expect the volume size to be 1000.

### Actual Behavior
The volume size I specified was ignored. This happens in both plan and apply modes.

### Steps to Reproduce
Specified the volume_size a number of different ways, including:
- `terraform plan -var volume_size=1000 .`
- `terraform plan -var 'volume_size="1000"' .`

### References
This seems related to the following issue, note that I originally had some difficulty trying to specify the volume size via a variable due to this bug:
- GH-7962

**Comment by jen20** [comment]
Hi @j16r! Thanks for opening an issue. This is actually a combination of two things - the quick fix is to refer to the variable correctly - you need `${var.volume_size}` as the value. The second is the lack of good error message - this is something that @mitchellh was working on recently, but also seems to be related to #8234. I'll leave this open until we get a resolution to that, but adding in the missing `var` prefix to your variable should resolve your immediate problem.

**Comment by mitchellh** [comment]
Yes this is all fixed up and ready to go but the fix requires breaking BC with the `template` resource so its staged until 0.8. See #8010
