### ISSUE TITLE
terraform input does not respect region defaults

### ISSUE THREAD

**Issue by tomkoufakis** [hashicorp/terraform#8926]
Hi there,
### Terraform Version

0.7.4
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_db_instance
### Terraform Configuration Files

``` hcl

```
### Debug Output

https://gist.github.com/tomkoufakis/159674836859f70882c457ed85118532
### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
### Expected Behavior

The import should have occurred using the us-west-2 region 
### Actual Behavior

The import occurred using the us-east-1 region (default)
### Steps to Reproduce
1. Set one of:
   export TF_VAR_region="us-west-2"
   export AWS_DEFAULT_REGION="us-west-2"
   export AWS_REGION="us-west-2"
2. Call terraform import -no-color -input=false -backup=- aws_db_instance.retcon-sql1-ex retcon-sql1-ex

**Comment by endofcake** [comment]
I can confirm this still happens in  v0.8.1.
