### ISSUE TITLE
aws_security_group: conflicting ingress block definitions

### ISSUE THREAD

**Issue by imkira** [hashicorp/terraform#893]
Hi there.

I am using Terraform v0.3.6 and I have just noticed that if I have say 2 block definitions like the following:

```
    ingress {
        from_port = 8000
        to_port = 8000
        protocol = "tcp"
        security_groups = ["${var.group_id}"]
    }
    ingress {
        from_port = 8000
        to_port = 8000
        protocol = "tcp"
        self = true
    }
```

It creates the security group as expected on the first ```apply```.
Then, for my surprise, ```plan``` tells me here are changes. That instead of having 2 ingress rules that I only have 1 (when in fact according to AWS console there is actually 2) :

```
~ aws_security_group.server
    ingress.#:                                    "1" => "2"
```

Then if I try applying it it explodes saying it can't create a new ingress rule because of a ```InvalidPermission.Duplicate``` (yes, because it already exists and the plan was wrong in the first place).

I bang my head for about half an hour just to notice that the problem was because terraform seems to group ingress rules according to their definitions so, since the rules look the same, and since "self" is just "sugar" it seems to be breaking somewhere.
I was able to fix this by using a single ingress rule with both ```security_groups``` and ```self``` in the same block:

```
    ingress {
        from_port = 8000
        to_port = 8000
        protocol = "tcp"
        security_groups = ["${var.group_id}"]
        self = true
    }
```

I believe one of the two following things should be done:

- sanity check preventing the user to create define such blocks
-  to be able to "pick up" ingress blocks and "merge" them as necessary

I don't care about the first one, as long as the error is easy to understand.

**Comment by pmoust** [comment]
@imkira it's being thoroughly discussed in https://github.com/hashicorp/terraform/issues/670

**Comment by imkira** [comment]
Thanks a lot @pmoust 
Closing and referencing from there.
