### ISSUE TITLE
Azure CreateOrUpdate failing due to Updating State (subnets & security groups)

### ISSUE THREAD

**Issue by rjinski** [hashicorp/terraform#8931]
### Terraform Version

`Terraform v0.7.3`
### Affected Resource(s)
- azurerm_subnet
- azurerm_network_security_group
- **azurerm_network_security_rule**
### Terraform Configuration Files

[configuration](https://gist.github.com/rjinski/0897fd7bcd387ec8a418a057560cc46b)
### Debug Output

[debug](https://gist.github.com/rjinski/9992a91b065b5528cf7d6a29eeb0a21a)
### Expected Behavior

A successful build
### Actual Behavior

Race conditions. Terraform is attempting to update a resource that is currently _locked_. Re-running `terraform apply` provides a successful execution.
### Steps to Reproduce
- `terraform apply`
- wait for error
- `terraform apply`

Thank you

**Comment by rjinski** [comment]
A fix for this seems to be to chain the `azurerm_network_security_rule ` with `depends_on` to stop them updating the `azurerm_network_security_group` in parallel.

**Comment by jen20** [comment]
Hi @rjinski, thanks for the analysis and report! This is not easy to fix - Terraform does not have the concept of implicit dependencies in this manner, so we can't build them in automatically. However, we could catch the locked status and retry if it is detectable.

**Comment by rjinski** [comment]
The work around didn't actually work around :(

It seems as thought it depends how quick Azure updates the status depends on the chance of success or not. Manually adding a creation order still results in possible "RetryableError". This isn't isolated to only security rules either. Routing rules seem to be showing a similar behaviour.

**Comment by tombuildsstuff** [comment]
Hi @rjinski 

Thanks for reporting this issue - apologies for the delay in getting back to you here!

Using [the Terraform config posted above](https://gist.github.com/rjinski/0897fd7bcd387ec8a418a057560cc46b) I'm able to replicate this bug using Terraform 0.9.3. Once retrying using the master branch, where PR #13637 has been merged in - I'm now unable to replicate this issue, and so I believe this has been fixed.

As such I'm going to close this issue :)

Thanks!
