### ISSUE TITLE
Feature Request: RDS MSSQL Time Zone Support

### ISSUE THREAD

**Issue by bmurtagh** [hashicorp/terraform#8937]
Today AWS released the ability to specify a timezone for a MSSQL RDS instance [Amazon RDS for SQL Server now supports Local Time Zone](https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-rds-sql-server-supports-local-time-zone/).

I'd like to request that this feature request be reviewed for addition to Terraform. 

Thank you in advance.

**Comment by bmurtagh** [comment]
Just wanted to update this FR with info from the AWS Go SDK team. 

I opened https://github.com/aws/aws-sdk-go/issues/844 this morning with the AWS Go SDK who completed work on updating the service models in the SDK.

**Comment by catsby** [comment]
I added this in #11247, thanks!
