### ISSUE TITLE
Google Provider does not support us-central1 for google sql database instances

### ISSUE THREAD

**Issue by ctaymor** [hashicorp/terraform#8942]
### Terraform Version
v0.7.5-dev

### Affected Resource(s)
Please list the resources as a list, for example:
- google_sql_database_instance

### Terraform Configuration Files

```hcl
variable "region" {
  type = "string"
  default = "us-central1"
}

variable "google_sql_db_tier" {
  type = "string"
  default = "db-f1-micro"
}

variable "create_google_sql" {
  type = "string"
  default = "0"
}

 resource "google_sql_database_instance" "master" {
  region = "${var.region}"
  settings {
    tier = "${var.google_sql_db_tier}"
   }

  count = "${var.create_google_sql}"
}
```

```tfvars
region = "us-central1"
google_sql_db_tier = "D0"
create_google_sql = "1"
```

### Debug Output
https://gist.github.com/ctaymor/5404f6dd2082f2c01ff40af0ce4baa7e

### Expected Behavior
It should have succeeded in creating the google sql database instance.

### Actual Behavior
Terraform failed to bring up the google sql db instance.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Other information
This worked successfully when setting the region to `us-east1`.

**Comment by ctaymor** [comment]
Looks like this works when using `us-central`. It would be great for it to match the cloudsql docs here: https://cloud.google.com/sql/docs/instance-locations and work with `us-central1`.

**Comment by evandbrown** [comment]
Thanks for reporting this @ctaymor. I've pinged our docs team to update their page. `us-central` (no prefix) is the correct region for "first generation" CloudSQL instances, which is what Terraform supports. Second generation instance types use the suffixed region name.

I'll file a separate issue to support 2nd gen instances shortly...
