### ISSUE TITLE
vSphere/VM resource: Destroy will delete unmanaged disks with VM

### ISSUE THREAD

**Issue by dagnello** [hashicorp/terraform#8945]
After a VM is created with Terraform, if a user adds additional disk devices to VM, then performs a terraform destroy, the VM and these additional disks will be deleted together.  Depending on the deployment and expectations, this might not be desired.  Resources (in this case disks) not managed by TF, should not be deleted with a TF destroy.  Since this is an inherent functionality within vSphere, these additional disks would have to be detached prior to deleting VM.

**Comment by stack72** [comment]
Closed via #8947
