### ISSUE TITLE
Feature request: nomad provider

### ISSUE THREAD

**Issue by omame** [hashicorp/terraform#8952]
Are there any plans to have a nomad provider for terraform?
What I have in mind is the ability to schedule jobs in nomad using terraform.

**Comment by apparentlymart** [comment]
I can't speak to Hashicorp's plans, but I can say that *I* am very interested in this and will probably end up writing one if they don't. :grinning:

My proposal in #8769 is largely motivated by having first-class support for Nomad's planning mechanism in Terraform, so Terraform can give the user all the same information that Nomad itself does.

**Comment by ketzacoatl** [comment]
Note the related thread in #4442, along with the associated WIP PR (https://github.com/hashicorp/terraform/pull/8662) - is this a duplicate, or does it differ from what we've got rolling in #4442?

**Comment by apparentlymart** [comment]
There is Nomad provider code sitting in #9538. I can't speak to @mitchellh's plans here but it seems to be basically complete for a first version. What I proposed in #8769 could be added later, so isn't a blocker here.

**Comment by mitchellh** [comment]
Done! Will be in 0.8, the beta is starting tomorrow most likely.
