### ISSUE TITLE
Support aws autoscaling group suspended_processes attribute

### ISSUE THREAD

**Issue by zihaoyu** [hashicorp/terraform#8954]
### Terraform Version

0.7.3
### Affected Resource(s)
- aws_autoscaling_group

I'd like to have `suspended_processes` support for AWS autoscaling group resources. Currently it seems like there is no support for such configuration.

**Comment by stack72** [comment]
Hi @zihaoyu 

I have opened PR #10096 to add support for this - keep an eye on that PR for any issues :)

Paul
