### ISSUE TITLE
Complications using Auto Scaling Lifecycle Hooks to establish Auto Scaling Group instance health

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/terraform#8957]
I want to be able to do the following:
- Create an AWS EC2 Auto Scaling Group
- Immediately associate a `autoscaling:EC2_INSTANCE_LAUNCHING` lifecycle hook with the Auto Scaling Group, thereby putting all new instances in `Pending:Wait` state until a `CONTINUE` result is dispatched [1]
- Provision each instance using an EC2 user data script
- As the last step in the provisioner, upon otherwise successful completion, dispatch a lifecycle notification [2] against the (ASG, instance) tuple with a `CONTINUE` result, thereby changing the instance's state from `Pending:Wait` to `InService`, indicating the instance is "healthy"
- Have Terraform continue provisioning IFF the minimum number of instances are "healthy"

However, this is not currently possible:

When you create an `aws_autoscaling_lifecycle_hook` resource in Terraform whose `autoscaling_group_name` attribute refers to the `name` attribute of an associated `aws_autoscaling_group` (ASG) resource, an implicit dependency of the former upon the latter is created.   For example:

```
# my_asg implicitly depends on a my_asg_launch_config
resource "aws_autoscaling_group" "my_asg" {
  launch_configuration = "${aws_launch_configuration.my_asg_launch_config.name}"
  min_size = 2
  max_size = 100
  wait_for_capacity_timeout = "30m"
}

# my_asg_hook implicitly depends on my_asg
resource "aws_autoscaling_lifecycle_hook" "my_asg_hook" {
  name = "KeymasterAutoScalingLaunchHook"
  autoscaling_group_name = "${aws_autoscaling_group.my_asg.name}"
  lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"
}
```

This dependency correctly establishes the order of operations: the ASG must be created so that its name can be evaluated and used as an attribute of the lifecycle hook.

By default, when you apply a template containing an ASG with Terraform, setting a minimum size (via `min_size`) or desired capacity (`desired_capacity`) attribute causes Terraform to wait for the the Auto Scaler to report that the minimum number of instances is healthy (unless you also set `wait_for_capacity_timeout` to 0).  The creation of any dependent resources will be blocked, including any lifecycle hook resources such as the one declared in the example above.

This presents a quandary if you want to use a lifecycle hook to establish instance readiness.  

For a lifecycle hook to be effective, it must be created before the ASG launches any instances (or at least before they exit the `Pending` state).  But due to Terraform's blocking behavior, the above configuration will cause the lifecycle hook to be created too late: Terraform will wait until the Auto Scaler has launched the minimum number of instances and they have transitioned to `InService` state.  Then -- and only then -- will Terraform create the lifecycle hook resource.  But it will not be effective until the Auto Scaler launches additional resources (or terminates existing ones), and any instances created will be assumed by "healthy" by Terraform, even if the provisioning script concludes otherwise.

One can, of course, set `wait_for_capacity_timeout = 0` in the `aws_autoscaling_group` resource declaration, in which case Terraform will create the `aws_autoscaling_lifecycle_hook` resource as soon as the ASG's name can be determined.  But this means that you cannot extrapolate from the resource's successful creation that any healthy instances were created.

References: 

[1] http://docs.aws.amazon.com/autoscaling/latest/userguide/AutoScalingGroupLifecycle.html
[2] http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CompleteLifecycleAction.html

**Comment by vancluever** [comment]
Looks like this is available! 

https://github.com/hashicorp/terraform/commit/7dd7078b826635ea7aee99bb90654ec970e74948

It just needs documenting. I'll do the needful.
