### ISSUE TITLE
Add separated resource for configuring S3 bucket lifecycle rules 

### ISSUE THREAD

**Issue by pabloajz** [hashicorp/terraform#8961]
Add a separate resource aws_s3_bucket_lifecycle_rule for supporting lifecycle rules (http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) 

**Current situation**

Lifecycle rules can be defined only inline in the aws_s3_bucket resource, but not as external resources than can be attached to the S3 bucket afterwards

**Use Case**

I have one S3 bucket containing Logs organised into different keys. Each key is generated by other components (different Log Groups for example). I want to setup different lifecycle rules for each Log Group (Key) when they are created, and they are created dynamically after the S3 bucket is created.

**Comment by hanks** [comment]
this feature is good, my scenario is that I use bucket with module. And I want to add different number of lifecycle rules to different bucket resources with the same module. But now lifecycle can only be set in resource body. I need to create different modules just for the lifecyle rules.

**Comment by bdashrad** [comment]
This would be so useful, along with the ability to define CORS, replication, and website rules in a separate resources. This would allow us to have much simpler modules for creating different s3 buckets.
