### ISSUE TITLE
Terraform 0.7.4 fails to read AWS key

### ISSUE THREAD

**Issue by lexsys27** [hashicorp/terraform#8963]
### Terraform Version
0.7.4
In version 0.7.0 works fine. The key is valid - I can connect to EC2 instance using this key.

### Affected Resource(s)

- aws_instance

### Terraform Configuration Files

```hcl
connection {
      user = "ubuntu"
      key_file = "~/.ssh/lx-eu-west-1.pem"
}
```

### Expected Behavior
I create AWS key pair and pass it terraform remote provisioner. I expect provisioner to login to the AWS instance and run commands. 

### Actual Behavior
I get an error

```
* Failed to read key "~/.ssh/lx-eu-west-1.pem": no key found
```

### Steps to Reproduce

1.  Create new AWS EC2 key pair
2. Create config file with remote provisioner
2. `terraform apply`

**Comment by brucemartins** [comment]
I see the same thing with openstack when using file provisioner "uploading file" so not specific to aws or openstack I dont believe

**Comment by mootpt** [comment]
`key_file` has been deprecated. https://www.terraform.io/docs/provisioners/connection.html#key_file

You should use https://www.terraform.io/docs/provisioners/connection.html#private_key with file() interpolation going forward.

Here is the relevant commit: https://github.com/hashicorp/terraform/commit/7ffa66d1a536428dcdf16e68c32ff7ca2b83674a

**Comment by mootpt** [comment]
Given your example, this would be something like: `private_key = "${file("~/.ssh/lx-eu-west-1.pem")}"`

**Comment by lexsys27** [comment]
Thank you for help!

**Comment by spanktar** [comment]
Maybe this should be added to https://www.terraform.io/upgrade-guides/0-7.html

**Comment by janfabry** [comment]
The `key_file` is not just deprecated, it doesn't work anymore at all ([because `pathorcontents.Read` isn't applied anymore](https://github.com/hashicorp/terraform/commit/968472a63e4542a2c5e2693c4489da4776dac996#diff-d1b9df521bc0abcc44e4d3cefd5414b7)). The docs say it "may be removed in a future version", which leaves the impression that it might still work.

**Comment by mmell** [comment]
At some point (< 0.7.4?) this stopped working

    private_key = "${"~/.ssh/lx-eu-west-1.pem"}"

With `v0.7.4`, as @mootpt says, it must read the file:

    private_key = "${file("~/.ssh/lx-eu-west-1.pem")}"

**Comment by murphy7801** [comment]
Same issue as above aswell

**Comment by sanster23** [comment]
Hi, 
Please have a look at this issue https://github.com/Shippable/support/issues/4497 
I am using terraform ~ 0.11.7 
but still i get the same error 
* Failed to read key "~/.ssh/lx-eu-west-1.pem": no key found
