### ISSUE TITLE
provider/openstack: feature-request: user/tenant management 

### ISSUE THREAD

**Issue by vmindru** [hashicorp/terraform#8964]
Hi there,

I am missing openstack user/tenant provisioning.

VM

**Comment by vmindru** [comment]
can we get some priority hear please

**Comment by jtopjian** [comment]
@vmindru I apologize for the delay on this - I could have done a better job explaining the situation in this Issue.

[Gophercloud](https://github.com/gophercloud/gophercloud) (the underlying Go library that Terraform uses for OpenStack) did not support management of tenants or users when you first requested this. I began working on tenant support in October and was just added to Gophercloud [two weeks ago](https://github.com/gophercloud/gophercloud/tree/master/openstack/identity/v3/projects). Now user support needs to be added, which I might be able to get to in the coming weeks.

Again, I apologize for the delay - no doubt this is frustrating on your part. However, please keep in mind that the OpenStack provider is community maintained. I'm personally only able to work on both Terraform and Gophercloud in my spare time. I'm more than happy to provide guidance and answer any questions for others who would like to contribute code to move things along faster. :)

**Comment by vmindru** [comment]
@jtopjian thank you for time for this answer. I guess I will have to try to learn  go and attempt to contribute and help writing this and try to get a PR in place.

**Comment by jtopjian** [comment]
@vmindru Just a quick update on this: I have begun work on Keystone User support in Gophercloud. Creating Terraform resources for Keystone Projects is on my list of things to do soon. :)

**Comment by vmindru** [comment]
@jtopjian  yo :) how is it going? I hope you are doing well. Did you have a chance to push this one forward?

**Comment by jtopjian** [comment]
@vmindru I'm still working on getting user support into Gophercloud. Project support still needs to be added to Terraform, though. The past few weeks have been fixing bugs, which is the first priority, and reviewing submitted features. Sorry again for the delay on this.
