### ISSUE TITLE
provider/openstack: feature-request: image management

### ISSUE THREAD

**Issue by vmindru** [hashicorp/terraform#8965]
Hi there,

i am missing openstack image management ( this might end up as separate glance provider ) 

VM

**Comment by jtopjian** [comment]
@vmindru Glance resources should work correctly under the current OpenStack provider. The limiting factor at the moment is getting glance/image support into Gophercloud. 

But definitely something worthwhile to have! Thanks for reporting it :)

**Comment by vmindru** [comment]
bump

**Comment by vmindru** [comment]
I guess the reply to this would be same as for  https://github.com/hashicorp/terraform/issues/8964, have this been added to Gophercloud?

**Comment by jtopjian** [comment]
Yes! Image Support was added [three months ago](https://github.com/gophercloud/gophercloud/tree/master/openstack/imageservice/v2) and this has been on my short-list of features to get to. Again, I apologize for not doing a better job keeping this updated.

**Comment by jtopjian** [comment]
`openstack_images_image_v2` was just added in #11942. It will be available in both the next 0.8 and 0.9-rc release. :)

**Comment by vmindru** [comment]
w000t!!!!!
