### ISSUE TITLE
librato_alert cannot be modified

### ISSUE THREAD

**Issue by jonleighton** [hashicorp/terraform#8966]
When I modify a `librato_alert` and run `terraform apply`, an invalid request is made to the Librato Metrics API, so the modification fails.

### Terraform Version
0.7.4

### Affected Resource(s)
librato_alert

### Terraform Configuration Files

```hcl
variable "librato_email" {}
variable "librato_token" {}

provider "librato" {
  email = "${var.librato_email}"
  token = "${var.librato_token}"
}

resource "librato_service" "default" {
  title = "Email"
  type = "mail"
  settings = <<SETTINGS
{
  "addresses": "nobody@example.com"
}
SETTINGS
}

resource "librato_alert" "default" {
  name = "test"
  description = "A Test Alert"
  services = [ "${librato_service.default.id}" ]

  condition {
    type = "above"
    threshold = 10
    metric_name = "test"
  }
}
```

### Debug Output
https://gist.github.com/jonleighton/3b263e77864e0dd70f8860723c6e1887

### Expected Behavior
The alert is modified.

### Actual Behavior
The Librato API rejected the `PUT` request which Terraform made:

```
* librato_alert.default: Error updating Librato alert: PUT https://metrics-api.librato.com/v1/alerts/6469005: 400  Parameter errors: name: is not present, is invalid,.
```

### Steps to Reproduce
1. Create a Librato Metrics account and make a note of the email and API token
2. Run `curl -u '<email>:<token>' -d 'gauges[0][name]=test' -d 'gauges[0][value]=60' -X POST https://metrics-api.librato.com/v1/metrics` to create a metric
3. Create the resources: `terraform apply -var 'librato_email=<email>' -var 'librato_token=<token>'`
4. Modify the `librato_alert` `description` field
5. Run `terraform apply -var 'librato_email=<email>` again

### Important Factoids
None

### References
- https://github.com/hashicorp/terraform/pull/8170

**Comment by elblivion** [comment]
The test case only changes `name` which is always required on changes :facepalm:. Reading the API docs more closely the `conditions` are also obligatory on an update.

**Comment by elblivion** [comment]
I've got a fix for this, will open a PR shortly.
