### ISSUE TITLE
CloudFront distribution changes fail with "HttpVersion is missing for the resource" with v0.7.4

### ISSUE THREAD

**Issue by tmatilai** [hashicorp/terraform#8967]
### Summary

Creating a CloudFront distribution works, but changes to it (or to a distribution created with earlier Terraform version) fail:

> Error applying plan:
>
> 1 error(s) occurred:
>
> \* aws_cloudfront_distribution.cf: IllegalUpdate: HttpVersion is missing for the resource
>        status code: 400, request id: xxx

### Terraform Version

Terraform v0.7.4 (0.7.3 works fine)

### Affected Resource(s)

- aws_cloudfront_distribution

### References
- GH-8877 (updated the AWS library)
- GH-8777 (might fix this, didn't test)

**Comment by danielnbarbosa** [comment]
I"m also seeing this.  Happens with deletes and changes to cloudfront distributions.

**Comment by tomgoren** [comment]
Just started happening to me as well.

**Comment by AirbornePorcine** [comment]
Seeing this as well for any deletes or changes.

**Comment by giladwolff** [comment]
Happens to me as well.

**Comment by jswierad** [comment]
+1, same here.

**Comment by rfink** [comment]
Same problem, on update / delete.

**Comment by stack72** [comment]
Hi all

I am currently looking into this now

Paul

**Comment by stack72** [comment]
Closed via #8777

**Comment by mattfysh** [comment]
qq - if this issue prevents updates to other resources, how can I temporarily disable the cf distro? thanks!

**Comment by stack72** [comment]
Hi @mattyfish

Not sure what you mean - I think you mean that if this is causing you issues before this gets patched in 0.7.5, can you disable the resource from Terraform - correct?

If this is the case, you would have to remove the resource from the terraform.tfstate file - you'd then need to remember to readd it when 0.7.5 hits

Paul

**Comment by rfink** [comment]
Is there a timeline for the 0.7.5 release by any chance?

**Comment by stack72** [comment]
@rfink not quite - soon™️  :)
