### ISSUE TITLE
librato_alert doesn't create a condition with a duration

### ISSUE THREAD

**Issue by jonleighton** [hashicorp/terraform#8968]
When I use a `duration` in a `condition` block in a `librato_alert`, the duration is not set during the creation of the alert. A subsequent `terraform apply` attempts to set the duration, but this also fails due to #8966.

### Terraform Version
0.7.4

### Affected Resource(s)
librato_alert

### Terraform Configuration Files
``` hcf
variable "librato_email" {}
variable "librato_token" {}

provider "librato" {
  email = "${var.librato_email}"
  token = "${var.librato_token}"
}

resource "librato_service" "default" {
  title = "Email"
  type = "mail"
  settings = <<SETTINGS
{
  "addresses": "nobody@example.com"
}
SETTINGS
}

resource "librato_alert" "default" {
  name = "test"
  description = "A Test Alert"
  services = [ "${librato_service.default.id}" ]

  condition {
    type = "above"
    threshold = 10
    metric_name = "test"
    duration = 60
  }
}
```

### Debug Output
https://gist.github.com/jonleighton/b82e81e6ba92ffb80b5418cf247cce58

### Expected Behavior
The alert's condition should have been created with a duration.

### Actual Behavior
The alert's condition was created to trigger immediately.

### Steps to Reproduce
1. Create a Librato Metrics account and make a note of the email and API token
2. Run `curl -u '<email>:<token>' -d 'gauges[0][name]=test' -d 'gauges[0][value]=60' -X POST https://metrics-api.librato.com/v1/metrics` to create a metric
3. `terraform apply -var 'librato_email=<email>' -var 'librato_token=<token>'`

Now observe in Librato Metrics that the alert condition doesn't have the duration specified.

A subsequent `terraform apply` will detect this, and try to modify the alert. However this will also fail, due to #8966.

### References
- #8966
- #8170

**Comment by elblivion** [comment]
Very odd. I reproduced also by adding a `duration` to the test condition at https://github.com/hashicorp/terraform/blob/master/builtin/providers/librato/resource_librato_alert_test.go#L181. Doesn't seem to happen for a `summary_function`, will investigate when I have time.
