### ISSUE TITLE
docker_container's ip_address is empty when using network_mode

### ISSUE THREAD

**Issue by rkr-kununu** [hashicorp/terraform#8972]
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- docker_container
### Terraform Configuration Files

``` hcl

resource "docker_network" "network" {
  name = "demo"
}

resource "docker_image" "image" {
  name = "gliderlabs/alpine:latest"
  keep_locally = true
}

resource "docker_container" "container" {
  name = "demo-container"

  image = "${docker_image.image.name}"

  network_mode = "${docker_network.network.name}"

  command = [ "sleep", "356d" ]
}

output "ip_address" {
  value = "${docker_container.container.ip_address}"
}
```
### Expected Behavior

I expected that 'ip_address' would be set to ip_address of the docker container.
### Actual Behavior

The 'ip_address' was not set.
### Important Factoids

I did some poking around the code.  It appears that the problem is two-fold.
1. Running docker-inspect on the running container also shows that 'IPAddress' is also empty.
2. However, docker-inspect also shows that the "Networks" map also contains all the relevant information (ip address, gateways for _each_ network the container is running in).  It also appears that the go-dockerclient terraform's using is parsing this information (see NetworkSettings->Networks).  My hope is that this "Network" map can be exposed as part of docker_container's output.

**Comment by mavogel** [comment]
@rkr-kununu you can take a look at the fix in https://github.com/terraform-providers/terraform-provider-docker/issues/9#issuecomment-431379195 if you like. I write there because if I tag you in the other issue you won't be notified. (Had that in the past 🤔 )
