### ISSUE TITLE
Support for Amazon DMS (Database Migration Service)

### ISSUE THREAD

**Issue by orlando** [hashicorp/terraform#8973]
DMS support would be cool, it's something that we are using at the moment, but had to do it manually because looks like there's no support for it.

Happy to help to get a base implementation if this something you guys want to merge.
### Terraform Version

0.7.4
### Expected Behavior
- Support DMS
### Actual Behavior
- Looks like this is something we don't support right now
### Important Factoids
- Looks like this is supported by the [aws-sdk-go](https://github.com/aws/aws-sdk-go)

**Comment by kurtmaile** [comment]
Is this now supported or on the roadmap?  We too would love this to be supported by terraform (soon!) :)

**Comment by orlando** [comment]
@kurtmaile this is something I was about to implement, but then DMS didn't work out for us. We choose another route and now we are not using it.

Looks like this is something that is going to be useful for other people, so feel free to submit a PR

**Comment by kurtmaile** [comment]
@orlando sorry to hear it didnt work out for you hope someone else at picks this up as we are finding good success with the tool.  Any reason with the tool you changed directions FYI?  Or just went for a a differernt pattern?  Our use case is geared to the on-going replication of data / events we consume in aurora as the DMS target and then republish to lambda via the aurora SP interface to be handled in a variety of ways.  We have a large legacy DB that is the heart of the business, which wont be going away anytime soon, so this is the best way now to start tapping this data / change stream while other more long term solutions are introduced.  Would be good to hear you thoughts based on your experiences - good and bad.  Cheers!

**Comment by orlando** [comment]
@kurtmaile your use case sounds good. I was trying to use DMS to create a data warehouse for analytics from multiple microservices, but the connection got stuck after being idle for some time (around 3 hours). This was a postgres to postgres replication. When this happens, postgres keeps storing WALs until the disk is full, which was a huge problem for us.

Here's the support entry https://forums.aws.amazon.com/message.jspa?messageID=743515#743515

Also, AWS support (even when we had business plan), wasn't of much help.

**Comment by jamesbrown7** [comment]
+1 on DMS support.

Another use case for your list: we intend to use it for Disaster Recovery. We're using Terraform to replicate all the rest of our infrastructure resources, including RDS, S3, EC2, IAM, and SGs. Using Terraform in this case not only allows us better control over our infrastructure, but allows us to much more easily create new replicas of our source environments.

**Comment by kurtmaile** [comment]
Need to get this more of a priority, seems its an in demand service....does hashicorp have a roadmap for services not yet supported?

**Comment by orlando** [comment]
@kurtmaile I think that *demanding* something because you need it is the right way to do it. I don't think Hashicorp has a roadmap of thinks that are going to be integrated, most of the stuff come from contributions.

Looks like @jzbruno is working on this feature at the moment.
