### ISSUE TITLE
Terraform 0.7.4 crash during planning with azurerm provider

### ISSUE THREAD

**Issue by cchildress** [hashicorp/terraform#8995]
### Terraform Version
0.7.4

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm provider (I think the crash actually happened here. The last entry before the panic is for azurerm_virtual_machine.)
- cloudflare provider

### Terraform Configuration Files
[Link](https://drive.google.com/file/d/0B8j8uwKj3jzUN3RPOEJodTBEaGc/view?usp=sharing)

### Debug Output
[Link to the gist](https://gist.github.com/cchildress/9f18875771c7ccde02c93445f5393e0c)

### Panic Output
I included it with the config.

### Expected Behavior
Run plan and see a list of new resources to be created.

### Actual Behavior
A crash log gets written out.

### Steps to Reproduce
1. Run `terraform plan` with the azurerm provider using modules.

### Important Factoids
Not sure if this is actually relevant to the crash, but the plan should have created two availability sets, two new nics, two new storage containers, and two new virtual machines as children of one module.

**Comment by stack72** [comment]
@cchildress thanks for reporting the issue here -sorry this has caused you some pain! Please can you give me access to download the files from google drive? anything at the hashicorp.com domain will be useful

Thanks

Paul

**Comment by cchildress** [comment]
@stack72 Sorry about that, the link should be good now.

**Comment by stack72** [comment]
Hi @cchildress 

Thanks for that - looking into your issue now :)

P.

**Comment by stack72** [comment]
Hi @cchildress 

I believe I have found the cause here - I am just adding a test to ensure it works as expected and will open a PR

P.

**Comment by cchildress** [comment]
Hey @stack72 
Good to hear, hopefully I got the report in quickly enough to see it go out in 0.7.5.
Thanks for the quick turnaround!

**Comment by cchildress** [comment]
Hey @stack72 
I appear to be able to reproduce this on Terraform 0.7.6. I've been going through the crash log and the stack trace from the SIGSEGV is identical to the one in this gist.
Do you want this submitted as a new issue or do you want to re-open this one?
I can get you new crash logs if you need them, but I wanted to reach out first and see what you need. It takes a little while to go through these long crash logs and sanitize account info out.

**Comment by stack72** [comment]
Hi @cchildress 

Are you using the new config structure of boot_diagnostics rather than diagnostics_profile?

There was a change at the top of the changelog about the deprecation

Paul

**Comment by cchildress** [comment]
Hi @stack72 
No, I don't have either defined in the tf files. I also searched through the state files and the string diagnostics doesn't show up anywhere.
A quick spot check in the Azure portal shows that some of our machines have it enabled and some don't. I don't think Terraform enabled them though; I'm thinking someone may have manually enabled it on a troublesome machine in the portal.
I'd have no problem with that to enabled or disabled across the board, but I don't see how I could apply the change since Terraform is crashing during the refresh.

**Comment by cchildress** [comment]
I created [issue 9461](https://github.com/hashicorp/terraform/issues/9461) to track this in 0.7.6.
