### ISSUE TITLE
Terraform | CLC provider | Get name of a clc_group searching with ID.

### ISSUE THREAD

**Issue by sgreco2002** [hashicorp/terraform#9014]
Hi
i'm new to terraform, and i'm about to become mad to understand how to achieve my scope :)
let me explain you the scenario.
I'm using terraform version v0.7.3 using the CLC provider (Centurylink cloud).
i've declared a variable file with all the group folder that i need:

`variable "VTYPEFOLDER" {`
`type = "map"`
`description = "Folder that contain the VM"`
`default = {`
`GlobParent = "Mainfolder"`
`GlobFolder1 = "SubFolder1"`
`GlobFolder2 = "SubFolder2"`
`GlobFolder3 = "SubFolder3"`
`}`
`}`

Then, i've created all the resource on cloud in a "loop" using the word 'count' and getting the name using the count.index to retreive the folder name.

`resource "clc_group" "RAPPTYPEAVS" {`
`count = "${length(var.VTYPEFOLDER)}"`
`location_id = "${var.VAPPFOLDER.["GlobLocationID"]}"`
`parent = "${var.VTYPEFOLDER.["GlobParent"]}"`
`name = "${element (values(var.VTYPEFOLDER), count.index)}"`
`}`

Now, i'm about to create the VM, that require the group_id value, that is only reliable using the statement `clc_group.RAPPTYPEAVS.*.id.`
But how can i get the id based on folder name within this resource "clc_group"?
This is an example of what i want to do (sorry for using a 'sql' example, but is the best way to explain what i want to do):
...
`group_id = select clc_group.folder.id where clc_group.folder.name = "Subfolder1"`
...

Please let me know if there is some feature that can help me.
thanks,
s.

**Comment by inge4pres** [comment]
Hi @sgreco2002 

I believe you have a syntax issue here 
`location_id = "${var.VAPPFOLDER.["GlobLocationID"]}"`
should be
`location_id = "${var.VAPPFOLDER["GlobLocationID"]}"`

**Comment by sgreco2002** [comment]
Thanks for answer Francesco, i will correct.
What about my question instead? I mean about to "query" id value in CLC for clc_group using a key (folder_name).
It could be feasable?

**Comment by inge4pres** [comment]
Already tried lookup() function to get the value you need from the map?

**Comment by sgreco2002** [comment]
i will do! 
let you know, thanks!
