### ISSUE TITLE
softlayer_ssh_key public_key parameter doesn't strip line break

### ISSUE THREAD

**Issue by ti-mo** [hashicorp/terraform#9015]
When re-running TF against an existing (valid) `softlayer_ssh_key` with the same input, the resource is re-created when the input parameter contains a trailing line break. This line break is stripped by the SoftLayer API, the output is echoed back and saved in state.
### Terraform Version

v0.7.4
### Affected Resource(s)
- `softlayer_ssh_key` combined with `file()` interpolation into `public_key` attribute
### Terraform Configuration Files

``` hcl
resource "softlayer_ssh_key" "pubkey" {
  name = "pubkey"
  public_key = "${file("~/.ssh/id_rsa")}"
}
```
### Debug Output

(No debug output, was a little overkill)

```
-/+ softlayer_ssh_key.pubkey
    fingerprint: "cf:85:79:a9:f7:1a:ca:b8:35:74:89:a3:8b:a1:d3:21" => "<computed>"
    name:        "pubkey" => "pubkey"
    public_key:  "ssh-rsa AAAAB3NzaC1...xkfw==" => "ssh-rsa AAAAB3NzaC1...xkfw==\n" (forces new resource)
```
### Expected Behavior

No resource re-creation should have taken place, since an SSH key object in SoftLayer holds at most one SSH key.
### Actual Behavior

The `softlayer_ssh_key` resource got re-created and its dependent `softlayer_virtual_guest` got updated.
### Steps to Reproduce
1. `terraform apply`
2. `terraform apply` / `terraform plan`
### Important Factoids

This can obviously be worked around by removing the line break from the SSH key, but I consider this a minor defect nonetheless.
### References

I could not find any related open issues or PRs.

**Comment by renier** [comment]
@ti-mo This has been fixed at https://github.com/softlayer/terraform-provider-softlayer/. The in-tree terraform version of the provider is grossly obsolete.

**Comment by ti-mo** [comment]
@renier Thank you, that explains a lot! Closing for now.
