### ISSUE TITLE
s3_bucket wants to refresh every time due to referenced aws_iam_policy_document

### ISSUE THREAD

**Issue by mbrannigan** [hashicorp/terraform#9016]
If the `s3_bucket` refers to a policy generated by the `aws_iam_policy_document` data source, that bucket will attempt to refresh every run as it thinks the policy document has changed.

I attempted to remove all variables from the `aws_iam_policy_document` and replace them with static values, but it still wanted to refresh the bucket with each run.

What was successful was when i used `policy=file('policy.json')`, removing the `aws_iam_policy_document` completely.

Terraform Version: 0.7.3

Affected resources:
- aws_iam_policy_document
- aws_s3_bucket

Example code:
https://gist.github.com/mbrannigan/b219d6856592bf880282fe55e7d19bd8

**Comment by mbrannigan** [comment]
We have another bucket configured like this:
https://gist.github.com/mbrannigan/e9a1df44e1d450962afce8c9eeea262e
This one does not try to re-apply the `aws_iam_policy` document

I think the issue is that I'm passing the `aws_iam_policy` in the first example into a module.

**Comment by apparentlymart** [comment]
Hi @mbrannigan! Sorry for the issue here.

I tried to recreate using your given example code, but I wasn't able to see the problem.

If possbile, could you post the output from `terraform plan` (with any secrets redacted) after you've already applied once and Terraform is applying the unnecessary follow-up change? That would help to understand what exactly is changing and causing Terraform to think it needs to re-make this bucket.

**Comment by mbrannigan** [comment]
Here's the plan
`module.C3S3.aws_s3_bucket.bucket` wants to change due to an apparent 'change' in the policy.

I also included the module that is being called to create the bucket

https://gist.github.com/mbrannigan/1a78309c1a3648a6cd57f63eb0e7da6b

**Comment by apparentlymart** [comment]
Hi again @mbrannigan. Thanks for the extra info!

Looking at the before and after documents here, it seems like this is another example of a recurring problem in Terraform where each AWS service seems to do its own undocumented normalization of policies, so when we read back the policy documents they are different than what we submitted. We have some pretty significant code in Terraform to try to replicate these normalizations, but it seems like we've missed something here.

What jumped out at me as the main non-whitespace and non-ordering difference is the normalization of the `Principal` fields. In your config you wrote it as:

```json
        "Principal": {
            "AWS": "210987654321"
        }
```

...but S3 is returning it normalized into a full ARN:

```json
        "Principal": {
            "AWS": "arn:aws:iam::123456789012:root"
        },
```

Assuming this is what's causing the problem the workaround for now would be to replace the bare account ids in your config with the full ARN as shown above; this should be treated equivalently by AWS, but then when we read the policy back from the API we won't see a non-semantic difference.

This is something we should catch and normalize inside Terraform's policy normalization function, if the above workaround fixes it for you.

**Comment by mbrannigan** [comment]
That change worked perfectly.  Thanks for the input on that nuance of the policy!

**Comment by apparentlymart** [comment]
Thanks @mbrannigan! I made a new issue #9036 to note that we should be normalizing this automatically inside Terraform.

**Comment by mbrannigan** [comment]
Awesome!  Thanks again.
