### ISSUE TITLE
Is development on Windows possible?

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform#9019]
Team Terraform,

Is it possible to develop Terraform on Windows?  The Makefile calls shell scripts, so they obviously won't work on Windows.  Ok, so let's try using Vagrant...

After I `vagrant up` (VirtualBox), I hit a bunch of issues:
1. The shared folder did not contain anything, so I had to manually recreate it and `ln-s /media/sf_terraform`.  My colleague says this is a common problem with Windows host OSes.
2. `make` gave a File not found error, which I later realized was due to executable permissions not carrying over.  I cloned the repo within the Vagrant box and make then worked, but that kinda defeats the purpose of the Vagrant box.

If development on Windows is not possible, I would like to spare others from the pain by clearly indicating this on the README.md.  I'm willing to do the PR if someone can confirm my info is correct.

**Comment by mitchellh** [comment]
Yes it is. When I work on Windows I generally just work outside of Vagrant with Go installed since thats the only main dependency. Terraform can compile natively on Windows.
