### ISSUE TITLE
Allow empty names in dme_record (dnsmadeasy)

### ISSUE THREAD

**Issue by benosman** [hashicorp/terraform#9034]
I'm having issues setting any kind of record with an empty name field. Name field is required so must be present.
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- dme_record
### Terraform Configuration Files

``` hcl

resource "dme_record" "a_record" {
  domainid = "${var.domainid}"
  name = ""
  type = "A"
  value = "8.8.8.8"
  ttl = "600"
  gtdLocation = "DEFAULT"
}

resource "dme_record" "txt_record" {
  domainid = "${var.domainid}"
  name = ""
  type = "TXT"
  value = "v=spf1 mx a"
  ttl = "600"
  gtdLocation = "DEFAULT"
}

```
### Debug Output

https://gist.github.com/benosman/b4381a3b871c1bee8ec9243fb1fb12c0
### Expected Behavior

Records should have been added on the TLD.
### Actual Behavior

500 Internal server error.
### Steps to Reproduce
1. `terraform apply`
### References

Similar issues on other DNS providers:
- GH-8944  - dyn_record
- GH-7534  - aws_route53_record

**Comment by jgleonard** [comment]
+1 on Terraform v0.9.3
I'm running into a similar issue.  Any progress?
