### ISSUE TITLE
Unable to use output variable from dependency inside of module input list

### ISSUE THREAD

**Issue by mattfysh** [hashicorp/terraform#9037]
Hi there,

### Terraform Version
v0.7.4

### Affected Resource(s)
- aws_iam_user
- aws_iam_group
- aws_iam_group_membership

### Terraform Configuration Files
**main.tf**
```hcl
variable "access_key" {}
variable "secret_key" {}

provider "aws" {
	access_key = "${var.access_key}"
	secret_key = "${var.secret_key}"
	region = "ap-southeast-2"
}

resource "aws_iam_user" "tmp" {
	name = "tmp"
}

module "tmp_group" {
	source = "./group"
	name = "tmp"
	users = [ "${aws_iam_user.tmp.id}" ]
}
```

**group/main.tf**
```hcl
variable "name" {}
variable "users" {
	type = "list"
}

resource "aws_iam_group" "group" {
	name = "${var.name}"
}

resource "aws_iam_group_membership" "users" {
	name = "${var.name}_users"
	group = "${aws_iam_group.group.id}"
	users = "${var.users}"
}
```

### Expected Behavior
1. user created
2. group created
3. user added to group

### Actual Behavior
ERR: `aws_iam_group_membership.users: users: should be a list`

### Steps to Reproduce
1. `terraform apply`

### References
May be duplicate of #8048

**Comment by mattfysh** [comment]
If module input variable is a string, I'm able to pass in `stringvar = "${aws_iam_user.tmp.id}"`. It's only when the input variable is a list, the inner variables will not be resolved before entering the module

**Comment by apparentlymart** [comment]
Hi @mattfysh!

I think the issue here is that when interpolating a list it must be interpolated *into* a list, like this:

```hcl
resource "aws_iam_group_membership" "users" {
    name = "${var.name}_users"
    group = "${aws_iam_group.group.id}"
    users = ["${var.users}"]
}
```

Notice that the `users` argument is now a single-element list containing the interpolation, rather than just a bare string.

Could you give that a try and let me know if it helps?

Thanks!

**Comment by mattfysh** [comment]
thanks @apparentlymart, that seems to have fixed it :)
although, it does highlight a couple of other issues:

1. if I inline replace the variable in main.tf such that `users = [ "tmp" ]`, this works. That is without making the change suggested
2. this could probably use some docs on the interpolation syntax page, as I couldn't find anything there on referencing list variables, and coming from another language makes it not so straightforward putting arrays within string literals

**Comment by apparentlymart** [comment]
Agreed that this doesn't seem to be documented anywhere obvious. Makes me wonder now how I figured it out myself. :grinning:

The only reference I could find on the Interpolation Syntax page was buried in the documentation for `split`:

> `split(delim, string)` - Splits the string previously created by join back into a list. This is useful for pushing lists through module outputs since they currently only support string values. Depending on the use, the string this is being performed within may need to be wrapped in brackets to indicate that the output is actually a list, e.g. `a_resource_param = ["${split(",", var.CSV_STRING)}"]`. Example: `split(",", module.amod.server_ids)`

...and even this is very unclear about it, using vague terms like "depending on the use" and "may need to be wrapped". We should definitely explain this better in a more explicit location on that page. I'm going to add the documentation tag to this to remind us about it.
