### ISSUE TITLE
Cloudflare API Support

### ISSUE THREAD

**Issue by omarabid** [hashicorp/terraform#9040]
This is not a bug report but rather a feature request. The cloudflare API currently supports only the "Record" resource. The GO API Library has many other features, though.

https://godoc.org/github.com/cloudflare/cloudflare-go

Any chances of getting some of these into the Cloudflare Provider?

**Comment by apparentlymart** [comment]
Hi @omarabid!

In an ideal world Terraform would be able to create *everything*, but with finite development time it's necessary to prioritize. If you have some specific use-cases in mind that would be helped by new resources in Terraform it would help a lot if you could describe them a little, which will help to understand which of the Cloudflare concepts would be most useful/valuable.

**Comment by jonleighton** [comment]
Personally I'd particularly like to see Page Rules supported in Terraform.

**Comment by jamestyrrell** [comment]
Yeh, Page Rules support would be excellent.

**Comment by mwarkentin** [comment]
+1 to page rules.

**Comment by OJFord** [comment]
I agree with page rules as most important.

Crypto>SSL and automatic HTTPS rewrites (and the other Boolean toggles on that page) are potentially low-hanging but juicy fruit too though.

It doesn't seem like it'd be too difficult (just time-consuming) to implement something else using [the existing records implementation](https://github.com/hashicorp/terraform/blob/master/builtin/providers/cloudflare/resource_cloudflare_record.go) as a reference - are you open to PRs for this?

**Comment by cemo** [comment]
New private beta Load Balancer feature is also worth to implement.

**Comment by elithrar** [comment]
@cemo We're going to push support for our LB API to our Go library "soon" - if you'd like to collaborate on the Terraform integration we're open to it!

(Matt S @ Cloudflare)

**Comment by OJFord** [comment]
@jonleighton @jamestyrrell @mwarkentin - Please feel free to test Page Rules with my branch (#11249) - everything I've tested 'works', in so far as the rules are created.

I am seeing an error coming out of the cloudflare-go library though, which stops terraform saving the state. I'm 90% sure it's a problem in the lib, but I could have done something wrong... YMMV so if any of you do have a chance to test (with some kind of demo, or a copy of something existing, not production of course!). 🙂

**Comment by elithrar** [comment]
It's possible that an API change has our v4 API returning an integer for a
value but accepting a string.

Hence, the API response doesn't marshal into a map[string]string.

Debugging should be possible by dumping the response before we marshal.
I'll attempt to take a look at this soon.
