### ISSUE TITLE
ELB creation timing out while waiting for health check to return healthy

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform#9045]
Running TF 0.7.1 currently we've started occasionally seeing errors that look like this:

```
05:07:13 [0m[1mmodule.balancer_cc_instance.aws_elb.scope: Still creating... (4m40s elapsed)[21m[0m
05:07:23 [0m[1mmodule.balancer_cc_instance.aws_elb.scope: Still creating... (4m50s elapsed)[21m[0m
05:07:33 [0m[1mmodule.balancer_cc_instance.aws_elb.scope: Still creating... (5m0s elapsed)[21m[0m
05:07:43 [31mError applying plan:
05:07:43 
05:07:43 2 error(s) occurred:
05:07:43 
05:07:43 * aws_elb.scope: timeout while waiting for state to become 'success'. last error: %!s(<nil>)
05:07:43 * aws_elb.scope: Failure configuring health check for ELB: SignatureDoesNotMatch: Signature expired: 20160926T040240Z is now earlier than 20160926T040242Z (20160926T040742Z - 5 min.)
05:07:43    status code: 403, request id: c5a36582-839e-11e6-a712-a5cda905e94f
05:07:43 
05:07:43 Terraform does not automatically rollback in the face of errors.
05:07:43 Instead, your Terraform state file has been partially updated with
05:07:43 any resources that successfully completed. Please address the error
05:07:43 above and apply again to incrementally change your infrastructure.[0m[0m
05:07:43 + exitcode=1
```

At this point in our automation when it fails we don't actually have any instances attached to the ELB so the ELB's health check should automatically return healthy. We're currently creating about 120 ELBs every morning after destroying them at the end of the previous working day and seeing on average maybe 1 failure a day since our move to 0.7.1.

If we check the ELB directly at that point with either the CLI or AWS Console it appears to be fine. However when Terraform re-runs it then complains that there is already an ELB with that name:

```
05:08:38 1 error(s) occurred:
05:08:38 
05:08:38 * aws_elb.scope: DuplicateLoadBalancerName: Load Balancer named test01-wx-aat1-www-balancer already exists and it is configured with different parameters.
05:08:38    status code: 400, request id: cb0df6dd-839e-11e6-8475-db9773cef9ef
05:08:38 
```

Because of the previous failure meaning that it never made it into the state file even though it had successfully created it.

We didn't see these errors on previous versions of Terraform (we were on 0.6.16 for a long time and 0.6.14 before that) but have been seeing them intermittently since we moved to 0.7.1 a little over a month ago.

Looking at the history for the ELB resource I can't see anything obvious that would lead to a regression specifically around ELBs or for that to have then been fixed since 0.7.1 in the latest release. Due to the intermittent nature of this issue it's difficult to test it ad-hoc rather than in our daily build of environments but I'll try and spend some time this week to see if I can reproduce it separately and then test with the latest release.

**Comment by tomelliff** [comment]
This looks like it may have been fixed by moving to the AWS Go SDK 1.4.15 in https://github.com/hashicorp/terraform/commit/4ff762993da57c9dded85de164e02e2c9b0ff4c7. Today was our first day since moving to 0.7.1 where we haven't had this issue so as long as it stays fine tomorrow then I'll close this as fixed.

**Comment by tomelliff** [comment]
Spoke to soon apparently as it reoccurred this morning:
```
05:04:14 2 error(s) occurred:
05:04:14 
05:04:14 * aws_elb.scope: timeout while waiting for state to become 'success' (timeout: 1m0s)
05:04:14 * aws_elb.scope: timeout while waiting for state to become 'success' (timeout: 1m0s)
05:04:14 
```

**Comment by ianpackard** [comment]
We also have this problem. Using terraform 0.7.7 - Several users experience a timeout, followed by an incomplete state file. This causes terraform to attempt to recreate the ELB..

* aws_elb.my_elb: DuplicateLoadBalancerName: Load Balancer named my-elb already exists and it is configured with different parameters.
      status code: 400, request id: ec55abe5-a5c0-11e6-a655-23f78c04ac6b

**Comment by cablespaghetti** [comment]
We're also seeing this timeout issue. However I think it may be separate to this original bug.

**Comment by johnnorton** [comment]
It is possible to increase the timeout while waiting for the ELB?

**Comment by marktb1** [comment]
+1
