### ISSUE TITLE
google_compute_forwarding_rule isn't idempotent anymore (issue with a single port in port_range).

### ISSUE THREAD

**Issue by sbadia** [hashicorp/terraform#9051]
### Terraform Version
- `v0.7.4` (I don't remember but this bug occur since 0.7.x)
### Affected Resource(s)
- google_compute_forwarding_rule
### Output

The resource google_compute_forwarding_rule isn't idempotent anymore across run.

```
-/+ google_compute_forwarding_rule.ipsec-foobar1-gw1-rule-udp4500
    ip_address:  "1.2.3.4" => "1.2.3.4"
    ip_protocol: "UDP" => "UDP"
    name:        "ipsec-foobar1-gw1-rule-udp4500" => "ipsec-foobar1-gw1-rule-udp4500"
    port_range:  "4500-4500" => "4500" (forces new resource)
    project:     "foobar-cloud" => "<computed>"
    region:      "europe-west1" => "<computed>"
    self_link:   "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/forwardingRules/ipsec-foobar1-gw1-rule-udp4500" => "<computed>"
    target:      "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/targetVpnGateways/ipsec-foobar1-gw1" => "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/targetVpnGateways/ipsec-foobar1-gw1"

-/+ google_compute_forwarding_rule.ipsec-foobar1-gw1-rule-udp500
    ip_address:  "1.2.3.4" => "1.2.3.4"
    ip_protocol: "UDP" => "UDP"
    name:        "ipsec-foobar1-gw1-rule-udp500" => "ipsec-foobar1-gw1-rule-udp500"
    port_range:  "500-500" => "500" (forces new resource)
    project:     "foobar-cloud" => "<computed>"
    region:      "europe-west1" => "<computed>"
    self_link:   "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/forwardingRules/ipsec-foobar1-gw1-rule-udp500" => "<computed>"
    target:      "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/targetVpnGateways/ipsec-foobar1-gw1" => "https://www.googleapis.com/compute/v1/projects/foobar-cloud/regions/europe-west1/targetVpnGateways/ipsec-foobar1-gw1"
```
### Expected Behavior

Without resources changes (`.tf` files), a `plan` or `apply` should be idempotent.
### Actual Behavior

The resource google_compute_forwarding_rule isn't idempotent anymore across run.
### Steps to Reproduce
1. Create a `.tf` file with a `google_compute_forwarding_rule` with a `port_range` containing only one port.
2. `terraform apply` (this create the forwarding rule)
3. `terraform apply` (this run delete/create the same forwarding rule)
### Workaround

According the [documentation](https://www.terraform.io/docs/providers/google/r/compute_forwarding_rule.html), we can configure `port_range` with a `A range e.g. "1024-2048" or a single port "1024" (defaults to all ports!).`

We can workaround this issue by configure `port_range` like this:

``` diff
- port_range  = "4500"
+ port_range  = "4500-4500"
```

**Comment by Stono** [comment]
+1, this is hitting me too!

**Comment by Amit-PivotalLabs** [comment]
I'm having this same problem on `v0.7.13`.  I have a handful of `google_compute_forwarding_rule`s specified, one of which has an actual port range, and the rest have a single port.  The single-port ones are being destroyed and recreated every time I `terraform apply` in my CI pipeline.  This causes availability downtime.
