### ISSUE TITLE
How to import resource on a openstack provider with multiple region ?

### ISSUE THREAD

**Issue by xtero** [hashicorp/terraform#9054]
### Terraform Version

0.7.4
### Affected Resource(s)
- any importable openstack resources
### Terraform Configuration Files

No configuration file
### Debug Output

https://gist.github.com/xtero/d048e6b0235a13ea8622eb197781883e
### Panic Output

N.A
### Expected Behavior

In my environment, I have set the varibale OS_REGION_NAME to "fr1".
So during the import, I expect terraform to filter endpoint based on this value.
### Actual Behavior

Nothing is filtered. And I end up with 2 endpoint instead of one
### Steps to Reproduce
1. We need to have at least 2 region with endpoint for each region for the same component.
2. We have to defined tenant variables :

```
OS_REGION_NAME=fr1
OS_PASSWORD=123
OS_AUTH_URL=https://identity.fr1.cloudwatt.com/v2.0/
OS_USERNAME=toto
OS_TENANT_NAME=My_tenant
```
1. The problem occure when we run something like :

```
$ terraform import openstack_networking_network_v2.any_name any-id-goes-here
```
1. We got the following error message : "Error creating OpenStack networking client: Discovered 2 matching endpoints"
### Important Factoids

We are using a public cloud based on Openstack that provide 2 regions "fr1" and "fr2".

**Comment by lklepner** [comment]
I'm experiencing the same problem. Have you found a solution to this?

**Comment by jtopjian** [comment]
I'm sorry for the late response on this one. 

I've just submitted #10509 which should fix this problem. If you're able to build Terraform from source, please do try it out and let me know the result. :)
