### ISSUE TITLE
Import based on configuration for provider

### ISSUE THREAD

**Issue by ajcrites** [hashicorp/terraform#9059]
`terraform import` does not allow reading from configuration files, so if you want to import to a configuration that has something like

``` hcl
provider "aws" {
    region = "${var.aws_region}"
    profile = "${var.aws_profile}"
}
```

you can't. You have to find another way to specify provider information for the import -- in this case, AWS credential information.
### Terraform Version

0.7.4
### Affected Resource(s)

Terraform core
### Terraform Configuration Files

Import does not use configuration
### Expected Behavior

You should be able to specify configuration for `terraform import` to use.
### Actual Behavior

`terraform import` does not provide any way to read from configuration to get data.
### Steps to Reproduce

Create a configuration with a `provider` section and apply the configuration. When you want to `terraform import`, you will notice that there is no way to specify which configuration to read from.

An example with AWS would be:

``` hcl
provider "aws" {
    region = "${var.aws_region}"
    profile = "${var.aws_profile}"
}
```

You would be able to do `terraform plan -var aws_region=us-east-1 -var aws_profile=foo`. However, if you set these variables for `terraform import`, they don't get used for your AWS credentials.

Note that this has nothing to do with `terraform import` creating or managing configuration, I just think there should be a way to provide information about a particular configuration -- particularly provider information -- during imports.

**Comment by mitchellh** [comment]
Fixed by #9809 (not yet merged but will be shortly)
