### ISSUE TITLE
Tags not being applied to aws_vpc_dhcp_options

### ISSUE THREAD

**Issue by mcheshier-switch** [hashicorp/terraform#9064]
### Terraform Version

v0.7.4 (Windows)
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_vpc_dhcp_options
### Terraform Configuration Files

resource "aws_vpc_dhcp_options" "Google_DNS" {
  domain_name_servers = ["8.8.8.8","8.8.4.4"]
  domain_name = "us-east-1.compute.internal"

  tags {
      Name = "Google_DNS"
      Terraform = "Managed by Terraform"
  }
}
### Expected Behavior

DHCP options set record should have been created with the Name and Terraform tags.
### Actual Behavior

Options set created successfully, no tags.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

I'm using Windows, if that makes a difference.

**Comment by optimisticanshul** [comment]
<img width="705" alt="screen shot 2016-09-27 at 1 17 41 pm" src="https://cloud.githubusercontent.com/assets/4547169/18864612/ceb1089c-84b4-11e6-9bcd-37a0cab46aae.png">


```
aws_vpc_dhcp_options.Google_DNS: Creating...
  domain_name:           "" => "us-east-1.compute.internal"
  domain_name_servers.#: "" => "2"
  domain_name_servers.0: "" => "8.8.8.8"
  domain_name_servers.1: "" => "8.8.4.4"
  tags.%:                "" => "2"
  tags.Name:             "" => "Google_DNS"
  tags.Terraform:        "" => "Managed by Terraform"
aws_vpc_dhcp_options.Google_DNS: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Working as expected @mcheshier-switch

**Comment by stack72** [comment]
Hi @mcheshier-switch 

Thanks for opening the issue here - as @optimisticanshul points out, this does work as expected. We have an acceptance test that runs nightly for this. 

Can you confirm if it is just this resource that doesn't get tags applied or all ec2 resources?

Thanks

Paul

**Comment by mcheshier-switch** [comment]
Hi Paul, I took a look and there is one other component without tags, but
not everything. Here's some more detail about what I was doing:

My .tf file was designed to build out my VPC + networking infrastructure in
a new region from scratch. It worked great until I encountered an error in
one of my routing files. I am new to Terraform and didn't fully grok how it
handles the default route for you. This caused an error. Once I fixed that,
all resources I expected were created without Terraform reporting errors,
but viewing some of the resources in the console does not display tags.

The following created successfully with tags:

VPC
Subnets
Internet Gateway
Route Tables

The following were created without tags:

Security group
DHCP Option Set

Also of note, the CIDR blocks in my security group are also not set - it
has allow all for everything but not the IP restrictions I put in place to
block everything but the VPN.

I also tried using taint on the SG and DHCP option set and rebuilding them,
but still no tags. My next step is probably going to be destroying
everything, deleting my state file and trying again.

If it helps, I can send you the .tf file as well.

Thanks!

**Comment by stack72** [comment]
Hi @mcheshier-switch 

if you can add a gist of the .tf file (minus any secrets) then i can check here on my end :)

P.

**Comment by mcheshier-switch** [comment]
Hi Paul, here's the Gist. Thanks for taking a look!

https://gist.github.com/anonymous/48aa1f84388a07d70d5bca4f9f363fa1

**Comment by stack72** [comment]
Hi @mcheshier-switch 

Apologies for not getting back to you sooner on this - I have just tested this as follows. Using the config:

```
[stacko@Pauls-MacBook-Pro:~/Code/terraform-recreations/9064]
% ccat main.tf
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "VPC_Switch" {
  cidr_block = "10.210.0.0/16"
  enable_dns_hostnames = "true"

  tags {
      Name = "VPC_Switch"
      Terraform = "Managed by Terraform"
  }
}

resource "aws_vpc_dhcp_options" "Google_DNS" {
  domain_name_servers = ["8.8.8.8","8.8.4.4"]
  domain_name = "us-east-1.compute.internal"

  tags {
      Name = "Google-DNS"
      Terraform = "Managed by Terraform"
  }
}
```

A plan looks like this:

```
[stacko@Pauls-MacBook-Pro:~/Code/terraform-recreations/9064]
% terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_vpc.VPC_Switch
    cidr_block:                "10.210.0.0/16"
    default_network_acl_id:    "<computed>"
    default_route_table_id:    "<computed>"
    default_security_group_id: "<computed>"
    dhcp_options_id:           "<computed>"
    enable_classiclink:        "<computed>"
    enable_dns_hostnames:      "true"
    enable_dns_support:        "<computed>"
    instance_tenancy:          "<computed>"
    main_route_table_id:       "<computed>"
    tags.%:                    "2"
    tags.Name:                 "VPC_Switch"
    tags.Terraform:            "Managed by Terraform"

+ aws_vpc_dhcp_options.Google_DNS
    domain_name:           "us-east-1.compute.internal"
    domain_name_servers.#: "2"
    domain_name_servers.0: "8.8.8.8"
    domain_name_servers.1: "8.8.4.4"
    tags.%:                "2"
    tags.Name:             "Google-DNS"
    tags.Terraform:        "Managed by Terraform"


Plan: 2 to add, 0 to change, 0 to destroy.
```

An apply looks like this:

```
% terraform apply
aws_vpc_dhcp_options.Google_DNS: Creating...
  domain_name:           "" => "us-east-1.compute.internal"
  domain_name_servers.#: "" => "2"
  domain_name_servers.0: "" => "8.8.8.8"
  domain_name_servers.1: "" => "8.8.4.4"
  tags.%:                "" => "2"
  tags.Name:             "" => "Google-DNS"
  tags.Terraform:        "" => "Managed by Terraform"
aws_vpc.VPC_Switch: Creating...
  cidr_block:                "" => "10.210.0.0/16"
  default_network_acl_id:    "" => "<computed>"
  default_route_table_id:    "" => "<computed>"
  default_security_group_id: "" => "<computed>"
  dhcp_options_id:           "" => "<computed>"
  enable_classiclink:        "" => "<computed>"
  enable_dns_hostnames:      "" => "true"
  enable_dns_support:        "" => "<computed>"
  instance_tenancy:          "" => "<computed>"
  main_route_table_id:       "" => "<computed>"
  tags.%:                    "" => "2"
  tags.Name:                 "" => "VPC_Switch"
  tags.Terraform:            "" => "Managed by Terraform"
aws_vpc_dhcp_options.Google_DNS: Creation complete
aws_vpc.VPC_Switch: Creation complete

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

A follow up plan looks like this:

```
[stacko@Pauls-MacBook-Pro:~/Code/terraform-recreations/9064]
% terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

aws_vpc.VPC_Switch: Refreshing state... (ID: vpc-5da5963a)
aws_vpc_dhcp_options.Google_DNS: Refreshing state... (ID: dopt-71547215)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

I can see that the tags have been applied in the console:

<img width="818" alt="screen shot 2016-10-07 at 00 17 30" src="https://cloud.githubusercontent.com/assets/227823/19173981/783e861c-8c23-11e6-8284-00047460e8e9.png">

I have tried this on both Terraform 0.7.4 and the latest release (as of today), 0.7.5 and it works in each

**Comment by stack72** [comment]
Hi @mcheshier-switch 
Is this still an issue for you?

Paul

**Comment by catsby** [comment]
Closing this for now, please let us know if you're still hitting this!

**Comment by mcheshier-switch** [comment]
Hi Hashicorp, I updated to version 0.7.10 and this issue appears to now be
resolved. There is some interesting behavior you may want to make a note of
and fix/document, though I doubt it's a high-priority issue.

Without specifying a VPC like this in my SG:

vpc_id = "${aws_vpc.my_VPC.id}"

my security group *is* created, but in the default VPC. A second security
group with the same tag is *also* created in my new VPC created by
Terraform, but it has no rules associated with it.

I recommend adding the vpc_id reference to the documentation at:

https://www.terraform.io/docs/providers/aws/r/security_group.html

Since this can be a little confusing.

Thanks!

**Comment by stack72** [comment]
Hi @mcheshier-switch 

Thanks for keeping us informed here - we have already included the documentation :) https://www.terraform.io/docs/providers/aws/r/security_group.html#vpc_id

Hope this helps going forward

Thanks

Paul
