### ISSUE TITLE
Terraform is not removing tainted aws_resource and it's failing to remove aws_volume_attachment

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/terraform#9065]
### Terraform Version

0.7.4
### Affected Resource(s)
- aws_volume_attachment
- aws_instance
### Terraform Configuration Files

``` hcl
resource "aws_instance" "teamcity_server" {
  ami = "${var.server_ami}"
  availability_zone = "${var.server_az}"
  instance_type = "${var.server_instance_type}"
  vpc_security_group_ids = [ "${split(",", var.security_groups)}" ]
  subnet_id = "${var.subnet_id}"

  key_name = "${var.key_name}"
  iam_instance_profile = "tc-server"

  root_block_device {
    volume_type = "gp2"
  }
}

resource "aws_ebs_volume" "data_volume" {
  availability_zone = "${var.server_az}"
  snapshot_id = "${var.data_volume_snapshot}"
  size = "${var.data_volume_size}"
  type = "gp2"
}

resource "aws_volume_attachment" "data_volume_attachment" {
  device_name = "/dev/sdf"
  instance_id = "${aws_instance.teamcity_server.id}"
  volume_id = "${aws_ebs_volume.data_volume.id}"
}
```

I ommited non-relevant parts.
### Expected Behavior

Since the `aws_instance` has an `aws_volume_attachment`, we used to taint `aws_instance` before running `terraform destroy` to ensure the instance is marked for deletion so that  `aws_instance`, `aws_volume_attachment`, `aws_ebs_volume` are properly destroyed regardless of the volume attachment dependency. This was working fine until v0.6.16.
### Actual Behavior

```
$ terraform taint -no-color -allow-missing -module=teamcity aws_instance.teamcity_server
The resource aws_instance.teamcity_server in the module root.teamcity has been marked as tainted!
$ terraform destroy
...
Error applying plan:

1 error(s) occurred:

* aws_volume_attachment.data_volume_attachment: Error waiting for Volume (vol-af94311b) to detach from Instance: i-a6182dbe
```

[Full logs](https://gist.github.com/hgontijo/50a926fdc665dd31c22dd85ccc3957ed)

Based on the logs, `aws_instance` is not being removed as expected by running `taint` before `destroy`. 
### Steps to Reproduce
1. `terraform apply`
2. `terraform taint -no-color -allow-missing -module=teamcity aws_instance.teamcity_server``
3. `terraform destroy`
### References

That maybe related to:
- GH-9000

**Comment by kshcherban** [comment]
Same issue with 0.7.10
Seems like before detaching instance should be stopped.
