### ISSUE TITLE
Add a `formatmap` function

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#9066]
Currently there exists a `formatlist` function which can be used to join array elements together. I have a Terraform module which accepts a list of environment variables to be injected into a script executed via a `null_resource`. Ideally, I want the `environment` variable to be exposed as a `map` rather than as a `list`. That is, I am currently doing this:

```
  provisioner "local-exec" {
    command = <<COMMAND
mkdir -p "$(dirname "${null_resource.runner.triggers.filepath}")"
${path.module}/bin/package ${join(" ", formatlist("-e \"%s\"", var.environment))} -o "${null_resource.runner.triggers.filepath}" "${var.package}" "${var.version}"
COMMAND
  }
```

Whereas I would prefer to do this:

```
  provisioner "local-exec" {
    command = <<COMMAND
mkdir -p "$(dirname "${null_resource.runner.triggers.filepath}")"
${path.module}/bin/package ${join(" ", formatlist("-e \"%{key}s=%{value}s\"", var.environment))} -o "${null_resource.runner.triggers.filepath}" "${var.package}" "${var.version}"
COMMAND
  }
```

**Comment by alexdavid** [comment]
It's not an ideal solution, but those looking for a current workaround can use something like this:
```terraform
formatlist("-e \"%s=%s\"", keys(var.environment), values(var.environment))
```

**Comment by apparentlymart** [comment]
Thanks for sharing that workaround, @alexdavid.

Given that there is a usable workaround here I'm going to close this for now, though we are definitely feeling the current limitations with manipulating lists and maps with functions in the interpolation language so we are likely to do some core interpolation language work in the medium term to try to get to a point where it's not necessary to provide searate `...list` and `...map` versions of every function to allow it to be used across a list. This idea is still in early stages but something we are working towards gradually.

**Comment by apparentlymart** [comment]
Hi all!

For posterity I just wanted to note here that the improved configuration language interpreter we're currently working on integrating has a general feature that allows any function to be applied to the elements of a list or map.

```hcl
# NOT YET IMPLEMENTED and details may change before release

    [for x in var.list: format("%08x", x)]
    {for k, v in var.list: k => format("%08x", v)}
```

We already have quite a lot of issues open that are covered by these improvements, so I'm not going to re-open this one but just wanted to note this here in case this issue comes up in search in future.
