### ISSUE TITLE
azurerm imported resources have an empty resource_group_name

### ISSUE THREAD

**Issue by carinadigital** [hashicorp/terraform#9072]
### Terraform Version
0.7.4

### Affected Resource(s)
Confirmed the following resources but could be more:
- azurerm_public_ip
- azurerm_storage_account

### Terraform Configuration Files
```hcl
resource "azurerm_public_ip" "my-ip" {
  name                         = "my-ip"
  location                     = "uksouth"
  resource_group_name          = "dev"
  public_ip_address_allocation = "static"
}
```

### Debug Output
```
-/+ azurerm_public_ip.my-ip
    fqdn:                         "" => "<computed>"
    ip_address:                   "[My IP Here]" => "<computed>"
    location:                     "uksouth" => "uksouth"
    name:                         "my-ip" => "my-ip"
    public_ip_address_allocation: "static" => "static"
    resource_group_name:          "" => "dev" (forces new resource)
```
### Expected Behavior
The imported resource should have a resource_group_name

### Actual Behavior
resource_group_name was empty.

### Steps to Reproduce
1. Create your azurerm resource via the gui.
2. Use terraform to Import the resource.
3. See that the terraform plan wants to re-create the resource because of the missing resource_group_name.

### Important Factoids
In the two resources I have looked at resource_group_name is not set in the Read() functions.

**Comment by stack72** [comment]
Closed via #9073
