### ISSUE TITLE
Consul backend for remote state has size limit of 512KB

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/terraform#9077]
I just noticed that Consul has a hard coded size limit for a single KV to 512KB (since 2014) and that limit is easily reached with the state file of a small sized environment.

I initially opened https://github.com/hashicorp/consul/issues/2363 at Consul to make that value configurable but there are concerns about the impact on, for instance, replication when having big KV in store.

Has anyone else hit this limit yet?
Would it be feasible to have TF compress the state file before shipping it remotely?
Another option would be to split the state in multiple KV, since Consul now supports transactions to  write them atomically.

Thanks!

**Comment by stack72** [comment]
Hey @gpaggi 

Thanks for opening the issue here - this has already been raised as an issue in #8491. There is an associated PR for this. I am going to close this as a duplicate so we can track all the conversation in that PR

Paul
