### ISSUE TITLE
* vsphere_folder.frontend: Failed to create folder at frontend; ServerFaultCode: The operation is not supported on the object.

### ISSUE THREAD

**Issue by mrjcleaver** [hashicorp/terraform#9078]
Hi there,

I built the primary example per the website: https://www.terraform.io/docs/providers/vsphere/index.html
### Terraform Version

Terraform v0.7.4

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
### Affected Resource(s)
- vsphere_folder.frontend
### Terraform Configuration Files

``` hcl
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.vsphere_allow_unverified_ssl}"
}

# Create a folder
resource "vsphere_folder" "frontend" {
  path = "frontend"
  datacenter = "ha-datacenter"
}

# Create a file
resource "vsphere_file" "ubuntu_disk" {
  datastore = "datastore1"
  source_file = "/home/ubuntu/my_disks/custom_ubuntu.vmdk"
  destination_file = "/my_path/disks/custom_ubuntu.vmdk"
  datacenter = "ha-datacenter"      
}

# Create a disk image
resource "vsphere_virtual_disk" "extraStorage" {
    size = 2
    vmdk_path = "myDisk.vmdk"
    # govc datacenter.info
    datacenter = "ha-datacenter"
    datastore = "datastore1"
}

# Create a virtual machine within the folder
resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  folder = "${vsphere_folder.frontend.path}"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "VM Network"
  }

  disk {
    template = "centos-68"
  }
}
```
### Debug Output

https://gist.github.com/mrjcleaver/48920b0fe849223139997e81fb69bc0f
### Panic Output

n/a
### Expected Behavior

Should have worked, per the public website example 
### Actual Behavior

What actually happened?

> Error applying plan:
> 
> 1 error(s) occurred:
> - vsphere_folder.frontend: Failed to create folder at frontend; ServerFaultCode: The operation is not supported on the object.
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
### Steps to Reproduce

Please list the steps required to reproduce the issue
1. `terraform apply`
### Important Factoids
1. Local ESXi 6.0
2. I had to add `datacenter` to some of the above resources as your proforma code does not work
### References
- https://github.com/mkuzmin/terraform-vsphere/issues/12 (similar issue from defunct project)

**Comment by mrjcleaver** [comment]
The similarity to https://github.com/mkuzmin/terraform-vsphere/issues/12 says "vSphere APi is tricky. Root folder is not the same as root VM folder." 

The implication is that this example is no longer supported. As such it is misleading and a terrible first experience.

**Comment by hbokh** [comment]
Sorry for dropping in this late, but having some related issues over here.
 @mrjcleaver, are you running on something like "VMware vSphere 6" aka ESXi / standalone - so not VMware vCenter?
AFAIK the name _vSphere_ is misleading, because _vCenter Server_ is what's really needed when you want to use all the bells and whistles on Terraform.
Check out [#5896](https://github.com/hashicorp/terraform/issues/5896). I can run some `govc` commands against my ESXi 6.5, but `folder.create` is not allowed:
```
govc folder.create /some_folder
govc: ServerFaultCode: The operation is not supported on the object.
```

If this is really the case, the documentation should be made more clear about this.

**Comment by simonverzijl** [comment]
Am I understanding correctly that I can't use this against a (free) ESXi installation because of licensing ?  Tried similar to the TS and getting same errors.

First was getting "vsphere_file.ubuntu_disk: error datacenter '' not found"  when I left out the optional(?) datacenter parameter.

Adding datacenter=ha-datacenter results in 
"vsphere_folder.web: Failed to create folder at terraform_web_folder; ServerFaultCode: The operation is not supported on the object."

**Comment by hbokh** [comment]
@simonverzijl Affirmative.

**Comment by TheNotary** [comment]
Do the people at VMware know that the community will not be able to support VMware if it isn't made available to them?

**Comment by asubmani** [comment]
AFAIK, "datacetner" is a vCenter thing. The Free vSphere ESXi does not have a datacenter. It only has a data store.
If you are using vCenter try this: 
```hcl
# Add the datacenter data source
data "vsphere_datacenter" "fronteddc" {
    name = "ha-datacenter"
}

# Create a folder
resource "vsphere_folder" "frontend" {
  path = "frontend"
  datacenter = "ha-datacenter"
  datacenter_id = "${data.vsphere_datacenter.frontenddc.id}"
}
```
You would also need to change the vsphere_user/password/server variable to your vcenter server instead of the vsphere ESXi host.
```hcl
  user           = "${var.vsphere_user}"  # vcenter user in username@ssodomain.com format
  password       = "${var.vsphere_password}" # vcenter password
  vsphere_server = "${var.vsphere_server}"  # name of your vcenter server/appliance
```
