### ISSUE TITLE
Specifying disk in softlayer causes 500 error

### ISSUE THREAD

**Issue by pat610** [hashicorp/terraform#9083]
I'm installing a custom private image in SoftLayer which fails when I specify my disks.  However it works when I leave disks out of the configuration.

softlayer_virtual_guest.terraform-sample-BDTGroup: Creating...
backend_vlan_id: "" => "559104"
cpu: "" => "8"
dedicated_acct_host_only: "" => "false"
disks.#: "" => "1"
disks.0: "" => "100"
domain: "" => "somedomain.com"
frontend_vlan_id: "" => "559102"
hourly_billing: "" => "true"
image: "" => "4b36e2f4-02f7-4830-8dd2-c37988c76783"
ipv4_address: "" => ""
ipv4_address_private: "" => ""
local_disk: "" => "false"
name: "" => "terraform-vm"
private_network_only: "" => "false"
public_network_speed: "" => "1000"
ram: "" => "32768"
region: "" => "tor01"
Error applying plan:

1 error(s) occurred:

```
softlayer_virtual_guest.terraform-sample-BDTGroup: Error creating virtual guest: softlayer-go: could not SoftLayer_Virtual_Guest#createObject, HTTP error code: '500'
```
### Terraform Version

Terraform v0.7.3
### Terraform Configuration Files

``` hcl
resource "softlayer_virtual_guest" "terraform-sample-BDTGroup" {
    name = "terraform-vm"
    domain = "somedomain.com"
    image = "4b36e2f4-02f7-4830-8dd2-c37988c76783"
    region = "tor01"
    public_network_speed = 1000
    hourly_billing = true
    private_network_only = false
    cpu = 8
    ram = 32768
    disks = [100]
    dedicated_acct_host_only = false
    local_disk = false
    frontend_vlan_id = 559102
    backend_vlan_id = 559104    
}
```
### Expected Behavior

Get a VM with my custom image
### Actual Behavior

Error applying plan:

1 error(s) occurred:

```
softlayer_virtual_guest.terraform-sample-BDTGroup: Error creating virtual guest: softlayer-go: could not SoftLayer_Virtual_Guest#createObject, HTTP error code: '500'
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

SoftLayer with a custom image
### References
- GH-8734

**Comment by renier** [comment]
@pat610 Have you tried https://github.com/softlayer/terraform-provider-softlayer/? There are published binaries. Have not been able to get core updated with that version yet.
