### ISSUE TITLE
Adding disks in SoftLayer not working

### ISSUE THREAD

**Issue by pat610** [hashicorp/terraform#9084]
I've been trying to add disks to a vm with terraform.  Terraform gives a success message but the disks never show in my vm.
### Terraform Version

Terraform v0.7.3
### Terraform Configuration Files

``` hcl
resource "softlayer_virtual_guest" "terraform-test-pat4" {
    name = "terraform-test-pat4"
    domain = "somedomain.com"
    region = "tor01"
    public_network_speed = 100
    hourly_billing = true
    private_network_only = false
    cpu = 8
    ram = 16384
    dedicated_acct_host_only = false
    local_disk = false
    disks = [100, 500, 1000]
    block_device_template_group_gid = "4b36e2f4-02f7-4830-8dd2-c37988c76783"
}
```
### Expected Behavior

New disks added to VM
### Actual Behavior

terraform apply
softlayer_virtual_guest.terraform-test-pat4: Refreshing state... (ID: 24546589)
softlayer_virtual_guest.terraform-test-pat4: Modifying...
  disks.#: "0" => "3"
  disks.0: "" => "100"
  disks.1: "" => "500"
  disks.2: "" => "1000"
softlayer_virtual_guest.terraform-test-pat4: Still modifying... (10s elapsed)
softlayer_virtual_guest.terraform-test-pat4: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

This message shows success but when lsblk I don't see my new drives.

[root@terraform-test-pat5 ~]# lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   100G  0 disk 
├─xvda1 202:1    0 815.8M  0 part /boot
├─xvda2 202:2    0  41.8G  0 part /
├─xvda3 202:3    0  28.3G  0 part /var/log
└─xvda4 202:4    0  23.4G  0 part /store/tmp
xvdb    202:16   0     2G  0 disk 
└─xvdb1 202:17   0     2G  0 part 
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by renier** [comment]
@pat610 See https://github.com/softlayer/terraform-provider-softlayer/issues/50 for an explanation of the error
