### ISSUE TITLE
depends_on broken for Data template_file

### ISSUE THREAD

**Issue by stongo** [hashicorp/terraform#9086]
### Terraform Version

v0.7.4
### Affected Resource(s)
- data template_file
### Terraform Configuration Files

``` hcl
resource "null_resource" "discovery_token" {
  provisioner "local-exec" {
    command = "curl https://discovery.etcd.io/new?size=${var.node_count} > ${path.module}/.token"
  }
}
data "template_file" "cloud_config" {
  depends_on = ["null_resource.discovery_token"]
  template = "${file("${path.module}/templates/cloud-config.yaml")}"
  vars {
    discovery_token = "${file("${path.module}/.token")}"
  }
}
```
### Debug Output

https://gist.github.com/stongo/1c4c16773d8b8189215c3fd48054c729
### Expected Behavior

The `depends_on` directive should still be obeyed or else panic if it's not allowed. In this case the `null_resource.discovery_token` should complete before data template is updated.
If not allowed, please restore it's functionality as templating becomes very limited without any control structure. 
### Actual Behavior

The template data is updated before `null_resource.discovery_token` executes
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by mluedke** [comment]
I am having the same issue on v0.7.7.

**Comment by mitchellh** [comment]
I'm unable to reproduce this. The ordering happens properly for me. If you have any additional reproduction info please let me know!

**Comment by lehins** [comment]
The actual issue is not in the dependency, but rather in the `file` interpolation function. It reads the file during validation, not during rendering the template. Just for anybody looking here is a related ticket #8406

**Comment by arehmandev** [comment]
Just encountered this one too. Heres to recreate:

```
resource "null_resource" "hello" {
  provisioner "local-exec" {
    command = "bash hello > ${path.module}/hello.txt"
  }
}

data "template_file" "init" {
  depends_on = ["null_resource.hello"]
  template   = "${file("${path.module}/hello.txt")}"
}
```

The data.template_file will fail as it will say ${path.module}/hello.txt doesn't exist despite the depends_on being stated.
