### ISSUE TITLE
Terraform Plan fails on Windows when it attempts to refresh state of an AWS Route Table resource 

### ISSUE THREAD

**Issue by aoraki** [hashicorp/terraform#9090]
Hi,
    I encountered an issue using Terraform on Windows today.

**System Details**
My system details are as follows;

Laptop : Dell Latitude E6440
OS : Windows 10 Enterprise Edition
Processor : Intel(R) Core i7-4610M CPU @ 3.00GHz  
System Type : 16 GB RAM, 64-bit OS, x64-based processor

**Terraform Versions were problem was encountered**
0.7.4
0.7.0

**Problem Description**
I was attempting to run the `terraform plan` command on a terraform project.  The terraform project in question involves setting up various types of resources on AWS.  I had previously set up the backend config to point at an S3 bucket that contains the state for the resources that are contained within the terraform config, and I had run the `terraform get` command to load all the modules for the configuration (it ran successfully).

When I ran the `terraform plan` command the following message was output

> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but
> will not be persisted to local or remote state storage.

It then started refreshing the state of the various items in the config.  However while it was refreshing state it encountered an resource that had an entry in the state file, but did not exist in AWS.  The resource in question is an AWS Route Table resource.   When this happened the following error was output and the `terraform plan` execution stopped immediately without outputting what changes would be brought about by applying the config;

```
Error refreshing state: 1 error(s) occurred:

* aws_route.peer_route: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-9e3329fb' does not exist
        status code: 400, request id: 17e705df-219b-480e-a32e-ccabaab5ad66
```

It appears that when Terraform is checking if a route table exists, and the amazon API is replying with a  response saying that the route table doesn't exist, Terraform is interpreting that (incorrectly) as an error response and then refuses to continue.

The entry in the state file is as follows;

```
               "aws_route.peer_route": {
                    "type": "aws_route",
                    "depends_on": [
                        "aws_vpc_peering_connection.release_eng",
                        "null_resource.peer_route_diagnostics"
                    ],
                    "primary": {
                        "id": "r-rtb-9e3329fb3326654407",
                        "attributes": {
                            "destination_cidr_block": "10.184.234.0/24",
                            "destination_prefix_list_id": "",
                            "gateway_id": "",
                            "id": "r-rtb-9e3329fb3326654407",
                            "instance_id": "",
                            "instance_owner_id": "",
                            "nat_gateway_id": "",
                            "network_interface_id": "",
                            "origin": "CreateRoute",
                            "route_table_id": "rtb-9e3329fb",
                            "state": "active",
                            "vpc_peering_connection_id": "pcx-9c69e4f5"
                        }
                    },
                    "provider": "aws.release_eng_peer_route"
                },
```

When the same `terraform plan` command is run against the project in an OS X environment, Terraform flags the resource as needing to be created and continues.  It outputs the following, which is what I would expect to see given the entry in the state file, and the absence of the resource in AWS.

```
+ module.dev_vpc.base.aws_route.peer_route
    destination_cidr_block:     "10.184.12.0/24"
    destination_prefix_list_id: "<computed>"
    gateway_id:                 "<computed>"
    instance_id:                "<computed>"
    instance_owner_id:          "<computed>"
    nat_gateway_id:             "<computed>"
    network_interface_id:       "<computed>"
    origin:                     "<computed>"
    route_table_id:             "rtb-9e3329fb"
    state:                      "<computed>"
    vpc_peering_connection_id:  "${aws_vpc_peering_connection.release_eng.id}"
```

Whereas on Windows it fails saying it ran into an error while trying to determine if the resource exists.

Problem was encountered using both versions of Terraform I outlined above.

**Comment by achalupa74** [comment]
+1

**Comment by fastnsilver** [comment]
I am seeing the same on Mac OS Sierra.  I'm running terraform 0.7.5. I am trying to create VPC as described here: http://blog.kaliloudiaby.com/index.php/terraform-to-provision-vpc-on-aws-amazon-web-services/, except that I am deviating slightly by creating gateways in 3 availability zones. 

I see

```
Error refreshing state: 4 error(s) occurred:

* aws_route.public_gateway_route: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-e108af86' does not exist
	status code: 400, request id: afc84054-2205-4a61-9ba4-55dfb586224a
* aws_route.private_nat_gateway_route.2: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-ef08af88' does not exist
	status code: 400, request id: 1380b8d7-1548-4746-84e5-fda7930f8bd7
* aws_route.private_nat_gateway_route.1: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-e208af85' does not exist
	status code: 400, request id: 0f8f3484-2fc0-43f5-bba0-640d4ea7effe
* aws_route.private_nat_gateway_route.0: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-e008af87' does not exist
	status code: 400, request id: f1e1ff58-82af-487b-8766-896fb8753459
```

This is a portion of my module config, https://github.com/fastnsilver/grivet/blob/terraforming/bin/deploy/terraform/aws/modules/vpc/main.tf

**Comment by fastnsilver** [comment]
Nevermind.  My solution was to `rm -f` the `terraform.tfstate` file, re-run `terraform get` and `terraform plan -var-file={env}.tf`.

**Comment by stevehorsfield** [comment]
We are experiencing this issue with an Atlas configuration as well. Issue on plan in later versions of Terraform. On Apply on earlier versions.
