### ISSUE TITLE
Support importing aws_elasticache_replication_group

### ISSUE THREAD

**Issue by nara-tup** [hashicorp/terraform#9094]
Hi there,
Would like support for being able to import aws_elasticache_replication_group and aws_elasticache_cluster

**Comment by stack72** [comment]
Hi @nara-tup 

Thanks for the feature request here. Luckily, there is a PR in place for importing `aws_elasticache_cluster` - that will be included in Terraform 0.7.5 :)

If we can, then we will also get the import of `aws_elasticache_replication_group` included as well

Paul
