### ISSUE TITLE
Tags for digital ocean droplets keep changing order

### ISSUE THREAD

**Issue by simaofreitas** [hashicorp/terraform#9099]
Hi,

I'm using terraform for managing a set of droplets in digital ocean.
Yesterday I introduced tags (using `digitalocean_tag`) and everything is working correctly.
The problem is that every time I run `terraform plan` (or `apply`) I get changes because the `tags` keep changing their order inside the `tfstate` file.

Terraform version: `0.7.3`

Example of tags definition:

```
resource "digitalocean_tag" "staging" {
    name = "staging"
}

resource "digitalocean_tag" "web" {
    name = "web"
}
```

Example of droplet definition

```
resource "digitalocean_droplet" "machine01" {
  image              = "ubuntu-14-04-x64"
  name               = "machine01"
  region             = "fra1"
  size               = "16gb"
  private_networking = true
  backups            = true
  tags               = ["${digitalocean_tag.staging.id}", "${digitalocean_tag.web.id}"]

  ssh_keys = [
     ...
  ]
}
```

When running `terraform plan` (after I already ran `terraform apply`) I get this:

```
~ digitalocean_droplet.machine01
    tags.0: "staging" => "web"
    tags.1: "web" => "staging"
```

If I `apply`, the next time I run `plan` I would get the reverse output. But it always changes.

Couldn't find any open issues about this.

Any ideas?

Thanks a lot

**Comment by mrjcleaver** [comment]
Perhaps something like this for vSphere can be an inspiration: https://github.com/hashicorp/terraform/issues/6520

**Comment by nmarley** [comment]
This is a real issue, and I think could be solved (maybe?) by sorting the tags received from DO. An even bigger issue is that it also randomly orders SSH keys if you specify multiple, which results in a droplet being destroyed & re-created for no reason other than sort order.
