### ISSUE TITLE
Make SoftLayer provider's timeouts configurable

### ISSUE THREAD

**Issue by bondyk** [hashicorp/terraform#9113]
Hi,

Terraform doesn't have a possibility to configure timeout for SoftLayer provider. In case if SoftLayer takes more than 10 minutes to create a new virtual guest than terraform exits with timeout error. 
It would be great to be able to configure timeout values.
Currently timeout values are hard coded here: https://github.com/hashicorp/terraform/blob/master/builtin/providers/softlayer/resource_softlayer_virtual_guest.go (WaitForUpgradeTransactionsToAppear, WaitForPublicIpAvailable, WaitForNoActiveTransactions)
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- softlayer_virtual_guest
### Debug Output

```
softlayer_virtual_guest.tor01-dev-ybt-vm-3178-sa: Still creating... (9m50s elapsed)
softlayer_virtual_guest.tor01-dev-ybt-vm-3178-sa: Still creating... (10m0s elapsed)
Error applying plan:

1 error(s) occurred:

softlayer_virtual_guest.tor01-dev-ybt-vm-3178-sa: Error waiting for virtual machine (24570963) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)
```
### Expected Behavior

It should be possible to configure timeouts for SoftLayer provider:
- to wait for no active transactions
- to wait for public IP available
- to wait for upgrade transactions to appear
### Actual Behavior

Terraform exits with timeout error if time for waiting active transactions takes more than 10 minutes
### Steps to Reproduce

Use SoftLayer provider to create a new virtual guest
### References
- The same related to OpenStack https://github.com/hashicorp/terraform/issues/4129

**Comment by sibblegp** [comment]
This is also important for Bare Metal support.

**Comment by renier** [comment]
The in-tree plugin does not support bare metals. https://github.com/softlayer/terraform-provider-softlayer/ does have support for bare metals and this issue has already been moved over there: https://github.com/softlayer/terraform-provider-softlayer/issues/22
