### ISSUE TITLE
stringer can't import github.com/hashicorp/terraform/terraform ?

### ISSUE THREAD

**Issue by ringods** [hashicorp/terraform#912]
Well, my first contribution to ``terraform`` (& Go) isn't going very smooth. First I bumped into #911, now running ``make`` fails on ``stringer``:

```
AtrisoBook:terraform ringods$ pwd
/Users/ringods/Projects/contributions/go/src/github.com/hashicorp/terraform
AtrisoBook:terraform ringods$ make
go generate ./...
stringer: checking package: field_reader_config.go:9:2: could not import github.com/hashicorp/terraform/terraform (can't find import: github.com/hashicorp/terraform/terraform)
helper/schema/schema.go:14: running "stringer": exit status 1
make: *** [generate] Error 1
AtrisoBook:terraform ringods$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ringods/Projects/contributions/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
AtrisoBook:terraform ringods$ which stringer
/Users/ringods/Projects/contributions/go/bin/stringer
AtrisoBook:terraform ringods$
```

I'm puzzled whether there is something wrong with the terraform build or with my environment. Any help appreciated.

**Comment by mitchellh** [comment]
The only thing I can think of is that this is a $GOPATH issue. Write some code that just says

```
package main 

import(
_ "github.com/hashicorp/terraform/terraform"
)

func main() {}
```

And run it and see if it works. `go run thatfile.go`

**Comment by mitchellh** [comment]
I'm going t close this because its almost certainly not a Terraform issue but I'll keep trying to help yo out there.

**Comment by ringods** [comment]
From within the Terraform project directory:

```
AtrisoBook:terraform ringods$ cat thatfile.go
package main

import(
	_ "github.com/hashicorp/terraform/terraform"
)

func main() {}

AtrisoBook:terraform ringods$ go run thatfile.go
AtrisoBook:terraform ringods$
```

So that seems to work.

**Comment by ringods** [comment]
The closest I come to the problem is this:
http://comments.gmane.org/gmane.comp.lang.go.general/148740
If I look at the sources, the problematic import is the only 4-part one.

**Comment by ringods** [comment]
@mitchellh importing the package on the command line solved my make problem:

```
ringods$ go install github.com/hashicorp/terraform/terraform
ringods$ make
go generate ./...
TF_ACC= go test ./...  -timeout=30s -parallel=4
ok  	github.com/hashicorp/terraform	0.012s
ok  	github.com/hashicorp/terraform/builtin/bins/provider-atlas	0.013s
ok  	github.com/hashicorp/terraform/builtin/bins/provider-aws	0.012s
ok  	github.com/hashicorp/terraform/builtin/bins/provider-azure	0.014s
ok  	github.com/hashicorp/terraform/builtin/bins/provider-cloudflare	0.014s
ok  	github.com/hashicorp/terraform/builtin/bins/provider-cloudstack	0.012s
...
```

Don't know if this is intended, but if so, can this be added to the README.md or the Makefile?

**Comment by mitchellh** [comment]
@ringods That also rings of a GOPATH problem: if you `go install`, it sends it to the $GOPATH. The error message you got above says it can't find it on the $GOPATH. After you did `go install` it worked, which only copies files to the $GOPATH.

So I still think you have some nascent weirdness in your env somehow. :(

**Comment by ringods** [comment]
@mitchellh what I don't understand is that I cloned the terraform repo *in* the ``GOPATH`` as in the README:

```
ringods$ pwd
/Users/ringods/Projects/contributions/go/src/github.com/hashicorp/terraform
```

The subpackage ``terraform`` is there. So what was it copying then, and to where?

**Comment by mitchellh** [comment]
I don't know, I haven't seen it before. :

**Comment by mitchellh** [comment]
:(

**Comment by mitchellh** [comment]
Hah, odd, I just started getting the same thing on a branch that worked yesterday. I wonder if stringer is just broken...

**Comment by ryanuber** [comment]
I've seen this myself. It seems like stringer wants a compiled `github.com/hashicorp/terraform/terraform` package before it will generate further code.

```
$ rm -rf ~/go/pkg/darwin_amd64/github.com/hashicorp/terraform/
$ make generate
go generate ./...
stringer: checking package: field_reader_config.go:9:2: could not import github.com/hashicorp/terraform/terraform (can't find import: github.com/hashicorp/terraform/terraform)
helper/schema/schema.go:14: running "stringer": exit status 1
make: *** [generate] Error 1
$ go install github.com/hashicorp/terraform/terraform
$ make generate
go generate ./...
$
```

**Comment by mitchellh** [comment]
@ryanuber This must be new or something. And I would consider it a bug in stringer I'm just not sure where to report it...

**Comment by ringods** [comment]
@mitchellh @ryanuber my Go experience started yesterday evening, so I'm not of much help, but can you re-read the mailing list thread I point to earlier:

http://comments.gmane.org/gmane.comp.lang.go.general/148740

Specifically, does the answer from Naoki Inada help?

**Comment by mitchellh** [comment]
@ringods That does help. Very strange. I'll play around.
