### ISSUE TITLE
aws-elb change subnet error

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#9120]
## Version:
Terraform v0.7.4

## Senario:
I have a elb with `subnets = ["subnet_a_in_az_a", "subnet_b_in_az_b"]`, and I want to change `subnet_a_in_az_a` to `subnet_c_in_az_a`. The two subnets are in the same availability zone.

## Command:
* `terraform plan`
* `terraform apply`

## Result:
`terraform plan` is ok, like:

```
~ module.sample_elb.aws_elb.elb
    subnets.1288866936: "subnet-e30313ba" => "subnet-e30313ba"
    subnets.3285680907: "subnet-5da0602b" => ""
    subnets.3489851208: "" => "subnet-47249131"

Plan: 0 to add, 1 to change, 0 to destroy.
```

but `terraform apply` error:

```
Error applying plan:

1 error(s) occurred:

* aws_elb.elb: Failure adding ELB subnets: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
	status code: 409, request id: c4c3e205-85e7-11e6-ae32-2b536773e250
```

## Workaround

Firstly delete `subnet_a_in_az_a` in aws console page, and then `terraform plan and apply` it. I guess terraform command does not delete old subnet firstly.

**Comment by catsby** [comment]
Should be fixed in #9131
