### ISSUE TITLE
google_compute_instance_group_manager only allows creating instance groups in same region as google provider region

### ISSUE THREAD

**Issue by oryband** [hashicorp/terraform#9126]
### Terraform Version

```
Terraform v0.7.4
```
### Affected Resource(s)

Please list the resources as a list, for example:
- **google_compute_instance_group_manager**
- google_compute_instance_template
- google_compute_autoscaler
### Terraform Configuration Files

``` hcl
# i've omitted sensitive variables
# there is also some aws configuration included which is not related or relevant
variable "gcp_region" { default = "us-central1" }
provider "google" {
  credentials = "${file("${var.gcp_credentials_file}")}"
  project     = "${var.gcp_project}"
  region      = "${var.gcp_region}"
}

resource "google_compute_instance_template" "frontend-europe-west1" {
  name_prefix = "frontend-prod-europe-west1-"
  region = "europe-west1"
  lifecycle {
    create_before_destroy = true
  }
  machine_type = "n1-standard-1"
  disk { ... }
  network_interface {
    subnetwork = "europe-west1"
    access_config {} # ephemeral
  }
  can_ip_forward = false
  scheduling {
    automatic_restart = true
    on_host_maintenance  = "MIGRATE"
    preemptible = false
  }
  metadata { ... }
}
resource "google_compute_instance_template" "frontend-us-central1" {
  name_prefix = "frontend-prod-us-central1-"
  region = "us-central1"
  lifecycle {
    create_before_destroy = true
  }
  machine_type = "n1-standard-1"
  disk { ... }
  network_interface {
    subnetwork = "us-central1"
    access_config {} # ephemeral
  }
  can_ip_forward = false
  scheduling {
    automatic_restart = true
    on_host_maintenance  = "MIGRATE"
    preemptible = false
  }
  metadata { ... }
}

variable "update_strategy" { default = "NONE" }
variable "named_port" {
  type = "map"
  default = {
    name = "http"
    port = "80"
  }
}
resource "google_compute_instance_group_manager" "frontend-europe-west1-d" {
  name = "frontend-prod-tf-europe-west1-d"
  base_instance_name = "frontend-prod-tf-europe-west1-d"
  instance_template = "${google_compute_instance_template.frontend-europe-west1.self_link}"
  zone = "europe-west1-d"
  update_strategy = "${var.update_strategy}"
  named_port = {
    name = "${var.named_port["name"]}"
    port = "${var.named_port["port"]}"
  }
}
resource "google_compute_instance_group_manager" "frontend-us-central1-c" {
  name = "frontend-prod-tf-us-central1-c"
  base_instance_name = "frontend-prod-tf-us-central1-c"
  instance_template = "${google_compute_instance_template.frontend-us-central1.self_link}"
  zone = "us-central1-c"
  update_strategy = "${var.update_strategy}"
  named_port = {
    name = "${var.named_port["name"]}"
    port = "${var.named_port["port"]}"
  }
}
```
### Debug Output

I've omitted sensitive strings and replaced them with `...`: https://gist.github.com/oryband/41c4e54ff88d92e3366644dc4f9a3db4
### Expected Behavior
- Two instance group managers should be created in zones: `europe-west1-d`, `us-central1-c`.
- Two instance templates should be created in regions: `europe-west1`, `us-central1`.
### Actual Behavior
- Instance templates are created as expected.
- Physically two instance groups managers are indeed created on GCP. However `.tfstate` only shows the one which is in the same region as the provider: `us-central1-c`. If I switch the provider region to `europe-west1-d`, destroy the instance groups and re-apply, the result is reversed: only the `europe-west1-d` group manager is added to `.tfstate`.
### Steps to Reproduce
1. `terraform apply`
### Important Factoids
1. This line in the log:

```
2016/09/29 15:46:32 [DEBUG] plugin: terraform: google-provider (internal) 2016/09/29 15:46:32 [WARN] Removing Instance Group Manager "...-europe-west1-d" because it's gone
```
1. I believe the problem originates [around this code](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance_group_manager.go#L210). The instance group manager resource is fetched only according to the region given in the provider. Since the group manager zone (thus region) is `europe-west1-d` and the provider region is `us-central1`, the resource is not found and thus deleted from Terraform's state. In reality it does exist, but it should be looked up in the right region.
2. I guess the solution would be to infer the region from the `zone` required field in `google_compute_instance_group_manager`, or make `region` a required field as well.
### References
- This might be a hidden cause or relation to #6234 . I had the same problem as described in #6234 even though I had the `create_before_destroy` config enabled. The reason was that Terraform attempted to destroy just the template without deleting the instance group manager first. In my case though it is because Terraform isn't aware that the instance group manager exist due to the bug I described. Mentioning this for the sake of documentation.
- Following from what I said, it might be worth reconsidering adding the `region` field for a different reason, but which will also be used for #8866.
### Final Notes

I banged my head against this issue for two and a half days now. This practically means you can't create instance groups managers (with autoscaling) in more than one region in Google GCP.

**Comment by oryband** [comment]
PING. Can I get any comment on this? This is a pretty big issue, as cross-region autoscaling in Google Cloud isn't currently possible.

**Comment by cblecker** [comment]
There may be some ways to improve the code and handling around group managers, however, have you tried using multiple copies of the google provider to accomplish what you're trying to do?

https://www.terraform.io/docs/configuration/providers.html

You'd create more than one google provider, specifying the region, and then add the provider field to the individual group managers.

**Comment by oryband** [comment]
@cblecker I got it working following your tip, thanks!

However, this is quite misleading and is still a bug. Other resource types e.g. templates, autoscaling groups don't require a separate provider.

**Comment by cblecker** [comment]
@oryband --
I'd like to flush out what part of this might be considered a bug. So the region is a property of the provider at the moment. There's an argument to be made to say that when creating templates, you shouldn't have to specify the region at all because it should be inferred from the provider level. Zones may still be needed optionally, if there is zone specific information like subnetting/IPs that you're specifying in a template.

Same with group managers. You need to specify the zone today, and in the future (#8866) we might have a resource to be able to spin up a group manager in a region that works in multiple zones. However none of this points me to believe that group managers need a new region parameter -- you just create multiple providers with different region parameters, and track them independently. That's why Terraform permits multiple providers.

All of the above is just my opinion though. Would be interested in arguments going the other way.

**Comment by oryband** [comment]
@cblecker there's no mention in the GCP docs in Terraform that says that you should use multiple providers in order to support multiple regions. Also related resource types such as templates and autoscalers don't mention this as well. I've learned Terraform a couple of weeks ago and followed the tutorial completely and it also doesn't mentions this.

My point is that this flow is not obvious and in fact very confusing. I've wasted a couple of days over this, scanning the docs, google and GitHub issues with no explanation how to do this properly.

IMHO group_manager resource configuration should be updated or the docs should be updated with advanced examples.

**Comment by oryband** [comment]
@cblecker also, since the `zone` field is required for `group_manager`, its region can be inferred from the zone, thus the `region` (provided by the `provider` field) shouldn't be required in my case.

Also, `autoscaler` suffers from a similar issue: It requires a `zone` even though it requires a `group_manager` target which already defines a `zone`. This looks like its redundant.

**Comment by oryband** [comment]
@cblecker also, please note that upon calling `destroy`, terraform silently skips `google_compute_autoscaler` when using the default `google` provider, if the autoscaler is in a different region than the provider configuration. I've just wasted another few hours trying to debug this:

1. Created an instance group with autoscaling. The configuration was similar to the above: the `zone` was in a different region that the default `google` provider, and it was using the default provider.
1. Destroyed the resources. The operation succeeded but only the instance group resource was destroyed. The autoscaling resource was *silently* skipped and was still remaining. There is no way to see this in the Google Cloud Console and `gcloud` tool. I've managed to find this resource after a few hours using the Google API Explorer. This is *very* hard to find.
1. Recreating the instance group with autoscaling fails because the autoscaling resource already exists.

There are multiple issues here:
 1. From what I understand, Terraform skipped the autoscaling resource because it used the default `google` provider which uses a different region. Thus the query to Google doesn't return any autoscaler resources, and no autoscaler is destroyed. However, the `.tfstate` file shows that this resource should exist. I expect Terraform to manage this accordingly.
 1. Repeating what I wrote in previous messages, since it applies here as well: I think the docs should clearly state that when launching multi-region infrastructure, a separate unique `google` provider (with a matching `alias`) should be used for all resources in that region. Otherwise this can cause some really hard to find and frustrating errors like I had to deal with.
