### ISSUE TITLE
Amount of support for free ESXi version?

### ISSUE THREAD

**Issue by mrjcleaver** [hashicorp/terraform#9132]
Can someone (tell me or) put a quick outline document together that lists how much support is offered for the free version of ESXi?

Thanks,
   Maritn.

**Comment by mitchellh** [comment]
Hey @mrjcleaver, you may get a better response out of the mailing list or community. I've noticed you've asked a bunch of Qs using issues here, and I've tried to answer many, but we don't really use issues in this way.

Another approach is to take a look at the Terraform docs and cross compare the features there to what you're trying to do with free ESXi.
