### ISSUE TITLE
Remove/purge unmanaged AWS VPC table entries?

### ISSUE THREAD

**Issue by edmundcraske** [hashicorp/terraform#9133]
Hi,
For AWS VPC tables (route, security group, network ACL) it is possible to create an empty table and then separately add entries/rules using the relevant resource. However, when doing this terraform does not ensure that the only entries present are ones that it knows about. I can't see any current way of getting terraform to purge/remove entries that were not added by it.

Not sure whether this would be considered something that should be added to terraform functionality? Or if enforcement of policy would be considered to be the job of some other tool (or indeed ensuring that your account is locked down so that nobody can alter your stuff outside of terraform?)

**Comment by JoeButler99** [comment]
I'm interested in this too. We have aws network acl building from various lists, and static rules so it's not possible to define them all in the single block but we would like to purge 'non managed' rules
