### ISSUE TITLE
Feature Request: List untracked resources

### ISSUE THREAD

**Issue by AMeng** [hashicorp/terraform#9135]
## Feature Request

Add a CLI option to list untracked resources.
## Why:

It would be useful to know what resources exist outside of Terraform. Given that I use a resource type, such as `aws_db_instance`, I would like to list all of my RDS instances that are not tracked in Terraform. A new CLI option would be great for this. Something like `terraform missing` that would inspect the state file and check only for resource types that are actually used in the state file. Or even if the command required a resource type, I would still find it useful. Something like `terraform missing aws_db_instance` to list missing RDS instances.
## Use Cases:
1. **Getting Started**: It is difficult to transition to Terraform because every existing resource must be imported. The `import` command is extremely helpful for this, but the user must know what resources currently exist. This requires using a separate interface to gather the information. Users need to check things like AWS accounts, DataDog alert lists, etc. This is extra work that everyone does to get started. Terraform should help with this.
2. **Monitoring and Alerting**: It would be useful to know when resources are created manually outside of Terraform. For a team to adopt the Terraform workflow, they need to agree which resources are to be managed by Terraform and which are not. Its currently difficult to tell when, say, an Elasticache instance was created outside of Terraform and never imported. A Terraform command to list untracked resources would be helpful for automating alerts around this.
3. **Matching Terraform**: It may be desirable to delete all resources that are not explicitly defined in Terraform, even if they never were. This is not currently possible, but by adding logic for Terraform to understand all resources, something like this can eventually be added as an option to `terraform plan`.

Once the framework is in place, this can be developed on a per-resource basis similar to how the current `import` command only supports specific resources. An error message can be displayed for resource types that are not operational yet.

**Comment by stack72** [comment]
Hi @AMeng 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
