### ISSUE TITLE
Feature Request: VPC Endpoint route table association resource

### ISSUE THREAD

**Issue by coen-hyde** [hashicorp/terraform#9138]
# Feature

A vpc endpoint route table association resource
# Why

So all route tables do not have to exist at the time the endpoint is created.
# My Use Case:

I use Terraform's remote state to logically group infrastructure. Having a this resource would allow me to create the endpoint in one deployment but associate route tables in another.

**Comment by kwilczynski** [comment]
@coen-hyde hi there! Thank you for this! It is not a bad idea at all, actually.

I will have a look into it.

**Comment by supergibbs** [comment]
I'd love this too but I assumed it didn't exist since the AWS CLI doesn't seem to support it:

http://docs.aws.amazon.com/cli/latest/reference/ec2/create-route.html

**Comment by supergibbs** [comment]
Actually could be done with http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-vpc-endpoint.html

**Comment by kwilczynski** [comment]
@coen-hyde @supergibbs hi there! Yes, modifying the VPC endpoint is the key here, especially since the `route_table_ids` are already optional. A clear low hanging fruit. 👍

**Comment by kwilczynski** [comment]
@coen-hyde @supergibbs hi! Apologies for the delay. I have began work in #9244.

**Comment by coen-hyde** [comment]
@kwilczynski awsome! Hardly a delay. I wasn't expecting this to be worked on so soon

**Comment by stack72** [comment]
Closed via #10137
