### ISSUE TITLE
[QA]: implementation about built-in dependency resolution

### ISSUE THREAD

**Issue by AdoHe** [hashicorp/terraform#9142]
FYI. I am a newbie of terraform, and when I look through the website, I noticed this `Built-in dependency resolution`, this seems quite interesting, I want to know how we implement this and want to know the related code.

**Comment by nwalke** [comment]
I believe what you're referring to is Terraform's knowledge of what resources should be created in what order.  All this means is that if you write a configuration that specifies, for example, both a VPC and a subnet, Terraform will ensure that the VPC is created first.  You don't have to worry about making sure that resources are brought up in the correct order to satisfy dependencies, Terraform manages that.

Paul Hinze did an excellent talk if you're interested in learning more about how it manages to do this: https://youtu.be/4Pd9NrZSbGU

**Comment by AdoHe** [comment]
@nwalke thanks for your reply, I would take a look at this video.

**Comment by mitchellh** [comment]
Answered
