### ISSUE TITLE
AWS IAM roles with dots are unsupported

### ISSUE THREAD

**Issue by dtbartle** [hashicorp/terraform#9145]
### Terraform Version
Terraform v0.7.5-dev (built from head)

### Affected Resource(s)
AWS IAM roles with dots (e.g. "foo.bar").

### Terraform Configuration Files
`{"provider":{"aws":{"region":"us-west-1"}},"resource":{"aws_iam_role": {"foo.bar": {"name": "foo.bar", "assume_role_policy": ""}}}}`

### Debug Output
https://gist.github.com/dtbartle/103a1b3d00f7b355b1e086650e8633bb

### Expected Behavior
Dots in AWS IAM roles should be supported. Ideally any valid roles should be supported (http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html), but dots are the only thing tripping me up. Unfortunately, I can't simply change my role names, so this is a hard blocker for my adoption of terraform.

### Actual Behavior
```
Errors:

  * aws_iam_role.foo.bar: foo.bar: resource name can only contain letters, numbers, dashes, and underscores.
```

### Steps to Reproduce
`terraform plan`

**Comment by jen20** [comment]
Hi @dtbartle! Thanks for opening an issue here. There is an important distinction between the _internal_ name of the role resource (which indeed has those restrictions because of things like interpolation syntax) and the AWS-facing role name specified as the `name` argument. So you could do this:

```
resource "aws_iam_role" "foo_bar" {
    name = "foo.bar"
    assume_role_policy = "whatever"
}
```

You'd then refer to the role for interpolation as `${aws_iam_role.foo_bar.name}` and get the AWS name back, for example.

**Comment by rustyShacklefurd** [comment]
I think that this really is a bug.  I've made the change described above and it still fails with this message: 

module root: 1 error(s) occurred:

* resource 'aws_iam_policy_attachment.CloudWatchFullAccess' config: unknown resource 'aws_iam_role.nodes' referenced in variable aws_iam_role.nodes.useast1.prod.example.com.name

here is the code that I'm trying to run:
`resource "aws_iam_role" "nodes_useast1_prod_example_com" {
  name               = "nodes.useast1.prod.example.com"
  assume_role_policy = "${file("../../policies/iam_role/ec2.json")}"
}

resource "aws_iam_policy_attachment" "CloudWatchFullAccess" {
  name       = "CloudWatchFullAccess"
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
  roles      = [
    "${aws_iam_role.graphite.name}",
    "${aws_iam_role.nodes.useast1.prod.example.com.name}",
  ]
}`

From the error output it looks like the parser isn't getting past the first `.` on the name but I'm not sure.  These resource already live in AWS and I'm trying to make it so all AWS resource are tracked and managed by terraform so I'm hoping there's some way to work around this short of excluding it from tracking.
