### ISSUE TITLE
"terraform destroy" fails due to NAT gateway in FAILED state.

### ISSUE THREAD

**Issue by chan-alex** [hashicorp/terraform#9147]
### Terraform Version
$ terraform -v
Terraform v0.7.4

### Affected Resource(s)
aws_nat_gateway
aws_subnet

### Debug Output
[error.txt](https://github.com/hashicorp/terraform/files/502502/error.txt)

### Expected Behavior
"terraform destroy" should have destroy all resources.

### Actual Behavior
Sometimes the creation of a NAT gateway can end up in a FAILED state during a "terraform apply" run. 
From the AWS console, it can be seen that the NAT gateway is in a FAILED state.

This seems to mess up the tfstate file in a way that can sometimes prevent "terraform destroy" from working properly.

### Steps to Reproduce
This is very hard to reproduce as the problem is with the AWS platform, not terraform. Yet it is causing terraform to not work properly.

### References
[error.txt](https://github.com/hashicorp/terraform/files/502502/error.txt)

**Comment by inge4pres** [comment]
Hi @chan-alex 

I remember a similar issue was resolved adding dependency on NAT gateway to the Internet Gateway attached to the VPC.
