### ISSUE TITLE
github_team_repository not persisted to state?

### ISSUE THREAD

**Issue by publysher** [hashicorp/terraform#9149]
My github_team_repository resources do not show up in `terraform show`. Whenever I create a fresh plan, they are indicated as new. 
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- github_team_repository
### Terraform Configuration Files

``` hcl
resource "github_team" "frontend" {
  name    = "Frontend"
  privacy = "closed"
}

resource "github_team_repository" "frontend_frontend" {
  team_id    = "${github_team.frontend.id}"
  repository = "frontend"
  permission = "push"
}
```
### Expected Behavior

The first time, `terraform plan` should show:

```
+ github_team.frontend
+ github_team_repository.frontend_frontend
```

After applying, `terraform plan` should indicate that everything is in sync. 

After applying, `terraform show | grep frontend_frontend` should show the github_team_repository resource. 
### Actual Behavior

After applying, `terraform plan` shows:

```
+ github_team_repository.frontend_frontend
```

`terraform apply` will re-create the resource. 

`terraform show` does not show the resource.

**Comment by hiroqn** [comment]
i got same bug
