### ISSUE TITLE
aws_s3_bucket_notification failing

### ISSUE THREAD

**Issue by magic69** [hashicorp/terraform#9156]
### Terraform Version

0.7.4
### Affected Resource(s)

`aws_s3_bucket_notification.bucket_notification`
### Terraform Configuration Files

`resource "aws_s3_bucket_notification" "bucket_notification" {
        bucket = "${aws_s3_bucket.XXXX.id}"
        lambda_function {
                lambda_function_arn = "${aws_lambda_function.XXXX.arn}"
                events = ["s3:ObjectCreated:*"]
        }
}`
### Panic Output

```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket_notification.bucket_notification: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.4
    Resource ID: aws_s3_bucket_notification.bucket_notification
    Mismatch reason: attribute mismatch: lambda_function.0.lambda_function_arn
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"lambda_function.0.lambda_function_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:lambda:us-west-
2:940119295925:function:***", New:"${aws_lambda_function.****.arn}", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destr
oy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyTainted:false}
```

I am trying to modify a lambda group to use VPC configuration when this error occurs, If I delete the notification and let TF recreate it it will work fine.
### Expected Behavior

The bucket notification resource should not generate a change as it was not changed.
### Actual Behavior

Not really sure.

**Comment by mitchellh** [comment]
Hello! This should be fixed in later versions of Terraform. Please try again. Thanks!
