### ISSUE TITLE
Downgrading ec2 instance type from t2.small to t2.micro "forces new resource"

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#9157]
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- aws_instance
### Terraform Configuration Files

``` hcl
resource "aws_instance" "hsreplaynet_web_01" {
    ami = "${lookup(var.amis, var.region)}"
    instance_type = "t2.small"
    key_name = "${aws_key_pair.hsreplay_provisioner_auth.id}"
    security_groups = ["${var.prod_security_group_name}"]
    tags {
        name = "hsreplaynet_web_01"
        class = "hsreplaynet"
    }
}
```

Downgrading the `instance_type` will force a new resource. Upgrading it however, will not. I have seen this on several different instance types such as t2.small, t2.large, m4.xlarge and m4.2xlarge.

I have also verified that I was able to manually go in the AWS console, stop the instance, downgrade it and restart the instance without having to recreate it.

**Comment by apparentlymart** [comment]
Hi @jleclanche!

Currently Terraform doesn't have a way to model actions that require temporarily stopping an instance. This is being discussed over in #1579. I think robust support for managing the multi-step process of stopping, altering and re-starting will be a pre-requisite for this, though this would definitely be a great additional feature to support once that's in place.

**Comment by jleclanche** [comment]
@apparentlymart Are we talking about the same thing? Terraform does support *upgrading* the instance, which has the exact same prerequisite (stopping and then restarting the instance). Or am I missing something?

**Comment by apparentlymart** [comment]
If by "upgrading" you mean replacing `instance_type` with another value that is somehow "bigger" than the current value, I am not aware that Terraform is able to do that without destroying the image. Are you sure that's true? A quick check of the code suggests to me that *any* change to `instance_type` will "force new resource", regardless of what direction you're changing it.

I think I must not be understanding what you are asking about here... could you perhaps show an example output of `terraform plan` for the "upgrade" and "downgrade" actions you're talking about, so I can understand precisely what configuration changes you're thinking of?

**Comment by jleclanche** [comment]
This is the weirdest thing. I'm changing a `m4.large` to `m4.2xlarge` and now I *do* see "forces new resource". But I can promise you that I ran that upgrade before, and it *didn't* force a new resource. In fact, I might even be able to dig the terraform plan files on Jenkins as I keep those around for some time.

But yes, you got it, that's what I've been seeing: instance_type "upgrades" are fine, but downgrades force a new resource. Although now I'm seeing downgrades everywhere. Hrm.

Also worth noting I don't see this "forces new resource" problem on RDS instances at all.

**Comment by FlorinAndrei** [comment]
Terraform devs: Please keep this issue open until TF can properly handle stop/start/restart of instances - as described in https://github.com/hashicorp/terraform/issues/1579 and similar.

Once we can stop/start instances, then changing the instance type (or size) without destroy/recreate should be easy to handle from within Terraform.
