### ISSUE TITLE
ID is not changed - Writing Custom Terraform Providers

### ISSUE THREAD

**Issue by SydOps** [hashicorp/terraform#9166]
### Terraform Version

Terraform v0.7.0
### Affected Resource(s)
- own provider
### Terraform Configuration Files

```
func resourceServerCreate(d *schema.ResourceData, m interface{}) error {
    address := d.Get("address").(string)
    d.SetId(address + "!")
    return nil
}

$ cat test.tf
resource "dummy_server" "foo" {
    address = "hashicorp.com"
}
```
### Expected Behavior

What should have happened?

both `id` and `address` should be updated. 
### Actual Behavior

What actually happened?

Change the address in `test.tf`, and `terraform apply`, in terraform.tfstate, the address is changed, but not `id`
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1.  `terraform apply`
2. change address from "hashicorp.com" to "mitchellh.com"
3. `terraform apply`
4. check terraform.tfstate

```
$ cat terraform.tfstate
{
    "version": 3,
    "terraform_version": "0.7.0",
    "serial": 5,
    "lineage": "fe3b4d2d-8df6-4f91-a6fc-0d7e3c723945",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "dummy_server.foo": {
                    "type": "dummy_server",
                    "primary": {
                        "id": "hashicorp.com!",
                        "attributes": {
                            "address": "mitchellh.com",
                            "id": "hashicorp.com!"
                        }
                    }
                }
            }
        }
    ]
}
```

I have to `terraform taint` on the resource and apply again to get the expect result. 
### References

https://www.hashicorp.com/blog/terraform-custom-providers.html

**Comment by SydOps** [comment]
upgrade terraform to 0.7.4, get same result.

So should `id` be changed or not?

**Comment by dmportella** [comment]
I have this issue too with the consul provider

**Comment by apparentlymart** [comment]
Hi @SydOps!

Does your resource also have an `Update` implementation? If it does, then it will be that function that handles the change rather than your `Create`, causing your `SetId` call not to run. You'd need to duplicate the `SetId` call in the `Update` function.

**Comment by mitchellh** [comment]
Closing due to lack of response, but @apparentlymart is spot on.

**Comment by dmportella** [comment]
@mitchellh i dont even remember why i said i had this issue....
