### ISSUE TITLE
Add note about using US East 1 ACM certs for CloudFront

### ISSUE THREAD

**Issue by robert-stuttaford** [hashicorp/terraform#9170]
Just a gotcha that could help some folks in the future.

According to https://forums.aws.amazon.com/thread.jspa?messageID=722324, ACM certs should be generated in US East 1 if they are to be used with CloudFront.

It'd save folks time if https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#acm_certificate_arn had a note to this effect.

**Comment by stack72** [comment]
Closed via 9190
