### ISSUE TITLE
Cloudfront acceptance tests not working due to missing logging bucket

### ISSUE THREAD

**Issue by PayscaleNateW** [hashicorp/terraform#9176]
### Terraform Version
7.5-dev

### Affected Resource(s)
- aws_cloudfront_distribution

### Debug Output
```
testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
		
* aws_cloudfront_distribution.s3_distribution: InvalidArgument: The S3 bucket that you specified for CloudFront logs doesn't exist: mylogs.369808094885234229.s3.amazonaws.com
status code: 400, request id: 61a3ffe8-88fd-11e6-bea0-cd141793b819

```

### Expected Behavior
Acceptance tests should run and create s3 buckets and cloudfront distributions

### Actual Behavior
I get an error because the mylogs bucket does not exist, thus the cloudfront distributions can't be created.

### Steps to Reproduce
1. run the cloudfront acceptance tests from the master branch: `make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestAccAWSCloudFrontDistribution'`

### Important Factoids
- I ran into an issue trying to fix it because I was including .s3.amazonaws.com in the bucket name. I do not think this should be in the bucket name, just in the logging_config bucket value

### References
- I think I have a fix for this here: #9175 (if this is actually a bug others are experiencing)

**Comment by stack72** [comment]
Closed via #9175
