### ISSUE TITLE
Not an issue but a problem and requesting a work around

### ISSUE THREAD

**Issue by ste-bah** [hashicorp/terraform#9179]
We are using the following snippits in our VPC module which works in 0.6.16 and is going to be problematic upgrading to 0.7 as the VPC module we have created is used with multiple production and non production VPC's. These can have 0 private subnets and up to 6 or with 0 nat gateways. Currently we create the nat gateways likes so:

```
resource "aws_nat_gateway" "nat" {
allocation_id = "${element(aws_eip.nat.*.id, count.index)}"
subnet_id     = "${element(split(",", var.public_subnet_ids), count.index)}"
count         = "${var.nat_gateways_count}"
depends_on = ["aws_internet_gateway.igw"]
}
```
Then we allocate a nat gateway for each private subnet network route table like so :

```
resource "aws_route" "nat_gateway" {
route_table_id         = "${element(aws_route_table.private.*.id, count.index)}"
destination_cidr_block = "0.0.0.0/0"
nat_gateway_id         = "${element(aws_nat_gateway.nat.*.id, count.index)}"
count                  = "${var.pri_count}"
depends_on             = ["aws_route_table.private"]
}
```

this however now leads to the following error in 0.7.X when there are 0 nat gateways listed when running terraform plan or terraform apply:

```
Error running plan: 2 error(s) occurred:

element: element() may not be used with an empty list in: ${element(aws_nat_gateway.nat.*.id, count.index)}

element: element() may not be used with an empty list in: ${element(aws_nat_gateway.nat.*.id, count.index)}
```
Is there are work around available for this scenario which is not destructive for existing vpc's and existing state files ?

**Comment by ste-bah** [comment]
It's not the end of the world as I can always add a nat gateway to get around the error in 0.7 but I'd prefer to be able to mimic the behaviour of 0.6.16 if possible.

**Comment by rumenvasilev** [comment]
I believe your problem is in the count definition. If you assign the same value to count on both resources, you should have no problems.
I guess you scenario is:
```
var.nat_gateways_count = 0
var.pri_count = 2
```
This is how i did it:
```
resource "aws_nat_gateway" "mod" {
  count = "${length(split(",", var.azs))}"
  allocation_id = "${element(aws_eip.natgw.*.id, count.index)}"
  subnet_id = "${element(aws_subnet.public.*.id, count.index)}"
}
resource "aws_route" "default_private" {
  count = "${length(split(",", var.azs))}"
  route_table_id = "${element(aws_route_table.private.*.id, count.index)}"
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id = "${element(aws_nat_gateway.mod.*.id, count.index)}"
}
```
Mind that count value is the same in both resources.

**Comment by ste-bah** [comment]
Hi @rumenvasilev  I've re-worked everything doing exactly that and tested it in a test environment and all seems ok with no major disruptive changes - I'll close this question!
