### ISSUE TITLE
[AWS] Terraform should gracefully handle changes to launch configurations

### ISSUE THREAD

**Issue by Tomino2112** [hashicorp/terraform#9189]
Making changes to launch configurations on AWS is at the moment painful business. You have to clone your configuration, make whatever changes necessary, then assign this configuration to auto scaling group, then clone it again with the same name as before and then re-assign again. 

Terraform should handle all this under the hood.

At the moment, it just gives 400 error:

```
 aws_launch_configuration.api_streaming: Error creating launch configuration: AlreadyExists: Launch Configuration by this name already exists - A launch configuration already exists with the name LC-Api-Streaming
        status code: 400, request id: 702c4bc0-897c-11e6-b121-8d079b108564
```

**Comment by Tomino2112** [comment]
Also, launch configuration do not refresh security groups correctly. 
![2016-10-03_163429](https://cloud.githubusercontent.com/assets/1140217/19043319/873f4276-8987-11e6-86dc-c68963fdef22.jpg)
![2016-10-03_163420](https://cloud.githubusercontent.com/assets/1140217/19043318/873d2838-8987-11e6-9080-3cb132621891.jpg)

and in tfstate
```
...
"security_groups.#": "3",
"security_groups.199840254": "sg-46c22a20",
"security_groups.2170208753": "sg-40c22a26",
"security_groups.4174098932": "sg-42c22a24",
...
```

**Comment by stack72** [comment]
Hi @Tomino2112 

Please can you tell me if you are using a `name` in your AWS Launch configuration?

Thanks

Paul

**Comment by Tomino2112** [comment]
hi @stack72 

Here is one of our launch confs:

```
resource "aws_launch_configuration" "api_streaming" {
	name = "LC-Api-Streaming"
	image_id = "${var.aws_amis["streaming"]}"
	instance_type = "m3.medium" // @todo To variables
	key_name = "${var.key_name}"
	security_groups = [
		"${aws_security_group.openvpnssh.id}",
		"${aws_security_group.api_streaming.id}",
		"${aws_security_group.deploy_ssh.id}",
		"${aws_security_group.mysql_connection.id}",
		"${aws_security_group.redis_connection.id}",
	]
	associate_public_ip_address = false
	enable_monitoring = true
	iam_instance_profile = "${aws_iam_instance_profile.api_streaming.name}"

	lifecycle {
		create_before_destroy = true
	}
}
```

PS: Looking at it now, now sure what the `lifecycle` supposed to do - its about 2 months since I last touched this

**Comment by stack72** [comment]
Hi @Tomino2112 

This is indeed the issue then. AWS doesn't allow a Launch Config to be updated so in Terraform we introduced the name_prefix to allow this to happen

This is in the documentation to suggest the best way to handle this

https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

P.

**Comment by Tomino2112** [comment]
@stack72  Indeed, I didn't see the `name_prefix` option, that seems to work. Any chance that when you make changes to LC it could reflect on currently running instances? Example would be the security groups

**Comment by stack72** [comment]
Hi @Tomino2112 

I'm not sure what you mean? If you are using a Launch Config, then you are most probably also using an AutoScaling Group

If you make changes to the LaunchConfig then the next time instances are launched, they will get the latest LaunchConfig. There is currently no way in Terraform to be able to trigger the update of downstream resource as technically they don't actually need to be linked (i.e. you can create a launch config and not have an asg)

Is this what you mean?

Paul

**Comment by Tomino2112** [comment]
Yes,  I am talking about already running instances,  not future created instances. I understand whats the issue,  just thought if there would be some possibility.  It adds manual step when changing security groups for launch configuration.  That becomes quite time consuming whwn you have 10 instances in each group.  Of course some sort of custom script with boto will be able to help..

**Comment by majormoses** [comment]
I can see the value of such an option to attach missing security groups. That being said it feels like a rabbit hole to me. If we wanted to do what is being proposed for say user data or AMI we now have to shutdown the instance modify it and bring it back up. This starts to get messy, say we are talking about your data tier this kind of orchestration to do a rolling restart should not live in TF. In addition as paul mentioned you can have a launch config that has no scaling group, there are just a lot of potential gotchas now that we would open up by trying to accommodate this.

I prefer knowing that anything someone does to launch config and asg will never bring down an instance that was previously attached. Danger would now come from knowledge (and therefore lack of) of the resource api (aws-sdk) as opposed to now you know that it is always a safe operation such as security group attachment.

I think that if you want to update these right away then you should have something external to TF bring up replacement instances or modifications in whatever way is safe. This is the approach I have seen at the last 2 companies using terraform.
