### ISSUE TITLE
Re-allow ability to declare/define members of hash in multiple files.

### ISSUE THREAD

**Issue by voltechs** [hashicorp/terraform#9193]
Hi all. I'm in the process of updating from 0.6.x to 0.7.x (0.7.4 specifically)

Really struggling with the new variable handling. Please fix this.
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)

variables
### Terraform Configuration Files

``` hcl
## variables.tf
variable "env" {
    default = {
        my_secret = "((SH*129hsN(Uhs9A78sdh@"
        something_else = "whatever"
    }
}
```

``` hcl
## secrets.tfvars

# before 0.7.x
env.my_secret = "((SH*129hsN(Uhs9A78sdh@"
# env.something_else == "whatever"

# after 0.7.x

env = {
    my_secret = "((SH*129hsN(Uhs9A78sdh@"
}
# env.something_else == undefined/nil/null
```
### Debug Output

N/A
### Panic Output

N/A
### Expected Behavior

By forcing map variables to be defined in the new 0.7.x fashion, you are limiting the dynamic use of the map in multiple files. We can no longer define/redefine just one variable without needing to know the values of the rest of the variables. I expect to be
### Actual Behavior

By being forced to define/redefine the top level map-variable (`env = { ... }`) it's no longer to define some variables in one file and others in another.
### Steps to Reproduce
1. Define two files for variables
2. Define variables similar to examples above
3. Pass variable files into `terraform plan`
4. Watch it fail and be disappointed.
### Important Factoids

N/A
### References

N/A

**Comment by jbardin** [comment]
Hi @voltechs,

Sorry about the issue you're having here. While I'm not able to exactly reproduce your issue, I can give you an example that works to start with.

With the following 3 files:

```
# main.tf
output something {
	value = "${var.env["something_else"]}"
}

output secret {
	value = "${var.env["my_secret"]}"
}
```

```
# variables.tf
variable env {
    default = {
        my_secret = "original value"
        something_else = "whatever"
    }
}
```

```
# terraform.tfvars
env = {
	my_secret = "overridden"
}
```

Running `terraform apply` will show the following:

```
Outputs:

secret = overridden
something = whatever
```

If you rename `terraform.tfvars` to `secrets.tfvars`, it requires explicitly passing that as a `-var-file`

```
$ mv terraform.tfvars secrets.tfvars
$ terraform apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

secret = original value
something = whatever
$ terraform apply -var-file secrets.tfvars
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

secret = overridden
something = whatever
```

If you're still having an issue, or are not sure how to apply this, can you provide a self-contained config to demonstrate the behavior your'e seeing?

**Comment by bitpusher-real** [comment]
Having the same problem. @jbardin Your example works at advertised, but fails if you push the map down into a module:

    # main.tf

    module foo {
      source = "foo"
      test = "${var.env}"
    }

    output secret {
      value = "${module.foo.secret}"
    }

    output something {
      value = "${module.foo.something}"
    }


    # foo/main.tf

    variable "test" {
      default = {
        secret = "original"
        something = "whatever"
      }
    }

    output secret {
      value = "${var.test["secret"]}"
    }

    output something {
      value = "${var.test["something"]}"
    }


    $ terraform apply

    Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

    Outputs:

    secret = override


The output for `something` has completely has disappeared, with no errors.

**Comment by mitchellh** [comment]
The original issue here I believe is a dup of #8219 and should be fixed with the referenced PR there. Maps are now merged across var files.
