### ISSUE TITLE
Connect to existing resources not created through terraform

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#92]
I'm wondering if there's a supported way to bootstrap the state file in an existing environment.  I'm imagining basically a `terraform apply --noop` that still outputs a state file as if it had succeeded so that the next `terraform plan` would show no changes but future changes could be made via terraform. I guess it'd need a way to associate the existing instance ids with the noop-created instances.

Curious if anything like this exists or is in the works.

**Comment by phinze** [comment]
#581 has become the de-facto home for this request lately, so closing this as a dup even though it's older
