### ISSUE TITLE
Deleting AWS API GW domain base path mapping with the empty base path fails

### ISSUE THREAD

**Issue by rafal-gancarz-opencredo** [hashicorp/terraform#9212]
Hi there,

After creating a base path mapping with an empty base path (an optional attribute) for the custom domain TF doesn't seem to be able to destroy it.

This is because the API (http://docs.aws.amazon.com/apigateway/api-reference/link-relation/basepathmapping-delete/) requires to use the special value of `(none)` for the path variable `base_path` to denote the empty base path and Terraform doesn't set the path variable correctly.

Terraform version: 0.7.4
Affected resource: aws_api_gateway_base_path_mapping
Debug output: https://gist.github.com/rafal-gancarz-opencredo/5ca8a05cf600b0947519a94f0457d566

**Comment by d2chau** [comment]
I too have verified this. 

The AWS cli also requires a parameter of "(none)" passed in. 
`aws apigateway delete-base-path-mapping --domain-name "ignitor-alpha.readytalk.com" --base-path "(none)"`

If it is ran with an empty string,
`aws apigateway delete-base-path-mapping --domain-name "ignitor-alpha.readytalk.com" --base-path ""`
The response is `No JSON object could be decoded`

**Comment by Ninir** [comment]
Hi guys,
Made some work on this [here](https://github.com/hashicorp/terraform/pull/10177). Hope it will fit :)
