### ISSUE TITLE
terraform state show panic

### ISSUE THREAD

**Issue by matthewbrahms** [hashicorp/terraform#9218]
### Terraform Version
Terraform version: 0.7.4

### Affected Resource(s)
terraform state show

### Panic Output
https://gist.github.com/matthewbrahms/8311922f2474b95df4fa106f4cb61fc1

### Expected Behavior
Output the terraform state

### Actual Behavior
Crash output

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform  state show`

**Comment by jbardin** [comment]
Hi @matthewbrahms, 

Thanks for reporting the issue. Can you confirm if this still happens with v0.7.5? 
If it is still a problem, do you happen to have a configuration that we can use to reproduce the issue? If you have a state file without any sensitive information, that would help too.

Thanks

**Comment by matthewbrahms** [comment]
@jbardin It is no longer doing this on v0.7.5.  Thanks for checking in.  Let me know if I need to provide anything else.

**Comment by jbardin** [comment]
Great! I think this was taken care of in the `github.com/mitchellh/cli` package. I'll mark this as closed.
