### ISSUE TITLE
Access provider attributes

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#9221]
Is it possible to access output attributes for a provider? I have made an `ec2_ondemand_price` module which looks up the current EC2 on-demand price for a given region and instance type. We use this module to set our spot prices equal to the on demand price. The problem I have at the moment is that my `ec2_ondemand_price` module needs to know the AWS region, but it should be able to query this from the provider rather than needing to be passed in as a variable.

**Comment by joshuaspence** [comment]
An alternative to being able to access provider attributes would be an `aws_region` data source, I suppose.

**Comment by joshuaspence** [comment]
Given that we currently do this, #5480 would be another solution to my problem.

```
provider "aws" {
  region = "${var.region}"
}
```

**Comment by apparentlymart** [comment]
Hi @joshuaspence!

The patch I've been working on over in #6819 has a potential solution to this, which would work as follows:

```hcl
data "aws_region" "current" {
  current = true
}
```

**Comment by joshuaspence** [comment]
Thanks for the pointer

**Comment by stack72** [comment]
Hi @joshuaspence 

Does #6819 solve your issue?

Paul

**Comment by joshuaspence** [comment]
Yes, it does. Thanks!
