### ISSUE TITLE
Specifying version_label for aws_elastic_beanstalk_environment

### ISSUE THREAD

**Issue by joeharrison714** [hashicorp/terraform#9223]
Hi. In the aws cli, when creating a elastic beanstalk environment, you can specify a version label of the application you want to deploy. If not specified, the default is to deploy a sample application.

Currently, there does not appear to be a way to specify the version label when using aws_elastic_beanstalk_environment in terraform. Would it be possible for this to be added?

Here is the corrosponding section in the cli docs:
http://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/create-environment.html

> --version-label (string)
> The name of the application version to deploy.
> If the specified application has no associated application versions, AWS Elastic Beanstalk update-environment returns an InvalidParameterValue error.
> Default: If not specified, AWS Elastic Beanstalk attempts to launch the sample application in the container.

**Comment by dharrisio** [comment]
@joeharrison714 This will be possible once #5770 is merged.

**Comment by joeharrison714** [comment]
any idea when that will be?

**Comment by dharrisio** [comment]
@stack72 This issue can be closed as well (#5770).

**Comment by stack72** [comment]
Closed via #5770
