### ISSUE TITLE
Terraform reloads after successful apply, no changes made, still shows 3 more changes

### ISSUE THREAD

**Issue by karthickk100** [hashicorp/terraform#9225]
I am running the latest terraform version(v0.7.4), I apply terraform, it works fine with no errors, then I try to plan, it shows 3 to change. Nothing has changed in the config, but it still shows as 3 to change. I see some solutions in the previous thread, like making a lower case of protocol("tcp") and adding lifecycle, nothing has helped. Here is my output and config file. Let me know if you need more. This is killing us, not letting us proceed.

I have security group and security group rules as showm below. aws_security_group_rule as well as shown below.
I have my security group xyz_sg_abc at the bottom.

33m~ aws_security_group.xyz_sg_abc
[0m    egress.#:                                      "14" => "4"
    egress.1238134219.cidr_blocks.#:               "0" => "0"
    egress.1238134219.from_port:                   "3389" => "3389"
    egress.1238134219.prefix_list_ids.#:           "0" => "0"
    egress.1238134219.protocol:                    "udp" => "udp"
    egress.1238134219.security_groups.#:           "1" => "1"
    egress.1238134219.security_groups.3352223863:  "sg-940721ee" => "sg-940721ee"
    egress.1238134219.self:                        "false" => "false"
    egress.1238134219.to_port:                     "3389" => "3389"
    egress.136061899.cidr_blocks.#:                "0" => "0"
    egress.136061899.from_port:                    "443" => "443"
    egress.136061899.prefix_list_ids.#:            "0" => "0"
    egress.136061899.protocol:                     "tcp" => "tcp"
    egress.136061899.security_groups.#:            "1" => "1"
    egress.136061899.security_groups.2876704322:   "sg-b80721c2" => "sg-b80721c2"
    egress.136061899.self:                         "false" => "false"
    egress.136061899.to_port:                      "443" => "443"
    egress.1467575756.cidr_blocks.#:               "0" => "0"
    egress.1467575756.from_port:                   "61620" => "0"
    egress.1467575756.prefix_list_ids.#:           "0" => "0"
    egress.1467575756.protocol:                    "tcp" => ""
    egress.1467575756.security_groups.#:           "1" => "0"
    egress.1467575756.security_groups.2169191079:  "sg-c70127bd" => ""
    egress.1467575756.self:                        "false" => "false"
    egress.1467575756.to_port:                     "61620" => "0"
    egress.149989598.cidr_blocks.#:                "0" => "0"
    egress.149989598.from_port:                    "80" => "0"
    egress.149989598.prefix_list_ids.#:            "0" => "0"
    egress.149989598.protocol:                     "tcp" => ""
    egress.149989598.security_groups.#:            "2" => "0"
    egress.149989598.security_groups.2980972767:   "sg-c20127b8" => ""
    egress.149989598.security_groups.4111187599:   "sg-c80127b2" => ""
    egress.149989598.self:                         "false" => "false"
    egress.149989598.to_port:                      "80" => "0"
    egress.187082154.cidr_blocks.#:                "0" => "0"
    egress.187082154.from_port:                    "9042" => "0"
    egress.187082154.prefix_list_ids.#:            "0" => "0"
    egress.187082154.protocol:                     "tcp" => ""
    egress.187082154.security_groups.#:            "1" => "0"
    egress.187082154.security_groups.2169191079:   "sg-c70127bd" => ""
    egress.187082154.self:                         "false" => "false"
    egress.187082154.to_port:                      "9042" => "0"
    egress.2195547251.cidr_blocks.#:               "0" => "0"
    egress.2195547251.from_port:                   "22" => "0"
    egress.2195547251.prefix_list_ids.#:           "0" => "0"
    egress.2195547251.protocol:                    "tcp" => ""
    egress.2195547251.security_groups.#:           "1" => "0"
    egress.2195547251.security_groups.2169191079:  "sg-c70127bd" => ""
    egress.2195547251.self:                        "false" => "false"
    egress.2195547251.to_port:                     "22" => "0"
    egress.3400316176.cidr_blocks.#:               "0" => "0"
    egress.3400316176.from_port:                   "7000" => "0"
    egress.3400316176.prefix_list_ids.#:           "0" => "0"
    egress.3400316176.protocol:                    "tcp" => ""
    egress.3400316176.security_groups.#:           "1" => "0"
    egress.3400316176.security_groups.2169191079:  "sg-c70127bd" => ""
    egress.3400316176.self:                        "false" => "false"
    egress.3400316176.to_port:                     "7000" => "0"
    egress.357529062.cidr_blocks.#:                "0" => "0"
    egress.357529062.from_port:                    "9160" => "0"
    egress.357529062.prefix_list_ids.#:            "0" => "0"
    egress.357529062.protocol:                     "tcp" => ""
    egress.357529062.security_groups.#:            "1" => "0"
    egress.357529062.security_groups.2169191079:   "sg-c70127bd" => ""
    egress.357529062.self:                         "false" => "false"
    egress.357529062.to_port:                      "9160" => "0"
    egress.3827110669.cidr_blocks.#:               "0" => "0"
    egress.3827110669.from_port:                   "80" => "80"
    egress.3827110669.prefix_list_ids.#:           "0" => "0"
    egress.3827110669.protocol:                    "tcp" => "tcp"
    egress.3827110669.security_groups.#:           "1" => "1"
    egress.3827110669.security_groups.2876704322:  "sg-b80721c2" => "sg-b80721c2"
    egress.3827110669.self:                        "false" => "false"
    egress.3827110669.to_port:                     "80" => "80"
    egress.3929861091.cidr_blocks.#:               "0" => "0"
    egress.3929861091.from_port:                   "61621" => "0"
    egress.3929861091.prefix_list_ids.#:           "0" => "0"
    egress.3929861091.protocol:                    "tcp" => ""
    egress.3929861091.security_groups.#:           "1" => "0"
    egress.3929861091.security_groups.2169191079:  "sg-c70127bd" => ""
    egress.3929861091.self:                        "false" => "false"
    egress.3929861091.to_port:                     "61621" => "0"
    egress.4211759511.cidr_blocks.#:               "0" => "0"
    egress.4211759511.from_port:                   "1433" => "0"
    egress.4211759511.prefix_list_ids.#:           "0" => "0"
    egress.4211759511.protocol:                    "tcp" => ""
    egress.4211759511.security_groups.#:           "1" => "0"
    egress.4211759511.security_groups.3551840219:  "sg-cc0127b6" => ""
    egress.4211759511.self:                        "false" => "false"
    egress.4211759511.to_port:                     "1433" => "0"
    egress.680397075.cidr_blocks.#:                "0" => "0"
    egress.680397075.from_port:                    "7001" => "0"
    egress.680397075.prefix_list_ids.#:            "0" => "0"
    egress.680397075.protocol:                     "tcp" => ""
    egress.680397075.security_groups.#:            "1" => "0"
    egress.680397075.security_groups.2169191079:   "sg-c70127bd" => ""
    egress.680397075.self:                         "false" => "false"
    egress.680397075.to_port:                      "7001" => "0"
    egress.808665337.cidr_blocks.#:                "0" => "0"
    egress.808665337.from_port:                    "7199" => "0"
    egress.808665337.prefix_list_ids.#:            "0" => "0"
    egress.808665337.protocol:                     "tcp" => ""
    egress.808665337.security_groups.#:            "1" => "0"
    egress.808665337.security_groups.2169191079:   "sg-c70127bd" => ""
    egress.808665337.self:                         "false" => "false"
    egress.808665337.to_port:                      "7199" => "0"
    egress.922980179.cidr_blocks.#:                "0" => "0"
    egress.922980179.from_port:                    "3389" => "3389"
    egress.922980179.prefix_list_ids.#:            "0" => "0"
    egress.922980179.protocol:                     "tcp" => "tcp"
    egress.922980179.security_groups.#:            "1" => "1"
    egress.922980179.security_groups.3352223863:   "sg-940721ee" => "sg-940721ee"
    egress.922980179.self:                         "false" => "false"
    egress.922980179.to_port:                      "3389" => "3389"
    ingress.#:                                     "14" => "4"
    ingress.1238134219.cidr_blocks.#:              "0" => "0"
    ingress.1238134219.from_port:                  "3389" => "3389"
    ingress.1238134219.protocol:                   "udp" => "udp"
    ingress.1238134219.security_groups.#:          "1" => "1"
    ingress.1238134219.security_groups.3352223863: "sg-940721ee" => "sg-940721ee"
    ingress.1238134219.self:                       "false" => "false"
    ingress.1238134219.to_port:                    "3389" => "3389"
    ingress.136061899.cidr_blocks.#:               "0" => "0"
    ingress.136061899.from_port:                   "443" => "443"
    ingress.136061899.protocol:                    "tcp" => "tcp"
    ingress.136061899.security_groups.#:           "1" => "1"
    ingress.136061899.security_groups.2876704322:  "sg-b80721c2" => "sg-b80721c2"
    ingress.136061899.self:                        "false" => "false"
    ingress.136061899.to_port:                     "443" => "443"
    ingress.1467575756.cidr_blocks.#:              "0" => "0"
    ingress.1467575756.from_port:                  "61620" => "0"
    ingress.1467575756.protocol:                   "tcp" => ""
    ingress.1467575756.security_groups.#:          "1" => "0"
    ingress.1467575756.security_groups.2169191079: "sg-c70127bd" => ""
    ingress.1467575756.self:                       "false" => "false"
    ingress.1467575756.to_port:                    "61620" => "0"
    ingress.149989598.cidr_blocks.#:               "0" => "0"
    ingress.149989598.from_port:                   "80" => "0"
    ingress.149989598.protocol:                    "tcp" => ""
    ingress.149989598.security_groups.#:           "2" => "0"
    ingress.149989598.security_groups.2980972767:  "sg-c20127b8" => ""
    ingress.149989598.security_groups.4111187599:  "sg-c80127b2" => ""
    ingress.149989598.self:                        "false" => "false"
    ingress.149989598.to_port:                     "80" => "0"
    ingress.187082154.cidr_blocks.#:               "0" => "0"
    ingress.187082154.from_port:                   "9042" => "0"
    ingress.187082154.protocol:                    "tcp" => ""
    ingress.187082154.security_groups.#:           "1" => "0"
    ingress.187082154.security_groups.2169191079:  "sg-c70127bd" => ""
    ingress.187082154.self:                        "false" => "false"
    ingress.187082154.to_port:                     "9042" => "0"
    ingress.2195547251.cidr_blocks.#:              "0" => "0"
    ingress.2195547251.from_port:                  "22" => "0"
    ingress.2195547251.protocol:                   "tcp" => ""
    ingress.2195547251.security_groups.#:          "1" => "0"
    ingress.2195547251.security_groups.2169191079: "sg-c70127bd" => ""
    ingress.2195547251.self:                       "false" => "false"
    ingress.2195547251.to_port:                    "22" => "0"
    ingress.3400316176.cidr_blocks.#:              "0" => "0"
    ingress.3400316176.from_port:                  "7000" => "0"
    ingress.3400316176.protocol:                   "tcp" => ""
    ingress.3400316176.security_groups.#:          "1" => "0"
    ingress.3400316176.security_groups.2169191079: "sg-c70127bd" => ""
    ingress.3400316176.self:                       "false" => "false"
    ingress.3400316176.to_port:                    "7000" => "0"
    ingress.357529062.cidr_blocks.#:               "0" => "0"
    ingress.357529062.from_port:                   "9160" => "0"
    ingress.357529062.protocol:                    "tcp" => ""
    ingress.357529062.security_groups.#:           "1" => "0"
    ingress.357529062.security_groups.2169191079:  "sg-c70127bd" => ""
    ingress.357529062.self:                        "false" => "false"
    ingress.357529062.to_port:                     "9160" => "0"
    ingress.3827110669.cidr_blocks.#:              "0" => "0"
    ingress.3827110669.from_port:                  "80" => "80"
    ingress.3827110669.protocol:                   "tcp" => "tcp"
    ingress.3827110669.security_groups.#:          "1" => "1"
    ingress.3827110669.security_groups.2876704322: "sg-b80721c2" => "sg-b80721c2"
    ingress.3827110669.self:                       "false" => "false"
    ingress.3827110669.to_port:                    "80" => "80"
    ingress.3929861091.cidr_blocks.#:              "0" => "0"
    ingress.3929861091.from_port:                  "61621" => "0"
    ingress.3929861091.protocol:                   "tcp" => ""
    ingress.3929861091.security_groups.#:          "1" => "0"
    ingress.3929861091.security_groups.2169191079: "sg-c70127bd" => ""
    ingress.3929861091.self:                       "false" => "false"
    ingress.3929861091.to_port:                    "61621" => "0"
    ingress.4211759511.cidr_blocks.#:              "0" => "0"
    ingress.4211759511.from_port:                  "1433" => "0"
    ingress.4211759511.protocol:                   "tcp" => ""
    ingress.4211759511.security_groups.#:          "1" => "0"
    ingress.4211759511.security_groups.3551840219: "sg-cc0127b6" => ""
    ingress.4211759511.self:                       "false" => "false"
    ingress.4211759511.to_port:                    "1433" => "0"
    ingress.680397075.cidr_blocks.#:               "0" => "0"
    ingress.680397075.from_port:                   "7001" => "0"
    ingress.680397075.protocol:                    "tcp" => ""
    ingress.680397075.security_groups.#:           "1" => "0"
    ingress.680397075.security_groups.2169191079:  "sg-c70127bd" => ""
    ingress.680397075.self:                        "false" => "false"
    ingress.680397075.to_port:                     "7001" => "0"
    ingress.808665337.cidr_blocks.#:               "0" => "0"
    ingress.808665337.from_port:                   "7199" => "0"
    ingress.808665337.protocol:                    "tcp" => ""
    ingress.808665337.security_groups.#:           "1" => "0"
    ingress.808665337.security_groups.2169191079:  "sg-c70127bd" => ""
    ingress.808665337.self:                        "false" => "false"
    ingress.808665337.to_port:                     "7199" => "0"
    ingress.922980179.cidr_blocks.#:               "0" => "0"
    ingress.922980179.from_port:                   "3389" => "3389"
    ingress.922980179.protocol:                    "tcp" => "tcp"
    ingress.922980179.security_groups.#:           "1" => "1"
    ingress.922980179.security_groups.3352223863:  "sg-940721ee" => "sg-940721ee"
    ingress.922980179.self:                        "false" => "false"
    ingress.922980179.to_port:                     "3389" => "3389"
[0m
[0m[33m~ aws_security_group.trf_sg_schdtasks
[0m    egress.#:                                      "2" => "1"
    egress.1685082047.cidr_blocks.#:               "0" => "0"
    egress.1685082047.from_port:                   "80" => "80"
    egress.1685082047.prefix_list_ids.#:           "0" => "0"
    egress.1685082047.protocol:                    "tcp" => "tcp"
    egress.1685082047.security_groups.#:           "1" => "1"
    egress.1685082047.security_groups.2739699671:  "sg-7004220a" => "sg-7004220a"
    egress.1685082047.self:                        "false" => "false"
    egress.1685082047.to_port:                     "80" => "80"
    egress.4211759511.cidr_blocks.#:               "0" => "0"
    egress.4211759511.from_port:                   "1433" => "0"
    egress.4211759511.prefix_list_ids.#:           "0" => "0"
    egress.4211759511.protocol:                    "tcp" => ""
    egress.4211759511.security_groups.#:           "1" => "0"
    egress.4211759511.security_groups.3551840219:  "sg-cc0127b6" => ""
    egress.4211759511.self:                        "false" => "false"
    egress.4211759511.to_port:                     "1433" => "0"
    ingress.#:                                     "2" => "1"
    ingress.1685082047.cidr_blocks.#:              "0" => "0"
    ingress.1685082047.from_port:                  "80" => "80"
    ingress.1685082047.protocol:                   "tcp" => "tcp"
    ingress.1685082047.security_groups.#:          "1" => "1"
    ingress.1685082047.security_groups.2739699671: "sg-7004220a" => "sg-7004220a"
    ingress.1685082047.self:                       "false" => "false"
    ingress.1685082047.to_port:                    "80" => "80"
    ingress.4211759511.cidr_blocks.#:              "0" => "0"
    ingress.4211759511.from_port:                  "1433" => "0"
    ingress.4211759511.protocol:                   "tcp" => ""
    ingress.4211759511.security_groups.#:          "1" => "0"
    ingress.4211759511.security_groups.3551840219: "sg-cc0127b6" => ""
    ingress.4211759511.self:                       "false" => "false"
    ingress.4211759511.to_port:                    "1433" => "0"
[0m
[0m[33m~ aws_security_group.trf_sg_sqlserver
[0m    egress.#:                                      "5" => "4"
    egress.1333604694.cidr_blocks.#:               "0" => "0"
    egress.1333604694.from_port:                   "1434" => "1434"
    egress.1333604694.prefix_list_ids.#:           "0" => "0"
    egress.1333604694.protocol:                    "udp" => "udp"
    egress.1333604694.security_groups.#:           "1" => "1"
    egress.1333604694.security_groups.2739699671:  "sg-7004220a" => "sg-7004220a"
    egress.1333604694.self:                        "false" => "false"
    egress.1333604694.to_port:                     "1434" => "1434"
    egress.395540511.cidr_blocks.#:                "0" => "0"
    egress.395540511.from_port:                    "4022" => "4022"
    egress.395540511.prefix_list_ids.#:            "0" => "0"
    egress.395540511.protocol:                     "tcp" => "tcp"
    egress.395540511.security_groups.#:            "1" => "1"
    egress.395540511.security_groups.2739699671:   "sg-7004220a" => "sg-7004220a"
    egress.395540511.self:                         "false" => "false"
    egress.395540511.to_port:                      "4022" => "4022"
    egress.4073516292.cidr_blocks.#:               "0" => "0"
    egress.4073516292.from_port:                   "1433" => "1433"
    egress.4073516292.prefix_list_ids.#:           "0" => "0"
    egress.4073516292.protocol:                    "tcp" => "tcp"
    egress.4073516292.security_groups.#:           "1" => "1"
    egress.4073516292.security_groups.2739699671:  "sg-7004220a" => "sg-7004220a"
    egress.4073516292.self:                        "false" => "false"
    egress.4073516292.to_port:                     "1433" => "1433"
    egress.4228220737.cidr_blocks.#:               "0" => "0"
    egress.4228220737.from_port:                   "1433" => "0"
    egress.4228220737.prefix_list_ids.#:           "0" => "0"
    egress.4228220737.protocol:                    "tcp" => ""
    egress.4228220737.security_groups.#:           "1" => "0"
    egress.4228220737.security_groups.2980972767:  "sg-c20127b8" => ""
    egress.4228220737.self:                        "false" => "false"
    egress.4228220737.to_port:                     "1433" => "0"
    egress.833803214.cidr_blocks.#:                "0" => "0"
    egress.833803214.from_port:                    "1434" => "1434"
    egress.833803214.prefix_list_ids.#:            "0" => "0"
    egress.833803214.protocol:                     "tcp" => "tcp"
    egress.833803214.security_groups.#:            "1" => "1"
    egress.833803214.security_groups.2739699671:   "sg-7004220a" => "sg-7004220a"
    egress.833803214.self:                         "false" => "false"
    egress.833803214.to_port:                      "1434" => "1434"
    ingress.#:                                     "5" => "4"
    ingress.1333604694.cidr_blocks.#:              "0" => "0"
    ingress.1333604694.from_port:                  "1434" => "1434"
    ingress.1333604694.protocol:                   "udp" => "udp"
    ingress.1333604694.security_groups.#:          "1" => "1"
    ingress.1333604694.security_groups.2739699671: "sg-7004220a" => "sg-7004220a"
    ingress.1333604694.self:                       "false" => "false"
    ingress.1333604694.to_port:                    "1434" => "1434"
    ingress.395540511.cidr_blocks.#:               "0" => "0"
    ingress.395540511.from_port:                   "4022" => "4022"
    ingress.395540511.protocol:                    "tcp" => "tcp"
    ingress.395540511.security_groups.#:           "1" => "1"
    ingress.395540511.security_groups.2739699671:  "sg-7004220a" => "sg-7004220a"
    ingress.395540511.self:                        "false" => "false"
    ingress.395540511.to_port:                     "4022" => "4022"
    ingress.4073516292.cidr_blocks.#:              "0" => "0"
    ingress.4073516292.from_port:                  "1433" => "1433"
    ingress.4073516292.protocol:                   "tcp" => "tcp"
    ingress.4073516292.security_groups.#:          "1" => "1"
    ingress.4073516292.security_groups.2739699671: "sg-7004220a" => "sg-7004220a"
    ingress.4073516292.self:                       "false" => "false"
    ingress.4073516292.to_port:                    "1433" => "1433"
    ingress.4228220737.cidr_blocks.#:              "0" => "0"
    ingress.4228220737.from_port:                  "1433" => "0"
    ingress.4228220737.protocol:                   "tcp" => ""
    ingress.4228220737.security_groups.#:          "1" => "0"
    ingress.4228220737.security_groups.2980972767: "sg-c20127b8" => ""
    ingress.4228220737.self:                       "false" => "false"
    ingress.4228220737.to_port:                    "1433" => "0"
    ingress.833803214.cidr_blocks.#:               "0" => "0"
    ingress.833803214.from_port:                   "1434" => "1434"
    ingress.833803214.protocol:                    "tcp" => "tcp"
    ingress.833803214.security_groups.#:           "1" => "1"
    ingress.833803214.security_groups.2739699671:  "sg-7004220a" => "sg-7004220a"
    ingress.833803214.self:                        "false" => "false"
    ingress.833803214.to_port:                     "1434" => "1434"
[0m
[0m
[0m[1mPlan:[0m 0 to add, 3 to change, 0 to destroy.[0m

resource "aws_security_group" "xyz_sg_abc" {
  name        = "xyz-${var.environment}-sg-abc"
  description = "Security Group for whatever"
  vpc_id      = "${aws_vpc.xyz_vpc.id}"

  # HTTP access from anywhere
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    security_groups = ["${aws_security_group.xyz_sg_cfelb01.id}"]
  }
  ingress {
    from_port   = 3389
    to_port     = 3389
    protocol    = "tcp"
    security_groups = ["${aws_security_group.xyz_sg_win_jh.id}"]
  }
  ingress {
    from_port   = 3389
    to_port     = 3389
    protocol    = "udp"
    security_groups = ["${aws_security_group.xyz_sg_win_jh.id}"]
  }
	ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    security_groups = ["${aws_security_group.xyz_sg_cfelb01.id}"]
  }

# outbound internet access

  egress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    security_groups = ["${aws_security_group.xyz_sg_cfelb01.id}"]
  }
  egress {
    from_port   = 3389
    to_port     = 3389
    protocol    = "tcp"
    security_groups = ["${aws_security_group.xyz_sg_win_jh.id}"]
  }
  egress {
    from_port   = 3389
    to_port     = 3389
    protocol    = "udp"
    security_groups = ["${aws_security_group.xyz_sg_win_jh.id}"]
  }
  egress {
		from_port   = 443
		to_port     = 443
		protocol    = "tcp"
		security_groups = ["${aws_security_group.xyz_sg_cfelb01.id}"]
	}

tags {
			Name = "xyz-${var.environment}-sg-abc"
			Environment = "${var.environment}"
	}
}

resource "aws_security_group_rule" "xyz_sg_abc_rule01" {
    type = "ingress"
    from_port = 1433
    to_port = 1433
    protocol = "tcp"
    security_group_id = "${aws_security_group.xyz_sg_abc.id}"
    source_security_group_id = "${aws_security_group.xyz_sg_sqlserver.id}"
}

resource "aws_security_group_rule" "xyz_sg_abc_rule02" {
    type = "egress"
    from_port = 1433
    to_port = 1433
    protocol = "tcp"
    security_group_id = "${aws_security_group.xyz_sg_abc.id}"
    source_security_group_id = "${aws_security_group.xyz_sg_sqlserver.id}"
}

**Comment by apparentlymart** [comment]
Hello! Sorry for the issue here.

The trick with this is that the `security_groups` argument is intended for EC2-Classic security groups. It works "by accident" due to assume quirks of the underlying API design, but then Terraform gets confused because it doesn't expect VPC security groups to show up here.

The fix is to use the `vpc_security_group_ids` instead when using VPC security groups.

It would be good for Terraform to detect and report this situation better...

**Comment by karthickk100** [comment]
@apparentlymart 
Hi Thanks for your feedback. I am using GroupIds and not the name. 
(security_groups = ["${aws_security_group.xyz_sg_cfelb01.id}"])

If you are meaning "vpc_security_group_ids" instead of "security_groups", then neither resources "AWS_SECURITY_GROUP" or "AWS_SECURITY_GROUP_RULE" support "vpc_security_group_ids". 

Please let me know what do I need to fix.

**Comment by apparentlymart** [comment]
Sorry for my inattention here... You are right that I didn't look closely enough at what you posted and confused this with a different (frequently occurring) problem.

I am not on a computer anymore so I can't dig in further but I will try to take a closer look tomorrow.

**Comment by catsby** [comment]
Hello –

It looks like you are using both `aws_security_group` with rule defined in-line and `aws_security_group_rule` to add additional rules to a security group. Unfortunately this is not currently supported; please see the note on the documentation page:

- https://www.terraform.io/docs/providers/aws/r/security_group.html

When defining rules in-line with resource `aws_security_group` , the resource attempts to manage _all_ the rules there. Any rule added externally (either manually via the web console, or by adding `aws_security_group_rule` resources), will cause a conflict and perpetual diff because of those new rules. 

At this time I have no other suggestions or workarounds beyond refactoring your configuration to use either only in-line rules with your `aws_security_group` resources, or only `aws_security_group_rule` resources .

Please let me know if you have any other questions. I'm going to close this issue for now though.

**Comment by karthickk100** [comment]
@catsby How do you resolve SG A referencing SG B and SG B referencing SG A, and where I cannot use a Self(because of ports) ?

**Comment by catsby** [comment]
If I understand your question correctly, you can use `aws_security_group_rule` resources to do this, like so:

```
resource "aws_security_group" "sg_a" {
  name        = "sg_a_test"
  description = "sg_a_test"
}

resource "aws_security_group_rule" "sg_rule_a" {
  type      = "egress"
  from_port = 0
  to_port   = 0

  protocol                 = "1"
  security_group_id        = "${aws_security_group.sg_a.id}"
  source_security_group_id = "${aws_security_group.sg_b.id}"
}

resource "aws_security_group" "sg_b" {
  name        = "sg_b_test"
  description = "sg_b_test"
}

resource "aws_security_group_rule" "sg_rule_b" {
  type      = "egress"
  from_port = 0
  to_port   = 0

  protocol                 = "1"
  security_group_id        = "${aws_security_group.sg_b.id}"
  source_security_group_id = "${aws_security_group.sg_a.id}"
}
```

**Comment by karthickk100** [comment]
@catsby Thats exactly what we are doing, thats when we hit the above error.
