### ISSUE TITLE
Changing aws_alb_listener_rule priority doesn't actually update it in AWS

### ISSUE THREAD

**Issue by nickrw** [hashicorp/terraform#9227]
### Terraform Version

0.7.4
### Affected Resource(s)
- aws_alb_listener_rule
### Terraform Configuration Files

``` hcl
resource "aws_alb_listener_rule" "test" {
  listener_arn = "${alb_listener.test.arn}"
  priority = "100"
  action {
    type = "forward"
    target_group_arn = "${aws_alb_target_group.test.arn}"
  }
  condition {
    field = "path-pattern"
    values = ["/test/*"]
  }
}
```
### Expected Behavior

Changing the priority from "100" to "101" should update the listener rule in AWS
### Actual Behavior

The rule remains unchanged, though `terraform plan` shows

```
~ aws_alb_listener_rule.test
    priority: "100" => "101"
```

and `terraform apply` shows

```
aws_alb_listener_rule.test: Modifying...
  priority: "100" => "101"
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with initial priority
2. Modify priority to another number
3. `terraform apply` again
4. Observe rule priorities are unchanged, `terraform plan` still shows a desired change

**Comment by nickrw** [comment]
Looking [at the code](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_alb_listener_rule.go) it seems like priority updates are simply not implemented. The ModifyRule api call doesn't support updating the priority so it isn't sent there. There's a separate call, [SetRulePriorities](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SetRulePriorities.html).

I'm not familiar with terraform's code, so I'm just speculating, but I assume this might be tricky to implement. If I have two rules and I swap their priorities round it would require a single API call to SetRulePriorities for the two resources.

**Comment by consultantRR** [comment]
I am seeing this as well in `Terraform v0.8.0-dev`.

**Comment by zambien** [comment]
An easy workaround which I'm using is to set the listener priorities to a static number and to update the target group instead.  Blue green example with path routing below:

```
resource "aws_alb_listener_rule" "default_blue_green_rule" {
  listener_arn = "${aws_alb_listener.front_end.arn}"

  #priority = "${var.current_task_configuration == "blue" ? "50" : "51"}"
  # Maybe this will be fixed at some point: https://github.com/hashicorp/terraform/issues/9227
  # until then do it this way.
  priority = 50

  action {
    type             = "forward"
    target_group_arn = "${var.current_task_configuration == "green" ? aws_alb_target_group.tg_green.arn: aws_alb_target_group.tg_blue.arn}"
  }

  condition {
    field  = "path-pattern"
    values = ["${var.current_task_configuration == "green" ? "${var.task_green_path}*": "${var.task_blue_path}*"}"]
  }
}

resource "aws_alb_listener_rule" "canary_blue_green_rule" {
  listener_arn = "${aws_alb_listener.front_end.arn}"

  # priority = "${var.current_task_configuration == "green" ? "50" : "52"}"
  priority = 51

  action {
    type             = "forward"
    target_group_arn = "${var.current_task_configuration == "green" ? aws_alb_target_group.tg_blue.arn: aws_alb_target_group.tg_green.arn}"
  }

  condition {
    field  = "path-pattern"
    values = ["${var.current_task_configuration == "green" ? "${var.task_blue_path}*": "${var.task_green_path}*"}"]
  }
}

```
