### ISSUE TITLE
aws_security_group recreates empty ingress rule every time

### ISSUE THREAD

**Issue by b-dean** [hashicorp/terraform#9240]
We have a variable that we set a list of CIDR blocks that we use for an ingress rule on a security group. We use `compact` because there are some cases where the list is empty or contains some empty items and that'll make AWS say the CIDR blocks are invalid. An empty list however is fine.

The problem is that it seems to want to remake that ingress rule every time. It probably has something to do with AWS not actually adding a rule that has no CIDR blocks (and isn't a "self" rule).
### Terraform Version

0.7.4
### Affected Resource(s)
- aws_security_group
### Terraform Configuration Files

``` hcl
variable "ingress_cidrs" {
  type = "list"
  default = []
}

resource "aws_security_group" "sg" {
  ingress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["${compact(var.ingress_cidrs)}"]
  }
}
```
### Output

Here's a gist with the CLI output from running `terraform apply` and `terraform plan`. Also the `terraform.tfstate`.
https://gist.github.com/b-dean/b2dddbfc95bde98780ffa569e7e1ccec
### Expected Behavior

I expect to be able to `apply` and then `plan` and see no pending changes.
### Actual Behavior

The `terraform plan` shows the ingress rule changing every time. This is probably because AWS is deleting the rule since it doesn't actually _do_ anything.
### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by rsepassi** [comment]
I've had a similar issue in which I defined an `aws_security_group` with several ingress rules but accidentally failed to provide both the `security_groups` property and the `cidr_blocks` property, which makes the `ingress` stanza have no effect. However, both `terraform plan` and `terraform apply` show that the security group should be modified. I was very confused that `terraform apply` showed that it was successful in "modifying" the security group but when I looked in the console, the group had no ingress rules.

`plan`/`apply` should either recognize that an `ingress` rule without a `cidr_blocks` or `security_groups` property is the same as not having that rule at all.
