### ISSUE TITLE
AWS Elasticache parameter group only works for 1 region

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/terraform#9246]
### Terraform Version
0.7.4

### Affected Resource(s)
aws_elasticache_parameter_group

### Terraform Configuration Files
Any default parameter group will work. Notice that there's no option for setting a region or availability zone.
```hcl
resource "aws_elasticache_parameter_group" "default" {
    name = "cache-params"
    family = "redis2.8"

    parameter {
        name = "activerehashing"
        value = "yes"
    }

    parameter {
        name = "min-slaves-to-write"
        value = "2"
    }
}
```

### Expected Behavior
You should be able to specify the region for a parameter group to be created in.

### Actual Behavior
Terraform defaults to the AWS provider's default region, with no ability to create parameter groups in other regions. I think this may have been overlooked because the [AWS documentation](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ParameterGroups.Creating.html) does not mention regions, or because AWS uses [separate endpoints for elasticache regions](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/RegionsAndAZs.html#SupportedRegions).

### Important Factoids
This works fine with the AWS CLI or console across regions.
`aws elasticache describe-cache-parameter-groups --region us-west-1`

**Comment by radeksimko** [comment]
Hi @dmikalova 
as @apparentlymart explained in https://github.com/hashicorp/terraform/issues/9247#issuecomment-251857652 the way AWS provider works is that you specify the region as part of the provider block. If you do need to create resources that spread across more regions you can define more providers & add aliases to them.

## One region

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_elasticache_parameter_group" "default" {
    ...
}
```

## Multiple regions

```hcl
provider "aws" {
  alias = "us-east"
  region = "us-east-1"
}

resource "aws_elasticache_parameter_group" "east" {
  provider = "aws.us-east"
  ...
}

provider "aws" {
  alias = "us-west"
  region = "us-west-1"
}

resource "aws_elasticache_parameter_group" "west" {
  provider = "aws.us-west"
  ...
}
```

**Comment by dmikalova** [comment]
Thanks, after looking over things again this makes sense.
