### ISSUE TITLE
"associate_public_ip_address" missing on aws_launch_configuration documentation

### ISSUE THREAD

**Issue by egarbi** [hashicorp/terraform#926]
Something like:
* associate_public_ip_address - (Optional) Associate a public ip address with an instance in a VPC. 

It should be added here:
http://www.terraform.io/docs/providers/aws/r/launch_config.html
on the Argument Reference section.

**Comment by sethvargo** [comment]
Hi @egarbi 

The documentation for Terraform is all open source and lives in the `website/` folder of this repository. Would you like to submit a Pull Request to incorporate those changes?

**Comment by egarbi** [comment]
Hi @sethvargo, ok I will

**Comment by egarbi** [comment]
@sethvargo https://github.com/hashicorp/terraform/pull/933

**Comment by mitchellh** [comment]
Fixed by #933
