### ISSUE TITLE
provider/aws: data source "aws_ami" is working incorrect in terraform 0.7.5

### ISSUE THREAD

**Issue by opokhvalit** [hashicorp/terraform#9274]
Hi!

After upgrade to terraform 0.7.5 data source "aws_ami" is returning incorrect value. When I set most_recent value to true, data source is return OLDERS AMI instead of LATEST

Sample code:

> data "aws_ami" "sl_ami_is" {
>     most_recent = true
>     owners = ["${var.aws_owner_id}"]
>     filter {
>         name = "virtualization-type"
>         values = ["paravirtual"]
>     }
>     filter {
>         name = "name"
>         values = ["SL-64-AmazonLnx-*"]
>     }
> }
> 
> output "AMI ID" {
>     value = "${data.aws_ami.sl_ami_is.id}"
> }
> 

And results of execution this code for terraform 0.7.4 and 0.7.5
for 0.7.4

> $ terraform.0.7.4 apply
> data.aws_ami.sl_ami_is: Refreshing state...
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> 
> Outputs:
> AMI ID = ami-3d084c2a
> 

for 0.7.5

> $ terraform apply
> data.aws_ami.sl_ami_is: Refreshing state...
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> 
> Outputs:
> AMI ID = ami-ffc2b395
>

**Comment by kwilczynski** [comment]
@opokhvalit hi there! Thank you for bringing this to our attention! I am sorry that you have issue.

Let me look into this.

**Comment by kwilczynski** [comment]
@opokhvalit hello again! I have resolved this in #9277. 

I sincerely apologise. This regression was introduced in #9033 where I have fixed a different problem with this data source.

**Comment by stack72** [comment]
Closed via #9277

**Comment by opokhvalit** [comment]
Thanx!

**Comment by commarla** [comment]
thanks!
