### ISSUE TITLE
AWS CloudFront IPv6 support

### ISSUE THREAD

**Issue by osiegmar** [hashicorp/terraform#9276]
AWS [announced support](https://aws.amazon.com/de/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/) for IPv6 protocol in Amazon CloudFront.

**Comment by stack72** [comment]
Hi @osiegmar 

Thanks for opening the issue here - we are going to need #9275 to be merged before we can get this in place

P.

**Comment by shadone** [comment]
ping, any update on this?
