### ISSUE TITLE
`depends_on` field in `terraform.tfstate` changes order arbitrarilly

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#928]
```
@@ -16,8 +16,8 @@
                 "aws_instance.coreos.0": {
                     "type": "aws_instance",
                     "depends_on": [
-                        "aws_security_group.coreos",
-                        "aws_subnet.core"
+                        "aws_subnet.core",
+                        "aws_security_group.coreos"
                     ],
                     "primary": {
                         "id": "i-f3c30209",
Stage this hunk [y,n,q,a,d,/,K,j,J,g,e,?]? 
```

I'm guessing these are written in whatever order the graph happens to be walked in or something, so changes to the configuration can reorder them. It would be nice if they were written in a canonical order to cut down on the diff noise.

**Comment by mitchellh** [comment]
Looks good, we might as well just sort these in alphabetical. The ordering here doesn't actually matter, its just a set.

**Comment by mitchellh** [comment]
Fixed. 

@phinze I pushed directly to master since its trivial.
