### ISSUE TITLE
provider/logentries Cannot refresh state 'unknown request list_logtypes_default'

### ISSUE THREAD

**Issue by wdullaer** [hashicorp/terraform#9280]
### Terraform Version

0.7.4
### Affected Resource(s)

provider: logentries
resource: logentries_log
### Terraform Configuration Files

``` hcl
resource "heroku_drain" "test_logentries" {
  app = "test-app-name"
  url = "https://heroku.logentries.com/v1/drain/${logentries_log.test_logs.token}"
}

# We'll create a new logset so we don't need to recover the uuid of the heroku one out of band
resource "logentries_logset" "test_logset" {
  name = "test-logset"
  location = "heroku"
}

resource "logentries_log" "test_logs" {
  logset_id = "${logentries_logset.test_logset.id}"
  name = "test-log"
  source = "syslog"
  type = "heroku"
}
```
### Expected Behavior

It should refresh the state

The resources got created successfully, but it errors when trying to refresh the state afterwards
### Actual Behavior

It errors our with

```
failed to retrieve default log type list: Unknown request list_logtypes_default.
```

The logentries API is not well documented, but it appears that this list default logtypes call is not supported.
I also explicitly specified the logtype in the config file, so I'm not sure why it is trying to list the default types.
### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by dabdine-r7** [comment]
Taking a look at this

**Comment by dabdine-r7** [comment]
I believe the best path forward is to remove the list_logtypes_default test when applying the configuration, but I'll check with the logentries team on this. If so, I'll submit a PR to address this defect. Thanks for filing @wdullaer

**Comment by wdullaer** [comment]
I could reproduce it using curl. But the API is not documented, so I couldn't really fix it.

If you need any help testing your solution, do not hesitate to ask.

**Comment by dabdine-r7** [comment]
@wdullaer thanks! I verified that the API request was removed. Since this request is only used for validating the log type, I don't think it's needed. So, the plan is to remove the validation step.

PR will be out shortly.

**Comment by ahmadferdous** [comment]
Hi @wdullaer,

[`logentries_log` documentation](https://www.terraform.io/docs/providers/logentries/r/log.html#token) says `token` attribute is exported only when the log `source` is `token`. However, you used `token` attribute in argument `url` of `heroku_drain` resource, when your log `source` is `syslog`. So, it's not supposed to work. 

Did your logentries config work? If yes, did you have to make any changes to the code you posted?

**Comment by wdullaer** [comment]
It's been a year and a half and I have moved jobs over a year ago, so I don't really remember. My apologies
