### ISSUE TITLE
crash retrieving map with interpolated key

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#9282]
### Terraform Version
v0.7.5

### Affected Resource(s)

This appears to be an issue with the core.

### Terraform Configuration Files

Attached:  [tf-reproduce.zip](https://github.com/hashicorp/terraform/files/516528/tf-reproduce.zip)

`modules/subnets/main.tf` contains a map `output`:

```
output "vpcs" {
    value = "${map(
        "dev_aws_gen_us-east-1", "10.112.0.0/19"
    )}"
}
```

It's referenced in `main.tf` like

```
resource "aws_vpc" "default" {
    cidr_block = "${module.subnets.vpcs[format("%s_%s_%s_%s", var.environment, var.provider, var.account, var.region)]}"
}
```

### Panic Output

[crash.log.txt](https://github.com/hashicorp/terraform/files/516533/crash.log.txt)

### Expected Behavior

`terraform plan` should have shown a plan to create an `aws_vpc` resource.

### Actual Behavior

💣🔥
`panic: runtime error: index out of range`

### Steps to Reproduce

1. unpack attached zip
2. run `terraform get`
3. run `terraform plan`

If `cidr_block` is changed to `"${module.subnets.vpcs["dev_aws_gen_us-east-1"]}"` the `apply` works fine.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #8384

**Comment by jbardin** [comment]
Hi @blalor,

Thanks for the report and reproduction. I don't think this has anything to do with modules, it appears to be the `format` inside the map index that is throwing off the interpolator.

This reduced config crashes with apply
```
variable map {
	default = {
		a = "b"
	}
}

output "formatted_index" {
	value = "${var.map[format("%s", "a")]}"
}
```
