### ISSUE TITLE
Running apply with -target blows away some outputs

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#9287]
### Terraform Version

0.7.4
### Affected Resource(s)

Please list the resources as a list, for example:
- outputs

Given an HCL like the following:

```
resource "compute_instance" "foo" {
  count = 10
}

resource "compute_instance" "bar" {
  count = 10
}

output "foo_ips" {
  value = ["compute_instance.bar.*.ip"]
}

output "bar_ips" {
  value = ["compute_instance.bar.*.ip"]
}
```

When I run `terraform apply` and `terraform output` everything works as expected.  But if I  rebuild just `foo` using `terraform apply -target "compute_instance.foo",`terraform output`only shows`foo_ips`.  Even though a subsequent`terraform plan`shows nothing has changed, I have to run an`apply`again to bring`bar_ips` back.

I can verify that after targeting `foo`, only `foo_ips` is in the tfstate file.  It looks like instead of doing an update, the logic does a complete replace.

**Comment by mitchellh** [comment]
This is a dup of #2598. Outputs will all get wrapped up together.
