### ISSUE TITLE
Cannot write computed values to nested attributes

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#929]
On master, the following yields an empty string in that output variable, and empty strings are visible when doing terraform show.  However I have annotated the source code and seen that d.Set(...) is being called correctly in resourceComputeInstanceRead

That makes me wonder if there is a bug in core?  Or maybe the code in resourceComputeInstanceRead is wrong (in which case what should it look like?)

    resource "google_compute_instance" "test0" {
        name = "test0"
        machine_type = "g1-small"
        zone = "us-central1-a"
    
        disk {
            image = "debian-7-wheezy-v20140814"
        }
    
        network {
            source = "default"
        }
    }
    output "network_ip" {
        value = "${google_compute_instance.test0.network.0.internal_address}"
    }

**Comment by mitchellh** [comment]
Can you get me the `TF_LOG=1` output for the bare (no state) apply?

**Comment by sparkprime** [comment]
http://codepad.org/iYOAKNrV

**Comment by mitchellh** [comment]
Oh, and now the `terraform show` output (with state)

**Comment by sparkprime** [comment]
http://codepad.org/FLYDNVHG

**Comment by mitchellh** [comment]
Ah, I figured this out. This is just totally broken on master.
