### ISSUE TITLE
CLI switch for plan to include changes to outputs

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#9309]
Would it be possible to add a command line switch for `terraform plan` to return non-0 status when there is a change to the `outputs` for the state?

Use Case - automating Terraform projects, we run a `plan` and then an `apply` only if `plan` indicates there are changes. 

Behavior -
When adding only an output to a project, `terraform plan -detailed-exitcode` exits with a value of `0` indicating there are no diffs.

Desired Behavior -
An additional command line switch to reports diffs to `outputs` as a plan diff, `terraform plan -include-outputs -detailed-exitcode` would exit with a value of  `2`.

**Comment by defn-bn** [comment]
Just found that `terraform refresh` will also apply changed outputs to the state backend.  To find out if outputs changed, I do a diff of `terraform output` before and after `terraform refresh`.

**Comment by apparentlymart** [comment]
Hi @johnrengelman! Sorry for the long silence here.

I posted the results of some initial design work for something related to this over in #15419. We're intending to look into this more in a forthcoming release. I'm going to close this one just to consolidate discussion into the other issue, Thanks for requesting this!
