### ISSUE TITLE
azurerm can't create LoadBalancer rule with probe

### ISSUE THREAD

**Issue by pmcq** [hashicorp/terraform#9311]
I am unable to create resources that refer to  LoadBalancer probe_ids or backend_address_pool_ids.  I can create load balancers, rules, and NICs that don't refer to a particular probe/backend_address_pool or manually set the string name, but I can't use something like `"${azurerm_lb_probe.web_probe.id}"`

### Terraform Version
Terraform v0.7.6-dev (d83770d58257581fa229c41d095772d16dee81da+CHANGES)

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_lb_backend_address_pool
- azurerm_lb_probe

Resources using these:
- azurerm_lb_rule
- azurerm_network_interface

### Terraform Configuration Files
```hcl
resource "azurerm_lb" "web_lb" {
  name = "${var.environment}-WEB"
  location = "West US"
  resource_group_name = "${azurerm_resource_group.main.name}"

  frontend_ip_configuration {
    name = "${var.environment}-WEB-ipconfig"
    subnet_id = "${azurerm_subnet.edge.id}"
  }
}

resource "azurerm_lb_backend_address_pool" "web_backendpool" {
  name = "${var.environment}-WEB-backendpool"
  location = "West US"
  resource_group_name = "${azurerm_resource_group.main.name}"
  loadbalancer_id = "${azurerm_lb.web_lb.id}"
}

resource "azurerm_lb_probe" "web_probe" {
  name = "${var.environment}-WEB-probe"
  location = "West US"                                                   
  resource_group_name = "${azurerm_resource_group.main.name}"            
  loadbalancer_id = "${azurerm_lb.web_lb.id}"                            
  protocol = "Http"
  port = 9000                                                            
  request_path = "/ping"                                                 
  interval_in_seconds = 5
} 

resource "azurerm_lb_rule" "web_lbrule" {
  name = "${var.environment}-WEB-lbrule"
  location = "West US"
  resource_group_name = "${azurerm_resource_group.main.name}"            
  loadbalancer_id = "${azurerm_lb.web_lb.id}"                            
  frontend_ip_configuration_name = "${var.environment}-WEB-ipconfig"     
  protocol = "Tcp"
  frontend_port = 80
  backend_port = 9000
  probe_id = "${azurerm_lb_probe.web_probe.id}"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.web_backendpool.id}"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
Load balancer rule with the given probe & backend address pool should have been created

### Actual Behavior
Azure returned an error stating that the ID for the probe/backend address pool refers to the wrong type:
```
{"code":"InvalidJsonReferenceWrongType","message":"Reference Id /subscriptions/ffafcfaf-21f1-4594-bb65-9076e00b15f7/resourceGroups/mainResourceGroup/providers/Microsoft.Network/loadBalancers/azure-WEB is referencing resource of a wrong type. The Id is expected to reference resources of type loadBalancers/backendAddressPools. Path properties.ipConfigurations[0].properties.loadBalancerBackendAddressPools[0]."}
```
And doing a `terraform plan` shows that the IDs being used seem to refer to the LoadBalancer itself instead of the ID of the Probe.

```
+ azurerm_lb_rule.web_lbrule
    backend_address_pool_id:        "/subscriptions/ffafcfaf-21f1-4594-bb65-9076e00b15f7/resourceGroups/mainResourceGroup/providers/Microsoft.Network/loadBalancers/azure-WEB"
    backend_port:                   "9000"
    enable_floating_ip:             "false"
    frontend_ip_configuration_id:   "<computed>"
    frontend_ip_configuration_name: "azure-WEB-ipconfig"
    frontend_port:                  "80"
    idle_timeout_in_minutes:        "<computed>"
    load_distribution:              "<computed>"
    loadbalancer_id:                "/subscriptions/ffafcfaf-21f1-4594-bb65-9076e00b15f7/resourceGroups/mainResourceGroup/providers/Microsoft.Network/loadBalancers/azure-WEB"
    location:                       "westus"
    name:                           "azure-WEB-lbrule"
    probe_id:                       "/subscriptions/ffafcfaf-21f1-4594-bb65-9076e00b15f7/resourceGroups/mainResourceGroup/providers/Microsoft.Network/loadBalancers/azure-WEB"
    protocol:                       "Tcp"
    resource_group_name:            "mainResourceGroup"
```

I'm new to terraform, but it seems like this an issue in this section of code (for probes): 
https://github.com/hashicorp/terraform/blob/7d3d707d22e134ef9a9b44de5c479ce29ae964ea/builtin/providers/azurerm/resource_arm_loadbalancer_probe.go#L123-L131

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This stuff is super new (and great!)

### References
Azure resource manager load balancer support was just added in this pull request:
- https://github.com/hashicorp/terraform/pull/9199

**Comment by pmcq** [comment]
Hmmmm I might be misunderstanding how to use probe/backend address pools, but have been basing this off of the docs on that pull request that I could specify IDs for some of those resources.

**Comment by markrendle** [comment]
All the output IDs for LB probes, rules and backend pools are just the ID of the LB itself; you can construct the correct ID using e.g. `"${azurerm_lb.test.id}/backendAddressPools/BackendPool1"` where `BackendPool1` is the `name` you gave the pool.

It would be better if the output IDs were set to this, since it can be derived from the information supplied when creating the pool/rule/probe.

cc @stack72
