### ISSUE TITLE
Unknown variable accessed Error when adding a new variable to a template

### ISSUE THREAD

**Issue by marktb1** [hashicorp/terraform#9316]
Hi, 

Had an issue today with adding a new variable to an existing template resource. If I just appended the variable to the file I was templating and template resource, it would throw  a "failed to render : unknown variable accessed" error upon terraform planning. I worked around this by making a whole new template resource and file to template. This seems like a regression of [#2306](https://github.com/hashicorp/terraform/issues/2306)

I'm running Terraform v0.7.4, but checked the changelog for 0.7.5 and saw no mention of template bug fixes.

**Comment by mattsoftware** [comment]
I have this issue as well, but under further investigation it looks like its just the error that might be misleading. If I have an issue with ANY of the variables used on the template, then it ALWAYS reports the first variable as being unknown. 

I have been trying to use aws_elasticache_cluster.main.cache_nodes.*.address however it seems I am hitting this bug (https://github.com/hashicorp/terraform/issues/8794) which is also causing my template to fail

**Comment by mitchellh** [comment]
Hey @marktb1, thanks for reporting this issue! Do you mind showing us a simple config we can use to reproduce this issue? Thanks!

**Comment by mattsoftware** [comment]
This might help.....

So there is a problem with sending the variable bugtwo through to the template, but the error reported is the following...
```
data.template_file.bug: Refreshing state...
Error applying plan:

1 error(s) occurred:

* data.template_file.bug: failed to render : 2:4: unknown variable accessed: bugone

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```
bug.tpl:
```
${bugone}
${bugtwo}
```

bug.tf:
```
data "template_file" "bug" {
    template = "${file("bug.tpl")}"
    vars {
        bugone = "one"
        bugtwo = "${two}"
    }
}

output "file" { value = "${data.template_file.bug.rendered}" }
```

**Comment by mattsoftware** [comment]
I should have mentioned of course if i change the bugtwo vars from "${two}" to somethign that works (like "two" for example) the template renders perfectly and we are all good.

The error is misleading as the actual problem isn't with bugone as the error message reports, the issue with with bugtwo which needs to be fixed to fix the rendering of the template. It seems that the first variable in the template is always the one that reports the error.

Hope all that makes sense.

**Comment by mitchellh** [comment]
Ooooh ooh. This is a dup. I don't remember the original issue but to fix this we need to make a backwards incompatible change to `template_file` in 0.8. The issue is that currently we don't catch plain `${var}` usage (as opposed to `${prefix.var}`) and error due to some design decisions made.

This is actually different from #8794.

I can't find the original its probably a number of pages back (I remember reading it back when there were ~1,000 issues). The fix is easy and already staged actually, but because it breaks BC with all existing templates (ick...), we're waiting for 0.8.

**Comment by rossedman** [comment]
@mattsoftware @mitchellh could there potentially be a regression in this? experiencing this on 0.10.8 right now.
