### ISSUE TITLE
Allow tags to be configured on instances launched by an ASG

### ISSUE THREAD

**Issue by bobtfish** [hashicorp/terraform#932]
I'd like to use terraform to define autoscaling groups which launch instances tagged a specific way (i.e. PropagateAtLaunch=true), similar to:

aws autoscaling create-or-update-tags --tags "ResourceId=my-asg,ResourceType=auto-scaling-group,Key=environment,Value=test,PropagateAtLaunch=true"

It'd also be useful to support tags which are PropagateAtLaunch=false, but that's less important for my use-case.

**Comment by ojongerius** [comment]
+1

**Comment by yikaus** [comment]
+1

**Comment by phrawzty** [comment]
:+1:

**Comment by dcapwell** [comment]
+1

**Comment by catsby** [comment]
This is implemented in #1319

**Comment by krisdigitx** [comment]
any examples on how to tag instances using ASG??

**Comment by bobtfish** [comment]
@krisdigitx you just create an auto scaling group with tags which specify propagate_at_launch = true, and then those tags are copied onto any instances launched by that ASG.

See https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html and http://docs.aws.amazon.com/autoscaling/latest/userguide/autoscaling-tagging.html for more info.
