### ISSUE TITLE
IAM Policy document and * Principals

### ISSUE THREAD

**Issue by TaiSHiNet** [hashicorp/terraform#9335]
When trying to specify Principals with `aws_iam_policy_document` I'd do something like

```
principals {
  type = "*"
  identifiers = ["*"]
}
```

This would result as:

```
"Principal": {
  "*": "*"
},
```

In the terraform state.
But whenever you re-run plan/apply it'll show a mismatch and require a change due to AWS converting the `"*": "*"` simply to `"Principal": "*"`
If I were to try with empty principal, the apply would fail with the following message:
`Error putting S3 policy: MalformedPolicy: Missing required field Principal`

**Comment by apparentlymart** [comment]
Thanks for reporting this, @TaiSHiNet.

It seems like our code needs to treat this situation as a special case and normalize it the same way AWS does. Probably we need to do this in our shared IAM policy normalization code as well as in the `aws_iam_policy_document` data source. :astonished:

**Comment by adhodgson1** [comment]
I am also getting this issue, at the moment I am not using the aws_iam_policy_document resource when I need to set principal to * for this reason.

**Comment by nwalke** [comment]
Just ran in to this when trying to allow an open bucket for hosting assets.

**Comment by TaiSHiNet** [comment]
Just to clarify, even if you apply with `"*": "*"` it'll be translated to "*" by AWS and work as intended
@nwalke ^

**Comment by nwalke** [comment]
Yup, I get it.  Just shows that it's going to be modified on each run.
