### ISSUE TITLE
crash with remote state file

### ISSUE THREAD

**Issue by liamjbennett** [hashicorp/terraform#9337]
In one of our projects the remote state file (stored in s3) was renamed. The remote config command was re-run to point to the new tfstate file but now every terraform plan results in the following crash

https://gist.github.com/liamjbennett/21a67fe4d260c485767307ca419ef292

TF version: v0.7.5

**Comment by jbardin** [comment]
Hi @liamjbennett,

Thanks for the bug report. This looks like a combination of a bug in copystructure that didn't get fixed for v0.7.5, and an issue that prevented the state file from be properly normalized.

I have a hunch that there are one or more `null` values in your state file, probably in a `Deposed` field. Can you confirm for me? Thanks!
