### ISSUE TITLE
TF doesn't respect arithmetic operator precedence

### ISSUE THREAD

**Issue by redbaron** [hashicorp/terraform#9338]
### Terraform Version
0.7.5

### Affected Resource(s)
```
output "zzz" {
  value = "${2 + 0 * 10}"
}
```

### Expected Behavior
`zzz = 2`

### Actual Behavior
`zzz = 20`

**Comment by jbardin** [comment]
Hi @redbaron,

Thanks for the report. I'm  going to close this one to track the issue over here #9169
