### ISSUE TITLE
Run integration tests in multiple aws partitions

### ISSUE THREAD

**Issue by jmcarp** [hashicorp/terraform#9342]
I don't know this for a fact, but I'm guessing that aws integration tests are only run in the default "aws" partition. I'm guessing this because I recently fixed some (but likely not all) partition-related bugs in https://github.com/hashicorp/terraform/pull/9273. Ideally, integration tests would run in at least two aws partitions so that bugs of this kind would be caught automatically. It sounds like getting an account in the aws-us-gov partition can be complicated, so testing in the aws and aws-cn partitions might be the simplest path.

I would send a patch for this myself, but I'm not sure where the acceptance tests run--I don't see them in travis and am guessing you all have a private ci service for this?

**Comment by stack72** [comment]
Hi @jmcarp 

Thanks for letting us know about this - we are indeed trying to get this setup! We are trying to get an account in US-Gov to help us run our tests in. Lots more work is going to happen in this work over the coming weeks as we are overhauling our acceptance tests :)

Please keep an eye for the announcements - hopefully we will catch these types of issues going forward

Paul

**Comment by jmcarp** [comment]
@stack72: were you able to get a govcloud account for testing? I'm asking because I just tried to upgrade to 0.8.x and ran into a govcloud-specific issue: https://github.com/hashicorp/terraform/pull/12414

**Comment by cnelson** [comment]
@stack72 Did y'all find a way to run your tests in GovCloud?  If not, I'd like to discuss running them for you in our account as we use terraform daily and frequently run into GovCloud specific issues.

Thoughts?

**Comment by stack72** [comment]
Hi @cnelson 

We have been able to run selective tests in GovCloud - the issue with running them all is that we will get a lot of failures due to unsupported features

Paul
