### ISSUE TITLE
Allow Assign Existing Float IP to New Droplet

### ISSUE THREAD

**Issue by miry** [hashicorp/terraform#9353]
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)

Please list the resources as a list, for example:
- digitalocean_floating_ip
- digitalocean_droplet

There are no example describes how to assign existing Float Ip resource to new droplet. https://www.terraform.io/docs/providers/do/r/floating_ip.html

It would great to have similar solution as for `aws_eip`: https://www.terraform.io/docs/providers/aws/r/eip_association.html

Example:

```
resource "digitalocean_floating_ip_association" "ip_assoc" {
  instance_id = "${digitalocean_droplet.web.id}"
  allocation_id = "${digitalocean_floating_ip.example.id}"
}
```

or provide ip in `digitalocean_droplet` resource:

```
resource "digitalocean_droplet" "web" {
  ...
  float_ips = ["${digitalocean_floating_ip.example.id}"]
  ...
}
```

**Comment by kasperisager** [comment]
This would be incredibly useful as it would allow Droplets to access the Floating IP during provisioning. I personally need this for a Consul deployment where each server node needs to advertise the address of its associated Floating IP. This allows me to effortlessly taint and rebuild a failed server and simply let Terraform bring up a new one with same Floating IP and Volume attached as the old one.

Much like @miry, I'm envisioning something along the lines of:

```tf
resource "digitalocean_volume" "consul" {
  ...
}

resource "digitalocean_floating_ip" "consul" {
  ...
}

resource "digitalocean_droplet" "consul" {
  ...
  volume_ids = ["${digitalocean_volume.consul.id}"]
  floating_ip = "${digitalocean_floating_ip.consul.ip_address}"
  
  provisioner "file" {
    destination = "/etc/consul.d/server.json"
    content = <<EOF
    {
      "advertise_addr": "${self.floating_ip}"
    }
EOF
  }
}
```

I'm currently hacking my around this using a `null_resource` but it's not pretty.
