### ISSUE TITLE
Automatically call `terraform get`

### ISSUE THREAD

**Issue by Supernomad** [hashicorp/terraform#9358]
### Description

I have been using terraform for a while now and have really used the module subsystem to great success, however there is one, quite honestly, infuriating issue where I have to litter `terraform get` throughout all of my CI scripts and configuration management. This is not the biggest deal in the world, but I am curious as to why this is the case. It is very apparent that terraform knows that the module doesn't exist, and its at least conceivable that it could quite easily run the get call automatically. Also this could only happen on the initial get, which would quell any issues regarding versioning.

That being said, I believe i am just missing something that makes this undesirable and/or impossible. Any clues as to what that something is?
### Terraform Version

``` shell
$ terraform -v
Terraform v0.7.4
```
### Affected Resource(s)

This specifically pertains to the module setup.
### Expected Behavior

I am expecting that if a given terraform module does not already exist that `terraform apply` would automatically grab this module from where ever it resides, whether that is locally or from some remote source. 
### Actual Behavior

You must call `terraform get` which is just odd as terraform obviously knows that it needs the module, and indeed knows exactly where to get it from.
### References

After a quick search I couldn't find anything about this, but please forgive me if I missed it.

**Comment by apparentlymart** [comment]
Hi @Supernomad!

In this way Terraform is being consistent with how things work in other languages, with `go get`, `npm install`, `pip install`, `gem install`, `berks`, etc. This is usually done to separate concerns: obtaining dependencies and running them is two separate steps, so in principle other tools can be used to do the "obtaining dependencies" step, and you don't need to pay the cost of this on every run or risk that a dependency will get upgraded behind your back.

I could definitely hear the argument that these reasons feel less strong for Terraform... it's unlikely that there would be a competing module manager, for example.

It's definitely an interesting thought, and it would be interesting to think through the costs and benefits of this particular design decision in Terraform, and whether deviating from the practice followed by other languages is warranted here.

**Comment by Supernomad** [comment]
@apparentlymart I totally understand that automatically getting the modules as a default action could be a breaking change for some, maybe it could be implemented as a pair of flags say `--get` and `--force-get`. 

Running `terraform apply --get` would allow for terraform to automatically get the required modules, if and only if they do not already exist. On the other hand running `terraform apply --force-get` would always grab the latest modules regardless if they already happen to exist. 

Does that sound like something within the realm of possibility for terraform's future?

**Comment by mitchellh** [comment]
I understand the reasoning @Supernomad but I'm in agreement with @apparentlymart here. 

`terraform get` is downloading potentially 3rd party code onto your machine and doing this automatically is scary in addition to just generally wanting a separate of concerns. Given its only a handful more characters to just do this manually: `terraform get && terraform apply` I'm inclined to say that let's just keep it that way for now.
