### ISSUE TITLE
Terraform panics when running plan

### ISSUE THREAD

**Issue by caseylang** [hashicorp/terraform#9359]
### Terraform Version
0.6.16
Unable to upgrade because of a similar issue in #8609 

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_target_pool

### Panic Output
https://gist.github.com/caseylang/d9278e9551db9d080155effa449e858c

### Expected Behavior
The plan should have been applied

### Actual Behavior
The plan panicked.

### References
- #8609

It's possible this issue is as well fixed by 6ee98a72e850803e8597b01111db2b9a3a15d33a but I thought this this is the first indication of this problem occurring with a 0.6.16 plan during an apply, it was worth creating a ticket. 

I should also bring up that, as opposed to `terraform plan` failing when using `0.7.2`, `terraform plan` runs without issue here. Only during `apply` does Terraform panic.

**Comment by jbardin** [comment]
Hi @caseylang,

Thanks for filing the issue. Since Terraform v0.6.16 isn't a current release, can you provide the panic output from the latest release?

**Comment by caseylang** [comment]
Sorry @jbardin, I resolved the issue by destroying my project and recreating with `0.7.5` :( 
As mentioned in the issue though, my errors match what was presented in #8609.

I see a PR with the fix from that issue has been added. Possibly that's enough and this issue can be closed.

**Comment by jbardin** [comment]
Thanks for getting back. That PR should take care of the panic, so I'll close this for now.
