### ISSUE TITLE
Missing `aws_autoscaling_group`.`termination_policies` cause changes on each apply

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#936]
If you don't define `termination_policies` within an `aws_autoscaling_group`, Terraform always detects a change.

```ruby
provider "aws" {
  region = "eu-west-1"
}

resource "aws_vpc" "default" {
  cidr_block = "10.12.0.0/16"
}

resource "aws_subnet" "private" {
  availability_zone = "eu-west-1a"
  cidr_block = "10.12.0.0/24"
  vpc_id = "${aws_vpc.default.id}"
}

resource "aws_security_group" "sample" {
  description = "Sample sg"
  vpc_id = "${aws_vpc.default.id}"
  name = "sample"
}

resource "aws_launch_configuration" "sample" {
  name = "sample"
  image_id = "ami-8f0087f8"
  instance_type = "t2.small"
  associate_public_ip_address = false
  key_name = "coreos-test"
  security_groups = ["${aws_security_group.sample.id}"]
}

resource "aws_autoscaling_group" "sample" {
  name = "sample"
  availability_zones = ["eu-west-1a"]
  launch_configuration = "${aws_launch_configuration.sample.name}"
  min_size = 1
  max_size = 3
  desired_capacity = 1
  vpc_zone_identifier = ["${aws_subnet.private.id}"]
}
```

No matter how many times you run `terraform apply`, you'll always see following:

```
aws_autoscaling_group.sample: Refreshing state... (ID: sample)
aws_autoscaling_group.sample: Modifying...
  termination_policies.#: "" => "<computed>"
aws_autoscaling_group.sample: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

I think that if no `termination_policies` option is given, it should automatically use [`Default`](http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/AutoScalingBehavior.InstanceTermination.html#default-termination-policy), there's AFAIK nothing to _"compute"_?

**Comment by radeksimko** [comment]
I reckon that this will help making it happen :)
https://github.com/mitchellh/goamz/pull/218

**Comment by phinze** [comment]
Yup https://github.com/hashicorp/terraform/pull/923 will fix once merged :grinning:

**Comment by radeksimko** [comment]
Ah, I've just noticed, this is probably going to be a duplicate in favour of #923 so I'm closing this one.

**Comment by radeksimko** [comment]
well, silly things happen when I forget what I read/said before just a few comments above... ignore what I just said. I'll keep it closed anyway as it's now linked.
