### ISSUE TITLE
syntax for map output from parallel lists

### ISSUE THREAD

**Issue by mblakele** [hashicorp/terraform#9374]
### Terraform Version

Terraform v0.7.4
### Enhancement Request

Say I've created parallel lists of resources, and I'd like to see certain details in output. For example:

``` hcl
output "test_id_list" {
  value = ["${aws_iam_user.dev_readonly.*.id}"]
}

output "test_key_list" {
  value = ["${aws_iam_access_key.dev_readonly.*.id}"]
}

output "test_secret_list" {
  value = ["${aws_iam_access_key.dev_readonly.*.secret}"]
}
```

This is ok, but ideally I'd like to combine these three parallel lists in a map of lists, something like:

``` hcl
{
   "user1": ["key", "secret"],
   "user2": ["key", "secret"],
   # ...etc
}
```

Have I missed a syntax to build this map as part of output? I know about #2114 and `map()` and `list()`, but that requires enumerating all the map keys.
### References
- #2114

**Comment by morkot** [comment]
+1

**Comment by mildwonkey** [comment]
This is now possible in Terraform 0.12! There are multiple ways of achieving what was originally requested. I think the `zipmap()` function fits this particular situation best, but [for expressions](https://www.terraform.io/docs/configuration/expressions.html#for-expressions) are also a great option, designed for transforming lists and maps.

Here's an example using zipmap:

```hcl
variable "users" {
  default = ["user1","user2"]
}

variable "keys" {
  default = [
    ["key1", "secret1"],
    ["key2", "secret2"],
  ]
}

locals {
  keymap = zipmap(var.users, var.keys)
}

output "usermap" {
  value = local.keymap
}
```

```
$ terraform output
usermap = {
  "user1" = [
    "key1",
    "secret1",
  ]
  "user2" = [
    "key2",
    "secret2",
  ]
}
```
