### ISSUE TITLE
datadog_monitor tags overwritten

### ISSUE THREAD

**Issue by nyanshak** [hashicorp/terraform#9375]
### Terraform Version

Terraform v0.7.5
### Affected Resource(s)
- datadog_monitor

The tags for Datadog monitors are for filtering, and are implemented in terraform as a map, but I think it should be a list instead to better match Datadog's API.

builtin/providers/datadog/resource_datadog_monitor.go:
https://github.com/hashicorp/terraform/blob/0475157c4f8a1bf506c83974672344830149a031/builtin/providers/datadog/resource_datadog_monitor.go#L265-L269

These lines split the tag on colon and add to a map, but this behavior is not correct if you have (for example):
- example_tag:value1
- example_tag:value2

This is valid in Datadog, but only the second value will be added to the terraform resource, since it's a map instead of an array.

This can result in terraform overwriting tags that should be tracked.

**Comment by ojongerius** [comment]
@stack72 you've merged #10570. Users will get errors if they do not update their configs. What do you think is the best way forward: just updating the changelog with a warning, or should we give a warning when the config has a map, instead of the list we expect?
When this provider was external I've similar things with breaking changes as a courtesy to users. Not sure what is common in Terraform.

**Comment by stack72** [comment]
Hi @ojongerius 

I think we should note this in the incompatibilities section of the changelog. The reason I merged this was because we are about to go to 0.8 and it seemed like it was the right place to make the change (major version)

Do you think something like this:

```
provider/datadog: datadog_monitor should be a map now and no longer a list
```

?

**Comment by jaygorrell** [comment]
@stack72 That's backwards, but otherwise that should be fine.

**Comment by stack72** [comment]
Hi 

Do we still think this is an error? It's been 2 months since this was reported and released

Paul

**Comment by ojongerius** [comment]
🎉
