### ISSUE TITLE
[AWS][API Gateway] aws_api_gateway_api_key is not attached to the new deployment

### ISSUE THREAD

**Issue by Ninir** [hashicorp/terraform#9376]
Hi everyone!

I'm having a weird issue with aws_api_gateway_api_key and linking to a given stage using AWS Api Gateway. Hope I'm not missing anything there :)
### Terraform Version

0.7.5
### Affected Resource(s)
- aws_api_gateway_api_key
### Terraform Configuration Files

``` hcl
resource "aws_api_gateway_api_key" "access_key" {
  name        = "${var.project_name}-${var.stack}-token"

  stage_key {
    rest_api_id = "${aws_api_gateway_rest_api.weather.id}"
    stage_name  = "${aws_api_gateway_deployment.deployment.stage_name}"
  }
}

resource "aws_api_gateway_deployment" "deployment" {
  depends_on = ["aws_api_gateway_method.weather_station_method"]

  rest_api_id = "${aws_api_gateway_rest_api.weather.id}"
  stage_name  = "${var.stack}"

  description = "${var.deployment_version}"

  variables {
    "version" = "${var.deployment_version}"
  }
}
```
### Expected Behavior

While having a aws_api_gateway_api_key which is linked to a given stage, if that stage is to be recreated (new deployment), the api_key should be linked to the new resource since it has a dependency to it (stage_name).
### Actual Behavior

The api_key is detached, the deployment gets recreated, the api_key is not attached again.
### Steps to Reproduce
- [1] Make an update (a variable for instance) so that the deployment resource gets updated.
- [2] terraform plan/apply:

``` hcl
-/+ aws_api_gateway_deployment.deployment
    description:       "20161014203600" => "20161014204500"
    rest_api_id:       "XXXXXX" => "XXXXXX"
    stage_name:        "prod" => "prod"
    variables.%:       "1" => "1"
    variables.version: "20161014203600" => "20161014204500" (forces new resource)

Plan: 1 to add, 1 to change, 1 to destroy.
```
- [3] The deployment gets updated. The api key is not associated to the stage looking at the AWS console.
- [4] Second terraform plan/apply:
  `aws_api_gateway_api_key.access_key` wants to be modified and attached:

``` hcl
aws_api_gateway_api_key.access_key: Modifying...
  stage_key.#:                      "0" => "1"
  stage_key.4088272323.rest_api_id: "" => "XXXXX"
  stage_key.4088272323.stage_name:  "" => "prod"
aws_api_gateway_api_key.access_key: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
- [5] The api key resource is attached to the stage again.
### References

The following issues are kind of related and the suggestion proposed might help there too.
- GH-6613

**Comment by stack72** [comment]
@Ninir is this still an issue?

**Comment by Ninir** [comment]
I think it is not anymore since usage plans :)
Closing!

**Comment by stack72** [comment]
<3

**Comment by haidaraM** [comment]
This is still issue with usage plans. The issue has moved to usage plan: They are not associated with the stage of the deployment.

**Comment by j-ventura** [comment]
Yep, this one is still there... I'm having my CI just `terraform apply` twice, but it makes me feel dirty...

**Comment by antvak** [comment]
> Yep, this one is still there... I'm having my CI just `terraform apply` twice, but it makes me feel dirty...

Any changes in this one? Is there a workaround?
