### ISSUE TITLE
Openstack provider doesn't refresh instance.attachment info

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#9378]
Using terraform 0.7.4, I have a `openstack_blockstorage_volume_v1` defined that is attached to a `k8s_openstack.openstack_compute_instance_v2`.   Sometimes, when creating the instance there is an error (I don't know what causes this but different issue):

```
* openstack_compute_instance_v2.k8s_master.2: Post https://osvip:8774/v2/a4d44df338e04faf9ac77d297a5681dc/servers/6fa08ea1-2a5d-45a5-922b-c2756e765432/os-volume_attachments: EOF
```

This leaves terraform in the following state:

```
openstack_blockstorage_volume_v1.k8s_master.2:
  id = 1a54a613-a698-48d1-813e-dae6ad1888fd
  attachment.# = 0
  availability_zone = nova
  description = K8S master storage
  metadata.% = 1
  metadata.readonly = False
  name = master-2
  region = default
  size = 30
  snapshot_id =
  source_vol_id =
  volume_type = standard


openstack_compute_instance_v2.k8s_master.2: (tainted)
  id = 6fa08ea1-2a5d-45a5-922b-c2756e765432
  access_ip_v4 = 56.119.244.180
  access_ip_v6 = [2001:558:fc0e:100:f816:3eff:febc:bb97]
  config_drive = true
  flavor_id = 103
  flavor_name = m1.medium
  image_id = d226e923-e8b5-4588-8512-92b6c20cafee
  image_name = k8s_1.3.8_0.0.0
  key_pair = default
  metadata.% = 0
  name = cmce_k8s_master_2
  network.# = 1
  network.0.access_network = false
  network.0.fixed_ip_v4 = 96.119.244.180
  network.0.fixed_ip_v6 = [2001:558:fc0e:100:f816:3eff:febc:bb97]
  network.0.floating_ip =
  network.0.mac = fa:16:3e:bc:bb:97
  network.0.name = Public
  network.0.port =
  network.0.uuid = 29e67a54-76dd-4626-b7cb-64e7c2bdaefa
  region = ndc_cmc_e
  scheduler_hints.# = 1
  scheduler_hints.2899862404.build_near_host_ip =
  scheduler_hints.2899862404.different_host.# = 0
  scheduler_hints.2899862404.group = ed588d52-34a8-43d4-b895-af5094fb5b93
  scheduler_hints.2899862404.query.# = 0
  scheduler_hints.2899862404.same_host.# = 0
  scheduler_hints.2899862404.target_cell =
  security_groups.# = 2
  security_groups.3481342481 = k8s_masters
  security_groups.3814588639 = default
  stop_before_destroy = false
  user_data = 9002d85cb15d2a6c510ba08bf0541d6bfefe5e0f
  volume.# = 1
  volume.3689035365.device = /dev/vdc
  volume.3689035365.id = 1a54a613-a698-48d1-813e-dae6ad1888fd
  volume.3689035365.volume_id = 1a54a613-a698-48d1-813e-dae6ad1888fd
```

The instance thinks the block storage is attached, but the block storage doesn't think it's attached to anything.  Looking at the resources outside of terraform, the volume is _not_ attached to the instance.  However, when you do a terraform refresh, terraform still thinks that instance has the volume attached.  This results in a subsequent terraform apply failing because terraform is trying to disconnect a volume that is already disconnected.  

Shouldn't terraform refresh that volume metadata on the instance?

**Comment by jtopjian** [comment]
Thanks for reporting this.

EOF errors are a little hard to debug. Do you have access to either the nova or cinder logs to see if you can spot a stack trace or another type of error?

**Comment by jtopjian** [comment]
@matthughes A few releases back, an `openstack_compute_volume_attach_v2` resource was added to handle the link between volumes and instances. I'm quite confident this resolves the issue you reported.

I'm going to close this, but if you still run into this problem using the new `openstack_compute_volume_attach_v2` resource, definitely open a new issue and I'll take a look.

Thanks,
Joe
