### ISSUE TITLE
Support ENI on route tables resources 

### ISSUE THREAD

**Issue by jespada** [hashicorp/terraform#938]
Currently there is no way in [route_table resource] (https://www.terraform.io/docs/providers/aws/r/route_table.html) to define an ENI as the part of the route, this could be useful, for auto scaling groups, for instance if you define an auto scaling group to auto-heal your nat instance(using an ENI and EIP), you can't know ahead the instance id, so you need to use the ENI.

**Comment by egarbi** [comment]
or maybe an extra attribute on [auto_scaling](https://terraform.io/docs/providers/aws/r/autoscale.html) resource in order to be imported from route_table.
Example:
route {
  cidr_block = "0.0.0.0/0"
  instance_id = "${aws_autoscaling_group.instance.id"}"
}
I don’t know if that is even possible.

**Comment by threetee** [comment]
+1 to this. I just tested with current master (https://github.com/hashicorp/terraform/commit/0a72db3ac3663ab506b74d7b1f97b522416d68b9), and route tables that have had any routes added after the fact have those routes removed by a 'terraform apply' run. In my prod environment, VPN and NAT servers are in autoscaling groups for resiliency, and whenever a new NAT instance comes online, it modifies the relevant route tables for its private subnets to tell them to send outbound traffic its way. Losing those routes causes significant problems, so it would be great to be able to somehow tell terraform to ignore them.

**Comment by ojongerius** [comment]
+1

**Comment by jtopper** [comment]
+1

**Comment by Tokynet** [comment]
+1
