### ISSUE TITLE
Terraform vsphere resource pool issue

### ISSUE THREAD

**Issue by ambadiaravind** [hashicorp/terraform#9380]
HI,

We are trying to create VM using terraform vsphere provider but when performing terraform apply its giving error no default resource_pool found.

~/usr/local/sbin/terraform -v
Terraform v0.7.6

Below is my configuration

provider "vsphere" {
  user = "user"
  password = "*****"
  vsphere_server = "vc.abc.com"
  allow_unverified_ssl = "True"
}

resource "vsphere_virtual_machine" "10V" {
  name   = "abc-test"
  vcpu   = 2
  memory = 8096
  datacenter = "STAGE"
  folder = "Systems"

  network_interface {
   label = "INA"
  }

  disk {
    template="Templates/10V-template"
  }
}

Below is the error I am getting

Error applying plan:

1 error(s) occurred:
- vsphere_virtual_machine.10V: no default resource pool found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Even though resource_pool is optional why I am getting error.
- Aravind

**Comment by taspencer** [comment]
I'm having the same problem. Any updates on this?

**Comment by joshmullis** [comment]
Having same issue which is making terraform unusable for our current setup.

**Comment by Spikeophant** [comment]
I have a similar issue, I use clusters heavily but not resource pools within those clusters.  We manage our compute at the cluster level, and have dedicated blades to different types of servers, for example we have several production clusters, some dedicated to general computing, some dedicated to DB servers, then we have clusters specific to QA and Dev, in this way we can buy blades that are appropriate for the workloads we're running.  I am going to pull and look at this issue as it is preventing me from moving from my lab env to work in my actual production env.

**Comment by Spikeophant** [comment]
Some additional notes on this, I have spent some time troubleshooting, I got the key off my vsphere server and began decrypting the traffic off the wire so I could see what we're actually asking for.  What I found was interesting in that my vsphere instance responds to a request to describe the resources with a MOB id for the resource pool for the cluster I'm working with, and when I look that up, the name is Resources.  So it's interesting that the provider isn't able to use this pool, and it does not look like an issue with Vsphere at all.  I will continue digging in and report back as I locate additional information.

**Comment by Spikeophant** [comment]
Fixed my issue, it turned out there was for some reason a slight difference in the cluster name as displayed in the Vcenter ui and what it gave back when looking up the MOB id.

**Comment by brettdh** [comment]
@Spikeophant what change did you have to make to get this to work? I'm having trouble here too, trying to figure out how to use the "default, invisible" resource pool (as described [here](https://docs.vmware.com/en/VMware-vSphere/5.5/com.vmware.vsphere.resmgmt.doc/GUID-60077B40-66FF-4625-934A-641703ED7601.html)) with terraform.

**Comment by brettdh** [comment]
@Spikeophant or: could you give an example of a host or cluster with the correct path to its default resource pool?

**Comment by jaredvonhalle** [comment]
I am having this same issue. Does anyone have any more details on the solution? To be clear, I'm trying to provision without a cluster (by specifying a specific host), so I'd also like to use the default resource pool of the host and am getting the "no default resource pool found" error described above.

**Comment by joshmullis** [comment]
@jaredvonhalle 

Set the below variable and replace the values enclosed in <> to the appropriate values.


```
vsphere_resourcepool = "/<DATACENTER>/host/<FOLDER>/<FOLDER>/<CLUSTER>/Resources"

resource "vsphere_virtual_machine" "vm" {
...
    resource_pool = "${var.vsphere_resourcepool}"
...
}
```

**Comment by jaredvonhalle** [comment]
Thank you @joshmullis. My issue is that I'm trying to do this without using a cluster. Rather, I just want to use the default resource pool of the host. I've tried every path I can think of to reference the host's resource pool directly, even though I think the correct way to do it should be to just leave out the resource_pool directive altogether.

**Comment by joshmullis** [comment]
@jaredvonhalle I agree on the leaving it out part for sure.  Did you try exchanging the <CLUSTER> with the esx hostname?

**Comment by albertvdv** [comment]
@jaredvonhalle - I am facing the exact same issue. I want to deploy VMs to a specific host (not to a cluster) to the default resource pool. Did you ever mange to find a workaround for your issue?

**Comment by jaredvonhalle** [comment]
Yes, finally figured it out! Here's what worked @albertvdv 

<folder>/<folder>/<hostName>/Resources

Where the folder tags represent the folder path that for your host in the "hosts and clusters" view of vSphere.

**Comment by albertvdv** [comment]
Thanks a lot @jaredvonhalle! Very helpful.
In case it helps anyone else - targeting a specific host (instead of a cluster) can be achieved as suggested by @joshmullis (under the the resource section) e.g. 

resource "vsphere_virtual_machine" "centos-vm" {
    name   = "centos-vm"
    vcpu   = 1
    memory = 1024
    cluster = "${var.vsphere_server}"

where vsphere_server is your vSphere host's FQDN
