### ISSUE TITLE
[Q] Is it possible to execute an action before resource is destroyed?

### ISSUE THREAD

**Issue by Ashald** [hashicorp/terraform#9393]
In my particular case it looks like this. I have a cluster of Consul servers as an Auto-Scaling Group of a fixed size (defined as a module):
```
module "consul" {
  source = "./consul"

  name = "consul-0.7.0"
  type = "c4.large"
  size = 3
  ami = "${var.aws_consul_ami}"
  security_groups = "${var.aws_dev_support_security_groups}"
  subnets = "${var.aws_dev_support_subnets}"
}
```

When there is a new release of Consul I'd like to change the `name` and `ami` parameters and apply the change so I'll get a new cluster created and the old one destroyed. Now, as you know, before tearing the old cluster down I need to ensure that Consul servers will gracefully leave so I won't end up with a broken Consul cluster.

I'd imagine it as some kind of trigger/hook that would be executed by Terraform before destroying old Consul cluster (ASG in other words) so I can execute a command that would make old servers gracefully leave the cluster.

Is it possible by any means? Or maybe there is an alternative solution for that?

**Comment by endofcake** [comment]
@Ashald , as an alternative solution you could look into using [Autoscaling Lifecycle hooks](http://docs.aws.amazon.com/autoscaling/latest/userguide/lifecycle-hooks.html#adding-lifecycle-hooks) + some lambda.

**Comment by Ashald** [comment]
@endofcake this wouldn't work as we cannot rely on auto-scaling events. Also, it wouldn't work n other platforms. The question is whether there is a way to execute an action when Terraform makes a change.

**Comment by jbardin** [comment]
Hi,

Thanks for opening an issue.

We have an older open issue about a "destroy" provisioner, with a lot of discussion at #386.
