### ISSUE TITLE
aws_instance needs to be destroyed and recreated to attach security group

### ISSUE THREAD

**Issue by jedipi** [hashicorp/terraform#9394]
### Terraform Version
0.7.5

### Affected Resource(s)
aws_instance

### Terraform Configuration Files
```hcl
resource "aws_security_group" "airflow_instance" {
	ingress = {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"
    cidr_blocks = ["XX.XXX.X.XXX/32"]		
	}
}

resource "aws_instance" "airflow" {
  ami             = "ami-0d729a60"
  instance_type   = "t2.micro"
  key_name 			  = "devkp2"
  security_groups = ["${aws_security_group.airflow_instance.name}"]
}
```

### Debug Output
https://gist.github.com/jedipi/dfde8349e36cc745605f7174d9343ff7

### Expected Behavior
aws_instance could be modified to add a security group without forcing a new resource

### Actual Behavior
the apply failed to modify the resource as is, and i had to reapply and destroy and create a new instance for the change to take effect

### Steps to reproduce
1. create aws instance with no security groups
2. modify state to create a new security group and attach this security group to the instance
3. run terraform apply

### Steps to Reproduce
1. `terraform apply`

**Comment by ole-flaregames** [comment]
Is your instance running in VPC network mode or ec2-classic network mode?

Because you cannot change the security groups within ec2-classic network without terminating the current instance and relaunching it again.

**Comment by jedipi** [comment]
ah, i think my error was not using `vpc_security_group_id's.. apologies
