### ISSUE TITLE
Having `-panic` in resource name causes Terraform to crash

### ISSUE THREAD

**Issue by endofcake** [hashicorp/terraform#9395]
### Terraform Version
Terraform v0.7.6

### Affected Resource(s)

- aws_sns_topic
- aws_lambda_function

I tried renaming the topic to something without `-panic`, and it worked without errors. I also renamed my existing lambda to have `-panic`, and it started to crash as well. This may be an issue with Terraform core.

### Terraform Configuration Files
```hcl
resource "aws_sns_topic" "something-panic" {
  name = "something-panic"
  display_name = "something panic"
}
```

### Panic Output
https://gist.github.com/endofcake/a9c6a21eb5b1484a4b5b6c29c5dc26f5

### Expected Behavior
No crash. 

### Actual Behavior
Terraform crashes.

### Steps to Reproduce
1. `terraform plan` (if I save the plan in a file, I can apply it without errors)

**Comment by kwilczynski** [comment]
@endofcake hi there! I am sorry that you are having issues.

I had a look at the attached panic output, but it seem fine in terms of Terraform completing, is it the right output?

**Comment by endofcake** [comment]
Hi @kwilczynski , yes, this is the correct output, I've replicated it several times. As I mentioned, if I save plan in a file, I am able to apply it, this works fine.

**Comment by mitchellh** [comment]
This is triggering panicwrap with a false positive. I looked at panicwrap to make it more robust but that led down a pretty dark path of complexity. I think in the interest of time and the fact that this is the first time this has happened in panicwrap's 2 year life, we'll just change the log messages.

**Comment by endofcake** [comment]
Thank you @mitchellh !
