### ISSUE TITLE
`ignore_changes` with variable does not work as expect

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#9396]
Terraform 0.7.6

I want to ignore change about `user_data`, and use code below is ok

```
lifecycle {
    ignore_changes = ["user_data"]
}
```

but when I want to use variable, it can not work as expect, and user_data changes force to 
create a new instance.
```
lifecycle {
    ignore_changes = ["${var.ignore_changes}"]
}

variable "ignore_changes" {
  type = "list"

  default = ["user_data"]
} 
```

**Comment by jbardin** [comment]
Hi @hanks

Thanks for the report. 

To add another data point, this doesn't work for individual string variables either.

**Comment by jtopper** [comment]
I've just hit this with the same use case. 0.7.7 also affected.

**Comment by mitchellh** [comment]
Lifecycle doesn't have any interpolation done at the moment.

Due to the implementation of Terraform, it'd be possible to interpolate variables but not resource attributes, etc. This would still be a decent undertaking but one that is at least possible...

**Comment by mitchellh** [comment]
"Fixed" in #9576. The solution for now is to error with interpolations.

It is technically possible to support interpolations here and I respect that feature request and that is something we should support in the future. However, we'll use this issue to track that it appears it should work and doesn't when it is explicitly designed to not support interpolations at the moment. Hence, a validation error is more appropriate for now.

**Comment by hanks** [comment]
ok, thanks, looking forward for this new feature :)

**Comment by jtopper** [comment]
That would suit my use case. I can't think of a reason I'd want to use
computed resource attributes in this situation anyway.

**Comment by jcampbell05** [comment]
One use case for us is on production we can change shape of our servers but dont want the ami to be updated but on dev we want latest cutting edge ami at all times.

Easiest way is to change the ignore_changes variable but at the moment isn't possible.

**Comment by mattock** [comment]
In our case we only (wanted) to manage AWS Lambda payloads in production, but not in testing, where they get updated outside of Terraform. Having interpolation support in ignore_changes would have helped accomplish this task fairly easily.
