### ISSUE TITLE
Support for different Azure Environments

### ISSUE THREAD

**Issue by arafato** [hashicorp/terraform#9400]
Hi--, 

currently, Terraform does not support the different Azure Environments such as GermanCloud, ChinaCloud and USGov Cloud which all use different endpoints for resource management and authentication compared to the "normal" Azure cloud. 
This is because Terraform uses [https://github.com/jen20/riviera](https://github.com/jen20/riviera) as part of its built-in Azure provider which does not support these environments.
We submitted two PRs (which have already been merged into the main branch) to fix this:
- [https://github.com/jen20/riviera/pull/16](https://github.com/jen20/riviera/pull/16)
- [https://github.com/jen20/riviera/pull/18](https://github.com/jen20/riviera/pull/18)

Can you please merge this new version of Riviera with Terraform to add according support? Thanks!

Best regards
--Oliver.

**Comment by stack72** [comment]
Hi @arafato 

Thanks for getting in touch - updating the vendoring of this package now - it will be released as part of Terraform 0.7.8

Sorry for the delay

Paul

**Comment by stack72** [comment]
Reopening this issue - the commit https://github.com/jen20/riviera/commit/d5a628a09ee1cd0c797a763e312ac910f91df0d7#diff-86a602c1be18246f0fa608526afe683eR119 introduces a panic into the ARM provider now

```
panic: reflect: call of reflect.Value.Interface on zero Value
jen20/riviera/azure/request.go:119
````

**Comment by arafato** [comment]
Hi @stack72 , thanks for getting back!
What were the input parameters that triggered this panic message? How can I reproduce this error?

**Comment by stack72** [comment]
Hi @arafato 

it was fixed in this PR https://github.com/jen20/riviera/pull/20
