### ISSUE TITLE
terraform plan crash from 0.7.4 to 0.7.6

### ISSUE THREAD

**Issue by yesteph** [hashicorp/terraform#9405]
Hello,

Running terraform plan is OK on 0.7.4.
We upgraded to 0.7.6 and now terraform plan crash. Downgrade is OK

See the attached crash.log file
[crash.log.zip](https://github.com/hashicorp/terraform/files/533931/crash.log.zip)

Tell me if you need additional information.

**Comment by jbardin** [comment]
Hi @yesteph,

Sorry about the crash, and thanks for reporting it. Can you provide the config that caused the crash, or at least the parts related to the interpolation that failed? 

Thanks!

**Comment by yesteph** [comment]
Thank you to treat this bug.

You will find the terraform config as attached document.
Note that I removed the terraform state files and the crash also occurs.

Regards.

2016-10-17 20:27 GMT+02:00 James Bardin <notifications@github.com>:

**Comment by jbardin** [comment]
@yesteph, 

You can't email attachments to GH issues. If the config is small you can put it inline, or provide a link to a gist, or even email me directly via my username @hashicorp.com

**Comment by jbardin** [comment]
Hi @yesteph,

I have a little more information in issue #9415, so I'm going to close this as a duplicate and continue any discussion there.

Thanks!

**Comment by yesteph** [comment]
Hello,

Thank you.

2016-10-18 17:18 GMT+02:00 James Bardin <notifications@github.com>:
