### ISSUE TITLE
Terraform 0.7.6 crashes on a plan that works with 0.7.5

### ISSUE THREAD

**Issue by hakamadare** [hashicorp/terraform#9415]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.7.6 (crashes)
0.7.5 (does not crash)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_subnet
- aws_route_table_association

I apologize, I don't have the time to go through a complete reproduction procedure right now.  In brief:

at root:
```
module "network" {
  source        = "../modules/network"
  stack         = "${var.stack}"
  env           = "${var.env}"
  azs           = ["${var.azs}"]
  vpc_cidr      = "${var.vpc_cidr}"
  public_cidrs  = ["${var.public_cidrs}"]
  private_cidrs = ["${var.private_cidrs}"]
  db_cidrs      = ["${var.db_cidrs}"]
}
```

in the `network` module:
```
resource "aws_subnet" "db" {
  vpc_id            = "${module.vpc.vpc_id}"
  cidr_block        = "${var.db_cidrs[count.index]}"
  availability_zone = "${var.azs[count.index]}"
  count             = "${length(var.db_cidrs)}"

  tags {
    Name = "tf-vpc-${var.stack}-${var.env}-db-${var.azs[count.index]}"
  }
}

resource "aws_route_table_association" "db" {
  count          = "${length(var.db_cidrs)}"
  subnet_id      = "${element(aws_subnet.db.*.id, count.index)}"
  route_table_id = "${element(split(",", module.vpc.private_route_table_id), count.index)}"
}
```

Crash log is attached.
[crash.log.zip](https://github.com/hashicorp/terraform/files/534684/crash.log.zip)

**Comment by jbardin** [comment]
Thanks @hakamadare!

This should be enough to reproduce the problem.

**Comment by jbardin** [comment]
Hi @hakamadare,

Unfortunately, I haven't been able to reproduce the crash from what's here. I think it might be failing in another part of the config (aws_route_table.private). Is there more to the config you can provide?

@yesteph, If you still have an example that fails with 0.7.6, that might be useful too.

Thanks!

**Comment by yesteph** [comment]
Hello @jbardin,

I have just sent you a mail with the conf leading to the crash.

Regards,

**Comment by jbardin** [comment]
Thanks for the config @yesteph, I was able to reproduce your issue with v0.7.6. That particular issue was fixed in v0.7.7.

@hakamadare, can you confirm is v0.7.7 also fixes the crash you were seeing?

**Comment by hakamadare** [comment]
@jbardin i no longer see the crash with 0.7.7.  thanks!

**Comment by jbardin** [comment]
Great! Thanks for the update!
