### ISSUE TITLE
Terraform does not validate variable stanza keys

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#9416]
### Terraform Version

Terraform v0.7.7-dev (94cbc37312ed08eccccadbec97d0fa76690fd417)
### Affected Resource(s)
- Core
### Terraform Configuration Files

``` hcl
variable "foo" {
  a = "b"
  c = "d"
}
```
### Expected Behavior

Terraform should validate that neither "a" nor "c" are valid keys to a `variable` stanza.
### Actual Behavior

Terraform happily ignores values.
### Steps to Reproduce
1. `terraform apply`

**Comment by mitchellh** [comment]
Fairly easy to fix, making notes for some future self or someone: we need a `loadVariables` function within the config parsing `config/loader_hcl.go` that actually does key validation using the `checkHCLKeys` function that we already have.

I'm not working on this now but making notes about how to fix.
