### ISSUE TITLE
Scaleway: Adding multiple volumes doesn't work

### ISSUE THREAD

**Issue by tboerger** [hashicorp/terraform#9417]
### Terraform Version

`0.7.6`

### Affected Resource(s)

* `scaleway_server`
* `scaleway_volume`
* `scaleway_volume_attachment`

### Terraform Configuration Files

```hcl
variable "access" {
  type = "string"
}

variable "org" {
  type = "string"
}

provider "scaleway" {
  access_key   = "${var.access}"
  organization = "${var.org}"
}

resource "scaleway_server" "store" {
  name  = "store"
  image = "75c28f52-6c64-40fc-bb31-f53ca9d02de9"
  type  = "C2S"
}

resource "scaleway_volume" "store" {
  count      = "3"
  name       = "vol-${count.index}"
  size_in_gb = "150"
  type       = "l_ssd"
}

resource "scaleway_volume_attachment" "store" {
  count  = "3"
  volume = "${element(scaleway_volume.store.*.id, count.index)}"
  server = "${element(scaleway_server.store.*.id, 0)}"
}
```

### Debug Output

https://gist.github.com/tboerger/c1e36a1ab2d53cfc072c6a9919bcbc66

### Panic Output

n/a

### Expected Behavior

I would expect to have a running server that got 3 additional volumes assigned.

### Actual Behavior

The setup simply fails because one volume attachment invokes a reboot of the server while the next volume attachment fails because the server is not running anymore:

```
2 error(s) occurred:

* scaleway_volume_attachment.store.2: StatusCode: 400, Type: invalid_request_error, APIMessage: server is being stopped or rebooted
* scaleway_volume_attachment.store.0: StatusCode: 400, Type: invalid_request_error, APIMessage: server is being stopped or rebooted
```

After the failed action you can see on the Scaleway web UI that only one volume have been attached to the server:

<img width="1045" alt="bildschirmfoto 2016-10-17 um 23 31 16" src="https://cloud.githubusercontent.com/assets/156964/19456541/20ef6e1a-94c2-11e6-9f15-5b427e0ce76f.png">

### Steps to Reproduce

1. Get an `access_key` and the `organization` from your Scaleway account
2. Simply execute `terraform apply` and wait

### Important Factoids

I tried to launch multiple nodes with multiple volumes at once, but I have slimmed down the example to keep it simple. Maybe it would already help to assign volumes while node creation, the API supports that.

### References

Maybe these issues are somehow related or maybe a PR solves the issue partially:

* #9254
* #8678

/cc @nicolai86

**Comment by nicolai86** [comment]
Hey @tboerger 

thanks for the bug report! 

I think the server state handling inside `scaleway_volume_attachment` is the problem.
Scaleway only allows to attach volumes to a stopped server, meaning the resource needs to stop the server, attach the volume, and start it up again.

As a test for this hypothesis you could add `state = "stopped"` to the `scaleway_server` resource. If it works with a stopped server we'll have to make the state handling more robust. 

Can you verify that?

**Comment by tboerger** [comment]
I thought that can really help, but that results in an server error: https://gist.github.com/tboerger/ec91591d98335f69187ba89cbdb49eb2

```patch
--- test.tf.orig	2016-10-18 07:51:34.000000000 +0200
+++ test.tf	2016-10-18 07:43:51.000000000 +0200
@@ -17,6 +17,7 @@
   name  = "store"
   image = "75c28f52-6c64-40fc-bb31-f53ca9d02de9"
   type  = "C2S"
+  state = "stopped"
 }

 resource "scaleway_volume" "store" {
```

**Comment by tboerger** [comment]
Maybe a solution can be to attach volumes directly to the server, the API accepts that (at least for creation). That can also solve #9254 and seems to be added within #8678, but than there is still the issue to add volumes to already created servers.

**Comment by nicolai86** [comment]
I think supporting volumes inline would work, and to work around the VC1M issue you referenced it's probably required.

The multiple volume attachment should be fixed in any case. Luckily adding some testcases should break this reliably, and then we can fix it.

**Comment by tboerger** [comment]
I really would like to provide a fix but I don't have enough internal knowledge of terraform to get an idea how to solve that issue with attaching volumes.

**Comment by nicolai86** [comment]
@tboerger not a nice solution, but if you're interested in the details check out #9493

**Comment by tboerger** [comment]
Getting solved via https://github.com/hashicorp/terraform/pull/9493
