### ISSUE TITLE
resourceAwsRouteExists throws error instead of returning false

### ISSUE THREAD

**Issue by idris** [hashicorp/terraform#9421]
While doing a `terraform refresh` (or `terraform plan` or `terraform destroy`), I get the error in **Output** below.

It seems like rather than hitting the [`return false, fmt.Errorf("Error while checking if route exists: %s", err)` branch](https://github.com/hashicorp/terraform/blob/94cbc37312ed08eccccadbec97d0fa76690fd417/builtin/providers/aws/resource_aws_route.go#L354-L356), it should [`return false, nil` like the lines below it](https://github.com/hashicorp/terraform/blob/94cbc37312ed08eccccadbec97d0fa76690fd417/builtin/providers/aws/resource_aws_route.go#L358-L362).

I think this is do-able by just checking the error code against `InvalidRouteTableID.NotFound`, [like is done elsewhere in the file](https://github.com/hashicorp/terraform/blob/94cbc37312ed08eccccadbec97d0fa76690fd417/builtin/providers/aws/resource_aws_route.go#L200).

### Terraform Version
Terraform v0.7.6

### Affected Resource(s)
Please list the resources as a list, for example:
- route
- route table

### Output
```
Error refreshing state: 5 error(s) occurred:

* aws_route.external: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-2e1a8148' does not exist
	status code: 400, request id: f8a4788e-1981-4dca-ae32-f72bc89ba841
* aws_route.internal.0: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-2c1a814a' does not exist
	status code: 400, request id: f1e1ad14-12cd-46db-84ef-7d24fa604d6e
* aws_route.internal.3: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-2f1a8149' does not exist
	status code: 400, request id: cb9b5cd6-264b-430f-93f2-11d78a0822a7
* aws_route.internal.1: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-2d1a814b' does not exist
	status code: 400, request id: feb5818d-478c-487b-940f-33a4f6772605
* aws_route.internal.2: Error while checking if route exists: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-2b1a814d' does not exist
	status code: 400, request id: a94621d1-391c-4b34-b7ad-2741bb030cee
```

### Expected Behavior
Terraform should recognize that the route table is gone.

### Actual Behavior
Terraform refresh fails due to the error.

### References
Seems similar to:
* https://github.com/hashicorp/terraform/issues/8388
* https://github.com/hashicorp/terraform/issues/5288

**Comment by kwilczynski** [comment]
@idris hi there! I am sorry that you are having issues.

I believe, I was able to address this issue in #9431. Hopefully this will resolve the issue for you.
