### ISSUE TITLE
Build local development environment error with vagrant 

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#9425]
Golang: 1.7.1
MacOS: 10.11.6 
Vagrant: 1.8.5
VirtualBox: 5.0.26 r108824

I want to build local development environment with vagrant+virtualbox, but when I execute `make` command in the container, **`cannot allocate memory`** error occurs, I check the VM memory size is 512MB, but in the vagrantfile, already set memory to 4096 MB to the virtualbox provider, maybe it is not work for the virtualbox provider. 

```
vagrant@terraform:/opt/gopath/src/github.com/hashicorp/terraform$ make
==> Checking that code complies with gofmt requirements...
==> Checking AWS provider for unchecked errors...
==> NOTE: at this time we only look for uncheck errors in the AWS package
==> Installing errcheck...
cgo failed: [go tool cgo -objdir /tmp/runtime_cgo_C656979320 -import_runtime_cgo=false -import_syscall=false -- -I /tmp/runtime_cgo_C656979320 -Wall -Werror cgo.go]: fork/exec /opt/go/bin/go: cannot allocate memory
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/18 02:35:13 Generated command/internal_plugin_list.go
TF_ACC= go test $(go list ./... | grep -v '/terraform/vendor/' | grep -v '/builtin/bins/')  -timeout=30s -parallel=4
go build github.com/hashicorp/terraform/builtin/providers/aws: /opt/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/terraform/vendor/github.com/xanzy/go-cloudstack/cloudstack: /opt/go/pkg/tool/linux_amd64/compile: signal: killed
go build github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/vim25/types: /opt/go/pkg/tool/linux_amd64/compile: signal: killed
FAIL    github.com/hashicorp/terraform [build failed]
ok      github.com/hashicorp/terraform/builtin/providers/archive    0.024s
ok      github.com/hashicorp/terraform/builtin/providers/atlas  0.003s
go build github.com/hashicorp/terraform/builtin/providers/aws: /opt/go/pkg/tool/linux_amd64/compile: signal: killed
FAIL    github.com/hashicorp/terraform/builtin/providers/aws [build failed]
ok      github.com/hashicorp/terraform/builtin/providers/azure  0.024s
ok      github.com/hashicorp/terraform/builtin/providers/azurerm    4.926s
...
```
# workaround
1. stop vm first
2. modify memory and cpu parameter in the VirtualBox Settings Menu
3. vagrant reload

**Comment by mengesb** [comment]
I can confirm this problem as well.

MacOS: 10.12
Vagrant: 1.8.5
VirtualBox: 5.1.6r110634

The work-around also worked for me.

What about supporting docker native instead of forcing the boot2docker?

**Comment by cblecker** [comment]
I just attempted this, and the VM's memory is allocated correctly at 4096 MB.

MacOS: 10.11.6
Vagrant: 1.8.6
VirtualBox: 5.1.8 r111374

@hanks @mengesb: Perhaps try upgrading your Vagrant and VirtualBox versions to the latest?

**Comment by hanks** [comment]
@cblecker thank you for your answer.

I upgrade to:
 
* Vagrant: 1.8.6
* VirtualBox: 5.1.8 r111374

and remove the .vagrant folder, virutalbox vm files, git pull latest master code and execute `vagrant up` again. It does not work, the vm memory size is still 512MB.

**Comment by james-flynn-ie** [comment]
Should we close this issue, as it relates to older versions of Vagrant and Virtualbox?
