### ISSUE TITLE
Ruined the ability to merge multiple maps in terraform 0.7

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#9426]
In newer versions of terraform (I guess 0.7+), the ability to merge variable maps has been ruined.

Previously you could have 2 different variable files, with e.g.

```
# file 1

instances.app_ami_id = "ami-12345678"
```

```
# file 2

instances.db_ami_id = "ami-abcdefgh"
```

And assuming a variable resource with:

```
variable "instances" {
  default = {
    app_ami_id = "please-set"
    db_ami_id = "please-set"
  }
}
```

You could then do a nice `terraform plan -var-file=./file1.tfvars -var-file=./file2.tfvars`, and it would all work out pretty nicely.

With the new var-file config in terraform 0.7, it no longer merges maps this way, and just takes the first map definition it finds (thus resulting in lots of undefined keys). There are several use-cases you may want to include multiple -var-files. (In our case we externally look up ami-ids through various scripts, so we dont have to keep tracking them in terraform)

It's a real shame this has been done, as it leads to anti-DRY code. Could terraform merge variable maps again?

**Comment by jbardin** [comment]
Hi @gtmtech,

Sorry you're having trouble with this issue.  We are tracking that issue with #8129, and we will update that issue when we have more information.
