### ISSUE TITLE
ARN attributes for more AWS resources?

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#943]
Floating an idea, which I'll try to implement:

Maybe more resources should have `arn` attributes. With IAM somewhat implemented (#939) it's likely these will be needed. For example, I have a process that registers instances with an ELB, and I need to create an IAM policy for that process, and to limit it to controlling the ELB it's responsible for, I need that ELB's ARN.

While it's possible to construct the ARN from the `name` attribute if you also know the region and the account number, it's a real pain to pass these variables around. Especially the account number: I don't even have it in the manifests. I don't even really know it: I have to look it up. Even with all the information available it's easy to miss or double a colon or otherwise mess it up.

Seems the providers could do this pretty easily, and make things more elegant overall.

**Comment by mitchellh** [comment]
That would be really really cool. Tagged.

**Comment by catsby** [comment]
Stumbling on to this... I added a `buildARN` method to RDS awhile back, because I needed it for tags:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L567

I'm sure if that's a good starting point as something we can extract, but I thought I'd mention it here.

**Comment by norcalli** [comment]
I would like to request this again as I ran into wanting the ELB arn for an IAM policy.

**Comment by stack72** [comment]
I am going to close this out - we are adding ARNs on a resource by resource basis when the API returns them and also when people make specific requests :)

Please feel free to open a PR for a specific ARN addition that you need :)

Paul
