### ISSUE TITLE
slow to destroy scaleway instances

### ISSUE THREAD

**Issue by dcharbonnier** [hashicorp/terraform#9430]
On scaleway you can _archive_ or _terminate_ an instance.
Currently terraform archive and then destroy the volume, this is extremely slow (almost an hour in some cases).
_Terminate_ would skip the archive step and, according to their support (ticket DRGAZ301) should be fast)

https://github.com/hashicorp/terraform/blob/276ff83b8458212bd4d96c5fc94765b899260aa1/builtin/providers/scaleway/helpers.go#L38   
https://github.com/hashicorp/terraform/blob/276ff83b8458212bd4d96c5fc94765b899260aa1/vendor/github.com/scaleway/scaleway-cli/pkg/api/api.go#L1200   
https://github.com/scaleway/scaleway-cli/blob/5801dfefe16e749b2600de765f465701a1a6edd2/pkg/api/api.go#L1200

**Comment by nicolai86** [comment]
there are still some broken tests but https://github.com/nicolai86/terraform/commit/364f70b8bd97175a80973e0c3c3dfbd36bb06f6e will eventually address this problem.

**Comment by dcharbonnier** [comment]
alternate solution `make testacc TEST=./builtin/providers/scaleway` pass
