### ISSUE TITLE
Changing openstack_compute_instance_v2 volume's device has no effect

### ISSUE THREAD

**Issue by ouroboros8** [hashicorp/terraform#9433]
### Terraform Version

Terraform v0.7.6
### Affected Resource(s)

Please list the resources as a list, for example:
- openstack_compute_instance_v2
### Terraform Configuration Files

``` hcl
resource "openstack_compute_instance_v2" "basic" {
  name = "Test1"
  region = "regionname"
  image_id = "8d4a1267-de54-4d41-a49f-1836c1189cec"
  flavor_id = "f0577618-9125-4948-b450-474e225bbc4c"

  volume {
    volume_id = "${openstack_blockstorage_volume_v2.volume_1.id}"
    device = "/dev/sdz" # changed from "/dev/sdb"
  }
}

resource "openstack_blockstorage_volume_v2" "volume_1" {
  region = "regionname"
  size = 1
}
```
### Expected Behavior

Detach volume on `/dev/sdb` from the device and reattach on `/dev/sdz`
### Actual Behavior

Nothing happens. Plan and apply pick up no changes.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the config above
2. change `/dev/sdz` to, for example, `/dev/sdf`
3. `terraform plan`, `terraform apply`

**Comment by jtopjian** [comment]
@ouroboros8 I apologize for the delay on this.

Please check out the new [`openstack_compute_volume_attach_v2`](https://www.terraform.io/docs/providers/openstack/r/compute_volume_attach_v2.html) resource. 

I just noticed a typo in the above docs: you _can_ specify a device with this resource and upon changing the device, the resource (in this case, the attachment of the volume) will be deleted and recreated. This will effectively detach the volume from the instance and reattach it with the new device name.

However, use the `device` argument with caution. 

Please see #11285 for updated documentation (until it's reflected in the website).

I'm going to close this issue, but please let me know if you have any questions. :)
