### ISSUE TITLE
allow self reference in resources

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#944]
It would be great there were a 'self' reference within a resource. A trivial example:

```
resource "aws_elb" "foo" {
  name = "${var.some_var}-elb"
  ...
  provisioner "local-exec" {
    command = "./some-script.sh ${self.name}"
  }
}
``` 

This can create cycles, which will have to be detected, but I think this is a very useful feature.

**Comment by mitchellh** [comment]
I agree that something like this should be possible. I think there is another issue tracking this same thing. If I find it I'll link it back and close this.

**Comment by errm** [comment]
It would be very useful in security groups for clusters where you want all the members of the group to be able to connect to one another

**Comment by mitchellh** [comment]
This is done with #1033, once merged.
