### ISSUE TITLE
container_definitions doesn't support a list

### ISSUE THREAD

**Issue by dropped** [hashicorp/terraform#9443]
Hi there,

I'm trying to use container_definitions on aws_ecs_task_definition resource as a list how is documented here: https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#container_definitions, but it's not working.

### Terraform Version
Terraform v0.7.6

### Affected Resource(s)
- aws_ecs_task_definition

### Terraform Configuration Files
```hcl
resource "aws_ecs_task_definition" "ecs-ctn-redmine" {
  family = "tdn-redmine"

  container_definitions = ["${file("task-definitions/postgres.json")}", "${file("task-definitions/redmine.json")}"]
  
  volume {
    name = "postgres"
    host_path = "/ecs/postgres"
  }

  volume {
    name = "redmine"
    host_path = "/ecs/redmine"
  }
}
```

### Expected Behavior
It should use the list of containers_definitions how is documented.

### Actual Behavior
```
Errors:

  * aws_ecs_task_definition.ecs-ctn-redmine: container_definitions must be a single value, not a list
```

Is the documentation deprecated? How can I add two or more containers on the same task_definition?

**Comment by kwilczynski** [comment]
@dropped hi there! I am very sorry that you are having troubles!

The documentation is perhaps not very clear, as per:

> `container_definitions` - (Required) A list of container definitions in JSON format. See AWS docs for syntax. Note, you only need the containerDefinitions array, not the parent hash including the family and volumes keys.

What is meant in here, is a list of task definitions passed/encoded as JSON, for example:

```json
[
  {
    "name": "alpha",
    "image": "alpha",
    "cpu": 1,
    "memory": 256
  },
  {
    "name": "beta",
    "image": "beta",
    "cpu": 4,
    "memory": 4096
  }
]
```

I will update documentation to make it clearer, and add an example illustrating this.

Hope this helps!

**Comment by kwilczynski** [comment]
@dropped hi again!

To add ...

You could have single file containing JSON and include it, or use some form of `formatlist` with `join` and `split`, etc., to achieved the final result based on two files, or something like this (not the nicest solution, though) utilising template:

```
data "template_file" "example" {
  template = "[ ${postgres}, ${redmine} ]"
  vars {
    postgres = "${file("task-definitions/postgres.json")}"
    redmine = "${file("task-definitions/redmine.json")}"
  }
}

output "rendered" {
  value = "${data.template_file.example.rendered}"
}
```

This renders:

```
$ ./terraform output
rendered = [ {
  "name": "postgres",
  "image": "postgres",
  "cpu": 4,
  "memory": 4096,
  "essential": true,
  "portMappings": [
    {
      "containerPort": 5432,
      "hostPort": 5432
    }
  ]
}
, {
  "name": "redmine",
  "image": "redmine",
  "cpu": 2,
  "memory": 1024,
  "essential": true,
  "portMappings": [
    {
      "containerPort": 80,
      "hostPort": 80
    }
  ]
}
 ]
```

Which parses into a valid JSON, as per:

```json
$ ./terraform output -json | jq '.rendered.value | fromjson'
[
  {
    "name": "postgres",
    "image": "postgres",
    "cpu": 4,
    "memory": 4096,
    "essential": true,
    "portMappings": [
      {
        "containerPort": 5432,
        "hostPort": 5432
      }
    ]
  },
  {
    "name": "redmine",
    "image": "redmine",
    "cpu": 2,
    "memory": 1024,
    "essential": true,
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 80
      }
    ]
  }
]
```

I hope this gives you some ideas, and again I am sorry for troubles!

**Comment by dropped** [comment]
Hi @kwilczynski.

Firts, thanks a lot for your help. 

Ok, now I got what you meant. Sorry for my misunderstanding.

Now I'm using just an one JSON as you said and it's working, thanks again mate.

So, it's solved.

**Comment by kwilczynski** [comment]
@dropped hi there! I am glad that you were able to resolve the issue. As promised, I have sent a Pull Request to update the documentation so that is showcases how to use this particular attribute to provide multiple container definitions (#9454).
