### ISSUE TITLE
Output of literal nested maps does not work

### ISSUE THREAD

**Issue by alefend** [hashicorp/terraform#9458]
Following #9268, I tried to declare an output variable as a map of maps. The outermost map declaration is interpreted well, while the inner one is interpreted as a list of maps.

### Terraform Version
0.7.7

### Affected Resource(s)
- output

### Terraform Configuration Files
```hcl
output "nested_map_output" {
    value = {
        scalar = "value"
        nested = {
            one = "1"
            two = "2"
        }
    }
}
```

### Expected Behavior
The expected output was:
```
nested_map_output = {
  nested = map[one:1 two:2]
  scalar = value
}
```

### Actual Behavior
The value of the `nested` item was instead a list of maps
```
nested_map_output = {
  nested = [map[one:1 two:2]]
  scalar = value
}
```

A workaround, as suggested in #8384, is to use the `map()` interpolation function for the inner declarations:
```
output "nested_map_output" {
    value = {
        scalar = "value"
        nested = "${map(
            "one", "1",
            "two", "2"
        )}"
    }
}
```

### References
- GH-8384
- GH-9268

**Comment by jbardin** [comment]
Hi @alefend,

Thanks for reporting the issue. Tee root cause here is that the `template` is defined as a string value, but it's getting a list. Normally this is caught during the initial validation, but that doesn't happen until later due to the splat in the interpolation string.

**Comment by jbardin** [comment]
Hi @alfend:

Sorry, about the misplaced template comment, posted that to the wrong issue during triage. Thanks for example, and we'll try to get this working!

**Comment by jbardin** [comment]
Hi,

The issue here stems from maps currently needing to be homogenous. Having the mix of a string type and a nested map is causes an error, but that error in an "output" fails silently. If you tried to use a map like this in a resource, you would see 

    map "var.somemap" does not have homogenous value types

I opened an separate issue to track the lack of feedback from outputs here at #9568
