### ISSUE TITLE
alb_target_group_attachment should specify 'Port' as optional attribute

### ISSUE THREAD

**Issue by redbaron** [hashicorp/terraform#9460]
### Terraform Version

0.7.7
### Affected Resource(s)

alb_target_group_attachment
### Expected Behavior

`Port` attribute is optional as per AWS specs: https://docs.aws.amazon.com/cli/latest/reference/elbv2/register-targets.html
### Actual Behavior

`Port` is mandatory

**Comment by kwilczynski** [comment]
@redbaron hi there! I am sorry you are having troubles with this resource!

I had a look and port is indeed optional, therefore we need to rectify this.

For posterity: 

https://godoc.org/github.com/aws/aws-sdk-go/service/elbv2#TargetDescription

**Comment by kwilczynski** [comment]
@redbaron hi there! Apologies for the delay concerning closing this issue!

There is one another thing that has to be done prior to closing this one, but I will keep you posted.
