### ISSUE TITLE
Adding new IAM User to an exisiting IAM Group 

### ISSUE THREAD

**Issue by zerolaser** [hashicorp/terraform#9464]
I am using terraform 0.7.3 and have gone through the  [terraform examples](https://www.terraform.io/docs/providers/aws/r/iam_group_membership.html) for creating users & groups.  I was wondering if there is a way to add a newly created user to add an exisiting IAM group which is not created using terraform.  Just like adding a new user to an exisiting policy using policy_arn.

**Comment by nwalke** [comment]
Have you tried using `aws_iam_group_membership` and feeding it the name of the group?
https://www.terraform.io/docs/providers/aws/r/iam_group_membership.html

Also, IAM groups can be imported in to Terraform.  Look towards the bottom of this page: https://www.terraform.io/docs/providers/aws/r/iam_group.html

**Comment by zerolaser** [comment]
@nwalke   just giving the group name in the resource `aws_iam_group_membership` added the user to the group `group = "group_name"`. I thought I should be calling the group name in this format ` group = "${aws_iam_group.group.name}"`. Also, When I import the exisiting IAM group and perform `terraform plan` its marking the group for destruction and is failing to destroy as the group has some policy already attached to it. could you guide me, how to proceed here ?

**Comment by nwalke** [comment]
It all depends what you want to do.  Do you want the group to be in Terraform or not?  If not, I would set the group name to a variable and use that as the group name under the `aws_iam_group_membership` resource.  If you do want it to be in Terraform, you'll need to do something like an import.

For your last question, since the group already has a policy (or policies) associated with it, you'd need to add those to your config as well.

**Comment by zerolaser** [comment]
@nwalke I currently, do not want this group to be a part of terraform. Setting the group name to a variable worked and `terraform output` was showing just the users which terraform created. But `terraform destroy` is removing all the users from the group, even though some users are not part of terraform state file, Which seems like a bug to me.

**Comment by nwalke** [comment]
Are you able to post your config?  The more you're able to share, the easier it would be for me to try and replicate.
