### ISSUE TITLE
Support lifecycle on aws_db_subnet_group

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/terraform#9465]
Would be really handy to be able to ignore_changes and prevent_destroy

Thanks!

**Comment by apparentlymart** [comment]
Hi @chadgrant!

Both of these things should work on all resources, so I'm a little confused as to what's causing your problem here. Would you mind sharing a bit of configuration where you tried to use this and what Terraform said when you ran it? Thanks!

**Comment by chadgrant** [comment]
sure, just removed it and still have the error up.

* aws_db_subnet_group.data: : invalid or unknown key: lifecyle

**Comment by chadgrant** [comment]
dur, my bad
