### ISSUE TITLE
Make terraform more resilient in face of i/o errors

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#9467]
### Terraform Version

0.7.6
### Affected Resource(s)

Any time terraform makes an HTTP call, it seems to re-resolve the DNS.   For whatever reason, my DNS server is not 100% and terraform will fail with:

```
* openstack_compute_instance_v2.noder: Get https://vip.openstack.net:8774/v2/a4d44df338e04faf9ac77d297a5681dc/servers/1da4371b-b7a1-4ead-b7a2-f961b40e17d5/os-volume_attachments: dial tcp: lookup vip.openstack.net on 69.252.80.80:53: dial udp 69.252.80.80:53: i/o timeout
```

Any chance terraform could start using https://github.com/hashicorp/go-retryablehttp?  It's quite a pain when you're half way through provisioning a 100-node cluster and the whole thing needs to be started over because a connection blip caused an issue.

**Comment by pkolyvas** [comment]
Seems this was completed some time ago. Closing it out.
