### ISSUE TITLE
Terraform keeps wanting to delete the identifier for an aurora instance

### ISSUE THREAD

**Issue by philipl** [hashicorp/terraform#9469]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- aws_rds_cluster_instance
### Terraform Configuration Files

``` hcl
# Aurora cluster instance
resource "aws_rds_cluster_instance" "director_db" {
    count              = "${var.rds_aurora_instance_count}"
    cluster_identifier = "${aws_rds_cluster.director_db.id}"
    instance_class     = "${var.rds_instance_class}"
}
```
### Expected Behavior

Should not plan any changes
### Actual Behavior

Attempts to remove instance identifier, which silently doesn't actually do anything. Change reappeares in plan the next time.
### Output

```
~ module.directormanagement.aws_rds_cluster_instance.director_db.0
    identifier: "terraform-20161018180000830893928w47" => ""

~ module.directormanagement.aws_rds_cluster_instance.director_db.1
    identifier: "terraform-20161018180000830953957aek" => ""

~ module.directormanagement.aws_rds_cluster_instance.director_db.2
    identifier: "terraform-20161018180000831827138fry" => ""
```
### Steps to Reproduce
1. `terraform plan`

**Comment by philipl** [comment]
Narrowed it down. This happens if an identifier is not provided in the configuration. However, the identifier is documented as optional, so either it should be made required or this behaviour fixed.

In 0.7.9, the bogus behaviour is even more extreme - it will destroy and recreate the resource - meaning it is no longer harmless.

**Comment by ccampanale** [comment]
👍 

We're seeing the same thing in 0.8.3. I see a PR has been in place with what appears to be a passing fix since Nov. 2016. Any idea when this will be merged?

In the meantime we are generating the identifiers from other resources/variables and the instance count.index, "${aws_rds_cluster.main.id}-instance-${count.index}" which seems to be fine but this should still be fixed to avoid confusion as it is an option variable.

Cheers!
