### ISSUE TITLE
most_recent does not return the most recent element

### ISSUE THREAD

**Issue by damphyr** [hashicorp/terraform#9471]
Doing 
```
data "aws_ami" "xenial" {
  most_recent = true
  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]

  }
  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }
  owners = ["099720109477"] # Canonical
}
```
we get an image from sometime in April

I narrowed the filter to ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-201610*"] and of the three values (there are images for 20161010, 20161011 and 20161013) the value returned is the _oldest_.

This with Terraform 0.7.5

**Comment by joshuaspence** [comment]
This was fixed in Terraform 0.7.6 (specifically #9277)
