### ISSUE TITLE
scaleway_server image not found

### ISSUE THREAD

**Issue by dcharbonnier** [hashicorp/terraform#9472]
```
data "scaleway_image" "docker" {
  architecture = "x86_64"
  name = "Docker"
}

resource "scaleway_server" "test" {
  name = "test"
  image = "${data.scaleway_image.docker.id}"
}
```

Result in `APIMessage: "f88b996d-3d9b-4ef1-bf70-ea7f64180d7a" not found`

It works with images id that are not public and I didn't tested with something else than docker

**Comment by dcharbonnier** [comment]
Docker => docker return the correct ID....

**Comment by dcharbonnier** [comment]
@nicolai86 are you able to create an instance with the official image 'Docker' on a x86 machine ? I confirm that I get a 404 on the server creation with the data_cource

**Comment by nicolai86** [comment]
@dcharbonnier I'm using the docker bootscript with xenial already: https://github.com/nicolai86/scaleway-kubernetes-demo/blob/master/main.tf. I'll play with the docker image later today or tmw to see what's not working for you

**Comment by nicolai86** [comment]
@dcharbonnier thanks for the bug report. 

I can confirm this is a problem with the `scaleway_image` data source. I hope to have a fix for this soon!

**Comment by nicolai86** [comment]
@dcharbonnier can you verify that #9899 solves this issue?
