### ISSUE TITLE
Support ELB proxy protocol

### ISSUE THREAD

**Issue by armon** [hashicorp/terraform#948]
It would be useful to have control over the proxy protocol for ELB. See:
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html#enable-proxy-protocol-api

**Comment by kidoman** [comment]
Hi guys, this would be a awesome feature.

**Comment by mohitsethi** [comment]
:+1:  for this feature.

**Comment by bscott** [comment]
:+1:

**Comment by bobtfish** [comment]
+1 we'd like this at Yelp
