### ISSUE TITLE
validate cidr_block is actually a cidr block in plan

### ISSUE THREAD

**Issue by jrynyt** [hashicorp/terraform#9481]
### Terraform Version

0.7.6
### Affected Resource(s)
- aws_security_group ingress/egress
- and any other resource that accepts cidr blocks
### Expected Behavior

`terraform plan` should fail if the value is not in cidr notation
### Actual Behavior

`plan` succeeds, then on `apply` the AWS API returns an error:

```
* aws_security_group.mysg: Error authorizing security group ingress rules: InvalidParameterValue: CIDR block 1.2.3.4 is malformed
    status code: 400, request id: XXX
```
### Steps to Reproduce
1. Use a value for `cidr_block` in aws_security_group ingress/egress that is not actually a cidr block.
2. `terraform plan` -- succeeds
3. `terraform apply` -- fails

**Comment by kwilczynski** [comment]
@jrynyt hi there! I am sorry that you've had an issue!

Adding CIDR validation is not a bad idea.

**Comment by kwilczynski** [comment]
To add, we already have `validateCIDRNetworkAddress` helper, which some of the resources are using already. It would be  matter of re-using it.

**Comment by magnusthorne** [comment]
+1

**Comment by pjfbashton** [comment]
To add to this - TF will fail if the value is in CIDR notation however is not valid network.
