### ISSUE TITLE
Parameter Group has a 'dot' in its name. Plan command results in an error.

### ISSUE THREAD

**Issue by AnudeepReddyJ21** [hashicorp/terraform#9485]
Hi,

I have a RDS Parameter group with the name 'default.aurora5.6'. I imported it with the terraform import command 

./terraform import aws_db_parameter_group.default-aurora5-6 default.aurora5.6 

Now I create a configuration script for it.

resource "aws_db_parameter_group" "default-aurora5-6" {
    name = "default.aurora5.6"
    family = "aurora5.6"
    description = "Default parameter group for aurora5.6"
}

./terraform plan results in an error that only alphanumeric characters are allowed in name. How do I fix this? That's a default group.

Thanks,
Anudeep

**Comment by kwilczynski** [comment]
@AnudeepReddyJ21 hi there! I am sorry you are having issues!

I had a look, and the validation is trying to make sure that the following criteria are met:

- Must be 1 to 255 alphanumeric characters;
- First character must be a letter;
- Cannot end with a hyphen or contain two consecutive hyphens;

Which is what the API documentation seem to be suggesting. I have not tried to create a parameter group with a dot yet, but they might be allowing a dot as part of their "alphanumeric characters set".

There is one question I need to ask - why do you want to import the default parameter group? You cannot manage it as a resource, and it is there by default. In other words, there is very little you can gain from importing the default parameter group. Is this something you really want to do?

**Comment by AnudeepReddyJ21** [comment]
Yes. I didn't think about that. I don't have to import the default group. I was just importing all the groups and came across this issue with default option groups and parameter groups. 

Thank you very much for the quick reply.

**Comment by kwilczynski** [comment]
@AnudeepReddyJ21 hi there! I am glad you were able to resolve your issue.

I have check and it does not appear that you can create a parameter group with dot in the name, as per:

<img width="671" alt="screen shot 2016-10-20 at 17 59 08" src="https://cloud.githubusercontent.com/assets/250723/19570469/1779dec4-96f2-11e6-9386-676a6df60370.png">

**Comment by AnudeepReddyJ21** [comment]
Thank you for verifying. Yeah only the default ones seem to have a dot for parameter groups and a colon for option groups, and thus cannot be used in terraform scripts. I appreciate your time.
