### ISSUE TITLE
AWS RedShift Subnet Group resource does not support tags

### ISSUE THREAD

**Issue by davidski** [hashicorp/terraform#9492]
### Terraform Version
Terraform 0.7.7

### Affected Resource(s)
- aws_redshift_subnet_group

### Terraform Configuration Files
```hcl
resource "aws_redshift_subnet_group" "test" {
  name = "redshift_test"
  subnet_ids  =[ "${module.redshift_subnet.subnet_id}" ]
  tags {
    Name = "test_subnet"
    description = "Primary subnet for redshift"
    project = "test"
    managed_by = "Terraform"
  }
}
```

### Expected Behavior
Creates a RedShift subnet group with the specified tags.

### Actual Behavior
`invalid or unknown key: tags`

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Tags on RedShift subnet groups are supported via the aws-cli as referenced at http://docs.aws.amazon.com/cli/latest/reference/redshift/create-cluster-subnet-group.html

**Comment by dennis-bsi** [comment]
I have reproduced this behavior and will attempt to fix tonight.  Building some new redshift clusters this weekend so I'll definitely get to it then.
