### ISSUE TITLE
Support for base-2 logarithms (or subnet split function)

### ISSUE THREAD

**Issue by matschaffer** [hashicorp/terraform#9498]
### Terraform Version

0.7.7
### Affected Resource(s)

Interpolation
### Requested Behavior

So I have this worked out for creating VPCs with subnets in a module:

``` hcl
resource "aws_vpc" "main" {
  cidr_block = "${var.cidr_block}"
  tags { Name = "${var.name}" }
}
resource "aws_subnet" "public" {
  count = "${var.availability_zone_count}"

  vpc_id = "${aws_vpc.main.id}"

  cidr_block        = "${cidrsubnet(var.cidr_block, var.cidrsubnet_newbits, count.index)}"
  availability_zone = "${element(var.availability_zones, count.index)}"

  map_public_ip_on_launch = true

  tags { Name = "${var.name}-public-${element(var.availability_zones, count.index)}" }
}
```

Pretty cool, but it would be especially awesome if `cidrsubnet`'s  `newbits` arg didn't have to leak out of the abstraction and could be computed based on `length(var.availability_zones)`.

In python it'd be `int(math.ceil(math.log(len(availability_zones), 2)))` but without better math support or other helpers, I'll just have to have people do the math and pass in variables for now.

**Comment by joshuaspence** [comment]
+1

**Comment by rjinski** [comment]
+1
