### ISSUE TITLE
Lambda UpdateFunctionConfiguration support

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#9506]
Is it already possible to update the function configuration of a Lambda function in AWS? I am directly referring to [this function in AWS API](http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html)

**Comment by Puneeth-n** [comment]
Thanks!

**Comment by Ninir** [comment]
Hi @Puneeth-n 
Yes it is already the case if you at [this](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_lambda_function.go#L514) :)

That's meant, if you update your lambda resource, this API will be called.

Do you need more information on this?

**Comment by Puneeth-n** [comment]
@Ninir Thanks! closing the issue.
