### ISSUE TITLE
provider/azurerm azurerm_subnet should have its gateway IP as an exported attribute

### ISSUE THREAD

**Issue by wendorf** [hashicorp/terraform#9519]
According to the [Azure virtual network documentation], the gateway IP address of a subnet is predictable (e.g. if the subnet is 10.0.3.0/24, the gateway IP is 10.0.3.1). It is as simple as `cidrhost(azurerm_subnet.my_subnet.address_prefix, 1)`.

It would be nice if this information were part of the built-in exported attributes for azurerm_subnets so that users of the resource can easily determine what the Gateway is without needing to do calculations.
### Terraform Version

0.7.7
### Affected Resource(s)
- azurerm_subnet
### Expected Behavior

The resource knows its own gateway IP
### Actual Behavior

The resource does not know its gateway IP

**Comment by pmcatominey** [comment]
Hey @wendorf,

I'm not sure that the subnet is the right resource to expose the Gateway IP as not all subnets will have a Gateway deployed. The IP should instead be exported by the gateway resource which is currently in progress: #9255.

**Comment by wendorf** [comment]
@pmcatominey I believe the term "gateway" is a little overloaded in Azure. I'm not referring to a virtual network gateway (which is used to connect your Azure subnet to your personal on-prem network), but the default subnet gateway which I believe is always present in an Azure subnet.

**Comment by pmcatominey** [comment]
Hi @wendorf,

I've just checked the API after creating a Network via the Portal and only a single subnet is present, the Gateway Subnet was not. Even in cases where the GatewaySubnet is present, there is no data from the API which indicates the gateway address. I still believe that the best place to expose this is in the virtual network gateway resource itself.

**Comment by DevOpsFu** [comment]
@wendorf I see what you're getting at here, but I've never come across a use case for knowing that particular piece of information about a subnet in Azure. Could you elaborate?

**Comment by wendorf** [comment]
@DevOpsFu I use [BOSH](https://bosh.io), a (most) IaaS-agnostic software deployment and VM management tool. To use it with Azure, it needs to know the specifics of your subnet, including the gateway address. You can see that in the example manifest [here](https://bosh.io/docs/init-azure.html) if you look at the `/networks/[type=manual]/subnets/*/gateway` key.

I'd like to programmatically configure my BOSH environment without needing to know the implementation details of Azure, which is why having the gateway IP as an attribute would be valuable.
