### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Devinsuit** [hashicorp/terraform#9522]
https://www.terraform.io/intro/getting-started/remote.html  The link  **Environments tab in Atlas** is broken.

https://www.terraform.io/docs/providers/google/r/compute_instance_group.html The link  **the official documentation**  is broken

**Comment by walterdolce** [comment]
> https://www.terraform.io/docs/providers/google/r/compute_instance_group.html The link the official documentation is broken

This should be fixed by #9524. Regarding the first link, I couldn't find a reference to fix that as well (even in the various account areas in Atlas after I logged in). Perhaps someone from the core maintainers can help?
