### ISSUE TITLE
provider/bitbucket fork_policy not updated correctly

### ISSUE THREAD

**Issue by ksatirli** [hashicorp/terraform#9529]
Hi there,

I'm running into a problem with the `bitbucket_repository` resource. It seems remote fields are not correctly updated, even though they are stored in the `tfstate` file. 

This ticket is specific to `fork_policy`, but I've noticed similar issues with `is_private` and `language`.
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- bitbucket_repository
### Terraform Configuration Files

``` hcl
resource "bitbucket_repository" "test-repository" {
  owner = "${var.bitbucket_username}"
  name = "test-repository-3kjh4asdkj"
  is_private = "true"
  language = "other"
  fork_policy = "no_forks"
}
```

Note: in the above example, `bitbucket_username` is just the same username used to configure the provider itself.
### Panic Output

no panic
### Expected Behavior

The `fork_policy` should be set on an initial run and then only show up as changed when it actually has changed
### Actual Behavior

The `fork_policy` shows as changed on every run.
### Steps to Reproduce
1. `terraform apply`
2. inspect initial output:

``` hcl
+ bitbucket_repository.test-repository
    clone_https: "<computed>"
    clone_ssh:   "<computed>"
    fork_policy: "no_forks"
    has_issues:  "false"
    has_wiki:    "false"
    is_private:  "true"
    language:    "other"
    name:        "test-repository-3kjh4asdkj"
    owner:       "my-bitbucket-username"
    scm:         "git"
```
1. Another `terraform apply` will then show that the resource has been updated, again. This shows up as changed resource on every run.
### Important Factoids

n/a

**Comment by cwood** [comment]
I dont get this at all.

```sh
╭─cwood@cwood  ~/Projects/playground/terraform
╰─♥ terraform apply
bitbucket_repository.test-repository: Creating...
  clone_https: "" => "<computed>"
  clone_ssh:   "" => "<computed>"
  fork_policy: "" => "no_forks"
  has_issues:  "" => "false"
  has_wiki:    "" => "false"
  is_private:  "" => "true"
  language:    "" => "other"
  name:        "" => "test-repository-3kjh4asdkj"
  owner:       "" => "colinbits"
  scm:         "" => "git"
bitbucket_repository.test-repository: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
╭─cwood@cwood  ~/Projects/playground/terraform
╰─♥ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

bitbucket_repository.test-repository: Refreshing state... (ID: colinbits/test-repository-3kjh4asdkj)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
╭─cwood@cwood  ~/Projects/playground/terraform
╰─♥ terraform apply
bitbucket_repository.test-repository: Refreshing state... (ID: colinbits/test-repository-3kjh4asdkj)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by cwood** [comment]
This might be a issue with the PUT api. Ill take a look.

**Comment by cwood** [comment]
I just talked to our devs and the issue is with is_private and forking_policy. It can only be set on create and can not be updated yet. I can set this to on change to delete and create the repo.

**Comment by ksatirli** [comment]
Apologies for the late reply @cwood and thank you for your patience.

I just tried my original code and was indeed unable to reproduce it. I'll chalk it up to a ghost in the machine.

That being said, I do see issues with the `PUT` API and it marking resources as having pending  changes on every run.

Setting this to "on change -> delete" seems dangerous (unless I am misunderstanding). I certainly wouldn't want to lose a repo just because I updated a flag in TF.

**Comment by cwood** [comment]
The bug is submitted internally, for now, this is more an issue with the bitbucket API then with terraform. The code that handles the fork policy is really just two flags and it will block based on is_private or not.

Eg; if you set is_private to False from True it wont allow you to unless the forking policy. Depending on your change bitbucket might allow you through.

**Comment by ksatirli** [comment]
Thanks for the clarification @cwood! 

Do you have any updates at this point?

**Comment by cwood** [comment]
Not super this has been ticketed in our Jira. Ill see if I can poke seomeone on our API team to handle this.
