### ISSUE TITLE
aws_rds_cluster documentation refers to French AWS docs

### ISSUE THREAD

**Issue by ligustah** [hashicorp/terraform#9539]
Hi there,

the current documentation of the aws_rds_cluster resource contains a link to the French version of the "[RDS Maintenance](http://docs.aws.amazon.com/fr_fr/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html)" page. I assume this was unintentional and might need to be changed.

**Comment by ligustah** [comment]
[More pages](https://github.com/hashicorp/terraform/search?utf8=%E2%9C%93&q=fr_fr) seem to have such links.

**Comment by kwilczynski** [comment]
@ligustah hi there! Ah, nice catch!

**Comment by stack72** [comment]
closed via #9544
