### ISSUE TITLE
Issue Creating S3 Bucket : AuthorizationHeaderMalformed

### ISSUE THREAD

**Issue by CruzanCaramele** [hashicorp/terraform#9545]
### Terraform Version
**Terraform v0.7.7**

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### Terraform Configuration Files
```
resource "aws_s3_bucket" "db-backup-bucket" {
	bucket = "db-backup-bucket"
	acl    = "private"

	tags {
		Name        = "db-backup-bucket"
		Environment = "Prod" 
	}
}

variable "aws_access_key" {
	type        = "string"
	description = "Access Key Account"
	default     = "{{env `AWS_ACCESS_KEY_ID`}}"
}

variable "aws_secret_key" {
	type        = "string"
	description = "Secret Key Account"
	default     = "{{env `AWS_SECRET_ACCESS_KEY`}}"
}

#--------------------------------------------------------------
# Region
#--------------------------------------------------------------
variable "region" {
	type        = "string"
	description = "The AWS region to create resources in."
  	default     = "us-east-1"
}
```

### Expected Behavior
The S3 Bucket should be created

### Actual Behavior
Fails to Create the bucket
```
**aws_s3_bucket.db-backup-bucket: Error creating S3 bucket: AuthorizationHeaderMalformed:**
**The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'**
** status code: 400, request id: F01E2A7A94C88BAE **
```

### Steps to Reproduce
1. `terraform apply`

**Comment by CruzanCaramele** [comment]
changing the name of the bucket to be unique accross AWS fixes this issue. Closing this as resolved

**Comment by oonisim** [comment]
According to the AWS, there are three situation when the AuthorizationHeaderMalformed for S3 can happen.

```
1. When you are creating a bucket with a name that this already being used as a bucket name in your AWS account or in any other AWS account (Please note that S3 bucket names are globally unique [1]). 

2. When you are doing an operation on your S3 bucket and you have set the Region variable (either when configuring the SDK or while using environment variables etc) to a region other than the one in which the bucket is actually present [2] [3]

3. You have recently deleted a S3 bucket in a particular region (say us-east-1) and you are trying to create a bucket (with the same name as the the bucket that was deleted) in another region right after deleting the bucket.
```

Hence, try to change the bucket name or give time (up to 2 days) and try again.
>  if a bucket which is present in a certain region say (us-east-1) is deleted, you can always create a bucket with the same name in another region. There is no such restriction in S3 that states you cannot do this. However, you will be able to do this only after you allow some time after deleting the bucket. This is because S3 buckets follow the Eventual Consistency model in the case of DELETE operation [4]. It means that after you delete a bucket, it takes a few hours, generally up-to 24 to 48 hours for the DELETE operation to be replicated across all our data centres. Once this change has propagated you can go ahead and create the bucket again in the desired region.
