### ISSUE TITLE
ebs_block_device attribute changes on aws_launch_configuration not detected during plan

### ISSUE THREAD

**Issue by aequitas** [hashicorp/terraform#9548]
When changing an `ebs_block_device` attribute on a `aws_launch_configuration` Terraform will not detect the change needs to be made and the plan stays empty.

Removing the attribute is also not detected as a change. 

The change will be applied if:
- a change is triggered by an argument of the launch configuration.
- an attribute is added
- a launch configuration resource is tainted
### Terraform Version

0.7.7
### Affected Resource(s)
- aws_launch_configuration
### Terraform Configuration Files

``` hcl
resource "aws_launch_configuration" "server" {

    .........

    lifecycle {
        create_before_destroy = true
    }

    ebs_block_device {
        device_name = "/dev/xvdf"
        volume_type = "gp2"
        #50 -> 200
        volume_size = 200
        delete_on_termination = false
    }
}
```
### Expected Behavior

When changing parameters of a `ebs_block_device` or when removing the attribute altogether Terraform should pickup this difference and put it in the plan.
### Actual Behavior

Terraform does not pickup this difference, plan stays empty.

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

data.terraform_remote_state.infra: Refreshing state...
data.template_file.init: Refreshing state...
aws_iam_instance_profile.server: Refreshing state... (ID: server)
aws_launch_configuration.server: Refreshing state... (ID: server-201610211927381563635933fu)

No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```
### Steps to Reproduce
1. create launch configuration with `ebs_block_device` attribute
2. plan & apply
3. change parameters of `ebs_block_device` attribute
4. plan

**Comment by mindw** [comment]
See #1445?

**Comment by aequitas** [comment]
@mindw thanks, total case of rtfm.
