### ISSUE TITLE
Outputted map does not contain all expected keys

### ISSUE THREAD

**Issue by moio** [hashicorp/terraform#9549]
### Terraform Version

Latest 0.7.8
### Affected Resource(s)

Core issue. Reproduced with either:
- aws_instance
- [libvirt_volume and libvirt_domain](https://github.com/dmacvicar/terraform-provider-libvirt)
### Terraform Configuration Files
- https://github.com/moio/terraform_output_map_issue_example

Please add proper AWS credentials in https://github.com/moio/terraform_output_map_issue_example/blob/master/main.tf#L2
### Debug Output

https://gist.github.com/moio/2a980e348bccde29be8d13e47821e218
### Expected Behavior

```
terraform_output_map_issue_example$ terraform plan
Refreshing Terraform state in-memory prior to plan...
...
+ module.base.aws_instance.example
...
+ module.extension.aws_instance.example

Plan: 2 to add, 0 to change, 0 to destroy
```
### Actual Behavior

```
terraform_output_map_issue_example$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * key "base_instance_id" does not exist in map var.configuration in:

Extension of ${var.configuration["base_instance_id"]}
```
### Steps to Reproduce
- clone repo above
- add AWS credentials
- `terraform plan`
### Important Factoids

I am trying to use a variable from an output of a module in another module.

Note that this does work in case of literals ([`param1` in the sample](https://github.com/moio/terraform_output_map_issue_example/blob/master/main.tf#L9)).

Also note that this does work using the [hacky interpolated map literal syntax](https://github.com/moio/terraform_output_map_issue_example/blob/master/base/main.tf#L15).
### References
- https://github.com/hashicorp/terraform/issues/8384
- https://github.com/hashicorp/terraform/pull/9268

**Comment by flypenguin** [comment]
this is a major blocker in my current efforts to automate our whole vpc setup and I went pretty much crazy debugging my system until I found this. any ideas of when this is fixed?

**Comment by flypenguin** [comment]
BTW #6524 is also applicable to this - the map contents get indented every time I (in that case my editor) uses fmt before saving. pretty annoying :)

**Comment by mitchellh** [comment]
Fixed in master!

**Comment by moio** [comment]
Thanks everybody, great job!

**Comment by moio** [comment]
@mitchellh, @jbardin: JFYI while testing this I found several possibly related failures reported in https://github.com/hashicorp/terraform/issues/10187. Thanks again!
