### ISSUE TITLE
Passing List to an input variable of a module

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#955]
I am building an AWS AutoScaling group module and wanted to pass a `List` instead of string type for some of its variables.

Currently it seems that this is not possible. Is there a way to create a list by exploding a string to a list?

Is there a way to overcome this without hacking the core too much?

**Comment by pmoust** [comment]
Creating a List by using a function to explode a string based on a given delimiter would suffice for my use case as well, but there is no such native function built-in.

**Comment by pmoust** [comment]
Relates https://github.com/hashicorp/terraform/issues/57

**Comment by mitchellh** [comment]
#885 will fix your issue.

**Comment by mitchellh** [comment]
(Not merged yet, just linking the two)

**Comment by mitchellh** [comment]
Fixed by #885
