### ISSUE TITLE
Missing OpsGenie Support

### ISSUE THREAD

**Issue by justinwalz** [hashicorp/terraform#9557]
Hi there,

I noticed that PagerDuty support was just implemented. It would be nice to also have support for OpsGenie. Thanks!
### Terraform Version

Terraform v0.7.7
### Expected Behavior

Support for OpsGenie
### Actual Behavior

Not yet.
### References
- WebAPI https://www.opsgenie.com/docs/dashboard/web-api
- GoSDK https://github.com/opsgenie/opsgenie-go-sdk

**Comment by tombuildsstuff** [comment]
Hey @justinwalz

I took a look into this and have just sent PR #11012 with initial support for Users and Teams :)

**Comment by justinwalz** [comment]
Awesome!
