### ISSUE TITLE
dynamodb capacity update fails at runtime with ResourceInUseException

### ISSUE THREAD

**Issue by vasili-zolotov** [hashicorp/terraform#9559]
When we run a plan change that, as part of the same change, updates capacities on a table and on table's indexes a runtime error happens while change is applied. Output below.

It appears that in order to do this reliably some of the changes need to be serialized, e.g. changes to an index and its parent table.

```
Error applying plan:

3 error(s) occurred:

* aws_dynamodb_table.access_keys_table: ResourceInUseException: Attempt to change a resource which is still in use: Index is being updated.  Table: z1-AccessKeys Index: UserId
    status code: 400, request id: TH1ICS9VR3AJGH2OP15HFVHN57VV4KQNSO5AEMVJF66Q9ASUAAJG
* aws_dynamodb_table.directors_table: ResourceInUseException: Attempt to change a resource which is still in use: Index is being updated.  Table: z1-Directors Index: NeedsProcessing
    status code: 400, request id: N85T8E1PKELRRLJPVDPLO42EDRVV4KQNSO5AEMVJF66Q9ASUAAJG
* aws_dynamodb_table.clusters_table: ResourceInUseException: Attempt to change a resource which is still in use: Index is being updated.  Table: z1-Clusters Index: NeedsProcessing
    status code: 400, request id: 7NH8MBD7RQ66V4GU8EVJTAJFPNVV4KQNSO5AEMVJF66Q9ASUAAJG
```

I will confirm in advance that this was that only one terraform change was being applied at the time. That is the error is induced by the failed command itself.

**Comment by Ninir** [comment]
Hi @vasili-zolotov 

A fix just landed into Terraform and will be released in the next version. Sorry it look this long to get back to you :)

**Comment by kvincent3** [comment]
Thanks @Ninir,

Is 1.119 the next version ?

**Comment by Ninir** [comment]
Hi @kvincent3

Not sure to get the "1.119" version :/ what does it relates too please? :)

**Comment by kvincent3** [comment]
Hi @Ninir,
I misunderstood your comment. I thought you were talking about aws dynamodb version.
Thanks
