### ISSUE TITLE
Remote-exec aws cli through winrm on windows fails

### ISSUE THREAD

**Issue by stephensmalls** [hashicorp/terraform#9562]
Hi there,

While sending an awscli command vi remote-exec to an AWS instance running windows 2012 r2 with aws cli installed give me an unrecognized aws cli error. but works flawlessly while logged into the instance interactively
### Terraform Version

Terraform v0.7.5
### Affected Resource(s)

provider "aws" {
  region = "us-east-1"
}

resource "null_resource" "deploy_adfs_connection" {
  provisioner "remote-exec"{
    inline = [
      "\u0022aws s3 rm s3://devops.windows/saml/adfs.xml\u0022",
      "\u0022aws s3 cp C:\Windows\Temp\adfs.xml s3://devops.windows/saml/adfs.xml\u0022"
    ]
    connection {
      type = "winrm"
      host = "<ipaddress>"
      user = "Administrator"
      password = "<password>"
      timeout = "30m"
    }
  }
}
### Debug Output

 Traceback (most recent call last):
   File "aws", line 27, in <module>
   File "aws", line 23, in main
   File "awscli\clidriver.pyc", line 50, in main
   File "awscli\clidriver.pyc", line 178, in main
   File "awscli\argparser.pyc", line 71, in parse_known_args
 LookupError: unknown encoding: cp65001
### Expected Behavior

on the instance I am able to run both commands without issue
### Steps to Reproduce

I am unable to provide all of my deployment code, but I will say this. It's a vanilla windows 2012 r2 installation with the latest aws cli sdk installed. I am able to make a winrm connection and successfully run powershell scripts uploaded to the instance using a remote-exec resource.
### Important Factoids

I have setup roles and profiles correctly as I am able to parse the meta-data of the instance and successfully run commands

Thanks!

**Comment by dhdanno** [comment]
I'm seeing same issue with Ansible running aws commands via WinRM. Can anyone shed any light on the root cause or a resolution for this?

**Comment by dhdanno** [comment]
I upgraded to Python/3.6.1 and the problem seems to be resolved

**Comment by anmiles** [comment]
@dhdanno Could you please provide more details? Where you upgraded Python? I did not find python on my local machine and on ec2 instance. Do AWS use built-in python and should I upgrade it somehow?
