### ISSUE TITLE
Feature Request: Resource Finder

### ISSUE THREAD

**Issue by blunney1** [hashicorp/terraform#9563]
Hi there,

It would be mighty handy to have a way to search a VPC for a resource that matches a certain configuration and return that resource's identifying information (id, name, etc).  For instance, say you want to find a security group that enables a list of inbound addresses mapped to originating IPs, and allows a list of outbound addresses, also mapped to destination addresses.  The "resource finder" would attempt to match the security groups in the VPC with the specified attributes.  

Note the attributes are not limited to those above, but any defining set of attributes that can be specified for a resource, like tags, etc.

This is somewhat like import, but the found resource is _not_ brought into the state file and put under the configuration's management.  

A "resource finder" capability would allow a configuration to share resources created by a different configuration, but not endanger the other configuration during an `apply`, `taint`, or `destroy`.
### Terraform Version

terraform 0.7.7
### Affected Resource(s)
- aws_*
### Expected Behavior

The resource finder finds existing infrastructure in a VPC that matches a specification and makes the identity of the found resource available.
### Actual Behavior

Nothing, yet.

**Comment by jennyfountain** [comment]
+2

**Comment by apparentlymart** [comment]
Hi @blunney1! Thanks for this feature request.

I think what you're asking for here is what the "data sources" feature, added in 0.7, is getting at: the ability to read data from elsewhere (including AWS) for use in a Terraform configuration.

For AWS VPCs, for example, we can retrieve VPC data for use in a configuration like this (as of Terraform 0.7.6):

```hcl
data "aws_vpc" "production" {
  tags = {
    Environment = "production"
  }
}
```

Here Terraform would look for a VPC with a tag key "Environment" whose value is  "production", and if it is found you could use it to create managed objects using resources, like this:

```
resource "aws_subnet" "usw1a" {
  vpc_id = "${data.aws_vpc.production.id}"
  cidr_block = "${cidrsubnet("${data.aws_vpc.production.cidr_block}", 4, 1)}"
  availability_zone = "us-west-1a"
}
```

This feature is still relatively new, so we don't have data sources for everything but there's already 14 data sources in the AWS provider, and specific suggestions for new ones are very welcome to help prioritize.
