### ISSUE TITLE
Google Cloud - "remote-exec" not working on centos6 images

### ISSUE THREAD

**Issue by andrelss** [hashicorp/terraform#9564]
Hello Team,

I am not able to run "remote-exec" on centos 6 imagens anylonger.

It has been working fine but is not since last friday which I had to create a new environment, it only happens with centos6 images and not with centos7, ubuntu, debian etc.

Doesn't give me any error neither warning message, it keeps just as (Still creating... (4m1s elapsed))

This is my instance creation template:

```
resource "google_compute_instance" "galaxy" {
  count = "1"
  name = "${var.environment_name}-galaxy"
  machine_type = "${var.standard2.["gce"]}"
  zone = "us-central1-f"
  tags = ["${var.environment_name}-allow-ssh-internal","${var.environment_name}-allow-aem-internal"]

  disk {
        image = "centos-6-v20160921"
        size  = "150"
        auto_delete = "true"
  }

  network_interface {
    subnetwork = "${var.subnetwork_name}"
        access_config {
            // Ephemeral IP
        }
  }

  service_account {
        scopes = ["cloud-platform"]
  }

   provisioner "file" {
        source = "shell.sh"
        destination = "/tmp/shell.sh"
        connection {
          user = "laranja"
            agent = "true" 
            timeout = "60s"
        }  
    }

   provisioner "remote-exec" {
        inline = [
            "echo = ============== Hello, here we GO ===============",
            "sudo chmod +x /tmp/shell.sh",
            "/tmp/shell.sh args"
        ]
        connection {
          user = "laranja"
            agent = "true" 
            timeout = "30s"
        }  
   } 
}
```

### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- google instances

Any clue? I really appreciate any help.

Thanks a lot.

**Comment by cblecker** [comment]
Does the file provisioner copy over correctly? Is your SSH key already installed in the agent?

You can enable Terraform debug logging by following the instructions here:
https://www.terraform.io/docs/internals/debugging.html

**Comment by andrelss** [comment]
Hello cblecker,

Thanks for your quick response, yes my SSH key is already installed in the agent and as I sad before, it works just fine with others distros.

The debug or error logging doesn't help me much! :(

**Comment by cblecker** [comment]
I just tested this and it worked as intended for me:
```hcl
/*
This is a test server definition for GCE+Terraform for GH-9564
*/

resource "google_compute_firewall" "gh-9564-firewall-externalssh" {
  name    = "gh-9564-firewall-externalssh"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["externalssh"]
}

resource "google_compute_instance" "gh-9564-instance" {
  name         = "gh-9564-instance-${count.index}"
  machine_type = "f1-micro"
  zone         = "${var.region_zone}"
  tags         = ["externalssh"]

  disk {
    image = "centos-6"
  }

  network_interface {
    network = "default"

    access_config {
      # Ephemeral
    }
  }

  provisioner "file" {
    connection {
      type    = "ssh"
      user    = "${var.user}"
      timeout = "120s"
    }

    source      = "temp.sh"
    destination = "/tmp/temp.sh"
  }

  provisioner "remote-exec" {
    connection {
      type    = "ssh"
      user    = "${var.user}"
      timeout = "120s"
    }

    inline = [
      "sudo chmod +x /tmp/temp.sh",
      "/tmp/temp.sh",
    ]
  }

  # Ensure firewall rule is provisioned before server, so that SSH doesn't fail.
  depends_on = ["google_compute_firewall.gh-9564-firewall-externalssh"]

  service_account {
    scopes = ["compute-ro"]
  }
}
```

**Comment by andrelss** [comment]
Thank you for your quick response and sorry to take so much to be back. (I was working on another demand).

I've made the changes according to your comment "depends on" and "service account scope" but the problem still.

When I run with other kind of distro such as centos 7 or debian the problem doens't comes up, really weird :(

Nobody else are facing the situation?

Thanks a lot.

**Comment by andrelss** [comment]
@cblecker  The issue was at my side, the IT guys has made some change on our firewall which were blocking my script to connect on port 22 :(

Sorry about that and thank you very much for your help.
