### ISSUE TITLE
aws_cloudformation_stack - SignatureDoesNotMatch: Signature expired

### ISSUE THREAD

**Issue by jrstarke** [hashicorp/terraform#9571]
I'm trying to spin up a new CloudFormation Stack using `aws_cloudformation_stack` from an large example template (It takes ~21 minutes to complete http://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/architecture.html).

When it does, I get the following error

```
* aws_cloudformation_stack.waf_security_automations: SignatureDoesNotMatch: Signature expired: 20161024T215820Z is now earlier than 20161024T215917Z (20161024T220417Z - 5 min.)
    status code: 403, request id: cec1f295-9a35-11e6-80c5-cf6fcfc9763b
```

This first occurred in Terraform `0.7.3`, but I upgraded to `0.7.7` and it still occurs.

The template is from the AWS WAF Security Automations, and is 
### Terraform Version
- 0.7.3 and 0.7.4
### Affected Resource(s)
- aws_cloudformation_stack

**Comment by jgartrel** [comment]
I think I am also stumbling across this bug. As best as I can see, if querying the state of N records in a route53 zone exceeds 5 minutes, then it looks like the cached signature that is used for API calls expires.

I am really surprised that anyone with large TF configs do not experience this all of the time.

```
* aws_route53_record.do_dns_node.1: SignatureDoesNotMatch: Signature expired: 20161201T170030Z is now earlier than 20161201T170230Z (20161201T170730Z - 5 min.)
	status code: 403, request id: a470a4ac-b7e8-11e6-8fc7-2b7a7fe7fb76
exit status 1
```

**Comment by apatrida** [comment]
There is no setting to change the 5 min timeout?
