### ISSUE TITLE
Change to vpc_zone_identifier attribute in aws_autoscaling_group not reflecting properly

### ISSUE THREAD

**Issue by maxc0d3r** [hashicorp/terraform#9579]
I am running terraform v0.7.7.

I've a aws_autoscaling_group resource with vpc_zone_identifier who's value I changed and upon running terraform apply I could see the change happen. However my old instances with old subnet-ids are still up and running. Shouldn't the already created instances be destroyed and new instances created in new subnets after change to vpc_zone_identifier?

**Comment by stack72** [comment]
Hi @maxc0d3r 

Thanks for getting in touch about this. I was able to run an experiment using the following AWS Config:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "main" {
  vpc_id            = "${aws_vpc.default.id}"
  cidr_block        = "10.0.1.0/24"
  availability_zone = "us-west-2a"
}

resource "aws_subnet" "alt" {
  vpc_id            = "${aws_vpc.default.id}"
  cidr_block        = "10.0.2.0/24"
  availability_zone = "us-west-2b"
}

resource "aws_launch_configuration" "foobar" {
  image_id          = "ami-1817d178"
  instance_type     = "t2.micro"
  enable_monitoring = false
}

resource "aws_autoscaling_group" "bar" {
  vpc_zone_identifier = [
    "${aws_subnet.main.id}",
  ]

  max_size                  = 2
  min_size                  = 1
  health_check_grace_period = 300
  health_check_type         = "ELB"
  desired_capacity          = 1
  force_delete              = true
  termination_policies      = ["OldestInstance"]
  launch_configuration      = "${aws_launch_configuration.foobar.name}"

}

resource "aws_security_group" "tf_test_self" {
  name        = "tf_test_alb_asg"
  description = "tf_test_alb_asg"
  vpc_id      = "${aws_vpc.default.id}"

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

When I ran this config, the ASG was pointing to us-west-2a and will have created a machine there:

<img width="976" alt="screen shot 2016-11-03 at 10 43 33" src="https://cloud.githubusercontent.com/assets/227823/19963094/d2794d66-a1b2-11e6-9b16-58f61e0eb58a.png">

<img width="863" alt="screen shot 2016-11-03 at 10 43 48" src="https://cloud.githubusercontent.com/assets/227823/19963098/d7503c0a-a1b2-11e6-8ee8-9b9165208f33.png">

I then changed the ASG config to look as follows:

```
resource "aws_autoscaling_group" "bar" {
  vpc_zone_identifier = [
    "${aws_subnet.main.id}",
  ]

  max_size                  = 2
  min_size                  = 1
  health_check_grace_period = 300
  health_check_type         = "ELB"
  desired_capacity          = 1
  force_delete              = true
  termination_policies      = ["OldestInstance"]
  launch_configuration      = "${aws_launch_configuration.foobar.name}"
}
```

Notice that I changed it from 1 subnet to another - this means that I swapped it from us-west-2a to us-west-2b:

<img width="927" alt="screen shot 2016-11-03 at 10 44 32" src="https://cloud.githubusercontent.com/assets/227823/19963135/fd1b3fe8-a1b2-11e6-8a30-0921549fc3bc.png">

My ASG immediately kicked into action launching an instance in the new subnet:

<img width="871" alt="screen shot 2016-11-03 at 10 44 46" src="https://cloud.githubusercontent.com/assets/227823/19963160/114bf138-a1b3-11e6-872f-1dbe8fedc62e.png">

It then initiated the termination of the old instance:

<img width="869" alt="screen shot 2016-11-03 at 10 46 06" src="https://cloud.githubusercontent.com/assets/227823/19963169/1cb954d4-a1b3-11e6-9e55-eddf5c8d5943.png">

I am using Terraform 0.7.8

Please let me know if this is still an issue for you

Paul
