### ISSUE TITLE
Security group does not belong to VPC

### ISSUE THREAD

**Issue by JulianGindi** [hashicorp/terraform#958]
I keep running into an issue when creating a elastic load balancer using Terraform. The security group I setup to be associated with the ELB is pointing to the correct VPC in the console, but when I run terraform apply I get the error "InvalidConfigurationRequest: Security group 'foo' does not belong to VPC 'bar'". Not sure how to wrap my head around this.

**Comment by bitglue** [comment]
Are you giving to the ELB the security group names, or the security group IDs? I'm attaching security groups in a VPC to an ELB with Terraform without any issue. It would help to see the relevant parts of your configuration.

**Comment by JulianGindi** [comment]
I'm using the security group ids. Here is a snippet...

```
 resource "aws_elb" "py_elb" {
     name = "foo"
     availability_zones = ["${aws_instance.py.availability_zone}"]

     listener {
         instance_port = 80
         instance_protocol = "http"
         lb_port = 80
         lb_protocol = "http"
     }

     instances = ["${aws_instance.py.id}"]
     security_groups = ["${aws_security_group.public_elb_security_group.id}",]
 }

```

**Comment by bitglue** [comment]
Not sure if it's related, but you might try associating some subnets to the ELB. [The API docs][1] aren't too clear on this point, but the web console won't let you make an ELB in a VPC without associating subnets. And although the API docs *say* it's required to specify availability zones, in their example of "Create a TCP Load Balancer in EC2-VPC", there are no availability zones specified (though there are subnets).

Here's my configuration, which is working with HEAD:

```
resource "aws_security_group" "elb" {
    name = "www-elb"
    description = "HTTP and HTTPS from anywhere"
    vpc_id = "${var.vpc_id}"

    ingress {
        from_port = "80"
        to_port = "80"
        cidr_blocks = ["0.0.0.0/0"]
        protocol = "tcp"
    }

    ingress {
        from_port = "443"
        to_port = "443"
        cidr_blocks = ["0.0.0.0/0"]
        protocol = "tcp"
    }
}

resource "aws_elb" "www" {
    name = "www-placelocal"
    subnets = ["subnet-xxx", "subnet-xxx", "subnet-xxx"]
    security_groups = ["${aws_security_group.elb.id}"]

    listener {
        instance_port = "${var.www_http_port}"
        instance_protocol = "http"
        lb_port = 80
        lb_protocol = "http"
    }

    listener {
        instance_port = "${var.www_https_port}"
        instance_protocol = "tcp"
        lb_port = 443
        lb_protocol = "tcp"
    }
}
```

  [1]: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancer.html

**Comment by JulianGindi** [comment]
Alright, cool. I'll give this a shot. When specifying the subnets do I use their names or ids?

**Comment by bitglue** [comment]
I use the IDs. Probably [the docs](https://terraform.io/docs/providers/aws/r/elb.html) should be more explicit.

**Comment by JulianGindi** [comment]
Hmm, I ran into the following errors when I had multiple IDs specified:

`Error creating ELB: ValidationError: Only one of SubnetIds or AvailabilityZones may be specified`

I updated the elb block to look like such:

```
...
subnets = ["${aws_subnet.py_subnet_c.id}", "${aws_subnet.py_subnet_b.id}"]
...
```

**Comment by bitglue** [comment]
Yes, I don't have any availability zones in my configuration. My guess is (though I can't find the Amazon documentation that says this) that if you specify subnets, you get a VPC ELB. If you specify availability zones, you get an EC2-classic ELB. If you specify both, you get an error.

**Comment by JulianGindi** [comment]
Hmm, alright. Well that brings me back to square-one since I want an "EC2-level" ELB (specifying two availability zones and two instances)

**Comment by bitglue** [comment]
I don't think you can do that with AWS. Your stuff (be it instances, security groups, ELBs, or whatever) can exist in a VPC, or in the networking scheme that existed before VPC was introduced, called EC2-classic. If your instances are in a VPC, then the must be assigned security groups from that VPC, and your load balancer must be associated to subnets from that VPC. I don't know of any instances where AWS lets you mix EC2-classic and VPC objects.

**Comment by JulianGindi** [comment]
Gotcha, that makes sense. So I will specify the subnets (as opposed to the availability zones). Really appreciate the help.

**Comment by mitchellh** [comment]
Looks like this was just an AWS issue. :)

**Comment by gswallow** [comment]
AWS's documentation on this is really confusing.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-scheme

From what I understand, when you create an internet-facing ELB, you use AZs.  When you create an internal ELB, you use subnets.

I have yet to get an ELB to work, except I just started today, and I'm using a different tool than Terraform.

**Comment by yashwanthkalva** [comment]
This issue does occur in spite of passing AZz info using "data" source. 
I am using one public subnet, an internet facing ELB to balance 2 EC2 instances in a private subnet. 

As a workaround to issue, I created 2 public subnets and passed subnet ids to ELB resource instead of AZs info.  This issue does not seem to be resolved.
