### ISSUE TITLE
Unable to run destroy when one provider depends on another

### ISSUE THREAD

**Issue by wjam** [hashicorp/terraform#9585]
Terraform complains of a cycle when trying to run `destroy` when one provider depends on data supplied by another provider.
### Terraform Version

```
$ terraform -v
Terraform v0.7.7
```
### Affected Resource(s)
- `provider`
- Possibly `consul_keys`, although I suspect it's more an issue with how the dependency graph is calculated for `destroy`
### Terraform Configuration Files

Demonstration of the issue can be found at https://github.com/wjam/terraform-destroy-bug
### Debug Output

Debug output can be created by running the demonstration in the repository linked above
### Expected Behavior

Terraform should be able to `destroy` a state file where the configuration of one provider depends on another.
### Actual Behavior

Terraform refuses to destroy the state as it believes there is a cyclic dependency
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Checkout https://github.com/wjam/terraform-destroy-bug
1. Start up Consul inside docker (`docker-compose up`)
1. Seed consul with the relevant information (`./consul-setup.sh`)
1. Apply terraform (`terraform apply -var='consul_address=localhost:8500'`)
1. Attempt to run destroy (`terraform destroy -var='consul_address=localhost:8500'`)
### Important Factoids

GitHub repository contains a minimal test case of the issue.

**Comment by mitchellh** [comment]
This is fixed and works properly with the new destroy graphs. You can try it yourself in 0.7.8+ with:

```
terraform destroy -Xnew-destroy -Xnew-apply
```

Both have to be specified due to an unrelated issue... but that should get you going!
