### ISSUE TITLE
allow aws_route53_record to use zone_name instead of zone_id

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform#9590]
The AWS interface seems to require only one of either the zone NAME or the zone ID to create a record ([see here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-hostedzonename))

It would be nice if the AWS resource would have the same choice. I imagine something like described below under "Terraform configuration files"
### Terraform Version

up to 0.7.7
### Affected Resource(s)
- aws_route53_record
### Terraform Configuration Files

``` hcl
# this works
resource "aws_route53_record" "jump" {
  name    = "jump.my-domain.com"
  zone_id = "ABCDEF123"
  type    = "CNAME"
  ttl     = "600"
  records = ["${aws_eip.my_eip.public_ip}"]
}

# this would be nice
resource "aws_route53_record" "jump" {
  name      = "jump.my-domain.com"
  zone_name = "my-domain.com"
  type      = "CNAME"
  ttl       = "600"
  records   = ["${aws_eip.my_eip.public_ip}"]
}
```

**Comment by kwilczynski** [comment]
@flypenguin hi there!

This is a good idea, but a bit tricky to implement. It would require us to list all the hosted zones and then filter out these matching the particular name which would possibly return both the public and private zone IDs should the hosted zone have the same name (which is valid in Route53; and you can have multiple private hosted zones with the same domain name). In other words, it might fail should multiple hosted zones have the same name. Might not be the most ideal behaviour.

I would suggest a data source which allows one to query for a Route53 resources, plus apply filters like e.g. domain name, type (public or private), has a VPC ID assigned, etc. It would then return details about a matching hosted zone where one of them would be the hosted zone ID that could be passed down to the `aws_route53_record` resource.

Would that be something of interest to you?

**Comment by flypenguin** [comment]
sure, basically I want to be able to just use the zone name to set things up. 

but I think AWS *does* all that for you, because the API allows for you to use just the zone name, not the zone ID. (at least that's how I understand the descriptions)

**Comment by kwilczynski** [comment]
@flypenguin hi there again. I had a look at http://docs.aws.amazon.com/sdk-for-go/api/service/route53/ and I could not find a way to pass the zone name only.

CloudFormation, which is what you liked to, most certainly implements this in a bespoke way what is specific to its internal workings, the API (which is what we use via an official SDK), does not have such functionality, unfortunately.

**Comment by flypenguin** [comment]
oh, I thought CF would just pass through to the API.
Anyway, the data source would be super fine with me!
