### ISSUE TITLE
Create an output for aws_alb_target_group for the arn suffix

### ISSUE THREAD

**Issue by adhodgson1** [hashicorp/terraform#9593]
Hi,

It is possible to use the arn_suffix output on the aws_alb resource for cloudwatch alarms.  In some of the alarms, I need to use the target group as well, and for this there is no output for the arn_suffix.

Could this be added?

Thanks,
Andrew.
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- aws_alb_target_group
- aws_cloudwatch_metric_alarm (requires the arn suffix of the target group).

**Comment by stack72** [comment]
Hi @adhodgson1 

Thanks for getting in touch here - do you mean the ARN of the alb_target_group e.g. `arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/my-targets/73e2d6bc24d8a067` 

P.

**Comment by stack72** [comment]
ping @adhodgson1 :)

**Comment by bradleythughes** [comment]
#8833 added `arn_suffix` to `aws_alb`. @adhodgson1 is asking for the same to be added to `aws_alb_target_group` to make it easier to create alarms for e.g. the HealthyHostCount.

**Comment by stack72** [comment]
got it! Adding this now :)
