### ISSUE TITLE
aws_elasticache_replication_group is broken for Redis in cluster mode

### ISSUE THREAD

**Issue by dario-simonetti** [hashicorp/terraform#9596]
The `aws_elasticache_replication_group` resource seems to be broken as terraform panics when running `apply` or `import`.

### Terraform Version
0.7.5, 0.7.7 and 0.7.8-dev

### Affected Resource(s)
- `aws_elasticache_replication_group`

### Terraform Configuration Files
```hcl
resource "aws_elasticache_replication_group" "test" {
  replication_group_id = "test"
  replication_group_description = "Replication group for test"
  engine_version = "3.2.4"
  maintenance_window = "thu:03:00-thu:04:00"
  node_type = "cache.t2.micro"
  number_cache_clusters = "2"
  parameter_group_name = "default.redis3.2.cluster.on"
  automatic_failover_enabled = true
  port = 6379

  subnet_group_name = "my-subnet-group-name"
  security_group_ids = ["sg-7e7eb519"]

  snapshot_window = "02:00-03:00"
  snapshot_retention_limit = 7

  apply_immediately = true
  availability_zones = ["eu-west-1a", "eu-west-1b"]
}
```

### Debug Output
https://gist.github.com/dario-simonetti/7b39f42a7f37643ef8b3d1de52d6c843

### Panic Output
https://gist.github.com/dario-simonetti/7503f38754e30b4751902bd9462691e7

### Expected Behavior
It should create an Amazon ElastiCache cluster and add the resource to the `terraform.tfstate` file.

### Actual Behavior
It creates the Amazon ElastiCache cluster but it panics just after creation and the resource is never added to the `terraform.tfstate` file.

### Steps to Reproduce
1. `terraform apply`

Same happens with `terraform import aws_elasticache_replication_group.test test` when the resource already exists on AWS.

**Comment by stack72** [comment]
Closed via #9601
