### ISSUE TITLE
Request: Empty variable Prompt, Provide user context.

### ISSUE THREAD

**Issue by zdxn** [hashicorp/terraform#9598]
### Terraform Version

v0.7.7
### Affected Resource(s)

Terraform Core Functionality
### Terraform Configuration Files

```
#Example for variable prompt context

variable "aws_region" {} :prompt("Please select a region from ${var.regions}"
```
### Expected Behavior

When running terraform plan, or apply without supply the variables. I should be prompted for input with context to the actual prompt.

Prompt value can be expressed via :prompt(" "), Allows interpolation of variables to provide easier list access.
### Actual Behavior

Currently you are only prompted for a input, there is very little context. This would be an added feature.
### References

https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/command/ui_input.go#L39-L127

I'm assume the code should be in the above source. I'm not a go developer nor am i going to attempt to be to implement this as I will just break stuff.

**Comment by mildwonkey** [comment]
Thanks for submitting this feature request!  In current versions of terraform you can use the variable's `description` field to provide additional information in the prompt (note the second `$` in the string):

```hcl
variable "aws_region" {
  description = "Please select a region from $${var.regions}"
}
```
# terraform plan
var.aws_region
  Please select a region from ${var.regions}

  Enter a value:
```
