### ISSUE TITLE
Terraform apply failing as a result of commented variables in template_files being parsed

### ISSUE THREAD

**Issue by bmurtagh** [hashicorp/terraform#9599]
### Terraform Version

Terraform v0.7.3
### Affected Resource(s)
- data.template_file (only tested with template_file Data Sources)
### Debug Output

`data.template_file.bastion-bootstrap: failed to render : 23:42: unknown variable accessed: bastion_eip_allocation_id`
### Expected Behavior

Nothing. The line was commented out (#) in the template_file declaration as well as the bootstrap file:
`# bastion_eip_allocation_id   = "${aws_eip.bastion-eip.id}"`
`# export BASTION_EIP_ALLOCATION_ID="${bastion_eip_allocation_id}" &&`
### Actual Behavior

The `terraform apply` run failed with the above error.
### Steps to Reproduce
- Generate a template_file data source like so:

```
# Bastion Server Bootstrap & EC2 Instance
data "template_file" "colleague-bastion-bootstrap" {
  template   = "${file("user_data/bastion-bootstrap.sh")}"
  # depends_on = ["aws_eip.bastion-eip"]

  vars {
    environment                 = "${var.environment}"
    aws_key_pair                = "${var.aws_key_pair}"
    time_zone                   = "${var.time_zone}"
    s3_bucket                   = "${var.s3_bucket}"
    aws_region                  = "${var.aws_region}"
    user_data_s3_directory      = "${var.user_data_s3_directory}"
    bastion_bootstrap_filename  = "${var.bastion_bootstrap_filename}"
    envname_prefix              = "${var.envname_prefix}"
    aws_key_pair_s3_url         = "${var.aws_key_pair_s3_url}"
    # bastion_eip_allocation_id   = "${aws_eip.bastion-eip.id}"
  }
}
```
- Create the following `user_data/bastion-bootstrap.sh`:

```
#!/bin/bash
echo "in bastion-bootstrap.sh"
# export BASTION_EIP_ALLOCATION_ID="${bastion_eip_allocation_id}" &&
echo "end bastion-bootstrap.sh"
```
- Kick off a `terraform apply`

**Comment by bmurtagh** [comment]
To help clarify my user expectation:

I'm hoping that the variable interpolation would be ignored when a line in a `template_file` line begins with `#` or `/*`

Example: if ${..} is in a line that begins with # or /*, when the rendering process is executed, treat ${..} as if it were like $${..}

**Comment by clstokes** [comment]
Hey @bmurtagh, I think you have to use Go template's specific comment syntax - e.g. `{{/* a comment */}}`. Otherwise, it's unknown to the interpreter if you meant to comment the line or have a line prefixed with a hash.

https://golang.org/pkg/text/template/

**Comment by mitchellh** [comment]
@clstokes is almost right. Our templates aren't even Go syntax so that's not quite right either.

There is no way to comment a line in a template. You can _escape_ interpolations with a double `$` but there is no way to outright ignore lines. This isn't something we're looking to support with this language. We may support other template engines in the future.
