### ISSUE TITLE
retry_duration for redshift_configuration

### ISSUE THREAD

**Issue by LoganArnett** [hashicorp/terraform#9606]
I recently started working with Terraform and I am trying to setup an `aws_kinesis_firehose_delivery_stream` with a [`redshift_configuration`](https://github.com/hashicorp/terraform/blob/791a02e6e456df7e36f7c24813850519df947e91/builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream.go#L172-L216) and realized that a `retry_duration` option is not available. There is one for the [`elasticsearch_configuration`](https://github.com/hashicorp/terraform/blob/791a02e6e456df7e36f7c24813850519df947e91/builtin/providers/aws/resource_aws_kinesis_firehose_delivery_stream.go#L276) so I was wondering if this was a feature that was in the works or in scope?

**Comment by catsby** [comment]
Fixed with #10113

**Comment by LoganArnett** [comment]
Awesome thanks 👍
