### ISSUE TITLE
terraform plan does not detect missing `ttl` attribute for aws_route53_records

### ISSUE THREAD

**Issue by mrwacky42** [hashicorp/terraform#9610]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
### Terraform Version

0.7.5 and 0.7.7
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_route_53_record
### Terraform Configuration Files

``` hcl
resource "aws_route53_record" "example" {
    name = "example"
    type = "CNAME"
    zone_id = "${var.example_zone_id}"
    records = ["hashicorp.com"]
}
```
### Debug Output

N/A
### Panic Output

N/A
### Expected Behavior

TF should have bellyached that `TTL` is required 
### Actual Behavior

Terraform shows this plan:

```
+ aws_route53_record.example
    fqdn:               "<computed>"
    name:               "example"
    records.#:          "1"
    records.4210768119: "hashicorp.com"
    type:               "CNAME"
    zone_id:            "<redacted>"
```

But trying to apply yields the problem:

```
Error applying plan:

1 error(s) occurred:

* aws_route53_record.example: provider.aws: aws_route53_record: example: "ttl": required field is not set
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply saved-plan` (where plan has a `aws_route53_resource` that has no TTL argument)
### Important Factoids

N/A
### References

N/A

**Comment by mrwacky42** [comment]
Now I'm confused, I went to submit a patch, and found the code I probably would have added was added by https://github.com/hashicorp/terraform/commit/c346da69 .

What is the different path `terraform plan` takes versus `apply`, I wonder..

**Comment by stack72** [comment]
Hi @mrwacky42 

That patch was added for Terraform 0.7.7 - you are on 0.7.5 

Paul

**Comment by mrwacky42** [comment]
@stack72  - This patch was merged to master almost 18 months ago.
And I just tested 0.7.7 and still the same behavior. The patch I mentioned fires the error at `apply` time, but not when I `plan`.

Please reopen.

**Comment by Ninir** [comment]
@stack72 Do you think that having a `ValidateAgainstFunc` function would help? There are many cases where you want to validate at read & not apply. Hope something like this does not exist, if so sorry... 😓
