### ISSUE TITLE
aws_emr_cluster: Please add ServiceAccessSecurityGroup to ec2_attributes

### ISSUE THREAD

**Issue by adamjohnson01** [hashicorp/terraform#9611]
Hi there,

Would it be possible to add the ability to add managed service security group to the ec2_attributes? This is required if you use managed security groups when creating the EMR cluster in a private subnet.

### Terraform Version
0.7.7

### Affected Resource(s)
- aws_emr_cluster

**Comment by stack72** [comment]
Hi @adamjohnson01 

closing as a duplicate of #9518 - thanks for the request here

Paul
