### ISSUE TITLE
terraform crash (v 0.7.7)

### ISSUE THREAD

**Issue by rblumen-desk** [hashicorp/terraform#9615]
[crash.log.txt](https://github.com/hashicorp/terraform/files/552145/crash.log.txt)

**Comment by kwilczynski** [comment]
@rblumen-desk hi there! Thank you for reporting an issue and sorry that you are having troubles!

I am a little bit confused to how can we help? As far as I know, we do not support Dataloop as official built-in provider which ships as part of Terraform, and your crash shows some issues that might be related to it. Having no code to look at, no Terraform template to check and actually almost nothing to work against to determine to root cause, I am not sure what can we do to help?

**Comment by kwilczynski** [comment]
The relevant part of the crash log:

```
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: panic: Unknown type for input: 6
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: goroutine 51 [running]:
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: panic(0x50a3a0, 0xc4201ae1f0)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /usr/local/go/src/runtime/panic.go:500 +0x1a1
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: github.com/hashicorp/terraform/helper/schema.schemaMap.Input(0xc4201a86c0, 0x867480, 0xc4201b4070, 0xc42024ca80, 0x554320, 0xc420259a01, 0xc4201b4070)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /Users/rblumen/Devel/golang-work/src/github.com/hashicorp/terraform/helper/schema/schema.go:488 +0x420
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: github.com/hashicorp/terraform/helper/schema.(*Provider).Input(0xc4201a8660, 0x867480, 0xc4201b4070, 0xc42024ca80, 0xc42024a4e0, 0x0, 0x0)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /Users/rblumen/Devel/golang-work/src/github.com/hashicorp/terraform/helper/schema/provider.go:111 +0x4c
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Input(0xc420220640, 0xc42023e460, 0xc42023eb00, 0x0, 0x0)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /Users/rblumen/Devel/golang-work/src/github.com/hashicorp/terraform/plugin/resource_provider.go:408 +0x1cc
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: reflect.Value.call(0xc42023c660, 0xc42025c088, 0x13, 0x5d31b6, 0x4, 0xc420259ee0, 0x3, 0x3, 0x0, 0x0, ...)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /usr/local/go/src/reflect/value.go:434 +0x5c8
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: reflect.Value.Call(0xc42023c660, 0xc42025c088, 0x13, 0xc420259ee0, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /usr/local/go/src/reflect/value.go:302 +0xa4
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: net/rpc.(*service).call(0xc420236200, 0xc4202361c0, 0xc42023e190, 0xc420252980, 0xc420242220, 0x4f0500, 0xc42023e460, 0x16, 0x4f0540, 0xc42023eb00, ...)
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /usr/local/go/src/net/rpc/server.go:383 +0x148
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop: created by net/rpc.(*Server).ServeCodec
2016/10/25 18:35:44 [DEBUG] plugin: terraform-provider-dataloop:        /usr/local/go/src/net/rpc/server.go:477 +0x421
```

**Comment by stack72** [comment]
Hi @rblumen-desk 

Thanks for opening the crash report here. As @kwilczynski points out above, this isn't a provider that is part of Terraform. Therefore, we suggest that you report the crash to that provider as a first port of call. 

Hope this helps

Paul

**Comment by rblumen-desk** [comment]
I reported the error because the output said that this error type is always a terraform bug.  I believe that this crash happened because a required var of type SchemaMap was not provided, so the schema/helper went into the Input() path, which does not handle the SchemaMap type.   I made the following code change to schema.go which fixed this issue:

```
                @@ -480,7 +482,7 @@ func (m schemaMap) Input(
                switch v.Type {
-               case TypeBool, TypeInt, TypeFloat, TypeSet:
+               case TypeBool, TypeInt, TypeFloat, TypeSet, TypeMap:

```

**Comment by rblumen-desk** [comment]
I don't think that this is a provider issue as such, it is a code path that goes through the schema/helper framework that is an unhandled case, causing a crash in schema.go

**Comment by kwilczynski** [comment]
@rblumen-desk hi there again! Thank you for getting back to use with more details.

Would you have a small code snippet handy to showcase how this is triggered? Otherwise we still cannot really tell whether what happened is valid or not. There might be a reason why `TypeMap` wasn't there in the first place, etc.

**Comment by rblumen-desk** [comment]
The provider def contains a field like this and the .tf file did not contain this field.  Terraform prompts for fields that are required but not in .tf. 

`	dataloopSchema := schema.Provider{
		Schema: map[string]*schema.Schema{
			"vars": &schema.Schema{
				Type:        schema.TypeMap,
				Required:  true,
				Default: StringMap{},
				Description: "any TF vars needed by dataloop source templates during compiler expansion",
			},
`
