### ISSUE TITLE
Feature Request: aws_route_table data source

### ISSUE THREAD

**Issue by matschaffer** [hashicorp/terraform#9619]
The new `aws_vpc` & `aws_subnet` data sources are great!

But to build a template which peers VPCs (and actually permits traffic flow), we need the routing table ID of the involved VPCs. If one of the VPCs is not covered by the set of TF templates you're working in, the best I think you can do is hard code the value as a variable or module output.

Seems like a `aws_route_table` data source similar to `aws_subnet` would do the trick to make the association very smooth.
### Terraform Version

terraform 0.7.7
### Affected Resource(s)

aws_route_table
### Terraform Configuration Files

``` hcl
data "aws_vpc" "common" {
  filter {
    name = "tag:Name"
    values = ["common"]
  }
}

data "aws_route_table" "common" {
  vpc_id = "${data.aws_vpc.common.id}"
}

data "aws_vpc" "vpn" {
  filter {
    name = "tag:Name"
    values = ["vpn"]
  }
}

data "aws_route_table" "vpn" {
  vpc_id = "${data.aws_vpc.vpn.id}"
}

resource "aws_vpc_peering_connection" "peer_vpn_common" {
  vpc_id = "${data.aws_vpc.vpn.id}"
  peer_vpc_id = "${data.aws_vpc.common.id}"
  auto_accept = true
  tags {
    Name = "vpn_common"
  }
}

resource "aws_route" "vpn_common" {
  route_table_id = "${data.aws_route_table.vpn.id}"
  destination_cidr_block = "${data.aws_vpc.common.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peer_vpn_common.id}"
}

resource "aws_route" "common_vpn" {
  route_table_id = "${data.aws_route_table.common.id}"
  destination_cidr_block = "${data.aws_vpc.vpn.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peer_vpn_common.id}"
}

```
### Expected Behavior

A terraform-managed peering relationship, even if the VPCs aren't both covered by the same set of TF templates.
### Actual Behavior

Nothing, yet.

**Comment by w-p** [comment]
Similar use case.
After creating a management VPN, it is necessary to update the route tables associated with each subnet.

```
variable "remote_cidr" {}
variable "local_cidrs" {}
variable "vpn_gw_id" {}

data "aws_subnet" "subnets" {
    cidr_block = "${element(var.local_cidrs, count.index)}"
    count = "${length(var.local_cidrs)}"
}

/* need this guy */
data "aws_route_table" "tables" {
    subnet_id = "${element(data.aws_subnet.subnets.*.id, count.index)}"
    count = "${length(var.local_cidrs)}"
}

resource "aws_route" "route_mod" {
    gateway_id = "${var.vpn_gw_id}"
    destination_cidr_block = "${var.remote_cidr}"
    route_table_id = "${element(data.aws_route_table.tables.*.id, count.index)}"
    count = "${length(var.local_cidrs)}"
}
```

**Comment by matschaffer** [comment]
Looks like 08b7f672277e326f4821b28c045703bd6b518570 covers this.

Kinda confusing that gh shows "May 14" with a v0.8.2 tag that I'm pretty sure wasn't released but, uh... LGTM! 😛
