### ISSUE TITLE
aws_eip.public_ip inside of aws_instance provisioner

### ISSUE THREAD

**Issue by ctro** [hashicorp/terraform#962]
`aws_eip` depends on an `aws_instance`.
My aws_instance wants to use its public_ip (elastic ip) as part of the provisioning process, maybe to write some configs.

Using `${aws_instance.foo.public_ip}` inside of a provisioner on foo does not return the EIP, but rather the default, interim public ip.

`${aws_eip.public_ip}` inside of a provisioner on foo does not work b/c of circular dependency.

Given this, I'm not sure if it's possible to reference an EIP.public_ip address inside of a provisioner on an aws_instance that is attached to that EIP.

Are there current workarounds or future plans to support this kind of thing?

**Comment by ctro** [comment]
I found a workaround mentioned in #557

Defining a `connection`, and `provisioner` block with `host` set to `${aws_eip.foo.public_ip}` handles this situation.   I think grouping "Public IP provisioning steps" with the aws_eip makes sense.

**Comment by hfuops** [comment]
I ran into the same issue  a week ago and googled everywhere. Fortunately I figured out the solution.
The reason has been explained on the #557 already.
please see below
 `resource "aws_eip" "demo" {
  instance = "${aws_instance.TS-demo.id}"
  depends_on = ["aws_instance.TS-demo"]
  vpc      = true
}

resource "aws_instance" "TS-demo" {
  ami                    = "${lookup(var.aws_opsman_ami,var.region)}"
  instance_type          = "m3.medium"
  key_name               = "${var.key_name}"
  subnet_id              = "${aws_subnet.public.id}"
  vpc_security_group_ids = ["${aws_security_group.all_pass.id}"]

  tags {
    Name = "demo"
  }

  provisioner "local-exec" {
    command = "echo ${aws_instance.TS-demo.private_ip} > private_ips"
  }

}
resource "null_resource" "preparation" {
    triggers {
        instance = "${aws_instance.TS-demo.id}"
    }
  connection {
    host        ="${aws_eip.demo.public_ip}"   # don't forget  this option.
    user        = "ubuntu"
    timeout     = "30s"
    private_key = "${file("./skyfree.pem")}"
    agent = false
  }

  provisioner "file" {
    source      = "./tfvars"
    destination = "/tmp/"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo apt-get -y update",
    ]
  }

}`
