### ISSUE TITLE
new data source "aws_ebs_volume"

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform#9620]
For the management of volume attachments to hosts a new data source would help me greatly. My idea is something like an `aws_ebs_volume` with which I could select one or many volumes by tags, e.g. like this:

```
data "aws_ebs_volume" "confluence" {
  single = true  # fail if more than one found

  filter {
    Name = "app-confluence"
  }
}
```

A thing that would also be useful maybe is this:

```
data "aws_ebs_volume" "confluence" {
  single = true     # fail if more than one found
  create = true     # create if not there

  creation_info {
    # basically same information as for aws_ebs_volume
    size = 20

    tags {
      Name = "app-confluence"
    }
  }

  filter {
    Name = "app-confluence"
  }
}
```
### Rationale

This creates a way for selecting a volume based on (for example) tags, so the volume can be used in an automated way, but **can never be deleted** automatically by accident (if you remove the definition from a *.tf file for example).

The auto-create case is just a convenience which saves a manual step, albeit one I would find highly useful. 

The reason behind is that I have stateful applications which are deployed to hosts. My hosts are ephemeral though, and can come and go all the time. I also re-distribute applications across hosts pretty often because our infrastructure is not final yet. So the data of those applications resides on external EBS volumes, which are _highly_ sensitive and should _never_ be deleted. Selecting those data volumes is right now a manual process, although they are heavily tagged.

Managing them with terraform I would like to maybe not do the classical way, because if I accidently delete them from terraform they will be gone in the cloud as well, and we will have data loss. The way with the auto-create would be perfect, but the data source itself would already help greatly.
### Terraform Version

0.7.7 +
### Affected Resource(s)

new resource
### Terraform Configuration Files

see example above

**Comment by stack72** [comment]
The skeleton of this functionality has been created in #9753
