### ISSUE TITLE
EMR Cluster - core_instance_count doesn't actually refer to core instances

### ISSUE THREAD

**Issue by ddcprg** [hashicorp/terraform#9623]
The docs read:

_core_instance_count - (Optional) number of Amazon EC2 instances used to execute the job flow. Default 0_

However, this works as documented in the [CLI docs](https://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html): _EMR will use one node as the cluster's master node and use the remainder of the nodes as core nodes_

So _core_instance_count = 1_ means 1 master node with no core nodes.

Since this can be confusing can either rename the variable or change the logic to honor the variable name?

I'll be glad to contribute the code.

**Comment by ddcprg** [comment]
I've opened a PR for this change: https://github.com/hashicorp/terraform/pull/9683

**Comment by ddcprg** [comment]
I've also opened this PR: https://github.com/hashicorp/terraform/pull/10529

**Comment by stack72** [comment]
Closed via #10529
