### ISSUE TITLE
Confusion on the KMS key id

### ISSUE THREAD

**Issue by n-my** [hashicorp/terraform#9626]
Terraform version : 0.7.7

I am using an Redshift cluster encrypted with a KMS key.

The creation is working well but every `terraform plan/apply` would recreate the cluster. This is because of a confusion on what is the KMS key id.

What is stored in the terraform.tfstate :

```
kms_key_id = arn:aws:kms:eu-west-1:xxxxxxxxxxxx:key/ea0e8cbb-b968-4b2a-a534-ce66754a105b
```

What is computed by Terraform

```
kms_key_id = ea0e8cbb-b968-4b2a-a534-ce66754a105b
```

Thus a `terraform plan` outputs :

```
kms_key_id: "arn:aws:kms:eu-west-1:xxxxxxxxxxxx:key/ea0e8cbb-b968-4b2a-a534-ce66754a105b" => "ea0e8cbb-b968-4b2a-a534-ce66754a105b" (forces new resource)
```

If needed you can find my Terraform template [here](https://gist.github.com/n-my/a0f9f6573cfa7d7874f2d4e7600757d8)

This is related to [this issue](https://github.com/hashicorp/terraform/issues/8259) but I created a new one because in my case I don't use an alias for the key.

**Comment by Ninir** [comment]
Related to https://github.com/hashicorp/terraform/pull/7842

It could be interesting to validate the kms_key_id format so that we ensure it is an ARN. What do you think?

**Comment by n-my** [comment]
Good catch @Ninir ! I was indeed providing the key id instead of the the key arn.

**Comment by n-my** [comment]
I'm closing it since this in not a bug.
