### ISSUE TITLE
Diffs didn't match during apply

### ISSUE THREAD

**Issue by blunney1** [hashicorp/terraform#9630]
Hi there,

My config blows up trying to create an ELB.  The message in the [gist](https://gist.github.com/blunney1/886d7704e86e2ef696079c519a81e244) below states there is a mismatch:

`Mismatch reason: attribute mismatch: instances.3157636498`

It further states this is a bug in Terraform and yields a dump for a bug report.

Bug report dutifully reported.
### Terraform Version

Terraform Version: 0.7.3
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_elb
### Terraform Configuration Files

``` hcl
resource "aws_elb" "pgbouncer_elb" {
  name     = "pgbouncer-elb"
  subnets  = ["${split(",", var.private_subnets)}"]
  internal = true

  # The same availability zone as our instances
  listener {
    instance_port     = 5499
    instance_protocol = "tcp"
    lb_port           = 5499
    lb_protocol       = "tcp"
  }

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    target              = "TCP:5499"
    interval            = 30
  }

  security_groups             = ["${var.ssh_security_group}", "${aws_security_group.pg_pgsql.id}"]
  instances                   = ["${aws_instance.pgbouncer-int_func.*.id}", "${aws_instance.pgbouncer-int_load.*.id}"]
  cross_zone_load_balancing   = true
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400

  tags {
    App      = "${var.app_name}"
    Built_by = "Terraform"
  }
}
```
### Debug Output

https://gist.github.com/blunney1/886d7704e86e2ef696079c519a81e244
### Expected Behavior

An AWS ELB should have been created.
### Actual Behavior

Terraform balked.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by mitchellh** [comment]
This should be fixed in the latest version (0.7.11 atm) of Terraform. Its often hard to tell exactly if its the same issue that we fixed but the error messages were very similar. If you find this to not be the case please open a new issue. Thanks!
