### ISSUE TITLE
OpenStack multinetwork VM

### ISSUE THREAD

**Issue by diltram** [hashicorp/terraform#9632]
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- openstack_compute_instance_v2
### Terraform Configuration Files

```
resource "openstack_compute_instance_v2" "controller" {
    count = 1
    name = "${var.prefix}compute-node${count.index + 1}"
    image_name = "ubuntu-16.04-cloud"
    flavor_name = "m2.medium"
    key_pair = "${var.prefix}internal-key"

    network {
        uuid = "${openstack_networking_network_v2.mgmt_network.id}"
        access_network = true
    }

    network {
        uuid = "${openstack_networking_network_v2.second_network.id}"
    }
}
```
### Actual Behavior

```
-/+ openstack_compute_instance_v2.controller
    access_ip_v4:             "192.168.50.20" => "<computed>"
    access_ip_v6:             "" => "<computed>"
    flavor_id:                "8" => "<computed>"
    flavor_name:              "m2.medium" => "m2.medium"
    image_id:                 "59d44110-f1cd-4532-8bd4-18d48420366e" => "<computed>"
    image_name:               "ubuntu-16.04-cloud" => "ubuntu-16.04-cloud"
    key_pair:                 "dilu-terra-multinode-internal-key" => "dilu-terra-multinode-internal-key"
    name:                     "dilu-terra-multinode-controller-node1" => "dilu-terra-multinode-controller-node1"
    network.#:                "2" => "2"
    network.0.access_network: "false" => "false"
    network.0.fixed_ip_v4:    "192.168.50.20" => "<computed>"
    network.0.fixed_ip_v6:    "" => "<computed>"
    network.0.floating_ip:    "" => "<computed>"
    network.0.mac:            "fa:16:3e:5a:a6:5e" => "<computed>"
    network.0.name:           "dilu-terra-multinode-mgmt-net" => "<computed>"
    network.0.port:           "" => "<computed>"
    network.0.uuid:           "1c4b3e6a-18f8-493d-99a0-179af85d8ad7" => "d1c2fc8a-3340-4a1b-a6aa-57bf5d340767" (forces new resource)
    network.1.access_network: "false" => "false"
    network.1.fixed_ip_v4:    "192.168.50.20" => "<computed>"
    network.1.fixed_ip_v6:    "" => "<computed>"
    network.1.floating_ip:    "" => "<computed>"
    network.1.mac:            "fa:16:3e:5a:a6:5e" => "<computed>"
    network.1.name:           "dilu-terra-multinode-mgmt-net" => "<computed>"
    network.1.port:           "" => "<computed>"
    network.1.uuid:           "1c4b3e6a-18f8-493d-99a0-179af85d8ad7" => "1c4b3e6a-18f8-493d-99a0-179af85d8ad7"
    region:                   "RegionOne" => "RegionOne"
    security_groups.#:        "1" => "<computed>"
    stop_before_destroy:      "false" => "false"
```

What actually happened?

So VM is created correctly but the problem is with network array.
I was trying to get IP address from the first network but network.0 and network.1 contains the same IP addresses and other but when I will log in into that VM everything is OK.
It's just a problem with this how Terraform OpenStack plugins read the networks.

Also because of that Terraform every time when I will run `terraform plan` or `terraform apply` will show/recreate all VMs because it's showing that one of networks is missconfigured.

**Comment by jtopjian** [comment]
Thank you for reporting this!

**Comment by jtopjian** [comment]
@diltram I'm very sorry for the late reply on this issue. I'm unable to reproduce this, which can mean two things:

1. This was fixed sometime between when you reported it and now. I'm not sure this is the case, though. I can't recall the network ordering being touched for quite a long time and multi-network tests are part of the standard acceptance tests for this provider.

2. This might be specific to the Neutron driver being used in your cloud.

Are you still seeing this issue? If so, can you provide some details about your OpenStack cloud's network configuration (underlying Neutron driver, mainly). 

Also if so, can you provide the output of:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
$ OS_DEBUG=1 TF_LOG=DEBUG terraform plan
```

Thanks, and I do apologize for the lateness on this one.

**Comment by diltram** [comment]
I just double checked that. It had to be fixed in previous release as the issue doesn't exist any more in my environment.
