### ISSUE TITLE
Whats the Aws IAM infrastructure best practice?

### ISSUE THREAD

**Issue by zerolaser** [hashicorp/terraform#9635]
What is best practice for creating IAM stuff for the whole infrastructure. I was thinking to splitting up into this format:-
```
├── Modules
├── Dev
│   ├── users
│   │   ├── user1.tf
│   │   ├── user2.tf
│   │   ├── user3.tf
│   │   └── terraform.tfstate
│   ├── groups
│   │   ├── group1.tf
│   │   ├── group2.tf
│   │   ├── group3.tf
│   │   └── terraform.tfstate
│   ├── roles
│   │   ├── role1.tf
│   │   ├── role2.tf
│   │   ├── role3.tf
│   │   └── terraform.tfstate
└── Prod
│   ├── users
│   │   ├── user1.tf
│   │   ├── user2.tf
│   │   ├── user3.tf
│   │   └── terraform.tfstate
│   ├── groups
│   │   ├── group1.tf
│   │   ├── group2.tf
│   │   ├── group3.tf
│   │   └── terraform.tfstate
│   ├── roles
│   │   ├── role1.tf
│   │   ├── role2.tf
│   │   ├── role3.tf
│   │   └── terraform.tfstate
└──
```
 This way whenever user/group/role no longer required i could simply delete the tf file  and `terraform apply` will remove the exisiting IAM resource. I would like to know how you guys are implementing it.

**Comment by stack72** [comment]
Hi @zerolaser 

Thanks for checking in with us on this :) Luckily, we have a [best-practices](https://github.com/hashicorp/best-practices) repo that may be able to give you some insight :)

Hopefully it helps

Please let us know if it doesn't 

Paul

**Comment by zerolaser** [comment]
@stack72 I have gone through the best-practices and it helped me module in a better way. But my actual question was how multiple IAM resources are handled, I was confused should all the IAM resources should be handled in a single state file or an individual state file for each application? 
If Assumed all the iam resources will be in one state file, and if a particular user is part of more than one group say `Admin` and `Super Admin` .Terraform was throwing an error user already exists. 
If each application is handled separately how to link the common resources ?
