### ISSUE TITLE
"terraform plan" indicates that all resources need to be built, despite minor change

### ISSUE THREAD

**Issue by JulianGindi** [hashicorp/terraform#964]
I am using AWS as my provider and went to change the timeout value for the health check on my elastic load balancer. When I ran `terraform plan` it indicated that it was going to rebuild all my resources (including a database). This does not make sense to me. Any insight would be greatly appreciated.

**Comment by rmenn** [comment]
Sorry since it isnt clear, i wanted to know did you launch these resources with terraform?

**Comment by JulianGindi** [comment]
Yes, every resource was launched and configured via Terraform.

**Comment by rmenn** [comment]
Could you post your file and the output from the plan?

**Comment by JulianGindi** [comment]
@rmenn I don't have the output available but I can assure you the plan suggested that everything needed to be remove and than replace...which doesn't seem right for a small update. Here is the plan: https://gist.github.com/JulianGindi/3767d1c8f9cdef0b9d39

**Comment by rmenn** [comment]
Would you have the statefile handy? As i know that the resource does not need a refresh for the healthcheck change

**Comment by JulianGindi** [comment]
https://gist.github.com/JulianGindi/f2825884b7d6c8d27eb9 - Appreciate all the help so far :)

**Comment by JulianGindi** [comment]
Just tested it with a simplified setup on a separate AWS account, and ran into the same issue.

**Comment by JulianGindi** [comment]
I'm going to try to dig into the issue myself a bit. Any hints on where the related functionality is in the codebase?

**Comment by JulianGindi** [comment]
Anyone get a change to look into this? I wonder if anyone can reproduce it.

**Comment by phinze** [comment]
Hey there - sorry you're hitting trouble.

> Just tested it with a simplified setup on a separate AWS account, and ran into the same issue.

Can you provide the config that's giving you issues? That way we can help you figure out what might be going on here.

**Comment by catsby** [comment]
Unfortunately we can't yet reproduce this. If you have more information to help us to do so, please re-open this issue and we'll take another look.

Thanks!
