### ISSUE TITLE
Terraform is not handling the manual changes made to the IAM resources.

### ISSUE THREAD

**Issue by zerolaser** [hashicorp/terraform#9643]
I have created a sample IAM group and having an issue where manual changes to made to the IAM group, say like adding an existing policy/user is not detected by terraform.
### Terraform Version

`v0.7.7`
### Actual behavior

Whenever somebody makes manual changes like adding a policy to IAM group/user/role or user to IAM group, terraform is not detecting them.
### Expected behavior

Any manual changes made to the terraform resources should be detected when performing `terraform plan` and detach/remove them when `terraform apply` is performed.

**Comment by catsby** [comment]
Hey @zerolaser – sorry to say that right now `aws_iam_group` doesn't offer anything in the terms of managing the users or policies associated. The `aws_iam_group_membership` resource would detect changes to the users for this group, but we also don't have any resource for managing _all_ of the group policies. 

I'm marking this as both `bug` and `enhancement`, because we should probably have this, we simply don't right now.

Thanks!

**Comment by zerolaser** [comment]
@catsby also, In my scenario I was applying policies to the group and add the respective users to the group. any manual policies added to user will not be detected as the resource `aws_iam_user_policy_attachment` is not present.
Secondly, instead of using the resource `aws_iam_group_policy_attachment` for each group, I was using `aws_iam_policy_attachment`. which makes it easier to add all roles, groups and users. 

Also, I have checked for `aws_iam_user_policy_attachment` and manually attached an AWS managed policies and it wasn't detected at all. 
```
resource "aws_iam_user" "user" {
    name = "test_user"
}
resource "aws_iam_user_policy_attachment" "readonlypolicy" {
    user = "${aws_iam_user.user.name}"
    policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}
resource "aws_iam_user_policy" "testuserpolicy" {
    name = "test_user_dev"
    user = "${aws_iam_user.user.name}"
    policy = "${file("admin.json")}"
}
```  
Shouldn't the resource  `aws_iam_*_policy_attachment` handle the manual policies attached  just as `aws_iam_group_membership` handling them?
