### ISSUE TITLE
terraform_remote_state is typecasting string to bool  

### ISSUE THREAD

**Issue by fmasuhr** [hashicorp/terraform#9647]
### Terraform Version

`v0.7.8`
### Affected Resource(s)
- terraform_remote_state
### Terraform Configuration Files

`maint.tf`:

``` hcl
data "terraform_remote_state" "remote" {
  backend = "local"
  config {
    path = "${path.module}/remote/terraform.tfstate"
  }
}

output "test" {
  value = "${data.terraform_remote_state.remote.foo["bar"]}"
}
```

`./remote/terraform.tfstate`:

``` hcl
{
    "version": 3,
    "terraform_version": "0.7.8",
    "serial": 1,
    "lineage": "",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
                "foo": {
                    "sensitive": false,
                    "type": "map",
                    "value": {
                        "bar": "true"
                    }
                }
            },
            "resources": {},
            "depends_on": []
        }
    ]
}
```
### Expected Behavior

When running `terraform apply` i would expect the output `test` to be equal string `true`
### Actual Behavior

When running `terraform apply` the output `test` is equal `1`
### Steps to Reproduce

run `terraform apply` for `main.tf`

**Comment by apparentlymart** [comment]
Hi @fmasuhr! Sorry for this strange behavior.

I strongly suspect that this is the same issue as #13512. Although you got there first, I ended up digging into that one and making some notes there, so I'm going to close this one just to consolidate any ongoing discussion over there. Thanks for reporting this, and sorry we let it sit here for so long.
