### ISSUE TITLE
nested interpolation

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#9650]
Hi all,

````
Terraform 0.7.4
````

````
## flat hashmap
variable "sns_sqs" {
    default = [
        "a=a1",
        "a=a2",
        "b=b1",
        "c=c1"
    ]
}

resource "aws_sns_topic_subscription" "sns-sqs" {
    count = "${length(var.sns_sqs)}"
    protocol = "sqs"
    topic_arn = "arn:aws:sns:eu-west-1:123456:${element([split("=", element(var.sns_sqs, count.index))], 0)}-alpha"
    endpoint  = "arn:aws:sqs:eu-west-1:123456:${element([split("=", element(var.sns_sqs, count.index))], 1)}-alpha"
}
````

This results in a `parse error: syntax error`

Any idea why I am facing this error?

Thanks in advance.

**Comment by jbardin** [comment]
Hi @Puneeth-n,

I think the only problem here is that you don't need the the square brackets around the `split`function inside the interpolation

See if this does what you want:

    topic_arn = "arn:aws:sns:eu-west-1:123456:${element(split("=", element(var.sns_sqs, count.index)), 0)}-alpha"

**Comment by Puneeth-n** [comment]
@jbardin Nope. I tried both.
