### ISSUE TITLE
AutoMinorVersionUpgrade not set for AWS elasticache redis resource

### ISSUE THREAD

**Issue by ebgc** [hashicorp/terraform#9652]
Hi there,

### Terraform Version
Terraform v0.7.4

### Affected Resource(s)
- aws_elasticache_replication_group

### Important Factoids
https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#apply_immediately does not mention the attribute 'AutoMinorVersionUpgrade' which is available via AWS API: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html

AWS SDK for GO supports this attribute : http://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/

ciao and tx

**Comment by kwilczynski** [comment]
@ebgc hi there! I am sorry you had troubles because of this!

Let me see what we can do about it.

**Comment by kwilczynski** [comment]
I need to check with SDK developers, as the comment in the SDK and documentation says that this parameter is disabled. It might be an old information, though.

**Comment by stack72** [comment]
Closed via #9657
