### ISSUE TITLE
TF can't detect deleted aws_autoscaling_schedule

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#9654]
If I delete a autoscaling groups schedule in the AWS console, TF won't recongnize this and instead error out:

```
* aws_autoscaling_schedule.test-scaleup-weekdays: Error retrieving Autoscaling Scheduled Actions: ValidationError: Group core-jenkins not found
        status code: 400, request id: ff12e75c-9c59-11e6-8f16-630c68265022
```

### Terraform Version
0.7.5

### Affected Resource(s)
- aws_autoscaling_schedule

### Expected Behavior
The schedule should have been created.

### Actual Behavior
TF throws an error and can't continue (until the entry is removed from the state file).

### Steps to Reproduce
1. Create a aws_autoscaling_schedule with TF
2. Delete this schedule in the AWS console
3. Rerun 'terraform apply`

**Comment by FransUrbo** [comment]
Also, if I create the ASG in the AWS console and don't remove the <code>aws_autoscaling_schedule</code> entries from the state file, it will complain:

```
* aws_autoscaling_schedule.jenkins-scaleup-weekdays: Error retrieving Autoscaling Scheduled Actions: ValidationError: Group core-jenkins not found
        status code: 400, request id: fe945a0d-9c5f-11e6-a16f-41c6555e2186
```

**Comment by stack72** [comment]
Hi @FransUrbo 

nice find - just opened a PR that will fix this - it will be part of Terraform 0.7.8

Paul

**Comment by FransUrbo** [comment]
Does this also fix the problem I'm having with TF wanting to recreate them every day?

Last night before I went home I ran `apply` and everything was fine - no changed resource all good.

The first thing I did this morning was run `apply` again and I get:
```
* aws_autoscaling_schedule.jenkins-scaleup-weekdays: Error Creating Autoscaling Scheduled Action: ValidationError: Given start time is in the past
        status code: 400, request id: 5248f716-9cf6-11e6-99be-57830e31f130
```

**Comment by stack72** [comment]
Afraid not - that's maybe going to be a config problem. Can you post the config?

**Comment by FransUrbo** [comment]
@mathieuherbert Does your commit cd5934e solve this problem?
