### ISSUE TITLE
AWS group import pulling wrong group when using assume_role in another account in provider

### ISSUE THREAD

**Issue by hurleyit** [hashicorp/terraform#9665]
### Terraform Version

```
thurley$ terraform -v
Terraform v0.7.7

```
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_iam_group
### Terraform Configuration Files

``` hcl
provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::SUBACCOUNT:role/service-terraform"
  }
  region = "us-east-1"
}

data "terraform_remote_state" "aws" {
    backend = "s3"
    config {
        bucket = "TERRAFORMBUCKET"
        key = "terraform.tfstate"
        region = "us-east-1"
        profile = "default"
    }
}
```
### Debug Output

https://gist.github.com/hurleyit/0f732f697185230bd30a11ce798ecf7e
### Expected Behavior

It should have found and imported the group from the account referenced in the assume role portion of the aws provider.
### Actual Behavior

It attempted to import the group from the account referenced in default. If the group exists in the default account, it adds it to terraform.tfstate. If it doesn't exist, it says a resource with that id does not exist.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform import aws_iam_group.quicksight-admin quicksight-admin`
### Important Factoids

We have users provisioned in a main account and use roles to do our work in other accounts. aws_iam_user works without issues.

**Comment by mitchellh** [comment]
Fixed by #9809 (not yet merged but will be shortly)
