### ISSUE TITLE
aws_route inconsistency

### ISSUE THREAD

**Issue by adamgotterer** [hashicorp/terraform#9671]
Hi there,
### Terraform Version

0.7.5 and 0.7.7
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_route

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
### Terraform Configuration Files

``` hcl
resource "aws_route" "legacy_public" {
  route_table_id = "${aws_route_table.public.id}"
  destination_cidr_block = "${var.legacy_cidr}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.legacy.id}"
  depends_on = ["aws_route_table.public"]
}

resource "aws_route" "legacy_private" {
  count = "${length(var.private_subnets)}"
  route_table_id = "${element(aws_route_table.private.*.id, count.index)}"
  destination_cidr_block = "${var.legacy_cidr}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.legacy.id}"
  depends_on = ["aws_route_table.private"]
}
```
### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
### Expected Behavior

It should set a route target for the VPC peering connection.
### Actual Behavior

Each time I run apply it switches between adding the route record or removing it.

First apply:
https://gist.github.com/adamgotterer/20b3fbe60faf2dbe96f41d4f54e0601a

Second apply:
https://gist.github.com/adamgotterer/e36602b8b2fe5beac8cb935a7bcc0ba3
### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Possibly related to #6551

**Comment by mborho** [comment]
Had the same behaviour, until I realized you can't mix up inline routes in **aws_route_table** and additional **aws_route** resources for the route table.

https://www.terraform.io/docs/providers/aws/r/route_table.html.
