### ISSUE TITLE
google_compute_target_https_proxy does not handle certs correctly

### ISSUE THREAD

**Issue by jasonkeene** [hashicorp/terraform#9672]
### Terraform Version

```
$ terraform version
Terraform v0.7.7
```
### Affected Resource
- google_compute_target_https_proxy
### Terraform Configuration Files

vars.tf:

``` hcl
variable "concourse-cert" {
  type = "string"
}
```

terraform.tfvars:

``` hcl
concourse-cert = "projects/cff-loggregator/global/sslCertificates/wildcard-ci"
```

concourse.tf:

``` hcl
resource "google_compute_instance_group" "concourse-1" {
  name        = "concourse-${var.zone-1}-1"
  zone        = "${var.zone-1}"
  named_port {
    name = "http"
    port = "8080"
  }
  instances = "${var.concourse-web-instance-urls}"
}

resource "google_compute_backend_service" "concourse" {
  name        = "concourse"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 10
  enable_cdn  = false

  backend {
    group = "${google_compute_instance_group.concourse-1.self_link}"
  }

  health_checks = ["${google_compute_http_health_check.concourse.self_link}"]
}

resource "google_compute_http_health_check" "concourse" {
  name               = "concourse"
  request_path       = "/login"
  check_interval_sec = 1
  timeout_sec        = 1
  port               = 8080
}

resource "google_compute_target_https_proxy" "concourse" {
  name             = "concourse"
  url_map          = "${google_compute_url_map.concourse.self_link}"
  ssl_certificates = ["${var.concourse-cert}"]
}

resource "google_compute_url_map" "concourse" {
  name        = "concourse"

  default_service = "${google_compute_backend_service.concourse.self_link}"
}
```
### Debug Output

https://gist.github.com/jasonkeene/9a4c5a6f0c2032bf5471ed44742141c2
### Expected Behavior

An apply that contains a `google_compute_target_https_proxy` resource with certs referenced should be idempotent across multiple applys.
### Actual Behavior

With the first run, terraform creates the `google_compute_target_https_proxy` referencing an existing cert. The tfstate file does not contain the reference to the cert. When I run `tf apply` it attempts to add the cert to the `google_compute_target_https_proxy` again and errors out.
### Steps to Reproduce
1. `terraform apply`
2. `terraform plan # see the bad plan`
3. `terraform apply # get the error from gcp api`

**Comment by cblecker** [comment]
I'm able to duplicate this behaviour, but only when using the truncated form of the api endpoint. It works the way you expect it to when using the full URL (appending your current variable value with `https://www.googleapis.com/compute/v1/`).

I think this has to do with state storage and comparison with partial self links, as opposed to any issue specific to this resource.

**Comment by jasonkeene** [comment]
@cblecker Awesome, that worked. I think this would be more clear if the diff showed the old cert URL. Our output showed that the certs went from a zero-length list to a 1-length list, so we assumed it was a bug in this resource.

**Comment by cblecker** [comment]
@jasonkeene I'd venture that there may still be a bug in there somewhere with how state is stored and compared when a state refresh operation is done, or at the very least a more graceful way to handle it. Glad the full URL is working as a workaround though!
