### ISSUE TITLE
Outputs should support descriptions

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#9678]
### Terraform Version

Feature request.
### Affected Resource(s)

Please list the resources as a list, for example:
- outputs
### Terraform Configuration Files

It'd be great if I could provide a `description` for an output, in the same way I can provide one for a `variable`. This would make module documentation easier and make it easier to treat outputs like outgoing API documentation.

``` hcl
output "public_subnet_id" {
  description = "The AWS subnet ID"
  value = "${aws_subnet.public.id}"
}
```

**Comment by mgagliardo** [comment]
I don't know if this works out for you but my workaround for this is to do the following:
```
//My comments/description here
output "public_subnet_id" {
  value = "${aws_subnet.public.id}"
}
```

And using terraform-docs [Terraform docs](https://github.com/segmentio/terraform-docs):

```
$ terraform-docs md .

## Outputs

| Name | Description |
|------|-------------|
| public_subnet_id |  |
```

It will auto-generate a nice and consistent output for my README.md file. Maybe this will work for you as well.

Regards!

**Comment by jamtur01** [comment]
I use the same work around. But figured I'd ask at the source. :)

**Comment by mitchellh** [comment]
Absolutely, we just talked about this in a meeting yesterday. Tagged.

**Comment by Ninir** [comment]
As per https://github.com/hashicorp/terraform/pull/9722/files, this can be closed now I think.

Did you get a chance to try it @jamtur01?

**Comment by jamtur01** [comment]
Yes - can be closed!
