### ISSUE TITLE
aws_instance: tags with empty value are not applied

### ISSUE THREAD

**Issue by patricklucas** [hashicorp/terraform#968]
It is valid for AWS resource tags to have a key but no value, but Terraform does not successfully create them.

Terraform indicates that it wants to increase the tag count, but it does not actually create the resource unless I add a non-empty value:

```
~ aws_instance.foo-1
    tags.#: "3" => "4"
```

```
~ aws_instance.foo-1
    tags.#:                "3" => "4"
    tags.puppet:role::foo: "" => "a"
```

**Comment by mitchellh** [comment]
Thanks! This will be fixed with the PR above once I get a review.
