### ISSUE TITLE
terraform fmt should not recurse into .terraform/modules directories

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#9685]
### Terraform Version

Feature request.
### Affected Resource(s)
- Modules
- terraform fmt
### Requested Behavior

The `terraform fmt` command recurses into subdirectories. If the `.terraform` directory is present with downloaded modules it also processes any `.tf` files in the `modules` directory tree.

This can change those files. If this happens and we run a `terraform get -update` the get process will find locally changed files and fail - despite those local changes being only formatting. Since we can't protect from folks not formatting third-party right we should exclude the `.terraform/modules` tree from the `terraform fmt` command's recursion.

**Comment by nwalke** [comment]
Duplicate of #6663

**Comment by jamtur01** [comment]
Closed in favor of #6663.
