### ISSUE TITLE
"Variable 'yyy': duplicate found. Variable names must be unique." when using module multiple times

### ISSUE THREAD

**Issue by edmeister** [hashicorp/terraform#9688]
We are currently building our infrastructure and have multiple modules that use one the community modules (https://github.com/terraform-community-modules/tf_aws_coreos_ami).

When doing a `terraform get`  we get this output and error message:

```
$ terraform get
... (local modules)
Get: git::https://github.com/terraform-community-modules/tf_aws_coreos_ami.git
Get: git::https://github.com/terraform-community-modules/tf_aws_coreos_ami.git
Get: git::https://github.com/terraform-community-modules/tf_aws_coreos_ami.git
Error loading Terraform: module pop_ami.pop-cluster.root: 1 error(s) occurred:

* Variable 'all_amis': duplicate found. Variable names must be unique.
```

Terraform version: 0.7.7

Some code samples:
```
module "pop_ami" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami"
  region = "${var.region}"
  channel = "stable"
  virttype = "hvm"
}

resource "aws_launch_configuration" "pop" {
    image_id = "${module.pop_ami.ami_id}"
    instance_type = "${var.instance_type}"
    ...
}
```

Is this a bug in the current version of Terraform or is there no support for using a github module multiple times in different own modules? If that's the case, is there some workaround?

**Comment by alfonso-cabrera** [comment]
That should work as long as your modules have different names:

`module "pop_ami" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami"
  region = "${var.region}"
  channel = "stable"
  virttype = "hvm"
}

module "pop_ami_1" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami"
  region = "${var.region}"
  channel = "stable"
  virttype = "hvm"
}`

**Comment by edmeister** [comment]
Thanks for your reply. Every module has its own name though. I'll add some other relevant files that give an idea of the structure of our code.

```
# modules/aws/jenkins/main.tf
module "jenkins_ami" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami"
  region = "${var.region}"
  channel = "stable"
  virttype = "hvm"
}

resource "aws_instance" "jenkins" {
  ami                    = "${module.jenkins_ami.ami_id}"
  ...
}

# modules/aws/pop-cluster/main.tf
module "pop_ami" {
  source = "github.com/terraform-community-modules/tf_aws_coreos_ami"
  region = "${var.region}"
  channel = "stable"
  virttype = "hvm"
}

resource "aws_launch_configuration" "pop" {
  image_id = "${module.pop_ami.ami_id}"
  ...
}

# providers/aws/eu-central-1/jenkins.tf
module "jenkins" {
  source = "path/to/our/modules/aws/jenkins"
  ...
}

# providers/aws/eu-central-1/pop-cluster.tf
module "pop-cluster" {
  source = "../../../../modules/aws/pop-cluster"
  ...
}
```

So when we run a `terraform get` or `terraform plan` for our providers/aws/eu-central-1/ folder, we get this error.

**Comment by mitchellh** [comment]
I took a look at the module: https://github.com/terraform-community-modules/tf_aws_coreos_ami

And it indeed does define the variable multiple times (once with JSON and once in TF). This is a bug with this module and you should report it there.
