### ISSUE TITLE
aws_ecs_service/desired_count must be optional

### ISSUE THREAD

**Issue by BrunoBonacci** [hashicorp/terraform#9690]
The `desired_count` in the `aws_ecs_service` appears to be required. However the AWS api mandate this parameter only for the _creation_ of a service. For the update part of a service the `desired_count` must be optional.
- CreateService http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html
- UpdateService http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html

The reason being is that the `desired_count` is subject to automatic modification via the auto scaling policies. Mandate this value causes the service to _overwrite_ the value which was set by the auto-scaling policies.

Assume the case that you have a service which is created with a `desired_count = 3`. Then thanks to the auto scaling policies the service is scaled out to a `desired_count = 10`. At this point the terraform script still contains `desired_count = 3` and if you were to apply the changes the `desired_count` would be _forcefully reset_ to its initial value of 3.

```
~ aws_ecs_service.ecs_service
    desired_count: "10" => "3"
```

And if I try to remove the `desired_count = 3` from the script then it will set it to 0.

```
~ aws_ecs_service.ecs_service
    desired_count: "10" => "0"
```

By forcefully setting a lower number of `desired_count` it will tell the ECS service to KILL some of the excess containers to meet the desired number.
This would obviously cause some service disruption as suddenly big part of the container fleet will disappear.

The `desired_count` is required for manual scaling, but it is harmful/dangerous to use in conjunction to autoscaling. Like for the EC2 autoscaling should be entirely optional to use this value.
The solution suggested Is to introduce a new option for the `aws_ecs_service` called `initial_count` which will be passed as `desired_count` only when the resource is created and never during an update.

This is currently a big problem for those who want to use ECS in conjunction with the autoscaling policies as there is no alternative solution.
### Terraform Version
- Terraform v0.7.7
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_ecs_service
### Terraform Configuration Files

``` hcl
resource "aws_ecs_service" "mongo" {
  name = "mongodb"
  cluster = "${aws_ecs_cluster.foo.id}"
  task_definition = "${aws_ecs_task_definition.mongo.arn}"

  desired_count = 3

  iam_role = "${aws_iam_role.foo.arn}"
  depends_on = ["aws_iam_role_policy.foo"]

  load_balancer {
    elb_name = "${aws_elb.foo.name}"
    container_name = "mongo"
    container_port = 8080
  }
}
```
### Expected Behavior

The solution suggested Is to introduce a new option for the `aws_ecs_service` called `initial_count` which will be passed as `desired_count` only when the resource is created and never during an update.
### Actual Behavior

The `desired_count` KILLS all excess containers causing application downtime.
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. create a ECS cluster
2. create a container service
3. define autoscaling policies
4. let the policies scale your system under load
5. re-apply the script
6. notice `desired_count` is reset to the initial value and excess container killed.

**Comment by nhuray** [comment]
@BrunoBonacci @apparentlymart @mitchellh 

Any news about this issue ? 

It's a bit annoying because before updating my service I need to get the `desired_count` with the AWS Cli and pass the variable to Terraform:

```

**Comment by nhuray** [comment]
@BrunoBonacci @apparentlymart @mitchellh 

After looking at the code I think we don't have to introduce a new option for the `aws_ecs_service` called `initial_count, we just have to remove the update of the `desired_count` when we `read` from  the real-infrastructure (`DescribeService`). I gonna submit a PR for this !

**Comment by BrunoBonacci** [comment]
This issue has been moved here:
https://github.com/terraform-providers/terraform-provider-aws/issues/335
