### ISSUE TITLE
Feature Request: interleave

### ISSUE THREAD

**Issue by craigmonson** [hashicorp/terraform#9697]
### Terraform Version

0.7.7
### Description

I'd like to be able to interleave 2 lists together; primarily to create a map for an output to a module, which would mean the map function in the interpolation syntax would need to accept lists too.

Example:

``` tf
variable "my_names" {
  type = "list"
  #...
}
resource "aws_instance" "named_instances" {
  count "${length(var.my_names)}"
  #...
  tags {
    Name = "${element(var.my_names, count.index)}"
    #...
  }
}

output "id_map" {
  value = "${map(interleave(var.my_names, aws_instance.named_instances.*.id))}"
}
```

**Comment by jbardin** [comment]
Hi @craigmonson,

I may be misunderstanding, but is [`zipmap`](https://www.terraform.io/docs/configuration/interpolation.html#zipmap_list_list_) what you're looking for?

**Comment by craigmonson** [comment]
Oh, there ya go.  That's what I was looking for.  Came out Nov 1st with 0.7.8.

Thanks!
