### ISSUE TITLE
AWS route table creation failed on 0.3.6 [same code works in 0.3.1/0.3.5 ]

### ISSUE THREAD

**Issue by yikaus** [hashicorp/terraform#970]
Hi , Below code was run successfully on 0.3.1/0.3.5 , but failed on 0.3.6 with a bug exception

##########Network configuration#############
##VPC
resource "aws_vpc" "infratestVPC" {
    cidr_block = "192.168.0.0/16"
}

##Subnet
resource "aws_subnet" "infratest_private" {
    vpc_id = "${aws_vpc.infratestVPC.id}"
    cidr_block = "192.168.0.0/24"
}

resource "aws_subnet" "infratest_public" {
    vpc_id = "${aws_vpc.infratestVPC.id}"
    cidr_block = "192.168.1.0/24"
}

##Gateway
resource "aws_internet_gateway" "infratest_igw" {
    vpc_id = "${aws_vpc.infratestVPC.id}"
}

#RouteTable
resource "aws_route_table" "public_route" {
    vpc_id = "${aws_vpc.infratestVPC.id}"
    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = "${aws_internet_gateway.infratest_igw.id}"
    }
    
} 

Error applying plan:

aws_route_table.public_route: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.

Should be easy to reproduce .

**Comment by mitchellh** [comment]
This is fixed now. I'm not sure what fixed it but I jsu ran the exact config! :)

**Comment by yikaus** [comment]
Good , waiting on next release ! :_)

**Comment by yikaus** [comment]
Tested it with fresh 0.3.7 , all good now , great !!
