### ISSUE TITLE
Terraform Doesn't Recognize A Default of an Empty Array as an Optional Module Variable

### ISSUE THREAD

**Issue by thegranddesign** [hashicorp/terraform#9711]
Just like the title says.  Even if you put:

``` json
"my_var": { "type": "list", "default": [] }
```

If you try to access the module without specifying `my_var` it will blow up saying that `my_var` is required.
### Terraform Version

0.7.7

**Comment by sl1pm4t** [comment]
@thegranddesign 
This appears to be fixed in the next terraform version.
I can reproduce in 0.7.7 but not 0.7.8 (built today from master)

Also, this problem doesn't occur if the module config is HCL (not JSON).

**Comment by thegranddesign** [comment]
@sl1pm4t awesome! 

And yeah all my configs are JSON. I prefer it quite a bit over HCL. Much easier to read, editors all support it for syntax checking and highlighting, easier to work with templates since every language has JSON parsers. Only downside is lack of comments. Wish YAML was supported.

**Comment by paddyforan** [comment]
Hi @thegranddesign! This issue appears to be resolved as 0.7.8 has been released, so I'm going to close it out. If it's still an issue, please feel free to comment in this issue and we'll reopen it. Thanks for reporting the bug.

**Comment by thegranddesign** [comment]
@paddyforan thank you so much!!
