### ISSUE TITLE
Changelog / Warnings should clarify private_key changes within provisioning.

### ISSUE THREAD

**Issue by mobiuscog** [hashicorp/terraform#9723]
With the release of 0.6.7 last year, the following improvement was within the changelog:
- connection/ssh: Accept `private_key` contents instead of paths ([#3846](https://github.com/hashicorp/terraform/issues/3846))

However, private_key paths were still accepted until the recent commit https://github.com/hashicorp/terraform/commit/968472a63e4542a2c5e2693c4489da4776dac996#diff-d1b9df521bc0abcc44e4d3cefd5414b7 which arrived with the release of 0.7.7

Unfortunately, this then breaks SSH provisioning connections for anyone that has missed the discussion or similar documents, without warning and just begins failing SSH handshakes (a colleague went from 0.7.3 to 0.7.7 and I spent a morning diving into the code to figure out why).

The documentation is kept fairly well up-to-date, but there was nothing in the changelog regarding this, and it would have made sense for it to be mentioned as a backwards incompatibility. Ideally, it would have failed to plan/run with a suitable error message, although the subtlety here may well be that it was being set via interpolation.

Terraform is great, but can be really frustrating when things just break.

**Comment by stack72** [comment]
Hi @mobiuscog 

My apologies for the issue here - this was something that has, unfortunately, slipped through the net. We just posted an errata for it as part of our 0.7.8 release announcement!

We apologise for the problems here and will try and make sure this doesn't happen again

```
Please also note the retroactive addition to a Backwards Incompaitiblity notice in the v0.7.4 release regarding private keys and the connection block of provisioners:
* https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#074-september-19-2016
```

Paul
