### ISSUE TITLE
Function REPL-esque Evaluator?

### ISSUE THREAD

**Issue by tylerFowler** [hashicorp/terraform#9750]
It would be nice to have a sort of REPL-like 'playground' where you could simply type in string blocks with interpolation functions. For example when I'm doing more complicated stuff with a series of functions I'd like to have a way outside of using a dummy Terraform project with a single file & output to make sure the functions will do what I think they'll do for a certain input as a quick sanity check.

**Comment by apparentlymart** [comment]
Hmm... this is an interesting thought, @tylerFowler.

Were you imagining that you'd run it in a directory containing a Terraform configuration and its associated state, and then you could use it to look at arbitrary data from the state?

```
$ terraform repl
> aws_instance.main.id
i-12341234
> join(" ", aws_instance.consul.*.private_ip)
10.1.0.1 10.1.0.2 10.1.0.3
> exit
$ 
```

This also made me think about giving Terraform its own analog of `consul-template` where you can give it a template file and it'll generate output based on what's currently in the state. I opened #9760 for that. :grinning:

**Comment by tylerFowler** [comment]
Yeah! That'd be really cool. Really my initial thought was just as a sanity check to make sure that chained functions would have the behavior I thought they would have given some known input or something. But taking that a step further into interactively inspecting your own infrastructure state would be equally helpful.
