### ISSUE TITLE
CheckDestroy function in acceptance test doesn't get resource state

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/terraform#976]
I'm writing tests for my custom Terraform plugin. Basic functionality works fine, but now I'm trying to add `CheckDestroy` validation, and it doesn't work as expected. 

Even if a tested resource was created successfully, the function always receives empty `State` value, so I cannot obtain resource ID to check, if it still exists.

A code like
```
func testAccCheckVirtualMachineDestroy(s *terraform.State) error {
    return fmt.Errorf("%s", s)
}
```
fails with
```
--- FAIL: TestAccVirtualMachine_basic (92.70s)
        testing.go:142: Error destroying resource! WARNING: Dangling resources
                may exist. The full state and error is shown below.
                
                Error: Check failed: ####### <no state>
                
                State: <no state>
FAIL
```

A full test run log is at https://gist.github.com/mkuzmin/271854fe3e7765599d09
The test sources are at https://github.com/mkuzmin/terraform-vsphere/blob/testing/resource_virtual_machine_test.go

Do you have any ideas what can be wrong here?

**Comment by mitchellh** [comment]
This is weirdly non-intuitive, but its working as I intended. You should add a teststep that copies the ID to a local variable, then use that in your destroy check. The state passed in you should verify that your resource is gone.

**Comment by mitchellh** [comment]
Does that make sense? Hope that helps.

**Comment by mkuzmin** [comment]
Sorry, but it's still unclear. I'm not asking to teach me how to develop in Go, but could you please just point to any example.
I'm looking at built-in provider code, and don't see anything similar.
I.e. CloudFlare plugin at https://github.com/hashicorp/terraform/blob/master/builtin/providers/cloudflare/resource_cloudflare_record_test.go#L86
Is it using any local variables?

**Comment by mitchellh** [comment]
Sure yeah, this isn't with destroy but the same pattern: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elb_test.go#L28

During your test steps, save the output to a copy local variable, then create the destroy function to use that.
