### ISSUE TITLE
Can't build terraform for development

### ISSUE THREAD

**Issue by artburkart** [hashicorp/terraform#9761]
Hi,

I apologize if this is just a simple golang problem—I'm very new to the language—I'm trying to build terraform, so I can implement some functionality, but when I run [make dev](https://github.com/hashicorp/terraform/blob/836d17158fd1dbec2fd4643369af35a5cee561af/README.md#developing-terraform), I get the following errors on [master](https://github.com/hashicorp/terraform/commits/3630bb0e3f91d3c93447e229d9b5a38c7ec210a4):

```
go_code/src/github.com/hashicorp/terraform$ make dev
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/10/31 21:39:02 Generated command/internal_plugin_list.go
==> Removing old directory...
==> Building...
Number of parallel builds: 3

-->     linux/amd64: github.com/hashicorp/terraform

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/terraform/vendor/github.com/Azure/azure-sdk-for-go/management
vendor/github.com/Azure/azure-sdk-for-go/management/http.go:91: unknown tls.Config field 'Renegotiation' in struct literal


==> Results:
total 0
```

When I delete line 91, it builds successfully, which is great and all, but is there something I can do to make it build successfully? I imagine the deps directory needs a new json file or something?

Cheers

**Comment by stack72** [comment]
Hi @artburkart 

Terraform has now got a dependency on Go 1.7 due to changes in the Azure SDK. I will get this added to the README today

Sorry for the trouble here

Paul
