### ISSUE TITLE
Locks in AzureRM

### ISSUE THREAD

**Issue by AMMullan** [hashicorp/terraform#9768]
Hi,

I can't see any option for setting Locks on resources, i.e. we want to have a Resource Group in Azure for networking components and have it Locked so only Owners can manage it but Terraform doesn't seem to have this feature?

REST API documentation is here: https://azure.microsoft.com/en-gb/documentation/articles/resource-group-lock-resources/

### Terraform Version
Terraform v0.7.7

### Affected Resource(s)
- azurerm_resource_group
- any other resource that has the Locks options

### Expected Behavior
Create locks for whichever resources need them.

**Comment by pmcatominey** [comment]
Hi @AMMullan,

I've been working on this resource but came across a couple of SDK issues which I've reported in Azure/azure-sdk-for-go#440.

Cheers

**Comment by marsher** [comment]
Hi @pmcatominey,

Is there any update on this resource?
Looks like Azure/azure-sdk-for-go#440 has been fixed.
