### ISSUE TITLE
Terraform keeps wanting to change route53 records

### ISSUE THREAD

**Issue by tomstachura** [hashicorp/terraform#9772]
Terraform keeps wanting to change the following when running the attached prod/main.tf even though nothing has changed in the files:

~ module.tst1.lb_web.aws_route53_record.r53_record
    alias.111955117.evaluate_target_health:  "" => "true"
    alias.111955117.name:                    "" => "TEST1-WEB-934561747.us-west-2.elb.amazonaws.com"
    alias.111955117.zone_id:                 "" => "Z1H1FL5HABSF5"
    alias.3481356494.evaluate_target_health: "true" => "false"
    alias.3481356494.name:                   "test1-web-934561747.us-west-2.elb.amazonaws.com" => ""
    alias.3481356494.zone_id:                "Z1H1FL5HABSF5" => ""

~ module.tst1.lb_ui.aws_route53_record.r53_record
    alias.1772725216.evaluate_target_health: "" => "true"
    alias.1772725216.name:                   "" => "TEST1-UI-128225832.us-west-2.elb.amazonaws.com"
    alias.1772725216.zone_id:                "" => "Z1H1FL5HABSF5"
    alias.2787155967.evaluate_target_health: "true" => "false"
    alias.2787155967.name:                   "test1-ui-128225832.us-west-2.elb.amazonaws.com" => ""
    alias.2787155967.zone_id:                "Z1H1FL5HABSF5" => ""

~ module.tst1.lb_id.aws_route53_record.r53_record
    alias.1642565914.evaluate_target_health: "true" => "false"
    alias.1642565914.name:                   "test1-id-1993475306.us-west-2.elb.amazonaws.com" => ""
    alias.1642565914.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.3961525715.evaluate_target_health: "" => "true"
    alias.3961525715.name:                   "" => "TEST1-ID-1993475306.us-west-2.elb.amazonaws.com"
    alias.3961525715.zone_id:                "" => "Z1H1FL5HABSF5"

~ module.tst1.lb_solr.aws_route53_record.r53_record
    alias.2989646069.evaluate_target_health: "true" => "false"
    alias.2989646069.name:                   "internal-test1-solr-2033871431.us-west-2.elb.amazonaws.com" => ""
    alias.2989646069.zone_id:                "Z1H1FL5HABSF5" => ""
    alias.3452499411.evaluate_target_health: "" => "true"
    alias.3452499411.name:                   "" => "internal-TEST1-SOLR-2033871431.us-west-2.elb.amazonaws.com"
    alias.3452499411.zone_id:                "" => "Z1H1FL5HABSF5"

[terraform bug report.zip](https://github.com/hashicorp/terraform/files/564248/terraform.bug.report.zip)

I removed the access keys, a certificate and a couple of IP's from the script, otherwise you should be able to run them.

**Comment by stack72** [comment]
Hi @tomstachura 

I believe we have fixed this in master due to #9704. This will be released as part of Terraform 0.7.8 soon:tm:

Please let us know if that doesn't help

Sorry for the issues 

Paul
