### ISSUE TITLE
Add arn_suffix output value for aws_alb_target_group

### ISSUE THREAD

**Issue by Tomino2112** [hashicorp/terraform#9773]
At the moment, only output values for `aws_alb_target_group` are `id` and `arn`

When setting cloudwatch alarms, dimensions should be referenced by the arn suffixes, as is correctly exported by `aws_alb`

**Comment by kwilczynski** [comment]
@Tomino2112 hi there!

I am happy to report that this was recently done via https://github.com/hashicorp/terraform/pull/9734, therefore it is going to be included in an upcoming release (0.7.8).

**Comment by Tomino2112** [comment]
@kwilczynski Awesome ! In the meantime though, is there something I can do? I am trying to use `split` fn but cannot really get my head around how to reference the last part?

I am trying: 
```
split(":", aws_alb_target_group.api_rest.arn).last -> error
```

```
element(split(":", aws_alb_target_group.api_rest.arn), how_to_get_length_of_list)
```

**Comment by Tomino2112** [comment]
Never mind, I have just done this:

```
${element(split(":", aws_alb_target_group.api_rest.arn), 5)}
```

`5` is hardcoded, but will do until the new version is out
