### ISSUE TITLE
duplicate security group

### ISSUE THREAD

**Issue by tomstachura** [hashicorp/terraform#9778]
This is pointing me to pages of discussion from over a year ago. Seems this bug is still happening

2 error(s) occurred:

* aws_security_group_rule.ivory.0: [WARN] A duplicate Security Group rule was found on (sg-4f0f7836). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 199.58.192.98/32, TCP, from port: 22, to port: 22, ALLOW" already exists
* aws_security_group_rule.ivory.1: [WARN] A duplicate Security Group rule was found on (sg-4f0f7836). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 35.161.227.236/32, TCP, from port: 22, to port: 22, ALLOW" already exists

I have 2 of these pointing to 2 different security groups. If I have just 1 of these, it works. If I have 2 it fails with the above.
resource "aws_security_group_rule" "admin" {
  type = "ingress"
  from_port   = 22
  to_port     = 22
  protocol    = "tcp"
  security_group_id = "${aws_security_group.admin.id}" # for the 2nd one, this was changed to another ID
  cidr_blocks = ["${var.admin_ips[count.index]}/32"]

  count       = "${length(var.admin_ips)}"
}

**Comment by catsby** [comment]
Hey @tomstachura – do you have any more information regarding the other security groups? What other rules are present there, are they managed by Terraform, if so do those resources have other `aws_security_group_rule` resources involved or any rules defined inline? Any more information you can share without exposing secrets would be greatly appreciated

**Comment by tomstachura** [comment]
Hi – feel free to look through the entire setup – attached.

 

Tom

 

Tom Stachura
 <tel:1-604-525-7096> 1-604-525-7096 /  <mailto:tom@unoworks.ca> tom@unoworks.ca
 <https://twitter.com/tomstachura>   <https://www.linkedin.com/profile/view?id=4191438>

**Comment by DoomedKid** [comment]
+1

**Comment by jalleyne** [comment]
+1
having this issue as well, it looks like terraform doesn't take the source_security_group_id into consideration when checking duplicate existence.
