### ISSUE TITLE
Support AWS Cloudformation YAML files

### ISSUE THREAD

**Issue by booi** [hashicorp/terraform#9779]
Hi, 

AWS recently began supporting Cloudformation in YAML files and we run a hybrid terraform-managed set of Cloudformation stacks. It seems like Terraform does not support Cloudformation files in YAML in either template_body or template_url properties of aws_cloudformation_stack.

### Terraform Version
$ terraform -v
Terraform v0.7.7

### Affected Resource(s)
aws_cloudformation_stack

### Terraform Configuration Files
```hcl
resource "aws_cloudformation_stack" "admin" {
  name = "admin"
  template_url = "${var.cf_bucket_url}/admin.yaml"
  capabilities = ["CAPABILITY_NAMED_IAM"]
}
```

### Debug Output
https://gist.github.com/booi/6363d1c6cad7b41736f83dbce33442bf

### Expected Behavior
Cloudformation stack created successfully and Terraform should return no error.

### Actual Behavior
Cloudformation stack is actually created successfully (so no YAML file error). 
Terraform returns the error in the gist above.

**Comment by stack72** [comment]
Closed via #11121
