### ISSUE TITLE
resource churn because of whitespace/indentation changes in IAM policy

### ISSUE THREAD

**Issue by hakamadare** [hashicorp/terraform#9786]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
$ terraform -v
Terraform v0.7.7
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket_policy

### Terraform Configuration Files
```hcl
data "aws_iam_policy_document" "log_bucket_policy" {
  statement {
    sid = "1"
    actions = [
      "s3:PutObject"
    ]
    effect = "Allow"
    resources = [
      "arn:aws:s3:::${var.log_bucket}/logs/alb/AWSLogs/${data.aws_caller_identity.current.account_id}/*"
    ]
    principals = [
      {
        type = "AWS",
        identifiers = ["${data.aws_elb_service_account.current.id}"]
      }
    ]
  }
}

resource "aws_s3_bucket_policy" "log_bucket_policy" {
  bucket = "${var.log_bucket}"
  policy = "${data.aws_iam_policy_document.log_bucket_policy.json}"
}
```

### Expected Behavior
What should have happened?

1. Policy created on initial apply
2. Policy applied to bucket on initial apply
3. No changes on future applies

### Actual Behavior
What actually happened?

1. Policy created on initial apply
2. Policy applied to bucket on initial apply
3. On every subsequent plan/apply:

```
~ module.edge_tier.aws_s3_bucket_policy.log_bucket_policy
    policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"1\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::XXXXXXXXXXX:root\"},\"Action\":\"s3:PutObject\",\"Resource\":\"arn:aws:s3:::XXXXXXXXXXX/logs/alb/AWSLogs/XXXXXXXXXXXXX/*\"}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"1\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"s3:PutObject\",\n      \"Resource\": \"arn:aws:s3:::XXXXXXXXXXXXX/logs/alb/AWSLogs/XXXXXXXXXXXXX/*\",\n      \"Principal\": {\n        \"AWS\": \"XXXXXXXXXXXXXX\"\n      }\n    }\n  ]\n}"
```

Specifically, there's no change in the content of the policy that I can see, other than the introduction of whitespace and newlines.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by catsby** [comment]
Hey @hakamadare – the difference is in the `principal`: 

```
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXXXX:root"
      },
```

vs. 

```
      "Principal": {
        "AWS": "XXXXXXXXXXXXXX"
      },
```

For `data.aws_iam_policy_document` when the `principal` type is `AWS`, the `identifiers` need to be the ARN. Please try this:

```
    principals = [
      {
        type = "AWS",
        identifiers = ["${data.aws_elb_service_account.current.arn}"]
      }
    ]
```

And let us know!

- https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html
- https://www.terraform.io/docs/providers/aws/d/elb_service_account.html

**Comment by hakamadare** [comment]
@catsby that did the trick!  thank you :)

**Comment by catsby** [comment]
Great, thanks for following up!
