### ISSUE TITLE
support for GCP regional instance groups

### ISSUE THREAD

**Issue by jaibheem** [hashicorp/terraform#9787]
Hello,

I am trying out Terraform for the GCP. how ever I don't see option to create regional instance groups. (This is the Beta feature though)

Resource:
google_compute_instance_group_manager

https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#creating_a_regional_managed_instance_group

is this going to addressed ?

**Comment by cblecker** [comment]
duplicate of #8866

**Comment by stack72** [comment]
Hi @jaibheem 

Thanks for the report here - as @cblecker has pointed out, this is a duplicate. Please use the other issue for any tracking

Thanks

Paul

**Comment by jaibheem** [comment]
hello @stack72 @cblecker I see it is now GA : https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#creating_a_regional_managed_instance_group 

do we have plan for making it available in Terraform?
