### ISSUE TITLE
local-exec provisioner for S3 bucket causes panic when used in a module

### ISSUE THREAD

**Issue by 2rs2ts** [hashicorp/terraform#9790]
When I have a module that creates an `aws_s3_bucket` and uses a `local-exec` provisioner I get a panic after the provisioning script runs.

### Terraform Version

Terraform v0.7.8

### Affected Resource(s)

- aws_s3_bucket
- module

### Terraform Configuration Files

main.tf:

```hcl
provider "aws" {
  region = "us-east-1"
}
module "mymodule" {
  source = "./module"
}
```

module/main.tf:

```hcl
resource "aws_s3_bucket" "my_test_bucket" {
  bucket = "andrews-test-bucket"
  acl = "private"
  provisioner "local-exec" {
    command = "/bin/true"
  }
}
```

### Debug Output

https://gist.github.com/2rs2ts/ad35dd3e727e99139d7156bbd98140c8

### Panic Output

https://gist.github.com/2rs2ts/d08d20771dd38686e4c95fbe0e15b2c8

### Expected Behavior

No panic should have occurred.

### Actual Behavior

Terraform panicked after completing the provisioning. It created the bucket and ran the command just fine, but panicked afterward.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

This does not happen if the `aws_s3_bucket` is not created by a `module`, i.e. move the contents of module/main.tf into main.tf and remove the `module` declaration.

Also, this worked in 0.7.7. This is a regression.

**Comment by mitchellh** [comment]
Ah, this is fixed in 0.7.9
