### ISSUE TITLE
outputs should have count

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#9793]
Terraform "output" resources should have count, otherwise its impossible to define key/value pairs for the resources which do have count.

So you have to do something like this instead:

```
output "my_private_ips" {
  value = "${join(",", aws_instance.my_instances.*.private_ip)}"
}
```

Which outputs something like:

```
my_private_ips = 10.1.1.1,10.1.1.2,10.1.1.3,10.1.1.4
```

And is suboptimal to being able to output:

```
my_private_ips.0 = 10.1.1.1
my_private_ips.1 = 10.1.1.2
my_private_ips.2 = 10.1.1.3
```

**Comment by mitchellh** [comment]
Please tell me if I'm missing a use case but this doesn't seem necessary now that outputs can be lists:

```
resource "null_resource" "foo" {
    count = 5
}

output "foo" {
  value = ["${null_resource.foo.*.id}"]
}
```

```
module "child" {
    source = "./child"
}

output "output" {
    value = "${module.child.foo[0]}"
}
```
