### ISSUE TITLE
Imported state for aws_elasticache_cluster causes a problem with the port field

### ISSUE THREAD

**Issue by makered** [hashicorp/terraform#9796]
Hi,

After importing my Redis EC cluster via:

`terraform import aws_elasticache_cluster.my_cluster my_cluster`

and writing a resource script to match the state that contains:

`port = 6379`

the plan for some reason shows:

`port: "" => "6379" (forces new resource)`

The state file contains only the following in relation to the port:

`"cache_nodes.0.port": "6379"`

When I manually added the following to the state file:

`"port": "6379"`

and re-ran the plan, the result does not show a change on port and there is no plan to replace the cluster

Could this be a bug?

I am running Terraform 0.7.7

**Comment by makered** [comment]
Just wanted to add that as a test I spun up a new EC cluster from a fresh script and examined the state, both of the following were present:

`"cache_nodes.0.port": "6379"`
`"port": "6379"`

**Comment by nbirnel** [comment]
This is still present in Terraform v0.7.10 - 
`terraform import aws_elasticache_cluster.foo my_cluster` does not import "port".

**Comment by sirkjohannsen** [comment]
Still an issue in 0.8.3

**Comment by hamstah** [comment]
Hi,
Just had the same issue in 0.9.3.
Fixing the state file with

* `terraform state pull > state.json`
* Find the elasticache resource
* Add `"port": "6379"`
* `terraform state push state.json`
* `terraform plan`

**Comment by EitherZeroOrOne** [comment]
I have this issues as well. `terraform import` will cause `"port"` to be missing from state file and so running `terraform plan` results in the displayed diff

**Comment by skeggse** [comment]
@EitherZeroOrOne this issue was closed and has been replaced by https://github.com/terraform-providers/terraform-provider-aws/issues/341
