### ISSUE TITLE
Add Papertrail provider

### ISSUE THREAD

**Issue by ejholmes** [hashicorp/terraform#98]
If I get some time I might implement this. It would be great to be able to add Papertrail systems and be able to add them as drains on a heroku app.

/cc @leonsodhi

**Comment by josephholsten** [comment]
@ejholmes did you ever get a spike of this started?

**Comment by ejholmes** [comment]
Nope. Not using papertrail or terraform atm :)

**Comment by phinze** [comment]
We'd welcome any PRs w/ Papertrail support, but we don't have any plans as a core team to work on the feature, so closing this for now.

**Comment by sjauld** [comment]
This would be so good. @mubeta06 can you build?

**Comment by mubeta06** [comment]
Hai

Just as soon as this hangover goes away

**Comment by mohandutt134** [comment]
I have worked on this, Here is the first implementation https://github.com/oogway/terraform-provider-papertrail
