### ISSUE TITLE
Add the option to specify Networkdomain to resource_cloudstack_network

### ISSUE THREAD

**Issue by noni73** [hashicorp/terraform#9801]
Please add the option to specify Networkdomain on network creation. 
The go provider is able to specify Networkdomain.
https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/NetworkService.go

### Affected Resource(s)
- resource_cloudstack_network

### References
- GH-3248

**Comment by svanharmelen** [comment]
@noni73 this was already fixed a couple of months ago by PR #10638
