### ISSUE TITLE
Feature Request:  Do not do variable and output validations after `terraform get --update`

### ISSUE THREAD

**Issue by jgartrel** [hashicorp/terraform#9808]
It would be great `terraform get --update` command would just fetch the dependent modules and setup its local module cache, as it has done in the past. Any code or syntax validations should be done at runtime as a prerequisite to 'plan' or 'apply'.

### Terraform Version
terraform v0.7.3 and greater

### Affected Resource(s)

- core
- custom modules

### Steps to Reproduce
Please list GH-9134 for the steps required to reproduce the issue

### References
- GH-9134

**Comment by mitchellh** [comment]
Dup of #9134 it appears
