### ISSUE TITLE
terraform import creates configuration file

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/terraform#9827]
Hi there,

After running `terraform import` to import aws instance to tfstate, I have to write configuration files manually, could terraform create the files for me?

### Terraform Version
Terraform v0.7.9-dev (de4ae7a7423585dceee33ca6d195dca592887f7a+CHANGES)

### Affected Resource(s)
- aws_instance

**Comment by catsby** [comment]
Hey @waterdudu – this is certainly a feature we plan to add! Unfortunately we have no timeline for delivering it. Thanks for opening this issue, I'm going to close it however as we'll be tracking and developing the feature internally
