### ISSUE TITLE
provider/openstack: `openstack_fw_policy_v1` defaulting `shared` results in 400 response

### ISSUE THREAD

**Issue by fatmcgav** [hashicorp/terraform#9829]
The `openstack_fw_policy_v1` resource defaults `shared` to `false`. 
However `shared` is an 'admin-only' field, as described here: [openstack-api-ref/networking/v2/fwaas#create-firewall-policy](http://developer.openstack.org/api-ref/networking/v2/index.html?expanded=create-firewall-policy-detail) 

Attempting to specify `shared` with a non-admin accounts results in a HTTP 400 response from Neutron. 
> {"NeutronError": "Attribute 'shared' not allowed in POST"}

### Terraform Version
0.7.8-dev

### Affected Resource(s)
-`openstack_fw_policy_v1`

### Terraform Configuration Files
```hcl
resource "openstack_fw_policy_v1" "policy_1" {
  region = "uk-1"
  name = "policy_1"
  rules = [
    "${openstack_fw_rule_v1.allow_icmp.id}",
    "${openstack_fw_rule_v1.allow_ssh.id}"
  ]
}
```

Pull request incoming to resolve.

**Comment by jtopjian** [comment]
@fatmcgav passing `shared: False` as a non-admin user works with the default FWaaS driver. Do you know what FWaaS driver your cloud is using? I'd just like to know for reference.

The patch you made looks great, so I'm going to merge it. :)

**Comment by fatmcgav** [comment]
@jtopjian I don't, but I can try and find-out... I doubt it's default though, as they've made lots of 'tweaks' to stuff...

**Comment by jtopjian** [comment]
@fatmcgav sounds good! Definitely interested if you can find out :)
