### ISSUE TITLE
Elastic Transcoder Preset: MaxFrameRate defaults to 30, but shouldn't.

### ISSUE THREAD

**Issue by tecnobrat** [hashicorp/terraform#9847]
When using a `aws_elastictranscoder_preset` we want to be able to set "FrameRate" to a static frame rate, and not use MaxFrameRate.

According to the AWS docs, this is accomplished by simply not passing MaxFrameRate. However terraform defaults MaxFrameRate to 30:

https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/builtin/providers/aws/resource_aws_elastic_transcoder_preset.go#L213-L218

This causes the following API error on apply:

```
* aws_elastictranscoder_preset.desktop_video: Error creating Elastic Transcoder Preset: ValidationException: When you specify a value for MaxFrameRate, you must also specify 'FrameRate':'Auto'. Either change the value of FrameRate or remove the MaxFrameRate object, and resubmit the request.
	status code: 400, request id: f70b50ff-a1e7-11e6-8ba6-0f0748938856
```

MaxFrameRate will default to 30 if you do not pass a value, according to the AWS docs.  So terraform does not need to enforce this setting to be default of 30.

**Comment by svanzoest** [comment]
I just ran into this as well. It makes it impossible to create a preset with a constant FrameRate.
