### ISSUE TITLE
aws_security_group_rule inappropriately creating open rule

### ISSUE THREAD

**Issue by apenney** [hashicorp/terraform#9854]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.8

### Affected Resource(s)
- aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group_rule" "v5-support-portmapper" {
    type                     = "ingress"
    from_port                = 111
    to_port                  = 111
    protocol                 = "all"
    source_security_group_id = "${var.titan_security_group}"
    security_group_id        = "sg-74571111"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
A rule for port 111 to be opened.

### Actual Behavior

This rule was created:

All traffic | All | All | sg-626aa91f (legacy_titan_app)

I manually deleted it and another terraform run recreated it.  The run outputs:

```
module.legacy_mongo.aws_security_group_rule.v5-support-portmapper: Creating...
  from_port:                "" => "111"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-74571111"
  self:                     "" => "false"
  source_security_group_id: "" => "sg-626aa91f"
  to_port:                  "" => "111"
  type:                     "" => "ingress"
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by catsby** [comment]
Hey @apenney – the `all` for `protocol` is equivalent to using `-1`, in which case you must specify `0` for both `to_port` and `from_port`. This explains why the rule you're getting is an allow all->all . I've updated our documentation to reflect this in https://github.com/hashicorp/terraform/commit/92eb13e9ef52a496d8fcc7ca82d145c65726d4db 

Sorry for the trouble!
