### ISSUE TITLE
terraform fmt repeatedly indents multiline strings

### ISSUE THREAD

**Issue by erikh** [hashicorp/terraform#9859]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

0.7.8

### Affected Resource(s)

none

### Terraform Configuration Files
```hcl
resource "null_resource" "some_command" {
  provisioner "local-exec" {
    command = "echo '
some newlines
and additonal output'"
  }
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform fmt` of the above should further indent the inside of the "echo" statement each `terraform fmt` run.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

I looked but found none.

**Comment by mitchellh** [comment]
Good catch. I have a fix in the HCL PR referenced in this issue.
