### ISSUE TITLE
aws_iam_role/aws_iam_user: Updating role policy does not work after adding new user

### ISSUE THREAD

**Issue by michaelpisula** [hashicorp/terraform#9862]
Hi there,
Having a problem with IAM roles and users:

### Terraform Version
0.7.8

### Affected Resource(s)
- aws_iam_role
- aws_iam_user

### Expected Behavior
I have a role with a policy that allows all users to assume a role. When adding a new user, this user is also added to the role policy. Upon creation, the user is created and the policy role is updated. I would expect this to work ;-)

### Actual Behavior
When I run `terraform apply` it does not work the first time. I get the following error message
Error applying plan:

1 error(s) occurred:

* aws_iam_role.aws_working_role: Error Updating IAM Role (aws_working_role) Assume Role Policy: MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::xxx:user/User"
	status code: 400

Making a trivial change to the policy (e.g. reordering the users) and running again works. Most likely this is some kind of race condition. Terraform reports user creation to be complete before starting to modify the role. I am only seeing this now with more than one user in the policy.

Not terribly important, as the workaround is fairly simple, still looks like a bug.

Cheers,
Michael

**Comment by Ninir** [comment]
@michaelpisula Could you provide a configuration so that we can reproduce it please? thanks!
