### ISSUE TITLE
aws_iam_user: Destroying users with force_destroy does not work

### ISSUE THREAD

**Issue by michaelpisula** [hashicorp/terraform#9863]
Hi there,

### Terraform Version
0.7.8

### Affected Resource(s)
aws_iam_user

### Expected Behavior
I have several users defined with `force_destroy` set to true. When removing one of them from the configuration `terraform apply` runs fine, no errors, reports user as destroyed. Looking into the IAM console I would expect the user to be gone.

### Actual Behavior
User is still present in IAM console. Access Keys were however removed. Setting `force_destroy` to false will lead to successful removal (if that user has no access keys or login profiles of course).

Looks like a small bug to me. Removing the user in the Console or removing access keys before are both valid workarounds for me, so this is not very pressing.

Cheers,
Michael

**Comment by minamijoyo** [comment]
@michaelpisula Hi, I've fixed this issue in #9900.

**Comment by michaelpisula** [comment]
Awesome, thanks :-)
