### ISSUE TITLE
Enhancement: Allow more than one IP Configuration on azurerm_network_interface

### ISSUE THREAD

**Issue by carinadigital** [hashicorp/terraform#9874]
Allow more one or more IP configurations to be attached to an azurerm_network_interface.

### Terraform Version
0.7.8

### Affected Resource(s)
azurerm_network_interface

### Important Factoids
Some challenges that I've seen.
1. TODO notice in code for the ip configuration loop https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_network_interface_card.go#L266
2. Schema for top level private_ip_address can only store one value.
https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_network_interface_card.go#L54

**Comment by pmcatominey** [comment]
Hey @carinadigital 

I've tried this locally and it appears that this feature is still in [preview](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-powershell). So supporting multiple `ip_configuration` blocks will depend on that feature becoming full available.

I will have a PR open soon which paves the way for this however and also tackles a few other bugs with the nic resource.

Cheers,
Peter
