### ISSUE TITLE
Apply [diff mismatch/crash] when code is applied as a module on [0.7.7/0.7.8]

### ISSUE THREAD

**Issue by vfabrizi** [hashicorp/terraform#9879]
### Terraform Version
The problem happen on 0.7.7 and 0.7.8, I've never tried this stack with previous versions.

### Affected Resource(s)
It's probably not related to a specific resource as it only show up when the code is applied as a module.

### Terraform Configuration Files
https://github.com/vfabrizi/terraformissue

### Debug Output
https://github.com/vfabrizi/terraformissue
7.7debug.log 7.8debug.log

### Panic Output
It does panic on 0.7.8. On 0.7.8 it does produce a diff mismatch error on a elb or asg resource.
https://github.com/vfabrizi/terraformissue
7.7debug.log 7.8debug.log

### Expected Behavior
The code should apply as expected when applied as a root project, and when applied as a module through a (mostly) empty root project.

### Actual Behavior
On the first run it does crash, on a second run it finish applying succesfully.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply` from the root project. If apply is run with the module as root (that is from the module directory) it does apply on the first run.

### Important Factoids
There's a number of count used as conditional logic. I pruned them down in order to pinpoint what could be the root cause, but it always happen to be related to the module/non-module apply.

**Comment by mitchellh** [comment]
This is fixed in 0.7.9 which we released this morning. Thanks!
