### ISSUE TITLE
Feature request - Please add automated bidding to "aws_spot_fleet_request" resource

### ISSUE THREAD

**Issue by bljordan** [hashicorp/terraform#9890]
### Terraform Version

0.7.9

### Affected Resource(s)

- aws_spot_fleet_request

### Feature Request

Currently "spot_price" is a required field.  Amazon has added the radio button for automated bidding up to the on-demand price.  It'd be great if we could manage these kinds of spot fleets in Terraform.

**Comment by stack72** [comment]
Hi @bljordan 

Apologies for leaving this for so long. Currently, the AWS SDK doesn't support this:

```
	// The bid price per unit hour.
	//
	// SpotPrice is a required field
	SpotPrice *string `locationName:"spotPrice" type:"string" required:"true"`
```

I can't find any support for it in the [AWS Cli](http://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-fleet.html) either

I am not sure what we can do here - is this a specific feature that your AWS account has access to before other users?

Paul

**Comment by bljordan** [comment]
Hi Paul,

Since writing this feature request, I've been using spot fleets in the AWS console and in terraform. I believe the option in the AWS console for "automated bidding" may be a default behavior for spot fleets.

The difference is that the AWS console looks up the on-demand price of the instance type (in the region) and sets that as the SpotPrice by default.  It'd be nice if terraform could look this up and either fill in the SpotPrice field or make the field optional.  I understand you may not want to diverge from what the SDK provides... maybe this functionality could use data from a terraform provider to get the latest on-demand prices for the instance types. 

From the AWS console:
"Use automated bidding (recommended)
Provision Spot instances at the current Spot price capped at the On-Demand price"
vs
"Set your max price (per instance/hour)" - terraform matches this with the SpotPrice field

Let me know if that makes sense or needs further explanation.  If anyone knows otherwise on how these work, please chime in.

Thanks,
Ben

**Comment by catsby** [comment]
This is a nice feature we'd like to add, but unfortunately the AWS API doesn't seem to expose this kind of capability to us.

**Comment by RCM7** [comment]
Hey there, seems to be they eventually implemented this.

> Type (request), type (response)
The type of request. Indicates whether the fleet will only request the target capacity or also attempt to maintain it. When you request a certain target capacity, the fleet will only place the required bids. It will not attempt to replenish Spot instances if capacity is diminished, nor will it submit bids in alternative Spot pools if capacity is not available. When you want to maintain a certain target capacity, fleet will place the required bids to meet this target capacity. It will also automatically replenish any interrupted instances. Default: maintain.
Type: String
Valid Values: request | maintain
Required: No

In my use case it would be really handy to set it to `request` !

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html
