### ISSUE TITLE
Elasticache Replication Group ID Error 

### ISSUE THREAD

**Issue by AnudeepReddyJ21** [hashicorp/terraform#9895]
#Hi,

(1) I have an Elasticache replication group with the name 'xx-yy-66-zz'. I have imported it using the command 'terraform import aws_elasticache_replication_group.xxyy66zz xx-yy-66-zz

I created a configuration file (pasted below) to match the state file.

resource "aws_elasticache_replication_group" "xxyy66zz" {
  replication_group_id          = "xx-yy-66-zz"
  replication_group_description = "xxxx"
  node_type                     = "cache.r3.xlarge"
  number_cache_clusters         = 2
  port                          = 6379
  parameter_group_name          = "xxxx"
  automatic_failover_enabled    = true
  
}

When I run 'terraform plan', I receive an error saying "replication_group_id must contain from 1 to 16 alphanumeric characters or hyphens"

(2)I have another replication group with the name 'xxx-yyy2'. I have imported it and created a similar configuration file (pasted below)

resource "aws_elasticache_replication_group" "xxxyyy2" {
  replication_group_id          = "xxx-yyy2"
  replication_group_description = "xxxx"
  node_type                     = "cache.r3.xlarge"
  number_cache_clusters         = 2
  port                          = 6379
  parameter_group_name          = "xxxx"
  automatic_failover_enabled    = true

}

Terraform plan on this group doesn't result in any errors.

May I know why this is happening?

Thanks,
Anudeep

**Comment by stack72** [comment]
Hi @AnudeepReddyJ21 

Apologies for the issue here - is this the exact replication_group_id? I have just added this as an addition to the validation tests as follows:

```
{
			Value:    "xx-yy-66-zz",
			ErrCount: 0,
		},
```

The test passes as expected:

```
% make testacc TEST=./builtin/providers/aws TESTARGS='-run=TestResourceAWSElastiCacheReplicationGroupIdValidation'
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2016/11/07 10:49:55 Generated command/internal_plugin_list.go
TF_ACC=1 go test ./builtin/providers/aws -v -run=TestResourceAWSElastiCacheReplicationGroupIdValidation -timeout 120m
=== RUN   TestResourceAWSElastiCacheReplicationGroupIdValidation
--- PASS: TestResourceAWSElastiCacheReplicationGroupIdValidation (0.00s)
PASS
ok  	github.com/hashicorp/terraform/builtin/providers/aws	0.020s
```

Paul

**Comment by AnudeepReddyJ21** [comment]
Hi Paul,

To be more specific, its like this xxxxxxx-zzzz-6-yy

The issue is some of the replication groups result in same error while others do not. They are all alphanumeric with hyphens in between, which clearly meets the requirements. 

Thanks,
Anudeep

**Comment by stack72** [comment]
Hi @AnudeepReddyJ21 

I think the issue is that the length of the ID is > 16 - that is a bug in Terraform. Not that it has a hyphen

What is the actual length of the ID?

P.

**Comment by AnudeepReddyJ21** [comment]
True. The length of the ID is 20. Some ID's that I have length exceeding 20 too. Thanks for the info. I hope the bug gets fixed soon. I am Terraform v0.7.7 , which I think is the latest version.

Thanks,
Anudeep

**Comment by stack72** [comment]
Hi @AnudeepReddyJ21 

Yes, will fix this in a PR now :)

P.

**Comment by AnudeepReddyJ21** [comment]
Great! Thanks a lot!
