### ISSUE TITLE
"Experimental feature failure" encountered during "terraform destroy"

### ISSUE THREAD

**Issue by yamaszone** [hashicorp/terraform#9896]
### Terraform Version
v0.7.9

### Affected Resource(s)
Please list the resources as a list, for example:
The issue appears to be related to multiple resources. Not sure if the issue is with Terraform's core.

### Terraform Configuration Files
```hcl
https://github.com/yamaszone/stack.git
```

### Debug Output
https://gist.github.com/yamaszone/f358bf7f0e0d183a75b1885198a8f534

### Panic Output
N/A

### Expected Behavior
Fix the potential issue with the experimental feature so that the aforementioned error is not displayed and confuse users.

### Actual Behavior
What actually happened?
Saw https://gist.github.com/yamaszone/f358bf7f0e0d183a75b1885198a8f534

### Steps to Reproduce
Didn't see the error with v0.7.8 but started seeing the error with v0.7.9.
1. Checkout branch `develop` of https://github.com/yamaszone/stack.git
2. Configure `~/.aws/credentials` and `hashicorp/terraform:light` similar to [this](https://github.com/yamaszone/stack/blob/develop/tf)
3. `terraform apply` and provide inputs as prompted
4. `terraform destroy` and observe the aforementioned issue

**Comment by mitchellh** [comment]
Dup of #9905. Thanks for the repro!
