### ISSUE TITLE
rendering templates broke between 0.7.5 and 0.7.9

### ISSUE THREAD

**Issue by buzztroll** [hashicorp/terraform#9897]
Here is a sample config file where I see the difference:

```
data "template_file" "host" {
  count = 3
  template = "${host}:2181"
  vars {
    host = "SOMENAME${count.index}"
  }
}

data "template_file" "combined" {
  template = "${zk_servers}"
  vars {
    zk_servers = "${join(",", data.template_file.host.*.rendered)}"
  }
}

output "out" {
  value = "${data.template_file.combined.rendered}"
}
```

Here is the output from 0.7.5 (which is what is expected):

```
data.template_file.host.2: Refreshing state...
data.template_file.host.1: Refreshing state...
data.template_file.host.0: Refreshing state...
data.template_file.combined: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = SOMENAME0:2181,SOMENAME1:2181,SOMENAME2:2181
```

And here is the output from 0.7.9

```
data.template_file.host.1: Refreshing state...
data.template_file.host.0: Refreshing state...
data.template_file.host.2: Refreshing state...
data.template_file.combined: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out =
```

**Comment by apparentlymart** [comment]
@buzztroll I can't explain why it isn't giving you a better error message, but the template interpolations in the `template` attribute need to be escaped so that they are handled by the template provider rather than core Terraform. This is done by doubling the dollar signs there, like `"$${host}:2181"`.

Due to some quirky coincidences is has been sometimes working without the double escaping, but that will stop working in the forthcoming 0.8 release, so probably worth correcting it now.

**Comment by buzztroll** [comment]
With the $$ I get the same results with 0.7.8 and 0.7.9:
```
$ cat main.tf
data "template_file" "host" {
  count = 3
  template = "$${host}:2181"
  vars {
    host = "SOMENAME${count.index}"
  }
}

data "template_file" "combined" {
  template = "${zk_servers}"
  vars {
    zk_servers = "${join(",", data.template_file.host.*.rendered)}"
  }
}

output "out" {
  value = "${data.template_file.combined.rendered}"
}
$ ~/Downloads/terraform-0.7.9 apply
data.template_file.host.2: Refreshing state...
data.template_file.host.1: Refreshing state...
data.template_file.host.0: Refreshing state...
data.template_file.combined: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out =
$ rm terraform.tfstate
$ ~/Downloads/terraform-0.7.7 apply
data.template_file.host.0: Refreshing state...
data.template_file.host.1: Refreshing state...
data.template_file.host.2: Refreshing state...
data.template_file.combined: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = SOMENAME0:2181,SOMENAME1:2181,SOMENAME2:2181
```

**Comment by antimack** [comment]
+1, for me template_file resource is broken both on 0.7.8 and 0.7.9 as well, I'm using template_file to create a policy for iam_roles for AWS Beanstalk environments both on staging and production, with 0.7.8 and 0.7.9 "plan" command shows "computed" in policy and I had an error:
* aws_iam_role_policy.iam_role_policy: Error putting IAM role policy xxxxxxxxxxxxxxxxx: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutRolePolicyInput.PolicyDocument.

Also tried to switch from resource to "data" type but in that case both for 0.7.8. and 0.7.9 terraform just stuck on creating iam_role.
After reverting to 0.7.4 everything works like it should.

**Comment by mitchellh** [comment]
I thought we held the simple variable change until 0.8, and 0.7.5 is a real long time ago... in either case the following works:

```
data "template_file" "host" {
  count = 3
  template = "$${host}:2181"
  vars {
    host = "SOMENAME${count.index}"
  }
}

data "template_file" "combined" {
  template = "$${zk_servers}"
  vars {
    zk_servers = "${join(",", data.template_file.host.*.rendered)}"
  }
}

output "out" {
  value = "${data.template_file.combined.rendered}"
}
```

I've updated the docs to be very descriptive and clear about this (referenced here).
