### ISSUE TITLE
Creation dependencies

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#99]
Sometimes, there's a dependency that happens during creation.

Here's an example:

```
resource "heroku_app" "foobar" {
    name = "terraform-test-app"

    config_vars {
        foo = "bar"
    }
}

resource "heroku_addon" "papertrail" {
    app = "${heroku_app.foobar.name}"
    plan = "papertrail:choklad"
}

output "url" {
    value = "${heroku_addon.foobar.config_vars.0}=${heroku_app.foobar.config_vars.0.PAPERTRAIL_API_TOKEN}"
}
```

The `papertrail` addon needs to be created after the app due to the `app` attribute. But, the output (which looks at the `app`) needs to see a new app state *after* the addon has been created.

In a perfect world, the `heroku_app` is refreshed after the addon is created.

**Comment by phinze** [comment]
Going to close this for inactivity. This scenario could probably be addressed by splitting out `config_vars` somehow into additional top-level resources. We'd welcome PRs in this direction, but going to close this for now.

**Comment by willdurand** [comment]
Heya! Sorry to bother you but this is still the case in Terraform v0.6.16. The issue is that it requires 2 successive `apply` to get the infrastructure up (first `apply` fails).

**Comment by willdurand** [comment]
> Going to close this for inactivity. This scenario could probably be addressed by splitting out config_vars somehow into additional top-level resources. We'd welcome PRs in this direction, but going to close this for now.

@phinze I have some spare time to "fix" this behavior if you think it is worth doing it. Yet, I don't understand this sentence: "This scenario could probably be addressed by splitting out config_vars somehow into additional top-level resources".
