### ISSUE TITLE
"Experimental feature failure" on apply [0.7.9], followup on #9879

### ISSUE THREAD

**Issue by vfabrizi** [hashicorp/terraform#9907]
### Terraform Version
0.7.9

### Affected Resource(s)
Apparently IAM policies
* Unknown 'ValidateResource' shadow value: &errors.errorString{s:"shadow closed"}
* Diff "module.stack_ext_ssl.aws_iam_role_policy.policy" had unequal states (real, then shadow):

### Terraform Configuration Files
https://github.com/vfabrizi/terraformissue

### Debug Output
Debug level output can be found in 7.9debug.log, actual cli output on output.log
https://github.com/vfabrizi/terraformissue

### Panic Output
7.9debug.log

### Expected Behavior
No warning and successful resource creation.

### Actual Behavior
Well handled internal state mismatch, and successful resource creation. Resources appears to have been created in the right way, and a second run of terraform apply behave as expected and with no warning. As in #9879, if the apply is made at module level, then everything works fine. The issue only appears when the tf scripts are applied as a module.

### Steps to Reproduce
1. `terraform apply`

### References
This is a follow up on #9879. The same exact tf files now gets processed successfully.

**Comment by jmvbxx** [comment]
We have just experienced the same problem however with 25 errors all of which are `unknown variable accessed:`

**Comment by mitchellh** [comment]
This is now fixed!

**Comment by jmvbxx** [comment]
@mitchellh Great news, thanks! I'll wait until the change gets pushed up to `brew`.

**Comment by mitchellh** [comment]
It'll be in 0.7.10, for reference.

**Comment by mitchellh** [comment]
Note that this error doesn't affect your operation: TF still works completely fine, just an experimental feature is failing (which doesn't matter), so you can keep using TF. Its just slightly annoying that thte error message will keep showingup. :)

**Comment by jmvbxx** [comment]
Thank you, @mitchellh
