### ISSUE TITLE
formatlist() should be able to take empty list but cant

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#9908]
terraform 0.7.5 

`formatlist(string, list)` should be able to take an empty list. The functionality in this case should be obvious, it outputs an empty list.

Instead, it prints this error:

```
template = "${join(",", formatlist("example%s", list()))}"

* formatlist: no lists in arguments to formatlist in:

${join(",", formatlist("example%s", list()))}
```

This really shouldn't be an error, there is no reason why it shouldn't be able to cope with this just fine. I've worked up this example for you, but the real usecase is using `aws_instance.example.*.private_ip`, as the list parameter to a `formatlist` when the count of the example aws_instance is 0. Terraform should cope with this just fine, and doesnt >.<

**Comment by stack72** [comment]
Hi @gtmtech 

Thanks for the request here - this was added in https://github.com/hashicorp/terraform/issues/9795 which was part of the 0.7.8 release

Thanks

Paul
