### ISSUE TITLE
Unable to find aws_volume_attachment id

### ISSUE THREAD

**Issue by tdeheurles** [hashicorp/terraform#9910]
Hi.

I'm trying to update a `terraform state` that a diverged from the reality.
I have updated my `terraform code` to match the new changes and have successfully imported most new resources. I then run `terraform plan` to diff reality/state/code.

But I'm failing on the `aws_volume_attachment` as I don't know how to find the id by using the `aws cli` or `aws console`. 

My current feeling is this `aws_volume_attachment.id` is a terraform one but maybe I'm wrong.

**Comment by tdeheurles** [comment]
I did a manual update of the aws_volume_attachment in the terraform state. After this one match the reality, the `terraform plan` was fine and didn't try to update the resource.

This seems to confirm that some ids are present at the terraform level and not cloud provider one.

**Comment by geoffreywiseman** [comment]
Should this really be closed? This seems like a problem to me. I'm happy that @tdeheurles was able to solve the problem he/she was experiencing, but seems like it'll continue to be a problem for people adopting terraform when they already have EBS volumes attached to instances if there's no way to import this.

**Comment by geoffreywiseman** [comment]
Ah, sounds like this is (mostly) resolved by #11060. Feels wrong to apply to create an attachment that already exists, but ... at least it doesn't fail, I guess.
