### ISSUE TITLE
make plugin-dev should be removed from the Makefile

### ISSUE THREAD

**Issue by ilijaljubicic** [hashicorp/terraform#9912]
### Terraform Version
fails when building modules for  0.7.9 at least, did not try with older versions

##############################################################################
terraform make plugin-dev .. fails if GOBIN is set and not same as $GOPATH/bin

should 'make plugin-dev' look like this?

plugin-dev: generate
	go install github.com/hashicorp/terraform/builtin/bins/$(PLUGIN)
	mv $(GOBIN)/$(PLUGIN) $(GOBIN)/terraform-$(PLUGIN)

About GOBIN:
The bin directory holds compiled commands. Each command is named for its source directory, but only the final element, not the entire path. That is, the command with source in DIR/src/foo/quux is installed into DIR/bin/quux, not DIR/bin/foo/quux. The "foo/" prefix is stripped so that you can add DIR/bin to your PATH to get at the installed commands. If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin. GOBIN must be an absolute path

**Comment by abitrolly** [comment]
Is it still actual?

**Comment by mildwonkey** [comment]
Now that the providers are in their own repositories, `make plugin-dev` should just be removed from Terraform's makefile. I'll update the description of this issue accordingly, thanks!

**Comment by abitrolly** [comment]
https://github.com/hashicorp/terraform/blob/e68fe72cdf276c04959b064d5fccb075fcecdb36/Makefile#L25-L26

Could this shorthand still be useful for local development or debugging? I am not following Terraform development lately and don't know what is the best practices for testing Terraform plugins.

**Comment by teamterraform** [comment]
Since the original discussion here, the `terraform` provider moved back into this repository, and so `make plugin-dev PLUGIN=provider=terraform` is now a valid thing to do again, though as before no other providers can be built this way because they are in separate repositories. The provisioners in this codebase can still be built via this target too. Therefore we're going to close this out. Thanks!
