### ISSUE TITLE
No access to route table grated by vpc

### ISSUE THREAD

**Issue by eredi93** [hashicorp/terraform#9914]
The aws_vpc module creates a main_route_table that i have no control of. Could we have a nested object? or delete it straight away after aws creates it?

**Comment by stack72** [comment]
Hi @eredi93 

Do you mean the Default route table? https://www.terraform.io/docs/providers/aws/r/default_route_table.html

P.

**Comment by eredi93** [comment]
https://www.terraform.io/docs/providers/aws/r/vpc.html
```main_route_table_id - The ID of the main route table associated with this VPC. Note that you can change a VPC's main route table by using an aws_main_route_table_association```

Once you create a vpc in automatically it creates a route_table

**Comment by stack72** [comment]
got it - thanks for the clarification
