### ISSUE TITLE
crash during apply -

### ISSUE THREAD

**Issue by gosuri** [hashicorp/terraform#992]
Terraform (`v0.3.7-dev e9778c85a5291b6db767277703a4f08bbee20765`) crashed during apply due to `panic: interface conversion: interface is *ec2.EC2, not *aws.AWSClient` at `builtin/providers/aws/resource_aws_security_group.go:297` 

crash log: https://gist.github.com/gosuri/9ee1f32a1a8cffb17e6d

**Comment by mitchellh** [comment]
Fixed, I tihnk acceptance tests would've caught this but we haven't run them recently and this change was today.

**Comment by gosuri** [comment]
Sweet. Thanks so much for the quick turnaround!
