### ISSUE TITLE
google_compute_image timeouts booting 50 GB image

### ISSUE THREAD

**Issue by zachgersh** [hashicorp/terraform#9923]
I actually verified that moving the timeout up to around 10 minutes fixes the issue. Unfortunately, as disks grow larger you are going to need more time for them to boot.  I don't know if moving the timeout is the correct solution.

### Terraform Version
v0.7.9

### Affected Resource(s)
google_compute_image

### Expected Behavior
I can create an image from a source URI that is 50 gigs or over in size without terraform timing out.

### Actual Behavior
Terraform timed out at the 4 minute mark due to the usage of
https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_image.go#L135

Which has the low low timeout of only 4 minutes:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/compute_operation.go#L95

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. make an image that is 50 GBs or over in size
2. `terraform apply`

**Comment by cblecker** [comment]
Does it take a similar amount of time to provision the server outside of Terraform? If so, then yes, it would just be boosting the timeout. If it is significantly different provisioning this manually, than provisioning it with Terraform, then there may be something worth digging into trace logs for.

**Comment by zachgersh** [comment]
@cblecker - I can double check that and see what the timings look like. I don't know if raising the timeout is the right approach though it would be easy for me to bump it forward with a PR.

I wanted to suggest one of two options (this is if the server provisions just as slowly in my other test):

1. Image resource gets a configurable timeout that you can specify (this allows anyone to boot any disk size).
2. All resources get some sort of configurable timeout (way larger in scope and probably not needed but wanted to throw it out there).

**Comment by cblecker** [comment]
Yes, if it takes a similar amount of time on both (suggesting that GCP actually needs that length of time to process and create the image), then a configurable timeout at either level (image resource specific, or all resources) would be better than bumping the global provider-wide timeout IMHO.

**Comment by zachgersh** [comment]
@cblecker created the same 50 GB image on the images section of GCP console and it took around seven minutes (so this doesn't seem to be a terraform delay). We're going to proceed with the individual timeout PR for just GCP images.

cc @rmasand

**Comment by paddyforan** [comment]
This should be fixed with #10081. :)
