### ISSUE TITLE
Experimental feature failure

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#9927]
### Terraform Version
Terraform v0.7.9

### Terraform Configuration Files
https://dl.dropboxusercontent.com/u/29966/terraform/tf-2016110700.zip

### Debug Output
https://gist.github.com/FlorinAndrei/fcf143c540480e8ea5991b4cd49e4eee

### Steps to Reproduce
`terraform apply plan`

**Comment by mitchellh** [comment]
Thanks! Fixed in master, will be in 0.7.10
