### ISSUE TITLE
AWS Redshift Enhanced VPC Routing argument

### ISSUE THREAD

**Issue by madnice** [hashicorp/terraform#9928]
### Terraform Version
0.7.9

### Affected Resource(s)
- aws_redshift_cluster

### References
Amazon Official Redshift Docs: [https://docs.aws.amazon.com/redshift/latest/mgmt/enhanced-vpc-routing.html](url)

Amazon now supports a boolean to enable VPC Enhanced Routing in Redshift. It doesn't appear to be a toggle after deployment of a Redshift resource. If it's already in Terraform, then this is just a Documentation update issue.

**Comment by paddyforan** [comment]
@optimisticanshul just landed a patch to add this. It should be included in our next release. Thanks for requesting the enhancement! Feel free to open an issue if we're missing features anywhere else.
