### ISSUE TITLE
feature request: Amazon CloudWatch Logs PutDestination/PutDestinationPolicy

### ISSUE THREAD

**Issue by AndHei** [hashicorp/terraform#9930]
for AWS cross account delivery of Amazon CloudWatch Logs "aws_cloudwatch_log_subscription_filter" it would be much appreciated if Amazon CloudWatch Logs PutDestination/PutDestinationPolicy would be added to terraform.

Amazon CloudWatch Logs PutDestination
http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDestination.html

Amazon CloudWatch Logs PutDestinationPolicy
http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDestinationPolicy.html

**Comment by grubernaut** [comment]
Fixed in #11940, thanks!
