### ISSUE TITLE
Terraform always shows changes to policy when using CanonicalUser

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#9933]
On Terraform 0.7.9 the following resources apply successfully, but Terraform always shows changes in subsequent plans:

```
resource "aws_s3_bucket" "bucket" {
  bucket = "REDACTED"

  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_policy" "bucket" {
  bucket = "${aws_s3_bucket.bucket.bucket}"
  policy = "${data.aws_iam_policy_document.bucket.json}"
}

data "aws_iam_policy_document" "bucket" {
  # Allow encoding.com to access files within the bucket.
  statement {
    actions = [
      "s3:GetObject",
      "s3:PutObject",
    ]
    resources = [
      "${aws_s3_bucket.bucket.arn}/*",
    ]

    principals {
      type        = "CanonicalUser"
      identifiers = ["1a85ad8fea02b4d948b962948f69972a72da6bed800a7e9ca7d0b43dc61d5869"]
    }
  }
}
```

(Note that the `CanonicalUser` is not sensitive, it comes from the [Encoding.com documentation](http://help.encoding.com/knowledge-base/article/using-amazon-s3-with-the-watch-folder/)

Subsequent `terraform plan`s show the following changes to be applied:

```
~ aws_s3_bucket_policy.bucket
    policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::456240961796:root\"},\"Action\":[\"s3:PutObject\",\"s3:GetObject\"],\"Resource\":\"arn:aws:s3:::REDACTED/*\"}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:PutObject\",\n        \"s3:GetObject\"\n      ],\n      \"Resource\": \"arn:aws:s3:::REDACTED/*\",\n      \"Principal\": {\n        \"CanonicalUser\": \"1a85ad8fea02b4d948b962948f69972a72da6bed800a7e9ca7d0b43dc61d5869\"\n      }\n    }\n  ]\n}"
```

It seems that the issue here is that Amazon normalizes the policy by changing `"CanonicalUser": "1a85ad8fea02b4d948b962948f69972a72da6bed800a7e9ca7d0b43dc61d5869"` to `"AWS": "arn:aws:iam::456240961796:root"`.

I clarified this with AWS support, who responded with this:

> Yes, this is expected because of the format "AWS":"account-ARN" which is the default and since Amazon S3 also supports canonical user ID, you can also mention the canonical user ID during policy creation. 
>
> Reference: http://docs.aws.amazon.com/AmazonS3/latest/dev/s3-bucket-user-policy-specifying-principal-intro.html

**Comment by cpoole** [comment]
I switched to using the iam_arn output in my policy statements, seems to have solved the problem. This could be fixed with a simple docs change.

**Comment by eskp** [comment]
How is this a fix?
