### ISSUE TITLE
Experimental feature failure

### ISSUE THREAD

**Issue by levinse** [hashicorp/terraform#9934]
Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

1 error(s) occurred:

* apply operation: Real and shadow states do not match! Real state:

(I can provide the full / sensitive output if needed but this keeps happening)

**Comment by jdblack** [comment]
I got this in 0.7.9 as well:

* apply operation: Real and shadow states do not match! Real state:

data.template_file.logging-host:
  ID = 9a3171e19560fc375ae46c76ff67ccc0307cd61339fc7ad71a32200007d76a1b
  rendered = s-s1
  template = ${env_s}-${shard_s}
  vars.% = 2
  vars.env_s = s
  vars.shard_s = s1
vault_secret.docker_auth:
  ID = path:secret/core/docker/auth
  data.% = 1
  data.value = [SECRET_VALUE_HERE]
  path = /secret/core/docker/auth

.....
Shadow state:

%!s(PANIC=runtime error: invalid memory address or nil pointer dereference)

**Comment by mitchellh** [comment]
Hey @jdblack or @levinse, thanks for reporting an issue! I'm fairly confident that this will be the same as #9905, but can't be 100% sure w/o a full output. Let me know.

**Comment by jdblack** [comment]
I also think its a duplicate.

Unfortunately our output is over 7,000 lines long and contains sensitive
data.

I did include the full shadow output,  which I believe just listed a NPE

We unfortunately have sensitive data in our hashicorp output. I did

**Comment by mitchellh** [comment]
@jdblack I'll have 0.7.10 released tomorrow morning, check with that and you may be good to go. Contains a good number of fixes in this category.

**Comment by sriney-boc** [comment]
I get the same error with 0.7.10

**Comment by mitchellh** [comment]
Unfortunately I cannot diagnose the error without knowing what doesn't match. If that error showed up then the states do not match.

**Comment by sriney-boc** [comment]
It's only showing when I run with a target

plan -target=module....
