### ISSUE TITLE
Terraform v0.7.9: Experimental feature failure!

### ISSUE THREAD

**Issue by cypherhat** [hashicorp/terraform#9938]
### Terraform Version
v0.7.9

### Affected Resource(s)

All details are in this tarball: https://www.dropbox.com/s/8wxijd8c08m3hga/0.7.9.tar?dl=0

There are 3 files - all encrypted with HashiCorp's PGP key:

apply.txt: The output of the apply command.
terraform.tfstate: The state file
terraform.log: The debug log

The terraform project is available here: https://github.com/Immutability-io/consul-terraform

### Behavior
There were no negative outcomes - the infrastructure was deployed successfully.

### Steps to Reproduce

`terraform apply -var-file=mycluster.tfvars`

### Important Factoids
All the keys included in the state and output have been destroyed. 

### References
https://github.com/Immutability-io/consul-terraform

**Comment by mitchellh** [comment]
Thanks! Fixed in master, will be in 0.7.10
