### ISSUE TITLE
AWS: routing table / instance = chicken / egg

### ISSUE THREAD

**Issue by james-masson** [hashicorp/terraform#994]
Consider the situation where a routing table contains a route to an instance.
But the instance is in a subnet where this routing table is applied.

```
resource "aws_route_table" "dmz" {
  vpc_id = "${aws_vpc.default.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.default.id}"
  }
  route {
    cidr_block = "${var.site.vpn_network}"
    instance_id = "${aws_instance.openvpn.id}"
  }
}

resource "aws_instance" "openvpn" {
  ami = "${lookup(var.aws_centos_ami, var.site.region)}"
  instance_type = "t2.small"
  key_name = "${var.aws_key_name}"
  security_groups = ["${aws_security_group.openvpn.id}"]
  subnet_id = "${aws_subnet.dmz.id}"
  associate_public_ip_address = true
  source_dest_check = false
  provisioner "remote-exec" {
      script = "bootstrap_openvpn.sh"
      connection {
        user = "root"
        key_file = "${var.aws_private_key}"
    }
  }
}
```

The current behaviour seems to be that the instance is *provisioned* before the routing table.
Unfortunately this leads to the provisioner failing, as the correct routing is not in place yet.

Ideally, the instance would be created, but not provisioned, until the routing table is in place.

Any ideas for a workaround?

**Comment by mitchellh** [comment]
As a workaround you can put the provisioner inside the routing able. You lose some of the benefits of Terraform there (tainted resources) but it does work. There is another issue I just responded to yesterday that is exactly this. I'm sorry I don't know it at the current time but its around here open somewhere. :)
