### ISSUE TITLE
SSH provisioner - private_ip

### ISSUE THREAD

**Issue by james-masson** [hashicorp/terraform#995]
SSH provisioning works just fine when creating an instance using public_ip

I read in another bug that it's an undocumented feature that if the VM created has no public IP, the SSH provisioner falls back to connecting to localhost.

In order to make SSH provisioning work using private_ip - I have to add a connection block in each instance block, referring to itself, eg.

```
## Puppet master
resource "aws_instance" "puppet-master" {
  ami = "${lookup(var.aws_centos_ami, var.site.region)}"
  instance_type = "t2.small"
  key_name = "${var.aws_key_name}"
  security_groups = ["${var.aws_security_group_id_internal}"]
  subnet_id = "${aws_subnet.mgt.id}"
  tags {
    Name = "puppet-master"
  }
  connection {
    user = "root"
    host = "${aws_instance.puppet-master.private_ip}"
    key_file = "${var.aws_private_key}"
  }
  provisioner "remote-exec" {
      script = "scripts/bootstrap_puppet_master.sh"
  }
}
```

This feels a bit redundant - specifically...
```
host = "${aws_instance.puppet-master.private_ip}"
```

I've not found a better way of doing it, ideally some variable inheritance or a global setting would make this better? eg.
```
ssh_provisioner {
    host = private_ip
}
```

or 

```
<host definition>
<connection>
host = "${private_ip}"

```

**Comment by prepor** [comment]
+1
