### ISSUE TITLE
Lists based on splat have inconsistent ordering (regression)

### ISSUE THREAD

**Issue by Alars-ALIT** [hashicorp/terraform#9951]
### Terraform Version
0.7.8 and 0.7.9 (0.7.6 is ok, 0.7.7 unknown)

### Affected Resource(s)
Core

### Terraform Configuration Files
Repro case:
-------------------
variable "over_ten_list"     { default = ["k","j","i","h","g","f","e","d","c","b","a"] }
variable "exactly_ten_list"  { default = ["j","i","h","g","f","e","d","c","b","a"] }

data "template_file" "exactly" {
  count    = 10
  template = "${var.exactly_ten_list[count.index]}" 
}

data "template_file" "over_ten" {
  count    = 11
  template = "${var.over_ten_list[count.index]}" 
}

# Order kept
output "exactly_ten"  { value = ["${data.template_file.exactly.*.rendered}"] }
# Unordered
output "over_ten"     { value = ["${data.template_file.over_ten.*.rendered}"] }
------------------------
### Debug Output
exactly_ten = [
    j,
    i,
    h,
    g,
    f,
    e,
    d,
    c,
    b,
    a
]
over_ten = [
    k,
    j,
    **a,**
    i,
    h,
    g,
    f,
    e,
    d,
    c,
    b
]

### Expected Behavior
List order should be consistent and independent on nr of items in list

### Actual Behavior
When list contains more then 10 items list becomes unordered

**Comment by mitchellh** [comment]
This was just fixed on master, will be fixed in 0.7.10
