### ISSUE TITLE
Experimental feature failure: howto disable.

### ISSUE THREAD

**Issue by sirhopcount** [hashicorp/terraform#9953]
Hi,

Is there a way to disable the the "Experimental feature failure" output? I cannot find any reference in the documentation and nobody seems to be able to tell me on gitter.

I get it is important but most of the errors we encounter already have a issue assigned to them and the output is interfering with the work flow because the output gets added to the end of the run you cannot quickly view the result of a run without scrolling back.

Regards,

Adrian.

**Comment by mitchellh** [comment]
You can set `-Xshadow=false` and this will disable it. We're going to push out releases quickly to address fixed issues, with 0.7.10 coming tomorrow.
