### ISSUE TITLE
Randomly occurring error: "Error launching instance, possible mismatch of Security Group IDs and Names"

### ISSUE THREAD

**Issue by jmvbxx** [hashicorp/terraform#9954]
Morning, all;

I've been working on a stack since yesterday and an occasionally running into the above error. If I run `terraform apply` again it works properly.

### Terraform Version
Terraform v0.7.9

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Terraform Configuration Files
Here's the security group creation
```
resource "aws_security_group" "default" {
  name = "aws_default"
  description = "Default security group"

  # inbound access from anywhere
  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["${var.ip_range}"]
  }

  # outbound internet access
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["${var.ip_range}"]
  }
}
```
Here is the instance creation
```
resource "aws_instance" "app1" {
  connection {
    user = "ubuntu"
  }

  instance_type = "${var.instance_type}"
  tags {
    Name = "app1"
    Group = "apps"
  }

  security_groups = ["aws_default"]
  ami = "${var.amis}"
  key_name = "${var.key_name}"

  provisioner "remote-exec" {
    inline = [
      "sudo apt-get update",
      "sudo apt-get install -y python-minimal"
    ]
    connection {
      type = "ssh"
      user = "ubuntu"
      agent = false
      private_key = "${file("~/.ssh/id_rsa")}"
    }  
  }
}
```

### Debug Output
https://gist.github.com/jmvbxx/34b8794e746cd20dc1dae1529943d834

### Expected Behavior
The instances should have been created and associated with the security group. However, it appears that every now and then there is a delay in the time required to create the group and the instances don't see it when they need to. If `terraform apply` is immediately run a second time it works properly.

### Actual Behavior
The above error from the debug gist.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Nothing special

### References
None

**Comment by mtoigo** [comment]
I've seen the same exact thing. No changes in any of my configuration, but this just randomly started.

**Comment by mtoigo** [comment]
Renaming the security group resolved the issue but there's very likely still an underlying bug here.
