### ISSUE TITLE
vCD: Add more vapp / vm customization options

### ISSUE THREAD

**Issue by keras** [hashicorp/terraform#9956]
My wishlist:
- Allow creating multiple VMs to single vapp & add more VMs to existing vapp
- Allow attaching VM to multiple networks (by creating multiple NICs)
- Allow adding multiple disks to a VM
- Allow expanding a disk of a VM
- Allow customization of a VM's storage profile

**Comment by robcoward** [comment]
Thank you for your wishlist @keras. I've added them to the list of enhancement we hope to shortly be working on.

**Comment by dn1s** [comment]
Allow customization of a VM's storage profile see: #13935

**Comment by jtyr** [comment]
I think this issue should remain open as the issue #13935 allows to customise only the `storage_profile support`. That resolves only one bullet point out of 5 of this issue.

**Comment by bobbydeveaux** [comment]
@jtyr this has not been 'closed' it's just been moved to the new repo. See: https://github.com/terraform-providers/terraform-provider-vcd/issues/9
