### ISSUE TITLE
Azure RM storage account name dependency error message

### ISSUE THREAD

**Issue by lmickh** [hashicorp/terraform#9963]
This may very well be a larger issue with the way error messages are constructed regarding dependencies.  I haven't tested it elsewhere yet.

### Terraform Version
Terraform v0.7.9

### Affected Resource(s)
- azurerm_storage_account
- azurerm_storage_container

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "test" {
  name = "invalid_test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location = "easust2"
  account_type = "Standard_LRS"
}

resource "azurerm_storage_container" "test" {
  name = "invalid_test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  storage_account_name = "${azurerm_storage_account.test.name}"
  container_access_type = "private"
}
```

### Expected Behavior
Azure storage accounts and containers must have a name that consists of only alphanumerics.  Would expect that it would provide an error message saying that the resource has an invalid name.  This would allow the user to troubleshoot the problem correctly.

* azurerm_storage_account.invalid_test: name can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long

### Actual Behavior
When using an invalid name (containing a hyphen or underscore), instead of reporting that the storage account name is invalid Terraform will instead give a message saying the variable cannot be found for the resource.  Only after the depending resource (storage container in the code above) is removed, does the correct message appear.

* Resource 'azurerm_storage_account.invalid_test' does not have attribute 'name' for variable 'azurerm_storage_account.invalid_test.name'

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @lmickh 

I am not sure why you are seeing this behaviour. I have used your config above and get the following:

```
% terraform plan                                                                                                                         1 ↵ ✭
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * azurerm_storage_account.test: name can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long
  * azurerm_storage_container.test: only lowercase alphanumeric characters and hyphens allowed in "name": "invalid_test"
```

```
% terraform apply                                                                                                                            ✭
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * azurerm_storage_account.test: name can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long
  * azurerm_storage_container.test: only lowercase alphanumeric characters and hyphens allowed in "name": "invalid_test"
```

Is this something that you can continually recreate?

Paul

**Comment by lmickh** [comment]
I overlooked that I was calling it from a module originally.  It functions as expected outside of a module, but gives the abbreviated message within it.  Sorry for the red herring.

**Comment by stack72** [comment]
No problemo :) Glad it works as expected
