### ISSUE TITLE
apply operation: Configure had unequal configurations (real, then shadow)

### ISSUE THREAD

**Issue by dmangot** [hashicorp/terraform#9978]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

0.7.9

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

2 error(s) occurred:

* apply operation: Configure had unequal configurations (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{}, Config:map[string]interface {}{}, raw:(*config.RawConfig)(0x425c01740)}

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"region":"us-east-1"}, Config:map[string]interface {}{"region":"us-east-1"}, raw:(*config.RawConfig)(0x4250a7680)}
* apply operation: Configure had unequal configurations (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"region":"us-east-1"}, Config:map[string]interface {}{"region":"us-east-1"}, raw:(*config.RawConfig)(0x425c6cd20)}

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{}, Config:map[string]interface {}{}, raw:(*config.RawConfig)(0x425c01500)}

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

**Comment by mitchellh** [comment]
This is fixed and part of 0.7.10 tomorrow. :) Thanks!
