### ISSUE TITLE
Experimental feature failed

### ISSUE THREAD

**Issue by adamgotterer** [hashicorp/terraform#9981]
While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

The following failures happened while running experimental features.
Please report a Terraform bug so that future Terraform versions that
enable these features can be improved!

You can report an issue at: https://github.com/hashicorp/terraform/issues

3 error(s) occurred:

* apply operation: Real and shadow diffs do not match! Real diff:

module.db:
module.ecs_private:
module.ecs_public:
module.redis:
module.vpc:

Shadow diff:

module.db:
module.ecs_private:
  UPDATE: aws_ecs_service.datadog-agentpublic
    task_definition: "datadog-agent:25" => "datadog-agent"
module.ecs_public:
  UPDATE: aws_ecs_service.datadog-agentpublic
    task_definition: "datadog-agent:25" => "datadog-agent"
module.redis:
module.vpc:

* apply operation: 1:3: unknown variable accessed: var.datadog_agent_task_id in:

${var.datadog_agent_task_id}
* apply operation: 1:3: unknown variable accessed: var.datadog_agent_task_id in:

${var.datadog_agent_task_id}

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

**Comment by mitchellh** [comment]
This is fixed in master and will be part of a 0.7.10 release tomorrow. Thanks for reporting!
