### ISSUE TITLE
whitespace at end of vpc_id causes object to be destroyed and recreated endlessly

### ISSUE THREAD

**Issue by wjimenez5271** [hashicorp/terraform#9982]
consider if you have the following `aws_subnet` resource:

```
resource "aws_subnet" "mysubnet" {
    vpc_id = "vpc-65b14a03"
    cidr_block = "10.0.0.0/24"
    availability_zone = "us-west-2a"
    tags {
        Name = "mysubnet"
    }
}
```

and you accidentally add some whitespace to the `vpc_id` parameter like so

```
resource "aws_subnet" "mysubnet" {
    vpc_id = "vpc-65b14a03 "
    cidr_block = "10.0.0.0/24"
    availability_zone = "us-west-2a"
    tags {
        Name = "mysubnet"
    }
}
```

It seems terraform will create the resource on one iteration, next iteration delete and recreate it, and this will continue endlessly. 

I can imagine that perhaps the AWS API strips the whitespace and so it is able to create the resource, however terraform state knows it as a string with that whitespace, which causes it to be a mismatch next time around. Ideally it would be nice if terraform would present the user with an error when this whitespace is present, otherwise it is difficult to identify the problem based on the behavior.

**Comment by kwilczynski** [comment]
@wjimenez5271 hi there! Sorry that you've had an issue here.

The behaviour you are observing is most likely what you are describing. The two approaches to fix this issue would be either stripping leading and trailing whitespace for certain attributes or validation that the field does not contain any whitespace (which in case of an ID it should not).

**Comment by wjimenez5271** [comment]
Thanks for the response!

If you're asking for my opinion I like the latter option. But either could
work.
