### ISSUE TITLE
can I defined aws_db_parameter to attatch to aws_db_parameter_group

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#9983]
version: 0.7.9

scenario:
I use module for aws_db_parameter_group, but the parameters are not decided yet, is there a way to define standalone db parameter to attach aws_db_parameter_group, like `aws_security_group_rule` and `aws_security_group`

**Comment by stack72** [comment]
Hi @hanks 

Luckily, `parameter_group` doesn't force a new resource. But when you specify it in the config, you may need to include the parameter `apply_immediately = true` to make sure it get's applied

Be aware of `apply_immediately` it could potentially cause a server reboot

Paul

**Comment by hanks** [comment]
I define a module, but I need to create several parameter groups. If I add
a new parameter into the module, it will affect all the resources. How to
avoid this situation.
Paul Stack <notifications@github.com>于2016年11月9日 周三21:30写道：

**Comment by stack72** [comment]
Hi @hanks 

so your module has multiple db_instances and you don't want to add the parameter group to them all?

Does your parameter group need to be reused across modules?

Paul

**Comment by hanks** [comment]
yeah, I want to use it in prod and stg db with the same parameter group,
but trivial modification with them
Paul Stack <notifications@github.com>于2016年11月9日 周三21:38写道：
