### ISSUE TITLE
aws_iam_user name field should permit plus sign

### ISSUE THREAD

**Issue by CpuID** [hashicorp/terraform#9985]
### Terraform Version

v0.7.9

### Affected Resource(s)

- aws_iam_user

### Terraform Configuration Files

```hcl
resource "aws_iam_user" "some_resource_blah_com" {
  name = "something+blah@blah.com"
}
```

### Expected Behavior

Successful plan or apply, plus signs are valid in the name (resources that already exist have them in our AWS account).

### Actual Behavior

```
  * aws_iam_user.some_resource_blah_com: only alphanumeric characters, hyphens, underscores, commas, periods, @ symbols and equals signs allowed in "name": "something+blah@blah.com"
```

### Steps to Reproduce

1. `terraform plan`

OR

1. `terraform apply`

**Comment by kwilczynski** [comment]
@CpuID hi there! Sorry that you have had issues with this resource.

I will link a relevant document:

http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

**Comment by CpuID** [comment]
thx :)
