### ISSUE TITLE
Experimental feature failure - Unknown 'ValidateResource' shadow value: &errors.errorString{s:"shadow closed"}

### ISSUE THREAD

**Issue by icadariu** [hashicorp/terraform#9987]
Hi,

I get this message at the end of terraform apply:

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.
...
8 error(s) occurred:

* apply operation: Unknown 'ValidateResource' shadow value: &errors.errorString{s:"shadow closed"}
* apply operation: Diff "module.compute_front.aws_launch_configuration.as_lc_ecs" had unequal states (real, then shadow):

After this, a lot of private data is dumped on the screen and then this is the end which I think it's important

* apply operation: Real and shadow diffs do not match! Real diff:

module.compute_front:
module.compute_internal:
module.db:
module.efs:
module.elb_front:
module.elb_internal:
module.iam:
module.nat_instance:
module.vpc:
module.vpc_peer_dev:

Shadow diff:

module.compute_front:
  UPDATE: aws_autoscaling_group.as_group
    launch_configuration: "name-public-lc-ecs-20161109081229329924447zgx" => "<computed>"
module.compute_internal:
  UPDATE: aws_autoscaling_group.as_group
    launch_configuration: "name-internal-lc-ecs-201611090812293423260372ex" => "<computed>"
module.db:
module.efs:
module.elb_front:
module.elb_internal:
module.iam:
module.nat_instance:
module.vpc:
module.vpc_peer_dev:

* apply operation: 1:3: unknown variable accessed: var.elb_name in:

${var.elb_name}
* apply operation: 1:3: unknown variable accessed: var.elb_name in:

${var.elb_name}

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

elb module have as output this line which get the elb name -> 
output "elb_name" {
  value = "${aws_elb.elb.name}"
}

And here is my main.tf file where I define both modules (elb and compute)

# Public ELB
module "elb_front" {
  source = "../../modules/https_elb"

  cidr_block = "${module.vpc.cidr_block}" # own vpc
  vpc_id      = "${module.vpc.vpc_id}"
  elb_target = "HTTP:80/"

  # change the following values if it's an internal ELB
  elb_internal = false
  elb_name     = "${var.project_name}-front-lb"
  subnets      = ["${module.vpc.public_subnets}"]
}

# public AS machines
module "compute_front" {
  source = "../../modules/compute"

  # change these values to create a pub/priv elb
  ec2_sg_name   = "as_ec2_front_SG"
  compute_name  = "${var.project_name}-public"   # cluster name
  elb_name      = "${module.elb_front.elb_name}"
  elb_http_only = "${module.elb_front.elb_sg}"

I'm not sure why shadow can't obtain the right elb_name since my actual terraform config seems to work so any help will be great :)

Thanks,
Ionut

**Comment by mitchellh** [comment]
This is fixed, 0.7.10 is being released now.
