### ISSUE TITLE
Azure - MS documentation referenced implies that provision_vm_agent is true by default but this is not true within Terraform itself

### ISSUE THREAD

**Issue by DavidR91** [hashicorp/terraform#9995]
### Terraform Version
0.7.8

### Affected Resource(s):
- azurerm_virtual_machine

### Terraform Configuration Files
N/A

### Expected Behavior
When provisioning an Azure virtual machine, the VM agent should be provisioned by default because:

- This is consistent with Microsoft docs on how the parameter behaves [when not explicitly supplied]
- The agent is required in order to do certain operations (e.g. install extensions) - but importantly it is essential for getting meaningful errors out of provisioning failures (esp. ones shown in the Azure portal)

### Actual Behavior
The VM agent is not provisioned by default. Changing this property after the machine is first made is not permitted.

### Steps to Reproduce
Perform `apply` with any .tf that uses `azurerm_virtual_machine` where os_profile_windows_config\provision_vm_agent has not been explicitly set to a value

(You can verify it lacks the agent by viewing 'Extensions' on the portal. There is a banner at the top stating "The virtual machine agent is not installed")

### Important Factoids
The Terraform docs link to https://msdn.microsoft.com/en-us/library/mt163591.aspx#Anchor_2 wherein os_profile_windows_config\provision_vm_agent (`provisionVMAgent` in the MS docs) is specifically documented as 

> When this property is not specified in the request body, default behavior is to set it to true. This will ensure that VM Agent is installed on the VM so that extensions can be added to the VM later.

Terraform does not match this behaviour (despite referencing this documentation) presumably because an explicit `false` is supplied unless you override the provision_vm_agent property

**Comment by glennmate** [comment]
+1
