### ISSUE TITLE
aws_db_instance: default storage type is 'standard'

### ISSUE THREAD

**Issue by jonatanblue** [hashicorp/terraform#9998]
This issue outlines a discrepancy between Terraform behaviour and the behaviour recommended by AWS. I believe that Terraform follow the AWS recommendation in this case.

### Terraform Version
`v0.7.5`

### Affected Resource(s)
- aws_db_instance

### Expected Behavior
RDS instance should be created with the same default storage as if created on AWS: SSD (`gp2`).

### Actual Behavior
RDS instance is created with a magnetic (`standard`) drive (which is recommended against by AWS).

### Steps to Reproduce
1. Write a resource definition for `aws_db_instance` and to not set `storage_type`.
2. Plan & apply.
3. RDS instance is created with magentic storage.

### References
* The current behaviour is [well documented](https://www.terraform.io/docs/providers/aws/r/db_instance.html#storage_type).
* The current behaviour is undesirable according to the [AWS documentation](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html):

> Amazon RDS also supports Magnetic storage, for backward compatibility. We recommend that you use General Purpose (SSD) or Provisioned IOPS for any new storage needs.

**Comment by stack72** [comment]
Hi @jonatanblue 

Thanks for opening the issue here. In the terraform codebase, we don't actually set a default value for `storage_type`:

```
"storage_type": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
```

That means it's actually AWS that is setting that value for it - the SDK actually has this in it

```

	// Specifies the storage type to be associated with the DB instance.
	//
	//  Valid values: standard | gp2 | io1
	//
	//  If you specify io1, you must also include a value for the Iops parameter.
	//
	//  Default: io1 if the Iops parameter is specified; otherwise standard
	StorageType *string `type:"string"`
```

I hope this helps?

Paul

**Comment by jonatanblue** [comment]
Thanks for clarifying this @stack72.

Is it worth updating to the docs for the `aws_rds_instance` example to include `storage_type`, to highlight the fact that if unspecified it defaults to magentic?

**Comment by stack72** [comment]
Hi @jonatanblue 

That may be a good option - please feel free to drop us a PR with that addition to the docs :) 

Thanks

Paul
